### ISSUE TITLE
H2 test failure

### ISSUE THREAD

**Issue by loriadi** [OpenLiberty/open-liberty#10062]

**Comment by loriadi** [comment]
testUnknownFrameType:junit.framework.AssertionFailedError: 2019-11-15-03:19:59:218 The response did not contain [SUCCESS].  Full output is:
ERROR: Caught exception attempting to call test method testUnknownFrameType on servlet http2.test.driver.war.servlets.GenericFrameTests
java.lang.IllegalArgumentException: Number of bytes requested: -1 exceeds space remaining in the buffers provided: 0
at com.ibm.ws.tcpchannel.internal.TCPWriteRequestContextImpl.checkForErrors(TCPWriteRequestContextImpl.java:397)
at com.ibm.ws.tcpchannel.internal.TCPWriteRequestContextImpl.write(TCPWriteRequestContextImpl.java:67)
at com.ibm.ws.http2.test.connection.H2Connection.sendBytes(H2Connection.java:210)
at com.ibm.ws.http2.test.Http2Client.sendBytes(Http2Client.java:173)
at http2.test.driver.war.servlets.GenericFrameTests.testUnknownFrameType(GenericFrameTests.java:191)
at componenttest.app.FATServlet.doGet(FATServlet.java:67)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1230)
at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:729)
at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:426)
at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1226)
at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:5017)
at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.handleRequest(DynamicVirtualHost.java:314)
at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:1007)
at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:279)
at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1136)
at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:417)
at com.ibm.ws.http.dispatcher

**Comment by loriadi** [comment]
In H2Connection, the sendBytes() method was not synchronized.  This method uses common buffers to send data so it must be synchronized.
