### ISSUE TITLE
Test Failure: com.ibm.ws.request.timing.fat.TimingRequestTiming.testTimingContextInfoConflict

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#10080]
RTC 270041

```
testTimingContextInfoConflict:java.lang.Exception: 2019-11-21-14:46:28:367 Errors/warnings were found in server RequestTimingServer logs:
<br>[11/21/19 14:46:25:810 UTC] 00000037 com.ibm.ws.request.timing.RequestTimingService               E TRAS3300E: The timing configuration associated with PID com.ibm.ws.request.timing.servlet.metatype_28 cannot be read from the configuration.
at componenttest.topology.impl.LibertyServer.checkLogsForErrorsAndWarnings(LibertyServer.java:2528)
at componenttest.topology.impl.LibertyServer.stopServer(LibertyServer.java:2406)
at componenttest.topology.impl.LibertyServer.stopServer(LibertyServer.java:2221)
at componenttest.topology.impl.LibertyServer.stopServer(LibertyServer.java:2196)
at com.ibm.ws.request.timing.fat.TimingRequestTiming.testTimingContextInfoConflict(TimingRequestTiming.java:603)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:193)
at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:314)
at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:167)
```

**Comment by lamkavan** [comment]
Looks like an issue with setting the servers configuration back to server_original.xml  (line 602). This operation is also unnecessary as at the beginning of each test we manually change the server config to the required one. PR to fix this is here https://github.com/OpenLiberty/open-liberty/pull/10198
