### ISSUE TITLE
Socket timeout while destroying stale connection (oracle.jdbc.driver.PhysicalConnection.close)

### ISSUE THREAD

**Issue by dyapasrikanth** [OpenLiberty/open-liberty#10137]
**Describe the bug**
SQLRecoverableException thrown while destroying the stale connection from pool.

After oracle DB failover, connection pool failing to destroy the stale connection and returning new connection.

```
<dataSource id="auditLogDatasource" jndiName="jdbc/audit_log" type="javax.sql.DataSource" validationTimeout="10s">
        <jdbcDriver libraryRef="OracleLib"/>
        <properties.oracle URL="jdbc:oracle:thin://@localhost:1496/test"
                           password="test" user="test" loginTimeout="10" />
        <connectionManager connectionTimeout="10s" maxIdleTime="30m" maxPoolSize="30" minPoolSize="1" reapTime="3m" purgePolicy="FailingConnectionOnly"/>
</dataSource>
```

**Steps to Reproduce**
1. Start the application and make sure it has one free connection in pool (oracle database)
2. Restart the database with failover (Reboot with failover option to another available zone)
3. Try to access the application which uses pooled connection to read/write to database.
4. After around 15-16 min application giving the response as it is failing to destroy the stale connection.

**Expected behavior**
Connection timeout (connectionTimeout) should happen on connection cleanup and should return new connection to application.

**Diagnostic information:**
 - OpenLiberty Version: 19.0.0.12
 - Java Version: 
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
 - Oracle driver: Database product version : Oracle Database 11g Enterprise Edition Release 11.2.0.4.0 - 64bit Production
JDBC driver version  : 12.1.0.2.0
Driver lib: ojdbc7.jar

Stack trace

```
[WARNING ] TRAS0112W: Request AAATEXKsEfJ_AAAAAAAAAAO has been running on thread 00000057 for at least 24007.170ms. The following stack trace shows what this thread is currently running.

 	 at oracle.jdbc.driver.PhysicalConnection.isProxySession(PhysicalConnection.java:4398)
	 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	 at java.lang.reflect.Method.invoke(Method.java:498)
	 at com.ibm.ws.rsadapter.impl.OracleHelper.doConnectionCleanup(OracleHelper.java:354)
	 at com.ibm.ws.rsadapter.impl.WSRdbManagedConnectionImpl.cleanupStates(WSRdbManagedConnectionImpl.java:2847)
	 at com.ibm.ws.rsadapter.impl.WSRdbManagedConnectionImpl.cleanup(WSRdbManagedConnectionImpl.java:2774)
	 at com.ibm.ejs.j2c.MCWrapper.cleanup(MCWrapper.java:1541)
	 at com.ibm.ejs.j2c.FreePool.cleanupAndDestroyMCWrapper(FreePool.java:459)
	 at com.ibm.ejs.j2c.PoolManager.reserve(PoolManager.java:1602)
	 at com.ibm.ejs.j2c.ConnectionManager.allocateMCWrapper(ConnectionManager.java:581)
	 at com.ibm.ejs.j2c.ConnectionManager.allocateConnection(ConnectionManager.java:314)
	 at com.ibm.ws.rsadapter.jdbc.WSJdbcDataSource.getConnection(WSJdbcDataSource.java:138)
	 at com.ibm.ws.rsadapter.jdbc.WSJdbcDataSource.getConnection(WSJdbcDataSource.java:112)
	 at test.dao.AuditDao.store(AuditDao.java:38)
	 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	 at java.lang.reflect.Method.invoke(Method.java:498)
	 at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:88)
	 at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:78)
	 at org.jboss.weld.injection.MethodInvocationStrategy$SimpleMethodInvocationStrategy.invoke(MethodInvocationStrategy.java:129)
	 at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:299)
	 at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:277)
	 at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:255)
	 at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:269)
	 at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:258)
	 at org.jboss.weld.event.EventImpl.fire(EventImpl.java:92)
	 at test.AuthHomeServlet.audit(AuthHomeServlet.java:72)
	 at test.AuthHomeServlet.doPost(AuthHomeServlet.java:37)
	 at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	 at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	 at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1230)
	 at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:729)
	 at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:426)
	 at com.ibm.ws.webcontainer.filter.WebAppFilterChain.invokeTarget(WebAppFilterChain.java:182)
	 at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:93)
	 at test.MkidUserPrincipalFilter.doFilter(MkidUserPrincipalFilter.java:38)
	 at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:201)
	 at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:90)
	 at com.ibm.ws.webcontainer.filter.WebAppFilterManager.doFilter(WebAppFilterManager.java:1001)
	 at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1139)
	 at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1010)
	 at com.ibm.ws.webcontainer.servlet.CacheServletWrapper.handleRequest(CacheServletWrapper.java:75)
	 at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:938)
	 at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:279)
	 at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1136)
	 at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:417)
	 at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:376)
	 at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:548)
	 at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:482)
	 at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:347)
	 at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.ready(HttpInboundLink.java:318)
	 at com.ibm.ws.channel.ssl.internal.SSLConnectionLink.determineNextChannel(SSLConnectionLink.java:1077)
	 at com.ibm.ws.channel.ssl.internal.SSLConnectionLink$MyReadCompletedCallback.complete(SSLConnectionLink.java:656)
	 at com.ibm.ws.channel.ssl.internal.SSLReadServiceContext$SSLReadCompletedCallback.complete(SSLReadServiceContext.java:1803)
	 at com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:503)
	 at com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueManager.java:573)
	 at com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:954)
	 at com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:1043)
	 at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:239)
	 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	 at java.lang.Thread.run(Thread.java:748)

The following table shows the events that have run during this request.

Duration      Operation
24008.514ms + websphere.servlet.service | auth | authHomeServlet
```
After 15-16 min
```
ERROR   ] J2CA0081E: Method destroy failed while trying to execute method destroy on ManagedConnection WSRdbManagedConnectionImpl@4882472a from resource No longer available. Caught exception: com.ibm.ws.rsadapter.exceptions.DataStoreAdapterException: DSRA0080E: An exception was received by the Data Store Adapter. See original exception message: {0}. with SQL State : 08000 SQL Code : 17410
	at com.ibm.ws.rsadapter.impl.WSRdbManagedConnectionImpl.destroy(WSRdbManagedConnectionImpl.java:2597)
	at [internal classes]
	at test.dao.AuditDao.store(AuditDao.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:88)
	at [internal classes]
	at test.AuthHomeServlet.audit(AuthHomeServlet.java:72)
	at test.AuthHomeServlet.doPost(AuthHomeServlet.java:37)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1230)
	at [internal classes]
	at test.MkidUserPrincipalFilter.doFilter(MkidUserPrincipalFilter.java:38)
	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:201)
	at [internal classes]
Caused by: java.sql.SQLRecoverableException: No more data to read from socket DSRA0010E: SQL State = 08000, Error Code = 17,410
	at oracle.jdbc.driver.T4CMAREngine.unmarshalUB1(T4CMAREngine.java:1157)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:350)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:227)
	at oracle.jdbc.driver.T4C7Ocommoncall.doOLOGOFF(T4C7Ocommoncall.java:61)
	at oracle.jdbc.driver.T4CConnection.logoff(T4CConnection.java:574)
	at oracle.jdbc.driver.PhysicalConnection.close(PhysicalConnection.java:4011)
	at com.ibm.ws.rsadapter.impl.WSRdbManagedConnectionImpl.destroy(WSRdbManagedConnectionImpl.java:2592)
	... 17 more

[WARNING ] TRAS0115W: Request AAATEXKsEfJ_AAAAAAAAAAO on thread 00000057 which was previously detected to be hung, has completed after 936215.673ms.
```
Partial thread dump
```
"Default Executor-thread-29" #87 daemon prio=5 os_prio=31 tid=0x00007fa06793d800 nid=0x13d03 waiting for monitor entry [0x0000700012743000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at oracle.jdbc.driver.PhysicalConnection.isProxySession(PhysicalConnection.java:4398)
	- waiting to lock <0x00000007bd6d0900> (a oracle.jdbc.driver.T4CConnection)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.ibm.ws.rsadapter.impl.OracleHelper.doConnectionCleanup(OracleHelper.java:354)
	at com.ibm.ws.rsadapter.impl.WSRdbManagedConnectionImpl.cleanupStates(WSRdbManagedConnectionImpl.java:2847)
	at com.ibm.ws.rsadapter.impl.WSRdbManagedConnectionImpl.cleanup(WSRdbManagedConnectionImpl.java:2774)
	at com.ibm.ejs.j2c.MCWrapper.cleanup(MCWrapper.java:1541)
	at com.ibm.ejs.j2c.FreePool.cleanupAndDestroyMCWrapper(FreePool.java:459)
	at com.ibm.ejs.j2c.PoolManager.reserve(PoolManager.java:1602)
	at com.ibm.ejs.j2c.ConnectionManager.allocateMCWrapper(ConnectionManager.java:581)
	at com.ibm.ejs.j2c.ConnectionManager.allocateConnection(ConnectionManager.java:314)
	at com.ibm.ws.rsadapter.jdbc.WSJdbcDataSource.getConnection(WSJdbcDataSource.java:138)
	at com.ibm.ws.rsadapter.jdbc.WSJdbcDataSource.getConnection(WSJdbcDataSource.java:112)
	at test.dao.AuditDao.store(AuditDao.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:88)
	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:78)
	at org.jboss.weld.injection.MethodInvocationStrategy$SimpleMethodInvocationStrategy.invoke(MethodInvocationStrategy.java:129)
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:299)
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:277)
	at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:255)
	at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:269)
	at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:258)
	at org.jboss.weld.event.EventImpl.fire(EventImpl.java:92)
	at test.AuthHomeServlet.audit(AuthHomeServlet.java:72)
	at test.AuthHomeServlet.doPost(AuthHomeServlet.java:37)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1230)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:729)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:426)
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.invokeTarget(WebAppFilterChain.java:182)
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:93)
	at test.MkidUserPrincipalFilter.doFilter(MkidUserPrincipalFilter.java:38)
	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:201)
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:90)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.doFilter(WebAppFilterManager.java:1001)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1139)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1010)
	at com.ibm.ws.webcontainer.servlet.CacheServletWrapper.handleRequest(CacheServletWrapper.java:75)
	at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:938)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:279)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1136)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:417)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:376)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:548)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:482)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:347)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.ready(HttpInboundLink.java:318)
	at com.ibm.ws.channel.ssl.internal.SSLConnectionLink.determineNextChannel(SSLConnectionLink.java:1077)
	at com.ibm.ws.channel.ssl.internal.SSLConnectionLink$MyReadCompletedCallback.complete(SSLConnectionLink.java:656)
	at com.ibm.ws.channel.ssl.internal.SSLReadServiceContext$SSLReadCompletedCallback.complete(SSLReadServiceContext.java:1803)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:503)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueManager.java:573)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:954)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:1043)
	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:239)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
	- <0x00000007822c8b38> (a java.util.concurrent.ThreadPoolExecutor$Worker)
```

**Comment by dyapasrikanth** [comment]
Let me know if you need more details on this.

**Comment by nmittles** [comment]
Our JDBC team has been taking a look at this.  From the information provided it appears that Oracle's JDBC driver code is deadlocking. The thread dump information provided shows us one thread in contention of an `oracle.jdbc.driver.PhysicalConnection` object.  There should be another thread also contending for access to this object. It would be interested to see what this other thread is doing.

That being said we're looking at non-Liberty code here. Liberty *might* be able to work around the Oracle code deadlocking, but that is a big if. We would need to correctly guess why the Oracle code is deadlocking and then find a sequence of Oracle API calls that would prevent the driver from getting into this situation.  The real solution will require contacting your Oracle support for assistance on configuring/fixing their JDBC driver/database.

As for throwing a `connectionTimeout` exception, Liberty has the connection in its connection pool, and is able to use the connection via the JDBC driver.  The JDBC driver then uses the connection to contact the database, and then this JDBC driver code deadlocks for some unknown reason (again this is not code Liberty has control over). So, we don't see this as an appropriate scenario to have the Liberty server throw a  `connectionTimeout` exception. This would be assuming we could get control back from the JDBC driver's deadlocked code, which is the real problem.

Our team will try to assist as much as it can, but at the end of the day we're attempting to work around code that is deadlocking inside the Oracle JDBC driver.

**Comment by dyapasrikanth** [comment]
@nmittles thanks for the response, I hope I will get some direction soon.

**Comment by nmittles** [comment]
@dyapasrikanth Do you have more details on the thread dump?  Specifically what other threads are blocked in `oracle.jdbc.driver.PhysicalConnection`?

**Comment by dyapasrikanth** [comment]
@nmittles I didn't see any other thread in blocked state.
[Threaddump.txt](https://github.com/OpenLiberty/open-liberty/files/3962794/Threaddump.txt)

Do I need set the `oracle.jdbc.ReadTimeout` property in datasource configuration ? If I have to How can I set it ?

like this `<properties.oracle connectionProperties="oracle.jdbc.ReadTimeout=10"/>`

**Comment by nmittles** [comment]
The provided Threaddump.txt shows `Thread-170` is running the test application's `AuditDao.store()` method.  `Thread-170` is blocked on making a reflective call to `oracle.jdbc.driver.PhysicalConnection.isProxySession()`. Thread 170's block is due to `Thread-30`.  See the snippet below:

```
3XMTHREADINFO      "Default Executor-thread-170" J9VMThread:0x000000000336EC00, j9thread_t:0x00007FB72C06B7A0, java/lang/Thread:0x00000000FC0015A0, state:B, prio=5
3XMJAVALTHREAD            (java/lang/Thread getId:0x132, isDaemon:true)
3XMTHREADINFO1            (native thread ID:0x7685, native priority:0x5, native policy:UNKNOWN, vmstate:B, vm thread flags:0x00000201)
3XMTHREADINFO2            (native stack address range from:0x00007FB766725000, to:0x00007FB766765000, size:0x40000)
3XMCPUTIME               CPU usage total: 0.087915636 secs, current category="Application"
3XMTHREADBLOCK     Blocked on: oracle/jdbc/driver/T4CConnection@0x00000000F5AFA938 Owned by: "Thread-30" (J9VMThread:0x0000000003957600, java/lang/Thread:0x00000000FC001528)
3XMHEAPALLOC             Heap bytes allocated since last GC cycle=0 (0x0)
3XMTHREADINFO3           Java callstack:
4XESTACKTRACE                at sun/reflect/NativeMethodAccessorImpl.invoke0(Native Method)
4XESTACKTRACE                at sun/reflect/NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:95(Compiled Code))
4XESTACKTRACE                at sun/reflect/DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55(Compiled Code))
4XESTACKTRACE                at java/lang/reflect/Method.invoke(Method.java:508(Compiled Code))
4XESTACKTRACE                at com/ibm/ws/rsadapter/impl/OracleHelper.doConnectionCleanup(OracleHelper.java:355)
```
<br />
<br />
<br />

Checking `Thread-30` yields:
```
"Thread-30" J9VMThread:0x0000000003957600, j9thread_t:0x00007FB6FC019560, java/lang/Thread:0x00000000FC001528, state:R, prio=5
3XMJAVALTHREAD            (java/lang/Thread getId:0x16E, isDaemon:true)
3XMTHREADINFO1            (native thread ID:0x53B, native priority:0x5, native policy:UNKNOWN, vmstate:R, vm thread flags:0x00000001)
3XMTHREADINFO2            (native stack address range from:0x00007FB777660000, to:0x00007FB7776A0000, size:0x40000)
3XMCPUTIME               CPU usage total: 0.001033796 secs, current category="Application"
3XMHEAPALLOC             Heap bytes allocated since last GC cycle=0 (0x0)
3XMTHREADINFO3           Java callstack:
4XESTACKTRACE                at java/net/SocketInputStream.socketRead0(Native Method)
4XESTACKTRACE                at java/net/SocketInputStream.socketRead(SocketInputStream.java:127(Compiled Code))
4XESTACKTRACE                at java/net/SocketInputStream.read(SocketInputStream.java:182(Compiled Code))
4XESTACKTRACE                at java/net/SocketInputStream.read(SocketInputStream.java:152(Compiled Code))
4XESTACKTRACE                at java/net/ManagedSocketInputStreamAPSIHighPerformanceNew.read(ManagedSocketInputStreamAPSIHighPerformanceNew.java:100(Compiled Code))
4XESTACKTRACE                at oracle/net/ns/Packet.receive(Packet.java:311)
4XESTACKTRACE                at oracle/net/ns/DataPacket.receive(DataPacket.java:105)
4XESTACKTRACE                at oracle/net/ano/CryptoDataPacket.receive(Bytecode PC:1)
4XESTACKTRACE                at oracle/net/ns/NetInputStream.getNextPacket(NetInputStream.java:305)
4XESTACKTRACE                at oracle/net/ns/NetInputStream.read(NetInputStream.java:249)
4XESTACKTRACE                at oracle/net/ns/NetInputStream.read(NetInputStream.java:171)
4XESTACKTRACE                at oracle/net/ns/NetInputStream.read(NetInputStream.java:89)
4XESTACKTRACE                at oracle/jdbc/driver/T4CSocketInputStreamWrapper.readNextPacket(T4CSocketInputStreamWrapper.java:123)
4XESTACKTRACE                at oracle/jdbc/driver/T4CSocketInputStreamWrapper.read(T4CSocketInputStreamWrapper.java:79)
4XESTACKTRACE                at oracle/jdbc/driver/T4CMAREngineStream.unmarshalUB1(T4CMAREngineStream.java:429)
4XESTACKTRACE                at oracle/jdbc/driver/T4CTTIfun.receive(T4CTTIfun.java:397)
4XESTACKTRACE                at oracle/jdbc/driver/T4CTTIfun.doRPC(T4CTTIfun.java:257)
4XESTACKTRACE                at oracle/jdbc/driver/T4CTTIoping.doOPING(T4CTTIoping.java:50)
4XESTACKTRACE                at oracle/jdbc/driver/T4CConnection.doPingDatabase(T4CConnection.java:5221)
5XESTACKTRACE                   (entered lock: oracle/jdbc/driver/T4CConnection@0x00000000F5AFA938, entry count: 1)
4XESTACKTRACE                at oracle/jdbc/driver/PhysicalConnection$2.run(PhysicalConnection.java:7044)
4XESTACKTRACE                at java/lang/Thread.run(Thread.java:785)
```
<br />
<br />
<br />

Now that we see the deadlock is due to a socket read in Oracle JDBC driver, setting the `oracle.jdbc.ReadTimeout` would be an appropriate workaround to the hang in the Oracle JDBC driver.  Keep in mind that the `oracle.jdbc.ReadTimeout` is specified in milliseconds, so a value of 10 might be too short.  Our other recommendation would be to use Oracle Universal Connection Pool (UCP), which supports Oracle features such as Fast Connection Failover.  It is possible that UCP will circumvent the deadlock completely. See the following link for more information on UCP and Liberty:
https://openliberty.io/blog/2019/04/26/reactive-microservices-microprofile-19004.html#oracle

**Comment by dyapasrikanth** [comment]
@nmittles Oracle UCP worked like a charm as **it has the timeout (15s - hardcoded) on connection validation**.

```	 at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	 at java.util.concurrent.FutureTask.awaitDone(FutureTask.java:426)
	 at java.util.concurrent.FutureTask.get(FutureTask.java:204)
	 at oracle.ucp.util.UCPTaskManagerImpl$3.get(UCPTaskManagerImpl.java:163)
	 at oracle.ucp.common.UniversalPooledConnectionImpl.isValid(UniversalPooledConnectionImpl.java:260)
	 at oracle.ucp.common.UniversalPooledConnectionImpl.isValid(UniversalPooledConnectionImpl.java:225)
	 at oracle.ucp.common.UniversalConnectionPoolImpl.borrowConnectionAndValidate(UniversalConnectionPoolImpl.java:173)
	 at oracle.ucp.common.UniversalConnectionPoolImpl.borrowConnection(UniversalConnectionPoolImpl.java:143)
	 at oracle.ucp.jdbc.JDBCConnectionPool.borrowConnection(JDBCConnectionPool.java:157)
	 at oracle.ucp.jdbc.PoolDataSourceImpl.getConnection(PoolDataSourceImpl.java:931)
	 at oracle.ucp.jdbc.PoolDataSourceImpl.getConnection(PoolDataSourceImpl.java:873)
	 at oracle.ucp.jdbc.PoolDataSourceImpl.getConnection(PoolDataSourceImpl.java:863)
	 at com.ibm.ws.rsadapter.impl.WSManagedConnectionFactoryImpl$7.run(WSManagedConnectionFactoryImpl.java:995)
	 at com.ibm.ws.rsadapter.impl.WSManagedConnectionFactoryImpl$7.run(WSManagedConnectionFactoryImpl.java:984)```

Can we get this timeout in Liberty connection manager ?
