### ISSUE TITLE
JSF JSFInjectionClassListCollaborator UnableToAdaptException

### ISSUE THREAD

**Issue by wtlucy** [OpenLiberty/open-liberty#10150]
The following `CWWKM0453E` error is logged at startup time when JSF is initialized.  There does not appear to be any functional issue - this `JSFInjectionClassListCollaborator` is successfully invoked again at later points in the startup process.  We might just need to prevent this collaborator from running at this point, or to suppress exception.

```
[12/12/19, 10:09:20:120 UTC] 0000002c jsf           1 
com.ibm.ws.jsf.shared.util.JSFInjectionClassListCollaborator getInjectionClasses failed to adapt to InfoStore for class annotations
com.ibm.wsspi.adaptable.module.UnableToAdaptException: CWWKM0453E: WebSphere Application Server internal error occurred. Please contact WebSphere Application Server support with the following data: Container is not a module com.ibm.ws.adaptable.module.internal.AdaptableContainerImpl@adf77f56 ( bundleentry://105.fwk-1144735314/ file:/home/jazz_build/_ngwAsBywEeqOxqTQwEzk7g-EBC.PROD.WASRTC-6MG-000-00-00/jbe/build/dev/image/output/wlp/usr/servers/jsfAparServer/workarea/org.eclipse.osgi/105/data/cacheAdapt/.overlay/ )
    at com.ibm.ws.container.service.annocache.internal.WebAnnotationsAdapterImpl.adapt(WebAnnotationsAdapterImpl.java:54)
    at com.ibm.ws.container.service.annocache.internal.WebAnnotationsAdapterImpl.adapt(WebAnnotationsAdapterImpl.java:33)
    at com.ibm.ws.adaptable.module.internal.AdapterFactoryServiceImpl.adapt(AdapterFactoryServiceImpl.java:200)
    at com.ibm.ws.adaptable.module.internal.AdaptableContainerImpl.adapt(AdaptableContainerImpl.java:174)
    at com.ibm.ws.container.service.annocache.AnnotationsBetaHelper.getWebAnnotations(AnnotationsBetaHelper.java:268)
    at com.ibm.ws.jsf.shared.util.JSFInjectionClassListCollaborator.getInjectionClasses(JSFInjectionClassListCollaborator.java:100)
    at com.ibm.ws.webcontainer.osgi.webapp.WebAppInjectionClassListAdapter.getInjectionClasses(WebAppInjectionClassListAdapter.java:98)
    at com.ibm.ws.container.service.app.deploy.internal.InjectionClassListAdapter.adapt(InjectionClassListAdapter.java:41)
    at com.ibm.ws.container.service.app.deploy.internal.InjectionClassListAdapter.adapt(InjectionClassListAdapter.java:31)
    at com.ibm.ws.adaptable.module.internal.AdapterFactoryServiceImpl.adapt(AdapterFactoryServiceImpl.java:200)
    at com.ibm.ws.adaptable.module.internal.AdaptableContainerImpl.adapt(AdaptableContainerImpl.java:174)
    at com.ibm.ws.cdi.internal.archive.liberty.CDIArchiveImpl.getInjectionClassList(CDIArchiveImpl.java:403)
    at com.ibm.ws.cdi.impl.weld.BeanDeploymentArchiveImpl.initializeJEEComponentClasses(BeanDeploymentArchiveImpl.java:361)
    at com.ibm.ws.cdi.impl.weld.BeanDeploymentArchiveImpl.scan(BeanDeploymentArchiveImpl.java:289)
    at com.ibm.ws.cdi.impl.weld.WebSphereCDIDeploymentImpl.scan(WebSphereCDIDeploymentImpl.java:601)
    at com.ibm.ws.cdi.impl.CDIContainerImpl.startInitialization(CDIContainerImpl.java:128)
    at com.ibm.ws.cdi.liberty.CDIRuntimeImpl.applicationStarting(CDIRuntimeImpl.java:448)
    at com.ibm.ws.container.service.state.internal.ApplicationStateManager.fireStarting(ApplicationStateManager.java:51)
    at com.ibm.ws.container.service.state.internal.StateChangeServiceImpl.fireApplicationStarting(StateChangeServiceImpl.java:50)
    at com.ibm.ws.app.manager.module.internal.SimpleDeployedAppInfoBase.preDeployApp(SimpleDeployedAppInfoBase.java:550)
    at com.ibm.ws.app.manager.module.internal.SimpleDeployedAppInfoBase.installApp(SimpleDeployedAppInfoBase.java:511)
    at com.ibm.ws.app.manager.module.internal.DeployedAppInfoBase.deployApp(DeployedAppInfoBase.java:347)
    at com.ibm.ws.app.manager.war.internal.WARApplicationHandlerImpl.install(WARApplicationHandlerImpl.java:65)
    at com.ibm.ws.app.manager.internal.statemachine.StartAction.execute(StartAction.java:140)
    at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.enterState(ApplicationStateMachineImpl.java:1266)
    at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.run(ApplicationStateMachineImpl.java:881)
    at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:239)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:825)
```

**Comment by wtlucy** [comment]
This duplicates the older issue #9283.
