### ISSUE TITLE
Fault Tolerance reports an internal error when an asynchronous method returns null

### ISSUE THREAD

**Issue by Joseph-Cass** [OpenLiberty/open-liberty#10189]
**Describe the bug**
Seen whilst writing a unit test. Looks as though if a user has an async method which returns null, FT returns the following internal error:

```
java.util.concurrent.ExecutionException: org.eclipse.microprofile.faulttolerance.exceptions.FaultToleranceException: internal.error.CWMFT4998E
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2022)
	at com.ibm.ws.microprofile.faulttolerance.test.AsyncTest.testAsyncRequestContextCalls(AsyncTest.java:177)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:30)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)
Caused by: org.eclipse.microprofile.faulttolerance.exceptions.FaultToleranceException: internal.error.CWMFT4998E
	at com.ibm.ws.microprofile.faulttolerance20.impl.AsyncExecutor.handleException(AsyncExecutor.java:504)
	at com.ibm.ws.microprofile.faulttolerance20.impl.AsyncExecutor.runExecutionAttempt(AsyncExecutor.java:294)
	at com.ibm.ws.microprofile.faulttolerance20.impl.AsyncExecutor.lambda$0(AsyncExecutor.java:210)
	at com.ibm.ws.microprofile.faulttolerance20.impl.AsyncExecutor$$Lambda$20.0000000000000000.run(Unknown Source)
	at com.ibm.ws.microprofile.faulttolerance20.state.impl.AsyncBulkheadStateNullImpl.lambda$0(AsyncBulkheadStateNullImpl.java:35)
	at com.ibm.ws.microprofile.faulttolerance20.state.impl.AsyncBulkheadStateNullImpl$$Lambda$22.0000000000000000.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.lang.NullPointerException
	at com.ibm.ws.microprofile.faulttolerance20.impl.AsyncCompletionStageExecutor.processMethodResult(AsyncCompletionStageExecutor.java:120)
	at com.ibm.ws.microprofile.faulttolerance20.impl.AsyncExecutor.runExecutionAttempt(AsyncExecutor.java:277)
	... 10 more


```

**Expected behavior**
A debug message stating the method should not return null

**Comment by Joseph-Cass** [comment]
Needs testing for FT 1.0 and 2.0 and for CompletionStages and Futures
