### ISSUE TITLE
H2 close with error produces invalid state

### ISSUE THREAD

**Issue by loriadi** [OpenLiberty/open-liberty#10196]
This error happens when the H2 code has not yet sent the response to the initial request (we have waited until the connection is established), and then an error occurs on the connection.  In this case, we need to close the connection and discard the response, as the link is closed upon error.

This problem is intermittent and would only occur if the H2 connection experienced an error after the connection is established, but before the response to the initial request was satisfied.

**Comment by loriadi** [comment]
Stack Dump = java.io.IOException: Invalid state
	at com.ibm.ws.http.channel.internal.outbound.HttpOutputStreamImpl.flushHeaders(HttpOutputStreamImpl.java:459)
	at com.ibm.ws.webcontainer31.osgi.response.IResponse31Impl.flushHeaders(IResponse31Impl.java:70)
	at com.ibm.ws.webcontainer31.srt.SRTServletResponse31.flushData(SRTServletResponse31.java:142)
	at com.ibm.ws.webcontainer31.srt.SRTServletResponse31.finishKeepConnection(SRTServletResponse31.java:107)
	at com.ibm.ws.webcontainer31.osgi.srt.SRTConnectionContext31.finishConnection(SRTConnectionContext31.java:152)
	at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:1166)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:279)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1134)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:415)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:374)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:548)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:482)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:347)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.ready(HttpInboundLink.java:318)
	at com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.sendToDiscriminators(NewConnectionInitialReadCallback.java:165)
	at com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.complete(NewConnectionInitialReadCallback.java:74)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:503)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueManager.java:573)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:954)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:1043)
	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:239)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:825)

**Comment by loriadi** [comment]
#build
