### ISSUE TITLE
Rest Client for MicroProfile loses entity on POST requests with status code 202 response

### ISSUE THREAD

**Issue by SPSpunkt** [OpenLiberty/open-liberty#10228]
**Describe the bug**
If using Rest Client for MicroProfile (Apache CXF impl in case of OLP/WLP!) together with a remote service that responds a status code 202 and an entity, the response filter (chain) is called twice but the entity is null for the final call. (InputStream#read == -1)

* Logging filters may fail with NPT like issues or  
* even simple unmarshalling fails for the missing entity

Sample stack traces (please take care, it is very use case dependent)
```
[ERROR   ] SRVE0315E: Es ist eine Ausnahme eingetreten: java.lang.Throwable: javax.ws.rs.client.ResponseProcessingException: Problem with reading the data, class java.sql.Date, ContentType: application/json.
	at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:5075)
	at [internal classes]
Caused by: javax.ws.rs.client.ResponseProcessingException: Problem with reading the data, class java.sql.Date, ContentType: application/json.
	at org.apache.cxf.jaxrs.impl.ResponseImpl.reportMessageHandlerProblem(ResponseImpl.java:563)
	at [internal classes]
	at com.sun.proxy.$Proxy86.dTOJson(Unknown Source)
	at servicea.Resources.dtoJson(Resources.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.ibm.ws.jaxrs20.cdi.component.JaxRsFactoryImplicitBeanCDICustomizer.serviceInvoke(JaxRsFactoryImplicitBeanCDICustomizer.java:304)
	... 1 more
Caused by: javax.json.bind.JsonbException: Internal error: null
	at org.eclipse.yasson.internal.Unmarshaller.deserializeItem(Unmarshaller.java:74)
	... 9 more
Caused by: java.util.NoSuchElementException
	at org.glassfish.json.JsonParserImpl.next(JsonParserImpl.java:361)
	... 9 more
```
**Steps to Reproduce**
Use a OLP/JAX-RS client (Apache CXF) to consume a remote REST service, that response a status code 202 together with an entity. You can find a simple test project at https://bitbucket.org/spspunkt/apachecxfbug/src/master/service-a/src/test/java/it/TestIT.java
after deploying Service A and Service B (https://bitbucket.org/spspunkt/apachecxfbug/src/master/) to localhost.

**Expected behavior**
The response entity should always be available. (the response entity is available e.g. deploying our test projects to Wildfly 18 platform)

**Diagnostic information:**
tested with
 - OpenLiberty Version: [19.0.0.10]
 - WLP Version: [19.0.0.6]
 - Java HotSpot(TM) 64-Bit Server VM, Version 1.8.0_162-b12

**Comment by andymc12** [comment]
Thanks for reporting this error.  It seems like the issue occurs when the JSON-B MessageBodyWriter is used to send the request entity.  That class was calling `json.toJson(obj, entityStream)` which closes the passed-in entity stream after writing the object to it.  This is in violation of the spec which says that the MBW must not close the entity stream.  It also forces the request to be processed which is why the ClientResponseFilter is invoked twice (first during the inadvertent request processing, and again during normal response processing).  I believe that the double processing is what was resulting in the problem with your test application.  I was able to reproduce your results prior to my change, and now I get the expected results.
