### ISSUE TITLE
Unsynchronized use of shared SimpleDateFormat

### ISSUE THREAD

**Issue by tbitonti** [OpenLiberty/open-liberty#10221]
Build break:

componenttest.exception.TopologyException: Failures occured while waiting for app to start:
  Application AGG failure: CWWKZ0002E: An exception occurred while starting the application AGG. The exception message was: com.ibm.ws.container.service.metadata.MetaDataException: java.lang.ArrayIndexOutOfBoundsException: Array index out of range: -2147483648
at componenttest.topology.impl.LibertyServer.validateAppsLoaded(LibertyServer.java:1739)
at componenttest.topology.impl.LibertyServer.validateServerStarted(LibertyServer.java:2252)
at componenttest.topology.impl.LibertyServer.startServerWithArgs(LibertyServer.java:1514)
at componenttest.topology.impl.LibertyServer.startServerAndValidate(LibertyServer.java:1097)
at componenttest.topology.impl.LibertyServer.startServerAndValidate(LibertyServer.java:1079)
at componenttest.topology.impl.LibertyServer.startServerAndValidate(LibertyServer.java:1066)
at componenttest.topology.impl.LibertyServer.startServer(LibertyServer.java:929)
at com.ibm.ws.jdbc.fat.fvt.ttt.tests.DestroyInUseConnectionTest.setUp(DestroyInUseConnectionTest.java:30)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:334)
at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:168)
```

The underlying FFDC causing the problem is:
```
Caused by: java.lang.ArrayIndexOutOfBoundsException: Array index out of range: -2147483648
        at java.base/java.util.Calendar.getDisplayName(Calendar.java:2146)
        at java.base/java.text.SimpleDateFormat.subFormat(SimpleDateFormat.java:1156)
        at java.base/java.text.SimpleDateFormat.format(SimpleDateFormat.java:997)
        at java.base/java.text.SimpleDateFormat.format(SimpleDateFormat.java:967)
        at java.base/java.text.DateFormat.format(DateFormat.java:374)
        at com.ibm.ws.annocache.util.internal.UtilImpl_Utils.getDateAndTime(UtilImpl_Utils.java:330)
        at com.ibm.ws.annocache.targets.cache.internal.TargetCacheImpl_WriterBinary.getTimeStamp(TargetCacheImpl_WriterBinary.java:46)
        at com.ibm.ws.annocache.targets.cache.internal.TargetCacheImpl_WriterBinary.writeHeader(TargetCacheImpl_WriterBinary.java:167)
        at com.ibm.ws.annocache.targets.cache.internal.TargetCacheImpl_WriterBinary.writeFragment(TargetCacheImpl_WriterBinary.java:400)
        at com.ibm.ws.annocache.targets.cache.internal.TargetCacheImpl_WriterBinary.writeEntire(TargetCacheImpl_WriterBinary.java:393)
        at com.ibm.ws.annocache.targets.cache.internal.TargetCacheImpl_DataMod$2.accept(TargetCacheImpl_DataMod.java:194)
        at com.ibm.ws.annocache.targets.cache.internal.TargetCacheImpl_DataMod$2.accept(TargetCacheImpl_DataMod.java:192)
        at com.ibm.ws.annocache.targets.cache.internal.TargetCacheImpl_DataBase.performBinaryWrite(TargetCacheImpl_DataBase.java:543)
        at com.ibm.ws.annocache.targets.cache.internal.TargetCacheImpl_DataApp.scheduleWrite(TargetCacheImpl_DataApp.java:412)
        at com.ibm.ws.annocache.targets.cache.internal.TargetCacheImpl_DataMod.scheduleWrite(TargetCacheImpl_DataMod.java:692)
        at com.ibm.ws.annocache.targets.cache.internal.TargetCacheImpl_DataMod.writeContainersTable(TargetCacheImpl_DataMod.java:207)
        at com.ibm.ws.annocache.targets.internal.TargetsScannerOverallImpl.validContainerTable(TargetsScannerOverallImpl.java:790)
        at com.ibm.ws.annocache.targets.internal.TargetsScannerOverallImpl.validInternalContainers(TargetsScannerOverallImpl.java:1006)
        at com.ibm.ws.annocache.targets.internal.TargetsScannerOverallImpl.validInternalContainers_Select(TargetsScannerOverallImpl.java:968)
        at com.ibm.ws.annocache.targets.internal.TargetsScannerOverallImpl.validInternalUnresolved(TargetsScannerOverallImpl.java:1560)
        at com.ibm.ws.annocache.targets.internal.TargetsScannerOverallImpl.validInternal(TargetsScannerOverallImpl.java:2084)
        at com.ibm.ws.annocache.targets.internal.AnnotationTargetsImpl_Targets.ensureInternalResults(AnnotationTargetsImpl_Targets.java:730)
        at com.ibm.ws.annocache.targets.internal.AnnotationTargetsImpl_Targets.getSeedTable(AnnotationTargetsImpl_Targets.java:559)
        at com.ibm.ws.annocache.targets.internal.AnnotationTargetsImpl_Targets.getAnnotatedClasses(AnnotationTargetsImpl_Targets.java:1117)
        at com.ibm.ws.annocache.targets.internal.AnnotationTargetsImpl_Targets.getAnnotatedClasses(AnnotationTargetsImpl_Targets.java:1169)
        at com.ibm.ws.container.service.annocache.internal.FragmentAnnotationsImpl.selectAnnotatedClasses(FragmentAnnotationsImpl.java:50)
        at com.ibm.ws.webcontainer.osgi.container.config.WebAppConfiguratorHelper.configureFromAnnotations(WebAppConfiguratorHelper.java:823)
        at com.ibm.ws.webcontainer.osgi.container.config.WebAppConfigurator.configure(WebAppConfigurator.java:439)
        at com.ibm.ws.webcontainer.osgi.container.config.WebAppConfigurationAdapter.adapt(WebAppConfigurationAdapter.java:119)
        at com.ibm.ws.webcontainer.osgi.container.config.WebAppConfigurationAdapter.adapt(WebAppConfigurationAdapter.java:43)
        at com.ibm.ws.adaptable.module.internal.AdapterFactoryServiceImpl.adapt(AdapterFactoryServiceImpl.java:200)
        at com.ibm.ws.adaptable.module.internal.AdaptableContainerImpl.adapt(AdaptableContainerImpl.java:174)
        at com.ibm.ws.webcontainer.osgi.WebContainer.createModuleMetaData(WebContainer.java:833)
        ... 13 more
```

**Comment by tbitonti** [comment]
Note:
        // Per: https://stackoverflow.com/questions/18383251/strange-arrayindexoutofboundsexception-for-java-simpledateformat
