### ISSUE TITLE
JsonB provider not found when loaded from library

### ISSUE THREAD

**Issue by Legion2** [OpenLiberty/open-liberty#10248]
**Describe the bug**
I'm using `smallrye-reactive-messaging-provider` library as implementation of the reactive messaging api. The library is packaged into the war file, because the implementation provided by liberty don't provide the new features I require. On a Incoming message channel I want to convert the input stream using Jsonb to an object.
```java
@Incoming("results")
public CompletionStage<Void> getMessages(Message<InputStream> message) {
	JsonbBuilder.create();
}
```
But the Jsonb provider is not found.
In other parts of the code the Jsonb is used without problems.

```
io.smallrye.reactive.messaging.ProcessingException: Exception thrown when calling the method de.uni_stuttgart.tik.viplab.websocket_api.ecs.ECSComputationService#getMessages
	at io.smallrye.reactive.messaging.AbstractMediator.lambda$initialize$0(AbstractMediator.java:50)
	at io.smallrye.reactive.messaging.AbstractMediator.invoke(AbstractMediator.java:61)
	at io.smallrye.reactive.messaging.SubscriberMediator.lambda$processMethodReturningACompletionStage$6(SubscriberMediator.java:161)
	at io.smallrye.reactive.streams.stages.FlatMapCompletionStageFactory$FlatMapCompletionStage.lambda$apply$0(FlatMapCompletionStageFactory.java:47)
	at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onNext(FlowableFlatMap.java:132)
	at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.drainLoop(FlowableFlatMap.java:501)
	at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.drain(FlowableFlatMap.java:366)
	at io.reactivex.internal.operators.flowable.FlowableFlatMap$InnerSubscriber.onNext(FlowableFlatMap.java:665)
	at io.reactivex.internal.subscriptions.DeferredScalarSubscription.complete(DeferredScalarSubscription.java:117)
	at io.reactivex.processors.AsyncProcessor.subscribeActual(AsyncProcessor.java:242)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.Flowable.subscribe(Flowable.java:14865)
	at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onNext(FlowableFlatMap.java:163)
	at io.smallrye.reactive.streams.utils.ConnectableProcessor.onNext(ConnectableProcessor.java:122)
	at org.eclipse.microprofile.reactive.streams.operators.CompletionSubscriber$1DefaultCompletionSubscriber.onNext(CompletionSubscriber.java:85)
	at org.eclipse.microprofile.reactive.streams.operators.CompletionSubscriber$1DefaultCompletionSubscriber.onNext(CompletionSubscriber.java:85)
	at io.smallrye.reactive.messaging.SubscriberMediator$1.onNext(SubscriberMediator.java:100)
	at io.smallrye.reactive.streams.utils.WrappedSubscriber.onNext(WrappedSubscriber.java:42)
	at io.reactivex.subscribers.SafeSubscriber.onNext(SafeSubscriber.java:90)
	at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.drainLoop(FlowableFlatMap.java:501)
	at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.drain(FlowableFlatMap.java:366)
	at io.reactivex.internal.operators.flowable.FlowableFlatMap$InnerSubscriber.onNext(FlowableFlatMap.java:665)
	at io.reactivex.internal.subscriptions.DeferredScalarSubscription.complete(DeferredScalarSubscription.java:117)
	at io.reactivex.processors.AsyncProcessor.onComplete(AsyncProcessor.java:201)
	at io.smallrye.reactive.streams.utils.CompletionStageToPublisher.lambda$fromCompletionStage$0(CompletionStageToPublisher.java:23)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2144)
	at de.uni_stuttgart.tik.ecs.ecc.connector.ECSInput.executePollActions(ECSInput.java:81)
	at de.uni_stuttgart.tik.ecs.ecc.connector.ECSInput.lambda$2(ECSInput.java:57)
	at com.ibm.ws.threading.internal.PolicyTaskFutureImpl.run(PolicyTaskFutureImpl.java:715)
	at com.ibm.ws.threading.internal.PolicyExecutorImpl.runTask(PolicyExecutorImpl.java:1135)
	at com.ibm.ws.threading.internal.PolicyExecutorImpl$GlobalPoolTask.run(PolicyExecutorImpl.java:189)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.GeneratedMethodAccessor671.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at io.smallrye.reactive.messaging.AbstractMediator.lambda$initialize$0(AbstractMediator.java:48)
	... 36 more
Caused by: java.util.ServiceConfigurationError: javax.json.bind.spi.JsonbProvider: Provider org.eclipse.yasson.JsonBindingProvider not found
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:590)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1212)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1221)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1265)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1300)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1385)
	at javax.json.bind.spi.JsonbProvider.provider(JsonbProvider.java:112)
	at javax.json.bind.JsonbBuilder.create(JsonbBuilder.java:108)
	at de.uni_stuttgart.tik.viplab.websocket_api.ecs.ECSComputationService.getMessages(ECSComputationService.java:69)
	at de.uni_stuttgart.tik.viplab.websocket_api.ecs.ECSComputationService$Proxy$_$$_WeldClientProxy.getMessages(Unknown Source)
	... 39 more
```

**Steps to Reproduce**
maven dependencies
```
	<dependencies>
		<!-- Workaround for Beta features -->
		<dependency>
			<groupId>io.smallrye.reactive</groupId>
			<artifactId>smallrye-reactive-messaging-provider</artifactId>
			<version>1.0.8</version>
		</dependency>
		<dependency>
			<groupId>io.smallrye.reactive</groupId>
			<artifactId>smallrye-reactive-streams-operators</artifactId>
			<version>1.0.10</version>
		</dependency>

		<dependency>
			<groupId>javax.websocket</groupId>
			<artifactId>javax.websocket-api</artifactId>
			<version>1.1</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>javax.json.bind</groupId>
			<artifactId>javax.json.bind-api</artifactId>
			<version>1.0</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
			<version>1.7.28</version>
		</dependency>
		<dependency>
			<groupId>javax.enterprise</groupId>
			<artifactId>cdi-api</artifactId>
			<version>2.0</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>javax.annotation</groupId>
			<artifactId>javax.annotation-api</artifactId>
			<version>1.3.2</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.eclipse.microprofile.config</groupId>
			<artifactId>microprofile-config-api</artifactId>
			<version>1.3</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.eclipse.microprofile.metrics</groupId>
			<artifactId>microprofile-metrics-api</artifactId>
			<version>2.0</version>
			<scope>provided</scope>
		</dependency>
		<!-- <dependency> <groupId>org.eclipse.microprofile.reactive.messaging</groupId> 
			<artifactId>microprofile-reactive-messaging-api</artifactId> <version>1.0</version> 
			<scope>compile</scope> </dependency> -->
		<dependency>
			<groupId>org.eclipse.microprofile.rest.client</groupId>
			<artifactId>microprofile-rest-client-api</artifactId>
			<version>1.3.4</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>javax.ws.rs</groupId>
			<artifactId>javax.ws.rs-api</artifactId>
			<version>2.1.1</version>
			<scope>provided</scope>
		</dependency>

	</dependencies>
```
2. send a message to the incoming channel.
3. Code for handling the message is executed:
```
@Incoming("results")
public CompletionStage<Void> getMessages(Message<InputStream> message) {
	JsonbBuilder.create();
}
```
4. exception is thrown

**Expected behavior**
The Jsonb Provider is found and can be used to convert json strings to objects.

**Diagnostic information:**
 - OpenLiberty Version: 19.0.0.11 and 19.0.0.12
 - Java Version: 8 and 13 tested
```
java version "13.0.1" 2019-10-15
Java(TM) SE Runtime Environment (build 13.0.1+9)
Java HotSpot(TM) 64-Bit Server VM (build 13.0.1+9, mixed mode, sharing)
```
 - server.xml configuration 
```
<server description="name">
	<featureManager>
		<feature>websocket-1.1</feature>
		<feature>jsonb-1.0</feature>
		<feature>cdi-2.0</feature>
		<feature>mpConfig-1.3</feature>
		<feature>mpMetrics-2.0</feature>
		<feature>mpHealth-2.0</feature>
		<feature>concurrent-1.0</feature>
		<!-- <feature>mpReactiveMessaging-1.0</feature> -->
		<!-- <feature>mpRestClient-1.3</feature> -->
	</featureManager>

	<mpMetrics authentication="false"/>
	<httpEndpoint httpPort="${default.http.port}"
		httpsPort="-1" id="defaultHttpEndpoint" onError="FAIL" />
</server>
```
**Additional context**
It seams like a class loading problem, because the context Classloader can't find the SPI provider class `org.eclipse.yasson.JsonBindingProvider`, from this method invocation. But when in another context the SPI provider class `org.eclipse.yasson.JsonBindingProvider` can be loaded without problems.

**Comment by Azquelt** [comment]
I suspect this is caused by the TCCL being set to the app classloader during app startup (which is when smallrye reactive messaging initializes all the connectors). It looks like your connector is creating a background task (calling `ECSInput.lambda$2`), I assume that's inheriting the app classloader as the TCCL.

I've got a potential fix in #10262 but I misread your failure case initially and need to go back and add a test that better captures it.

**Comment by yasammez** [comment]
I am not entirely sure but I believe this fix broke my usecase of configuring custom adapters for mp-rest client.

I am using a microprofile-config.properties like

```
com.example.app.StuffApi/mp-rest/providers=com.example.app.JsonContextResolver
```

to be able to build my own Jsonb for REST requests.

```
@Provider
class JsonContextResolver implements ContextResolver<Jsonb> {
    @Override
    public Jsonb getContext(Class<?> type) {
        return JsonBuilder.newBuilder().withConfig(/* ... */).build();    
    }
}
```

This works with wlp 19.0.0.6 as intended. Hower on 20.0.0.2 this throws a ServiceConfigurationException and through debugging I found out the instantiated ServiceLoader doesn't have a provider for Jsonb registered. Which is curious, since the actual implementation, yasson, does exist in every place exactly as before.

Am I making a (hopefully simple to fix) configuration error or should I open a bug ticket for this?

**Comment by Azquelt** [comment]
@yasammez I don't _think_ so.

Your problem certainly could be as a result of the TCCL not being set up correctly as it will try to load `ServiceLoader` to get the  `JsonbProvider` when you call `JsonBuilder.newBuilder()`.

However, the change I made for this defect was to
 * ensure that the TCCL is set up correctly during CDI startup
 * remove some code that set up the TCCL from MicroProfile Metrics since this code is always driven by CDI, which now sets up the TCCL correctly

It's possible I've missed something there, but neither of those changes should affect what you're doing.

It does sound like a bug though. Can you open a new issue? As well as the information above, please include the set of features you're using in your `server.xml` and the exception stack trace if you have it. Thanks.
