### ISSUE TITLE
Test Failure (1023-20171119-0238): EEConcurrencyConfigTest.testNestedLongRunningPolicy task canceled due to lack of Modified method

### ISSUE THREAD

**Issue by njr-11** [OpenLiberty/open-liberty#1027]
Test case intermittently reports canceled task, which is due to the ManagedScheduledExecutorService modified method not being visible to OSGi, which then deactivates/activates the service upon modify of nested element, causing previously submitted tasks to be canceled.  The test often runs cleanly because the tasks can finish successfully before the deactivate logic is reached.

junit.framework.AssertionFailedError: 2017-11-19-06:31:15:488 The response did not contain "[SUCCESS]".  Full output is:"
ERROR: Caught exception attempting to call test method testTask1BlockedByTask2LongRunningCompleted on servlet fat.concurrent.web.EEConcurrencyUtilsFATServlet
java.util.concurrent.CancellationException
	at com.ibm.ws.threading.internal.PolicyTaskFutureImpl.get(PolicyTaskFutureImpl.java:586)
	at fat.concurrent.web.EEConcurrencyUtilsFATServlet.testTask1BlockedByTask2LongRunningCompleted(EEConcurrencyUtilsFATServlet.java:461)
	at fat.concurrent.web.EEConcurrencyUtilsFATServlet.invokeTest(EEConcurrencyUtilsFATServlet.java:94)
	at componenttest.app.FATServlet.doGet(FATServlet.java:73)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1255)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:743)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:440)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1154)
	at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:4962)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.handleRequest(DynamicVirtualHost.java:314)
	at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:995)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:279)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:957)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:357)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:316)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:499)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:433)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:313)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.ready(HttpInboundLink.java:284)
	at com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.sendToDiscriminators(NewConnectionInitialReadCallback.java:165)
	at com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.complete(NewConnectionInitialReadCallback.java:74)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:501)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueManager.java:571)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:926)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:1015)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1153)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:785)
". expected:<0> but was:<1>
	at componenttest.topology.utils.HttpUtils.findStringInHttpConnection(HttpUtils.java:527)
	at componenttest.topology.utils.HttpUtils.findStringInHttpConnection(HttpUtils.java:485)
	at componenttest.topology.utils.HttpUtils.findStringInUrl(HttpUtils.java:464)
	at componenttest.topology.utils.HttpUtils.findStringInReadyUrl(HttpUtils.java:436)
	at componenttest.topology.utils.HttpUtils.findStringInReadyUrl(HttpUtils.java:406)
	at componenttest.topology.utils.FATServletClient.runTest(FATServletClient.java:81)
	at com.ibm.ws.concurrent.fat.EEConcurrencyConfigTest.runTest(EEConcurrencyConfigTest.java:60)
	at com.ibm.ws.concurrent.fat.EEConcurrencyConfigTest.testNestedLongRunningPolicy(EEConcurrencyConfigTest.java:489)
	at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:175)
	at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:316)
	at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:152)

**Comment by njr-11** [comment]
Build reported failures in a couple of different tests due to pre-existing issues in componentry that is unrelated to the changes in this pull.
