### ISSUE TITLE
Test Failure: com.ibm.ws.testing.opentracing.test.FATOpentracing.testImmediate

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#10293]
RTC 270522

```
testImmediate:junit.framework.AssertionFailedError: EQ [ Operation ] expected:<[GET:com.ibm.ws.testing.opentracing.service.FATOpentracingService.]getTracerState> but was:<[http://localhost:8010/serviceApp/rest/testService/]getTracerState>
at com.ibm.ws.testing.opentracing.test.FATOpentracing.assertEq(FATOpentracing.java:211)
at com.ibm.ws.testing.opentracing.test.FATOpentracing.verifyTracerStateEvent(FATOpentracing.java:615)
at com.ibm.ws.testing.opentracing.test.FATOpentracing.verifyTracerStateEvent(FATOpentracing.java:597)
at com.ibm.ws.testing.opentracing.test.FATOpentracing.verifyTracerStateEvent(FATOpentracing.java:591)
at com.ibm.ws.testing.opentracing.test.FATOpentracing.testImmediate(FATOpentracing.java:657)
at componenttest.rules.repeater.RepeatTests$CompositeRepeatTestActionStatement.evaluate(RepeatTests.java:115)

```

**Comment by lamkavan** [comment]
After careful analysis by Felix  Wong, the root cause of this issue is caused by a synchronization  problem found within the implementation of opentracing1.x  PR to resolve issue is here https://github.com/OpenLiberty/open-liberty/pull/10442

In the implementation there is 
`protected void activate(ComponentContext context) {
        setContainerFilter();
        setClientFilter();
    }`
and 
`protected void setOpentracingFilterHelper(OpentracingFilterHelper helper) {
        this.helper = helper;
        if (containerFilter != null) {
            containerFilter.setFilterHelper(helper);
        }
        if (clientFilter != null) {
            clientFilter.setFilterHelper(helper);
        }
    }`

These two methods needs to be synchronized such that they do not both run at the same time. If these methods run at the same time it can result in the helper for either the Container or Client filter to be NULL when using MicroProfile OpenTracing.
