### ISSUE TITLE
Missed conversion to annotation caching

### ISSUE THREAD

**Issue by tbitonti** [OpenLiberty/open-liberty#10316]
From SVT logs:

[1/6/20 11:13:05:463 EST] 00000081 tainer.service.annotations.internal.ModuleAnnotationsAdapter 
W Unconverted adapt to module annotations
O java.lang.Throwable: Unconverted adapt to module annotations
O 	at com.ibm.ws.container.service.annotations.internal.ModuleAnnotationsAdapter.adapt(ModuleAnnotationsAdapter.java:76)
O 	at com.ibm.ws.container.service.annotations.internal.ModuleAnnotationsAdapter.adapt(ModuleAnnotationsAdapter.java:31)
O 	at com.ibm.ws.adaptable.module.internal.AdapterFactoryServiceImpl.adapt(AdapterFactoryServiceImpl.java:200)
O 	at com.ibm.ws.adaptable.module.internal.AdaptableContainerImpl.adapt(AdaptableContainerImpl.java:174)
O 	at com.ibm.ws.adaptable.module.internal.InterpretedContainerImpl.adapt(InterpretedContainerImpl.java:203)
O 	at com.ibm.ws.jaxws.ejb.EJBJaxWsModuleInfoBuilder.build(EJBJaxWsModuleInfoBuilder.java:72)
O 	at com.ibm.ws.jaxws.support.JaxWsModuleMetaDataListener.extendModuleMetaData(JaxWsModuleMetaDataListener.java:100)
O 	at com.ibm.ws.app.manager.module.internal.SimpleDeployedAppInfoBase$ModuleContainerInfoBase.createModuleMetaData(SimpleDeployedAppInfoBase.java:190)
O 	at com.ibm.ws.app.manager.module.internal.SimpleDeployedAppInfoBase.preDeployApp(SimpleDeployedAppInfoBase.java:535)
O 	at com.ibm.ws.app.manager.module.internal.SimpleDeployedAppInfoBase.installApp(SimpleDeployedAppInfoBase.java:511)
O 	at com.ibm.ws.app.manager.module.internal.DeployedAppInfoBase.deployApp(DeployedAppInfoBase.java:347)
O 	at com.ibm.ws.app.manager.ear.internal.EARApplicationHandlerImpl.install(EARApplicationHandlerImpl.java:76)
O 	at com.ibm.ws.app.manager.internal.statemachine.StartAction.execute(StartAction.java:140)
O 	at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.enterState(ApplicationStateMachineImpl.java:1266)
O 	at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.run(ApplicationStateMachineImpl.java:881)
O 	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:239)
O 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
O 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
O 	at java.lang.Thread.run(Thread.java:818)

This must be converted to use the annotations beta helper.

**Comment by tbitonti** [comment]
Two versions exist; both must be converted:
open-liberty\dev\com.ibm.ws.jaxws.2.3.ejb\src\com\ibm\ws\jaxws\ejb
EJBJaxWsModuleInfoBuilder.java
open-liberty\dev\com.ibm.ws.jaxws.ejb\src\com\ibm\ws\jaxws\ejb
EJBJaxWsModuleInfoBuilder.java
