### ISSUE TITLE
acmeCA-2.0: Ensure we can run acme_fat tests on zOS

### ISSUE THREAD

**Issue by kristip17** [OpenLiberty/open-liberty#10329]
Make sure we can run our acme tests on zOS with docker.

For our preliminary test, skipping on zOS -- due to previous exceptions on #10330

For #9017 

```
org.testcontainers.containers.ContainerFetchException: Can't get Docker image: RemoteDockerImage(imageName=quay.io/testcontainers/sshd:1.0.0)
at org.testcontainers.containers.GenericContainer.getDockerImageName(GenericContainer.java:1153)
at org.testcontainers.containers.GenericContainer.setDockerImageName(GenericContainer.java:1141)
at org.testcontainers.containers.GenericContainer.<init>(GenericContainer.java:246)
at org.testcontainers.containers.PortForwardingContainer.createSSHSession(PortForwardingContainer.java:32)
at org.testcontainers.containers.PortForwardingContainer.getSshConnection(PortForwardingContainer.java:26)
at org.testcontainers.containers.PortForwardingContainer.exposeHostPort(PortForwardingContainer.java:67)
at org.testcontainers.containers.PortForwardingContainer.exposeHostPort(PortForwardingContainer.java:61)
at org.testcontainers.Testcontainers.exposeHostPorts(Testcontainers.java:15)
at com.ibm.ws.security.acme.FATSuite.beforeClass(FATSuite.java:69)
Caused by: java.lang.IllegalStateException: Could not find a valid Docker environment. Please see logs and check configuration
at org.testcontainers.dockerclient.DockerClientProviderStrategy.lambda$getFirstValidStrategy$3(DockerClientProviderStrategy.java:158)
at org.testcontainers.dockerclient.DockerClientProviderStrategy$$Lambda$21.0000000033300370.get(Unknown Source)
at java.util.Optional.orElseThrow(Optional.java:301)
at org.testcontainers.dockerclient.DockerClientProviderStrategy.getFirstValidStrategy(DockerClientProviderStrategy.java:150)
at org.testcontainers.DockerClientFactory.client(DockerClientFactory.java:111)
at org.testcontainers.images.RemoteDockerImage.resolve(RemoteDockerImage.java:51)
at org.testcontainers.images.RemoteDockerImage.resolve(RemoteDockerImage.java:27)
at org.testcontainers.utility.LazyFuture.getResolvedValue(LazyFuture.java:20)
at org.testcontainers.utility.LazyFuture.get(LazyFuture.java:27)
at org.testcontainers.containers.GenericContainer.getDockerImageName(GenericContainer.java:1151)````

**Comment by kristip17** [comment]
This has been resolved.
