### ISSUE TITLE
Access denied for java.util.PropertyPermission

### ISSUE THREAD

**Issue by AndrewDJBanks** [OpenLiberty/open-liberty#10503]
java.security.AccessControlException: Access denied ("java.util.PropertyPermission" "line.separator" "read")
	at java.base/java.security.AccessController.throwACE(AccessController.java:176)
	at java.base/java.security.AccessController.checkPermissionHelper(AccessController.java:237)
	at java.base/java.security.AccessController.checkPermission(AccessController.java:373)
	at java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:322)
	at java.base/java.lang.SecurityManager.checkPropertyAccess(SecurityManager.java:1066)
	at java.base/java.lang.System.getProperty(System.java:450)
	at java.base/java.lang.System.getProperty(System.java:419)
	at com.ibm.ws.sib.trm.client.Utils.<clinit>(Utils.java:88)

**Comment by AndrewDJBanks** [comment]
See https://github.com/OpenLiberty/open-liberty/pull/10509
