### ISSUE TITLE
Issues tracing when using jdbc properties

### ISSUE THREAD

**Issue by gjwatts** [OpenLiberty/open-liberty#10642]
The JDBC FAT test fails when running in FULL mode during testTrace() in ConfigTest.java when testing against Postgres, Oracle and SQLServer.  (For this test, there is no specific Postgres defined in DataProperties, so for this test it falls under the generic entry.)

The error can be found in the JUnit output.txt file: 

```java.lang.Exception: Trace string could not be found. Expected to find: getDriverMajorVersion()
	at com.ibm.ws.jdbc.fat.tests.ConfigTest.testTrace(ConfigTest.java:1595)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:30)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:47)
	at org.junit.rules.RunRules.evaluate(RunRules.java:18)
	at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:193)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:30)
	at org.testcontainers.containers.FailureDetectingExternalResource$1.evaluate(FailureDetectingExternalResource.java:30)
	at org.junit.rules.RunRules.evaluate(RunRules.java:18)
	at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:314)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:167)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:24)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at junit.framework.JUnit4TestAdapter.run(JUnit4TestAdapter.java:39)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.run(JUnitTestRunner.java:534)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.launch(JUnitTestRunner.java:1196)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.main(JUnitTestRunner.java:1041)
```

Looking in messages.log we can see the trace state changed message was posted, but the corresponding trace data is not showing up in trace.log.

The test can be recreated by running any of these tests:
```
./gradlew com.ibm.ws.jdbc_fat:buildandrun -Dfat.bucket.db.type=Oracle -Dfat.test.mode=FULL -Dfat.test.class.name=com.ibm.ws.jdbc.fat.tests.ConfigTest -Dfat.test.method.name=testTrace

./gradlew com.ibm.ws.jdbc_fat:buildandrun -Dfat.bucket.db.type=Postgres -Dfat.test.mode=FULL -Dfat.test.class.name=com.ibm.ws.jdbc.fat.tests.ConfigTest -Dfat.test.method.name=testTrace

./gradlew com.ibm.ws.jdbc_fat:buildandrun -Dfat.bucket.db.type=SQLServer -Dfat.test.mode=FULL -Dfat.test.class.name=com.ibm.ws.jdbc.fat.tests.ConfigTest -Dfat.test.method.name=testTrace
```

**Comment by KyleAure** [comment]
When we test using database rotation we can test against [Derby, DB2, Oracle, Postgres, and SQLServer].  When we do database rotation testing we remove the `derby.embedded.properties` and substitute in generic `properties` for every database EXCEPT DB2.  If this test is failing for Postgres using generic properties.  Then I would expect that Oracle, and SQLServer would also fail, and DB2 would pass.  If this is the case then really the issue here is tracing when using generic `properties` and not a postgres issue.

**Comment by gjwatts** [comment]
Good call Kyle.  The test does in fact works for DB2 and Derby, but fails for Oracle, Postgres and SQLServer.
