### ISSUE TITLE
Test Failure: com.ibm.ws.request.timing.fat.TimingRequestTiming.testTimingContextInfoConflict

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#10806]
RTC 271903

```
testTimingContextInfoConflict:java.lang.Exception: 2020-01-28-19:42:46:043 Errors/warnings were found in server RequestTimingServer logs:
<br>[1/28/20 19:42:43:634 UTC] 00000038 com.ibm.ws.request.timing.RequestTimingService               E TRAS3300E: The timing configuration associated with PID com.ibm.ws.request.timing.servlet.metatype_30 cannot be read from the configuration.
at componenttest.topology.impl.LibertyServer.checkLogsForErrorsAndWarnings(LibertyServer.java:2541)
at componenttest.topology.impl.LibertyServer.stopServer(LibertyServer.java:2406)
at componenttest.topology.impl.LibertyServer.stopServer(LibertyServer.java:2221)
at componenttest.topology.impl.LibertyServer.stopServer(LibertyServer.java:2196)
at com.ibm.ws.request.timing.fat.TimingRequestTiming.testTimingContextInfoConflict(TimingRequestTiming.java:602)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:193)
at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:314)
at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:167)
at componenttest.rules.repeater.RepeatTests$CompositeRepeatTestActionStatement.evaluate(RepeatTests.java:115)
```

**Comment by fmhwong** [comment]
@leemelim  Can you take a look?

**Comment by leemelim** [comment]
The PR below fixes the test failure:
https://github.com/OpenLiberty/open-liberty/pull/10662
