### ISSUE TITLE
mpReactiveMessaging Kafka connector does not retry connection

### ISSUE THREAD

**Issue by ianpartridge** [OpenLiberty/open-liberty#10937]
**Describe the bug**

The OpenLiberty Kafka connector for MP Reactive Messaging requires that the Kafka connection succeeds on startup. If it does not succeed (for example, if the Kafka is not yet available) it does not retry.

This means that your Open Liberty application is left "up" but "sick", with no way to recover.

**Steps to Reproduce**

0. Do not start Kafka
1. Start an OpenLiberty application with mpReactiveMessaging, attempting to connect to Kafka
2. Observe the connection to Kafka has failed
3. Start up Kafka
4. Observe that OpenLiberty does not retry the connection so it cannot recover from the failure state

**Expected behavior**

Open Liberty should retry the connection, enabling the application to recover.

**Other notes**

Unless I am mistaken, the Kafka connector in Quarkus does support this.  See the `retry` option:

https://smallrye.io/smallrye-reactive-messaging/#_retrieving_messages_from_kafka

**Comment by ianpartridge** [comment]
CC: @matthewpwilson

**Comment by ianpartridge** [comment]
This causes problems when a complete scenario is being deployed on Kubernetes. For example, if you are deploying a `Kafka` CR for Strimzi, and an OpenLiberty microservice as an `AppsodyApplication` CR.

You can’t deploy both at the same time because the OpenLiberty microservice will fail to start up and hang.

**Comment by ianpartridge** [comment]
Any update on this @tevans78 ?

**Comment by Azquelt** [comment]
I tried to reproduce this on Friday by starting liberty without starting Kafka, and it just seemed to sit there waiting forever without producing an error. I'm not sure what's different about this vs. your Kubernetes setup at the moment.

**Comment by ianpartridge** [comment]
> I tried to reproduce this on Friday by starting liberty without starting Kafka, and it just seemed to sit there waiting forever without producing an error.

When you then started Kafka, did Liberty notice that Kafka had appeared and connect to it?

**Comment by Azquelt** [comment]
> When you then started Kafka, did Liberty notice that Kafka had appeared and connect to it?
Yes.

Tested like this: 
* Start liberty
* Go make a cup of tea
* Start kafka
  * I have my test channel configured with `auto.offset.reset=earliest` so my test program immediately receives all the messages on the topic.

Stopping Kafka while liberty is running, waiting a couple of minutes and then starting it again also seems to work fine, with liberty carrying on from where it had got to.

**Comment by Azquelt** [comment]
From your original report:
> Observe the connection to Kafka has failed

How are you doing this? Is there some sort of error printed out or are you just noting that no messages are received?

**Comment by matthewpwilson** [comment]
The error we see in the scenario Ian describes above is:
```
[3/30/20 13:58:24:849 UTC] 00000040 SystemOut                                                    O 2020-03-30 13:58:24 WARN  ClientUtils:74 - Couldn't resolve server my-cluster-kafka-bootstrap.coffeeshop.svc:9092 from bootstrap.servers as DNS resolution failed for my-cluster-kafka-bootstrap.coffeeshop.svc
[3/30/20 13:58:24:854 UTC] 00000040 io.smallrye.reactive.messaging.impl.ConfiguredChannelFactory E Unable to create the publisher or subscriber during initialization
```
This is the failure mode if the k8s service for the Kafka doesn't exist, therefore kubedns does not resolve the domain name.  Full messages.log attached.
[messages-no-kafka.log](https://github.com/OpenLiberty/open-liberty/files/4403357/messages-no-kafka.log)

**Comment by Azquelt** [comment]
Thanks @matthewpwilson I'll have another go and test with an unresolvable name which later becomes resolvable.

**Comment by Azquelt** [comment]
With an unresolvable hostname I get this:
```
com.ibm.ws.microprofile.reactive.messaging.kafka.adapter.KafkaAdapterException: java.lang.reflect.InvocationTargetException
	at com.ibm.ws.microprofile.reactive.messaging.kafka.adapter.KafkaAdapterFactory.getInstance(KafkaAdapterFactory.java:167)
	at com.ibm.ws.microprofile.reactive.messaging.kafka.adapter.KafkaAdapterFactory.getInstance(KafkaAdapterFactory.java:156)
	at com.ibm.ws.microprofile.reactive.messaging.kafka.adapter.KafkaAdapterFactory.newKafkaConsumer(KafkaAdapterFactory.java:95)
	at com.ibm.ws.microprofile.reactive.messaging.kafka.AdapterFactoryImpl$Proxy$_$$_WeldClientProxy.newKafkaConsumer(Unknown Source)
	at com.ibm.ws.microprofile.reactive.messaging.kafka.KafkaIncomingConnector.getPublisherBuilder(KafkaIncomingConnector.java:115)
	at com.ibm.ws.microprofile.reactive.messaging.kafka.KafkaIncomingConnector$Proxy$_$$_WeldClientProxy.getPublisherBuilder(Unknown Source)
	at io.smallrye.reactive.messaging.impl.ConfiguredChannelFactory.createPublisherBuilder(ConfiguredChannelFactory.java:171)
	at io.smallrye.reactive.messaging.impl.ConfiguredChannelFactory.lambda$register$5(ConfiguredChannelFactory.java:149)
	at java.util.HashMap.forEach(HashMap.java:1289)
	at io.smallrye.reactive.messaging.impl.ConfiguredChannelFactory.register(ConfiguredChannelFactory.java:149)
	at io.smallrye.reactive.messaging.impl.ConfiguredChannelFactory.initialize(ConfiguredChannelFactory.java:123)
	at io.smallrye.reactive.messaging.impl.ConfiguredChannelFactory$Proxy$_$$_WeldClientProxy.initialize(Unknown Source)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:647)
	at io.smallrye.reactive.messaging.extension.MediatorManager.initializeAndRun(MediatorManager.java:160)
	at io.smallrye.reactive.messaging.extension.MediatorManager$Proxy$_$$_WeldClientProxy.initializeAndRun(Unknown Source)
	at io.smallrye.reactive.messaging.extension.ReactiveMessagingExtension.afterDeploymentValidation(ReactiveMessagingExtension.java:108)
	at sun.reflect.GeneratedMethodAccessor457.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:95)
	at org.jboss.weld.injection.MethodInvocationStrategy$SpecialParamPlusBeanManagerStrategy.invoke(MethodInvocationStrategy.java:187)
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:330)
	at org.jboss.weld.event.ExtensionObserverMethodImpl.sendEvent(ExtensionObserverMethodImpl.java:123)
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:308)
	at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:286)
	at javax.enterprise.inject.spi.ObserverMethod.notify(ObserverMethod.java:124)
	at org.jboss.weld.util.Observers.notify(Observers.java:166)
	at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:285)
	at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:273)
	at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:177)
	at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:171)
	at org.jboss.weld.bootstrap.events.AbstractContainerEvent.fire(AbstractContainerEvent.java:53)
	at org.jboss.weld.bootstrap.events.AbstractDeploymentContainerEvent.fire(AbstractDeploymentContainerEvent.java:35)
	at org.jboss.weld.bootstrap.events.AfterDeploymentValidationImpl.fire(AfterDeploymentValidationImpl.java:28)
	at org.jboss.weld.bootstrap.WeldStartup.validateBeans(WeldStartup.java:505)
	at org.jboss.weld.bootstrap.WeldBootstrap.validateBeans(WeldBootstrap.java:93)
	at com.ibm.ws.cdi.impl.CDIContainerImpl.startInitialization(CDIContainerImpl.java:157)
	at com.ibm.ws.cdi.liberty.CDIRuntimeImpl.applicationStarting(CDIRuntimeImpl.java:453)
	at com.ibm.ws.container.service.state.internal.ApplicationStateManager.fireStarting(ApplicationStateManager.java:51)
	at com.ibm.ws.container.service.state.internal.StateChangeServiceImpl.fireApplicationStarting(StateChangeServiceImpl.java:50)
	at com.ibm.ws.app.manager.module.internal.SimpleDeployedAppInfoBase.preDeployApp(SimpleDeployedAppInfoBase.java:547)
	at com.ibm.ws.app.manager.module.internal.SimpleDeployedAppInfoBase.installApp(SimpleDeployedAppInfoBase.java:508)
	at com.ibm.ws.app.manager.module.internal.DeployedAppInfoBase.deployApp(DeployedAppInfoBase.java:347)
	at com.ibm.ws.app.manager.war.internal.WARApplicationHandlerImpl.install(WARApplicationHandlerImpl.java:65)
	at com.ibm.ws.app.manager.internal.statemachine.StartAction.execute(StartAction.java:140)
	at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.enterState(ApplicationStateMachineImpl.java:1286)
	at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.run(ApplicationStateMachineImpl.java:884)
	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:239)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedConstructorAccessor827.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.ibm.ws.microprofile.reactive.messaging.kafka.adapter.KafkaAdapterFactory.getInstance(KafkaAdapterFactory.java:165)
	... 51 more
Caused by: org.apache.kafka.common.KafkaException: Failed to construct kafka consumer
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:820)
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:631)
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:612)
	at com.ibm.ws.microprofile.reactive.messaging.kafka.adapter.impl.KafkaConsumerImpl.<init>(KafkaConsumerImpl.java:37)
	... 54 more
Caused by: org.apache.kafka.common.config.ConfigException: No resolvable bootstrap urls given in bootstrap.servers
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:88)
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:47)
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:735)
	... 57 more
```

Looking at what the Kafka client is doing, it does look like it tries to resolve the broker IP address when the `KafkaConsumer` is created and throws an exception if no addresses are resolvable.

It's somewhat annoying that it transparently covers most other connection issues but not this one, but we should be able to change the connector code to warn and retry if the broker hostname isn't immediately available.

I do wonder whether we'll hit issues with Java caching the failed hostname lookup or if kubernetes causes the broker to move and the IP address attached to the hostname to change, but we can cross those bridges when we come to them if they turn out to be an issue.

**Comment by Azquelt** [comment]
I've coded a potential solution whereby if we can't create the KafkaConsumer, we allow the app to start and retry the connection in the background until it connects and then we start consuming messages.

However, I've realised this comes with a number of downsides.

Kafka reports this error as a `ConfigException` - i.e. your config is broken. This is the same exception you'd get if you forgot `bootstrap.servers` altogether or your config hasn't loaded for some other reason.

That means we can't just retry on this exception without also retrying on things that should be a fatal exception and require the end user to modify their application or config.

Secondly, the current behaviour prevents the app from starting, which for a fatal exception is desirable. My workaround allows the app to start but keeps retrying the kafka connection in the background until it's able to connect.

In a dynamic environment like kubernetes, if the app fails to start, the pod should be considered unhealthy and be restarted anyway, which would get around the immediate problem, even if it takes longer than we'd like.

Therefore, I propose a slightly different solution:
* If the `KafkaConnector` can't be started, we wait and retry the connection for a limited time (say 30 seconds)
* If the connector doesn't connect in this time, we throw an exception as before and the app fails to start

On your end, you need to ensure that if the application doesn't start, then your pod is considered unhealthy and gets restarted.

**Comment by matthewpwilson** [comment]
Thanks @Azquelt.  I hadn't really clocked that the application fails to start, and I agree this seems to be the right behaviour in the general case.  However, a liveness check doesn't help here as it reports UP even when an app fails to start (see also #11722 re behaviour of readiness check when app doesn't start).  If the app isn't there to report DOWN then the server will report a status of UP.  Perhaps you could have an opt-in on the retry in the same way the smallrye-kafka connector does?

**Comment by Azquelt** [comment]
I think we could have an opt-in retry, as long as it happens during application start-up so the app doesn't report as started until the name resolves.

I assume that would be preferable to the app container failing the first startup every time you bring up the deployment anyway.
