### ISSUE TITLE
Test Failure (20171127-0525): EEConcurrencyConfigTest.testPolicyRef tasks canceled due to config update

### ISSUE THREAD

**Issue by njr-11** [OpenLiberty/open-liberty#1120]
Test Failure (20171127-0525): com.ibm.ws.concurrent.fat.EEConcurrencyConfigTest.testPolicyRef

junit.framework.AssertionFailedError: 2017-11-27-09:57:05:385 The response did not contain "[SUCCESS]".  Full output is:"
ERROR: Caught exception attempting to call test method testTask1BlockedByTask2Completed on servlet fat.concurrent.web.EEConcurrencyUtilsFATServlet
java.util.concurrent.CancellationException
	at com.ibm.ws.threading.internal.PolicyTaskFutureImpl.get(PolicyTaskFutureImpl.java:587)
	at fat.concurrent.web.EEConcurrencyUtilsFATServlet.testTask1BlockedByTask2Completed(EEConcurrencyUtilsFATServlet.java:403)
	at fat.concurrent.web.EEConcurrencyUtilsFATServlet.invokeTest(EEConcurrencyUtilsFATServlet.java:94)
	at componenttest.app.FATServlet.doGet(FATServlet.java:73)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1255)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:743)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:440)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1154)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1004)
	at com.ibm.ws.webcontainer.servlet.CacheServletWrapper.handleRequest(CacheServletWrapper.java:76)
	at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:926)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:279)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:957)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:357)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:316)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:499)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:433)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:313)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.ready(HttpInboundLink.java:284)
	at com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.sendToDiscriminators(NewConnectionInitialReadCallback.java:165)
	at com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.complete(NewConnectionInitialReadCallback.java:74)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:501)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueManager.java:571)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:926)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:1015)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1157)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:627)
	at java.lang.Thread.run(Thread.java:809)
". expected:<0> but was:<1>
	at componenttest.topology.utils.HttpUtils.findStringInHttpConnection(HttpUtils.java:527)
	at componenttest.topology.utils.HttpUtils.findStringInHttpConnection(HttpUtils.java:485)
	at componenttest.topology.utils.HttpUtils.findStringInUrl(HttpUtils.java:464)
	at componenttest.topology.utils.HttpUtils.findStringInReadyUrl(HttpUtils.java:436)
	at componenttest.topology.utils.HttpUtils.findStringInReadyUrl(HttpUtils.java:406)
	at componenttest.topology.utils.FATServletClient.runTest(FATServletClient.java:81)
	at com.ibm.ws.concurrent.fat.EEConcurrencyConfigTest.runTest(EEConcurrencyConfigTest.java:60)
	at com.ibm.ws.concurrent.fat.EEConcurrencyConfigTest.testPolicyRef(EEConcurrencyConfigTest.java:543)
	at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:175)
	at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:316)
	at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:152)

In the logs, we see the cause is an unexpected deactivate/activate rather than the modified method being used,
[com.ibm.ws.concurrent.internal.ManagedExecutorServiceImpl(266)] Cannot dynamically update the configuration due to dependency changes induced on dependency ConcurrencyPolicy
[com.ibm.ws.concurrent.internal.ManagedExecutorServiceImpl(266)] Deactivating and Activating to reconfigure from configuration

The configuration update switches from 
`<managedExecutorService id="execSvc1" jndiName="concurrent/execSvc1" concurrencyPolicyRef="**normalPolicy**"/>`
to
`<managedExecutorService id="execSvc1" jndiName="concurrent/execSvc1" concurrencyPolicyRef="**policy1**"/>`

Here is how we are currently defining the dependency,
`    @Reference(policy = ReferencePolicy.DYNAMIC, target = "(id=unbound)")
    protected void setConcurrencyPolicy(ConcurrencyPolicy svc) {`

`  <AD id="concurrencyPolicyRef"                  type="String"  ibm:type="pid" ibm:reference="com.ibm.ws.concurrency.policy.concurrencyPolicy" default="defaultConcurrencyPolicy" cardinality="1"`

`  <AD id="ConcurrencyPolicy.target"              type="String"  ibm:final="true" default="(service.pid=${concurrencyPolicyRef})"`

**Comment by njr-11** [comment]
After discussing with Brent, it seems the current design for DS doesn't guarantee ordering of config updates such that dependencies will remain resolvable.  When the update to add policy1 happens before the update to set concurrencyPolicyRef=policy1, then the test runs cleanly.  When the updates happen in reverse order, the test fails because the service component for the managed executor needs to deactivate until the policy1 dependency becomes available.  This is what forces the deactivate/activate, leading to canceled tasks, which cause the test failure.  Given that this is how declarative services is designed, the test needs to be updated to align with that design.  It could be switched back at some future point if declarative services is ever enhanced.
