### ISSUE TITLE
Provide meaningful error messages for MP Reactive Messaging

### ISSUE THREAD

**Issue by aguibert** [OpenLiberty/open-liberty#11274]
**Is your feature request related to a problem? Please describe.**
If I deploy a MP reactive messaging app in Liberty and something goes wrong, I get these very generic lines in my console.log:
```
[ERROR   ] Unable to create the publisher or subscriber during initialization
java.lang.reflect.InvocationTargetException
[ERROR   ] CWWKZ0002E: An exception occurred while starting the application kitchen. The exception message was: com.ibm.ws.container.service.state.StateChangeException: org.jboss.weld.exceptions.DeploymentException
[AUDIT   ] CWWKF0012I: The server installed the following features: [cdi-2.0, concurrent-1.0, jaxrs-2.1, jaxrsClient-2.1, jndi-1.0, json-1.0, jsonb-1.0, jsonp-1.1, mpConfig-1.3, mpHealth-2.1, mpReactiveMessaging-1.0, mpReactiveStreams-1.0, servlet-4.0].
```

This gets even worse when running in a Docker container (in production or using MicroShed Testing). When I dug out the stack trace for this particular error message, I get the full stack trace:
```
[3/11/20 20:43:25:614 GMT] 0000002c io.smallrye.reactive.messaging.impl.ConfiguredChannelFactory E Unable to create the publisher or subscriber during initialization
com.ibm.ws.microprofile.reactive.messaging.kafka.adapter.KafkaAdapterException: java.lang.reflect.InvocationTargetException
	at com.ibm.ws.microprofile.reactive.messaging.kafka.adapter.KafkaAdapterFactory.getInstance(KafkaAdapterFactory.java:167)
	at com.ibm.ws.microprofile.reactive.messaging.kafka.adapter.KafkaAdapterFactory.getInstance(KafkaAdapterFactory.java:156)
	at com.ibm.ws.microprofile.reactive.messaging.kafka.adapter.KafkaAdapterFactory.newKafkaConsumer(KafkaAdapterFactory.java:95)
	at com.ibm.ws.microprofile.reactive.messaging.kafka.AdapterFactoryImpl$Proxy$_$$_WeldClientProxy.newKafkaConsumer(Unknown Source)
	at com.ibm.ws.microprofile.reactive.messaging.kafka.KafkaIncomingConnector.getPublisherBuilder(KafkaIncomingConnector.java:115)
	at com.ibm.ws.microprofile.reactive.messaging.kafka.KafkaIncomingConnector$Proxy$_$$_WeldClientProxy.getPublisherBuilder(Unknown Source)
	at io.smallrye.reactive.messaging.impl.ConfiguredChannelFactory.createPublisherBuilder(ConfiguredChannelFactory.java:145)
	at io.smallrye.reactive.messaging.impl.ConfiguredChannelFactory.lambda$register$4(ConfiguredChannelFactory.java:123)
	at io.smallrye.reactive.messaging.impl.ConfiguredChannelFactory$$Lambda$100/00000000F86FECB0.accept(Unknown Source)
	at java.util.HashMap.forEach(HashMap.java:1289)
	at io.smallrye.reactive.messaging.impl.ConfiguredChannelFactory.register(ConfiguredChannelFactory.java:123)
	at io.smallrye.reactive.messaging.impl.ConfiguredChannelFactory.initialize(ConfiguredChannelFactory.java:118)
	at io.smallrye.reactive.messaging.impl.ConfiguredChannelFactory$Proxy$_$$_WeldClientProxy.initialize(Unknown Source)
	at io.smallrye.reactive.messaging.extension.MediatorManager$$Lambda$98/00000000F86FE500.accept(Unknown Source)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:647)
	at io.smallrye.reactive.messaging.extension.MediatorManager.initializeAndRun(MediatorManager.java:132)
	at io.smallrye.reactive.messaging.extension.MediatorManager$Proxy$_$$_WeldClientProxy.initializeAndRun(Unknown Source)
	at io.smallrye.reactive.messaging.extension.ReactiveMessagingExtension.afterDeploymentValidation(ReactiveMessagingExtension.java:86)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:95)
	at org.jboss.weld.injection.MethodInvocationStrategy$SpecialParamPlusBeanManagerStrategy.invoke(MethodInvocationStrategy.java:187)
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:330)
	at org.jboss.weld.event.ExtensionObserverMethodImpl.sendEvent(ExtensionObserverMethodImpl.java:123)
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:308)
	at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:286)
	at javax.enterprise.inject.spi.ObserverMethod.notify(ObserverMethod.java:124)
	at org.jboss.weld.util.Observers.notify(Observers.java:166)
	at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:285)
	at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:273)
	at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:177)
	at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:171)
	at org.jboss.weld.bootstrap.events.AbstractContainerEvent.fire(AbstractContainerEvent.java:53)
	at org.jboss.weld.bootstrap.events.AbstractDeploymentContainerEvent.fire(AbstractDeploymentContainerEvent.java:35)
	at org.jboss.weld.bootstrap.events.AfterDeploymentValidationImpl.fire(AfterDeploymentValidationImpl.java:28)
	at org.jboss.weld.bootstrap.WeldStartup.validateBeans(WeldStartup.java:505)
	at org.jboss.weld.bootstrap.WeldBootstrap.validateBeans(WeldBootstrap.java:93)
	at com.ibm.ws.cdi.impl.CDIContainerImpl.startInitialization(CDIContainerImpl.java:157)
	at com.ibm.ws.cdi.liberty.CDIRuntimeImpl.applicationStarting(CDIRuntimeImpl.java:453)
	at com.ibm.ws.container.service.state.internal.ApplicationStateManager.fireStarting(ApplicationStateManager.java:51)
	at com.ibm.ws.container.service.state.internal.StateChangeServiceImpl.fireApplicationStarting(StateChangeServiceImpl.java:50)
	at com.ibm.ws.app.manager.module.internal.SimpleDeployedAppInfoBase.preDeployApp(SimpleDeployedAppInfoBase.java:550)
	at com.ibm.ws.app.manager.module.internal.SimpleDeployedAppInfoBase.installApp(SimpleDeployedAppInfoBase.java:511)
	at com.ibm.ws.app.manager.module.internal.DeployedAppInfoBase.deployApp(DeployedAppInfoBase.java:347)
	at com.ibm.ws.app.manager.war.internal.WARApplicationHandlerImpl.install(WARApplicationHandlerImpl.java:65)
	at com.ibm.ws.app.manager.internal.statemachine.StartAction.execute(StartAction.java:140)
	at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.enterState(ApplicationStateMachineImpl.java:1264)
	at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.run(ApplicationStateMachineImpl.java:879)
	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:239)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:821)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.ibm.ws.microprofile.reactive.messaging.kafka.adapter.KafkaAdapterFactory.getInstance(KafkaAdapterFactory.java:165)
	... 55 more
Caused by: org.apache.kafka.common.KafkaException: Failed to construct kafka consumer
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:820)
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:631)
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:612)
	at com.ibm.ws.microprofile.reactive.messaging.kafka.adapter.impl.KafkaConsumerImpl.<init>(KafkaConsumerImpl.java:37)
	... 60 more
Caused by: org.apache.kafka.common.config.ConfigException: No resolvable bootstrap urls given in bootstrap.servers
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:88)
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:47)
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:735)
	... 63 more
```

**Describe the solution you'd like**
I would like the root message of the InvocationTargetException to be surfaced in console.log

**Describe alternatives you've considered**
1. Don't ever mess up writing a MP Reactive Messaging app ;)
2. Design issue for disabling stack trace hiding in STDOUT: https://github.com/OpenLiberty/open-liberty/issues/10904

**Comment by Azquelt** [comment]
Looks like we should at least remove `InvocationTargetException` from the stack.

We might also need to consider making `KafkaAdapterException` smarter about how it constructs its message.

**Comment by Azquelt** [comment]
Not quite sure what the best way to do this is.

The message in the console.log appears to just be the message of the first exception.

The last exception in the stack is the only one with enough information to tell the user how to fix the issue.

`InvocationTargetException` is basically just noise, but if we took that out then you'd just get `org.apache.kafka.common.KafkaException: Failed to construct kafka consumer` which is more useful but not by much.

So we would need to walk through the whole cause list to construct the message for `KafkaAdaptorException`, which isn't too bad, but means that when you get the whole stack trace printed out, you get a lot of noise.

@aguibert What do you think is the better trade-off here. Keep the stack trace clean and clear (as it mostly is at the moment) so that it's easy to follow in messages.log or stuff all the causal exceptions into the message of `KafkaAdaptorException` so you get something out in console.log?

**Comment by Azquelt** [comment]
I note that we also need to introduce another exception in `KafkaIncomingConnector.getPublisherBuilder(Config)` to identify which channel we failed to create a connector for.

**Comment by aguibert** [comment]
perhaps as a compromise we can chain only the caused by messages instead of the the entire stack traces?

I know EJB container does this currently, basically whenever they wrap an exception they do:
```java
} catch (Exception e) {
  new FooException("Failure to do <blah> because of: " + e.getMessage(), e);
}
```

If many exceptions are chained like this it does end up looking a bit odd:
```
Failure to do <blah> because of: <foo> because of: <bar> because of: <baz>
```
but at least all of the information messages are there.

**Comment by Azquelt** [comment]
The last two exceptions aren't ours, they're from the Kafka client and they don't follow that pattern, so naively the message would end with `Failed to construct kafka consumer` which still isn't very helpful.

However, if we assume that all Kafka exceptions are going to need us to walk the exception cause chain to create an exception message, then we can do that in `KafkaAdapterException`.

Hopefully we can get something like
```
[ERROR   ] Unable to create the publisher or subscriber during initialization
Could not create Kafka incoming connector for the foobar channel because of: Failed to construct kafka consumer because of: No resolvable bootstrap urls given in bootstrap.servers
```

I'm a little torn over whether to include the exception class name or not. At the moment I think I'll go with not because in this instance the exception messages make sense on their own. In the worst case we might get a confusing message if the exception message doesn't make sense without the context of the exception type and the user will have to look at the stack trace in messages.log.

**Comment by aguibert** [comment]
I'm leaning towards including the exception type to cover the worst case scenario you mentioned. I think including the exception types also helps delimit multiple messages more clearly so the user knows we really are just chaining together a bunch of exception messages (which might be helpful in the event stitching together the exception messages looks odd)
