### ISSUE TITLE
Internal Jsonb feature exposes Jsonb service to Application Classloader

### ISSUE THREAD

**Issue by WhiteCat22** [OpenLiberty/open-liberty#1128]
Found while creating a jaxrs-2.1 test case packaging my own jsonb impl inside my war file. Jaxrs-2.1 uses the internal jsonb feature and should not expose the jsonb api to the application classloader, however, when I package my own jsonb impl and api jars I get the following error:

Stack Dump = java.util.ServiceConfigurationError: javax.json.bind.spi.JsonbProvider: Provider org.eclipse.yasson.JsonBindingProvider not a subtype
	at java.util.ServiceLoader.fail(ServiceLoader.java:250)
	at java.util.ServiceLoader.access$300(ServiceLoader.java:196)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:387)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:415)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:491)
	at javax.json.bind.spi.JsonbProvider.provider(JsonbProvider.java:113)
	at javax.json.bind.JsonbBuilder.create(JsonbBuilder.java:108)
	at jaxrs21.fat.jsonb.MyJsonBProvider.<init>(MyJsonBProvider.java:35)
	at jaxrs21.fat.jsonb.JsonBPOJOApplication.getSingletons(JsonBPOJOApplication.java:43)
	at com.ibm.ws.jaxrs20.server.LibertyJaxRsServerFactoryBean.updateEndpointInfo(LibertyJaxRsServerFactoryBean.java:370)
	at com.ibm.ws.jaxrs20.server.LibertyJaxRsServerFactoryBean.onApplicationInit(LibertyJaxRsServerFactoryBean.java:180)
	at com.ibm.ws.jaxrs20.server.LibertyJaxRsServerFactoryBean.doInit(LibertyJaxRsServerFactoryBean.java:263)
	at com.ibm.ws.jaxrs20.server.JaxRsWebEndpointImpl.init(JaxRsWebEndpointImpl.java:66)
	at com.ibm.websphere.jaxrs.server.IBMRestServlet.init(IBMRestServlet.java:64)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.init(ServletWrapper.java:297)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:598)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:440)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1154)
	at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:4962)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.handleRequest(DynamicVirtualHost.java:314)
	at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:995)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:279)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:957)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:357)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:316)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:499)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:433)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:313)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.ready(HttpInboundLink.java:284)
	at com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.sendToDiscriminators(NewConnectionInitialReadCallback.java:165)
	at com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.complete(NewConnectionInitialReadCallback.java:74)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:501)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueManager.java:571)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:926)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:1015)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1153)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:785)

**Comment by WhiteCat22** [comment]
[jsonbapp.zip](https://github.com/OpenLiberty/open-liberty/files/1515698/jsonbapp.zip)

To reproduce run the attached app and send a GET request to: http://localhost:9080/jsonbapp/pojo/person/person

**Comment by aguibert** [comment]
@WhiteCat22 I've just merged in the fix for this issue in PR #1178 
Can you please confirm this fixes the issue?

**Comment by WhiteCat22** [comment]
I was able to test that this fixes the issue.
