### ISSUE TITLE
NullPointerException thrown from liberty logging component

### ISSUE THREAD

**Issue by lmsurpre** [OpenLiberty/open-liberty#11287]
**Describe the bug**
```
An unexpected exception occurred while processing the request
java.lang.NullPointerException
	at com.ibm.ws.logging.collector.CollectorJsonHelpers.addUnchangingFieldsJSON_Message(CollectorJsonHelpers.java:239)
	at com.ibm.ws.logging.collector.CollectorJsonHelpers.startMessageJsonFields(CollectorJsonHelpers.java:559)
	at com.ibm.ws.logging.collector.CollectorJsonUtils_JSON.jsonifyTraceAndMessage(CollectorJsonUtils_JSON.java:279)
	at com.ibm.ws.logging.collector.CollectorJsonUtils_JSON.jsonifyEvent(CollectorJsonUtils_JSON.java:67)
	at com.ibm.ws.logging.collector.CollectorJsonUtils.jsonifyEvent(CollectorJsonUtils.java:59)
	at com.ibm.ws.logging.internal.impl.JsonLogHandler.formatEvent(JsonLogHandler.java:162)
	at com.ibm.ws.logging.internal.impl.ConsoleLogHandler.synchronousWrite(ConsoleLogHandler.java:106)
	at com.ibm.ws.collector.manager.buffer.BufferManagerImpl.add(BufferManagerImpl.java:108)
	at com.ibm.ws.logging.source.LogSource.publish(LogSource.java:106)
	at com.ibm.ws.logging.internal.impl.BaseTraceService.publishToLogSource(BaseTraceService.java:1138)
	at com.ibm.ws.logging.internal.impl.BaseTraceService.publishLogRecord(BaseTraceService.java:1117)
	at com.ibm.ws.logging.internal.impl.BaseTraceService$2.publish(BaseTraceService.java:283)
	at java.util.logging.Logger.log(Logger.java:749)
	at com.ibm.ws.logging.internal.WsLogger.log(WsLogger.java:140)
	at com.ibm.ws.logging.internal.WsLogger.log(WsLogger.java:264)
	at com.ibm.ws.logging.internal.WsLogger.info(WsLogger.java:509)
	at com.ibm.fhir.server.util.FHIRRestHelper.logBundleRequestCompletedMsg(FHIRRestHelper.java:2122)
	at com.ibm.fhir.server.util.FHIRRestHelper.setBundleResponseFields(FHIRRestHelper.java:2108)
	at com.ibm.fhir.server.util.FHIRRestHelper.processEntriesForMethod(FHIRRestHelper.java:1734)
	at com.ibm.fhir.server.util.FHIRRestHelper.processBundleEntries(FHIRRestHelper.java:1421)
	at com.ibm.fhir.server.util.FHIRRestHelper.doBundle(FHIRRestHelper.java:1016)
	at com.ibm.fhir.server.resources.Batch.bundle(Batch.java:64)
	at sun.reflect.GeneratedMethodAccessor132.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at com.ibm.ws.jaxrs20.server.LibertyJaxRsServerFactoryBean.performInvocation(LibertyJaxRsServerFactoryBean.java:656)
	at com.ibm.ws.jaxrs20.server.LibertyJaxRsInvoker.performInvocation(LibertyJaxRsInvoker.java:160)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
	at com.ibm.ws.jaxrs20.server.LibertyJaxRsInvoker.invoke(LibertyJaxRsInvoker.java:273)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:205)
	at com.ibm.ws.jaxrs20.server.LibertyJaxRsInvoker.invoke(LibertyJaxRsInvoker.java:444)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:111)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:61)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:99)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:124)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:274)
	at com.ibm.ws.jaxrs20.endpoint.AbstractJaxRsWebEndpoint.invoke(AbstractJaxRsWebEndpoint.java:134)
	at com.ibm.websphere.jaxrs.server.IBMRestServlet.handleRequest(IBMRestServlet.java:146)
	at com.ibm.websphere.jaxrs.server.IBMRestServlet.doPost(IBMRestServlet.java:104)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:706)
	at com.ibm.websphere.jaxrs.server.IBMRestServlet.service(IBMRestServlet.java:96)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1225)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:729)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:426)
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.invokeTarget(WebAppFilterChain.java:182)
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:93)
	at com.ibm.fhir.server.filter.rest.FHIRRestServletFilter.doFilter(FHIRRestServletFilter.java:138)
	at javax.servlet.http.HttpFilter.doFilter(HttpFilter.java:127)
	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:201)
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:90)
	at com.ibm.fhir.server.filter.rest.FHIRRestAuthorizationServletFilter.doFilter(FHIRRestAuthorizationServletFilter.java:86)
	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:201)
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:90)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.doFilter(WebAppFilterManager.java:1001)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1139)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1010)
	at com.ibm.ws.webcontainer.servlet.CacheServletWrapper.handleRequest(CacheServletWrapper.java:75)
	at com.ibm.ws.webcontainer40.servlet.CacheServletWrapper40.handleRequest(CacheServletWrapper40.java:83)
	at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:938)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:279)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1134)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:415)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:374)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:548)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:482)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:347)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.ready(HttpInboundLink.java:318)
	at com.ibm.ws.channel.ssl.internal.SSLConnectionLink.determineNextChannel(SSLConnectionLink.java:1077)
	at com.ibm.ws.channel.ssl.internal.SSLConnectionLink$MyReadCompletedCallback.complete(SSLConnectionLink.java:656)
	at com.ibm.ws.channel.ssl.internal.SSLReadServiceContext$SSLReadCompletedCallback.complete(SSLReadServiceContext.java:1803)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:504)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueManager.java:574)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:958)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:1047)
	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:239)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:820)
```

**Steps to Reproduce**
Hard to reproduce.  I only saw it once while running a performance test against our application thats running in IBM Cloud Kubernetes Service (IKS).

**Expected behavior**
The liberty logging system should never throw a NullPointerException

**Diagnostic information:**
 - Liberty Version: 20.0.0.2
 - Java Version: 
```
java version "1.8.0_241"
Java(TM) SE Runtime Environment (build 8.0.6.6 - pxa6480sr6fp6-20200213_01(SR6 FP6))
IBM J9 VM (build 2.9, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20200124_438197 (JIT enabled, AOT enabled)
OpenJ9   - 6754bf2
OMR      - dca2cde
IBM      - 5cc5f54)
JCL - 20200210_01 based on Oracle jdk8u241-b07
```
 - server.xml configuration (WITHOUT sensitive information like passwords):
```
<server description="fhir-server">

    <!-- Enable features -->
    <featureManager>
        <feature>appSecurity-2.0</feature>
        <feature>batchManagement-1.0</feature>
        <feature>jaxrs-2.1</feature>
        <!-- the db2 jcc driver for 11.5.0.0 doesn't fully implement jdbc-4.2 -->
        <feature>jdbc-4.1</feature>
        <feature>jsonp-1.1</feature>
        <feature>mpOpenAPI-1.0</feature>
        <feature>openidConnectServer-1.0</feature>
        <feature>servlet-4.0</feature>
        <feature>transportSecurity-1.0</feature>    
        <feature>websocket-1.1</feature>
    </featureManager>

    <!-- Disable welcome page so that internal server info won't be revealed in responses
         to requests with an invalid context root.
    -->
    <httpDispatcher enableWelcomePage="false" />
    <!-- Disable X-Powered-By header to avoid leaking information and
         override the default error pages to avoid showing stack traces
         for nonsensical queries like requests for a JSP page that doesn't exist.
    -->
    <webContainer disableXPoweredBy="true" 
        displaytextwhennoerrorpagedefined="Unexpected request/response. Please check the URL and try again."
        deferServletLoad="false" />

    <!-- IBM FHIR Server's keystore and truststore configuration -->
    <ssl id="defaultSSLConfig" keyStoreRef="defaultKeyStore" trustStoreRef="defaultTrustStore" clientAuthenticationSupported="true" />
    <keyStore id="defaultKeyStore" location="${server.config.dir}/resources/security/fhirKeystore.jks" password="change-password"/>
    <keyStore id="defaultTrustStore" location="${server.config.dir}/resources/security/fhirTruststore.jks" password="change-password"/>
    <webAppSecurity allowFailOverToBasicAuth="true" singleSignonEnabled="false"/>

    <!-- Define a basic user registry with a few users. -->
    <basicRegistry id="basic" realm="BasicRealm"> 
        <user name="fhiruser" password="change-password"/>
        <user name="fhiradmin" password="change-password"/>
        <group name="FHIRUsers">
            <member name="fhiruser"/>
        </group>
        <group name="clientAdministrator">
            <member name="fhiruser"/>
        </group>
    </basicRegistry>

    <authorization-roles id="com.ibm.ws.batch">
        <security-role name="batchAdmin">
            <user name="fhiradmin" />
        </security-role>
        <security-role name="batchSubmitter">
            <user name="fhiruser" />
        </security-role>
        <security-role name="batchMonitor">
            <user name="fhiradmin" />
            <user name="fhiruser" />
        </security-role>
    </authorization-roles>
    
    <!-- This entry defines the ports that the server will listen on.
        By default, the httpPort is disabled (set to "-1").
        Modify the port #'s as needed to satisfy your config requirements.
        Note: on Linux, the server must be running with root priviledges in order to
        listen on ports <= 1024.
     -->
    <httpEndpoint id="defaultHttpEndpoint" host="*" httpPort="-1" httpsPort="9443" onError="FAIL"/>
    
    <!-- Automatically expand WAR files and EAR files -->
    <applicationManager autoExpand="true"/>

    <applicationMonitor updateTrigger="mbean"/>

    <!-- This is the main IBM FHIR Server REST API war -->
    <webApplication contextRoot="fhir-server/api/v4" id="fhir-server-webapp" location="fhir-server.war" name="fhir-server-webapp">
        <classloader commonLibraryRef="fhirSharedLib" privateLibraryRef="configResources,fhirUserLib"/>
        <!-- Include id attributes to make it easier to override this via dropinConfig -->
        <application-bnd id="binding">
            <security-role id="users" name="FHIRUsers">
                <group name="FHIRUsers"/>
            </security-role>
        </application-bnd>
    </webApplication>

    <!-- 
        This library element puts a specific directory in the classpath so that it can be used
        for user-provided configuration files (e.g. extension-search-parameters.xml)
    -->
    <library id="configResources">
        <folder dir="${server.config.dir}/config"/>
        <fileset dir="${server.config.dir}/config" includes="*.jar"/>
    </library>
    
    <!-- 
        This sharedlib can contain user-contributed jars that are intended to augment
        the IBM FHIR Server installation (persistence interceptors, persistence layer impl's,
        custom operation impl's, etc.)
     -->
    <library id="fhirUserLib">
        <fileset dir="${server.config.dir}/userlib" includes="*.jar"/>
    </library>
   
    <!-- Definitions related to the JDBC proxy datasource -->
    <library id="fhirSharedLib">
        <fileset dir="${shared.resource.dir}/lib/derby" includes="*.jar"/>
        <fileset dir="${shared.resource.dir}/lib/db2" includes="*.jar"/>
        <fileset dir="${shared.resource.dir}/lib/fhir" includes="*.jar"/>
    </library>
    
    <dataSource id="fhirProxyDataSource" jndiName="jdbc/fhirProxyDataSource"
        type="javax.sql.XADataSource">
        <jdbcDriver libraryRef="fhirSharedLib"
            javax.sql.XADataSource="com.ibm.fhir.persistence.proxy.FHIRProxyXADataSource" />
        <connectionManager />
    </dataSource>
</server>
```
configDroping:
```
<server>
    <!-- use the default java cacerts as trustStore (for db2 on cloud) -->
    <sslDefault sslRef="cloudSSLConfig"/>
    <ssl id="cloudSSLConfig" keyStoreRef="defaultKeyStore" trustStoreRef="javaTrustStore"/>
    <keyStore id="javaTrustStore" type="JKS" location="${java.home}/lib/security/cacerts"/>

    <!-- webApp security is provided via IAM in IBM Cloud -->
    <webAppSecurity singleSignonEnabled="false" useAuthenticationDataForUnprotectedResource="false"/>
    <webApplication id="fhir-server-webapp">
        <application-bnd id="binding">
            <security-role id="users" name="FHIRUsers">
                <special-subject type="EVERYONE"/>
            </security-role>
        </application-bnd>
    </webApplication>

    <logging traceSpecification="${env.TRACE_SPEC}" traceFileName="stdout" isoDateFormat="true"/>

    <!-- set statementCacheSize, syncQueryTimeoutWithTransactionTimeout, pool size, and timeouts -->
    <dataSource id="fhirProxyDataSource" jndiName="jdbc/fhirProxyDataSource" type="javax.sql.XADataSource" statementCacheSize="100" syncQueryTimeoutWithTransactionTimeout="true">
        <jdbcDriver libraryRef="fhirSharedLib" javax.sql.XADataSource="com.ibm.fhir.persistence.proxy.FHIRProxyXADataSource"/>
        <connectionManager maxPoolSize="400" minPoolSize="20" connectionTimeout="60s" maxIdleTime="2m"/>
    </dataSource>

    <!-- temporary test for performance -->
    <executor name="LargeThreadPool" id="default" coreThreads="40" maxThreads="40" />

    <!-- temporary test for performance -->
    <httpEndpoint id="defaultHttpEndpoint" host="*" httpPort="-1" httpsPort="9443" onError="FAIL">
        <httpOptions maxKeepAliveRequests="-1" persistTimeout="120s" purgeDataDuringClose="true"/>
        <accessLogging logFormat='%h %i %u %t "%r" %s %b'/>
    </httpEndpoint>

    <remoteIp useRemoteIpInAccessLog="true"/>
</server>
```

 - If it would be useful, upload the messages.log file found in `$WLP_OUTPUT_DIR/messages.log`
N/A, logs are streamed to LogDNA

**Additional context**
We have JSON logging enabled with a couple field-maps, so I'm wondering if it could be related to #10707

**Comment by Yushan-Lin** [comment]
This problem will be fixed in 20.0.0.4
