### ISSUE TITLE
Ignore "CWWKE0701E" in com.ibm.ws.fat.wc.tests.WCSameSiteCookieAttributeTests

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#11313]
The `testSameSiteConfig_Lax_WebAppSecurity_Strict()` configures a new server.xml to add the `appSecurity-2.0` feature and adds an application element with some additional configuration for the test.

The test executes and then the test reverts back to the original server.xml. The ssl code doesn't do anything with this IllegalStateException:

`com.ibm.ws.ssl.internal.KeystoreConfigurationFactory.update`:
```
 } catch (IllegalStateException e) {
            // This must mean the bundle was stopped, which happens only if
            // we're trying to update and shut down simultaneously.
            // Harmless, so discard the exception rather than report FFDC.
 }
```
It looks as though it still ends up being logged in the `messages.log` and therefore the test framework fails the test because it has an exception in the logs. We should ignore this exception in the test when the test is stopped.

> A CWWKG0016I: Starting server configuration update.
> 
> CWWKF0007I: Feature update started.
> 
> CWWKZ0009I: The application SameSiteTest has stopped successfully.
> SRVE0253I: [SameSiteSecurityTest] [/SameSiteSecurityTest] 
> CWWKZ0009I: The application SameSiteSecurityTest has stopped successfully.
> CWWKS1124I: The collective authentication plugin with class name NullCollectiveAuthenticationPlugin has been deactivated. 

> CWPKI0819I: The default keystore is not created because a password is not configured on the <keyStore id="defaultKeyStore"/> element, and the 'keystore_password' environment variable is not set. 
> CWWKE0701E: FrameworkEvent ERROR java.lang.IllegalStateException: BundleContext is no longer valid
> 	at org.eclipse.osgi.internal.framework.BundleContextImpl.checkValid(BundleContextImpl.java:1055)
> 	at org.eclipse.osgi.internal.framework.BundleContextImpl.ungetService(BundleContextImpl.java:726)
> 	at org.apache.felix.scr.impl.manager.SingleRefPair.ungetServiceObjects(SingleRefPair.java:72)
> 	at org.apache.felix.scr.impl.manager.DependencyManager$AbstractCustomizer.ungetService(DependencyManager.java:226)
> 	at org.apache.felix.scr.impl.manager.DependencyManager$MultipleDynamicCustomizer.removedService(DependencyManager.java:399)
> 	at org.apache.felix.scr.impl.manager.DependencyManager$MultipleDynamicCustomizer.removedService(DependencyManager.java:294)
> 	at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.customizerRemoved(ServiceTracker.java:1242)
> 	at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.customizerRemoved(ServiceTracker.java:1137)
> 	at org.apache.felix.scr.impl.manager.ServiceTracker$AbstractTracked.untrack(ServiceTracker.java:997)
> 	at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:1176)
> 	at org.apache.felix.scr.impl.BundleComponentActivator$ListenerInfo.serviceChanged(BundleComponentActivator.java:125)
> 	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:113)
> 	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:985)
> 	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
> 	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
> 	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:896)
> 	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:834)
> 	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.unregister(ServiceRegistrationImpl.java:227)
> 	at com.ibm.ws.ssl.internal.KeystoreConfig.unregister(KeystoreConfig.java:123)
> 	at com.ibm.ws.ssl.internal.KeystoreConfigurationFactory.updated(KeystoreConfigurationFactory.java:120)
> 	at com.ibm.ws.config.admin.internal.ManagedServiceFactoryTracker$2.run(ManagedServiceFactoryTracker.java:267)
> 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
> 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
> 	at com.ibm.ws.config.admin.internal.UpdateQueue$Queue.run(UpdateQueue.java:66)
> 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
> 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
> 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
> 	at java.base/java.lang.Thread.run(Thread.java:825)
>  Event:org.osgi.framework.FrameworkEvent[source=com.ibm.ws.ssl_1.3.39.202003110909 [114]] 
> CWWKS0009I: The security service has stopped.
> CWWKG0017I: The server configuration was successfully updated in 0.595 seconds.
> CWWKF0013I: The server removed the following features: [appSecurity-2.0, distributedMap-1.0, jndi-1.0, ssl-1.0].
> CWWKF0008I: Feature update completed in 0.551 seconds.

**Comment by pnicolucci** [comment]
I'm going to cancel this FAT update as after further investigation we've decided to look at not having felix scr log the message.
