### ISSUE TITLE
FFDC when testReplaceWithNewFailOverEnabledInstanceWhileServerIsRunning shuts down executor

### ISSUE THREAD

**Issue by njr-11** [OpenLiberty/open-liberty#11381]
Test Failure (20200312-2035): com.ibm.ws.concurrent.persistent.fat.failover1serv.SwitchFromSingleInstanceToFailOverTest.testReplaceWithNewFailOverEnabledInstanceWhileServerIsRunning

```
junit.framework.AssertionFailedError: 2020-03-13-10:06:48:241 [Unexpected FFDC reporting java.lang.IllegalStateException was found (count = 2): C:\jazz-build-engines\jazz112.hursley.ibm.com\EBC.PROD.WASRTC\build\dev\image\output\wlp\usr\servers\com.ibm.ws.concurrent.persistent.fat.failover1serv\logs\ffdc\ffdc_20.03.13_10.06.39.0.log
>------Start of DE processing------ = [3/13/20, 10:06:39:741 GMT]
>Exception = java.lang.IllegalStateException
>Source = com.ibm.ws.concurrent.persistent.internal.InvokerTask
>probeid = 611
>Stack Dump = java.lang.IllegalStateException: Attempting to execute an operation on a closed EntityManager.
>	at org.eclipse.persistence.internal.jpa.EntityManagerImpl.verifyOpen(EntityManagerImpl.java:1928)
>	at org.eclipse.persistence.internal.jpa.EntityManagerImpl.close(EntityManagerImpl.java:1772)
>	at com.ibm.ws.concurrent.persistent.db.DatabaseTaskStore.persist(DatabaseTaskStore.java:1289)
>	at com.ibm.ws.concurrent.persistent.internal.InvokerTask.run(InvokerTask.java:575)
>	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
>	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
>	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:239)
>	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
>	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
>	at java.base/java.lang.Thread.run(Thread.java:825)
]
	at componenttest.custom.junit.runner.FATRunner.blowup(FATRunner.java:296)
	at componenttest.custom.junit.runner.FATRunner.access$600(FATRunner.java:64)
	at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:246)
	at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:314)
	at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:167)
```

**Comment by njr-11** [comment]
This can happen occasionally due to how the test removes executors that might be concurrently attempting to run tasks/timers at the time of remove.  It's good to see that the tasks/timers do end up failing over to a new instance.  The test just needs an update to expect the possible FFDC.

**Comment by wraschke** [comment]
Sorry, I'm using this PR as a test subject.

#help

**Comment by wraschke** [comment]
#help
