### ISSUE TITLE
NPE in OpentracingUtils.lookupAppName()

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#11582]
https://github.com/OpenLiberty/open-liberty/blob/50d4aa1daf09469f02380f7942c439b65ded00a3/dev/com.ibm.ws.opentracing.1.3/src/com/ibm/ws/opentracing/OpentracingUtils.java#L82

```
[01/04/20 11:28:47:811 EDT] 00000056 .apache.cxf.cxf.core.3.2:1.0.38.cl200320200305-1433(id=173)] W Interceptor for {https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/nightly/info.json}WebClient has thrown exception, unwinding now
java.lang.NullPointerException
	at com.ibm.ws.opentracing.OpentracingUtils.lookupAppName(OpentracingUtils.java:82)
	at com.ibm.ws.opentracing.OpentracingTracerManager.getTracer(OpentracingTracerManager.java:141)
	at com.ibm.ws.opentracing.OpentracingClientFilter.filter(OpentracingClientFilter.java:92)
	at org.apache.cxf.jaxrs.client.spec.ClientRequestFilterInterceptor.handleMessage(ClientRequestFilterInterceptor.java:73)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.jaxrs.client.AbstractClient.doRunInterceptorChain(AbstractClient.java:712)
	at org.apache.cxf.jaxrs.client.WebClient.doChainedInvocation(WebClient.java:1056)
	at org.apache.cxf.jaxrs.client.WebClient.doInvoke(WebClient.java:902)
	at org.apache.cxf.jaxrs.client.WebClient.doInvoke(WebClient.java:871)
	at org.apache.cxf.jaxrs.client.WebClient.invoke(WebClient.java:431)
	at org.apache.cxf.jaxrs.client.SyncInvokerImpl.method(SyncInvokerImpl.java:135)
	at org.apache.cxf.jaxrs.client.SyncInvokerImpl.method(SyncInvokerImpl.java:130)
	at org.apache.cxf.jaxrs.client.SyncInvokerImpl.get(SyncInvokerImpl.java:50)
	at org.apache.cxf.jaxrs.client.spec.InvocationBuilderImpl.get(InvocationBuilderImpl.java:92)
	at io.openliberty.website.dheclient.DHEClient.retrieveJSON(DHEClient.java:36)
	at io.openliberty.website.dheclient.DHEBuildParser$RetrieveBuildList.call(DHEBuildParser.java:363)
	at io.openliberty.website.dheclient.DHEBuildParser$RetrieveBuildList.call(DHEBuildParser.java:1)
	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by fmhwong** [comment]
https://github.com/OpenLiberty/open-liberty/blob/c7cc28dde0bb6c2b3628e62b776982bd94e95d5e/dev/com.ibm.ws.container.service.compat/src/com/ibm/ws/threadContext/ComponentMetaDataAccessorImpl.java#L65 

It looks like `getComponentMetaData()` returned `null` as `defaultCMD` was `null`.
