### ISSUE TITLE
IllegalStateException can be logged if BundleContext becomes invalid during ConfigEventDispatcher

### ISSUE THREAD

**Issue by tjwatson** [OpenLiberty/open-liberty#11630]
```
[4/3/20, 1:38:10:488 UTC] 00000023 LogService-12-com.ibm.ws.org.apache.felix.scr W CWWKE0700W: bundle com.ibm.ws.org.apache.felix.scr:1.0.39.202004021905 (12) Bundle in unexpected state java.lang.IllegalStateException: BundleContext is no longer valid
 at org.eclipse.osgi.internal.framework.BundleContextImpl.checkValid(BundleContextImpl.java:1055)
 at org.eclipse.osgi.internal.framework.BundleContextImpl.ungetService(BundleContextImpl.java:726)
 at org.apache.felix.scr.impl.manager.RegionConfigurationSupport.getConfigurationInfo(RegionConfigurationSupport.java:536)
 at org.apache.felix.scr.impl.manager.RegionConfigurationSupport.configurationEvent(RegionConfigurationSupport.java:322)
 at org.apache.felix.scr.impl.manager.RegionConfigurationSupport$2.configurationEvent(RegionConfigurationSupport.java:115)
 at com.ibm.ws.config.admin.internal.ConfigEventDispatcher$1.run(ConfigEventDispatcher.java:101)
 at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
 at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
 at com.ibm.ws.config.admin.internal.UpdateQueue$Queue.run(UpdateQueue.java:66)
 at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
 at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
 at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
 at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
 at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
 at java.base/java.lang.Thread.run(Thread.java:825)
```

Felix SCR is logging this as a warning.  But it is a normal situation that should be handled without logging a warning.  The warning is harmless and can be ignored.

**Comment by tjwatson** [comment]
This was fixed in Apache felix using issue https://issues.apache.org/jira/browse/FELIX-6241
