### ISSUE TITLE
Concurent Login Issue

### ISSUE THREAD

**Issue by wrodrig** [OpenLiberty/open-liberty#11646]
**Describe the bug**
When doing a concurrent login of four users two users are able to authenticate and two fail with the following error

[ERROR   ] SRVE0315E: An exception occurred: java.lang.Throwable: java.lang.ArrayIndexOutOfBoundsException
    at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:5033)
    at [internal classes]
Caused by: java.lang.ArrayIndexOutOfBoundsException
    at java.util.ArrayList.toArray(ArrayList.java:423)
    at com.ibm.ws.security.token.ltpa.internal.UserData.addAttribute(UserData.java:98)
    ... 1 more

[ERROR   ] SRVE0315E: An exception occurred: java.lang.Throwable: java.lang.ArrayIndexOutOfBoundsException
    at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:5033)
    at [internal classes]
Caused by: java.lang.ArrayIndexOutOfBoundsException
    at java.util.ArrayList.toArray(ArrayList.java:423)
    at com.ibm.ws.security.token.ltpa.internal.UserData.addAttribute(UserData.java:98)
    ... 1 more

**Expected behavior**
All four users should be able to authenticate with no problem

**Diagnostic information:**
 - OpenLiberty Version: 19.0.0.12-20.0.0.3

**Comment by wrodrig** [comment]
Code changes were made in order to improve the handling of concurrent login.
