### ISSUE TITLE
Exception when calling JsonbBuilder.newBuilder in ContextResolver

### ISSUE THREAD

**Issue by yasammez** [OpenLiberty/open-liberty#11693]
**Describe the bug**
I am using a microprofile-config.properties like

```
com.example.app.StuffApi/mp-rest/providers=com.example.app.JsonContextResolver
```

to be able to build my own Jsonb for REST requests.

```
@Provider
class JsonContextResolver implements ContextResolver<Jsonb> {
    @Override
    public Jsonb getContext(Class<?> type) {
        return JsonBuilder.newBuilder().withConfig(/* ... */).build();    
    }
}
```

This works with wlp 19.0.0.6 as intended. However on 20.0.0.2 this throws a ServiceConfigurationError and through debugging I found out the instantiated ServiceLoader doesn't have a provider for Jsonb registered.

Stacktrace:
```
java.lang.RuntimeException: java.util.ServiceConfigurationError: javax.json.bind.spi.JsonbProvider: Provider org.eclipse.yasson.JsonBindingProvider not found
at org.apache.cxf.microprofile.client.proxy.MicroProfileClientProxyImpl$Invoker.call(MicroProfileClientProxyImpl.java:490) ~[?:?]
at org.apache.cxf.microprofile.client.cdi.MPRestClientInvocationContextImpl.interceptorChainCompleted(MPRestClientInvocationContextImpl.java:82) ~[?:?]
at org.apache.cxf.microprofile.client.cdi.MPRestClientInvocationContextImpl.proceed(MPRestClientInvocationContextImpl.java:90) ~[?:?]
at com.ibm.ws.microprofile.faulttolerance.cdi.FaultToleranceInterceptor.lambda$execute$0(FaultToleranceInterceptor.java:231) ~[?:?]
at com.ibm.ws.microprofile.faulttolerance20.state.impl.SyncBulkheadStateNullImpl.run(SyncBulkheadStateNullImpl.java:26) ~[?:?]
at com.ibm.ws.microprofile.faulttolerance20.impl.SyncExecutor.run(SyncExecutor.java:131) ~[?:?]
at com.ibm.ws.microprofile.faulttolerance20.impl.SyncExecutor.execute(SyncExecutor.java:76) ~[?:?]
at com.ibm.ws.microprofile.faulttolerance.cdi.FaultToleranceInterceptor.execute(FaultToleranceInterceptor.java:235) ~[?:?]
at com.ibm.ws.microprofile.faulttolerance.cdi.FaultToleranceInterceptor.executeFT(FaultToleranceInterceptor.java:81) ~[?:?]
at com.ibm.ws.microprofile.faulttolerance.cdi20.FaultToleranceCDI20Interceptor.intercept(FaultToleranceCDI20Interceptor.java:130) ~[?:?]
at com.ibm.ws.microprofile.faulttolerance.cdi20.FaultToleranceCDI20Interceptor.intercept(FaultToleranceCDI20Interceptor.java:42) ~[?:?]
at org.apache.cxf.microprofile.client.cdi.InterceptorInvoker.invoke(InterceptorInvoker.java:40) ~[?:?]
at org.apache.cxf.microprofile.client.cdi.MPRestClientInvocationContextImpl.invokeNextInterceptor(MPRestClientInvocationContextImpl.java:75) ~[?:?]
at org.apache.cxf.microprofile.client.cdi.MPRestClientInvocationContextImpl.proceed(MPRestClientInvocationContextImpl.java:88) ~[?:?]
at org.apache.cxf.microprofile.client.cdi.CDIInterceptorWrapperImpl.invoke(CDIInterceptorWrapperImpl.java:192) ~[?:?]
at org.apache.cxf.microprofile.client.proxy.MicroProfileClientProxyImpl.invoke(MicroProfileClientProxyImpl.java:458) ~[?:?]
at com.sun.proxy.$Proxy134.getSteuer(Unknown Source) ~[?:?]
at com.company.app.controller.MyController.getStuff(MyController.java:22) ~[app-1.6-SNAPSHOT.war:?]
Caused by: java.util.ServiceConfigurationError: javax.json.bind.spi.JsonbProvider: Provider org.eclipse.yasson.JsonBindingProvider not found
at java.util.ServiceLoader.fail(ServiceLoader.java:239) ~[?:1.8.0_222]
at java.util.ServiceLoader.access$300(ServiceLoader.java:185) ~[?:1.8.0_222]
at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:372) ~[?:1.8.0_222]
at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404) ~[?:1.8.0_222]
at java.util.ServiceLoader$1.next(ServiceLoader.java:480) ~[?:1.8.0_222]
at javax.json.bind.spi.JsonbProvider.provider(JsonbProvider.java:113) ~[com.ibm.websphere.javaee.jsonb.1.0_1.0.37.jar:?]
at javax.json.bind.JsonbBuilder.newBuilder(JsonbBuilder.java:133) ~[com.ibm.websphere.javaee.jsonb.1.0_1.0.37.jar:?]
at com.company.app.config.JsonContextResolver.getContext(JsonContextResolver.java:12) ~
at com.company.app.config.JsonContextResolver.getContext(JsonContextResolver.java:7) ~
at com.ibm.ws.jaxrs21.providers.json.JsonBProvider.getJsonb(JsonBProvider.java:213) ~[?:?]
at com.ibm.ws.jaxrs21.providers.json.JsonBProvider.readFrom(JsonBProvider.java:156) ~[?:?]
at org.apache.cxf.jaxrs.utils.JAXRSUtil
```

**Steps to Reproduce**
Use a custom JsonbProvider as described above and make sure it successfully deploys against wlp 19.0.0.6. Once deployed on wlp 20.0.0.2, calling a codepath which involves the such configured mp-rest client should result in an exception.

**Expected behavior**
JsonbBuilder.newBuilder should return an instance of a JsonbBuilder, preferrably the configured default (yasson).

**Diagnostic information:**
 - OpenLiberty Version: 20.0.0.2
 - Java Version: 1.8.0_222
 - server.xml configuration
```
<server desc="com.company.app">
    <featureManager>
    <feature>beanValidation-2.0</feature>
        <feature>cdi-2.0</feature>
        <feature>concurrent-1.0</feature>
        <feature>ejbLite-3.2</feature>
        <feature>jaspic-1.1</feature>
        <feature>jaxrs-2.1</feature>
        <feature>jsonb-1.0</feature>
        <feature>jsonp-1.1</feature>
        <feature>mpConfig-1.3</feature>
        <feature>mpOpenAPI-1.0</feature>
        <feature>mpRestClient-1.2</feature>
        <feature>servlet-4.0</feature>
        <feature>jaxrsClient-2.1</feature>
        <feature>mpMetrics-1.1</feature>
        <feature>mpFaultTolerance-2.0</feature>
    </featureManager>
    <httpEndpoint host="*" httpPort="${env.DEFAULT_HTTP_PORT}" httpsPort="${env.DEFAULT_HTTPS_PORT}" id="defaultHttpEndpoint">
        <tcpOptions acceptThread="true" waitToAccept="true"/>
        <accessLogging filePath="${env.X_LOG_DIR}/access.log" logFormat="%A %t &quot;SourceIP=%h&quot; &quot;%r&quot; %s %B %D %{R}W."/>      
    </httpEndpoint>
    <jndiEntry jndiName="auth.token.password" value="${env.AUTH_TOKEN_PASSWORD}"/>
    
    <sslDefault sslRef="SSLContext"/>
    <ssl id="SSLContext" keyStoreRef="KeyStore" trustStoreRef="TrustStore"/>
    <keyStore id="TrustStore" location="${shared.config.dir}/cacerts-1.0.0.p12" password="REDACTED"/>
    <keyStore id="KeyStore" location="${shared.config.dir}/cacerts-1.0.0.p12" password="REDACTED"/>
    <webApplication contextRoot="api/v1" id="myapp" name="myapp"  location="myapp-1.6-SNAPSHOT.war"  />
```

**Additional context**
This might be related to https://github.com/OpenLiberty/open-liberty/issues/10248 but I am not sure.

**Comment by yasammez** [comment]
Additional information: I tested the same setup with wlp 20.0.0.1 and it worked. The problem must have been introduced with wlp 20.0.0.2.

**Comment by andymc12** [comment]
Hi @yasammez - what thread is this running on?  It looks like the first line in the stack is the rest client interface - is this invoked asynchronously on another thread?  The thread is important because it contains the classloading context necessary to load the JSON-B provider that is packaged with Liberty - but that context will only be on the thread if the thread is managed by Liberty (or if the context has been propagated to an unmanaged thread). 

My guess is that the thread that the failure occurs on does not have the necessary classloading context.  So, assuming that the application did not change from release-to-release then something in Liberty may have changed so that the classloading context is not propagated correctly.

Is it possible to provide a reproducer app?  If my guess is right, the app probably starts in a JAX-RS resource or servlet or something and then executes the MP Rest Client in another thread.  The main thing I would like to see is how the app executes the MP Rest Client.

Thanks for reporting this!

**Comment by yasammez** [comment]
hi, thanks for your reply. I just tested it in a debugger and the thread in question is called (this time) "Default Executor-thread-721". As far as I know we're not using any async features in the code, just a regular Jax-RS controller which in turn injects a mp-rest client.

```
@RequestScoped
@Default
@EnableModelValidation
public class MyController {

    @Inject
    @RestClient
    private MyClient myClient;

    @GET
    @Produces({ "application/json", "application/problem+json" })
    Response getStuff() {
        return Response.status(200).type("application/json").entity(myClient.getStuff()).build();
    }

}
```

With the client looking like

```
@RegisterRestClient(baseUri = "http://localhost:1234")
@RegisterClientHeaders
public interface MyClient {
    
    @GET 
    @Path("/")
    @Produces("application/json")
    String getStuff();

}
```

I will try to strip my case down to a minimal example if my employer allows.

**Comment by yasammez** [comment]
Of course when trying to build a minimal example, the error vanished in front of my eyes. Digging deeper I found a proprietary servlet Filter which changes the name of the current thread (presumably for logging purposes) before everything else gets called. Could this be the source of the problem?

**Comment by andymc12** [comment]
@yasammez interesting.  The name of the thread shouldn't matter, but can you check to see if it also changes the thread's context classloader (usually with a `setContextClassLoader(...)` call)?  That could cause this issue.

**Comment by yasammez** [comment]
I'm afraid that wasn't the case. I performed a (lengthy) binary search on the code and am now at the conclusion that one of our internal libraries is causing the issue. However I don't have a smoking gun yet.

**Comment by andymc12** [comment]
You can get a stack trace (in trace.log) for each time that somebody changes the context classloader of a Liberty-managed thread -- this can be quite a lot, so I would definitely not recommend using this in production.  That might help in this case.

To enable that you'll need to set this line in the bootstrap.properties file (create it in the server directory if it is not already there):
`com.ibm.ws.logging.trace.specification=com.ibm.ws.threading.internal.ThreadFactoryImpl*=all`

If you specify trace settings in the server.xml, then you should also add `com.ibm.ws.threading.internal.ThreadFactoryImpl*=all` to the traceSpecification there too.

Using that trace setting, you could reproduce the failure - then look back in the trace.log to the last time that somebody called `setContextClassLoader` on that thread. That might identify the source of the problem.  If you want to post the trace.log, I can help with the diagnosing.

**Comment by yasammez** [comment]
Thank you for your recommendation. I followed it and received at the following stacktrace:

```
 at com.ibm.ws.threading.internal.ThreadFactoryImpl$LibertyThread.setContextClassLoader(ThreadFactoryImpl.java:139)
    at org.apache.cxf.common.classloader.ClassLoaderUtils$ClassLoaderHolder.reset(ClassLoaderUtils.java:57)
    at org.apache.cxf.jaxrs.client.ClientProxyImpl.doChainedInvocation(ClientProxyImpl.java:910)
    at org.apache.cxf.jaxrs.client.ClientProxyImpl.invoke(ClientProxyImpl.java:343)
    at org.apache.cxf.microprofile.client.proxy.MicroProfileClientProxyImpl.invokeActual(MicroProfileClientProxyImpl.java:463)
    at org.apache.cxf.microprofile.client.proxy.MicroProfileClientProxyImpl.access$000(MicroProfileClientProxyImpl.java:76)
    at org.apache.cxf.microprofile.client.proxy.MicroProfileClientProxyImpl$Invoker.call(MicroProfileClientProxyImpl.java:485)
    at org.apache.cxf.microprofile.client.cdi.CDIInterceptorWrapperImpl.invoke(CDIInterceptorWrapperImpl.java:190)
    at org.apache.cxf.microprofile.client.proxy.MicroProfileClientProxyImpl.invoke(MicroProfileClientProxyImpl.java:458)
    at com.sun.proxy.$Proxy104.getStuff(Unknown Source)
    at com.company.app.MyController.getStuff(MyController.java:53)
```

However, this still leaves me puzzled. It seems, the proxy itself changes the context class loader?

**Comment by yasammez** [comment]
We rewrote our context provider as following:
```
public class MpClientJsonbProvider implements ContextResolver<Jsonb> {
   private Jsonb jsonb;

   public MpClientJsonbProvider() {
      JsonbConfig config = new JsonbConfig().withAdapters(/* ... */);
      jsonb = JsonbBuilder.create(config);
   }

   @Override
   public Jsonb getContext(Class<?> type) {
      return jsonb;
   }

}
```

This fixed our problem. I am not sure however, why. Maybe it was the double `@Provider` registration? Anyway, this ticket can be closed now. Thank you for your help and sorry for the noise.
