### ISSUE TITLE
Spnego Token validation fails using Eclipse OpenJ9 V 1.8.0_242

### ISSUE THREAD

**Issue by mbroz2** [OpenLiberty/open-liberty#11711]
@gianretosaligari commented on [Wed Apr 08 2020](https://github.com/OpenLiberty/openliberty.io/issues/1597)

Dear team
I'm using Kerberos authentication with OpenLiberty V 20.0.0.3 and OpenJDK J9 1.8.0_242-b08. Login fails with the following excetpion. Same app works fine using Eclipse OpenJ9 VM, version 11.0.5+10. I checked the JDK8 configuration about the unlimited policy files and it looks fine. I suspect that the JDK8 has a configuration flow so that Open Liberty can't fine the crypto libraries to decript the token. 
Could you please help me to fix this issue?
Kind Regards
Gian-Reto

Launching defaultServer (Open Liberty 20.0.0.3/wlp-1.0.38.cl200320200305-1433) on Eclipse OpenJ9 VM, version 1.8.0_242-b08 (en_US)

Exit  
com.ibm.ws.security.authentication.AuthenticationException: Failure unspecified at GSS-API level (Mechanism level: Invalid argument (400) - Cannot find key of appropriate type to decrypt AP REP - AES256 CTS mode with HMAC SHA1-96)
	at com.ibm.ws.security.spnego.internal.Krb5Util.validateSpnegoToken(Krb5Util.java:149)
	at com.ibm.ws.security.spnego.internal.Krb5Util.processSpnegoToken(Krb5Util.java:109)
	at com.ibm.ws.security.spnego.SpnegoAuthenticator.authenticate(SpnegoAuthenticator.java:52)
	at com.ibm.ws.security.spnego.SpnegoService.authenticate(SpnegoService.java:146)
	at com.ibm.ws.webcontainer.security.extended.WebProviderAuthenticatorProxyExtended.handleSpnego(WebProviderAuthenticatorProxyExtended.java:194)
	at com.ibm.ws.webcontainer.security.extended.WebProviderAuthenticatorProxyExtended.authenticate(WebProviderAuthenticatorProxyExtended.java:127)
	at com.ibm.ws.webcontainer.security.WebAuthenticatorProxy.authenticate(WebAuthenticatorProxy.java:64)
	at com.ibm.ws.webcontainer.security.WebAppSecurityCollaboratorImpl.authenticateRequest(WebAppSecurityCollaboratorImpl.java:1211)
	at com.ibm.ws.webcontainer.security.WebAppSecurityCollaboratorImpl.determineWebReply(WebAppSecurityCollaboratorImpl.java:967)
	at com.ibm.ws.webcontainer.security.WebAppSecurityCollaboratorImpl.performSecurityChecks(WebAppSecurityCollaboratorImpl.java:656)
	at com.ibm.ws.webcontainer.security.WebAppSecurityCollaboratorImpl.preInvoke(WebAppSecurityCollaboratorImpl.java:574)
	at com.ibm.wsspi.webcontainer.collaborator.CollaboratorHelper.preInvokeCollaborators(CollaboratorHelper.java:459)
	at com.ibm.ws.webcontainer.osgi.collaborator.CollaboratorHelperImpl.preInvokeCollaborators(CollaboratorHelperImpl.java:270)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1106)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1002)
	at com.ibm.ws.webcontainer.servlet.CacheServletWrapper.handleRequest(CacheServletWrapper.java:75)
	at com.ibm.ws.webcontainer40.servlet.CacheServletWrapper40.handleRequest(CacheServletWrapper40.java:83)
	at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:938)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:279)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1136)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:417)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:376)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:547)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:481)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:346)
	at com.ibm.ws.http.channel.internal.inbound.HttpICLReadCallback.complete(HttpICLReadCallback.java:70)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:503)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueManager.java:573)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:954)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:1043)
	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:239)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:821)

**Comment by utle** [comment]
It worked when setting the default_keytab_name in the krb5.conf.
