### ISSUE TITLE
Avoid starting management EJB app during server shutdown

### ISSUE THREAD

**Issue by tkburroughs** [OpenLiberty/open-liberty#11816]
When there is a dynamic server configuration change occurring just as the server command is used to stop the server, it is possible the management EJB application may attempt to restart during server shutdown, and result in an error like the following:

```
Stack Dump = java.lang.IllegalStateException: Located service is null,AtomicServiceReference[name=orbRef,ctx=org.apache.felix.scr.impl.manager.ComponentContextImpl@ffb5bc19,ref={com.ibm.ws.transport.iiop.spi.ORBRef, com.ibm.ws.transport.iiop.spi.ClientORBRef, com.ibm.ws.transport.iiop.spi.ServerPolicySource}={serverPolicy.0.layers.0.attributeLayer.0.identityAssertionEnabled=false, clientPolicy.0.stateful=false, orbSSLInitTimeout=10, service.scope=bundle, AdapterActivatorOp.target=(service.pid=com.ibm.ws.transport.iiop.internal.NamingServiceAdapterActivator_31), service.ranking=5, serverPolicy.0.config.referenceType=com.ibm.ws.security.csiv2.serverPolicyCSIV2, serverPolicy.0.layers.0.config.referenceType=com.ibm.ws.security.csiv2.serverPolicyLayers, component.name=com.ibm.ws.transport.iiop.internal.ORBWrapperInternal, clientPolicy.0.config.referenceType=com.ibm.ws.security.csiv2.clientPolicyCSIV2, clientPolicy.0.layers.0.attributeLayer.0.identityAssertionEnabled=false, serverPolicy.0.layers.0.authenticationLayer.0.mechanisms=[LTPA,GSSUP], clientPolicy.0.layers.0.authenticationLayer.0.establishTrustInClient=Supported, clientPolicy.0.layers.0.attributeLayer.0.config.referenceType=com.ibm.ws.security.csiv2.clientPolicyAttributeLayer, config.source=file, clientPolicy.0.layers.0.authenticationLayer.0.mechanisms=[LTPA,GSSUP], id=defaultOrb, serverPolicy.0.layers.0.attributeLayer.0.config.referenceType=com.ibm.ws.security.csiv2.attributeLayer, service.pid=com.ibm.ws.transport.iiop.internal.ORBWrapper_32, clientPolicy.0.layers.0.attributeLayer.0.identityAssertionTypes=[ITTAnonymous,ITTPrincipalName], AdapterActivatorOp.cardinality.minimum=1, nameService=corbaloc:iiop:localhost:2809/NameService, service.id=813, IiopEndpoint.target=(service.pid=com.ibm.ws.transport.iiop.internal.IIOPEndpointImpl_28), service.bundleid=167, clientPolicy.0.layers.0.transportLayer.0.sslEnabled=true, clientPolicy.0.layers.0.authenticationLayer.0.config.referenceType=com.ibm.ws.security.csiv2.clientPolicyAuthenticationLayer, config.overrides=true, serverPolicy.0.stateful=false, iiopEndpoint=[com.ibm.ws.transport.iiop.internal.IIOPEndpointImpl_28], serverPolicy.0.layers.0.authenticationLayer.0.establishTrustInClient=Required, ComponentFactory.target=(component.factory=com.ibm.ws.transport.iiop.internal.ORBWrapperInternal), component.id=645, serverPolicy.0.layers.0.attributeLayer.0.identityAssertionTypes=[ITTAnonymous,ITTPrincipalName,ITTX509CertChain,ITTDistinguishedName], serverPolicy.0.layers.0.authenticationLayer.0.config.referenceType=com.ibm.ws.security.csiv2.authenticationLayer, SubsystemFactory.cardinality.minimum=6, clientPolicy.0.layers.0.config.referenceType=com.ibm.ws.security.csiv2.clientPolicyLayers, clientPolicy.0.layers.0.transportLayer.0.config.referenceType=com.ibm.ws.security.csiv2.transportLayer, config.id=com.ibm.ws.transport.iiop.internal.ORBWrapper[defaultOrb], serverPolicy.0.layers.0.transportLayer.0.sslEnabled=true, service.factoryPid=com.ibm.ws.transport.iiop.internal.ORBWrapper, adapterActivator=[com.ibm.ws.transport.iiop.internal.NamingServiceAdapterActivator_31], service.vendor=IBM, serverPolicy.0.layers.0.transportLayer.0.config.referenceType=com.ibm.ws.security.csiv2.transportLayer, subsystemFactory=[com.ibm.ws.transport.iiop.spi.SubsystemFactory_50,com.ibm.ws.transport.iiop.spi.SubsystemFactory_51,com.ibm.ws.transport.iiop.spi.SubsystemFactory_52,com.ibm.ws.transport.iiop.spi.SubsystemFactory_47,com.ibm.ws.transport.iiop.spi.SubsystemFactory_48,com.ibm.ws.transport.iiop.spi.SubsystemFactory_49], config.displayId=orb[defaultOrb]},svc=null]
	at com.ibm.wsspi.kernel.service.utils.AtomicServiceReference.getService(AtomicServiceReference.java:261)
	at com.ibm.wsspi.kernel.service.utils.AtomicServiceReference.getServiceWithException(AtomicServiceReference.java:210)
	at com.ibm.ws.ejbcontainer.remote.internal.EJBRemoteRuntimeImpl.getEjbAdapter(EJBRemoteRuntimeImpl.java:287)
	at com.ibm.ws.ejbcontainer.remote.internal.EJBRemoteRuntimeImpl.bind(EJBRemoteRuntimeImpl.java:185)
	at com.ibm.ws.ejbcontainer.remote.internal.EJBRemoteRuntimeImpl.bindSystem(EJBRemoteRuntimeImpl.java:179)
	at com.ibm.ws.ejbcontainer.osgi.internal.SystemNameSpaceBinderImpl.bindBindings(SystemNameSpaceBinderImpl.java:77)
	at com.ibm.ws.ejbcontainer.osgi.internal.SystemNameSpaceBinderImpl.bindBindings(SystemNameSpaceBinderImpl.java:24)
	at com.ibm.ws.ejbcontainer.runtime.AbstractEJBRuntime.bindInterface(AbstractEJBRuntime.java:997)
	at com.ibm.ws.ejbcontainer.runtime.AbstractEJBRuntime.bindInterfaces(AbstractEJBRuntime.java:935)
	at com.ibm.ws.ejbcontainer.runtime.AbstractEJBRuntime.bindInterfaces(AbstractEJBRuntime.java:862)
	at com.ibm.ws.ejbcontainer.osgi.internal.EJBRuntimeImpl.bindInterfaces(EJBRuntimeImpl.java:1086)
	at com.ibm.ws.ejbcontainer.runtime.AbstractEJBRuntime.startModule(AbstractEJBRuntime.java:524)
	at com.ibm.ws.ejbcontainer.osgi.internal.EJBRuntimeImpl.startSystemModule(EJBRuntimeImpl.java:1024)
	at com.ibm.ws.ejbcontainer.osgi.internal.EJBContainerImpl.startSystemModule(EJBContainerImpl.java:227)
	at com.ibm.ws.management.j2ee.mejb.service.ManagementEJBService.startManagementEJB(ManagementEJBService.java:160)
	at com.ibm.ws.management.j2ee.mejb.service.ManagementEJBService.setEJBRemoteRuntime(ManagementEJBService.java:76)

```

**Comment by tkburroughs** [comment]
When the server is being stopped, there is no point in attempting to restart a system application.  EJB Container should just no-op system application starts that occur once the serve has begun shutting down.
