### ISSUE TITLE
Test Failure (20171130-0424): PersistentExecutorDemoTest.testCancelTask fails with Java 2 security enabled

### ISSUE THREAD

**Issue by njr-11** [OpenLiberty/open-liberty#1192]
The following error occurs in builds with Java 2 security enabled:

Test Failure (20171130-0424): com.ibm.ws.concurrent.persistent.fat.demo.PersistentExecutorDemoTest.testCancelTask

java.io.IOException: Server returned HTTP response code: 500 for URL: http://localhost:8011/persistentdemo?newTaskName=TaskA&initialDelay=3&interval=2&units=SECONDS
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1891)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1489)
	at com.ibm.ws.concurrent.persistent.fat.demo.PersistentExecutorDemoTest.runInServlet(PersistentExecutorDemoTest.java:73)
	at com.ibm.ws.concurrent.persistent.fat.demo.PersistentExecutorDemoTest.testCancelTask(PersistentExecutorDemoTest.java:118)

Logs show that Derby lacks permissions. For example,

Caused by: ERROR XBM0C: Missing privilege for operation 'exists' on file 'service.properties': Access denied ("java.io.FilePermission" "/home/jazz_build/_EAtw4NWYEeeEtKxTXP6tcw-EBC.PROD.WASRTC-GD2-000-00-00/jbe/build/dev/image/output/wlp/usr/shared/resources/data/persistdemodb/service.properties" "read")
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.services.monitor.StorageFactoryService$FileOperationHelper.handleSecPrivException(Unknown Source)
	at org.apache.derby.impl.services.monitor.StorageFactoryService$FileOperationHelper.exists(Unknown Source)
	at org.apache.derby.impl.services.monitor.StorageFactoryService.resolveServicePropertiesFiles(Unknown Source)
	at org.apache.derby.impl.services.monitor.StorageFactoryService.access$500(Unknown Source)
	at org.apache.derby.impl.services.monitor.StorageFactoryService$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(AccessController.java:650)
	at org.apache.derby.impl.services.monitor.StorageFactoryService.getServiceProperties(Unknown Source)
	at org.apache.derby.impl.services.monitor.BaseMonitor.findProviderAndStartService(Unknown Source)
	at org.apache.derby.impl.services.monitor.BaseMonitor.startPersistentService(Unknown Source)
	at org.apache.derby.iapi.services.monitor.Monitor.startPersistentService(Unknown Source)
	... 46 more
Caused by: java.security.AccessControlException: Access denied ("java.io.FilePermission" "/home/jazz_build/_EAtw4NWYEeeEtKxTXP6tcw-EBC.PROD.WASRTC-GD2-000-00-00/jbe/build/dev/image/output/wlp/usr/shared/resources/data/persistdemodb/service.properties" "read")
	at java.security.AccessController.throwACE(AccessController.java:157)
	at java.security.AccessController.checkPermissionHelper(AccessController.java:217)
	at java.security.AccessController.checkPermission(AccessController.java:349)
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:562)
	at java.lang.SecurityManager.checkRead(SecurityManager.java:901)
	at java.io.File.exists(File.java:825)
	... 55 more

**Comment by njr-11** [comment]
I attempted to make the fix for this, but found that another developer has already corrected it.  I'll cancel this issue as duplicate.
