### ISSUE TITLE
CDI system not available in context of threadPool

### ISSUE THREAD

**Issue by Mixermachine** [OpenLiberty/open-liberty#11972]
**Describe the bug**
I'm currently implementing a Java Server with a state machine which processes data.
I make heavy use of thread pools as I'm expecting many large files in peak times.

To start a new step in the state machine I use the CDI system to get an instance of the next service which should process a file.
When I'm using new *Class* I can not use @Inject (no injection happening) so I reverted to CDI.current().
When I'm in the context of a ThreadPool, the CDI system is not available. CDI.current() == null

**Steps to Reproduce**
```
public class Worker implements Runnable {
    private static final OtherService otherService = CDI.current().get(OtherService.class).get();

    @Override
    public void run() {
    }
}
```

```
private final ExecutorService executorService = new ForkJoinPool(1);
executorService.execute(new Worker());
```
--> NullpointerException
CDI.current() is null

**Expected behavior**
CDI.current is not null but provides the current CDI service.

**Diagnostic information:**
 - OpenLiberty Version: 20.0.0.4
 - Java Version: Java 13
 - server.xml configuration:
```
<featureManager>
    <feature>jaxrs-2.1</feature>
    <feature>mpConfig-1.3</feature>
    <feature>mpHealth-2.1</feature>
    <feature>mpMetrics-2.2</feature>
  </featureManager>

  <applicationManager autoExpand="true" />

  <mpMetrics authentication="false" />

  <variable name="default.http.port" defaultValue="9080"/>
  <variable name="default.https.port" defaultValue="9443"/>
  <variable name="app.context.root" defaultValue="/"/>

  <httpEndpoint host="*" httpPort="${default.http.port}" httpsPort="${default.https.port}" id="defaultHttpEndpoint"/>
  <keyStore id="defaultKeyStore" password="*" />

  <webApplication location="regulus-influx-file-ingestor.war" contextRoot="${app.context.root}"/>

  <logging consoleLogLevel="INFO" consoleSource="message,trace,accessLog,ffdc" />
```

Greetings from Munich

Aaron

**Comment by tevans78** [comment]
@Mixermachine there are no JEE contexts available on the thread started via a ForkJoinPool. You should use a ManagedExecutorService instead, either looked up via JNDI or injected using `@Resource`.
https://javaee.github.io/javaee-spec/javadocs/javax/enterprise/concurrent/ManagedExecutorService.html

**Comment by Mixermachine** [comment]
Hy @tevans78 
that's a good info 👍.

Currently IntelliJ can not find ManagedExecutorService.
Is 
```
<dependency>
    <groupId>javax</groupId>
    <artifactId>javaee-api</artifactId>
    <version>7.0</version>
</dependency>
```
the right dependecy?

Also: can I controll the number of threads in a ManagedExecutorService?

Thanks in advance

**Comment by tevans78** [comment]
Try this
```
<dependency>
    <groupId>javax.enterprise.concurrent</groupId>
    <artifactId>javax.enterprise.concurrent-api</artifactId>
    <version>1.1</version>
</dependency>
```

If you just inject a ManagedExecutorService without specifying any particular JNDI name then you will get the default. Open Liberty will manage and optimise your threads for you, something it is very good at and I would recommend sticking with the defaults. This blog post is good reading: https://openliberty.io/blog/2019/04/03/liberty-threadpool-autotuning.html

If you really want to, you can configure a non-default executor in your server.xml;
https://openliberty.io/docs/ref/config/#managedExecutorService.html

I notice that you are already using serveral MicroProfile features. Have you considered using MicroProfile Fault Tolerance to control your threading? Using an Asynchronous Bulkhead might give you exactly the functionality you want? e.g.
```
@ApplicationScoped
public class Worker {
    @Asynchronous
    @Bulkhead(value = 5, waitingTaskQueue = 5)
    public CompletionStage<Connection> serviceA() {
       Connection conn = null;
       counterForInvokingServiceA++;
       conn = connectionService();
       return CompletableFuture.completedFuture(conn);
    }
}
```
NB: The example above uses CompletionStage which is specific to FT 2.1.
https://download.eclipse.org/microprofile/microprofile-fault-tolerance-2.1/microprofile-fault-tolerance-spec.html#_interactions_when_returning_a_code_completionstage_code

This guide will give you an overview of the MP Fault Tolerance Bulkhead but note that it is based on version Fault Tolerance 1.0: https://openliberty.io/guides/bulkhead.html

**Comment by Mixermachine** [comment]
Hy Tevans,

Bulkheads look very nice.
Before I can implement them I have one small problem:

I create the initial state of my state machine with a new (new Received(dbEntry)) and give this state machine a dbEntry object which contains all information about the job.
The bad thing is: I lose the JEE context there and can not create a managedThreadPool or use the Bulkhead feature.
Can I create the State in a different way?
Or do I have to make it a @RequestScoped class and remove the DBEntry from the constructor?

**Comment by Mixermachine** [comment]
Hy @tevans78 
I'm now rebuilding the state machines to be @RequestScoped.

The Bulkhead feature looks very good, but I'm currently already working on so much new stuff, I think I need to finish some before I put additional things in :D.


When I'm trying to get the ManagedExecutorService I get the following Exception on the Dev Server:

```
java.lang.IllegalArgumentException: Can not set javax.enterprise.concurrent.ManagedExecutorService field com.sf.regulus.decompression.DecompressionService.executorService to com.ibm.ws.concurrent.mp.ManagedExecutorImpl
	at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
	at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
	at java.base/jdk.internal.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81)
	at java.base/java.lang.reflect.Field.set(Field.java:780)
	at com.ibm.wsspi.injectionengine.InjectionTargetField.injectMember(InjectionTargetField.java:175)
	at com.ibm.wsspi.injectionengine.InjectionTarget.inject(InjectionTarget.java:111)
	at com.ibm.ws.cdi.impl.weld.injection.WebSphereInjectionServicesImpl.inject(WebSphereInjectionServicesImpl.java:198)
	at com.ibm.ws.cdi.impl.weld.injection.WebSphereInjectionServicesImpl.inject(WebSphereInjectionServicesImpl.java:150)
	at com.ibm.ws.cdi.impl.weld.injection.WebSphereInjectionServicesImpl.access$000(WebSphereInjectionServicesImpl.java:74)
	at com.ibm.ws.cdi.impl.weld.injection.WebSphereInjectionServicesImpl$1.run(WebSphereInjectionServicesImpl.java:134)
	at com.ibm.ws.cdi.impl.weld.injection.WebSphereInjectionServicesImpl$1.run(WebSphereInjectionServicesImpl.java:130)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:554)
	at com.ibm.ws.cdi.impl.weld.injection.WebSphereInjectionServicesImpl.callInject(WebSphereInjectionServicesImpl.java:130)
	at com.ibm.ws.cdi.impl.weld.injection.WebSphereInjectionServicesImpl.injectJavaEEResources(WebSphereInjectionServicesImpl.java:112)
	at com.ibm.ws.cdi.impl.weld.injection.WebSphereInjectionServicesImpl.aroundInject(WebSphereInjectionServicesImpl.java:317)
	at org.jboss.weld.injection.InjectionContextImpl.run(InjectionContextImpl.java:46)
	at org.jboss.weld.injection.producer.ResourceInjector.inject(ResourceInjector.java:71)
	at org.jboss.weld.injection.producer.BasicInjectionTarget.inject(BasicInjectionTarget.java:117)
	at org.jboss.weld.bean.ManagedBean.create(ManagedBean.java:161)
	at org.jboss.weld.contexts.AbstractContext.get(AbstractContext.java:96)
	at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get(ContextualInstanceStrategy.java:100)
	at org.jboss.weld.bean.ContextualInstanceStrategy$ApplicationScopedContextualInstanceStrategy.get(ContextualInstanceStrategy.java:140)
	at org.jboss.weld.bean.ContextualInstance.get(ContextualInstance.java:50)
	at org.jboss.weld.bean.proxy.ContextBeanInstance.getInstance(ContextBeanInstance.java:102)
	at org.jboss.weld.bean.proxy.ProxyMethodHandler.getInstance(ProxyMethodHandler.java:131)
	at com.sf.regulus.decompression.DecompressionService$Proxy$_$$_WeldClientProxy.toString(Unknown Source)
	at com.sf.regulus.db.dbEntryStateImpl.Received.success(Received.java:30)
	at com.sf.regulus.db.dbEntryStateImpl.Received$Proxy$_$$_WeldClientProxy.success(Unknown Source)
	at com.sf.regulus.ingestor.IngestHTTPRestServer.process(IngestHTTPRestServer.java:102)
	at com.sf.regulus.ingestor.IngestHTTPRestServer.ingest(IngestHTTPRestServer.java:72)
	at com.sf.regulus.ingestor.IngestHTTPRestServer$Proxy$_$$_WeldClientProxy.ingest(Unknown Source)
	at jdk.internal.reflect.GeneratedMethodAccessor672.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at com.ibm.ws.jaxrs20.cdi.component.JaxRsFactoryImplicitBeanCDICustomizer.serviceInvoke(JaxRsFactoryImplicitBeanCDICustomizer.java:334)
	at com.ibm.ws.jaxrs20.server.LibertyJaxRsServerFactoryBean.performInvocation(LibertyJaxRsServerFactoryBean.java:641)
	at com.ibm.ws.jaxrs20.server.LibertyJaxRsInvoker.performInvocation(LibertyJaxRsInvoker.java:160)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
	at com.ibm.ws.jaxrs20.server.LibertyJaxRsInvoker.invoke(LibertyJaxRsInvoker.java:273)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:205)
	at com.ibm.ws.jaxrs20.server.LibertyJaxRsInvoker.invoke(LibertyJaxRsInvoker.java:444)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:111)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:61)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:99)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:124)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:274)
	at com.ibm.ws.jaxrs20.endpoint.AbstractJaxRsWebEndpoint.invoke(AbstractJaxRsWebEndpoint.java:136)
	at com.ibm.websphere.jaxrs.server.IBMRestServlet.handleRequest(IBMRestServlet.java:146)
	at com.ibm.websphere.jaxrs.server.IBMRestServlet.doPost(IBMRestServlet.java:104)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:706)
	at com.ibm.websphere.jaxrs.server.IBMRestServlet.service(IBMRestServlet.java:96)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1230)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:729)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:426)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1226)
	at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:5021)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.handleRequest(DynamicVirtualHost.java:314)
	at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:1007)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:279)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1134)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:415)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:374)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:551)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:484)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:346)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.ready(HttpInboundLink.java:317)
	at com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.sendToDiscriminators(NewConnectionInitialReadCallback.java:167)
	at com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.complete(NewConnectionInitialReadCallback.java:75)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:504)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueManager.java:574)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:958)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:1047)
	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:239)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
```

Have you seen this before?

**Comment by Emily-Jiang** [comment]
@Mixermachine can you point us to your github if possible to figure out what is wrong? If you use concurrency feature, you also need to add `concurrent-1.0` feature.

**Comment by Mixermachine** [comment]
Hi @Emily-Jiang sadly I can not give out the code as I'm bound by a contract.
I hope I can stitch a small example of the problem together tomorrow.

One word to everybody here:
Thanks for your support and openness.
This really is a nice community.

**Comment by Mixermachine** [comment]
Hi @Emily-Jiang 
After some iterations of my code everything works now.
`concurrent-1.0` did the trick and the dependency is correctly injected.

Thx again to everybody 👍
