### ISSUE TITLE
OIDC NPE in AuthorizationCodeHandler TS003640456

### ISSUE THREAD

**Issue by barbj** [OpenLiberty/open-liberty#12034]
Exception = java.lang.NullPointerException
Source = com.ibm.ws.security.openidconnect.clients.common.AuthorizationCodeHandler
probeid = 140
Stack Dump = java.lang.NullPointerException
	at org.apache.http.impl.client.CloseableHttpClient.determineTarget(CloseableHttpClient.java:92)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at com.ibm.ws.security.openidconnect.clients.common.OidcClientHttpUtil.postToEndpoint(OidcClientHttpUtil.java:158)
	at com.ibm.ws.security.openidconnect.clients.common.OidcClientUtil.postToTokenEndpoint(OidcClientUtil.java:185)
	at com.ibm.ws.security.openidconnect.clients.common.OidcClientUtil.getTokensFromAuthzCode(OidcClientUtil.java:103)

**Comment by ayoho** [comment]
Upgrading the JDK ended up solving this, so closing.
