### ISSUE TITLE
com.ibm.ws.session.store.cache.CacheStoreService exception if wlp under a directoy with space

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/open-liberty#12143]
To reproduce the problem:
- make a directory with space, e.g. "test space"
- cd to "test space""
- git clone https://github.com/openliberty/guide-sessions.git
- cd guide-sessions\finish
- mvn liberty:dev
- will have following exception:
```
[INFO] [ERROR   ] SESN0307E: An exception occurred when initializing the cache. The exception is: java.lang.IllegalArgumentException: SESN0300E: Invalid syntax in httpSessionCache URI.  Cause is java.net.URISyntaxException: Illegal character in opaque part at index 30: file:C:/Tasks/CNAI/guides/test space/guide-sessions/finish/target/liberty/wlp/usr/servers/defaultServer/hazelcast-config.xml.
[INFO]  at com.ibm.ws.session.store.cache.CacheStoreService.activateLazily(CacheStoreService.java:184)
[INFO] Tests compilation was successful.
[INFO]  at [internal classes]
[INFO]  at com.ibm.ws.session.store.cache.CacheHashMap$$Lambda$119.0000000000000000.run(Unknown Source)
[INFO]  at java.base/java.security.AccessController.doPrivileged(AccessController.java:678)
[INFO]  at com.ibm.ws.session.store.cache.CacheHashMap.<init>(CacheHashMap.java:133)
[INFO]  at [internal classes]
[INFO] Caused by: java.net.URISyntaxException: Illegal character in opaque part at index 30: file:C:/Tasks/CNAI/guides/test space/guide-sessions/finish/target/liberty/wlp/usr/servers/defaultServer/hazelcast-config.xml
[INFO]  at java.base/java.net.URI$Parser.fail(URI.java:2913)
[INFO]  at java.base/java.net.URI$Parser.checkChars(URI.java:3084)
[INFO]  at java.base/java.net.URI$Parser.parse(URI.java:3120)
[INFO]  at java.base/java.net.URI.<init>(URI.java:600)
[INFO]  at com.ibm.ws.session.store.cache.CacheStoreService.activateLazily(CacheStoreService.java:182)
[INFO]  ... 5 more
[INFO] .
```

**Comment by gkwan-ibm** [comment]
[messages.log](https://github.com/OpenLiberty/open-liberty/files/4617450/messages.log)
[ffdc_20.05.12_10.17.58.0.log](https://github.com/OpenLiberty/open-liberty/files/4617451/ffdc_20.05.12_10.17.58.0.log)
[ffdc_20.05.12_10.17.58.1.log](https://github.com/OpenLiberty/open-liberty/files/4617452/ffdc_20.05.12_10.17.58.1.log)

**Comment by gkwan-ibm** [comment]
ffdc showed:
SESN0300E: Invalid syntax in httpSessionCache URI.  Cause is java.net.URISyntaxException: Illegal character in opaque part at index 30: file:C:/Tasks/CNAI/guides/test space/guide-sessions/finish/target/liberty/wlp/usr/servers/defaultServer/hazelcast-config.xml.
