### ISSUE TITLE
MicroProfile: Metrics and FT don't work together

### ISSUE THREAD

**Issue by tevans78** [OpenLiberty/open-liberty#1229]
@davidcurrie hit this exception when trying to add @Metered to a class which also has a @Fallback method.

```
Stack Dump = org.jboss.weld.exceptions.DefinitionException: internal.error.CWMFT4999E
    at org.jboss.weld.bootstrap.events.ContainerLifecycleEvents.fireProcessAnnotatedType(ContainerLifecycleEvents.java:182)
    at org.jboss.weld.bootstrap.events.ContainerLifecycleEvents.fireProcessAnnotatedType(ContainerLifecycleEvents.java:166)
    at org.jboss.weld.bootstrap.BeanDeployer.processAnnotatedTypes(BeanDeployer.java:156)
    at org.jboss.weld.bootstrap.BeanDeployment.createTypes(BeanDeployment.java:245)
    at org.jboss.weld.bootstrap.WeldStartup.startInitialization(WeldStartup.java:407)
    at org.jboss.weld.bootstrap.WeldBootstrap.startInitialization(WeldBootstrap.java:76)
    at com.ibm.ws.cdi.impl.CDIContainerImpl$2.run(CDIContainerImpl.java:142)
    at com.ibm.ws.cdi.impl.CDIContainerImpl$2.run(CDIContainerImpl.java:139)
    at java.security.AccessController.doPrivileged(AccessController.java:638)
    at com.ibm.ws.cdi.impl.CDIContainerImpl.applicationStarting(CDIContainerImpl.java:139)
    at com.ibm.ws.cdi.liberty.CDIRuntimeImpl.applicationStarting(CDIRuntimeImpl.java:382)
    at com.ibm.ws.container.service.state.internal.ApplicationStateManager.fireStarting(ApplicationStateManager.java:28)
    at com.ibm.ws.container.service.state.internal.StateChangeServiceImpl.fireApplicationStarting(StateChangeServiceImpl.java:50)
    at com.ibm.ws.app.manager.module.internal.DeployedAppInfoBase.preDeployApp(DeployedAppInfoBase.java:380)
    at com.ibm.ws.app.manager.module.internal.DeployedAppInfoBase.deployApp(DeployedAppInfoBase.java:409)
    at com.ibm.ws.app.manager.war.internal.WARApplicationHandlerImpl.install(WARApplicationHandlerImpl.java:65)
    at com.ibm.ws.app.manager.internal.statemachine.StartAction.execute(StartAction.java:140)
    at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.enterState(ApplicationStateMachineImpl.java:1258)
    at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.run(ApplicationStateMachineImpl.java:873)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.lang.Thread.run(Thread.java:811)
Caused by: java.lang.RuntimeException: internal.error.CWMFT4999E
    at com.ibm.ws.microprofile.faulttolerance.cdi.AnnotatedTypeWrapper.<init>(AnnotatedTypeWrapper.java:47)
    at com.ibm.ws.microprofile.faulttolerance.cdi.FaultToleranceCDIExtension.addFaultToleranceAnnotation(FaultToleranceCDIExtension.java:170)
    at com.ibm.ws.microprofile.faulttolerance.cdi.FaultToleranceCDIExtension.processAnnotatedType(FaultToleranceCDIExtension.java:119)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
    at java.lang.reflect.Method.invoke(Method.java:508)
    at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:88)
    at org.jboss.weld.injection.MethodInvocationStrategy$SpecialParamPlusBeanManagerStrategy.invoke(MethodInvocationStrategy.java:144)
    at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:299)
    at org.jboss.weld.event.ExtensionObserverMethodImpl.sendEvent(ExtensionObserverMethodImpl.java:124)
    at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:277)
    at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:255)
    at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:269)
    at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:258)
    at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:166)
    at org.jboss.weld.bootstrap.events.ContainerLifecycleEvents.fireProcessAnnotatedType(ContainerLifecycleEvents.java:180)
    ... 21 more
```

**Comment by realModusOperandi** [comment]
Possibly the same issue I found in #380?

**Comment by tevans78** [comment]
Does indeed look similar ... I think a change is needed to the reflection code in `com.ibm.ws.microprofile.faulttolerance.cdi.AnnotatedTypeWrapper`
