### ISSUE TITLE
acmeCA-2.0: Workaround or fix intermittent Pebble start failures on Windows

### ISSUE THREAD

**Issue by kristip17** [OpenLiberty/open-liberty#12334]
On my Win10 box, I have probably at 20% fail rate running tests when the Pebble/Challenge Server/TestContainer startup fails with this obscure error.

No magic solution yet -- Stopping gradle, restarting Docker Desktop, restart my VPN, doing a try/catch/retry, adding retry counts/time to the TestContainer start, updating Docker Desktop. Since we don't see this on PBs, I assume it's something about Windows/Local Docker/VPN (maybe --although I think I saw it happen in the office). 

```
com/sun/jna/platform/win32/Kernel32

java.lang.NoClassDefFoundError: com/sun/jna/platform/win32/Kernel32
at com.github.dockerjava.okhttp.NamedPipeSocketFactory$1.connecct(NamedPipeSocketFactory.java:56)
at org.testcontainerss.shaded.okhttp3.internal.platform.Platform.connectSocket(Platform.java:130)
at org.testcontainers.shaded.okhhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:263)
at org.testcontainers.shaded.okhttp3.internal.connection.RealConnection.connect(RealConnection.java:183)
at org.testcontainers.shaded.okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:224)
at org.testcontainers.shaded.okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.jjava:108)
at org.testcontainers.shaded.okhttp3.interrnal.connection.ExchangeFinder.find(ExchangeFinder.java:88)
at org.testcontainers.shaded.okhttp3.internal.connecttion.Transmitter.newExchange(Transmitter.java:169)
at org.testcontainers.shaded.okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:411)
at org.testcontainers.shaded.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
at org.testcontainers.shaded.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:1117)
at org.testcontainers.shaded.okhttp3.internal.cache..CacheInterceptor.intercept(CacheInterceptor.java:94)
at org.testcontainers.shaded.okhttp3.internal.http.ReallInterceptorChain.proceed(RealInterceptorChain.java:142)
at org.testcontainers.shaded.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:1117)
at org.testcontainers.shaded.okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
at org.testcontainers.shaded.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
at org.testcontainers.shaded.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.jjava:88)
at org.testcontainers.shaded.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
at org.testcontainers.shaded.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
at org.testcontainers.shaded.okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
at org.testcontainers.shaded.okhttp33.RealCall.execute(RealCall.java:81)
at com.githuub.dockerjava.okhttp.OkHttpInvocationBuilder.execute(OkHttpInvocationBuilder.java:276)
at com.github.dockerjava.okhttp.OkHttpInvocationBuilder.execute(OkHttpInvocationBuilder.java:271)
at com.github.dockerjava.okhttp.OkHttpInvocationBuilder.get(OkHttpInvocationBuilder.java:239)
at com.github.dockerjava.okhttp.OkHttpInvocationBBuilder.get(OkHttpInvocationBuilder.java:89)
at ccom.github.dockerjava.core.exec.InspectContainerCmdExec.execute(InspectContainerCmdExec.java:31)
at com.github.dockerjava.core.exec.InspectContainerCmdExec.execute(InspectContainerCmdExec.java:113)
at com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21)
at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)
at com.github.dockerjava.core.command.InspectContainerCmdImpl.exec(InspectContainerCmdImpl.java:52)
at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:418)
at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:315)
at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:76)
at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:313)
at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:300)
at com.ibm.ws.security.acme.docker.pebble.PebbleContainer.<init>(PebbleContainer.java:82)
at com.ibm.ws.security.acme.fat.AcmeSimpleTest.beforeClasss(AcmeSimpleTest.java:89)
at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:318)
at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:1171)
Caused by: java.lang.ClassNotFoundException: com.sun.jna.platform.win32.Kernel32
at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at sun.misc.Launcher$AppClassLoaader.loadClass(Launcher.java:335)
at java.lang.ClassLoader.loaadClass(ClassLoader.java:357)
```

**Comment by kristip17** [comment]
Working better now with recent changes from #12386
