### ISSUE TITLE
The persistence_fat fails when running with Java 2 Security

### ISSUE THREAD

**Issue by daliasheasha** [OpenLiberty/open-liberty#1234]
The persistence_fat fails with the following error when it's run with java 2 security enabled:
```
Stack Dump = java.security.AccessControlException: Access denied ("java.io.FilePermission" "C:\Dev\Liberty\Git\CD\open-liberty\dev\build.image\wlp\usr\servers\com.ibm.ws.persistence.consumer.jpa21\static-orm.xml" "read")
	at java.security.AccessController.throwACE(AccessController.java:150)
	at java.security.AccessController.checkPermissionHelper(AccessController.java:222)
	at java.security.AccessController.checkPermissionDisableCallin(AccessController.java:264)
	at java.security.AccessController.checkPermission(AccessController.java:309)
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:562)
	at java.lang.SecurityManager.checkRead(SecurityManager.java:901)
	at java.io.File.isDirectory(File.java:855)
	at java.io.File.toURI(File.java:743)
	at com.ibm.wsspi.persistence.internal.util.PersistenceClassLoader.registerFileResource(PersistenceClassLoader.java:99)
	at com.ibm.wsspi.persistence.internal.PUInfoImpl.<init>(PUInfoImpl.java:77)
	at com.ibm.wsspi.persistence.internal.PersistenceServiceUnitImpl.<init>(PersistenceServiceUnitImpl.java:70)
	at com.ibm.wsspi.persistence.internal.PersistenceServiceImpl.createPersistenceServiceUnit(PersistenceServiceImpl.java:59)
	at persistence_fat.consumer.ConsumerService.createPersistenceServiceUnit(ConsumerService.java:210)
	at persistence_fat.consumer.ConsumerImpl.updateUnicodeConfig(ConsumerImpl.java:172)
	at persistence_fat.consumer.web.ConsumerServlet.testPersistUnicodeFilteredStringBoundaries(ConsumerServlet.java:80)
....
```

In Pull request: https://github.com/OpenLiberty/open-liberty/pull/1187/files, I disabled the persistence fat from running with Java 2 Security. However, the main issue needs to be investigated and resolved.

**Comment by tkburroughs** [comment]
@dazey3 Please take a look.
