### ISSUE TITLE
The jpa_22_fat fails when run with Java 2 Security

### ISSUE THREAD

**Issue by daliasheasha** [OpenLiberty/open-liberty#1235]
The jpa_22_fat fails with the following error when it's run with java 2 security enabled:

```
[12/4/17 16:44:14:937 CST] 00000032 SystemErr                                                    R javax.persistence.PersistenceException: java.security.AccessControlException: Access denied ("java.io.FilePermission" ".\createDDL.jdbc" "write")
	at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.deploy(EntityManagerSetupImpl.java:844)
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.getAbstractSession(EntityManagerFactoryDelegate.java:216)
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.createEntityManagerImpl(EntityManagerFactoryDelegate.java:324)
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.createEntityManagerImpl(EntityManagerFactoryImpl.java:348)
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.createEntityManager(EntityManagerFactoryImpl.java:329)
	at com.ibm.ws.jpa.container.v22.internal.JPA22Runtime.createEntityManagerInstance(JPA22Runtime.java:110)
	at com.ibm.ws.jpa.management.JPAEMPool.getEntityManager(JPAEMPool.java:155)
	at com.ibm.ws.jpa.management.JPATxEntityManager.getEMInvocationInfo(JPATxEntityManager.java:254)
	at com.ibm.ws.jpa.management.JPATxEntityManager.getEMInvocationInfo(JPATxEntityManager.java:164)
	at com.ibm.ws.jpa.management.JPAEntityManager.clear(JPAEntityManager.java:289)
	at cdi.web.ELIServlet.testInjectionOccursBeforePostConstructAndInsertionCallbacks(ELIServlet.java:69)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
...
```

In Pull request: https://github.com/OpenLiberty/open-liberty/pull/1187/files, I disabled the CDIFatServer test from from running with Java 2 Security. However, the main issue needs to be investigated and resolved.

**Comment by jgrassel** [comment]
Yeah, the problem's because I had set the ddl generation to "both" instead of "database" (only) in the CDI bucket.  I've included a fix for that in #1213
