### ISSUE TITLE
NullPointerException in LTPAConfiguration component

### ISSUE THREAD

**Issue by brenthdaniel** [OpenLiberty/open-liberty#12403]
A user reported the following exception:

```
[5/28/20 10:28:40:921 CDT] 00000013 LogService-65-com.ibm.ws.security.token.ltpa                 E CWWKE0701E: bundle com.ibm.ws.security.token.ltpa:1.0.40.cl200520200429-1655 (65)[com.ibm.ws.security.token.ltpa.LTPAConfiguration(391)] : The activate method has thrown an exception java.lang.NullPointerException
	at com.ibm.ws.security.token.ltpa.internal.LTPAConfigurationImpl.loadConfig(LTPAConfigurationImpl.java:115)
	at com.ibm.ws.security.token.ltpa.internal.LTPAConfigurationImpl.activate(LTPAConfigurationImpl.java:107)
```

The LTPAConfiguraton component is defined with configuration-policy "optional" but can't actually handle the case where it activates without configuration. Line 115 gets an NPE when it tries to unbox the null property into a primitive:

`        keyTokenExpiration = (Long) props.get(CFG_KEY_TOKEN_EXPIRATION);`

There is almost never a good reason to use configuration policy "optional", so the right fix here may be changing that to "required" rather than handling the case where the property is null.

**Comment by Emily-Jiang** [comment]
Another customer experienced this problem as well. It would be good to have it fixed soon! Thanks!

**Comment by utle** [comment]
Fixed by https://github.com/OpenLiberty/open-liberty/pull/14857
