### ISSUE TITLE
H2 NPE HttpOutputStreamImpl.flushHeaders

### ISSUE THREAD

**Issue by loriadi** [OpenLiberty/open-liberty#12537]
NPE when an error on another thread causes the resource to be cleaned up.
>at com.ibm.ws.http.channel.internal.outbound.HttpOutputStreamImpl.flushHeaders(HttpOutputStreamImpl.java:461)
>at com.ibm.ws.webcontainer31.osgi.response.IResponse31Impl.flushHeaders(IResponse31Impl.java:70)
>at com.ibm.ws.webcontainer31.srt.SRTServletResponse31.flushData(SRTServletResponse31.java:142)
>at com.ibm.ws.webcontainer31.srt.SRTServletResponse31.finishKeepConnection(SRTServletResponse31.java:107)
>at com.ibm.ws.webcontainer31.osgi.srt.SRTConnectionContext31.finishConnection(SRTConnectionContext31.java:152)
>at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:1166)
>at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:279)
>at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1134)
>at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:415)
>at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:374)
>at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:546)
>at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:480)
>at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:345)
>at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.ready(H

**Comment by loriadi** [comment]
Merged on 6/9/20
