### ISSUE TITLE
Test Failure: com.ibm.ws.logging.fat.CustomAccessLogFieldsTest.testFieldsInAccessLogAreSameInJSON

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#12589]
RTC 275245

```
testFieldsInAccessLogAreSameInJSON:java.lang.NullPointerException: 2020-06-11-13:33:49:132 null
at com.ibm.ws.logging.fat.CustomAccessLogFieldsTest.parseIntoKvp(CustomAccessLogFieldsTest.java:662)
at com.ibm.ws.logging.fat.CustomAccessLogFieldsTest.testFieldsInAccessLogAreSameInJSON(CustomAccessLogFieldsTest.java:317)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:197)
at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:318)
at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:171)
```

RTC 275272

```
testChangeJsonAccessLogFieldsConfigValue:java.lang.NullPointerException: 2020-06-12-10:02:22:390 null
at com.ibm.ws.logging.fat.CustomAccessLogFieldsTest.areFieldsPresent(CustomAccessLogFieldsTest.java:601)
at com.ibm.ws.logging.fat.CustomAccessLogFieldsTest.testChangeJsonAccessLogFieldsConfigValue(CustomAccessLogFieldsTest.java:355)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:197)
at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:318)
at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:171)
```

**Comment by jennifer-c** [comment]
Previous test failures were fixed with latest commit in #12598 - new test failure #link 275603

```
testChangeJsonAccessLogFieldsConfigValue:junit.framework.AssertionFailedError: 2020-06-22-06:52:37:963 There are fields missing in the output JSON log.
at com.ibm.ws.logging.fat.CustomAccessLogFieldsTest.testChangeJsonAccessLogFieldsConfigValue(CustomAccessLogFieldsTest.java:385)
at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:197)
at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:318)
at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:171)
```
