### ISSUE TITLE
com.ibm.ws.jaxrs.2.0_fat failures with jaxrs-3.0

### ISSUE THREAD

**Issue by jim-krueger** [OpenLiberty/open-liberty#12672]
The purpose of this issue is to document FAT failures encountered running with the new RestEasy Implementation.

**Comment by jim-krueger** [comment]
Related to #12217

**Comment by jim-krueger** [comment]
#11803

**Comment by jim-krueger** [comment]
Failed Test:  com.ibm.ws.jaxrs20.fat.annotationscan.AnnotationScanTest
Failure:RESTEASY002005: Failed executing GET /
org.jboss.resteasy.core.NoMessageBodyWriterFoundFailure: Could not find MessageBodyWriter for response object of type: java.lang.String of media type: application/octet-stream

**Comment by jim-krueger** [comment]
2. fat.test.class.name=com.ibm.ws.jaxrs20.fat.beanparam.BeanParamTest

(added several lines for java2 security)
  	<javaPermission className="java.util.PropertyPermission" name="java.home" actions="read"/>
  	<javaPermission className="java.util.PropertyPermission" name="javax.ws.rs.client.ClientBuilder" actions="read"/>
  	<javaPermission className="java.io.FilePermission" name="/Library/Java/JavaVirtualMachines/jdk1.8.0_231.jdk/Contents/Home/jre/lib/jaxrs.properties" actions="read"/>

Failure after those additions:
E SRVE0271E: Uncaught init() exception created by servlet [com.ibm.ws.jaxrs.fat.beanparam.ClientTestServlet] in application [beanparam]: java.lang.RuntimeException: java.lang.ClassNotFoundException: org.glassfish.jersey.client.JerseyClientBuilder cannot be found by com.ibm.websphere.javaee.jaxrs.2.1_1.0.42.202006170836
	at javax.ws.rs.client.ClientBuilder.newBuilder(ClientBuilder.java:110)
	at javax.ws.rs.client.ClientBuilder.newClient(ClientBuilder.java:121)
	at com.ibm.ws.jaxrs.fat.beanparam.ClientTestServlet.init(ClientTestServlet.java:40)

**Comment by jim-krueger** [comment]
3) com.ibm.ws.jaxrs20.fat.beanvalidation.JAXRSClientServerValidationTest

Uses CDI... so wait for that.

**Comment by jim-krueger** [comment]
4)  com.ibm.ws.jaxrs20.fat.bookcontinuationstore.JAXRSContinuationsTest

`E RESTEASY002010: Failed to execute
javax.ws.rs.ServiceUnavailableException: HTTP 503 Service Unavailable
	at org.jboss.resteasy.plugins.server.servlet.Servlet3AsyncHttpRequest$Servlet3ExecutionContext$Servle3AsychronousResponse.handleTimeout(Servlet3AsyncHttpRequest.java:261)
	at org.jboss.resteasy.plugins.server.servlet.Servlet3AsyncHttpRequest$Servlet3ExecutionContext$Servle3AsychronousResponse$1.run(Servlet3AsyncHttpRequest.java:151)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
`

**Comment by jim-krueger** [comment]
5) com.ibm.ws.jaxrs20.fat.bookstore.JAXRS20ClientServerBookTest

`[6/18/20` 10:37:39:895 CDT] 0000002c com.ibm.ws.webcontainer.servlet                              E SRVE0271E: Uncaught init() exception created by servlet [com.ibm.ws.jaxrs20.fat.bookstore.BookApplication] in application [bookstore]: java.lang.RuntimeException: RESTEASY003405: It is illegal to inject a @PathParam into a singleton
	at org.jboss.resteasy.core.PathParamInjector.inject(PathParamInjector.java:137)
	at org.jboss.resteasy.core.ResourcePropertyInjector.inject(ResourcePropertyInjector.java:152)
	at org.jboss.resteasy.plugins.server.resourcefactory.SingletonResource.registered(SingletonResource.java:36)
	at org.jboss.resteasy.core.ResourceMethodRegistry.addResourceFactory(ResourceMethodRegistry.java:246)
	at org.jboss.resteasy.core.ResourceMethodRegistry.addResourceFactory(ResourceMethodRegistry.java:227)
	at org.jboss.resteasy.core.ResourceMethodRegistry.addResourceFactory(ResourceMethodRegistry.java:208)
	at org.jboss.resteasy.core.ResourceMethodRegistry.addResourceFactory(ResourceMethodRegistry.java:192)
	at org.jboss.resteasy.core.ResourceMethodRegistry.addResourceFactory(ResourceMethodRegistry.java:175)
	at org.jboss.resteasy.core.ResourceMethodRegistry.addSingletonResource(ResourceMethodRegistry.java:114)
	at org.jboss.resteasy.core.ResteasyDeploymentImpl.registerResources(ResteasyDeploymentImpl.java:578)
	at org.jboss.resteasy.core.ResteasyDeploymentImpl.registration(ResteasyDeploymentImpl.java:470)
	at org.jboss.resteasy.core.ResteasyDeploymentImpl.startInternal(ResteasyDeploymentImpl.java:160)
	at org.jboss.resteasy.core.ResteasyDeploymentImpl.start(ResteasyDeploymentImpl.java:117)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.init(ServletContainerDispatcher.java:144)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.init(HttpServletDispatcher.java:42)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.init(ServletWrapper.java:291)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.loadOnStartupCheck(ServletWrapper.java:1373)
	at com.ibm.ws.webcontainer.webapp.WebApp.doLoadOnStartupActions(WebApp.java:1197)
	at com.ibm.ws.webcontainer.webapp.WebApp.commonInitializationFinally(WebApp.java:1165)
	at com.ibm.ws.webcontainer.webapp.WebApp.initialize(WebApp.java:1063)
	at com.ibm.ws.webcontainer.webapp.WebApp.initialize(WebApp.java:6663)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost.startWebApp(DynamicVirtualHost.java:467)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost.startWebApplication(DynamicVirtualHost.java:462)
	at com.ibm.ws.webcontainer.osgi.WebContainer.startWebApplication(WebContainer.java:1175)
	at com.ibm.ws.webcontainer.osgi.WebContainer.startModule(WebContainer.java:967)
	at com.ibm.ws.app.manager.module.internal.ModuleHandlerBase.deployModule(ModuleHandlerBase.java:99)
	at com.ibm.ws.app.manager.module.internal.DeployedModuleInfoImpl.installModule(DeployedModuleInfoImpl.java:49)
	at com.ibm.ws.app.manager.module.internal.SimpleDeployedAppInfoBase.deployModules(SimpleDeployedAppInfoBase.java:597)
	at com.ibm.ws.app.manager.module.internal.SimpleDeployedAppInfoBase.installApp(SimpleDeployedAppInfoBase.java:511)
	at com.ibm.ws.app.manager.module.internal.DeployedAppInfoBase.deployApp(DeployedAppInfoBase.java:347)
	at com.ibm.ws.app.manager.war.internal.WARApplicationHandlerImpl.install(WARApplicationHandlerImpl.java:65)
	at com.ibm.ws.app.manager.internal.statemachine.StartAction.execute(StartAction.java:144)
	at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.enterState(ApplicationStateMachineImpl.java:1315)
	at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.run(ApplicationStateMachineImpl.java:897)
	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:239)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by jim-krueger** [comment]
6.  com.ibm.ws.jaxrs20.fat.callback.JAXRS20CallBackTest

`Caused by: java.lang.ClassNotFoundException: org.glassfish.jersey.client.JerseyClientBuilder cannot be found by com.ibm.websphere.javaee.jaxrs.2.1_1.0.42.202006170836`

**Comment by jim-krueger** [comment]
Problems:
**AnnotationScanTest**
Having problems finding IBMRestServlet.  Andy's recent changes applied.  Will need further investigation.

**BeanParamTest**
java.lang.ClassNotFoundException: org.glassfish.jersey.client.JerseyClientBuilder cannot be found by com.ibm.websphere.javaee.jaxrs.2.1_1.0.43.202007151150

**Comment by jim-krueger** [comment]
HelloWorldTest:  1 failure (testSimpleWithEncodedURL).   Resteasy doesn't handle encoded ApplicationPath, however an encoded Path on the resource method works fine.

**Comment by jim-krueger** [comment]
https://github.com/OpenLiberty/open-liberty/pull/14091  (first pass... skips tests that currently fail).

**Comment by jim-krueger** [comment]
No longer needed
