### ISSUE TITLE
JAX-RS 2.1 TCK tests fail when the server has trace enabled.

### ISSUE THREAD

**Issue by jkoehler22** [OpenLiberty/open-liberty#12693]
server.xml:
```
<?xml version="1.0" encoding="UTF-8"?>
<server description="new server">

    <!-- Enable features -->
    <featureManager>
        <feature>jsp-2.3</feature>      
        <feature>jaxrs-2.1</feature>
        <feature>jaxb-2.2</feature> 
    </featureManager>

    <!-- To access this server from a remote client add a host attribute to the following element, e.g. host="*" -->
    <httpEndpoint id="defaultHttpEndpoint"
                  httpPort="9080"
                  httpsPort="9443" />

	<!-- Automatically expand WAR files and EAR files -->
	<applicationManager autoExpand="true"/>
        

    <logging consoleLogLevel="INFO" traceSpecification="com.ibm.ws.jaxrs*=all:org.apache.cxf.*=all:com.ibm.websphere.jaxrs*=all"/>
    <logging maxFileSize="0"/>
</server>

```
message.log:
```
[6/18/20 7:55:56:500 EDT] 00000067 com.ibm.ws.webcontainer.util.ApplicationErrorUtils           E SRVE0777E: Exception thrown by application class 'com.ibm.ws.logging.internal.impl.BaseTraceService.publishTraceLogRecord:1,005'
java.lang.StackOverflowError
	at com.ibm.ws.logging.internal.impl.BaseTraceService.publishTraceLogRecord(BaseTraceService.java:1005)
	at com.ibm.ws.logging.internal.impl.BaseTraceService.publishLogRecord(BaseTraceService.java:976)
	at com.ibm.ws.logging.internal.impl.BaseTraceService$2.publish(BaseTraceService.java:281)
	at java.util.logging.Logger.log(Logger.java:749)
	at com.ibm.ws.logging.internal.WsLogger.log(WsLogger.java:140)
	at com.ibm.ws.logging.internal.WsLogger.logp(WsLogger.java:338)
	at com.ibm.ws.logging.internal.WsLogger.entering(WsLogger.java:445)
	at org.apache.cxf.phase.PhaseInterceptorChain.getCurrentMessage(PhaseInterceptorChain.java:163)
	at org.apache.cxf.jaxrs.impl.CacheControlHeaderProvider.getCurrentMessage(CacheControlHeaderProvider.java:238)
	at org.apache.cxf.jaxrs.impl.CacheControlHeaderProvider.getSeparator(CacheControlHeaderProvider.java:223)
	at org.apache.cxf.jaxrs.impl.CacheControlHeaderProvider.toString(CacheControlHeaderProvider.java:137)
	at org.apache.cxf.jaxrs.impl.CacheControlHeaderProvider.toString(CacheControlHeaderProvider.java:37)
	at javax.ws.rs.core.CacheControl.toString(CacheControl.java:359)
	at java.lang.String.valueOf(String.java:3422)
	at java.lang.StringBuilder.append(StringBuilder.java:516)
	at java.util.AbstractCollection.toString(AbstractCollection.java:473)
	at java.lang.String.valueOf(String.java:3422)
	at java.lang.StringBuilder.append(StringBuilder.java:516)
	at java.util.AbstractMap.toString(AbstractMap.java:570)
	at org.apache.cxf.jaxrs.impl.MetadataMap.toString(MetadataMap.java:225)
	at java.lang.String.valueOf(String.java:3422)
	at java.lang.StringBuilder.append(StringBuilder.java:516)
	at org.apache.cxf.message.MessageImpl.toString(MessageImpl.java:1399)
	at java.text.MessageFormat.subformat(MessageFormat.java:1291)
	at java.text.MessageFormat.format(MessageFormat.java:876)
	at java.text.Format.format(Format.java:168)
	at java.text.MessageFormat.format(MessageFormat.java:852)
	at com.ibm.ws.logging.internal.impl.BaseTraceFormatter.formatMessage(BaseTraceFormatter.java:301)
	at com.ibm.ws.logging.internal.impl.BaseTraceFormatter.formatVerboseMessage(BaseTraceFormatter.java:373)
	at com.ibm.ws.logging.internal.impl.BaseTraceService.publishTraceLogRecord(BaseTraceService.java:1005)
	at com.ibm.ws.logging.internal.impl.BaseTraceService.publishLogRecord(BaseTraceService.java:976)
	at com.ibm.ws.logging.internal.impl.BaseTraceService$2.publish(BaseTraceService.java:281)
	at java.util.logging.Logger.log(Logger.java:749)
	at com.ibm.ws.logging.internal.WsLogger.log(WsLogger.java:140)
	at com.ibm.ws.logging.internal.WsLogger.logp(WsLogger.java:338)
	at com.ibm.ws.logging.internal.WsLogger.exiting(WsLogger.java:467)
	at org.apache.cxf.phase.PhaseInterceptorChain.getCurrentMessage(PhaseInterceptorChain.java:163)
	at org.apache.cxf.jaxrs.impl.CacheControlHeaderProvider.getCurrentMessage(CacheControlHeaderProvider.java:238)
	at org.apache.cxf.jaxrs.impl.CacheControlHeaderProvider.getSeparator(CacheControlHeaderProvider.java:223)
	at org.apache.cxf.jaxrs.impl.CacheControlHeaderProvider.toString(CacheControlHeaderProvider.java:137)
	at org.apache.cxf.jaxrs.impl.CacheControlHeaderProvider.toString(CacheControlHeaderProvider.java:37)
	at javax.ws.rs.core.CacheControl.toString(CacheControl.java:359)
	at java.lang.String.valueOf(String.java:3422)
	at java.lang.StringBuilder.append(StringBuilder.java:516)
	at java.util.AbstractCollection.toString(AbstractCollection.java:473)
	at java.lang.String.valueOf(String.java:3422)
	at java.lang.StringBuilder.append(StringBuilder.java:516)
	at java.util.AbstractMap.toString(AbstractMap.java:570)
	at org.apache.cxf.jaxrs.impl.MetadataMap.toString(MetadataMap.java:225)
	at java.lang.String.valueOf(String.java:3422)
	at java.lang.StringBuilder.append(StringBuilder.java:516)
	at org.apache.cxf.message.MessageImpl.toString(MessageImpl.java:1399)
	at java.text.MessageFormat.subformat(MessageFormat.java:1291)
	at java.text.MessageFormat.format(MessageFormat.java:876)
	at java.text.Format.format(Format.java:168)
	at java.text.MessageFormat.format(MessageFormat.java:852)
	at com.ibm.ws.logging.internal.impl.BaseTraceFormatter.formatMessage(BaseTraceFormatter.java:301)
```
Possible solution:
add  a `@Trivial` for `CacheControlHeaderProvider.toString`

**Comment by andymc12** [comment]
fixed by #12712
