### ISSUE TITLE
Test Failure: com.ibm.ws.logging.fat.CustomAccessLogFieldsTest.testInvalidTokens

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#12819]
RTC  275735

```
testInvalidTokens:junit.framework.AssertionFailedError: 2020-06-23-02:47:45:010 [Unexpected FFDC reporting java.lang.Exception was found (count = 1): /home/jazz_build/Build/jbe/build/dev/image/output/wlp/usr/servers/CustomAccessLogFieldsXml/logs/ffdc/ffdc_20.06.23_02.47.41.0.log
>------Start of DE processing------ = [6/23/20, 2:47:41:115 PDT]
>Exception = java.lang.Exception
>Source = com.ibm.ws.webcontainer.osgi.WebContainer$3
>probeid = startModule async
>Stack Dump = java.lang.Exception: startWebApplication async
> at com.ibm.ws.webcontainer.osgi.WebContainer$3.run(WebContainer.java:976)
> at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:239)
> at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
> at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
> at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
> at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
> at java.base/java.lang.Thread.run(Thread.java:832)
]
at componenttest.custom.junit.runner.FATRunner.blowup(FATRunner.java:300)
at componenttest.custom.junit.runner.FATRunner.access$600(FATRunner.java:66)
at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:250)
at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:318)
at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:171)
```

**Comment by jennifer-c** [comment]
Closing due to no reoccurrence in last SOE (07/10) due to #12836
