### ISSUE TITLE
Facing null pointer exception while EJB client is de-serializing  the array object

### ISSUE THREAD

**Issue by vivekbajpai** [OpenLiberty/open-liberty#13114]
There is ejb server running on Liberty, client is also running on separate liberty server, ejb server is serving ejb client request by sending ArrayList of custom class objects.

There is no error on liberty ejb server side, but facing NPE on ejb client side during de-serializing of ArrayList with following stack trace.

java.lang.NullPointerException
      at org.apache.yoko.rmi.impl.ValueDescriptor.defaultReadValue(ValueDescriptor.java:649)
      at org.apache.yoko.rmi.impl.ValueDescriptor.readSerializable(ValueDescriptor.java:750)
      at org.apache.yoko.rmi.impl.ValueDescriptor.readValue(ValueDescriptor.java:732)
      at org.apache.yoko.rmi.impl.ValueDescriptor.readValue(ValueDescriptor.java:583)
      at org.apache.yoko.rmi.impl.ValueHandlerImpl.readValue0(ValueHandlerImpl.java:138)
      at org.apache.yoko.rmi.impl.ValueHandlerImpl.readValue(ValueHandlerImpl.java:106)
      at org.apache.yoko.orb.OB.ValueReader.readRMIValue(ValueReader.java:955)
      at org.apache.yoko.orb.OB.ValueReader.access$200(ValueReader.java:57)
      at org.apache.yoko.orb.OB.ValueReader$FactoryCreationStrategy.create(ValueReader.java:292)
      at org.apache.yoko.orb.OB.ValueReader$FactoryCreationStrategy.create(ValueReader.java:285)
      at org.apache.yoko.orb.OB.ValueReader.read(ValueReader.java:780)
      at org.apache.yoko.orb.OB.ValueReader.readValue(ValueReader.java:1037)
      at org.apache.yoko.orb.OB.ValueReader.readAbstractInterface(ValueReader.java:1104)
      at org.apache.yoko.orb.CORBA.InputStream.read_abstract_interface(InputStream.java:1450)
      at org.apache.yoko.rmi.impl.CorbaObjectReader.readAbstractObject(CorbaObjectReader.java:147)
      at org.apache.yoko.rmi.impl.ObjectReaderBase.readObjectOverride(ObjectReader.java:83)
      at org.apache.yoko.rmi.impl.DelegatingObjectReader.readObjectOverride0(DelegatingObjectReader.java:26)
      at org.apache.yoko.rmi.impl.CustomMarshaledObjectReader.readObjectOverride(CustomMarshaledObjectReader.java:124)
      at java.io.ObjectInputStream.readObjectImpl(ObjectInputStream.java:542)
      at java.io.ObjectInputStream.readObject(ObjectInputStream.java:474)
      at java.util.ArrayList.readObject(ArrayList.java:808)
      at sun.reflect.GeneratedMethodAccessor72.invoke(Unknown Source)
      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
      at java.lang.reflect.Method.invoke(Method.java:508)
      at org.apache.yoko.rmi.impl.ValueDescriptor.readSerializable(ValueDescriptor.java:740)
      at org.apache.yoko.rmi.impl.ValueDescriptor.readValue(ValueDescriptor.java:725)
      at org.apache.yoko.rmi.impl.ValueDescriptor.readValue(ValueDescriptor.java:583)
      at org.apache.yoko.rmi.impl.ValueHandlerImpl.readValue0(ValueHandlerImpl.java:138)
      at org.apache.yoko.rmi.impl.ValueHandlerImpl.readValue(ValueHandlerImpl.java:106)
      at org.apache.yoko.orb.OB.ValueReader.readRMIValue(ValueReader.java:955)
      at org.apache.yoko.orb.OB.ValueReader.access$200(ValueReader.java:57)
      at org.apache.yoko.orb.OB.ValueReader$ClassCreationStrategy.create(ValueReader.java:184)
      at org.apache.yoko.orb.OB.ValueReader.read(ValueReader.java:780)
      at org.apache.yoko.orb.OB.ValueReader.readValue(ValueReader.java:1056)
      at org.apache.yoko.orb.CORBA.InputStream.read_value(InputStream.java:1433 

**Describe the bug**

If there is a stack trace, please include the FULL stack trace (without any `[internal classes]` lines in it). To find the full stack trace, you may need to check in `$WLP_OUTPUT_DIR/messages.log`

**Steps to Reproduce**
Steps to reproduce the bug

**Expected behavior**

**Diagnostic information:**
 - OpenLiberty Version: [e.g. 19.0.0.8]
 - Java Version: [i.e. full output of `java -version`]
 - server.xml configuration (WITHOUT sensitive information like passwords)
 - If it would be useful, upload the messages.log file found in `$WLP_OUTPUT_DIR/messages.log`

**Additional context**

**Comment by vivekbajpai** [comment]
Adding more info.
EJB client and Server are docker containers, having base image as IBM java.
All containers have same liberty and Java versions,
Liberty Version:20.0.0.6
java version "1.8.0_251"
Java(TM) SE Runtime Environment (build 8.0.6.11 - pxa6480sr6fp11-20200602_01(SR6 FP11))
IBM J9 VM (build 2.9, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20200601_448156 (JIT enabled, AOT enabled)
OpenJ9   - 6c940fd
OMR      - 91c4c01
IBM      - 19f2e5e)
JCL - 20200520_01 based on Oracle jdk8u251-b08

**Comment by chackoj** [comment]
It looks like there is a mismatch between the client and server versions of a class that is being marshalled over IIOP. The immediate fix is to ensure both sides of the communication are using identical (rather than merely _compatible_) versions of serializable classes.

There are a few pitfalls in marshalling between evolved versions of a class, and this error is one of them. A good interim solution is to update the Yoko ORB used by Liberty so that these errors helpfully direct users to the root cause by identifying the class(es) that have differing versions.

**Comment by vivekbajpai** [comment]
Yes Correct, there was mismatch of object between client and server.  I got this working.
Thanks you all, for very quick response, and suggestion. 
Since I got it working.
I am closing this defect.
Thanks again
