### ISSUE TITLE
EJB Custom Bindings: Remove ignoreDuplicateEJBBindings config attribute

### ISSUE THREAD

**Issue by olendvcook** [OpenLiberty/open-liberty#13161]
While working on #8232 I discovered that the ddparser code in OL will not let you have duplicate bindings in `ejb-jar-bnd.xml` or `ejb-jar-bnd.xmi` and fail application start with an error like this:

```
com.ibm.ws.javaee.ddmodel.DDParser$ParseException: CWWKC2269E: The name attribute for all <session> and <message-driven> bean elements must be unique. Found duplicate name ConfigTestsTestBean1 in the META-INF/ibm-ejb-jar-bnd.xml deployment descriptor.
	at com.ibm.ws.javaee.ddmodel.ejbbnd.EJBJarBndType.finish(EJBJarBndType.java:157)
	at com.ibm.ws.javaee.ddmodel.DDParser.parse(DDParser.java:666)
	at com.ibm.ws.javaee.ddmodel.DDParser.parseRootElement(DDParser.java:581)
	at com.ibm.ws.javaee.ddmodel.ejbbnd.EJBJarBndDDParser.parse(EJBJarBndDDParser.java:27)
	at com.ibm.ws.javaee.ddmodel.ejbbnd.EJBJarBndAdapter.adapt(EJBJarBndAdapter.java:71)
``` 

We have decided that rather than changing the DDParser code to allow duplicate bindings and implement this config attribute, we will just take it out and revisit this if many customers hit this and complain. The workaround is just to remove the duplicate bindings.

**Comment by olendvcook** [comment]
merged
