### ISSUE TITLE
Test Failure: componenttest.application.manager.test.FATTest.testStartStopFromXml

### ISSUE THREAD

**Issue by hlhoots** [OpenLiberty/open-liberty#13198]
testStartStopFromXml:junit.framework.AssertionFailedError: 2020-06-18-08:10:05:598 [Unexpected FFDC reporting java.io.FileNotFoundException was found (count = 1): /home/jazz_build/_nvvwULEsEeqCjdhsjSafyw-EBC.PROD.WASRTC-6I0-000-00-00/jbe/build/dev/image/output/wlp/usr/servers/appManagerTestServer/logs/ffdc/ffdc_20.06.18_08.10.02.0.log
>------Start of DE processing------ = [6/18/20 8:10:02:769 UTC]
>Exception = java.io.FileNotFoundException
>Source = com.ibm.ws.classloading.java2sec.PermissionManager
>probeid = 776
>Stack Dump = java.io.FileNotFoundException: /home/jazz_build/_nvvwULEsEeqCjdhsjSafyw-EBC.PROD.WASRTC-6I0-000-00-00/jbe/build/dev/image/output/wlp/usr/servers/appManagerTestServer/apps/snoop.war (Is a directory)
>at java.base/java.io.RandomAccessFile.open0(Native Method)
>at java.base/java.io.RandomAccessFile.open(RandomAccessFile.java:345)
>at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:259)
>at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:214)
>at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1271)
>at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1237)
>at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:727)
>at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:844)
>at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:247)
>at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:177)
>at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:148)
>at com.ibm.ws.classloading.java2sec.PermissionManager.RecursiveFind(PermissionManager.java:774)
>at com.ibm.ws.classloading.java2sec.PermissionManager.addPermissionsXMLPermission(PermissionManager.java:690)
>at com.ibm.ws.app.manager.module.internal.DeployedAppInfoBase.addPermissions(DeployedAppInfoBase.java:464)
>at com.ibm.ws.app.manager.module.internal.DeployedAppInfoBase.getProtectionDomain(DeployedAppInfoBase.java:404)
>at com.ibm.ws.app.manager.war.internal.WARDeployedAppInfo.createModuleClassLoader(WARDeploye

**Comment by hlhoots** [comment]
Looks to be a test case bug.  The test expects a FileNotFoundException, but doesn't account for the FFDC processing that sees the exception and generates a failure.

catch (java.io.FileNotFoundException ex) {
                //expected if the web container has unloaded the page already (it could be blank or not there)
            }
