### ISSUE TITLE
NPE during MyFaces Resource Handling 

### ISSUE THREAD

**Issue by volosied** [OpenLiberty/open-liberty#13739]
Customer  is  reporting of a NPE when MyFaces is handling a resource.

java.lang.NullPointerException
	at javax.faces.application.ResourceWrapper.userAgentNeedsUpdate(ResourceWrapper.java:74) 
  at ResourceHandlerImpl.java:610)
	at javax.faces.application.ResourceHandlerWrapper.handleResourceRequest(ResourceHandlerWrapper.java:72)
	at org.primefaces.application.resource.PrimeResourceHandler.handleResourceRequest(PrimeResourceHandler.java:96)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:196)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1230)

I'm creating this issue to tag a OLGH issue when creating a debug module.

**Comment by volosied** [comment]
Customer resolved this issue on their own.  May have been related to the Dynatrace monitoring tool , but it's not confirmed.
