### ISSUE TITLE
A javax.naming Exception is thrown from a NamingManager.getObjectInstance() call.

### ISSUE THREAD

**Issue by chackoj** [OpenLiberty/open-liberty#13828]
We have a servlet that uses a new InitialContext() to bind a string value to a name and then look that value up again (using the same InitialContext object). This works without any problem unless we enable the blueprint-1.0 feature in that server, in which case it fails with an InvalidNameException from Aries.

**Comment by sebratton** [comment]
A new version of open source aries jndi packaged by Open Liberty had changed so that it threw an exception during normal processing where previously it had not. This resuts in liberty sometimes throwing an exception from a call NamingManager.getObjectInstance(), rather than proceeding. This issue is to fix that change in aries.

A typical failure call stack when this failure occurs is:

javax.naming.InvalidNameException: Name                                                                                
	at org.apache.aries.jndi.url.OsgiNameParser.parse(OsgiNameParser.java:46)                                              
	at org.apache.aries.jndi.url.ServiceRegistryContext.parse(ServiceRegistryContext.java:134)                             
	at org.apache.aries.jndi.url.ServiceRegistryContext.lookup(ServiceRegistryContext.java:138)                            
	at org.apache.aries.jndi.url.OsgiURLContextFactory.findAny(OsgiURLContextFactory.java:70)                              
	at org.apache.aries.jndi.url.OsgiURLContextFactory.getObjectInstance(OsgiURLContextFactory.java:49)                    
	at org.apache.aries.jndi.ObjectFactoryHelper.getObjectFromFactory(ObjectFactoryHelper.java:260)                        
	at org.apache.aries.jndi.ObjectFactoryHelper.getObjectInstanceUsingObjectFactories(ObjectFactoryHelper.java:123)       
	at org.apache.aries.jndi.ObjectFactoryHelper.doGetObjectInstance(ObjectFactoryHelper.java:99)                          
	at org.apache.aries.jndi.ObjectFactoryHelper.lambda$getObjectInstance$0(ObjectFactoryHelper.java:62)                   
	at org.apache.aries.jndi.ObjectFactoryHelper$$Lambda$19/000000008EF85C30.call(Unknown Source)                          
	at org.apache.aries.jndi.Utils.doPrivilegedE(Utils.java:158)                                                           
	at org.apache.aries.jndi.ObjectFactoryHelper.getObjectInstance(ObjectFactoryHelper.java:62)                            
	at org.apache.aries.jndi.OSGiObjectFactoryBuilder.getObjectInstance(OSGiObjectFactoryBuilder.java:66)                  
	at org.apache.aries.jndi.OSGiObjectFactoryBuilder.getObjectInstance(OSGiObjectFactoryBuilder.java:48)                  
	at javax.naming.spi.NamingManager.getObjectInstance(NamingManager.java:311)          
         …
