### ISSUE TITLE
Investigate Faces-3.0 testViewParamNotNull_EE9_FEATURES Failure

### ISSUE THREAD

**Issue by volosied** [OpenLiberty/open-liberty#13887]
dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23ViewParametersTests.java 

testViewParamNotNull_EE9_FEATURES -- Test is Skipped for Now

```
2020-09-10-19:10:02:047 The validation message was not displayed.

junit.framework.AssertionFailedError: 2020-09-10-19:10:02:047 The validation message was not displayed.
at com.ibm.ws.jsf23.fat.tests.JSF23ViewParametersTests.testViewParamNotNull(JSF23ViewParametersTests.java:89)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:197)
at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:318)
at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:171)
at componenttest.rules.repeater.RepeatTests$CompositeRepeatTestActionStatement.evaluate(RepeatTests.java:115) 
```

**Comment by volosied** [comment]
Failure cause by missing rule: 
`javax.faces.INTERPRET_EMPTY_STRING_SUBMITTED_VALUES_AS_NULL=jakarta.faces.INTERPRET_EMPTY_STRING_SUBMITTED_VALUES_AS_NULL`
