### ISSUE TITLE
Investigate Faces-3.0 testExternalContextGetRealPath_Startup_Shutdown_EE9_FEATURES Failure

### ISSUE THREAD

**Issue by volosied** [OpenLiberty/open-liberty#13888]
fat/src/com/ibm/ws/jsf23/fat/tests/JSF23ExternalContextStartupShutdownTests.java 

testExternalContextGetRealPath_Startup_Shutdown_EE9_FEATURES -- Test is Skipped for Now

```
2020-09-10-19:07:29:919 The following message was not found: .*JSF23: PreDestroyApplicationEvent getRealPath test:.*

junit.framework.AssertionFailedError: 2020-09-10-19:07:29:919 The following message was not found: .*JSF23: PreDestroyApplicationEvent getRealPath test:.*
at com.ibm.ws.jsf23.fat.tests.JSF23ExternalContextStartupShutdownTests.testExternalContextGetRealPath_Startup_Shutdown(JSF23ExternalContextStartupShutdownTests.java:104)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:197)
at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:318)
at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:171)
at componenttest.rules.repeater.RepeatTests$CompositeRepeatTestActionStatement.evaluate(RepeatTests.java:115) 
```

**Comment by volosied** [comment]
Failure caused by missing rule:
`javax.faces.event.PreDestroyApplicationEvent=jakarta.faces.event.PreDestroyApplicationEvent`
