### ISSUE TITLE
Liberty java security function does not honor JDK's java.policy file.

### ISSUE THREAD

**Issue by jhanders34** [OpenLiberty/open-liberty#13908]
**Describe the bug**
Applications get AccessControlExceptions for permissions that are granted in the JDK's java.policy file.

java.security.AccessControlException: Access denied ("java.util.PropertyPermission" "java.specification.version" "read")
	at java.security.AccessController.throwACE(AccessController.java:176)
	at java.security.AccessController.checkPermissionHelper(AccessController.java:238)
	at java.security.AccessController.checkPermission(AccessController.java:385)
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:562)
	at java.lang.SecurityManager.checkPropertyAccess(SecurityManager.java:1307)
	at java.lang.System.getProperty(System.java:477)
	at java.lang.System.getProperty(System.java:460)
	at app1.web.TestServletA.basicTest(TestServletA.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at componenttest.app.FATServlet.doGet(FATServlet.java:71)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)

**Steps to Reproduce**
I updated the basicTest in the build.example_fat Servlet to add:
```
System.getProperty("java.specification.version");
```

**Expected behavior**
I expect that if an application does a System.getProperty on properties that they are granted in the JDK's java.policy, they should succeed unless restricted by configuration in the application or in the server.xml.

**Diagnostic information:**
 - OpenLiberty Version: 20.0.0.9

**Additional context**
The reason I found this issue is that I updated a FAT's servlet to use a property that is granted in the JDK's java.policy.  In order to get the test to pass with java security enabled I needed to add a permission to the server.xml.  I found similar permissions in other server.xml's for permissions granted in the JDK's java.policy.  I think the FAT server.xml's should be cleaned up for those permissions as part of this issue.  I am willing to help with a PR to do that.

I was able to get this work by making some changes to the way that application permission checking is done.  I have added those changes in a branch here:  https://github.com/OpenLiberty/open-liberty/compare/integration...jhanders34:perf-improvement6?expand=1.  I have some concerns that the change in this branch could have some performance implications since we will now be populating code sources with all the permissions from the JDK's java.policy files.  I can foresee that there could be a footprint impact.

I have discussed this bug with @emilytee.  She asked me to open this issue to track the bug.

**Comment by jhanders34** [comment]
Doing a quick group I see these particular properties in server.xml files and the number of files that have them.
```
    150 "*"
      7 "java.specification.version"
      3 "java.vendor"
      4 "java.version"
      9 "line.separator"
      3 "os.arch"
      4 "os.name"
      3 "os.version"
```

**Comment by jhanders34** [comment]
Emily took my changes and created a PR with them and I have verified that the PR mentioned above resolves the error I was seeing.  I am closing out this issue since it is now resolved.

**Comment by jhanders34** [comment]
I am going to make a PR to fix up the test cases to remove the permissions for things in the java.policy and will attach it to this issue.
