### ISSUE TITLE
RESTful WS TCK: NPE when creating client instances

### ISSUE THREAD

**Issue by andymc12** [OpenLiberty/open-liberty#14050]
Brian posted the following in slack while trying to run the RESTful WS 3.0 TCK:
> Also seeing some tests that NPE, like so:
```
Caused by: java.lang.NullPointerException
       at io.openliberty.org.jboss.resteasy.common.client.LibertyResteasyClientBuilderImpl.getBundleContext(LibertyResteasyClientBuilderImpl.java:56)
       at io.openliberty.org.jboss.resteasy.common.client.LibertyResteasyClientBuilderImpl.build(LibertyResteasyClientBuilderImpl.java:35)
       at io.openliberty.org.jboss.resteasy.common.client.LibertyResteasyClientBuilderImpl.build(LibertyResteasyClientBuilderImpl.java:28)
       at jakarta.ws.rs.client.ClientBuilder.newClient(ClientBuilder.java:88)
       at com.sun.ts.tests.jaxrs.common.client.JaxrsWebTestCase.getClientWithRegisteredProviders(JaxrsWebTestCase.java:254)
       ...
```
> I had to add the common jar to the test client's classpath in order to get that far, so it's entirely possible that I need to add additional stuff and it's just not failing in an obvious way.

I believe that the error is occurring because we added some code to inject Liberty's SSL config into the client creation process, and that depends on OSGI Declarative Services, which means it will only work when running inside the Liberty server.  We need to make that support optional so that it will work in a Java SE environment (with no OSGI / DS).

**Comment by andymc12** [comment]
In the course of resolving this, I found a few other things that need to be on the class path - and we also need a default MP Config implementation.
