### ISSUE TITLE
com.ibm.ws.logstash.collector_fat: com.ibm.ws.logstash.collector.tests.LogstashSSLTest.testLogstashEvents

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#14201]
RTC 278255

```
testLogstashEvents:java.lang.NullPointerException: 2020-09-28-01:58:41:921 null
at com.ibm.ws.logstash.collector.tests.LogstashSSLTest.findHealthCenterDirecotry(LogstashSSLTest.java:451)
at com.ibm.ws.logstash.collector.tests.LogstashSSLTest.checkGcSpecialCase(LogstashSSLTest.java:431)
at com.ibm.ws.logstash.collector.tests.LogstashSSLTest.testLogstashEvents(LogstashSSLTest.java:147)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:197)
at org.testcontainers.containers.FailureDetectingExternalResource$1.evaluate(FailureDetectingExternalResource.java:30)
at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:318)
at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:171)
```

**Comment by fmhwong** [comment]
This is a JDK 14 problem.  JAVA_HOME: /home/jazz_build/Build/jbe/jvms/jdk-14-ea+31_linux-x64_bin
