### ISSUE TITLE
Skip logging of some errors in mpOpenTracing.

### ISSUE THREAD

**Issue by jdmcclur** [OpenLiberty/open-liberty#14217]
I am seeing this in a mp-4.0 whenever I hit a bad endpoint. We think this should not be logged every time (it could still be traced).

```
[WARNING ] CWMOT0009W: The OpenTracing exception mapper detected and is handling an unhandled exception from the JAX-RS application.
                                                                                                             javax.ws.rs.NotFoundException: HTTP 404 Not Found
  at org.apache.cxf.jaxrs.utils.SpecExceptions.toNotFoundException(SpecExceptions.java:89)
  at [internal classes]
[err] java.lang.IllegalStateException: The following values are either null or empty - fullyQualifiedClassName: null fullMethodSignature: null
[err]     at io.openliberty.microprofile.metrics.internal.monitor.MetricsJaxRsEMCallbackImpl.resolveSimpleTimerClassMethodTags(MetricsJaxRsEMCallbackImpl.java:100)
[err]     at [internal classes]
[err]     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[err]     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[err]     at java.lang.Thread.run(Thread.java:823)
```

**Comment by jdmcclur** [comment]
@fmhwong - I forgot about this issue. Do you know if any work was done here?

**Comment by fmhwong** [comment]
Will the same exception be logged when mpOT is not enabled?

**Comment by jdmcclur** [comment]
I dont see anything logged when mpOT is not enabled.

Here is what I see. I have a jax-rs endpoint localhost:9080/root/ping which works fine. If I try to access localhost:9080/root/ping2 without mpOT I dont see anything in the logs.

But if mpOT-2.0 (or microProfile-4.0) are enabled I see below, but slightly different errors

**mpOpenTracing-2.0**
```
[WARNING ] CWMOT0009W: The OpenTracing exception mapper detected and is handling an unhandled exception from the JAX-RS application. 
[INFO]                                                                                                                javax.ws.rs.NotFoundException: HTTP 404 Not Found
[INFO]  at <unknown class>.toNotFoundException(SpecExceptions.java:89)
[INFO]  at <unknown class>.toNotFoundException(ExceptionUtils.java:128)
[INFO]  at <unknown class>.processRequest(JAXRSInInterceptor.java:244)
[INFO]  at <unknown class>.handleMessage(JAXRSInInterceptor.java:96)
[INFO]  at <unknown class>.doIntercept(PhaseInterceptorChain.java:308)
[INFO]  at <unknown class>.onMessage(ChainInitiationObserver.java:123)
[INFO]  at <unknown class>.invoke(AbstractHTTPDestination.java:277)
[INFO]  at <unknown class>.invoke(AbstractJaxRsWebEndpoint.java:137)
[INFO]  at <unknown class>.handleRequest(IBMRestServlet.java:146)
[INFO]  at <unknown class>.doGet(IBMRestServlet.java:112)
[INFO]  at <unknown class>.service(HttpServlet.java:686)
[INFO]  at <unknown class>.service(IBMRestServlet.java:96)
[INFO]  at <unknown class>.service(ServletWrapper.java:1258)
[INFO]  at <unknown class>.handleRequest(ServletWrapper.java:746)
[INFO]  at <unknown class>.handleRequest(ServletWrapper.java:443)
[INFO]  at <unknown class>.invokeFilters(WebAppFilterManager.java:1227)
[INFO]  at <unknown class>.handleRequest(WebApp.java:5049)
[INFO]  at <unknown class>.handleRequest(DynamicVirtualHost.java:320)
[INFO]  at <unknown class>.handleRequest(WebContainer.java:1007)
[INFO]  at <unknown class>.run(DynamicVirtualHost.java:285)
[INFO]  at <unknown class>.run(HttpDispatcherLink.java:1184)
[INFO]  at <unknown class>.wrapHandlerAndExecute(HttpDispatcherLink.java:453)
[INFO]  at <unknown class>.ready(HttpDispatcherLink.java:412)
[INFO]  at <unknown class>.handleDiscrimination(HttpInboundLink.java:566)
[INFO]  at <unknown class>.handleNewRequest(HttpInboundLink.java:500)
[INFO]  at <unknown class>.processRequest(HttpInboundLink.java:360)
[INFO]  at <unknown class>.complete(HttpICLReadCallback.java:70)
[INFO]  at <unknown class>.requestComplete(WorkQueueManager.java:504)
[INFO]  at <unknown class>.attemptIO(WorkQueueManager.java:574)
[INFO]  at <unknown class>.workerRun(WorkQueueManager.java:958)
[INFO]  at <unknown class>.run(WorkQueueManager.java:1047)
[INFO]  at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:238)
[INFO]  at [internal classes]
```

**microProfile-4.0**
```
[err] java.lang.IllegalStateException: The following values are either null or empty - fullyQualifiedClassName: null fullMethodSignature: null
[INFO] [err]    at <unknown class>.resolveSimpleTimerClassMethodTags(MetricsJaxRsEMCallbackImpl.java:120)
[INFO] [err]    at <unknown class>.onDefaultMappedException(MetricsJaxRsEMCallbackImpl.java:81)
[INFO] [err]    at <unknown class>.toResponse(DefaultExceptionMapper.java:52)
[INFO] [err]    at <unknown class>.convertFaultToResponse(ExceptionUtils.java:85)
[INFO] [err]    at <unknown class>.convertFaultToResponse(JAXRSUtils.java:1881)
[INFO] [err]    at <unknown class>.convertExceptionToResponseIfPossible(JAXRSInInterceptor.java:296)
[INFO] [err]    at <unknown class>.handleMessage(JAXRSInInterceptor.java:103)
[INFO] [err]    at <unknown class>.doIntercept(PhaseInterceptorChain.java:308)
[INFO] [err]    at <unknown class>.onMessage(ChainInitiationObserver.java:123)
[INFO] [err]    at <unknown class>.invoke(AbstractHTTPDestination.java:277)
[INFO] [err]    at <unknown class>.invoke(AbstractJaxRsWebEndpoint.java:137)
[INFO] [err]    at <unknown class>.handleRequest(IBMRestServlet.java:146)
[INFO] [err]    at <unknown class>.doGet(IBMRestServlet.java:112)
[INFO] [err]    at <unknown class>.service(HttpServlet.java:686)
[INFO] [err]    at <unknown class>.service(IBMRestServlet.java:96)
[INFO] [err]    at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1258)
[INFO] [err]    at [internal classes]
[INFO] [err]    at <unknown class>.invokeTarget(WebAppFilterChain.java:193)
[INFO] [err]    at <unknown class>.doFilter(WebAppFilterChain.java:98)
[INFO] [err]    at <unknown class>.doFilter(JaspiServletFilter.java:56)
[INFO] [err]    at <unknown class>.doFilter(FilterInstanceWrapper.java:201)
[INFO] [err]    at <unknown class>.doFilter(WebAppFilterChain.java:91)
[INFO] [err]    at <unknown class>.doFilter(WebAppFilterManager.java:1002)
[INFO] [err]    at <unknown class>.invokeFilters(WebAppFilterManager.java:1140)
[INFO] [err]    at <unknown class>.invokeFilters(WebAppFilterManager.java:1011)
[INFO] [err]    at <unknown class>.handleRequest(CacheServletWrapper.java:75)
[INFO] [err]    at <unknown class>.handleRequest(CacheServletWrapper40.java:85)
[INFO] [err]    at <unknown class>.handleRequest(WebContainer.java:938)
[INFO] [err]    at <unknown class>.run(DynamicVirtualHost.java:285)
[INFO] [err]    at <unknown class>.run(HttpDispatcherLink.java:1184)
[INFO] [err]    at <unknown class>.wrapHandlerAndExecute(HttpDispatcherLink.java:453)
[INFO] [err]    at <unknown class>.ready(HttpDispatcherLink.java:412)
[INFO] [err]    at <unknown class>.handleDiscrimination(HttpInboundLink.java:566)
[INFO] [err]    at <unknown class>.handleNewRequest(HttpInboundLink.java:500)
[INFO] [err]    at <unknown class>.processRequest(HttpInboundLink.java:360)
[INFO] [err]    at <unknown class>.ready(HttpInboundLink.java:327)
[INFO] [err]    at <unknown class>.sendToDiscriminators(NewConnectionInitialReadCallback.java:167)
[INFO] [err]    at <unknown class>.complete(NewConnectionInitialReadCallback.java:75)
[INFO] [err]    at <unknown class>.requestComplete(WorkQueueManager.java:504)
[INFO] [err]    at <unknown class>.attemptIO(WorkQueueManager.java:574)
[INFO] [err]    at <unknown class>.workerRun(WorkQueueManager.java:958)
[INFO] [err]    at <unknown class>.run(WorkQueueManager.java:1047)
[INFO] [err]    at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:238)
[INFO] [err]    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[INFO] [err]    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[INFO] [err]    at java.base/java.lang.Thread.run(Thread.java:866)
```

**Comment by fmhwong** [comment]
Are there a set of Exceptions that you would like to not logged or just logged once?

**Comment by jdmcclur** [comment]
@fmhwong - I don't have a good answer for that, just that the errors above seem unnecessary.

**Comment by tonyreigns** [comment]
A change has been made to silence this exception when OpenTracing is enabled. Closing the issue.
