### ISSUE TITLE
Shorten EJBCustomBinding metatype labels

### ISSUE THREAD

**Issue by olendvcook** [OpenLiberty/open-liberty#14265]
```
junit.framework.AssertionFailedError: The label for attribute bindToJavaGlobal of type com.ibm.ws.ejbcontainer.runtime is longer than 50 characters. "Bind enterprise beans to contexts in the java: namespace by using specification defined JNDI names".
	at com.ibm.ws.config.internal.schemaChecker.MetaTypeValidator$FailureRecord.<init>(MetaTypeValidator.java:102)
	at com.ibm.ws.config.internal.schemaChecker.MetaTypeValidator$FailureRecord.<init>(MetaTypeValidator.java:94)
	at com.ibm.ws.config.internal.schemaChecker.MetaTypeValidator.validateAnnotation(MetaTypeValidator.java:472)
	at com.ibm.ws.config.internal.schemaChecker.MetaTypeValidator.validateAnnotation(MetaTypeValidator.java:523)
	at com.ibm.ws.config.internal.schemaChecker.MetaTypeValidator.validateType(MetaTypeValidator.java:419)
```

Hard limit of <50 characters for labels

**Comment by olendvcook** [comment]
In master
