### ISSUE TITLE
[Java15] Test Failure: com.ibm.ws.logging.json.fat.MessagesLogEnvTest.checkFfdc

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#14472]
RTC 278690

```
checkFfdc:junit.framework.AssertionFailedError: 2020-09-08-19:38:56:211 Test failed with one or more errors
at com.ibm.ws.logging.json.fat.JSONEventsTest.checkFfdc(JSONEventsTest.java:118)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:197)
at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:318)
at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:171)
```

**Comment by fmhwong** [comment]
@Yushan-Lin Can you take a look of this one?

In this Java 15 build, FFDC doesn't have a message field.

```
{
"type":"liberty_ffdc",
"host":"EB-IKQ-EBC.openstacklocal",
"ibm_userDir":"C:\/jazz-build-engines\/jazz112.hursley.ibm.com\/EBC.PROD.WASRTC\/build\/dev\/image\/output\/wlp\/usr\/",
"ibm_serverName":"com.ibm.ws.logging.json.MessagesLogEnvServer",
"ibm_datetime":"2020-10-10T17:27:32.538+0100",
"ibm_className":"com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters",
"ibm_exceptionName":"java.lang.NullPointerException",
"ibm_probeID":"1105","ibm_threadId":"00000049",
"ibm_stackTrace":"java.lang.NullPointerException\r\n
    \tat com.ibm.logs.LogstashServlet.doGet(LogstashServlet.java:57)\r\n
    \tat javax.servlet.http.HttpServlet.service(HttpServlet.java:575)\r\n
    \tat javax.servlet.http.HttpServlet.service(HttpServlet.java:668)\r\n
    \tat com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1230)\r\n
    \tat com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:729)\r\n
    \tat com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:426)\r\n
    \tat com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1226)\r\n
    \tat com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:5057)\r\n
    \tat com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.handleRequest(DynamicVirtualHost.java:314)\r\n
    \tat com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:1005)\r\n
    \tat com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:279)\r\n
    \tat com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1134)\r\n
    \tat com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:415)\r\n
    \tat com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:374)\r\n
    \tat com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:565)\r\n
    \tat com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:499)\r\n
    \tat com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:359)\r\n
    \tat com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.ready(HttpInboundLink.java:326)\r\n
    \tat com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.sendToDiscriminators(NewConnectionInitialReadCallback.java:167)\r\n
    \tat com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.complete(NewConnectionInitialReadCallback.java:75)\r\n
    \tat com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:504)\r\n
    \tat com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueManager.java:574)\r\n
    \tat com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:958)\r\n
    \tat com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:1047)\r\n
    \tat com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:239)\r\n
    \tat java.base\/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)\r\n
    \tat java.base\/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)\r\n
    \tat java.base\/java.lang.Thread.run(Thread.java:851)\r\n",
"ibm_objectDetails":"Object type = com.ibm.ws.webcontainer.osgi.filter.WebAppFilterManagerImpl\r\n  _filterWrappers = class java.util.Hashtable@fa676f61\r\n    table = \"\/* Could not access table *\/\"\r\n    count = \"\/* Could not access count *\/\"\r\n    threshold = \"\/* Could not access threshold *\/\"\r\n    loadFactor = \"\/* Could not access loadFactor *\/\"\r\n    modCount = \"\/* Could not access modCount *\/\"\r\n    serialVersionUID = \"\/* Could not access serialVersionUID *\/\"\r\n    MAX_ARRAY_SIZE = \"\/* Could not access MAX_ARRAY_SIZE *\/\"\r\n    keySet = \"\/* Could not access keySet *\/\"\r\n    entrySet = \"\/* Could not access entrySet *\/\"\r\n    values = \"\/* Could not access values *\/\"\r\n    KEYS = \"\/* Could not access KEYS *\/\"\r\n    VALUES = \"\/* Could not access VALUES *\/\"\r\n    ENTRIES = \"\/* Could not access ENTRIES *\/\"\r\n  chainCache = class java.util.Collections$SynchronizedMap@eb7a5db8\r\n    serialVersionUID = \"\/* Could not access serialVersionUID *\/\"\r\n    m = \"\/* Could not access m *\/\"\r\n    mutex = \"\/* Could not access mutex *\/\"\r\n    keySet = \"\/* Could not access keySet *\/\"\r\n    entrySet = \"\/* Could not access entrySet *\/\"\r\n    values = \"\/* Could not access values *\/\"\r\n  forwardChainCache = class java.util.Collections$SynchronizedMap@6f3732f5\r\n    serialVersionUID = \"\/* Could not access serialVersionUID *\/\"\r\n    m = \"\/* Could not access m *\/\"\r\n    mutex = \"\/* Could not access mutex *\/\"\r\n    keySet = \"\/* Could not access keySet *\/\"\r\n    entrySet = \"\/* Could not access entrySet *\/\"\r\n    values = \"\/* Could not access values *\/\"\r\n  includeChainCache = class java.util.Collections$SynchronizedMap@16079ae3\r\n    serialVersionUID = \"\/* Could not access serialVersionUID *\/\"\r\n    m = \"\/* Could not access m *\/\"\r\n    mutex = \"\/* Could not access mutex *\/\"\r\n    keySet = \"\/* Could not access keySet *\/\"\r\n    entrySet = \"\/* Could not access entrySet *\/\"\r\n    values = \"\/* Could not access values *\/\"\r\n  errorChainCache = class java.util.Collections$SynchronizedMap@dfd9050e\r\n    serialVersionUID = \"\/* Could not access serialVersionUID *\/\"\r\n    m = \"\/* Could not access m *\/\"\r\n   ...",
"ibm_sequence":"1602347252538_0000000000001"
}
```
