### ISSUE TITLE
Test Failure: com.ibm.ws.logstash.collector.tests.LogstashSSLTest.testLogstashForGCEvent

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#14481]
RTC 278730

```
testLogstashForGCEvent:junit.framework.AssertionFailedError: 2020-10-13-06:23:11:778 liberty_gc not found
at com.ibm.ws.logstash.collector.tests.LogstashSSLTest.testLogstashForGCEvent(LogstashSSLTest.java:186)
at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:197)
at org.testcontainers.containers.FailureDetectingExternalResource$1.evaluate(FailureDetectingExternalResource.java:30)
at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:318)
at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:171)
```

**Comment by fmhwong** [comment]
RTC defect was reopened on 10/27
