### ISSUE TITLE
Test Failure: com.ibm.ws.logging.json.fat.MessagesLogEnvTest.checkFfdc

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#14541]
RTC 278831

```
junit.framework.AssertionFailedError: 2020-10-16-11:55:56:766 Test failed with one or more errors
at com.ibm.ws.logging.json.fat.JSONEventsTest.checkFfdcJava15(JSONEventsTest.java:151)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:197)
at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:318)
at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:171)
```

This might be related to https://github.com/OpenLiberty/open-liberty/pull/14470

**Comment by Yushan-Lin** [comment]
@fmhwong the test was removed with that PR `com.ibm.ws.logging.json.fat.JSONEventsTest.checkFfdcJava15`.
The build must have not gotten the changes yet

**Comment by Yushan-Lin** [comment]
@fmhwong The build doesn't have the latest changes as the PR removes `com.ibm.ws.logging.json.fat.JSONEventsTest.checkFfdcJava15`

**Comment by fmhwong** [comment]
No new occurrences
