### ISSUE TITLE
Ensure SameSite apps are started before driving a request

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#14558]
> messages.log:
> 
> [10/10/20, 4:40:19:029 PDT] 00000029 com.ibm.ws.config.xml.internal.ConfigRefresher               A CWWKG0016I: Starting server configuration update.
> [10/10/20, 4:40:19:030 PDT] 00000029 com.ibm.ws.config.xml.internal.XMLConfigParser               A CWWKG0028A: Processing included configuration resource: /home/jazz_build/Build/jbe/build/dev/image/output/wlp/usr/servers/fatTestCommon.xml
> [10/10/20, 4:40:19:037 PDT] 00000029 com.ibm.ws.config.xml.internal.ConfigRefresher               A CWWKG0017I: The server configuration was successfully updated in 0.007 seconds.
> [10/10/20, 4:40:23:364 PDT] 0000002a com.ibm.ws.tcpchannel.internal.TCPPort                       I CWWKO0219I: TCP Channel defaultHttpEndpoint has been started and is now listening for requests on host *  (IPv4) port 8010.
> [10/10/20, 4:40:23:367 PDT] 0000002a com.ibm.ws.http.internal.VirtualHostImpl                     A CWWKT0016I: Web application available (default_host): http://ebcprh2320g2xbybj-n.fyre.ibm.com:8010/SameSiteTest/
> [10/10/20, 4:40:23:375 PDT] 0000002a com.ibm.ws.tcpchannel.internal.TCPChannel                    I CWWKO0220I: TCP Channel defaultHttpEndpoint has stopped listening for requests on host *  (IPv4) port 8010.
> [10/10/20, 4:40:23:376 PDT] 0000002a com.ibm.ws.http.internal.VirtualHostImpl                     A CWWKT0017I: Web application removed (default_host): http://ebcprh2320g2xbybj-n.fyre.ibm.com:8010/SameSiteTest/
> [10/10/20, 4:40:23:394 PDT] 0000002a com.ibm.ws.tcpchannel.internal.TCPPort                       I CWWKO0219I: TCP Channel defaultHttpEndpoint has been started and is now listening for requests on host *  (IPv4) port 8010.
> [10/10/20, 4:40:23:397 PDT] 0000002a com.ibm.ws.http.internal.VirtualHostImpl                     A CWWKT0016I: Web application available (default_host): http://ebcprh2320g2xbybj-n.fyre.ibm.com:8010/SameSiteTest/
> 
> output.txt
> 
> 10/10/2020 04:40:19:391 PDT] 001 LibertyServer                  waitForConfigUpdateInLogUsingM I Started waiting for CWWKG001[7-8]I and messages matching regexps [] at 4:40:18 AM PDT and finished at 4:40:19 AM PDT. Found: [[10/10/20, 4:40:19:037 PDT] 00000029 com.ibm.ws.config.xml.internal.ConfigRefresher               A CWWKG0017I: The server configuration was successfully updated in 0.007 seconds.]
> [10/10/2020 04:40:19:391 PDT] 001 LibertyServer                  waitForConfigUpdateInLogUsingM I First line searched: [ [10/10/20, 4:40:19:029 PDT] 00000029 com.ibm.ws.config.xml.internal.ConfigRefresher               A CWWKG0016I: Starting server configuration update. ]
> [10/10/2020 04:40:19:391 PDT] 001 LibertyServer                  waitForConfigUpdateInLogUsingM I Last line searched:  [ [10/10/20, 4:40:19:037 PDT] 00000029 com.ibm.ws.config.xml.internal.ConfigRefresher               A CWWKG0017I: The server configuration was successfully updated in 0.007 seconds. ]
> [10/10/2020 04:40:19:391 PDT] 001 LibertyServer                  waitForConfigUpdateInLogUsingM I Last line searching reached end of file, preceding last line was the last line of text seen.
> [10/10/2020 04:40:19:400 PDT] 001 FeatureDependencyProcessor     validateTestedFeatures         I Validated that all installed features were present in test dependencies JSON file.
> [10/10/2020 04:40:19:400 PDT] 001 WCSameSiteCookieAttributeTests testSameSiteConfig_AddCookie_S I url: http://localhost:8010/SameSiteTest/SameSiteAddCookieServlet?cookieToAdd=add_one_cookie
> 

After the test prints the URL we try to drive the request. It seems as though there was a delay intermittently and we try the request before the application is available.

**Comment by pnicolucci** [comment]
Currently it looks like we can get intermittent failures if we don't do this explicitly since the same server is used for many tests I don't believe looking at the code that `getInstalledAppNames ` uses the mark in the logs when calling `waitForConfigUpdateInlogUsingMark `

**Comment by pnicolucci** [comment]
We see the following randomly:

> 
> [10/10/2020 04:40:23:854 PDT] 001 FATRunner                      evaluate                       S null
> org.apache.hc.client5.http.HttpHostConnectException: Connect to http://localhost:8010 [localhost/127.0.0.1] failed: Connection refused (Connection refused)
> 	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
> 	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
> 	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
> 	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
> 	at java.base/java.net.Socket.connect(Socket.java:609)
> 	at org.apache.hc.client5.http.socket.PlainConnectionSocketFactory$1.run(PlainConnectionSocketFactory.java:87)
> 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:734)
> 	at org.apache.hc.client5.http.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:84)
> 	at org.apache.hc.client5.http.impl.io.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:148)
> 	at org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:409)
> 	at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.connectEndpoint(InternalExecRuntime.java:164)
> 	at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.connectEndpoint(InternalExecRuntime.java:174)
> 	at org.apache.hc.client5.http.impl.classic.ConnectExec.execute(ConnectExec.java:135)
> 	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
> 	at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
> 	at org.apache.hc.client5.http.impl.classic.ProtocolExec.execute(ProtocolExec.java:165)
> 	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
> 	at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
> 	at org.apache.hc.client5.http.impl.classic.HttpRequestRetryExec.execute(HttpRequestRetryExec.java:93)
> 	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
> 	at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
> 	at org.apache.hc.client5.http.impl.classic.RedirectExec.execute(RedirectExec.java:116)
> 	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
> 	at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
> 	at org.apache.hc.client5.http.impl.classic.ContentCompressionExec.execute(ContentCompressionExec.java:128)
> 	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
> 	at org.apache.hc.client5.http.impl.classic.InternalHttpClient.doExecute(InternalHttpClient.java:178)
> 	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:75)
> 	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:89)
> 	at com.ibm.ws.fat.wc.tests.WCSameSiteCookieAttributeTests.testSameSiteConfig_AddCookie_Strict(WCSameSiteCookieAttributeTests.java:448)
