### ISSUE TITLE
JNDI IIOP lookup fails with Yoko error "Release called on unknown client"

### ISSUE THREAD

**Issue by chackoj** [OpenLiberty/open-liberty#14843]
[20/10/29 11:40:18:503 JST] 0000a74a id=00000000 org.apache.yoko.orb.CORBA.Delegate                           1 Received unexpected exception for request
org.apache.yoko.orb.OB.AssertionFailed: Yoko encountered an internal error Release called on unknown client
	at org.apache.yoko.orb.OB.Assert.fail(Assert.java:22)
	at org.apache.yoko.orb.OB.ClientManager.releaseClient(ClientManager.java:428)
	at org.apache.yoko.orb.OB.DowncallStub.handleFailureException(DowncallStub.java:369)
	at org.apache.yoko.orb.OB.DowncallStub.invoke(DowncallStub.java:662)
	at org.apache.yoko.orb.CORBA.Delegate.invoke(Delegate.java:462)
	at org.apache.yoko.orb.CORBA.Delegate.is_a(Delegate.java:311)
	at org.omg.CORBA.portable.ObjectImpl._is_a(ObjectImpl.java:56)
	at com.ibm.ws.jndi.iiop.OrbContext.lookup(OrbContext.java:56)
	at org.apache.aries.jndi.DelegateContext.lookup(DelegateContext.java:161)
	at javax.naming.InitialContext.lookup(InitialContext.java:428)
	…

**Comment by chackoj** [comment]
build: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_-ZLfACBAEeuPC7nYV-RLig
