### ISSUE TITLE
NullPointer in EJB bind/unbind if Naming Context Service Does not start

### ISSUE THREAD

**Issue by olendvcook** [OpenLiberty/open-liberty#14885]
```
Stack Dump = java.lang.IllegalStateException: Located service is null,AtomicServiceReference[name=orbRef,ctx=org.apache.felix.scr.impl.manager.ComponentContextImpl@ea95011d,ref={com.ibm.ws.transport.iiop.spi.ORBRef, com.ibm.ws.transport.iiop.spi.ClientORBRef, com.ibm.ws.transport.iiop.spi.ServerPolicySource}={orbSSLInitTimeout=10, service.scope=bundle, AdapterActivatorOp.target=(service.pid=com.ibm.ws.transport.iiop.internal.NamingServiceAdapterActivator_19), service.ranking=5, component.name=com.ibm.ws.transport.iiop.internal.ORBWrapperInternal, config.source=file, id=defaultOrb, service.pid=com.ibm.ws.transport.iiop.internal.ORBWrapper_4, AdapterActivatorOp.cardinality.minimum=1, nameService=corbaname::localhost:2809, service.id=360, IiopEndpoint.target=(service.pid=com.ibm.ws.transport.iiop.internal.IIOPEndpointImpl_11), service.bundleid=96, config.overrides=true, iiopEndpoint=[com.ibm.ws.transport.iiop.internal.IIOPEndpointImpl_11], ComponentFactory.target=(component.factory=com.ibm.ws.transport.iiop.internal.ORBWrapperInternal), component.id=294, SubsystemFactory.cardinality.minimum=4, config.id=com.ibm.ws.transport.iiop.internal.ORBWrapper[defaultOrb], service.factoryPid=com.ibm.ws.transport.iiop.internal.ORBWrapper, adapterActivator=[com.ibm.ws.transport.iiop.internal.NamingServiceAdapterActivator_19], service.vendor=IBM, subsystemFactory=[com.ibm.ws.transport.iiop.spi.SubsystemFactory_8,com.ibm.ws.transport.iiop.spi.SubsystemFactory_7,com.ibm.ws.transport.iiop.spi.SubsystemFactory_6,com.ibm.ws.transport.iiop.spi.SubsystemFactory_5], config.displayId=orb[defaultOrb]},svc=null]
	at com.ibm.wsspi.kernel.service.utils.AtomicServiceReference.getService(AtomicServiceReference.java:261)
	at com.ibm.wsspi.kernel.service.utils.AtomicServiceReference.getServiceWithException(AtomicServiceReference.java:210)
	at com.ibm.ws.ejbcontainer.remote.internal.EJBRemoteRuntimeImpl.getEjbAdapter(EJBRemoteRuntimeImpl.java:287)
	at com.ibm.ws.ejbcontainer.remote.internal.EJBRemoteRuntimeImpl.bind(EJBRemoteRuntimeImpl.java:185)
	at com.ibm.ws.ejbcontainer.remote.internal.EJBRemoteRuntimeImpl.bind(EJBRemoteRuntimeImpl.java:169)
	at com.ibm.ws.ejbcontainer.osgi.internal.NameSpaceBinderImpl.bindBindings(NameSpaceBinderImpl.java:558)
	at com.ibm.ws.ejbcontainer.osgi.internal.NameSpaceBinderImpl.bindBindings(NameSpaceBinderImpl.java:54)
	at com.ibm.ws.ejbcontainer.runtime.AbstractEJBRuntime.bindInterface(AbstractEJBRuntime.java:995)
	at com.ibm.ws.ejbcontainer.runtime.AbstractEJBRuntime.bindInterfaces(AbstractEJBRuntime.java:948)
	at com.ibm.ws.ejbcontainer.runtime.AbstractEJBRuntime.bindInterfaces(AbstractEJBRuntime.java:860)
	at com.ibm.ws.ejbcontainer.osgi.internal.EJBRuntimeImpl.bindInterfaces(EJBRuntimeImpl.java:1201)
	at com.ibm.ws.ejbcontainer.runtime.AbstractEJBRuntime.startModule(AbstractEJBRuntime.java:522)
	at com.ibm.ws.ejbcontainer.osgi.internal.EJBRuntimeImpl.start(EJBRuntimeImpl.java:1123)
```
^ That happens which causes us to shutdown and uninstall the module resulting in the following NPE

```
Stack Dump = java.lang.NullPointerException
	at com.ibm.ws.ejbcontainer.remote.internal.EJBRemoteRuntimeImpl.hasBindings(EJBRemoteRuntimeImpl.java:261)
	at com.ibm.ws.ejbcontainer.remote.internal.EJBRemoteRuntimeImpl.unbindAll(EJBRemoteRuntimeImpl.java:252)
	at com.ibm.ws.ejbcontainer.osgi.internal.NameSpaceBinderImpl.unbindBindings(NameSpaceBinderImpl.java:650)
	at com.ibm.ws.ejbcontainer.runtime.AbstractEJBRuntime.uninstall(AbstractEJBRuntime.java:758)
	at com.ibm.ws.ejbcontainer.runtime.AbstractEJBRuntime.startModule(AbstractEJBRuntime.java:620)
	at com.ibm.ws.ejbcontainer.osgi.internal.EJBRuntimeImpl.start(EJBRuntimeImpl.java:1123)
	at com.ibm.ws.ejbcontainer.osgi.internal.EJBContainerImpl.startEJBInWARModule(EJBContainerImpl.java:194)
	at com.ibm.ws.ejbcontainer.war.internal.EJBWARRuntimeImpl.moduleStarting(EJBWARRuntimeImpl.java:60)
	at com.ibm.ws.container.service.state.internal.ModuleStateManager.fireStarting(ModuleStateManager.java:28)
	at com.ibm.ws.container.service.state.internal.StateChangeServiceImpl.fireModuleStarting(StateChangeServiceImpl.java:80)
	at com.ibm.ws.app.manager.module.internal.ModuleHandlerBase.deployModule(ModuleHandlerBase.java:90)
	at com.ibm.ws.app.manager.module.internal.DeployedModuleInfoImpl.installModule(DeployedModuleInfoImpl.java:49)
	at com.ibm.ws.app.manager.module.internal.SimpleDeployedAppInfoBase.deployModules(SimpleDeployedAppInfoBase.java:597)
	at com.ibm.ws.app.manager.module.internal.SimpleDeployedAppInfoBase.installApp(SimpleDeployedAppInfoBase.java:511)
	at com.ibm.ws.app.manager.module.internal.DeployedAppInfoBase.deployApp(DeployedAppInfoBase.java:349)
	at com.ibm.ws.app.manager.war.internal.WARApplicationHandlerImpl.install(WARApplicationHandlerImpl.java:65)
```

We're cleaning up while trying to shut down so this issue is to circumvent the NPE and let us shut down more cleanly.

**Comment by olendvcook** [comment]
done
