### ISSUE TITLE
NPE from cache in Yoko after connection failure

### ISSUE THREAD

**Issue by chackoj** [OpenLiberty/open-liberty#14903]
The stack trace will look something like this:
java.lang.NullPointerException
-	at org.apache.yoko.util.concurrent.ReferenceCountedCache.remove(ReferenceCountedCache.java:107)
-	at org.apache.yoko.orb.OB.GIOPConnection.processException(GIOPConnection.java:691)
-	at org.apache.yoko.orb.OB.GIOPConnectionThreaded.refresh(GIOPConnectionThreaded.java:679)
-	at org.apache.yoko.orb.OB.Connection$State$3.applyTo(Connection.java:56)
-	at org.apache.yoko.orb.OB.Connection.setState(Connection.java:132)
-	at org.apache.yoko.orb.OB.GIOPConnection.destroy(GIOPConnection.java:1021)
-	at org.apache.yoko.orb.OB.ORBInstance$1.clean(ORBInstance.java:39)
-	at org.apache.yoko.orb.OB.ORBInstance$1.clean(ORBInstance.java:36)
-	at org.apache.yoko.util.concurrent.ReferenceCountedCache.clean(ReferenceCountedCache.java:128)
-	at org.apache.yoko.orb.OB.GIOPClient.reuseOrCreateOutboundConnection(GIOPClient.java:152)
-	at org.apache.yoko.orb.OB.GIOPClient.getWorker(GIOPClient.java:127)

**Comment by joe-chacko** [comment]
Fixed in a subsequent Yoko update.
