### ISSUE TITLE
io.openliberty.microprofile.config.2.0.internal_fat_tck fails to run locally

### ISSUE THREAD

**Issue by tjwatson** [OpenLiberty/open-liberty#14915]
```
io.openliberty.microprofile.config.internal_fat_tck.FATSuite
io.openliberty.microprofile.config.internal_fat_tck.FATSuite
launchConfig20Tck_EE8_FEATURES(io.openliberty.microprofile.config.internal_fat_tck.Config20TCKLauncher)
junit.framework.AssertionFailedError: 2020-11-11-08:32:53:926 No TCK test JUnit result files were found in the results directory which suggests the TCK tests did not run
Errors found in mvnOutput were:
### maven test output:
[ERROR] Failed to execute goal on project tck.runner.tck: Could not resolve dependencies for project io.openliberty.microprofile.config20.internal:tck.runner.tck:jar:2.0: Could not find artifact org.eclipse.microprofile.config:microprofile-config-tck:jar:2.0-ibm20201020 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

	at componenttest.topology.utils.MvnUtils.findJunitResultFiles(MvnUtils.java:182)
	at componenttest.topology.utils.MvnUtils.postProcessTestResults(MvnUtils.java:481)
	at componenttest.topology.utils.MvnUtils.runCleanTest(MvnUtils.java:634)
	at componenttest.topology.utils.MvnUtils.runTCKMvnCmd(MvnUtils.java:143)
	at componenttest.topology.utils.MvnUtils.runTCKMvnCmd(MvnUtils.java:113)
	at io.openliberty.microprofile.config.internal_fat_tck.Config20TCKLauncher.launchConfig20Tck(Config20TCKLauncher.java:57)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:197)
	at componenttest.rules.repeater.RepeatTests$CompositeRepeatTestActionStatement.evaluate(RepeatTests.java:115)
	at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:318)
	at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:171)

```
It appears that it expects `org.eclipse.microprofile.config:microprofile-config-tck:jar:2.0-ibm20201020` to come from maven central.

**Comment by Joseph-Cass** [comment]
Thanks for raising this @tjwatson :) I've made a PR which hopefully should fix this.
