### ISSUE TITLE
Bean Validation 1.1 NullPointerException from ValidationReleasableFactoryImpl

### ISSUE THREAD

**Issue by nmittles** [OpenLiberty/open-liberty#14926]
The `beanValidation-1.1` feature can throw a NullPointerException when configured with Hibernate JPA and the `cdi-1.2` feature is enabled.

```
HHH000274: Unable to apply constraints on DDL for jpa22bval.entity.BeanValEntity
java.lang.NullPointerException
	at com.ibm.ws.beanvalidation.v11.cdi.internal.ValidationReleasableFactoryImpl.getCurrentBeanManager(ValidationReleasableFactoryImpl.java:90)
	at com.ibm.ws.beanvalidation.v11.cdi.internal.ValidationReleasableFactoryImpl.createConstraintValidatorFactory(ValidationReleasableFactoryImpl.java:81)
	at com.ibm.ws.beanvalidation.v11.config.ValidationConfiguratorV11.getConstraintValidatorFactoryOverride(ValidationConfiguratorV11.java:195)
	at com.ibm.ws.beanvalidation.v11.config.internal.ValidationConfigurationV11FactoryImpl.getConstraintValidatorFactoryOverride(ValidationConfigurationV11FactoryImpl.java:60)
	at com.ibm.ws.beanvalidation.OSGiBeanValidationImpl.getConstraintValidatorFactory(OSGiBeanValidationImpl.java:116)
	at com.ibm.ws.beanvalidation.ValidatorFactoryAccessor.getValidatorFactory(ValidatorFactoryAccessor.java:219)
	at com.ibm.ws.beanvalidation.ValidatorFactoryAccessor.getValidatorFactory(ValidatorFactoryAccessor.java:182)
	at com.ibm.ws.beanvalidation.ValidatorFactoryAccessor.getValidatorFactory(ValidatorFactoryAccessor.java:61)
	at com.ibm.ws.beanvalidation.AbstractBeanValidation.getValidatorFactoryOrDefault(AbstractBeanValidation.java:82)
	at com.ibm.ws.jpa.container.beanvalidation.JPABVComponentImpl.getValidatorFactory(JPABVComponentImpl.java:43)
	at com.ibm.ws.jpa.container.beanvalidation.JPAValidator.obtainValidator(JPAValidator.java:165)
	at com.ibm.ws.jpa.container.beanvalidation.JPAValidator.getConstraintsForClass(JPAValidator.java:213)
	at org.hibernate.cfg.beanvalidation.TypeSafeActivator.applyDDL(TypeSafeActivator.java:207)
	at org.hibernate.cfg.beanvalidation.TypeSafeActivator.applyRelationalConstraints(TypeSafeActivator.java:191)
	at org.hibernate.cfg.beanvalidation.TypeSafeActivator.applyRelationalConstraints(TypeSafeActivator.java:150)
	at org.hibernate.cfg.beanvalidation.TypeSafeActivator.activate(TypeSafeActivator.java:98)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.hibernate.cfg.beanvalidation.BeanValidationIntegrator.integrate(BeanValidationIntegrator.java:132)
	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:281)
	at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:462)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:892)
	at org.hibernate.jpa.HibernatePersistenceProvider.createContainerEntityManagerFactory(HibernatePersistenceProvider.java:151)
	at com.ibm.ws.jpa.management.JPAPUnitInfo.createEMFactory(JPAPUnitInfo.java:919)
	at com.ibm.ws.jpa.management.JPAPUnitInfo.initialize(JPAPUnitInfo.java:766)
	at com.ibm.ws.jpa.management.JPAPxmlInfo.extractPersistenceUnits(JPAPxmlInfo.java:182)
	at com.ibm.ws.jpa.management.JPAScopeInfo.processPersistenceUnit(JPAScopeInfo.java:88)
	at com.ibm.ws.jpa.management.JPAApplInfo.addPersistenceUnits(JPAApplInfo.java:119)
	at com.ibm.ws.jpa.container.osgi.internal.JPAComponentImpl.processWebModulePersistenceXml(JPAComponentImpl.java:515)
	at com.ibm.ws.jpa.container.osgi.internal.JPAComponentImpl.applicationStarting(JPAComponentImpl.java:304)
	at com.ibm.ws.container.service.state.internal.ApplicationStateManager.fireStarting(ApplicationStateManager.java:51)
	at com.ibm.ws.container.service.state.internal.StateChangeServiceImpl.fireApplicationStarting(StateChangeServiceImpl.java:50)
	at com.ibm.ws.app.manager.module.internal.SimpleDeployedAppInfoBase.preDeployApp(SimpleDeployedAppInfoBase.java:547)
	at com.ibm.ws.app.manager.module.internal.SimpleDeployedAppInfoBase.installApp(SimpleDeployedAppInfoBase.java:508)
	at com.ibm.ws.app.manager.module.internal.DeployedAppInfoBase.deployApp(DeployedAppInfoBase.java:349)
	at com.ibm.ws.app.manager.war.internal.WARApplicationHandlerImpl.install(WARApplicationHandlerImpl.java:65)
	at com.ibm.ws.app.manager.internal.statemachine.StartAction.execute(StartAction.java:144)
	at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.enterState(ApplicationStateMachineImpl.java:1317)
	at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.run(ApplicationStateMachineImpl.java:897)
	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:239)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by nmittles** [comment]
#14927 has been merged.
