### ISSUE TITLE
Performance issue with OIDC RP, OAuth bearer tokens and postToInstrospectEndpoint

### ISSUE THREAD

**Issue by barbj** [OpenLiberty/open-liberty#14971]
TS004489270
When OAuth bearer tokens are used in headers for authenticating requests, we a noticed severe performance impact due to many SSL handshakes happening between the OIDC client and server. The thread dumps show the handshakes happening in postToInstrospectEndpoint. 

We posted this in #was-liberty slack and @brutif answered:

I took a quick look at the code at https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/OidcClientHttpUtil.java and it looks like postToInstrospectEndpoint creates a new httpclient every time.  I will speculate that means the connection isn’t reused.  If that’s correct, then a code change would probably be needed.  I notice one can configure useSystemPropertiesForHttpClientConnections so http client will respect system properties, but looking at the httpclient docs,  I couldn’t spot anything that could be passed in to help here.

We have authentication cache enabled and also tried setting without effect: <openidConnectClient useSystemPropertiesForHttpClientConnections="true"/>
JVM options:
* -Dhttp.conn-manager.max-per-route=200
* -Dhttp.conn-manager.max-total=200
* -DmaxKeepAliveRequests=-1
* -DkeepAliveEnabled=true

We expect that connection pooling takes place at this point by default so that connections get reused and expensive SSL handshakes do not take place so often. 

During tests, thread dumps show many simultaneous thread with a stack like this:

at com/ibm/jsse2/av.startHandshake(av.java:1020)
at org/apache/http/conn/ssl/SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436)
 at org/apache/http/conn/ssl/SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384)
 at org/apache/http/impl/conn/DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142(Compiled Code))
 at org/apache/http/impl/conn/PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:374)
 at org/apache/http/impl/execchain/MainClientExec.establishRoute(MainClientExec.java:393)
 at org/apache/http/impl/execchain/MainClientExec.execute(MainClientExec.java:236(Compiled Code))
 at org/apache/http/impl/execchain/ProtocolExec.execute(ProtocolExec.java:186)
 at org/apache/http/impl/execchain/RetryExec.execute(RetryExec.java:89(Compiled Code))
 at org/apache/http/impl/execchain/RedirectExec.execute(RedirectExec.java:110)
 at org/apache/http/impl/client/InternalHttpClient.doExecute(InternalHttpClient.java:185)
 at org/apache/http/impl/client/CloseableHttpClient.execute(CloseableHttpClient.java:83)
 at org/apache/http/impl/client/CloseableHttpClient.execute(CloseableHttpClient.java:108)
 at org/apache/http/impl/client/CloseableHttpClient.execute(CloseableHttpClient.java:56)
 at com/ibm/ws/security/openidconnect/clients/common/OidcClientHttpUtil.postToIntrospectEndpoint(OidcClientHttpUtil.java:209)
 at com/ibm/ws/security/openidconnect/clients/common/OidcClientUtil.postToCheckTokenEndpoint(OidcClientUtil.java:197)
 at com/ibm/ws/security/openidconnect/clients/common/OidcClientUtil.checkToken(OidcClientUtil.java:154)
 at com/ibm/ws/security/openidconnect/client/AccessTokenAuthenticator.introspectToken(AccessTokenAuthenticator.java:408)
 at com/ibm/ws/security/openidconnect/client/AccessTokenAuthenticator.authenticate(AccessTokenAuthenticator.java:145)
 at com/ibm/ws/security/openidconnect/client/internal/OidcClientImpl.authenticate(OidcClientImpl.java:404)
 at com/ibm/ws/security/openidconnect/client/internal/OidcClientImpl.authenticate(OidcClientImpl.java:367)
 at com/ibm/ws/security/openidconnect/client/internal/OidcClientImpl.authenticate(OidcClientImpl.java:310)
 at com/ibm/ws/webcontainer/security/WebProviderAuthenticatorProxy.handleOidcClient(WebProviderAuthenticatorProxy.java:598)
 at com/ibm/ws/webcontainer/security/WebProviderAuthenticatorProxy.authenticate(WebProviderAuthenticatorProxy.java:466)
 at com/ibm/ws/webcontainer/security/WebAuthenticatorProxy.authenticate(WebAuthenticatorProxy.java:68)
 at com/ibm/ws/webcontainer/security/WebAppSecurityCollaboratorImpl.authenticateRequest(WebAppSecurityCollaboratorImpl.java:1211)
 at com/ibm/ws/webcontainer/security/WebAppSecurityCollaboratorImpl.determineWebReply(WebAppSecurityCollaboratorImpl.java:967)
 at com/ibm/ws/webcontainer/security/WebAppSecurityCollaboratorImpl.performSecurityChecks(WebAppSecurityCollaboratorImpl.java:656(Compiled Code))
 at com/ibm/ws/webcontainer/security/WebAppSecurityCollaboratorImpl.preInvoke(WebAppSecurityCollaboratorImpl.java:574)
 at com/ibm/wsspi/webcontainer/collaborator/CollaboratorHelper.preInvokeCollaborators(CollaboratorHelper.java:459)
 at com/ibm/ws/webcontainer/osgi/collaborator/CollaboratorHelperImpl.preInvokeCollaborators(CollaboratorHelperImpl.java:270)
 at com/ibm/ws/webcontainer/filter/WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1114)
 at com/ibm/ws/webcontainer/filter/WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1010)
 at com/ibm/ws/webcontainer/servlet/CacheServletWrapper.handleRequest(CacheServletWrapper.java:75)
 at com/ibm/ws/webcontainer/WebContainer.handleRequest(WebContainer.java:936)
 at com/ibm/ws/webcontainer/osgi/DynamicVirtualHost$2.run(DynamicVirtualHost.java:279)
 at com/ibm/ws/http/dispatcher/internal/channel/HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1134)
 at com/ibm/ws/http/dispatcher/internal/channel/HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:415)
 at com/ibm/ws/http/dispatcher/internal/channel/HttpDispatcherLink.ready(HttpDispatcherLink.java:374)
 at com/ibm/ws/http/channel/internal/inbound/HttpInboundLink.handleDiscrimination(HttpInboundLink.java:577)
 at com/ibm/ws/http/channel/internal/inbound/HttpInboundLink.handleNewRequest(HttpInboundLink.java:511)
 at com/ibm/ws/http/channel/internal/inbound/HttpInboundLink.processRequest(HttpInboundLink.java:359(Compiled Code))
 at com/ibm/ws/http/channel/internal/inbound/HttpInboundLink.ready(HttpInboundLink.java:326(Compiled Code))
 at com/ibm/ws/channel/ssl/internal/SSLConnectionLink.determineNextChannel(SSLConnectionLink.java:1100(Compiled Code))
 at com/ibm/ws/channel/ssl/internal/SSLConnectionLink.readyInboundPostHandshake(SSLConnectionLink.java:757)
 at com/ibm/ws/channel/ssl/internal/SSLConnectionLink$MyHandshakeCompletedCallback.complete(SSLConnectionLink.java:427)
 at com/ibm/ws/channel/ssl/internal/SSLUtils.handleHandshake(SSLUtils.java:953(Compiled Code))
 at com/ibm/ws/channel/ssl/internal/SSLHandshakeIOCallback.complete(SSLHandshakeIOCallback.java:85)
 at com/ibm/ws/tcpchannel/internal/WorkQueueManager.requestComplete(WorkQueueManager.java:504)
 at com/ibm/ws/tcpchannel/internal/WorkQueueManager.attemptIO(WorkQueueManager.java:574(Compiled Code))
 at com/ibm/ws/tcpchannel/internal/WorkQueueManager.workerRun(WorkQueueManager.java:958)
 at com/ibm/ws/tcpchannel/internal/WorkQueueManager$Worker.run(WorkQueueManager.java:1047)
 at com/ibm/ws/threading/internal/ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:239(Compiled Code))
 at java/util/concurrent/ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160(Compiled Code))
 at java/util/concurrent/ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
 at java/lang/Thread.run(Thread.java:822)

**Comment by chnke** [comment]
Related to openliberty/open-liberty#12496

**Comment by ayoho** [comment]
As mentioned above, instead of implementing connection pooling or caching, it would be much simpler and should achieve a similar improvement by implementing introspect and userinfo data caching, which is tracked by https://github.com/OpenLiberty/open-liberty/issues/12496.
