### ISSUE TITLE
Test Failure (20180104-0223): junit.framework.TestSuite.com.ibm.ws.logging.json.fat.MessagesLogEnvTest

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#1505]
RTC 249852

componenttest.exception.TopologyException: The necessary feature timedexit-1.0 was not enabled. Please include fatTestPorts.xml or fatTestCommon.xml in the server.xml for server com.ibm.ws.logging.json.MessagesLogEnvServer.
at componenttest.topology.impl.LibertyServer.validateTimedExitEnabled(LibertyServer.java:1914)
at componenttest.topology.impl.LibertyServer.validateServerStarted(LibertyServer.java:1884)
at componenttest.topology.impl.LibertyServer.startServerWithArgs(LibertyServer.java:1219)
at componenttest.topology.impl.LibertyServer.startServerAndValidate(LibertyServer.java:838)
at componenttest.topology.impl.LibertyServer.startServerAndValidate(LibertyServer.java:820)
at componenttest.topology.impl.LibertyServer.startServerAndValidate(LibertyServer.java:807)
at componenttest.topology.impl.LibertyServer.startServer(LibertyServer.java:655)
at com.ibm.ws.logging.json.fat.MessagesLogEnvTest.setUpClass(MessagesLogEnvTest.java:49)
at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:289)
at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:147)

**Comment by fmhwong** [comment]
Some messages were missing from messages.log on zOS.

**Comment by Channyboy** [comment]
Seems to be a gap when a registered z/os wshandler service spawns a messageRouter and when a LogSource is registered as a service as well. 

Prior to messageRouter existing, LogSource is being sent messages directly from the*TraceService and once a messageRouter is available the LogSource will cease to be sent messages directly from *TraceService and will be sent through the MessageRouter.

The following issues will address the issue by ALWAYS sending directly to LogSource (and/or TraceSource) from the *TraceService

Related to:
https://github.com/OpenLiberty/open-liberty/issues/1447
https://github.com/OpenLiberty/open-liberty/issues/1443

**Comment by Channyboy** [comment]
Issue resolved in PR #3092
