### ISSUE TITLE
TCK: Multiple restfulWS apps fail with DefinitionException: WELD-000075: Normal scoped managed bean implementation class has a public field

### ISSUE THREAD

**Issue by brideck** [OpenLiberty/open-liberty#15229]
Multiple applications in the restfulWS TCK fail to start with the following exception:

```
org.jboss.weld.exceptions.DefinitionException: WELD-000075: Normal scoped managed bean implementation class has a public field:  [EnhancedAnnotatedFieldImpl] @MatrixParam public com.sun.ts.tests.jaxrs.ee.rs.matrixparam.sub.SubResource.fieldEntityThrowingExceptionGivenByName
     at org.jboss.weld.bean.ManagedBean.checkBeanImplementation(ManagedBean.java:235)
     at org.jboss.weld.bean.AbstractClassBean.internalInitialize(AbstractClassBean.java:74)
     at org.jboss.weld.bean.ManagedBean.internalInitialize(ManagedBean.java:107)
     at org.jboss.weld.bean.RIBean.initialize(RIBean.java:69)
     at org.jboss.weld.bootstrap.ConcurrentBeanDeployer$4.doWork(ConcurrentBeanDeployer.java:96)
     at org.jboss.weld.bootstrap.ConcurrentBeanDeployer$4.doWork(ConcurrentBeanDeployer.java:93)
     at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:62)
     at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:55)
     at com.ibm.ws.threading.internal.PolicyTaskFutureImpl.run(PolicyTaskFutureImpl.java:718)
     at com.ibm.ws.threading.internal.PolicyExecutorImpl.runTask(PolicyExecutorImpl.java:1135)
     at com.ibm.ws.threading.internal.PolicyExecutorImpl$GlobalPoolTask.run(PolicyExecutorImpl.java:189)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
     at java.lang.Thread.run(Thread.java:748)
```

These tests contain JAX-RS resources that have public non-static fields like:
```
  @MatrixParam("FieldParamEntityThrowingExceptionGivenByName")
  public ParamEntityThrowingExceptionGivenByName fieldEntityThrowingExceptionGivenByName;
```

**Comment by andymc12** [comment]
This occurs because RESTEasy's CDI extension is automatically adding `@RequestScoped` to all JAX-RS resources.  The spec says that JAX-RS resources should be "per-request" by default, but it does not explicitly say that it must be `@RequestScoped`.  

The CDI spec says that scoped CDI beans (i.e. beans with `@*Scoped` annotations) are not allowed to have public fields.  

Since `restfulWS-3.0` includes CDI, it is deferring to the CDI implementation for lifecycle management, and it determined (correctly) that the TCK resource class has a public field and it rejected it.  

The solution for this should be to _not_ add the `@RequestScoped` annotation to JAX-RS resources.  This will require a change in RESTEasy code eventually, but for now, we can make that change in our "overlay" fork since we already overlay the extension file.
