### ISSUE TITLE
JAX-RS 2.0 and 2.1 queryParam fails with javax.ws.rs.core.UriBuilderException: URI can not be built

### ISSUE THREAD

**Issue by jkoehler22** [OpenLiberty/open-liberty#15234]
Customer has report this problem.  I am using this to track progress as I work with the CXF community.

Customer that is trying to use` ("/?abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-._~%1A!$'()*+,;:@", "apiKeyQueryParam1Value" )` as a `queryParam`.  The get fails with a `javax.ws.rs.core.UriBuilderException: URI can not be built.`

I have reproduced the problem. I have tried 2 options to get this to work 
### Option 1 Not encoded
        ```Response response = client.target("http://localhost:" + "8010" + "/paramconverter/")
                        .path("application/resource/queryParamSpecialCharactersEncoded")
                        .queryParam("/?abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-._~%1A!$'()*+,;:@", "apiKeyQueryParam1Value")
                        .request(MediaType.APPLICATION_JSON_TYPE)
                        .get();```
### Option 2 Encoded
        ```Response response = client.target("http://localhost:" + "8010" + "/paramconverter/")
                        .path("application/resource/queryParamSpecialCharacters")
                        .queryParam(URLEncoder.encode("/?abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-._~%1A!$'()*+,;:@", "UTF-8"), "apiKeyQueryParam1Value")           
                        .request(MediaType.APPLICATION_JSON_TYPE)
                        .get();```

```URLEncoder.encode = %2F%3FabcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-._%7E%251A%21%24%27%28%29*%2B%2C%3B%3A%40```

**Comment by jkoehler22** [comment]
**Option 1 Not encoded fails with**
```
[12/8/20, 8:52:07:462 CST] 00000069 com.ibm.ws.logging.internal.impl.IncidentImpl                I FFDC1015I: An FFDC Incident has been created: "java.net.URISyntaxException: Illegal character in query at index 154: http://localhost:8010/paramconverter/application/resource/queryParamSpecialCharacters?/?abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-._~!$'()* ,;:@=apiKeyQueryParam1Value org.apache.cxf.jaxrs.impl.UriBuilderImpl 110" at ffdc_20.12.08_08.52.07.0.log
[12/8/20, 8:52:07:469 CST] 00000069 SystemOut                                                    O ERROR: javax.ws.rs.core.UriBuilderException: URI can not be built
[12/8/20, 8:52:07:469 CST] 00000069 SystemErr                                                    R javax.ws.rs.core.UriBuilderException: URI can not be built
	at org.apache.cxf.jaxrs.impl.UriBuilderImpl.doBuild(UriBuilderImpl.java:111)
	at org.apache.cxf.jaxrs.impl.UriBuilderImpl.buildFromEncoded(UriBuilderImpl.java:248)
	at org.apache.cxf.jaxrs.client.AbstractClient.getCurrentURI(AbstractClient.java:324)
	at org.apache.cxf.jaxrs.client.spec.ClientImpl$WebTargetImpl.request(ClientImpl.java:327)
	at org.apache.cxf.jaxrs.client.spec.ClientImpl$WebTargetImpl.request(ClientImpl.java:448)
	at com.ibm.ws.jaxrs.fat.paramconverter.ClientTestServlet.testQueryParamSpecialCharacters(ClientTestServlet.java:256)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at componenttest.app.FATServlet.doGet(FATServlet.java:71)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1257)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:745)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:442)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1226)
	at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:5057)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.handleRequest(DynamicVirtualHost.java:314)
	at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:1005)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:279)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1141)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:422)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:381)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:565)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:499)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:359)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.ready(HttpInboundLink.java:326)
	at com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.sendToDiscriminators(NewConnectionInitialReadCallback.java:167)
	at com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.complete(NewConnectionInitialReadCallback.java:75)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:504)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueManager.java:574)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:958)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:1047)
	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:239)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.net.URISyntaxException: Illegal character in query at index 154: http://localhost:8010/paramconverter/application/resource/queryParamSpecialCharacters?/?abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-._~!$'()* ,;:@=apiKeyQueryParam1Value
	at java.base/java.net.URI$Parser.fail(URI.java:2915)
	at java.base/java.net.URI$Parser.checkChars(URI.java:3086)
	at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3174)
	at java.base/java.net.URI$Parser.parse(URI.java:3116)
	at java.base/java.net.URI.<init>(URI.java:600)
	at org.apache.cxf.jaxrs.impl.UriBuilderImpl.buildURIFromEncoded(UriBuilderImpl.java:205)
	at org.apache.cxf.jaxrs.impl.UriBuilderImpl.buildURI(UriBuilderImpl.java:174)
	at org.apache.cxf.jaxrs.impl.UriBuilderImpl.doBuild(UriBuilderImpl.java:109)
	... 37 more
```

**Comment by jkoehler22** [comment]
**Option 2 Encoded fails with**

```
[12/8/20, 14:42:59:941 CST] 00000074 SystemErr                                                    R javax.ws.rs.core.UriBuilderException: URI can not be built
	at org.apache.cxf.jaxrs.impl.UriBuilderImpl.doBuild(UriBuilderImpl.java:120)
	at org.apache.cxf.jaxrs.impl.UriBuilderImpl.buildFromEncoded(UriBuilderImpl.java:245)
	at org.apache.cxf.jaxrs.client.AbstractClient.getCurrentURI(AbstractClient.java:319)
	at org.apache.cxf.jaxrs.client.WebClient.finalizeMessage(WebClient.java:1110)
	at org.apache.cxf.jaxrs.client.WebClient.doChainedInvocation(WebClient.java:1084)
	at org.apache.cxf.jaxrs.client.WebClient.doInvoke(WebClient.java:932)
	at org.apache.cxf.jaxrs.client.WebClient.doInvoke(WebClient.java:901)
	at org.apache.cxf.jaxrs.client.WebClient.invoke(WebClient.java:461)
	at org.apache.cxf.jaxrs.client.SyncInvokerImpl.method(SyncInvokerImpl.java:135)
	at org.apache.cxf.jaxrs.client.SyncInvokerImpl.method(SyncInvokerImpl.java:130)
	at org.apache.cxf.jaxrs.client.SyncInvokerImpl.get(SyncInvokerImpl.java:50)
	at org.apache.cxf.jaxrs.client.spec.InvocationBuilderImpl.get(InvocationBuilderImpl.java:92)
	at com.ibm.ws.jaxrs.fat.paramconverter.ClientTestServlet.testQueryParamSpecialCharactersEncoded2(ClientTestServlet.java:305)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at componenttest.app.FATServlet.doGet(FATServlet.java:71)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:686)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:791)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1257)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:745)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:442)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1226)
	at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:5057)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.handleRequest(DynamicVirtualHost.java:314)
	at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:1005)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:279)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1141)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:422)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:381)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:565)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:499)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:359)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.ready(HttpInboundLink.java:326)
	at com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.sendToDiscriminators(NewConnectionInitialReadCallback.java:167)
	at com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.complete(NewConnectionInitialReadCallback.java:75)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:504)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueManager.java:574)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:958)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:1047)
	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:239)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.net.URISyntaxException: Illegal character in query at index 154: http://localhost:8010/paramconverter/application/resource/queryParamSpecialCharacters?/?abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-._~!$'()* ,;:@=apiKeyQueryParam1Value
	at java.base/java.net.URI$Parser.fail(URI.java:2915)
	at java.base/java.net.URI$Parser.checkChars(URI.java:3086)
	at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3174)
	at java.base/java.net.URI$Parser.parse(URI.java:3116)
	at java.base/java.net.URI.<init>(URI.java:600)
	at org.apache.cxf.jaxrs.impl.UriBuilderImpl.buildURIFromEncoded(UriBuilderImpl.java:202)
	at org.apache.cxf.jaxrs.impl.UriBuilderImpl.buildURI(UriBuilderImpl.java:175)
	at org.apache.cxf.jaxrs.impl.UriBuilderImpl.doBuild(UriBuilderImpl.java:118)
	... 44 more
```

**Comment by jkoehler22** [comment]
JAX-RS 2.1 RestEasy works for Option 2 Encoded
JAX-RS 1.1 Wink works for Option 1 Not encoded

**Comment by jkoehler22** [comment]
Option 1 Not encoded trace.log
[trace.log](https://github.com/OpenLiberty/open-liberty/files/5662060/trace.log)

**Comment by jkoehler22** [comment]
Option 2 Encoded trace.log
[trace.log](https://github.com/OpenLiberty/open-liberty/files/5662066/trace.log)

**Comment by jkoehler22** [comment]
Response from CXF

if the name of the query parameter is indeed `"/?abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-._~%1A!$'()*+,;:@"`,
the **CXF does always decode query parameter names**, so the not-so-nice workaround is to encode the name twice:
```
    Response response = client.target("https://urldefense.proofpoint.com/v2/url?u=http-3A__localhost&d=DwIFAw&c=jf_iaSHvJObTbx-siA1ZOg&r=Ru_ri9bp_SWNDhGKSl6lKUFWahoPKux8URrU15ebn-4&m=p4Hwt1T1MXpsm3AfdWfNdRr2xQnODZfaSEJNfOyKlhk&s=A97fjHL3NUnv3U9m5LjGKOX8QolbOOI9Gr1sblbYudM&e= :" + "8010" + "/paramconverter/")
      .path("application/resource/queryParamSpecialCharacters")
      .queryParam(URLEncoder.encode(URLEncoder.encode("/?abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-._~%1A!$'()*+,;:@", "UTF-8"), "UTF-8"), "apiKeyQueryParam1Value")
      .request(MediaType.APPLICATION_JSON_TYPE)
      .get();
 ```         
Probably could be considered a bug, please feel free to open an issue [1].
Hope it helps, thanks.

**Comment by jkoehler22** [comment]
JIRA can be found here:  https://issues.apache.org/jira/browse/CXF-8387

**Comment by jkoehler22** [comment]
**Option 3 Encoded Twice**
```
    Response response = client.target("https://urldefense.proofpoint.com/v2/url?u=http-3A__localhost&d=DwIFAw&c=jf_iaSHvJObTbx-siA1ZOg&r=Ru_ri9bp_SWNDhGKSl6lKUFWahoPKux8URrU15ebn-4&m=p4Hwt1T1MXpsm3AfdWfNdRr2xQnODZfaSEJNfOyKlhk&s=A97fjHL3NUnv3U9m5LjGKOX8QolbOOI9Gr1sblbYudM&e= :" + "8010" + "/paramconverter/")
      .path("application/resource/queryParamSpecialCharacters")
      .queryParam(URLEncoder.encode(URLEncoder.encode("/?abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-._~%1A!$'()*+,;:@", "UTF-8"), "UTF-8"), "apiKeyQueryParam1Value")
      .request(MediaType.APPLICATION_JSON_TYPE)
      .get();

 ```
   @GET
    @Path("queryParamSpecialCharacters")
    public Response queryParamSpecialCharacters(@QueryParam("/?abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-._~%1A!$'()*+,;:@") String queryParm1) {
        System.out.println("queryParamSpecialCharacters queryParm1 = " + queryParm1);
        return Response.ok(queryParm1).build();
    }
```
```

**Comment by jkoehler22** [comment]
**Option 3 Encoded Twice fails with** 

`[12/16/20, 9:32:33:870 CST] 0000006b SystemOut                                                    O queryParamSpecialCharacters queryParm1 = null`

**Comment by jkoehler22** [comment]
CXF Pull Request  https://github.com/apache/cxf/pull/809

**Comment by jim-krueger** [comment]
Option 1 is not supported by CXF, RestEasy, or Jersey.  Option 2 has now been fixed under CXF PR listed above.

**Comment by jim-krueger** [comment]
CXF fix has been ported to Liberty under #17861

**Comment by jim-krueger** [comment]
Eclipse import error corrected under #17895
