### ISSUE TITLE
Remove (or try to fix) JSP's "useInMemory" Parameter

### ISSUE THREAD

**Issue by volosied** [OpenLiberty/open-liberty#15240]
Current implementation of "useInMemory" is broken.

[useInMemory:  Generate Java source and classes in memory (without writing to disk).](https://openliberty.io/docs/20.0.0.12/reference/config/jspEngine.html)

When testing this parameter: 
`<jspEngine useInMemory="true"/>`

the following error is encountered: 

`Error 404: javax.servlet.UnavailableException: SRVE0200E: Servlet [org.apache.jsp._EL30CollectionObjectOperations]: Could not find required class - _EL30CollectionObjectOperations.class`

This should be investigated to see if the implementation can be fixed.  Otherwise, this parameter should be removed from the code and the documentation.

**Comment by pnicolucci** [comment]
I believe at one point in time we had a restriction listed for this property that it did not work. However it looks like the latest restrictions don't list it . I don't believe this ever worked in Liberty and the configuration open should be removed if there is no valid implementation of the functionality.

**Comment by volosied** [comment]
Errors I've encountered: 
```
------Start of DE processing------ = [9/27/23, 15:33:01:136 EDT]
Exception = javax.servlet.UnavailableException
Source = com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest()
probeid = 302
Stack Dump = javax.servlet.UnavailableException: SRVE0200E: Servlet [org.apache.jsp._index]: Could not find required class - _index.class
	at com.ibm.ws.webcontainer.servlet.ServletWrapper$1.run(ServletWrapper.java:1553)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.loadServlet(ServletWrapper.java:1513)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:592)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:445)
	at com.ibm.wsspi.webcontainer.servlet.GenericServletWrapper.handleRequest(GenericServletWrapper.java:120)
	at com.ibm.ws.jsp.webcontainerext.AbstractJSPExtensionServletWrapper.handleRequest(AbstractJSPExtensionServletWrapper.java:208)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1361)
	at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:5076)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.handleRequest(DynamicVirtualHost.java:328)
	at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:1038)
```

```
------Start of DE processing------ = [9/27/23, 15:35:04:042 EDT]
Exception = java.lang.NullPointerException
Source = com.ibm.ws.webcontainer.webapp.WebApp.handleRequest
probeid = 985
Stack Dump = java.lang.NullPointerException: Cannot invoke "java.net.URL.getProtocol()" because the return value of "com.ibm.wsspi.jsp.resource.JspInputSource.getAbsoluteURL()" is null
	at com.ibm.ws.jsp.inmemory.resource.InMemoryTagFileResources.<init>(InMemoryTagFileResources.java:43)
	at com.ibm.ws.jsp.inmemory.resource.InMemoryJspResourceFactory.createTagFileResources(InMemoryJspResourceFactory.java:38)
	at com.ibm.ws.jsp.translator.utils.JspTranslatorUtil.translateJsp(JspTranslatorUtil.java:292)
	at com.ibm.ws.jsp.translator.utils.JspTranslatorUtil.translateJspAndCompile(JspTranslatorUtil.java:115)
	at com.ibm.ws.jsp.webcontainerext.AbstractJSPExtensionServletWrapper.translateJsp(AbstractJSPExtensionServletWrapper.java:543)
	at com.ibm.ws.jsp.webcontainerext.AbstractJSPExtensionServletWrapper._checkForTranslation(AbstractJSPExtensionServletWrapper.java:460)
	at com.ibm.ws.jsp.webcontainerext.AbstractJSPExtensionServletWrapper.checkForTranslation(AbstractJSPExtensionServletWrapper.java:250)
	at com.ibm.ws.jsp.webcontainerext.AbstractJSPExtensionProcessor.findWrapper(AbstractJSPExtensionProcessor.java:516)
	at com.ibm.ws.jsp.webcontainerext.AbstractJSPExtensionProcessor.getServletWrapper(AbstractJSPExtensionProcessor.java:355)
	at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:5046)
```
