### ISSUE TITLE
NPE calling a EJB 2.x method with CDI enabled

### ISSUE THREAD

**Issue by Thihup** [OpenLiberty/open-liberty#15244]
**Describe the bug**
We're trying to port an old EJB application and when we enable the CDI feature the application is not able to deploy successfully.
I could create a minimal example using the same structure of classes. However I couldn't figure out why Open Liberty failed to deploy the application, looks like it is a bug.

```
[12/9/20, 16:43:42:672 BRT] 00000025 com.ibm.ejs.container.LocalExceptionMappingStrategy          E CNTR0019E: EJB threw an unexpected (non-declared) exception during invocation of method "supportsSecurity". Exception data: java.lang.NullPointerException: Cannot invoke "com.ibm.ws.cdi.internal.interfaces.WebSphereBeanDeploymentArchive.getDescendantBdas()" because "bda" is null
	at com.ibm.ws.cdi.impl.managedobject.CDIEJBManagedObjectFactoryImpl.getEjbDescriptor(CDIEJBManagedObjectFactoryImpl.java:147)
	at com.ibm.ws.cdi.impl.managedobject.CDIEJBManagedObjectFactoryImpl.createContext(CDIEJBManagedObjectFactoryImpl.java:78)
	at com.ibm.ejs.container.ManagedBeanOBase.createInterceptorsAndInstance(ManagedBeanOBase.java:198)
	at com.ibm.ejs.container.StatelessBeanO.initialize(StatelessBeanO.java:155)
	at com.ibm.ejs.container.BeanOFactory.create(BeanOFactory.java:103)
	at com.ibm.ejs.container.EJSHome.createBeanO(EJSHome.java:975)
	at com.ibm.ejs.container.EJSHome.createBeanO(EJSHome.java:1077)
	at com.ibm.ejs.container.activator.UncachedActivationStrategy.atActivate(UncachedActivationStrategy.java:62)
	at com.ibm.ejs.container.activator.Activator.preInvokeActivateBean(Activator.java:263)
	at com.ibm.ejs.container.EJSContainer.preInvokeActivate(EJSContainer.java:3001)
	at com.ibm.ejs.container.EJSContainer.EjbPreInvoke(EJSContainer.java:2390)
	at io.openliberty.sample.ejb2.EJSLocalCSLSecurityEJB_1cad06b9.supportsSecurity(EJSLocalCSLSecurityEJB_1cad06b9.java)
	at io.openliberty.sample.ejb2.SecurityProxy.<clinit>(SecurityProxy.java:22)
	at io.openliberty.sample.SampleApplication.init(SampleApplication.java:19)
	at javax.servlet.GenericServlet.init(GenericServlet.java:244)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.init(ServletWrapper.java:291)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:584)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:426)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1226)
	at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:5057)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.handleRequest(DynamicVirtualHost.java:314)
	at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:1005)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:279)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1141)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:422)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:381)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:565)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:499)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:359)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.ready(HttpInboundLink.java:326)
	at com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.sendToDiscriminators(NewConnectionInitialReadCallback.java:167)
	at com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.complete(NewConnectionInitialReadCallback.java:75)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:504)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueManager.java:574)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:958)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:1047)
	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:239)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)

```

**Steps to Reproduce**
1. Download the example: 
[example-ejb-cdi.zip](https://github.com/OpenLiberty/open-liberty/files/5668287/example-ejb-cdi.zip)
2. `$ mvn clean install && cd war && mvn liberty:dev`
3. Go to `http://localhost:9080/war/hello`

**Expected behavior**
No exceptions to happen.

**Diagnostic information:**
 - OpenLiberty Version: 20.0.0.12
 - Java Version: 15 (Both OpenJ9 and Hotspot, only used Hotspot because of the better helpful NPE message)
[messages.log](https://github.com/OpenLiberty/open-liberty/files/5668298/messages.log)

**Additional context**
The following conditions doesn't trigger the exception:
- Remove the CDI feature (or)
- Delete the SomeBean class (or)
- Remove the <cdi12 enableImplicitBeanArchives="false"/> (or)
- Add the META-INF/beans.xml to the _ejb_ module

**Comment by tkburroughs** [comment]
Appears to be related to https://github.com/OpenLiberty/open-liberty/issues/15152

If you have bean archive scanning disabled in server.xml, then CDI isn't going to know about the EJBs unless there is a beans.xml.
Since adding a beans.xml resolves the problem, I guessing one or the other (beans.xml or archive scanning) is required.

@benjamin-confino is it correct that they must have either beans.xml or archive scanning enabled?

**Comment by Thihup** [comment]
Sure! However, in the example, the EJB does nothing related to the CDI bean. In our case, the equivalent to the "cdi" module is a third-party library and our application doesn't use it yet.
Deploying the same application works in the Wildfly but fails with Payara. The weirder is that calling an EJB method breaks and it is not a deployment failure.

**Comment by tkburroughs** [comment]
My understanding of the CDI spec is that CDI considers an EJB to in fact be a CDI bean.  So, although you might not think you are using CDI, you are.  CDI becomes responsible for constructing EJB instances; which is why CDI is confused. Without performing archive scanning or including a beans.xml, CDI is faltering when attempting to create that EJB instance since it isn't aware that bean exists.  When CDI is present, any EJB Container implementation must delegate bean construction to CDI.

I think we'll need @benjamin-confino 's expertise to clarify if my explanation is correct, and if the CDI feature can be improved to better handle this.
