### ISSUE TITLE
Once I migrate from older Spring boot version 1.5.9 to 2.0.0.M7, execution of jar gives the error mentioned here. 

### ISSUE THREAD

**Issue by ShailendraMoyal** [OpenLiberty/open-liberty#1526]
C:\Users\SHAILENDRAMOYAL\Documents\ONCodebase\OP-Redesign\build\libs>java -jar OP-Redesign-0.0.1-SNAPSHOT.jar

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::             (v2.0.0.M7)

[ERROR] 2018-01-10 14:55:29.373 [main] SpringApplication - Application startup failed
org.springframework.beans.factory.BeanDefinitionStoreException: Failed to process import candidates for configuration class [com.ibm.opredesign.OppocTestProjectApplication]; nested exception is java.io.FileNotFoundException: class path resource [org/springframework/boot/autoconfigure/web/EmbeddedServletContainerAutoConfiguration$BeanPostProcessorsRegistrar.class] cannot be opened because it does not exist
        at org.springframework.context.annotation.ConfigurationClassParser.processImports(ConfigurationClassParser.java:616) ~[spring-context-5.0.2.RELEASE.jar!/:5.0.2.RELEASE]
        at org.springframework.context.annotation.ConfigurationClassParser.processDeferredImportSelectors(ConfigurationClassParser.java:548) ~[spring-context-5.0.2.RELEASE.jar!/:5.0.2.RELEASE]
        at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:184) ~[spring-context-5.0.2.RELEASE.jar!/:5.0.2.RELEASE]
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:316) ~[spring-context-5.0.2.RELEASE.jar!/:5.0.2.RELEASE]
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:233) ~[spring-context-5.0.2.RELEASE.jar!/:5.0.2.RELEASE]
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:273) ~[spring-context-5.0.2.RELEASE.jar!/:5.0.2.RELEASE]
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:93) ~[spring-context-5.0.2.RELEASE.jar!/:5.0.2.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:693) ~[spring-context-5.0.2.RELEASE.jar!/:5.0.2.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:531) ~[spring-context-5.0.2.RELEASE.jar!/:5.0.2.RELEASE]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:138) ~[spring-boot-2.0.0.M7.jar!/:2.0.0.M7]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:751) [spring-boot-2.0.0.M7.jar!/:2.0.0.M7]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:387) [spring-boot-2.0.0.M7.jar!/:2.0.0.M7]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:327) [spring-boot-2.0.0.M7.jar!/:2.0.0.M7]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1245) [spring-boot-2.0.0.M7.jar!/:2.0.0.M7]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1233) [spring-boot-2.0.0.M7.jar!/:2.0.0.M7]
        at com.ibm.opredesign.OppocTestProjectApplication.main(OppocTestProjectApplication.java:27) [classes!/:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [OP-Redesign-0.0.1-SNAPSHOT.jar:?]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [OP-Redesign-0.0.1-SNAPSHOT.jar:?]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [OP-Redesign-0.0.1-SNAPSHOT.jar:?]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [OP-Redesign-0.0.1-SNAPSHOT.jar:?]
Caused by: java.io.FileNotFoundException: class path resource [org/springframework/boot/autoconfigure/web/EmbeddedServletContainerAutoConfiguration$BeanPostProcessorsRegistrar.class] cannot be opened because it does not exist
        at org.springframework.core.io.ClassPathResource.getInputStream(ClassPathResource.java:180) ~[spring-core-5.0.2.RELEASE.jar!/:5.0.2.RELEASE]
        at org.springframework.core.type.classreading.SimpleMetadataReader.<init>(SimpleMetadataReader.java:51) ~[spring-core-5.0.2.RELEASE.jar!/:5.0.2.RELEASE]
        at org.springframework.core.type.classreading.SimpleMetadataReaderFactory.getMetadataReader(SimpleMetadataReaderFactory.java:99) ~[spring-core-5.0.2.RELEASE.jar!/:5.0.2.RELEASE]
        at org.springframework.boot.type.classreading.ConcurrentReferenceCachingMetadataReaderFactory.createMetadataReader(ConcurrentReferenceCachingMetadataReaderFactory.java:88) ~[spring-boot-2.0.0.M7.jar!/:2.0.0.M7]
        at org.springframework.boot.type.classreading.ConcurrentReferenceCachingMetadataReaderFactory.getMetadataReader(ConcurrentReferenceCachingMetadataReaderFactory.java:75) ~[spring-boot-2.0.0.M7.jar!/:2.0.0.M7]
        at org.springframework.core.type.classreading.SimpleMetadataReaderFactory.getMetadataReader(SimpleMetadataReaderFactory.java:94) ~[spring-core-5.0.2.RELEASE.jar!/:5.0.2.RELEASE]
        at org.springframework.context.annotation.ConfigurationClassParser.asSourceClass(ConfigurationClassParser.java:699) ~[spring-context-5.0.2.RELEASE.jar!/:5.0.2.RELEASE]
        at org.springframework.context.annotation.ConfigurationClassParser$SourceClass.getRelated(ConfigurationClassParser.java:930) ~[spring-context-5.0.2.RELEASE.jar!/:5.0.2.RELEASE]
        at org.springframework.context.annotation.ConfigurationClassParser$SourceClass.getAnnotationAttributes(ConfigurationClassParser.java:911) ~[spring-context-5.0.2.RELEASE.jar!/:5.0.2.RELEASE]
        at org.springframework.context.annotation.ConfigurationClassParser.collectImports(ConfigurationClassParser.java:532) ~[spring-context-5.0.2.RELEASE.jar!/:5.0.2.RELEASE]
        at org.springframework.context.annotation.ConfigurationClassParser.getImports(ConfigurationClassParser.java:505) ~[spring-context-5.0.2.RELEASE.jar!/:5.0.2.RELEASE]
        at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:296) ~[spring-context-5.0.2.RELEASE.jar!/:5.0.2.RELEASE]
        at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:241) ~[spring-context-5.0.2.RELEASE.jar!/:5.0.2.RELEASE]
        at org.springframework.context.annotation.ConfigurationClassParser.processImports(ConfigurationClassParser.java:606) ~[spring-context-5.0.2.RELEASE.jar!/:5.0.2.RELEASE]
        ... 23 more

**Comment by ShailendraMoyal** [comment]
Content of my Build.gradle is 
buildscript {
	ext {
		springBootVersion = '2.0.0.M7'
	}
	repositories {
		mavenCentral()
		maven { url "https://repo.spring.io/milestone" }
	}
	dependencies {
		 classpath "org.springframework.boot:spring-boot-gradle-plugin:2.0.0.M7"
	}
}

apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'org.springframework.boot'
apply plugin: 'io.spring.dependency-management'

group = 'com.ibm.opredesign'
version = '0.0.1-SNAPSHOT'

sourceCompatibility = 1.8
targetCompatibility = 1.8

repositories {
	mavenCentral()
	maven(){
		url "https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/spring-starter-alpha1"
	}
	maven { url "https://repo.spring.io/milestone" }
}

configurations {
   	all*.exclude group:'org.springframework.boot', module : 'spring-boot-starter-logging'
}
	

dependencies {
	compile('org.springframework.boot:spring-boot-starter-data-jpa')
	
	compile('org.springframework.boot:spring-boot-starter-log4j2')
	compile('io.openliberty.boot:liberty-spring-boot-starter:0.5.0.M1')
	compile('io.openliberty.boot:liberty-boot-ssl:0.5.0.M1')

	runtime('com.h2database:h2')
	testCompile('org.springframework.boot:spring-boot-starter-test'){
        exclude module: 'commons-logging'
    }
    
    compile('org.springframework.boot:spring-boot-starter-web') {
    	exclude module: "spring-boot-starter-tomcat"
 	 }
  
	compile files("${projectDir}/lib/db2jcc4.jar")
	compile ("io.springfox:springfox-swagger2:2.4.0")
	compile ("io.springfox:springfox-swagger-ui:2.4.0")
}

**Comment by ShailendraMoyal** [comment]
Dear team @ any update on the same.

**Comment by aguibert** [comment]
hi @ShailendraMoyal, Liberty doesn't support Spring 2.X yet, but some of the devs are looking into it.

**Comment by tjwatson** [comment]
Closing this issue since the Liberty Spring Boot Starter was an experimental project that is not part of open-liberty.  If the Liberty Spring Boot starter becomes a part of an open-liberty release then it would be updated to support Spring Boot 2.0.x
