### ISSUE TITLE
Investigate FFDC java.io.FileNotFoundException: ...apps\WSSampleSeiClient (Access is denied.) when Java2Security enabled in wssecurity CXF FAT

### ISSUE THREAD

**Issue by meiaus** [OpenLiberty/open-liberty#15283]
```
[12/9/20 9:39:36:183 CST] 00000059 com.ibm.ws.app.manager.AppMessageHelper                      I CWWKZ0018I: Starting application webcontent.
[12/9/20 9:39:36:185 CST] 00000056 com.ibm.ws.app.manager.AppMessageHelper                      I CWWKZ0018I: Starting application WSSampleSeiClient.
[12/9/20 9:39:36:187 CST] 00000059 bm.ws.app.manager.war.internal.WARDeployedAppInfoFactoryImpl I CWWKZ0135I: The webcontent application is using the expanded directory at the C:\Users\Mei-HsiangChang\libertyGit\open-liberty\dev\build.image\wlp\usr\servers\com.ibm.ws.wssecurity_fat.sample\apps\webcontent location.
[12/9/20 9:39:36:187 CST] 00000056 bm.ws.app.manager.war.internal.WARDeployedAppInfoFactoryImpl I CWWKZ0135I: The WSSampleSeiClient application is using the expanded directory at the C:\Users\Mei-HsiangChang\libertyGit\open-liberty\dev\build.image\wlp\usr\servers\com.ibm.ws.wssecurity_fat.sample\apps\WSSampleSeiClient location.
[12/9/20 9:39:36:293 CST] 00000068 com.ibm.ws.app.manager.AppMessageHelper                      I CWWKZ0018I: Starting application webcontentprovider.
[12/9/20 9:39:36:294 CST] 00000068 bm.ws.app.manager.war.internal.WARDeployedAppInfoFactoryImpl I CWWKZ0136I: The webcontentprovider application is using the archive file at the C:\Users\Mei-HsiangChang\libertyGit\open-liberty\dev\build.image\wlp\usr\servers\com.ibm.ws.wssecurity_fat.sample\dropins\webcontentprovider.war location.
[12/9/20 9:39:36:400 CST] 00000055 com.ibm.ws.app.manager.AppMessageHelper                      I CWWKZ0018I: Starting application WSSampleSei.
[12/9/20 9:39:36:400 CST] 00000055 bm.ws.app.manager.war.internal.WARDeployedAppInfoFactoryImpl I CWWKZ0136I: The WSSampleSei application is using the archive file at the C:\Users\Mei-HsiangChang\libertyGit\open-liberty\dev\build.image\wlp\usr\servers\com.ibm.ws.wssecurity_fat.sample\dropins\WSSampleSei.war location.
[12/9/20 9:39:36:604 CST] 00000056 com.ibm.ws.logging.internal.impl.IncidentImpl                I FFDC1015I: An FFDC Incident has been created: "java.io.FileNotFoundException: C:\Users\Mei-HsiangChang\libertyGit\open-liberty\dev\build.image\wlp\usr\servers\com.ibm.ws.wssecurity_fat.sample\apps\WSSampleSeiClient (Access is denied.) com.ibm.ws.classloading.java2sec.PermissionManager 776" at ffdc_20.12.09_09.39.36.1.log
[12/9/20 9:39:36:604 CST] 00000059 com.ibm.ws.logging.internal.impl.IncidentImpl                I FFDC1015I: An FFDC Incident has been created: "java.io.FileNotFoundException: C:\Users\Mei-HsiangChang\libertyGit\open-liberty\dev\build.image\wlp\usr\servers\com.ibm.ws.wssecurity_fat.sample\apps\webcontent (Access is denied.) com.ibm.ws.classloading.java2sec.PermissionManager 776" at ffdc_20.12.09_09.39.36.0.log
[12/9/20 9:39:37:304 CST] 0000004b com.ibm.ws.ssl.config.WSKeyStore                             I CWPKI0819I: The default keystore is not created because a password is not configured on the <keyStore id="defaultKeyStore"/> element, and the 'keystore_password' environment variable is not set. 
[12/9/20 9:39:37:812 CST] 00000059 com.ibm.ws.session.WASSessionCore                            I SESN8501I: The session manager did not find a persistent storage location; HttpSession objects will be stored in the local application server's memory.
[12/9/20 9:39:37:820 CST] 00000059 com.ibm.ws.webcontainer.osgi.webapp.WebGroup                 I SRVE0169I: Loading Web Module: webcontent.
[12/9/20 9:39:37:820 CST] 00000059 com.ibm.ws.webcontainer                                      I SRVE0250I: Web Module webcontent has been bound to default_host.
[12/9/20 9:39:37:827 CST] 00000059 com.ibm.ws.http.internal.VirtualHostImpl                     A CWWKT0016I: Web application available (default_host): http://host.docker.internal:8010/webcontent/
[12/9/20 9:39:38:140 CST] 00000066 org.apache.cxf.management.jmx.InstrumentationManagerImpl     I registering MBean org.apache.cxf:bus.id=webcontent-Client-Bus,type=Bus,instance.id=-1688227253: org.apache.cxf.bus.ManagedBus@55c756ac
[12/9/20 9:39:38:178 CST] 00000066 org.apache.cxf.management.jmx.InstrumentationManagerImpl     I registered org.apache.cxf:bus.id=webcontent-Client-Bus,type=Bus,instance.id=-1688227253
[12/9/20 9:39:38:431 CST] 00000066 org.apache.cxf.management.jmx.InstrumentationManagerImpl     I registering MBean org.apache.cxf:bus.id=webcontent-Client-Bus,WorkQueueManager=Bus.WorkQueueManager,type=WorkQueueManager,instance.id=2001366959: org.apache.cxf.bus.managers.WorkQueueManagerImplMBeanWrapper@e8908617
[12/9/20 9:39:38:431 CST] 00000056 com.ibm.ws.webcontainer.osgi.webapp.WebGroup                 I SRVE0169I: Loading Web Module: WSSampleSeiClient.
[12/9/20 9:39:38:431 CST] 00000056 com.ibm.ws.webcontainer                                      I SRVE0250I: Web Module WSSampleSeiClient has been bound to default_host.
[12/9/20 9:39:38:431 CST] 00000056 com.ibm.ws.http.internal.VirtualHostImpl                     A CWWKT0016I: Web application available (default_host): http://host.docker.internal:8010/WSSampleSeiClient/
[12/9/20 9:39:38:557 CST] 00000066 com.ibm.ws.session.WASSessionCore                            I SESN0176I: A new session context will be created for application key default_host/webcontent
[12/9/20 9:39:38:573 CST] 00000066 com.ibm.ws.util                                              I SESN0172I: The session manager is using the Java default SecureRandom implementation for session ID generation.
[12/9/20 9:39:38:611 CST] 0000005d com.ibm.ws.webcontainer.osgi.mbeans.PluginGenerator          I SRVE9103I: A configuration file for a web server plugin was automatically generated for this server at C:\Users\Mei-HsiangChang\libertyGit\open-liberty\dev\build.image\wlp\usr\servers\com.ibm.ws.wssecurity_fat.sample\logs\state\plugin-cfg.xml.
[12/9/20 9:39:38:686 CST] 00000066 com.ibm.ws.webcontainer.webapp                               W SRVE0274W: Error while adding servlet mapping for path-->/CxfClientServlet, wrapper-->ServletWrapper[CxfClientServlet:[/CxfClientServlet]], application-->webcontent.
[12/9/20 9:39:38:705 CST] 00000066 com.ibm.ws.cache.CacheServiceImpl                            I DYNA1056I: Dynamic Cache (object cache) initialized successfully.
[12/9/20 9:39:38:713 CST] 00000066 com.ibm.ws.app.manager.AppMessageHelper                      A CWWKZ0001I: Application webcontent started in 2.530 seconds.

```

FFDC:
```
------Start of DE processing------ = [12/9/20 9:39:36:482 CST]
Exception = java.io.FileNotFoundException
Source = com.ibm.ws.classloading.java2sec.PermissionManager
probeid = 776
Stack Dump = java.io.FileNotFoundException: C:\Users\Mei-HsiangChang\libertyGit\open-liberty\dev\build.image\wlp\usr\servers\com.ibm.ws.wssecurity_fat.sample\apps\webcontent (Access is denied.)
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:241)
	at java.util.zip.ZipFile.<init>(ZipFile.java:171)
	at java.util.zip.ZipFile.<init>(ZipFile.java:142)
	at com.ibm.ws.classloading.java2sec.PermissionManager.RecursiveFind(PermissionManager.java:774)
	at com.ibm.ws.classloading.java2sec.PermissionManager.addPermissionsXMLPermission(PermissionManager.java:690)
	at com.ibm.ws.app.manager.module.internal.DeployedAppInfoBase.addPermissions(DeployedAppInfoBase.java:467)
	at com.ibm.ws.app.manager.module.internal.DeployedAppInfoBase.getProtectionDomain(DeployedAppInfoBase.java:406)
	at com.ibm.ws.app.manager.war.internal.WARDeployedAppInfo.createModuleClassLoader(WARDeployedAppInfo.java:98)
	at com.ibm.ws.app.manager.module.internal.ExtendedModuleInfoImpl.getClassLoader(ExtendedModuleInfoImpl.java:122)
	at com.ibm.ws.container.service.annocache.internal.ModuleAnnotationsImpl.<init>(ModuleAnnotationsImpl.java:196)
	at com.ibm.ws.container.service.annocache.internal.ModuleAnnotationsImpl.<init>(ModuleAnnotationsImpl.java:159)
	at com.ibm.ws.container.service.annocache.internal.WebAnnotationsImpl.<init>(WebAnnotationsImpl.java:89)
	at com.ibm.ws.container.service.annocache.internal.WebAnnotationsAdapterImpl.adapt(WebAnnotationsAdapterImpl.java:61)
	at com.ibm.ws.container.service.annocache.internal.WebAnnotationsAdapterImpl.adapt(WebAnnotationsAdapterImpl.java:33)
	at com.ibm.ws.adaptable.module.internal.AdapterFactoryServiceImpl.adapt(AdapterFactoryServiceImpl.java:200)
	at com.ibm.ws.adaptable.module.internal.AdaptableContainerImpl.adapt(AdaptableContainerImpl.java:174)
	at com.ibm.ws.container.service.annocache.AnnotationsBetaHelper.getWebAnnotations(AnnotationsBetaHelper.java:268)
	at com.ibm.ws.webcontainer.osgi.container.config.WebAppConfigurator.setWebAnnotations(WebAppConfigurator.java:85)
	at com.ibm.ws.webcontainer.osgi.container.config.WebAppConfigurator.configure(WebAppConfigurator.java:400)
	at com.ibm.ws.webcontainer.osgi.container.config.WebAppConfigurationAdapter.adapt(WebAppConfigurationAdapter.java:119)
	at com.ibm.ws.webcontainer.osgi.container.config.WebAppConfigurationAdapter.adapt(WebAppConfigurationAdapter.java:43)
	at com.ibm.ws.adaptable.module.internal.AdapterFactoryServiceImpl.adapt(AdapterFactoryServiceImpl.java:200)
	at com.ibm.ws.adaptable.module.internal.AdaptableContainerImpl.adapt(AdaptableContainerImpl.java:174)
	at com.ibm.ws.webcontainer.osgi.WebContainer.createModuleMetaData(WebContainer.java:851)
	at com.ibm.ws.app.manager.module.internal.ModuleHandlerBase.createModuleMetaData(ModuleHandlerBase.java:63)
	at com.ibm.ws.app.manager.module.internal.SimpleDeployedAppInfoBase$ModuleContainerInfoBase.createModuleMetaData(SimpleDeployedAppInfoBase.java:189)
	at com.ibm.ws.app.manager.module.internal.SimpleDeployedAppInfoBase.preDeployApp(SimpleDeployedAppInfoBase.java:532)
	at com.ibm.ws.app.manager.module.internal.SimpleDeployedAppInfoBase.installApp(SimpleDeployedAppInfoBase.java:508)
	at com.ibm.ws.app.manager.module.internal.DeployedAppInfoBase.deployApp(DeployedAppInfoBase.java:349)
	at com.ibm.ws.app.manager.war.internal.WARApplicationHandlerImpl.install(WARApplicationHandlerImpl.java:65)
	at com.ibm.ws.app.manager.internal.statemachine.StartAction.execute(StartAction.java:144)
	at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.enterState(ApplicationStateMachineImpl.java:1317)
	at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.run(ApplicationStateMachineImpl.java:897)
	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:239)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:818)

```

```
------Start of DE processing------ = [12/9/20 9:39:36:504 CST]
Exception = java.io.FileNotFoundException
Source = com.ibm.ws.classloading.java2sec.PermissionManager
probeid = 776
Stack Dump = java.io.FileNotFoundException: C:\Users\Mei-HsiangChang\libertyGit\open-liberty\dev\build.image\wlp\usr\servers\com.ibm.ws.wssecurity_fat.sample\apps\WSSampleSeiClient (Access is denied.)
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:241)
	at java.util.zip.ZipFile.<init>(ZipFile.java:171)
	at java.util.zip.ZipFile.<init>(ZipFile.java:142)
	at com.ibm.ws.classloading.java2sec.PermissionManager.RecursiveFind(PermissionManager.java:774)
	at com.ibm.ws.classloading.java2sec.PermissionManager.addPermissionsXMLPermission(PermissionManager.java:690)
	at com.ibm.ws.app.manager.module.internal.DeployedAppInfoBase.addPermissions(DeployedAppInfoBase.java:467)
	at com.ibm.ws.app.manager.module.internal.DeployedAppInfoBase.getProtectionDomain(DeployedAppInfoBase.java:406)
	at com.ibm.ws.app.manager.war.internal.WARDeployedAppInfo.createModuleClassLoader(WARDeployedAppInfo.java:98)
	at com.ibm.ws.app.manager.module.internal.ExtendedModuleInfoImpl.getClassLoader(ExtendedModuleInfoImpl.java:122)
	at com.ibm.ws.container.service.annocache.internal.ModuleAnnotationsImpl.<init>(ModuleAnnotationsImpl.java:196)
	at com.ibm.ws.container.service.annocache.internal.ModuleAnnotationsImpl.<init>(ModuleAnnotationsImpl.java:159)
	at com.ibm.ws.container.service.annocache.internal.WebAnnotationsImpl.<init>(WebAnnotationsImpl.java:89)
	at com.ibm.ws.container.service.annocache.internal.WebAnnotationsAdapterImpl.adapt(WebAnnotationsAdapterImpl.java:61)
	at com.ibm.ws.container.service.annocache.internal.WebAnnotationsAdapterImpl.adapt(WebAnnotationsAdapterImpl.java:33)
	at com.ibm.ws.adaptable.module.internal.AdapterFactoryServiceImpl.adapt(AdapterFactoryServiceImpl.java:200)
	at com.ibm.ws.adaptable.module.internal.AdaptableContainerImpl.adapt(AdaptableContainerImpl.java:174)
	at com.ibm.ws.container.service.annocache.AnnotationsBetaHelper.getWebAnnotations(AnnotationsBetaHelper.java:268)
	at com.ibm.ws.webcontainer.osgi.container.config.WebAppConfigurator.setWebAnnotations(WebAppConfigurator.java:85)
	at com.ibm.ws.webcontainer.osgi.container.config.WebAppConfigurator.configure(WebAppConfigurator.java:400)
	at com.ibm.ws.webcontainer.osgi.container.config.WebAppConfigurationAdapter.adapt(WebAppConfigurationAdapter.java:119)
	at com.ibm.ws.webcontainer.osgi.container.config.WebAppConfigurationAdapter.adapt(WebAppConfigurationAdapter.java:43)
	at com.ibm.ws.adaptable.module.internal.AdapterFactoryServiceImpl.adapt(AdapterFactoryServiceImpl.java:200)
	at com.ibm.ws.adaptable.module.internal.AdaptableContainerImpl.adapt(AdaptableContainerImpl.java:174)
	at com.ibm.ws.webcontainer.osgi.WebContainer.createModuleMetaData(WebContainer.java:851)
	at com.ibm.ws.app.manager.module.internal.ModuleHandlerBase.createModuleMetaData(ModuleHandlerBase.java:63)
	at com.ibm.ws.app.manager.module.internal.SimpleDeployedAppInfoBase$ModuleContainerInfoBase.createModuleMetaData(SimpleDeployedAppInfoBase.java:189)
	at com.ibm.ws.app.manager.module.internal.SimpleDeployedAppInfoBase.preDeployApp(SimpleDeployedAppInfoBase.java:532)
	at com.ibm.ws.app.manager.module.internal.SimpleDeployedAppInfoBase.installApp(SimpleDeployedAppInfoBase.java:508)
	at com.ibm.ws.app.manager.module.internal.DeployedAppInfoBase.deployApp(DeployedAppInfoBase.java:349)
	at com.ibm.ws.app.manager.war.internal.WARApplicationHandlerImpl.install(WARApplicationHandlerImpl.java:65)
	at com.ibm.ws.app.manager.internal.statemachine.StartAction.execute(StartAction.java:144)
	at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.enterState(ApplicationStateMachineImpl.java:1317)
	at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.run(ApplicationStateMachineImpl.java:897)
	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:239)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:818)
```

**Comment by meiaus** [comment]
The current checked-in repo containing the CXF FAT samples client apps:

https://github.com/meiaus/open-liberty/tree/mei_wssecurity_migfat1015/dev/com.ibm.ws.wssecurity_fat.wsscxf/publish/servers/com.ibm.ws.wssecurity_fat.sample/apps
