### ISSUE TITLE
CDI TCK: Test App Fails to Start Intermittently

### ISSUE THREAD

**Issue by brideck** [OpenLiberty/open-liberty#15420]
The CDI TCK contains a test application that is designed to fail to start with the following exception:
```
jakarta.enterprise.inject.spi.DefinitionException: CWOWB1007E: The producer field, org.jboss.cdi.tck.tests.implementation.simple.resource.broken.type.ResourceProducer.manager, has type java.lang.String, which does not match the type of the injected object.
	at com.ibm.ws.cdi.impl.weld.injection.EEValidationUtils.throwDefinitionException(EEValidationUtils.java:77)
	at com.ibm.ws.cdi.impl.weld.injection.EEValidationUtils.throwDefinitionException(EEValidationUtils.java:81)
	at com.ibm.ws.cdi.impl.weld.injection.EEValidationUtils.validateJndiLookup(EEValidationUtils.java:226)
	at com.ibm.ws.cdi.impl.weld.injection.EEValidationUtils.validateJndiLookup(EEValidationUtils.java:168)
	at com.ibm.ws.cdi.impl.weld.injection.EEValidationUtils.validateResource(EEValidationUtils.java:354)
	at com.ibm.ws.cdi.impl.weld.injection.WebSphereInjectionServicesImpl.validateAnnotatedMember(WebSphereInjectionServicesImpl.java:383)
	at com.ibm.ws.cdi.impl.weld.injection.WebSphereInjectionServicesImpl.registerInjectionTarget(WebSphereInjectionServicesImpl.java:350)
	at org.jboss.weld.manager.InjectionTargetFactoryImpl.postProcess(InjectionTargetFactoryImpl.java:159)
	at org.jboss.weld.manager.InjectionTargetFactoryImpl.createInjectionTarget(InjectionTargetFactoryImpl.java:94)
	at org.jboss.weld.bean.ManagedBean.<init>(ManagedBean.java:102)
	at org.jboss.weld.bean.ManagedBean.of(ManagedBean.java:82)
	at org.jboss.weld.bootstrap.AbstractBeanDeployer.createManagedBean(AbstractBeanDeployer.java:280)
	at org.jboss.weld.bootstrap.BeanDeployer.createClassBean(BeanDeployer.java:221)
	at org.jboss.weld.bootstrap.ConcurrentBeanDeployer$2.doWork(ConcurrentBeanDeployer.java:68)
	at org.jboss.weld.bootstrap.ConcurrentBeanDeployer$2.doWork(ConcurrentBeanDeployer.java:65)
	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:62)
	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:55)
	at com.ibm.ws.threading.internal.PolicyTaskFutureImpl.run(PolicyTaskFutureImpl.java:718)
	at com.ibm.ws.threading.internal.PolicyExecutorImpl.runTask(PolicyExecutorImpl.java:1135)
	at com.ibm.ws.threading.internal.PolicyExecutorImpl.invokeAll(PolicyExecutorImpl.java:684)
	at com.ibm.ws.concurrent.internal.ManagedExecutorServiceImpl.invokeAll(ManagedExecutorServiceImpl.java:543)
	at org.jboss.weld.executor.AbstractExecutorServices.invokeAllAndCheckForExceptions(AbstractExecutorServices.java:59)
	at org.jboss.weld.executor.AbstractExecutorServices.invokeAllAndCheckForExceptions(AbstractExecutorServices.java:67)
	at org.jboss.weld.bootstrap.ConcurrentBeanDeployer.createClassBeans(ConcurrentBeanDeployer.java:65)
	at org.jboss.weld.bootstrap.BeanDeployment.createBeans(BeanDeployment.java:256)
	at org.jboss.weld.bootstrap.WeldStartup.deployBeans(WeldStartup.java:438)
	at org.jboss.weld.bootstrap.WeldBootstrap.deployBeans(WeldBootstrap.java:86)
	at com.ibm.ws.cdi.impl.CDIContainerImpl.startInitialization(CDIContainerImpl.java:160)
	at com.ibm.ws.cdi.liberty.CDIRuntimeImpl.applicationStarting(CDIRuntimeImpl.java:479)
	at com.ibm.ws.container.service.state.internal.ApplicationStateManager.fireStarting(ApplicationStateManager.java:51)
	at com.ibm.ws.container.service.state.internal.StateChangeServiceImpl.fireApplicationStarting(StateChangeServiceImpl.java:50)
	at com.ibm.ws.app.manager.module.internal.SimpleDeployedAppInfoBase.preDeployApp(SimpleDeployedAppInfoBase.java:547)
	at com.ibm.ws.app.manager.module.internal.SimpleDeployedAppInfoBase.installApp(SimpleDeployedAppInfoBase.java:508)
	at com.ibm.ws.app.manager.module.internal.DeployedAppInfoBase.deployApp(DeployedAppInfoBase.java:349)
	at com.ibm.ws.app.manager.war.internal.WARApplicationHandlerImpl.install(WARApplicationHandlerImpl.java:65)
	at com.ibm.ws.app.manager.internal.statemachine.StartAction.execute(StartAction.java:149)
	at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.enterState(ApplicationStateMachineImpl.java:1317)
	at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.performAction(ApplicationStateMachineImpl.java:1162)
	at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.run(ApplicationStateMachineImpl.java:905)
	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:239)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

However, sometimes the application just gets stuck in the STARTING state and the test fails:
```
CWWKZ0022W: Application 99a758fa9ec19d6faae5397ba59ca914e5593a37 has not started in 30.001 seconds.
```

The test fails more often than not when running with the webProfile-9.0 feature and passes more often than not when running with the jakartaee-9.0 feature.  I have collected App Manager & CDI trace from both a failing WebProfile run and a passing JakartaEE run and have made that available to the CDI development team.

**Comment by brideck** [comment]
Looking at the trace I've collected myself, I can see that in the failing trace a call to BeanDeploymentArchiveImpl.getBeanManager simply fails to ever return for some reason:
```
[1/4/21 16:51:41:298 EST] 00000232 id=2091399d com.ibm.ws.cdi.impl.weld.BeanDeploymentArchiveImpl           > getBeanManager Entry 
```

The passing case returns immediately:
```
[1/4/21 14:13:45:281 EST] 0000012e id=51f06bd3 com.ibm.ws.cdi.impl.weld.BeanDeploymentArchiveImpl           > getBeanManager Entry 
[1/4/21 14:13:45:281 EST] 0000012e id=51f06bd3 com.ibm.ws.cdi.impl.weld.BeanDeploymentArchiveImpl           < getBeanManager Exit  
                                                                                                               Weld BeanManager for 99a758fa9ec19d6faae5397ba59ca914e5593a37#99a758fa9ec19d6faae5397ba59ca914e5593a37.war [bean count=2]
```

**Comment by tevans78** [comment]
Was resolved by https://github.com/OpenLiberty/open-liberty/pull/15457
