### ISSUE TITLE
NullPointerException in HttpServletRequest or HttpServletResponse context proxies

### ISSUE THREAD

**Issue by jim-krueger** [OpenLiberty/open-liberty#15550]
Using the HttpServletRequest or HttpServletResponse JAX-RS context proxies with a null runtime context may result in a NullPointerException similar to the following:

java.lang.NullPointerException
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
at java.lang.reflect.Method.invoke(Method.java:508)
at com.ibm.ws.jaxrs20.injection.HttpServletRequestInjectionProxy$1.invoke(HttpServletRequestInjectionProxy.java:58)

**Comment by jim-krueger** [comment]
This issue is resolved by adding null checks to these two proxy classes similar to those in other proxy classes.
