### ISSUE TITLE
java.lang.ClassNotFoundException: my.custom.Object (no security manager: RMI class loader disabled)

### ISSUE THREAD

**Issue by c-koell** [OpenLiberty/open-liberty#15590]
**Describe the bug**
We try to invoke a remote MBean via JMX (RMI). The return value from the MBean attribute is a custom class (my.custom.Object)
We see following stacktrace
```
error unmarshalling return; nested exception is: 
	java.lang.ClassNotFoundException: my.custom.Object (no security manager: RMI class loader disabled) - [REAL-CAUSE] class java.lang.ClassNotFoundException - [REAL-CAUSE MESSAGE -0] my.custom.Object (no security manager: RMI class loader disabled)
java.rmi.UnmarshalException: error unmarshalling return; nested exception is: 
	java.lang.ClassNotFoundException: my.custom.Object (no security manager: RMI class loader disabled)
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:197) ~[?:?]
	at jdk.jmx.remote.internal.rmi.PRef.invoke(Unknown Source) ~[?:?]
	at javax.management.remote.rmi.RMIConnectionImpl_Stub.getAttribute(Unknown Source) ~[?:?]
	at javax.management.remote.rmi.RMIConnector$RemoteMBeanServerConnection.getAttribute(RMIConnector.java:904) ~[?:?]
	at at.gv.tirol.common.jmx.JMXConnection.getAttribute(JMXConnection.java:92)
...
Caused by: java.lang.ClassNotFoundException: my.custom.Object (no security manager: RMI class loader disabled)
at sun.rmi.server.LoaderHandler.loadClass(LoaderHandler.java:405) ~[?:?]
at sun.rmi.server.LoaderHandler.loadClass(LoaderHandler.java:195) ~[?:?]
at java.rmi.server.RMIClassLoader$2.loadClass(RMIClassLoader.java:637) ~[?:?]
at java.rmi.server.RMIClassLoader.loadClass(RMIClassLoader.java:264) ~[?:?]
at sun.rmi.server.MarshalInputStream.resolveClass(MarshalInputStream.java:213) ~[?:?]
at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2117) ~[?:?]
at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1984) ~[?:?]
at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2291) ~[?:?]
at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1801) ~[?:?]
at java.io.ObjectInputStream.readObject(ObjectInputStream.java:577) ~[?:?]
at java.io.ObjectInputStream.readObject(ObjectInputStream.java:487) ~[?:?]
at java.util.HashMap.readObject(HashMap.java:1458) ~[?:?]
at jdk.internal.reflect.GeneratedMethodAccessor1206.invoke(Unknown Source) ~[?:?]
at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1175) ~[?:?]
at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2452) ~[?:?]
at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2318) ~[?:?]
at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1801) ~[?:?]
at java.io.ObjectInputStream.readObject(ObjectInputStream.java:577) ~[?:?]
at java.io.ObjectInputStream.readObject(ObjectInputStream.java:487) ~[?:?]
at sun.rmi.server.UnicastRef.unmarshalValue(UnicastRef.java:327) ~[?:?]
at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:177) ~[?:?]
... 66 more
```
If i try the same code in a standalone java application no exception occurs.

**Expected behavior**
Is it possible to configure the classloader ? and this code works fine on websphere 9

**Diagnostic information:**
 - OpenLiberty Version: 20.0.0.12
 - Java Version: Eclipse OpenJ9 VM, Version 11.0.9+11

**Comment by c-koell** [comment]
Hi!

Is this a problem of the classloader from openliberty ?
We need to invoke MBeans with custom class so it would be great if someone can have a look at this ... thanks !

**Comment by c-koell** [comment]
Hi once again .. it would be great to get some feedback here ... thanks in advance

**Comment by c-koell** [comment]
Apologize for the noise but i have found that it is a classloader problem at my side :-(
