### ISSUE TITLE
Test Failure: com.ibm.ws.logging.fat.InvalidTraceSpecificationTest.testValidTraceSpec

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#15623]
RTC 279884

```
testValidTraceSpec:java.lang.Exception: 2020-10-03-13:31:05:116 Errors/warnings were found in server com.ibm.ws.logging.tracespec logs:
<br>[10/3/20, 13:27:39:363 BST] 00000050 com.ibm.ws.config.xml.internal.ConfigRefresher               W CWWKG0027W: Timeout while updating server configuration.
at componenttest.topology.impl.LibertyServer.checkLogsForErrorsAndWarnings(LibertyServer.java:2555)
at componenttest.topology.impl.LibertyServer.stopServer(LibertyServer.java:2420)
at componenttest.topology.impl.LibertyServer.stopServer(LibertyServer.java:2235)
at componenttest.topology.impl.LibertyServer.stopServer(LibertyServer.java:2210)
at com.ibm.ws.logging.fat.InvalidTraceSpecificationTest.tearDown(InvalidTraceSpecificationTest.java:162)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:197)
at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:318)
at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:171)
```

PR https://github.com/OpenLiberty/open-liberty/pull/14036 attempted to fix #14250 but it might have introduced this.

**Comment by fmhwong** [comment]
No occurrence in last 2 weeks
