### ISSUE TITLE
Test Failure: junit.framework.TestSuite.com.ibm.ws.logstash.collector.tests.LogstashSSLTest

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#15702]
RTC 281093

```
com.ibm.ws.logstash.collector.tests.LogstashSSLTest:org.testcontainers.containers.ContainerLaunchException: Container startup failed
    at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:327)
    at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:308)
    at org.testcontainers.containers.GenericContainer.starting(GenericContainer.java:1021)
    at org.testcontainers.containers.FailureDetectingExternalResource$1.evaluate(FailureDetectingExternalResource.java:29)
    at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:318)
    at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:171)
Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
    at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)
    at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:320)
Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container
    at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:494)
    at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:322)
    at org.testcontainers.containers.GenericContainer$$Lambda$72/000000000000000000.call(Unknown Source)
    at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
Caused by: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for container port to open (libh-docker-10.fyre.ibm.com ports: [34534] should be listening)
    at org.testcontainers.containers.wait.strategy.HostPortWaitStrategy.waitUntilReady(HostPortWaitStrategy.java:49)
    at org.testcontainers.containers.wait.strategy.AbstractWaitStrategy.waitUntilReady(AbstractWaitStrategy.java:35)
    at org.testcontainers.containers.GenericContainer.waitUntilContainerStarted(GenericContainer.java:889)
    at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:437)
```

**Comment by fmhwong** [comment]
Other tests use timeout from 3-5 mins.  Suggest to increase timeout to at least 3 mins.

https://github.com/OpenLiberty/open-liberty/blob/c6b489e86c93951ec46f45b87bb8e95effe08fed/dev/com.ibm.ws.logstash.collector_fat/fat/src/com/ibm/ws/logstash/collector/tests/LogstashCollectorTest.java#L189
