### ISSUE TITLE
Test Failure: org.eclipse.microprofile.metrics.tck.TimerTest.testRate

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#15732]
RTC 268568

```
testRate:java.lang.AssertionError: expected:<1.0> but was:<1.1203899899654197>
at org.junit.Assert.fail(Assert.java:93)
at org.junit.Assert.failNotEquals(Assert.java:647)
at org.junit.Assert.assertEquals(Assert.java:443)
at org.junit.Assert.assertEquals(Assert.java:512)
at org.eclipse.microprofile.metrics.tck.TestUtils.assertEqualsWithTolerance(TestUtils.java:41)
at org.eclipse.microprofile.metrics.tck.TimerTest.testRate(TimerTest.java:107)
```

It should be fixed with https://github.com/OpenLiberty/open-liberty/pull/14840 but not sure why it happened again.

**Comment by Channyboy** [comment]
PRs to backport:
https://github.com/eclipse/microprofile-metrics/pull/630
https://github.com/eclipse/microprofile-metrics/pull/631
https://github.com/eclipse/microprofile-metrics/pull/632
https://github.com/eclipse/microprofile-metrics/pull/633
