### ISSUE TITLE
Dumping server with variable with defaultValue throws NPE

### ISSUE THREAD

**Issue by Thihup** [OpenLiberty/open-liberty#15785]
**Describe the bug**
Running `server dump` with a running server that contains a variable with defaultValue throws NPE and the dumps/introspection/ConfigVariables.txt gets corrupted.

ConfigVariables.txt
```
The description of this introspector:
Lists all variables from server configuration files, command line properties, and the file system

User Config Variables
---------------------
foo=java.lang.NullPointerException: Cannot invoke "String.replaceAll(String, String)" because the return value of "com.ibm.ws.config.xml.LibertyVariable.getObscuredValue()" is null
	at com.ibm.ws.diagnostics.osgi.ConfigVariableIntrospection.introspect(ConfigVariableIntrospection.java:74)
	at com.ibm.ws.kernel.launch.internal.FrameworkManager$IntrospectionContext.introspect(FrameworkManager.java:1191)
	at com.ibm.ws.kernel.launch.internal.FrameworkManager$IntrospectionContext.introspectIntrospectors(FrameworkManager.java:1134)
	at com.ibm.ws.kernel.launch.internal.FrameworkManager$IntrospectionContext.introspectAll(FrameworkManager.java:1116)
	at com.ibm.ws.kernel.launch.internal.FrameworkManager.introspectFramework(FrameworkManager.java:1086)
	at com.ibm.ws.kernel.launch.internal.ServerCommandListener.executeCommand(ServerCommandListener.java:427)
	at com.ibm.ws.kernel.launch.internal.ServerCommandListener.acceptAndExecuteCommand(ServerCommandListener.java:387)
	at com.ibm.ws.kernel.launch.internal.ServerCommandListener.startListening(ServerCommandListener.java:315)
	at com.ibm.ws.kernel.launch.internal.FrameworkManager$4.run(FrameworkManager.java:763)
```

**Steps to Reproduce**
Declare a variable without value but with defaultValue:
```xml
<variable name="foo" defaultValue="test" />
```

**Expected behavior**
To see the value "test" in the ConfigVariables.txt file

**Diagnostic information:**
 - OpenLiberty Version: 21.0.0.1

**Comment by andymc12** [comment]
Looks like this could be fixed fairly easily by adding a null check here https://github.com/OpenLiberty/open-liberty/blob/4441f3384761078c7e57af89d7918480e9914ffc/dev/com.ibm.ws.diagnostics/src/com/ibm/ws/diagnostics/osgi/ConfigVariableIntrospection.java#L74

@Thihup would you be able to provide a pull request with a null check?  It should probably still write out something to indicate that it is not defined (perhaps just "NOT_DEFINED" or "null" or even an empty string), but the key is that the `getObscuredValue()` could be null.

Thanks for identifying this issue!

**Comment by Thihup** [comment]
Shouldn't the defaultValue be used in this case? From my tests in runtime it uses the defaultValue if value isn't specified.
