### ISSUE TITLE
Test Failure: componenttest.application.manager.test.AutoExtractTest.testAutoExtractEarDefinedExpandLocation

### ISSUE THREAD

**Issue by hlhoots** [OpenLiberty/open-liberty#15958]
testAutoExtractEarDefinedExpandLocation:junit.framework.AssertionFailedError: 2021-01-22-00:47:41:293 [Unexpected FFDC reporting java.io.FileNotFoundException was found (count = 1): /home/jazz_build/Build/jbe/build/dev/image/output/wlp/usr/servers/autoExtractTestServer/logs/ffdc/ffdc_21.01.22_00.47.33.0.log
>------Start of DE processing------ = [1/22/21, 0:47:33:431 PST]
>Exception = java.io.FileNotFoundException
>Source = com.ibm.ws.classloading.java2sec.PermissionManager
>probeid = 782
>Stack Dump = java.io.FileNotFoundException: /home/jazz_build/Build/jbe/build/dev/image/output/wlp/usr/servers/autoExtractTestServer/myApps/app-j2ee.ear (Is a directory)
>    at java.base/java.io.RandomAccessFile.open0(Native Method)
>    at java.base/java.io.RandomAccessFile.open(RandomAccessFile.java:345)
>    at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:259)
>    at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:214)
>    at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1271)
>    at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1237)
>    at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:727)
>    at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:844)
>    at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:247)
>    at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:177)
>    at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:148)
>    at com.ibm.ws.classloading.java2sec.PermissionManager.RecursiveFind(PermissionManager.java:780)
>    at com.ibm.ws.classloading.java2sec.PermissionManager.addPermissionsXMLPermission(PermissionManager.java:690)
>    at com.ibm.ws.app.manager.module.internal.DeployedAppInfoBase.addPermissions(DeployedAppInfoBase.java:467)
>    at com.ibm.ws.app.manager.module.internal.DeployedAppInfoBase.getProtectionDomain(DeployedAppInfoBase.java:406)
>    at com.ibm.ws.app.manager.ear.internal.EARDeployedAppInfo.basicCreateAppClassLoader(EARDeployedAppInfo.java:162)
>    at com.ibm.ws.app.manager.ear.internal.EARDeployedAppInfo.getAppClassLoader(EARDeployedAppInfo.java:121)
>    at com.ibm.ws.app.manager.ear.internal.EARDeployedAppInfo.getAppClassLoaderId(EARDeployedAppInfo.java:114)
>    at com.ibm.ws.app.manager.ear.internal.EARDeployedAppInfo.createModuleChildClassLoader(EARDeployedAppInfo.java:1325)
>    at com.ibm.ws.app.manager.ear.internal.EARDeployedAppInfo.createModuleClassLoader(EARDeployedAppInfo.java:1244)
>    at com.ibm.ws.app.manager.module.internal.ExtendedModuleInfoImpl.getClassLoader(ExtendedModuleInfoImpl.java:122)
>    at com.ibm.ws.container.service.annocache.internal.ModuleAnnotationsImpl.<init>(ModuleAnnotationsImpl.java:196)
>    at com.ibm.ws.container.service.annocache.internal.ModuleAnnotationsImpl.<init>(ModuleAnnotationsImpl.java:159)
>    at com.ibm.ws.container.service.annocache.internal.WebAnnotationsImpl.<init>(WebAnnotationsImpl.java:89)
>    at com.ibm.ws.container.service.annocache.internal.WebAnnotationsAdapterImpl.adapt(WebAnnotationsAdapterImpl.java:61)
>    at com.ibm.ws.container.service.annocache.internal.WebAnnotationsAdapterImpl.adapt(WebAnnotationsAdapterImpl.java:33)
>    at com.ibm.ws.adaptable.module.internal.AdapterFactoryServiceImpl.adapt(AdapterFactoryServiceImpl.java:200)
>    at com.ibm.ws.adaptable.module.internal.AdaptableContainerImpl.adapt(AdaptableContainerImpl.java:174)
>    at com.ibm.ws.adaptable.module.internal.InterpretedContainerImpl.adapt(InterpretedContainerImpl.java:203)
>    at com.ibm.ws.container.service.annocache.AnnotationsBetaHelper.getWebAnnotations(AnnotationsBetaHelper.java:268)
>    at com.ibm.ws.webcontainer.osgi.container.config.WebAppConfigurator.setWebAnnotations(WebAppConfigurator.java:86)
>    at com.ibm.ws.webcontainer.osgi.container.config.WebAppConfigurator.configure(WebAppConfigurator.java:415)
>    at com.ibm.ws.webcontainer.osgi.container.config.WebAppConfigurationAdapter.adapt(WebAppConfigurationAdapter.java:119)
>    at com.ibm.ws.webcontainer.osgi.container.config.WebAppConfigurationAdapter.adapt(WebAppConfigurationAdapter.java:43)
>    at com.ibm.ws.adaptable.module.internal.AdapterFactoryServiceImpl.adapt(AdapterFactoryServiceImpl.java:200)
>    at com.ibm.ws.adaptable.module.internal.AdaptableContainerImpl.adapt(AdaptableContainerImpl.java:174)
>    at com.ibm.ws.adaptable.module.internal.InterpretedContainerImpl.adapt(InterpretedContainerImpl.java:203)
>    at com.ibm.ws.webcontainer.osgi.WebContainer.createModuleMetaData(WebContainer.java:852)
>    at com.ibm.ws.app.manager.module.internal.ModuleHandlerBase.createModuleMetaData(ModuleHandlerBase.java:63)
>    at com.ibm.ws.app.manager.module.internal.SimpleDeployedAppInfoBase$ModuleContainerInfoBase.createModuleMetaData(SimpleDeployedAppInfoBase.java:189)
>    at com.ibm.ws.app.manager.module.internal.SimpleDeployedAppInfoBase.preDeployApp(SimpleDeployedAppInfoBase.java:532)
>    at com.ibm.ws.app.manager.module.internal.SimpleDeployedAppInfoBase.installApp(SimpleDeployedAppInfoBase.java:508)
>    at com.ibm.ws.app.manager.module.internal.DeployedAppInfoBase.deployApp(DeployedAppInfoBase.java:349)
>    at com.ibm.ws.app.manager.ear.internal.EARApplicationHandlerImpl.install(EARApplicationHandlerImpl.java:77)
>    at com.ibm.ws.app.manager.internal.statemachine.StartAction.execute(StartAction.java:149)
>    at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.enterState(ApplicationStateMachineImpl.java:1352)
>    at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.run(ApplicationStateMachineImpl.java:897)
>    at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:239)
>    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
>    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
>    at java.base/java.lang.Thread.run(Thread.java:834)
]
    at componenttest.custom.junit.runner.FATRunner.blowup(FATRunner.java:300)
    at componenttest.custom.junit.runner.FATRunner.access$600(FATRunner.java:66)
    at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:250)
    at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:318)
    at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:171)

**Comment by hlhoots** [comment]
Looks to be resolved in latest java 2 sec builds.  closing
