### ISSUE TITLE
Custom encryption module is receiving unexpected string 

### ISSUE THREAD

**Issue by una-tapa** [OpenLiberty/open-liberty#15961]
**Describe the bug**
Custom password encryption module is NOT receiving expected information.  

If there is a stack trace, please include the FULL stack trace (without any `[internal classes]` lines in it). To find the full stack trace, you may need to check in `$WLP_OUTPUT_DIR/messages.log`

```
[2/17/21 7:59:16:929 CET] 0000003b id=00000000 com.ibm.ws.crypto.util.PasswordCipherUtil                    E decipher CWWKS1852E: There was an unexpected exception during password decryption by using the custom password encryption serv\
ice.
com.ibm.wsspi.security.crypto.PasswordDecryptException: java.lang.IllegalArgumentException: Illegal base64 character -39
        at com.ibm.websphere.crypto.sample.customencryption.CustomEncryptionImpl.decrypt(CustomEncryptionImpl.java:157)
        at com.ibm.ws.crypto.util.PasswordCipherUtil.decipher(PasswordCipherUtil.java:214)
        at com.ibm.websphere.crypto.PasswordUtil.decode_password(PasswordUtil.java:624)
        at com.ibm.websphere.crypto.PasswordUtil.decode(PasswordUtil.java:135)
        at com.ibm.ws.jdbc.DataSourceService.parseConfiguration(DataSourceService.java:829)
        at com.ibm.ws.jdbc.DataSourceService.init(DataSourceService.java:563)
        at com.ibm.ws.jca.cm.AbstractConnectionFactoryService$2.run(AbstractConnectionFactoryService.java:522)
```

**Steps to Reproduce**
1. Create custom encryption module as a user feature
2. Configure server.xml with encrypted password (that is surely get decrypted standalone)  In my recreate, I set ` <keyStore id="defaultKeyStore" password="{custom}OhT339Bw3wymUcP92Mkz+Q==" />` 
3.  Start the Liberty server 
4. Look for the trace output from following code. 
https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.crypto.passwordutil/src/com/ibm/websphere/crypto/PasswordUtil.java#L132
```
[2/17/21 15:10:41:172 EST] 00000029 id=00000000 com.ibm.websphere.crypto.PasswordUtil                        3 decode before invoking decode_password : crypto_algorithm : custom
encoded_string : {custom}OhT339Bw3wymUcP92Mkz+Q==
[2/17/21 15:10:41:172 EST] 00000029 id=00000000 com.ibm.websphere.crypto.PasswordUtil                        3 decode_password byte array before decoding  <-   OhT339Bw3wymUcP92Mkz+Q== is BASE64 decoded to :pQ3
0000: 3A 14 F7 DF D0 70 DF 0C  A6 51 C3 FD D8 C9 33 F9  : :....p...Q....3.
[2/17/21 15:10:41:173 EST] 00000029 id=00000000 ebsphere.crypto.sample.customencryption.CustomEncryptionImpl 1 decrypt : info : com.ibm.wsspi.security.crypto.EncryptedInfo@4615cf86
```
5. Instead of passing `OhT339Bw3wymUcP92Mkz+Q==` into the PasswordCipherUtil.decrypt(), Liberty is passing in `:....p...Q....3.`
6. If I decode `OhT339Bw3wymUcP92Mkz+Q==` using BASE64Decode, I get this string `:....p...Q....3.`

**Expected behavior**
The decrypt module should receive what's configured in the server.xml

**Diagnostic information:**
 - OpenLiberty Version: [e.g. 21.0.0.1]
 - server.xml configuration (WITHOUT sensitive information like passwords)
 - If it would be useful, upload the messages.log file found in `$WLP_OUTPUT_DIR/messages.log`
```
<?xml version="1.0" encoding="UTF-8"?>
<server description="new server">

    <!-- Enable features -->
    <featureManager>
        <feature>webProfile-8.0</feature>
        <feature>usr:customEncryption-1.0</feature>
    </featureManager>

    <!-- To access this server from a remote client add a host attribute to the following element, e.g. host="*" -->
    <httpEndpoint id="defaultHttpEndpoint"
                  httpPort="9080"
                  httpsPort="9443" />
                  
    <!-- Automatically expand WAR files and EAR files -->
    <applicationManager autoExpand="true"/>

    <keyStore id="defaultKeyStore" password="{custom}OhT339Bw3wymUcP92Mkz+Q==" />

</server>
```

**Additional context**

It looks like we (unnecessarily?) decode the value by calling "convert_viewable_to_bytes" before calling custom module to decrypt.   The code is here. 
https://github.com/OpenLiberty/open-liberty/blob/976ae166877576fd0723ef2fee10d9c9d85d52fc/dev/com.ibm.ws.crypto.passwordutil/src/com/ibm/websphere/crypto/PasswordUtil.java#L609

**Comment by una-tapa** [comment]
"convert_viewable_to_string" is called for encoding. 
https://github.com/OpenLiberty/open-liberty/blob/976ae166877576fd0723ef2fee10d9c9d85d52fc/dev/com.ibm.ws.crypto.passwordutil/src/com/ibm/websphere/crypto/PasswordUtil.java#L708

Liberty performs Base64encoding/decoding for passwords.  This is not performed in tWAS custom encode/decode plugin.

**Comment by utle** [comment]
If customers do not use tWAS passwordUtil or Liberty securityUtil to encrypt the password, then it can be a problem.

**Comment by una-tapa** [comment]
If I remember correctly, this is usage issue and not the code issue  I will summarize and planning to close.

**Comment by una-tapa** [comment]
We learned that the customer no longer see the behavior after he changed the usage.  No further information available.
