### ISSUE TITLE
Running CXF X509Async FAT with trace spec org.apache.cxf.*=all failed with StackOverflowError

### ISSUE THREAD

**Issue by meiaus** [OpenLiberty/open-liberty#16074]
When running Running CXF X509Async FAT with the trace enabled via bootstrap.properties `com.ibm.ws.logging.trace.specification=*=info=enabled:org.apache.cxf.*=all=enabled`, the test failed with the following error:

messages.log:
```
[2/25/21 12:55:01:588 CST] 0000004f com.ibm.ws.webcontainer.servlet                              I SRVE0242I: [x509aSync] [/x509aSync] [X509AsyncService]: Initialization successful.
[2/25/21 12:55:01:901 CST] 0000005c .org.apache.cxf.cxf.rt.wsdl.3.2:1.0.48.202101111530(id=171)] I Creating Service {http://x509async.wssecfvt.test}X509AsyncService from WSDL: http://localhost:8010/x509aSync/X509AsyncService?wsdl
[2/25/21 12:55:02:318 CST] 0000005c com.ibm.ws.webcontainer.util.ApplicationErrorUtils           E SRVE0777E: Exception thrown by application class 'com.ibm.ws.logging.internal.WsLogger.createWsLogRecord:207'
java.lang.StackOverflowError
	at com.ibm.ws.logging.internal.WsLogger.createWsLogRecord(WsLogger.java:207)
	at com.ibm.ws.logging.internal.WsLogger.createLogRecord(WsLogger.java:187)
	at com.ibm.ws.logging.internal.WsLogger.logp(WsLogger.java:335)
	at com.ibm.ws.logging.internal.WsLogger.entering(WsLogger.java:443)
	at org.apache.cxf.jaxws.JaxWsClientProxy.invoke(JaxWsClientProxy.java:105)
	at com.sun.proxy.$Proxy82.toString(Unknown Source)
	at java.text.MessageFormat.subformat(MessageFormat.java:1291)
	at java.text.MessageFormat.format(MessageFormat.java:876)
	at java.text.Format.format(Format.java:168)
	at java.text.MessageFormat.format(MessageFormat.java:852)
```

trace log:

```
[2/25/21 12:55:02:033 CST] 0000005c id=00000000 .ws.org.apache.cxf.cxf.core.3.2:1.0.48.202101111530(id=159)] 1 the interface we are checking is test.wssecfvt.x509async.UrnX509AsyncType
[2/25/21 12:55:02:033 CST] 0000005c id=00000000 .ws.org.apache.cxf.cxf.core.3.2:1.0.48.202101111530(id=159)] 1 the interface's classloader we are checking is com.ibm.ws.classloading.internal.AppClassLoader@d84ec541
[2/25/21 12:55:02:033 CST] 0000005c id=00000000 .ws.org.apache.cxf.cxf.core.3.2:1.0.48.202101111530(id=159)] 1 the customer interface is test.wssecfvt.x509async.UrnX509AsyncType. Will try to fetch it from Cache
[2/25/21 12:55:02:033 CST] 0000005c id=00000000 .ws.org.apache.cxf.cxf.core.3.2:1.0.48.202101111530(id=159)] 1 can't find ProxyClassLoader from ClassValue Cache, will create a new one
[2/25/21 12:55:02:033 CST] 0000005c id=00000000 .ws.org.apache.cxf.cxf.core.3.2:1.0.48.202101111530(id=159)] 1 interface for new created ProxyClassLoader is test.wssecfvt.x509async.UrnX509AsyncType
[2/25/21 12:55:02:033 CST] 0000005c id=00000000 .ws.org.apache.cxf.cxf.core.3.2:1.0.48.202101111530(id=159)] 1 interface's classloader for new created ProxyClassLoader is com.ibm.ws.classloading.internal.AppClassLoader@d84ec541
[2/25/21 12:55:02:033 CST] 0000005c id=00000000 .ws.org.apache.cxf.cxf.core.3.2:1.0.48.202101111530(id=159)] 1 interface for new created ProxyClassLoader is test.wssecfvt.x509async.UrnX509AsyncType
[2/25/21 12:55:02:033 CST] 0000005c id=00000000 .ws.org.apache.cxf.cxf.core.3.2:1.0.48.202101111530(id=159)] 1 interface's classloader for new created ProxyClassLoader is com.ibm.ws.classloading.internal.AppClassLoader@d84ec541
[2/25/21 12:55:02:033 CST] 0000005c id=00000000 .ws.org.apache.cxf.cxf.core.3.2:1.0.48.202101111530(id=159)] 1 interface for new created ProxyClassLoader is javax.xml.ws.BindingProvider
[2/25/21 12:55:02:033 CST] 0000005c id=00000000 .ws.org.apache.cxf.cxf.core.3.2:1.0.48.202101111530(id=159)] 1 interface's classloader for new created ProxyClassLoader is org.eclipse.osgi.internal.loader.EquinoxClassLoader@4375d4d9[com.ibm.websphere.javaee.jaxws.2.3:1.0.48.202101111530(id=161)]
[2/25/21 12:55:02:033 CST] 0000005c id=00000000 .ws.org.apache.cxf.cxf.core.3.2:1.0.48.202101111530(id=159)] 1 interface for new created ProxyClassLoader is java.io.Closeable
[2/25/21 12:55:02:033 CST] 0000005c id=00000000 .ws.org.apache.cxf.cxf.core.3.2:1.0.48.202101111530(id=159)] 1 interface's classloader for new created ProxyClassLoader is null
[2/25/21 12:55:02:033 CST] 0000005c id=00000000 .ws.org.apache.cxf.cxf.core.3.2:1.0.48.202101111530(id=159)] 1 interface for new created ProxyClassLoader is org.apache.cxf.endpoint.Client
[2/25/21 12:55:02:033 CST] 0000005c id=00000000 .ws.org.apache.cxf.cxf.core.3.2:1.0.48.202101111530(id=159)] 1 interface's classloader for new created ProxyClassLoader is org.eclipse.osgi.internal.loader.EquinoxClassLoader@daa2d1a8[com.ibm.ws.org.apache.cxf.cxf.core.3.2:1.0.48.202101111530(id=159)]
[2/25/21 12:55:02:033 CST] 0000005c id=00000000 org.apache.cxf.common.util.ProxyHelper                       > canSeeAllInterfaces ENTRY org.apache.cxf.common.util.ProxyClassLoader@1e785d35 [Ljava.lang.Class;@ea3bead4
[2/25/21 12:55:02:033 CST] 0000005c id=00000000 org.apache.cxf.common.util.ProxyHelper                       < canSeeAllInterfaces RETURN true
[2/25/21 12:55:02:033 CST] 0000005c id=00000000 .ws.org.apache.cxf.cxf.core.3.2:1.0.48.202101111530(id=159)] 1 find required loader from ProxyClassLoader cache with key[java.io.Closeablenull, javax.xml.ws.BindingProviderorg.eclipse.osgi.internal.loader.EquinoxClassLoader@4375d4d9[com.ibm.websphere.javaee.jaxws.2.3:1.0.48.202101111530(id=161)], org.apache.cxf.endpoint.Clientorg.eclipse.osgi.internal.loader.EquinoxClassLoader@daa2d1a8[com.ibm.ws.org.apache.cxf.cxf.core.3.2:1.0.48.202101111530(id=159)], test.wssecfvt.x509async.UrnX509AsyncTypecom.ibm.ws.classloading.internal.AppClassLoader@d84ec541]
[2/25/21 12:55:02:033 CST] 0000005c id=00000000 org.apache.cxf.common.util.ProxyHelper                       < getClassLoaderForInterfaces RETURN org.apache.cxf.common.util.ProxyClassLoader@1e785d35
[2/25/21 12:55:02:318 CST] 0000005c id=00000000 com.ibm.ws.webcontainer.util.ApplicationErrorUtils           E SRVE0777E: Exception thrown by application class 'com.ibm.ws.logging.internal.WsLogger.createWsLogRecord:207'
java.lang.StackOverflowError
	at com.ibm.ws.logging.internal.WsLogger.createWsLogRecord(WsLogger.java:207)
	at com.ibm.ws.logging.internal.WsLogger.createLogRecord(WsLogger.java:187)
	at com.ibm.ws.logging.internal.WsLogger.logp(WsLogger.java:335)
	at com.ibm.ws.logging.internal.WsLogger.entering(WsLogger.java:443)
	at org.apache.cxf.jaxws.JaxWsClientProxy.invoke(JaxWsClientProxy.java:105)
	at com.sun.proxy.$Proxy82.toString(Unknown Source)
```

Note: when enabling the trace with additional substring, e.g., `org.apache.cxf.transport.*=all`, `org.apache.cxf.phase.*=all`, etc., the problem didn't appear.

The trace log zip in the box: https://ibm.ent.box.com/file/780543616445 (requiring access permission to the box folder)

**Comment by meiaus** [comment]
@arunavemulapalli @neuwerk @BerksanAtes @sawadood

**Comment by meiaus** [comment]
Attempted to recreate but the error no longer appeared.

1. From 1 test method scenario (in CxfX509ASyncTests.java), the trace string is set as ```[8/29/21, 12:12:13:593 PDT] 00000001 com.ibm.ws.logging.internal.TraceSpecification               I TRAS0018I: The trace state has been changed. The new trace state is *=info:org.apache.cxf.*=all.```

log zip in the box: https://ibm.box.com/s/5uc6tuvhtmmldkagldpcevqmqy6mm6fe

2. From all test method scenario (in CxfX509ASyncTests.java), the trace string is set as ```[8/29/21, 13:37:15:543 PDT] 00000001 com.ibm.ws.logging.internal.TraceSpecification               I TRAS0018I: The trace state has been changed. The new trace state is *=info:WSS4J=all:WSSECURITY=all:com.ibm.ws.jaxws.*=all:logservice=all:org.apache.cxf.*=all:org.apache.cxf.ws.security.message.*=all.```

log zip in the box: https://ibm.box.com/s/tt9jpbkgyy9g5t1sva2tt80bzgnvw9wg
