### ISSUE TITLE
Running OL wssecurity CXF FAT with EE8 and Java11 failed with WRONG_DOCUMENT_ERR

### ISSUE THREAD

**Issue by meiaus** [OpenLiberty/open-liberty#16072]
Running OL wssecurity FAT `com.ibm.ws.wssecurity.fat.cxf.usernametoken.CxfUNTBasicTests` with EE8 new feature runtime (jaxws-2.3, etc.) and Java11 failed with the following error:

```
[2/24/21, 15:50:15:627 CST] 00000072 .ws.org.apache.cxf.cxf.core.3.2:1.0.48.202101111530(id=161)] W Interceptor for {http://wssec.basic.cxf.fats}SOAPService2#{http://cxf.apache.org/jaxws/dispatch}Invoke has thrown exception, unwinding now
org.w3c.dom.DOMException: WRONG_DOCUMENT_ERR: A node is used in a different document than the one that created it.
	at java.xml/com.sun.org.apache.xerces.internal.dom.ParentNode.internalInsertBefore(ParentNode.java:355)
	at java.xml/com.sun.org.apache.xerces.internal.dom.ParentNode.insertBefore(ParentNode.java:286)
	at java.xml/com.sun.org.apache.xerces.internal.dom.NodeImpl.appendChild(NodeImpl.java:230)
	at org.apache.cxf.staxutils.W3CDOMStreamWriter.setChild(W3CDOMStreamWriter.java:120)
	at org.apache.cxf.staxutils.W3CDOMStreamWriter.newChild(W3CDOMStreamWriter.java:113)
	at org.apache.cxf.staxutils.W3CDOMStreamWriter.createAndAddElement(W3CDOMStreamWriter.java:171)
	at org.apache.cxf.staxutils.OverlayW3CDOMStreamWriter.createAndAddElement(OverlayW3CDOMStreamWriter.java:65)
	at org.apache.cxf.binding.soap.saaj.SAAJStreamWriter.createAndAddElement(SAAJStreamWriter.java:192)
	at org.apache.cxf.staxutils.W3CDOMStreamWriter.writeStartElement(W3CDOMStreamWriter.java:149)
	at org.apache.cxf.staxutils.OverlayW3CDOMStreamWriter.writeStartElement(OverlayW3CDOMStreamWriter.java:210)
	at org.apache.cxf.staxutils.DelegatingXMLStreamWriter.writeStartElement(DelegatingXMLStreamWriter.java:155)
```

The same FAT running with EE8 and Java8 passed without getting the above error.
When comparing to the respective trace logs between the 2 runs, it's noted the following packages are different:

From java11:
`com.sun.xml.internal.stream.writers.XMLStreamWriterImpl`
`com.sun.xml.messaging.saaj.soap.ver1_1.Message1_1Impl`

![image](https://user-images.githubusercontent.com/27024803/109429824-b8be6080-79c3-11eb-9c66-a1e53728f9d3.png)

![image](https://user-images.githubusercontent.com/27024803/109429855-d390d500-79c3-11eb-9f25-a14315305d5c.png)

```
product = Open Liberty 21.0.0.1 (wlp-1.0.48.202101111530)
wlp.install.dir = C:/Users/Mei-HsiangChang/libertyGit/open-liberty/dev/build.image/wlp/
java.home = C:\jdk-11.0.10.9-openj9
java.version = 11.0.10
java.runtime = OpenJDK Runtime Environment (11.0.10+9)
os = Windows 10 (10.0; amd64) (en_US)

```

From java8:
`com.ibm.xml.xlxp.api.stax.XMLOutputFactoryImpl$XMLStreamWriterProxy`
`com.sun.xml.internal.messaging.saaj.soap.ver1_1.Message1_Impl`

![image](https://user-images.githubusercontent.com/27024803/109429871-e3101e00-79c3-11eb-8a81-251635864342.png)

![image](https://user-images.githubusercontent.com/27024803/109429885-f15e3a00-79c3-11eb-83f8-9962040501c5.png)

```
product = Open Liberty 21.0.0.1 (wlp-1.0.48.202101111530)
wlp.install.dir = C:/Users/Mei-HsiangChang/libertyGit/open-liberty/dev/build.image/wlp/
java.home = C:\java8\ibm-java-sdk-80-win-x86_64_8.0.5.41\sdk\jre
java.version = 1.8.0_221
java.runtime = Java(TM) SE Runtime Environment (8.0.5.41 - pwa6480sr5fp41-20190919_01(SR5 FP41))
os = Windows 10 (10.0; amd64) (en_US)
```

The trace log zip (from failing scenario) in the box:  https://ibm.ent.box.com/file/781564300030 (requiring access permission to the box folder)

**Comment by meiaus** [comment]
@arunavemulapalli @neuwerk @BerksanAtes @sawadood

**Comment by meiaus** [comment]
With the fix @arunavemulapalli provided by updating com.ibm.ws.org.apache.cxf.cxf.core.3.2 **bnd.overrides** to add the package `com.sun.xml.messaging.saaj.*`, the problem is resolved.  

```
DynamicImport-Package: \
  com.ctc.wstx.*,\
  com.sun.xml.messaging.saaj.*,\
  javax.xml.ws,\
  org.apache.cxf.bus,\
  org.apache.cxf.*

```

**Comment by meiaus** [comment]
For test record:

The above bnd.overrides update resolved the oiginal `WRONG_DOCUMENT_ERR` error but new set of errors were generated including below FFDC and NPE (which is tracked in https://github.com/OpenLiberty/open-liberty/issues/17031).

For these FFDC, they are redolved by adding @AllowedFFDC in the associated test methods.
```
@AllowedFFDC(value = {  "java.security.PrivilegedActionException",
                           "java.lang.NoSuchMethodException" })
```

Taking one test method as an example for FFDC:

- Output.txt:
```
[05/03/2021 12:05:49:349 PDT] 001 FATRunner                      evaluate                       I entering com.ibm.ws.wssecurity.fat.cxf.usernametoken.CxfSSLUNTNonceTests.testCxfUntNonceOnlySSL
[05/03/2021 12:05:49:349 PDT] 001 SSLTestCommon                  testCxfUntNonceOnlySSL         I *****************************testCxfUntNonceOnlySSL
[05/03/2021 12:05:49:349 PDT] 001 SSLTestCommon                  testCxfUntNonceOnlySSL         I Invoking: https://localhost:8020/untsslclient/CxfUntSSLSvcClient
[05/03/2021 12:06:08:336 PDT] 001 SSLTestCommon                  testCxfUntNonceOnlySSL         I Response from CXF UNT SSL Service client: <html><head><title>CXF UNT SSL Service Cleint</title></head><body><p>Request: UNT CXF Service Client</p><p>Response: WSSECFVT FVTVersion_ba05</p></body></html>
[05/03/2021 12:06:08:337 PDT] 001 SSLTestCommon                  testCxfUntNonceOnlySSL         I testCxfUntNonceOnlySSL: PASS
[05/03/2021 12:06:08:358 PDT] 001 FATRunner                      evaluate                       S null
junit.framework.AssertionFailedError: [Unexpected FFDC reporting java.security.PrivilegedActionException was found (count = 1): C:\Users\Administrator\libertyGit\open-liberty\dev\build.image\wlp\usr\servers\com.ibm.ws.wssecurity_fat.ssl\logs\ffdc\ffdc_21.05.03_12.06.01.0.log
>------Start of DE processing------ = [5/3/21, 12:06:01:809 PDT]
>Exception = java.security.PrivilegedActionException
>Source = org.apache.wss4j.dom.util.WSSecurityUtil
>probeid = 135
>Stack Dump = java.security.PrivilegedActionException: java.lang.NoSuchMethodException: com.sun.org.apache.xerces.internal.dom.ElementNSImpl.getDomElement()
>	at java.base/java.security.AccessController.doPrivileged(AccessController.java:742)
>	at org.apache.wss4j.dom.util.WSSecurityUtil.getMethod(WSSecurityUtil.java:130)
>	at org.apache.wss4j.dom.util.WSSecurityUtil.access$000(WSSecurityUtil.java:62)
>	at org.apache.wss4j.dom.util.WSSecurityUtil$1.computeValue(WSSecurityUtil.java:73)
>	at org.apache.wss4j.dom.util.WSSecurityUtil$1.computeValue(WSSecurityUtil.java:69)
>	at java.base/java.lang.ClassValue.getFromHashMap(ClassValue.java:228)
>	at java.base/java.lang.ClassValue.getFromBackup(ClassValue.java:210)
>	at java.base/java.lang.ClassValue.get(ClassValue.java:116)
>	at org.apache.wss4j.dom.util.WSSecurityUtil.getDomElement(WSSecurityUtil.java:697)
>	at org.apache.wss4j.dom.util.WSSecurityUtil.prependChildElement(WSSecurityUtil.java:364)
>	at org.apache.wss4j.dom.util.WSSecurityUtil.findWsseSecurityHeaderBlock(WSSecurityUtil.java:491)
>	at org.apache.wss4j.dom.message.WSSecHeader.insertSecurityHeader(WSSecHeader.java:167)
>	at org.apache.cxf.ws.security.wss4j.PolicyBasedWSS4JOutInterceptor$PolicyBasedWSS4JOutInterceptorInternal.handleMessageInternal(PolicyBasedWSS4JOutInterceptor.java:145)
>	at org.apache.cxf.ws.security.wss4j.PolicyBasedWSS4JOutInterceptor$PolicyBasedWSS4JOutInterceptorInternal.handleMessage(PolicyBasedWSS4JOutInterceptor.java:110)
>	at org.apache.cxf.ws.security.wss4j.PolicyBasedWSS4JOutInterceptor$PolicyBasedWSS4JOutInterceptorInternal.handleMessage(PolicyBasedWSS4JOutInterceptor.java:97)
>	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
>	at org.apache.cxf.endpoint.ClientImpl.doInvoke(ClientImpl.java:530)
>	at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:441)
>	at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:356)
>	at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:314)
>	at org.apache.cxf.endpoint.ClientImpl.invokeWrapped(ClientImpl.java:349)
>	at org.apache.cxf.jaxws.DispatchImpl.invoke(DispatchImpl.java:322)
>	at org.apache.cxf.jaxws.DispatchImpl.invoke(DispatchImpl.java:241)
>	at com.ibm.ws.wssecurity.fat.untsslclient.CxfUntSSLSvcClient.doWorker(CxfUntSSLSvcClient.java:479)
>	at com.ibm.ws.wssecurity.fat.untsslclient.CxfUntSSLSvcClient.doGet(CxfUntSSLSvcClient.java:537)
>	at javax.servlet.http.HttpServlet.service(HttpServlet.java:686)
>	at javax.servlet.http.HttpServlet.service(HttpServlet.java:791)
>	at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1258)
>	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:746)
>	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:443)
>	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.invokeTarget(WebAppFilterChain.java:183)
>	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:94)
>	at com.ibm.ws.security.jaspi.JaspiServletFilter.doFilter(JaspiServletFilter.java:56)
>	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:201)
>	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:91)
>	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.doFilter(WebAppFilterManager.java:1002)
>	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1140)
>	at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:5061)
>	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.handleRequest(DynamicVirtualHost.java:314)
>	at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:1007)
>	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:279)
>	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1159)
>	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:428)
>	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:387)
>	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:566)
>	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:500)
>	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:360)
>	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.ready(HttpInboundLink.java:327)
>	at com.ibm.ws.channel.ssl.internal.SSLConnectionLink.determineNextChannel(SSLConnectionLink.java:1100)
>	at com.ibm.ws.channel.ssl.internal.SSLConnectionLink.readyInboundPostHandshake(SSLConnectionLink.java:757)
>	at com.ibm.ws.channel.ssl.internal.SSLConnectionLink$MyHandshakeCompletedCallback.complete(SSLConnectionLink.java:427)
>	at com.ibm.ws.channel.ssl.internal.SSLUtils.handleHandshake(SSLUtils.java:954)
>	at com.ibm.ws.channel.ssl.internal.SSLHandshakeIOCallback.complete(SSLHandshakeIOCallback.java:85)
>	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:504)
>	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueManager.java:574)
>	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:958)
>	at com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:1047)
>	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:238)
>	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
>	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
>	at java.base/java.lang.Thread.run(Thread.java:836)
>Caused by: java.lang.NoSuchMethodException: com.sun.org.apache.xerces.internal.dom.ElementNSImpl.getDomElement()
>	at java.base/java.lang.Class.newNoSuchMethodException(Class.java:635)
>	at java.base/java.lang.Class.throwExceptionOrReturnNull(Class.java:1385)
>	at java.base/java.lang.Class.getMethodHelper(Class.java:1471)
>	at java.base/java.lang.Class.getMethod(Class.java:1377)
>	at org.apache.wss4j.dom.util.WSSecurityUtil$3.run(WSSecurityUtil.java:132)
>	at org.apache.wss4j.dom.util.WSSecurityUtil$3.run(WSSecurityUtil.java:130)
>	at java.base/java.security.AccessController.doPrivileged(AccessController.java:738)
>	... 60 more
, Unexpected FFDC reporting java.lang.NoSuchMethodException was found (count = 1): C:\Users\Administrator\libertyGit\open-liberty\dev\build.image\wlp\usr\servers\com.ibm.ws.wssecurity_fat.ssl\logs\ffdc\ffdc_21.05.03_12.06.01.1.log
>------Start of DE processing------ = [5/3/21, 12:06:01:841 PDT]
>Exception = java.lang.NoSuchMethodException
>Source = org.apache.wss4j.dom.util.WSSecurityUtil$1
>probeid = 74
>Stack Dump = java.lang.NoSuchMethodException: com.sun.org.apache.xerces.internal.dom.ElementNSImpl.getDomElement()
>	at java.base/java.lang.Class.newNoSuchMethodException(Class.java:635)
>	at java.base/java.lang.Class.throwExceptionOrReturnNull(Class.java:1385)
>	at java.base/java.lang.Class.getMethodHelper(Class.java:1471)
>	at java.base/java.lang.Class.getMethod(Class.java:1377)
>	at org.apache.wss4j.dom.util.WSSecurityUtil$3.run(WSSecurityUtil.java:132)
>	at org.apache.wss4j.dom.util.WSSecurityUtil$3.run(WSSecurityUtil.java:130)
>	at java.base/java.security.AccessController.doPrivileged(AccessController.java:738)
>	at org.apache.wss4j.dom.util.WSSecurityUtil.getMethod(WSSecurityUtil.java:130)
>	at org.apache.wss4j.dom.util.WSSecurityUtil.access$000(WSSecurityUtil.java:62)
>	at org.apache.wss4j.dom.util.WSSecurityUtil$1.computeValue(WSSecurityUtil.java:73)
>	at org.apache.wss4j.dom.util.WSSecurityUtil$1.computeValue(WSSecurityUtil.java:69)
>	at java.base/java.lang.ClassValue.getFromHashMap(ClassValue.java:228)
>	at java.base/java.lang.ClassValue.getFromBackup(ClassValue.java:210)
>	at java.base/java.lang.ClassValue.get(ClassValue.java:116)
>	at org.apache.wss4j.dom.util.WSSecurityUtil.getDomElement(WSSecurityUtil.java:697)
>	at org.apache.wss4j.dom.util.WSSecurityUtil.prependChildElement(WSSecurityUtil.java:364)
>	at org.apache.wss4j.dom.util.WSSecurityUtil.findWsseSecurityHeaderBlock(WSSecurityUtil.java:491)
>	at org.apache.wss4j.dom.message.WSSecHeader.insertSecurityHeader(WSSecHeader.java:167)
>	at org.apache.cxf.ws.security.wss4j.PolicyBasedWSS4JOutInterceptor$PolicyBasedWSS4JOutInterceptorInternal.handleMessageInternal(PolicyBasedWSS4JOutInterceptor.java:145)
>	at org.apache.cxf.ws.security.wss4j.PolicyBasedWSS4JOutInterceptor$PolicyBasedWSS4JOutInterceptorInternal.handleMessage(PolicyBasedWSS4JOutInterceptor.java:110)
>	at org.apache.cxf.ws.security.wss4j.PolicyBasedWSS4JOutInterceptor$PolicyBasedWSS4JOutInterceptorInternal.handleMessage(PolicyBasedWSS4JOutInterceptor.java:97)
>	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
>	at org.apache.cxf.endpoint.ClientImpl.doInvoke(ClientImpl.java:530)
>	at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:441)
>	at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:356)
>	at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:314)
>	at org.apache.cxf.endpoint.ClientImpl.invokeWrapped(ClientImpl.java:349)
>	at org.apache.cxf.jaxws.DispatchImpl.invoke(DispatchImpl.java:322)
>	at org.apache.cxf.jaxws.DispatchImpl.invoke(DispatchImpl.java:241)
>	at com.ibm.ws.wssecurity.fat.untsslclient.CxfUntSSLSvcClient.doWorker(CxfUntSSLSvcClient.java:479)
>	at com.ibm.ws.wssecurity.fat.untsslclient.CxfUntSSLSvcClient.doGet(CxfUntSSLSvcClient.java:537)
>	at javax.servlet.http.HttpServlet.service(HttpServlet.java:686)
>	at javax.servlet.http.HttpServlet.service(HttpServlet.java:791)
>	at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1258)
>	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:746)
>	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:443)
>	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.invokeTarget(WebAppFilterChain.java:183)
>	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:94)
>	at com.ibm.ws.security.jaspi.JaspiServletFilter.doFilter(JaspiServletFilter.java:56)
>	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:201)
>	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:91)
>	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.doFilter(WebAppFilterManager.java:1002)
>	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1140)
>	at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:5061)
>	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.handleRequest(DynamicVirtualHost.java:314)
>	at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:1007)
>	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:279)
>	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1159)
>	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:428)
>	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:387)
>	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:566)
>	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:500)
>	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:360)
>	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.ready(HttpInboundLink.java:327)
>	at com.ibm.ws.channel.ssl.internal.SSLConnectionLink.determineNextChannel(SSLConnectionLink.java:1100)
>	at com.ibm.ws.channel.ssl.internal.SSLConnectionLink.readyInboundPostHandshake(SSLConnectionLink.java:757)
>	at com.ibm.ws.channel.ssl.internal.SSLConnectionLink$MyHandshakeCompletedCallback.complete(SSLConnectionLink.java:427)
>	at com.ibm.ws.channel.ssl.internal.SSLUtils.handleHandshake(SSLUtils.java:954)
>	at com.ibm.ws.channel.ssl.internal.SSLHandshakeIOCallback.complete(SSLHandshakeIOCallback.java:85)
>	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:504)
>	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueManager.java:574)
>	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:958)
>	at com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:1047)
>	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:238)
>	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
>	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
>	at java.base/java.lang.Thread.run(Thread.java:836)
]
	at componenttest.custom.junit.runner.FATRunner.blowup(FATRunner.java:300)
	at componenttest.custom.junit.runner.FATRunner.access$600(FATRunner.java:66)
	at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:250)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:30)
	at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:318)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:171)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:24)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at componenttest.rules.repeater.RepeatTests$CompositeRepeatTestActionStatement.evaluate(RepeatTests.java:115)
	at org.junit.rules.RunRules.evaluate(RunRules.java:18)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at junit.framework.JUnit4TestAdapter.run(JUnit4TestAdapter.java:39)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.run(JUnitTestRunner.java:520)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.launch(JUnitTestRunner.java:1060)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.main(JUnitTestRunner.java:911)
[05/03/2021 12:06:08:364 PDT] 001 FATRunner                      evaluate                       I exiting com.ibm.ws.wssecurity.fat.cxf.usernametoken.CxfSSLUNTNonceTests.testCxfUntNonceOnlySSL

```

**Comment by arunavemulapalli** [comment]
I haven't merged this fix yet.

**Comment by arunavemulapalli** [comment]
done.
