### ISSUE TITLE
While processing X509Async client response, ws-security callbackhandler class failed to load - ClassNotFound exception

### ISSUE THREAD

**Issue by meiaus** [OpenLiberty/open-liberty#16071]
Running OL FAT test suite `com.ibm.ws.wssecurity.fat.cxf.x509token.CxfX509ASyncTests` with new EE8 feature runtime (jaxws-2.3, com.ibm.ws.org.apache.cxf.cxf.core.3.2, etc.) failed with
```
[2/26/21 17:27:20:351 CST] 0000006a com.ibm.ws.logging.internal.impl.IncidentImpl                I FFDC1015I: An FFDC Incident has been created: "java.lang.ClassNotFoundException: com.ibm.ws.wssecurity.example.cbhwss4j.CommonPasswordCallbackWss4j cannot be found by com.ibm.ws.org.apache.cxf.rt.security.3.3.6_1.0.48.202101281834 org.apache.cxf.ws.security.wss4j.WSS4JInInterceptor 644" at ffdc_21.02.26_17.27.20.0.log
[2/26/21 17:27:20:476 CST] 0000006a com.ibm.ws.logging.internal.impl.IncidentImpl                I FFDC1015I: An FFDC Incident has been created: "org.apache.wss4j.common.ext.WSSecurityException: com.ibm.ws.wssecurity.example.cbhwss4j.CommonPasswordCallbackWss4j cannot be found by com.ibm.ws.org.apache.cxf.rt.security.3.3.6_1.0.48.202101281834
Original Exception was java.lang.ClassNotFoundException: com.ibm.ws.wssecurity.example.cbhwss4j.CommonPasswordCallbackWss4j cannot be found by com.ibm.ws.org.apache.cxf.rt.security.3.3.6_1.0.48.202101281834 org.apache.cxf.ws.security.wss4j.WSS4JInInterceptor 381" at ffdc_21.02.26_17.27.20.1.log
[2/26/21 17:27:20:490 CST] 0000006a .ws.org.apache.cxf.cxf.core.3.2:1.0.48.202101111530(id=159)] W Interceptor for {http://x509async.wssecfvt.test}X509AsyncService#{http://x509async.wssecfvt.test}invoke has thrown exception, unwinding now
org.apache.cxf.binding.soap.SoapFault: com.ibm.ws.wssecurity.example.cbhwss4j.CommonPasswordCallbackWss4j cannot be found by com.ibm.ws.org.apache.cxf.rt.security.3.3.6_1.0.48.202101281834
	at org.apache.cxf.ws.security.wss4j.WSS4JUtils.createSoapFault(WSS4JUtils.java:240)
	at org.apache.cxf.ws.security.wss4j.WSS4JInInterceptor.handleMessageInternal(WSS4JInInterceptor.java:382)
	at org.apache.cxf.ws.security.wss4j.WSS4JInInterceptor.handleMessage(WSS4JInInterceptor.java:213)
	at org.apache.cxf.ws.security.wss4j.PolicyBasedWSS4JInInterceptor.handleMessage(PolicyBasedWSS4JInInterceptor.java:123)
	at org.apache.cxf.ws.security.wss4j.PolicyBasedWSS4JInInterceptor.handleMessage(PolicyBasedWSS4JInInterceptor.java:76)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.endpoint.ClientImpl.onMessage(ClientImpl.java:810)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.handleResponseInternal(HTTPConduit.java:1750)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream$1.run(HTTPConduit.java:1235)
```

FFDC:
```
------Start of DE processing------ = [2/26/21 17:27:20:246 CST]
Exception = java.lang.ClassNotFoundException
Source = org.apache.cxf.ws.security.wss4j.WSS4JInInterceptor
probeid = 644
Stack Dump = java.lang.ClassNotFoundException: com.ibm.ws.wssecurity.example.cbhwss4j.CommonPasswordCallbackWss4j cannot be found by com.ibm.ws.org.apache.cxf.rt.security.3.3.6_1.0.48.202101281834
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:516)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:171)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:871)
	at org.apache.cxf.common.classloader.ClassLoaderUtils.loadClass2(ClassLoaderUtils.java:319)
	at org.apache.cxf.common.classloader.ClassLoaderUtils.loadClass(ClassLoaderUtils.java:279)
	at org.apache.cxf.rt.security.utils.SecurityUtils.getCallbackHandler(SecurityUtils.java:58)
	at org.apache.cxf.ws.security.wss4j.WSS4JInInterceptor.getCallback(WSS4JInInterceptor.java:643)
	at org.apache.cxf.ws.security.wss4j.WSS4JInInterceptor.getCallback(WSS4JInInterceptor.java:631)
	at org.apache.cxf.ws.security.wss4j.WSS4JInInterceptor.handleMessageInternal(WSS4JInInterceptor.java:271)
	at org.apache.cxf.ws.security.wss4j.WSS4JInInterceptor.handleMessage(WSS4JInInterceptor.java:213)
	at org.apache.cxf.ws.security.wss4j.PolicyBasedWSS4JInInterceptor.handleMessage(PolicyBasedWSS4JInInterceptor.java:123)
	at org.apache.cxf.ws.security.wss4j.PolicyBasedWSS4JInInterceptor.handleMessage(PolicyBasedWSS4JInInterceptor.java:76)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.endpoint.ClientImpl.onMessage(ClientImpl.java:810)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.handleResponseInternal(HTTPConduit.java:1750)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream$1.run(HTTPConduit.java:1235)
	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:239)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:818)
```

```
product = Open Liberty 21.0.0.1 (wlp-1.0.48.202101111530)
wlp.install.dir = C:/Users/Mei-HsiangChang/libertyGit/open-liberty/dev/build.image/wlp/
java.home = C:\java8\ibm-java-sdk-80-win-x86_64_8.0.5.41\sdk\jre
java.version = 1.8.0_221
```

The trace log zip in the box: https://ibm.ent.box.com/file/781037460888 (requiring access permission to the box folder)

**Comment by meiaus** [comment]
@arunavemulapalli @neuwerk @BerksanAtes @sawadood

**Comment by arunavemulapalli** [comment]
This is resolved. closing.
