### ISSUE TITLE
Cannot write unit test on class using liberty api

### ISSUE THREAD

**Issue by sdehors-ibm** [OpenLiberty/open-liberty#16070]
Hello,

I'm accessing the com.ibm.websphere.ssl.JSSEHelper in the application code to get the sslcontext defined in liberty. To be able to reference it in the application I added the maven dependency:
```
<dependency>
            <groupId>com.ibm.websphere.appserver.api</groupId>
            <artifactId>com.ibm.websphere.appserver.api.ssl</artifactId>
            <scope>provided</scope>
</dependency>
```
works well at runtime but when executing a junit test of the class, the jvm complains that it cannot find the class com.ibm.ws.logging.internal.TraceSpecification. 

It seems this class is not available in the maven packages published on central? is there another way to include it so that tests can be executed outside liberty, otherwise it seems there is a problem if application developers cannot write unit tests against code that uses those classes.

**Comment by ratiaris** [comment]
Hi,

I have a very similar issue when mocking the `com.ibm.websphere.security.openidconnect.PropagationHelper.getIdToken()` with _mockito_.

In our POM we have the following dependencies:
```
        <dependency>
            <groupId>io.openliberty.features</groupId>
            <artifactId>openidConnectClient-1.0</artifactId>
            <type>esa</type>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.ibm.websphere.appserver.spi</groupId>
            <artifactId>com.ibm.websphere.appserver.spi.logging</artifactId>
            <version>1.1.9</version>
            <scope>test</scope>
        </dependency>
```

The mock initialization fails as follows: 
```
java.lang.NoClassDefFoundError: com.ibm.websphere.security.openidconnect.PropagationHelper (initialization failure)
        at java.base/java.lang.J9VMInternals.initializationAlreadyFailed(J9VMInternals.java:172)
        at com.ibm.decision.runtime.webapp.ArchivesStorageResourceTest.test_51_JwtToken(ArchivesStorageResourceTest.java:202)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
        at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
        at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:364)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:272)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:237)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:158)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
        at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
Caused by: java.lang.NoClassDefFoundError: com.ibm.ws.logging.internal.TraceSpecification
        at com.ibm.websphere.ras.Tr.<clinit>(Tr.java:125)
        at com.ibm.websphere.security.openidconnect.PropagationHelper.<clinit>(PropagationHelper.java:65535)
        at java.base/java.lang.Class.forNameImpl(Native Method)
        at java.base/java.lang.Class.forName(Class.java:417)
        at org.mockito.internal.creation.bytebuddy.InlineBytecodeGenerator.assureInitialization(InlineBytecodeGenerator.java:236)
        at org.mockito.internal.creation.bytebuddy.InlineBytecodeGenerator.triggerRetransformation(InlineBytecodeGenerator.java:254)
        at org.mockito.internal.creation.bytebuddy.InlineBytecodeGenerator.mockClassStatic(InlineBytecodeGenerator.java:226)
        at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator.mockClassStatic(TypeCachingBytecodeGenerator.java:63)
        at org.mockito.internal.creation.bytebuddy.InlineDelegateByteBuddyMockMaker.createStaticMock(InlineDelegateByteBuddyMockMaker.java:566)
        at org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMaker.createStaticMock(InlineByteBuddyMockMaker.java:83)
        at org.mockito.internal.util.MockUtil.createStaticMock(MockUtil.java:202)
        at org.mockito.internal.MockitoCore.mockStatic(MockitoCore.java:134)
        at org.mockito.Mockito.mockStatic(Mockito.java:2307)
        at org.mockito.Mockito.mockStatic(Mockito.java:2244)
        at com.ibm.decision.runtime.webapp.ArchivesStorageResourceTest.test_51_JwtToken(ArchivesStorageResourceTest.java:200)
        ... 35 more
Caused by: java.lang.ClassNotFoundException: com.ibm.ws.logging.internal.TraceSpecification
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:766)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1074)
        ... 50 more

**Comment by una-tapa** [comment]
Hi, @sdehors-ibm 

First off, my apologies we did not get to this issue sooner! [Florian](https://github.ibm.com/Florian-Signoret) pointed me to this issue while he reported other issue related to his project. 

I have a quick question. Is the failing unit test running on the server or outside of it? If it's running outside, I'm wondering if it makes sense to call the server API using plain Java. I'm concerned about potential issues with class loading since the API might not have access to internal server classes, as reported. If the failing test case is running on the server, I'm thinking about reaching out to our classloader experts for help. Please share your insights. Thanks!

**Comment by sdehors-ibm** [comment]
Hi, the test is run with junit in maven and pulling the dependency from maven. The capability to write unit tests without starting the whole server is a must. It should be possible to mock the JSSEHelper, but because the class as dependencies that cannot be found, the mocking fails. If we put mocking appart, at least it should be possible to invoke JSSEHelper.getInstance() and have it return null. 

If the dependency is available on maven central to be included as "provided" scope in the application code, then maven should be able to get all the classes needed to run that code.

**Comment by una-tapa** [comment]
[An internal discussion](https://ibm-cloud.slack.com/archives/C31DW78RG/p1695675493167039) in progress.
