### ISSUE TITLE
Rest Client reports a problem when using a special custom config source

### ISSUE THREAD

**Issue by Emily-Jiang** [OpenLiberty/open-liberty#16081]
**Describe the bug**
I have the following custom config source created. The following error stopped Liberty from starting.
```
[INFO] [ERROR   ] CWWKZ0004E: An exception occurred while starting the application liberty. The exception message was: com.ibm.ws.container.service.state.StateChangeException: org.jboss.weld.exceptions.DefinitionException: Exception List with 1 exceptions:
[INFO] Exception 0 :
[INFO] java.lang.IllegalArgumentException: The scope Alice is invalid
[INFO] 	at org.apache.cxf.microprofile.client.cdi.RestClientBean.readScope(RestClientBean.java:207)
[INFO] 	at org.apache.cxf.microprofile.client.cdi.RestClientBean.<init>(RestClientBean.java:93)
[INFO] 	at com.ibm.ws.microprofile.rest.client.cdi.LibertyRestClientExtension.lambda$registerClientBeans$1(LibertyRestClientExtension.java:97)
[INFO] 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
[INFO] 	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
[INFO] 	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
[INFO] 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
[INFO] 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
[INFO] 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[INFO] 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[INFO] 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[INFO] 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
[INFO] 	at com.ibm.ws.microprofile.rest.client.cdi.LibertyRestClientExtension.registerClientBeans(LibertyRestClientExtension.java:97)
[INFO] 	at jdk.internal.reflect.GeneratedMethodAccessor781.invoke(Unknown Source)
[INFO] 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
[INFO] 	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:95)
[INFO] 	at org.jboss.weld.injection.MethodInvocationStrategy$SpecialParamPlusBeanManagerStrategy.invoke(MethodInvocationStrategy.java:187)
[INFO] 	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:330)
[INFO] 	at org.jboss.weld.event.ExtensionObserverMethodImpl.sendEvent(ExtensionObserverMethodImpl.java:123)
[INFO] 	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:308)
[INFO] 	at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:286)
[INFO] 	at javax.enterprise.inject.spi.ObserverMethod.notify(ObserverMethod.java:124)
[INFO] 	at org.jboss.weld.util.Observers.notify(Observers.java:166)
[INFO] 	at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:285)
[INFO] 	at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:273)
[INFO] 	at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:177)
[INFO] 	at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:171)
[INFO] 	at org.jboss.weld.bootstrap.events.AbstractContainerEvent.fire(AbstractContainerEvent.java:53)
[INFO] 	at org.jboss.weld.bootstrap.events.AbstractDefinitionContainerEvent.fire(AbstractDefinitionContainerEvent.java:44)
[INFO] 	at org.jboss.weld.bootstrap.events.AfterBeanDiscoveryImpl.fire(AfterBeanDiscoveryImpl.java:75)
[INFO] 	at org.jboss.weld.bootstrap.WeldStartup.deployBeans(WeldStartup.java:462)
[INFO] 	at org.jboss.weld.bootstrap.WeldBootstrap.deployBeans(WeldBootstrap.java:86)
[INFO] 	at com.ibm.ws.cdi.impl.CDIContainerImpl.startInitialization(CDIContainerImpl.java:160)
[INFO] 	at com.ibm.ws.cdi.liberty.CDIRuntimeImpl.applicationStarting(CDIRuntimeImpl.java:479)
[INFO] 	at com.ibm.ws.container.service.state.internal.ApplicationStateManager.fireStarting(ApplicationStateManager.java:51)
[INFO] 	at com.ibm.ws.container.service.state.internal.StateChangeServiceImpl.fireApplicationStarting(StateChangeServiceImpl.java:50)
[INFO] 	at com.ibm.ws.app.manager.module.internal.SimpleDeployedAppInfoBase.preDeployApp(SimpleDeployedAppInfoBase.java:547)
[INFO] 	at com.ibm.ws.app.manager.module.internal.SimpleDeployedAppInfoBase.installApp(SimpleDeployedAppInfoBase.java:508)
[INFO] 	at com.ibm.ws.app.manager.module.internal.DeployedAppInfoBase.deployApp(DeployedAppInfoBase.java:349)
[INFO] 	at com.ibm.ws.app.manager.war.internal.WARApplicationHandlerImpl.install(WARApplicationHandlerImpl.java:65)
[INFO] 	at com.ibm.ws.app.manager.internal.statemachine.StartAction.execute(StartAction.java:149)
[INFO] 	at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.enterState(ApplicationStateMachineImpl.java:1352)
[INFO] 	at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.performAction(ApplicationStateMachineImpl.java:1229)
[INFO] 	at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.run(ApplicationStateMachineImpl.java:905)
[INFO] 	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:239)
[INFO] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[INFO] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[INFO] 	at java.base/java.lang.Thread.run(Thread.java:832)
[INFO] Caused by: java.lang.ClassNotFoundException: Alice cannot be found by com.ibm.ws.org.apache.cxf.cxf.rt.rs.mp.client.3.3_1.0.49.cl210220210209-1100
[INFO] 	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:516)
[INFO] 	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:171)
[INFO] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
[INFO] 	at org.apache.cxf.common.classloader.ClassLoaderUtils.loadClass2(ClassLoaderUtils.java:319)
[INFO] 	at org.apache.cxf.common.classloader.ClassLoaderUtils.loadClass(ClassLoaderUtils.java:293)
[INFO] 	at org.apache.cxf.microprofile.client.cdi.RestClientBean.readScope(RestClientBean.java:205)
[INFO] 	... 47 more
[INFO] 


```
```

public class CustomConfigSource implements ConfigSource {

    @Override
    public Set<String> getPropertyNames() {
        
        return Collections.singleton("customer.name");
    }

    @Override
    public Map<String, String> getProperties() {
        Map<String, String> props = new HashMap<>();
        getPropertyNames().forEach((prop) -> props.put(prop, getValue(prop)));
        return props;
    }

    @Override
    public String getValue(String propertyName) {
        
        return "Alice";
    }

    @Override
    public String getName() {
        
        return "CustomConfigSource";
    }

    @Override
    public int getOrdinal() {
        return 120;
    }
    
}


```

Here is my personal github [repo](https://github.com/Emily-Jiang/test-mp4) to replicate this issue

**Comment by Emily-Jiang** [comment]
@andymc12 commented the following:
here is the code that handles our interaction with MP Config:
https://github.com/apache/cxf/blob/master/rt/rs/microprofile-client/src/main/java/org/apache/cxf/microprofile/client/config/ConfigFacade.java
rt/rs/microprofile-client/src/main/java/org/apache/cxf/microprofile/client/config/ConfigFacade.java

hmmm. I think this could only happen for a single property config source
could the MP Config impl handle this?  for example, if somebody (in this case, MP Rest Client) calls Config.getValue(...) or Config.getOptionalValue(...) could the config impl intercept the call to the ConfigSource and not even call getValue(propertyName)  if propertyName is not in the set returned from getPropertyNames() ?

**Comment by Azquelt** [comment]
This behaves as I'd expect. The `ConfigSource` interface requires that a `getValue()` returns `null` if the requested property is not present in the config source.

In addition, intuitively, when you call `config.getValue()` I'd expect it to call `getValue()` on each `ConfigSource` in turn (sorted by ordinal) until it finds a value or reaches the end of the list. That would seem the quickest and simplest way to get the value.

I also note that the doc for `getPropertyNames()` says this
> Gets all property names known to this configuration source, potentially without evaluating the values. **The property names may be a subset of the names of the total set of retrievable properties in this config source.**

That means we can't rely on the result of `getPropertyNames()` to determine which properties are available to be looked up in this config source.
