### ISSUE TITLE
Test Failure: com.ibm.ws.logging.fat.InvalidTraceSpecificationTest.testValidTraceSpec

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#16173]
RTC 282254

```
testValidTraceSpec:java.lang.Exception: 2021-01-09-12:56:16:475 Errors/warnings were found in server com.ibm.ws.logging.tracespec logs:
<br>[1/9/21, 12:53:11:474 PST] 00000020 com.ibm.ws.config.xml.internal.ConfigRefresher               W CWWKG0027W: Timeout while updating server configuration.
at componenttest.topology.impl.LibertyServer.checkLogsForErrorsAndWarnings(LibertyServer.java:2555)
at componenttest.topology.impl.LibertyServer.stopServer(LibertyServer.java:2420)
at componenttest.topology.impl.LibertyServer.stopServer(LibertyServer.java:2235)
at componenttest.topology.impl.LibertyServer.stopServer(LibertyServer.java:2210)
at com.ibm.ws.logging.fat.InvalidTraceSpecificationTest.tearDown(InvalidTraceSpecificationTest.java:162)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:197)
at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:318)
at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:171)

```

**Comment by fmhwong** [comment]
This seems to be a JDK 11 problem.

**Comment by fmhwong** [comment]
```
********************************************************************************
product = WebSphere Application Server 21.0.0.3 (wlp-1.0.50.cl210320210305-0300)
wlp.install.dir = /home/jazz_build/Build/jbe/build/dev/image/output/wlp/
java.home = /home/jazz_build/Build/jbe/jvms/OpenJDK11U-jdk_s390x_linux_hotspot_11.0.5_10
java.version = 11.0.5
java.runtime = OpenJDK Runtime Environment (11.0.5+10)
os = Linux (4.18.0-147.el8.s390x; s390x) (en_US)
process = 11308@ebcprs0788lznerjf-n.fyre.ibm.com
********************************************************************************
[3/7/21, 22:16:54:930 EST] 00000001 com.ibm.ws.logging.internal.TraceSpecification               I TRAS0018I: The trace state has been changed. The new trace state is *=info:com.ibm.ws.runtime.update.*=all:logservice=detail.
[3/7/21, 22:16:54:961 EST] 00000001 com.ibm.ws.kernel.launch.internal.FrameworkManager           A CWWKE0001I: The server com.ibm.ws.logging.tracespec has been launched.
[3/7/21, 22:16:55:785 EST] 00000015 LogService-12-com.ibm.ws.org.apache.felix.scr                I CWWKE0703I: bundle com.ibm.ws.org.apache.felix.scr:1.0.50.cl210320210305-0300 (12) Starting with globalExtender setting: true   
[3/7/21, 22:16:55:791 EST] 00000015 LogService-12-com.ibm.ws.org.apache.felix.scr                I CWWKE0703I: bundle com.ibm.ws.org.apache.felix.scr:1.0.50.cl210320210305-0300 (12)  Version = 1.0.50.cl210320210305-0300   
[3/7/21, 22:16:55:884 EST] 00000014 com.ibm.ws.config.xml.internal.XMLConfigParser               A CWWKG0028A: Processing included configuration resource: /home/jazz_build/Build/jbe/build/dev/image/output/wlp/usr/servers/fatTestPorts.xml
[3/7/21, 22:16:55:896 EST] 00000014 com.ibm.ws.config.xml.internal.XMLConfigParser               A CWWKG0028A: Processing included configuration resource: /home/jazz_build/Build/jbe/build/dev/image/output/wlp/usr/servers/fatTestCommon.xml
[3/7/21, 22:16:56:034 EST] 0000001a com.ibm.ws.logging.internal.TraceSpecification               I TRAS0018I: The trace state has been changed. The new trace state is *=info:com.ibm.someInvalid.*=all.
[3/7/21, 22:16:56:257 EST] 00000001 com.ibm.ws.kernel.launch.internal.FrameworkManager           I CWWKE0002I: The kernel started after 1.509 seconds
[3/7/21, 22:16:56:401 EST] 0000001e com.ibm.ws.kernel.feature.internal.FeatureManager            I CWWKF0007I: Feature update started.
[3/7/21, 22:16:57:382 EST] 00000015 com.ibm.ws.app.manager.internal.monitor.DropinMonitor        A CWWKZ0058I: Monitoring dropins for applications.
[3/7/21, 22:16:57:655 EST] 00000013 com.ibm.ws.timedexit.internal.TimedExitComponent             A TE9900A: Timed Exit Enabled
[3/7/21, 22:16:57:678 EST] 0000001e com.ibm.ws.tcpchannel.internal.TCPPort                       I CWWKO0219I: TCP Channel defaultHttpEndpoint has been started and is now listening for requests on host *  (IPv6) port 8010.
[3/7/21, 22:16:57:733 EST] 0000001e com.ibm.ws.kernel.feature.internal.FeatureManager            A CWWKF0012I: The server installed the following features: [jsp-2.2, servlet-3.0, timedexit-1.0].
[3/7/21, 22:16:57:734 EST] 0000001e com.ibm.ws.kernel.feature.internal.FeatureManager            I CWWKF0008I: Feature update completed in 1.518 seconds.
[3/7/21, 22:16:57:734 EST] 0000001e com.ibm.ws.kernel.feature.internal.FeatureManager            A CWWKF0011I: The com.ibm.ws.logging.tracespec server is ready to run a smarter planet. The com.ibm.ws.logging.tracespec server started in 2.987 seconds.
[3/7/21, 22:16:58:410 EST] 00000020 com.ibm.ws.config.xml.internal.ConfigRefresher               A CWWKG0016I: Starting server configuration update.
[3/7/21, 22:16:58:412 EST] 00000020 com.ibm.ws.config.xml.internal.XMLConfigParser               A CWWKG0028A: Processing included configuration resource: /home/jazz_build/Build/jbe/build/dev/image/output/wlp/usr/servers/fatTestPorts.xml
[3/7/21, 22:16:58:412 EST] 00000020 com.ibm.ws.config.xml.internal.XMLConfigParser               A CWWKG0028A: Processing included configuration resource: /home/jazz_build/Build/jbe/build/dev/image/output/wlp/usr/servers/fatTestCommon.xml
[3/7/21, 22:17:59:568 EST] 00000020 com.ibm.ws.config.xml.internal.ConfigRefresher               W CWWKG0027W: Timeout while updating server configuration.
[3/7/21, 22:18:08:971 EST] 0000001a com.ibm.ws.logging.internal.TraceSpecification               I TRAS0018I: The trace state has been changed. The new trace state is *=info:com.ibm.someInvalid.*=all:com.ibm.ws.*=all.
[3/7/21, 22:18:08:971 EST] 0000001a com.ibm.ws.logging.internal.TraceSpecification               I TRAS0040I: The configured trace state included the following specifications that do not match any loggers currently registered in the server: com.ibm.someInvalid.*=all Ignore this message if the trace specifications com.ibm.someInvalid.*=all are valid.
[3/7/21, 22:20:59:252 EST] 00000010 com.ibm.ws.kernel.launch.internal.ServerCommandListener      A CWWKE0055I: Server shutdown requested on Sunday, March 7, 2021 at 10:20 PM. The server com.ibm.ws.logging.tracespec is shutting down.
[3/7/21, 22:20:59:435 EST] 0000002e com.ibm.ws.runtime.update.internal.RuntimeUpdateManagerImpl  A CWWKE1100I: Waiting for up to 30 seconds for the server to quiesce.
[3/7/21, 22:21:00:266 EST] 00000029 com.ibm.ws.tcpchannel.internal.TCPChannel                    I CWWKO0220I: TCP Channel defaultHttpEndpoint has stopped listening for requests on host *  (IPv6) port 8010.
[3/7/21, 22:21:01:928 EST] 0000002e com.ibm.ws.runtime.update.internal.RuntimeUpdateManagerImpl  I CWWKE1101I: Server quiesce complete.
[3/7/21, 22:21:02:860 EST] 00000001 com.ibm.ws.kernel.launch.internal.FrameworkManager           A CWWKE0036I: The server com.ibm.ws.logging.tracespec stopped after 4 minutes, 8.112 seconds.

```
