### ISSUE TITLE
BundleException: Cannot connect region 'system.bundle' to itself

### ISSUE THREAD

**Issue by tjwatson** [OpenLiberty/open-liberty#1617]
The following exception can be observed as an FFDC and the feature manager fails to provision features correctly.  This happens if the timestamp changes on one of the kernel bundles and in particular the com.ibm.ws.kernel.feature bundle between restarts and the server is updated to add or remove a feature from the feature list.  The issue is the com.ibm.ws.kernel.feature bundle gets discarded by the Equinox framework if the timestamp of the jar changes from the last time liberty was launched.  This causes the kernel boot strap to re-install the com.ibm.ws.kernel.feature bundle.

The issue is this is done using the system.bundle context and the bundles get assigned to the same region as the system.bundle.  Normally in a boot strapping scenario this is not an issue because there we would have started from a fresh framework with no bundles (or regions) created yet.  But in this case the feature manager will have already created all the regions according to the product extensions installed.  Part of that includes moving the system.bundle into its own region.  So when com.ibm.ws.kernel.feature is reinstalled by the kernel it gets moved into the system.bundle region.

The constructor com.ibm.ws.kernel.feature.internal.Provisioner.Provisioner(FeatureManager, Set<String>) makes the assumption that the com.ibm.ws.kernel.feature is always in the `kernelRegion` not the `system.bundle` region.  If the com.ibm.ws.kernel.feature bundle is in the `system.bundle` region we run into this error.  The root cause of this issue is that we do not properly recover the region setting for when a kernel bundle is discarded because of a timestamp change on disk to the kernel bundle jar.  We should add a check somewhere to ensure that the only bundle in the `system.bundle` region is the actual `system.bundle`.  All other bundles should be moved to the kernel region.

```
org.osgi.framework.BundleException: Cannot connect region 'system.bundle' to itself
        at org.eclipse.equinox.internal.region.StandardRegionDigraph.createConnection(StandardRegionDigraph.java:151)
        at org.eclipse.equinox.internal.region.StandardRegionDigraph.connect(StandardRegionDigraph.java:133)
        at org.eclipse.equinox.internal.region.BundleIdBasedRegion.connectRegion(BundleIdBasedRegion.java:176)
        at com.ibm.ws.kernel.feature.internal.Provisioner.connectToProductHub(Provisioner.java:903)
        at com.ibm.ws.kernel.feature.internal.Provisioner.createProductRegion(Provisioner.java:717)
        at com.ibm.ws.kernel.feature.internal.Provisioner.access$700(Provisioner.java:89)
        at com.ibm.ws.kernel.feature.internal.Provisioner$3.call(Provisioner.java:664)
        at com.ibm.ws.kernel.feature.internal.Provisioner$3.call(Provisioner.java:629)
        at com.ibm.ws.kernel.feature.ApiRegion.update(ApiRegion.java:163)
        at com.ibm.ws.kernel.feature.internal.Provisioner.createAndUpdateProductRegions(Provisioner.java:629)
        at com.ibm.ws.kernel.feature.internal.FeatureManager.updateFeatures(FeatureManager.java:1180)
        at com.ibm.ws.kernel.feature.internal.FeatureManager.update(FeatureManager.java:690)
        at com.ibm.ws.kernel.feature.internal.FeatureManager.processFeatureChanges(FeatureManager.java:793)
        at com.ibm.ws.kernel.feature.internal.FeatureManager$1.run(FeatureManager.java:588)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by anjumfatima90** [comment]
#build

**Comment by tjwatson** [comment]
This has been fixed for a while
