### ISSUE TITLE
Upgrade version of Shibboleth used in SAML testing

### ISSUE THREAD

**Issue by c00crane** [OpenLiberty/open-liberty#16198]
We will need to upgrade the version of Shibboleth that we're using to test with - I believe that the current version is 3.3.1.  I'll look into upgrading to 4.1 if possible.  If it is not, it'll have to be above 3.4.6 or above.

The idp.war fails to start with Java 16.  We see warnings in prior versions, but, with 16, we now see failures.  We can work around it for now, but, we will need to fix the issues before we try to run on even newer versions.

The errors are:
[3/6/21, 16:42:34:087 PST] 0000002b com.ibm.ws.logging.internal.impl.IncidentImpl                I FFDC1015I: An FFDC Incident has been created: "org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'shibboleth.ParserPool' defined in file [/home/jazz_build/Build/jbe/build/dev/com.ibm.ws.security.saml.sso_fat/autoFVT/shibboleth-idp/system/conf/global-system.xml]: Cannot create inner bean '%{idp.xml.securityManager:%{jdkBuilderAttribute}}#7535e5db' of type [com.sun.org.apache.xerces.internal.util.SecurityManager] while setting bean property 'builderAttributes' with key [TypedStringValue: value [http://apache.org/xml/properties/security-manager], target type [null]]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '%{idp.xml.securityManager:%{jdkBuilderAttribute}}#7535e5db' defined in file [/home/jazz_build/Build/jbe/build/dev/com.ibm.ws.security.saml.sso_fat/autoFVT/shibboleth-idp/system/conf/global-system.xml]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.sun.org.apache.xerces.internal.util.SecurityManager]: Is the constructor accessible?; nested exception is java.lang.IllegalAccessException: class org.springframework.beans.BeanUtils cannot access class com.sun.org.apache.xerces.internal.util.SecurityManager (in module java.xml) because module java.xml does not export com.sun.org.apache.xerces.internal.util to unnamed module @f49ec68f com.ibm.ws.webcontainer.webapp.WebApp.notifyServletContextCreated 1341" at ffdc_21.03.06_16.42.33.0.log
[3/6/21, 16:42:34:090 PST] 0000002b com.ibm.ws.webcontainer.webapp                               E SRVE0283E: Exception caught while initializing context: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'shibboleth.ParserPool' defined in file [/home/jazz_build/Build/jbe/build/dev/com.ibm.ws.security.saml.sso_fat/autoFVT/shibboleth-idp/system/conf/global-system.xml]: Cannot create inner bean '%{idp.xml.securityManager:%{jdkBuilderAttribute}}#7535e5db' of type [com.sun.org.apache.xerces.internal.util.SecurityManager] while setting bean property 'builderAttributes' with key [TypedStringValue: value [http://apache.org/xml/properties/security-manager], target type [null]]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '%{idp.xml.securityManager:%{jdkBuilderAttribute}}#7535e5db' defined in file [/home/jazz_build/Build/jbe/build/dev/com.ibm.ws.security.saml.sso_fat/autoFVT/shibboleth-idp/system/conf/global-system.xml]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.sun.org.apache.xerces.internal.util.SecurityManager]: Is the constructor accessible?; nested exception is java.lang.IllegalAccessException: class org.springframework.beans.BeanUtils cannot access class com.sun.org.apache.xerces.internal.util.SecurityManager (in module java.xml) because module java.xml does not export com.sun.org.apache.xerces.internal.util to unnamed module @f49ec68f
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveInnerBean(BeanDefinitionValueResolver.java:313)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:122)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveManagedMap(BeanDefinitionValueResolver.java:407)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:165)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1481)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1226)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:296)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:296)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:776)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:861)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:444)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:326)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107)
	at com.ibm.ws.webcontainer.webapp.WebApp.notifyServletContextCreated(WebApp.java:2437)
	at com.ibm.ws.webcontainer31.osgi.webapp.WebApp31.notifyServletContextCreated(WebApp31.java:514)
	at com.ibm.ws.webcontainer.webapp.WebApp.initialize(WebApp.java:1041)
	at com.ibm.ws.webcontainer.webapp.WebApp.initialize(WebApp.java:6683)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost.startWebApp(DynamicVirtualHost.java:470)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost.startWebApplication(DynamicVirtualHost.java:465)
	at com.ibm.ws.webcontainer.osgi.WebContainer.startWebApplication(WebContainer.java:1179)
	at com.ibm.ws.webcontainer.osgi.WebContainer.access$100(WebContainer.java:110)
	at com.ibm.ws.webcontainer.osgi.WebContainer$3.run(WebContainer.java:976)
	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:238)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:853)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name '%{idp.xml.securityManager:%{jdkBuilderAttribute}}#7535e5db' defined in file [/home/jazz_build/Build/jbe/build/dev/com.ibm.ws.security.saml.sso_fat/autoFVT/shibboleth-idp/system/conf/global-system.xml]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.sun.org.apache.xerces.internal.util.SecurityManager]: Is the constructor accessible?; nested exception is java.lang.IllegalAccessException: class org.springframework.beans.BeanUtils cannot access class com.sun.org.apache.xerces.internal.util.SecurityManager (in module java.xml) because module java.xml does not export com.sun.org.apache.xerces.internal.util to unnamed module @f49ec68f
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1105)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1050)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveInnerBean(BeanDefinitionValueResolver.java:299)
	... 36 more
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.sun.org.apache.xerces.internal.util.SecurityManager]: Is the constructor accessible?; nested exception is java.lang.IllegalAccessException: class org.springframework.beans.BeanUtils cannot access class com.sun.org.apache.xerces.internal.util.SecurityManager (in module java.xml) because module java.xml does not export com.sun.org.apache.xerces.internal.util to unnamed module @f49ec68f
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:148)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:89)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1098)
	... 40 more
Caused by: java.lang.IllegalAccessException: class org.springframework.beans.BeanUtils cannot access class com.sun.org.apache.xerces.internal.util.SecurityManager (in module java.xml) because module java.xml does not export com.sun.org.apache.xerces.internal.util to unnamed module @f49ec68f
	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:385)
	at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:687)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:489)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:142)
	... 42 more

**Comment by c00crane** [comment]
Comment in progress - not done till this line is removed...
Update/Upgrade Shibboleth version:

1. Make a copy of the latest release version under open-liberty/dev/com.ibm.ws.security.saml.sso_fat.common/shibboleth-idp (today, we have 3.3.1, 4.0.1 & 4.1.0, so now we'd make a copy of 4.1.0).  Name the copy with the release name you're upgrading to.
2. Search for files that end in ".orig" in the newly copied tree.  Rename them - removing the ".orig" (make sure to keep track of the files that you rename, you'll need to rename them back when you're done) (When Shibboleth was first incorporated into the testing with SAML, we realized that some of the files needed test machine unique values and they weren't picking up variables properly.  The files that were renamed to end in ".orig" contain "xxx<*>xxx" strings will be updated by the test runtime.  Copies of the files will be created without the ".orig" ending - those copies will have test machine specific information inserted in place of the "xxx<*>xxx" values.)
2. Download the version of Shibboleth that you're upgrading too.  That should available from a directory under: [https://shibboleth.net/downloads/identity-provider/](url) (grab the zip or tar.gz)
3. Unzip or extract from the tar.
4. Run the <extractLocation>/bin/install.<sh|bat> script - specify the location of the newly copied directory under shibboleth-idp in the com.ibm.ws.security.saml.sso_fat.common project as your idp install location. (Doing this will make the install script perform an upgrade instead of an clean install.)
5. Go back to the newly copied tree and rename the now updated files back to having the extension of ".orig".
6. Now, we need to get the idp.war from Maven:  [https://mvnrepository.com/artifact/net.shibboleth.idp/idp-war](url).  Download the version of the war that upgrading to.
7. We need the war out in artifactory. Use the steps documented at: [https://github.ibm.com/websphere/WS-CD-Open/wiki/Artifactory-for-Liberty-Development](url) to get it uploaed into artifactory.  (note: The tool that does the upload will update the war as a jar - you'll need someone with more authority to change the type and update the pom info for a war)
8. Update open-liberty/dev/com.ibm.ws.security.saml.sso_fat.common/build.gradle (follow the example of the other Shibboleth instances).
- add an entry to configurations
- add an entry to dependencies (you'll have to run tests to figure out what needs to be included (this entry lists the jars that we need to embed in our runtime instance of the idp.war in order to make it run.  You may need to get updated jars from maven and add them to artifactory (if they're not already found in artifactory).  
- create an updateIdp_xxx_WAR task and its dependencies for the new version - also add an "assemble.dependsOn for the new task.
9. Update open-liberty/dev/com.ibm.ws.security.saml.sso_fat.common/ShibbolethCommon.gradle
- add a copy to copy the new (updated jar from the build/test-application directory to the test-apps directory of the Shibboleth Liberty Server.
10. Update **chooseIdpWarVersion** in open-liberty/dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/ShibbolethHelpers.java to decide which Shibboleth instance to use (current version usage is based on Java version at runtime)
11. Now the hard part - run all SAML FATs and figure out what may be missing or changed.  (This and step 8 may need some repeating - you won't really know what jars are missing or are the wrong version until you start the server and then try to run some tests)  I suggest trying to run on project to start (com.ibm.ws.security.saml.sso_fat).
