### ISSUE TITLE
Running CXF SAML FAT EE8 test failed with Response: Security processing failed relating to "MalformedURLException: no protocol: cxf-ehcache.xml"

### ISSUE THREAD

**Issue by meiaus** [OpenLiberty/open-liberty#16214]
Per discussion with @arunavemulapalli, opening this issue for further investigation if this will be potential runtime problem.
For now to progress the FAT update with new runtime testing, adding the cxf-ehcache_ee8.xml on securityClient xml and adding @AllowedFFDC in the test methods:

- securityClient_1_symSignEnc_wss4j.xml:
```
ws-security.cache.config.file="${server.config.dir}/cxf-ehcache_ee8.xml"
```
- cxf-ehcache_ee8.xml:
```
<config
        xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
        xmlns='http://www.ehcache.org/v3'
        xsi:schemaLocation="http://www.ehcache.org/v3 http://www.ehcache.org/schema/ehcache-core-3.8.xsd">

     <cache-template name="org.apache.cxf.ws.security.tokenstore.TokenStore">

        <key-type>java.lang.String</key-type>
        <value-type>org.apache.cxf.ws.security.tokenstore.SecurityToken</value-type>
        <expiry>
            <ttl unit="seconds">3600</ttl>
        </expiry>
        <resources>
            <heap unit="entries">10000</heap>
        </resources>
      </cache-template>
      <cache-template name="ws-security.nonce.cache.instance">
        <key-type>java.lang.String</key-type>
        <value-type>org.apache.wss4j.common.cache.EHCacheValue</value-type>
        <expiry>
            <ttl unit="seconds">60</ttl>
        </expiry>
        <resources>
            <heap unit="entries">500</heap>
            <disk unit="MB" persistent="true">10</disk>
        </resources>
      </cache-template>
</config>

```
- in test method:
```
    @AllowedFFDC(value = { "java.lang.Exception", "java.lang.ClassNotFoundException", "java.net.MalformedURLException" })
    @Test
    public void testSAMLCXFSignedSupportingTokens_Symmmetric() throws Exception {
...
```
Taking the test suite com.ibm.ws.wssecurity.fat.cxf.samltoken.OneServerTests.CxfSAMLSymSignEnc1ServerTests as an example for the associated logs:

- output.txt
```
03/10/2021 17:01:46:129 CST] 001 CommonTest                     failed                         I testSAMLCXFSignedSupportingTokens_Symmmetric_EE8_FEATURES: Test failed
...
[03/10/2021 17:01:46:129 CST] 001 FATRunner                      evaluate                       S null
java.lang.AssertionError: response: Did not get to the Service Cleint
 Was expecting [This is WSSECFVT CXF Symmetric Signature Web Service (using SAML)] but received: <html><head><title>CXF SAML Service Cleint</title></head><body><p>Request: SAML CXF Service Client</p><p>Response: Security processing failed.</p></body></html>.
	at org.junit.Assert.fail(Assert.java:93)
	at org.junit.Assert.assertTrue(Assert.java:43)
	at com.ibm.ws.security.fat.common.CommonMessageTools.assertAndLog(CommonMessageTools.java:81)
	at com.ibm.ws.security.fat.common.CommonMessageTools.assertTrueAndLog(CommonMessageTools.java:61)
	at com.ibm.ws.security.saml20.fat.commonTest.SAMLCommonValidationTools.validateResponseContent(SAMLCommonValidationTools.java:302)
	at com.ibm.ws.security.saml20.fat.commonTest.SAMLCommonValidationTools.validateWithResponse(SAMLCommonValidationTools.java:270)
	at com.ibm.ws.security.saml20.fat.commonTest.SAMLCommonValidationTools.validateResult(SAMLCommonValidationTools.java:127)
	at com.ibm.ws.security.saml20.fat.commonTest.SAMLCommonTestHelpers.invokeACSWithSAMLResponse(SAMLCommonTestHelpers.java:797)
	at com.ibm.ws.security.saml20.fat.commonTest.SAMLCommonTestHelpers.invokeACSWithSAMLResponse(SAMLCommonTestHelpers.java:747)
	at com.ibm.ws.security.saml20.fat.commonTest.SAMLCommonTest.genericSAML(SAMLCommonTest.java:594)
	at com.ibm.ws.security.saml20.fat.commonTest.SAMLCommonTest.genericSAML(SAMLCommonTest.java:521)
	at com.ibm.ws.wssecurity.fat.cxf.samltoken.common.CxfSAMLSymSignEncTests.testSAMLCXFSignedSupportingTokens_Symmmetric(CxfSAMLSymSignEncTests.java:88)

- messages.log
```
[3/10/21 17:01:15:430 CST] 0000005b com.ibm.ws.logging.internal.impl.IncidentImpl                I FFDC1015I: An FFDC Incident has been created: "java.net.MalformedURLException: no protocol: cxf-ehcache.xml org.apache.cxf.rt.security.utils.SecurityUtils 123" at ffdc_21.03.10_17.01.15.1.log
...
Caused by: org.apache.cxf.ws.security.tokenstore.TokenStoreException: org.ehcache.xml.exceptions.XmlConfigurationException: Error parsing XML configuration at file:/C:/Users/Mei-HsiangChang/libertyGit/open-liberty/dev/build.image/wlp/usr/servers/com.ibm.ws.wssecurity_fat.saml/cxf-ehcache.xml
...
Caused by: org.ehcache.xml.exceptions.XmlConfigurationException: Error parsing XML configuration at file:/C:/Users/Mei-HsiangChang/libertyGit/open-liberty/dev/build.image/wlp/usr/servers/com.ibm.ws.wssecurity_fat.saml/cxf-ehcache.xml
...
Caused by: org.xml.sax.SAXParseException: The prefix "xsi" for attribute "xsi:noNamespaceSchemaLocation" associated with an element type "ehcache" is not bound.

```
- ffdc
```
------Start of DE processing------ = [3/10/21 21:39:20:641 CST]
Exception = java.net.MalformedURLException
Source = org.apache.cxf.rt.security.utils.SecurityUtils
probeid = 123
Stack Dump = java.net.MalformedURLException: no protocol: cxf-ehcache.xml
```
- ffdc
```
------Start of DE processing------ = [3/10/21 21:40:14:389 CST]
Exception = java.lang.NullPointerException
Source = com.ibm.ws.container.service.metadata.internal.MetaDataManager
probeid = 149
Stack Dump = java.lang.NullPointerException
	at org.apache.cxf.ws.security.tokenstore.EHCacheTokenStore.close(EHCacheTokenStore.java:120)
	at org.apache.cxf.ws.security.tokenstore.EHCacheTokenStore.preShutdown(EHCacheTokenStore.java:130)
	at org.apache.cxf.bus.managers.CXFBusLifeCycleManager.preShutdown(CXFBusLifeCycleManager.java:97)
	at org.apache.cxf.bus.extension.ExtensionManagerBus.shutdown(ExtensionManagerBus.java:289)
	at com.ibm.ws.jaxws.metadata.JaxWsClientMetaData.destroy(JaxWsClientMetaData.java:41)
	at com.ibm.ws.jaxws.metadata.JaxWsModuleMetaData.destroy(JaxWsModuleMetaData.java:200)
	at com.ibm.ws.jaxws.support.JaxWsModuleMetaDataListener.moduleMetaDataDestroyed(JaxWsModuleMetaDataListener.java:166)
```

The autoFVT log zip in the box:  (requiring access permission to the box folder)

**Comment by meiaus** [comment]
@arunavemulapalli @neuwerk @sawadood @BerksanAtes
