### ISSUE TITLE
featureUtility throws NPE when installing cl features

### ISSUE THREAD

**Issue by jjiwooLim** [OpenLiberty/open-liberty#16285]
**Describe the bug**
Installing closed liberty feature to openliberty crashes NPE.

[18/03/21 15:24:31:689 GMT] Resolving remote features. This process might take several minutes to complete.
<====-----------------> 15.00%
java.lang.NullPointerException
	at com.ibm.ws.install.internal.ExceptionUtils.create(ExceptionUtils.java:604)
	at com.ibm.ws.install.internal.InstallKernelMap.singleFileResolve(InstallKernelMap.java:956)
	at com.ibm.ws.install.internal.InstallKernelMap.get(InstallKernelMap.java:294)
	at com.ibm.ws.install.featureUtility.FeatureUtility.installFeatures(FeatureUtility.java:389)
	at com.ibm.ws.install.featureUtility.cli.InstallFeatureAction.install(InstallFeatureAction.java:204)
	at com.ibm.ws.install.featureUtility.cli.InstallFeatureAction.execute(InstallFeatureAction.java:220)
	at com.ibm.ws.install.featureUtility.cli.InstallFeatureAction.handleTask(InstallFeatureAction.java:73)
	at com.ibm.ws.install.featureUtility.cli.FeatureAction.handleTask(FeatureAction.java:92)
	at com.ibm.ws.install.featureUtility.FeatureUtilityExecutor.main(FeatureUtilityExecutor.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.ibm.ws.kernel.boot.cmdline.UtilityMain.internal_main(UtilityMain.java:173)
	at com.ibm.ws.kernel.boot.cmdline.UtilityMain.main(UtilityMain.java:53)
	at com.ibm.ws.kernel.boot.cmdline.Main.main(Main.java:52)

**Steps to Reproduce**
wlp/bin/featureUtility installFeature --verbose com.ibm.websphere.appserver.features:jaxrs-1.1

**Expected behavior**
Should install the feature without NPE

**Diagnostic information:**
 - OpenLiberty Version: [e.g. 20.0.0.2]
 - openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.24.0, JRE 11 Mac OS X amd64-64-Bit Compressed References 20210120_897 (JIT enabled, AOT enabled)
OpenJ9   - 345e1b09e
OMR      - 741e94ea8
JCL      - 0a86953833 based on jdk-11.0.10+9)

**Comment by jjiwooLim** [comment]
#libybot
