### ISSUE TITLE
Fixes issues synchronizing on value based classes 

### ISSUE THREAD

**Issue by Thihup** [OpenLiberty/open-liberty#16299]
**Describe the bug**
Running Open Liberty with the `-XX:+UnlockDiagnosticVMOptions -XX:DiagnoseSyncOnValueBasedClasses=2` and JDK 16, you'll get a lot of warnings of synchronizing on value based classes, mostly java.lang.Integer

https://openjdk.java.net/jeps/390

An example of the warning:
```
[17,773s][info][valuebasedclasses] Synchronizing on object 0x000000070a000cc0 of klass java.lang.Integer
[17,773s][info][valuebasedclasses]      at com.ibm.ws.artifact.zip.cache.internal.ZipFileReaper.getRipest(ZipFileReaper.java:976)
[17,773s][info][valuebasedclasses]      - locked <0x000000070a000cc0> (a java.lang.Integer)
[17,773s][info][valuebasedclasses]      at com.ibm.ws.artifact.zip.cache.internal.ZipFileReaper$ReaperRunnable.run(ZipFileReaper.java:478)
[17,773s][info][valuebasedclasses]      at java.lang.Thread.run(java.base@16/Thread.java:831)
```

**Comment by jhanders34** [comment]
I have a PR started for this that will be merged in the next month likely.

**Comment by gjwatts** [comment]
@Thihup Thank you for reporting this issue and teaming up with us to improve Open Liberty!

**Comment by Thihup** [comment]
Thank you for answering so quickly ;)

**Comment by jhanders34** [comment]
I have fixed the ones I knew about in the liberty code.  I see that there are some also in EclipseLink and DB2 for the application scenario I was running.  I followed up with the JPA team to have them work with the EclipseLink community to get EclipseLink updated.
