### ISSUE TITLE
Unable to package JSONB-1.0 API in applications.

### ISSUE THREAD

**Issue by WhiteCat22** [OpenLiberty/open-liberty#1635]
Currently, users are unable to package the JSONB-1.0 API jar in their applications because Liberty does not tolerate Java 9 module classes. Users need to be able to package the JSONB-1.0 API jar to use their own JSONB implementation instead of the default implementation provided by Liberty. If you attempt to package the JSONB-1.0 API jar with Apache Johnzon you get the following error:

CWWKC0044W: An exception occurred while scanning class and annotation data. The exception was java.lang.RuntimeException
	at org.objectweb.asm.ClassVisitor.visitModule(ClassVisitor.java:148)
	at org.objectweb.asm.ClassReader.readModule(ClassReader.java:731)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:632)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:500)
	at com.ibm.ws.anno.targets.internal.AnnotationTargetsImpl_Targets.scanClass(AnnotationTargetsImpl_Targets.java:497)
	at com.ibm.ws.anno.targets.internal.AnnotationTargetsImpl_Streamer.process(AnnotationTargetsImpl_Streamer.java:88)
	at com.ibm.ws.anno.classsource.internal.ClassSourceImpl_MappedContainer.process(ClassSourceImpl_MappedContainer.java:351)
	at com.ibm.ws.anno.classsource.internal.ClassSourceImpl_MappedContainer.scanClasses(ClassSourceImpl_MappedContainer.java:283)
	at com.ibm.ws.anno.classsource.internal.ClassSourceImpl_MappedContainer.scanClasses(ClassSourceImpl_MappedContainer.java:128)
	at com.ibm.ws.anno.classsource.internal.ClassSourceImpl_Aggregate.scanClasses(ClassSourceImpl_Aggregate.java:369)
	at com.ibm.ws.anno.targets.internal.AnnotationTargetsImpl_Scanner.scanClasses(AnnotationTargetsImpl_Scanner.java:254)
	at com.ibm.ws.anno.targets.internal.AnnotationTargetsImpl_Scanner.scanDirect(AnnotationTargetsImpl_Scanner.java:216)
	at com.ibm.ws.anno.targets.internal.AnnotationTargetsImpl_Targets.doScanDirectClasses(AnnotationTargetsImpl_Targets.java:379)
	at com.ibm.ws.anno.targets.internal.AnnotationTargetsImpl_Targets.scanDirectClasses(AnnotationTargetsImpl_Targets.java:348)
	at com.ibm.ws.anno.targets.internal.AnnotationTargetsImpl_Targets.selectAnnotatedTargets(AnnotationTargetsImpl_Targets.java:1753)
	at com.ibm.ws.anno.targets.internal.AnnotationTargetsImpl_Targets.getAnnotatedClasses(AnnotationTargetsImpl_Targets.java:913)
	at com.ibm.ws.anno.targets.internal.AnnotationTargetsImpl_Targets.getAnnotatedClasses(AnnotationTargetsImpl_Targets.java:983)
	at com.ibm.ws.container.service.annotations.internal.WebAnnotationsImpl$FragmentAnnotationsImpl.selectAnnotatedClasses(WebAnnotationsImpl.java:453)
	at com.ibm.ws.webcontainer.osgi.container.config.WebAppConfiguratorHelper.configureFromAnnotations(WebAppConfiguratorHelper.java:806)
	at com.ibm.ws.webcontainer.osgi.container.config.WebAppConfigurator.configure(WebAppConfigurator.java:422)
	at com.ibm.ws.webcontainer.osgi.container.config.WebAppConfigurationAdapter.adapt(WebAppConfigurationAdapter.java:119)
	at com.ibm.ws.webcontainer.osgi.container.config.WebAppConfigurationAdapter.adapt(WebAppConfigurationAdapter.java:43)
	at com.ibm.ws.adaptable.module.internal.AdapterFactoryServiceImpl.adapt(AdapterFactoryServiceImpl.java:193)
	at com.ibm.ws.adaptable.module.internal.AdaptableContainerImpl.adapt(AdaptableContainerImpl.java:170)
	at com.ibm.ws.webcontainer.osgi.WebContainer.createModuleMetaData(WebContainer.java:833)
	at com.ibm.ws.app.manager.module.internal.ModuleHandlerBase.createModuleMetaData(ModuleHandlerBase.java:63)
	at com.ibm.ws.app.manager.module.internal.SimpleDeployedAppInfoBase$ModuleContainerInfoBase.createModuleMetaData(SimpleDeployedAppInfoBase.java:168)
	at com.ibm.ws.app.manager.module.internal.DeployedAppInfoBase.preDeployApp(DeployedAppInfoBase.java:368)
	at com.ibm.ws.app.manager.module.internal.DeployedAppInfoBase.deployApp(DeployedAppInfoBase.java:412)
	at com.ibm.ws.app.manager.war.internal.WARApplicationHandlerImpl.install(WARApplicationHandlerImpl.java:65)
	at com.ibm.ws.app.manager.internal.statemachine.StartAction.execute(StartAction.java:140)
	at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.enterState(ApplicationStateMachineImpl.java:1258)
	at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.run(ApplicationStateMachineImpl.java:873)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1153)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:785)

**Comment by WhiteCat22** [comment]
Related to https://github.com/openliberty/open-liberty/issues/1423

**Comment by WhiteCat22** [comment]
jar in question: https://mvnrepository.com/artifact/javax.json.bind/javax.json.bind-api/1.0

**Comment by tbitonti** [comment]
This issue relates to two cases both of which arise from features added retrospectively to pre-java9 processing by the java9 specification:

(1) "module-info.class", which is a new class type file which encodes java9 module information.  These classes occur as root level classes in Java archives.  For the purpose of this issue, Java archives are taken to include JAR files, WAR files, and RAR files.  JAR files includes utility JAR files, EJBJAR files, APPCLIENT JAR files, and WAR FRAGMENT JAR files.

(2) META-INF/versions/**/*.class.  The possible presence of version specific classes under META-INF is a java9 feature.  The function is labelled as "multi-release" JARs.  As with the prior case, this issue accepts the same wide definition of JAR files as specified for that case.

For this issue, the desired behavior is that all classes which arise from cases (1) and (2) are to be ignored.  In particular, annotation scanning will ignore all such classes, and any caching of annotations data will similarly ignore such classes.

While technically new function (a design change made retroactively to java8 by java9), this issue is being handled as a defect.  The target is 1Q2018, as a part of JavaEE8 support.
