### ISSUE TITLE
HostnameVerifier, socket reset for TTL error and NPE with JDK 8.0.6.26

### ISSUE THREAD

**Issue by ibmfjk** [OpenLiberty/open-liberty#16415]
**Describe the bug**

after we changed the jre version to 8.0.6.26, I always get below exception when connecting the one endpoint using cxf, The hostname verifier should not be a problem as the hostname is correctly included as a SAN.
```
[2021-03-30T03:10:23.755+0000] 00000054 .apache.cxf.cxf.core.3.2:1.0.47.cl201220201111-0736(id=143)] W Interceptor for {https://xxxx.fyre.ibm.com:7443/oidc/endpoint/ums/token}WebCl
ient has thrown exception, unwinding now
java.lang.RuntimeException: RuntimeException invoking https://xxxx.fyre.ibm.com:7443/oidc/endpoint/ums/token: HostnameVerifier, socket reset for TTL
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:83)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:57)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:437)
        at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.mapException(HTTPConduit.java:1451)
        at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.close(HTTPConduit.java:1439)
        at org.apache.cxf.io.AbstractWrappedOutputStream.close(AbstractWrappedOutputStream.java:77)
        at org.apache.cxf.transport.AbstractConduit.close(AbstractConduit.java:56)
        at org.apache.cxf.transport.http.HTTPConduit.close(HTTPConduit.java:689)
        at org.apache.cxf.interceptor.MessageSenderInterceptor$MessageSenderEndingInterceptor.handleMessage(MessageSenderInterceptor.java:63)
        at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
        at org.apache.cxf.jaxrs.client.AbstractClient.doRunInterceptorChain(AbstractClient.java:704)
        at org.apache.cxf.jaxrs.client.WebClient.doChainedInvocation(WebClient.java:1086)
        at org.apache.cxf.jaxrs.client.WebClient.doInvoke(WebClient.java:932)
        at org.apache.cxf.jaxrs.client.WebClient.doInvoke(WebClient.java:901)
        at org.apache.cxf.jaxrs.client.WebClient.invoke(WebClient.java:461)
        at org.apache.cxf.jaxrs.client.SyncInvokerImpl.method(SyncInvokerImpl.java:150)
        at org.apache.cxf.jaxrs.client.SyncInvokerImpl.method(SyncInvokerImpl.java:145)
        at org.apache.cxf.jaxrs.client.SyncInvokerImpl.post(SyncInvokerImpl.java:85)
        at org.apache.cxf.jaxrs.client.spec.InvocationBuilderImpl.post(InvocationBuilderImpl.java:157)
        at com.ibm.dba.ums.security.authentication.jaas.modules.UMSLoginModule.authorize(UMSLoginModule.java:146)
        at com.ibm.dba.ums.security.authentication.jaas.modules.UMSLoginModuleBase.login(UMSLoginModuleBase.java:267)
        at com.ibm.ws.security.jaas.common.modules.WSLoginModuleProxy.login(WSLoginModuleProxy.java:141)
        at com.ibm.ws.kernel.boot.security.LoginModuleProxy.login(LoginModuleProxy.java:51)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
        at java.lang.reflect.Method.invoke(Method.java:508)
        at javax.security.auth.login.LoginContext.invoke(LoginContext.java:788)
        at javax.security.auth.login.LoginContext.access$000(LoginContext.java:196)
        at javax.security.auth.login.LoginContext$4.run(LoginContext.java:698)
        at javax.security.auth.login.LoginContext$4.run(LoginContext.java:696)
        at java.security.AccessController.doPrivileged(AccessController.java:738)
        at javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:696)
        at javax.security.auth.login.LoginContext.login(LoginContext.java:597)
        at com.lombardisoftware.client.delegate.common.ServiceLocator.login(ServiceLocator.java:552)
        at com.lombardisoftware.client.delegate.common.ServiceLocator.getSubject(ServiceLocator.java:518)
        at com.lombardisoftware.client.delegate.common.ServiceLocator.getSubject(ServiceLocator.java:496)
        at com.ibm.bpm.server.startup.SchedulerInitializerStartupBean$1.run(SchedulerInitializerStartupBean.java:128)
        at java.lang.Thread.run(Thread.java:822)
        at com.ibm.ws.concurrent.internal.ManagedThreadImpl.run(ManagedThreadImpl.java:94)
        at com.ibm.bpm.ps.ConditionActionManager.resolveCondition(ConditionActionManager.java:102)
        at com.ibm.bpm.server.startup.LibertyPSStatusChecker$TeamWorksAppMBeanListener.handleNotification(LibertyPSStatusChecker.java:140)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor$ListenerWrapper.handleNotification(DefaultMBeanServerInterceptor.java:1766)
        at javax.management.NotificationBroadcasterSupport.handleNotification(NotificationBroadcasterSupport.java:286)
        at javax.management.NotificationBroadcasterSupport$SendNotifJob.run(NotificationBroadcasterSupport.java:363)
        at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:239)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.lang.Thread.run(Thread.java:822)
Caused by: java.lang.RuntimeException: HostnameVerifier, socket reset for TTL
        at org.apache.cxf.transport.https.AllowAllHostnameVerifier.verify(AllowAllHostnameVerifier.java:48)
        at com.ibm.net.ssl.www2.protocol.https.c.b(c.java:117)
        at com.ibm.net.ssl.www2.protocol.https.c.afterConnect(c.java:181)
        at com.ibm.net.ssl.www2.protocol.https.d.connect(d.java:46)
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1352)
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1327)
        at com.ibm.net.ssl.www2.protocol.https.b.getOutputStream(b.java:91)
        at org.apache.cxf.transport.http.URLConnectionHTTPConduit$URLConnectionWrappedOutputStream.setupWrappedStream(URLConnectionHTTPConduit.java:312)
        at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.handleHeadersTrustCaching(HTTPConduit.java:1391)
        at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.onFirstWrite(HTTPConduit.java:1352)
        at org.apache.cxf.transport.http.URLConnectionHTTPConduit$URLConnectionWrappedOutputStream.onFirstWrite(URLConnectionHTTPConduit.java:345)
        at org.apache.cxf.io.AbstractWrappedOutputStream.write(AbstractWrappedOutputStream.java:47)
        at org.apache.cxf.io.AbstractThresholdOutputStream.write(AbstractThresholdOutputStream.java:69)
        at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.close(HTTPConduit.java:1406)
        ... 44 more
```

 I also see error when connecting to https://xxxxxx.fyre.ibm.com:7443/ums/, the problem just start to appear after we switch to latest base image where jre is upgraded and com.ibm.crypto.plus.provider.IBMJCEPlus is enabled, not sure if that is the cause.
```An error occurred during a connection to ditzier1.fyre.ibm.com:7443. PR_END_OF_FILE_ERROR ```

**Steps to Reproduce**
Start Liberty 20.0.0.12 server with JRE version to 8.0.6.26 (for security CVEs fix), in the ffdc you can also found below exception:

```
Stack Dump = java.lang.NullPointerException
        at com.ibm.crypto.fips.provider.RSAPSSSignature.b(Unknown Source)
        at com.ibm.crypto.fips.provider.RSAPSSSignature.c(Unknown Source)
        at com.ibm.crypto.fips.provider.RSAPSSSignature.engineSign(Unknown Source)
        at java.security.Signature$Delegate.engineSign(Signature.java:1391)
        at java.security.Signature.sign(Signature.java:704)
        at com.ibm.jsse2.a7.c(a7.java:22)
        at com.ibm.jsse2.P$d.<init>(P$d.java:99)
        at com.ibm.jsse2.P$c.produce(P$c.java:3)
        at com.ibm.jsse2.F$e.a(F$e.java:9)
        at com.ibm.jsse2.F$b.a(F$b.java:2)
        at com.ibm.jsse2.F$b.consume(F$b.java:22)
        at com.ibm.jsse2.p.consume(p.java:43)
        at com.ibm.jsse2.Z.a(Z.java:73)
        at com.ibm.jsse2.bf$a$b.a(bf$a$b.java:2)
        at com.ibm.jsse2.bf$a$b.run(bf$a$b.java:3)
        at java.security.AccessController.doPrivileged(AccessController.java:774)
        at com.ibm.jsse2.bf$a.run(bf$a.java:26)
        at com.ibm.ws.channel.ssl.internal.SSLUtils.handleHandshake(SSLUtils.java:751)
        at com.ibm.ws.channel.ssl.internal.SSLConnectionLink.readyInbound(SSLConnectionLink.java:589)
        at com.ibm.ws.channel.ssl.internal.SSLConnectionLink.ready(SSLConnectionLink.java:336)
        at com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.sendToDiscriminators(NewConnectionInitialReadCallback.java:167)
        at com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.complete(NewConnectionInitialReadCallback.java:75)
        at com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:504)
        at com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueManager.java:574)
        at com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:958)
        at com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:1047)
        at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:239)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.lang.Thread.run(Thread.java:822)
```

**Expected behavior**
there is no NPE or certificate issue during server startup.

**Diagnostic information:**
 - OpenLiberty Version: [e.g. 20.0.0.12]
 
 - Java Version: 
 java version "1.8.0_281"
Java(TM) SE Runtime Environment (build 8.0.6.26 - pxa6480sr6fp26-20210216_01(SR6 FP26))
IBM J9 VM (build 2.9, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20210216_465732 (JIT enabled, AOT enabled)
OpenJ9   - e5f4f96
OMR      - 999051a
IBM      - 358762e)
JCL - 20210108_01 based on Oracle jdk8u281-b09

 - server.xml configuration (WITHOUT sensitive information like passwords)
 - If it would be useful, upload the messages.log file found in `$WLP_OUTPUT_DIR/messages.log`

**Additional context**
with below java version, I did not see the issue:

java version "1.8.0_271"
Java(TM) SE Runtime Environment (build 8.0.6.20 - pxa6480sr6fp20-20201120_02(SR6 FP20))
IBM J9 VM (build 2.9, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20201102_458768 (JIT enabled, AOT enabled)
OpenJ9   - 5b31a42
OMR      - 6ad3a34
IBM      - b7e48f4)
JCL - 20201119_01 based on Oracle jdk8u271-b09

**Comment by andymc12** [comment]
FWIW, the underlying CXF has changed recently which will impact this behavior slightly - instead of throwing the RuntimeException ("HostnameVerifier, socket reset for TTL"), it will just return false - which still doesn't help, but makes less noise. We are planning to move to the latest version of CXF shortly, which should get this change ( https://github.com/apache/cxf/commit/3a22718d6ce69d01d860a73f3eaf4bc7c658d2b6#diff-9ff8546cfef6f07b015557267e840384a9de3e8db023bdf43dcef1a5148662f9 ).

The actual problem is the SSLException that occurs during the `AllowAllHostnameVerifier`'s `verify` method.  We should be able to see that exception by enabling `org.apache.cxf.transport.https.AllowAllHostnameVerifier=all` trace.  I suspect it will be something similar to the NPE that you posted  - and that will likely be the root of the problem.  If so, we'll need to pull in somebody much more familiar with SSL than me.  HTH

**Comment by ibmfjk** [comment]
my issue if fixed by https://www.ibm.com/support/pages/node/6422887
