### ISSUE TITLE
InjectionException: The injection engine failed to load the com.ibm.ws.ejbcontainer.remote.client.internal.injection.EJBLinkClientObjectFactoryImpl ObjectFactory class

### ISSUE THREAD

**Issue by brideck** [OpenLiberty/open-liberty#16596]
In the last month, an inordinate amount of the Jakarta EE TCK testing that involves the Liberty client has started failing intermittently with the following exception:

com.ibm.wsspi.injectionengine.InjectionException: CWNEN0030E: The server was unable to obtain an object instance for the java:comp/env/ejb/AppManagedNoTxVehicleBean reference.  The exception message was: com.ibm.wsspi.injectionengine.InjectionException: The injection engine failed to load the com.ibm.ws.ejbcontainer.remote.client.internal.injection.EJBLinkClientObjectFactoryImpl ObjectFactory class.
	at com.ibm.wsspi.injectionengine.InjectionBinding.getInjectionObject(InjectionBinding.java:1454)
	at com.ibm.ws.ejb.injection.processor.EJBInjectionBinding.getInjectionObject(EJBInjectionBinding.java:1046)
	at com.ibm.wsspi.injectionengine.InjectionBinding.getInjectionObject(InjectionBinding.java:1384)
	at com.ibm.ws.injectionengine.osgi.internal.naming.InjectionJavaColonHelper.getObjectInstance(InjectionJavaColonHelper.java:116)
	at com.ibm.ws.jndi.url.contexts.javacolon.internal.JavaURLContext.lookup(JavaURLContext.java:332)
	at com.ibm.ws.jndi.url.contexts.javacolon.internal.JavaURLContext.lookup(JavaURLContext.java:370)
	at org.apache.aries.jndi.DelegateContext.lookup(DelegateContext.java:149)
	at javax.naming.InitialContext.lookup(InitialContext.java:417)
	at com.sun.ts.lib.util.TSNamingContext.lookup(TSNamingContext.java:69)
	at com.sun.ts.tests.common.vehicle.appmanagedNoTx.AppManagedNoTxVehicleRunner.run(AppManagedNoTxVehicleRunner.java:38)
	at com.sun.ts.lib.harness.ServiceEETest.run(ServiceEETest.java:105)
	at com.sun.ts.lib.harness.EETest.getPropsReady(EETest.java:486)
	at com.sun.ts.lib.harness.ServiceEETest.run(ServiceEETest.java:209)
	at com.sun.ts.lib.harness.EETest.run(EETest.java:285)
	at com.sun.ts.tests.common.vehicle.VehicleClient.main(VehicleClient.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.ibm.ws.clientcontainer.internal.ClientRunnerImpl.run(ClientRunnerImpl.java:95)
	at com.ibm.ws.kernel.launch.internal.FrameworkManager.launchClient(FrameworkManager.java:360)
	at com.ibm.ws.kernel.launch.internal.FrameworkManager.launchFramework(FrameworkManager.java:299)
	at com.ibm.ws.kernel.launch.internal.LauncherDelegateImpl.doFrameworkLaunch(LauncherDelegateImpl.java:114)
	at com.ibm.ws.kernel.launch.internal.LauncherDelegateImpl.launchFramework(LauncherDelegateImpl.java:100)
	at com.ibm.ws.kernel.boot.internal.KernelBootstrap.go(KernelBootstrap.java:214)
	at com.ibm.ws.appclient.boot.ClientLauncher.handleActions(ClientLauncher.java:64)
	at com.ibm.ws.kernel.boot.Launcher.createPlatform(Launcher.java:117)
	at com.ibm.ws.kernel.boot.cmdline.EnvCheck.main(EnvCheck.java:59)
	at com.ibm.ws.appclient.boot.cmdline.ClientEnvCheck.main(ClientEnvCheck.java:26)
Caused by: com.ibm.wsspi.injectionengine.InjectionException: com.ibm.wsspi.injectionengine.InjectionException: The injection engine failed to load the com.ibm.ws.ejbcontainer.remote.client.internal.injection.EJBLinkClientObjectFactoryImpl ObjectFactory class.
	at com.ibm.wsspi.injectionengine.InjectionBinding.getInjectionObjectInstance(InjectionBinding.java:1542)
	at com.ibm.ws.ejb.injection.processor.EJBInjectionBinding.getInjectionObjectInstance(EJBInjectionBinding.java:1108)
	at com.ibm.wsspi.injectionengine.InjectionBinding.getInjectionObject(InjectionBinding.java:1428)
	... 28 more
Caused by: com.ibm.wsspi.injectionengine.InjectionException: The injection engine failed to load the com.ibm.ws.ejbcontainer.remote.client.internal.injection.EJBLinkClientObjectFactoryImpl ObjectFactory class.
	at com.ibm.ws.injectionengine.osgi.internal.OSGiInjectionEngineImpl.getObjectFactory(OSGiInjectionEngineImpl.java:776)
	at com.ibm.wsspi.injectionengine.InjectionBinding.getInjectionObjectInstance(InjectionBinding.java:1530)
	... 30 more

Something appears to have changed when the client initializes such that the required services are not all started yet, even though the application and client claim to both be running and ready.  I have attempted to collect logservice trace to help see what might be going wrong, but am unable to reproduce the failure with this trace enabled.

**Comment by tkburroughs** [comment]
The problem appears to be that the ClientORB never comes up  (see com.ibm.ws.transport.iiop.spi.ClientORBRef)

Without the ClientORB, then com.ibm.ws.clientcontainer.remote.common.internal.ClientSupportFactoryImpl does not come up.... and thus any naming lookup that should be directed to the remote server will fail.  Also, injection of an EJB that doesn't have a binding (i.e. EJB link) will not work either because EJBLinkClientObjectFactoryImpl will not start without ClientSupportFactoryImpl.

**Comment by brideck** [comment]
I have not seen this issue much (at all?) since the restart of CTS builds at the end of July, but I'll keep looking for it over the next couple of months before doing anything with this.

**Comment by brideck** [comment]
This issue has continued to be nonexistent in CTS builds, so I'm going to close it.
