### ISSUE TITLE
Authorization failure occurs when LDAP or basic user attempts login in SAF federated registry

### ISSUE THREAD

**Issue by ryanesch** [OpenLiberty/open-liberty#16637]
A SAFException is thrown when a user is logging in.
This is a specific scenario when a user has:

- SAF registry
- Any additional registry inside a federated registry
- No <safCredentials> element

When a non-SAF user attempts login, a SAFException is thrown when the z/os credential is being created:
```
com.ibm.ws.security.saf.SAFException: CWWKS2910E: SAF service WAS_INTERNAL did not succeed. SAF return code 0xffffffff. RACF return code 0xffffffff. RACF reason code 0xffffffff. Internal error code 0x00000001.
	at com.ibm.ws.security.saf.SAFServiceResult.getSAFException(SAFServiceResult.java:323)
	at com.ibm.ws.security.saf.SAFServiceResult.throwSAFException(SAFServiceResult.java:315)
	at com.ibm.ws.security.credentials.saf.internal.SAFCredentialsServiceImpl.createAssertedCredentialToken(SAFCredentialsServiceImpl.java:562)
	at com.ibm.ws.security.credentials.saf.internal.SAFCredentialsServiceImpl.createAssertedCredential(SAFCredentialsServiceImpl.java:508)
	at com.ibm.ws.security.credentials.saf.internal.SAFCredentialsServiceImpl.setCredential(SAFCredentialsServiceImpl.java:957)
```
When the SAF credential is not used, it should not be created.

**Comment by ryanesch** [comment]
https://github.com/OpenLiberty/open-liberty/pull/16239
