### ISSUE TITLE
Java 2 Sec com.ibm.websphere.microprofile.faulttolerance_fat.tests.CDIRetryTest & CDITimeoutTest failure

### ISSUE THREAD

**Issue by hutchig** [OpenLiberty/open-liberty#1666]
https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_ahvW0Ps0EeefH4uRV76YPQ&tab=com.ibm.team.build.web.ui.internal.editors.result.test.TestProvider

com.ibm.ws.fat.util.browser.WebBrowserException: The body of Web Browser 38 Response 1 does not contain: SUCCESS - Response body: ERROR: Caught exception attempting to call test method testRetry on servlet com.ibm.ws.microprofile.faulttolerance_fat.cdi.RetryServlet
java.security.AccessControlException: Access denied ("java.lang.RuntimePermission" "getClassLoader")
	at java.security.AccessController.throwACE(AccessController.java:157)
	at java.security.AccessController.checkPermissionHelper(AccessController.java:217)
	at java.security.AccessController.checkPermission(AccessController.java:349)
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:562)
	at java.lang.Class.getClassLoader(Class.java:442)
	at com.ibm.ws.microprofile.faulttolerance.cdi.config.AbstractAnnotationConfig$AnnotationParameterConfig.readConfigValue(AbstractAnnotationConfig.java:89)
	at com.ibm.ws.microprofile.faulttolerance.cdi.config.AbstractAnnotationConfig$AnnotationParameterConfig.getConfigValue(AbstractAnnotationConfig.java:85)
	at com.ibm.ws.microprofile.faulttolerance.cdi.config.AbstractAnnotationConfig$AnnotationParameterConfig.init(AbstractAnnotationConfig.java:67)
	at com.ibm.ws.microprofile.faulttolerance.cdi.config.AbstractAnnotationConfig$AnnotationParameterConfig.access$600(AbstractAnnotationConfig.java:54)
	at com.ibm.ws.microprofile.faulttolerance.cdi.config.AbstractAnnotationConfig.getParameterConfig(AbstractAnnotationConfig.java:199)
	at com.ibm.ws.microprofile.faulttolerance.cdi.config.RetryConfig.<init>(RetryConfig.java:29)
	at com.ibm.ws.microprofile.faulttolerance.cdi.FaultToleranceInterceptor.processPolicies(FaultToleranceInterceptor.java:123)
	at com.ibm.ws.microprofile.faulttolerance.cdi.FaultToleranceInterceptor.getFTPolicies(FaultToleranceInterceptor.java:89)
	at com.ibm.ws.microprofile.faulttolerance.cdi.FaultToleranceInterceptor.executeFT(FaultToleranceInterceptor.java:73)
	at org.jboss.weld.interceptor.reader.SimpleInterceptorInvocation$SimpleMethodInvocation.invoke(SimpleInterceptorInvocation.java:73)
	at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeAroundInvoke(InterceptorMethodHandler.java:84)
	at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeInterception(InterceptorMethodHandler.java:72)
	at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.invoke(InterceptorMethodHandler.java:56)
	at org.jboss.weld.bean.proxy.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(CombinedInterceptorAndDecoratorStackMethodHandler.java:79)
	at org.jboss.weld.bean.proxy.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(CombinedInterceptorAndDecoratorStackMethodHandler.java:68)
	at com.ibm.ws.microprofile.faulttolerance_fat.cdi.beans.RetryBeanB$Proxy$_$$_WeldSubclass.connectB(Unknown Source)
	at com.ibm.ws.microprofile.faulttolerance_fat.cdi.beans.RetryBeanB$Proxy$_$$_WeldClientProxy.connectB(Unknown Source)
	at com.ibm.ws.microprofile.faulttolerance_fat.cdi.RetryServlet.testRetry(RetryServlet.java:58)
	at componenttest.app.FATServlet.doGet(FATServlet.java:67)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1255)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:743)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:440)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1154)
	at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:4962)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.handleRequest(DynamicVirtualHost.java:314)
	at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:995)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:279)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1009)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:412)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:371)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:530)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:464)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:329)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.ready(HttpInboundLink.java:300)
	at com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.sendToDiscriminators(NewConnectionInitialReadCallback.java:165)
	at com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.complete(NewConnectionInitialReadCallback.java:74)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:501)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueManager.java:571)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:926)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:1015)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1153)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:785)

	at com.ibm.ws.fat.util.browser.WebResponse.verifyResponseBody(WebResponse.java:880)
	at com.ibm.ws.fat.util.browser.WebResponse.verifyResponseBodyContains(WebResponse.java:837)
	at com.ibm.ws.fat.util.SharedServer.verifyResponse(SharedServer.java:232)
	at com.ibm.websphere.microprofile.faulttolerance_fat.tests.CDIRetryTest.testRetry(CDIRetryTest.java:35)

**Comment by Emily-Jiang** [comment]
I fixed this as part of #686
