### ISSUE TITLE
Fix the intermittent EE9 only Test Failure: Test Failure: com.ibm.ws.jaxrs20.fat.securitycontext.CustomSecurityContextTest.testCustomSecurityContextSetInFilter_EE9_FEATURES

### ISSUE THREAD

**Issue by jkoehler22** [OpenLiberty/open-liberty#16693]
testCustomSecurityContextSetInFilter_EE9_FEATURES:junit.framework.AssertionFailedError: 2021-04-16-13:03:02:143 [Unexpected FFDC reporting java.lang.IllegalArgumentException was found (count = 1): /home/jazz_build/Build/jbe/build/dev/image/output/wlp/usr/servers/com.ibm.ws.jaxrs.fat.customSecurityContext/logs/ffdc/ffdc_21.04.16_13.03.01.0.log
>------Start of DE processing------ = [4/16/21, 13:03:01:998 PDT]
>Exception = java.lang.IllegalArgumentException
>Source = com.ibm.ws.security.token.internal.TokenManagerImpl
>probeid = 87
>Stack Dump = java.lang.IllegalArgumentException: CWWKS4000E: A configuration exception has occurred. The requested TokenService instance of type Ltpa2 could not be found.
> at com.ibm.ws.security.token.internal.TokenManagerImpl.getTokenServiceForType(TokenManagerImpl.java:185)
> at com.ibm.ws.security.token.internal.TokenManagerImpl.createSSOToken(TokenManagerImpl.java:82)
> at com.ibm.ws.security.credentials.ssotoken.internal.SSOTokenCredentialProvider.setSsoTokenCredential(SSOTokenCredentialProvider.java:108)
> at com.ibm.ws.security.credentials.ssotoken.internal.SSOTokenCredentialProvider.setCredential(SSOTokenCredentialProvider.java:85)
> at com.ibm.ws.security.credentials.internal.CredentialsServiceImpl.setCredentials(CredentialsServiceImpl.java:76)
> at com.ibm.ws.security.authentication.internal.jaas.modules.ServerCommonLoginModule.setCredentials(ServerCommonLoginModule.java:148)
> at com.ibm.ws.security.authentication.jaas.modules.UsernameAndPasswordLoginModule.setUpTemporarySubject(UsernameAndPasswordLoginModule.java:145)
> at com.ibm.ws.security.authentication.jaas.modules.UsernameAndPasswordLoginModule.login(UsernameAndPasswordLoginModule.java:78)
> at com.ibm.ws.kernel.boot.security.LoginModuleProxy.login(LoginModuleProxy.java:51)
> at java.base/javax.security.auth.login.LoginContext.invoke(LoginContext.java:726)
> at java.base/javax.security.auth.login.LoginContext$4.run(LoginContext.java:665)
> at java.base/javax.security.auth.login.LoginContext$4.run(LoginContext.java:663)
> at java.base/java.security.AccessController.doPrivileged(AccessController.java:770)
> at java.base/javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:663)
> at java.base/javax.security.auth.login.LoginContext.login(LoginContext.java:574)
> at com.ibm.ws.security.authentication.internal.jaas.JAASServiceImpl.doLoginContext(JAASServiceImpl.java:343)
> at com.ibm.ws.security.authentication.internal.jaas.JAASServiceImpl.performLogin(JAASServiceImpl.java:329)
> at com.ibm.ws.security.authentication.internal.jaas.JAASServiceImpl.performLogin(JAASServiceImpl.java:314)
> at com.ibm.ws.security.authentication.internal.AuthenticationServiceImpl.performJAASLogin(AuthenticationServiceImpl.java:495)
> at com.ibm.ws.security.authentication.internal.AuthenticationServiceImpl.authenticate(AuthenticationServiceImpl.java:210)
> at com.ibm.ws.webcontainer.security.internal.BasicAuthAuthenticator.basicAuthenticate(BasicAuthAuthenticator.java:126)
> at com.ibm.ws.webcontainer.security.internal.BasicAuthAuthenticator.handleBasicAuth(BasicAuthAuthenticator.java:117)
> at com.ibm.ws.webcontainer.security.internal.BasicAuthAuthenticator.authenticate(BasicAuthAuthenticator.java:70)
> at com.ibm.ws.webcontainer.security.WebAuthenticatorProxy.authenticate(WebAuthenticatorProxy.java:88)
> at com.ibm.ws.webcontainer.security.WebAppSecurityCollaboratorImpl.authenticateRequest(WebAppSecurityCollaboratorImpl.java:1233)
> at com.ibm.ws.webcontainer.security.WebAppSecurityCollaboratorImpl.setAuthenticatedSubjectIfNeeded(WebAppSecurityCollaboratorImpl.java:855)
> at com.ibm.ws.webcontainer.security.WebAppSecurityCollaboratorImpl.optionallyAuthenticateUnprotectedResource(WebAppSecurityCollaboratorImpl.java:812)
> at com.ibm.ws.webcontainer.security.WebAppSecurityCollaboratorImpl.determineWebReply(WebAppSecurityCollaboratorImpl.java:982)
> at com.ibm.ws.webcontainer.security.WebAppSecurityCollaboratorImpl.performSecurityChecks(WebAppSecurityCollaboratorImpl.java:678)
> at com.ibm.ws.webcontainer.security.WebAppSecurityCollaboratorImpl.preInvoke(WebAppSecurityCollaboratorImpl.java:596)
> at com.ibm.wsspi.webcontainer.collaborator.CollaboratorHelper.preInvokeCollaborators(CollaboratorHelper.java:459)
> at com.ibm.ws.webcontainer.osgi.collaborator.CollaboratorHelperImpl.preInvokeCollaborators(CollaboratorHelperImpl.java:270)
> at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1115)
> at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:5061)
> at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.handleRequest(DynamicVirtualHost.java:314)
> at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:1006)
> at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:279)
> at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1159)
> at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:428)
> at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:387)
> at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:566)
> at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:500)
> at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:360)
> at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.ready(HttpInboundLink.java:327)
> at com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.sendToDiscriminators(NewConnectionInitialReadCallback.java:167)
> at com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.complete(NewConnectionInitialReadCallback.java:75)
> at com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:504)
> at com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueManager.java:574)
> at com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:958)
> at com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:1047)
> at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:238)
> at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
> at java.base/java.lang.Thread.run(Thread.java:834)
, Unexpected FFDC reporting com.ibm.websphere.security.auth.TokenCreationFailedException was found (count = 1): /home/jazz_build/Build/jbe/build/dev/image/output/wlp/usr/servers/com.ibm.ws.jaxrs.fat.customSecurityContext/logs/ffdc/ffdc_21.04.16_13.03.02.0.log
>------Start of DE processing------ = [4/16/21, 13:03:02:024 PDT]
>Exception = com.ibm.websphere.security.auth.TokenCreationFailedException
>Source = com.ibm.ws.security.credentials.ssotoken.internal.SSOTokenCredentialProvider
>probeid = 112
>Stack Dump = com.ibm.websphere.security.auth.TokenCreationFailedException: CWWKS4000E: A configuration exception has occurred. The requested TokenService instance of type Ltpa2 could not be found.
> at com.ibm.ws.security.token.internal.TokenManagerImpl.createSSOToken(TokenManagerImpl.java:88)
> at com.ibm.ws.security.credentials.ssotoken.internal.SSOTokenCredentialProvider.setSsoTokenCredential(SSOTokenCredentialProvider.java:108)
> at com.ibm.ws.security.credentials.ssotoken.internal.SSOTokenCredentialProvider.setCredential(SSOTokenCredentialProvider.java:85)
> at com.ibm.ws.security.credentials.internal.CredentialsServiceImpl.setCredentials(CredentialsServiceImpl.java:76)
> at com.ibm.ws.security.authentication.internal.jaas.modules.ServerCommonLoginModule.setCredentials(ServerCommonLoginModule.java:148)
> at com.ibm.ws.security.authentication.jaas.modules.UsernameAndPasswordLoginModule.setUpTemporarySubject(UsernameAndPasswordLoginModule.java:145)
> at com.ibm.ws.security.authentication.jaas.modules.UsernameAndPasswordLoginModule.login(UsernameAndPasswordLoginModule.java:78)
> at com.ibm.ws.kernel.boot.security.LoginModuleProxy.login(LoginModuleProxy.java:51)
> at java.base/javax.security.auth.login.LoginContext.invoke(LoginContext.java:726)
> at java.base/javax.security.auth.login.LoginContext$4.run(LoginContext.java:665)
> at java.base/javax.security.auth.login.LoginContext$4.run(LoginContext.java:663)
> at java.base/java.security.AccessController.doPrivileged(AccessController.java:770)
> at java.base/javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:663)
> at java.base/javax.security.auth.login.LoginContext.login(LoginContext.java:574)
> at com.ibm.ws.security.authentication.internal.jaas.JAASServiceImpl.doLoginContext(JAASServiceImpl.java:343)
> at com.ibm.ws.security.authentication.internal.jaas.JAASServiceImpl.performLogin(JAASServiceImpl.java:329)
> at com.ibm.ws.security.authentication.internal.jaas.JAASServiceImpl.performLogin(JAASServiceImpl.java:314)
> at com.ibm.ws.security.authentication.internal.AuthenticationServiceImpl.performJAASLogin(AuthenticationServiceImpl.java:495)
> at com.ibm.ws.security.authentication.internal.AuthenticationServiceImpl.authenticate(AuthenticationServiceImpl.java:210)
> at com.ibm.ws.webcontainer.security.internal.BasicAuthAuthenticator.basicAuthenticate(BasicAuthAuthenticator.java:126)
> at com.ibm.ws.webcontainer.security.internal.BasicAuthAuthenticator.handleBasicAuth(BasicAuthAuthenticator.java:117)
> at com.ibm.ws.webcontainer.security.internal.BasicAuthAuthenticator.authenticate(BasicAuthAuthenticator.java:70)
> at com.ibm.ws.webcontainer.security.WebAuthenticatorProxy.authenticate(WebAuthenticatorProxy.java:88)
> at com.ibm.ws.webcontainer.security.WebAppSecurityCollaboratorImpl.authenticateRequest(WebAppSecurityCollaboratorImpl.java:1233)
> at com.ibm.ws.webcontainer.security.WebAppSecurityCollaboratorImpl.setAuthenticatedSubjectIfNeeded(WebAppSecurityCollaboratorImpl.java
Further analysis is available at https://libh-proxy1.fyre.ibm.com/cognitive/defectAnalysis.html?failureGroupId=failure_group-9adce6e6-c6b0-4586-a529-2b75ed44664b

**Comment by jkoehler22** [comment]
A bunch of ClassNotFoundException found in the logs.  Here is an example:

```
[4/16/21, 13:03:01:358 PDT] 00000029 org.jboss.resteasy.resteasy_jaxrs.i18n                       W RESTEASY002120: ClassNotFoundException: Unable to load builtin provider org.jboss.resteasy.rxjava2.SingleRxInvokerImpl from bundleresource://166.fwk1705773089/META-INF/services/jakarta.ws.rs.ext.Providers
java.lang.ClassNotFoundException: org.jboss.resteasy.rxjava2.SingleRxInvokerImpl
    at com.ibm.ws.classloading.internal.UnifiedClassLoader.findClass(UnifiedClassLoader.java:137)
    at com.ibm.ws.classloading.internal.ThreadContextClassLoader.findClass(ThreadContextClassLoader.java:141)
    at java.base/java.lang.ClassLoader.loadClassHelper(ClassLoader.java:1180)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1095)
    at com.ibm.ws.classloading.internal.UnifiedClassLoader.loadClass0(UnifiedClassLoader.java:116)
    at com.ibm.ws.classloading.internal.UnifiedClassLoader$Delegation.loadClass(UnifiedClassLoader.java:85)
    at com.ibm.ws.classloading.internal.UnifiedClassLoader.loadClass(UnifiedClassLoader.java:109)
    at com.ibm.ws.classloading.internal.ThreadContextClassLoader.loadClass(ThreadContextClassLoader.java:157)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1078)
    at org.jboss.resteasy.plugins.providers.RegisterBuiltin.registerProviders(RegisterBuiltin.java:95)
    at org.jboss.resteasy.plugins.providers.RegisterBuiltin.register(RegisterBuiltin.java:74)
    at org.jboss.resteasy.plugins.providers.RegisterBuiltin.getClientInitializedResteasyProviderFactory(RegisterBuiltin.java:54)
    at org.jboss.resteasy.client.jaxrs.internal.ResteasyClientBuilderImpl.getProviderFactory(ResteasyClientBuilderImpl.java:372)
    at org.jboss.resteasy.client.jaxrs.internal.ResteasyClientBuilderImpl.getConfiguration(ResteasyClientBuilderImpl.java:457)
    at io.openliberty.restfulWS.internal.ssl.component.SslClientBuilderListener.building(SslClientBuilderListener.java:59)
    at io.openliberty.org.jboss.resteasy.common.client.LibertyResteasyClientBuilderImpl.build(LibertyResteasyClientBuilderImpl.java:50)
    at io.openliberty.org.jboss.resteasy.common.client.LibertyResteasyClientBuilderImpl.build(LibertyResteasyClientBuilderImpl.java:39)
    at jakarta.ws.rs.client.ClientBuilder.newClient(ClientBuilder.java:88)
    at com.ibm.ws.jaxrs.fat.customsecuritycontext.servlet.CustomSecurityContextTestServlet.testCustomSecurityContextSetInFilter(CustomSecurityContextTestServlet.java:70)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at componenttest.app.FATServlet.doGet(FATServlet.java:71)
    at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:500)
    at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587)
    at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1258)
    at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:746)
    at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:443)
    at com.ibm.ws.webcontainer.filter.WebAppFilterChain.invokeTarget(WebAppFilterChain.java:183)
    at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:94)
    at com.ibm.ws.security.jaspi.JaspiServletFilter.doFilter(JaspiServletFilter.java:56)
    at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:201)
    at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:91)
    at com.ibm.ws.webcontainer.filter.WebAppFilterManager.doFilter(WebAppFilterManager.java:1002)
    at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1140)
    at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:5061)
    at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.handleRequest(DynamicVirtualHost.java:314)
    at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:1006)
    at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:279)
    at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1159)
    at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:428)
    at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:387)
    at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:566)
    at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:500)
    at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:360)
    at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.ready(HttpInboundLink.java:327)
    at com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.sendToDiscriminators(NewConnectionInitialReadCallback.java:167)
    at com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.complete(NewConnectionInitialReadCallback.java:75)
    at com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:504)
    at com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueManager.java:574)
    at com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:958)
    at com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:1047)
    at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:238)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by jim-krueger** [comment]
Returned as not reproducible
