### ISSUE TITLE
SOAPFaultException: Could not find conduit initiator occuring with wsAtomicTransacitons-1.2 and jaxrs-2.x

### ISSUE THREAD

**Issue by neuwerk** [OpenLiberty/open-liberty#16845]
A JAX-WS Web Service or Client is unable to send a request or response when the JAX-WS application is deployed with the `wsAtomicTransactions-1.2` feature and either the `jaxrs-2.0` or `jaxrs-2.1` feature. 

```
Caused by: java.util.concurrent.ExecutionException: javax.xml.ws.soap.SOAPFaultException: Could not find conduit initiator for address: <URL OF JAX-WS PORT> and transport: http://schemas.xmlsoap.org/soap/http
        at java.util.concurrent.FutureTask.report(FutureTask.java:133)
        at java.util.concurrent.FutureTask.get(FutureTask.java:203)
        at com.ibm.tx.jta.embeddable.impl.WSATParticipantWrapper.prepare(WSATParticipantWrapper.java:133)
        ... 55 more
Caused by: javax.xml.ws.soap.SOAPFaultException: Could not find conduit initiator for address: <URL OF JAX-WS PORT> and transport: http://schemas.xmlsoap.org/soap/http
        at org.apache.cxf.jaxws.JaxWsClientProxy.invoke(JaxWsClientProxy.java:156)
        at com.sun.proxy.$Proxy295.prepareOperation(Unknown Source)
        at com.ibm.ws.wsat.service.impl.WebClientImpl$2.call(WebClientImpl.java:103)
        at com.ibm.ws.wsat.service.impl.WebClientImpl$9.run(WebClientImpl.java:223)
        at java.security.AccessController.doPrivileged(AccessController.java:738) (edited) 
```

**Steps to Reproduce**
 
Invoke any JAX-WS Web Service with the application deployed on a Liberty instance using both `wsAtomicTransaction-1.2` and `jaxrs-2.0` or `jaxrs-2.1`

**Expected behavior**
 
JAX-WS Web Service will be invoked without Conduit related SOAPFautExceptions. 

**Diagnostic information:**
 - OpenLiberty Version: `21.0.0.3`
 - server.xml configuration 
 ```
         <featureManager>
                <feature>jaxrs-2.0</feature>
                <feature>wsAtomicTransaction-1.2</feature>
        </featureManager>
```
or 

 ```
         <featureManager>
                <feature>jaxrs-2.1</feature>
                <feature>wsAtomicTransaction-1.2</feature>
        </featureManager>
```

**Comment by neuwerk** [comment]
The `wsAtomicTransactions-1.2` feature is pulling in the`jaxrs-2.x` features' Conduit code from CXF 3.x rather than from `jaxws-2.2`, which is what it should be using.

Until a fix is in place, the only work around would be to use `jaxws-2.2` and one of the `jaxrs-2.x` features, or `wsAtomicTransactions-1.2` without the `jaxrs-2.x` features (Note: This might not be possible to deploy with any other configuration depending on application's own dependencies). 

This also occurs when convenience features like `webProfile-x` features are deployed with `wsAtomicTransactions-1.2` (since webProfile depends on the jaxrs-2.x features).

**Comment by neuwerk** [comment]
#16849
