### ISSUE TITLE
Suppress FFDC if MessageDigest.clone not supported 

### ISSUE THREAD

**Issue by NottyCode** [OpenLiberty/open-liberty#16945]
**Describe the bug**
The BasicAuthCacheKeyProvider tries to use MessageDigest.clone which is optional. It falls back to MessageDigest.getInstance, but an FFDC is generated which isn't necessary because we just fall back to an alternative approach. The FFDC should be suppressed.

**Steps to Reproduce**
Run IBMJCEPlus which doesn't support MessageDigest.clone

**Expected behavior**
No FFDC

**Diagnostic information:**
 - OpenLiberty Version: any
 - Java Version: Java(TM) SE Runtime Environment (8.0.6.26 - pxa6480sr6fp26-20210216_01(SR6 FP26))
```
Stack Dump = java.lang.CloneNotSupportedException
	at java.security.MessageDigest$Delegate.clone(MessageDigest.java:595)
	at com.ibm.ws.security.authentication.internal.cache.keyproviders.BasicAuthCacheKeyProvider.getMessageDigest(BasicAuthCacheKeyProvider.java:199)
	at com.ibm.ws.security.authentication.internal.cache.keyproviders.BasicAuthCacheKeyProvider.getHashedPassword(BasicAuthCacheKeyProvider.java:213)
	at com.ibm.ws.security.authentication.internal.cache.keyproviders.BasicAuthCacheKeyProvider.createLookupKey(BasicAuthCacheKeyProvider.java:164)
	at com.ibm.ws.security.authentication.internal.AuthenticationServiceImpl.findSubjectByUseridAndPassword(AuthenticationServiceImpl.java:407)
	at com.ibm.ws.security.authentication.internal.AuthenticationServiceImpl.findSubjectInAuthCache(AuthenticationServiceImpl.java:343)
	at com.ibm.ws.security.authentication.internal.AuthenticationServiceImpl.authenticate(AuthenticationServiceImpl.java:208)
	at com.ibm.ws.webcontainer.security.internal.BasicAuthAuthenticator.basicAuthenticate(BasicAuthAuthenticator.java:126)
	at com.ibm.ws.webcontainer.security.internal.BasicAuthAuthenticator.handleBasicAuth(BasicAuthAuthenticator.java:117)
	at com.ibm.ws.webcontainer.security.internal.BasicAuthAuthenticator.authenticate(BasicAuthAuthenticator.java:70)
	at com.ibm.ws.webcontainer.security.WebAuthenticatorProxy.authenticate(WebAuthenticatorProxy.java:88)
	at com.ibm.ws.webcontainer.security.WebAppSecurityCollaboratorImpl.authenticateRequest(WebAppSecurityCollaboratorImpl.java:1233)
	at com.ibm.ws.webcontainer.security.WebAppSecurityCollaboratorImpl.determineWebReply(WebAppSecurityCollaboratorImpl.java:989)
	at com.ibm.ws.webcontainer.security.WebAppSecurityCollaboratorImpl.performSecurityChecks(WebAppSecurityCollaboratorImpl.java:678)
	at com.ibm.ws.webcontainer.security.WebAppSecurityCollaboratorImpl.preInvoke(WebAppSecurityCollaboratorImpl.java:596)
	at com.ibm.wsspi.webcontainer.collaborator.CollaboratorHelper.preInvokeCollaborators(CollaboratorHelper.java:459)
	at com.ibm.ws.webcontainer.osgi.collaborator.CollaboratorHelperImpl.preInvokeCollaborators(CollaboratorHelperImpl.java:270)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1114)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1010)
	at com.ibm.ws.webcontainer.servlet.CacheServletWrapper.handleRequest(CacheServletWrapper.java:75)
	at com.ibm.ws.webcontainer40.servlet.CacheServletWrapper40.handleRequest(CacheServletWrapper40.java:86)
	at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:937)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:279)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1146)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:427)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:386)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:566)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:500)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:360)
	at com.ibm.ws.http.channel.internal.inbound.HttpICLReadCallback.complete(HttpICLReadCallback.java:70)
	at com.ibm.ws.channel.ssl.internal.SSLReadServiceContext$SSLReadCompletedCallback.complete(SSLReadServiceContext.java:1824)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:504)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueManager.java:574)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:958)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:1047)
	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:238)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:822)```

**Comment by utle** [comment]
Fixed by Ignore FFDC CloneNotSupportedException #16949
