### ISSUE TITLE
MicroProfile Health check fails when server has an OSGi app (internal or external) or a WAR without any CDI beans

### ISSUE THREAD

**Issue by scottkurz** [OpenLiberty/open-liberty#17]
The common theme here is that the Health Check discovery can fail because of the presence of other deployed application modules that aren't themselves contributing Health Check beans.   These can be true application modules or internal, "system" app modules.  

In these cases, the health endpoint (e.g. [http://localhost:9080/health](http://localhost:9080/health)) will return a response status of **500**.

There are two main cases, with different response payloads (which will also include a stack trace):

In the one case, in which there is an OSGi application (external app or "system app") deployed contributing a web module, the error response looks like: 
```
java.lang.IllegalStateException: ClassLoader ID is null for application component com.ibm.ws.microprofile.metrics#com.ibm.ws.microprofile.metrics. Verify the application component is installed.
	at com.ibm.ws.microprofile.health.services.impl.AppModuleContextService.getContextClassLoaderIdentifier(AppModuleContextService.java:151)
	at com.ibm.ws.microprofile.health.services.impl.AppModuleContextService.createThreadContext(AppModuleContextService.java:169)
	at com.ibm.ws.microprofile.health.services.impl.AppModuleContextService.createContextualProxy(AppModuleContextService.java:195)
	at com.ibm.ws.microprofile.health.services.impl.HealthExecutorImpl.runHealthChecks(HealthExecutorImpl.java:69)
	at com.ibm.ws.microprofile.health.internal.HealthCheckServiceImpl.performHealthCheck(HealthCheckServiceImpl.java:107)
	at com.ibm.ws.microprofile.health.internal.servlet.HealthCheckServlet.service(HealthCheckServlet.java:53)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1255)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:743)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:440)
        ... stack trace continues ...
```

In the second case, in which there is a WAR module deployed, but one in which there are zero discovered CDI-managed beans, the exception in the response looks like:

```
javax.naming.NameNotFoundException: javax.naming.NameNotFoundException: java:comp/BeanManager
	at com.ibm.ws.jndi.url.contexts.javacolon.internal.JavaURLContext.lookup(JavaURLContext.java:355)
	at com.ibm.ws.jndi.url.contexts.javacolon.internal.JavaURLContext.lookup(JavaURLContext.java:370)
	at org.apache.aries.jndi.DelegateContext.lookup(DelegateContext.java:161)
	at javax.naming.InitialContext.lookup(InitialContext.java:428)
	at com.ibm.ws.microprofile.health.services.impl.HealthCheckCDIBeanInvokerImpl.getHealthCheckBeans(HealthCheckCDIBeanInvokerImpl.java:71)
	at com.ibm.ws.microprofile.health.services.impl.HealthCheckCDIBeanInvokerImpl.checkAllBeans(HealthCheckCDIBeanInvokerImpl.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at com.ibm.ws.context.service.serializable.ContextualInvocationHandler.invoke(ContextualInvocationHandler.java:76)
	at com.ibm.ws.context.service.serializable.ContextualInvocationHandler.invoke(ContextualInvocationHandler.java:97)
	at com.sun.proxy.$Proxy41.checkAllBeans(Unknown Source)
	at com.ibm.ws.microprofile.health.services.impl.HealthExecutorImpl.runHealthChecks(HealthExecutorImpl.java:72)
	at com.ibm.ws.microprofile.health.internal.HealthCheckServiceImpl.performHealthCheck(HealthCheckServiceImpl.java:107)
	at com.ibm.ws.microprofile.health.internal.servlet.HealthCheckServlet.service(HealthCheckServlet.java:53)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1255)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:743)
```

**Comment by scottkurz** [comment]
Resolved
