### ISSUE TITLE
Failed to run POST request by openapi/ui through Skills Network environment

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/open-liberty#17048]
To reproduce the problem:
- visit https://openliberty.skillsnetwork.site/quicklab/ol-masterclass-1
- login the Skills Network
- follow the following instructions instead of the lab instructions
  - open a new command-line session -> select  **Terminal** > **New Termina**l from the menu of the IDE and run: 
```
git clone https://github.com/OpenLiberty/open-liberty-masterclass.git
cd open-liberty-masterclass/finish/barista
mvn liberty:dev
```
  - Open another new command-line session -> select **Terminal** > **New Terminal** from the menu of the IDE and run:
```
cd open-liberty-masterclass/finish/coffee-shop
mvn liberty:dev
```
  - select **Launch Application** from the menu of the IDE, a box will appear where the port number is required. The application is running on port 9080. The Open Liberty homepage will load.
  - visit /openapi/ui similar to `https://accountname-9080.theiadocker-1.proxy.cognitiveclass.ai/openapi/ui`
  - try the POST request
  - will get 500 Error: Internal Server Error
```
connection: keep-alive  
content-language: en-US  
content-length: 0  date: Mon, 03 May 2021 17:28:22 GMT  
io.openliberty.microprofile.metrics.internal.monitor.metricsjaxrsemcallbackimpl.exception: java.lang.reflect.UndeclaredThrowableException  x-powered-by: Servlet/4.0 
the following error show on the coffee-shop command session
INFO] [WARNING ] CWPMI2005W: The MicroProfile Metrics exception mapper detected and is handling an unhandled exception from the JAX-RS application. 
[INFO]                                                                                                                java.lang.reflect.UndeclaredThrowableException
[INFO]  at com.sun.proxy.$Proxy89.getBaseUriBuilder(Unknown Source)
[INFO]  at com.sebastian_daschner.coffee_shop.boundary.OrdersResource.buildUri(OrdersResource.java:67)
[INFO]  at com.sebastian_daschner.coffee_shop.boundary.OrdersResource.orderCoffee(OrdersResource.java:63)
[INFO]  at com.sebastian_daschner.coffee_shop.boundary.OrdersResource$Proxy$_$$_WeldSubclass.orderCoffee$$super(Unknown Source)
[INFO]  at jdk.internal.reflect.GeneratedMethodAccessor901.invoke(Unknown Source)
[INFO]  at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[INFO]  at org.jboss.weld.interceptor.proxy.TerminalAroundInvokeInvocationContext.proceedInternal(TerminalAroundInvokeInvocationContext.java:51)
[INFO]  at [internal classes]
[INFO]  at com.sebastian_daschner.coffee_shop.boundary.OrdersResource$Proxy$_$$_WeldSubclass.orderCoffee(Unknown Source)
[INFO]  at jdk.internal.reflect.GeneratedMethodAccessor896.invoke(Unknown Source)
[INFO]  at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[INFO]  at com.ibm.ws.jaxrs20.cdi.component.JaxRsFactoryImplicitBeanCDICustomizer.serviceInvoke(JaxRsFactoryImplicitBeanCDICustomizer.java:342)
[INFO]  at [internal classes]
[INFO] Caused by: java.lang.reflect.InvocationTargetException
[INFO]  ... 18 more
[INFO] Caused by: java.lang.IllegalArgumentException: Illegal character in scheme name at index 5: https,http,http://localhost/coffee-shop/resources/
[INFO]  at java.base/java.net.URI.create(URI.java:883)
[INFO]  at org.apache.cxf.jaxrs.impl.UriInfoImpl.getBaseUri(UriInfoImpl.java:83)
[INFO]  ... 14 more
[INFO] Caused by: java.net.URISyntaxException: Illegal character in scheme name at index 5: https,http,http://localhost/coffee-shop/resources/
[INFO]  at java.base/java.net.URI$Parser.fail(URI.java:2913)
[INFO]  at java.base/java.net.URI$Parser.checkChars(URI.java:3084)
[INFO]  at java.base/java.net.URI$Parser.parse(URI.java:3110)
[INFO]  at java.base/java.net.URI.<init>(URI.java:600)
[INFO]  at java.base/java.net.URI.create(URI.java:881)
[INFO]  ... 15 more
```

**Comment by gkwan-ibm** [comment]
traces:
[jaxrs-traces.log.zip](https://github.com/OpenLiberty/open-liberty/files/6422928/jaxrs-traces.log.zip)
[webcontainer-traces.log.zip](https://github.com/OpenLiberty/open-liberty/files/6422929/webcontainer-traces.log.zip)

**Comment by gkwan-ibm** [comment]
We can open issue to SN network if it need to fix something.

**Comment by gkwan-ibm** [comment]
The problem is starting from SN. `https://accountname-9080.theiadocker-1.proxy.cognitiveclass.ai/openapi/ui` starts by `https`, it forwards to `http://localhost:9080/...`, and the `orderCoffee` endpoint use `uriInfo` to construct an URI to call another endpoint. That  produced the scheme to be `https,http,http` and exception.

Phu gave us a workaround by setting `<webContainer trusted="false"/>` to the coffee-shop server.xml.

@pmd1nh @andymc12 you can keep this issue to fix the code to throw 400 instead of 500 error. Or, you can close this issue.

Thanks
