### ISSUE TITLE
OL wssecurity CXF SAML/SAML.2 FAT with EE8 and Java11 failed with feature conflict

### ISSUE THREAD

**Issue by meiaus** [OpenLiberty/open-liberty#17097]
Running wsscxf.saml and wsscxf.saml.2 FAT with EE8 wssecurity latest runtime (including April 29 commits) either with Java11 or Java8, the EE8 tests all failed with the same error related to feature conflict.  
Below logs are from one of the tests as an example:

- messages.log
```
********************************************************************************
product = Open Liberty 21.0.0.5 (wlp-1.0.52.202104301748)
wlp.install.dir = C:/Users/Administrator/libertyGit/open-liberty/dev/build.image/wlp/
java.home = C:\jdk-11.0.11.9-openj9
java.version = 11.0.11
java.runtime = OpenJDK Runtime Environment (11.0.11+9)
os = Windows Server 2016 (10.0; amd64) (en_US)
process = 16428@ventails1
********************************************************************************
[5/7/21, 20:11:21:789 PDT] 00000001 com.ibm.ws.logging.internal.TraceSpecification               I TRAS0018I: The trace state has been changed. The new trace state is #com.ibm.oauth.*=all:#com.ibm.ws.security.common*=all:#com.ibm.ws.security.saml*=all:#org.apache.ws.security.*=all:*=info:com.ibm.ws.security.*=all:com.ibm.ws.webcontainer.*=all:com.ibm.ws.wssecurity.*=all:com.ibm.wsspi.security.oauth20.*=all:org.apache.cxf.*=all:org.apache.xml.security.*=all.
[5/7/21, 20:11:21:908 PDT] 00000001 com.ibm.ws.kernel.launch.internal.FrameworkManager           A CWWKE0001I: The server com.ibm.ws.wssecurity_fat.saml.2servers has been launched.
[5/7/21, 20:11:47:046 PDT] 00000001 com.ibm.ws.kernel.launch.internal.FrameworkManager           I CWWKE0002I: The kernel started after 30.214 seconds
[5/7/21, 20:11:47:605 PDT] 00000088 com.ibm.ws.kernel.feature.internal.FeatureManager            I CWWKF0007I: Feature update started.
[5/7/21, 20:11:48:511 PDT] 00000088 com.ibm.ws.kernel.feature.internal.FeatureManager            E CWWKF0033E: The singleton features com.ibm.websphere.appserver.jta-1.1 and com.ibm.websphere.appserver.jta-1.2 cannot be loaded at the same time.  The configured features wsSecuritySaml-1.1 and appSecurity-3.0 include one or more features that cause the conflict. Your configuration is not supported; update server.xml to remove incompatible features.
[5/7/21, 20:11:48:535 PDT] 00000088 com.ibm.ws.logging.internal.impl.IncidentImpl                I FFDC1015I: An FFDC Incident has been created: "java.lang.IllegalArgumentException: Unable to load conflicting versions of features "com.ibm.websphere.appserver.jta-1.1" and "com.ibm.websphere.appserver.jta-1.2".  The feature dependency chains that led to the conflict are: com.ibm.websphere.appserver.wsSecuritySaml-1.1 -> com.ibm.websphere.appserver.wsSecurity-1.1 -> com.ibm.websphere.appserver.jta-1.1 and com.ibm.websphere.appserver.appSecurity-3.0 -> com.ibm.websphere.appserver.cdi-2.0 -> com.ibm.websphere.appserver.transaction-1.2 -> com.ibm.websphere.appserver.jta-1.2 com.ibm.ws.kernel.feature.internal.FeatureManager reportErrors" at ffdc_21.05.07_20.11.48.0.log
[5/7/21, 20:11:48:546 PDT] 00000088 com.ibm.ws.kernel.feature.internal.FeatureManager            E CWWKF0033E: The singleton features com.ibm.websphere.appserver.samlWeb2.0.internal.opensaml-2.6 and com.ibm.websphere.appserver.samlWeb2.0.internal.opensaml-3.4 cannot be loaded at the same time.  The configured features samlWeb-2.0 and com.ibm.websphere.appserver.wsSecuritySaml1.1-jaxws2.3 include one or more features that cause the conflict. Your configuration is not supported; update server.xml to remove incompatible features.
[5/7/21, 20:11:48:566 PDT] 00000088 com.ibm.ws.logging.internal.impl.IncidentImpl                I FFDC1015I: An FFDC Incident has been created: "java.lang.IllegalArgumentException: Unable to load conflicting versions of features "com.ibm.websphere.appserver.samlWeb2.0.internal.opensaml-2.6" and "com.ibm.websphere.appserver.samlWeb2.0.internal.opensaml-3.4".  The feature dependency chains that led to the conflict are: com.ibm.websphere.appserver.samlWeb-2.0 -> io.openliberty.samlWeb2.0.internal.ee-6.0 -> com.ibm.websphere.appserver.samlWeb2.0.internal.opensaml-2.6 and com.ibm.websphere.appserver.wsSecuritySaml1.1-jaxws2.3 -> com.ibm.websphere.appserver.samlWeb2.0.internal.opensaml-3.4 com.ibm.ws.kernel.feature.internal.FeatureManager reportErrors" at ffdc_21.05.07_20.11.48.1.log
[5/7/21, 20:11:48:574 PDT] 00000088 com.ibm.ws.kernel.feature.internal.FeatureManager            E CWWKF0033E: The singleton features com.ibm.websphere.appserver.wss4j-1.0 and com.ibm.websphere.appserver.wss4j-2.3 cannot be loaded at the same time.  The configured features samlWeb-2.0 and com.ibm.websphere.appserver.wsSecurity1.1-jaxws2.3 include one or more features that cause the conflict. Your configuration is not supported; update server.xml to remove incompatible features.
[5/7/21, 20:11:48:587 PDT] 00000088 com.ibm.ws.logging.internal.impl.IncidentImpl                I FFDC1015I: An FFDC Incident has been created: "java.lang.IllegalArgumentException: Unable to load conflicting versions of features "com.ibm.websphere.appserver.wss4j-1.0" and "com.ibm.websphere.appserver.wss4j-2.3".  The feature dependency chains that led to the conflict are: com.ibm.websphere.appserver.samlWeb-2.0 -> io.openliberty.samlWeb2.0.internal.ee-6.0 -> com.ibm.websphere.appserver.samlWeb2.0.internal.opensaml-2.6 -> com.ibm.websphere.appserver.wss4j-1.0 and com.ibm.websphere.appserver.wsSecurity1.1-jaxws2.3 -> com.ibm.websphere.appserver.wsSecurity1.1.internal.jaxws-2.3 -> com.ibm.websphere.appserver.wss4j-2.3 com.ibm.ws.kernel.feature.internal.FeatureManager reportErrors" at ffdc_21.05.07_20.11.48.2.log
[5/7/21, 20:11:48:593 PDT] 00000088 com.ibm.ws.kernel.feature.internal.FeatureManager            W CWWKF0046W: The configuration includes an incompatible combination of features. As a result, the feature manager did not install any features.
[5/7/21, 20:11:48:738 PDT] 00000088 com.ibm.ws.kernel.feature.internal.FeatureManager            I CWWKF0008I: Feature update completed in 1.703 seconds.
[5/7/21, 20:11:48:739 PDT] 00000088 com.ibm.ws.kernel.feature.internal.FeatureManager            A CWWKF0011I: The com.ibm.ws.wssecurity_fat.saml.2servers server is ready to run a smarter planet. The com.ibm.ws.wssecurity_fat.saml.2servers server started in 31.913 seconds.
[5/7/21, 20:12:32:351 PDT] 0000006f com.ibm.ws.kernel.launch.internal.ServerCommandListener      A CWWKE0055I: Server shutdown requested on Friday, May 7, 2021 at 8:12 PM. The server com.ibm.ws.wssecurity_fat.saml.2servers is shutting down.
[5/7/21, 20:12:32:369 PDT] 000000b9 com.ibm.ws.runtime.update.internal.RuntimeUpdateManagerImpl  A CWWKE1100I: Waiting for up to 30 seconds for the server to quiesce.
[5/7/21, 20:12:32:383 PDT] 000000b9 com.ibm.ws.runtime.update.internal.RuntimeUpdateManagerImpl  I CWWKE1101I: Server quiesce complete.
[5/7/21, 20:12:32:522 PDT] 00000001 com.ibm.ws.kernel.launch.internal.FrameworkManager           A CWWKE0036I: The server com.ibm.ws.wssecurity_fat.saml.2servers stopped after 1 minutes, 15.695 seconds.

```
- ffdc
```
- ------Start of DE processing------ = [5/7/21, 20:11:48:522 PDT]
Exception = java.lang.IllegalArgumentException
Source = com.ibm.ws.kernel.feature.internal.FeatureManager
probeid = reportErrors
Stack Dump = java.lang.IllegalArgumentException: Unable to load conflicting versions of features "com.ibm.websphere.appserver.jta-1.1" and "com.ibm.websphere.appserver.jta-1.2".  The feature dependency chains that led to the conflict are: com.ibm.websphere.appserver.wsSecuritySaml-1.1 -> com.ibm.websphere.appserver.wsSecurity-1.1 -> com.ibm.websphere.appserver.jta-1.1 and com.ibm.websphere.appserver.appSecurity-3.0 -> com.ibm.websphere.appserver.cdi-2.0 -> com.ibm.websphere.appserver.transaction-1.2 -> com.ibm.websphere.appserver.jta-1.2
	at com.ibm.ws.kernel.feature.internal.FeatureManager.reportErrors(FeatureManager.java:1864)
	at com.ibm.ws.kernel.feature.internal.FeatureManager.updateFeatures(FeatureManager.java:1390)
	at com.ibm.ws.kernel.feature.internal.FeatureManager.update(FeatureManager.java:749)
	at com.ibm.ws.kernel.feature.internal.FeatureManager.processFeatureChanges(FeatureManager.java:863)
	at com.ibm.ws.kernel.feature.internal.FeatureManager$1.run(FeatureManager.java:649)
	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:238)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:836)

```
- ffdc
```
------Start of DE processing------ = [5/7/21, 20:11:48:556 PDT]
Exception = java.lang.IllegalArgumentException
Source = com.ibm.ws.kernel.feature.internal.FeatureManager
probeid = reportErrors
Stack Dump = java.lang.IllegalArgumentException: Unable to load conflicting versions of features "com.ibm.websphere.appserver.samlWeb2.0.internal.opensaml-2.6" and "com.ibm.websphere.appserver.samlWeb2.0.internal.opensaml-3.4".  The feature dependency chains that led to the conflict are: com.ibm.websphere.appserver.samlWeb-2.0 -> io.openliberty.samlWeb2.0.internal.ee-6.0 -> com.ibm.websphere.appserver.samlWeb2.0.internal.opensaml-2.6 and com.ibm.websphere.appserver.wsSecuritySaml1.1-jaxws2.3 -> com.ibm.websphere.appserver.samlWeb2.0.internal.opensaml-3.4
	at com.ibm.ws.kernel.feature.internal.FeatureManager.reportErrors(FeatureManager.java:1864)
	at com.ibm.ws.kernel.feature.internal.FeatureManager.updateFeatures(FeatureManager.java:1390)
	at com.ibm.ws.kernel.feature.internal.FeatureManager.update(FeatureManager.java:749)
	at com.ibm.ws.kernel.feature.internal.FeatureManager.processFeatureChanges(FeatureManager.java:863)
	at com.ibm.ws.kernel.feature.internal.FeatureManager$1.run(FeatureManager.java:649)
	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:238)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:836)

```
- ffdc
```
------Start of DE processing------ = [5/7/21, 20:11:48:578 PDT]
Exception = java.lang.IllegalArgumentException
Source = com.ibm.ws.kernel.feature.internal.FeatureManager
probeid = reportErrors
Stack Dump = java.lang.IllegalArgumentException: Unable to load conflicting versions of features "com.ibm.websphere.appserver.wss4j-1.0" and "com.ibm.websphere.appserver.wss4j-2.3".  The feature dependency chains that led to the conflict are: com.ibm.websphere.appserver.samlWeb-2.0 -> io.openliberty.samlWeb2.0.internal.ee-6.0 -> com.ibm.websphere.appserver.samlWeb2.0.internal.opensaml-2.6 -> com.ibm.websphere.appserver.wss4j-1.0 and com.ibm.websphere.appserver.wsSecurity1.1-jaxws2.3 -> com.ibm.websphere.appserver.wsSecurity1.1.internal.jaxws-2.3 -> com.ibm.websphere.appserver.wss4j-2.3
	at com.ibm.ws.kernel.feature.internal.FeatureManager.reportErrors(FeatureManager.java:1864)
	at com.ibm.ws.kernel.feature.internal.FeatureManager.updateFeatures(FeatureManager.java:1390)
	at com.ibm.ws.kernel.feature.internal.FeatureManager.update(FeatureManager.java:749)
	at com.ibm.ws.kernel.feature.internal.FeatureManager.processFeatureChanges(FeatureManager.java:863)
	at com.ibm.ws.kernel.feature.internal.FeatureManager$1.run(FeatureManager.java:649)
	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:238)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:836)

```

**Comment by meiaus** [comment]
@arunavemulapalli

**Comment by jhanders34** [comment]
Are these runs with the commits in PR #16725?  Those changes have not been merged yet.  I am still doing review for them and have concerns about the feature file changes.

**Comment by arunavemulapalli** [comment]
@jhanders34  , Yes.  Mei-hsiang is trying to run the updated tests with the commits from the mentioned PR to make progress with the FAT changes.  I am going to close this issue and we need to track Mei-hsiang's work with some other mechanism.
