### ISSUE TITLE
NPE hitting ibm/api/config endpoint with  <application-bnd> in server config

### ISSUE THREAD

**Issue by scottkurz** [OpenLiberty/open-liberty#17252]
**Describe the bug**

I get NullPointerException when hitting the endpoint:  **https://localhost:9443/ibm/api/config**

```text
Caused by: java.lang.NullPointerException
	at com.ibm.ws.config.xml.internal.MetaTypeRegistry.getAttributeCardinality(MetaTypeRegistry.java:1292)
	at com.ibm.ws.config.xml.internal.WSConfigurationHelperImpl.getMetaTypeAttributeCardinality(WSConfigurationHelperImpl.java:152)
	at com.ibm.ws.rest.handler.config.internal.ConfigRESTHandler.getConfigInfo(ConfigRESTHandler.java:266)
	at com.ibm.ws.rest.handler.config.internal.ConfigRESTHandler.handleSingleInstance(ConfigRESTHandler.java:444)
	at com.ibm.wsspi.rest.config.ConfigBasedRESTHandler.handleRequest(ConfigBasedRESTHandler.java:305)
	at com.ibm.ws.rest.handler.config.internal.ConfigRESTHandler.handleRequest(ConfigRESTHandler.java:538)
	at com.ibm.ws.rest.handler.internal.service.RESTHandlerContainerImpl.handleRequest(RESTHandlerContainerImpl.java:463)
	at com.ibm.ws.rest.handler.internal.servlet.RESTProxyServlet.handleWithDelegate(RESTProxyServlet.java:119)
	at com.ibm.ws.rest.handler.internal.servlet.RESTProxyServlet.service(RESTProxyServlet.java:64)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:791)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1258)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:746)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:443)
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.invokeTarget(WebAppFilterChain.java:183)
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:94)
	at com.ibm.ws.app.manager.wab.internal.OsgiDirectoryProtectionFilter.doFilter(OsgiDirectoryProtectionFilter.java:90)
	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:201)
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:91)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.doFilter(WebAppFilterManager.java:1002)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1140)
	at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:5061)
	... 15 more
```

From using the debugger, I noticed the problem seems to revolve around a config like the  "<application-bnd>" in the server.xml like: 

```xml
    <application id="batch-bonuspayout-application" location="batch-bonuspayout-application.war" name="batch-bonuspayout-application" type="war"/>
        <application-bnd>
            <security-role name="JOBSTARTER">
                <user name="sammy" />
                <run-as userid="sammy" password="sammypwd"/>
            </security-role>
        </application-bnd>
    </application>
```

as the `attributeID` value equals "application-bnd" at the time the NPE occurs.

**Steps to Reproduce**

If the above is enough to easily recreate, then the setup I used is too complicated.   If not let me know, and I can help with more detail.

Note that when I commented out the "application-bnd" the problem went away.

**Expected behavior**

Normally this endpoint shows a full config listing.   It did seem to me that when I narrowed down the config endpoint by passing query parms that things still worked successfully, e.g. to view a specific DS.

**Diagnostic information:**
 - OpenLiberty Version: 21.0.0.5
 - Java Version: [i.e. full output of `java -version`]
java version "11.0.6" 2020-01-14 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.6+8-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.6+8-LTS, mixed mode)
 - server.xml configuration (WITHOUT sensitive information like passwords):  see above
 - If it would be useful, upload the messages.log file found in `$WLP_OUTPUT_DIR/messages.log`

**Additional context**

**Comment by scottkurz** [comment]
@nmittles  just sending you an FYI since I think you worked on the REST endpoint.. though maybe if this is the config layer underneath it has nothing to do with that?
