### ISSUE TITLE
Test Failure: com.ibm.ws.microprofile.opentracing.jaeger_fat.JaegerConfigTest.testTraceCreated

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#17273]
RTC 283901

```
testTraceCreated:java.io.IOException: Server returned HTTP response code: 500 for URL: http://localhost:8010/mpOpenTracing/rest/ws/helloWorld
at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1919)
at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1515)
at com.ibm.ws.microprofile.opentracing.jaeger_fat.FATUtilsServer.gatherHttpRequest(FATUtilsServer.java:78)
at com.ibm.ws.microprofile.opentracing.jaeger_fat.JaegerConfigTest.executeWebService(JaegerConfigTest.java:160)
at com.ibm.ws.microprofile.opentracing.jaeger_fat.JaegerConfigTest.testTraceCreated(JaegerConfigTest.java:106)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```

**Comment by fmhwong** [comment]
This failed on Java 2 security builds and I found this in messages.log.

```
[WARNING ] CWMOT0010W: OpenTracing cannot track JAX-RS requests because an OpentracingTracerFactory class was not provided or client libraries for tracing backend are not in the class path.

```
