### ISSUE TITLE
Update PackageLooseContentTest.testUsr to skip on z/OS

### ISSUE THREAD

**Issue by hlhoots** [OpenLiberty/open-liberty#17286]
Error:
/WebSphere/Misc/jazz_build/jbe_zrock048/jazz/buildsystem/buildengine/eclipse/build/dev/image/output/wlp/usr/servers/com.ibm.ws.kernel.boot.loose.config.fat/com.ibm.ws.kernel.boot.loose.config.fat.zip (EDC5129I No such file or directory.)

java.io.FileNotFoundException: /WebSphere/Misc/jazz_build/jbe_zrock048/jazz/buildsystem/buildengine/eclipse/build/dev/image/output/wlp/usr/servers/com.ibm.ws.kernel.boot.loose.config.fat/com.ibm.ws.kernel.boot.loose.config.fat.zip (EDC5129I No such file or directory.)
at java.util.zip.ZipFile.open(Native Method)
at java.util.zip.ZipFile.<init>(ZipFile.java:241)
at java.util.zip.ZipFile.<init>(ZipFile.java:171)
at java.util.zip.ZipFile.<init>(ZipFile.java:142)
at com.ibm.ws.kernel.boot.internal.commands.AbstractLooseConfigTest.verifyContents(AbstractLooseConfigTest.java:225)
at com.ibm.ws.kernel.boot.internal.commands.PackageLooseContentsTest.verifyContents(PackageLooseContentsTest.java:144)
at com.ibm.ws.kernel.boot.internal.commands.PackageLooseContentsTest.testUsr(PackageLooseContentsTest.java:131)

Resolution:
Update PackageLooseContentTest.testUsr to skip on z/OS with an assertTrue vs using the @SkipIfSysProp annotation.  The skip code needs to run with @RunWith(FATRunner.java) else the annotation is ignored.

**Comment by hlhoots** [comment]
Should be resolved by https://github.com/OpenLiberty/open-liberty/pull/17212

**Comment by hlhoots** [comment]
Previous fix did not work because the @SkipIfSysProp only runs with  @RunWith(FATRunner.java).  Since this test uses @RunWith(Parameterized.class) it needs to be just be skipped with an assumeTrue.
