### ISSUE TITLE
NPE occurs during trace of ManagedExecutorServiceImpl

### ISSUE THREAD

**Issue by frowe** [OpenLiberty/open-liberty#17351]
In slack thread https://ibm-cloud.slack.com/archives/C30NGTBFS/p1622042314179900, an IBM cloud customer posted a stack trace from an issue he was having with some Db2 config and the Db2 cloud service.  The stack trace showed an NPE in ManagedExecutorServiceImpl. toString(), which appears to need null checks for either the name and hashcode fields:

```
CWWKE0701E: bundle com.ibm.ws.concurrent:1.0.47.cl201220201111-0736 (184)[com.ibm.ws.concurrent.internal.ManagedExecutorServiceImpl(416)] : Error during instantiation of the implementation object java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:83)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:57)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:437)
	at org.apache.felix.scr.impl.inject.internal.ComponentConstructorImpl.newInstance(ComponentConstructorImpl.java:312)
	at org.apache.felix.scr.impl.manager.SingleComponentManager.createImplementationObject(SingleComponentManager.java:286)
	at org.apache.felix.scr.impl.manager.SingleComponentManager.createComponent(SingleComponentManager.java:115)
	at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:1000)
	at org.apache.felix.scr.impl.manager.SingleComponentManager.getServiceInternal(SingleComponentManager.java:973)
	at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:918)
	at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse$1.run(ServiceFactoryUse.java:216)
	at java.security.AccessController.doPrivileged(AccessController.java:678)
	at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.factoryGetService(ServiceFactoryUse.java:213)
	at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.getService(ServiceFactoryUse.java:114)
	at org.eclipse.osgi.internal.serviceregistry.ServiceConsumer$2.getService(ServiceConsumer.java:48)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.getService(ServiceRegistrationImpl.java:530)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.getService(ServiceRegistry.java:494)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.getService(BundleContextImpl.java:685)
	at org.apache.felix.scr.impl.manager.SingleRefPair.getServiceObject(SingleRefPair.java:88)
	at org.apache.felix.scr.impl.inject.methods.BindMethod.getServiceObject(BindMethod.java:675)
	at org.apache.felix.scr.impl.manager.DependencyManager.getServiceObject(DependencyManager.java:2545)
	at org.apache.felix.scr.impl.manager.DependencyManager.doInvokeBindMethod(DependencyManager.java:2064)
	at org.apache.felix.scr.impl.manager.DependencyManager.invokeBindMethod(DependencyManager.java:2047)
	at org.apache.felix.scr.impl.manager.SingleComponentManager.invokeBindMethod(SingleComponentManager.java:443)
	at org.apache.felix.scr.impl.manager.DependencyManager$MultipleDynamicCustomizer.addedService(DependencyManager.java:333)
	at org.apache.felix.scr.impl.manager.DependencyManager$MultipleDynamicCustomizer.addedService(DependencyManager.java:301)
	at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.customizerAdded(ServiceTracker.java:1200)
	at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.customizerAdded(ServiceTracker.java:1121)
	at org.apache.felix.scr.impl.manager.ServiceTracker$AbstractTracked.trackAdding(ServiceTracker.java:928)
	at org.apache.felix.scr.impl.manager.ServiceTracker$AbstractTracked.track(ServiceTracker.java:864)
	at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:1152)
	at org.apache.felix.scr.impl.BundleComponentActivator$ListenerInfo.serviceChanged(BundleComponentActivator.java:114)
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:113)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:985)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:896)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:834)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:258)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:525)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager$3.register(AbstractComponentManager.java:929)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager$3.register(AbstractComponentManager.java:915)
	at org.apache.felix.scr.impl.manager.RegistrationManager.changeRegistration(RegistrationManager.java:133)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.registerService(AbstractComponentManager.java:984)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.activateInternal(AbstractComponentManager.java:752)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.enableInternal(AbstractComponentManager.java:674)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.enable(AbstractComponentManager.java:437)
	at org.apache.felix.scr.impl.manager.ConfigurableComponentHolder.enableComponents(ConfigurableComponentHolder.java:667)
	at org.apache.felix.scr.impl.BundleComponentActivator.initialEnable(BundleComponentActivator.java:305)
	at org.apache.felix.scr.impl.Activator.loadComponents(Activator.java:554)
	at org.apache.felix.scr.impl.Activator.access$200(Activator.java:70)
	at org.apache.felix.scr.impl.Activator$ScrExtension.start(Activator.java:421)
	at org.apache.felix.scr.impl.AbstractExtender.createExtension(AbstractExtender.java:196)
	at org.apache.felix.scr.impl.AbstractExtender.modifiedBundle(AbstractExtender.java:169)
	at org.apache.felix.scr.impl.AbstractExtender.modifiedBundle(AbstractExtender.java:49)
	at org.osgi.util.tracker.BundleTracker$Tracked.customizerModified(BundleTracker.java:488)
	at org.osgi.util.tracker.BundleTracker$Tracked.customizerModified(BundleTracker.java:1)
	at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:232)
	at org.osgi.util.tracker.BundleTracker$Tracked.bundleChanged(BundleTracker.java:450)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:973)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEventPrivileged(EquinoxEventPublisher.java:235)
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:141)
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:133)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor.publishModuleEvent(EquinoxContainerAdaptor.java:217)
	at org.eclipse.osgi.container.Module.publishEvent(Module.java:498)
	at org.eclipse.osgi.container.Module.start(Module.java:485)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1844)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:820)
Caused by: java.lang.NullPointerException
	at com.ibm.ws.concurrent.internal.ManagedExecutorServiceImpl.toString(ManagedExecutorServiceImpl.java:774)
	at com.ibm.ws.logging.hpel.impl.BinaryLogRecordSerializerVersion2Impl.writeParam(BinaryLogRecordSerializerVersion2Impl.java:781)
	at com.ibm.ws.logging.hpel.impl.BinaryLogRecordSerializerVersion2Impl.serialize(BinaryLogRecordSerializerVersion2Impl.java:311)
	at com.ibm.ws.logging.hpel.handlers.LogRecordHandler$SerializationBuffer.serialize(LogRecordHandler.java:190)
	at com.ibm.ws.logging.hpel.handlers.LogRecordHandler.processEvent(LogRecordHandler.java:95)
	at com.ibm.ws.logging.hpel.handlers.LogRecordHandler.publish(LogRecordHandler.java:236)
	at com.ibm.ws.logging.internal.hpel.HpelTraceServiceWriter$NoCloseLogRecordHandler.publish(HpelTraceServiceWriter.java:305)
	at com.ibm.ws.logging.internal.hpel.HpelTraceServiceWriter.repositoryPublish(HpelTraceServiceWriter.java:283)
	at com.ibm.ws.logging.internal.hpel.HpelBaseTraceService.publishTraceLogRecord(HpelBaseTraceService.java:131)
	at com.ibm.ws.logging.internal.impl.BaseTraceService.entry(BaseTraceService.java:745)
	at com.ibm.websphere.ras.Tr.entry(Tr.java:483)
	at com.ibm.ws.concurrent.internal.ManagedExecutorServiceImpl$2.<init>(ManagedExecutorServiceImpl.java:132)
	at com.ibm.ws.concurrent.internal.ManagedExecutorServiceImpl.<init>(ManagedExecutorServiceImpl.java:132)
	... 73 more
  ,formattedMsg=CWWKE0701E: bundle com.ibm.ws.concurrent:1.0.47.cl201220201111-0736 (184)[com.ibm.ws.concurrent.internal.ManagedExecutorServiceImpl(416)] : Error during instantiation of the implementation object java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:83)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:57)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:437)
	at org.apache.felix.scr.impl.inject.internal.ComponentConstructorImpl.newInstance(ComponentConstructorImpl.java:312)
	at [internal classes]
Caused by: java.lang.NullPointerException
	at com.ibm.ws.concurrent.internal.ManagedExecutorServiceImpl.toString(ManagedExecutorServiceImpl.java:774)
	at [internal classes]
	at com.ibm.ws.logging.hpel.impl.BinaryLogRecordSerializerVersion2Impl.writeParam(BinaryLogRecordSerializerVersion2Impl.java:781)
	at com.ibm.ws.logging.hpel.impl.BinaryLogRecordSerializerVersion2Impl.serialize(BinaryLogRecordSerializerVersion2Impl.java:311)
	at com.ibm.ws.logging.hpel.handlers.LogRecordHandler$SerializationBuffer.serialize(LogRecordHandler.java:190)
	at com.ibm.ws.logging.hpel.handlers.LogRecordHandler.processEvent(LogRecordHandler.java:95)
	at com.ibm.ws.logging.hpel.handlers.LogRecordHandler.publish(LogRecordHandler.java:236)
	at com.ibm.ws.logging.internal.hpel.HpelTraceServiceWriter$NoCloseLogRecordHandler.publish(HpelTraceServiceWriter.java:305)
	at com.ibm.ws.logging.internal.hpel.HpelTraceServiceWriter.repositoryPublish(HpelTraceServiceWriter.java:283)
	at com.ibm.ws.logging.internal.hpel.HpelBaseTraceService.publishTraceLogRecord(HpelBaseTraceService.java:131)
	at com.ibm.ws.logging.internal.impl.BaseTraceService.entry(BaseTraceService.java:745)
	at com.ibm.websphere.ras.Tr.entry(Tr.java:483)
	... 1 more
```

**Comment by njr-11** [comment]
This occurs on the OSGi path because on that path the `name` field isn't populated until activate, but some bytecode injected trace of an inner class that initializes a class level field runs before the activate, causing the NullPointerException when toString tries to access the name assuming that it doesn't contain a null.  This reproduces when running the main concurrent_fat bucket which runs with concurrent=all trace enabled.  It appears in the trace log but doesn't impact function at all so the test bucket runs cleanly despite the NullPointerException on the trace path.
