### ISSUE TITLE
HttpSessionCache does not work with hazelcast 4.x

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/open-liberty#17357]
**Describe the bug**
Got following exception when use Hazelcast 4.2
```
[INFO] [ERROR   ] CWWKM1002E: The XML file in /Users/gkwan/tasks/CNAI/guides/testsite/sessions/version-update/guide-sessions/finish/target/liberty/wlp/usr/servers/defaultServer/hazelcast.xml could not be read.
[INFO] [ERROR   ] CWWKM1002E: The XML file in /Users/gkwan/tasks/CNAI/guides/testsite/sessions/version-update/guide-sessions/finish/target/liberty/wlp/usr/servers/defaultServer/server.xml could not be read.
[INFO] [ERROR   ] SESN0309E: The jCacheVendorLib session cache library is empty. Verify that the server configuration contains a valid httpSessionCache configuration. See the sample configuration. 
[INFO] 
[INFO]     <httpSessionCache libraryRef="JCacheLib"/>
[INFO] 
[INFO]    <library id="JCacheLib">
[INFO]         <file name="${shared.resource.dir}/jcache/JCacheProvider.jar"/>
[INFO]     </library>
[INFO] 
[INFO] [ERROR   ] SESN0307E: An exception occurred when initializing the cache. The exception is: javax.cache.CacheException: No CachingProviders have been configured
[INFO] 	at javax.cache.Caching$CachingProviderRegistry.getCachingProvider(Caching.java:391)
[INFO] 	at javax.cache.Caching.getCachingProvider(Caching.java:169)
[INFO] 	at com.ibm.ws.session.store.cache.CacheStoreService.lambda$activateLazily$0(CacheStoreService.java:211)
[INFO] 	at [internal classes]
[INFO] .
[INFO] [ERROR   ] SRVE8059E: An unexpected exception occurred when trying to retrieve the session context
[INFO] Internal Server Error
```

**Steps to Reproduce**
- `git clone https://github.com/openliberty/guide-sessions.git -b version-update`
- `cd  /guide-sessions/finish`
- `mvn liberty:dev`
- will see the above error

**Expected behavior**
- No error and the application can run
- can run the apis at http://localhost:9080/openapi/ui/

**Diagnostic information:**
 - OpenLiberty Version: 21.0.0.5
 - Java Version: Java version: 11.0.9, vendor: AdoptOpenJDK,
 - server.xml configuration: https://raw.githubusercontent.com/OpenLiberty/guide-sessions/version-update/finish/src/main/liberty/config/server.xml
 - If it would be useful, upload the messages.log file found in `$WLP_OUTPUT_DIR/messages.log`
[messages.log](https://github.com/OpenLiberty/open-liberty/files/6577205/messages.log)

**Additional context**
- https://github.com/hazelcast/hazelcast-reference-manual/blob/master/src/docs/asciidoc/migration_guides.adoc

**Comment by gkwan-ibm** [comment]
close
- the [Caching HTTP session data using JCache and Hazelcast](https://openliberty.io/guides/sessions.html) guide and OL can work well with hazelcast 5.x
