### ISSUE TITLE
JAX-RS 2.1 TCK com/sun/ts/tests/jaxrs/api/rs/core/linkjaxbadapter/JAXRSClient falures

### ISSUE THREAD

**Issue by jkoehler22** [OpenLiberty/open-liberty#1751]

**Comment by jkoehler22** [comment]
Incorrect Output Failure 1: jaxrs/api/rs/core/linkjaxbadapter/JAXRSClient_unmarshallTest_from_servlet

01-23-2018 10:33:21:  SVR-TRACE: ABOUT TO INVOKE EETEST RUN METHOD!
01-23-2018 10:33:21:  SVR-ERROR: Marshalled Link <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<model>
    <link href="some:///" type="application/svg+xml" name2="val2" title="XTitleX" name1="val1" rel="Relation"/>
</model>
  does not contain expected uri reference some://where.at:port/
01-23-2018 10:33:21:  SVR-ERROR: Test case throws exception: Marshalled Link <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<model>
    <link href="some:///" type="application/svg+xml" name2="val2" title="XTitleX" name1="val1" rel="Relation"/>
</model>
  does not contain expected uri reference some://where.at:port/
01-23-2018 10:33:21:  SVR-ERROR: Exception at:
01-23-2018 10:33:21:  SVR-ERROR: com.sun.ts.lib.harness.EETest$Fault: Marshalled Link <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<model>
    <link href="some:///" type="application/svg+xml" name2="val2" title="XTitleX" name1="val1" rel="Relation"/>
</model>
  does not contain expected uri reference some://where.at:port/
        at com.sun.ts.tests.jaxrs.common.JAXRSCommonClient.fault(JAXRSCommonClient.java:730)
        at com.sun.ts.tests.jaxrs.common.JAXRSCommonClient.assertTrue(JAXRSCommonClient.java:625)
        at com.sun.ts.tests.jaxrs.common.JAXRSCommonClient.assertContains(JAXRSCommonClient.java:747)
        at com.sun.ts.tests.jaxrs.api.rs.core.linkjaxbadapter.JAXRSClient.marshallTest(JAXRSClient.java:74)
        at com.sun.ts.tests.jaxrs.api.rs.core.linkjaxbadapter.JAXRSClient.unmarshallTest(JAXRSClient.java:108)

**Comment by jkoehler22** [comment]
Incorrect Output Failure 2: jaxrs/api/rs/core/linkjaxbadapter/JAXRSClient_marshallTest_from_servlet

01-23-2018 10:33:20:  SVR-TRACE: ABOUT TO INVOKE EETEST RUN METHOD!
01-23-2018 10:33:20:  SVR-ERROR: Marshalled Link <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<model>
    <link href="some:///" type="application/svg+xml" name2="val2" title="XTitleX" name1="val1" rel="Relation"/>
</model>
  does not contain expected uri reference some://where.at:port/
01-23-2018 10:33:20:  SVR-ERROR: Test case throws exception: Marshalled Link <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<model>
    <link href="some:///" type="application/svg+xml" name2="val2" title="XTitleX" name1="val1" rel="Relation"/>
</model>
  does not contain expected uri reference some://where.at:port/
01-23-2018 10:33:20:  SVR-ERROR: Exception at:
01-23-2018 10:33:20:  SVR-ERROR: com.sun.ts.lib.harness.EETest$Fault: Marshalled Link <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<model>
    <link href="some:///" type="application/svg+xml" name2="val2" title="XTitleX" name1="val1" rel="Relation"/>
</model>
  does not contain expected uri reference some://where.at:port/
        at com.sun.ts.tests.jaxrs.common.JAXRSCommonClient.fault(JAXRSCommonClient.java:730)
        at com.sun.ts.tests.jaxrs.common.JAXRSCommonClient.assertTrue(JAXRSCommonClient.java:625)
        at com.sun.ts.tests.jaxrs.common.JAXRSCommonClient.assertContains(JAXRSCommonClient.java:747)
        at com.sun.ts.tests.jaxrs.api.rs.core.linkjaxbadapter.JAXRSClient.marshallTest(JAXRSClient.java:74)

**Comment by jkoehler22** [comment]
Closing as this test is passing in the TCK.
