### ISSUE TITLE
Running local FAT with CxfSAMLWSSTemplates* and CxfSAMLWSSTemplatesWithExternalPolicy* test classes failed: These policy alternatives can not be satisfied

### ISSUE THREAD

**Issue by meiaus** [OpenLiberty/open-liberty#17588]
When running the FAT test suite locally with both CxfSAMLWSSTemplates* and CxfSAMLWSSTemplatesWithExternalPolicy* test classes in the same FAT project (e.g., com.ibm.ws.wssecurity_fat.wsscxf.saml; please note this project contains the newly regrouped test classes), the following 6 tests failed with the same errors.

As a side note, when separating these 2 test classes into 2 different FAT projects, then the error did not appear, for example, CxfSAMLWSSTemplates* and CXFSAMLSSLBasic* classes in one project;
CxfSAMLWSSTemplatesWithExternalPolicy* with CxfSAMLAsymSignEncTests* in another project.

- FATSuite.java

```
. . .
import com.ibm.ws.wssecurity.fat.cxf.samltoken.LiteAlwaysRunTest.AlwaysRunAndPassTest;
import com.ibm.ws.wssecurity.fat.cxf.samltoken.OneServerTests.CxfSAMLWSSTemplates1ServerTests;
import com.ibm.ws.wssecurity.fat.cxf.samltoken.TwoServerTests.CxfSAMLWSSTemplates2ServerTests;
import com.ibm.ws.wssecurity.fat.cxf.samltoken.TwoServerTests.CxfSAMLWSSTemplatesWithExternalPolicy2ServerTests;

. . .
@RunWith(Suite.class)
@SuiteClasses({

	   //Lite
	   AlwaysRunAndPassTest.class,
             
       //Full
       CxfSAMLWSSTemplates2ServerTests.class,
       CxfSAMLWSSTemplates1ServerTests.class,
       CxfSAMLWSSTemplatesWithExternalPolicy2ServerTests.class
          
              
})


```
- junit html test result
![image](https://user-images.githubusercontent.com/27024803/122498567-f7007f80-cfb4-11eb-8883-ed7b05a4e12f.png)

- from com.ibm.ws.wssecurity.fat.cxf.samltoken.TwoServerTests.CxfSAMLWSSTemplates2ServerTests:
CxfSAMLWSSTemplatesTests_AsymmetricX509MutualAuthenticationWithSaml_omitInitiatorTokenEE8Only_EE8_FEATURES
CxfSAMLWSSTemplatesTests_AsymmetricX509MutualAuthenticationWithSaml_omitRecipientTokenEE8Only_EE8_FEATURES
CxfSAMLWSSTemplatesTests_X509SymmetricForMessageAndSamlForClient_omitProtectionPolicyEE8Only_EE8_FEATURES

- from com.ibm.ws.wssecurity.fat.cxf.samltoken.OneServerTests.CxfSAMLWSSTemplates1ServerTests
CxfSAMLWSSTemplatesTests_AsymmetricX509MutualAuthenticationWithSaml_omitInitiatorTokenEE8Only_EE8_FEATURES
CxfSAMLWSSTemplatesTests_AsymmetricX509MutualAuthenticationWithSaml_omitRecipientTokenEE8Only_EE8_FEATURES
CxfSAMLWSSTemplatesTests_X509SymmetricForMessageAndSamlForClient_omitProtectionPolicyEE8Only_EE8_FEATURES

```
2021-06-17-12:52:00:151 response: Did not get to the Service Cleint Was expecting [This is WSSTemplateWebSvc4 Web Service] but received: <html><head><title>CXF WSS Templates Test Service Client</title></head><body><p>Request: CXF WSS Templates Test Service Client</p><p>Response: javax.xml.ws.soap.SOAPFaultException: These policy alternatives can not be satisfied: {http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702}SignedEncryptedSupportingTokens: The received token does not match the signed encrypted supporting token requirement {http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702}SamlToken: The received token does not match the token inclusion requirement {http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702}WssSamlV20Token11 {http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702}AsymmetricBinding: Received Timestamp does not match the requirements {http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702}InitiatorToken {http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702}X509Token: The received token does not match the token inclusion requirement {http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702}RecipientToken {http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702}IncludeTimestamp {http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702}OnlySignEntireHeadersAndBody {http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702}EncryptSignature {http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702}SignedParts: Soap Body is not SIGNED</p></body></html>.

junit.framework.AssertionFailedError: 2021-06-17-12:52:00:151 response: Did not get to the Service Cleint
Was expecting [This is WSSTemplateWebSvc4 Web Service] but received: <html><head><title>CXF WSS Templates Test Service Client</title></head><body><p>Request: CXF WSS Templates Test Service Client</p><p>Response: javax.xml.ws.soap.SOAPFaultException: These policy alternatives can not be satisfied:
{http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702}SignedEncryptedSupportingTokens: The received token does not match the signed encrypted supporting token requirement
{http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702}SamlToken: The received token does not match the token inclusion requirement
{http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702}WssSamlV20Token11
{http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702}AsymmetricBinding: Received Timestamp does not match the requirements
{http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702}InitiatorToken
{http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702}X509Token: The received token does not match the token inclusion requirement
{http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702}RecipientToken
{http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702}IncludeTimestamp
{http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702}OnlySignEntireHeadersAndBody
{http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702}EncryptSignature
{http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702}SignedParts: Soap Body is not SIGNED</p></body></html>.
at com.ibm.ws.security.fat.common.CommonMessageTools.assertAndLog(CommonMessageTools.java:81)
at com.ibm.ws.security.fat.common.CommonMessageTools.assertTrueAndLog(CommonMessageTools.java:61)
at com.ibm.ws.security.saml20.fat.commonTest.SAMLCommonValidationTools.validateResponseContent(SAMLCommonValidationTools.java:302)
at com.ibm.ws.security.saml20.fat.commonTest.SAMLCommonValidationTools.validateWithResponse(SAMLCommonValidationTools.java:270)
at com.ibm.ws.security.saml20.fat.commonTest.SAMLCommonValidationTools.validateResult(SAMLCommonValidationTools.java:127)
at com.ibm.ws.security.saml20.fat.commonTest.SAMLCommonTestHelpers.invokeACSWithSAMLResponse(SAMLCommonTestHelpers.java:803)
at com.ibm.ws.security.saml20.fat.commonTest.SAMLCommonTestHelpers.invokeACSWithSAMLResponse(SAMLCommonTestHelpers.java:753)
at com.ibm.ws.security.saml20.fat.commonTest.SAMLCommonTest.genericSAML(SAMLCommonTest.java:594)
at com.ibm.ws.security.saml20.fat.commonTest.SAMLCommonTest.genericSAML(SAMLCommonTest.java:521)
at com.ibm.ws.wssecurity.fat.cxf.samltoken.common.CxfSAMLWSSTemplatesTests.CxfSAMLWSSTemplatesTests_AsymmetricX509MutualAuthenticationWithSaml_omitInitiatorTokenEE8Only(CxfSAMLWSSTemplatesTests.java:296)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:197)
at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:318)
at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:171)
at componenttest.rules.repeater.RepeatTests$CompositeRepeatTestActionStatement.evaluate(RepeatTests.java:115) 
```

The log zip `autoFVT-wsdl-ep-6fail.zip` is in box: https://ibm.ent.box.com/file/823346672993

**Comment by meiaus** [comment]
fyi - @arunavemulapalli  @jimmy1wu

**Comment by meiaus** [comment]
The issue didn't appear once the 2 classes are separated:
CxfSAMLWSSTemplatesWithExternalPolicy in com.ibm.ws.wssecurity_fat.wsscxf.saml
CxfSAMLWSSTemplates* in com.ibm.ws.wssecurity_fat.wsscxf.saml.1

The update is in #17452.
