### ISSUE TITLE
Java 16+ strong encapsulation violation in com.ibm.ws.jmx_fat

### ISSUE THREAD

**Issue by gjwatts** [OpenLiberty/open-liberty#17602]
The `com.ibm.ws.jmx_fat` bucket is currently failing at Java 16+ due to the default behavior change in the JVM switch for [enforcing strong encapsulation in Java 16](https://openjdk.java.net/jeps/396) (and removal of that switch in Java 17) as part of the [Java JPMS](https://www.infoworld.com/article/3543253/what-is-jpms-introducing-the-java-platform-module-system.html) design.  

The stack trace shows:
```
java.lang.reflect.InaccessibleObjectException: 2021-06-11-10:25:56:977 Unable to make public java.lang.String com.ibm.tools.attach.attacher.OpenJ9VirtualMachine.toString() accessible: module jdk.attach does not "exports com.ibm.tools.attach.attacher" to unnamed module @aa66157e
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
	at com.ibm.ws.jmx.fat.attach.ForwardingInvocationHandler.invoke(ForwardingInvocationHandler.java:35)
	at jdk.proxy2/jdk.proxy2.$Proxy12.toString(Unknown Source)
	at java.base/java.lang.String.valueOf(String.java:3068)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:169)
	at com.ibm.ws.jmx.fat.AttachSupport.<init>(AttachSupport.java:46)
	at com.ibm.ws.jmx.fat.JMXTest.testMBeanAttachAPI(JMXTest.java:96)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:197)
	at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:318)
	at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:171)
```

If possible, the FAT bucket should be updated to no longer violate JPMS strong encapsulation.  If that is not feasible, the jvm argument `--add-exports jdk.attach/com.ibm.tools.attach.attacher=ALL-UNNAMED` will need to be used by this test bucket to handle the strong encapsulation violation.

Beware, the `--add-opens` and `--add-exports` jvm arguments are only valid for Java 9 or higher, so they need to be skipped if running on Java 8.

**Comment by gjwatts** [comment]
Fixed by #18324.  Closing.
