### ISSUE TITLE
Java 16+ strong encapsulation violation from org.apache.cxf.common in com.ibm.ws.jaxrs.2.0_fat

### ISSUE THREAD

**Issue by gjwatts** [OpenLiberty/open-liberty#17616]
The `com.ibm.ws.jaxrs.2.0_fat` bucket is currently failing at Java 16+ due to the default behavior change in the JVM switch for [enforcing strong encapsulation in Java 16](https://openjdk.java.net/jeps/396) (and removal of that switch in Java 17) as part of the [Java JPMS](https://www.infoworld.com/article/3543253/what-is-jpms-introducing-the-java-platform-module-system.html) design.  

The stack trace shows:
```
java.lang.reflect.InaccessibleObjectException: 2021-06-18-14:51:04:248 Unable to make field private static volatile java.net.Authenticator java.net.Authenticator.theAuthenticator accessible: module java.base does not "opens java.net" to unnamed module @5b98dfd9
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:177)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:171)
	at org.apache.cxf.common.util.ReflectionUtil$11.run(ReflectionUtil.java:196)
	at org.apache.cxf.common.util.ReflectionUtil$11.run(ReflectionUtil.java:194)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:682)
	at org.apache.cxf.common.util.ReflectionUtil.setAccessible(ReflectionUtil.java:194)
	at org.apache.cxf.transport.http.CXFAuthenticator.addAuthenticator(CXFAuthenticator.java:55)
	at org.apache.cxf.transport.http.URLConnectionHTTPConduit.<init>(URLConnectionHTTPConduit.java:90)
	at org.apache.cxf.transport.http.HTTPTransportFactory.getConduit(HTTPTransportFactory.java:229)
	at org.apache.cxf.transport.http.HTTPTransportFactory.getConduit(HTTPTransportFactory.java:208)
	at org.apache.cxf.endpoint.AbstractConduitSelector.createConduit(AbstractConduitSelector.java:145)
	at org.apache.cxf.endpoint.AbstractConduitSelector.getSelectedConduit(AbstractConduitSelector.java:107)
	at org.apache.cxf.endpoint.UpfrontConduitSelector.prepare(UpfrontConduitSelector.java:63)
	at org.apache.cxf.jaxrs.client.ClientConfiguration.prepareConduitSelector(ClientConfiguration.java:110)
	at org.apache.cxf.jaxrs.client.AbstractClient.prepareConduitSelector(AbstractClient.java:911)
	at org.apache.cxf.jaxrs.client.AbstractClient.createMessage(AbstractClient.java:1020)
	at org.apache.cxf.jaxrs.client.WebClient.finalizeMessage(WebClient.java:1063)
	at org.apache.cxf.jaxrs.client.WebClient.doChainedInvocation(WebClient.java:1036)
	at org.apache.cxf.jaxrs.client.WebClient.doInvoke(WebClient.java:894)
	at org.apache.cxf.jaxrs.client.WebClient.doInvoke(WebClient.java:862)
	at org.apache.cxf.jaxrs.client.WebClient.invoke(WebClient.java:427)
	at org.apache.cxf.jaxrs.client.WebClient$SyncInvokerImpl.method(WebClient.java:1551)
	at org.apache.cxf.jaxrs.client.WebClient$SyncInvokerImpl.get(WebClient.java:1471)
	at org.apache.cxf.jaxrs.client.spec.InvocationBuilderImpl.get(InvocationBuilderImpl.java:85)
	at com.ibm.ws.jaxrs20.fat.annotationscan.AnnotationScanTest.testApplication1Resource1(AnnotationScanTest.java:112)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:197)
	at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:318)
	at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:171)
	at componenttest.rules.repeater.RepeatTests$CompositeRepeatTestActionStatement.evaluate(RepeatTests.java:115)
```

`org.apache.cxf.common.util.ReflectionUtil` is the last non-core Java class in the stack trace.  This defect might be fixed by a newer version that properly handles strong encapsulation.  If not, then `--add-opens java.base/java.net=ALL-UNNAMED` will need to be added to the arguments when starting the JVM for this FAT.  Beware, the `--add-opens/--add-exports` jvm arguments are only valid for Java 9+, so they need to be skipped if running on Java 8.

**Comment by andymc12** [comment]
CXF 3.1.X (which is the implementation for `jaxrs-2.0` does not have a newer version of `CXFAuthenticator` that would work with Java 16.  There is an updated version of `CXFAuthenticator` for 3.4.X which is used in `jaxrs-2.1`.

My suggested fix for this is to skip the test when running `jaxrs-2.0` and Java >= 16.

**Comment by jhanders34** [comment]
@andymc12 are you saying that we will not support JAXRS 2.0 with Java 16 and above?  This seems like the wrong approach to resolve this issue.  Either we should open java.net in java9.options or we should update the code to work with Java 16 like what was done with the 3.4.x version of CXF.  The customer should NOT be required to add their own --open to the jvm.options.  That is why we do it everywhere else in the java9.options to make it seamless for the customer to move to Java 16+.

**Comment by andymc12** [comment]
@jhanders34 - no, we are still planning to support JAX-RS 2.0 with Java 16, but it will be on the user to add the necessary command line arguments. We will not make CXF code changes to support Java 16 for JAX-RS 2.0. HTH
