### ISSUE TITLE
java.lang.ClassNotFoundException: org.glassfish.jersey.client.JerseyClientBuilder cannot be found by com.ibm.websphere.javaee.jaxrs.2.1_1.0.52.cl210520210510-1231

### ISSUE THREAD

**Issue by comfyeagle** [OpenLiberty/open-liberty#17622]
**Describe the bug**
After calling a SOAP service that responds with an MTOM/multipart content-type response, creating a jax-rs client with ClientBuilder.newClient() fails with

 java.lang.ClassNotFoundException: org.glassfish.jersey.client.JerseyClientBuilder cannot be found by com.ibm.websphere.javaee.jaxrs.2.1_1.0.52.cl210520210510-1231

In version 20.0.0.5 that scenario was working. With version 21.0.0.5 it will throw above Exception

If there is a stack trace, please include the FULL stack trace (without any `[internal classes]` lines in it). To find the full stack trace, you may need to check in `$WLP_OUTPUT_DIR/messages.log`
[err] Default Executor-thread-11 error while loading Client Builder implementation
[err] java.lang.RuntimeException: java.lang.ClassNotFoundException: org.glassfish.jersey.client.JerseyClientBuilder cannot be found by com.ibm.websphere.javaee.jaxrs.2.1_1.0.52.cl210520210510-1231
[err] 	at javax.ws.rs.client.ClientBuilder.newBuilder(ClientBuilder.java:110)
[err] 	at test.Timer.run(Timer.java:42)
[err] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[err] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[err] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[err] 	at java.lang.reflect.Method.invoke(Method.java:497)
[err] 	at com.ibm.ejs.container.EJSContainer.invokeProceed(EJSContainer.java:4886)
[err] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[err] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[err] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[err] 	at java.lang.reflect.Method.invoke(Method.java:497)
[err] 	at com.ibm.ejs.container.interceptors.InterceptorProxy.invokeInterceptor(InterceptorProxy.java:189)
[err] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[err] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[err] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[err] 	at java.lang.reflect.Method.invoke(Method.java:497)
[err] 	at com.ibm.ejs.container.interceptors.InterceptorProxy.invokeInterceptor(InterceptorProxy.java:189)
[err] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[err] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[err] 	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:238)
[err] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[err] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[err] 	at java.lang.Thread.run(Thread.java:745)
[err] Caused by: java.lang.ClassNotFoundException: org.glassfish.jersey.client.JerseyClientBuilder cannot be found by com.ibm.websphere.javaee.jaxrs.2.1_1.0.52.cl210520210510-1231
[err] 	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:519)
[err] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[err] 	at java.lang.Class.forName0(Native Method)
[err] 	at java.lang.Class.forName(Class.java:264)
[err] 	at javax.ws.rs.client.FactoryFinder.newInstance(FactoryFinder.java:111)
[err] 	... 38 more

**Steps to Reproduce**
[jax-rs-test.zip](https://github.com/OpenLiberty/open-liberty/files/6692320/jax-rs-test.zip)
run the project with a SoapUI MockServer based on src/main/resources/Simple.wsdl and enabled MTOM functionality. See Screenshot for details on SoapUI setup.

![image](https://user-images.githubusercontent.com/86287761/122885425-5c4eca80-d33f-11eb-9693-2dd3219b87c3.png)

**Expected behavior**
Creating the Client with ClientBuilder.newClient() should always work even if a previous call to a SOAP service with MTOM enabled was made.

**Diagnostic information:**
 - OpenLiberty Version: 21.0.0.5
 - Java Version:
java version "1.8.0_291"
Java(TM) SE Runtime Environment (build 8.0.6.30 - pxa6480sr6fp30-20210507_01(SR6 FP30))
IBM J9 VM (build 2.9, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20210415_469669 (JIT enabled, AOT enabled)
OpenJ9   - c2bc063
OMR      - fa000e8
IBM      - 8165371)
JCL - 20210419_01 based on Oracle jdk8u291-b09
 - server.xml configuration (WITHOUT sensitive information like passwords)
[jax-rs-client-config.zip](https://github.com/OpenLiberty/open-liberty/files/6692401/jax-rs-client-config.zip)

**Comment by andymc12** [comment]
Hi @comfyeagle - I've most often seen this error before when the thread that is trying to create a new `ClientBuilder` instance does not have the proper thread context classloader set.  The exception is misleading... it looks for the Jersey ClientBuilder instance because Jersey is the reference implementation - before getting this far, it attempted to load the `ClientBuilder` implementation from the thread's context classloader.  If that classloader were set correctly, then it should have found Open Liberty's implementation (based on Apache CXF).

I could not reproduce the error you see, but I suspect that that is because I don't have the SOAP service running that the `SoapServiceClient` is invoking - as a result, it ends with a connection error and then proceeds to invoke the JAX-RS client request - and it fails because my client is not configured to accept GitHub's SSL certificate - but it certainly gets further than creating the `ClientBuilder`. 

But I think we can discover what's going wrong with a few tweaks to your code and config. 
* First, can you print out the thread context classloader at the beginning of the Timer's `run` method, then again after the call to the SOAP service?
It should look something like this:
```
    @Timeout
    @TransactionAttribute(TransactionAttributeType.NOT_SUPPORTED)
    public void run() {
        try {
            System.out.println("context classloaderbefore : " + Thread.currentThread().getContextClassLoader());
            try {
                System.out.println("call service " + new SoapServiceClient().callService());
            } catch (Exception e) {
                e.printStackTrace();
            }
            System.out.println("class loader " + Thread.currentThread().getName() + " trying to get Client Builder implementation");
            System.out.println("context classloader after: " + Thread.currentThread().getContextClassLoader());
            Response method = ClientBuilder.newClient().target("https://github.com/OpenLiberty/open-liberty#readme").request().method(HttpMethod.GET);
            System.out.println(Thread.currentThread().getName() + " got github openliberty page " + method.readEntity(String.class));
        } catch (Throwable throwable) {
            System.err.println(Thread.currentThread().getName() + " error while loading Client Builder implementation");
            throwable.printStackTrace();
        }
    }
```

* Next, let's print out every time that the context classloader is changed on Liberty-managed threads.  We can do that by adding these lines to the bootstrap.properties file in the server directory (you may need to create this file if it doesn't exist):
```
com.ibm.ws.logging.trace.specification=*=info:com.ibm.ws.threading.internal.*=all
com.ibm.ws.logging.max.files=1
```

With those changes, can you reproduce the problem and then attach the server's trace.log file?  Thanks

**Comment by comfyeagle** [comment]
Hi @andymc12,

thank you for your response, it is very much appreciated. 

I made the changes to the code and also activated tracing in bootstrap.properties. The issue is still there. You can find the logs here 
[logs.zip](https://github.com/OpenLiberty/open-liberty/files/6699845/logs.zip)

Here you can also find the soap ui project which is necessary to reproduce the error. You also need to start the MockService 1. What I find interesting is, if the mock server returns a non multipart response (set EnableMtom and ForceMtom to false, see screenshot in my initial commen), then I have no problem with creating the client.
[soap-server.zip](https://github.com/OpenLiberty/open-liberty/files/6699854/soap-server.zip)

thank you
