### ISSUE TITLE
com/ibm/websphere/ras/Tr.register(<class>) re-registers duplicate class names

### ISSUE THREAD

**Issue by gjdeval** [OpenLiberty/open-liberty#17656]
A class hooks into Liberty RAS trace subsystem by calling com/ibm/websphere/ras/Tr.register(<class>) to receive a TraceComponent, which is used for subsequent trace activity. Tr.register should be called only once per class, and the comments in the implementation provide guidance to that effect.

However, when Tr.register is called it does not check whether this class has already been registered. So if (contrary to the recommended pattern) Tr.register is called repeatedly with the same class, it will repeatedly register the class, rather than just returning the already-created TraceComponent. 

This was discovered while diagnosing lock contention problems encountered by a stack product, which made the mistake of calling Tr.register in a class constructor when trace was enabled. 

Tr.register should check for an existing TraceComponent and return it if found. 

Here's a stack trace showing the problem, for reference.
```
at sun/instrument/InstrumentationImpl.retransformClasses0(Native Method)
at sun/instrument/InstrumentationImpl.retransformClasses(InstrumentationImpl.java:163)
at sun/reflect/GeneratedMethodAccessor22.invoke(Bytecode PC:42)
at sun/reflect/DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55(Compiled Code))
at java/lang/reflect/Method.invoke(Method.java:508(Compiled Code))
at com/ibm/ws/kernel/launch/internal/TraceInstrumentation.invoke(TraceInstrumentation.java:80)
at com/sun/proxy/$Proxy0.retransformClasses(Bytecode PC:18)
at com/ibm/ws/ras/instrument/internal/main/LibertyRuntimeTransformer.retransformClass(LibertyRuntimeTransformer.java:250)
at com/ibm/ws/ras/instrument/internal/main/LibertyRuntimeTransformer.traceStateChanged(LibertyRuntimeTransformer.java:222(Compiled Code))
at com/ibm/ws/logging/internal/osgi/Activator$RuntimeTransformerComponentListener.traceComponentUpdated(Activator.java:117(Compiled Code))
at com/ibm/websphere/ras/TrConfigurator.traceComponentUpdated(TrConfigurator.java:232(Compiled Code))
at com/ibm/websphere/ras/TraceComponent.setTraceSpec(TraceComponent.java:294(Compiled Code))
   (entered lock: com/ibm/websphere/ras/TraceComponent@0x00000000E3E40200, entry count: 1)
at com/ibm/websphere/ras/Tr.registerTraceComponent(Tr.java:790(Compiled Code))
at com/ibm/websphere/ras/Tr.register(Tr.java:287)                                           <======== THE PROBLEM
at com/ibm/zosconnect/internal/web/ServiceProxyServlet$AsyncServiceRequestListener.<init>(Bytecode PC:76)
at com/ibm/zosconnect/internal/web/ServiceProxyServlet$4.<init>(Bytecode PC:13)
... snip ...
```

**Comment by Channyboy** [comment]
The existing `TR.register` methods in general create the `TraceComponent` object from arguments passed in (i.e. name, class, etc) and then proceed to _properly_ register the `TraceComponent` object. This includes method calls to various logging classes to store or register the `TraceComponent` object.  Part of the logic is to store it in a Set with Weak References within the `Tr` class. This cache as-is is used to update all reachable `TraceComponent`s   with any updated trace specifications.

registration summary:
1. `TraceComponent` is created
   -  TraceComponent is put in to the WeakReference Set
2. `Trace Component` is registered

Attempted the following:
i. Before creating the `TraceComponent` object, iterate through the existing Weak Reference Set (i.e. cache) to identify if any of the existing `TraceComponent` objects in the set match the name being registered (i.e. passed into the `Tr.register` method). If so, we return the found `TraceComponent` and  return it. This omits the 1 and 2 listed above.

ii. Using a `WeakHashMap` as the cache where the key is the `TraceComponent` object registered. In this approach, the `TraceComponent` object is created and then checked to see if it exists as a key in the Map (To avoid iterating through the entry set which is equivalent to `i` above). If it exists then we can skip the "registration" process. 

iii. Using the TWAS solution of a Map<String, TR> (where  the `String` is the name). This voids the _memory enhancements_  that the Weak References were originally supposed to achieve.

Performance Test Summary:
- Tested using the QuickLog Test with 4 threads invoking both Traces and Logs.
- `LogSource` class was modified to _register_ a `TraceComponent` each time a `parse()` command is invoked. As this method is called almost each time a log (i.e. console, message event) is processed through the collector manager _pipeline_ any performance improvements should be noticeable.
- System property was used to toggle between checking the cache or directly registering the cache ( as control test)
- Results on my _local workstation*_ shows that there are no improvements between the control and the modifications.

*Not a sanitary performance testing environment

Suggest to just modify the Javadoc to not register a class more than once. Should be done statically once per class.

**Comment by jhanders34** [comment]
I believe there is at least one additional approach that could be done to avoid the issues with the approaches you have above.  I find the approaches above all bad to achieve what we are looking for from a performance perspective.  I think you can do a combination of all of them to avoid all the negatives of each of them individually.

iv.  Create a ConcurrentHashMap<String, WeakReference<TraceComponent>>.  When you go to register your TraceComponent look it up in the ConcurrentHashMap and if it is found then you return it and avoid registering it again.  If you don't find it, then register as you have in the past.  You could do a computeIfAbsent to avoid some of the extra logic of doing a get and a putIfAbsent type logic as well.  Additionally you would need to do a poll on a ReferenceQueue for each of the WeakReferences to update when something is cleaned up.  The poll would be called before doing the get / computeIfAbsent logic referenced above.

If you want some help with implementing such a solution, let me know.

As to your testing, did you have trace enabled at all?  @gjdeval I believe that trace was enabled for this scenario right?

**Comment by gjdeval** [comment]
@Channyboy   Thanks for the status update. If you can provide me with the modified QuickLog implementation used for testing and brief instructions, I will give it a spin in a proper test environment to see what effect the system property has, and confirm that traffic is going down the expected paths during testing. 

It may be necessary to push the load with more than 4 threads to clearly show the locking issue - when we encountered this in the zOSconnect environment, the tester was running work at the system with 50 threads.

@jhanders34  In the zOSconnect environment trace was enabled - but if I understand the description above correctly, David's test should have shown the same contention issue, if the implementation is actually behaving as intended and enough load is pushed at it.

**Comment by jhanders34** [comment]
I thought in order to do the trace injection at runtime, trace had to be enabled for that class which is why I asked that question.  So if @Channyboy's scenario is not causing class transforms, then it would not be the same scenario as originally hit the problem.

**Comment by gjdeval** [comment]
I do not know if "trace injection at runtime" is somehow implicated in this issue. 
My understanding is that the problem arises when some class re-registers with the trace subsystem, and many threads drive work through that re-register action in parallel. 

@Channyboy  The test as described is missing a control step - we need to be able to turn the bad behavior (repeated calls to Tr.register) on and off, so that we can observe that there is a big performance impact caused by the attempt to recreate the problem.

After verifying that performance is impacted by enabling the Tr.register abuse, then we can test various proposed solutions to see how the solution implementation performs compared to the baseline.

**Comment by Channyboy** [comment]
A trace was set as `<logging traceSpecification="*=audit:com.ibm.*=all"/>`

@gjdeval 
The QuickLog Test is found here https://github.ibm.com/was-lumberjack/QuickLogTest (it only supports up to 16 threads)

The test results from a non modified liberty would be:
|Action	|Threads	|Duration (s)	|Delay (ms) |Actions Completed	Actions per Second|
|----|----|----|----|----
|trace	|4	|10	|0	|1021083	|102108
|log	|4	|10	|0	|99714	|9971

The instrumentation of the register in the `parse()` method in LogSource reduces through put to the following table.
The `LogSource.parse()` is part of the path that messages log events go through so this would have significant impact (to  messages/console.log at least)

|Action	|Threads	|Duration (s)	|Delay (ms) |Actions Completed	Actions per Second|
|----|----|----|----|----
|trace	|4	|10	|0	|984674	|98467
|log	|4	|10	|0	|515	|51

**Comment by Channyboy** [comment]
@gjdeval 

When the registration of the `TraceComponent` happens it results in the transformation of the target class (i.e. the class registering the `TraceComponent`. This perhaps is the main performance impact seen in the scenario of the client/customer class that was registering the `TraceComponent` per instance.

There exists the situations where a `TraceComponent` belonging to a class that is instrumented properly (i.e. static `TraceComponent`) is unloaded and reloaded. This happens when a service is deactivated and reactivated. Returning the existing `TraceComponent` is not effective as the "new" class would  require transforming again which defeats the purpose of retrieving a cached `TraceComponent`. 
  Additionally, this situation should have been address by the usage of the weak-referenced `TraceComponent` which would have been removed from the cache (due to the unloaded first class). However, the dereferencing and updating of a nulled WeakReference is subject to the JVM and in our testing (i.e. some other project's FATS) it does not do it _fast enough_. 

The inception of this issue was to resolve overhead from re-registering `TraceComponent`s. However under normal operation and instrumentation of `TraceComponents` that is not particularly an issue. The problem arises when `TraceComponent` is instrumented incorrectly. As caching would be to mostly address this (mis)use-case, to properly address the end-user's misuse of instrumenting `TraceComponent` would require somehow passing the context of how the `TraceComponent` is being registered (i.e. per instance) which may necessitate a much greater overhead overall than what caching `TraceComponent`s would serve to achieve.

The simple solution on the other hand is to more explicitly document how to appropriately instrument `TraceComponents`.

**Comment by Channyboy** [comment]
@gjdeval any issues on just updating the javadoc?
