### ISSUE TITLE
Test Failure: com.ibm.ws.request.timing.fat.TimingRequestTiming.testDynamicTimingUpdate

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#17702]
RTC 284443

```
testDynamicTimingUpdate:junit.framework.AssertionFailedError: 2021-06-10-00:03:40:966 Expected > 0 slow request warnings but found : 0
    at com.ibm.ws.request.timing.fat.TimingRequestTiming.testDynamicTimingUpdate(TimingRequestTiming.java:612)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:197)
    at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:318)
    at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:171)
    at componenttest.rules.repeater.RepeatTests$CompositeRepeatTestActionStatement.evaluate(RepeatTests.java:115)
```

**Comment by fmhwong** [comment]
New occurrences in RTC.

I think the condition in [TimingRequestTiming.java:188](https://github.com/OpenLiberty/open-liberty/blob/6635ca024e1e92794b144b9e9b3d81e8a84cb1ef/dev/com.ibm.ws.request.timing_fat/fat/src/com/ibm/ws/request/timing/fat/TimingRequestTiming.java#L188) should be changed to `if (slow == p_slow)` 
and [TimingRequestTiming.java:198](https://github.com/OpenLiberty/open-liberty/blob/6635ca024e1e92794b144b9e9b3d81e8a84cb1ef/dev/com.ibm.ws.request.timing_fat/fat/src/com/ibm/ws/request/timing/fat/TimingRequestTiming.java#L198) should be changed to 
```
assertTrue("Expected  > 0 slow request warnings but found : " + slow - p_slow, ((slow - p_slow) > 0));
```
