### ISSUE TITLE
when wsSecurity-1.1 feature enabled with Jakarta EE9 features: Provider org.glassfish.jaxb.runtime.v2.JAXBContextFactory not found

### ISSUE THREAD

**Issue by meiaus** [OpenLiberty/open-liberty#17758]
The issue was initially uncovered from running wssecurity CXF FAT (`com.ibm.ws.wssecurity_fat.wsscxf`) with Jakarta features: 
```
<featureManager>
        <feature>servlet-5.0</feature>
        <feature>appSecurity-4.0</feature>
        <feature>xmlWS-3.0</feature>
        <feature>pages-3.0</feature>
        <feature>wssecurity-1.1</feature>
    </featureManager>

```
Later recreated using `com.ibm.ws.jaxws.2.2.webcontainer_fat`, e.g., the command run locally: 
```
 ./gradlew com.ibm.ws.jaxws.2.2.webcontainer_fat:buildandrun -Dfat.test.class.name=com.ibm.ws.jaxws.fat.WebServiceInWebXM
LTest_Lite -Dglobal.debug.java2.sec=false
```
and the server.xml is manually updated (under `... com.ibm.ws.jaxws.2.2.webcontainer_fat\publish\servers\POJOServiceSecurityServer`)  to add the feature `wsSecurity-1.1`:

```
<server>
    <featureManager>
        <feature>jsp-2.2</feature>
        <feature>jaxws-2.2</feature>
        <feature>appSecurity-2.0</feature>
        <feature>wsSecurity-1.1</feature>
    </featureManager>
```

- messages.log:
```
...
[7/1/21, 17:33:48:511 PDT] 00000094 com.ibm.ws.logging.internal.impl.IncidentImpl                I FFDC1015I: An FFDC Incident has been created: "org.apache.xml.security.stax.ext.XMLSecurityConfigurationException: Error while searching for service [jakarta.xml.bind.JAXBContextFactory]
Original Exception was jakarta.xml.bind.JAXBException: Error while searching for service [jakarta.xml.bind.JAXBContextFactory]
 - with linked exception:
[java.util.ServiceConfigurationError: jakarta.xml.bind.JAXBContextFactory: Provider org.glassfish.jaxb.runtime.v2.JAXBContextFactory not found] org.apache.wss4j.stax.setup.WSSec 83" at ffdc_21.07.01_17.33.48.0.log
[7/1/21, 17:33:48:564 PDT] 00000094 com.ibm.ws.logging.internal.impl.IncidentImpl                I FFDC1015I: An FFDC Incident has been created: "java.lang.ExceptionInInitializerError com.ibm.ws.wssecurity.WSSecurityPolicyLoader 119" at ffdc_21.07.01_17.33.48.1.log
[7/1/21, 17:33:48:564 PDT] 00000094 com.ibm.ws.wssecurity.WSSecurityPolicyLoader                 E CWWKW0202E: WS-Security cannot be applied to any web service.  An error occurred while attempting to register the WS-Security policy loader with the CXF framework: [java.lang.ExceptionInInitializerError
	at java.base/java.lang.J9VMInternals.ensureError(J9VMInternals.java:184)
	at java.base/java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:173)
	at org.apache.cxf.ws.security.wss4j.WSS4JStaxOutInterceptor.<init>(WSS4JStaxOutInterceptor.java:94)
	at org.apache.cxf.ws.security.policy.interceptors.WSSecurityInterceptorProvider.<init>(WSSecurityInterceptorProvider.java:65)
	at com.ibm.ws.wssecurity.WSSecurityPolicyLoader.registerProviders(WSSecurityPolicyLoader.java:331)
	at com.ibm.ws.wssecurity.WSSecurityPolicyLoader.<init>(WSSecurityPolicyLoader.java:118)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
...

Caused by: java.util.ServiceConfigurationError: jakarta.xml.bind.JAXBContextFactory: Provider org.glassfish.jaxb.runtime.v2.JAXBContextFactory not found
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:589)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1212)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1221)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1265)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1300)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1385)
	at jakarta.xml.bind.ServiceLoaderUtil.firstByServiceLoader(ServiceLoaderUtil.java:39)
	... 72 more
```

The logs can be found in autoFVT zip file in the box: https://ibm.ent.box.com/file/828765527552

**Comment by meiaus** [comment]
@arunavemulapalli @neuwerk @BerksanAtes @sawadood

**Comment by meiaus** [comment]
So far the issue no longer appeared.

**Comment by arunavemulapalli** [comment]
I am removing the wss4j workaround and will close this issue once I verify the new update is good.
