### ISSUE TITLE
wssecurity cxf sample FAT: CxfBspTests/CxfInteropX509Tests failed with The private key for the supplied alias does not exist in the keystore

### ISSUE THREAD

**Issue by meiaus** [OpenLiberty/open-liberty#17810]
RTC defect:
284648

- messages.log
```
[7/5/21, 7:21:12:498 UTC] 00000046 org.apache.ws.security.util.WSSecurityUtil                   I @TJJ getDomElement node == com.sun.xml.messaging.saaj.soap.impl.ElementImpl@7df78154
[7/5/21, 7:21:12:499 UTC] 00000046 org.apache.ws.security.util.WSSecurityUtil                   I @TJJ getDomElement isJava9SAAJ == true
[7/5/21, 7:21:12:502 UTC] 00000046 org.apache.ws.security.message.WSSecSignature                E org.apache.ws.security.WSSecurityException: General security error (The private key for the supplied alias does not exist in the keystore)
[7/5/21, 7:21:12:503 UTC] 00000046 xf.ws.security.wss4j.policyhandlers.AsymmetricBindingHandler W Sign before encryption failed due to : Signature creation failed
[7/5/21, 7:21:12:504 UTC] 00000046 org.apache.cxf.phase.PhaseInterceptorChain                   W Interceptor for {http://com/ibm/was/wssample/sei/echo/}Echo11Service#{http://com/ibm/was/wssample/sei/echo/}echoOperation has thrown exception, unwinding now
org.apache.cxf.interceptor.Fault: Signature creation failed
	at org.apache.cxf.ws.security.wss4j.policyhandlers.AsymmetricBindingHandler.doSignBeforeEncrypt(AsymmetricBindingHandler.java:196)
	at org.apache.cxf.ws.security.wss4j.policyhandlers.AsymmetricBindingHandler.handleBinding(AsymmetricBindingHandler.java:102)
	at org.apache.cxf.ws.security.wss4j.PolicyBasedWSS4JOutInterceptor$PolicyBasedWSS4JOutInterceptorInternal.handleMessage(PolicyBasedWSS4JOutInterceptor.java:166)
	at org.apache.cxf.ws.security.wss4j.PolicyBasedWSS4JOutInterceptor$PolicyBasedWSS4JOutInterceptorInternal.handleMessage(PolicyBasedWSS4JOutInterceptor.java:89)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:273)
```

The tests failed with different flavors of JDK11:
1. [07/06/2021 13:43:09:439 PDT] 001 JavaInfo                       <init>                         I major=11  minor=0 service release=0 fixpack=0  vendor=IBM  javaHome=C:\download_ibm_jdk11\ibm-java-jdk_x64_windows_11.0.11.0\jdk-11.0.11+9
2. [07/06/2021 14:43:24:449 PDT] 001 JavaInfo                       <init>                         I major=11  minor=0 service release=0 fixpack=0  vendor=OPENJ9  javaHome=C:\AdoptOpenJDK\jdk-11.0.11.9-openj9
3. [07/06/2021 15:04:15:194 PDT] 001 JavaInfo                       <init>                         I major=11  minor=0 service release=0 fixpack=0  vendor=SUN_ORACLE  javaHome=C:\download_oracle_jdk\jdk-11.0.11+9_windows-x64_bin\jdk-11.0.11

Tracking this issue to investigate if the keystore needs to be recreated/updated.

logs in the box: https://ibm.ent.box.com/file/831511670310 (`17810-com.ibm.ws.wssecurity_fat.wsscxf-sample.zip`)

@arunavemulapalli

**Comment by meiaus** [comment]
The problem appeared on the classes `CxfBspTests` and `CxfInteropX509Tests` where in the past the test cases have excluded non-IBM JDK. Recently new flavor JDKs are being tested including IBM JDK 11,  which are outside the previous JDK conditional scope, therefore, the error re-appeared.   Since these new flavors are still under the same limitation per test case, additional checking is added to exclude as well. New message is updated in the log: `"Using a NON-IBM JDK or an Open JDK or an IBM JDK 11 - certain tests should not run!  WE WILL BE SKIPPING SOME TESTS"`.

**Comment by meiaus** [comment]
The update is made via https://github.com/OpenLiberty/open-liberty/pull/17452 (commit `e522080`).

![image](https://user-images.githubusercontent.com/27024803/131150539-82fcade7-d48b-4963-835f-eac934a4d1a9.png)
