### ISSUE TITLE
Test Failure: com.ibm.ws.logstash.collector.tests.LogstashSSLTest.testLogstashForAccessEvent

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#18100]
RTC 280097

```
testLogstashForAccessEvent:junit.framework.AssertionFailedError: 2020-11-30-11:02:33:766 Did not find liberty_accesslog
    at com.ibm.ws.logstash.collector.tests.LogstashSSLTest.testLogstashForAccessEvent(LogstashSSLTest.java:180)
    at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:197)
    at org.testcontainers.containers.FailureDetectingExternalResource$1.evaluate(FailureDetectingExternalResource.java:30)
    at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:318)
    at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:171)
```

**Comment by Channyboy** [comment]
From the most recent logs (first set I was able to obtain). It's not just only the `liberty_accesslog` that is failing, but multiple tests in the classes have been failing as well. Looking into the logs, it seems to be a connection issue with connecting with the docker container that's running on the (same) machine.
There are large amounts of `W TRAS0216W: The logstash collector was unable to connect to the logstash server on the specified host libr-dockerb-02.fyre.ibm.com and port number 51104.` emitted by the lumberjack client that is attempting to send data/events to the logstash server.

Reviewing the logs, the "access event" that was generated was successfully completed and the HTTP access log is created in the `http_defaultEndpoint_access.log`. But due to the failure to connect it was never "sent" to the logstashServer causing a failure of the test. This is a similar situationfor subsequent failing tests in this `LogstashSSLTest` class.

The exception thrown (a sample of many)
:
```
[8/23/21, 13:09:50:791 PDT] 000000fe id=00000000 com.ibm.ws.collector.TaskManager                             1 Unable to send events to the target. Reason java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:299)
	at com.ibm.ws.lumberjack.LumberjackClient$SSLHelper.createSocket(LumberjackClient.java:310)
	at com.ibm.ws.lumberjack.LumberjackClient.connect(LumberjackClient.java:90)
	at com.ibm.ws.logstash.collector.internal.LogstashClient.connect(LogstashClient.java:69)
	at com.ibm.ws.collector.TaskManager$SendEventsTask.run(TaskManager.java:255)
	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:238)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:866)
```
This may imply the logstash server crashed (i.e. the docker container crashed?). Or any multitude of factors preventing the (logstash) server (container) to not listen to requests.

This does appear to be an intermittent issue and am not sure if there should be any actions to take. @fmhwong

**Comment by fmhwong** [comment]
No occurrences in last 2 weeks.
