### ISSUE TITLE
Multiple entries in the subject with accessTokenCache enabled

### ISSUE THREAD

**Issue by c00crane** [OpenLiberty/open-liberty#18161]
Getting multiple entries in the subject with accessTokenCache enabled and AuthCache disabled.
Automated tests are failing:

```
2021-08-10-10:33:02:170 Did not find expected "sub" claim and value in the JSP response. Was expecting ["sub":"testuser"] but received [<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-US" lang="en-US"> <head> <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"> <style> body{ margin:0px; padding:0px; background-color: #ffffff; color:#000; font-family:Arial,Verdana,Helvetica,Tahoma,sans-serif; } #content { font-size: 1em; margin-left: 1em; margin-right: 1em; padding: 1em; } h4.basichead { font-family:Arial,Verdana,Helvetica,Tahoma,sans-serif; } p { padding-top: .5em; } ul { line-height: 1.3em; } a:link { color: #c00000 } a:visited { color: #c00000 } #page { border: 7px; padding: 7px } #box { margin: 0; } #title { font-family:Arial,Verdana,Helvetica,Tahoma,sans-serif; font-size:24px; font-weight: normal; color:#274a71; padding-bottom:6px; } #error { colory: #c00004; margin-bottom: 10px; } #code { font-family: monospace; font-size: 8pt; } #stack { margin-left: 30px; } </style> </head> <body> <div id="content"> <div id="page"> <div id="box"> <div id="error"> Exception thrown by application class 'com.ibm.ws.security.collaborator.CollaboratorUtils.multiplePrincipalsError:160' </div> <div id="code"> java.lang.IllegalStateException: SEC_TOO_MANY_PRINCIPALS<br> <div id="stack">at com.ibm.ws.security.collaborator.CollaboratorUtils.multiplePrincipalsError(CollaboratorUtils.java:160)<br>at [internal classes]<br>at com.ibm._jsp._propagationHelperUserInfoApiTest._jspService(_propagationHelperUserInfoApiTest.java:107)<br>at com.ibm.ws.jsp.runtime.HttpJspBase.service(HttpJspBase.java:100)<br>at [internal classes]<br> </div> </div> </div> </div> </div> </body> </html> ].

junit.framework.AssertionFailedError: 2021-08-10-10:33:02:170 Did not find expected "sub" claim and value in the JSP response. Was expecting ["sub":"testuser"] but received [<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-US" lang="en-US">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<style>
body{
margin:0px;
padding:0px;
background-color: #ffffff;
color:#000;
font-family:Arial,Verdana,Helvetica,Tahoma,sans-serif;
}
#content {
font-size: 1em;
margin-left: 1em;
margin-right: 1em;
padding: 1em;
}
h4.basichead {
font-family:Arial,Verdana,Helvetica,Tahoma,sans-serif;
}
p {
padding-top: .5em;
}
ul {
line-height: 1.3em;
}
a:link {
color: #c00000
}
a:visited {
color: #c00000
}
#page {
border: 7px;
padding: 7px
}
#box {
margin: 0;
}
#title {
font-family:Arial,Verdana,Helvetica,Tahoma,sans-serif;
font-size:24px;
font-weight: normal;
color:#274a71;
padding-bottom:6px;
}
#error {
colory: #c00004;
margin-bottom: 10px;
}
#code {
font-family: monospace;
font-size: 8pt;
}
#stack {
margin-left: 30px;
}
</style>
</head>
<body>

<div id="content">
<div id="page">
<div id="box">

<div id="error"> Exception thrown by application class 'com.ibm.ws.security.collaborator.CollaboratorUtils.multiplePrincipalsError:160'
</div>
<div id="code">
java.lang.IllegalStateException: SEC_TOO_MANY_PRINCIPALS<br>
<div id="stack">at com.ibm.ws.security.collaborator.CollaboratorUtils.multiplePrincipalsError(CollaboratorUtils.java:160)<br>at [internal classes]<br>at com.ibm._jsp._propagationHelperUserInfoApiTest._jspService(_propagationHelperUserInfoApiTest.java:107)<br>at com.ibm.ws.jsp.runtime.HttpJspBase.service(HttpJspBase.java:100)<br>at [internal classes]<br>
</div>
</div>
</div>
</div>
</div>

</body>
</html>

].
at com.ibm.ws.security.fat.common.CommonMessageTools.assertAndLog(CommonMessageTools.java:81)
at com.ibm.ws.security.fat.common.CommonMessageTools.assertTrueAndLog(CommonMessageTools.java:61)
at com.ibm.ws.security.oauth_oidc.fat.commonTest.CommonValidationTools.validateWithResponse(CommonValidationTools.java:299)
at com.ibm.ws.security.oauth_oidc.fat.commonTest.CommonValidationTools.validateResult(CommonValidationTools.java:131)
at com.ibm.ws.security.openidconnect.server.fat.jaxrs.config.CommonTests.InboundPropagation2ServerTests.testUserInfo(InboundPropagation2ServerTests.java:262)
at com.ibm.ws.security.openidconnect.server.fat.jaxrs.config.CommonTests.InboundPropagation2ServerTests.InboundPropagation2ServerTests_inboundPropagation_required(InboundPropagation2ServerTests.java:234)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:197)
at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:318)
at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:171)
at componenttest.rules.repeater.RepeatTests$CompositeRepeatTestActionStatement.evaluate(RepeatTests.java:143)

```
Steps to reproduce - run test case **InboundPropagation2ServerTests_inboundPropagation_required** in the **com.ibm.ws.security.openidconnect.server.fat.jaxrs.config** project
(generic steps - invoke the userinfo endpoint with an already used opaque access token created from a config with access token cache enabled and authcache disabled

**Comment by teddyjtorres** [comment]
In general, this is what needs to be done,

- [ ] Create a new ProviderAuthenticationResult with a new subject instead of returning the cached ProviderAuthenticationResult
- [ ] Need to add com.ibm.wsspi.security.cred.uniqueId, it is missing for the second request with cached result
- [ ] Do not clone Principals or All Credentials, just the hashtable and  OidcTokenImpl, if available, into new subject for the subsequent hashtable login or AuthCache hit. Cloning the hashtable should also fix the second point about com.ibm.wsspi.security.cred.uniqueId
