### ISSUE TITLE
Unexpectd FFDC from Jackson

### ISSUE THREAD

**Issue by MarkBluemel** [OpenLiberty/open-liberty#18237]
**Describe the bug**
By following @andymc12’s https://openliberty.io/blog/2020/11/11/byo-jackson.html
I am working to migrate our REST API to jaxrs-2.1 while retaining the use of Jackson. 

To improve on error handling, we have an ExceptionMapper in place which catches (among other things) parsing errors thrown by the Jackson code and produces Responses with (arguably) more meaningful messages for the API users.

The ExceptionMapper is clearly working, as our tests are getting the expected responses for known "bad" data for example trying to set a string value into an int field.

However for each of these we are also getting an FFDC file for the Jackson exception, like the one attached.

Stack Dump = com.fasterxml.jackson.databind.JsonMappingException: Unrecognized token 'banana': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (org.apache.cxf.transport.http.AbstractHTTPDestination$1); line: 1, column: 66] (through reference chain: com.ibm.mq.restapi.pojos.QueueAttributePojo["general"])
    at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:397)
    at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:356)
    at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1714)
    at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:295)
    at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:156)
    at com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:2020)
    at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1179)
    at com.fasterxml.jackson.jaxrs.base.ProviderBase.readFrom(ProviderBase.java:816)
    at org.apache.cxf.jaxrs.utils.JAXRSUtils$2.run(JAXRSUtils.java:1504)
    at java.security.AccessController.doPrivileged(AccessController.java:738)
    at org.apache.cxf.jaxrs.utils.JAXRSUtils.readFromMessageBodyReader(JAXRSUtils.java:1501)
    at org.apache.cxf.jaxrs.utils.JAXRSUtils.readFromMessageBody(JAXRSUtils.java:1454)
    at org.apache.cxf.jaxrs.utils.JAXRSUtils.processRequestBodyParameter(JAXRSUtils.java:972)
    at org.apache.cxf.jaxrs.utils.JAXRSUtils.processParameters(JAXRSUtils.java:908)
    at org.apache.cxf.jaxrs.interceptor.JAXRSInInterceptor.processRequest(JAXRSInInterceptor.java:282)
    at org.apache.cxf.jaxrs.interceptor.JAXRSInInterceptor.handleMessage(JAXRSInInterceptor.java:90)
    at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
    at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:123)
    at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:275)
    at com.ibm.ws.jaxrs20.endpoint.AbstractJaxRsWebEndpoint.invoke(AbstractJaxRsWebEndpoint.java:137)
    at com.ibm.websphere.jaxrs.server.IBMRestServlet.handleRequest(IBMRestServlet.java:146)
    at com.ibm.websphere.jaxrs.server.IBMRestServlet.doPost(IBMRestServlet.java:104)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:706)
    at com.ibm.websphere.jaxrs.server.IBMRestServlet.service(IBMRestServlet.java:96)
    at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1257)
    at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:745)
    at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:442)
    at com.ibm.ws.webcontainer.filter.WebAppFilterChain.invokeTarget(WebAppFilterChain.java:182)
    at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:93)
    at com.ibm.mq.restapi.filters.SecurityFilter.doFilter(SecurityFilter.java:109)
    at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:201)
    at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:90)
    at com.ibm.ws.webcontainer.filter.WebAppFilterManager.doFilter(WebAppFilterManager.java:1001)
    at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1139)
    at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1010)
    at com.ibm.ws.webcontainer.servlet.CacheServletWrapper.handleRequest(CacheServletWrapper.java:75)
    at com.ibm.ws.webcontainer40.servlet.CacheServletWrapper40.handleRequest(CacheServletWrapper40.java:86)
    at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:937)
    at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:279)
    at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1146)
    at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:427)
    at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:386)
    at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:566)
    at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:500)
    at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:360)
    at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.ready(HttpInboundLink.java:327)
    at com.ibm.ws.http.channel.h2internal.H2StreamProcessor$Http2Ready.run(H2StreamProcessor.java:1793)
    at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:238)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.lang.Thread.run(Thread.java:822)

**Steps to Reproduce**
Create a REST API using the jaxrs-2.1 feature, but with "BYO Jackson" and provide bad JSON data - for example an alphabetic string for an integer value.

**Expected behavior**
My ExceptionMapper to be used and no FFDC produced.

**Diagnostic information:**
 - OpenLiberty Version:
    WebSphere Application Server 21.0.0.3 (wlp-1.0.50.cl210320210309-1101)
    
 - Java Version: 
   Java(TM) SE Runtime Environment (8.0.6.31 - pxl6480sr6fp31-20210510_01(SR6 FP31))
   
 - server.xml configuration (WITHOUT sensitive information like passwords)
   I doubt that would be particularly valuable

 - If it would be useful, upload the messages.log file found in `$WLP_OUTPUT_DIR/messages.log`
   No useful information is found in "messages.log"

**Additional context**
Andy McCright has commented that 
"that looks like a bug to me... here's the code that is logging that FFDC:
 ```
   @FFDCIgnore(value = { Fault.class, RuntimeException.class })
    @Override
    public void handleMessage(Message message) {
        //...
        if (response == null) {
            try {
                processRequest(message, exchange);
                if (exchange.isOneWay()) {
                    ServerProviderFactory.getInstance(message).clearThreadLocalProxies();
                }
            } catch (Fault ex) {
                convertExceptionToResponseIfPossible(ex.getCause(), message);
            } catch (RuntimeException ex) {
                convertExceptionToResponseIfPossible(ex, message);
            } catch (IOException ex) {
                convertExceptionToResponseIfPossible(ex, message); // This is line 98
            }
        }
```
we ignore (via @FFDCIgnore annotation) the Fault and RuntimeException, but when we added the catch block for IOException about three years ago, we didn't add it the ignore list.
So it seems like JsonMappingException is wrapped by a JsonParseException which is a subclass of IOException .  This should be a quick fix."

**Comment by andymc12** [comment]
Yes, this looks like an oversight when we made a CXF upgrade a few years ago. The CXF upgrade added the catch block for `IOException` (of which `JsonParseException` is a subclass).  We process the IOException the same way that we process other exceptions, but for some reason we did not exclude the FFDC report for that exception.  We did exclude it for the JAX-RS 2.0 version of the class, which further fuels my belief that this was an oversight.

Since this is a release bug, the net is that users of Open Liberty and the `jaxrs-2.1` feature over the past 3 years may have seen FFDC output when handling an IOException thrown from their JAX-RS resource or provider classes. These FFDC reports should not have been output, and after applying this fix they will no longer be output.
