### ISSUE TITLE
Kernel boot FAT failing at Java 17

### ISSUE THREAD

**Issue by gjwatts** [OpenLiberty/open-liberty#18245]
From @tjwatson 
While starting the embedded server we see messages like this:
```
[8/18/21, 9:09:35:063 CDT] 0000003e com.ibm.ws.logging.internal.impl.IncidentImpl                I FFDC1015I: An FFDC Incident has been created: "org.osgi.framework.BundleException: An error occurred trying to read the bundle com.ibm.ws.kernel.launch.internal.ProvisionerImpl 326" at ffdc_21.08.18_09.09.35.0.log
[8/18/21, 9:09:35:111 CDT] 0000003e com.ibm.ws.logging.internal.impl.IncidentImpl                I FFDC1015I: An FFDC Incident has been created: "org.osgi.framework.BundleException: An error occurred trying to read the bundle com.ibm.ws.kernel.launch.internal.ProvisionerImpl checkInstallStatus" at ffdc_21.08.18_09.09.35.1.log
```

With FFDC exceptions like this:
```
Stack Dump = org.osgi.framework.BundleException: An error occurred trying to read the bundle
    at org.eclipse.osgi.storage.Storage.stageContent0(Storage.java:1154)
    at org.eclipse.osgi.storage.Storage.stageContent(Storage.java:1115)
    at org.eclipse.osgi.storage.Storage$4.getContent(Storage.java:781)
    at org.eclipse.osgi.storage.Storage.install(Storage.java:713)
    at org.eclipse.osgi.internal.framework.BundleContextImpl.installBundle(BundleContextImpl.java:182)
    at com.ibm.ws.kernel.launch.internal.ProvisionerImpl.installKernelBundle(ProvisionerImpl.java:280)
    at com.ibm.ws.kernel.launch.internal.ProvisionerImpl.installBundles(ProvisionerImpl.java:241)
    at com.ibm.ws.kernel.launch.internal.ProvisionerImpl.initialProvisioning(ProvisionerImpl.java:94)
    at com.ibm.ws.kernel.launch.internal.FrameworkManager.innerLaunchFramework(FrameworkManager.java:448)
    at com.ibm.ws.kernel.launch.internal.FrameworkManager.launchFramework(FrameworkManager.java:284)
    at com.ibm.ws.kernel.launch.internal.LauncherDelegateImpl.doFrameworkLaunch(LauncherDelegateImpl.java:114)
    at com.ibm.ws.kernel.launch.internal.LauncherDelegateImpl.launchFramework(LauncherDelegateImpl.java:100)
    at com.ibm.ws.kernel.boot.internal.KernelBootstrap.go(KernelBootstrap.java:214)
    at com.ibm.ws.kernel.boot.EmbeddedServerImpl$ServerTask.run(EmbeddedServerImpl.java:529)
    at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.io.IOException
    at org.eclipse.osgi.storage.url.reference.ReferenceInputStream.read(ReferenceInputStream.java:37)
    at java.base/java.io.InputStream.read(InputStream.java:284)
    at org.eclipse.osgi.storage.StorageUtil.readFile(StorageUtil.java:81)
    at org.eclipse.osgi.storage.Storage.stageContent0(Storage.java:1147)
    ... 14 more
```

Turns out this is caused by https://bugs.eclipse.org/bugs/show_bug.cgi?id=574236 and the fix for this will come with the next release of Equinox 2021-09.  

A workaround for the FAT is to pass the argument `--add-opens java.base/java.net=ALL-UNNAMED` when starting the JVM.

**Comment by gjwatts** [comment]
Fixed by #18283 which has been merged.  Closing.
