### ISSUE TITLE
NullPointerException if used with mpMetrics 3.0

### ISSUE THREAD

**Issue by dakr0013** [OpenLiberty/open-liberty#18299]
If i use `<feature>microProfile-4.0</feature>` it includes mpMetrics 3.0. This causes a NullPointerException after i call a secured endpoint without any jwt. This results in a status code 500 instead of 401. If i supply a valid jwt everything is ok.

Reproduction:
1. Add `<feature>microProfile-4.0</feature>` in server.xml
2. Startup system-service with `mvn liberty:dev`
3. Acces this url without a Authorization header: http://localhost:8080/system/properties/username

Console output:
```
[INFO] [AUDIT   ] CWWKZ0003I: Die Anwendung system wurde nach 1,886 Sekunden aktualisiert.
[INFO] [FEHLER  ] CWWKS5522E: Das MicroProfile-JWT-Feature kann die Authentifizierung nicht durchführen, weil in der Anforderung MicroProfile-JWT gefunden wurde.
[INFO] [WARNUNG ] CWPMI2005W: Der MicroProfile Metrics-Ausnahmemapper hat eine nicht behandelte Ausnahme der JAX-RS-Anwendung entdeckt und verarbeitet.
[INFO]                                                                                                                java.lang.NullPointerException
[INFO]  at java.base/java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
[INFO]  at com.ibm.ws.jaxrs.monitor.JaxRsMonitorFilter.getMetricInfo(JaxRsMonitorFilter.java:270)
[INFO]  at [internal classes]
[INFO]
[INFO] [WARNUNG ] Interceptor for {http://system.guides.openliberty.io/}SystemResource has thrown exception, unwinding now
[INFO] org.apache.cxf.interceptor.Fault
```

**Comment by gkwan-ibm** [comment]
I could reproduce the problem too.
- `git clone https://github.com/openliberty/guide-microprofile-jwt.git`
- `cd guide-microprofile-jwt/finish/system`
- update `system/src/main/liberty/config/server.xml` by adding `<feature>mpMetrics-3.0</feature>` 
- `mvn liberty:dev`
- visit http://localhost:8080/system/properties/username 
- will get
``` 
[INFO] [ERROR   ] CWWKS5522E: The MicroProfile JWT feature cannot perform authentication because a MicroProfile JWT cannot be found in the request.
[INFO] [WARNING ] CWPMI2005W: The MicroProfile Metrics exception mapper detected and is handling an unhandled exception from the JAX-RS application. 
[INFO]                                                                                                                java.lang.NullPointerException
[INFO] 	at java.base/java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
[INFO] 	at com.ibm.ws.jaxrs.monitor.JaxRsMonitorFilter.getMetricInfo(JaxRsMonitorFilter.java:270)
[INFO] 	at [internal classes]
[INFO] 
[INFO] [WARNING ] Interceptor for {http://system.guides.openliberty.io/}SystemResource has thrown exception, unwinding now
[INFO] org.apache.cxf.interceptor.Fault
```

`CWWKS5522E` is expected.
Is `CWPMI2005W` for NPE expected? Or is it an real issue?

I redirected this issue to open-liberty repository.

**Comment by gkwan-ibm** [comment]
@Channyboy

**Comment by gkwan-ibm** [comment]
@teddyjtorres

**Comment by andymc12** [comment]
@gkwan-ibm @dakr0013 - could one of you post the full stack trace from the messages.log file?  I would like to see the lines that are obfuscated by the `at [internal classes]` line.  Thanks!

**Comment by gkwan-ibm** [comment]
```
[2021-08-23, 18:10:50:563 EDT] 00000030 oprofile.metrics.internal.monitor.MetricsJaxRsEMCallbackImpl W CWPMI2005W: The MicroProfile Metrics exception mapper detected and is handling an unhandled exception from the JAX-RS application. 
                                                                                                               java.lang.NullPointerException
	at java.base/java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
	at com.ibm.ws.jaxrs.monitor.JaxRsMonitorFilter.getMetricInfo(JaxRsMonitorFilter.java:270)
	at com.ibm.ws.jaxrs.monitor.JaxRsMonitorFilter.createKeyPrefix(JaxRsMonitorFilter.java:261)
	at com.ibm.ws.jaxrs.monitor.JaxRsMonitorFilter.filter(JaxRsMonitorFilter.java:134)
	at org.apache.cxf.jaxrs.utils.JAXRSUtils.runContainerResponseFilters(JAXRSUtils.java:1959)
	at org.apache.cxf.jaxrs.interceptor.JAXRSOutInterceptor.serializeMessage(JAXRSOutInterceptor.java:176)
	at org.apache.cxf.jaxrs.interceptor.JAXRSOutInterceptor.processResponse(JAXRSOutInterceptor.java:124)
	at org.apache.cxf.jaxrs.interceptor.JAXRSOutInterceptor.handleMessage(JAXRSOutInterceptor.java:85)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.interceptor.OutgoingChainInterceptor.handleMessage(OutgoingChainInterceptor.java:90)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.phase.PhaseInterceptorChain.doInterceptStartingAt(PhaseInterceptorChain.java:478)
	at org.apache.cxf.jaxrs.interceptor.JAXRSInInterceptor.handleMessage(JAXRSInInterceptor.java:106)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:123)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:274)
	at com.ibm.ws.jaxrs20.endpoint.AbstractJaxRsWebEndpoint.invoke(AbstractJaxRsWebEndpoint.java:137)
	at com.ibm.websphere.jaxrs.server.IBMRestServlet.handleRequest(IBMRestServlet.java:146)
	at com.ibm.websphere.jaxrs.server.IBMRestServlet.doGet(IBMRestServlet.java:112)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:686)
	at com.ibm.websphere.jaxrs.server.IBMRestServlet.service(IBMRestServlet.java:96)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1258)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:746)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:443)
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.invokeTarget(WebAppFilterChain.java:183)
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:94)
	at com.ibm.ws.security.jaspi.JaspiServletFilter.doFilter(JaspiServletFilter.java:56)
	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:201)
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:91)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.doFilter(WebAppFilterManager.java:1002)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1140)
	at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:5049)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.handleRequest(DynamicVirtualHost.java:314)
	at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:1007)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:279)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1159)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:428)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:387)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:566)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:500)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:360)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.ready(HttpInboundLink.java:327)
	at com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.sendToDiscriminators(NewConnectionInitialReadCallback.java:167)
	at com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.complete(NewConnectionInitialReadCallback.java:75)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:504)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueManager.java:574)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:958)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:1047)
	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:238)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:836)
```

**Comment by jim-krueger** [comment]
I consider this NPE to be a bug.  I am investigating how MPMetrics needs to account for this.

**Comment by Channyboy** [comment]
Seems like the NPE is being thrown since the `appName` being passed is `null` that we try to retrive from `ComponentMetaData`.
So without a valid jwt it returns a null appname? And valid jwt it retrieves a value?

**Comment by pugmas** [comment]
Since OpenLiberty 21.0.0.8 we see this NPE when @RolesAllowed(...) is not fulfilled by the JWT.  
-> Expected: 403, Actual: 500

Something has changed in the handling of WebApplicationExceptions. 
So CWPMI2005W cannot be treated like in: https://www.ibm.com/docs/en/was-liberty/core?topic=messages-cwpmi

**Comment by mbroz2** [comment]
@jim-krueger plz update the description using the [bug report template](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=&labels=release+bug&template=bug_report.md&title=)
