### ISSUE TITLE
Jakarta EE9:JAX-RS:Application endpoints are failing with 404's after transforming from EE8 runtime 

### ISSUE THREAD

**Issue by jagraj** [OpenLiberty/open-liberty#18461]
**Describe the bug**
My application is transformed to Jakarta EE9 runtime from JEE8 by using transformer tool. When I try to run my application with the latest beta and all my jax-rs transactions are failing after debugging more with the development team here is the problem that we found.

Jax-rs application defined  @ApplicationPath(value="/rest/*") and this has been working fine with EE8 runtime but it fails with Jakarta EE9 runtime and I got into following failure. After more debugging with the development team and we found out that RESTEASY runtime does not support `"/rest/*"` path and we are able to hit the application with this path `value="/rest"`. 

```
[8/20/21 16:42:19:909 EDT] 00000022 id=00000000 org.apache.wink.client.internal.ResourceImpl                 3 invoke The client response returned the following error code: 404
[8/20/21 16:42:19:915 EDT] 00000022 id=00000000 om.ibm.websphere.svt.gs.gsjsfweb.utils.GSJSFExceptionHandler E handle Severe Error is jakarta.el.ELException: org.apache.wink.client.ClientWebException
[8/20/21 16:42:19:920 EDT] 00000022 id=00000000 SystemErr                                                    R org.apache.myfaces.view.facelets.el.ContextAwareELException: jakarta.el.ELException: org.apache.wink.client.ClientWebException
[8/20/21 16:42:19:925 EDT] 00000022 id=00000000 SystemErr                                                    R 	at org.apache.myfaces.view.facelets.el.ContextAwareTagMethodExpression.invoke(ContextAwareTagMethodExpression.java:108)
[8/20/21 16:42:19:988 EDT] 00000022 id=00000000 SystemErr                                                    R 	at org.apache.myfaces.application.ActionListenerImpl.processAction(ActionListenerImpl.java:74)
[8/20/21 16:42:19:988 EDT] 00000022 id=00000000 SystemErr                                                    R 	at jakarta.faces.component.UICommand.broadcast(UICommand.java:122)
[8/20/21 16:42:19:989 EDT] 00000022 id=00000000 SystemErr                                                    R 	at jakarta.faces.component.UIViewRoot._broadcastAll(UIViewRoot.java:1255)
[8/20/21 16:42:19:990 EDT] 00000022 id=00000000 SystemErr                                                    R 	at jakarta.faces.component.UIViewRoot.broadcastEvents(UIViewRoot.java:420)
[8/20/21 16:42:19:990 EDT] 00000022 id=00000000 SystemErr                                                    R 	at jakarta.faces.component.UIViewRoot._process(UIViewRoot.java:1741)
[8/20/21 16:42:19:991 EDT] 00000022 id=00000000 SystemErr                                                    R 	at jakarta.faces.component.UIViewRoot.processApplication(UIViewRoot.java:935)
[8/20/21 16:42:19:991 EDT] 00000022 id=00000000 SystemErr                                                    R 	at org.apache.myfaces.lifecycle.InvokeApplicationExecutor.execute(InvokeApplicationExecutor.java:42)
[8/20/21 16:42:19:992 EDT] 00000022 id=00000000 SystemErr                                                    R 	at org.apache.myfaces.lifecycle.LifecycleImpl.executePhase(LifecycleImpl.java:195)
[8/20/21 16:42:19:993 EDT] 00000022 id=00000000 SystemErr                                                    R 	at org.apache.myfaces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:142)
[8/20/21 16:42:19:993 EDT] 00000022 id=00000000 SystemErr                                                    R 	at jakarta.faces.webapp.FacesServlet.service(FacesServlet.java:204)
[8/20/21 16:42:19:994 EDT] 00000022 id=00000000 SystemErr                                                    R 	at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1258)
[8/20/21 16:42:19:994 EDT] 00000022 id=00000000 SystemErr                                                    R 	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:746)
[8/20/21 16:42:19:995 EDT] 00000022 id=00000000 SystemErr                                                    R 	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:443)
[8/20/21 16:42:19:995 EDT] 00000022 id=00000000 SystemErr                                                    R 	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.invokeTarget(WebAppFilterChain.java:183)
[8/20/21 16:42:19:996 EDT] 00000022 id=00000000 SystemErr                                                    R 	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:94)
[8/20/21 16:42:19:996 EDT] 00000022 id=00000000 SystemErr                                                    R 	at com.ibm.ws.security.jaspi.JaspiServletFilter.doFilter(JaspiServletFilter.java:56)
[8/20/21 16:42:19:996 EDT] 00000022 id=00000000 SystemErr                                                    R 	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:201)
[8/20/21 16:42:19:999 EDT] 00000022 id=00000000 SystemErr                                                    R 	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:91)
[8/20/21 16:42:20:003 EDT] 00000022 id=00000000 SystemErr                                                    R 	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.doFilter(WebAppFilterManager.java:1002)
[8/20/21 16:42:20:004 EDT] 00000022 id=00000000 SystemErr                                                    R 	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1140)
[8/20/21 16:42:20:005 EDT] 00000022 id=00000000 SystemErr                                                    R 	at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:5049)
[8/20/21 16:42:20:005 EDT] 00000022 id=00000000 SystemErr                                                    R 	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.handleRequest(DynamicVirtualHost.java:314)
[8/20/21 16:42:20:005 EDT] 00000022 id=00000000 SystemErr                                                    R 	at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:1007)
[8/20/21 16:42:20:007 EDT] 00000022 id=00000000 SystemErr                                                    R 	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:279)
[8/20/21 16:42:20:008 EDT] 00000022 id=00000000 SystemErr                                                    R 	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1159)
[8/20/21 16:42:20:008 EDT] 00000022 id=00000000 SystemErr                                                    R 	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:428)
[8/20/21 16:42:20:009 EDT] 00000022 id=00000000 SystemErr                                                    R 	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:387)
[8/20/21 16:42:20:010 EDT] 00000022 id=00000000 SystemErr                                                    R 	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:566)
[8/20/21 16:42:20:010 EDT] 00000022 id=00000000 SystemErr                                                    R 	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:500)
[8/20/21 16:42:20:010 EDT] 00000022 id=00000000 SystemErr                                                    R 	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:360)
[8/20/21 16:42:20:011 EDT] 00000022 id=00000000 SystemErr                                                    R 	at com.ibm.ws.http.channel.internal.inbound.HttpICLReadCallback.complete(HttpICLReadCallback.java:70)
[8/20/21 16:42:20:011 EDT] 00000022 id=00000000 SystemErr                                                    R 	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:504)
[8/20/21 16:42:20:011 EDT] 00000022 id=00000000 SystemErr                                                    R 	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueManager.java:574)
[8/20/21 16:42:20:012 EDT] 00000022 id=00000000 SystemErr                                                    R 	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:958)
[8/20/21 16:42:20:012 EDT] 00000022 id=00000000 SystemErr                                                    R 	at com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:1047)
[8/20/21 16:42:20:013 EDT] 00000022 id=00000000 SystemErr                                                    R 	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:238)
[8/20/21 16:42:20:013 EDT] 00000022 id=00000000 SystemErr                                                    R 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[8/20/21 16:42:20:013 EDT] 00000022 id=00000000 SystemErr                                                    R 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[8/20/21 16:42:20:014 EDT] 00000022 id=00000000 SystemErr                                                    R 	at java.lang.Thread.run(Thread.java:748)
[8/20/21 16:42:20:015 EDT] 00000022 id=00000000 SystemErr                                                    R Caused by: jakarta.el.ELException: org.apache.wink.client.ClientWebException
[8/20/21 16:42:20:016 EDT] 00000022 id=00000000 SystemErr                                                    R 	at org.apache.el.parser.AstValue.invoke(AstValue.java:258)
[8/20/21 16:42:20:016 EDT] 00000022 id=00000000 SystemErr                                                    R 	at org.apache.el.MethodExpressionImpl.invoke(MethodExpressionImpl.java:267)
[8/20/21 16:42:20:017 EDT] 00000022 id=00000000 SystemErr                                                    R 	at org.apache.myfaces.view.facelets.el.ContextAwareTagMethodExpression.invoke(ContextAwareTagMethodExpression.java:96)
[8/20/21 16:42:20:017 EDT] 00000022 id=00000000 SystemErr                                                    R 	... 39 more
[8/20/21 16:42:20:018 EDT] 00000022 id=00000000 SystemErr                                                    R Caused by: org.apache.wink.client.ClientWebException
[8/20/21 16:42:20:018 EDT] 00000022 id=00000000 SystemErr                                                    R 	at org.apache.wink.client.internal.ResourceImpl.invoke(ResourceImpl.java:232)
[8/20/21 16:42:20:019 EDT] 00000022 id=00000000 SystemErr                                                    R 	at org.apache.wink.client.internal.ResourceImpl.invoke(ResourceImpl.java:201)
[8/20/21 16:42:20:019 EDT] 00000022 id=00000000 SystemErr                                                    R 	at org.apache.wink.client.internal.ResourceImpl.get(ResourceImpl.java:306)
[8/20/21 16:42:20:021 EDT] 00000022 id=00000000 SystemErr                                                    R 	at com.ibm.websphere.svt.gs.gsjsfweb.utils.GarageSaleManagedBeanUtil.getAllStatesTaxInfo(GarageSaleManagedBeanUtil.java:296)
[8/20/21 16:42:20:023 EDT] 00000022 id=00000000 SystemErr                                                    R 	at com.ibm.websphere.svt.gs.gsjsfweb.utils.GarageSaleManagedBeanUtil.getTaxRate(GarageSaleManagedBeanUtil.java:347)
[8/20/21 16:42:20:024 EDT] 00000022 id=00000000 SystemErr                                                    R 	at com.ibm.websphere.svt.gs.gsjsfweb.GarageSaleJSFActions.addToCart(GarageSaleJSFActions.java:357)
[8/20/21 16:42:20:024 EDT] 00000022 id=00000000 SystemErr                                                    R 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[8/20/21 16:42:20:032 EDT] 00000022 id=00000000 SystemErr                                                    R 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[8/20/21 16:42:20:035 EDT] 00000022 id=00000000 SystemErr                                                    R 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[8/20/21 16:42:20:038 EDT] 00000022 id=00000000 SystemErr                                                    R 	at java.lang.reflect.Method.invoke(Method.java:498)
[8/20/21 16:42:20:038 EDT] 00000022 id=00000000 SystemErr                                                    R 	at org.apache.el.parser.AstValue.invoke(AstValue.java:247)
[8/20/21 16:42:20:039 EDT] 00000022 id=00000000 SystemErr                                                    R 	... 41 more
```

**Steps to Reproduce**
1. Tranform EE8 application to Jakarta EE9 version using transformer too.
2. If EE8 application had @ApplicationPath(value="/rest/*") defined in Application class.
3. When we try to access jax-rs endpoints then we are getting 404 errors. 

**Expected behavior**
After transforming application from EE8 to Jakarta EE9 version then application should work without changing changing the source.

**Diagnostic information:**
 - OpenLiberty Version:  Open Liberty 21.0.0.9-beta/wlp-1.0.55.cl210820210727-1323
 - Java Version: [OpenJDK 64-Bit Server VM, version 1.8.0_292-b10]
 - server.xml configuration (WITHOUT sensitive information like passwords)
 - If it would be useful, upload the messages.log file found in `$WLP_OUTPUT_DIR/messages.log`

**Comment by jim-krueger** [comment]
Upon further review:  Resteasy appears to be taking a more strict view of the specification whereas CXF did not

This is what the spec says:

> If the Application subclass is annotated with @ApplicationPath, implementations are REQUIRED to use the value of this annotation appended with ”/*” to define a mapping for the added server.

This means that  `@ApplicationPath("/somePath")` is the equivalent of a web.xml servlet mapping of /somePath/*.

Therefore the wildcard characters should be removed from @ApplicationPath in SVT applications.

**Comment by jhanders34** [comment]
Jim, If this is the approach that we take, there needs to be documentation stating that customers would need to make this change and maybe we also should work with @cthigh's team to get an update to the migration tools to detect this configuration and instruct customers to change it to remove the `/*` from their ApplicationPath's.

**Comment by jhanders34** [comment]
@andymc12 and @jim-krueger, If not updating RESTEasy to handle an ApplicationPath like what CXF does, can we get the doc issue updated to include this scenario?  Is there an issue for migration tool kit for these differences?

**Comment by jim-krueger** [comment]
@jhanders34 I had already updated our [Migration Issue](https://github.com/OpenLiberty/open-liberty/issues/12742) with this so it will be included.  Is this sufficient to close this?

**Comment by jhanders34** [comment]
Thanks @jim-krueger.  When I brought that up previously nothing was updated in this issue to state that.  I think it is sufficient to close out this issue, but it is really your and @jagraj 's call.

**Comment by jim-krueger** [comment]
Thanks @jhanders34,  @jagraj  per our call I will close this issue now.  Please feel free to re-open if you need to.
