### ISSUE TITLE
MP Config 3.0 integration with RESTful WS 3.0 (and potentially MP Rest Client 3.0)

### ISSUE THREAD

**Issue by andymc12** [OpenLiberty/open-liberty#18476]
PR #18454 resolved a configuration conflict with RESTEasy and MP Config 3.0. RESTEasy is designed with it's own configuration mechanism, but will use MP Config if it is available.  We need a solution that ensure that RESTEasy is properly configured regardless of whether MP Config is enabled or not.

The solution should ensure that MP Rest Client works properly with MP Config as well - as mandated by the MP Rest Client spec.

This issue should be a requirement before shipping MP 5.0 (issue #16991) and possibly MP Config 3.0 (issue #17766) and MP Rest Client 3.0 (issue #17947).  Although it is not a blocker for JAX-RS 3.0 (aka RESTful WS 3.0 - issue #11803), it may be impacted - and the solution which may ship after EE9/9.1 should not break zero migration compatibility.

**Comment by tevans78** [comment]
When I re-enabled the existing MP Config integration here
https://github.com/OpenLiberty/open-liberty/blob/53c8c61825854eb0f6b8be2c7c338bda4b908ff9/dev/io.openliberty.org.jboss.resteasy.common/src/org/jboss/resteasy/spi/config/DefaultConfiguration.java#L56

I actually got a failure from MP Metrics
```
Stack Dump = java.lang.IllegalStateException: The following values are either null or empty - fullyQualifiedClassName: null fullMethodSignature: null
	at io.openliberty.microprofile.metrics.internal.monitor.MetricsJaxRsEMCallbackImpl.resolveSimpleTimerClassMethodTags(MetricsJaxRsEMCallbackImpl.java:120)
	at io.openliberty.microprofile.metrics.internal.monitor.MetricsJaxRsEMCallbackImpl.onDefaultMappedException(MetricsJaxRsEMCallbackImpl.java:81)
	at com.ibm.ws.jaxrs.defaultexceptionmapper.DefaultExceptionMapper.toResponse(DefaultExceptionMapper.java:52)
	at org.jboss.resteasy.core.ExceptionHandler.executeExceptionMapper(ExceptionHandler.java:137)
	at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:322)
	at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:218)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:258)
	at <unknown class>.run(Unknown Source)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
	at <unknown class>.get(Unknown Source)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:255)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:60)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:55)
	at <unknown class>.service(HttpServlet.java:587)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1258)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:746)
```
