### ISSUE TITLE
NPE in JAXRS Metrics Interceptor when unauthorized (403) and Security is enforced via @RolesAllowed

### ISSUE THREAD

**Issue by jonasrutishauser** [OpenLiberty/open-liberty#18514]
**Describe the bug**
If the Security on a JAX-RS endpoint is enforced via `@RolesAllowed` and the requestor does not have the required role the response should be a HTTP 403. With Open Liberty 21.0.0.9 there is a HTTP 500 response as there is a NPE in the metrics interceptor.
```
Interceptor for {http://resource.service.war.openliberty.subscriber.admin.metro.css.ch/}AdminEventResource has thrown exception, unwinding now
org.apache.cxf.interceptor.Fault: null
        at org.apache.cxf.jaxrs.interceptor.JAXRSOutInterceptor.handleWriteException(JAXRSOutInterceptor.java:402) ~[com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2_1.0.56.jar:3.4.3]
        at org.apache.cxf.jaxrs.interceptor.JAXRSOutInterceptor.serializeMessage(JAXRSOutInterceptor.java:178) ~[com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2_1.0.56.jar:3.4.3]
        at org.apache.cxf.jaxrs.interceptor.JAXRSOutInterceptor.handleWriteException(JAXRSOutInterceptor.java:404) ~[com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2_1.0.56.jar:3.4.3]
        at org.apache.cxf.jaxrs.interceptor.JAXRSOutInterceptor.serializeMessage(JAXRSOutInterceptor.java:178) ~[com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2_1.0.56.jar:3.4.3]
        at org.apache.cxf.jaxrs.interceptor.JAXRSOutInterceptor.processResponse(JAXRSOutInterceptor.java:124) ~[com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2_1.0.56.jar:3.4.3]
        at org.apache.cxf.jaxrs.interceptor.JAXRSOutInterceptor.handleMessage(JAXRSOutInterceptor.java:85) ~[com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2_1.0.56.jar:3.4.3]
        at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308) [com.ibm.ws.org.apache.cxf.cxf.core.3.2_1.0.56.jar:3.4.3]
        at org.apache.cxf.interceptor.OutgoingChainInterceptor.handleMessage(OutgoingChainInterceptor.java:90) [com.ibm.ws.org.apache.cxf.cxf.core.3.2_1.0.56.jar:3.4.3]
        at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308) [com.ibm.ws.org.apache.cxf.cxf.core.3.2_1.0.56.jar:3.4.3]
        at org.apache.cxf.phase.PhaseInterceptorChain.doInterceptStartingAt(PhaseInterceptorChain.java:478) [com.ibm.ws.org.apache.cxf.cxf.core.3.2_1.0.56.jar:3.4.3]
        at org.apache.cxf.jaxrs.interceptor.JAXRSInInterceptor.handleMessage(JAXRSInInterceptor.java:106) [com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2_1.0.56.jar:3.4.3]
        at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308) [com.ibm.ws.org.apache.cxf.cxf.core.3.2_1.0.56.jar:3.4.3]
        at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:123) [com.ibm.ws.org.apache.cxf.cxf.core.3.2_1.0.56.jar:3.4.3]
        at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:277) [com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.3.2_1.0.56.jar:3.4.3]
        at com.ibm.ws.jaxrs20.endpoint.AbstractJaxRsWebEndpoint.invoke(AbstractJaxRsWebEndpoint.java:137) [com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2_1.0.56.jar:3.4.3]
        at com.ibm.websphere.jaxrs.server.IBMRestServlet.handleRequest(IBMRestServlet.java:146) [com.ibm.ws.jaxrs.2.0.server_1.0.56.jar:?]
        at com.ibm.websphere.jaxrs.server.IBMRestServlet.doGet(IBMRestServlet.java:112) [com.ibm.ws.jaxrs.2.0.server_1.0.56.jar:?]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:686) [com.ibm.websphere.javaee.servlet.4.0_1.0.56.jar:?]
        at com.ibm.websphere.jaxrs.server.IBMRestServlet.service(IBMRestServlet.java:96) [com.ibm.ws.jaxrs.2.0.server_1.0.56.jar:?]
        at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1258) [com.ibm.ws.webcontainer_1.1.56.jar:?]
        at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:746) [com.ibm.ws.webcontainer_1.1.56.jar:?]
        at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:443) [com.ibm.ws.webcontainer_1.1.56.jar:?]
        at com.ibm.ws.webcontainer.filter.WebAppFilterChain.invokeTarget(WebAppFilterChain.java:183) [com.ibm.ws.webcontainer_1.1.56.jar:?]
        at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:94) [com.ibm.ws.webcontainer_1.1.56.jar:?]
        at com.ibm.ws.security.jaspi.JaspiServletFilter.doFilter(JaspiServletFilter.java:56) [com.ibm.ws.security.jaspic.1.1_1.0.56.jar:?]
        at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:201) [com.ibm.ws.webcontainer_1.1.56.jar:?]
        at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:91) [com.ibm.ws.webcontainer_1.1.56.jar:?]
        at com.ibm.ws.webcontainer.filter.WebAppFilterManager.doFilter(WebAppFilterManager.java:1002) [com.ibm.ws.webcontainer_1.1.56.jar:?]
        at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1140) [com.ibm.ws.webcontainer_1.1.56.jar:?]
        at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:5049) [com.ibm.ws.webcontainer_1.1.56.jar:?]
        at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.handleRequest(DynamicVirtualHost.java:314) [com.ibm.ws.webcontainer_1.1.56.jar:?]
        at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:1007) [com.ibm.ws.webcontainer_1.1.56.jar:?]
        at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:279) [com.ibm.ws.webcontainer_1.1.56.jar:?]
        at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1159) [com.ibm.ws.transport.http_1.0.56.jar:?]
        at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:428) [com.ibm.ws.transport.http_1.0.56.jar:?]
        at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:387) [com.ibm.ws.transport.http_1.0.56.jar:?]
        at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:566) [com.ibm.ws.transport.http_1.0.56.jar:?]
        at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:500) [com.ibm.ws.transport.http_1.0.56.jar:?]
        at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:360) [com.ibm.ws.transport.http_1.0.56.jar:?]
        at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.ready(HttpInboundLink.java:327) [com.ibm.ws.transport.http_1.0.56.jar:?]
        at com.ibm.ws.channel.ssl.internal.SSLConnectionLink.determineNextChannel(SSLConnectionLink.java:1100) [com.ibm.ws.channel.ssl_1.0.56.jar:?]
        at com.ibm.ws.channel.ssl.internal.SSLConnectionLink.readyInboundPostHandshake(SSLConnectionLink.java:757) [com.ibm.ws.channel.ssl_1.0.56.jar:?]
        at com.ibm.ws.channel.ssl.internal.SSLConnectionLink$MyHandshakeCompletedCallback.complete(SSLConnectionLink.java:427) [com.ibm.ws.channel.ssl_1.0.56.jar:?]
        at com.ibm.ws.channel.ssl.internal.SSLUtils.handleHandshake(SSLUtils.java:954) [com.ibm.ws.channel.ssl_1.0.56.jar:?]
        at com.ibm.ws.channel.ssl.internal.SSLHandshakeIOCallback.complete(SSLHandshakeIOCallback.java:85) [com.ibm.ws.channel.ssl_1.0.56.jar:?]
        at com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:504) [com.ibm.ws.channelfw_1.0.56.jar:?]
        at com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueManager.java:574) [com.ibm.ws.channelfw_1.0.56.jar:?]
        at com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:958) [com.ibm.ws.channelfw_1.0.56.jar:?]
        at com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:1047) [com.ibm.ws.channelfw_1.0.56.jar:?]
        at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:238) [com.ibm.ws.threading_1.1.56.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_201]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_201]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: java.lang.NullPointerException
        at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936) ~[?:1.8.0_201]
        at com.ibm.ws.jaxrs.monitor.JaxRsMonitorFilter.getMetricInfo(JaxRsMonitorFilter.java:270) ~[com.ibm.ws.jaxrs.2.x.monitor.component_1.0.56.jar:?]
        at com.ibm.ws.jaxrs.monitor.JaxRsMonitorFilter.createKeyPrefix(JaxRsMonitorFilter.java:261) ~[com.ibm.ws.jaxrs.2.x.monitor.component_1.0.56.jar:?]
        at com.ibm.ws.jaxrs.monitor.JaxRsMonitorFilter.filter(JaxRsMonitorFilter.java:134) ~[com.ibm.ws.jaxrs.2.x.monitor.component_1.0.56.jar:?]
        at org.apache.cxf.jaxrs.utils.JAXRSUtils.runContainerResponseFilters(JAXRSUtils.java:1959) ~[com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2_1.0.56.jar:3.4.3]
        at org.apache.cxf.jaxrs.interceptor.JAXRSOutInterceptor.serializeMessage(JAXRSOutInterceptor.java:176) ~[com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2_1.0.56.jar:3.4.3]
        ... 51 more
```

**Steps to Reproduce**
- Deploy a JAX-RS Resource annotated with `@RolesAllowed`.
- Enable `mpMetrics-3.0` and `jaxrs-2.1` in the `server.xml`
- Make a call where an unauthorised response is expected

**Expected behavior**
No exception is thrown and a HTTP 403 response is returned

**Diagnostic information:**
 - OpenLiberty Version: 21.0.0.9
 - Java Version: 1.8.0_201

**Comment by andymc12** [comment]
This is a duplicate of #18299 - and should be fixed by #18330.
