### ISSUE TITLE
JAX-RS 2.0 Asynch test fails with  "RESTEASY003765: Response is closed" message

### ISSUE THREAD

**Issue by rumanaHaque** [OpenLiberty/open-liberty#18586]
**Describe the bug**
Using my AcmeAnnuity SVT application - which has different jax-rs services, the jax-rs 2.0 Asych test fails with this "RESTEASY003765: Response is closed" message. The same application runs correctly as an ee8 application. But after transforming to jakarta ee9 application (along with the corresponding ee9 features in server.xml), this test fails.

If there is a stack trace, please include the FULL stack trace (without any `[internal classes]` lines in it). To find the full stack trace, you may need to check in `$WLP_OUTPUT_DIR/messages.log`

```
[9/16/21 9:53:40:830 PDT] 00000023 SystemOut                                                    O From CRUDContactQuickReturnSEU ...
[9/16/21 9:53:40:832 PDT] 00000023 SystemErr                                                    R java.lang.RuntimeException: RESTEASY003765: Response is closed.
[9/16/21 9:53:40:832 PDT] 00000023 SystemErr                                                    R 	at com.ibm.wssvt.acme.annuity.common.servicelookup.jaxrs.AnnuityJAXRS20AsyncServiceProxy.executeAsync(AnnuityJAXRS20AsyncServiceProxy.java:812)
[9/16/21 9:53:40:895 PDT] 00000023 SystemErr                                                    R 	at com.ibm.wssvt.acme.annuity.common.servicelookup.jaxrs.AnnuityJAXRS20AsyncServiceProxy.executeAndVerifyAsync(AnnuityJAXRS20AsyncServiceProxy.java:451)
[9/16/21 9:53:40:895 PDT] 00000023 SystemErr                                                    R 	at com.ibm.wssvt.acme.annuity.common.servicelookup.jaxrs.AnnuityJAXRS20AsyncServiceProxy.createContact(AnnuityJAXRS20AsyncServiceProxy.java:346)
[9/16/21 9:53:40:895 PDT] 00000023 SystemErr                                                    R 	at com.ibm.wssvt.acme.annuity.common.client.adapter.AbstractAnnuityServerAdapter.createContact(AbstractAnnuityServerAdapter.java:105)
[9/16/21 9:53:40:895 PDT] 00000023 SystemErr                                                    R 	at com.ibm.wssvt.acme.annuity.common.client.executionunit.specialunit.quickreturn.CRUDContactQuickReturnSEU.execute(CRUDContactQuickReturnSEU.java:33)
[9/16/21 9:53:40:895 PDT] 00000023 SystemErr                                                    R 	at com.ibm.wssvt.acme.common.client.ExecutionUnitRunner.runTheEU(ExecutionUnitRunner.java:249)
[9/16/21 9:53:40:911 PDT] 00000023 SystemErr                                                    R 	at com.ibm.wssvt.acme.common.client.ExecutionUnitRunner.executeRun(ExecutionUnitRunner.java:157)
[9/16/21 9:53:40:911 PDT] 00000023 SystemErr                                                    R 	at com.ibm.wssvt.acme.common.client.AcmeJavaClient.executeClient(AcmeJavaClient.java:87)
[9/16/21 9:53:40:911 PDT] 00000023 SystemErr                                                    R 	at com.ibm.wssvt.acme.annuity.web.AnnuityWebServlet.doPost(AnnuityWebServlet.java:135)
[9/16/21 9:53:40:911 PDT] 00000023 SystemErr                                                    R 	at com.ibm.wssvt.acme.annuity.web.AnnuityWebServlet.doGet(AnnuityWebServlet.java:84)
[9/16/21 9:53:40:911 PDT] 00000023 SystemErr                                                    R 	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:500)
[9/16/21 9:53:40:911 PDT] 00000023 SystemErr                                                    R 	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587)
[9/16/21 9:53:40:911 PDT] 00000023 SystemErr                                                    R 	at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1258)
[9/16/21 9:53:40:911 PDT] 00000023 SystemErr                                                    R 	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:746)
[9/16/21 9:53:40:911 PDT] 00000023 SystemErr                                                    R 	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:443)
[9/16/21 9:53:40:911 PDT] 00000023 SystemErr                                                    R 	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.invokeTarget(WebAppFilterChain.java:183)
[9/16/21 9:53:40:911 PDT] 00000023 SystemErr                                                    R 	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:94)
[9/16/21 9:53:40:911 PDT] 00000023 SystemErr                                                    R 	at com.ibm.ws.security.jaspi.JaspiServletFilter.doFilter(JaspiServletFilter.java:56)
[9/16/21 9:53:40:911 PDT] 00000023 SystemErr                                                    R 	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:201)
[9/16/21 9:53:40:911 PDT] 00000023 SystemErr                                                    R 	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:91)
[9/16/21 9:53:40:911 PDT] 00000023 SystemErr                                                    R 	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.doFilter(WebAppFilterManager.java:1002)
[9/16/21 9:53:40:911 PDT] 00000023 SystemErr                                                    R 	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1140)
[9/16/21 9:53:40:911 PDT] 00000023 SystemErr                                                    R 	at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:5049)
[9/16/21 9:53:40:911 PDT] 00000023 SystemErr                                                    R 	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.handleRequest(DynamicVirtualHost.java:314)
[9/16/21 9:53:40:911 PDT] 00000023 SystemErr                                                    R 	at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:1007)
[9/16/21 9:53:40:911 PDT] 00000023 SystemErr                                                    R 	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:279)
[9/16/21 9:53:40:911 PDT] 00000023 SystemErr                                                    R 	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1159)
[9/16/21 9:53:40:911 PDT] 00000023 SystemErr                                                    R 	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:428)
[9/16/21 9:53:40:911 PDT] 00000023 SystemErr                                                    R 	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:387)
[9/16/21 9:53:40:911 PDT] 00000023 SystemErr                                                    R 	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:566)
[9/16/21 9:53:40:911 PDT] 00000023 SystemErr                                                    R 	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:500)
[9/16/21 9:53:40:911 PDT] 00000023 SystemErr                                                    R 	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:360)
[9/16/21 9:53:40:911 PDT] 00000023 SystemErr                                                    R 	at com.ibm.ws.http.channel.internal.inbound.HttpICLReadCallback.complete(HttpICLReadCallback.java:70)
[9/16/21 9:53:40:911 PDT] 00000023 SystemErr                                                    R 	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:504)
[9/16/21 9:53:40:911 PDT] 00000023 SystemErr                                                    R 	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueManager.java:574)
[9/16/21 9:53:40:911 PDT] 00000023 SystemErr                                                    R 	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:958)
[9/16/21 9:53:40:911 PDT] 00000023 SystemErr                                                    R 	at com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:1047)
[9/16/21 9:53:40:911 PDT] 00000023 SystemErr                                                    R 	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:238)
[9/16/21 9:53:40:911 PDT] 00000023 SystemErr                                                    R 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
[9/16/21 9:53:40:927 PDT] 00000023 SystemErr                                                    R 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[9/16/21 9:53:40:927 PDT] 00000023 SystemErr                                                    R 	at java.lang.Thread.run(Thread.java:825)
```

**Steps to Reproduce**
Run the transformed jakarta ee9 version of the AcmeAnnuity Application. It will fail at this test.

```
Exception Class: java.lang.RuntimeException was encountered: 1 time(s). Ratio to total CRUD: 0.0 % (Exception Count/Total CURD)
Detail Data about this Exception:
Incident number: 1 in: Thread id: 1. Date: Wed Sep 15 11:09:46 PDT 2021. Execution Unit Desc: 20.1 - Run Async JAXRS-2.0 client - CRUDContactQuickReturn . Message: RESTEASY003765: Response is closed.

```
**Expected behavior**
This test should run successfully.

**Diagnostic information:**
 - OpenLiberty Version: 21.0.0.10 (wlp-1.0.57.cl211020210909-1900)
 - Java Version: [java.version = 1.8.0_301
java.runtime = Java(TM) SE Runtime Environment (8.0.6.35 - pwa6480sr6fp35-20210714_01(SR6 FP35))]
 - server.xml configuration (WITHOUT sensitive information like passwords)
 - If it would be useful, upload the messages.log file found in `$WLP_OUTPUT_DIR/messages.log`

**Additional context**
This works for the ee8 version of the application, but fails in the transformed ee9 version of the application.

**Comment by andymc12** [comment]
This looks like a bug in RESTEasy that closes the `Response` object when using an `InvocationCallback<Response>` - so when the client attempts to read the entity in the response in the `Future<Response>`, it throws the "Response is close" exception. This is a bug because the InvocationCallback doesn't read the entity, so the `Response` should still be open.

**Comment by rumanaHaque** [comment]
Tested a patch for this problem provided by Andy in my env- and patch was successful. I was able to run my test successfully using the patch.
