### ISSUE TITLE
JAX-RS 2.1 async requests fail to authenticate with a proxy server on Java 8

### ISSUE THREAD

**Issue by WhiteCat22** [OpenLiberty/open-liberty#18849]
**Describe the bug**  
A `jaxrs-2.1` **async** requests fail to authenticate with a proxy server when tunneling through a proxy to an HTTPS endpoint on Java 8. This functionality works on Java 11.

**Note:** This only affects async requests and ONLY on Java 8. Standard request work as expected.

We have a FAT test that tests this and is failing:
`JAXRS21ClientSSLProxyAuthTest.testTunnelThroughProxyToHTTPSEndpoint_ClientBuilder()`

```
junit.framework.AssertionFailedError: 2021-09-03-15:14:44:683 Real response is [Proxy Error]:javax.ws.rs.ClientErrorException: HTTP 407 Proxy Authentication Required and the expected response is one of [[Basic Resource]:helloRochester]
at com.ibm.ws.jaxrs21.client.fat.test.JAXRS21AbstractTest.runTestOnServer(JAXRS21AbstractTest.java:84)
at com.ibm.ws.jaxrs21.client.fat.test.JAXRS21ClientSSLProxyAuthTest.testTunnelThroughProxyToHTTPSEndpoint_ClientBuilder(JAXRS21ClientSSLProxyAuthTest.java:160)
at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:197)
at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:318)
at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:171)
at componenttest.rules.repeater.RepeatTests$CompositeRepeatTestActionStatement.evaluate(RepeatTests.java:143)
```

Note: This is labeled `release bug`, but this has never worked and we've never claimed support.

**Comment by jim-krueger** [comment]
This problem is also seen in testTunnelThroughProxyToHTTPSEndpoint_WebTarget as well:
```
junit.framework.AssertionFailedError: 2023-02-20-13:13:38:768 Real response is [Proxy Error]:jakarta.ws.rs.ClientErrorException: HTTP 407 Proxy Authentication Required and the expected response is one of [[Basic Resource]:helloRochester]
at com.ibm.ws.jaxrs21.client.fat.test.JAXRS21AbstractTest.runTestOnServer(JAXRS21AbstractTest.java:86)
at com.ibm.ws.jaxrs21.client.fat.test.JAXRS21ClientSSLProxyAuthTest.testTunnelThroughProxyToHTTPSEndpoint_WebTarget(JAXRS21ClientSSLProxyAuthTest.java:372)
at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:204)
at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:364)
at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:178)
at componenttest.rules.repeater.RepeatTests$CompositeRepeatTestActionStatement.evaluate(RepeatTests.java:145)
```
