### ISSUE TITLE
NPE when using socialLogin-1.0 and access-id for a user

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#18858]
**Describe the bug**  
Received `Error 500: java.lang.NullPointerException` when calling an REST endpoint secured with socialLogin-1.0 and access-id.  Token is added to the Authorization header.

If there is a stack trace, please include the FULL stack trace (without any `[internal classes]` lines in it). To find the full stack trace, you may need to check in `$WLP_OUTPUT_DIR/messages.log`

See below.

**Steps to Reproduce**  

server.xml
```
<server description="automation-healing-webhooks-rest">
    <featureManager>
        <feature>beanValidation-2.0</feature>
        <feature>mpConfig-2.0</feature>
        <feature>mpOpenAPI-2.0</feature>
        <feature>mpHealth-3.0</feature>
        <feature>jaxrs-2.1</feature>
        <feature>cdi-2.0</feature>
        <feature>socialLogin-1.0</feature>
        <feature>appSecurity-2.0</feature>
        <feature>transportSecurity-1.0</feature>
    </featureManager>

    <httpEndpoint
        id="defaultHttpEndpoint"
        enabled="true"
        host="*"
        httpPort="8080"
        httpsPort="8443"
        sslOptionsRef="endpointSSLOptions"
    >
        <compression types="+application/json" serverPreferredAlgorithm="gzip"/>
    </httpEndpoint>

    <sslOptions id="endpointSSLOptions" sslRef="webhookSSLConfig" />

    <sslDefault sslRef="webhookSSLConfig" />

    <ssl id="webhookSSLConfig" keyStoreRef="defaultKeyStore" trustStoreRef="webhookTruststore" />

    <keyStore id="webhookTruststore"
        password="${TRUSTSTORE_PASSWORD}"
        location="${TRUSTSTORE_PATH}"
    />

    <okdServiceLogin realmName="${OKD_SERVICE_LOGIN_REALM_NAME}" />
    
    <webApplication location="automation-healing-webhooks-rest.war" contextRoot="/webhooks" >
        <application-bnd>
            <security-role name="can_report_application_runtine_problems">
                <user access-id="user:/${OKD_SERVICE_LOGIN_REALM_NAME}/${SERVICE_ACCOUNT_NAME}" />
            </security-role>
        </application-bnd>
    </webApplication>
    
    <webContainer disableXPoweredBy="true"/>

</server>
```

This [doc page](https://www.ibm.com/docs/en/was-liberty/nd?topic=liberty-mapping-management-roles) suggests access-id for a user should be in this format `user:/<security realm name>/<user name>`.  If I remove the first slash and I don't get the NPE.  I got a 403 instead.  Probably another bug.

**Expected behavior**  

Expect to get 2xx response code.

**Diagnostic information:**  
 - OpenLiberty Version: 21.0.0.7
 - Affected feature(s): socialLogin-1.0
 - Java Version: IBM J9 VM, version 8.0.6.31 - pxa6480sr6fp31-20210510_01(SR6 FP31)
 - server.xml configuration (see above)
 - If it would be useful, upload the messages.log file found in `$WLP_OUTPUT_DIR/messages.log`

**Additional context**  

```
java.lang.NullPointerException
	at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1022)
	at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1017)
	at com.ibm.ws.security.appbnd.internal.authorization.AppBndAuthorizationTableService.updateMapsForAccessId(AppBndAuthorizationTableService.java:447)
	at com.ibm.ws.security.appbnd.internal.authorization.AppBndAuthorizationTableService.getRolesForAccessId(AppBndAuthorizationTableService.java:516)
	at com.ibm.ws.security.authorization.builtin.internal.BuiltinAuthorizationService.getRolesForAccessId(BuiltinAuthorizationService.java:274)
	at com.ibm.ws.security.authorization.builtin.internal.BuiltinAuthorizationService.useAppBndForAccessDecision(BuiltinAuthorizationService.java:351)
	at com.ibm.ws.security.authorization.builtin.internal.BuiltinAuthorizationService.isSubjectAuthorized(BuiltinAuthorizationService.java:333)
	at com.ibm.ws.security.authorization.builtin.internal.BuiltinAuthorizationService.isAuthorized(BuiltinAuthorizationService.java:161)
	at com.ibm.ws.webcontainer.security.WebAppSecurityCollaboratorImpl$3.run(WebAppSecurityCollaboratorImpl.java:1610)
	at com.ibm.ws.webcontainer.security.WebAppSecurityCollaboratorImpl$3.run(WebAppSecurityCollaboratorImpl.java:1601)
	at java.security.AccessController.doPrivileged(AccessController.java:682)
	at com.ibm.ws.webcontainer.security.WebAppSecurityCollaboratorImpl.isUserInRole(WebAppSecurityCollaboratorImpl.java:1601)
	at com.ibm.ws.webcontainer.security.WebAppSecurityCollaboratorImpl.isUserInRole(WebAppSecurityCollaboratorImpl.java:509)
	at com.ibm.ws.webcontainer.srt.SRTServletRequest.isUserInRole(SRTServletRequest.java:2805)
	at com.ibm.ws.jaxrs20.server.JaxRsHttpServletRequestAdapter.isUserInRole(JaxRsHttpServletRequestAdapter.java:1014)
	at com.ibm.ws.jaxrs20.security.LibertyAuthFilter.lambda$handleMessage$2(LibertyAuthFilter.java:98)
	at com.ibm.ws.jaxrs20.security.LibertyAuthFilter$$Lambda$603/0x00000000e0093500.test(Unknown Source)
	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:101)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:969)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:137)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:541)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:528)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:514)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:241)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:207)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:245)
	at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:460)
	at com.ibm.ws.security.authorization.util.RoleMethodAuthUtil.parseMethodSecurity(RoleMethodAuthUtil.java:56)
	at com.ibm.ws.jaxrs20.security.LibertyAuthFilter.handleMessage(LibertyAuthFilter.java:96)
	at com.ibm.ws.jaxrs20.security.LibertyAuthFilter.filter(LibertyAuthFilter.java:52)
	at org.apache.cxf.jaxrs.utils.JAXRSUtils.runContainerRequestFilters(JAXRSUtils.java:1921)
	at org.apache.cxf.jaxrs.interceptor.JAXRSInInterceptor.processRequest(JAXRSInInterceptor.java:272)
	at org.apache.cxf.jaxrs.interceptor.JAXRSInInterceptor.handleMessage(JAXRSInInterceptor.java:90)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:123)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:274)
	at com.ibm.ws.jaxrs20.endpoint.AbstractJaxRsWebEndpoint.invoke(AbstractJaxRsWebEndpoint.java:137)
	at com.ibm.websphere.jaxrs.server.IBMRestServlet.handleRequest(IBMRestServlet.java:146)
	at com.ibm.websphere.jaxrs.server.IBMRestServlet.doPost(IBMRestServlet.java:104)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:706)
	at com.ibm.websphere.jaxrs.server.IBMRestServlet.service(IBMRestServlet.java:96)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1258)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:746)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:443)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1227)
	at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:5049)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.handleRequest(DynamicVirtualHost.java:314)
	at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:1007)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:279)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1159)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:428)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:387)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:566)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:500)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:360)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.ready(HttpInboundLink.java:327)
	at com.ibm.ws.channel.ssl.internal.SSLConnectionLink.determineNextChannel(SSLConnectionLink.java:1100)
	at com.ibm.ws.channel.ssl.internal.SSLConnectionLink$MyReadCompletedCallback.complete(SSLConnectionLink.java:675)
	at com.ibm.ws.channel.ssl.internal.SSLReadServiceContext$SSLReadCompletedCallback.complete(SSLReadServiceContext.java:1824)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:504)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueManager.java:574)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:958)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:1047)
	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:238)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:822)

[10/5/21 0:46:47:874 UTC] 0000003b id=         .apache.cxf.cxf.core.3.2:1.0.54.cl210720210629-1900(id=203)] W Exception in handleFault on interceptor org.apache.cxf.jaxrs.interceptor.JAXRSDefaultFaultOutInterceptor@79e581fa
org.apache.cxf.interceptor.Fault
	at org.apache.cxf.interceptor.AbstractFaultChainInitiatorObserver.onMessage(AbstractFaultChainInitiatorObserver.java:75)
	at org.apache.cxf.phase.PhaseInterceptorChain.wrapExceptionAsFault(PhaseInterceptorChain.java:374)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:332)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:123)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:274)
	at com.ibm.ws.jaxrs20.endpoint.AbstractJaxRsWebEndpoint.invoke(AbstractJaxRsWebEndpoint.java:137)
	at com.ibm.websphere.jaxrs.server.IBMRestServlet.handleRequest(IBMRestServlet.java:146)
	at com.ibm.websphere.jaxrs.server.IBMRestServlet.doPost(IBMRestServlet.java:104)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:706)
	at com.ibm.websphere.jaxrs.server.IBMRestServlet.service(IBMRestServlet.java:96)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1258)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:746)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:443)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1227)
	at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:5049)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.handleRequest(DynamicVirtualHost.java:314)
	at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:1007)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:279)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1159)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:428)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:387)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:566)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:500)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:360)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.ready(HttpInboundLink.java:327)
	at com.ibm.ws.channel.ssl.internal.SSLConnectionLink.determineNextChannel(SSLConnectionLink.java:1100)
	at com.ibm.ws.channel.ssl.internal.SSLConnectionLink$MyReadCompletedCallback.complete(SSLConnectionLink.java:675)
	at com.ibm.ws.channel.ssl.internal.SSLReadServiceContext$SSLReadCompletedCallback.complete(SSLReadServiceContext.java:1824)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:504)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueManager.java:574)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:958)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:1047)
	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:238)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:822)
Caused by: java.lang.NullPointerException
	at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1022)
	at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1017)
	at com.ibm.ws.security.appbnd.internal.authorization.AppBndAuthorizationTableService.updateMapsForAccessId(AppBndAuthorizationTableService.java:447)
	at com.ibm.ws.security.appbnd.internal.authorization.AppBndAuthorizationTableService.getRolesForAccessId(AppBndAuthorizationTableService.java:516)
	at com.ibm.ws.security.authorization.builtin.internal.BuiltinAuthorizationService.getRolesForAccessId(BuiltinAuthorizationService.java:274)
	at com.ibm.ws.security.authorization.builtin.internal.BuiltinAuthorizationService.useAppBndForAccessDecision(BuiltinAuthorizationService.java:351)
	at com.ibm.ws.security.authorization.builtin.internal.BuiltinAuthorizationService.isSubjectAuthorized(BuiltinAuthorizationService.java:333)
	at com.ibm.ws.security.authorization.builtin.internal.BuiltinAuthorizationService.isAuthorized(BuiltinAuthorizationService.java:161)
	at com.ibm.ws.webcontainer.security.WebAppSecurityCollaboratorImpl$3.run(WebAppSecurityCollaboratorImpl.java:1610)
	at com.ibm.ws.webcontainer.security.WebAppSecurityCollaboratorImpl$3.run(WebAppSecurityCollaboratorImpl.java:1601)
	at java.security.AccessController.doPrivileged(AccessController.java:682)
	at com.ibm.ws.webcontainer.security.WebAppSecurityCollaboratorImpl.isUserInRole(WebAppSecurityCollaboratorImpl.java:1601)
	at com.ibm.ws.webcontainer.security.WebAppSecurityCollaboratorImpl.isUserInRole(WebAppSecurityCollaboratorImpl.java:509)
	at com.ibm.ws.webcontainer.srt.SRTServletRequest.isUserInRole(SRTServletRequest.java:2805)
	at com.ibm.ws.jaxrs20.server.JaxRsHttpServletRequestAdapter.isUserInRole(JaxRsHttpServletRequestAdapter.java:1014)
	at com.ibm.ws.jaxrs20.security.LibertyAuthFilter.lambda$handleMessage$2(LibertyAuthFilter.java:98)
	at com.ibm.ws.jaxrs20.security.LibertyAuthFilter$$Lambda$603/0x00000000e0093500.test(Unknown Source)
	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:101)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:969)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:137)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:541)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:528)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:514)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:241)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:207)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:245)
	at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:460)
	at com.ibm.ws.security.authorization.util.RoleMethodAuthUtil.parseMethodSecurity(RoleMethodAuthUtil.java:56)
	at com.ibm.ws.jaxrs20.security.LibertyAuthFilter.handleMessage(LibertyAuthFilter.java:96)
	at com.ibm.ws.jaxrs20.security.LibertyAuthFilter.filter(LibertyAuthFilter.java:52)
	at org.apache.cxf.jaxrs.utils.JAXRSUtils.runContainerRequestFilters(JAXRSUtils.java:1921)
	at org.apache.cxf.jaxrs.interceptor.JAXRSInInterceptor.processRequest(JAXRSInInterceptor.java:272)
	at org.apache.cxf.jaxrs.interceptor.JAXRSInInterceptor.handleMessage(JAXRSInInterceptor.java:90)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	... 33 more
```

**Comment by jimmy1wu** [comment]
hello @fmhwong,

[the docs](https://www.ibm.com/docs/en/was-liberty/nd?topic=liberty-mapping-management-roles) have been corrected to show the correct format for the user's access-id: `user:<security realm name>/<user name>` and a fix for the npe has been merged. 

do you have some logs for the 403 error? i suspect maybe you need to add a name attribute to the user element

e.g.,
```
<user 
  name="${SERVICE_ACCOUNT_NAME}" 
  access-id="user:/${OKD_SERVICE_LOGIN_REALM_NAME}/${SERVICE_ACCOUNT_NAME}"
/>
```
