### ISSUE TITLE
OIDC running out of memory while serializing responses to "oidc/endpoint/OP/registration"

### ISSUE THREAD

**Issue by nastacio** [OpenLiberty/open-liberty#18905]
**Describe the bug**  
We are running OIDC in a Liberty server inside a container on OCP.

Depending on the payload in the request to the "oidc/endpoint/OP/registration" endpoint (e.g. missing a client id) , it seems Liberty is serializing a potentially large JSON response object with the metadata about all registered clients. In our environment, we have a large number of clients, and those JSON objects can get quite large (multiple megabytes.)

The serialization also takes a while, which means these large objects remain in memory for that period, which causes the container to use multiples of the memory it would take if the objects were chunked during that serialization.

In one example, we had to bump the JVM size from 250Mb to 700Mb to account for that factor.

_If there is a stack trace, please include the FULL stack trace (without any `[internal classes]` lines in it). To find the full stack trace, you may need to check in `$WLP_OUTPUT_DIR/messages.log`_

```
javacore.20211006.171815.9.0124.txt:3XMHEAPALLOC             Heap bytes allocated since last GC cycle=25997472 (0x18CB0A0)
javacore.20211006.171815.9.0124.txt-3XMTHREADINFO3           Java callstack:
javacore.20211006.171815.9.0124.txt-4XESTACKTRACE                at java/lang/StringCoding$StringEncoder.encode(StringCoding.java:322(Compiled Code))
javacore.20211006.171815.9.0124.txt-4XESTACKTRACE                at java/lang/StringCoding.encode(StringCoding.java:366(Compiled Code))
javacore.20211006.171815.9.0124.txt-4XESTACKTRACE                at java/lang/String.getBytes(String.java:1971(Compiled Code))
javacore.20211006.171815.9.0124.txt-4XESTACKTRACE                at com/ibm/ws/security/oauth20/web/RegistrationEndpointServices.processHeadOrGetAllClients(RegistrationEndpointServices.java:211)
javacore.20211006.171815.9.0124.txt-4XESTACKTRACE                at com/ibm/ws/security/oauth20/web/RegistrationEndpointServices.processHeadOrGet(RegistrationEndpointServices.java:127)
javacore.20211006.171815.9.0124.txt-4XESTACKTRACE                at com/ibm/ws/security/oauth20/web/RegistrationEndpointServices.handleEndpointRequest(RegistrationEndpointServices.java:100)
javacore.20211006.171815.9.0124.txt-4XESTACKTRACE                at com/ibm/ws/security/oauth20/web/OAuth20EndpointServices.handleEndpointRequest(OAuth20EndpointServices.java:276)
javacore.20211006.171815.9.0124.txt-4XESTACKTRACE                at com/ibm/ws/security/openidconnect/web/OidcEndpointServices.handleOidcRequest(OidcEndpointServices.java:261)
javacore.20211006.171815.9.0124.txt-4XESTACKTRACE                at com/ibm/ws/security/openidconnect/web/OidcEndpointServlet.handleRequest(OidcEndpointServlet.java:109)
javacore.20211006.171815.9.0124.txt-4XESTACKTRACE                at com/ibm/ws/security/openidconnect/web/OidcEndpointServlet.doGet(OidcEndpointServlet.java:59)
javacore.20211006.171815.9.0124.txt-4XESTACKTRACE                at javax/servlet/http/HttpServlet.service(HttpServlet.java:687)
javacore.20211006.171815.9.0124.txt-4XESTACKTRACE                at javax/servlet/http/HttpServlet.service(HttpServlet.java:790(Compiled Code))
javacore.20211006.171815.9.0124.txt-4XESTACKTRACE                at com/ibm/ws/webcontainer/servlet/ServletWrapper.service(ServletWrapper.java:1258)
javacore.20211006.171815.9.0124.txt-4XESTACKTRACE                at com/ibm/ws/webcontainer/servlet/ServletWrapper.handleRequest(ServletWrapper.java:746)
javacore.20211006.171815.9.0124.txt-4XESTACKTRACE                at com/ibm/ws/webcontainer/servlet/ServletWrapper.handleRequest(ServletWrapper.java:443)
javacore.20211006.171815.9.0124.txt-4XESTACKTRACE                at com/ibm/ws/webcontainer/filter/WebAppFilterChain.invokeTarget(WebAppFilterChain.java:183)
javacore.20211006.171815.9.0124.txt-4XESTACKTRACE                at com/ibm/ws/webcontainer/filter/WebAppFilterChain.doFilter(WebAppFilterChain.java:94)
javacore.20211006.171815.9.0124.txt-4XESTACKTRACE                at com/ibm/ws/security/openidconnect/web/OidcRequestFilter.setEndpointRequest(OidcRequestFilter.java:41)
javacore.20211006.171815.9.0124.txt-4XESTACKTRACE                at com/ibm/ws/security/oauth20/web/OAuth20RequestFilter.doFilter(OAuth20RequestFilter.java:95)
javacore.20211006.171815.9.0124.txt-4XESTACKTRACE                at com/ibm/ws/webcontainer/filter/FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:201)
javacore.20211006.171815.9.0124.txt-4XESTACKTRACE                at com/ibm/ws/webcontainer/filter/WebAppFilterChain.doFilter(WebAppFilterChain.java:91)
javacore.20211006.171815.9.0124.txt-4XESTACKTRACE                at com/ibm/ws/app/manager/wab/internal/OsgiDirectoryProtectionFilter.doFilter(OsgiDirectoryProtectionFilter.java:90)
javacore.20211006.171815.9.0124.txt-4XESTACKTRACE                at com/ibm/ws/webcontainer/filter/FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:201)
javacore.20211006.171815.9.0124.txt-4XESTACKTRACE                at com/ibm/ws/webcontainer/filter/WebAppFilterChain.doFilter(WebAppFilterChain.java:91)
javacore.20211006.171815.9.0124.txt-4XESTACKTRACE                at com/ibm/ws/webcontainer/filter/WebAppFilterManager.doFilter(WebAppFilterManager.java:1002)
javacore.20211006.171815.9.0124.txt-4XESTACKTRACE                at com/ibm/ws/webcontainer/filter/WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1140)
javacore.20211006.171815.9.0124.txt-4XESTACKTRACE                at com/ibm/ws/webcontainer/webapp/WebApp.handleRequest(WebApp.java:5049)
javacore.20211006.171815.9.0124.txt-4XESTACKTRACE                at com/ibm/ws/webcontainer/osgi/DynamicVirtualHost$2.handleRequest(DynamicVirtualHost.java:314)
javacore.20211006.171815.9.0124.txt-4XESTACKTRACE                at com/ibm/ws/webcontainer/WebContainer.handleRequest(WebContainer.java:1007)
javacore.20211006.171815.9.0124.txt-4XESTACKTRACE                at com/ibm/ws/webcontainer/osgi/DynamicVirtualHost$2.run(DynamicVirtualHost.java:279)
javacore.20211006.171815.9.0124.txt-4XESTACKTRACE                at com/ibm/ws/http/dispatcher/internal/channel/HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1159)
javacore.20211006.171815.9.0124.txt-4XESTACKTRACE                at com/ibm/ws/http/dispatcher/internal/channel/HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:428)
javacore.20211006.171815.9.0124.txt-4XESTACKTRACE                at com/ibm/ws/http/dispatcher/internal/channel/HttpDispatcherLink.ready(HttpDispatcherLink.java:387)
javacore.20211006.171815.9.0124.txt-4XESTACKTRACE                at com/ibm/ws/http/channel/internal/inbound/HttpInboundLink.handleDiscrimination(HttpInboundLink.java:566)
javacore.20211006.171815.9.0124.txt-4XESTACKTRACE                at com/ibm/ws/http/channel/internal/inbound/HttpInboundLink.handleNewRequest(HttpInboundLink.java:500)
javacore.20211006.171815.9.0124.txt-4XESTACKTRACE                at com/ibm/ws/http/channel/internal/inbound/HttpInboundLink.processRequest(HttpInboundLink.java:360)
javacore.20211006.171815.9.0124.txt-4XESTACKTRACE                at com/ibm/ws/http/channel/internal/inbound/HttpInboundLink.ready(HttpInboundLink.java:327)
javacore.20211006.171815.9.0124.txt-4XESTACKTRACE                at com/ibm/ws/channel/ssl/internal/SSLConnectionLink.determineNextChannel(SSLConnectionLink.java:1100)
javacore.20211006.171815.9.0124.txt-4XESTACKTRACE                at com/ibm/ws/channel/ssl/internal/SSLConnectionLink$MyReadCompletedCallback.complete(SSLConnectionLink.java:675)
javacore.20211006.171815.9.0124.txt-4XESTACKTRACE                at com/ibm/ws/channel/ssl/internal/SSLReadServiceContext$SSLReadCompletedCallback.complete(SSLReadServiceContext.java:1824)
javacore.20211006.171815.9.0124.txt-4XESTACKTRACE                at com/ibm/ws/tcpchannel/internal/WorkQueueManager.requestComplete(WorkQueueManager.java:504)
javacore.20211006.171815.9.0124.txt-4XESTACKTRACE                at com/ibm/ws/tcpchannel/internal/WorkQueueManager.attemptIO(WorkQueueManager.java:574)
javacore.20211006.171815.9.0124.txt-4XESTACKTRACE                at com/ibm/ws/tcpchannel/internal/WorkQueueManager.workerRun(WorkQueueManager.java:958)
javacore.20211006.171815.9.0124.txt-4XESTACKTRACE                at com/ibm/ws/tcpchannel/internal/WorkQueueManager$Worker.run(WorkQueueManager.java:1047)
javacore.20211006.171815.9.0124.txt-4XESTACKTRACE                at com/ibm/ws/threading/internal/ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:238(Compiled Code))
javacore.20211006.171815.9.0124.txt-4XESTACKTRACE                at java/util/concurrent/ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160(Compiled Code))
javacore.20211006.171815.9.0124.txt-4XESTACKTRACE                at java/util/concurrent/ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
javacore.20211006.171815.9.0124.txt-4XESTACKTRACE                at java/lang/Thread.run(Thread.java:825)
```

**Steps to Reproduce**  
As I understand it, make calls to the endpoint using a payload without a client id.

**Expected behavior**  
1. We need clarification on whether the behavior of returning the metadata for all registered clients is expected (cc @teddyjtorres)
2. That metadata can be quite large and its total size is outside the control of the process, so its serialization should use some sort of buffered approach to safeguard memory usage. As mentioned in the description, the usage increases the memory requirements of the JVM by 3x.

**Diagnostic information:**  
 - OpenLiberty Version: [e.g. 21.0.0.8 - 21.0.0.10]

```
Product name: WebSphere Application Server
Product version: 21.0.0.8
Product edition: BASE_ILAN
```

 - Affected feature(s) [e.g. mpHealth-3.0]
   `openidConnectServer-1.0`
 
 - Java Version: [i.e. full output of `java -version`]
```
 java -version
java version "1.8.0_301"
Java(TM) SE Runtime Environment (build 8.0.6.36 - pxa6480sr6fp36-20210824_02(SR6 FP36))
IBM J9 VM (build 2.9, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20210824_12036 (JIT enabled, AOT enabled)
OpenJ9   - 7bb9176
OMR      - 820a5aa
IBM      - dc8f23e)
JCL - 20210806_01 based on Oracle jdk8u301-b09
```

 - server.xml configuration (WITHOUT sensitive information like passwords)
[server.redacted.xml.zip](https://github.com/OpenLiberty/open-liberty/files/7296773/server.redacted.xml.zip)

 - If it would be useful, upload the messages.log file found in `$WLP_OUTPUT_DIR/messages.log`
N/A

**Additional context**

**Comment by teddyjtorres** [comment]
The answer to question 1 is yes. This is limited to users that have the clientManager role as documented in https://www.ibm.com/docs/en/was-liberty/nd?topic=cocpil-configuring-openid-connect-provider-accept-client-registration-requests.

**Comment by nastacio** [comment]
More information, on a potentially secondary problem while troubleshooting this problem.

I turned on extra tracing to try and get more information, by adding this line to the server.xml file, per guidance in this [Liberty OIDC troubleshooting page](https://www.ibm.com/support/pages/node/272965). 

```xml
<logging traceSpecification="com.ibm.ws.security.*=all:com.ibm.ws.webcontainer.security.*=all:com.ibm.oauth.*=all:com.ibm.wsspi.security.oauth20.*=all:org.openid4java.*=all:org.apache.http.client.*=all"/>
```

Note the relatively large 18Mb allocation from inside the tracing call:


```
JVMDUMP039I Processing dump event "allocation", detail "18068560 bytes, type char[]" at 2021/10/06 19:59:27 - please wait.
JVMDUMP032I JVM requested Java dump using '/opt/ibm/wlp/output/defaultServer/javacore.20211006.195927.9.0315.txt' in response to an event
JVMDUMP010I Java dump written to /opt/ibm/wlp/output/defaultServer/javacore.20211006.195927.9.0315.txt
JVMDUMP013I Processed dump event "allocation", detail "18068560 bytes, type char[]".
[10/6/21 19:59:28:892 GMT] 00000b12 id=         com.ibm.ws.webcontainer.util.ApplicationErrorUtils           E SRVE0777E: Exception thrown by application class 'java.lang.StringBuilder.ensureCapacityImpl:802'
java.lang.OutOfMemoryError: Java heap space
        at java.lang.StringBuilder.ensureCapacityImpl(StringBuilder.java:802)
        at java.lang.StringBuilder.append(StringBuilder.java:588)
        at com.ibm.ws.logging.internal.impl.BaseTraceFormatter.formatObj(BaseTraceFormatter.java:1090)
        at com.ibm.ws.logging.internal.impl.BaseTraceFormatter.formatMessage(BaseTraceFormatter.java:309)
        at com.ibm.ws.logging.internal.impl.BaseTraceFormatter.formatVerboseMessage(BaseTraceFormatter.java:379)
        at com.ibm.ws.logging.internal.impl.BaseTraceService.publishTraceLogRecord(BaseTraceService.java:1070)
        at com.ibm.ws.logging.internal.impl.BaseTraceService.entry(BaseTraceService.java:760)
        at com.ibm.websphere.ras.Tr.entry(Tr.java:483)
        at com.ibm.ws.security.oauth20.web.RegistrationEndpointServices.omitEmptyArrays(RegistrationEndpointServices.java:732)
        at com.ibm.ws.security.oauth20.web.RegistrationEndpointServices.processHeadOrGetAllClients(RegistrationEndpointServices.java:181)
        at com.ibm.ws.security.oauth20.web.RegistrationEndpointServices.processHeadOrGet(RegistrationEndpointServices.java:127)
        at com.ibm.ws.security.oauth20.web.RegistrationEndpointServices.handleEndpointRequest(RegistrationEndpointServices.java:100)
        at com.ibm.ws.security.oauth20.web.OAuth20EndpointServices.handleEndpointRequest(OAuth20EndpointServices.java:276)
        at com.ibm.ws.security.openidconnect.web.OidcEndpointServices.handleOidcRequest(OidcEndpointServices.java:261)
        at com.ibm.ws.security.openidconnect.web.OidcEndpointServlet.handleRequest(OidcEndpointServlet.java:109)
        at com.ibm.ws.security.openidconnect.web.OidcEndpointServlet.doGet(OidcEndpointServlet.java:59)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
```

**Comment by mossuchida** [comment]
When I run the following command, although I did not get the JSON return, I see heap utilization hits almost 100%:
```
curl -k -X GET -H 'Content-Type: application/json' -H 'Accept: application/json' -u oauthadmin:$OAUTHCLIENTSECRET "https://$HOST/idauth/oidc/endpoint/OP/registration"
CWOAU0073E: An authentication error occurred. Try closing the web browser and authenticating again, or contact the site administrator if the problem persists.
```
![image](https://user-images.githubusercontent.com/12548207/136277341-29f40dd8-5245-4bf6-8771-473d537bfd5a.png)

Here is another log from Instana for profiling

Here is registration stuck for about 4 hours:

![image](https://user-images.githubusercontent.com/12548207/136277707-f5819f99-684d-4e1a-ab5d-17a9165638af.png)

[traces2.log](https://github.com/OpenLiberty/open-liberty/files/7296987/traces2.log)

This one shows it hits heap OOM
![image](https://user-images.githubusercontent.com/12548207/136277801-e022da6f-1356-4393-9586-5afa888d2190.png)
[oom.log](https://github.com/OpenLiberty/open-liberty/files/7296962/oom.log)
