### ISSUE TITLE
Test Failure (20180129-0242): com.ibm.ws.logging.json.fat.MessagesLogEnvTest.checkAccessLog

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#1896]
junit.framework.AssertionFailedError: 2018-01-29-07:38:18:481 Test failed with one or more errors
at com.ibm.ws.logging.json.fat.JSONEventsTest.checkAccessLog(JSONEventsTest.java:89)
at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:185)
at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:307)
at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:159)

**Comment by fmhwong** [comment]
RTC 250781
