### ISSUE TITLE
update keystore files

### ISSUE THREAD

**Issue by arunavemulapalli** [OpenLiberty/open-liberty#19086]
some key sizes that we are using in tests in com.ibm.ws.wssecurity_fat.wsscxf.1 project are small and the tests are failing on some(specifically RHEL )platforms

**Comment by arunavemulapalli** [comment]
com.ibm.ws.wssecurity_fat.wsscxf.1
com.ibm.ws.wssecurity.fat.cxf.sha2sig.CxfSha2SigTests, com.ibm.ws.wssecurity.fat.cxf..wss11sig.CxfWss11SigTests, com.ibm.ws.wssecurity.fat.cxf.x509token.CxfX509ASyncTests,com.ibm.ws.wssecurity.fat.cxf..x509token.CxfX509SigTests

junit.framework.AssertionFailedError: 2021-10-17-06:10:15:203 
Expected: 
Response: This is WSSECFVT SHA2 Web Service.
 But received: 
<html><head><title>CXF Sha2 Sig Service Client</title></head><body><p>Request: CXF Sha2 Sig Service Client</p><p>Response: javax.xml.ws.soap.SOAPFaultException: General security error (Error during certificate path validation: Algorithm constraints check failed on keysize limits. RSA 1024bit key used with certificate: ...........</p></body></html>

	at com.ibm.ws.wssecurity.fat.utils.common.CommonTests.genericTestSub(CommonTests.java:512)
	at com.ibm.ws.wssecurity.fat.utils.common.CommonTests.genericTest(CommonTests.java:340)
	at com.ibm.ws.wssecurity.fat.utils.common.CommonTests.genericTest(CommonTests.java:315)
	at com.ibm.ws.wssecurity.fat.cxf.sha2sig.CxfSha2SigTests.testCxfSha2SignSoapBodyEE7Only(CxfSha2SigTests.java:96)
	at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:198)
	at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:319)
	at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:172)
	at componenttest.rules.repeater.RepeatTests$CompositeRepeatTestActionStatement.evaluate(RepeatTests.java:143)
