### ISSUE TITLE
add doPriv in the code

### ISSUE THREAD

**Issue by arunavemulapalli** [OpenLiberty/open-liberty#19107]
wsstemplate tests in com.ibm.ws.wssecurity_fat.wsscxf.saml and com.ibm.ws.wssecurity_fat.wsscxf.saml.1 are failing (when java2security is enabled and with the xmlWS-3.0/jaxws-2.3 features)

`[10/19/21, 17:08:00:292 PDT] 00000043 .ws.org.apache.cxf.cxf.core.3.2:1.0.58.202110182035(id=127)] W Interceptor for {http://wsstemplates.wssecfvt.test}WSSTemplatesService2#{http://cxf.apache.org/jaxws/dispatch}Invoke has thrown exception, unwinding now
java.security.AccessControlException: Access denied ("javax.security.auth.AuthPermission" "getSubject")
        at java.base/java.security.AccessController.throwACE(AccessController.java:176)
        at java.base/java.security.AccessController.checkPermissionHelper(AccessController.java:238)
        at java.base/java.security.AccessController.checkPermission(AccessController.java:385)
        at java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:322)
        at java.base/javax.security.auth.Subject.getSubject(Subject.java:288)
        at org.apache.cxf.ext.logging.event.DefaultLogEventMapper.getJAASPrincipals(DefaultLogEventMapper.java:138)
        at org.apache.cxf.ext.logging.event.DefaultLogEventMapper.getJAASPrincipal(DefaultLogEventMapper.java:124)
        at org.apache.cxf.ext.logging.event.DefaultLogEventMapper.getPrincipal(DefaultLogEventMapper.java:106)
        at org.apache.cxf.ext.logging.event.DefaultLogEventMapper.map(DefaultLogEventMapper.java:98)
        at org.apache.cxf.ext.logging.LoggingOutInterceptor$LoggingCallback.onClose(LoggingOutInterceptor.java:196)
        at org.apache.cxf.io.CachedOutputStream.close(CachedOutputStream.java:219)
        at org.apache.cxf.transport.AbstractConduit.close(AbstractConduit.java:56)
        at org.apache.cxf.transport.http.HTTPConduit.close(HTTPConduit.java:687)
        at org.apache.cxf.interceptor.MessageSenderInterceptor$MessageSenderEndingInterceptor.handleMessage(MessageSenderInterceptor.java:63)
        at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
        at org.apache.cxf.endpoint.ClientImpl.doInvoke(ClientImpl.java:530)
        at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:441)
        at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:356)
        at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:314)
        at org.apache.cxf.endpoint.ClientImpl.invokeWrapped(ClientImpl.java:349)
        at org.apache.cxf.jaxws.DispatchImpl.invoke(DispatchImpl.java:322)
        at org.apache.cxf.jaxws.DispatchImpl.invoke(DispatchImpl.java:241)
        at com.ibm.ws.wssecurity.fat.wsstemplatesclient.CxfWssSAMLTemplatesSvcClient.doWorker(CxfWssSAMLTemplatesSvcClient.java:239)
        at com.ibm.ws.wssecurity.fat.wsstemplatesclient.CxfWssSAMLTemplatesSvcClient.doPost(CxfWssSAMLTemplatesSvcClient.java:282)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:706)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:791)
        at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1258)
        at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:746)
        at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:443)
        at com.ibm.ws.webcontainer.filter.WebAppFilterChain.invokeTarget(WebAppFilterChain.java:193)
        at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:98)
        at com.ibm.ws.security.jaspi.JaspiServletFilter.doFilter(JaspiServletFilter.java:56)
        at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:197)
        at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:91)
        at com.ibm.ws.webcontainer.filter.WebAppFilterManager.doFilter(WebAppFilterManager.java:1002)
        at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1140)
        at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1011)
        at com.ibm.ws.webcontainer.servlet.CacheServletWrapper.handleRequest(CacheServletWrapper.java:75)
        at com.ibm.ws.webcontainer40.servlet.CacheServletWrapper40.handleRequest(CacheServletWrapper40.java:85)
        at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:938)
        at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:279)
        at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1159)
        at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:428)
        at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:387)
        at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:566)
        at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:500)
        at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:360)
        at com.ibm.ws.http.channel.internal.inbound.HttpICLReadCallback.complete(HttpICLReadCallback.java:70)
        at com.ibm.ws.channel.ssl.internal.SSLReadServiceContext$SSLReadCompletedCallback.complete(SSLReadServiceContext.java:1824)
        at com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:504)
        at com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueManager.java:574)
        at com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:958)
        at com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:1047)`

**Comment by arunavemulapalli** [comment]
update `dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.1/test-applications/samlwsstemplatesclient/resources/META-INF/permissions.xml` and `dev/com.ibm.ws.wssecurity_fat.wsscxf.saml/test-applications/samlwsstemplatesclientwithep/resources/META-INF/permissions.xml` and remove the getSubject AuthPermission once the cxf code is updated
