### ISSUE TITLE
Eclipse krazo does not work on OpenLiberty 21.* beta

### ISSUE THREAD

**Issue by cgawron** [OpenLiberty/open-liberty#19271]
When I try to use krazo with OpenLiberty, I get a similar error as #5505.

The [fix for the above issue](https://github.com/OpenLiberty/open-liberty/pull/5524) relates to cxf / jax-rs 2.0, so I guess a similar fix is needed for jax-rs 3.0, which is based on reasteasy.

I'm using these dependencies in my pom.xml:

        <dependency>
            <groupId>jakarta.mvc</groupId>
            <artifactId>jakarta.mvc-api</artifactId>
            <version>2.0.0</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.krazo</groupId>
            <artifactId>krazo-core</artifactId>
            <version>2.0.1</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.krazo</groupId>
            <artifactId>krazo-resteasy</artifactId>
            <version>2.0.1</version>
        </dependency>

Here is the exception that I get when I try to access my MVC application:

[INFO] [FEHLER  ] SRVE0777E: Es wurde eine Ausnahme von der Anwendungsklasse 'org.jboss.resteasy.core.ExceptionHandler.handleException:381' ausgelöst.
[INFO] org.jboss.resteasy.spi.UnhandledException: java.lang.RuntimeException: SRV.8.2: RequestWrapper objects must extend ServletRequestWrapper or HttpServletRequestWrapper
[INFO]  at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:381)
[INFO]  at [internal classes]
[INFO] Caused by: java.lang.RuntimeException: SRV.8.2: RequestWrapper objects must extend ServletRequestWrapper or HttpServletRequestWrapper
[INFO]  at com.ibm.wsspi.webcontainer.util.ServletUtil.unwrapRequest(ServletUtil.java:89)
[INFO]  at [internal classes]
[INFO]  at org.eclipse.krazo.engine.ServletViewEngine.forwardRequest(ServletViewEngine.java:121)
[INFO]  at org.eclipse.krazo.engine.JspViewEngine.processView(JspViewEngine.java:58)
[INFO]  at org.eclipse.krazo.core.ViewableWriter.writeTo(ViewableWriter.java:159)
[INFO]  at org.eclipse.krazo.core.ViewableWriter.writeTo(ViewableWriter.java:71)
[INFO]  at org.jboss.resteasy.core.interception.jaxrs.ServerWriterInterceptorContext.lambda$writeTo$1(ServerWriterInterceptorContext.java:79)
[INFO]  ... 1 more

**Comment by chkal** [comment]
Please also note that I'm pretty sure that Krazo wraps requests/responses in the required wrapper classes. See my comment and the reference to the source code here:

https://github.com/eclipse-ee4j/krazo/issues/282#issuecomment-962933724

**Comment by WhiteCat22** [comment]
Hi @cgawron, apologies for taking so long to address this. My coworker who was looking into this left IBM and never tagged the issue as a JAX-RS issue.

I would like to write a FAT test that reproduces the problem without Krazo, can you explain what Krazo is doing to hit this error?

**Comment by WhiteCat22** [comment]
closing until we can reproduce
