### ISSUE TITLE
[performance] Avoid ClassNotFoundException on loader delegation if possible

### ISSUE THREAD

**Issue by tjwatson** [OpenLiberty/open-liberty#19297]
The EE application class loader in Liberty has many levels of class loader delegation it has to deal with.  In some cases we have taken measures to avoid generating ClassNotFoundExceptions during delegation.  But there are some areas we can investigate to avoid more.  Two areas to investigate:

1. The AppClassLoader ends up delegating to something called the gateway class loader.  This class loader is backed by an OSGi bundle class loader.  This bundle dynamically imports packages in order to gain access to the API packages as defined by Liberty features.  Equinox recently put in a new method to its loader to do delegation to a bundle class loader without causing a CNFE generation/throw.  See https://bugs.eclipse.org/bugs/show_bug.cgi?id=577010 for the details.  The method is internal to Equinox but the savings may be worth a try to call it instead of the ClassLoader.loadClass call we currently use.
1. Delegating the the JVM parent class loader (or boot loader).  On Java 9+ we can use JPMS to find the exact set of packages that exist in the running JVM.  We could use this set of package names to determine if we should delegate up to the boot class loader or not.

**Comment by tjwatson** [comment]
For the design call.  While investigating the second part of this performance enhancement (delegating to the JVM parent class loader (or boot loader).  I discovered that all Liberty application class loaders get free access to everything on the -classpath of the JVM launch.  This includes all or com.ibm.ws.kernel.boot.  When I changed the boot delegation to only delegate for packages provided by the JVM modules I started seeing stuff fail that expects to be able to load things out of the kernel.boot JAR for free.  For example, the following:

```
Caused by: java.lang.ClassNotFoundException: com.ibm.ws.kernel.boot.jmx.internal.PlatformMBeanServerBuilder
	at com.ibm.ws.classloading.internal.UnifiedClassLoader.findClass(UnifiedClassLoader.java:157) ~[na:na]
	at com.ibm.ws.classloading.internal.ThreadContextClassLoader.findClass(ThreadContextClassLoader.java:141) ~[na:na]
	at com.ibm.ws.classloading.internal.UnifiedClassLoader.loadClass0(UnifiedClassLoader.java:134) ~[na:na]
	at com.ibm.ws.classloading.internal.UnifiedClassLoader$Delegation.loadClass(UnifiedClassLoader.java:85) ~[na:na]
	at com.ibm.ws.classloading.internal.UnifiedClassLoader.loadClass(UnifiedClassLoader.java:109) ~[na:na]
	at com.ibm.ws.classloading.internal.ThreadContextClassLoader.loadClass(ThreadContextClassLoader.java:157) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1078) ~[na:na]
	at java.management/javax.management.MBeanServerFactory.loadBuilderClass(MBeanServerFactory.java:444) ~[na:na]
	at java.management/javax.management.MBeanServerFactory.checkMBeanServerBuilder(MBeanServerFactory.java:487) ~[na:na]
```

I can certainly update the delegation logic to be able to figure out what packages are available from the kernel.boot JAR.  But there are several questions with this approach:

1. Do we really want applications to have free access to all these internals?
1. What about embedders that include other stuff on the -classpath?  All this is freely available for applications to load.  Should we be concerned if we close this hole and block such exposure to the application class loaders?

**Comment by tjwatson** [comment]
I opened #19895 for continuing the JVM boot delegation part of this design issue.  This design issue now is only about the internals of the Application Classloader delegation for access to Liberty API packages.

**Comment by tjwatson** [comment]
The Application Classloader has been updated with the changes to avoid ClassNotFoundException.  Closing.
