### ISSUE TITLE
mpOpenApi-2.0 fails to start because mpConfig component is not ready

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/open-liberty#19326]
**Describe the bug**  
During startup, the following message is seen:
```
 E CWWKE0701E: bundle io.openliberty.microprofile.openapi.2.0.internal.jakarta:1.0.59.cl211220211108-1100 (226)[io.openliberty.microprofile.openapi20.ApplicationRegistry(373)] : Error during instantiation of the implementation object java.lang.reflect.InvocationTargetException
```

FFDC shows:
```
Caused by: java.lang.IllegalStateException: No ConfigProviderResolver implementation found!
    at org.eclipse.microprofile.config.spi.ConfigProviderResolver.loadSpi(ConfigProviderResolver.java:138)
    at org.eclipse.microprofile.config.spi.ConfigProviderResolver.instance(ConfigProviderResolver.java:124)
    at org.eclipse.microprofile.config.ConfigProvider.getConfig(ConfigProvider.java:101)
    at io.openliberty.microprofile.openapi20.ApplicationRegistry.<init>(ApplicationRegistry.java:70)
```

I suspect but have not confirmed that OpenAPI documentation is not generated.

**Steps to Reproduce**  
* Enable `mpOpenApi-2.0`
* Start the server
* Occurs very rarely

**Expected behavior**  
Server should start as normal

**Diagnostic information:**  
 - OpenLiberty Version: latest integration
 - Affected feature(s) `mpOpenApi-2.0`
 - Java Version: [i.e. full output of `java -version`]
 - server.xml configuration (WITHOUT sensitive information like passwords)
 - If it would be useful, upload the messages.log file found in `$WLP_OUTPUT_DIR/messages.log`

**Additional context**  

Occurs rarely, likely present since the merge of #17697

**Comment by Azquelt** [comment]
Ideally we should fix this by having mpOpenApi depend on a service from mpConfig rather than calling `ConfigProvider.getConfig`.

In the short term, the easiest fix will be to ensure we don't call `getConfig` until later in the startup process.
