### ISSUE TITLE
NPE from WebAppSecurityConfigImpl

### ISSUE THREAD

**Issue by una-tapa** [OpenLiberty/open-liberty#19351]
**Describe the bug**  
NPE from WebAppSecurityConfigImpl

```
------Start of DE processing------ 
= [9/8/21 15:27:18:868 UTC]
Exception = java.lang.NullPointerException
Source = com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters
probeid = 1105
Stack Dump = java.lang.NullPointerException
        at com.ibm.ws.webcontainer.security.internal.WebAppSecurityConfigImpl.isUseAuthenticationDataForUnprotectedResourceEnabled(WebAppSecurityConfigImpl.java:362)
        at com.ibm.ws.webcontainer.security.WebAppSecurityCollaboratorImpl.optionallyAuthenticateUnprotectedResource(WebAppSecurityCollaboratorImpl.java:808)
        at com.ibm.ws.webcontainer.security.WebAppSecurityCollaboratorImpl.determineWebReply(WebAppSecurityCollaboratorImpl.java:982)
        at com.ibm.ws.webcontainer.security.WebAppSecurityCollaboratorImpl.performSecurityChecks(WebAppSecurityCollaboratorImpl.java:678)
        at com.ibm.ws.webcontainer.security.WebAppSecurityCollaboratorImpl.preInvoke(WebAppSecurityCollaboratorImpl.java:596)
        at com.ibm.wsspi.webcontainer.collaborator.CollaboratorHelper.preInvokeCollaborators(CollaboratorHelper.java:459)
        at com.ibm.ws.webcontainer.osgi.collaborator.CollaboratorHelperImpl.preInvokeCollaborators(CollaboratorHelperImpl.java:270)
        at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1114)
        at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:5057)
```

According to the code are 
https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/internal/WebAppSecurityConfigImpl.java#L362

The useAuthenticationDataForUnprotectedResource is defined as Boolean: 
`useAuthenticationDataForUnprotectedResource = (Boolean) newProperties.get(CFG_KEY_USE_AUTH_DATA_FOR_UNPROTECTED);
`
However, it is returned as "boolean"
```
    @Override
    public boolean isUseAuthenticationDataForUnprotectedResourceEnabled() {
        return useAuthenticationDataForUnprotectedResource;
    }
```
It looks like the object should be checked before returning. 
```
    @Override
    public boolean getAllowFailOverToAppDefined() {
        if (allowFailOverToAuthMethod != null && allowFailOverToAuthMethod.equalsIgnoreCase(LoginConfiguration.APP_DEFINED))
            return true;
        else
            return false;
    }
```
**Steps to Reproduce**  
No clear steps provided.  It sounds like the user deployed an application that includes unprotected URL.   

**Expected behavior**  
NullPointerException should not be thrown. 

**Diagnostic information:**  
 - OpenLiberty Version: 21.0.0.3
 - Affected feature(s) appSecurity-2.0
 - Java Version: 
 - server.xml configuration appSecurity-2.0
 - 
**Additional context**

**Comment by una-tapa** [comment]
It turned out this was the environment issue. Closing.
