### ISSUE TITLE
NoUserRepositoriesFoundException raised when accessing endpoints with Authorization header when no registry is defined

### ISSUE THREAD

**Issue by lolo4j** [OpenLiberty/open-liberty#19623]
When accessing an endpoint on a Liberty server that has no registry declared, but including an `Authorization` header in the request anyway, Liberty raises the following exception for each request:

```
[12/8/21 17:19:19:857 CET] 00000048 id=00000000 com.ibm.ws.security.wim.registry.util.LoginBridge            E CWIMK0011E: The user registry operation could not be completed. A valid user registry was not found. Add or correct the registry definition in the server.xml file. 
                                                                                                               com.ibm.wsspi.security.wim.exception.NoUserRepositoriesFoundException: CWIMK0011E: The user registry operation could not be completed. A valid user registry was not found. Add or correct the registry definition in the server.xml file.
  at com.ibm.ws.security.wim.ProfileManager.genericProfileManagerMethod(ProfileManager.java:237)
  at com.ibm.ws.security.wim.ProfileManager.login(ProfileManager.java:217)
  at com.ibm.ws.security.wim.VMMService.login(VMMService.java:249)
  at com.ibm.ws.security.wim.registry.util.LoginBridge.checkPassword(LoginBridge.java:116)
  at com.ibm.ws.security.wim.registry.WIMUserRegistry.checkPassword(WIMUserRegistry.java:151)
  at com.ibm.ws.security.authentication.jaas.modules.UsernameAndPasswordLoginModule.login(UsernameAndPasswordLoginModule.java:75)
  at com.ibm.ws.kernel.boot.security.LoginModuleProxy.login(LoginModuleProxy.java:51)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at javax.security.auth.login.LoginContext.invoke(LoginContext.java:755)
  at javax.security.auth.login.LoginContext.access$000(LoginContext.java:195)
  at javax.security.auth.login.LoginContext$4.run(LoginContext.java:682)
  at javax.security.auth.login.LoginContext$4.run(LoginContext.java:680)
  at java.security.AccessController.doPrivileged(AccessController.java:774)
  at javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:680)
  at javax.security.auth.login.LoginContext.login(LoginContext.java:587)
  at com.ibm.ws.security.authentication.internal.jaas.JAASServiceImpl.doLoginContext(JAASServiceImpl.java:343)
  at com.ibm.ws.security.authentication.internal.jaas.JAASServiceImpl.performLogin(JAASServiceImpl.java:329)
  at com.ibm.ws.security.authentication.internal.jaas.JAASServiceImpl.performLogin(JAASServiceImpl.java:314)
  at com.ibm.ws.security.authentication.internal.AuthenticationServiceImpl.performJAASLogin(AuthenticationServiceImpl.java:495)
  at com.ibm.ws.security.authentication.internal.AuthenticationServiceImpl.authenticate(AuthenticationServiceImpl.java:210)
  at com.ibm.ws.webcontainer.security.internal.BasicAuthAuthenticator.basicAuthenticate(BasicAuthAuthenticator.java:126)
  at com.ibm.ws.webcontainer.security.internal.BasicAuthAuthenticator.handleBasicAuth(BasicAuthAuthenticator.java:117)
  at com.ibm.ws.webcontainer.security.internal.BasicAuthAuthenticator.authenticate(BasicAuthAuthenticator.java:70)
  at com.ibm.ws.webcontainer.security.WebAuthenticatorProxy.authenticate(WebAuthenticatorProxy.java:88)
  at com.ibm.ws.webcontainer.security.WebAppSecurityCollaboratorImpl.authenticateRequest(WebAppSecurityCollaboratorImpl.java:1233)
  at com.ibm.ws.webcontainer.security.WebAppSecurityCollaboratorImpl.setAuthenticatedSubjectIfNeeded(WebAppSecurityCollaboratorImpl.java:855)
  at com.ibm.ws.webcontainer.security.WebAppSecurityCollaboratorImpl.optionallyAuthenticateUnprotectedResource(WebAppSecurityCollaboratorImpl.java:812)
  at com.ibm.ws.webcontainer.security.WebAppSecurityCollaboratorImpl.determineWebReply(WebAppSecurityCollaboratorImpl.java:982)
  at com.ibm.ws.webcontainer.security.WebAppSecurityCollaboratorImpl.performSecurityChecks(WebAppSecurityCollaboratorImpl.java:678)
  at com.ibm.ws.webcontainer.security.WebAppSecurityCollaboratorImpl.preInvoke(WebAppSecurityCollaboratorImpl.java:596)
  at com.ibm.wsspi.webcontainer.collaborator.CollaboratorHelper.preInvokeCollaborators(CollaboratorHelper.java:459)
  at com.ibm.ws.webcontainer.osgi.collaborator.CollaboratorHelperImpl.preInvokeCollaborators(CollaboratorHelperImpl.java:270)
  at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1114)
  at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:5057)
  at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.handleRequest(DynamicVirtualHost.java:314)
  at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:1006)
  at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:279)
  at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1146)
  at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:427)
  at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:386)
  at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:566)
  at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:500)
  at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:360)
  at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.ready(HttpInboundLink.java:327)
  at com.ibm.ws.http.channel.h2internal.H2StreamProcessor$Http2Ready.run(H2StreamProcessor.java:1793)
  at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:238)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  at java.lang.Thread.run(Thread.java:823)
```

We believe this is a consequence of this issue ands its implementation: https://github.com/OpenLiberty/open-liberty/issues/2489

Is there any way to avoid logging this exception at every request, other than disabliing the logging for `com.ibm.ws.security.wim.ProfileManager` ?

**Comment by jvanhill** [comment]
@lolo4j - You're analysis is correct. Is there a reason you are using federatedRegistry-1.0 without having a participating registry?

**Comment by jvanhill** [comment]
If you are not using `federatedRegistry-1.0`, then you should remove it from your list of features. It is possible, another feature you are using is enabling it. Is it possible you are using `appSecurity-1.0`? If so, consider moving to `appSecurity-2.0`, which removes the (unnecessary) dependency on `ldapRegistry-3.0` / `federatedRegistry-3.0`.

If none of those are viable, then you can hide the message using the configuration discussed here (search `hideMessage`):

https://openliberty.io/docs/21.0.0.2/log-trace-configuration.html

and here:

https://openliberty.io/docs/21.0.0.12/reference/config/logging.html

**Comment by lolo4j** [comment]
Hello @jvanhill thanks for your quick feedback. Our Liberty installation supports multiple modes of authentication, one of them being "no authentication at all". Depending on which mode is configured, we include the required user registry or auth provider client, or nothing.

From your suggestions, I'm guessing we should also tailor the set of features in each included file, rather than have them all in the main server.xml. I wil try that and let you know of the result.

**Comment by jvanhill** [comment]
@lolo4j - Did you have a chance to  test this? If so, did it work and can we close this?

**Comment by lolo4j** [comment]
Hello @jvanhill ,

Sorry for the lack of feedback.
By tailoring the feature set in server.xml, I managed to reduce the error logging to a single error line, instead of a full stack trace, for each incoming request. So that's a lesser evil 😄 

Please feel free to close this issue at your convenience.

**Comment by jvanhill** [comment]
@lolo4j - Would the `logging->hideMessage` configuration work for you?

`<logging hideMessage="CWIMK0011E" />`

See: https://openliberty.io/docs/latest/reference/config/logging.html

You could set it for when you know you have a configuration that has no registries.
