### ISSUE TITLE
Concurrency errors when using same JWT access token for inbound propagation

### ISSUE THREAD

**Issue by teddyjtorres** [OpenLiberty/open-liberty#19861]
**Describe the bug**  
For a Liberty server configured with openidConnectClient-1.0 using the same JWT access token for inbound propagation for multiple requests, there is a concurrency error. This fails the requests. 

The first issue is as shown in the stack trace below. The other issue is when creating the WSCredential for the subject, where the uniqueId and securityName are removed in one thread. When removeSecurityNameAndUniquedIdFromHashtable is called and then a second thread calls WSCredentialProvider' setCredential, there is a problem finding the hashtable, resulting in an unexpected code flow to find the user information from the registry instead of using the hashtable data.

If there is a stack trace, please include the FULL stack trace (without any `[internal classes]` lines in it). To find the full stack trace, you may need to check in `$WLP_OUTPUT_DIR/messages.log`

In FFDC:
```
Stack Dump = java.util.ConcurrentModificationException
	at java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:977)
	at java.util.LinkedList$ListItr.next(LinkedList.java:899)
	at javax.security.auth.Subject$SecureSet$1.next(Subject.java:1290)
	at com.ibm.ws.security.openidconnect.client.internal.AccessTokenCacheHelper.recreateSubject(AccessTokenCacheHelper.java:137)
	at com.ibm.ws.security.openidconnect.client.internal.AccessTokenCacheHelper.getCachedTokenAuthenticationResult(AccessTokenCacheHelper.java:51)
	at com.ibm.ws.security.openidconnect.client.AccessTokenAuthenticator.authenticate(AccessTokenAuthenticator.java:130)
	at com.ibm.ws.security.openidconnect.client.internal.OidcClientImpl.authenticate(OidcClientImpl.java:406)
```

**Steps to Reproduce**  
Steps to reproduce the bug
1. Configure openidConnectClient-1.0 feature
2. Enable inbound propagation and tokenReuse attributes
3. Drive concurrent requests to the protected resource very rapidly
4. ConcurrentModificationException is produced as shown above

**Expected behavior**  
A ConcurrentModificationException must not be thrown and the request must succeed.

**Diagnostic information:**  
 - OpenLiberty Version:
 - Affected feature(s) openidConnectClient-1.0
 - Java Version: [i.e. full output of `java -version`]
 - server.xml configuration (WITHOUT sensitive information like passwords)
 - If it would be useful, upload the messages.log file found in `$WLP_OUTPUT_DIR/messages.log`

**Additional context**

**Comment by peulvast** [comment]
Hello @teddyjtorres, do you have a ETA for this defect?
Thanks,
