### ISSUE TITLE
Test Failure (20220112-1819): com.ibm.ws.logging.fat.StackTraceFilteringForIBMFeatureExceptionTest.testConsoleIsTrimmedForNastyInternalErrorFromIBMFeature

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#19914]
RTC 288927

```
junit.framework.AssertionFailedError: 2022-01-13-01:55:49:268 The console stack should only have one [internal classes] in it. expected:<1> but was:<2>
at com.ibm.ws.logging.fat.AbstractStackTraceFilteringTest.assertConsoleLogCountEquals(AbstractStackTraceFilteringTest.java:76)
at com.ibm.ws.logging.fat.StackTraceFilteringForIBMFeatureExceptionTest.testConsoleIsTrimmedForNastyInternalErrorFromIBMFeature(StackTraceFilteringForIBMFeatureExceptionTest.java:55)
at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:198)
at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:319)
at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:172)
```

This was the console.log that contains more than 1 `[internal classes]`

```
Launching com.ibm.ws.logging.badconfig.ibm (WebSphere Application Server 22.0.0.2/wlp-1.0.61.202201241923) on IBM J9 VM, version 8.0.5.27 - pxa6480sr5fp27-20190104_01(SR5 FP27) (en_US)
[AUDIT   ] CWWKE0001I: The server com.ibm.ws.logging.badconfig.ibm has been launched.
[AUDIT   ] CWWKG0028A: Processing included configuration resource: /home/jazz_build/Build/jbe/build/dev/image/output/wlp/usr/servers/fatTestPorts.xml
[AUDIT   ] CWWKG0028A: Processing included configuration resource: /home/jazz_build/Build/jbe/build/dev/image/output/wlp/usr/servers/fatTestCommon.xml
[AUDIT   ] CWWKZ0058I: Monitoring dropins for applications.
The user feature is about to throw an exception.
[ERROR   ] CWWKE0701E: bundle test.configuration.fallalloverthefloor.ibmfeature:1.0.61.202201242026 (23)[com.ibm.ws.logging.fat.fallalloverthefloor.ibmfeature.BrokenFeature(214)] : The activate method has thrown an exception com.ibm.ws.logging.fat.fallalloverthefloor.ibmfeature.BrokenFeature$ConfigurationReceivedException
	at com.ibm.ws.logging.fat.fallalloverthefloor.ibmfeature.BrokenFeature.reallyThrowAnException(BrokenFeature.java:40)
	at [internal classes]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$$Lambda$61.000000009400A1A0.run(Unknown Source)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$$Lambda$96.0000000094017900.execute(Unknown Source)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1829)
	at [internal classes]
  
[AUDIT   ] TE9900A: Timed Exit Enabled
[AUDIT   ] CWWKF0012I: The server installed the following features: [servlet-3.1, timedexit-1.0, usr:unconfigurableIbmFeature-1.0].
[AUDIT   ] CWWKF0011I: The com.ibm.ws.logging.badconfig.ibm server is ready to run a smarter planet. The com.ibm.ws.logging.badconfig.ibm server started in 5.183 seconds.
[AUDIT   ] CWWKE0055I: Server shutdown requested on Tuesday, January 25, 2022 at 3:01 AM. The server com.ibm.ws.logging.badconfig.ibm is shutting down.
[AUDIT   ] CWWKE1100I: Waiting for up to 30 seconds for the server to quiesce.
[AUDIT   ] CWWKE0036I: The server com.ibm.ws.logging.badconfig.ibm stopped after 6.384 seconds.
```

Full stack from messages.log
```
[1/25/22 3:01:25:307 PST] 0000001e Service-23-test.configuration.fallalloverthefloor.ibmfeature E CWWKE0701E: bundle test.configuration.fallalloverthefloor.ibmfeature:1.0.61.202201242026 (23)[com.ibm.ws.logging.fat.fallalloverthefloor.ibmfeature.BrokenFeature(214)] : The activate method has thrown an exception com.ibm.ws.logging.fat.fallalloverthefloor.ibmfeature.BrokenFeature$ConfigurationReceivedException
	at com.ibm.ws.logging.fat.fallalloverthefloor.ibmfeature.BrokenFeature.reallyThrowAnException(BrokenFeature.java:40)
	at com.ibm.ws.logging.fat.fallalloverthefloor.ibmfeature.BrokenFeature.thinkAboutThrowingAnException(BrokenFeature.java:32)
	at com.ibm.ws.logging.fat.fallalloverthefloor.ibmfeature.BrokenFeature.activate(BrokenFeature.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.apache.felix.scr.impl.inject.methods.BaseMethod.invokeMethod(BaseMethod.java:244)
	at org.apache.felix.scr.impl.inject.methods.BaseMethod.access$500(BaseMethod.java:41)
	at org.apache.felix.scr.impl.inject.methods.BaseMethod$Resolved.invoke(BaseMethod.java:685)
	at org.apache.felix.scr.impl.inject.methods.BaseMethod.invoke(BaseMethod.java:529)
	at org.apache.felix.scr.impl.inject.methods.ActivateMethod.invoke(ActivateMethod.java:318)
	at org.apache.felix.scr.impl.inject.methods.ActivateMethod.invoke(ActivateMethod.java:308)
	at org.apache.felix.scr.impl.manager.SingleComponentManager.createImplementationObject(SingleComponentManager.java:354)
	at org.apache.felix.scr.impl.manager.SingleComponentManager.createComponent(SingleComponentManager.java:115)
	at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:1000)
	at org.apache.felix.scr.impl.manager.SingleComponentManager.getServiceInternal(SingleComponentManager.java:973)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.activateInternal(AbstractComponentManager.java:785)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.enableInternal(AbstractComponentManager.java:674)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.enable(AbstractComponentManager.java:437)
	at org.apache.felix.scr.impl.manager.ConfigurableComponentHolder.enableComponents(ConfigurableComponentHolder.java:667)
	at org.apache.felix.scr.impl.BundleComponentActivator.initialEnable(BundleComponentActivator.java:305)
	at org.apache.felix.scr.impl.Activator.loadComponents(Activator.java:554)
	at org.apache.felix.scr.impl.Activator.access$200(Activator.java:70)
	at org.apache.felix.scr.impl.Activator$ScrExtension.start(Activator.java:421)
	at org.apache.felix.scr.impl.AbstractExtender.createExtension(AbstractExtender.java:196)
	at org.apache.felix.scr.impl.AbstractExtender.modifiedBundle(AbstractExtender.java:169)
	at org.apache.felix.scr.impl.AbstractExtender.modifiedBundle(AbstractExtender.java:49)
	at org.osgi.util.tracker.BundleTracker$Tracked.customizerModified(BundleTracker.java:488)
	at org.osgi.util.tracker.BundleTracker$Tracked.customizerModified(BundleTracker.java:1)
	at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:232)
	at org.osgi.util.tracker.BundleTracker$Tracked.bundleChanged(BundleTracker.java:450)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:935)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:228)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEventPrivileged(EquinoxEventPublisher.java:229)
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:138)
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:130)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor.publishModuleEvent(EquinoxContainerAdaptor.java:206)
	at org.eclipse.osgi.container.Module.publishEvent(Module.java:499)
	at org.eclipse.osgi.container.Module.start(Module.java:486)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.lambda$1(ModuleContainer.java:1834)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$$Lambda$61.000000009400A1A0.run(Unknown Source)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$$Lambda$96.0000000094017900.execute(Unknown Source)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1829)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1778)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1739)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1661)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:228)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:339)
  
```

**Comment by fmhwong** [comment]
```
product = WebSphere Application Server 22.0.0.2 (wlp-1.0.61.202201241923)
wlp.install.dir = /home/jazz_build/Build/jbe/build/dev/image/output/wlp/
java.home = /home/jazz_build/Build/jbe/jvms/ibm-java-ws-sdk-pxa6480sr5fp27-20190104_01/jre
java.version = 1.8.0_191
java.runtime = Java(TM) SE Runtime Environment (8.0.5.27 - pxa6480sr5fp27-20190104_01(SR5 FP27))
os = Linux (4.15.0-161-generic; amd64) (en_US)
process = 18679@10.51.14.238
```

**Comment by fmhwong** [comment]
On openjdk version "11.0.11" 2021-04-20, I got this stack.

```
[ERROR   ] CWWKE0701E: bundle test.configuration.fallalloverthefloor.ibmfeature:1.0.61.202201191756 (23)[com.ibm.ws.logging.fat.fallalloverthefloor.ibmfeature.BrokenFeature(214)] : The activate method has thrown an exception com.ibm.ws.logging.fat.fallalloverthefloor.ibmfeature.BrokenFeature$ConfigurationReceivedException
	at com.ibm.ws.logging.fat.fallalloverthefloor.ibmfeature.BrokenFeature.reallyThrowAnException(BrokenFeature.java:40)
	at [internal classes]
  
```

**Comment by fmhwong** [comment]
Full stack trace from messages.log
```
[2022-01-26, 14:58:02:630 EST] 0000002b Service-23-test.configuration.fallalloverthefloor.ibmfeature E CWWKE0701E: bundle test.configuration.fallalloverthefloor.ibmfeature:1.0.61.202201191756 (23)[com.ibm.ws.logging.fat.fallalloverthefloor.ibmfeature.BrokenFeature(214)] : The activate method has thrown an exception com.ibm.ws.logging.fat.fallalloverthefloor.ibmfeature.BrokenFeature$ConfigurationReceivedException
	at com.ibm.ws.logging.fat.fallalloverthefloor.ibmfeature.BrokenFeature.reallyThrowAnException(BrokenFeature.java:40)
	at com.ibm.ws.logging.fat.fallalloverthefloor.ibmfeature.BrokenFeature.thinkAboutThrowingAnException(BrokenFeature.java:32)
	at com.ibm.ws.logging.fat.fallalloverthefloor.ibmfeature.BrokenFeature.activate(BrokenFeature.java:24)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.felix.scr.impl.inject.methods.BaseMethod.invokeMethod(BaseMethod.java:244)
	at org.apache.felix.scr.impl.inject.methods.BaseMethod.access$500(BaseMethod.java:41)
	at org.apache.felix.scr.impl.inject.methods.BaseMethod$Resolved.invoke(BaseMethod.java:685)
	at org.apache.felix.scr.impl.inject.methods.BaseMethod.invoke(BaseMethod.java:529)
	at org.apache.felix.scr.impl.inject.methods.ActivateMethod.invoke(ActivateMethod.java:318)
	at org.apache.felix.scr.impl.inject.methods.ActivateMethod.invoke(ActivateMethod.java:308)
	at org.apache.felix.scr.impl.manager.SingleComponentManager.createImplementationObject(SingleComponentManager.java:354)
	at org.apache.felix.scr.impl.manager.SingleComponentManager.createComponent(SingleComponentManager.java:115)
	at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:1000)
	at org.apache.felix.scr.impl.manager.SingleComponentManager.getServiceInternal(SingleComponentManager.java:973)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.activateInternal(AbstractComponentManager.java:785)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.enableInternal(AbstractComponentManager.java:674)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.enable(AbstractComponentManager.java:437)
	at org.apache.felix.scr.impl.manager.ConfigurableComponentHolder.enableComponents(ConfigurableComponentHolder.java:667)
	at org.apache.felix.scr.impl.BundleComponentActivator.initialEnable(BundleComponentActivator.java:305)
	at org.apache.felix.scr.impl.Activator.loadComponents(Activator.java:554)
	at org.apache.felix.scr.impl.Activator.access$200(Activator.java:70)
	at org.apache.felix.scr.impl.Activator$ScrExtension.start(Activator.java:421)
	at org.apache.felix.scr.impl.AbstractExtender.createExtension(AbstractExtender.java:196)
	at org.apache.felix.scr.impl.AbstractExtender.modifiedBundle(AbstractExtender.java:169)
	at org.apache.felix.scr.impl.AbstractExtender.modifiedBundle(AbstractExtender.java:49)
	at org.osgi.util.tracker.BundleTracker$Tracked.customizerModified(BundleTracker.java:488)
	at org.osgi.util.tracker.BundleTracker$Tracked.customizerModified(BundleTracker.java:1)
	at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:232)
	at org.osgi.util.tracker.BundleTracker$Tracked.bundleChanged(BundleTracker.java:450)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:935)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:228)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEventPrivileged(EquinoxEventPublisher.java:229)
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.lambda$0(EquinoxEventPublisher.java:141)
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher$$Lambda$115/0x0000000000000000.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:682)
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:140)
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:130)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor.publishModuleEvent(EquinoxContainerAdaptor.java:206)
	at org.eclipse.osgi.container.Module.publishEvent(Module.java:499)
	at org.eclipse.osgi.container.Module.start(Module.java:486)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.lambda$1(ModuleContainer.java:1834)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$$Lambda$166/0x0000000000000000.run(Unknown Source)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$$Lambda$230/0x0000000000000000.execute(Unknown Source)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1829)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1778)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1739)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1661)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:228)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:339)
 ```

**Comment by fmhwong** [comment]
The problem is this [line](https://github.com/OpenLiberty/open-liberty/blob/d4a4552f1d274fdf9fe59575865090bd3c233a04/dev/com.ibm.ws.logging.core/src/com/ibm/ws/logging/internal/PackageProcessor.java#L251) assumes the package name is in front of the last dot which these 2 lines are not.

```
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$$Lambda$61.000000009400A1A0.run(Unknown Source)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$$Lambda$96.0000000094017900.execute(Unknown Source)
```

**Comment by fmhwong** [comment]
Opened a Java defect in RTC 289225.

**Comment by fmhwong** [comment]
No occurrences in last 2 weeks.
