### ISSUE TITLE
Build break defect 288569: com.ibm.ws.wssecurity_fat.wsscxf.1 CxfX509StrTypeTests.java - The signature or decryption was invalid

### ISSUE THREAD

**Issue by meiaus** [OpenLiberty/open-liberty#20061]
Recap from 288569:

The history issue https://github.com/OpenLiberty/open-liberty/issues/18361 addressed the similar issue and it seems that in the recen builds the method execution sequence is changed, which caused the expected version of server.xml mismatched by the corresponding test methods.  For example, from current output.txt (taken from Jan30's resport: FAT Output Logs: https://libertyfs.hursley.ibm.com/liberty/dev/SOE/BucketOutput/2022-01-24/com.ibm.ws.wssecurity_fat.wsscxf.1/_jHhncICbEeykJKbDLxYjRw/fatoutput-com.ibm.ws.wssecurity_fat.wsscxf.1.zip ), where the method sequence shows:

[01/30/2022 05:25:53:462 PST] 001 FATRunner                      evaluate                       I entering com.ibm.ws.wssecurity.fat.cxf.x509token.CxfX509StrTypeTests.testCxfClientKeysMismatch
[01/30/2022 05:25:53:463 PST] 001 CommonTests                    testCxfClientKeysMismatch_EE8_ I *****************************Starting TEST: testCxfClientKeysMismatch_EE8_FEATURES

. . .

[01/30/2022 05:26:41:243 PST] 001 FATRunner                      evaluate                       I exiting com.ibm.ws.wssecurity.fat.cxf.x509token.CxfX509StrTypeTests.testCxfClientKeysMismatch
[01/30/2022 05:26:41:245 PST] 001 FATRunner                      evaluate                       I entering com.ibm.ws.wssecurity.fat.cxf.x509token.CxfX509StrTypeTests.testCxfClientSignThumbPrint

. . .

[01/30/2022 05:26:42:623 PST] 001 FATRunner                      evaluate                       I exiting com.ibm.ws.wssecurity.fat.cxf.x509token.CxfX509StrTypeTests.testCxfClientSignThumbPrint
[01/30/2022 05:26:42:624 PST] 001 FATRunner                      evaluate                       I entering com.ibm.ws.wssecurity.fat.cxf.x509token.CxfX509StrTypeTests.testCxfClientSignIssuerSerial

. . .

whereas in the java file: https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.wssecurity_fat.wsscxf.1/fat/src/com/ibm/ws/wssecurity/fat/cxf/x509token/CxfX509StrTypeTests.java, the method sequence is:

[@Test](https://wasrtc.hursley.ibm.com:9443/jazz/users/Test)
public void testCxfClientSignIssuerSerial() throws Exception {
. . .

[@Test](https://wasrtc.hursley.ibm.com:9443/jazz/users/Test)
public void testCxfClientSignThumbPrint() throws Exception {

. . .

[@Test](https://wasrtc.hursley.ibm.com:9443/jazz/users/Test)
[@AllowedFFDC](https://wasrtc.hursley.ibm.com:9443/jazz/users/AllowedFFDC)(value = { "org.apache.ws.security.WSSecurityException" }, repeatAction = { EmptyAction.ID })
[@ExpectedFFDC](https://wasrtc.hursley.ibm.com:9443/jazz/users/ExpectedFFDC)(value = { "org.apache.wss4j.common.ext.WSSecurityException" }, repeatAction = { EE8FeatureReplacementAction.ID })
public void testCxfClientKeysMismatch() throws Exception {

. . .

And the potential root cause could be the negative test method testCxfClientKeysMismatch uses unique server.xml per EE7 or EE8 but when the method sequence is changed, the postive test method like testCxfClientSignIssuerSerial executed after the negative method may re-use the version of server.xml only intended for the negative test. The fix will be add reconfigServer call to ensure the postive method uses the required server.xml.

reconfigServer(System.getProperty("user.dir") + File.separator + server.getPathToAutoFVTNamedServer() + "server_enc.xml");
} else if (featureVersion.equals("EE8")) {
reconfigServer(System.getProperty("user.dir") + File.separator + server.getPathToAutoFVTNamedServer() + "server_enc_wss4j.xml");
}
if (featureVersion.equals("EE7")) {

**Comment by meiaus** [comment]
Attempted local tests:

1. When the method sequence is changed to the following, the test didn't fail.

public void testCxfClientKeysMismatch()
public void testCxfClientSignIssuerSerial()
public void testCxfClientSignThumbPrint() 

2. When the method sequence is changed to the following, the test failed as seen in 288569

public void testCxfClientKeysMismatch()
public void testCxfClientSignThumbPrint() 
public void testCxfClientSignIssuerSerial()

junit result:

![image](https://user-images.githubusercontent.com/27024803/153268064-36ec3fff-d97d-4094-a0b3-683627abd3ba.png)


messages.log:
```
...
2/9/22, 12:18:28:227 CST] 00000032 SystemOut                                                    O ************************ testCxfClientSignIssuerSerial ************************
...

[2/9/22, 12:18:28:516 CST] 00000038 .ws.org.apache.cxf.cxf.core.3.2:1.0.62.202202071740(id=161)] W Interceptor for {http://x509sig.wssecfvt.test}X509XmlStrService2 has thrown exception, unwinding now
org.apache.cxf.binding.soap.SoapFault: A security error was encountered when verifying the message
	at org.apache.cxf.ws.security.wss4j.WSS4JUtils.createSoapFault(WSS4JUtils.java:238)
...
Caused by: org.apache.wss4j.common.ext.WSSecurityException: The signature or decryption was invalid
	at org.apache.wss4j.dom.processor.SignatureProcessor.handleToken(SignatureProcessor.java:202)
	at org.apache.wss4j.dom.engine.WSSecurityEngine.processSecurityHeader(WSSecurityEngine.java:340)
	at org.apache.cxf.ws.security.wss4j.WSS4JInInterceptor.handleMessageInternal(WSS4JInInterceptor.java:336)

```

**Comment by meiaus** [comment]
The latest PB build (Build Liberty Personal Build - EBC meiaus-20123-20220216-1343) with soe platform specified:
`soe.platform.requests WIN2022_OPENJDK17_TEMURIN_64_EBC,WIN2019_OPENJDK11_TEMURIN_64_EBC,RHEL7_X86_SUNJDK17_64_EBC`

and only the build of WIN2022_OPENJDK17_TEMURIN_64_EBC created the original failing execution order, where the fix is verified:
(Note: The specified `WIN2019_OPENJDK11_TEMURIN_64_EBC,RHEL7_X86_SUNJDK17_64_EBC` were the platforms originally reported with failure in the defect, but they didn't recreate the same execution order in this run.  It seems that the intermittency is observed as well.)

Junit:
![image](https://user-images.githubusercontent.com/27024803/154774282-e07e00fd-8323-496d-8839-497228e3be4b.png)

output.txt:
```
...
[02/17/2022 21:45:02:666 PST] 001 CommonTests                    testCxfClientKeysMismatch_EE8_ I *****************************Starting TEST: testCxfClientKeysMismatch_EE8_FEATURES

...
http://localhost:8010/x509sigclient/CxfX509SigSvcClient?id=user1&msg=&serviceName=X509XmlStrService3&testName=testCxfClientKeysMismatch&servicePort=UrnX509Str3&httpSecureDefaultPort=&clientWsdl=&pw=security&httpDefaultPort=8010
. . .
[02/17/2022 21:45:34:288 PST] 001 CommonTests                    testCxfClientKeysMismatch      I testCxfClientKeysMismatch: PASS
[02/17/2022 21:45:54:831 PST] 001 FATRunner                      evaluate                       I exiting com.ibm.ws.wssecurity.fat.cxf.x509token.CxfX509StrTypeTests.testCxfClientKeysMismatch
[02/17/2022 21:45:54:834 PST] 001 FATRunner                      evaluate                       I entering com.ibm.ws.wssecurity.fat.cxf.x509token.CxfX509StrTypeTests.testCxfClientSignThumbPrint
[02/17/2022 21:45:54:845 PST] 001 CommonTests                    testCxfClientSignThumbPrint_EE I *****************************Starting TEST: testCxfClientSignThumbPrint_EE8_FEATURES

. . .
[02/17/2022 21:45:56:934 PST] 001 CommonTests                    testCxfClientSignThumbPrint    I testCxfClientSignThumbPrint: PASS
[02/17/2022 21:45:56:934 PST] 001 CommonTests                    testCxfClientSignThumbPrint_EE I *****************************Ending TEST 
[02/17/2022 21:45:56:945 PST] 001 FATRunner                      evaluate                       I exiting com.ibm.ws.wssecurity.fat.cxf.x509token.CxfX509StrTypeTests.testCxfClientSignThumbPrint
[02/17/2022 21:45:56:947 PST] 001 FATRunner                      evaluate                       I entering com.ibm.ws.wssecurity.fat.cxf.x509token.CxfX509StrTypeTests.testCxfClientSignIssuerSerial
[02/17/2022 21:45:56:957 PST] 001 CommonTests                    testCxfClientSignIssuerSerial_ I *****************************Starting TEST: testCxfClientSignIssuerSerial_EE8_FEATURES

. . .

[02/17/2022 21:45:58:294 PST] 001 CommonTests                    testCxfClientSignIssuerSerial  I testCxfClientSignIssuerSerial: PASS
[02/17/2022 21:45:58:294 PST] 001 CommonTests                    testCxfClientSignIssuerSerial_ I *****************************Ending TEST 
[02/17/2022 21:45:58:304 PST] 001 FATRunner                      evaluate                       I exiting com.ibm.ws.wssecurity.fat.cxf.x509token.CxfX509StrTypeTests.testCxfClientSignIssuerSerial

```

messages.log:
```
********************************************************************************
product = WebSphere Application Server 22.0.0.3 (wlp-1.0.62.202202161400)
wlp.install.dir = C:/Users/jazz_build/Build/jazz-build-engines/wasrtc/EBCPROD/build/dev/image/output/wlp/
java.home = C:\Users\jazz_build\Build\jazz-build-engines\wasrtc\EBCPROD\jvms\jdk-17.0.2+8
java.version = 17.0.2
java.runtime = OpenJDK Runtime Environment (17.0.2+8)
os = Windows Server 2022 (10.0; amd64) (en_US)
process = 5196@ebcprh21759324-n

```

**Comment by meiaus** [comment]
Side information regarding execution order: https://github.com/junit-team/junit4/blob/main/doc/ReleaseNotes4.11.md#test-execution-order

**Comment by meiaus** [comment]
The PR is merged: https://github.com/OpenLiberty/open-liberty/pull/20123
