### ISSUE TITLE
Identify WOLA (Z)FATS and run them successfully

### ISSUE THREAD

**Issue by hutchig** [OpenLiberty/open-liberty#20183]

**Comment by hutchig** [comment]
https://wasrtc.hursley.ibm.com:9443/jazz/resource/itemOid/com.ibm.team.build.BuildResult/_FKabUJo1EeyylMvVD7B-oA  built successfully but did not run the FATs due to infrastructure problems it has been resubmitted as https://wasrtc.hursley.ibm.com:9443/jazz/resource/itemOid/com.ibm.team.build.BuildResult/__sQSwJ4UEey_qP_JrfMVIQ

**Comment by hutchig** [comment]
<img width="485" alt="image" src="https://user-images.githubusercontent.com/2861921/173803407-bb996bdb-8fe5-4ee3-bf6c-d0dbba43a5cf.png">
zfats='com.ibm.ws.jbatch.wola_zfat,com.ibm.ws.jbatch.security_zfat,com.ibm.ws.jbatch_zfat,com.ibm.ws.zos.channel.wola_zfat,com.ibm.ws.zos.connect.wola_zfat,com.ibm.ws.zos.ola.ims.svt_zfat,com.ibm.ws.zos.ola_zfat,com.ibm.ws.zos.ola.alcs_zfat,'

**Comment by hutchig** [comment]
- [x] clean com.ibm.ws.jbatch.wola_zfat,
- [x] clean com.ibm.ws.jbatch.security_zfat,
- [x] clean com.ibm.ws.jbatch_zfat,
- [ ] clean com.ibm.ws.zos.channel.wola_zfat,
- [x] clean com.ibm.ws.zos.connect.wola_zfat,
- [x] clean com.ibm.ws.zos.ola.ims.svt_zfat,
- [x] clean com.ibm.ws.zos.ola_zfat,
- [ ] clean com.ibm.ws.zos.ola.restart_zfat,
- [ ] clean com.ibm.ws.zos.ola.alcs_zfat

**Comment by hutchig** [comment]
https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_hanVUO5aEeyVkLDPEXw2dw&tab=com.ibm.team.build.web.ui.internal.editors.result.test.TestProvider
<img width="1347" alt="image" src="https://user-images.githubusercontent.com/2861921/174584973-80ee1d85-24f6-434f-86bd-a1bfd6750bcd.png">

**Comment by hutchig** [comment]
IMS testing is via ims.svt.FATTest:
<img width="328" alt="image" src="https://user-images.githubusercontent.com/2861921/174776477-def3b69e-3daa-4c5b-9742-454d0024a661.png">


(I can also see runs of this that fail with 
java.io.FileNotFoundException: File '/WebSphere/Misc/jazz_build/jbe_zrock157/jazz/buildsystem/buildengine/eclipse/build/dev/image/output/wlp/dev/api/ibm/zos/bboaapip.include' does not exist
in an unchanged (basically main branch)
...and there are lots of IMS AND CICS testing in com.ibm.ws.zos.ola_zfat
e.g https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_92LlYPLsEeyYXLZn0n3zUg&tab=com.ibm.team.build.web.ui.internal.editors.result.overview.OverviewPage

**Comment by hutchig** [comment]
<img width="1088" alt="image" src="https://user-images.githubusercontent.com/2861921/174776949-9a549167-d834-4a39-bbb6-a7627e2521a0.png">

Only *channel* and *alcs* FAT buckets remain to verify as 100% working

**Comment by hutchig** [comment]
The alcs specific build at https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_SeprIPCxEeyYXLZn0n3zUg&tab=com.ibm.team.build.web.ui.internal.editors.result.properties.PropertiesProvider with


fat.buckets.to.run | com.ibm.ws.zos.ola.alcs_zfat
-- | --

Has appearred to run 0 tests.
Think I found why!:
~/libertyGit/WS-CD-Open/dev/com.ibm.ws.zos.ola.alcs_zfat
$ ls
build				publish
build-ztest.xml.**disabled**

**Comment by hutchig** [comment]
Ditto for channel FAT:
$ cd com.ibm.ws.zos.channel.wola_zfat
~/libertyGit/WS-CD-Open/dev/com.ibm.ws.zos.channel.wola_zfat
$ ls
build				publish
build-ztest.xml.**disabled**	test-applications
fat				test-bundles

**Comment by hutchig** [comment]
alcs and channel ZFAT runs requested at https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewDefinition&id=_JWdEUD7dEemKFI0xRbWJ_w
https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_rVJ18PFGEeyYXLZn0n3zUg

**Comment by hutchig** [comment]
As per https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_rVJ18PFGEeyYXLZn0n3zUg&tab=com.ibm.team.build.web.ui.internal.editors.result.overview.OverviewPage
channel zfat fails to build: com.ibm.ws.zos.channel.wola_zfat
which prevents ANY zfats running 
Caused by: /home/jazz_build/Build/jbe/build/WS-CD-Open/dev/ant_build/public_imports/internal_imports/test_bundles.xml:80: Failed to build jar file: 
	at aQute.bnd.ant.BndTask.executeBackwardCompatible(BndTask.java:281)
	at aQute.bnd.ant.BndTask.execute(BndTask.java:116)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
	at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:392)
	at org.apache.tools.ant.Target.performTasks(Target.java:413)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1251)
	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:442)
	... 255 more
Caused by: /home/jazz_build/Build/jbe/build/WS-CD-Open/dev/com.ibm.ws.zos.channel.wola_zfat/test-bundles/wola.channel.test.helper.service/bnd.bnd: bnd failed
	at aQute.bnd.ant.BndTask.executeBackwardCompatible(BndTask.java:237)

**Comment by hutchig** [comment]
(From the main 1.5Meg build.log "Zipped up build.log for running ivyBuild"
[21-Jun-2022 10:00:18:110 PDT] 00000030       [bnd] 1 ERRORS
[21-Jun-2022 10:00:18:111 PDT] 00000030       [bnd]  in component wola.channel.test.helper.service.internal.WOLAChannelTestHelperServiceImpl, modified method modify specified but not found
[21-Jun-2022 10:00:18:111 PDT] 00000030       [bnd] /home/jazz_build/Build/jbe/build/WS-CD-Open/dev/com.ibm.ws.zos.channel.wola_zfat/test-bundles/wola.channel.test.helper.service/bnd.bnd: bnd failed
[21-Jun-2022 10:00:18:111 PDT] 00000030       [bnd]

**Comment by hutchig** [comment]
https://bnd.bndtools.org/chapters/200-components.html
<img width="505" alt="image" src="https://user-images.githubusercontent.com/2861921/175031104-1b354b2e-ddfc-408b-b691-6f312bf6cbf3.png">
<img width="718" alt="image" src="https://user-images.githubusercontent.com/2861921/175031166-c004bb1e-f3c1-47b5-a502-354475a31328.png">
<img width="433" alt="image" src="https://user-images.githubusercontent.com/2861921/175031234-11173ab9-5faf-4dc3-b934-12542b0bd92c.png">

**Comment by hutchig** [comment]
All the alcs zfat tests fail.

Errors are of the form:
java.io.FileNotFoundException: File '/WebSphere/Misc/jazz_build/jbe_boss0204/jazz/buildsystem/buildengine/eclipse/build/dev/image/output/wlp/clients/zos/bboa1reg' does not exist
	at com.ibm.ws.zos.ola.alcs.FATSuite.copyWolaClientModules(FATSuite.java:248)
OR
junit.framework.AssertionFailedError: ALCS compile exit 3 failure
	at com.ibm.ws.zos.ola.alcs.FATSuite.setUp(FATSuite.java:131)
OR
junit.framework.AssertionFailedError: ALLOCDS2 completion message not found
	at com.ibm.ws.zos.ola.alcs.FATSuite.setUp(FATSuite.java:100)

Not a single ALCS test passes in the standard #build (with edited properties) environment.

**Comment by hutchig** [comment]
The channel tests are also not healthy in the standard #build with properties edited to run them: 
<img width="442" alt="image" src="https://user-images.githubusercontent.com/2861921/175286196-c5260b26-76d3-4c8b-9559-c4da3fdda5a2.png">

**Comment by hutchig** [comment]
https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_3N0xUPLsEeyYXLZn0n3zUg&tab=com.ibm.team.build.web.ui.internal.editors.result.overview.OverviewPage
CICS coverage:
<img width="775" alt="image" src="https://user-images.githubusercontent.com/2861921/175505807-e82ff1f6-e661-4334-88a1-5b3b954bda80.png">

com.ibm.ws.zos.channel.wola_test
<img width="1670" alt="image" src="https://user-images.githubusercontent.com/2861921/175506561-160166b9-6879-42d6-88f5-f65736f05749.png">

com.ibm.ws.zos.ola_zfat
This also passed (but required an auto-second-run):

<img width="1650" alt="image" src="https://user-images.githubusercontent.com/2861921/175509958-a522ed9e-7ae2-4717-83a6-0166a1dec583.png">

com.ibm.ws.zos.connect_test
<img width="1679" alt="image" src="https://user-images.githubusercontent.com/2861921/175507424-a38b8f22-5df6-4b7f-963e-8956b5efaa5e.png">
	
com.ibm.ws.zos.connect.wola_zfat FAT tests are not 100% reliable first time:
WOLAConnectCICSFATTest
<img width="1670" alt="image" src="https://user-images.githubusercontent.com/2861921/175507269-f4678c72-2cfe-4db8-b383-f2660693c726.png">

But succedded on the second auto-retry:
<img width="1616" alt="image" src="https://user-images.githubusercontent.com/2861921/175509228-12db6868-c25c-4d48-8f05-d03f29aeb1d4.png">
<img width="1413" alt="image" src="https://user-images.githubusercontent.com/2861921/175509421-362f4c40-15eb-4462-9829-9983816cac05.png">

...and just for *Cics*Test completeness:
<img width="595" alt="image" src="https://user-images.githubusercontent.com/2861921/175511020-dc953ab9-3896-4124-bd90-070c0a68898b.png">

**Comment by hutchig** [comment]
IMS test coverage [here](https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_3N0xUPLsEeyYXLZn0n3zUg&tab=com.ibm.team.build.web.ui.internal.editors.result.test.TestProvider)

<img width="695" alt="image" src="https://user-images.githubusercontent.com/2861921/175513453-eaf62b13-602c-4f68-b0e0-a6a9308f28f9.png">

ola_zfat

<img width="1634" alt="image" src="https://user-images.githubusercontent.com/2861921/175514382-07257610-afb5-48dd-82b2-a8f7f58a65a8.png">

<img width="1626" alt="image" src="https://user-images.githubusercontent.com/2861921/175514288-82303221-e158-40b2-ad97-ab4141758cb6.png">


channel.wola_test
<img width="1634" alt="image" src="https://user-images.githubusercontent.com/2861921/175513931-19656226-5c91-4687-8492-60bbe6ae009b.png">

**Comment by hutchig** [comment]
Test not yet verified as running OK:
com.ibm.ws.zos.channel.wola_zfat com.ibm.ws.zos.channel.wola.zfat.WOLAChannelFATTest
testChannelConnect
WebSphere/Misc/jazz_build/jbe_zrock063/jazz/buildsystem/buildengine/eclipse/build/dev/image/output/wlp/lib/native/zos/s390x/bbgzscfms: not found

All alcs tests

**Comment by epj** [comment]
Example z/OS build (**since deleted**) -
https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_G6xpsCoUEe2pPfp3nZ4PGw&tab=com.ibm.team.build.web.ui.internal.editors.result.overview.OverviewPage

**Comment by hutchig** [comment]
build.ztest.xml.disabled are resent in the two 'invalid' testsuites in the above build, one can use a draft PR to rename them for the build @epj

**Comment by epj** [comment]
I'd been getting file not found errors in the zFATs for the WOLA specific include files.  Turns out I'd been trying to use build options which actually causes the build not to include some zos specific parts.   Here is what a personal build needs to specify, beyond the defaults you get with a hash-build:

For a zos personal build, specify:
fat.buckets.to.run  [give the list]
fat.test.mode       full
spawn.zos           true
                    
Do NOT specify 
spawn.common.fats.on.zos  
spawn.zos.tests 
spawn.fullfat.buckets

**Comment by epj** [comment]
All tests and results have been tracked in a spreadsheet kept in Box.
