### ISSUE TITLE
webContainer property skipMetaInfResourcesProcessing=true can cause NullPointerException in JSP taglib 

### ISSUE THREAD

**Issue by epj** [OpenLiberty/open-liberty#20247]
**Describe the bug**  
In Liberty, if webContainer property skipMetaInfResourcesProcessing is true, and a JSP references a taglib with a path under WEB-INF, it can cause a NullPointerException on the call to the JSP resulting in just the message Error 500: java.lang.NullPointerException.   The error in messages.log is as follows:

java.lang.NullPointerException
        at java.base/java.io.File.<init>(File.java:278)
        at com.ibm.ws.jsp.webcontainerext.JspDependent.isOutdated(JspDependent.java:84)
        at com.ibm.ws.jsp.webcontainerext.JspDependent.toString(JspDependent.java:129)
        at java.base/java.text.MessageFormat.subformat(MessageFormat.java:1302)
        at java.base/java.text.MessageFormat.format(MessageFormat.java:885)
        at java.base/java.text.Format.format(Format.java:158)
        at java.base/java.text.MessageFormat.format(MessageFormat.java:860)
        at com.ibm.ws.logging.internal.impl.BaseTraceFormatter.formatMessage(BaseTraceFormatter.java:301)
        at com.ibm.ws.logging.internal.impl.BaseTraceFormatter.formatVerboseMessage(BaseTraceFormatter.java:373)
        at com.ibm.ws.logging.internal.impl.BaseTraceService.publishTraceLogRecord(BaseTraceService.java:1072)
        at com.ibm.ws.logging.internal.impl.BaseTraceService.publishLogRecord(BaseTraceService.java:1043)
        at com.ibm.ws.logging.internal.impl.BaseTraceService$2.publish(BaseTraceService.java:285)
        at java.logging/java.util.logging.Logger.log(Logger.java:979)
        at com.ibm.ws.logging.internal.WsLogger.log(WsLogger.java:138)
        at com.ibm.ws.logging.internal.WsLogger.logp(WsLogger.java:336)
        at com.ibm.ws.logging.internal.WsLogger.exiting(WsLogger.java:465)
        at com.ibm.ws.jsp.webcontainerext.JspDependent.<init>(JspDependent.java:58)
        at com.ibm.ws.jsp.webcontainerext.AbstractJSPExtensionServletWrapper.loadClassInformation(AbstractJSPExtensionServletWrapper.java:233)
        at com.ibm.ws.jsp.webcontainerext.AbstractJSPExtensionServletWrapper.handleRequest(AbstractJSPExtensionServletWrapper.java:214)
        at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1227)
        at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:5049)
        ... 20 more
 

**Steps to Reproduce**  
See above.

**Expected behavior**  
The JSP should return to the client without a NPE even in file not found situations.

**Comment by epj** [comment]
Workaround options:
set webContainer property skipMetaInfResourcesProcessing to false
or 
remove the include or taglib statement in the JSP that references a file not found.
