### ISSUE TITLE
Avoid ConcurrentModificationException during dynamic configuration updates for federatedRepository  and user repositories

### ISSUE THREAD

**Issue by kristip17** [OpenLiberty/open-liberty#20298]
**Describe the bug**  
After configuration updates for both a federatedRepository and custom user registries or repositories, a `ConcurrentModificationException` error can occur. The `ConcurrentModificationException` could lead to a `CWIMK0004E` message being logged, indicating that the participating base entry cannot be found even though the registries are defined in the server.xml

If there is a stack trace, please include the FULL stack trace (without any `[internal classes]` lines in it). To find the full stack trace, you may need to check in `$WLP_OUTPUT_DIR/messages.log`

```
[2/16/22, 17:09:53:068 PST] 00000037 com.ibm.ws.kernel.feature.internal.FeatureManager            I CWWKF0007I: Feature update started.
[2/16/22, 17:09:53:098 PST] 00000037 com.ibm.ws.kernel.feature.internal.FeatureManager            A CWWKF0008I: Feature update completed in 0.130 seconds.
[2/16/22, 17:09:54:470 PST] 00000029 SystemErr                                                    R Exception in thread "Default Executor-thread-2"
[2/16/22, 17:09:54:476 PST] 00000029 SystemErr                                                    R java.util.ConcurrentModificationException
[2/16/22, 17:09:54:477 PST] 00000029 SystemErr                                                    R at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1043)
[2/16/22, 17:09:54:481 PST] 00000029 SystemErr                                                    R at java.base/java.util.ArrayList$Itr.next(ArrayList.java:997)
[2/16/22, 17:09:54:482 PST] 00000029 SystemErr                                                    R at com.ibm.ws.security.wim.ConfigManager$1.successfulCompletion(ConfigManager.java:671)
[2/16/22, 17:09:54:483 PST] 00000029 SystemErr                                                    R at com.ibm.ws.security.wim.ConfigManager$1.successfulCompletion(ConfigManager.java:655)
[2/16/22, 17:09:54:484 PST] 00000029 SystemErr                                                    R at com.ibm.ws.threading.internal.NonCancelableResultFuture.callListeners(NonCancelableResultFuture.java:135)
[2/16/22, 17:09:54:485 PST] 00000029 SystemErr                                                    R at com.ibm.ws.threading.internal.FutureMonitorImpl.setResult(FutureMonitorImpl.java:143)
[2/16/22, 17:09:54:486 PST] 00000029 SystemErr                                                    R at com.ibm.ws.runtime.update.internal.RuntimeUpdateManagerImpl$NotificationImpl.setResult(RuntimeUpdateManagerImpl.java:212)
[2/16/22, 17:09:54:486 PST] 00000029 SystemErr                                                    R at com.ibm.ws.config.xml.internal.ConfigRefresher.endConfigChanges(ConfigRefresher.java:204)
[2/16/22, 17:09:54:487 PST] 00000029 SystemErr                                                    R at com.ibm.ws.config.xml.internal.ConfigRefresher.access$000(ConfigRefresher.java:40)
[2/16/22, 17:09:54:488 PST] 00000029 SystemErr                                                    R at com.ibm.ws.config.xml.internal.ConfigRefresher$1.run(ConfigRefresher.java:187)
[2/16/22, 17:09:54:489 PST] 00000029 SystemErr                                                    R at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:245)
[2/16/22, 17:09:54:490 PST] 00000029 SystemErr                                                    R at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2/16/22, 17:09:54:491 PST] 00000029 SystemErr                                                    R at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2/16/22, 17:09:54:492 PST] 00000029 SystemErr                                                    R at java.base/java.lang.Thread.run(Thread.java:866)
```

Example of the `CWIMK0004E` message:
```
CWIMK0004E: The user registry operation could not be completed. The participating base entry definition o=SampleCustomRealm is not valid. Correct the participating base entry definition in the server.xml file. For example the syntax is <participatingBaseEntry name='...'/>. message can be logged incorrectly.
```

Follow up to the fix completed in #14908

**Steps to Reproduce**  
Timing issues, occurs randomly, usually when doing several dynamic config updates.

**Expected behavior**  
A `ConcurrentModificationException` error should not occur and a `CWIMK0004E` message should not occur when the Federated Repository and user registry configuration is correct.

**Diagnostic information:**  
 - OpenLiberty Version: 22.0.0.3
 - Affected feature(s): `federatedRepository-1.0` or `ldapRegistry-3.0`
 - Java Version: N/A
 - server.xml configuration (WITHOUT sensitive information like passwords): See `com.ibm.ws.security.wim.adapter.ldap.fat.LDAPRegistryDynamicUpdateTest.updateAppSecurity2ToAppSecurity1FeatureTest`
 - If it would be useful, upload the messages.log file found in `$WLP_OUTPUT_DIR/messages.log`: See RTC 289496

**Comment by mbroz2** [comment]
@kristip17 please update the description of this `relesae bug` using the [bug report template](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=&labels=release+bug&template=bug_report.md&title=)
