### ISSUE TITLE
Error while using UserProfile class in Social login feature

### ISSUE THREAD

**Issue by vijayanjay** [OpenLiberty/open-liberty#20322]
**Describe the bug**  

Followed below link to fetch userInfo upon user authenticated by social media.
https://www.ibm.com/docs/en/was-liberty/zos?topic=SS7K4U_liberty/com.ibm.websphere.javadoc.liberty.doc/com.ibm.websphere.appserver.api.social_1.0-javadoc/com/ibm/websphere/security/social/package-summary.html

Tried using userProfile/Manager like below,

`UserProfile userProfile = UserProfileManager.getUserProfile();
`
Getting below error,
`pod.java.lang.NoClassDefFoundError: javax.security.auth.Subject
`

**Steps to Reproduce**  
Integrated social login feature in liberty server and imported UserProfileManager and UserProfile to fetch IdToken/userInfo.
After authenticating using thirdparty login, while calling getUserProfile we are facing this error.

**Expected behavior**  
getUserInfo should be successful with UserProfile.

**Diagnostic information:**  
server.xml which we are using is as below,

```
<server>
    <featureManager>
        <feature>socialLogin-1.0</feature>
        <feature>appSecurity-4.0</feature>
    </featureManager>
    <oidcLogin id="googleOIDCLogin" clientId="51.apps.googleusercontent.com"
    clientSecret="{xor}G="  
    authorizationEndpoint="https://accounts.google.com/o/oauth2/v2/auth"
    tokenEndpoint="https://www.googleapis.com/oauth2/v4/token"
    jwksUri="https://www.googleapis.com/oauth2/v3/certs"
    scope="openid profile email"
    userNameAttribute="email"
    isClientSideRedirectSupported="true"
    issuer="https://accounts.google.com/"
    authFilterRef="socialAuthFilter" 
    realmNameAttribute="iss" >
    </oidcLogin>
    <sslDefault sslRef="DefaultSSLSettings" />
    <ssl id="DefaultSSLSettings" keyStoreRef="defaultKeyStore" trustStoreRef="defaultKeyStore" clientAuthenticationSupported="true"/>
    <keyStore id="defaultKeyStore" password="insecurePass" />
    <webAppSecurity trackLoggedOutSSOCookies="true"/>
    <webAppSecurity ssoRequiresSSL="true"/>
    <authFilter id="socialAuthFilter">
       <requestUrl id="thirdPartyURL" urlPattern="loginwiththirdparty" matchType="Contains"/>
    </authFilter>    
</server>
```

Liberty version:
```
Product name: WebSphere Application Server
Product version: 22.0.0.2
Product edition: BASE_ILAN
```

Java version:
```
java -version
java version "1.8.0_311"
Java(TM) SE Runtime Environment (build 8.0.7.0 - pxa6480sr7-20211025_01(SR7))
IBM J9 VM (build 2.9, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20211022_15212 (JIT enabled, AOT enabled)
OpenJ9   - 6abb372
OMR      - b898db9
IBM      - 2f2c48b)
JCL - 20210930_01 based on Oracle jdk8u311-b11
```

**Comment by jhanders34** [comment]
In order to determine more of what is going on, a stack trace of the exception should help narrow down which code is getting this exception.  If there is an earlier exception that would be good to know as well.  The NoClassDefFoundError is for a class that is in the Java runtime so it is definitely very odd.

**Comment by vijayanjay** [comment]
@jhanders34  please find the stack trace for above exception.

```
[3/7/22 3:22:32:309 GMT] 00000027 id=                                                                      R  java.lang.NoClassDefFoundError: javax.security.auth.Subject
[3/7/22 3:22:32:310 GMT] 00000027 id=                                                                      R  at com.ibm.websphere.security.social.UserProfileManager.getUserProfile(UserProfileManager.java:40)
[3/7/22 3:22:32:311 GMT] 00000027 id=                                                                      R  at security.custom.store.CustomStoreMongo.create(CustomStoreMongo.java:305)
[3/7/22 3:22:32:312 GMT] 00000027 id=                                                                      R  at com.ibm.ws.security.oauth20.plugins.custom.OauthTokenStore.add(OauthTokenStore.java:120)
[3/7/22 3:22:32:312 GMT] 00000027 id=                                                                      R  at com.ibm.oauth.core.internal.oauth20.token.OAuth20TokenFactory.persistToken(OAuth20TokenFactory.java:538)
[3/7/22 3:22:32:313 GMT] 00000027 id=                                                                      R  at com.ibm.oauth.core.internal.oauth20.token.OAuth20TokenFactory.createAuthorizationCode(OAuth20TokenFactory.java:219)
[3/7/22 3:22:32:314 GMT] 00000027 id=                                                                      R  at com.ibm.oauth.core.internal.oauth20.responsetype.impl.OAuth20ResponseTypeHandlerCodeImpl.buildTokensResponseType(OAuth20ResponseTypeHandlerCodeImpl.java:114)
[3/7/22 3:22:32:315 GMT] 00000027 id=                                                                      R  at com.ibm.oauth.core.internal.oauth20.OAuth20ComponentImpl.processAuthorization(OAuth20ComponentImpl.java:268)
[3/7/22 3:22:32:315 GMT] 00000027 id=                                                                      R  at com.ibm.oauth.core.internal.oauth20.OAuth20ComponentImpl.processAuthorization(OAuth20ComponentImpl.java:197)
[3/7/22 3:22:32:316 GMT] 00000027 id=                                                                      R  at com.ibm.ws.security.oauth20.internal.LibertyOAuth20Provider.processAuthorization(LibertyOAuth20Provider.java:1636)
[3/7/22 3:22:32:317 GMT] 00000027 id=                                                                      R  at com.ibm.ws.security.oauth20.web.OAuth20EndpointServices.handleUserAuthentication(OAuth20EndpointServices.java:760)
[3/7/22 3:22:32:317 GMT] 00000027 id=                                                                      R  at com.ibm.ws.security.oauth20.web.OAuth20EndpointServices.processAuthorizationRequest(OAuth20EndpointServices.java:509)
[3/7/22 3:22:32:318 GMT] 00000027 id=                                                                      R  at com.ibm.ws.security.oauth20.web.OAuth20EndpointServices.handleEndpointRequest(OAuth20EndpointServices.java:246)
[3/7/22 3:22:32:319 GMT] 00000027 id=                                                                      R  at com.ibm.ws.security.openidconnect.web.OidcEndpointServices.handleOidcRequest(OidcEndpointServices.java:261)
[3/7/22 3:22:32:320 GMT] 00000027 id=                                                                      R  at com.ibm.ws.security.openidconnect.web.OidcEndpointServlet.handleRequest(OidcEndpointServlet.java:109)
[3/7/22 3:22:32:320 GMT] 00000027 id=                                                                      R  at com.ibm.ws.security.openidconnect.web.OidcEndpointServlet.doGet(OidcEndpointServlet.java:59)
[3/7/22 3:22:32:321 GMT] 00000027 id=                                                                      R  at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
[3/7/22 3:22:32:322 GMT] 00000027 id=                                                                      R  at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
[3/7/22 3:22:32:323 GMT] 00000027 id=                                                                      R  at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1258)
[3/7/22 3:22:32:323 GMT] 00000027 id=                                                                      R  at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:746)
[3/7/22 3:22:32:324 GMT] 00000027 id=                                                                      R  at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:443)
[3/7/22 3:22:32:325 GMT] 00000027 id=                                                                      R  at com.ibm.ws.webcontainer.filter.WebAppFilterChain.invokeTarget(WebAppFilterChain.java:193)
[3/7/22 3:22:32:326 GMT] 00000027 id=                                                                      R  at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:98)
[3/7/22 3:22:32:326 GMT] 00000027 id=                                                                      R  at com.ibm.ws.security.openidconnect.web.OidcRequestFilter.setEndpointRequest(OidcRequestFilter.java:41)
[3/7/22 3:22:32:327 GMT] 00000027 id=                                                                      R  at com.ibm.ws.security.oauth20.web.OAuth20RequestFilter.doFilter(OAuth20RequestFilter.java:95)
[3/7/22 3:22:32:328 GMT] 00000027 id=                                                                      R  at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:201)
[3/7/22 3:22:32:329 GMT] 00000027 id=                                                                      R  at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:91)
[3/7/22 3:22:32:329 GMT] 00000027 id=                                                                      R  at com.ibm.ws.app.manager.wab.internal.OsgiDirectoryProtectionFilter.doFilter(OsgiDirectoryProtectionFilter.java:90)
[3/7/22 3:22:32:330 GMT] 00000027 id=                                                                      R  at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:201)
[3/7/22 3:22:32:331 GMT] 00000027 id=                                                                      R  at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:91)
[3/7/22 3:22:32:332 GMT] 00000027 id=                                                                      R  at com.ibm.ws.webcontainer.filter.WebAppFilterManager.doFilter(WebAppFilterManager.java:1002)
[3/7/22 3:22:32:332 GMT] 00000027 id=                                                                      R  at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1140)
[3/7/22 3:22:32:333 GMT] 00000027 id=                                                                      R  at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1011)
[3/7/22 3:22:32:334 GMT] 00000027 id=                                                                      R  at com.ibm.ws.webcontainer.servlet.CacheServletWrapper.handleRequest(CacheServletWrapper.java:75)
[3/7/22 3:22:32:334 GMT] 00000027 id=                                                                      R  at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:938)
[3/7/22 3:22:32:335 GMT] 00000027 id=                                                                      R  at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:281)
[3/7/22 3:22:32:336 GMT] 00000027 id=                                                                      R  at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1184)
[3/7/22 3:22:32:337 GMT] 00000027 id=                                                                      R  at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:453)
[3/7/22 3:22:32:338 GMT] 00000027 id=                                                                      R  at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:412)
[3/7/22 3:22:32:339 GMT] 00000027 id=                                                                      R  at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:566)
[3/7/22 3:22:32:340 GMT] 00000027 id=                                                                      R  at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:500)
[3/7/22 3:22:32:341 GMT] 00000027 id=                                                                      R  at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:360)
[3/7/22 3:22:32:341 GMT] 00000027 id=                                                                      R  at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.ready(HttpInboundLink.java:327)
[3/7/22 3:22:32:342 GMT] 00000027 id=                                                                      R  at com.ibm.ws.channel.ssl.internal.SSLConnectionLink.determineNextChannel(SSLConnectionLink.java:1100)
[3/7/22 3:22:32:343 GMT] 00000027 id=                                                                      R  at com.ibm.ws.channel.ssl.internal.SSLConnectionLink.readyInboundPostHandshake(SSLConnectionLink.java:757)
[3/7/22 3:22:32:344 GMT] 00000027 id=                                                                      R  at com.ibm.ws.channel.ssl.internal.SSLConnectionLink$MyHandshakeCompletedCallback.complete(SSLConnectionLink.java:427)
[3/7/22 3:22:32:344 GMT] 00000027 id=                                                                      R  at com.ibm.ws.channel.ssl.internal.SSLUtils.handleHandshake(SSLUtils.java:954)
[3/7/22 3:22:32:345 GMT] 00000027 id=                                                                      R  at com.ibm.ws.channel.ssl.internal.SSLHandshakeIOCallback.complete(SSLHandshakeIOCallback.java:85)
[3/7/22 3:22:32:346 GMT] 00000027 id=                                                                      R  at com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:514)
[3/7/22 3:22:32:346 GMT] 00000027 id=                                                                      R  at com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueManager.java:584)
[3/7/22 3:22:32:347 GMT] 00000027 id=                                                                      R  at com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:968)
[3/7/22 3:22:32:348 GMT] 00000027 id=                                                                      R  at com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:1057)
[3/7/22 3:22:32:349 GMT] 00000027 id=                                                                      R  at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:245)
[3/7/22 3:22:32:349 GMT] 00000027 id=                                                                      R  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
[3/7/22 3:22:32:350 GMT] 00000027 id=                                                                      R  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[3/7/22 3:22:32:351 GMT] 00000027 id=                                                                      R  at java.lang.Thread.run(Thread.java:825)
[3/7/22 3:22:32:351 GMT] 00000027 id=                                                                      R  Caused by:
[3/7/22 3:22:32:352 GMT] 00000027 id=                                                                      R  java.lang.ClassNotFoundException: javax.security.auth.Subject cannot be found by security.custom.store_1.0.0
[3/7/22 3:22:32:353 GMT] 00000027 id=                                                                      R  at org.eclipse.osgi.internal.loader.BundleLoader.generateException(BundleLoader.java:516)
[3/7/22 3:22:32:354 GMT] 00000027 id=                                                                      R  at org.eclipse.osgi.internal.loader.BundleLoader.findClass0(BundleLoader.java:511)
[3/7/22 3:22:32:355 GMT] 00000027 id=                                                                      R  at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:403)
[3/7/22 3:22:32:356 GMT] 00000027 id=                                                                      R  at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:168)
[3/7/22 3:22:32:357 GMT] 00000027 id=                                                                      R  at java.lang.ClassLoader.loadClass(ClassLoader.java:873)
[3/7/22 3:22:32:357 GMT] 00000027 id=                                                                      R  ... 55 more

```

**Comment by tjwatson** [comment]
`security.custom.store` appears to be an OSGi bundle installed into Liberty.  Any bundle that needs access to javax.* packages also needs to add that package to their `Import-Package` bundle manifest (JAR manifest) in order to properly wire to the package and load classes from it.

What is not clear to me is where this bundle is coming from.  The server.xml doesn't show any user/product extensions installed nor any shared libraries or bells installed.  Perhaps it is some dynamic bundle installed by Liberty, but I am not aware of what would do that (socialLogin feature?). Did you have some other configuration not shown that is configuring user/product extensions?

**Comment by vijayanjay** [comment]
In our build.gradle we have added below runtime dependencies,

   ` runtime files('libs/com.ibm.ws.security.sso.common_1.0.54.jar','libs/com.ibm.ws.security.openidconnect.common_1.0.57.jar','libs/com.ibm.ws.security.social_1.0.61.jar','libs/com.ibm.ws.security_1.0.61.jar','libs/com.ibm.ws.security.jwt_1.0.61.jar')
`
In Import-package we have already added `com.ibm.websphere.security.social`.

Could you please suggest the specific package to be added for `javax.security.auth.Subject`

We have a custom oauth store and we have imported OSGi to bundle Activator class.

**Comment by tjwatson** [comment]
The `javax.security.auth` should be specified in the `Import-Package` header for your bundle.

I am curious how you enable this bundle to be installed.  I don't see anything in the `server.xml` that would have enabled this bundle to be installed.

**Comment by teddyjtorres** [comment]
The appSecurity-4.0 is a Jakarta EE feature. The javax.security.auth.Subject is not. Please try using the appSecurity-3.0 feature instead.

**Comment by teddyjtorres** [comment]
The stack trace does not correspond to the server.xml file. The trace shows processing of an openidConnectServer-1.0 endpoint, but that is not what is configured.

**Comment by teddyjtorres** [comment]
Please disregard my comment about "The appSecurity-4.0 is a Jakarta EE feature. The javax.security.auth.Subject is not". The Subject class should be available with all the configured features.

**Comment by teddyjtorres** [comment]
Please make sure that API dependencies in build.gradle are from the wlp/dev/ directory. For example, please replace `libs/com.ibm.ws.security.social_1.0.61.jar` with the one from `wlp/dev/api/ibm/com.ibm.websphere.appserver.api.social_1.0.61.jar`. Same for other API jars.

**Comment by vijayanjay** [comment]
Thanks @teddyjtorres @tjwatson 

After replacing appSecurity-4.0 with appSecurity-3.0, authorization endpoint is not redirected.. so kept with old one which is appSecurity-2.0..

After replacing `wlp/dev/api/ibm/com.ibm.websphere.appserver.api.social_1.0.61.jar` we are facing `NoClassDefFoundError: javax.security.auth.Subject` error, but UserProfileManager is coming as null.

Do we have any other suggestion to fetch UserInfo ?? 

We have tried below methods as of now, 

openidconnect.PropagationHelper - IdToken not available
social.UserProfileManager - not able to use this, UserProfileManager is coming as null.

Do we need to add/modify anything in our` /config/configDropins/defaults/social_login_server.xml `

**Comment by tjwatson** [comment]
> After replacing `wlp/dev/api/ibm/com.ibm.websphere.appserver.api.social_1.0.61.jar` we are facing `NoClassDefFoundError: javax.security.auth.Subject` error, but UserProfileManager is coming as null.

Replacing with what?  I had expected you would need to modify your own bundle `security.custom.store`. But I still think we are missing a significant detail on what you are doing.  Can you provide your complete `server.xml`?  How are you installing `security.custom.store`?

**Comment by vijayanjay** [comment]
Replacing `libs/com.ibm.ws.security.social_1.0.61.jar` with `libs/com.ibm.websphere.appserver.api.social_1.0.61.jar`.
complete server.xml is the one which i have shared in above comment, which is present in `/config/configDropins/defaults/social_login_server.xml`
