### ISSUE TITLE
Test Failure: junit.framework.TestSuite.com.ibm.ws.testing.opentracing.test.FATSuite

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#20339]
RTC 289401

```
com.ibm.ws.testing.opentracing.test.FATSuite:java.lang.RuntimeException: Error getting server
    at componenttest.topology.impl.LibertyServerFactory.getLibertyServer(LibertyServerFactory.java:204)
    at componenttest.topology.impl.LibertyServerFactory.getLibertyServer(LibertyServerFactory.java:97)
    at componenttest.topology.impl.LibertyServerFactory.getLibertyServer(LibertyServerFactory.java:79)
    at componenttest.topology.impl.LibertyServerFactory.getLibertyServer(LibertyServerFactory.java:56)
    at componenttest.rules.repeater.FeatureReplacementAction.setup(FeatureReplacementAction.java:559)
    at componenttest.rules.repeater.RepeatTests$CompositeRepeatTestActionStatement.evaluate(RepeatTests.java:142)
Caused by: componenttest.exception.TopologyException: Unable to delete pre-existing server directory: C:/Users/jazz_build/Build/jazz-build-engines/wasrtc/EBCPROD/build/dev/image/output/wlp/usr/servers/opentracingFATServer4
    at componenttest.topology.impl.LibertyServer.setup(LibertyServer.java:658)
    at componenttest.topology.impl.LibertyServer.<init>(LibertyServer.java:599)
    at componenttest.topology.impl.LibertyServerFactory.getLibertyServer(LibertyServerFactory.java:160)
```

I think the problem was `.gitignore` was held by a process so it couldn't be deleted on Windows platform.

```
[03/05/2022 03:43:13:195 PST] 001 RemoteFile                     basicDeleteLocalFile           I Failed to delete 'C:\Users\jazz_build\Build\jazz-build-engines\wasrtc\EBCPROD\build\dev\image\output\wlp\usr\servers\opentracingFATServer2\.gitignore': C:\Users\jazz_build\Build\jazz-build-engines\wasrtc\EBCPROD\build\dev\image\output\wlp\usr\servers\opentracingFATServer2\.gitignore: The process cannot access the file because it is being used by another process
```

**Comment by tonyreigns** [comment]
Build break hasn't appeared in over a month since the latest fix: https://github.com/OpenLiberty/open-liberty/pull/23169

Closing issue.
