### ISSUE TITLE
LibertyRestClientBuilderImpl nonProxyHosts PatternSyntaxException

### ISSUE THREAD

**Issue by Maylann** [OpenLiberty/open-liberty#20403]
It seems that in the LibertyRestClientBuilderImpl [here](https://github.com/OpenLiberty/open-liberty/blame/1927e381f0682fc85d02c1cabcf4959af35c3868/dev/io.openliberty.org.jboss.resteasy.mprestclient/src/org/jboss/resteasy/microprofile/client/ot/LibertyRestClientBuilderImpl.java#L325) it is assumed that the nonProxyHosts are a regex patterns, but they are actually not as they can contain * as wildcards. (See doc https://docs.oracle.com/javase/8/docs/technotes/guides/net/proxies.html)
This results in an exception when my nonproxyHosts are parsed there, see example below:

When running with these nonProxyHosts: -Dhttp.nonProxyHosts="*.svc|*.cluster.local|localhost|127.0.0.1"

it results in following exception:

java.util.regex.PatternSyntaxException: Dangling meta character '*' near index 0
*.svc
^
	at java.base/java.util.regex.Pattern.error(Pattern.java:2028)
	at java.base/java.util.regex.Pattern.sequence(Pattern.java:2203)
	at java.base/java.util.regex.Pattern.expr(Pattern.java:2069)
	at java.base/java.util.regex.Pattern.compile(Pattern.java:1783)
	at java.base/java.util.regex.Pattern.<init>(Pattern.java:1430)
	at java.base/java.util.regex.Pattern.compile(Pattern.java:1069)
	at org.jboss.resteasy.microprofile.client.ot.LibertyRestClientBuilderImpl.build(LibertyRestClientBuilderImpl.java:325)
	at org.jboss.resteasy.microprofile.client.RestClientDelegateBean.create(RestClientDelegateBean.java:129)
	at org.jboss.weld.contexts.unbound.DependentContextImpl.get(DependentContextImpl.java:64)
	at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get(ContextualInstanceStrategy.java:100)
	at org.jboss.weld.bean.ContextualInstance.get(ContextualInstance.java:50)
	at org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:694)
	at org.jboss.weld.manager.BeanManagerImpl.getInjectableReference(BeanManagerImpl.java:794)
	at org.jboss.weld.injection.FieldInjectionPoint.inject(FieldInjectionPoint.java:92)
	at org.jboss.weld.util.Beans.injectBoundFields(Beans.java:345)
	at org.jboss.weld.util.Beans.injectFieldsAndInitializers(Beans.java:356)
	at org.jboss.weld.injection.producer.ResourceInjector$1.proceed(ResourceInjector.java:69)
	at com.ibm.ws.cdi.impl.weld.injection.WebSphereInjectionServicesImpl$3.run(WebSphereInjectionServicesImpl.java:323)
	at com.ibm.ws.cdi.impl.weld.injection.WebSphereInjectionServicesImpl$3.run(WebSphereInjectionServicesImpl.java:320)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at com.ibm.ws.cdi.impl.weld.injection.WebSphereInjectionServicesImpl.aroundInject(WebSphereInjectionServicesImpl.java:320)
	at org.jboss.weld.injection.InjectionContextImpl.run(InjectionContextImpl.java:46)

I have experienced same issue in resteasy, which was fixed here:

https://github.com/resteasy/resteasy-microprofile/pull/9/commits/9e9b1524fbb22dfc2a6794672dcc2455e46e81a4

**Comment by jim-krueger** [comment]
Minor adjustment:  To reproduce this problem I needed to change
-Dhttp.nonProxyHosts=".svc|.cluster.local|localhost|127.0.0.1"
to
-Dhttp.nonProxyHosts=*.svc|.cluster.local|localhost|127.0.0.1

**Comment by Maylann** [comment]
Sorry, that was actually a copy/paste mistake I guess. You are right @jim-krueger, the nonProxyHosts should be with the wildcards: 
-Dhttp.nonProxyHosts=*.svc|*.cluster.local|localhost|127.0.0.1

**Comment by mbroz2** [comment]
@jim-krueger please update the description of this `relesae bug` using the [bug report template](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=&labels=release+bug&template=bug_report.md&title=)

**Comment by jim-krueger** [comment]
**Describe the bug**  
Liberty Microprofile Rest Client support was assuming that http.nonProxyHosts would be in regex format.  So if a nonProxyHost in the list were to include special characters a java.util.regex.PatternSyntaxException similar to the following will occur:

java.util.regex.PatternSyntaxException: Dangling meta character '*' near index 0
*.svc
^
at java.base/java.util.regex.Pattern.error(Pattern.java:2028)
at java.base/java.util.regex.Pattern.sequence(Pattern.java:2203)
at java.base/java.util.regex.Pattern.expr(Pattern.java:2069)
at java.base/java.util.regex.Pattern.compile(Pattern.java:1783)
at java.base/java.util.regex.Pattern.(Pattern.java:1430)
at java.base/java.util.regex.Pattern.compile(Pattern.java:1069)
at org.jboss.resteasy.microprofile.client.ot.LibertyRestClientBuilderImpl.build(LibertyRestClientBuilderImpl.java:325)
at org.jboss.resteasy.microprofile.client.RestClientDelegateBean.create(RestClientDelegateBean.java:129)
at org.jboss.weld.contexts.unbound.DependentContextImpl.get(DependentContextImpl.java:64)
at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get(ContextualInstanceStrategy.java:100)
at org.jboss.weld.bean.ContextualInstance.get(ContextualInstance.java:50)
at org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:694)
at org.jboss.weld.manager.BeanManagerImpl.getInjectableReference(BeanManagerImpl.java:794)
at org.jboss.weld.injection.FieldInjectionPoint.inject(FieldInjectionPoint.java:92)
at org.jboss.weld.util.Beans.injectBoundFields(Beans.java:345)
at org.jboss.weld.util.Beans.injectFieldsAndInitializers(Beans.java:356)
at org.jboss.weld.injection.producer.ResourceInjector$1.proceed(ResourceInjector.java:69)
at com.ibm.ws.cdi.impl.weld.injection.WebSphereInjectionServicesImpl$3.run(WebSphereInjectionServicesImpl.java:323)
at com.ibm.ws.cdi.impl.weld.injection.WebSphereInjectionServicesImpl$3.run(WebSphereInjectionServicesImpl.java:320)
at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
at com.ibm.ws.cdi.impl.weld.injection.WebSphereInjectionServicesImpl.aroundInject(WebSphereInjectionServicesImpl.java:320)
at org.jboss.weld.injection.InjectionContextImpl.run(InjectionContextImpl.java:46)


**Steps to Reproduce**  
Any test using a nonProxyHost containing special characters will reproduce this problem.  For example:
-Dhttp.nonProxyHosts=*.svc|.cluster.local|localhost|127.0.0.1

**Expected behavior**  
The expected behavior is for the nonProxyHosts value to be converted to regex format.

**Diagnostic information:**  
 - Problem occurs in OpenLiberty Version: prior to 22.0.0.4

**Additional context**  
This problem was reported and fixed in CXF code under the following pull request:  https://github.com/resteasy/resteasy-microprofile/pull/9

**Comment by jim-krueger** [comment]
@mbroz2 Thanks for the reminder.
