### ISSUE TITLE
JSP included jar dependency check incorrect 

### ISSUE THREAD

**Issue by epj** [OpenLiberty/open-liberty#20509]
**Describe the bug**  
When a JSP includes another JSP that's contained in a jar under WEB-INF/lib, the out of date dependency checking exhibits two problems depending on the value of  jsp-attribute trackDependencies.  When trackDependencies is true (default) the date check can fail causing the JSP to recompile at each call.  This has the symptom of repeating messages 
SRVE0242I: [ ... ] Initialization successful.
SRVE0253I: [ ... ] Destroy successful.
(Same symptom as issue 18411 but nature of files involved somewhat different.)

When trackDependencies is false, there can be a NullPointerException as follows:
java.lang.NullPointerException
        at com.ibm.ws.jsp.webcontainerext.AbstractJSPExtensionServletWrapper.isDependentOutdated(AbstractJSPExtensionServletWrapper.java:735)
        at com.ibm.ws.jsp.webcontainerext.AbstractJSPExtensionServletWrapper._checkForTranslation(AbstractJSPExtensionServletWrapper.java:416)
        at com.ibm.ws.jsp.webcontainerext.AbstractJSPExtensionServletWrapper.checkForTranslation(AbstractJSPExtensionServletWrapper.java:253)
        at com.ibm.ws.jsp.webcontainerext.AbstractJSPExtensionServletWrapper.handleRequest(AbstractJSPExtensionServletWrapper.java:163)
        at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1227)
        at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1011)
        at com.ibm.ws.webcontainer.servlet.CacheServletWrapper.handleRequest(CacheServletWrapper.java:75)
        at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:938)
        at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:281)
        at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1184)
        at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:453)
        at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:412)
        at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:566)
        at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:500)
        at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:360)
        at com.ibm.ws.http.channel.internal.inbound.HttpICLReadCallback.complete(HttpICLReadCallback.java:70)
        at com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:514)
        at com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueManager.java:584)
        at com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:968)
        at com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:1057)
        at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:245)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
 

**Steps to Reproduce**  
See above

**Expected behavior**  
JSP's should not recompile on each call unless there is a valid update of an included file.  Also no NPE should happen.

**Diagnostic information:**  
 - OpenLiberty Version: issue known to be in 21.0.0.3 and later

**Comment by volosied** [comment]
Investigated this today.

When `trackDependencies` is false, we do not initialize `dependentsList`. 

https://github.com/OpenLiberty/open-liberty/blob/9c0ba6d96d36add7e6031f4cee362c9e76aaf991/dev/com.ibm.ws.jsp/src/com/ibm/ws/jsp/webcontainerext/AbstractJSPExtensionServletWrapper.java#L114-L116


When `isDependentOutdated()` is called, `dependentsList` is null which causes the NPE: 
 https://github.com/OpenLiberty/open-liberty/blob/9c0ba6d96d36add7e6031f4cee362c9e76aaf991/dev/com.ibm.ws.jsp/src/com/ibm/ws/jsp/webcontainerext/AbstractJSPExtensionServletWrapper.java#L731-L733

Solutions
-  Add a isTrackDependencies check to `isDependentOutdated()`

```
        // not track dependencies, dependentsList will be null;
        if (!options.isTrackDependencies()) {
            return outdated;
        }
```
        
-  Always  initialize dependentsList regardless of what is set for trackDependencies


___________
Another Note: if dependantList are greater than > 0 then they are written to the java file (regardless of trackDependencies):

https://github.com/OpenLiberty/open-liberty/blob/2fd4a880754c37a988c5ed9ac4f1ea5988e465d6/dev/com.ibm.ws.jsp/src/com/ibm/ws/jsp/translator/visitor/generator/GeneratorUtils.java#L573-L581

but the dependent files are only loaded when the property is true: 
https://github.com/OpenLiberty/open-liberty/blob/feb090727dc3882ebae9b0aa5f06294904841d06/dev/com.ibm.ws.jsp/src/com/ibm/ws/jsp/webcontainerext/AbstractJSPExtensionServletWrapper.java#L228-L234
