### ISSUE TITLE
EJSHome NullPointerException can occur during server shutdown

### ISSUE THREAD

**Issue by olendvcook** [OpenLiberty/open-liberty#20645]
```
Stack Dump = java.lang.NullPointerException
	at com.ibm.ejs.container.EJSHome.destroy(EJSHome.java:634)
	at com.ibm.ejs.container.EJSContainer.uninstallBean(EJSContainer.java:896)
	at com.ibm.ejs.container.EJSContainer.stopBean(EJSContainer.java:817)
	at com.ibm.ws.ejbcontainer.runtime.AbstractEJBRuntime.stopBean(AbstractEJBRuntime.java:1567)
	at com.ibm.ws.ejbcontainer.osgi.internal.EJBRuntimeImpl.stopBean(EJBRuntimeImpl.java:1162)
	at com.ibm.ws.ejbcontainer.runtime.AbstractEJBRuntime.uninstall(AbstractEJBRuntime.java:715)
	at com.ibm.ws.ejbcontainer.runtime.AbstractEJBRuntime.stopModule(AbstractEJBRuntime.java:662)
	at com.ibm.ws.ejbcontainer.osgi.internal.EJBRuntimeImpl.stop(EJBRuntimeImpl.java:1218)
	at com.ibm.ws.ejbcontainer.osgi.internal.EJBModuleRuntimeContainerImpl.stopModule(EJBModuleRuntimeContainerImpl.java:176)
	at com.ibm.ws.app.manager.module.internal.ModuleHandlerBase.undeployModule(ModuleHandlerBase.java:133)
	at com.ibm.ws.app.manager.module.internal.DeployedModuleInfoImpl.uninstallModule(DeployedModuleInfoImpl.java:64)
	at com.ibm.ws.app.manager.module.internal.SimpleDeployedAppInfoBase.uninstallApp(SimpleDeployedAppInfoBase.java:672)
	at com.ibm.ws.app.manager.ear.internal.EARApplicationHandlerImpl.uninstall(EARApplicationHandlerImpl.java:98)
	at com.ibm.ws.app.manager.internal.statemachine.StopAction.execute(StopAction.java:83)
	at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.enterState(ApplicationStateMachineImpl.java:1382)
	at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.performAction(ApplicationStateMachineImpl.java:1222)
	at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.run(ApplicationStateMachineImpl.java:909)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:866)
```

**Comment by olendvcook** [comment]
this can occur intermittently because the EJBRuntime pulls in PMICollaboratorFactory as a reference component, and then when we are shutting down we unset the reference, and make it null for EJSContainer. Then during module stop we try to use it to remove the pmi module and pmibean for the EJSHome.

So it depends on if the unset happens before the EJSHome.destroy()

**Comment by tkburroughs** [comment]
Fixed
