### ISSUE TITLE
Random request fails due to lookup of user in user registry even though LTPA token is provided 

### ISSUE THREAD

**Issue by simin-xia** [OpenLiberty/open-liberty#20659]
**Describe the bug**  
We are seeing random request failing to a server with 403 due to user authentication error. 
The behaviour is not consistent, and happens to different request when we retry. 

[2022-03-31T10:08:25.072+0000] 0000038f id=00000000 com.ibm.ws.security.authentication.AuthenticationException   > <init> Entry  
                                                                                                               CWIML0515E: The user registry operation could not be completed. The uid=simx@de.ibm.com,cn=users,O=IBM,C=US entity is not in the scope of the defaultWIMFileBasedRealm realm. Specify an entity that is in the scope of the configured realm in the server.xml file.
[2022-03-31T10:08:25.072+0000] 0000038f id=6d70b538 com.ibm.ws.security.authentication.AuthenticationException   < <init> Exit  
                                                                                                               com.ibm.ws.security.authentication.AuthenticationException: CWIML0515E: The user registry operation could not be completed. The uid=simx@de.ibm.com,cn=users,O=IBM,C=US entity is not in the scope of the defaultWIMFileBasedRealm realm. Specify an entity that is in the scope of the configured realm in the server.xml file.
    at com.ibm.ws.security.authentication.internal.AuthenticationServiceImpl.performJAASLogin(AuthenticationServiceImpl.java:556)
    at com.ibm.ws.security.authentication.internal.AuthenticationServiceImpl.authenticate(AuthenticationServiceImpl.java:214)
    at com.ibm.ws.webcontainer.security.internal.SSOAuthenticator.handleLtpaSSO(SSOAuthenticator.java:182)

**Steps to Reproduce**  

Open BAStudio, and observe the browser console log. 

**Expected behavior**  
Request succeed consistently with 200.

**Diagnostic information:**  
[t7998-dev-studio-trace.log.zip](https://github.com/OpenLiberty/open-liberty/files/8390461/t7998-dev-studio-trace.log.zip)

 - OpenLiberty Version: [e.g. 21.0.0.8 - 21.0.0.10]
 - Affected feature(s) [e.g. mpHealth-3.0]
 - Java Version: [i.e. full output of `java -version`]
```
********************************************************************************
product = IBM Business Automation Workflow Server Container 21.0.3, WebSphere Application Server 22.0.0.3 (wlp-1.0.62.cl220320220302-1100)
wlp.install.dir = /opt/ibm/wlp/
server.output.dir = /opt/ibm/wlp/output/defaultServer/
java.home = /opt/ibm/java/jre
java.version = 1.8.0_321
java.runtime = Java(TM) SE Runtime Environment (8.0.7.5 - pxa6480sr7fp5-20220208_01(SR7 FP5))
os = Linux (3.10.0-1160.53.1.el7.x86_64; amd64) (en_US)
```
 - server.xml configuration (WITHOUT sensitive information like passwords)
 - If it would be useful, upload the messages.log file found in `$WLP_OUTPUT_DIR/messages.log`

**Additional context**

**Comment by simin-xia** [comment]
A token comes in, it is understood (decryption works), but for some reason the user is searched in the user repository. This should not be necessary. I see several mentions of "ws.security.authentication.jaas.modules.HashtableLoginModule > getCustomCacheKey Entry  ..."
This should be an indicator to NOT use the local user registry.
The user is not found in the local user registry as BAS is not connected to LDAP, that's OK. The consequence appears to be resetting of the cookie as if logout was triggered.
```
[2022-03-31T10:08:25.074+0000] 0000038f id=dfd36c9b com.ibm.ws.webcontainer.security.SSOCookieHelperImpl         > createLogoutCookies Entry  
```
```
