### ISSUE TITLE
CWWKS4106E: LTPA CONFIGURATION ERROR IN LIBERTY when using PKCS11Impl provider

### ISSUE THREAD

**Issue by una-tapa** [OpenLiberty/open-liberty#2068]
When PKCS11Impl is configured in java.security,  Liberty fails to use LTPA key.   The code needs to use JCE provider even when PKCSImpl is configured higher priority in java.security file. 

Sample error output 
--------------
CWWKS4106E: LTPA configuration error. Unable to create or read
LTPA key file: /opt/libety17002/wlp/usr/servers/server1/resources/security/ltpa.keys

FFDC starts with

------Start of DE processing------ = [10/20/17 9:27:33:950 EDT]
Exception = java.security.InvalidKeyException
Source = com.ibm.ws.security.token.ltpa.internal.LTPAKeyCreateTask
probeid = 114
Stack Dump = java.security.InvalidKeyException: Wrong format:
RAW bytes needed
at com.ibm.crypto.provider.aW.a(Unknown Source)
at com.ibm.crypto.provider.aW.init(Unknown Source)
at com.ibm.crypto.provider.AbstractBufferingCipher.engineInit (Unknown Source)
at javax.crypto.Cipher.a(Unknown Source)
at javax.crypto.Cipher.a(Unknown Source)
at javax.crypto.Cipher.init(Unknown Source)
at javax.crypto.Cipher.init(Unknown Source)
at com.ibm.ws.crypto.ltpakeyutil.LTPACrypto.createCipher(LTPACrypto.java:595)

**Comment by ewhoch** [comment]
Reopening this to track the new fix introduction since this will now no longer be resolved in the stream.

**Comment by ewhoch** [comment]
This is still failing quite severely on MacOS. This delivery may just need to be pushed out to next release given that it's been attempted a couple times.

**Comment by una-tapa** [comment]
#2995 merged.
