### ISSUE TITLE
springboot application packaged with OL 22.0.0.3 failed to run

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/open-liberty#20693]
**Describe the bug**  
Packaged springboot application with OL 22.0.0.3 into a jar file. When run it, got following exception.

```
                   : Started Application in 2.764 seconds (JVM running for 6.19)
2022-04-01 16:51:29.686  INFO 64794 --- [ecutor-thread-9] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2022-04-01 16:51:29.726 ERROR 64794 --- [ecutor-thread-9] o.s.boot.SpringApplication               : Application run failed

javax.management.JMRuntimeException: Failed to load MBeanServerBuilder class com.ibm.ws.kernel.boot.jmx.internal.PlatformMBeanServerBuilder: java.lang.ClassNotFoundException: com.ibm.ws.kernel.boot.jmx.internal.PlatformMBeanServerBuilder
	at java.management/javax.management.MBeanServerFactory.checkMBeanServerBuilder(MBeanServerFactory.java:502) ~[na:na]
	at java.management/javax.management.MBeanServerFactory.getNewMBeanServerBuilder(MBeanServerFactory.java:535) ~[na:na]
	at java.management/javax.management.MBeanServerFactory.newMBeanServer(MB
```
**Steps to Reproduce**  
- `git clone https://github.com/openliberty/guide-spring-boot.git -b gkwan-ibm-latest-ol`
- `cd guide-spring-boot/finish`
- `./mvnw package`
- `java -jar target/GSSpringBootApp.jar`
- get the above exception and cannot run `http://localhost:9080/hello` URL

**Expected behavior**  
- no exception and can run `http://localhost:9080/hello` URL

**Diagnostic information:**  
 - OpenLiberty Version: [22.0.0.3]
 - Affected feature(s) [maybe springBoot-2.0 or server package]
 - Java Version: [i.e. full output of `java -version`]
 ```
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T11:41:47-05:00)
Maven home: /Users/gkwan/.m2/wrapper/dists/apache-maven-3.3.9-bin/2609u9g41na2l7ogackmif6fj2/apache-maven-3.3.9
Java version: 11.0.12, vendor: International Business Machines Corporation
Java home: /Users/gkwan/tasks/softwares/semeru-jdk-11.0.12+7/Contents/Home
Default locale: en_CA, platform encoding: UTF-8
OS name: "mac os x", version: "12.2.1", arch: "x86_64", family: "mac"
```
 - server.xml configuration (WITHOUT sensitive information like passwords)
   - https://github.com/OpenLiberty/guide-spring-boot/blob/gkwan-ibm-latest-ol/finish/src/main/liberty/config/server.xml

**Comment by gkwan-ibm** [comment]
full console output: [springboot.console.txt](https://github.com/OpenLiberty/open-liberty/files/8400897/springboot.console.txt)

**Comment by gkwan-ibm** [comment]
OL 22.0.0.2 have no problem.

Run `git clone https://github.com/openliberty/guide-spring-boot.git` instead. The default branch is hard-coded to use OL 22.0.0.2 because of this issue.

**Comment by jhanders34** [comment]
#regression

**Comment by tjwatson** [comment]
This is caused by the changes to #19336

Changes in that PR use the new Equinox method `org.eclipse.osgi.internal.loader.BundleLoader.findClassNoParentNoException(String)` to delegate to the gateway bundle class loader.  This method (as the name implies) does not delegate to the parent class loader of the bundle loader.  Before we did normal delegation to the gateway bundle class loader which would check the bundle parent class loader for packages that are configured for bootdelegation.  The package `com.ibm.ws.kernel.boot.jmx.internal` happens to be a package that gets configured for bootdelegation (see `com.ibm.ws.kernel.launch.internal.FrameworkConfigurator.extraBootDelegationPackages(BootstrapConfig)` method.  This would cause any class loads for the gateway bundle class loader in the `com.ibm.ws.kernel.boot.jmx.internal` package to end up delegating to the bundle class loader parent.  For Liberty that ends up being `com.ibm.ws.kernel.internal.classloader.BootstrapChildFirstJarClassloader`.  This class loader has the content of `com.ibm.ws.kernel.boot.jmx.internal` available.

But now the delegation to the bundle classloader from the `com.ibm.ws.classloading.internal.GatewayClassLoader` class does not do this boot delegation.  After not finding the class with the bundle class loader we eventually end up calling `java.lang.ClassLoader.findSystemClass(String)`.  For "normal" server launches this ends up finding the class because the `kernel.boot` JAR is on the system class path.  But for the executable JAR with the packaged server this JAR is not on the system classpath.  That is why it does not work in the executable JAR case.

**Comment by tjwatson** [comment]
A workaround is to force a 2 JVM launch so that we get the same system classpath as the normal `server start|run` case.  One way to do that is to define a `jvm.options` file under `src/main/liberty/config/jvm.options`.   The contents can be something simple like setting a system property that is not used:

```
-Dtest2JVM=true
```

**Comment by yooman00** [comment]
@tjwatson Similar problem still occur using 25.0.0.7, #m not using springboot.
Caused by: java.lang.ClassNotFoundException: com.ibm.ws.kernel.boot.security.SSLSocketFactoryProxy

 Is there any other workarround? Stoping the server leave the first JVM open.

**Comment by tjwatson** [comment]
> [@tjwatson](https://github.com/tjwatson) Similar problem still occur using 25.0.0.7, #m not using springboot. Caused by: java.lang.ClassNotFoundException: com.ibm.ws.kernel.boot.security.SSLSocketFactoryProxy
> 
> Is there any other workarround? Stoping the server leave the first JVM open.

Can you give the full stacktrace of the error?

**Comment by yooman00** [comment]
> > [@tjwatson](https://github.com/tjwatson) Similar problem still occur using 25.0.0.7, #m not using springboot. Caused by: java.lang.ClassNotFoundException: com.ibm.ws.kernel.boot.security.SSLSocketFactoryProxy
> > Is there any other workarround? Stoping the server leave the first JVM open.
> 
> Can you give the full stacktrace of the error?

SSL is well configured. starting the server with the workarround work well, except from the 2 JVM.

The Problem seems to occur on all features who try to use Connection and access the ssl configuration. Here two examples, one form a Datasource and Httpconnection
-------------------------
Caused by: java.sql.SQLNonTransientException: [jcc][t4][2043][11550][4.32.47] Ausnahmebedingung java.net.SocketException: Fehler beim Öffnen des Sockets zu Server myServer an Port 1234 mit Nachricht: java.lang.ClassNotFoundException: com.ibm.ws.kernel.boot.security.SSLSocketFactoryProxy. ERRORCODE=-4499, SQLSTATE=08001 DSRA0010E: SQL-Status = 08001, Fehlercode = -4.499
	at com.ibm.db2.jcc.am.b7.a(b7.java:338)
	at com.ibm.db2.jcc.am.b7.a(b7.java:435)
	at com.ibm.db2.jcc.t4.a0.a(a0.java:462)
	at com.ibm.db2.jcc.t4.a0.<init>(a0.java:97)
	at com.ibm.db2.jcc.t4.a.b(a.java:374)
	at com.ibm.db2.jcc.t4.b.newAgent_(b.java:2297)
	at com.ibm.db2.jcc.am.Connection.initConnection(Connection.java:862)
	at com.ibm.db2.jcc.am.Connection.<init>(Connection.java:807)
	at com.ibm.db2.jcc.t4.b.<init>(b.java:366)
	at com.ibm.db2.jcc.DB2DataSource.getSimpleConnection(DB2DataSource.java:139)
	at com.ibm.db2.jcc.DB2DataSource.getConnection(DB2DataSource.java:116)
	at com.ibm.db2.jcc.DB2DataSource.getConnection(DB2DataSource.java:91)
	at com.ibm.ws.rsadapter.impl.DatabaseHelper.getConnectionFromDatasource(DatabaseHelper.java:1467)
	at com.ibm.ws.rsadapter.impl.DB2JCCHelper.getConnectionFromDatasource(DB2JCCHelper.java:638)
	at com.ibm.ws.rsadapter.impl.WSManagedConnectionFactoryImpl$7.run(WSManagedConnectionFactoryImpl.java:1032)
	at com.ibm.ws.rsadapter.impl.WSManagedConnectionFactoryImpl$7.run(WSManagedConnectionFactoryImpl.java:1019)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:714)
	at java.base/java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:618)
	at com.ibm.ws.rsadapter.impl.WSManagedConnectionFactoryImpl.getConnectionUsingDS(WSManagedConnectionFactoryImpl.java:1019)
	at com.ibm.ws.rsadapter.impl.WSManagedConnectionFactoryImpl.getConnection(WSManagedConnectionFactoryImpl.java:848)
	at com.ibm.ws.rsadapter.impl.WSManagedConnectionFactoryImpl.createManagedConnection(WSManagedConnectionFactoryImpl.java:698)
	at com.ibm.ejs.j2c.FreePool.createManagedConnectionWithMCWrapper(FreePool.java:1389)
	at com.ibm.ejs.j2c.FreePool.createOrWaitForConnection(FreePool.java:1263)
	at com.ibm.ejs.j2c.PoolManager.reserve(PoolManager.java:1471)
	at com.ibm.ejs.j2c.ConnectionManager.allocateMCWrapper(ConnectionManager.java:576)
	at com.ibm.ejs.j2c.ConnectionManager.allocateConnection(ConnectionManager.java:308)
	at com.ibm.ws.rsadapter.jdbc.WSJdbcDataSource.getConnection(WSJdbcDataSource.java:143)
	at com.ibm.ws.rsadapter.jdbc.WSJdbcDataSource.getConnection(WSJdbcDataSource.java:117)
	at org.eclipse.persistence.sessions.JNDIConnector.connect(JNDIConnector.java:140)
	... 63 more
Caused by: java.net.SocketException: java.lang.ClassNotFoundException: com.ibm.ws.kernel.boot.security.SSLSocketFactoryProxy
	at java.base/javax.net.ssl.DefaultSSLSocketFactory.throwException(SSLSocketFactory.java:263)
	at java.base/javax.net.ssl.DefaultSSLSocketFactory.createSocket(SSLSocketFactory.java:270)
	at com.ibm.db2.jcc.t4.w.run(w.java:119)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:571)
	at com.ibm.db2.jcc.t4.a0.a(a0.java:435)
	... 89 more
Caused by: java.lang.ClassNotFoundException: com.ibm.ws.kernel.boot.security.SSLSocketFactoryProxy
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at java.base/javax.net.ssl.SSLSocketFactory$DefaultFactoryHolder.<clinit>(SSLSocketFactory.java:226)
	at java.base/javax.net.ssl.SSLSocketFactory.getDefault(SSLSocketFactory.java:78)
	at com.ibm.db2.jcc.t4.w.run(w.java:118)
	... 91 more

----------------------
...
Caused by: java.net.SocketException: java.lang.ClassNotFoundException: com.ibm.ws.kernel.boot.security.SSLSocketFactoryProxy
	at java.base/javax.net.ssl.DefaultSSLSocketFactory.throwException(SSLSocketFactory.java:263)
	at java.base/javax.net.ssl.DefaultSSLSocketFactory.createSocket(SSLSocketFactory.java:270)
	at java.base/sun.net.www.protocol.https.HttpsClient.createSocket(HttpsClient.java:419)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:163)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:531)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:636)
	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:377)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:193)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1237)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1123)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:179)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:141)
	at com.filenet.apiimpl.wsi.ServiceSessionNst$1.run(ServiceSessionNst.java:604)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:571)
	at com.filenet.apiimpl.wsi.ServiceSessionNst.cDoPrivilegedHttpConnectAndGetOutputStream(ServiceSessionNst.java:613)
	at com.filenet.apiimpl.wsi.ServiceSessionNst.cInitHttpConnection(ServiceSessionNst.java:574)
	at com.filenet.apiimpl.wsi.ServiceSessionNst.cOpenMultipartOutputStream(ServiceSessionNst.java:486)
	... 59 more
Caused by: java.lang.ClassNotFoundException: com.ibm.ws.kernel.boot.security.SSLSocketFactoryProxy
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at java.base/javax.net.ssl.SSLSocketFactory$DefaultFactoryHolder.<clinit>(SSLSocketFactory.java:226)
	at java.base/javax.net.ssl.SSLSocketFactory.getDefault(SSLSocketFactory.java:78)
	at java.base/javax.net.ssl.HttpsURLConnection.getDefaultSSLSocketFactory(HttpsURLConnection.java:336)
	at java.base/javax.net.ssl.HttpsURLConnection.<init>(HttpsURLConnection.java:292)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.<init>(HttpsURLConnectionImpl.java:80)
	at java.base/sun.net.www.protocol.https.Handler.openConnection(Handler.java:62)
	at java.base/sun.net.www.protocol.https.Handler.openConnection(Handler.java:57)
	at java.base/java.net.URL.openConnection(URL.java:1258)
	at com.filenet.apiimpl.wsi.ServiceSessionNst.cOpenHttpConnection(ServiceSessionNst.java:628)
	at com.filenet.apiimpl.wsi.ServiceSessionNst.cReqRespPath(ServiceSessionNst.java:300)
	... 58 more

**Comment by tjwatson** [comment]
This appears to be a separate issue from this original issue.  Please open a separate issue and provides steps to reproduce.
