### ISSUE TITLE
WAR module can't load class from JAR that lives in same EAR

### ISSUE THREAD

**Issue by mthmulders** [OpenLiberty/open-liberty#20718]
**Describe the bug**  
I have a project that packages as an EAR. The EAR contains a WAR and some JARs. Classes inside the WAR reference classes from the JARs. The project is on Java 11, and uses the Java Module System. 

The stack trace looks like this:

```
[4/5/22, 22:03:19:330 CEST] 00000027 org.jboss.resteasy.resteasy_jaxrs.i18n                       I RESTEASY002225: Deploying jakarta.ws.rs.core.Application: class web.SampleApplication$Proxy$_$$_WeldClientProxy
[4/5/22, 22:03:19:475 CEST] 00000027 com.ibm.ws.logging.internal.impl.IncidentImpl                I FFDC1015I: An FFDC Incident has been created: "java.lang.NoClassDefFoundError: domain/SampleRepository com.ibm.ws.webcontainer.servlet.ServletWrapper.init 181" at ffdc_22.04.05_22.03.19.0.log
[4/5/22, 22:03:19:475 CEST] 00000027 com.ibm.ws.webcontainer.servlet                              E SRVE0271E: Uncaught init() exception created by servlet [web.SampleApplication] in application [ear]: java.lang.NoClassDefFoundError: domain/SampleRepository
	at java.base/java.lang.Class.getDeclaredFields0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredFields(Class.java:3297)
	at java.base/java.lang.Class.getDeclaredFields(Class.java:2371)
	at org.jboss.resteasy.spi.metadata.ResourceBuilder.processDeclaredFields(ResourceBuilder.java:1125)
	at org.jboss.resteasy.spi.metadata.ResourceBuilder.processFields(ResourceBuilder.java:1100)
	at org.jboss.resteasy.spi.metadata.ResourceBuilder.fromAnnotations(ResourceBuilder.java:939)
	at org.jboss.resteasy.spi.metadata.ResourceBuilder.getRootResourceFromAnnotations(ResourceBuilder.java:901)
	at org.jboss.resteasy.plugins.server.resourcefactory.POJOResourceFactory.<init>(POJOResourceFactory.java:41)
	at org.jboss.resteasy.core.ResourceMethodRegistry.addPerRequestResource(ResourceMethodRegistry.java:87)
	at org.jboss.resteasy.core.ResteasyDeploymentImpl.registerResources(ResteasyDeploymentImpl.java:518)
	at org.jboss.resteasy.core.ResteasyDeploymentImpl.registration(ResteasyDeploymentImpl.java:475)
	at org.jboss.resteasy.core.ResteasyDeploymentImpl.startInternal(ResteasyDeploymentImpl.java:164)
	at org.jboss.resteasy.core.ResteasyDeploymentImpl.start(ResteasyDeploymentImpl.java:121)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.init(ServletContainerDispatcher.java:140)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.init(HttpServletDispatcher.java:42)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.init(ServletWrapper.java:299)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.loadOnStartupCheck(ServletWrapper.java:1401)
	at com.ibm.ws.webcontainer.webapp.WebApp.doLoadOnStartupActions(WebApp.java:1201)
	at com.ibm.ws.webcontainer.webapp.WebApp.commonInitializationFinally(WebApp.java:1169)
	at com.ibm.ws.webcontainer.webapp.WebApp.initialize(WebApp.java:1067)
	at com.ibm.ws.webcontainer.webapp.WebApp.initialize(WebApp.java:6675)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost.startWebApp(DynamicVirtualHost.java:472)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost.startWebApplication(DynamicVirtualHost.java:467)
	at com.ibm.ws.webcontainer.osgi.WebContainer.startWebApplication(WebContainer.java:1187)
	at com.ibm.ws.webcontainer.osgi.WebContainer.access$100(WebContainer.java:111)
	at com.ibm.ws.webcontainer.osgi.WebContainer$3.run(WebContainer.java:984)
	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:245)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassNotFoundException: domain.SampleRepository
	at com.ibm.ws.classloading.internal.AppClassLoader.findClassCommonLibraryClassLoaders(AppClassLoader.java:748)
	at com.ibm.ws.classloading.internal.AppClassLoader.findClass(AppClassLoader.java:319)
	at com.ibm.ws.classloading.internal.AppClassLoader.findOrDelegateLoadClass(AppClassLoader.java:720)
	at com.ibm.ws.classloading.internal.AppClassLoader.loadClass(AppClassLoader.java:592)
	at com.ibm.ws.classloading.internal.AppClassLoader.loadClass(AppClassLoader.java:559)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 32 more
```

**Steps to Reproduce**  
Build the [attached project (ol-ear-classloading.zip)](https://github.com/OpenLiberty/open-liberty/files/8421529/ol-ear-classloading.zip), and run `mvn liberty:dev` in the **ear** module.

**Expected behavior**  
The application loads without problems.

**Diagnostic information:**  
 - OpenLiberty Version: **22.0.03**
 - Affected feature(s) **jakartaee-9.1**
 - Java Version: **openjdk version "17.0.2" 2022-01-18**
**OpenJDK Runtime Environment Homebrew (build 17.0.2+0)**
**OpenJDK 64-Bit Server VM Homebrew (build 17.0.2+0, mixed mode, sharing)**
 - server.xml configuration (WITHOUT sensitive information like passwords)
 - If it would be useful, upload the messages.log file found in `$WLP_OUTPUT_DIR/messages.log`

I didn't modify **server.xml**, it's the default one generated by the Liberty Maven Plugin.
.

**Comment by dazavala** [comment]
Hello.  The server does not support java modules within Enterprise application archives. There are few options to make a dependency/library jar visible to a Web module at runtime.  I assume the artifactId of your library jar is "domain" in the options below.  

1. Package the domain jar in the `lib` directory of the EAR archive
2. Package the domain jar in the `WEB-INF/lib` directory of the WAR archive
3. Declare the domain jar as a dependency jar of either the Enterprise App or the Web module.  In this assembly you should see the domain jar package within the EAR (WAR), and within file `<EAR>(<WAR>)#/META-INF/MANIFEST.MF` you should see the `Class-Path` attribute set to the relative path to the domain jar within the EAR (WAR).  

The pom for the web module declares a dependency on the domain jar, but the dependency also declares `<scope>provided</scope>`.  That will prevent maven from packaging the domain jar into the WAR.  You'll want to change that, but I suspect you may not get the desired result with that change alone.

IMHO the simplest approach is option 1.  To do so, add element `<defaultLibBundleDir>lib</defaultLibBundleDir>` to the the maven-ear-plugin configuration within file `ol-ear-classloading.zip#pom.xml`, and keep the domain jar dependency within the same pom file, ensuring the dependency `<scope>` enables maven to package the jar into the EAR.   

```
<groupId>org.apache.maven.plugins</groupId>
   <artifactId>maven-ear-plugin</artifactId>
      <configuration>
         ...
        <defaultLibBundleDir>lib</defaultLibBundleDir>
        ...
```

If you are using a JavaEE development environment w/ maven support, you should be able to perform any of the three suggested options.  -Regards.

**Comment by mthmulders** [comment]
Thanks for the fast and extensive response!

Option 1 seems the simplest _and_ the cleanest to me. Ideally, the WAR would not contain the domain, and option 1 fits in that approach.

I've updated the configuration of the EAR plugin in two ways:
1. Add the `<defaultLibBundleDir>lib</defaultLibBundleDir>` element
2. Configure the **META-INF/MANIFEST.MF** to list the classpath of the WAR, as below

```xml
<archive>
    <manifest>
        <addClasspath>true</addClasspath>
    </manifest>
</archive>
```

Now the _domain_ and the _infrastructure_ JAR files appear in the correct place in the EAR. And after adding `@ApplicationScoped` on the `JpaSampleRepository`, Liberty happily discovers that class as the implementation of the `SampleRepository` interface from my domain.

Thanks a lot for enlightening me in this topic!

**Comment by dazavala** [comment]
@mthmulders Glad to help and good luck with your project!
