### ISSUE TITLE
Liberty can hang while trying to start

### ISSUE THREAD

**Issue by turkeylurkey** [OpenLiberty/open-liberty#20749]
Hello, when I start Liberty it can hang. This situation arises using dev mode in the Liberty Maven Plugin so it is not easily reduced to a separate test case. It is repeatable though.

**Steps to Reproduce** 
The use case is as follows. In dev mode the server is running when I add a Java file to the app src and it does not compile due to a missing jar. Next I add the jar to the build file (pom.xml) and compile the Java, three features are added to configDropins/overrides/generated-features.xml (servlet-4.0, cdi-2.0 and mpHealth-2.0), features are installed to Liberty from Maven and the app is updated.

At this point the server is fine and the app runs. However, if I stop Liberty and then try to start it again (using "server debug defaultServer") it hangs.  If I try to start the server outside dev mode then the console displays:

```
$ wlp/bin/server debug defaultServer

Listening for transport dt_socket at address: 7777
Launching defaultServer (Open Liberty 21.0.0.9/wlp-1.0.56.cl210920210824-2341) on Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_231-b11 24_Oct_2019_15_52 Mac OS X x64(SR6) (en_CA)
[AUDIT   ] CWWKE0001I: The server defaultServer has been launched.
[AUDIT   ] CWWKG0028A: Processing included configuration resource: /Users/paulg/WAS/devExperience/featureGeneration/tmp/basic-dev-project/target/liberty/wlp/usr/servers/defaultServer/extraFeatures.xml
[AUDIT   ] CWWKG0093A: Processing configuration drop-ins resource: /Users/paulg/WAS/devExperience/featureGeneration/tmp/basic-dev-project/target/liberty/wlp/usr/servers/defaultServer/configDropins/overrides/generated-features.xml
```
and it hangs. I have waited up to 120s for something to happen. If I hit control-C execution continues:
```
^C[AUDIT   ] CWWKF0012I: The server installed the following features: [cdi-2.0, jaxrs-2.1, jaxrsClient-2.1, jndi-1.0, json-1.0, jsonp-1.1, mpHealth-2.0, servlet-4.0].
[AUDIT   ] CWWKE0085I: The server defaultServer is stopping because the JVM is exiting.
[AUDIT   ] CWWKE1100I: Waiting for up to 30 seconds for the server to quiesce.
[AUDIT   ] CWWKF0011I: The defaultServer server is ready to run a smarter planet. The defaultServer server started in 40.722 seconds.
[AUDIT   ] CWWKE0036I: The server defaultServer stopped after 45.819 seconds.
```
In theory you could do the same on your machine but if you'd like I could run it again with a trace string and send you the logs or other information you require. 

**Expected behavior** 
Normally when the server is running I would expect to be able to stop it and start it again and have it running like it was before I stopped it. 

**Diagnostic information:**  
 - OpenLiberty Version: 21.0.0.9. Also reproduced on 22.0.0.3.
 - Affected feature(s) Happens when adding mpHealth-2.0 or mpHealth-3.1
 - Java Version: 
java version "1.8.0_231"
Java(TM) 2 Runtime Environment, Standard Edition (IBM build 1.8.0_231-b11 24_Oct_2019_15_52 Mac OS X x64(SR6))
Java HotSpot(TM) 64-Bit Server VM (build 25.231-b11, mixed mode)
IBM Java ORB build orb80-20190708.00
XML build XL TXE Java 1.0.62
XML build IBM JAXP 1.6.1
XML build XML4J 4.5.31
 - server.xml configuration (WITHOUT sensitive information like passwords)
 ```
<?xml version="1.0" encoding="UTF-8"?>
<server description="Sample Liberty server">

  <!--The Liberty Maven Plugin has generated Liberty features necessary for your application in configDropins/overrides/generated-features.xml-->

  <featureManager>
    <feature>jaxrs-2.1</feature>
  </featureManager>

  <httpEndpoint host="*" httpPort="${default.http.port}" httpsPort="${default.https.port}" id="defaultHttpEndpoint"/>

  <include location="extraFeatures.xml"/>
</server>
```
```
<?xml version="1.0" encoding="UTF-8"?>
<server description="extra server features">
	<featureManager>
        <!-- replace -->
    </featureManager>
</server>
```
```
<?xml version="1.0" encoding="UTF-8"?>
<server>
    <!--This file was generated by the Liberty Maven Plugin and will be overwritten on subsequent runs of the liberty:generate-features goal.
 It is recommended that you do not edit this file and that you commit this file to your version control.-->
    <featureManager>
        <!--The following features were generated based on API usage detected in your application-->
        <feature>servlet-4.0</feature>
        <feature>cdi-2.0</feature>
        <feature>mpHealth-2.0</feature>
    </featureManager>
</server>
```
 - If it would be useful, upload the messages.log file found in `$WLP_OUTPUT_DIR/messages.log`

**Additional context**  
FFDC:
```
Exception = java.lang.IllegalStateException
Source = com.ibm.ws.kernel.feature.internal.FeatureManager
probeid = 874
Stack Dump = java.lang.IllegalStateException: Framework/VM shutting down
	at com.ibm.ws.kernel.feature.internal.FeatureManager.checkBundleStatus(FeatureManager.java:2335)
	at com.ibm.ws.kernel.feature.internal.FeatureManager.update(FeatureManager.java:768)
	at com.ibm.ws.kernel.feature.internal.FeatureManager.processFeatureChanges(FeatureManager.java:870)
	at com.ibm.ws.kernel.feature.internal.FeatureManager$1.run(FeatureManager.java:656)
	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:238)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

dev mode log showing some ci.ant config activities like `liberty:create`, `liberty:install-feature`, `liberty:deploy` and Invoke command.
```
r
[INFO] Restarting server...
[INFO] CWWKM2001I: Invoke command is [/Users/paulg/WAS/devExperience/featureGeneration/tmp/basic-dev-project/target/liberty/wlp/bin/server, stop, defaultServer].
[INFO] 
[INFO] Stopping server defaultServer.
[INFO] [AUDIT   ] CWWKE0055I: Server shutdown requested on Thursday, April 7, 2022 at 6:56 PM. The server defaultServer is shutting down.
[INFO] [AUDIT   ] CWWKE1100I: Waiting for up to 30 seconds for the server to quiesce.
[INFO] [AUDIT   ] CWWKT0017I: Web application removed (default_host): http://192.168.0.209:9080/health/
[INFO] [AUDIT   ] CWWKT0017I: Web application removed (default_host): http://192.168.0.209:9080/dev-sample-proj-1.0-SNAPSHOT/
[INFO] [AUDIT   ] CWWKZ0009I: The application dev-sample-proj-1.0-SNAPSHOT has stopped successfully.
[INFO] [AUDIT   ] CWWKE0036I: The server defaultServer stopped after 1 minutes, 47.314 seconds.
[INFO] Server defaultServer stopped.
[INFO] Running liberty:create
[INFO] CWWKM2102I: Using artifact based assembly archive : io.openliberty:openliberty-kernel:null:22.0.0.3:zip.
[INFO] CWWKM2102I: Using installDirectory : /Users/paulg/WAS/devExperience/featureGeneration/tmp/basic-dev-project/target/liberty/wlp.
[INFO] CWWKM2102I: Using serverName : defaultServer.
[INFO] CWWKM2102I: Using serverDirectory : /Users/paulg/WAS/devExperience/featureGeneration/tmp/basic-dev-project/target/liberty/wlp/usr/servers/defaultServer.
[INFO] CWWKM2185I: The liberty-maven-plugin configuration parameter "appsDirectory" value defaults to "dropins".
[INFO] CWWKM2112I: Re-using previously installed assembly.
[INFO] Copying 3 files to /Users/paulg/WAS/devExperience/featureGeneration/tmp/basic-dev-project/target/liberty/wlp/usr/servers/defaultServer
[INFO] CWWKM2144I: Update server configuration file server.xml from /Users/paulg/WAS/devExperience/featureGeneration/tmp/basic-dev-project/src/main/liberty/config/server.xml.
[INFO] CWWKM2144I: Update server configuration file bootstrap.properties from inlined configuration.
[INFO] Running liberty:install-feature
[INFO] CWWKM2102I: Using artifact based assembly archive : io.openliberty:openliberty-kernel:null:22.0.0.3:zip.
[INFO] CWWKM2102I: Using installDirectory : /Users/paulg/WAS/devExperience/featureGeneration/tmp/basic-dev-project/target/liberty/wlp.
[INFO] CWWKM2102I: Using serverName : defaultServer.
[INFO] CWWKM2102I: Using serverDirectory : /Users/paulg/WAS/devExperience/featureGeneration/tmp/basic-dev-project/target/liberty/wlp/usr/servers/defaultServer.
[INFO] Parsing the server file /Users/paulg/WAS/devExperience/featureGeneration/tmp/basic-dev-project/target/liberty/wlp/usr/servers/defaultServer/server.xml for features and includes.
[INFO] Parsing the server file /Users/paulg/WAS/devExperience/featureGeneration/tmp/basic-dev-project/target/liberty/wlp/usr/servers/defaultServer/extraFeatures.xml for features and includes.
[INFO] Parsing the server file /Users/paulg/WAS/devExperience/featureGeneration/tmp/basic-dev-project/target/liberty/wlp/usr/servers/defaultServer/configDropins/overrides/generated-features.xml for features and includes.
[INFO] Installing features: [servlet-4.0, cdi-2.0, mphealth-2.0, jaxrs-2.1]

[INFO] The features are already installed, so no action is needed.
[INFO] Running liberty:deploy
[INFO] CWWKM2102I: Using artifact based assembly archive : io.openliberty:openliberty-kernel:null:22.0.0.3:zip.
[INFO] CWWKM2102I: Using installDirectory : /Users/paulg/WAS/devExperience/featureGeneration/tmp/basic-dev-project/target/liberty/wlp.
[INFO] CWWKM2102I: Using serverName : defaultServer.
[INFO] CWWKM2102I: Using serverDirectory : /Users/paulg/WAS/devExperience/featureGeneration/tmp/basic-dev-project/target/liberty/wlp/usr/servers/defaultServer.
[INFO] Copying 3 files to /Users/paulg/WAS/devExperience/featureGeneration/tmp/basic-dev-project/target/liberty/wlp/usr/servers/defaultServer
[INFO] CWWKM2144I: Update server configuration file server.xml from /Users/paulg/WAS/devExperience/featureGeneration/tmp/basic-dev-project/src/main/liberty/config/server.xml.
[INFO] CWWKM2144I: Update server configuration file bootstrap.properties from inlined configuration.
[INFO] CWWKM2185I: The liberty-maven-plugin configuration parameter "appsDirectory" value defaults to "dropins".
[INFO] CWWKM2160I: Installing application dev-sample-proj-1.0-SNAPSHOT.war.xml.
[INFO] CWWKM2001I: Invoke command is [/Users/paulg/WAS/devExperience/featureGeneration/tmp/basic-dev-project/target/liberty/wlp/bin/server, debug, defaultServer].
[INFO] 
[INFO] Listening for transport dt_socket at address: 7777
[INFO] Launching defaultServer (Open Liberty 22.0.0.3/wlp-1.0.62.cl220320220302-1100) on Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_231-b11 24_Oct_2019_15_52 Mac OS X x64(SR6) (en_CA)
[INFO] [AUDIT   ] CWWKE0001I: The server defaultServer has been launched.
[INFO] [AUDIT   ] CWWKG0028A: Processing included configuration resource: /Users/paulg/WAS/devExperience/featureGeneration/tmp/basic-dev-project/target/liberty/wlp/usr/servers/defaultServer/extraFeatures.xml
[INFO] [AUDIT   ] CWWKG0093A: Processing configuration drop-ins resource: /Users/paulg/WAS/devExperience/featureGeneration/tmp/basic-dev-project/target/liberty/wlp/usr/servers/defaultServer/configDropins/overrides/generated-features.xml
[INFO] CWWKM2010I: Searching for CWWKF0011I: in /Users/paulg/WAS/devExperience/featureGeneration/tmp/basic-dev-project/target/liberty/wlp/usr/servers/defaultServer/logs/messages.log. This search will timeout after 120 seconds.
[INFO] [ERROR   ] CWWKG0059E: The persisted identity com.ibm.ws.app.manager.webappcfg could not be processed because it extends an unavailable persisted identity com.ibm.ws.app.manager.
[INFO] [ERROR   ] CWWKG0059E: The persisted identity com.ibm.ws.app.manager.earappcfg could not be processed because it extends an unavailable persisted identity com.ibm.ws.app.manager.
[INFO] CWWKM2011E: Timed out searching for CWWKF0011I: in /Users/paulg/WAS/devExperience/featureGeneration/tmp/basic-dev-project/target/liberty/wlp/usr/servers/defaultServer/logs/messages.log.
[INFO] CWWKM2001I: Invoke command is [/Users/paulg/WAS/devExperience/featureGeneration/tmp/basic-dev-project/target/liberty/wlp/bin/server, stop, defaultServer].
[INFO] 
[INFO] Stopping server defaultServer.
[INFO] [AUDIT   ] CWWKE0055I: Server shutdown requested on Thursday, April 7, 2022 at 6:59 PM. The server defaultServer is shutting down.
[INFO] [AUDIT   ] CWWKE1100I: Waiting for up to 30 seconds for the server to quiesce.
[INFO] [AUDIT   ] CWWKF0012I: The server installed the following features: [cdi-2.0, jaxrs-2.1, jaxrsClient-2.1, jndi-1.0, json-1.0, jsonp-1.1, mpHealth-2.0, servlet-4.0].
[INFO] [AUDIT   ] CWWKF0011I: The defaultServer server is ready to run a smarter planet. The defaultServer server started in 122.689 seconds.
[INFO] [AUDIT   ] CWWKE0036I: The server defaultServer stopped after 2 minutes, 7.801 seconds.
[INFO] Server defaultServer stopped.
[ERROR] Could not restart the server.
io.openliberty.tools.common.plugins.util.PluginExecutionException: The server has not started within 120 seconds. Consider increasing the server start timeout if this continues to occur. For example, 'mvn liberty:dev -DserverStartTimeout=120'
    at io.openliberty.tools.common.plugins.util.DevUtil.startServer (DevUtil.java:878)
    at io.openliberty.tools.common.plugins.util.DevUtil.restartServer (DevUtil.java:1815)
    at io.openliberty.tools.common.plugins.util.DevUtil$HotkeyReader.readInput (DevUtil.java:2545)
    at io.openliberty.tools.common.plugins.util.DevUtil$HotkeyReader.run (DevUtil.java:2513)
    at java.lang.Thread.run (Thread.java:748)
[INFO] CWWKM2001I: Invoke command is [/Users/paulg/WAS/devExperience/featureGeneration/tmp/basic-dev-project/target/liberty/wlp/bin/server, stop, defaultServer].
```

**Comment by turkeylurkey** [comment]
messages.log
```
{"type":"liberty_message","host":"192.168.0.209","ibm_userDir":"\/Users\/paulg\/WAS\/devExperience\/featureGeneration\/tmp\/basic-dev-project\/target\/liberty\/wlp\/usr\/","ibm_serverName":"defaultServer","message":"product = Open Liberty 22.0.0.3 (wlp-1.0.62.cl220320220302-1100)\nwlp.install.dir = \/Users\/paulg\/WAS\/devExperience\/featureGeneration\/tmp\/basic-dev-project\/target\/liberty\/wlp\/\njava.home = \/Users\/paulg\/WAS\/Java8\/Contents\/Home\/jre\njava.version = 1.8.0_231\njava.runtime = Java(TM) 2 Runtime Environment, Standard Edition (1.8.0_231-b11 24_Oct_2019_15_52 Mac OS X x64(SR6))\nos = Mac OS X (10.16; x86_64) (en_CA)\nprocess = 22854@Pauls-MacBook-Pro-15.local\nClasspath = \/Users\/paulg\/WAS\/devExperience\/featureGeneration\/tmp\/basic-dev-project\/target\/liberty\/wlp\/bin\/tools\/ws-server.jar:\/Users\/paulg\/WAS\/devExperience\/featureGeneration\/tmp\/basic-dev-project\/target\/liberty\/wlp\/bin\/tools\/ws-javaagent.jar\nJava Library path = \/Users\/paulg\/Library\/Java\/Extensions:\/Library\/Java\/Extensions:\/Network\/Library\/Java\/Extensions:\/System\/Library\/Java\/Extensions:\/usr\/lib\/java:.\n","ibm_datetime":"2022-04-07T19:16:04.226-0400","ibm_sequence":"1649373364226_0000000000001"}
{"type":"liberty_message","host":"192.168.0.209","ibm_userDir":"\/Users\/paulg\/WAS\/devExperience\/featureGeneration\/tmp\/basic-dev-project\/target\/liberty\/wlp\/usr\/","ibm_serverName":"defaultServer","message":"CWWKE0001I: The server defaultServer has been launched.","ibm_threadId":"00000001","ibm_datetime":"2022-04-07T19:16:04.249-0400","ibm_messageId":"CWWKE0001I","module":"com.ibm.ws.kernel.launch.internal.FrameworkManager","loglevel":"AUDIT","ibm_sequence":"1649373364249_0000000000001"}
{"type":"liberty_message","host":"192.168.0.209","ibm_userDir":"\/Users\/paulg\/WAS\/devExperience\/featureGeneration\/tmp\/basic-dev-project\/target\/liberty\/wlp\/usr\/","ibm_serverName":"defaultServer","message":"CWWKG0028A: Processing included configuration resource: \/Users\/paulg\/WAS\/devExperience\/featureGeneration\/tmp\/basic-dev-project\/target\/liberty\/wlp\/usr\/servers\/defaultServer\/extraFeatures.xml","ibm_threadId":"0000001c","ibm_datetime":"2022-04-07T19:16:04.569-0400","ibm_messageId":"CWWKG0028A","module":"com.ibm.ws.config.xml.internal.XMLConfigParser","loglevel":"AUDIT","ibm_sequence":"1649373364569_0000000000002"}
{"type":"liberty_message","host":"192.168.0.209","ibm_userDir":"\/Users\/paulg\/WAS\/devExperience\/featureGeneration\/tmp\/basic-dev-project\/target\/liberty\/wlp\/usr\/","ibm_serverName":"defaultServer","message":"CWWKG0093A: Processing configuration drop-ins resource: \/Users\/paulg\/WAS\/devExperience\/featureGeneration\/tmp\/basic-dev-project\/target\/liberty\/wlp\/usr\/servers\/defaultServer\/configDropins\/overrides\/generated-features.xml","ibm_threadId":"0000001c","ibm_datetime":"2022-04-07T19:16:04.575-0400","ibm_messageId":"CWWKG0093A","module":"com.ibm.ws.config.xml.internal.ServerXMLConfiguration","loglevel":"AUDIT","ibm_sequence":"1649373364575_0000000000003"}
{"type":"liberty_message","host":"192.168.0.209","ibm_userDir":"\/Users\/paulg\/WAS\/devExperience\/featureGeneration\/tmp\/basic-dev-project\/target\/liberty\/wlp\/usr\/","ibm_serverName":"defaultServer","message":"CWWKE0002I: The kernel started after 0.607 seconds","ibm_threadId":"00000001","ibm_datetime":"2022-04-07T19:16:04.674-0400","ibm_messageId":"CWWKE0002I","module":"com.ibm.ws.kernel.launch.internal.FrameworkManager","loglevel":"INFO","ibm_sequence":"1649373364674_0000000000004"}
{"type":"liberty_message","host":"192.168.0.209","ibm_userDir":"\/Users\/paulg\/WAS\/devExperience\/featureGeneration\/tmp\/basic-dev-project\/target\/liberty\/wlp\/usr\/","ibm_serverName":"defaultServer","message":"CWWKF0007I: Feature update started.","ibm_threadId":"00000028","ibm_datetime":"2022-04-07T19:16:04.683-0400","ibm_messageId":"CWWKF0007I","module":"com.ibm.ws.kernel.feature.internal.FeatureManager","loglevel":"INFO","ibm_sequence":"1649373364683_0000000000005"}
{"type":"liberty_message","host":"192.168.0.209","ibm_userDir":"\/Users\/paulg\/WAS\/devExperience\/featureGeneration\/tmp\/basic-dev-project\/target\/liberty\/wlp\/usr\/","ibm_serverName":"defaultServer","message":"Aries Blueprint packages not available. So namespaces will not be registered","ibm_threadId":"0000001d","ibm_datetime":"2022-04-07T19:16:04.735-0400","module":"org.apache.cxf.bus.blueprint.NamespaceHandlerRegistererorg.eclipse.osgi.internal.loader.EquinoxClassLoader@7018e6e5[com.ibm.ws.org.apache.cxf.cxf.core.3.2:1.0.62.cl220320220302-1100(id=84)]","loglevel":"INFO","ibm_sequence":"1649373364735_0000000000006","ext_thread":"Equinox start level thread - Equinox Container: aa795559-2822-464f-809e-b383e8f94857"}
```

**Comment by yeekangc** [comment]
@turkeylurkey, do we have a workaround for this issue?

@hlhoots, can someone work with Paul and team to investigate and chase down the root cause?

Thanks.

**Comment by hlhoots** [comment]
@yeekangc Yes, will follow up with Paul. Thanks!

**Comment by turkeylurkey** [comment]
I believe it is hanging waiting for the debugger.
`Listening for transport dt_socket at address: 7777`
