### ISSUE TITLE
Openliberty 17.0.0.4+JCA 1.7 feature do not repsect resource adapter transaction support

### ISSUE THREAD

**Issue by hrstoyanov** [OpenLiberty/open-liberty#2075]
Hello,
I am developing a JCA adapter for OrintDB hosted [here at GitHub](https://github.com/peruncs/orientdb-jca). As you can see the resource adapter specify no transaction support:
```
@Connector(
        transactionSupport = TransactionSupport.TransactionSupportLevel.NoTransaction,
        version = "1.0",
        vendorName = "PerunCS",
        displayName = "OrientDB",
        description = "Java JCA 1.7 adapter for OrientDB 3+. See https://github.com/peruncs/orientdb-jca ",
        eisType = "Database")
```
Yet once deployed in OL 17.0.0.4 + JCA 1.7 I get this exception:

```
Caused by: javax.resource.ResourceException: OrientDB resource adapter does not support local transactions
        at com.peruncs.odb.impl.ODBManagedConnectionImpl.getLocalTransaction(ODBManagedConnectionImpl.java:128)
        at com.ibm.ejs.j2c.LocalTransactionWrapper.initialize(LocalTransactionWrapper.java:75)
        at [internal classes]
        at com.peruncs.odb.impl.ODBConnectionFactoryImpl.createConnection(ODBConnectionFactoryImpl.java:37)
        at com.recres.web.server.ODBProducer.openDatabase(ODBProducer.java:28)
        ... 17 more

[ERROR   ] SRVE0315E: An exception occurred: java.lang.Throwable: java.lang.RuntimeException: javax.resource.ResourceException: OrientDB resource adapter does not support local transactions
        at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:5006)
        at [internal classes]
Caused by: java.lang.RuntimeException: javax.resource.ResourceException: OrientDB resource adapter does not support local transactions
        at com.recres.web.server.ODBProducer.openDatabase(ODBProducer.java:31)
        at sun.reflect.GeneratedMethodAccessor762.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:88)
        at [internal classes]
        at org.jboss.weld.context.AbstractContext.get(AbstractContext.java:96)
        at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get(ContextualInstanceStrategy.java:100)
        at [internal classes]
        at com.peruncs.odb.api.AutoCloseable$Closeable$ODBConnection$2118976585$Proxy$_$$_WeldClientProxy.getOrientDBPool(Unknown Source)
        at com.recres.web.server.PingService.ping(PingService.java:23)
        at com.recres.web.server.PingService$Proxy$_$$_WeldClientProxy.ping(Unknown Source)
        at sun.reflect.GeneratedMethodAccessor749.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.ibm.ws.jaxrs20.server.LibertyJaxRsServerFactoryBean.performInvocation(LibertyJaxRsServerFactoryBean.java:633)
        at [internal classes]
        at com.recres.web.server.BootstrapFilter.doFilter(BootstrapFilter.java:27)
        at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:201)
        ... 1 more
Caused by: javax.resource.ResourceException: OrientDB resource adapter does not support local transactions
        at com.peruncs.odb.impl.ODBManagedConnectionImpl.getLocalTransaction(ODBManagedConnectionImpl.java:128)
        at com.ibm.ejs.j2c.LocalTransactionWrapper.initialize(LocalTransactionWrapper.java:75)
        at [internal classes]
        at com.peruncs.odb.impl.ODBConnectionFactoryImpl.createConnection(ODBConnectionFactoryImpl.java:37)
        at com.recres.web.server.ODBProducer.openDatabase(ODBProducer.java:28)

```

which tells me that OL/JCA do not respect the rsource adapter capabilities??? My client code in Microprofile-based so there is no JTA that would initiate transaction?

**Comment by hrstoyanov** [comment]
Seems like my mistake - my managed connection factory had this:
```
@Override
    public TransactionSupport.TransactionSupportLevel getTransactionSupport() {
        return TransactionSupportLevel.LocalTransaction;
    }
```
