### ISSUE TITLE
Unable to use Microprofile-5.0 or webProfile-9.1 features with Websphere Liberty 22.0.0.3

### ISSUE THREAD

**Issue by lee-cotton** [OpenLiberty/open-liberty#20780]
When adding the microprofile-5.0 or webProfile-9.1 features to Liberty server.xml the server fails to start 

`Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8

Launching default (WebSphere Application Server 22.0.0.3/wlp-1.0.62.cl220320220302-1100) on OpenJDK 64-Bit Server VM, version 1.8.0_322-b06 (en_US)

[AUDIT   ] CWWKE0001I: The server default has been launched.

[ERROR   ] CWWKF0044E: The cdi-3.0 and io.openliberty.distributedMapInternal-1.0 features cannot be loaded at the same time. The cdi-3.0 feature of Jakarta EE 9 is incompatible with the io.openliberty.distributedMapInternal-1.0 feature of Java EE 6. The microProfile-5.0 and microProfile-5.0 configured features include an incompatible combination of features. Your configuration is not supported. Update the configuration to use features that support either the Jakarta EE or Java EE programming models, but not both.

[WARNING ] CWWKF0046W: The configuration includes an incompatible combination of features. As a result, the feature manager did not install any features.

[AUDIT   ] CWWKF0011I: The default server is ready to run a smarter planet. The default server started in 1.497 seconds.

2022-04-12 08:28:36,435 INFO success: wlp entered RUNNING state, process has stayed up for > than 10 seconds (startsecs)

2022-04-12 08:28:36,435 INFO success: filebeat entered RUNNING state, process has stayed up for > than 10 seconds (startsecs)

------Start of DE processing------ = [4/12/22 8:28:27:963 UTC]

Exception = java.lang.IllegalArgumentException

Source = com.ibm.ws.kernel.feature.internal.FeatureManager

probeid = reportErrors

Stack Dump = java.lang.IllegalArgumentException: Unable to load conflicting versions of features "com.ibm.websphere.appserver.eeCompatible-9.0" and "com.ibm.websphere.appserver.eeCompatible-6.0".  The feature dependency chains that led to the conflict are: io.openliberty.microProfile-5.0 -> io.openliberty.cdi-3.0 -> io.openliberty.servlet.api-5.0 -> com.ibm.websphere.appserver.eeCompatible-9.0 and io.openliberty.microProfile-5.0 -> io.openliberty.mpJwt-2.0 -> com.ibm.websphere.appserver.jwt-1.0 -> com.ibm.wsspi.appserver.webBundleSecurity-1.0 -> com.ibm.websphere.appserver.distributedMap-1.0 -> io.openliberty.distributedMapInternal-1.0 -> com.ibm.websphere.appserver.eeCompatible-6.0

at com.ibm.ws.kernel.feature.internal.FeatureManager.reportErrors(FeatureManager.java:1895)

at com.ibm.ws.kernel.feature.internal.FeatureManager.updateFeatures(FeatureManager.java:1421)

at com.ibm.ws.kernel.feature.internal.FeatureManager.update(FeatureManager.java:773)

at com.ibm.ws.kernel.feature.internal.FeatureManager.processFeatureChanges(FeatureManager.java:887)

at com.ibm.ws.kernel.feature.internal.FeatureManager$1.run(FeatureManager.java:673)

at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:245)

at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

at java.lang.Thread.run(Thread.java:750)

Dump of callerThis

null

------Start of DE processing------ = [4/12/22 8:28:27:968 UTC]

Dump of objectArray[0]

------Start of DE processing------ = [4/12/22 8:28:27:966 UTC]

Object type = java.lang.String

Exception = java.lang.IllegalArgumentException

  String value = "com.ibm.websphere.appserver.eeCompatible"

Dump of objectArray[1]

Source = com.ibm.ws.kernel.feature.internal.FeatureManager

probeid = reportErrors

Stack Dump = java.lang.IllegalArgumentException: Unable to load conflicting versions of features "com.ibm.websphere.appserver.servlet-5.0" and "com.ibm.websphere.appserver.servlet-3.0".  The feature dependency chains that led to the conflict are: io.openliberty.microProfile-5.0 -> io.openliberty.restfulWS-3.0 -> io.openliberty.restfulWSClient-3.0 -> com.ibm.websphere.appserver.servlet-5.0 and io.openliberty.microProfile-5.0 -> io.openliberty.mpHealth-4.0 -> com.ibm.wsspi.appserver.webBundle-1.0 -> io.openliberty.webBundle.internal.ee-6.0 -> com.ibm.websphere.appserver.servlet-3.0

Object type = java.lang.String

at com.ibm.ws.kernel.feature.internal.FeatureManager.reportErrors(FeatureManager.java:1895)

at com.ibm.ws.kernel.feature.internal.FeatureManager.updateFeatures(FeatureManager.java:1421)

at com.ibm.ws.kernel.feature.internal.FeatureManager.update(FeatureManager.java:773)

at com.ibm.ws.kernel.feature.internal.FeatureManager.processFeatureChanges(FeatureManager.java:887)

at com.ibm.ws.kernel.feature.internal.FeatureManager$1.run(FeatureManager.java:673)

at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:245)

at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

Exception = java.lang.IllegalArgumentException

at java.lang.Thread.run(Thread.java:750)

Source = com.ibm.ws.kernel.feature.internal.FeatureManager

probeid = reportErrors

Stack Dump = java.lang.IllegalArgumentException: Unable to load conflicting versions of features "io.openliberty.servlet.api-5.0" and "io.openliberty.servlet.api-3.0".  The feature dependency chains that led to the conflict are: io.openliberty.microProfile-5.0 -> io.openliberty.cdi-3.0 -> io.openliberty.servlet.api-5.0 and io.openliberty.microProfile-5.0 -> io.openliberty.restfulWS-3.0 -> io.openliberty.restfulWSClient-3.0 -> com.ibm.websphere.appserver.globalhandler-1.0 -> io.openliberty.globalhandler1.0.internal.ee-6.0 -> io.openliberty.servlet.api-3.0

at com.ibm.ws.kernel.feature.internal.FeatureManager.reportErrors(FeatureManager.java:1895)

at com.ibm.ws.kernel.feature.internal.FeatureManager.updateFeatures(FeatureManager.java:1421)

  String value = "[ROOT->io.openliberty.microProfile-5.0->io.openliberty.cdi-3.0->io.openliberty.servlet.api-5.0->[com.ibm.websphere.appserver.eeCompatible-9.0] 9.0.0, ROOT->io.openliberty.microProfile-5.0->io.openliberty.mpJwt-2.0->com.ibm.websphere.appserver.jwt-1.0->com.ibm.wsspi.appserver.webBundleSecurity-1.0->com.ibm.websphere.appserver.distributedMap-1.0->io.openliberty.distributedMapInternal-1.0->[com.ibm.websphere.appserver.eeCompatible-6.0, com.ibm.websphere.appserver.eeCompatible-7.0, com.ibm.websphere.appserver.eeCompatible-8.0] 6.0.0]"

at com.ibm.ws.kernel.feature.internal.FeatureManager.update(FeatureManager.java:773)

at com.ibm.ws.kernel.feature.internal.FeatureManager.processFeatureChanges(FeatureManager.java:887)

at com.ibm.ws.kernel.feature.internal.FeatureManager$1.run(FeatureManager.java:673)

at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:245)

at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

at java.lang.Thread.run(Thread.java:750)

Dump of callerThis

null

Dump of objectArray[0]

Object type = java.lang.String

  String value = "com.ibm.websphere.appserver.servlet"

Dump of objectArray[1]

Object type = java.lang.String

  String value = "[ROOT->io.openliberty.microProfile-5.0->io.openliberty.restfulWS-3.0->io.openliberty.restfulWSClient-3.0->[com.ibm.websphere.appserver.servlet-5.0] 5.0.0, ROOT->io.openliberty.microProfile-5.0->io.openliberty.mpHealth-4.0->com.ibm.wsspi.appserver.webBundle-1.0->io.openliberty.webBundle.internal.ee-6.0->[com.ibm.websphere.appserver.servlet-3.0, com.ibm.websphere.appserver.servlet-3.1, com.ibm.websphere.appserver.servlet-4.0] 3.0.0]"

Dump of callerThis

null

Dump of objectArray[0]

Object type = java.lang.String

  String value = "io.openliberty.servlet.api"

Dump of objectArray[1]

Object type = java.lang.String

  String value = "[ROOT->io.openliberty.microProfile-5.0->io.openliberty.cdi-3.0->[io.openliberty.servlet.api-5.0] 5.0.0, ROOT->io.openliberty.microProfile-5.0->io.openliberty.restfulWS-3.0->io.openliberty.restfulWSClient-3.0->com.ibm.websphere.appserver.globalhandler-1.0->io.openliberty.globalhandler1.0.internal.ee-6.0->[io.openliberty.servlet.api-3.0, io.openliberty.servlet.api-3.1, io.openliberty.servlet.api-4.0] 3.0.0]"`

**Steps to Reproduce**  
Add microprofile-5.0 feature to server.xml:

`    <featureManager>
        <feature>microProfile-5.0</feature>
    </featureManager>
`

**Expected behavior**  
Server starts successfully and features can be used.

**Diagnostic information:**  

 - OpenLiberty Version: 
`Launching default (WebSphere Application Server 22.0.0.3/wlp-1.0.62.cl220320220302-1100) on OpenJDK 64-Bit Server VM, version 1.8.0_322-b06 (en_US)`

 - Affected feature(s) microprofile-5.0
 
 - Java Version: 
 `openjdk version "1.8.0_322"
OpenJDK Runtime Environment (build 1.8.0_322-b06)
OpenJDK 64-Bit Server VM (build 25.322-b06, mixed mode)`

 - server.xml configuration (WITHOUT sensitive information like passwords)

messages.log:

`********************************************************************************
product = WebSphere Application Server 22.0.0.3 (wlp-1.0.62.cl220320220302-1100)
wlp.install.dir = /opt/was/liberty/wlp/
java.home = /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.322.b06-2.el8_5.x86_64/jre
java.version = 1.8.0_322
java.runtime = OpenJDK Runtime Environment (1.8.0_322-b06)
os = Linux (5.10.104-linuxkit; amd64) (en_US)
process = 9@21241ed46755
Classpath = /opt/was/liberty/wlp/bin/tools/ws-server.jar:/opt/was/liberty/wlp/bin/tools/ws-javaagent.jar
Java Library path = /opt/ibm/cplex_libraries/opl-linux-22.1-x86-64-release/bin/x86-64_linux:/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
********************************************************************************
[4/12/22 8:28:26:773 UTC] 00000001 com.ibm.ws.kernel.launch.internal.FrameworkManager           A CWWKE0001I: The server default has been launched.
[4/12/22 8:28:27:728 UTC] 00000001 com.ibm.ws.kernel.launch.internal.FrameworkManager           I CWWKE0002I: The kernel started after 1.197 seconds
[4/12/22 8:28:27:859 UTC] 00000020 com.ibm.ws.kernel.feature.internal.FeatureManager            I CWWKF0007I: Feature update started.
[4/12/22 8:28:27:960 UTC] 00000020 com.ibm.ws.kernel.feature.internal.FeatureManager            E CWWKF0044E: The cdi-3.0 and io.openliberty.distributedMapInternal-1.0 features cannot be loaded at the same time. The cdi-3.0 feature of Jakarta EE 9 is incompatible with the io.openliberty.distributedMapInternal-1.0 feature of Java EE 6. The microProfile-5.0 and microProfile-5.0 configured features include an incompatible combination of features. Your configuration is not supported. Update the configuration to use features that support either the Jakarta EE or Java EE programming models, but not both.
[4/12/22 8:28:27:965 UTC] 00000020 com.ibm.ws.logging.internal.impl.IncidentImpl                I FFDC1015I: An FFDC Incident has been created: "java.lang.IllegalArgumentException: Unable to load conflicting versions of features "com.ibm.websphere.appserver.eeCompatible-9.0" and "com.ibm.websphere.appserver.eeCompatible-6.0".  The feature dependency chains that led to the conflict are: io.openliberty.microProfile-5.0 -> io.openliberty.cdi-3.0 -> io.openliberty.servlet.api-5.0 -> com.ibm.websphere.appserver.eeCompatible-9.0 and io.openliberty.microProfile-5.0 -> io.openliberty.mpJwt-2.0 -> com.ibm.websphere.appserver.jwt-1.0 -> com.ibm.wsspi.appserver.webBundleSecurity-1.0 -> com.ibm.websphere.appserver.distributedMap-1.0 -> io.openliberty.distributedMapInternal-1.0 -> com.ibm.websphere.appserver.eeCompatible-6.0 com.ibm.ws.kernel.feature.internal.FeatureManager reportErrors" at ffdc_22.04.12_08.28.27.0.log
[4/12/22 8:28:27:967 UTC] 00000020 com.ibm.ws.logging.internal.impl.IncidentImpl                I FFDC1015I: An FFDC Incident has been created: "java.lang.IllegalArgumentException: Unable to load conflicting versions of features "com.ibm.websphere.appserver.servlet-5.0" and "com.ibm.websphere.appserver.servlet-3.0".  The feature dependency chains that led to the conflict are: io.openliberty.microProfile-5.0 -> io.openliberty.restfulWS-3.0 -> io.openliberty.restfulWSClient-3.0 -> com.ibm.websphere.appserver.servlet-5.0 and io.openliberty.microProfile-5.0 -> io.openliberty.mpHealth-4.0 -> com.ibm.wsspi.appserver.webBundle-1.0 -> io.openliberty.webBundle.internal.ee-6.0 -> com.ibm.websphere.appserver.servlet-3.0 com.ibm.ws.kernel.feature.internal.FeatureManager reportErrors" at ffdc_22.04.12_08.28.27.1.log
[4/12/22 8:28:27:969 UTC] 00000020 com.ibm.ws.logging.internal.impl.IncidentImpl                I FFDC1015I: An FFDC Incident has been created: "java.lang.IllegalArgumentException: Unable to load conflicting versions of features "io.openliberty.servlet.api-5.0" and "io.openliberty.servlet.api-3.0".  The feature dependency chains that led to the conflict are: io.openliberty.microProfile-5.0 -> io.openliberty.cdi-3.0 -> io.openliberty.servlet.api-5.0 and io.openliberty.microProfile-5.0 -> io.openliberty.restfulWS-3.0 -> io.openliberty.restfulWSClient-3.0 -> com.ibm.websphere.appserver.globalhandler-1.0 -> io.openliberty.globalhandler1.0.internal.ee-6.0 -> io.openliberty.servlet.api-3.0 com.ibm.ws.kernel.feature.internal.FeatureManager reportErrors" at ffdc_22.04.12_08.28.27.2.log
[4/12/22 8:28:27:969 UTC] 00000020 com.ibm.ws.kernel.feature.internal.FeatureManager            W CWWKF0046W: The configuration includes an incompatible combination of features. As a result, the feature manager did not install any features.
[4/12/22 8:28:28:027 UTC] 00000020 com.ibm.ws.kernel.feature.internal.FeatureManager            I CWWKF0008I: Feature update completed in 0.299 seconds.
[4/12/22 8:28:28:028 UTC] 00000020 com.ibm.ws.kernel.feature.internal.FeatureManager            A CWWKF0011I: The default server is ready to run a smarter planet. The default server started in 1.497 seconds.`

**Comment by jhanders34** [comment]
This github repository is for Open Liberty issues.  The problem you are reporting is a WebSphere Liberty packaging issue and is not seen with the Open Liberty packages.  22.0.0.4 just published this morning and the WebSphere Liberty packaging issue that causes the problem you are reporting is resolved in that release.  If you want to pursue a fix for this issue in WebSphere Liberty in a release before 22.0.0.4, you should open a support issue against the WebSphere Liberty product.  A possible workaround on WebSphere Liberty 22.0.0.3 is to use the installUtility to uninstall the microprofile-5.0 and jakartaee-9.1 features and then re-install them.  

Since this issue is specific to WebSphere Liberty and not related to Open Liberty itself, I am closing this issue.
