### ISSUE TITLE
Test Failure: org.eclipse.microprofile.health.tck.CDIProducedProceduresTest.testSuccessfulLivenessResponsePayload

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#20833]
RTC 290144

```
testSuccessfulLivenessResponsePayload:
      java.lang.AssertionError: expected [200] but found [503]
at org.testng.Assert.fail(Assert.java:94)
at org.testng.Assert.failNotEquals(Assert.java:496)
at org.testng.Assert.assertEquals(Assert.java:125)
at org.testng.Assert.assertEquals(Assert.java:372)
at org.testng.Assert.assertEquals(Assert.java:382)
at org.eclipse.microprofile.health.tck.CDIProducedProceduresTest.testSuccessfulLivenessResponsePayload(CDIProducedProceduresTest.java:59)
```

Found this FFDC
```
------Start of DE processing------ = [4/10/22, 7:46:28:330 PDT]
Exception = java.lang.NoClassDefFoundError
Source = com.ibm.ws.injectionengine.InjectionProcessorManager.getAllDeclaredFields
probeid = 249
Stack Dump = java.lang.NoClassDefFoundError: org.apache.http.auth.Credentials
    at java.base/java.lang.J9VMInternals.prepareClassImpl(Native Method)
    at java.base/java.lang.J9VMInternals.prepare(J9VMInternals.java:340)
    at java.base/java.lang.Class.getDeclaredFields(Class.java:980)
    at com.ibm.ws.injectionengine.InjectionProcessorManager.getAllDeclaredFields(InjectionProcessorManager.java:390)
    at com.ibm.ws.injectionengine.InjectionProcessorManager.processAnnotations(InjectionProcessorManager.java:215)
    at com.ibm.ws.injectionengine.AbstractInjectionEngine.processInjectionMetaData(AbstractInjectionEngine.java:480)
    at com.ibm.ws.injectionengine.osgi.internal.OSGiInjectionEngineImpl.processInjectionMetaData(OSGiInjectionEngineImpl.java:240)
    at com.ibm.ws.injectionengine.ReferenceContextImpl.processImpl(ReferenceContextImpl.java:588)
    at com.ibm.ws.injectionengine.ReferenceContextImpl.process(ReferenceContextImpl.java:287)
    at com.ibm.ws.injectionengine.osgi.internal.OSGiReferenceContextImpl.process(OSGiReferenceContextImpl.java:30)
    at com.ibm.ws.cdi.impl.weld.WebSphereCDIDeploymentImpl.initializeInjectionServices(WebSphereCDIDeploymentImpl.java:666)
    at com.ibm.ws.cdi.impl.CDIContainerImpl.startInitialization(CDIContainerImpl.java:149)
    at com.ibm.ws.cdi.liberty.CDIRuntimeImpl.applicationStarting(CDIRuntimeImpl.java:488)
    at com.ibm.ws.container.service.state.internal.ApplicationStateManager.fireStarting(ApplicationStateManager.java:51)
    at com.ibm.ws.container.service.state.internal.StateChangeServiceImpl.fireApplicationStarting(StateChangeServiceImpl.java:50)
    at com.ibm.ws.app.manager.module.internal.SimpleDeployedAppInfoBase.preDeployApp(SimpleDeployedAppInfoBase.java:547)
    at com.ibm.ws.app.manager.module.internal.SimpleDeployedAppInfoBase.installApp(SimpleDeployedAppInfoBase.java:508)
    at com.ibm.ws.app.manager.module.internal.DeployedAppInfoBase.deployApp(DeployedAppInfoBase.java:349)
    at com.ibm.ws.app.manager.war.internal.WARApplicationHandlerImpl.install(WARApplicationHandlerImpl.java:65)
    at com.ibm.ws.app.manager.internal.statemachine.StartAction.execute(StartAction.java:161)
    at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.enterState(ApplicationStateMachineImpl.java:1357)
    at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.performAction(ApplicationStateMachineImpl.java:1202)
    at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.run(ApplicationStateMachineImpl.java:909)
    at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:245)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:866)
Caused by: java.lang.ClassNotFoundException: org.apache.http.auth.Credentials
    at com.ibm.ws.classloading.internal.AppClassLoader.findClassCommonLibraryClassLoaders(AppClassLoader.java:748)
    at com.ibm.ws.classloading.internal.AppClassLoader.findClass(AppClassLoader.java:319)
    at com.ibm.ws.classloading.internal.AppClassLoader.findOrDelegateLoadClass(AppClassLoader.java:720)
    at com.ibm.ws.classloading.internal.AppClassLoader.loadClass(AppClassLoader.java:592)
    at com.ibm.ws.classloading.internal.AppClassLoader.loadClass(AppClassLoader.java:559)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1086)
    ... 27 more
```

messages.log:
```
[4/10/22, 7:46:28:371 PDT] 00000033 com.ibm.ws.injectionengine.InjectionProcessorManager         W CWNEN0047W: Resource annotations on the fields of the org.eclipse.microprofile.health.tck.SingleStartupSuccessfulTest class will be ignored. The annotations could not be obtained because of the exception : java.lang.NoClassDefFoundError: org.apache.http.auth.Credentials
```

**Comment by fmhwong** [comment]
Looks like this failed on Semeru JDK only.

**Comment by pgunapal** [comment]
Closing, as the test failure has not occurred for more than 2 months. Will re-open if the test failure re-occurs again.
