### ISSUE TITLE
CTS: EE8: JAX-RS bucket: NullPointerException during SseEventSink.send

### ISSUE THREAD

**Issue by jkoehler22** [OpenLiberty/open-liberty#2084]
[2/8/18 10:05:06:487 EST] 00000060 com.ibm.ws.webcontainer.srt                                  W WARNING: Cannot set status. Response already committed.
[2/8/18 10:05:06:556 EST] 00000060 com.ibm.ws.webcontainer.srt                                  W SRVE8094W: WARNING: Cannot set header. Response already committed.  Stack trace of errant attempt to set header: 
        at com.ibm.ws.webcontainer.srt.SRTServletResponse.setHeader(SRTServletResponse.java:1748)
        at [internal classes].(Unknown Source)

[2/8/18 10:05:09:356 EST] 0000005a g.apache.cxf.cxf.rt.frontend.jaxrs.3.2:1.0.20.master(id=97)] W java.lang.NullPointerException
	at org.apache.cxf.jaxrs.ext.MessageContextImpl.get(MessageContextImpl.java:88)
	at org.apache.cxf.jaxrs.impl.tl.ThreadLocalMessageContext.get(ThreadLocalMessageContext.java:42)
	at org.apache.cxf.jaxrs.provider.JAXBElementProvider.getAttachments(JAXBElementProvider.java:540)
	at org.apache.cxf.jaxrs.provider.JAXBElementProvider.addAttachmentMarshaller(JAXBElementProvider.java:518)
	at org.apache.cxf.jaxrs.provider.JAXBElementProvider.marshal(JAXBElementProvider.java:443)
	at org.apache.cxf.jaxrs.provider.JAXBElementProvider.writeTo(JAXBElementProvider.java:319)
	at org.apache.cxf.jaxrs.sse.OutboundSseEventBodyWriter.writePayloadTo(OutboundSseEventBodyWriter.java:131)
	at org.apache.cxf.jaxrs.sse.OutboundSseEventBodyWriter.writeTo(OutboundSseEventBodyWriter.java:112)
	at org.apache.cxf.jaxrs.sse.OutboundSseEventBodyWriter.writeTo(OutboundSseEventBodyWriter.java:40)
	at com.ibm.ws.jaxrs21.sse.LibertySseEventSinkImpl.send(LibertySseEventSinkImpl.java:98)
	at com.sun.ts.tests.jaxrs.jaxrs21.ee.sse.sseeventsink.MBWCheckResource.sendJAXBElement(MBWCheckResource.java:129)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at com.ibm.ws.jaxrs20.server.LibertyJaxRsServerFactoryBean.performInvocation(LibertyJaxRsServerFactoryBean.java:646)
	at com.ibm.ws.jaxrs20.server.LibertyJaxRsInvoker.performInvocation(LibertyJaxRsInvoker.java:117)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
	at com.ibm.ws.jaxrs20.server.LibertyJaxRsInvoker.invoke(LibertyJaxRsInvoker.java:251)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:192)
	at com.ibm.ws.jaxrs20.server.LibertyJaxRsInvoker.invoke(LibertyJaxRsInvoker.java:422)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:103)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:61)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:99)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:124)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:276)
	at com.ibm.ws.jaxrs20.endpoint.AbstractJaxRsWebEndpoint.invoke(AbstractJaxRsWebEndpoint.java:136)
	at com.ibm.websphere.jaxrs.server.IBMRestServlet.handleRequest(IBMRestServlet.java:146)
	at com.ibm.websphere.jaxrs.server.IBMRestServlet.doGet(IBMRestServlet.java:112)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:686)
	at com.ibm.websphere.jaxrs.server.IBMRestServlet.service(IBMRestServlet.java:96)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1255)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:743)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:440)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1154)
	at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:4962)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.handleRequest(DynamicVirtualHost.java:314)
	at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:995)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:279)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1009)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:412)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:371)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:530)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:464)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:329)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.ready(HttpInboundLink.java:300)
	at com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.sendToDiscriminators(NewConnectionInitialReadCallback.java:165)
	at com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.complete(NewConnectionInitialReadCallback.java:74)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:501)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueManager.java:571)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:926)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:1015)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:811)

**Comment by jkoehler22** [comment]
[messages.log](https://github.com/OpenLiberty/open-liberty/files/1707656/messages.log)

**Comment by jkoehler22** [comment]
I can't upload the trace.log.  Ping me if you need that....

**Comment by jkoehler22** [comment]
[javatest.batch] 02-08-2018 10:05:13:  ERROR: The message was not received
[javatest.batch] 02-08-2018 10:05:13:  ERROR: Test case throws exception: The message was not received
[javatest.batch] 02-08-2018 10:05:13:  ERROR: Exception at:  
[javatest.batch] 02-08-2018 10:05:13:  ERROR: com.sun.ts.lib.harness.EETest$Fault: The message was not received
[javatest.batch] 	at com.sun.ts.tests.jaxrs.common.JAXRSCommonClient.fault(JAXRSCommonClient.java:730)
[javatest.batch] 	at com.sun.ts.tests.jaxrs.common.JAXRSCommonClient.assertTrue(JAXRSCommonClient.java:625)
[javatest.batch] 	at com.sun.ts.tests.jaxrs.common.JAXRSCommonClient.assertNotNull(JAXRSCommonClient.java:716)
[javatest.batch] 	at com.sun.ts.tests.jaxrs.jaxrs21.ee.sse.SSEJAXRSClient.querySSEEndpoint(SSEJAXRSClient.java:50)
[javatest.batch] 	at com.sun.ts.tests.jaxrs.jaxrs21.ee.sse.SSEJAXRSClient.querySSEEndpoint(SSEJAXRSClient.java:32)
[javatest.batch] 	at com.sun.ts.tests.jaxrs.jaxrs21.ee.sse.sseeventsink.JAXRSClient.jaxbElementTest(JAXRSClient.java:216)
[javatest.batch] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[javatest.batch] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
[javatest.batch] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
[javatest.batch] 	at java.lang.reflect.Method.invoke(Method.java:508)
[javatest.batch] 	at com.sun.ts.lib.harness.EETest.run(EETest.java:550)
[javatest.batch] 	at com.sun.ts.lib.harness.ServiceEETest.run(ServiceEETest.java:113)
[javatest.batch] 	at com.sun.ts.tests.common.vehicle.EmptyVehicleRunner.run(EmptyVehicleRunner.java:30)
[javatest.batch] 	at com.sun.ts.lib.harness.ServiceEETest.run(ServiceEETest.java:102)
[javatest.batch] 	at com.sun.ts.lib.harness.EETest.getPropsReady(EETest.java:446)
[javatest.batch] 	at com.sun.ts.lib.harness.ServiceEETest.run(ServiceEETest.java:210)
[javatest.batch] 	at com.sun.ts.lib.harness.EETest.run(EETest.java:257)
[javatest.batch] 	at com.sun.ts.tests.common.vehicle.VehicleClient.main(VehicleClient.java:27)
[javatest.batch] 
[javatest.batch] 02-08-2018 10:05:13:  [JAXRSCommonClient] Test cleanup OK
[javatest.batch] Feb 8, 2018 10:05:14 AM Finished executing all tests, wait for cleanup...
[javatest.batch] Feb 8, 2018 10:05:14 AM Harness done with cleanup from test run.
[javatest.batch] STATUS:Failed.Test case throws exception: The message was not received
[javatest.batch] Failed. Test case throws exception: The message was not received
[javatest.batch] ********************************************************************************
[javatest.batch] Finished Test:  FAILED........com/sun/ts/tests/jaxrs/jaxrs21/ee/sse/sseeventsink/JAXRSClient.java#**jaxbElementTes**t_from_standalone

**Comment by jkoehler22** [comment]
Second test is failing with the same NPE.  FAILED........com/sun/ts/tests/jaxrs/jaxrs21/ee/sse/sseeventsource/JAXRSClient.java#jaxbElementTest_from_standalone

**Comment by jim-krueger** [comment]
Adding stack from root problem on server:
[3/2/18 15:55:39:800 EST] 00000055 id=         org.apache.cxf.jaxrs.utils.ExceptionUtils                    > getStackTrace Entry  
                                                                                                               java.lang.NullPointerException
	at org.apache.cxf.jaxrs.ext.MessageContextImpl.get(MessageContextImpl.java:88)
	at org.apache.cxf.jaxrs.impl.tl.ThreadLocalMessageContext.get(ThreadLocalMessageContext.java:42)
	at org.apache.cxf.jaxrs.provider.JAXBElementProvider.getAttachments(JAXBElementProvider.java:540)
	at org.apache.cxf.jaxrs.provider.JAXBElementProvider.addAttachmentMarshaller(JAXBElementProvider.java:518)
	at org.apache.cxf.jaxrs.provider.JAXBElementProvider.marshal(JAXBElementProvider.java:443)
	at org.apache.cxf.jaxrs.provider.JAXBElementProvider.writeTo(JAXBElementProvider.java:319)
	at org.apache.cxf.jaxrs.sse.OutboundSseEventBodyWriter.writePayloadTo(OutboundSseEventBodyWriter.java:131)
	at org.apache.cxf.jaxrs.sse.OutboundSseEventBodyWriter.writeTo(OutboundSseEventBodyWriter.java:112)
	at org.apache.cxf.jaxrs.sse.OutboundSseEventBodyWriter.writeTo(OutboundSseEventBodyWriter.java:40)
	at com.ibm.ws.jaxrs21.sse.LibertySseEventSinkImpl.send(LibertySseEventSinkImpl.java:103)
	at com.sun.ts.tests.jaxrs.jaxrs21.ee.sse.sseeventsink.MBWCheckResource.sendJAXBElement(MBWCheckResource.java:129)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at com.ibm.ws.jaxrs20.server.LibertyJaxRsServerFactoryBean.performInvocation(LibertyJaxRsServerFactoryBean.java:646)
	at com.ibm.ws.jaxrs20.server.LibertyJaxRsInvoker.performInvocation(LibertyJaxRsInvoker.java:117)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
	at com.ibm.ws.jaxrs20.server.LibertyJaxRsInvoker.invoke(LibertyJaxRsInvoker.java:251)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:192)
	at com.ibm.ws.jaxrs20.server.LibertyJaxRsInvoker.invoke(LibertyJaxRsInvoker.java:422)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:103)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:61)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:99)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:124)
