### ISSUE TITLE
update featureUtility fat

### ISSUE THREAD

**Issue by jjiwooLim** [OpenLiberty/open-liberty#20851]
testInvalidMavenCoordinatePacking test

- Update verbose message referencing InstallUtility. 
- Use local repo instead of maven repo to reduce connection related issues. 
```
[04/06/2022 17:10:09:391 UTC] 001 FeatureUtilityToolTest         testInvalidMavenCoordinatePack I featureUtility command exit code: 21
[04/06/2022 17:10:09:392 UTC] 001 FeatureUtilityToolTest         testInvalidMavenCoordinatePack I command: /home/jazz_build/Build/jbe/build/dev/image/output/wlp/../featureUtility_fat_wlp/wlp/bin/featureUtility  if io.openliberty.features:jsp-2.3:22.0.0.3:esa --verbose
[04/06/2022 17:10:19:635 UTC] 001 FeatureUtilityToolTest         testInvalidMavenCoordinatePack I 
[04/06/2022 17:10:19:635 UTC] 001 FeatureUtilityToolTest         testInvalidMavenCoordinatePack I 
[4/6/22, 17:10:09:948 UTC] Check following assets whether they were installed or not: [io.openliberty.features:jsp-2.3:22.0.0.3:esa]
<---------------------> 0.00%
[4/6/22, 17:10:10:409 UTC] Using old resolve API
<---------------------> 0.00%
[4/6/22, 17:10:11:806 UTC] checkAssetsNotInstalled() ignore exception: CWWKF1258E: The io.openliberty.features:jsp-2.3:22.0.0.3:esa asset depends on io.openliberty.features:jsp-2.3:22.0.0.3:esa, which is not available in the configured repositories. Configure installUtility to connect to the IBM WebSphere Liberty Repository to download or install the asset. If you do not have internet access, contact your administrator to download the missing asset and any dependencies and add them to a configured repository.
<---------------------> 0.00%
[4/6/22, 17:10:11:816 UTC] checkAssetsNotInstalled() cause of exception: Top level feature not resolved: resource=io.openliberty.features:jsp-2.3:22.0.0.3:esa
Top level feature not resolved: resource=com.ibm.websphere.appserver.jsf2.2-jsfApiStub2.2
Top level feature not resolved: resource=com.ibm.websphere.appserver.jsf2.3-jsfApiStub2.3
Top level feature not resolved: resource=com.ibm.websphere.appserver.cdi1.2-jsf2.2
Top level feature not resolved: resource=com.ibm.websphere.appserver.cdi2.0-jsf2.3
Top level feature not resolved: resource=com.ibm.websphere.appserver.jsf.beanValidation-2.3
Top level feature not resolved: resource=com.ibm.websphere.appserver.jsf.beanValidation-2.2
MissingRequirement [requirementName=io.openliberty.features:jsp-2.3:22.0.0.3:esa, owningResource=null]
```

**Comment by jjiwooLim** [comment]
Resolved. The message now shows:
```
[3/25/24, 14:08:44:567 UTC]Check following assets whether they were installed or not: [io.openliberty.features:json-1.0:23.0.0.2:jar]
<---------------------> 0.00%
[3/25/24, 14:08:44:640 UTC]Using old resolve API
<---------------------> 0.00%
[3/25/24, 14:08:44:676 UTC]checkAssetsNotInstalled() ignore exception: CWWKF1203E: Unable to obtain the following features: io.openliberty.features:json-1.0:23.0.0.2:jar. Ensure that the features are valid.
<---------------------> 0.00%
[3/25/24, 14:08:44:678 UTC]checkAssetsNotInstalled() cause of exception: Top level feature not resolved: resource=io.openliberty.features:json-1.0:23.0.0.2:jar
MissingRequirement [requirementName=io.openliberty.features:json-1.0:23.0.0.2:jar, owningResource=null]

<---------------------> 0.00%
[3/25/24, 14:08:44:684 UTC]CWWKF1396E: The packaging format in feature Maven coordinate io.openliberty.features:json-1.0:23.0.0.2:jar is invalid. The valid packaging format is ESA.
com.ibm.ws.install.InstallException: CWWKF1396E: The packaging format in feature Maven coordinate io.openliberty.features:json-1.0:23.0.0.2:jar is invalid. The valid packaging format is ESA.
	at com.ibm.ws.install.featureUtility.FeatureUtility.verifyMavenCoordinate(FeatureUtility.java:420)
	at com.ibm.ws.install.featureUtility.FeatureUtility.getJsonsAndFeatures(FeatureUtility.java:398)
	at com.ibm.ws.install.featureUtility.FeatureUtility.<init>(FeatureUtility.java:116)
	at com.ibm.ws.install.featureUtility.FeatureUtility.<init>(FeatureUtility.java:52)
	at com.ibm.ws.install.featureUtility.FeatureUtility$FeatureUtilityBuilder.build(FeatureUtility.java:882)
	at com.ibm.ws.install.featureUtility.cli.InstallFeatureAction.install(InstallFeatureAction.java:245)
	at com.ibm.ws.install.featureUtility.cli.InstallFeatureAction.execute(InstallFeatureAction.java:262)
	at com.ibm.ws.install.featureUtility.cli.InstallFeatureAction.handleTask(InstallFeatureAction.java:80)
	at com.ibm.ws.install.featureUtility.cli.FeatureAction.handleTask(FeatureAction.java:98)
	at com.ibm.ws.install.featureUtility.FeatureUtilityExecutor.main(FeatureUtilityExecutor.java:60)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
	at com.ibm.ws.kernel.boot.cmdline.UtilityMain.internal_main(UtilityMain.java:175)
	at com.ibm.ws.kernel.boot.cmdline.UtilityMain.main(UtilityMain.java:55)
	at com.ibm.ws.kernel.boot.cmdline.Main.main(Main.java:54)
```
