### ISSUE TITLE
LTPA key creation fails when running on Semeru Java 11 and IBMJCECCA provider is configured instead of IBMJCE

### ISSUE THREAD

**Issue by una-tapa** [OpenLiberty/open-liberty#20871]
**Describe the bug**  

Liberty fails to create LTPA key and throws the following error :      **java.security.NoSuchProviderException: no such provider: IBMJCE**  when running on Semeru Java 11 with IBMJCECCA provider configured instead of IBMJCE 

```
Error stack
------Start of DE processing------ = [4/13/22, 9:12:55:162 GMT]
Exception = java.security.NoSuchProviderException
Source = com.ibm.ws.security.token.ltpa.internal.LTPAKeyCreateTask
probeid = 115
Stack Dump = java.security.NoSuchProviderException: no such provider: IBMJCE
        at java.base/sun.security.jca.GetInstance.getService(GetInstance.java:83)
        at java.base/javax.crypto.JceSecurity.getInstance(JceSecurity.java:204)
        at java.base/javax.crypto.SecretKeyFactory.getInstance(SecretKeyFactory.java:212)
        at com.ibm.ws.crypto.ltpakeyutil.LTPACrypto.constructSecretKey(LTPACrypto.java:589)
        at com.ibm.ws.crypto.ltpakeyutil.LTPACrypto.encrypt(LTPACrypto.java:644)
        at com.ibm.ws.crypto.ltpakeyutil.KeyEncryptor.encrypt(KeyEncryptor.java:53)
        at com.ibm.ws.crypto.ltpakeyutil.LTPAKeyFileUtilityImpl.generateLTPAKeys(LTPAKeyFileUtilityImpl.java:53)
        at com.ibm.ws.security.token.ltpa.internal.LTPAKeyFileCreatorImpl.createLTPAKeysFile(LTPAKeyFileCreatorImpl.java:62)
        at com.ibm.ws.security.token.ltpa.LTPAKeyInfoManager.prepareLTPAKeyInfo(LTPAKeyInfoManager.java:118)
        at com.ibm.ws.security.token.ltpa.internal.LTPAKeyCreateTask.getPreparedLtpaKeyInfoManager(LTPAKeyCreateTask.java:53)
        at com.ibm.ws.security.token.ltpa.internal.LTPAKeyCreateTask.createRequiredCollaborators(LTPAKeyCreateTask.java:87)
```

**Steps to Reproduce**  
Conditions described above. 

**Expected behavior**  
Liberty creates LTPA key successfully. 

**Diagnostic information:**  
 - OpenLiberty Version:  Any version 
 - Affected feature(s) appSecurity-1.0, appSecurity-2.0, appSecurity-3.0
 - Java Version: 
```
java.home = /u/wakelin/java11/J11.0_64.0406
java.version = 11.0.15-internal
java.runtime = IBM Semeru Runtime Certified Edition for z/OS (11.0.15-internal+0-adhoc.JENKINS.BuildJDK11s390xzosNightly)
os = z/OS (02.03.00; s390x) (en_US)
``` 
- java.security 

```
#
# List of providers and their preference orders (see above):
#
security.provider.1=OpenJCEPlus
security.provider.2=IBMJCECCA
security.provider.3=IBMZSecurity
security.provider.4=SUN
security.provider.5=SunRsaSign
security.provider.6=SunEC
security.provider.7=SunJSSE
security.provider.8=SunJCE
security.provider.9=SunJGSS
security.provider.10=SunSASL
security.provider.11=XMLDSig
security.provider.12=SunPCSC
security.provider.13=JdkLDAP
security.provider.14=JdkSASL
security.provider.15=SunPKCS11
```

**Additional context**  
No additional info.

**Comment by una-tapa** [comment]
Working on https://github.com/OpenLiberty/open-liberty/pull/20994
