### ISSUE TITLE
ArrayOutOfBounds exception on z/OS with either full or JMX audit events enabled on shutdown 

### ISSUE THREAD

**Issue by emilytee** [OpenLiberty/open-liberty#20981]
**Describe the bug**  
ArrayOutOfBounds exception with either full or JMX audit events enabled on shutdown 

Stack Dump = java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 10
	at com.ibm.ws.security.audit.source.AuditServiceImpl.sendEvent(AuditServiceImpl.java:483)
	at com.ibm.ws.request.probe.audit.servlet.AuditPE.auditEventJMXMBeanRegister01(AuditPE.java:648)
	at com.ibm.ws.request.probe.audit.servlet.AuditPE.processCounter(AuditPE.java:184)
	at com.ibm.ws.request.probe.RequestProbeService.processAllCounterProbeExtensions(RequestProbeService.java:231)
	at com.ibm.wsspi.request.probe.bci.TransformDescriptorHelper.exitHelper(TransformDescriptorHelper.java:195)
	at com.ibm.ws.security.audit.Audit.audit(Audit.java:68)
	at com.ibm.ws.security.audit.pipeline.AuditJMXPipeline.emitJMXMBeanRegisterEvent(AuditJMXPipeline.java:544)
	at com.ibm.ws.security.audit.pipeline.AuditJMXPipeline.unregisterMBean(AuditJMXPipeline.java:509)
	at com.ibm.ws.kernel.boot.jmx.internal.PlatformMBeanServer.unregisterMBean(PlatformMBeanServer.java:470)
	at com.ibm.websphere.monitor.meters.MeterCollection.lambda$MXBeanHelper$2(MeterCollection.java:149)
	at java.security.AccessController.doPrivileged(AccessController.java:738)
	at com.ibm.websphere.monitor.meters.MeterCollection.MXBeanHelper(MeterCollection.java:148)
	at com.ibm.websphere.monitor.meters.MeterCollection.remove(MeterCollection.java:194)
	at com.ibm.ws.jaxrs.monitor.JaxRsMonitorFilter.cleanApplication(JaxRsMonitorFilter.java:320)
	at com.ibm.ws.jaxrs.monitor.MonitorAppStateListener.applicationStopped(MonitorAppStateListener.java:53)
	at com.ibm.ws.container.service.state.internal.ApplicationStateManager.fireStopped(ApplicationStateManager.java:144)
	at com.ibm.ws.container.service.state.internal.StateChangeServiceImpl.fireApplicationStopped(StateChangeServiceImpl.java:65)
	at com.ibm.ws.app.manager.module.internal.SimpleDeployedAppInfoBase.uninstallApp(SimpleDeployedAppInfoBase.java:676)
	at com.ibm.ws.app.manager.war.internal.WARApplicationHandlerImpl.uninstall(WARApplicationHandlerImpl.java:81)
	at com.ibm.ws.app.manager.internal.statemachine.StopAction.execute(StopAction.java:83)
	at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.enterState(ApplicationStateMachineImpl.java:1382)
	at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.performAction(ApplicationStateMachineImpl.java:1222)
	at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.run(ApplicationStateMachineImpl.java:909)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:825)

**Steps to Reproduce**  
On a z/OS machine, with either full auditing enabled or with all JMX audit events enabled, on a system shutdown while multiple JMX events are still being processed, the buffer to save the audit events will overflow. 

**Expected behavior**  
The buffer used to store audit events should not cause an array out of bounds exception  

**Diagnostic information:**  
 - OpenLiberty Version: [e.g. 22.0.0.3+]
 - Affected feature(s) [audit-1.0]
 - Java Version: [Java version does not factor in]
 - server.xml configuration (enable audit-1.0 feature)
 - If it would be useful, upload the messages.log file found in `$WLP_OUTPUT_DIR/messages.log`

**Comment by una-tapa** [comment]
Closing this issue as the fix has been merged.
