### ISSUE TITLE
MP Config: intermittent TCK failure during undeploy

### ISSUE THREAD

**Issue by tevans78** [OpenLiberty/open-liberty#2104]
250952: Test Failure (20180202-0352): com.ibm.ws.microprofile.config12.tck.Config12TCKLauncher.launchConfig12Tck
https://wasrtc.hursley.ibm.com:9443/jazz/resource/itemName/com.ibm.team.workitem.WorkItem/250952

The RTC defect above links to a number of different builds, each of which appears to show a slightly different error. It would be a big help if the mvn process reported errors in a slightly better way, then we would have multiple separate defects rather than just one which says "mvn failed".

**Comment by tevans78** [comment]
```
Caused by: javax.enterprise.inject.spi.DeploymentException: Timeout while waiting for ApplicationMBean to reach targetState
	at org.jboss.arquillian.container.was.wlp_managed_8_5.WLPManagedContainer.waitForApplicationTargetState(WLPManagedContainer.java:831)
	at org.jboss.arquillian.container.was.wlp_managed_8_5.WLPManagedContainer.undeploy(WLPManagedContainer.java:571)
	at org.jboss.arquillian.container.impl.client.container.ContainerDeployController$4.call(ContainerDeployController.java:205)
	at org.jboss.arquillian.container.impl.client.container.ContainerDeployController$4.call(ContainerDeployController.java:185)
	at org.jboss.arquillian.container.impl.client.container.ContainerDeployController.executeOperation(ContainerDeployController.java:271)
	at org.jboss.arquillian.container.impl.client.container.ContainerDeployController.undeploy(ContainerDeployController.java:184)
```

**Comment by tevans78** [comment]
Liberty - Mac EBC 20180207-0258
```
[ERROR] Failed to execute goal on project tck.runner.tck: Could not resolve dependencies for project com.ibm.ws.microprofile.config:tck.runner.tck:jar:1.0-SNAPSHOT: The following artifacts could not be resolved: org.jboss.shrinkwrap:shrinkwrap-api:jar:1.2.6, org.testng:testng:jar:6.9.9: Could not transfer artifact org.jboss.shrinkwrap:shrinkwrap-api:jar:1.2.6 from/to central (https://repo.maven.apache.org/maven2): Connect to repo.maven.apache.org:443 [repo.maven.apache.org/151.101.60.215] failed: Connection refused (Connection refused) -> [Help 1]
```

**Comment by tevans78** [comment]
Liberty z/OS Platform Build 20180206-0228
Liberty z/OS Platform Build 20180205-0224
```
java.io.IOException: Cannot run program "mvn" (in directory "publish/tckRunner"): mvn

**Comment by tevans78** [comment]
This issue will be used for the intermittent undeploy exception. I saw it again in a recent personal build, failed 1/10 runs...
https://wasrtc.hursley.ibm.com:9443/jazz/resource/itemOid/com.ibm.team.build.BuildResult/_UA4AYBWXEeiANdIhjNYPnw
```
Results :

Failed tests: 
  EmptyValuesTest>Arquillian.arquillianAfterClass:128 » Deployment Exception whi...
```
Identical exception as above

**Comment by tevans78** [comment]
Since the update was made to the arquillian container, I don't think this has been seen again. Closing.
