### ISSUE TITLE
Test Failure: com.ibm.ws.logging_fat: testPrintStackTraceMultipleThreads

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#21223]
RTC 290678

```
junit.framework.AssertionFailedError: 2022-05-17-03:32:09:309 Expected 2500 events but found 2075 messages.
at com.ibm.ws.logging.fat.StackTraceJoinerTest.testPrintStackTraceMultipleThreads(StackTraceJoinerTest.java:337)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:199)
at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:320)
at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:173)
```

**Comment by Channyboy** [comment]
~From what the test is trying to perform (multi-threaded hits to an servlet to generate an exception), it would seem that some hits to the servlet did not go through.~

~Appears that the JVM may have run out of memory. Could decrease the amount of messages being generated.
However, where the first build break shows 2075/2500 messages were created properly, the second build break only shows 455/2500~

After discussing with with members from the Java team, this appears to be a bug with the JVM.

**Comment by Channyboy** [comment]
Eclipse Open J9 Issue opened here: https://github.com/eclipse-openj9/openj9/issues/15577

**Comment by Channyboy** [comment]
Closing this issue as there is no action our part. Issue has been opened and placed in the back-log https://github.com/eclipse-openj9/openj9/issues/15577

RTC item refers to that issue as well for tracking.
