### ISSUE TITLE
Check com.ibm.ws.session.utils.IDGeneratorImpl use of SecureRandom for checkpoint

### ISSUE THREAD

**Issue by tjwatson** [OpenLiberty/open-liberty#21233]
When using the `--at=applications` checkpoint a simple application that is deployed as a WAR will cause an instance of `com.ibm.ws.session.utils.IDGeneratorImpl` to get created with the following call stack:

```
        at com.ibm.ws.session.utils.IDGeneratorImpl.<init>(IDGeneratorImpl.java:104)
	at com.ibm.ws.session.SessionContext.createCoreSessionManager(SessionContext.java:209)
	at com.ibm.ws.session.SessionContext.<init>(SessionContext.java:157)
	at com.ibm.ws.webcontainer.session.impl.HttpSessionContextImpl.<init>(HttpSessionContextImpl.java:62)
	at com.ibm.ws.webcontainer31.session.impl.HttpSessionContext31Impl.<init>(HttpSessionContext31Impl.java:37)
	at com.ibm.ws.webcontainer31.session.impl.SessionContextRegistry31Impl.createSessionContextObject(SessionContextRegistry31Impl.java:40)
	at com.ibm.ws.webcontainer.session.impl.SessionContextRegistryImpl.createSessionContext(SessionContextRegistryImpl.java:83)
	- locked com.ibm.ws.webcontainer31.session.impl.SessionContextRegistry31Impl@189bc667
	at com.ibm.ws.webcontainer.session.impl.SessionContextRegistryImpl.getSessionContext(SessionContextRegistryImpl.java:304)
	at com.ibm.ws.webcontainer.WebContainer.getSessionContext(WebContainer.java:701)
	at com.ibm.ws.webcontainer.VirtualHost.getSessionContext(VirtualHost.java:188)
	at com.ibm.ws.webcontainer.webapp.WebGroup.getSessionContext(WebGroup.java:156)
	at com.ibm.ws.webcontainer.webapp.WebApp.createSessionContext(WebApp.java:1323)
	at com.ibm.ws.webcontainer.webapp.WebApp.commonInitializationStart(WebApp.java:1306)
	at com.ibm.ws.webcontainer.osgi.webapp.WebApp.commonInitializationStart(WebApp.java:256)
	at com.ibm.ws.webcontainer.webapp.WebApp.initialize(WebApp.java:1018)
	at com.ibm.ws.webcontainer.webapp.WebApp.initialize(WebApp.java:6685)
	- locked com.ibm.ws.webcontainer.webapp.WebApp$1@bb6ade95
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost.startWebApp(DynamicVirtualHost.java:472)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost.startWebApplication(DynamicVirtualHost.java:467)
	at com.ibm.ws.webcontainer.osgi.WebContainer.startWebApplication(WebContainer.java:1188)
	at com.ibm.ws.webcontainer.osgi.WebContainer.access$100(WebContainer.java:111)
	at com.ibm.ws.webcontainer.osgi.WebContainer$3.run(WebContainer.java:985)
	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:245)
	at java.base@11.0.16-internal/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base@11.0.16-internal/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base@11.0.16-internal/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base@11.0.16-internal/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base@11.0.16-internal/java.lang.Thread.run(Thread.java:840)
```

Investigation is needed about the state of this SecureRandom instance.  If in checkpoint state we may want to avoid seeding the SecureRandom until after restore.  It is not clear if that is possible.  Perhaps we can reseed it on restore?

**Comment by tjwatson** [comment]
This may become a non-issue.  The plan is for the JVM to handle this for us such that calls to SecureRandom instances created during checkpoint remain "securely random" on restore.

**Comment by tjwatson** [comment]
Closing this issue.  The JVM will automatically reseed this for us on restore.
