### ISSUE TITLE
Using grpc and grpcClient feature breaks other netty based services

### ISSUE THREAD

**Issue by BryanCutler** [OpenLiberty/open-liberty#21279]
**Describe the bug**  
We have a grpc based service and after adding the grpcClient feature, an existing service that also has io.netty as a dependency no longer works. The redis client fails in the classloader when creating a channel with the following error:

```
java.lang.LinkageError: loader constraint violation: when resolving method "io.netty.handler.ssl.SslContext.newEngine(Lio/netty/buffer/ByteBufAllocator;Ljava/lang/String;I)Ljavax/net/ssl/SSLEngine;" 
the class loader (instance of com/ibm/ws/classloading/internal/AppClassLoader) of the current class, org/redisson/client/handler/RedisChannelInitializer, 
and the class loader (instance of org/eclipse/osgi/internal/loader/EquinoxClassLoader) for the method's defining class, io/netty/handler/ssl/SslContext, 
have different Class objects for the type io/netty/buffer/ByteBufAllocator used in the signature
	at org.redisson.client.handler.RedisChannelInitializer.initSsl(RedisChannelInitializer.java:175)
	at org.redisson.client.handler.RedisChannelInitializer.initChannel(RedisChannelInitializer.java:75)
	at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129)
	at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112)
	at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:938)
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:609)
	at io.netty.channel.DefaultChannelPipeline.access$100(DefaultChannelPipeline.java:46)
	at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1463)
	at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1115)
	at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:650)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:514)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

I also need to create a grpcClient using a `NettyChannelBuilder` so I have enabled the third-party classloader in server.xml with:
```
<application ...>
    <classloader apiTypeVisibility="spec, ibm-api, stable, third-party"/>
</application>
```

**Steps to Reproduce**  
Steps to reproduce the bug
1. Enable grpc and grcpClient features
2. Enable third-party classloader in server.xml
3. Create a Redis client and attempt to connect

**Expected behavior**  
Existing dependencies that use netty should continue to function normally.

**Diagnostic information:**  
 - OpenLiberty Version: 22.0.0.5
 - Affected feature(s): grpc, grpcClient
 - Java Version: 8, 11
 - server.xml configuration

```
<server description="my-app">
    <featureManager>
        <feature>grpc-1.0</feature>
        <feature>grpcClient-1.0</feature>
        <feature>ssl-1.0</feature>
        <feature>localConnector-1.0</feature>
    </featureManager>

    <httpEndpoint host="*" httpPort="-1" httpsPort="9643" id="defaultHttpEndpoint">
            <httpOptions persistTimeout="2m" readTimeout="5m" writeTimeout="5m" ThrowIOEForInboundConnections="false"/>
    </httpEndpoint>

    <application context-root="/" id="my-app" location="my-app.war" name="my-app" type="war">
         <classloader apiTypeVisibility="spec, ibm-api, stable, third-party"/>
    </application>
</server>

```

**Comment by BryanCutler** [comment]
@mrsaldana do you have any recommendations to get around this problem?

**Comment by hutchig** [comment]
Apologies, I have been on vacation for 10 days.
I suspect this may be due to the line in

[https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.websphere.appserver.features/visibility/public/grpcClient-1.0/io.openliberty.grpcClient-1.0.feature#L9](https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.websphere.appserver.features/visibility/public/grpcClient-1.0/io.openliberty.grpcClient-1.0.feature#L9
)
that has
```
IBM-API-Package: \
 ...
  io.netty.handler.ssl; type="third-party", \
```
is causing the Application class loader to pick it up when you have
```
<application ...>
    <classloader apiTypeVisibility="spec, ibm-api, stable, **third-party**"/>
</application>
```
This causes the netty class used in the gRPC implementation to be on the users classpath which
can then contradict other libraries that bundle their own copy of Netty at a different version.

I will have more of an investigation to explore the best way of providing you with a solution.

**Comment by hutchig** [comment]
My investigations so far bring me to think that the io.netty.handler.ssl are exposed to Liberty applications (but require users to select to expose third-party api to apps in server.xml as you have discovered) as they form part of the gRPC API - for example your NettyChannelBuilder or for example here: https://grpc.github.io/grpc-java/javadoc/io/grpc/netty/GrpcSslContexts.html which uses the ssl package.
So in order to use GRPC apps need to load these Netty classes from Liberty. So if the apps ALSO bundle separate Netty jars either directly or transitively via another library (such as the Redis java client here) then these have to either be compatible or shadowed. I will explore futher if there is a means to make `apiTypeVisibility={third-party} more fine grained` or some other pattern to get round this.

**Comment by hutchig** [comment]
I do not believe we(Liberty) can shadow/rename the Netty packages that are part of Liberty as they are pinned by the exposed actual gRPC API that provides app portability. There is one feature (MicroProfile Reactive Messaging) that allows for the user to supply their own jar (for the Kafka java client) that is then used as part of the server implementation as a pre-requisite but this would be a odd use-case of that pattern (and which is not currently implemented or available for the gRPC-Netty dependency in Liberty so could not be an immediate fix now). I will investigate the 'scope' of the Netty classes we expose and classloader ordering but I can't see how this could avoid problems with something like Redis using a version of Netty that has an incompatible API with the Netty Liberty ships.

**Comment by hutchig** [comment]
I am currently investigating why the defining Classloader for RedisChannelInitializer (the AppClassLoader) which is the initializer for this classloading of ByteBufAllocator does not resolve the class to the same .class file as the gRPC library code does (the EquinoxClassLoader). I believe this is because ByteBufAllocator's package is not included in the [list that is exposed](https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.websphere.appserver.features/visibility/public/grpcClient-1.0/io.openliberty.grpcClient-1.0.feature#L9) on the third-party API classpath.

It would seem to me that exposing the `io.netty.handler.ssl; type="third-party", \` on to the third-party API classpath in order to enable the gRPC API elements that use `io.netty.handler.ssl` package classes is not sufficient. In order to make the third party API usable, one has to include all the packages for objects that are in the signatures of methods of any interfaces of the API used and indeed any other packages that had classes that are linked to from the exposed classes that are linked to by the applications' classes (even if those API classes are not interface classes or are supertypes etc.) - otherwise one will either get a class not found issue (if they are not present in the application classpath) or compatibility issues (if linked to and loaded from classes that have defining loaders that are 'above' the app class loader.)

It may be that we widen the number of packages on the third-party classpath.

I am not sure a solution using:
```
<enterpriseApplication location="myApp.ear" name="MyApp">
    <classloader delegation="parentLast"/>
</enterpriseApplication>
```
will help as the Equinox class loader will never delgate to the AppClassLoader.

A third possibility is to use the 'bring your own jar' pattern that the MicroProfile Reactive messaging feature uses for the Kafka client jar - but again that would need a Liberty PR to be usable. I will investigate these 3 possibilities a bit more. I favour the first one (widen the packages on the third-party list) but the set of packages will most likely will widen and widen if all gRPC API linkages are followed transitively and probably end up with a large chunk of the Netty API which I know is intentionally not included on the third-party classpath currently (so would need approval to ship).

**Comment by hutchig** [comment]
It appears that this problem turns up more generically with gRPC in non-Liberty embedded situations too: see https://github.com/grpc/grpc-java/blob/master/SECURITY.md#netty where we see "Most dependency versioning problems can be solved by using io.grpc:grpc-netty-shaded instead of io.grpc:grpc-netty, although this also limits your usage of the Netty-specific APIs. io.grpc:grpc-netty-shaded includes the proper version of Netty and netty-tcnative-boringssl-static in a way that won't conflict with other Netty usages." as linked to by https://yidongnan.github.io/grpc-spring-boot-starter/en/trouble-shooting.html

**Comment by BryanCutler** [comment]
I have tried using `io.grpc:grpc-netty-shaded` and I can build a channel with `io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder`, however when the channel is first used I get a similar classloader error:

```
Uncaught exception in the SynchronizationContext. Panic!. 
The exception is: loader constraint violation: when resolving field "STOPWATCH_SUPPLIER" the class loader (instance of com/ibm/ws/classloading/internal/AppClassLoader) of the referring class, io/grpc/internal/GrpcUtil, and the class loader (instance of org/eclipse/osgi/internal/loader/EquinoxClassLoader) for the field's resolved type, com/google/common/base/Supplier, have different Class objects for that type","exception":
"java.lang.LinkageError: loader constraint violation: when resolving field "STOPWATCH_SUPPLIER" the class loader (instance of com/ibm/ws/classloading/internal/AppClassLoader) of the referring class, io/grpc/internal/GrpcUtil,
 and the class loader (instance of org/eclipse/osgi/internal/loader/EquinoxClassLoader) for the field's resolved type, com/google/common/base/Supplier, have different Class objects for that type
	at io.grpc.netty.shaded.io.grpc.netty.NettyClientTransport.start(NettyClientTransport.java:217)
	at io.grpc.internal.ForwardingConnectionClientTransport.start(ForwardingConnectionClientTransport.java:34)
	at io.grpc.internal.ForwardingConnectionClientTransport.start(ForwardingConnectionClientTransport.java:34)
	at io.grpc.internal.InternalSubchannel.startNewTransport(InternalSubchannel.java:259)
	at io.grpc.internal.InternalSubchannel.access$400(InternalSubchannel.java:66)
	at io.grpc.internal.InternalSubchannel$2.run(InternalSubchannel.java:201)
	at io.grpc.SynchronizationContext.drain(SynchronizationContext.java:95)
	at io.grpc.SynchronizationContext.execute(SynchronizationContext.java:127)
	at io.grpc.internal.ManagedChannelImpl$RealChannel.newCall(ManagedChannelImpl.java:1012)
	at io.grpc.census.CensusTracingModule$TracingClientInterceptor.interceptCall(CensusTracingModule.java:417)
	at io.grpc.ClientInterceptors$InterceptorChannel.newCall(ClientInterceptors.java:156)
	at io.grpc.census.CensusStatsModule$StatsClientInterceptor.interceptCall(CensusStatsModule.java:793)
	at io.grpc.ClientInterceptors$InterceptorChannel.newCall(ClientInterceptors.java:156)
	at io.grpc.internal.ManagedChannelImpl.newCall(ManagedChannelImpl.java:923)
	at io.grpc.internal.ForwardingManagedChannel.newCall(ForwardingManagedChannel.java:63)
	at org.apache.arrow.flight.auth.ClientAuthInterceptor.interceptCall(ClientAuthInterceptor.java:48)
	at io.grpc.ClientInterceptors$InterceptorChannel.newCall(ClientInterceptors.java:156)
	at org.apache.arrow.flight.grpc.ClientInterceptorAdapter.interceptCall(ClientInterceptorAdapter.java:73)
	at io.grpc.ClientInterceptors$InterceptorChannel.newCall(ClientInterceptors.java:156)
	at org.apache.arrow.flight.impl.FlightServiceGrpc$FlightServiceStub.handshake(FlightServiceGrpc.java:586)
	at org.apache.arrow.flight.auth.ClientAuthWrapper.doClientAuth(ClientAuthWrapper.java:50)
	at org.apache.arrow.flight.FlightClient.authenticate(FlightClient.java:183)
```

I am using Guava version 30.1-jre in my app, which I believe is the same as Liberty

**Comment by hutchig** [comment]
I will expand the set of packages on the third party classpath to see if I can get a set that fixes this issue. I am aware that it might be that for some patterns of usage 'splitting' the location Netty classes are loaded from (and thus, in this case their classloader) is always going to lead to problems. I will also investigate more some sort of a 'container' or 'bring-your-own-netty' switch/pattern.

**Comment by BryanCutler** [comment]
Thanks @hutchig , if you have a potential fix I would be happy to try it out on my own application as well. Also, what is the recommendation regarding the grpc and netty dependencies. Currently, we are using grpc as "provided" by Liberty, so we exclude all grpc dependencies. For netty, we have been bundling the libraries with our application so please let me know if we should change that, or if that will be different with your fix.

**Comment by hutchig** [comment]
A simple statement of the particular problem:

_An application class calls a method on an object where that
object comes from the Liberty third-party classpath but the
class for one of the parameters does not._

So we  currently have two packages that Liberty's grpc puts on the third party classpath:
{io.netty.handler.ssl, io.grpc.netty}

So to remove this specific pattern of problem would mean exporting on the thirdparty classpath, the packages of(as that is the level of granularity we have),  all the public methods parameter types
from Liberty for those packages, which would be for the public methods of:

io.grpc.netty:

AbstractHttp2Headers.java
AbstractNettyHandler.java
CancelClientStreamCommand.java
CancelServerStreamCommand.java
ClientTransportLifecycleManager.java
CreateStreamCommand.java
FixedKeyManagerFactory.java
FixedTrustManagerFactory.java
ForcefulCloseCommand.java
GracefulCloseCommand.java
GracefulServerCloseCommand.java
GrpcHttp2ConnectionHandler.java
GrpcHttp2HeadersUtils.java
GrpcHttp2OutboundHeaders.java
GrpcSslContexts.java
Http2ControlFrameLimitEncoder.java
InsecureFromHttp1ChannelCredentials.java
InternalGracefulServerCloseCommand.java
InternalNettyChannelBuilder.java
InternalNettyChannelCredentials.java
InternalNettyServerBuilder.java
InternalNettyServerCredentials.java
InternalNettySocketSupport.java
InternalProtocolNegotiationEvent.java
InternalProtocolNegotiator.java
InternalProtocolNegotiators.java
InternalWriteBufferingAndExceptionHandlerUtils.java
JettyTlsUtil.java
KeepAliveEnforcer.java
MaxConnectionIdleManager.java
NegotiationType.java
NettyChannelBuilder.java
NettyChannelCredentials.java
NettyChannelProvider.java
NettyClientHandler.java
NettyClientStream.java
NettyClientTransport.java
NettyReadableBuffer.java
NettyServer.java
NettyServerBuilder.java
NettyServerCredentials.java
NettyServerHandler.java
NettyServerProvider.java
NettyServerStream.java
NettyServerTransport.java
NettySocketSupport.java
NettySslContextChannelCredentials.java
NettySslContextServerCredentials.java
NettyWritableBuffer.java
NettyWritableBufferAllocator.java
ProtocolNegotiationEvent.java
ProtocolNegotiator.java
ProtocolNegotiators.java
SendGrpcFrameCommand.java
SendPingCommand.java
SendResponseHeadersCommand.java
StreamIdHolder.java
UdsNameResolver.java
UdsNameResolverProvider.java
UdsNettyChannelProvider.java
UnhelpfulSecurityProvider.java
Utils.java
WriteBufferingAndExceptionHandler.java
WriteQueue.java

and
io.netty.handler.ssl:

AbstractSniHandler.java
ApplicationProtocolAccessor.java
ApplicationProtocolConfig.java
ApplicationProtocolNames.java
ApplicationProtocolNegotiationHandler.java
ApplicationProtocolNegotiator.java
ApplicationProtocolUtil.java
AsyncRunnable.java
BouncyCastle.java
BouncyCastleAlpnSslEngine.java
BouncyCastleAlpnSslUtils.java
CipherSuiteConverter.java
CipherSuiteFilter.java
Ciphers.java
ClientAuth.java
Conscrypt.java
ConscryptAlpnSslEngine.java
DefaultOpenSslKeyMaterial.java
DelegatingSslContext.java
ExtendedOpenSslSession.java
GroupsConverter.java
IdentityCipherSuiteFilter.java
Java7SslParametersUtils.java
Java8SslUtils.java
JdkAlpnApplicationProtocolNegotiator.java
JdkAlpnSslEngine.java
JdkAlpnSslUtils.java
JdkApplicationProtocolNegotiator.java
JdkBaseApplicationProtocolNegotiator.java
JdkDefaultApplicationProtocolNegotiator.java
JdkNpnApplicationProtocolNegotiator.java
JdkSslClientContext.java
JdkSslContext.java
JdkSslEngine.java
JdkSslServerContext.java
JettyAlpnSslEngine.java
JettyNpnSslEngine.java
NotSslRecordException.java
OpenSsl.java
OpenSslApplicationProtocolNegotiator.java
OpenSslAsyncPrivateKeyMethod.java
OpenSslCachingKeyMaterialProvider.java
OpenSslCachingX509KeyManagerFactory.java
OpenSslCertificateCompressionAlgorithm.java
OpenSslCertificateCompressionConfig.java
OpenSslCertificateException.java
OpenSslClientContext.java
OpenSslClientSessionCache.java
OpenSslContext.java
OpenSslContextOption.java
OpenSslDefaultApplicationProtocolNegotiator.java
OpenSslEngine.java
OpenSslEngineMap.java
OpenSslKeyMaterial.java
OpenSslKeyMaterialManager.java
OpenSslKeyMaterialProvider.java
OpenSslNpnApplicationProtocolNegotiator.java
OpenSslPrivateKey.java
OpenSslPrivateKeyMethod.java
OpenSslServerContext.java
OpenSslServerSessionContext.java
OpenSslSession.java
OpenSslSessionCache.java
OpenSslSessionContext.java
OpenSslSessionId.java
OpenSslSessionStats.java
OpenSslSessionTicketKey.java
OpenSslX509KeyManagerFactory.java
OpenSslX509TrustManagerWrapper.java
OptionalSslHandler.java
PemEncoded.java
PemPrivateKey.java
PemReader.java
PemValue.java
PemX509Certificate.java
PseudoRandomFunction.java
ReferenceCountedOpenSslClientContext.java
ReferenceCountedOpenSslContext.java
ReferenceCountedOpenSslEngine.java
ReferenceCountedOpenSslServerContext.java
SignatureAlgorithmConverter.java
SniCompletionEvent.java
SniHandler.java
SslClientHelloHandler.java
SslCloseCompletionEvent.java
SslClosedEngineException.java
SslCompletionEvent.java
SslContext.java
SslContextBuilder.java
SslContextOption.java
SslHandler.java
SslHandshakeCompletionEvent.java
SslHandshakeTimeoutException.java
SslMasterKeyHandler.java
SslProtocols.java
SslProvider.java
SslUtils.java
SupportedCipherSuiteFilter.java

We would then have to repeat the exercise for all the additional packages' classes', newly on the third-party classpath, public methods' parameters and so on until the list of packages stopped growing.

Let me think a bit more. Any opinions/ideas welcome.

**Comment by hutchig** [comment]
So I think the only sensible way forward for this is for either:

1. It is a 'restriction'. (i.e. 'don't bundle your own version of Netty in applications that want to use gRPC as it will clash with the partially exposed version that is used to implement gRPC) - this is where we are now.
2. Implement a feature like: https://www.ibm.com/docs/en/was-liberty/base?topic=23-configuring-third-party-javaserver-faces-implementations so that the internal gRPC implementation can be switched to use an externally provided netty.
3. Also technically feasible is for Liberty to expose 100% of the netty classes but then that might not suit libraries like Redis which are pre-packaged .

2 and 3 are sort of symmetrical as the Redis or application provided version could be problematic for maintenance etc or compatibility with the gRPC implementation.

I will look into how https://www.ibm.com/docs/en/was-liberty/base?topic=23-configuring-third-party-javaserver-faces-implementations works and how feasible it is (technically and with some senior colleagues.)

https://openliberty.io/docs/latest/reference/feature/jpaContainer-2.1.html is another example.

**Comment by BryanCutler** [comment]
Quick update @hutchig , I was able to workaround this issue by shading the Redis library along with the Netty that it depends on. It's not an ideal solution, so hopefully there is still some way to work this out with Liberty. From the options above, it seems like 2 would be the best since I could use the Netty version required by my app. I'm not quite sure how that would work though. Would that entail a change in Liberty or just an additional feature that I could install?

**Comment by hutchig** [comment]
I am very glad to here that @BryanCutler. I raised this issue in the 'design issues' meeting using #21627 last week. They did not have any other way forward than 2 above (so it is a limitation for now as this needs a new feature). Where it was left was:

-  find out if there is a workaround and where you got to now
-  find out the design/sizing of option 2
-  determine how many customers are hitting this to help prioritize it appropriately

So for now, apologies, this is a limitation.

The solution in 2 above is that the Netty classes come 100% from the user and is implemented using the
Liberty 'bell' mechanism (https://www.ibm.com/docs/en/was-liberty/zos?topic=features-basic-extensions-using-liberty-libraries-10) to wrap round the applications (Netty) library and make it available to the app servers internal
classes. It does mean that the Netty version used has to work for the two sets of classes involved (the server's grpc impl code and the app's code)
