### ISSUE TITLE
com.ibm.ws.monitor_fat Failure: Monitor Feature Failed to get right CPU from JVM MXBean

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#21357]
RTC 289890

Java 8 Semeru run failed with:
```
junit.framework.AssertionFailedError: 2022-03-22-21:39:47:383 Monitor Feature Failed to get right CPU from JVM MXBean
at com.ibm.ws.monitor.fat.FATTest.testVerifyProcessCPU(FATTest.java:306)
at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:197)
at componenttest.rules.repeater.RepeatTests$CompositeRepeatTestActionStatement.evaluate(RepeatTests.java:115)
at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:318)
at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:171)
```

**Comment by fmhwong** [comment]
This should be opened in WebSphere Liberty
