### ISSUE TITLE
ejbRemote-3.2 InaccessibleObjectException with Java 17

### ISSUE THREAD

**Issue by braetkuegeli** [OpenLiberty/open-liberty#21570]
**InaccessibleObjectException: module java.base does not "opens java.math"**  

An ejb with a method returning a BigInteger is failing with java 17:
```
javax.ejb.EJBException: nested exception is: java.rmi.RemoteException: CORBA INTERNAL 0 No; nested exception is: org.omg.CORBA.INTERNAL: : vmcid: 0x0 minor code: 0x0 completed: No
at io.openliberty.sample.ejb._SampleBean_Stub.getIntValue(_SampleBean_Stub.java:1101)
at io.openliberty.sample.ejb.SampleServlet.doGet(SampleServlet.java:19)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:686)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:791)
at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1258)
at [internal classes]
Caused by: java.rmi.RemoteException: CORBA INTERNAL 0 No; nested exception is: org.omg.CORBA.INTERNAL: : vmcid: 0x0 minor code: 0x0 completed: No
at org.apache.yoko.rmi.impl.UtilImpl.createRemoteException(UtilImpl.java:206)
at [internal classes]
at javax.rmi.CORBA.Util.mapSystemException(Util.java:84)
at io.openliberty.sample.ejb._SampleBean_Stub.getIntValue(_SampleBean_Stub.java:1)
... 5 more
Caused by: org.omg.CORBA.INTERNAL:
at org.apache.yoko.rmi.impl.ValueDescriptor$$Lambda$448/0x0000000000000000.get(Unknown Source)
at [internal classes]
at io.openliberty.sample.ejb._EJSRemote0SLTestBean_9055b929_Tie._get_intValue(_EJSRemote0SLTestBean_9055b929_Tie.java:2)
at io.openliberty.sample.ejb._EJSRemote0SLTestBean_9055b929_Tie._invoke(_EJSRemote0SLTestBean_9055b929_Tie.java)
at org.apache.yoko.orb.OBPortableServer.ServantDispatcher.dispatch(ServantDispatcher.java:189)
... 1 more
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make private void java.math.BigInteger.readObject(java.io.ObjectInputStream) throws java.io.IOException,java.lang.ClassNotFoundException accessible: module java.base does not "opens java.math" to unnamed module @89248e26
at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
at org.apache.yoko.rmi.impl.ValueDescriptor$1.run(ValueDescriptor.java:214)
... 5 more
```
**Steps to Reproduce**  

1. git clone https://github.com/OpenLiberty/sample-getting-started.git
2. cd sample-getting-started
3. Apply attached patch-file (git am < 0001-RemoteEjb-with-java17-bug.patch.txt)
4. in pom.xml change property liberty.env.JAVA_HOME to an Jdk17
5. mvn clean package liberty:run
6. Open http://localhost:9080/ejb

**Expected behavior**  
No exception (as with Java 8) 
http://localhost:9080/ejb should show '10'

Adding this to /liberty/wlp/lib/platform/java/**java9.options** solves the problem:

```
--add-opens
java.base/java.math=ALL-UNNAMED
```

**Diagnostic information:**  
 - OpenLiberty Version: 22.0.0.6
 - Affected feature(s): ejb-3.2, ejbRemote-3.2
 - Java Version: ```openjdk version "17.0.2" 2022-01-18
IBM Semeru Runtime Open Edition 17.0.2.0 (build 17.0.2+8)
Eclipse OpenJ9 VM 17.0.2.0 (build openj9-0.30.0, JRE 17 Linux amd64-64-Bit Compressed References 20220128_115 (JIT enabled, AOT enabled)
OpenJ9   - 9dccbe076
OMR      - dac962a28
JCL      - 64cd399ca28 based on jdk-17.0.2+8)```

**Additional context**  

[messages.log](https://github.com/OpenLiberty/open-liberty/files/9000186/messages.log)
[0001-RemoteEjb-with-java17-bug.patch.txt](https://github.com/OpenLiberty/open-liberty/files/9000190/0001-RemoteEjb-with-java17-bug.patch.txt)

**Comment by kiilivi** [comment]
I have a similar problem with remote EJB call. The weird thing is that it works if the server is online for a while.

Edit: In this case we use LocalDateTime in some remote EJB responses.

`Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make private java.lang.Object java.time.LocalDateTime.writeReplace() accessible: module java.base does not "opens java.time" to unnamed module @60a0a946
`
Java version:
```
openjdk 17.0.7 2023-04-18 LTS
OpenJDK Runtime Environment Zulu17.42+19-CA (build 17.0.7+7-LTS)
OpenJDK 64-Bit Server VM Zulu17.42+19-CA (build 17.0.7+7-LTS, mixed mode, sharing)
```

**Comment by tkburroughs** [comment]
@joe-chacko @ngmr Is there a solution to this in yoko? or is the expectation that adding `opens` will be required?
