### ISSUE TITLE
java.lang.IllegalStateException: Subject is read-only from WebAppFilterManager.invokeFilters

### ISSUE THREAD

**Issue by una-tapa** [OpenLiberty/open-liberty#21666]
**Describe the bug**  
An FFDC Incident has been created: "java.lang.IllegalStateException: Subject is read-only com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters 1105" 

```
------Start of DE processing------ = [6/15/22 7:44:02:615 EDT]
Exception = java.lang.IllegalStateException
Source = com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters
probeid = 1105
Stack Dump = java.lang.IllegalStateException: Subject is read-only
	at javax.security.auth.Subject$SecureSet$1.remove(Subject.java:1297)
	at javax.security.auth.Subject$SecureSet.remove(Subject.java:1386)
	at java.util.Collections$SynchronizedCollection.remove(Collections.java:2051)
	at com.ibm.ws.webcontainer.security.WebProviderAuthenticatorHelper.removeSecurityNameAndUniquedIdFromHashtable(WebProviderAuthenticatorHelper.java:142)
	at com.ibm.ws.webcontainer.security.WebProviderAuthenticatorHelper.loginWithUserName(WebProviderAuthenticatorHelper.java:77)
	at com.ibm.ws.webcontainer.security.WebProviderAuthenticatorProxy.handleOidcClient(WebProviderAuthenticatorProxy.java:631)
```

**Steps to Reproduce**  
This is intermittent issue depending on the scenario 

**Expected behavior**  
No Exception 

**Diagnostic information:**  
 - OpenLiberty Version: 21.0.0.10
 - Affected feature(s) appSecurity-x.0 
 - Java Version: Any 
 - 
**Additional context**  

The same symptom as [the issue 17489](https://github.com/OpenLiberty/open-liberty/issues/17489)
Fixed by https://github.com/OpenLiberty/open-liberty/pull/21790

**Comment by una-tapa** [comment]
Retrying with  https://github.com/OpenLiberty/open-liberty/pull/21790
