### ISSUE TITLE
featureUpdate downloads fail in Windows, due to #20945

### ISSUE THREAD

**Issue by barulheira** [OpenLiberty/open-liberty#21664]
**Describe the bug**  
Cannot connect to Maven repo on Windows due to changes made in #20945. Need to append backsplash instead of File.separator for urls. 

**Steps to Reproduce**  
featureUtility.exe installFeature <feature> or featureUtility.exe installServerFeature <server>
..
The remote repository "https://repo.maven.apache.org/maven2/\" is missing the following artifacts: [json-1.0-22.0.0.7.pom, json-1.0-22.0.0.7.esa]
[7/27/22, 11:31:52:318 PDT] Downloading required features ...
[7/27/22, 11:31:52:334 PDT] Starting installation ...
[7/27/22, 11:31:52:365 PDT] Successfully completed cleaning up temporary files.
<---------------------> Infinity%
java.lang.NullPointerException
        at com.ibm.ws.install.featureUtility.FeatureUtility.installFeatures(FeatureUtility.java:483)
        at com.ibm.ws.install.featureUtility.cli.InstallFeatureAction.install(InstallFeatureAction.java:241)
        at com.ibm.ws.install.featureUtility.cli.InstallFeatureAction.execute(InstallFeatureAction.java:257)
        at com.ibm.ws.install.featureUtility.cli.InstallFeatureAction.handleTask(InstallFeatureAction.java:78)
        at com.ibm.ws.install.featureUtility.cli.FeatureAction.handleTask(FeatureAction.java:100)
        at com.ibm.ws.install.featureUtility.FeatureUtilityExecutor.main(FeatureUtilityExecutor.java:58)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.ibm.ws.kernel.boot.cmdline.UtilityMain.internal_main(UtilityMain.java:173)
        at com.ibm.ws.kernel.boot.cmdline.UtilityMain.main(UtilityMain.java:53)
        at com.ibm.ws.kernel.boot.cmdline.Main.main(Main.java:52) 

**Expected behavior**  
Features install successfully.

**Diagnostic information:**  
 - OpenLiberty Version: [22.0.0.7]
 - 
**Additional context**

**Comment by jjiwooLim** [comment]
Hello, https://github.com/OpenLiberty/open-liberty/pull/21667 will revert it back to forward slash. Once our internal build finishes, I will merge it in. Thank you

**Comment by mbroz2** [comment]
@jjiwooLim please update the description of this `relesae bug` using the [bug report template](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=&labels=release+bug&template=bug_report.md&title=)
