### ISSUE TITLE
Rework the Sip Log Extension

### ISSUE THREAD

**Issue by volosied** [OpenLiberty/open-liberty#21770]
Follow PR https://github.com/OpenLiberty/open-liberty/pull/21465,  the SIP and rtcomm_connector FATs started to encounter consistent failures.  This indicates the [SipLogExtension](https://github.com/OpenLiberty/open-liberty/blob/2fd4a880754c37a988c5ed9ac4f1ea5988e465d6/dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/container/util/SipLogExtension.java) needs to be reworked.  Additionally, numerous  sip sessions are created. 

Stack traces of errors: 

```
Stack Dump = java.lang.IllegalStateException: Invalid Session: Id = wlp_53 Info = com.ibm.ws.sip.container.servlets.WASXSipApplicationSessionImpl@b71a52cc
	at com.ibm.ws.sip.container.servlets.SipApplicationSessionImpl.checkIsSessionValid(SipApplicationSessionImpl.java:1302)
	at com.ibm.ws.sip.container.servlets.SipApplicationSessionImpl.getSessions(SipApplicationSessionImpl.java:700)
	at com.ibm.ws.sip.container.servlets.WASXSipApplicationSessionImpl.getSessions(WASXSipApplicationSessionImpl.java:134)
	at com.ibm.ws.sip.container.util.SipLogExtension.getSecondSessionId(SipLogExtension.java:262)
	at com.ibm.ws.sip.container.util.SipLogExtension.access$400(SipLogExtension.java:35)
	at com.ibm.ws.sip.container.util.SipLogExtension$5.getValue(SipLogExtension.java:106)
	at com.ibm.websphere.logging.hpel.LogRecordContext.getExtensions(LogRecordContext.java:308)
	at com.ibm.ws.logging.internal.WsLogRecord.createWsLogRecord(WsLogRecord.java:531)
	at com.ibm.ws.logging.internal.impl.BaseTraceService.exit(BaseTraceService.java:887)
	at com.ibm.websphere.ras.Tr.exit(Tr.java:716)
	at com.ibm.sip.util.log.LogMgr.traceExit(LogMgr.java:200)
	at com.ibm.ws.sip.container.was.ContextBasedQueue.recordThreadID(ContextBasedQueue.java:373)
	at com.ibm.ws.sip.container.was.SignalingEndOfTask.run(SignalingEndOfTask.java:72)
	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:245)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:866)
```

```
 Exception in thread "Default Executor-thread-33" 
 java.lang.NullPointerException
 	at com.ibm.ws.sip.container.tu.TransactionUserBase.setHandler(TransactionUserBase.java:901)
 	at com.ibm.ws.sip.container.tu.TransactionUserWrapper.setHandler(TransactionUserWrapper.java:1198)
 	at com.ibm.ws.sip.container.servlets.SipSessionImplementation.setHandler(SipSessionImplementation.java:845)
 	at com.ibm.ws.sip.container.servlets.SipSessionImplementation.init(SipSessionImplementation.java:217)
 	at com.ibm.ws.sip.container.servlets.SipSessionImplementation.<init>(SipSessionImplementation.java:157)
 	at com.ibm.ws.sip.container.servlets.SIPSessionFactory.createSIPSession(SIPSessionFactory.java:44)
 	at com.ibm.ws.sip.container.tu.TransactionUserBase.getSipSession(TransactionUserBase.java:937)
 	at com.ibm.ws.sip.container.tu.TransactionUserBase.getAllSipSessions(TransactionUserBase.java:615)
 	at com.ibm.ws.sip.container.tu.TransactionUserWrapper.getAllSipSessions(TransactionUserWrapper.java:1425)
 	at com.ibm.ws.sip.container.servlets.SipApplicationSessionImpl.getAllSIPSessions(SipApplicationSessionImpl.java:681)
 	at com.ibm.ws.sip.container.servlets.SipApplicationSessionImpl.getAllSIPSessions(SipApplicationSessionImpl.java:652)
 	at com.ibm.ws.sip.container.servlets.SipApplicationSessionImpl.getSessions(SipApplicationSessionImpl.java:708)
 	at com.ibm.ws.sip.container.servlets.WASXSipApplicationSessionImpl.getSessions(WASXSipApplicationSessionImpl.java:134)
 	at com.ibm.ws.sip.container.util.SipLogExtension.getSecondSessionId(SipLogExtension.java:262)
 	at com.ibm.ws.sip.container.util.SipLogExtension.access$400(SipLogExtension.java:35)
 	at com.ibm.ws.sip.container.util.SipLogExtension$5.getValue(SipLogExtension.java:106)
 	at com.ibm.websphere.logging.hpel.LogRecordContext.getExtensions(LogRecordContext.java:308)
 	at com.ibm.ws.logging.internal.WsLogRecord.createWsLogRecord(WsLogRecord.java:531)
 	at com.ibm.ws.logging.internal.impl.BaseTraceService.error(BaseTraceService.java:806)
 	at com.ibm.websphere.ras.Tr.error(Tr.java:629)
 	at com.ibm.sip.util.log.LogMgr.error(LogMgr.java:297)
 	at com.ibm.ws.sip.container.was.SignalingEndOfTask.run(SignalingEndOfTask.java:93)
 	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:245)
 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
 	at java.base/java.lang.Thread.run(Thread.java:866)
```

**Comment by volosied** [comment]
https://www.ibm.com/docs/en/was-liberty/core?topic=SSD28V_liberty/com.ibm.websphere.javadoc.liberty.doc/com.ibm.websphere.appserver.api.hpel_2.0-javadoc/com/ibm/websphere/logging/hpel/LogRecordContext.html

**Comment by volosied** [comment]
Sip Docs regarding the extension: https://www.ibm.com/docs/en/was-liberty/base?topic=liberty-sip-binary-log-trace-extensions
