### ISSUE TITLE
Test Failure (20180112-0701): ConcurrentRxTestServlet.testNoNewMethods expected 104 but was 117

### ISSUE THREAD

**Issue by njr-11** [OpenLiberty/open-liberty#2181]
A test case that we wrote to identify when new methods are added to CompletableFuture (which need to be properly accounted for in code) has raised an error in the Java 9 builds letting us know that Java 9 has added 13 new methods to CompletableFuture that will need to be investigated and added to our implementation:

public CompletableFuture<T> completeAsync​(Supplier<? extends T> supplier)
public CompletableFuture<T> completeAsync​(Supplier<? extends T> supplier, Executor executor)
public CompletableFuture<T> completeOnTimeout​(T value, long timeout, TimeUnit unit)
public CompletableFuture<T> copy​()
public Executor defaultExecutor​()
public CompletionStage<T> minimalCompletionStage​()
public <U> CompletableFuture<U> newIncompleteFuture​()
public CompletableFuture<T> orTimeout​(long timeout, TimeUnit unit)

public static <U> CompletionStage<U> completedStage​(U value)
public static Executor delayedExecutor​(long delay, TimeUnit unit)
public static Executor delayedExecutor​(long delay, TimeUnit unit, Executor executor)
public static <U> CompletableFuture<U> failedFuture​(Throwable ex)
public static <U> CompletionStage<U> failedStage​(Throwable ex)

For reference, here is how the test case reports it:
junit.framework.AssertionFailedError: 2018-01-12-22:40:07:689 The response did not contain [SUCCESS].  Full output is:
	ERROR: Caught exception attempting to call test method testNoNewMethods on servlet web.ConcurrentRxTestServlet
	java.lang.AssertionError: Methods have been added to CompletableFuture which need to be properly implemented on wrapper class ManagedCompletableFuture expected:<104> but was:<117>
	at web.ConcurrentRxTestServlet.testNoNewMethods(ConcurrentRxTestServlet.java:1554)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@9-internal/Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@9-internal/NativeMethodAccessorImpl.java:62)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@9-internal/DelegatingMethodAccessorImpl.java:43)
	at componenttest.app.FATServlet.doGet(FATServlet.java:71)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:686)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:791)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1255)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:743)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:440)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1154)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1004)
	at com.ibm.ws.webcontainer.servlet.CacheServletWrapper.handleRequest(CacheServletWrapper.java:76)
	at com.ibm.ws.webcontainer40.servlet.CacheServletWrapper40.handleRequest(CacheServletWrapper40.java:83)
	at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:926)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:279)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:989)
	at com.ibm.ws.http.dispatcher.internal.ch

**Comment by njr-11** [comment]
It turns out that JAX-RS expert group has taken the very unusual interpretation that javax.ws.rs.client.ClientBuilder.executorService will only be used for executing asynchronous tasks that are the initial CompletionStage created by reactive client, not for executing asynchronous tasks that run the subsequent async stages of that stage.  And not only this, that it would be wrong to expect the executor to be used to run the async stages.  Thus, managed completable future cannot be used for JAX-RS 2.1, and it would be advantageous for us to wait until Java 9+ where a more optimal implementation of managed completable future could be written relying up on the defaultExecutor/newIncompleteFuture plugin points.

For now, the test case having served its purpose to notify us of the addition of new methods, I'll update the test case to expect the new method count and add some notes to ManagedCompletableFuture indicating that it should be rebased onto Java 9 before releasing it.
