### ISSUE TITLE
Calling getJspConfigDescriptor from a programmatically added listener causes an NPE

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#21820]
This behavior was observed during the testing and development of: https://github.com/openliberty/open-liberty/issues/20428

This is not specific to the Servlet 6.0 feature. It is an existing behavior that needs investigating.

Notes:
1) enabling the `jsp-2.3` feature resolved the issue in this particular test case.
2) Test to see if an NPE is thrown outside of the context of a programmatically added listener when no Pages feature is enabled.
      `Testing with just the servlet-4.0 feature with a simple servlet calling getJspConfigDescriptors with no web.xml the NPE occurs. Enabling the jsp feature I get a null return value as expected since there is no jspConfig within the web.xml`

3) Update code to avoid an NPE when no Pages feature is enabled. Review specification / API documents to ensure our behavior is correct.
4) Add new test cases to ensure an NPE is not occurring.
5) Update existing tests to remove the `jsp-2.3` feature when it isn't necessary.

Link to API: https://jakarta.ee/specifications/servlet/6.0/apidocs/jakarta.servlet/jakarta/servlet/servletcontext#getJspConfigDescriptor()

**Comment by pnicolucci** [comment]
[ffdc_22.07.20_08.01.32.0.log](https://github.com/OpenLiberty/open-liberty/files/9151660/ffdc_22.07.20_08.01.32.0.log)

```
Stack Dump = java.lang.NullPointerException
	at <unknown class>.<init>(JspConfigDescriptorImpl.java:39)
	at <unknown class>.getJspConfigDescriptor(WebApp.java:6628)
	at <unknown class>.getJspConfigDescriptor(ServletContextFacade.java:667)
	at <unknown class>.contextInitialized(MyProgrammaticServletContextListener.java:107)
	at <unknown class>.notifyServletContextCreated(WebApp.java:2447)
	at <unknown class>.notifyServletContextCreated(WebApp31.java:517)
	at <unknown class>.initialize(WebApp.java:1045)
	at <unknown class>.initialize(WebApp.java:6685)
	at <unknown class>.startWebApp(DynamicVirtualHost.java:472)
	at <unknown class>.startWebApplication(DynamicVirtualHost.java:467)
	at <unknown class>.startWebApplication(WebContainer.java:1188)
	at <unknown class>.access$100(WebContainer.java:111)
	at <unknown class>.run(WebContainer.java:985)
	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:245)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:866)
	```
