### ISSUE TITLE
featureUtility - Not decoding repository passwords when executing

### ISSUE THREAD

**Issue by veenarm** [OpenLiberty/open-liberty#21845]
**Describe the bug**  
When executing the featureUtility on `kernel-slim` images when ever we set overrides for the mavenCentralMirror or a secondary repository and we use the securityUtility to {xors}, {hash} or {aes} encode the passwords, authentication is failing to those end servers with http 401 forbidden. Replace it with the actual passwords in `plain text` and it works again.

**Steps to Reproduce**  
- Configure a on-prem or personal extra mirror  or override mavenCentralMirror
- Use securityUtils to {xors}, {hash} or {aes} encode your password configuration
- Execute featureUtils install (server or any normal install of features)

**Expected behavior**  
Expected that securityUtility encoded/hashed passwords suffice in the MavenRepository passwords.

**Diagnostic information:**  
 - OpenLiberty Version: [e.g. 21.0.0.12 - 22.0.0.6]
 - Affected feature(s) [Features not specific]
 - Java Version: OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
 - server.xml configuration (not needed to test issue)

**Additional context**  
The OpenLiberty documentation listed here: https://openliberty.io/docs/latest/reference/command/featureUtility-modifications.html
Shows that the repo2 password is {xor} hashed, thus why we think this is a bug.

``` 
[25/7/22, 20:23:02:272 AEST] Testing connection for repository: http://myreposerver/repository/maven-central/
[25/7/22, 20:23:02:403 AEST] Response code: 401
[25/7/22, 20:23:02:403 AEST] Connecting to the following repository: http://myreposerver/repository/maven-central/
[25/7/22, 20:23:02:525 AEST] CWWKF1392E: Incorrect credentials were provided for the http://myreposerver/repository/maven-central/ repository.
[25/7/22, 20:23:02:526 AEST] Could not download this json with maven coordinate: io.openliberty.features:features:21.0.0.12
[25/7/22, 20:23:02:526 AEST] Downloaded the following json files from remote: []
[25/7/22, 20:23:02:527 AEST] action.exception.stacktrace: null
[25/7/22, 20:23:02:527 AEST] CWWKF1409E: Unable to find the following feature JSON files locally or on the configured Maven repository: [io.openliberty.features:features:21.0.0.12].
com.ibm.ws.install.InstallException: CWWKF1409E: Unable to find the following feature JSON files locally or on the configured Maven repository: [io.openliberty.features:features:21.0.0.12].
        at com.ibm.ws.install.featureUtility.FeatureUtility.getJsonFiles(FeatureUtility.java:656)
        at com.ibm.ws.install.featureUtility.FeatureUtility.<init>(FeatureUtility.java:164)
        at com.ibm.ws.install.featureUtility.FeatureUtility.<init>(FeatureUtility.java:58)
        at com.ibm.ws.install.featureUtility.FeatureUtility$FeatureUtilityBuilder.build(FeatureUtility.java:792)
        at com.ibm.ws.install.featureUtility.cli.InstallServerAction.install(InstallServerAction.java:259)
        at com.ibm.ws.install.featureUtility.cli.InstallServerAction.execute(InstallServerAction.java:283)
        at com.ibm.ws.install.featureUtility.cli.InstallServerAction.handleTask(InstallServerAction.java:78)
        at com.ibm.ws.install.featureUtility.cli.FeatureAction.handleTask(FeatureAction.java:100)
        at com.ibm.ws.install.featureUtility.FeatureUtilityExecutor.main(FeatureUtilityExecutor.java:58)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.ibm.ws.kernel.boot.cmdline.UtilityMain.internal_main(UtilityMain.java:173)
        at com.ibm.ws.kernel.boot.cmdline.UtilityMain.main(UtilityMain.java:53)
        at com.ibm.ws.kernel.boot.cmdline.Main.main(Main.java:52)
```

I believe this can be resolved in the `ArtifactDownloader.java` class where it pulls out the password and use the `PasswordUtils.decode()` function before it - I may attempt to do a PR for this.

**Comment by NottyCode** [comment]
It wouldn't be possible to use a hashed password in this use case since a hashed password cannot be reversed into the actual password for the maven repository.

**Comment by veenarm** [comment]
The `securityUtility encoded passwords`, not random hashed passwords.
