### ISSUE TITLE
Test Failure: com.ibm.ws.request.probe.jdbc.fat.RequestProbeJDBCUnRegTDTest.testAllJdbcTDsUnRegistered

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#21865]
RTC 291276

```
testAllJdbcTDsUnRegistered:java.lang.Exception: 2022-06-18-16:44:02:634 Errors/warnings were found in server JDBCServer logs:
<br>[6/18/22, 16:43:54:367 PDT] 00000024 com.ibm.ws.request.timing.manager.SlowRequestManager         W TRAS0112W: Request AAAKYzZ2CS0_AAAAAAAAAAA has been running on thread 00000031 for at least 10050.429ms. The following stack trace shows what this thread is currently running.
at componenttest.topology.impl.LibertyServer.checkLogsForErrorsAndWarnings(LibertyServer.java:3006)
at componenttest.topology.impl.LibertyServer.stopServer(LibertyServer.java:2864)
at componenttest.topology.impl.LibertyServer.stopServer(LibertyServer.java:2747)
at componenttest.topology.impl.LibertyServer.stopServer(LibertyServer.java:2656)
at componenttest.topology.impl.LibertyServer.stopServer(LibertyServer.java:2631)
at com.ibm.ws.request.probe.jdbc.fat.RequestProbeJDBCUnRegTDTest.tearDown(RequestProbeJDBCUnRegTDTest.java:133)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:199)
at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:320)
at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:173)

```

**Comment by fmhwong** [comment]
This looks like a Windows only issue.
