### ISSUE TITLE
CDI: com.ibm.ws.fat.cdi.tests.CdiWabServerTest should not be run against EE8

### ISSUE THREAD

**Issue by tevans78** [OpenLiberty/open-liberty#2205]
WABs are not supported on EE8

java.lang.Exception: Errors/warnings were found in server cdiWABServer logs:
 <br>[1/16/18 10:25:33:770 UTC] 00000014 LogService-28-com.ibm.ws.jsp                                 E CWWKE0702E: Could not resolve module: com.ibm.ws.jsp [28]
 <br>[1/16/18 10:25:33:775 UTC] 00000014 LogService-31-com.ibm.ws.jsp.2.3                             E CWWKE0702E: Could not resolve module: com.ibm.ws.jsp.2.3 [31]
 <br>[1/16/18 10:25:33:799 UTC] 00000014 LogService-32-com.ibm.ws.jsp.jstl.facade                     E CWWKE0702E: Could not resolve module: com.ibm.ws.jsp.jstl.facade [32]
 <br>[1/16/18 10:25:38:063 UTC] 00000014 LogService-124-com.ibm.ws.app.manager.wab                    E CWWKE0702E: Could not resolve module: com.ibm.ws.app.manager.wab [124]
	at componenttest.topology.impl.LibertyServer.checkLogsForErrorsAndWarnings(LibertyServer.java:2358)
	at componenttest.topology.impl.LibertyServer.stopServer(LibertyServer.java:2245)
	at componenttest.topology.impl.LibertyServer.stopServer(LibertyServer.java:2139)
	at componenttest.topology.impl.LibertyServer.stopServer(LibertyServer.java:2108)
	at componenttest.topology.impl.LibertyServer.postTestTidy(LibertyServer.java:2472)
	at componenttest.topology.impl.LibertyServerFactory.tidyAllKnownServers(LibertyServerFactory.java:338)
	at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:321)
	at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:153)

**Comment by tevans78** [comment]
oops, this should be ws-cd
