### ISSUE TITLE
Java 19: Failed com.ibm.ws.concurrent_fat_zcontext: testInterruptOnDeactivate

### ISSUE THREAD

**Issue by njr-11** [OpenLiberty/open-liberty#22073]
The following test fails on Java 19 because with Java 19 the JDK stopped invoking .start() on our ForkJoinWorkerThread implementation, which had been using the .start() notification to track threads for interruption on shutdown of the application.  The test fails because these threads were not interrupted upon application stop.

```
junit.framework.AssertionFailedError: 2022-06-19-08:58:17:376 ERROR: Caught exception attempting to call test method testInterruptOnDeactivate_waitForInterrupt on servlet test.concurrent.sim.zos.context.web.SimZOSContextTestServlet
java.util.concurrent.TimeoutException
at java.base/java.util.concurrent.ForkJoinTask.reportExecutionException(ForkJoinTask.java:579)
at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1021)
at test.concurrent.sim.zos.context.web.SimZOSContextTestServlet.testInterruptOnDeactivate_waitForInterrupt(SimZOSContextTestServlet.java:164)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at componenttest.app.FATServlet.doGet(FATServlet.java:71)
at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:527)
at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:614)
at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1258)
at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:746)
at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:443)
at com.ibm.ws.webcontainer.filter.WebAppFilterChain.invokeTarget(WebAppFilterChain.java:193)
at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:98)
at com.ibm.ws.security.jaspi.JaspiServletFilter.doFilter(JaspiServletFilter.java:56)
at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:201)
at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:91)
at com.ibm.ws.webcontainer.filter.WebAppFilterManager.doFilter(WebAppFilterManager.java:1002)
at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1140)
at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:5059)
at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.handleRequest(DynamicVirtualHost.java:316)
at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:1007)
at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:281)
at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1184)
at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:453)
at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:412)
at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:566)
at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:500)
at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:360)
at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.ready(HttpInboundLink.java:327)
at com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.sendToDiscriminators(NewConnectionInitialReadCallback.java:167)
at com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.complete(NewConnectionInitialReadCallback.java:75)
at com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:514)
at com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueManager.java:584)
at com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:968)
at com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:1057)
at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:245)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1596)

at componenttest.topology.utils.FATServletClient.runTest(FATServletClient.java:92)
at test.concurrent.sim.zos.context.SimZOSContextProviderTest.testInterruptOnDeactivate(SimZOSContextProviderTest.java:88)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:199)
at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:349)
at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:173)
```

It might be possible to work around this by using the `onStart` notification instead.

**Comment by jgrassel** [comment]
Would be good to reference the submitted Oracle bug for historical reference https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8292027
