### ISSUE TITLE
Faces 4.0: Fix UnsupportOperationException when starting the a Faces app with the faces-4.0 feature

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#22214]
MyFaces Issue: https://issues.apache.org/jira/browse/MYFACES-4442

Open Liberty registers the `org.apache.myfaces.webapp.StartupServletContextListener` programmattically.  This is done here: https://github.com/OpenLiberty/open-liberty/blob/integration/dev/io.openliberty.faces.4.0.internal/src/com/ibm/ws/jsf/extprocessor/JSFExtensionFactory.java if the listener isn't already configured in the web.xml. This is done automatically if a `FacesServlet` or `MyFacesServlet` is defined in the web.xml of the application.

It is also added here: https://github.com/OpenLiberty/open-liberty/blob/integration/dev/io.openliberty.faces.4.0.internal/src/com/ibm/ws/jsf/ee/WASMyFacesContainerInitializer.java

> SRVE9002E: You cannot start this operation from a programmatically added listener when using servlet-3.1 feature. (Operation: getServletRegistrations | Listener: org.apache.myfaces.webapp.StartupServletContextListener | Application: SimpleTest)
> [AUDIT   ] CWWKZ0001I: Application SimpleTest started in 0.617 seconds.
> [AUDIT   ] CWWKF0012I: The server installed the following features: [expressionLanguage-5.0, faces-4.0, pages-3.1, servlet-6.0, timedexit-1.0].
> [AUDIT   ] CWWKF0011I: The faces40_simpleTest server is ready to run a smarter planet. The faces40_simpleTest server started in 12.250 seconds.
> [ERROR   ] SRVE0271E: Uncaught init() exception created by servlet [Faces Servlet] in application [SimpleTest]: java.lang.IllegalStateException: No Factories configured for this Application. This happens if the faces-initialization does not work at all - make sure that you properly include all configuration settings necessary for a basic faces application and that all the necessary libs are included. Also check the logging output of your web application and your container for any exceptions!
> If you did that and find nothing, the mistake might be due to the fact that you use some special web-containers which do not support registering context-listeners via TLD files and a context listener is not setup in your web.xml.
> A typical config looks like this;
> <listener>
>   <listener-class>org.apache.myfaces.webapp.StartupServletContextListener</listener-class>
> </listener>
> 
> 	at <unknown class>._getFactory(FactoryFinder.java:286)
> 	at <unknown class>.getFactory(FactoryFinder.java:207)
> 	at <unknown class>.init(FacesServlet.java:140)
> 	at <unknown class>.init(ServletWrapper.java:299)
> 	at <unknown class>.handleRequest(ServletWrapper.java:601)
> 	at <unknown class>.handleRequest(ServletWrapper.java:443)
> 	at <unknown class>.invokeFilters(WebAppFilterManager.java:1227)
> 	at <unknown class>.handleRequest(WebApp.java:5059)
> 	at <unknown class>.handleRequest(DynamicVirtualHost.java:316)
> 	at <unknown class>.handleRequest(WebContainer.java:1007)
> 	at <unknown class>.run(DynamicVirtualHost.java:281)
> 	at <unknown class>.run(HttpDispatcherLink.java:1199)
> 	at <unknown class>.wrapHandlerAndExecute(HttpDispatcherLink.java:468)
> 	at <unknown class>.ready(HttpDispatcherLink.java:427)
> 	at <unknown class>.handleDiscrimination(HttpInboundLink.java:566)
> 	at <unknown class>.handleNewRequest(HttpInboundLink.java:500)
> 	at <unknown class>.processRequest(HttpInboundLink.java:360)
> 	at <unknown class>.ready(HttpInboundLink.java:327)
> 	at <unknown class>.sendToDiscriminators(NewConnectionInitialReadCallback.java:167)
> 	at <unknown class>.complete(NewConnectionInitialReadCallback.java:75)
> 	at <unknown class>.requestComplete(WorkQueueManager.java:514)
> 	at <unknown class>.attemptIO(WorkQueueManager.java:584)
> 	at <unknown class>.workerRun(WorkQueueManager.java:968)
> 	at <unknown class>.run(WorkQueueManager.java:1057)
> 	at <unknown class>.run(ExecutorServiceImpl.java:245)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
> 	at java.base/java.lang.Thread.run(Thread.java:866)
>

**Comment by pnicolucci** [comment]
> [8/22/22, 8:54:54:608 EDT] 00000044 FacesInitiali E   An error occured while initializing MyFaces: SRVE9002E: You cannot start this operation from a programmatically added listener when using servlet-3.1 feature. (Operation: getServletRegistrations | Listener: org.apache.myfaces.webapp.StartupServletContextListener | Application: SimpleTest)
>                                  java.lang.UnsupportedOperationException: SRVE9002E: You cannot start this operation from a programmatically added listener when using servlet-3.1 feature. (Operation: getServletRegistrations | Listener: org.apache.myfaces.webapp.StartupServletContextListener | Application: SimpleTest)
> 	at <unknown class>.getServletRegistrations(WebApp31.java:246)
> 	at <unknown class>.getServletRegistrations(ServletContextFacade.java:657)
> 	at <unknown class>.getServletRegistrations(FacesServletMappingUtils.java:121)
> 	at <unknown class>.getFacesServletRegistration(FacesServletMappingUtils.java:152)
> 	at <unknown class>.initFaces(FacesInitializerImpl.java:154)
> 	at <unknown class>.contextInitialized(StartupServletContextListener.java:54)
> 	at <unknown class>.notifyServletContextCreated(WebApp.java:2447)
> 	at <unknown class>.notifyServletContextCreated(WebApp31.java:517)
