### ISSUE TITLE
Session timing issue during server shutdown

### ISSUE THREAD

**Issue by zhang-ca** [OpenLiberty/open-liberty#22221]
**Describe the bug**  
Cache service timing issue. It happens that the invalidation thread hits in the middle of cacheservice teardown.

**Steps to Reproduce**  
Run com.ibm.ws.session.cache_fat_infinispan_container and com.ibm.ws.session.cache_fat tests

**Expected behavior**  
Protect any calls to sessionMetaCache methods in CacheHashMap.performInvalidation() 
                    //Process the non-listener sessions first
                    doInvalidations();
                    //Read in all the sessions with listeners that need to be invalidated
                    processInvalidListeners();

**Diagnostic information:**  
org.infinispan.jcache.remote.JCache.checkNotClosed(JCache.java:423) 
org.infinispan.jcache.remote.JCache.iterator(JCache.java:406)
at com.ibm.ws.session.store.cache.CacheHashMap.processInvalidListeners(CacheHashMap.java:1103)
at com.ibm.ws.session.store.cache.CacheHashMap.performInvalidation(CacheHashMap.java:995)

Ref: RTC defect 291209

**Comment by zhang-ca** [comment]
There is a large window there for shutdown to effect it. For now PR #22222 will be enough to fix most of the cases, though we may want to test if iterating over the iterator after a jcache closes causes an error. That is, check before the cache.iterator() call, and check before calling .hasNext() or .next() as it is possible it makes call out to the remote cache. That chunk of logic maybe time consuming.
