### ISSUE TITLE
CWWKC0458E: An error occurred restoring the server process with the following message: null

### ISSUE THREAD

**Issue by tam512** [OpenLiberty/open-liberty#22362]
**Describe the bug**  

Build app image with InstantOn checkpoint at applications on RHEL 9 and run the  image on Ubuntu 22.04 got error 

```
# podman logs microwebapp-restore-app
[AUDIT   ] CWWKZ0001I: Application microwebapp started in 0.214 seconds.
[ERROR   ] CWWKC0454E: The server failed to restore from a checkpoint with the following message: CWWKC0458E: An error occurred restoring the server process with the following message: null
[AUDIT   ] CWWKF0012I: The server installed the following features: [appSecurity-4.0, cdi-3.0, checkpoint-1.0, concurrent-2.0, distributedMap-1.0, expressionLanguage-4.0, jndi-1.0, json-1.0, jsonb-2.0, jsonp-2.0, jwt-1.0, microProfile-5.0, monitor-1.0, mpConfig-3.0, mpFaultTolerance-4.0, mpHealth-4.0, mpJwt-2.0, mpMetrics-4.0, mpOpenAPI-3.0, mpOpenTracing-3.0, mpRestClient-3.0, pages-3.0, restfulWS-3.0, restfulWSClient-3.0, servlet-5.0, ssl-1.0, transportSecurity-1.0].
[AUDIT   ] CWWKF0011I: The defaultServer server is ready to run a smarter planet. The defaultServer server started in 0.377 seconds.
[AUDIT   ] CWWKE0084I: The server defaultServer is stopping because thread Checkpoint failed, exiting... (00000040) called the method java.lang.System.exit: 
    at java.base/java.lang.System.exit(Unknown Source)
    at io.openliberty.checkpoint.internal.CheckpointImpl.lambda$checkpointOrExitOnFailure$1(CheckpointImpl.java:355)
    at java.base/java.lang.Thread.run(Unknown Source)
```
Below is ffdc in the container
```
------Start of DE processing------ = [8/31/22, 21:24:42:098 UTC]
Exception = io.openliberty.checkpoint.internal.criu.CheckpointFailedException
Source = io.openliberty.checkpoint.internal.CheckpointImpl
probeid = 341
Stack Dump = io.openliberty.checkpoint.internal.criu.CheckpointFailedException: CWWKC0458E: An error occurred restoring the server process with the following message: null
    at io.openliberty.checkpoint.internal.CheckpointImpl.failedRestore(CheckpointImpl.java:586)
    at io.openliberty.checkpoint.internal.CheckpointImpl.callHooks(CheckpointImpl.java:560)
    at io.openliberty.checkpoint.internal.CheckpointImpl.restore(CheckpointImpl.java:579)
    at io.openliberty.checkpoint.internal.CheckpointImpl.checkpoint(CheckpointImpl.java:432)
    at io.openliberty.checkpoint.internal.CheckpointImpl.checkpointOrExitOnFailure(CheckpointImpl.java:340)
    at io.openliberty.checkpoint.internal.CheckpointImpl.check(CheckpointImpl.java:335)
    at java.base/java.util.ArrayList.forEach(Unknown Source)
    at com.ibm.ws.kernel.feature.internal.FeatureManager.checkServerReady(FeatureManager.java:823)
    at com.ibm.ws.kernel.feature.internal.FeatureManager.update(FeatureManager.java:786)
    at com.ibm.ws.kernel.feature.internal.FeatureManager.processFeatureChanges(FeatureManager.java:886)
    at com.ibm.ws.kernel.feature.internal.FeatureManager$1.run(FeatureManager.java:672)
    at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:245)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.util.ConcurrentModificationException
    at java.base/java.util.HashMap$HashIterator.nextNode(Unknown Source)
    at java.base/java.util.HashMap$KeyIterator.next(Unknown Source)
    at com.ibm.ws.kernel.service.util.CpuInfo$IntervalTask.notifyListeners(CpuInfo.java:467)
    at com.ibm.ws.kernel.service.util.CpuInfo$IntervalTask.run(CpuInfo.java:459)
    at com.ibm.ws.kernel.service.util.CpuInfo$IntervalTask.restore(CpuInfo.java:433)
    at io.openliberty.checkpoint.spi.CheckpointPhase$CheckpointPhaseHookImpl.restore(CheckpointPhase.java:286)
    at io.openliberty.checkpoint.internal.CheckpointImpl.callHooks(CheckpointImpl.java:557)
    ... 13 more
```

**Comment by tjwatson** [comment]
This is possible when you create a checkpoint on one machine that has a different number of CPUs than the machine you are restoring on.  I've got a fix building now.

Can you run the command `numactl -H` on the machine you did the checkpoint on and the machine you did the restore on so we can see the different CPU configurations?

**Comment by tam512** [comment]
- on machine create checkpoint (RHEL 9)
```
# numactl -H
available: 1 nodes (0)
node 0 cpus: 0 1 2 3
node 0 size: 7684 MB
node 0 free: 1794 MB
node distances:
node   0 
  0:  10 
```
- on machine that ran restore (Ubuntu 22.04)
```
# numactl -H
available: 1 nodes (0)
node 0 cpus: 0 1
node 0 size: 3925 MB
node 0 free: 760 MB
node distances:
node   0 
  0:  10 
```

**Comment by tjwatson** [comment]
Thanks, that confirms that you had a change in available CPUs.  Checkpoint at 4 and restored at 2.

Can you also check the chip set used by running the following on each machine? `cat /proc/cpuinfo | grep "model name"`

**Comment by tam512** [comment]
- RHEL9
```
# cat /proc/cpuinfo | grep "model name"
model name	: AMD EPYC Processor (with IBPB)
model name	: AMD EPYC Processor (with IBPB)
model name	: AMD EPYC Processor (with IBPB)
model name	: AMD EPYC Processor (with IBPB)
```
- Ubuntu 22.04
```
# cat /proc/cpuinfo | grep "model name"
model name	: AMD EPYC Processor (with IBPB)
model name	: AMD EPYC Processor (with IBPB)
```

**Comment by tjwatson** [comment]
Thanks.  There is another issue we recently discovered where if the checkpoint host uses Intel and the restore host uses AMD (or vise-versa) then we will see errors restoring.  That is an issue requiring a fix in OpenJ9.

**Comment by tjwatson** [comment]
A fix for this `ConcurrentModificationException` is available in the nightly Open Liberty builds.  I will need to respin the container images to include this fix once this fix shows up in a nightly Open Liberty build.

**Comment by tjwatson** [comment]
This should be fixed in the latest container images.

**Comment by tam512** [comment]
I also verified that it's working on the latest images
