### ISSUE TITLE
Make MP GraphQL 2.0 work with EE10/MP6 features

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/open-liberty#22380]
`mpGraphQL-2.0` is a standalone MicroProfile feature which should work with both MicroProfile 5.0 and MicroProfile 6.0.

**Comment by Azquelt** [comment]
I've done the initial work to update the feature files to tolerate EE10/MP6 and to repeat the FAT and TCK tests.

Most of the tests pass but there are a handful of FAT tests which do not.
* `BasicQueryTestServlet.testSimpleQueryWhenUnableToSerializeEntity_EE10_FEATURES_MicroProfile_60_GraphQL_20`
* `BasicQueryTestServlet.testSimpleQueryWhenUnableToSerializeEntity_EE10_FEATURES_MicroProfile_60_GraphQL_20`
* `InterfaceTestServlet.testMutationUsingInterfaceType_EE10_FEATURES_MicroProfile_60_GraphQL_20`

The failures look like deserialization problems and may be due to changes in jsonb (updated from 2.0 to 3.0 in EE10) but I think this needs a look from someone who understands the tests.

There's a branch with my changes here: https://github.com/Azquelt/open-liberty/tree/microprofile6-mpGraphQL

**Comment by Azquelt** [comment]
Failure 1:
```
junit.framework.AssertionFailedError: 2022-09-02-16:14:50:316 ERROR: Caught exception attempting to call test method testSimpleQueryWhenUnableToSerializeEntity on servlet mpGraphQL10.basicQuery.BasicQueryTestServlet
java.lang.NullPointerException
	at mpGraphQL10.basicQuery.BasicQueryTestServlet.testSimpleQueryWhenUnableToSerializeEntity(BasicQueryTestServlet.java:157)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at componenttest.app.FATServlet.doGet(FATServlet.java:67)
[...]
```

Comparing the server logs for EE9 and EE10, it looked to me like the same response is returned but was deserialized differently, resulting in a `null` where the test wasn't expecting one.

EE10:
```
[02/09/2022, 16:14:50:295 BST] 00000035 mpGraphQL10.basicQuery.LoggingFilter                         I Response status=200 entity={"errors":[{"message":"Server Error","locations":[{"line":4,"column":5}],"path":["allWidgetsUnableToSerialize",0,"quantity"],"extensions":{"exception":"graphql.GraphQLException","classification":"DataFetchingException","code":"graph-q-l"}}],"data":{"allWidgetsUnableToSerialize":[null]}}

[02/09/2022, 16:14:50:296 BST] 00000035 SystemOut                                                    O Response: WidgetQueryResponse[
  data : null
  errors : [
    {
      message : Server Error
      path : null
      extensions : null
    }
  ]
```

EE9:
```
[02/09/2022, 16:10:39:423 BST] 00000041 mpGraphQL10.basicQuery.LoggingFilter                         I Response status=200 entity={"errors":[{"message":"Server Error","locations":[{"line":4,"column":5}],"path":["allWidgetsUnableToSerialize",0,"quantity"],"extensions":{"exception":"graphql.GraphQLException","classification":"DataFetchingException","code":"graph-q-l"}}],"data":{"allWidgetsUnableToSerialize":[null]}}

[02/09/2022, 16:10:39:427 BST] 00000041 SystemOut                                                    O Response: WidgetQueryResponse[
  data : [
    allWidgets:                  [null]
    allWidgetsSet:               null
    allWidgetsUnableToSerialize: [null]
  ]
  errors : [
    {
      message : Server Error
      path : [Ljava.lang.Object;@75ba6b16
      extensions : 
    }
  ]
```

For some reason this failure is reported twice from my test run.

**Comment by Azquelt** [comment]
Failure 2:
```
junit.framework.AssertionFailedError: 2022-09-02-16:15:59:900 ERROR: Caught exception attempting to call test method testMutationUsingInterfaceType on servlet mpGraphQL10.iface.InterfaceTestServlet
jakarta.ws.rs.ProcessingException: jakarta.json.bind.JsonbException: Unable to deserialize property 'data' because of: Unable to deserialize property 'allWidgets' because of: Cannot infer a type for unmarshalling into: mpGraphQL10.iface.Widget
	at org.jboss.resteasy.client.jaxrs.internal.ClientResponse.readFrom(ClientResponse.java:254)
	at org.jboss.resteasy.specimpl.BuiltResponse.readEntity(BuiltResponse.java:90)
	at org.jboss.resteasy.specimpl.AbstractBuiltResponse.readEntity(AbstractBuiltResponse.java:256)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.extractResult(ClientInvocation.java:164)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.extractors.BodyEntityExtractor.extractEntity(BodyEntityExtractor.java:64)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invokeSync(ClientInvoker.java:154)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:115)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:76)
	at com.sun.proxy.$Proxy57.allWidgets(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.jboss.resteasy.microprofile.client.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:146)
	at org.jboss.resteasy.microprofile.client.ot.DefaultMethodInvocationHandler.invoke(DefaultMethodInvocationHandler.java:53)
	at org.jboss.resteasy.microprofile.client.ot.LibertyProxyInvocationHandler.invoke(LibertyProxyInvocationHandler.java:46)
	at com.sun.proxy.$Proxy59.allWidgets(Unknown Source)
	at mpGraphQL10.iface.InterfaceTestServlet.testMutationUsingInterfaceType(InterfaceTestServlet.java:113)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at componenttest.app.FATServlet.doGet(FATServlet.java:67)
[...]
Caused by: jakarta.json.bind.JsonbException: Unable to deserialize property 'data' because of: Unable to deserialize property 'allWidgets' because of: Cannot infer a type for unmarshalling into: mpGraphQL10.iface.Widget
	at org.eclipse.yasson.internal.deserializer.ObjectDeserializer.deserialize(ObjectDeserializer.java:70)
	at org.eclipse.yasson.internal.deserializer.ObjectDeserializer.deserialize(ObjectDeserializer.java:29)
	at org.eclipse.yasson.internal.deserializer.DefaultObjectInstanceCreator.deserialize(DefaultObjectInstanceCreator.java:57)
	at org.eclipse.yasson.internal.deserializer.DefaultObjectInstanceCreator.deserialize(DefaultObjectInstanceCreator.java:29)
	at org.eclipse.yasson.internal.deserializer.PositionChecker.deserialize(PositionChecker.java:85)
	at org.eclipse.yasson.internal.deserializer.PositionChecker.deserialize(PositionChecker.java:34)
	at org.eclipse.yasson.internal.deserializer.NullCheckDeserializer.deserialize(NullCheckDeserializer.java:46)
	at org.eclipse.yasson.internal.deserializer.NullCheckDeserializer.deserialize(NullCheckDeserializer.java:26)
	at org.eclipse.yasson.internal.DeserializationContextImpl.deserializeItem(DeserializationContextImpl.java:138)
	at org.eclipse.yasson.internal.DeserializationContextImpl.deserialize(DeserializationContextImpl.java:127)
	at org.eclipse.yasson.internal.JsonBinding.deserialize(JsonBinding.java:55)
	at org.eclipse.yasson.internal.JsonBinding.fromJson(JsonBinding.java:95)
	at io.openliberty.restfulWS30.jsonb20provider.JsonBProvider.readFrom(JsonBProvider.java:177)
	at org.jboss.resteasy.core.interception.jaxrs.AbstractReaderInterceptorContext.readFrom(AbstractReaderInterceptorContext.java:101)
	at org.jboss.resteasy.core.interception.jaxrs.AbstractReaderInterceptorContext.proceed(AbstractReaderInterceptorContext.java:80)
	at org.jboss.resteasy.client.jaxrs.internal.ClientResponse.readFrom(ClientResponse.java:217)
Caused by: jakarta.json.bind.JsonbException: Unable to deserialize property 'allWidgets' because of: Cannot infer a type for unmarshalling into: mpGraphQL10.iface.Widget
	at org.eclipse.yasson.internal.deserializer.ObjectDeserializer.deserialize(ObjectDeserializer.java:70)
	at org.eclipse.yasson.internal.deserializer.ObjectDeserializer.deserialize(ObjectDeserializer.java:29)
	at org.eclipse.yasson.internal.deserializer.DefaultObjectInstanceCreator.deserialize(DefaultObjectInstanceCreator.java:57)
	at org.eclipse.yasson.internal.deserializer.DefaultObjectInstanceCreator.deserialize(DefaultObjectInstanceCreator.java:29)
	at org.eclipse.yasson.internal.deserializer.PositionChecker.deserialize(PositionChecker.java:85)
	at org.eclipse.yasson.internal.deserializer.PositionChecker.deserialize(PositionChecker.java:34)
	at org.eclipse.yasson.internal.deserializer.NullCheckDeserializer.deserialize(NullCheckDeserializer.java:46)
	at org.eclipse.yasson.internal.deserializer.NullCheckDeserializer.deserialize(NullCheckDeserializer.java:26)
	at org.eclipse.yasson.internal.deserializer.ContextSwitcher.deserialize(ContextSwitcher.java:36)
	at org.eclipse.yasson.internal.deserializer.ContextSwitcher.deserialize(ContextSwitcher.java:22)
	at org.eclipse.yasson.internal.deserializer.ObjectDeserializer.deserialize(ObjectDeserializer.java:68)
Caused by: jakarta.json.bind.JsonbException: Cannot infer a type for unmarshalling into: mpGraphQL10.iface.Widget
	at org.eclipse.yasson.internal.deserializer.DefaultObjectInstanceCreator.<init>(DefaultObjectInstanceCreator.java:41)
	at org.eclipse.yasson.internal.deserializer.DeserializationModelCreator.createObjectDeserializer(DeserializationModelCreator.java:251)
	at org.eclipse.yasson.internal.deserializer.DeserializationModelCreator.deserializerChainInternal(DeserializationModelCreator.java:193)
	at org.eclipse.yasson.internal.deserializer.DeserializationModelCreator.deserializerChain(DeserializationModelCreator.java:135)
	at org.eclipse.yasson.internal.deserializer.DeserializationModelCreator.createNewChain(DeserializationModelCreator.java:487)
	at org.eclipse.yasson.internal.deserializer.DeserializationModelCreator.typeProcessor(DeserializationModelCreator.java:476)
	at org.eclipse.yasson.internal.deserializer.DeserializationModelCreator.typeProcessor(DeserializationModelCreator.java:429)
	at org.eclipse.yasson.internal.deserializer.DeserializationModelCreator.createCollectionDeserializer(DeserializationModelCreator.java:272)
	at org.eclipse.yasson.internal.deserializer.DeserializationModelCreator.deserializerChainInternal(DeserializationModelCreator.java:183)
	at org.eclipse.yasson.internal.deserializer.DeserializationModelCreator.deserializerChain(DeserializationModelCreator.java:135)
	at org.eclipse.yasson.internal.deserializer.DeserializationModelCreator.createNewChain(DeserializationModelCreator.java:487)
	at org.eclipse.yasson.internal.deserializer.DeserializationModelCreator.typeProcessor(DeserializationModelCreator.java:476)
	at org.eclipse.yasson.internal.deserializer.DeserializationModelCreator.typeProcessor(DeserializationModelCreator.java:429)
	at org.eclipse.yasson.internal.deserializer.DeserializationModelCreator.memberTypeProcessor(DeserializationModelCreator.java:422)
	at org.eclipse.yasson.internal.deserializer.DeserializationModelCreator.createObjectDeserializer(DeserializationModelCreator.java:222)
	at org.eclipse.yasson.internal.deserializer.DeserializationModelCreator.deserializerChainInternal(DeserializationModelCreator.java:193)
	at org.eclipse.yasson.internal.deserializer.DeserializationModelCreator.deserializerChain(DeserializationModelCreator.java:135)
	at org.eclipse.yasson.internal.deserializer.DeserializationModelCreator.createNewChain(DeserializationModelCreator.java:487)
	at org.eclipse.yasson.internal.deserializer.DeserializationModelCreator.typeProcessor(DeserializationModelCreator.java:476)
	at org.eclipse.yasson.internal.deserializer.DeserializationModelCreator.typeProcessor(DeserializationModelCreator.java:429)
	at org.eclipse.yasson.internal.deserializer.DeserializationModelCreator.memberTypeProcessor(DeserializationModelCreator.java:422)
	at org.eclipse.yasson.internal.deserializer.DeserializationModelCreator.createObjectDeserializer(DeserializationModelCreator.java:222)
	at org.eclipse.yasson.internal.deserializer.DeserializationModelCreator.deserializerChainInternal(DeserializationModelCreator.java:193)
	at org.eclipse.yasson.internal.deserializer.DeserializationModelCreator.deserializerChain(DeserializationModelCreator.java:135)
	at org.eclipse.yasson.internal.deserializer.DeserializationModelCreator.deserializerChain(DeserializationModelCreator.java:123)
	at org.eclipse.yasson.internal.DeserializationContextImpl.deserializeItem(DeserializationContextImpl.java:137)
	at org.eclipse.yasson.internal.DeserializationContextImpl.deserialize(DeserializationContextImpl.java:127)
	at org.eclipse.yasson.internal.JsonBinding.deserialize(JsonBinding.java:55)
	at org.eclipse.yasson.internal.JsonBinding.fromJson(JsonBinding.java:95)
	at io.openliberty.restfulWS30.jsonb20provider.JsonBProvider.readFrom(JsonBProvider.java:177)
	at org.jboss.resteasy.core.interception.jaxrs.AbstractReaderInterceptorContext.readFrom(AbstractReaderInterceptorContext.java:101)
	at org.jboss.resteasy.core.interception.jaxrs.AbstractReaderInterceptorContext.proceed(AbstractReaderInterceptorContext.java:80)
	at org.jboss.resteasy.client.jaxrs.internal.ClientResponse.readFrom(ClientResponse.java:217)
	at org.jboss.resteasy.specimpl.BuiltResponse.readEntity(BuiltResponse.java:90)
	at org.jboss.resteasy.specimpl.AbstractBuiltResponse.readEntity(AbstractBuiltResponse.java:256)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.extractResult(ClientInvocation.java:164)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.extractors.BodyEntityExtractor.extractEntity(BodyEntityExtractor.java:64)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invokeSync(ClientInvoker.java:154)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:115)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:76)
	at com.sun.proxy.$Proxy57.allWidgets(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.jboss.resteasy.microprofile.client.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:146)
	at org.jboss.resteasy.microprofile.client.ot.DefaultMethodInvocationHandler.invoke(DefaultMethodInvocationHandler.java:53)
	at org.jboss.resteasy.microprofile.client.ot.LibertyProxyInvocationHandler.invoke(LibertyProxyInvocationHandler.java:46)
	at com.sun.proxy.$Proxy59.allWidgets(Unknown Source)
	at mpGraphQL10.iface.InterfaceTestServlet.testMutationUsingInterfaceType(InterfaceTestServlet.java:95)

	at componenttest.topology.utils.FATServletClient.runTest(FATServletClient.java:92)
	at componenttest.custom.junit.runner.SyntheticServletTest.invokeExplosively(SyntheticServletTest.java:42)
	at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:199)
	at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:352)
	at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:173)
	at componenttest.rules.repeater.RepeatTests$CompositeRepeatTestActionStatement.evaluate(RepeatTests.java:143)
```

**Comment by WhiteCat22** [comment]
I did some investigation and here is what I've found so far:

1. According to the [spec](https://jakarta.ee/specifications/jsonb/3.0/jakarta-jsonb-spec-3.0.html#null-java-field)
```
The result of serializing a java field with a null value is the absence of the property in the resulting JSON document.
```

This hasn't changed, however, it looks like the implementation may have changed because `data` used serialize (incorrectly?) with 3 `null` fields (2 of which are arrays) and now it is not written at all.

I think the new behavior is correct and the test should be modified to send back some good data alongside the bad data to test partial results properly.


2. It looks like the test applicaiton's `JsonbDeserializer` isn't being registered and executed. I'm not sure if this is a product bug or a test bug at this point.
