### ISSUE TITLE
ClassNotFound with mpMetrics3.0

### ISSUE THREAD

**Issue by sdehors-ibm** [OpenLiberty/open-liberty#22455]
**Describe the bug**  

I'm trying to enable mpMetrics 3.0 micro profile on liberty 22.0.0.7. I selected only features compatible with microProfile4.1:
 ```
<featureManager>
        <!-- based on microProfile 4.1 -->
        <feature>cdi-2.0</feature>
        <feature>jaxrs-2.1</feature>
        <feature>jsonb-1.0</feature>
        <feature>mpMetrics-3.0</feature>
        <feature>mpOpenAPI-2.0</feature>
        <feature>mpOpenTracing-2.0</feature>
        <feature>mpContextPropagation-1.2</feature>
        <feature>openidConnectClient-1.0</feature>
        <feature>localConnector-1.0</feature>
    </featureManager>

```
Yet at startup I get this ClassNotFound exception :

[12/09/2022, 16:17:12:357 CEST] 00000026 254-io.openliberty.microprofile.metrics.internal.3.0.monitor E CWWKE0701E: FrameworkEvent ERROR org.osgi.framework.ServiceException: Exception in org.apache.felix.scr.impl.manager.SingleComponentManager.getService()
	at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.factoryGetService(ServiceFactoryUse.java:230)
	at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.getService(ServiceFactoryUse.java:118)
	at org.eclipse.osgi.internal.serviceregistry.ServiceConsumer$2.getService(ServiceConsumer.java:48)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.getService(ServiceRegistrationImpl.java:547)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.getService(ServiceRegistry.java:533)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.getService(BundleContextImpl.java:655)
	at org.apache.felix.scr.impl.manager.SingleRefPair.getServiceObject(SingleRefPair.java:88)
	at org.apache.felix.scr.impl.inject.field.FieldHandler$ReferenceMethodImpl.getServiceObject(FieldHandler.java:525)
	at org.apache.felix.scr.impl.manager.DependencyManager.getServiceObject(DependencyManager.java:2556)
	at org.apache.felix.scr.impl.manager.DependencyManager.doInvokeBindMethod(DependencyManager.java:2075)
	at org.apache.felix.scr.impl.manager.DependencyManager.invokeBindMethod(DependencyManager.java:2058)
	at org.apache.felix.scr.impl.manager.SingleComponentManager.invokeBindMethod(SingleComponentManager.java:443)
	at org.apache.felix.scr.impl.manager.DependencyManager$MultipleDynamicCustomizer.addedService(DependencyManager.java:333)
	at org.apache.felix.scr.impl.manager.DependencyManager$MultipleDynamicCustomizer.addedService(DependencyManager.java:301)
	at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.customizerAdded(ServiceTracker.java:1200)
	at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.customizerAdded(ServiceTracker.java:1121)
	at org.apache.felix.scr.impl.manager.ServiceTracker$AbstractTracked.trackAdding(ServiceTracker.java:928)
	at org.apache.felix.scr.impl.manager.ServiceTracker$AbstractTracked.track(ServiceTracker.java:864)
	at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:1152)
	at org.apache.felix.scr.impl.BundleComponentActivator$ListenerInfo.serviceChanged(BundleComponentActivator.java:114)
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:120)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:956)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:936)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry$1.run(ServiceRegistry.java:878)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry$1.run(ServiceRegistry.java:1)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:691)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:875)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:141)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:261)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:495)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager$3.register(AbstractComponentManager.java:929)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager$3.register(AbstractComponentManager.java:915)
	at org.apache.felix.scr.impl.manager.RegistrationManager.changeRegistration(RegistrationManager.java:133)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.registerService(AbstractComponentManager.java:984)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.activateInternal(AbstractComponentManager.java:752)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.enableInternal(AbstractComponentManager.java:674)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.enable(AbstractComponentManager.java:437)
	at org.apache.felix.scr.impl.manager.ConfigurableComponentHolder.enableComponents(ConfigurableComponentHolder.java:667)
	at org.apache.felix.scr.impl.BundleComponentActivator.initialEnable(BundleComponentActivator.java:305)
	at org.apache.felix.scr.impl.Activator.loadComponents(Activator.java:554)
	at org.apache.felix.scr.impl.Activator.access$200(Activator.java:70)
	at org.apache.felix.scr.impl.Activator$ScrExtension.start(Activator.java:421)
	at org.apache.felix.scr.impl.AbstractExtender.createExtension(AbstractExtender.java:196)
	at org.apache.felix.scr.impl.AbstractExtender.modifiedBundle(AbstractExtender.java:169)
	at org.apache.felix.scr.impl.AbstractExtender.modifiedBundle(AbstractExtender.java:49)
	at org.osgi.util.tracker.BundleTracker$Tracked.customizerModified(BundleTracker.java:488)
	at org.osgi.util.tracker.BundleTracker$Tracked.customizerModified(BundleTracker.java:1)
	at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:232)
	at org.osgi.util.tracker.BundleTracker$Tracked.bundleChanged(BundleTracker.java:450)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:944)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEventPrivileged(EquinoxEventPublisher.java:229)
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.lambda$0(EquinoxEventPublisher.java:141)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:691)
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:140)
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:130)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor.publishModuleEvent(EquinoxContainerAdaptor.java:217)
	at org.eclipse.osgi.container.Module.publishEvent(Module.java:499)
	at org.eclipse.osgi.container.Module.start(Module.java:486)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1847)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$1.execute(ModuleContainer.java:1835)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1840)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1784)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1745)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1667)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)
Caused by: java.lang.NoClassDefFoundError: com.ibm.ws.jaxrs.defaultexceptionmapper.DefaultExceptionMapperCallback
	at java.base/java.lang.ClassLoader.defineClassImpl(Native Method)
	at java.base/java.lang.ClassLoader.defineClassInternal(ClassLoader.java:466)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:427)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.defineClass(ModuleClassLoader.java:283)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.defineClass(ClasspathManager.java:716)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findClassImpl(ClasspathManager.java:639)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClassImpl(ClasspathManager.java:607)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClassImpl(ClasspathManager.java:587)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:566)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:335)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:397)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass0(BundleLoader.java:500)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:416)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:168)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1070)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.loadClass(EquinoxBundle.java:622)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.initDependencyManagers(AbstractComponentManager.java:1026)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.collectDependencies(AbstractComponentManager.java:1054)
	at org.apache.felix.scr.impl.manager.SingleComponentManager.getServiceInternal(SingleComponentManager.java:953)
	at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:918)
	at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse$1.run(ServiceFactoryUse.java:220)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:691)
	at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.factoryGetService(ServiceFactoryUse.java:217)
	... 70 more
Caused by: java.lang.ClassNotFoundException: com.ibm.ws.jaxrs.defaultexceptionmapper.DefaultExceptionMapperCallback cannot be found by io.openliberty.microprofile.metrics.internal.3.0.monitor_1.0.66.cl220720220620-2217
	at org.eclipse.osgi.internal.loader.BundleLoader.generateException(BundleLoader.java:541)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass0(BundleLoader.java:536)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:416)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:168)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1070)
	... 93 more
 Event:org.osgi.framework.FrameworkEvent[source=io.openliberty.microprofile.metrics.internal.3.0.monitor_1.0.66.cl220720220620-2217 [254]] 

It looks like a bug as there is nothing special about the setup, unless some dependency is missing ?

**Steps to Reproduce**  
install liberty 22.0.0.7 with the above set of features, start it.

**Expected behavior**  
I should not see the exception.

**Diagnostic information:**  
 - OpenLiberty Version: 22.0.0.7
 - Affected feature(s) mpMetrics-3.0
 - Java Version: openjdk version "11.0.15-ea" 2022-04-19
IBM Semeru Runtime Open Edition 11.0.15.0 (build 11.0.15-ea+10)
Eclipse OpenJ9 VM 11.0.15.0 (build openj9-0.32.0, JRE 11 Mac OS X aarch64-64-Bit 20220422_36 (JIT enabled, AOT enabled)
OpenJ9   - 9a84ec34e
OMR      - ab24b6666
JCL      - b7b5b42ea6 based on jdk-11.0.15+10)

 - server.xml configuration :
```
 <server description="new server">
  <featureManager>
    <!-- based on microProfile 4.1 -->
    <feature>cdi-2.0</feature>
    <feature>jaxrs-2.1</feature>
    <feature>jsonb-1.0</feature>
    <feature>mpMetrics-3.0</feature>
    <feature>mpOpenAPI-2.0</feature>
    <feature>mpOpenTracing-2.0</feature>
    <feature>mpContextPropagation-1.2</feature>
    <feature>openidConnectClient-1.0</feature>
    <feature>localConnector-1.0</feature>
  </featureManager>
  <cdi12 enableImplicitBeanArchives="false" />
  <applicationMonitor dropinsEnabled="false" updateTrigger="mbean" />
  <webContainer skipMetaInfResourcesProcessing="true" extractHostHeaderPort="true" trustHostHeaderPort="true" com.ibm.ws.webcontainer.enablePostOnlyJSecurityCheck="true" />
  <webAppSecurity allowLogoutPageRedirectToAnyHost="true" trackLoggedOutSSOCookies="true" ssoUseDomainFromURL="true" ssoCookieName="myCookieName" />
  <mpMetrics authentication="false" />
  <httpEndpoint id="defaultHttpEndpoint" httpPort="9080" httpsPort="9443">
    <accessLogging logFormat="%{t}W %h %u %{X-Correlation-Id}o %{From}i %{X-Correlation-Id}i %m %U%q %s %b %D" />
  </httpEndpoint>
  <applicationManager autoExpand="true" />
  <logging consoleFormat="simple" copySystemStreams="true" traceSpecification="${log.trace.specification}" jsonAccessLogFields="logFormat" jsonFieldMappings="ibm_accessLogDatetime:@timestamp,ibm_responseHeader_x-correlation-id:correlationId,ibm_remoteUserID:userId,loglevel:level,ibm_datetime:@timestamp" />
</server>
```
 
 - Logs
Launching defaultServer (WebSphere Application Server 22.0.0.7/wlp-1.0.66.cl220720220620-2217) on Eclipse OpenJ9 VM, version 11.0.15-ea+10 (en_GB)
[AUDIT   ] CWWKE0001I: The server defaultServer has been launched.
[AUDIT   ] CWWKE0100I: This product is licensed for development, and limited production use. The full license terms can be viewed here: https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/license/base_ilan/ilan/22.0.0.7/lafiles/en.html
[12/09/2022, 16:33:56:421 CEST] 00000001 com.ibm.ws.kernel.launch.internal.FrameworkManager           I CWWKE0002I: The kernel started after 6.085 seconds
[12/09/2022, 16:33:56:429 CEST] 00000032 com.ibm.ws.kernel.feature.internal.FeatureManager            I CWWKF0007I: Feature update started.
[12/09/2022, 16:33:56:655 CEST] 00000029 .apache.cxf.cxf.core.3.2:1.0.66.cl220720220620-2217(id=104)] I Aries Blueprint packages not available. So namespaces will not be registered
[12/09/2022, 16:33:56:677 CEST] 00000025 com.ibm.ws.security.ready.internal.SecurityReadyServiceImpl  I CWWKS0007I: The security service is starting...
[12/09/2022, 16:33:56:827 CEST] 00000026 com.ibm.ws.http.logging.internal.AccessLogger                W The 'rolloverInterval' and 'rolloverStartTime' logging format options are in beta and are not available in this version of OpenLiberty.
[12/09/2022, 16:33:56:857 CEST] 00000029 com.ibm.ws.cache.ServerCache                                 I DYNA1001I: WebSphere Dynamic Cache instance named baseCache initialized successfully.
[12/09/2022, 16:33:56:859 CEST] 00000029 com.ibm.ws.cache.ServerCache                                 I DYNA1071I: The cache provider default is being used.
[12/09/2022, 16:33:56:860 CEST] 00000029 com.ibm.ws.cache.CacheServiceImpl                            I DYNA1056I: Dynamic Cache (object cache) initialized successfully.
[12/09/2022, 16:33:56:860 CEST] 00000027 com.ibm.ws.cdi.internal.config.AggregatedConfiguration       W CWOWB1009W: Implicit bean archives are disabled.
[12/09/2022, 16:33:56:994 CEST] 0000002e com.ibm.ws.ssl.config.WSKeyStore                             I Successfully loaded default keystore: server.jks of type: JKS
[12/09/2022, 16:33:57:013 CEST] 0000003d com.ibm.ws.security.token.ltpa.internal.LTPAKeyCreateTask    I CWWKS4105I: LTPA configuration is ready after 0.021 seconds.
[12/09/2022, 16:33:57:015 CEST] 00000025 com.ibm.ws.security.ready.internal.SecurityReadyServiceImpl  I CWWKS0008I: The security service is ready.
[12/09/2022, 16:33:57:017 CEST] 00000025 ibm.ws.security.authentication.internal.jaas.JAASServiceImpl I CWWKS1123I: The collective authentication plugin with class name NullCollectiveAuthenticationPlugin has been activated. 
[12/09/2022, 16:33:57:215 CEST] 00000025 com.ibm.ws.session.WASSessionCore                            I SESN8501I: The session manager did not find a persistent storage location; HttpSession objects will be stored in the local application server's memory.
[12/09/2022, 16:33:57:270 CEST] 00000025 com.ibm.ws.security.oauth20.web.OAuth20EndpointServices      I CWWKS1410I: The OAuth endpoint service is activated.
[12/09/2022, 16:33:57:280 CEST] 00000025 com.ibm.ws.security.jwt.internal.ConsumerImpl                I CWWKS6012I: The JSON Web Token (JWT) consumer service is available.
[12/09/2022, 16:33:57:286 CEST] 00000025 com.ibm.ws.security.jwt.web.JwtEndpointServices              I CWWKS6002I: The JSON Web Token (JWT) endpoint service is available.
[12/09/2022, 16:33:57:301 CEST] 00000025 com.ibm.ws.security.wim.VMMService                           I CWIMK0009I: The user registry federation service is ready.
[12/09/2022, 16:33:57:342 CEST] 00000025 .microprofile.metrics.internal.monitor.MonitorMetricsHandler I CWPMI2003I: Monitoring metrics can be retrieved through mpMetrics.
[12/09/2022, 16:33:57:341 CEST] 00000023 254-io.openliberty.microprofile.metrics.internal.3.0.monitor E CWWKE0701E: FrameworkEvent ERROR org.osgi.framework.ServiceException: Exception in org.apache.felix.scr.impl.manager.SingleComponentManager.getService()

**Comment by jhanders34** [comment]
Did you previously start the server with a different set of features initially?  If so does starting with `--clean` resolve the issue?

**Comment by sdehors-ibm** [comment]
indeed the --clean solved the issue.
Thanks
