### ISSUE TITLE
Ensure work done by OpenAPIUIBundlesUpdater is not ongoing when doing a checkpoint

### ISSUE THREAD

**Issue by anjumfatima90** [OpenLiberty/open-liberty#22477]
The thread continually sleeps for 500 ms in a loop until the expected number of services is available in these three implementations of a method `waitForBundlesToStart(Set<Bundle> openAPIUIBundles)` in the following classes.
```
com.ibm.ws.openapi31.customization.OpenAPIUIBundlesUpdater
com.ibm.ws.microprofile.openapi.impl.OpenAPIUIBundlesUpdater
io.openliberty.microprofile.openapi20.internal.css.OpenAPIUIBundlesUpdater
```
The JVM Process looks like below:
```
4XESTACKTRACE                at java/lang/Thread.sleepImpl(Native Method)
4XESTACKTRACE                at java/lang/Thread.sleep(Thread.java:991)
4XESTACKTRACE                at java/lang/Thread.sleep(Thread.java:974)
4XESTACKTRACE                at io/openliberty/microprofile/openapi20/internal/css/OpenAPIUIBundlesUpdater.waitForBundlesToStart(OpenAPIUIBundlesUpdater.java:336)
4XESTACKTRACE                at io/openliberty/microprofile/openapi20/internal/css/OpenAPIUIBundlesUpdater.updateResources(OpenAPIUIBundlesUpdater.java:70)
5XESTACKTRACE                   (entered lock: io/openliberty/microprofile/openapi20/internal/css/OpenAPIUIBundlesUpdater@0x0000000612293DF0, entry count: 1)
4XESTACKTRACE                at io/openliberty/microprofile/openapi20/internal/css/CustomCSSWABUpdater.restoreDefaults(CustomCSSWABUpdater.java:41)
4XESTACKTRACE                at io/openliberty/microprofile/openapi20/internal/css/CustomCSSProcessor.lambda$processCSSUpdates$0(CustomCSSProcessor.java:241)
5XESTACKTRACE                   (entered lock: java/lang/Object@0x00000006121D30F8, entry count: 1)
4XESTACKTRACE                at io/openliberty/microprofile/openapi20/internal/css/CustomCSSProcessor$$Lambda$220/0x0000000000000000.run(Bytecode PC:8)
4XESTACKTRACE                at java/util/concurrent/Executors$RunnableAdapter.call(Executors.java:515(Compiled Code))
4XESTACKTRACE                at java/util/concurrent/FutureTask.run(FutureTask.java:264)
4XESTACKTRACE                at com/ibm/ws/threading/internal/ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:245)
4XESTACKTRACE                at java/util/concurrent/ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128(Compiled Code))
4XESTACKTRACE                at java/util/concurrent/ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
4XESTACKTRACE                at java/lang/Thread.run(Thread.java:839)
```

1. Why not use service events to count the available services to be event based instead of polling based?
2. We would like to have this work completed on the checkpoint side completely to avoid the work on the restore side.  Any issues with that?  If so then we suspect the work should be entirely done on the restore side to avoid whatever concerns there would be to do all the work on the checkpoint side.

**Comment by tjwatson** [comment]
@KeenanMcCarthy close this one if you are done.
