### ISSUE TITLE
WebService-Client Failure after upgrading to 22.0.0.8

### ISSUE THREAD

**Issue by c-koell** [OpenLiberty/open-liberty#22560]
**Describe the bug**  
After upgrading to 22.0.0.8 a working WebService-Client throws SoapException -> local part cannot be "null" when creating a QName
[https://openliberty.io/blog/2022/08/02/separate-stack-trace-22008.html](https://openliberty.io/blog/2022/08/02/separate-stack-trace-22008.html#jaxws) describes that there was a update in the underlying layer.

**Steps to Reproduce**  
WebService-Client works fine with server version < 22.0.0.8. After upgrading the code breaks.

**Diagnostic information:**  
 - OpenLiberty Version: 22.0.0.8
 - Affected feature(s) jaxws-2.2
 - Java Version: Eclipse OpenJ9 VM, Version 17.0.4.1+1

**Comment by neuwerk** [comment]
@c-koell thank you so much for opening this issue and bringing it to our attention! I do have a couple of questions, first is there anyway you can provide the stack trace for the failure? Realize that might not always be possible, but if so that'd be helpful for initial debugging. Second and even better for debugging, could you provide any info on how to recreate the issue?

**Comment by c-koell** [comment]
Hi @neuwerk ! Thank you for your quick response. 

This is the stacktrace of the SOAPFaultException
```
[INFO] [err] javax.xml.ws.soap.SOAPFaultException: local part cannot be "null" when creating a QName
[INFO] [err] 	at org.apache.cxf.jaxws.JaxWsClientProxy.mapException(JaxWsClientProxy.java:195)
[INFO] [err] 	at [internal classes]
[INFO] [err] 	at jdk.proxy26/jdk.proxy26.$Proxy137.get(Unknown Source)
[INFO] [err] 	at a.g.t.c.b.s.WebServiceClient.get(WebServiceClient.java:50)
[INFO] [err] 	at a.g.t.c.b.ejb.SessionBean.get(SessionBean.java:65)
[INFO] [err] 	at jdk.internal.reflect.GeneratedMethodAccessor1018.invoke(Unknown Source)
[INFO] [err] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[INFO] [err] 	at com.ibm.ejs.container.EJSContainer.invokeProceed(EJSContainer.java:4886)
[INFO] [err] 	at [internal classes]
[INFO] [err] 	at jdk.internal.reflect.GeneratedMethodAccessor1017.invoke(Unknown Source)
[INFO] [err] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[INFO] [err] 	at com.ibm.ejs.container.interceptors.InterceptorProxy.invokeInterceptor(InterceptorProxy.java:189)
[INFO] [err] 	at [internal classes]
[INFO] [err] 	at jdk.internal.reflect.GeneratedMethodAccessor1016.invoke(Unknown Source)
[INFO] [err] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[INFO] [err] 	at com.ibm.ejs.container.interceptors.InterceptorProxy.invokeInterceptor(InterceptorProxy.java:189)
[INFO] [err] 	at [internal classes]
[INFO] [err] 	at a.g.t.c.b.s.ejb.EJSLocalNSLSessionBean_1651b89f.get(EJSLocalNSLSessionBean_1651b89f.java)
[INFO] [err] 	at a.g.t.c.b.s..GetCommand.execute(GetCommand.java:41)
[INFO] [err] 	at a.g.t.c.b.s..GetCommand.execute(GetCommand.java:13)
[INFO] [err] 	at a.g.t.c.b.s..client.jaxrs.service.ServiceCommandController.execute(ServiceCommandController.java:127)
[INFO] [err] 	at a.g.t.c.b.s..rest.ServiceCommandController.execute(ServiceCommandController.java:27)
[INFO] [err] 	at a.g.t.c.b.s..rest.ServiceCommandController$Proxy$_$$_WeldClientProxy.execute(Unknown Source)
[INFO] [err] 	at jdk.internal.reflect.GeneratedMethodAccessor1008.invoke(Unknown Source)
[INFO] [err] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[INFO] [err] 	at com.ibm.ws.jaxrs20.cdi.component.JaxRsFactoryImplicitBeanCDICustomizer.serviceInvoke(JaxRsFactoryImplicitBeanCDICustomizer.java:350)
[INFO] [err] 	at [internal classes]
[INFO] [err] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:706)
[INFO] [err] 	at com.ibm.websphere.jaxrs.server.IBMRestServlet.service(IBMRestServlet.java:96)
[INFO] [err] 	at [internal classes]
[INFO] [err] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[INFO] [err] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[INFO] [err] 	at java.base/java.lang.Thread.run(Thread.java:858)
[INFO] [err] Caused by: 
[INFO] [err] java.lang.IllegalArgumentException: local part cannot be "null" when creating a QName
[INFO] [err] 	at java.xml/javax.xml.namespace.QName.<init>(QName.java:185)
[INFO] [err] 	at java.xml/com.sun.xml.internal.stream.events.AttributeImpl.<init>(AttributeImpl.java:80)
[INFO] [err] 	at java.xml/com.sun.xml.internal.stream.events.AttributeImpl.<init>(AttributeImpl.java:76)
[INFO] [err] 	at java.xml/com.sun.xml.internal.stream.events.NamespaceImpl.<init>(NamespaceImpl.java:50)
[INFO] [err] 	at java.xml/com.sun.xml.internal.stream.events.XMLEventFactoryImpl.createNamespace(XMLEventFactoryImpl.java:160)
[INFO] [err] 	at org.apache.cxf.binding.soap.interceptor.ReadHeadersInterceptor$HeadersProcessor.process(ReadHeadersInterceptor.java:369)
[INFO] [err] 	at [internal classes]
```

Can/should i enable some trace ?

**Comment by c-koell** [comment]
Any news here ?
thanks !

**Comment by c-koell** [comment]
@neuwerk any news here ? .. thanks

**Comment by c-koell** [comment]
With openliberty 23.0.0.10 i see no more failures. I don't what version fixed the problem but thats ok for me ;-)
