### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException when PurgeDataDuringClose=true

### ISSUE THREAD

**Issue by loriadi** [OpenLiberty/open-liberty#22660]
**Describe the bug**  
When the custom transport property PurgeDataDuringClose is set to true, java.lang.ArrayIndexOutOfBoundsException appears in the log.  The stack trace may be similar to the following:

 java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 0

	at com.ibm.ws.ssl.channel.impl.SSLUtils.allocateByteBuffers(SSLUtils.java:620)

	at com.ibm.ws.ssl.channel.impl.SSLReadServiceContext.getDecryptedNetworkBuffers(SSLReadServiceContext.java:892)

	at com.ibm.ws.ssl.channel.impl.SSLReadServiceContext.decryptMessage(SSLReadServiceContext.java:1211)

	at com.ibm.ws.ssl.channel.impl.SSLReadServiceContext.read(SSLReadServiceContext.java:304)

	at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.close(HttpInboundLink.java:833)

	at com.ibm.wsspi.channel.base.InboundApplicationLink.close(InboundApplicationLink.java:58)

	at com.ibm.ws.webcontainer.channel.WCChannelLink.close(WCChannelLink.java:333)

	at com.ibm.ws.webcontainer.channel.WCChannelLink.complete(WCChannelLink.java:1271)

	at com.ibm.ws.webcontainer.channel.WCChannelLink.localComplete(WCChannelLink.java:996)

	at com.ibm.ws.webcontainer.channel.WCChannelLink.finishBufferAsynch(WCChannelLink.java:871)

	at com.ibm.ws.webcontainer.channel.WCChannelLink.finishBufferResponse(WCChannelLink.java:835)

	at com.ibm.ws.webcontainer.channel.WCChannelLink.complete(WCChannelLink.java:1254)

	at com.ibm.ws.http.channel.inbound.impl.HttpISCWriteCallback.complete(HttpISCWriteCallback.java:122)

	at com.ibm.ws.ssl.channel.impl.SSLWriteServiceContext.complete(SSLWriteServiceContext.java:794)

	at com.ibm.ws.tcp.channel.impl.AioWriteCompletionListener.futureCompleted(AioWriteCompletionListener.java:165)

	at com.ibm.io.async.AbstractAsyncFuture.invokeCallback(AbstractAsyncFuture.java:217)

	at com.ibm.io.async.AsyncChannelFuture.fireCompletionActions(AsyncChannelFuture.java:161)

	at com.ibm.io.async.AsyncFuture.completed(AsyncFuture.java:138)

	at com.ibm.io.async.ResultHandler.complete(ResultHandler.java:204)

	at com.ibm.io.async.ResultHandler.runEventProcessingLoop(ResultHandler.java:775)

	at com.ibm.io.async.ResultHandler$2.run(ResultHandler.java:905)

	at com.ibm.ws.util.ThreadPool$Worker.run(ThreadPool.java:1909)

**Steps to Reproduce**  
Set the transport property PurgeDataDuringClose to true and have the server receive and send normal HTTP requests and responses.

**Expected behavior**  
With the transport property PurgeDataDuringClose set to true, HTTP requests should be received and responses sent with no errors.

**Diagnostic information:**  
 - OpenLiberty Version: All
 - Affected feature(s): All, but only if the custom transport property PurgeDataDuringClose is set to true
 - Java Version: n/a
 - server.xml configuration: n/a

**Additional context**  
n/a

**Comment by mbroz2** [comment]
@loriadi please update the description of this `release bug` using the [bug report template](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=&labels=release+bug&template=bug_report.md&title=)"

**Comment by loriadi** [comment]
@mbroz2  Done
