### ISSUE TITLE
mpMetrics-5.0: Out of Memory error with small heap.

### ISSUE THREAD

**Issue by jdmcclur** [OpenLiberty/open-liberty#22699]
When running with a test build of the new mpMetrics-5.0/microProfile 6.0 smallrye/micrometer implementation, I am seeing an Out of Memory Error after running for a short time with a heap of `256m`.  Increasing the heap to `512m` fixes the issue.  I am raising this issue because previous versions of mpMetrics ran fine with a max heap of 256m.

It looks like the new implementation is recording data for different percentiles of response times (I think), and some of the data structures end up being very large. Specifically, there are a few instances of this class, with activeCounts and inactiveCounts having a very large size: https://github.com/HdrHistogram/HdrHistogram/blob/master/src/main/java/org/HdrHistogram/ConcurrentHistogram.java

Here is a java stack when the OOM occurs:
```
3XMTHREADINFO      "Default Executor-thread-3" J9VMThread:0x0000000002578F00, omrthread_t:0x00007F41B80037E0, java/lang/Thread:0x00000000F09AD8D8, state:R, prio=5
3XMJAVALTHREAD            (java/lang/Thread getId:0x30, isDaemon:true)
3XMTHREADINFO1            (native thread ID:0x5FBE, native priority:0x5, native policy:UNKNOWN, vmstate:R, vm thread flags:0x00001020)
3XMTHREADINFO2            (native stack address range from:0x00007F42251C2000, to:0x00007F4225202000, size:0x40000)
3XMCPUTIME               CPU usage total: 6.216631678 secs, current category="Application"
3XMHEAPALLOC             Heap bytes allocated since last GC cycle=0 (0x0)
3XMTHREADINFO3           Java callstack:
4XESTACKTRACE                at java/util/concurrent/atomic/AtomicLongArray.<init>(AtomicLongArray.java:81)
4XESTACKTRACE                at org/HdrHistogram/ConcurrentHistogram$AtomicLongArrayWithNormalizingOffset.<init>(ConcurrentHistogram.java:651)
4XESTACKTRACE                at org/HdrHistogram/ConcurrentHistogram.allocateArray(ConcurrentHistogram.java:333)
4XESTACKTRACE                at org/HdrHistogram/ConcurrentHistogram.resize(ConcurrentHistogram.java:356)
4XESTACKTRACE                at org/HdrHistogram/DoubleHistogram.handleShiftValuesException(DoubleHistogram.java:592)
4XESTACKTRACE                at org/HdrHistogram/DoubleHistogram.shiftCoveredRangeToTheLeft(DoubleHistogram.java:555)
4XESTACKTRACE                at org/HdrHistogram/DoubleHistogram.autoAdjustRangeForValueSlowPath(DoubleHistogram.java:440)
5XESTACKTRACE                   (entered lock: org/HdrHistogram/DoubleRecorder$InternalConcurrentDoubleHistogram@0x00000000F18E5820, entry count: 1)
4XESTACKTRACE                at org/HdrHistogram/DoubleHistogram.autoAdjustRangeForValue(DoubleHistogram.java:411)
4XESTACKTRACE                at org/HdrHistogram/DoubleHistogram.recordSingleValue(DoubleHistogram.java:364(Compiled Code))
4XESTACKTRACE                at org/HdrHistogram/DoubleHistogram.recordValue(DoubleHistogram.java:289(Compiled Code))
4XESTACKTRACE                at org/HdrHistogram/DoubleRecorder.recordValue(DoubleRecorder.java:112(Compiled Code))
4XESTACKTRACE                at io/micrometer/core/instrument/distribution/TimeWindowPercentileHistogram.recordLong(TimeWindowPercentileHistogram.java:58(Compiled Code))
4XESTACKTRACE                at io/micrometer/core/instrument/distribution/TimeWindowPercentileHistogram.recordLong(TimeWindowPercentileHistogram.java:35(Compiled Code))
4XESTACKTRACE                at io/micrometer/core/instrument/distribution/AbstractTimeWindowHistogram.recordLong(AbstractTimeWindowHistogram.java:224(Compiled Code))
4XESTACKTRACE                at io/micrometer/core/instrument/distribution/TimeWindowPercentileHistogram.recordLong(TimeWindowPercentileHistogram.java:35(Compiled Code))
4XESTACKTRACE                at io/micrometer/core/instrument/AbstractTimer.record(AbstractTimer.java:182(Compiled Code))
4XESTACKTRACE                at io/micrometer/core/instrument/Timer.record(Timer.java:118(Compiled Code))
4XESTACKTRACE                at io/micrometer/core/instrument/composite/CompositeTimer.record(CompositeTimer.java:57(Compiled Code))
4XESTACKTRACE                at io/smallrye/metrics/legacyapi/TimerAdapter.update(TimerAdapter.java:92(Compiled Code))
4XESTACKTRACE                at io/openliberty/restfulws/mpmetrics/RestfulWsMonitorFilter.filter(RestfulWsMonitorFilter.java:212(Compiled Code))
```

**Comment by jdmcclur** [comment]
This has been fixed in small-rye metrics.
