### ISSUE TITLE
SVT: console.log does not switch to basic format from json format after server.xml was updated

### ISSUE THREAD

**Issue by tkulik** [OpenLiberty/open-liberty#2272]
Testing JSON logging for liberty.  I have installed liberty build from here:
https://rtpgsa.ibm.com/gsa/rtpgsa/projects/l/liberty.build/liberty/WASX.LIBERTY/daily/20180212-1300.44.linux/linux/zipper/externals/installables/

Note, this is not an open liberty, this is commercial.  

And deployed the following file:
java -jar wlp-base-runtime-18.0.0.1.jar

Initially I had the following setting in my liberty server.xml file:

logging messageFormat="basic" messageSource="message,accessLog"
logging consoleFormat="json" consoleSource="message,accessLog" consoleLogLevel="info"

And I could see that json formatted messages were written to console.log file.  And text formatted messages were written to messages.log.    Then I changed the settings in server.xml as follows:

logging messageFormat="json" messageSource="message,accessLog"
logging consoleFormat="basic" consoleSource="message,accessLog" consoleLogLevel="info"

And I did not restart my liberty server.  These changes should be picked up automatically.

I expected that now text formatted messages would go to console.log and json formatted messages would go to messages.log.   Ran some stress test to populate messages.log and accessLog.  

I see that now json formatted messages are written to messages.log file as expected,  and I can see that they are written to the same file which originally had messages in text format.   

But console.log is still getting messages in json format,  which is the problem. They were supposed to be in text format now.   And in addition to that some messages look like in a mixed format,  both json and text:

{"type":"liberty_accesslog","host":"json-logging.rtp.raleigh.ibm.com","ibm_userDir":"\/opt\/liberty\/wlp\/usr\/","ibm_serverName":"server1","ibm_uriPath":"\/SuperAddressBookWAR\/login","ibm_requestMethod":"GET","ibm_requestHost":"9.42.41.126","ibm_requestPort":"9080","ibm_remoteHost":"9.42.28.52","ibm_userAgent":"Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.2; SV1; .NET CLR 1.1.4322)","ibm_requestProtocol":"HTTP\/1.1","ibm_bytesReceived":717,"ibm_responseCode":200,"ibm_elapsedTime":868165,"ibm_datetime":"2018-02-16T17:19:19.110-0500","ibm_sequence":"1518819558231_00000000002EA"}
builder com.cloudant.client.api.ClientBuilder@2fbcdf60
no user found , please reinput
[ERROR   ] SRVE0777E: Exception thrown by application class 'com.ibm.ws.webcontainer.webapp.WebAppRequestDispatcher.dispatch:1,154'
java.lang.IllegalStateException: Cannot forward. Response already committed.
        at com.ibm.ws.webcontainer.webapp.WebAppRequestDispatcher.dispatch(WebAppRequestDispatcher.java:1154)
        at [internal classes]
        at com.ibm.spring.certification.servlet.LoginServlet.doWork(LoginServlet.java:68)
        at com.ibm.spring.certification.servlet.LoginServlet.doGet(LoginServlet.java:37)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
        at [internal classes]

[WARNING ] WARNING: Cannot set status. Response already committed.
builder com.cloudant.client.api.ClientBuilder@3aaeaaa1
no user found , please reinput
{"type":"liberty_accesslog","host":"json-logging.rtp.raleigh.ibm.com","ibm_userDir":"\/opt\/liberty\/wlp\/usr\/","ibm_serverName":"server1","ibm_uriPath":"\/SuperAddressBookWAR\/login","ibm_requestMethod":"POST","ibm_requestHost":"9.42.41.126","ibm_requestPort":"9080","ibm_remoteHost":"9.42.28.52","ibm_userAgent":"Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.2; SV1; .NET CLR 1.1.4322)","ibm_requestProtocol":"HTTP\/1.1","ibm_bytesReceived":717,"ibm_responseCode":200,"ibm_elapsedTime":603269,"ibm_datetime":"2018-02-16T17:19:20.323-0500","ibm_sequence":"1518819559710_00000000002EB"}
builder com.cloudant.client.api.ClientBuilder@2fec4e56

Then only after I restarted liberty server I could see messages in text format inside console.log. 

Also, if I set console.log to have json format, restart liberty server, and run some stress, then I see  properly formatted json messages inside console.log file.

**Comment by tkulik** [comment]
here is my server.xml file:

<server description="new server">

    
    <featureManager>
        <feature>localConnector-1.0</feature>
        <feature>jaxrs-2.0</feature>
        <feature>cloudant-1.0</feature>
        <feature>jndi-1.0</feature>
        <feature>jsp-2.3</feature>
        <feature>ejbLite-3.2</feature>
    </featureManager>


<httpEndpoint id="defaultHttpEndpoint"
                  host="*"
                  httpPort="9080"
                  httpsPort="9443" >
 <accessLogging logFormat="%h %u %t %r %s %b %D %{User-agent}i" filepath="${server.output.dir}/logs/http_defaultEndpoint_access.log"/>
 </httpEndpoint>

        
        <applicationManager autoExpand="true"/>

        <library id="cloudantLib">
        <fileset dir="${server.config.dir}" includes="java-cloudant-lib-2.6.2.jar"/>
    </library>

    <cloudant id="builder" jndiName="cloudant/builder" libraryRef="cloudantLib" password="984ad3fce2d3164f7156eda245be6593240e6c9aa4455152544fd8cc24680356" readTimeout="5m" url="https://7a51d655-20cf-4114-b7aa-148277d16a77-bluemix:984ad3fce2d3164f7156eda245be6593240e6c9aa4455152544fd8cc24680356@7a51d655-20cf-4114-b7aa-148277d16a77-bluemix.cloudant.com/" username="7a51d655-20cf-4114-b7aa-148277d16a77-bluemix"/>

    <applicationMonitor updateTrigger="mbean"/>

     <logging messageFormat="json" messageSource="message,accessLog"/>
     <logging consoleFormat="basic" consoleSource="message,accessLog" consoleLogLevel="info"/>

    <logging traceSpecification="*=all" />

    <enterpriseApplication id="SuperAddressBookEar8Cloudant" location="SuperAddressBookEar8Cloudant-0.0.1-SNAPSHOT.ear" name="SuperAddressBookEar8Cloudant">
        <classloader commonLibraryRef="cloudantLib"/>
    </enterpriseApplication>
</server>

**Comment by tkulik** [comment]
I have reproduced this problem on a newer build wlp-1.0.20.20180220-1350 from https://libfsfe01.hursley.ibm.com/liberty/dev/Xo/release/.  And I can still see the same problem.  So now console log is set to basic format, but i see these kind of messages:

[ERROR   ] SRVE0777E: Exception thrown by application class 'com.ibm.ejs.container.util.ExceptionUtil.EJBException:460'
javax.ejb.EJBException: See nested exception; nested exception is: com.cloudant.client.org.lightcouch.TooManyRequestsException: 429 Too Many Requests: too_many_requests: You've exceeded your current limit of 5 requests per second for query class. Please try later.
        at com.ibm.ejs.container.util.ExceptionUtil.EJBException(ExceptionUtil.java:460)
        at [internal classes]
        at com.ibm.spring.certification.direct.dao.EJSLocal0SLContactDocImpl_2b3ff50d.findOne(EJSLocal0SLContactDocImpl_2b3ff50d.java)
        at com.ibm.spring.certification.servlet.LoginServlet.doWork(LoginServlet.java:56)
        at com.ibm.spring.certification.servlet.LoginServlet.doGet(LoginServlet.java:37)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
        at [internal classes]
Caused by: com.cloudant.client.org.lightcouch.TooManyRequestsException: 429 Too Many Requests: too_many_requests: You've exceeded your current limit of 5 requests per second for query class. Please try later.
        at com.cloudant.client.org.lightcouch.CouchDbClient.execute(CouchDbClient.java:521)
        at com.cloudant.client.org.lightcouch.CouchDbClient.executeToInputStream(CouchDbClient.java:572)
        at com.cloudant.client.api.Database.findByIndex(Database.java:377)
        at com.cloudant.client.api.Database.findByIndex(Database.java:333)
        at com.ibm.spring.certification.direct.dao.impl.ContactDocImpl.findOne(ContactDocImpl.java:123)
        ... 5 more

[WARNING ] WARNING: Cannot set status. Response already committed.
{"type":"liberty_accesslog","host":"json-final.rtp.raleigh.ibm.com","ibm_userDir":"\/liberty2\/wlp\/usr\/","ibm_serverName":"server1","ibm_uriPath":"\/SuperAddressBookWAR\/jaxrs\/contacts\/list\/bob_113","ibm_requestMethod":"GET","ibm_queryString":"_=10","ibm_requestHost":"9.42.17.225","ibm_requestPort":"9080","ibm_remoteHost":"9.42.28.52","ibm_userAgent":"Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.2; SV1; .NET CLR 1.1.4322)","ibm_requestProtocol":"HTTP\/1.1","ibm_bytesReceived":237598,"ibm_responseCode":200,"ibm_elapsedTime":1604461,"ibm_datetime":"2018-02-20T19:00:30.376-0500","ibm_sequence":"1519171228754_00000000002C3"}

Looks like the problem is that accessLog messages are still coming in to console.log in a json format,  but they should stop since console.log is configured for basic format.   But regular messages for console.log are coming in text format, which is correct.

**Comment by tkulik** [comment]
Verified this defect using build wlp-1.0.20.integration. Working properly now.  Closing defect.
