### ISSUE TITLE
Ensure that we get a unique "state" value for each request

### ISSUE THREAD

**Issue by c00crane** [OpenLiberty/open-liberty#22726]
Testing @OpenIdAuthenticationMechanismDefinition:
My test class makes requests to unique applications.  I'm getting the same state for these requests.
We need to ensure that we get a unique value for the state on each request.

[npe.zip](https://github.com/OpenLiberty/open-liberty/files/9669216/npe.zip)

**Comment by ayoho** [comment]
I'm seeing two places where a state value is generated in the trace and both instances are unique:
```
[9/28/22, 16:59:34:489 CDT] 0000003c id=b836d910 rity.oidcclientcore.authentication.AuthorizationRequestUtils < generateStateValue Exit  
                                                                                                               001664402374487nUb65751Z
...
[9/28/22, 16:59:45:363 CDT] 00000051 id=f2dcc5c4 rity.oidcclientcore.authentication.AuthorizationRequestUtils < generateStateValue Exit  
                                                                                                               001664402385363UHa2omhBd
```

However in the `testSimplestAnnotatedServlet_WithEL_EE10_FEATURES` test case, when the `OpenIdContextLogger` goes to log the stored value, it'll call `OpenIdContextImpl.getStoredValue()`: https://github.com/OpenLiberty/open-liberty/blob/integration/dev/io.openliberty.security.jakartasec.3.0.internal/src/io/openliberty/security/jakartasec/identitystore/OpenIdContextImpl.java#L125:
```Java
    public <T> Optional<T> getStoredValue(HttpServletRequest request, HttpServletResponse response, String key) {
        T value = null;
        Storage storage = getStorage(request, response);

        if (OpenIdConstant.ORIGINAL_REQUEST.equals(key)) {
            String storageName = OidcStorageUtils.getOriginalReqUrlStorageKey(state);
            value = (T) storage.get(storageName);
        }

        return Optional.of(value);
    }
```

Looks like the state value it's using (`001664402374487nUb65751Z`) is the one that was generated in the previous test (`testSimplestAnnotatedServlet_withoutEL_EE10_FEATURES`):
```
[9/28/22, 16:59:31:384 CDT] 00000041 id=00000000 SystemOut                                                    O STARTING TEST CASE: testSimplestAnnotatedServlet_withoutEL_EE10_FEATURES
...
[9/28/22, 16:59:34:489 CDT] 0000003c id=b836d910 rity.oidcclientcore.authentication.AuthorizationRequestUtils < generateStateValue Exit  
                                                                                                               001664402374487nUb65751Z
...
[9/28/22, 16:59:45:124 CDT] 00000042 id=00000000 SystemOut                                                    O ReStoringConfig TEST CASE: testSimplestAnnotatedServlet_withoutEL_EE10_FEATURES
...
[9/28/22, 16:59:45:170 CDT] 00000047 id=00000000 SystemOut                                                    O STARTING TEST CASE: testSimplestAnnotatedServlet_WithEL_EE10_FEATURES
...
[9/28/22, 16:59:45:770 CDT] 00000049 id=00000000 openliberty.security.oidcclientcore.storage.OidcStorageUtils > getOriginalReqUrlStorageKey Entry  
                                                                                                               001664402374487nUb65751Z
...
[9/28/22, 16:59:45:770 CDT] 00000049 id=47b13251 enliberty.security.oidcclientcore.storage.CookieBasedStorage < get Exit  
                                                                                                               null
[9/28/22, 16:59:45:808 CDT] 00000049 id=00000000 com.ibm.ws.webcontainer.util.ApplicationErrorUtils           E SRVE0777E: Exception thrown by application class 'java.util.Objects.requireNonNull:221'
java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:221)
	at java.base/java.util.Optional.<init>(Optional.java:107)
	at java.base/java.util.Optional.of(Optional.java:120)
	at io.openliberty.security.jakartasec.identitystore.OpenIdContextImpl.getStoredValue(OpenIdContextImpl.java:134)
```

Looks to me like the `OpenIdContext` that's being injected in `BaseCallbackServlet` is the context from the previous test.
