### ISSUE TITLE
Investigate why cookie is disappearing

### ISSUE THREAD

**Issue by c00crane** [OpenLiberty/open-liberty#22727]
I have tests that are using @OpenIdAuthenticationMechanismDefinition in the servlets.
After logging in, we try to get some info out of the OpenIdContext in our callback servlet

@Inject 
private OpenIdContext context;

context.getStoredValue(req, resp, OpenIdConstant.ORIGINAL_REQUEST)

we end up with an NPE:
[9/28/22, 16:59:45:808 CDT] 00000049 com.ibm.ws.webcontainer.util.ApplicationErrorUtils           E SRVE0777E: Exception thrown by application class 'java.util.Objects.requireNonNull:221'
java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:221)
	at java.base/java.util.Optional.<init>(Optional.java:107)
	at java.base/java.util.Optional.of(Optional.java:120)
	at io.openliberty.security.jakartasec.identitystore.OpenIdContextImpl.getStoredValue(OpenIdContextImpl.java:134)
	at oidc.client.base.utils.OpenIdContextLogger.logStoredValue(OpenIdContextLogger.java:217)
	at oidc.client.base.utils.OpenIdContextLogger.logStoredValues(OpenIdContextLogger.java:204)
	at oidc.client.base.utils.OpenIdContextLogger.logContext(OpenIdContextLogger.java:84)
	at oidc.client.base.servlets.BaseCallbackServlet.doGet(BaseCallbackServlet.java:39)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:527)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:614)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1258)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:746)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:443)
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.invokeTarget(WebAppFilterChain.java:193)
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:98)
	at com.ibm.ws.security.jaspi.JaspiServletFilter.doFilter(JaspiServletFilter.java:56)
	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:201)
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:91)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.doFilter(WebAppFilterManager.java:1002)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1140)
	at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:5058)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.handleRequest(DynamicVirtualHost.java:316)
	at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:1007)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:281)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1239)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:468)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:427)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:567)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:501)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:361)
	at com.ibm.ws.http.channel.internal.inbound.HttpICLReadCallback.complete(HttpICLReadCallback.java:70)
	at com.ibm.ws.channel.ssl.internal.SSLReadServiceContext$SSLReadCompletedCallback.complete(SSLReadServiceContext.java:1824)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:514)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueManager.java:584)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:968)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:1057)
	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:245)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

Teddy looked at my trace and saw the cookie disappearing.  We need to investigate why.

The server config specifies:
<httpSession cookieHttpOnly=“false” cookieName=“clientJSESSIONID”/>

[npe.zip](https://github.com/OpenLiberty/open-liberty/files/9669247/npe.zip)

**Comment by c00crane** [comment]
Here is the rp trace with webcontainer trace enabled

[npe2.zip](https://github.com/OpenLiberty/open-liberty/files/9677733/npe2.zip)

**Comment by c00crane** [comment]
tests still have getStoredValue call disabled - will enable and see if this still happening.

**Comment by c00crane** [comment]
It looks like this issue has been resolved.  We seem to have an issue with trying to retrieve an "storedValue" that doesn't exist - getStoredValue is throwing an NPE - I'll open a new issue for that.
