### ISSUE TITLE
Processing of java.util.logging.LoggingPermission results in FFDC

### ISSUE THREAD

**Issue by brideck** [OpenLiberty/open-liberty#22754]
**Describe the bug**  
If an application includes a permissions.xml file containing this permission:
```
        <permission>
           <class-name>java.util.logging.LoggingPermission</class-name>
           <name>control</name>
        </permission>
```

This results in the following FFDC being generated during permission processing:
```
java.lang.NoSuchMethodException: java.util.logging.LoggingPermission.<init>(java.lang.String)
        at java.base/java.lang.Class.newNoSuchMethodException(Class.java:647)
        at java.base/java.lang.Class.getConstructor(Class.java:690)
        at com.ibm.ws.classloading.java2sec.PermissionManager.createPermissionObject(PermissionManager.java:537)
        at com.ibm.ws.app.manager.module.internal.DeployedAppInfoBase.addPermissions(DeployedAppInfoBase.java:461)
        at com.ibm.ws.app.manager.module.internal.DeployedAppInfoBase.getProtectionDomain(DeployedAppInfoBase.java:406)
        at com.ibm.ws.app.manager.war.internal.WARDeployedAppInfo.createModuleClassLoader(WARDeployedAppInfo.java:98)
        at com.ibm.ws.app.manager.module.internal.ExtendedModuleInfoImpl.getClassLoader(ExtendedModuleInfoImpl.java:122)
        at com.ibm.ws.container.service.annocache.internal.ModuleAnnotationsImpl.<init>(ModuleAnnotationsImpl.java:196)
        at com.ibm.ws.container.service.annocache.internal.ModuleAnnotationsImpl.<init>(ModuleAnnotationsImpl.java:159)
        at com.ibm.ws.container.service.annocache.internal.WebAnnotationsImpl.<init>(WebAnnotationsImpl.java:89)
        at com.ibm.ws.container.service.annocache.internal.WebAnnotationsAdapterImpl.adapt(WebAnnotationsAdapterImpl.java:61)
        at com.ibm.ws.container.service.annocache.internal.WebAnnotationsAdapterImpl.adapt(WebAnnotationsAdapterImpl.java:33)
        at com.ibm.ws.adaptable.module.internal.AdapterFactoryServiceImpl.adapt(AdapterFactoryServiceImpl.java:200)
        at com.ibm.ws.adaptable.module.internal.AdaptableContainerImpl.adapt(AdaptableContainerImpl.java:174)
        at com.ibm.ws.container.service.annocache.AnnotationsBetaHelper.getWebAnnotations(AnnotationsBetaHelper.java:268)
        at com.ibm.ws.webcontainer.osgi.container.config.WebAppConfigurator.setWebAnnotations(WebAppConfigurator.java:86)
        at com.ibm.ws.webcontainer.osgi.container.config.WebAppConfigurator.configure(WebAppConfigurator.java:422)
        at com.ibm.ws.webcontainer.osgi.container.config.WebAppConfigurationAdapter.adapt(WebAppConfigurationAdapter.java:119)
        at com.ibm.ws.webcontainer.osgi.container.config.WebAppConfigurationAdapter.adapt(WebAppConfigurationAdapter.java:43)
        at com.ibm.ws.adaptable.module.internal.AdapterFactoryServiceImpl.adapt(AdapterFactoryServiceImpl.java:200)
        at com.ibm.ws.adaptable.module.internal.AdaptableContainerImpl.adapt(AdaptableContainerImpl.java:174)
        at com.ibm.ws.webcontainer.osgi.WebContainer.createModuleMetaData(WebContainer.java:861)
        at com.ibm.ws.app.manager.module.internal.ModuleHandlerBase.createModuleMetaData(ModuleHandlerBase.java:63)
        at com.ibm.ws.app.manager.module.internal.SimpleDeployedAppInfoBase$ModuleContainerInfoBase.createModuleMetaData(SimpleDeployedAppInfoBase.java:189)
        at com.ibm.ws.app.manager.module.internal.SimpleDeployedAppInfoBase.preDeployApp(SimpleDeployedAppInfoBase.java:532)
        at com.ibm.ws.app.manager.module.internal.SimpleDeployedAppInfoBase.installApp(SimpleDeployedAppInfoBase.java:508)
        at com.ibm.ws.app.manager.module.internal.DeployedAppInfoBase.deployApp(DeployedAppInfoBase.java:349)
        at com.ibm.ws.app.manager.war.internal.WARApplicationHandlerImpl.install(WARApplicationHandlerImpl.java:65)
        at com.ibm.ws.app.manager.internal.statemachine.StartAction.execute(StartAction.java:161)
        at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.enterState(ApplicationStateMachineImpl.java:1357)
        at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.performAction(ApplicationStateMachineImpl.java:1202)
        at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.run(ApplicationStateMachineImpl.java:909)
        ...
```

**Steps to Reproduce**  
Install and start an application containing the specified permission.

**Expected behavior**  
Application start should complete with no FFDC generated.

**Diagnostic information:**  
 - OpenLiberty Version: At least as far back as 21.0.0.12
 - Affected feature(s) jakartaee-10.0, jakartaee-9.1 (does not seem to occur with jakartaee-8.0)

**Comment by emilytee** [comment]
Typically, Java Permissions have 2 constructors:  PermissionClass with target and action, and one with just the target.
In the case of LoggingPermission, there is only one constructor with both target and action, even though it accepts no actions.

Updating the PermissionManager createPermission method to check if this is a LoggingPermission and call the constructor with the target and a null action.
