### ISSUE TITLE
Error thrown on Oracle JVM -> "no such provider: SunJCE" 

### ISSUE THREAD

**Issue by una-tapa** [OpenLiberty/open-liberty#2278]
Continuation of #2254 

```Exception = java.security.NoSuchProviderException
Source = com.ibm.ws.security.token.ltpa.internal.LTPAKeyInfoManager
probeid = 156
Stack Dump = java.security.NoSuchProviderException: no such provider: SunJCE
	at sun.security.jca.GetInstance.getService(GetInstance.java:83)
	at javax.crypto.b.a(Unknown Source)
	at javax.crypto.SecretKeyFactory.getInstance(Unknown Source)
	at com.ibm.ws.crypto.ltpakeyutil.LTPACrypto.constructSecretKey(LTPACrypto.java:577)
	at com.ibm.ws.crypto.ltpakeyutil.LTPACrypto.decrypt(LTPACrypto.java:644)
```

**Comment by ewhoch** [comment]
Won't be an issue since the introducing PR was reverted, i'd suggest moving discussion back to #2068 and spinning off new PRs there instead of making a web of problems/fixes.
