### ISSUE TITLE
IllegalStateException in test case required_spec109_mustIssueOnSubscribeForNonNullSubscriber

### ISSUE THREAD

**Issue by mbuamuh** [OpenLiberty/open-liberty#22805]
The test case required_spec109_mustIssueOnSubscribeForNonNullSubscriber in the class org.reactivestreams.tck.IdentityProcessorVerification and org.reactivestreams.tck.PublisherVerification, fails with an IllegalStateException. The IllegalStateException is caught and thrown as a NullPointerException in OpenLiberty

**Comment by Azquelt** [comment]
This is a failure we very occasionally see in our builds (ref: RTC286531). I've added the stack trace below.

The error occurs when running the TCK verification test [required_spec109_mustIssueOnSubscribeForNonNullSubscriber](https://github.com/reactive-streams/reactive-streams-jvm/blob/v1.0.3/tck/src/main/java/org/reactivestreams/tck/PublisherVerification.java#L476) against in [onErrorResumeWith()](https://github.com/eclipse/microprofile-reactive-streams-operators/blob/1.0.1/tck/src/main/java/org/eclipse/microprofile/reactive/streams/operators/tck/spi/OnErrorResumeStageVerification.java#L199)

Our implementation for reactive-streams-operators 1.0 is smallrye-reactive-streams-operators which is no longer maintained. As this situation is quite obscure and the failure is very rare, I'd recommend ignoring the failure for now.

```
java.lang.NullPointerException: Actually not, but can't throw other exceptions due to RS
	at io.reactivex.Flowable.subscribe(Flowable.java:14927)
	at io.smallrye.reactive.streams.utils.recovery.OnErrorResumeWith.subscribeActual(OnErrorResumeWith.java:36)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.internal.operators.flowable.FlowableMap.subscribeActual(FlowableMap.java:37)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.Flowable.subscribe(Flowable.java:14868)
	at io.smallrye.reactive.streams.utils.WrappedProcessor.subscribe(WrappedProcessor.java:26)
	at org.reactivestreams.tck.PublisherVerification$11.run(PublisherVerification.java:483)
	at org.reactivestreams.tck.PublisherVerification.activePublisherTest(PublisherVerification.java:1138)
	at org.reactivestreams.tck.PublisherVerification.required_spec109_mustIssueOnSubscribeForNonNullSubscriber(PublisherVerification.java:477)
	at org.reactivestreams.tck.IdentityProcessorVerification.required_spec109_mustIssueOnSubscribeForNonNullSubscriber(IdentityProcessorVerification.java:311)
	at org.eclipse.microprofile.reactive.streams.operators.tck.arquillian.ReactiveStreamsArquillianTck.runAllTckTests(ReactiveStreamsArquillianTck.java:105)
[...]
Caused by: java.lang.IllegalStateException: Illegal transition - subscribe happened in the COMPLETE state
	at io.smallrye.reactive.streams.utils.ConnectableProcessor.subscribe(ConnectableProcessor.java:64)
	at io.reactivex.internal.operators.flowable.FlowableFromPublisher.subscribeActual(FlowableFromPublisher.java:29)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	... 132 more
```
