### ISSUE TITLE
java.lang.IllegalArgumentException occurs in FacesConfigurator#purgeConfiguration

### ISSUE THREAD

**Issue by volosied** [OpenLiberty/open-liberty#23005]
**Describe the bug**  
The following exception can occur in JSF.
```
java.lang.IllegalArgumentException: object is not an instance of declaring class
…
at java.lang.reflect.Method.invoke(Method.java:508)
org.apache.myfaces.config.FacesConfigurator.purgeConfiguration(FacesConfigurator.java:555)
at org.apache.myfaces.config.FacesConfigurator.update(FacesConfigurator.java:485)
at org.apache.myfaces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:136)
```

**Steps to Reproduce**  
1) JSF Application is in development mode
2) Update occurs to the faces-config.xml or the timestamp is changed. (The reporting scenario had the application build in a different time zone, and that may have caused JSF think changes were made) 
3) Visit any JSF page. 

**Expected behavior**  
No exception should occur. 

**Diagnostic information:**  
 - OpenLiberty Version: ALL
 - Affected feature(s) jsf-2.2, jsf-2.3, faces-3.0
 - Java Version: 

**Additional context**  
https://issues.apache.org/jira/browse/MYFACES-4469

**Comment by volosied** [comment]
closed in favor of #25111
