### ISSUE TITLE
mpTelemetry-1.0 logs exception on shutdown

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/open-liberty#23145]
The following exception is seen on shutdown:

```
[AUDIT   ] CWWKE0036I: The server Telemetry10TCKServer stopped after 2 minutes, 50.193 seconds.
Exception in thread "Thread-24" Exception in thread "Thread-27" org.jboss.weld.exceptions.IllegalStateException: WELD-000229: Contextual reference of Managed Bean [class org.eclipse.microprofile.telemetry.tracing.tck.exporter.InMemorySpanExporter] with qualifiers [@Any @Default] is not valid after container 9c4faf4a-2173-4a65-883d-6ab1ecf54362 shutdownorg.jboss.weld.exceptions.IllegalStateException: WELD-000229: Contextual reference of Managed Bean [class org.eclipse.microprofile.telemetry.tracing.tck.exporter.InMemorySpanExporter] with qualifiers [@Any @Default] is not valid after container cea92f31-6cc4-45cf-b995-9c4190e9e101 shutdown

	at org.jboss.weld.bean.proxy.ContextBeanInstance.getInstance(ContextBeanInstance.java:85)
	at org.jboss.weld.bean.proxy.ProxyMethodHandler.getInstance(ProxyMethodHandler.java:131)
	at org.eclipse.microprofile.telemetry.tracing.tck.exporter.InMemorySpanExporter$Proxy$_$$_WeldClientProxy.shutdown(Unknown Source)
	at io.opentelemetry.sdk.trace.export.BatchSpanProcessor$Worker.lambda$shutdown$3(BatchSpanProcessor.java:293)
	at io.opentelemetry.sdk.trace.export.BatchSpanProcessor$Worker$$Lambda$1441/0x0000000000000000.run(Unknown Source)
	at io.opentelemetry.sdk.common.CompletableResultCode.whenComplete(CompletableResultCode.java:133)
	at io.opentelemetry.sdk.trace.export.BatchSpanProcessor$Worker.shutdown(BatchSpanProcessor.java:290)
	at io.opentelemetry.sdk.trace.export.BatchSpanProcessor$Worker.access$200(BatchSpanProcessor.java:148)
	at org.jboss.weld.bean.proxy.ContextBeanInstance.getInstance(ContextBeanInstance.java:85)
	at io.opentelemetry.sdk.trace.export.BatchSpanProcessor.shutdown(BatchSpanProcessor.java:114)	at org.jboss.weld.bean.proxy.ProxyMethodHandler.getInstance(ProxyMethodHandler.java:131)

	at io.opentelemetry.sdk.trace.TracerSharedState.shutdown(TracerSharedState.java:103)	at org.eclipse.microprofile.telemetry.tracing.tck.exporter.InMemorySpanExporter$Proxy$_$$_WeldClientProxy.shutdown(Unknown Source)

	at io.opentelemetry.sdk.trace.SdkTracerProvider.shutdown(SdkTracerProvider.java:107)	at io.opentelemetry.sdk.trace.export.BatchSpanProcessor$Worker.lambda$shutdown$3(BatchSpanProcessor.java:293)

	at io.opentelemetry.sdk.autoconfigure.AutoConfiguredOpenTelemetrySdkBuilder.lambda$build$9(AutoConfiguredOpenTelemetrySdkBuilder.java:375)	at io.opentelemetry.sdk.trace.export.BatchSpanProcessor$Worker$$Lambda$1441/0x0000000000000000.run(Unknown Source)

	at io.opentelemetry.sdk.autoconfigure.AutoConfiguredOpenTelemetrySdkBuilder$$Lambda$849/0x000000002c0e78c0.run(Unknown Source)	at io.opentelemetry.sdk.common.CompletableResultCode.whenComplete(CompletableResultCode.java:133)

	at java.base/java.lang.Thread.run(Thread.java:866)	at io.opentelemetry.sdk.trace.export.BatchSpanProcessor$Worker.shutdown(BatchSpanProcessor.java:290)

	at io.opentelemetry.sdk.trace.export.BatchSpanProcessor$Worker.access$200(BatchSpanProcessor.java:148)
	at io.opentelemetry.sdk.trace.export.BatchSpanProcessor.shutdown(BatchSpanProcessor.java:114)
	at io.opentelemetry.sdk.trace.TracerSharedState.shutdown(TracerSharedState.java:103)
	at io.opentelemetry.sdk.trace.SdkTracerProvider.shutdown(SdkTracerProvider.java:107)
	at io.opentelemetry.sdk.autoconfigure.AutoConfiguredOpenTelemetrySdkBuilder.lambda$build$9(AutoConfiguredOpenTelemetrySdkBuilder.java:375)
	at io.opentelemetry.sdk.autoconfigure.AutoConfiguredOpenTelemetrySdkBuilder$$Lambda$849/0x000000002c0e78c0.run(Unknown Source)
	at java.base/java.lang.Thread.run(Thread.java:866)
Exception in thread "BatchSpanProcessor_WorkerThread-1" org.jboss.weld.exceptions.IllegalStateException: WELD-000229: Contextual reference of Managed Bean [class org.eclipse.microprofile.telemetry.tracing.tck.exporter.InMemorySpanExporter] with qualifiers [@Any @Default] is not valid after container 59229517-d2fd-4758-846d-7ccbc83f5116 shutdown
	at org.jboss.weld.bean.proxy.ContextBeanInstance.getInstance(ContextBeanInstance.java:85)
	at org.jboss.weld.bean.proxy.ProxyMethodHandler.getInstance(ProxyMethodHandler.java:131)
	at org.eclipse.microprofile.telemetry.tracing.tck.exporter.InMemorySpanExporter$Proxy$_$$_WeldClientProxy.shutdown(Unknown Source)
	at io.opentelemetry.sdk.trace.export.BatchSpanProcessor$Worker.lambda$shutdown$3(BatchSpanProcessor.java:293)
	at io.opentelemetry.sdk.trace.export.BatchSpanProcessor$Worker$$Lambda$1441/0x0000000000000000.run(Unknown Source)
	at io.opentelemetry.sdk.common.CompletableResultCode.succeed(CompletableResultCode.java:85)
	at io.opentelemetry.sdk.trace.export.BatchSpanProcessor$Worker.flush(BatchSpanProcessor.java:277)
	at io.opentelemetry.sdk.trace.export.BatchSpanProcessor$Worker.run(BatchSpanProcessor.java:238)
	at java.base/java.lang.Thread.run(Thread.java:866)
```

The exception is only seen in the console log, it does not appear in messages.log.

**Comment by Azquelt** [comment]
The exception stack is quite confused, it looks like several stacks are interleaved.

However, it does look like the `AutoConfiguredOpenTelemetrySdkBuilder` is running its shutdown hook which is trying to call into `InMemorySpanExporter`. `InMemorySpanExporter` is a bean in the application so its context will not be active during server shutdown.

This should be fixed by shutting down `OpenTelemetry` at app shutdown, rather than at server shutdown.
