### ISSUE TITLE
Fix Wsoc 21 Timeout: "Connection future timeout 5000 ms for"

### ISSUE THREAD

**Issue by volosied** [OpenLiberty/open-liberty#23172]
```
testUserPropertiesOnServer:java.io.IOException: 2022-09-09-01:25:28:507 Connection future timeout 5000 ms for ws://localhost:8010/basic21/userproperties
    at org.eclipse.jetty.websocket.jakarta.client.internal.JakartaWebSocketClientContainer.connect(JakartaWebSocketClientContainer.java:209)
    at org.eclipse.jetty.websocket.jakarta.client.internal.JakartaWebSocketClientContainer.connectToServer(JakartaWebSocketClientContainer.java:253)
    at io.openliberty.wsoc.util.wsoc.WsocTestRunner.runTest(WsocTestRunner.java:105)
    at io.openliberty.wsoc.util.wsoc.WsocTest.runWsocTest(WsocTest.java:103)
    at io.openliberty.wsoc.tests.all.UserPropertiesTest.testUserPropertiesOnServer(UserPropertiesTest.java:31)
    at io.openliberty.wsoc.tests.Basic21Test.testUserPropertiesOnServer(Basic21Test.java:218)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at io.openliberty.wsoc.util.OnlyRunNotOnZRule$ZosStatement.evaluate(OnlyRunNotOnZRule.java:64)
    at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:199)
    at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:352)
    at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:173)
 ```

I've only seen it occur on the first test. I'm wondering if this will disappear if we reorder the tests. 

https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.workitem.viewWorkItem&id=292475

2024 Update: 

JUnit tests run out of order occasionally, so this defect can still occur. Adding a 5 second wait during the start up method may be a potential solution?

**Comment by volosied** [comment]
Still occurring - reopening
