### ISSUE TITLE
IllegalStateException in dynacache when app server is stopping

### ISSUE THREAD

**Issue by kevin-ortega** [OpenLiberty/open-liberty#23225]
**Describe the bug**  
Sometimes while the Liberty server is shutting down an FFDC is created by a dynacache daemon thread:

Stack Dump = java.lang.IllegalStateException: ScheduledExecutorService service is unavailable
 at com.ibm.ws.cache.Scheduler.getScheduledExecutorService(Scheduler.java:93)
 at com.ibm.ws.cache.Scheduler.createNonDeferrable(Scheduler.java:108)
 at com.ibm.ws.cache.RealTimeDaemon.alarm(RealTimeDaemon.java:107)
 at com.ibm.ws.cache.RealTimeDaemon$2.run(RealTimeDaemon.java:111)
 at com.ibm.ws.cache.Scheduler$WrappedRunnable.run(Scheduler.java:130)
 at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
 at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
 at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
 at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
 at java.base/java.lang.Thread.run(Thread.java:866)

**Steps to Reproduce**  
Enable feature webCache-1.0 
Stop the Liberty server

**Expected behavior**  
Stopping the Liberty server should not cause an illegalStateException.  Dynacache should not attempt to create a schedule when the Liberty server is stopping.  

**Diagnostic information:**  
 - OpenLiberty Version: All versions
 - Affected feature: webCache-1.0
 - Java Version:  not Java version specific
 - server.xml configuration (WITHOUT sensitive information like passwords)
 - If it would be useful, upload the messages.log file found in `$WLP_OUTPUT_DIR/messages.log`

**Additional context**

**Comment by mbroz2** [comment]
@kevin-ortega please update the description of this `release bug` using the [bug report template](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=&labels=release+bug&template=bug_report.md&title=)
