### ISSUE TITLE
WASURLObjectFactoryFinder throws ClassNotFoundException when retreiving attributes for LDAP entity with colon in distinguished name

### ISSUE THREAD

**Issue by jvanhill** [OpenLiberty/open-liberty#2331]
When retrieving the attributes for an LDAP entity with a colon in the distinguished name, Aries throws a ClassNotFoundException.

```

------Start of DE processing------ = [2/20/18 22:34:55:925 CST]
Exception = java.lang.ClassNotFoundException
Source = com.ibm.ws.jndi.internal.WASURLObjectFactoryFinder.findFactory
probeid = 74
Stack Dump = java.lang.ClassNotFoundException: com.sun.jndi.url.cn=wxs.cn=wxsURLContextFactory
	at java.lang.Class.forNameImpl(Native Method)
	at java.lang.Class.forName(Class.java:361)
	at com.ibm.ws.jndi.internal.WASURLObjectFactoryFinder.findFactory(WASURLObjectFactoryFinder.java:62)
	at org.apache.aries.jndi.ContextHelper.getURLObjectFactory(ContextHelper.java:102)
	at org.apache.aries.jndi.ContextHelper.createURLContext(ContextHelper.java:69)
	at org.apache.aries.jndi.DelegateContext.getURLContext(DelegateContext.java:248)
	at org.apache.aries.jndi.DelegateContext.findContext(DelegateContext.java:214)
	at org.apache.aries.jndi.DelegateContext.findContext(DelegateContext.java:207)
	at org.apache.aries.jndi.DelegateContext.getAttributes(DelegateContext.java:271)
	at javax.naming.directory.InitialDirContext.getAttributes(InitialDirContext.java:163)
	at com.ibm.ws.security.wim.adapter.ldap.TimedDirContext.getAttributes(TimedDirContext.java:185)
	at com.ibm.ws.security.wim.adapter.ldap.LdapConnection.getAttributes(LdapConnection.java:1246)
	at com.ibm.ws.security.wim.adapter.ldap.LdapConnection.checkAttributesCache(LdapConnection.java:1355)
	at com.ibm.ws.security.wim.adapter.ldap.LdapConnection.getEntityByIdentifier(LdapConnection.java:1130)
	at com.ibm.ws.security.wim.adapter.ldap.LdapAdapter.getGroupsByOperationalAttribute(LdapAdapter.java:1465)
	at com.ibm.ws.security.wim.adapter.ldap.LdapAdapter.getGroups(LdapAdapter.java:1352)
	at com.ibm.ws.security.wim.adapter.ldap.LdapAdapter.get(LdapAdapter.java:452)
	at com.ibm.ws.security.wim.ProfileManager.getImpl(ProfileManager.java:532)
	at com.ibm.ws.security.wim.ProfileManager.genericProfileManagerMethod(ProfileManager.java:235)
	at com.ibm.ws.security.wim.ProfileManager.get(ProfileManager.java:192)
	at com.ibm.ws.security.wim.VMMService.get(VMMService.java:208)
	at com.ibm.ws.security.wim.registry.util.MembershipBridge.getUniqueGroupIds(MembershipBridge.java:655)
	at com.ibm.ws.security.wim.registry.WIMUserRegistry.getUniqueGroupIdsForUser(WIMUserRegistry.java:407)
	at web.UserRegistryServlet.handleMethodRequest(UserRegistryServlet.java:202)
	at web.UserRegistryServlet.doGet(UserRegistryServlet.java:239)
```

**Comment by tjwatson** [comment]
First question.  Is this an issue with com.ibm.ws.jndi.internal.WASURLObjectFactoryFinder or with the Aries code calling it?

Second quesion.  Why is this FFDC getting generated at all?  The method `WASURLObjectFactoryFinder.findFactory(String, Hashtable<?, ?>)` has `@FFDCIgnore(ClassNotFoundException.class)` and it catches the CNFE and should ultimately return null.  Did something go wrong with the buidl processing the `@FFDCIgnore(ClassNotFoundException.class)` annotation?  Is this a new FFDC that was not occurring before?

**Comment by tjwatson** [comment]
I was wrong.  The method does have `@FFDCIgnore(ClassNotFoundException.class)` and catches the CNFE, but then it stores it and does an explicit `FFDCFilter.processException()` for the CNFE.

**Comment by jvanhill** [comment]
I noticed the FFDC when I was writing new FATs for another issue we have. I assume it has always been this way, but nobody noticed or had encountered it.

I added trace for the WASURLObjectFactoryFinder class. I only see trace for it when we get these CNFE's. 

```
[2/21/18 9:35:28:294 CST] 00000056 id=71870188 com.ibm.ws.jndi.internal.WASURLObjectFactoryFinder           > findFactory Entry  
                                                                                                               cn=wxs
                                                                                                               {java.naming.provider.url=ldap://bluepages.ibm.com:389, java.naming.factory.initial=com.sun.jndi.ldap.LdapCtxFactory, java.naming.ldap.version=3, com.sun.jndi.ldap.connect.timeout=60000, java.naming.referral=ignore}
[2/21/18 9:35:28:294 CST] 00000056 id=71870188 com.ibm.ws.jndi.internal.WASURLObjectFactoryFinder           > getClassLoader Entry 
[2/21/18 9:35:28:295 CST] 00000056 id=         com.ibm.ws.jndi.internal.WASURLObjectFactoryFinder$1         > <init> Entry  
                                                                                                               com.ibm.ws.jndi.internal.WASURLObjectFactoryFinder@71870188
[2/21/18 9:35:28:295 CST] 00000056 id=c82c39a0 com.ibm.ws.jndi.internal.WASURLObjectFactoryFinder$1         < <init> Exit  
                                                                                                               com.ibm.ws.jndi.internal.WASURLObjectFactoryFinder$1@c82c39a0
[2/21/18 9:35:28:295 CST] 00000056 id=c82c39a0 com.ibm.ws.jndi.internal.WASURLObjectFactoryFinder$1         > run Entry 
[2/21/18 9:35:28:295 CST] 00000056 id=c82c39a0 com.ibm.ws.jndi.internal.WASURLObjectFactoryFinder$1         < run Exit  
                                                                                                               com.ibm.ws.classloading.internal.ThreadContextClassLoader@ec5daa62
[2/21/18 9:35:28:295 CST] 00000056 id=71870188 com.ibm.ws.jndi.internal.WASURLObjectFactoryFinder           < getClassLoader Exit  
                                                                                                               com.ibm.ws.classloading.internal.ThreadContextClassLoader@ec5daa62
[2/21/18 9:35:28:297 CST] 00000056 id=         com.ibm.ws.jndi.internal.WASURLObjectFactoryFinder           3 Could not find class com.sun.jndi.url.cn=wxs.cn=wxsURLContextFactory 
                                                                                                               java.lang.ClassNotFoundException: com.sun.jndi.url.cn=wxs.cn=wxsURLContextFactory
	at java.lang.Class.forNameImpl(Native Method)
	at java.lang.Class.forName(Class.java:361)
	at com.ibm.ws.jndi.internal.WASURLObjectFactoryFinder.findFactory(WASURLObjectFactoryFinder.java:62)
	at org.apache.aries.jndi.ContextHelper.getURLObjectFactory(ContextHelper.java:102)
	at org.apache.aries.jndi.ContextHelper.createURLContext(ContextHelper.java:69)
	at org.apache.aries.jndi.DelegateContext.getURLContext(DelegateContext.java:248)
	at org.apache.aries.jndi.DelegateContext.findContext(DelegateContext.java:214)
	at org.apache.aries.jndi.DelegateContext.findContext(DelegateContext.java:207)
	at org.apache.aries.jndi.DelegateContext.getAttributes(DelegateContext.java:271)
	at javax.naming.directory.InitialDirContext.getAttributes(InitialDirContext.java:163)
```
This indicates that the problem is probably in Aries code. Is it parsing the LDAP URL (incorrectly) to come up with the schema?

**Comment by jvanhill** [comment]
After looking at this with @sebratton it was determined that WASURLObjectFactoryFinder was NOT throwing a CNFE, but was just logging the FFDC. I had misinterpreted the trace. It was trying to load the invalid class's according to the JNDI spec, failing to do so, logging FFDC and then falling back to the default context.

However; I contend that FFDC should NOT be thrown when a otherwise normal operation is being requested. The issue here is that the Aries code sees the (valid) distinguished name (DN) with a ":" in it as meeting the RFC 1738 spec for a URL, so it passes it onto the WASURLObjectFactoryFinder.findFactory() method. Of course, the scheme with part of the DN is not a valid URL scheme, and we get the CNFE and log the FFDC.

I looked back in history and noticed @andymc12 had modified this file and asked his thoughts. He thought that the FFDC was useful, so he didn't want to completely remove it.

Perhaps we could check if the passed in scheme and determine if it is a valid DN, and if so, not try to load the classes nor throw the FFDC? If we want to be even more cautious, just use the check to not throw the FFDC?

**Comment by sebratton** [comment]
My preference here is to either remove the FFDC or have the FAT ignore it (which it may be doing now).  Although I can see some value to the FFDC, since the code in question even calls out in the comments that CNFE "can occur quite often", it seems that the first failure capture might just be noise.
