### ISSUE TITLE
Add support for JSR375 Decorator and Alternative

### ISSUE THREAD

**Issue by utle** [OpenLiberty/open-liberty#23322]
The current code throw an exception when application have @Decorator and @Alternative

Application fails to start with exception:

jakarta.enterprise.inject.spi.DeploymentException: CWWKS1925E: The deployment for the app-mem-basic-decorate-3.0.0.war module in the app-mem-basic-decorate-3.0.0 application failed because of multiple HttpAuthenticationMechanism implementations: ee.jakarta.tck.security.test.AuthenticationMechanismDecorator, com.ibm.ws.security.javaeesec.cdi.beans.BasicHttpAuthenticationMechanism. This failure is likely an application packaging issue. Make sure that each module has only one HttpAuthenticationMechanism implementation.

	at com.ibm.ws.security.javaeesec.cdi.extensions.JavaEESecCDIExtension.verifyConfiguration(JavaEESecCDIExtension.java:840)

	at com.ibm.ws.security.javaeesec.cdi.extensions.JavaEESecCDIExtension.afterBeanDiscovery(JavaEESecCDIExtension.java:206)

	at jdk.internal.reflect.GeneratedMethodAccessor89.invoke(Unknown Source)

	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

	at java.base/java.lang.reflect.Method.invoke(Method.java:566)

	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:95)

	at org.jboss.weld.injection.MethodInvocationStrategy$SpecialParamPlusBeanManagerStrategy.invoke(MethodInvocationStrategy.java:187)

	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:330)

	at org.jboss.weld.event.ExtensionObserverMethodImpl.sendEvent(ExtensionObserverMethodImpl.java:126)

	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:308)

	at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:286)

	at jakarta.enterprise.inject.spi.ObserverMethod.notify(ObserverMethod.java:142)

**Comment by utle** [comment]
Fixed by https://github.com/OpenLiberty/open-liberty/pull/23270/files
