### ISSUE TITLE
Investigate failure of testCXFClientEncryptUsernameTokenUsingXPath in CxfX509EncTests (com.ibm.ws.wssecurity.fat.cxf.x509token)

### ISSUE THREAD

**Issue by meiaus** [OpenLiberty/open-liberty#23345]
The test was noticed as commented out (from CL) during OL/CL migration, when attempting to run in current environment, it failed with both old/new (wss4j) CallbackHandler class: 

```
[11/14/22, 7:52:02:563 PST] 0000002c SystemErr                                                    R Caused by: 
[11/14/22, 7:52:02:565 PST] 0000002c SystemErr                                                    R org.apache.cxf.ws.policy.PolicyException: The element can't be serialized as it has no parent
[11/14/22, 7:52:02:567 PST] 0000002c SystemErr                                                    R 	at org.apache.cxf.ws.security.wss4j.policyhandlers.AbstractCommonBindingHandler.unassertPolicy(AbstractCommonBindingHandler.java:115)
[11/14/22, 7:52:02:568 PST] 0000002c SystemErr                                                    R 	at org.apache.cxf.ws.security.wss4j.policyhandlers.AsymmetricBindingHandler.doEncryption(AsymmetricBindingHandler.java:590)
[11/14/22, 7:52:02:568 PST] 0000002c SystemErr                                                    R 	at org.apache.cxf.ws.security.wss4j.policyhandlers.AsymmetricBindingHandler.doSignBeforeEncrypt(AsymmetricBindingHandler.java:247)
[11/14/22, 7:52:02:568 PST] 0000002c SystemErr                                                    R 	... 41 more
[11/14/22, 7:52:02:568 PST] 0000002c SystemErr                                                    R Caused by: 
[11/14/22, 7:52:02:568 PST] 0000002c SystemErr                                                    R org.apache.wss4j.common.ext.WSSecurityException: The element can't be serialized as it has no parent
Original Exception was org.apache.xml.security.encryption.XMLEncryptionException: The element can't be serialized as it has no parent
[11/14/22, 7:52:02:568 PST] 0000002c SystemErr                                                    R 	at org.apache.wss4j.dom.message.Encryptor.encryptElement(Encryptor.java:471)
[11/14/22, 7:52:02:568 PST] 0000002c SystemErr                                                    R 	at org.apache.wss4j.dom.message.Encryptor.doEncryption(Encryptor.java:201)
[11/14/22, 7:52:02:568 PST] 0000002c SystemErr                                                    R 	at org.apache.wss4j.dom.message.WSSecEncrypt.encryptForRef(WSSecEncrypt.java:211)
[11/14/22, 7:52:02:568 PST] 0000002c SystemErr                                                    R 	at org.apache.cxf.ws.security.wss4j.policyhandlers.AsymmetricBindingHandler.doEncryption(AsymmetricBindingHandler.java:566)
[11/14/22, 7:52:02:568 PST] 0000002c SystemErr                                                    R 	... 42 more
[11/14/22, 7:52:02:568 PST] 0000002c SystemErr                                                    R Caused by: 
[11/14/22, 7:52:02:568 PST] 0000002c SystemErr                                                    R org.apache.xml.security.encryption.XMLEncryptionException: The element can't be serialized as it has no parent
[11/14/22, 7:52:02:568 PST] 0000002c SystemErr                                                    R 	at org.apache.xml.security.encryption.XMLCipher.encryptData(XMLCipher.java:1102)
[11/14/22, 7:52:02:568 PST] 0000002c SystemErr                                                    R 	at org.apache.xml.security.encryption.XMLCipher.encryptData(XMLCipher.java:1090)
[11/14/22, 7:52:02:568 PST] 0000002c SystemErr                                                    R 	at org.apache.xml.security.encryption.XMLCipher.encryptElement(XMLCipher.java:859)
[11/14/22, 7:52:02:584 PST] 0000002c SystemErr                                                    R 	at org.apache.xml.security.encryption.XMLCipher.doFinal(XMLCipher.java:1000)
[11/14/22, 7:52:02:584 PST] 0000002c SystemErr                                                    R 	at org.apache.wss4j.dom.message.Encryptor.encryptElement(Encryptor.java:468)

```

Logs in box folder: https://ibm.ent.box.com/file/1070001961118

**Comment by meiaus** [comment]
fyi @arunavemulapalli
