### ISSUE TITLE
Investigating failure of 2 tests in CxfSSLUNTNonceTests.class

### ISSUE THREAD

**Issue by meiaus** [OpenLiberty/open-liberty#23415]
Observation:
1. The current test failure didn't seem to be matched to the prior defect 88389
2. The current test failure may be returned as expected, but adding @ExpectedFFDC still gets the failure status.

//Prior defect 88389 - uncomment next line when issue is resolved
testCxfUntReqTimestampHardcodedMsgTwiceSSL()
testCxfUntReqTimestampSendMsgTwiceSSL()

Failure from the current attempt (using EE7 test of testCxfUntReqTimestampHardcodedMsgTwiceSSL for log example):

```
[11/18/22, 11:05:08:824 PST] 0000002d SystemOut                                                    O ************************ testCxfUntReqTimestampHardcodedMsgTwiceSSL ************************

...

[11/18/22, 11:05:19:886 PST] 0000002d SystemErr                                                    R Caused by: 
[11/18/22, 11:05:19:886 PST] 0000002d SystemErr                                                    R org.apache.cxf.binding.soap.SoapFault: BSP:R3227: A SECURITY_HEADER MUST NOT contain more than one TIMESTAMP
[11/18/22, 11:05:19:902 PST] 0000002d SystemErr                                                    R 	at org.apache.cxf.binding.soap.interceptor.Soap11FaultInInterceptor.unmarshalFault(Soap11FaultInInterceptor.java:87)
[11/18/22, 11:05:19:902 PST] 0000002d SystemErr                                                    R 	at org.apache.cxf.binding.soap.interceptor.Soap11FaultInInterceptor.handleMessage(Soap11FaultInInterceptor.java:53)
[11/18/22, 11:05:19:902 PST] 0000002d SystemErr                                                    R 	at org.apache.cxf.binding.soap.interceptor.Soap11FaultInInterceptor.handleMessage(Soap11FaultInInterceptor.java:42)
[11/18/22, 11:05:19:902 PST] 0000002d SystemErr                                                    R 	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
[11/18/22, 11:05:19:902 PST] 0000002d SystemErr                                                    R 	at org.apache.cxf.interceptor.AbstractFaultChainInitiatorObserver.onMessage(AbstractFaultChainInitiatorObserver.java:112)
[11/18/22, 11:05:19:902 PST] 0000002d SystemErr                                                    R 	at org.apache.cxf.binding.soap.interceptor.CheckFaultInterceptor.handleMessage(CheckFaultInterceptor.java:70)
[11/18/22, 11:05:19:902 PST] 0000002d SystemErr                                                    R 	at org.apache.cxf.binding.soap.interceptor.CheckFaultInterceptor.handleMessage(CheckFaultInterceptor.java:35)
[11/18/22, 11:05:19:902 PST] 0000002d SystemErr                                                    R 	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
[11/18/22, 11:05:19:917 PST] 0000002d SystemErr                                                    R 	at org.apache.cxf.endpoint.ClientImpl.onMessage(ClientImpl.java:836)
[11/18/22, 11:05:19:917 PST] 0000002d SystemErr                                                    R 	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.handleResponseInternal(HTTPConduit.java:1758)
[11/18/22, 11:05:19:917 PST] 0000002d SystemErr                                                    R 	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.handleResponse(HTTPConduit.java:1632)
[11/18/22, 11:05:19:917 PST] 0000002d SystemErr                                                    R 	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.close(HTTPConduit.java:1424)
[11/18/22, 11:05:19:917 PST] 0000002d SystemErr                                                    R 	at org.apache.cxf.ext.logging.LoggingOutputStream.postClose(LoggingOutputStream.java:53)
[11/18/22, 11:05:19:917 PST] 0000002d SystemErr                                                    R 	at org.apache.cxf.io.CachedOutputStream.close(CachedOutputStream.java:228)
[11/18/22, 11:05:19:917 PST] 0000002d SystemErr                                                    R 	at org.apache.cxf.transport.AbstractConduit.close(AbstractConduit.java:56)
[11/18/22, 11:05:19:917 PST] 0000002d SystemErr                                                    R 	at org.apache.cxf.transport.http.HTTPConduit.close(HTTPConduit.java:691)
[11/18/22, 11:05:19:917 PST] 0000002d SystemErr                                                    R 	at org.apache.cxf.interceptor.MessageSenderInterceptor$MessageSenderEndingInterceptor.handleMessage(MessageSenderInterceptor.java:63)
[11/18/22, 11:05:19:933 PST] 0000002d SystemErr                                                    R 	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
[11/18/22, 11:05:19:933 PST] 0000002d SystemErr                                                    R 	at org.apache.cxf.endpoint.ClientImpl.doInvoke(ClientImpl.java:533)
[11/18/22, 11:05:19:933 PST] 0000002d SystemErr                                                    R 	at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:444)
[11/18/22, 11:05:19:933 PST] 0000002d SystemErr                                                    R 	at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:359)
[11/18/22, 11:05:19:933 PST] 0000002d SystemErr                                                    R 	at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:317)
[11/18/22, 11:05:19:933 PST] 0000002d SystemErr                                                    R 	at org.apache.cxf.endpoint.ClientImpl.invokeWrapped(ClientImpl.java:352)
[11/18/22, 11:05:19:933 PST] 0000002d SystemErr                                                    R 	at org.apache.cxf.jaxws.DispatchImpl.invoke(DispatchImpl.java:322)

```    

Logs in box folder: https://ibm.ent.box.com/file/1069994690944

**Comment by meiaus** [comment]
fyi @arunavemulapalli
