### ISSUE TITLE
JAX-WS: "javax.xml.ws.soap.SOAPFaultException: local part cannot be "null" when creating a QName" occures when processing SOAP Requests using the default namespace

### ISSUE THREAD

**Issue by neuwerk** [OpenLiberty/open-liberty#23419]
**Describe the bug**  

If SOAP Request, using the default namespace in the Envelope and Body (non-prefixed), is processed by a JAX-WS Web Service on Liberty 22.0.0.8 and above the following exception is thrown and a SOAP Fault will be returned by the provider.  

```
javax.xml.ws.soap.SOAPFaultException: local part cannot be "null" when creating a QName
at org.apache.cxf.jaxws.JaxWsClientProxy.mapException(JaxWsClientProxy.java:195)
at org.apache.cxf.jaxws.JaxWsClientProxy.invoke(JaxWsClientProxy.java:145)
at com.sun.proxy.$Proxy56.wsmain(Unknown Source)
at web.test.TestServlet.doGet(TestServlet.java:96)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
```
Example of non-working request:
```
<Envelope xmlns="http://schemas.xmlsoap.org/soap/envelope/">
  <Body>
    
    <ser:hello xmlns:ser="http://server.wsr.test.jaxws.ws.ibm.com">
       
      <arg0>from dispatch World</arg0>
    
    </ser:hello>
  
  </Body>
</Envelope>
```

If however, the request is prefixed and using the non-default namespace the request can be successfully processed by the provider. 

Example of working request:

```
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Body>
    
    <ser:hello xmlns:ser="http://server.wsr.test.jaxws.ws.ibm.com">
       
      <arg0>from dispatch World</arg0>
    
    </ser:hello>
  
  </soap:Body>
</soap:Envelope>
```

**Expected behavior**  
The JAX-WS Web Service deployed on 22.0.0.8 and above should still be able to process a SOAP message that it was able to process 22.0.0.7 and below. 

**Diagnostic information:**  
 - OpenLiberty Version: 22.0.0.8 and above
 - Affected feature(s)z: jaxws-2.2, xmlWS-3.0, xmlWS-4.0
 - Java Version: IBM Semeru Runtime Open Edition (11.0.15+10)
 - server.xml configuration (WITHOUT sensitive information like passwords)
```
<server>
    <featureManager>
        <feature>jsp-2.2</feature>        
        <feature>jaxws-2.2</feature>
    </featureManager>
</server>
```

**Additional context**  

Currently the only work around for the issue is to follow the XML specification best practice of using non-default namespaces in the soap request (See working example). If the non-default namespace is set on the Envelope and Body with any accompanying prefix a JAX-WS Web Service running on Liberty will be able to successfully process the message. 

The failure appears to be a bug in the Apache CXF code [ReadHeadersInterceptor](https://github.com/apache/cxf/blob/main/rt/bindings/soap/src/main/java/org/apache/cxf/binding/soap/interceptor/ReadHeadersInterceptor.java) (Line 375) that fails to account for a default namespace when processing a inbound soap message. 

However, changes to account for default namespaces will now result a valid Unmarshalling failure if the XML is invalid, like below.
```

[11/28/2022 17:56:35:575 CST] 001 FATRunner                      evaluate                       S null
javax.xml.bind.UnmarshalException
 - with linked exception:
[com.sun.istack.SAXParseException2; lineNumber: 2; columnNumber: 14; unexpected element (uri:"http://schemas.xmlsoap.org/soap/envelope/", local:"arg0"). Expected elements are <{}arg0>]
```

**Comment by neuwerk** [comment]
#23608 

Fixes the Null QName and adds accompanying FAT test.
