### ISSUE TITLE
Test Failure: com.ibm.ws.logging.fat.TimeBasedLogRolloverTest.testTimedRolloverEnv

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#23444]
RTC 293352

```
estTimedRolloverEnv:componenttest.exception.TopologyException: 2022-10-24-07:18:57:446 The necessary feature timedexit-1.0 was not enabled. Please include fatTestPorts.xml or fatTestCommon.xml in the server.xml for server com.ibm.ws.logging.timedrolloverenv.
at componenttest.topology.impl.LibertyServer.validateTimedExitEnabled(LibertyServer.java:2609)
at componenttest.topology.impl.LibertyServer.validateServerStarted(LibertyServer.java:2579)
at componenttest.topology.impl.LibertyServer.startServerWithArgs(LibertyServer.java:1711)
at componenttest.topology.impl.LibertyServer.startServerAndValidate(LibertyServer.java:1282)
at componenttest.topology.impl.LibertyServer.startServerAndValidate(LibertyServer.java:1264)
at componenttest.topology.impl.LibertyServer.startServerAndValidate(LibertyServer.java:1251)
at componenttest.topology.impl.LibertyServer.startServer(LibertyServer.java:1015)
at com.ibm.ws.logging.fat.TimeBasedLogRolloverTest.setUp(TimeBasedLogRolloverTest.java:120)
at com.ibm.ws.logging.fat.TimeBasedLogRolloverTest.testTimedRolloverEnv(TimeBasedLogRolloverTest.java:138)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:201)
at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:354)
at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:175)
```

This seems to be a Windows issue.

**Comment by fmhwong** [comment]
@ellen-lau This has been marked as high impact. Did you get a chance to look at it?
