### ISSUE TITLE
Nullpointer exception with opentelemetry agent and async request

### ISSUE THREAD

**Issue by sdehors-ibm** [OpenLiberty/open-liberty#23476]
**Describe the bug**  
Opentelemetry agent (with latest version 1.20.1) throws exceptions when tracing jax-rs async calls

```
[INFO] [WARNING ] SRVE8504W: The following uncaught exception was thrown by the AsyncListener: [io.opentelemetry.javaagent.instrumentation.servlet.v3_0.Servlet3Accessor$Listener] during onComplete: [java.lang.NullPointerException
[INFO]  at io.opentelemetry.javaagent.instrumentation.servlet.v3_0.Servlet3Accessor.isResponseCommitted(Servlet3Accessor.java:70)
[INFO]  at io.opentelemetry.javaagent.instrumentation.servlet.v3_0.Servlet3Accessor.isResponseCommitted(Servlet3Accessor.java:19)
[INFO]  at io.opentelemetry.javaagent.instrumentation.servlet.ServletHttpAttributesGetter.statusCode(ServletHttpAttributesGetter.java:72)
[INFO]  at io.opentelemetry.javaagent.instrumentation.servlet.ServletHttpAttributesGetter.statusCode(ServletHttpAttributesGetter.java:12)
[INFO]  at io.opentelemetry.javaagent.shaded.instrumentation.api.instrumenter.http.HttpCommonAttributesExtractor.onEnd(HttpCommonAttributesExtractor.java:65)
[INFO]  at io.opentelemetry.javaagent.shaded.instrumentation.api.instrumenter.http.HttpServerAttributesExtractor.onEnd(HttpServerAttributesExtractor.java:132)
[INFO]  at io.opentelemetry.javaagent.shaded.instrumentation.api.instrumenter.Instrumenter.doEnd(Instrumenter.java:224)
[INFO]  at io.opentelemetry.javaagent.shaded.instrumentation.api.instrumenter.Instrumenter.end(Instrumenter.java:144)
[INFO]  at io.opentelemetry.javaagent.instrumentation.servlet.AsyncRequestCompletionListener.onComplete(AsyncRequestCompletionListener.java:37)
[INFO]  at io.opentelemetry.javaagent.instrumentation.servlet.v3_0.Servlet3Accessor$Listener.onComplete(Servlet3Accessor.java:82)
[INFO]  at com.ibm.ws.webcontainer.async.AsyncListenerEntry.invokeOnComplete(AsyncListenerEntry.java:87)
[INFO]  at [internal classes]
[INFO] ]
```

**Steps to Reproduce**  
start liberty with jvm option: -javaagent:<path>/opentelemetry-javaagent-1.20.1.jar

This jaxrs endpoint reproduces the bug:

 ```
@GET
 @Produces(MediaType.APPLICATION_JSON)
 @Path("async")
 public CompletableFuture<String> getExternalResourceAsync(@QueryParam("wait") long wait) throws URISyntaxException {

        HttpRequest get = HttpRequest.newBuilder()
                .uri(new URI("https://github.com"))
                .GET()
                .build();

        CompletableFuture<HttpResponse<String>> response = client.sendAsync(get, BodyHandlers.ofString());

        return response.thenApply(r -> r.statusCode() + " : " + r.body());
    }

```

**Expected behavior**  
There should be no exception thrown and tracing should work. 

It seems the async event passed to AsyncListener does not contain any response.

**Diagnostic information:**  
 - OpenLiberty Version: 22.0.0.12 and before
 - Affected feature(s) jaxrs-2.1
 - Java Version: 
 openjdk 11.0.15-ea 2022-04-19
IBM Semeru Runtime Open Edition 11.0.15.0 (build 11.0.15-ea+10)
Eclipse OpenJ9 VM 11.0.15.0 (build openj9-0.32.0, JRE 11 Mac OS X aarch64-64-Bit 20220422_36 (JIT enabled, AOT enabled)
OpenJ9   - 9a84ec34e
OMR      - ab24b6666
JCL      - b7b5b42ea6 based on jdk-11.0.15+10)

 - server.xml configuration 
 ```
<server description="Sample Liberty server">
    <featureManager>
        <feature>cdi-2.0</feature>
        <feature>jaxrs-2.1</feature>
        <feature>jsonb-1.0</feature>
        <feature>mpMetrics-3.0</feature>
        <feature>mpOpenAPI-2.0</feature>
    </featureManager>

    <variable name="default.http.port" defaultValue="9080"/>
    <variable name="default.https.port" defaultValue="9443"/>

    <webApplication location="guide-getting-started.war" contextRoot="/" />

    <mpMetrics authentication="false"/>

    <httpEndpoint host="*" httpPort="${default.http.port}"
                  httpsPort="${default.https.port}" id="defaultHttpEndpoint"/>
    
</server>
```

**Additional context**  
The problem is not visible with restfulWS-3.0

**Comment by florian-signoret-ibm** [comment]
Hello,
It would be great to have this fixed, it is preventing me from using telemetry on my env.
Thanks!!
Florian

**Comment by pemily** [comment]
Same, I hope it will be fixed soon
