### ISSUE TITLE
SPENGO/Kerberos with Java 11 and Active Directory

### ISSUE THREAD

**Issue by dominikrebhan** [OpenLiberty/open-liberty#23495]
I am forcing a problem with SPNEGO. In my enterprise we are using Active Directory as the KDC base. SPN's are mapped to users. When changing to Java 11, I get the following kerberos error message:

**_Client not found in database_**

I think this is primarily due to the fact, that it is not supported to lookup the SPN directly in our environment. I created a custom tai with my own SPNEGO implementation against the GSS api, using the principal instead. After this change, SPENGO worked. I found no other way to geht this working with the default implementation. I think it would be great if liberty supports this change. It should be relatively easy to implement:

Adding a new optional property **userPrincipalName** in the spengo-configuration which then is the source for the **SpnGssCredential.createGSSName Method**.

What do you think about this? I could also contribute this change.
Kind regards

https://github.com/OpenLiberty/open-liberty/blob/672b858586c7785317eb4e9fe9a395cae848e297/dev/com.ibm.ws.security.spnego/src/com/ibm/ws/security/spnego/internal/SpnGssCredential.java
https://openliberty.io/docs/latest/reference/config/spnego.html

**Comment by utle** [comment]
Hi, 
If I understand correctly, your SPNEGO configuration is working fine with other Java version but have problem with Java 11. We can not re-create this problem Java 11, can you turn on the trace string below and re-create the problem and send me the trace.log, server.xml file and krb5.keytab file
`Trace string com.ibm.ws.security.*=all:com.ibm.webcontainer.security.*=all`
Also, please turn on the JGSS and KRB5 debugging.

**Comment by dominikrebhan** [comment]
Hi,
yes this is correct. I'm sorry but I cannot provide the entire traces. But here are some snippets:

`(WebSphere Application Server 22.0.0.11/wlp-1.0.70.cl221120221010-1540) on Eclipse OpenJ9 VM, version 11.0.16.1+1 (en_US)`

```
com.ibm.ws.security.spnego.internal.SpnGssCredential         E CWWKS4308E: Can not create a GSSCredential for service principal name: HTTP/xxx@xxx. A GSSException was received: GSSException: No valid credentials provided (Mechanism level: Attempt to obtain new ACCEPT credentials failed!)
	at java.security.jgss/sun.security.jgss.krb5.Krb5AcceptCredential.getInstance(Krb5AcceptCredential.java:79)
	at java.security.jgss/sun.security.jgss.krb5.Krb5MechFactory.getCredentialElement(Krb5MechFactory.java:133)
	at java.security.jgss/sun.security.jgss.GSSManagerImpl.getCredentialElement(GSSManagerImpl.java:187)
	at java.security.jgss/sun.security.jgss.GSSCredentialImpl.add(GSSCredentialImpl.java:439)
	at java.security.jgss/sun.security.jgss.GSSCredentialImpl.<init>(GSSCredentialImpl.java:74)
	at java.security.jgss/sun.security.jgss.GSSManagerImpl.createCredential(GSSManagerImpl.java:148)
	at com.ibm.ws.security.spnego.internal.SpnGssCredential.createGSSCredential(SpnGssCredential.java:134)
	at com.ibm.ws.security.spnego.internal.SpnGssCredential.createSpnGSSCredential(SpnGssCredential.java:109)
	at com.ibm.ws.security.spnego.internal.SpnGssCredential.init(SpnGssCredential.java:46)
	at com.ibm.ws.security.spnego.internal.SpnegoConfigImpl.initSpnGssCrendential(SpnegoConfigImpl.java:113)
	at com.ibm.ws.security.spnego.internal.SpnegoConfigImpl.<init>(SpnegoConfigImpl.java:103)
	at com.ibm.ws.security.spnego.SpnegoService.activate(SpnegoService.java:118)
```

```
Caused by: javax.security.auth.login.LoginException: Client not found in Kerberos database (6)
Caused by: KrbException: Client not found in Kerberos database (6)
Caused by: KrbException: Identifier doesn't match expected value (906)
```

Since Java 11 (or maybe earlier) the GSS-Api tries to lookup the credentials in the kdc as well for enhanced security. In our environment, this is not possible. The user mapped to the SPN has to be looked up. In Java 8 this was not happening, it just created the subject from the provided keytab.

**Comment by utle** [comment]
We can not recreate this problem for
(WebSphere Application Server 22.0.0.11/wlp-1.0.70.cl221120221010-1540) on Eclipse OpenJ9 VM, version 11.0.16.1+1 (en_US). Did you configure the following steps:
1) Create the MS AD user
2) Map the MS AD user to the SPN and create the keytab file.
3) Configure the SPN in the server.xml file

Here is the doc for configure the SPNEGO authentication.
https://openliberty.io/docs/latest/configuring-spnego-authentication.html

If you can not provide the trace and snippets of the server.xml, I afraid not much that I can go further.

**Comment by dominikrebhan** [comment]
Then this must be some special behavior in our environment, I will need to stick with my tai. Thank you for your research.
