### ISSUE TITLE
improve TCK as FAT output

### ISSUE THREAD

**Issue by hutchig** [OpenLiberty/open-liberty#2365]
The rather binary message on stdout when one or more TCK test fails is causing problems
in build triage by teams that do not own the test bucket involved. Ideally we want to
make the stdout 'fat bucket complete here are the error/failures' message be as detailed to a standard FAT bucket.

**Comment by hutchig** [comment]
For the raw TCK runners we got beautiful output at:

file:///Users/hutchig/git/mpConfigTckRunner/tck/target/surefire-reports/index.html
~/git/mpConfigTckRunner/tck/target/surefire-reports
$ ls
TEST-TestSuite.xml	 testng-results.xml failed.xml

**Comment by hutchig** [comment]
./build/libs/autoFVT/results/tck/surefire-reports/testng-results.xml

**Comment by hutchig** [comment]
I see
```
 <class name="org.eclipse.microprofile.config.tck.broken.WrongConverterOnInstanceInjectionTest">
        <methods>
          <include name="arquillianAfterClass"/>
          <include name="arquillianBeforeClass"/>
          <include name="arquillianAfterTest"/>
          <include name="arquillianBeforeTest"/>
        </methods>
      </class> <!-- org.eclipse.microprofile.config.tck.broken.WrongConverterOnInstanceInjectionTest -->
```
For all PASSING tests that are testing deployment exceptions made OK due to a @ShoulThrow
in testng-failed.xml
cf
https://github.com/krmahadevan/testng/commit/1a17caaf303eb2477f9a04e36ea054c1bef54e69

For a genuinely faiking test I see: 
```
   <class name="org.eclipse.microprofile.config.tck.ConfigProviderTest">
        <methods>
          <include name="arquillianAfterClass"/>
          <include name="arquillianBeforeClass"/>
          <include name="arquillianAfterTest"/>
          <include name="testEnvironmentConfigSource"/>
          <include name="arquillianBeforeTest"/>
        </methods>
      </class> <!-- org.eclipse.microprofile.config.tck.ConfigProviderTest -->

```
These before/after also all appear in testng-results.xml but there are notes to PASS

A genuine failure looks like:

        <test-method status="FAIL" signature="testEnvironmentConfigSource()[pri:0, instance:org.eclipse.microprofile.config.tck.ConfigProviderTest@2f943d71]" name="testEnvironmentConfigSource" duration-ms="71" started-at="2018-03-01T14:50:34Z" finished-at="2018-03-01T14:50:34Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [/libertyGit/open-liberty/dev/build.image/wlp/bin/tools/ws-server.jar ConfigTCKServer --clean] but found [org.gradle.launcher.daemon.bootstrap.GradleDaemon 4.3.1]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [/libertyGit/open-liberty/dev/build.image/wlp/bin/tools/ws-server.jar ConfigTCKServer --clean] but found [org.gradle.launcher.daemon.bootstrap.GradleDaemon 4.3.1]
        at org.testng.Assert.fail(Assert.java:94)
        at org.testng.Assert.failNotEquals(Assert.java:496)
        at org.testng.Assert.assertEquals(Assert.java:125)
        at org.testng.Assert.assertEquals(Assert.java:178)
        at org.testng.Assert.assertEquals(Assert.java:188)
        at org.eclipse.microprofile.config.tck.ConfigProviderTest.testEnvironmentConfigSource(ConfigProviderTest.java:78)

So testng-results is the on valid XML file to use with the levels of the stack we are working with.

**Comment by hutchig** [comment]
SO XQuery on 
/libertyGit/open-liberty/dev/com.ibm.ws.microprofile.config_fat_tck/build/libs/autoFVT/results/tck/surefire-reports/testng-results.xml is:

**Comment by hutchig** [comment]
#build
