### ISSUE TITLE
Dependency conflict between keycloak-admin-client & liberty

### ISSUE THREAD

**Issue by yanli-yao** [OpenLiberty/open-liberty#23834]
**Describe the bug**  
When update the version of dependency keycloak-admin-client  to 20.0.2 which brought a new dependency resteasy-client which brought the new dependency smallrye, our application failed to start with the following error without trace in console:
```
[ERROR  ] CWWKZ0002E: An exception occurred while starting the application xxx-xxx. The exception message was: com.ibm.ws.container.service.state.StateChangeException: org.jboss.weld.exceptions.DeploymentException
```
And we found the error with trace in ffdc log: 
```
------Start of DE processing------ = [1/3/23 20:54:42:416 CST]
Exception = com.ibm.ws.container.service.state.StateChangeException
Source = com.ibm.ws.app.manager.module.internal.SimpleDeployedAppInfoBase
probeid = 548
Stack Dump = com.ibm.ws.container.service.state.StateChangeException: org.jboss.weld.exceptions.DeploymentException
	at com.ibm.ws.container.service.state.internal.ApplicationStateManager.fireStarting(ApplicationStateManager.java:55)
	at com.ibm.ws.container.service.state.internal.StateChangeServiceImpl.fireApplicationStarting(StateChangeServiceImpl.java:50)
	at com.ibm.ws.app.manager.module.internal.SimpleDeployedAppInfoBase.preDeployApp(SimpleDeployedAppInfoBase.java:547)
	at com.ibm.ws.app.manager.module.internal.SimpleDeployedAppInfoBase.installApp(SimpleDeployedAppInfoBase.java:508)
	at com.ibm.ws.app.manager.module.internal.DeployedAppInfoBase.deployApp(DeployedAppInfoBase.java:349)
	at com.ibm.ws.app.manager.war.internal.WARApplicationHandlerImpl.install(WARApplicationHandlerImpl.java:65)
	at com.ibm.ws.app.manager.internal.statemachine.StartAction.execute(StartAction.java:149)
	at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.enterState(ApplicationStateMachineImpl.java:1352)
	at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.run(ApplicationStateMachineImpl.java:897)
	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:238)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.jboss.weld.exceptions.DeploymentException
	at org.jboss.weld.bootstrap.events.AbstractDeploymentContainerEvent.fire(AbstractDeploymentContainerEvent.java:38)
	at org.jboss.weld.bootstrap.events.AfterDeploymentValidationImpl.fire(AfterDeploymentValidationImpl.java:28)
	at org.jboss.weld.bootstrap.WeldStartup.validateBeans(WeldStartup.java:505)
	at org.jboss.weld.bootstrap.WeldBootstrap.validateBeans(WeldBootstrap.java:93)
	at com.ibm.ws.cdi.impl.CDIContainerImpl.startInitialization(CDIContainerImpl.java:162)
	at com.ibm.ws.cdi.liberty.CDIRuntimeImpl.applicationStarting(CDIRuntimeImpl.java:479)
	at com.ibm.ws.container.service.state.internal.ApplicationStateManager.fireStarting(ApplicationStateManager.java:51)
	... 12 more
Caused by: javax.enterprise.event.ObserverException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.jboss.weld.security.NewInstanceAction.run(NewInstanceAction.java:33)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.jboss.weld.injection.Exceptions.rethrowException(Exceptions.java:40)
	at org.jboss.weld.injection.Exceptions.rethrowException(Exceptions.java:78)
	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:103)
	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:85)
	at org.jboss.weld.injection.MethodInvocationStrategy$SimpleMethodInvocationStrategy.invoke(MethodInvocationStrategy.java:168)
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:330)
	at org.jboss.weld.event.ExtensionObserverMethodImpl.sendEvent(ExtensionObserverMethodImpl.java:123)
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:308)
	at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:286)
	at javax.enterprise.inject.spi.ObserverMethod.notify(ObserverMethod.java:124)
	at org.jboss.weld.util.Observers.notify(Observers.java:166)
	at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:285)
	at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:273)
	at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:177)
	at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:171)
	at org.jboss.weld.bootstrap.events.AbstractContainerEvent.fire(AbstractContainerEvent.java:53)
	at org.jboss.weld.bootstrap.events.AbstractDeploymentContainerEvent.fire(AbstractDeploymentContainerEvent.java:35)
	... 18 more
Caused by: java.lang.NoSuchMethodError: org.eclipse.microprofile.config.Config.unwrap(Ljava/lang/Class;)Ljava/lang/Object;
	at io.smallrye.config.inject.ConfigExtension.validate(ConfigExtension.java:201)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:95)
	... 32 more
```

**Steps to Reproduce**  
Steps to reproduce the bug

**Expected behavior**  
application to be started normally

**Diagnostic information:**  
 - OpenLiberty Version: 21.0.0.9, 21.0.0.5, 22.0.0.13
 - Affected feature(s) : microprofile
 - Java Version: 
```
    openjdk version "1.8.0_345"
    IBM Semeru Runtime Open Edition (build 1.8.0_345-b01)
    Eclipse OpenJ9 VM (build openj9-0.33.1, JRE 1.8.0 Linux ppc64le-64-Bit Compressed References 20220817_430 (JIT enabled, AOT enabled)
    OpenJ9   - 1d9d16830
    OMR      - b58aa2708
    JCL      - e361c66299 based on jdk8u345-b01)
```
 - server.xml configuration 
```
 <server description="new server">
    <!-- Enable features -->
    <featureManager>
          <feature>javaee-8.0</feature>
          <feature>microProfile-3.0</feature>
          <feature>transportSecurity-1.0</feature>
          <feature>localConnector-1.0</feature>
    </featureManager>
    <sslDefault sslRef="defaultSSLSettings"/>
    <ssl clientAuthenticationSupported="true" id="defaultSSLSettings" keyStoreRef="defaultKeyStore" trustDefaultCerts="true" trustStoreRef="defaultTrustStore"/>
    <keyStore id="defaultKeyStore" location="${server.config.dir}/resources/security/keystore.p12" password="LIBERTY_KEYSTORE_PASSWORD" type="PKCS12"/>
    <keyStore id="defaultTrustStore" location="${server.config.dir}/resources/security/truststore.p12" password="LIBERTY_KEYSTORE_PASSWORD" type="PKCS12"/>

    <!-- To access this server from a remote client add a host attribute to the following element, e.g. host="*" -->
    <httpEndpoint httpPort="9080" httpsPort="9443" id="defaultHttpEndpoint"/>
    <basicRegistry id="basic" realm="BasicRealm">
        <!-- <user name="yourUserName" password="" />  -->
    </basicRegistry>
                  
    <!-- Automatically expand WAR files and EAR files -->
    <applicationManager autoExpand="true"/>
    <applicationMonitor dropinsEnabled="false" updateTrigger="disabled"/>
    <application autoStart="true" context-root="my-app" id="my-app" location="${server.config.dir}/apps/my-app.war" name="my-app" type="war"/>
</server>
```
 - If it would be useful, upload the messages.log file found in `$WLP_OUTPUT_DIR/messages.log`

**Additional context**

**Comment by yanli-yao** [comment]
The conflict was caused by the dependency smallrye. Issue resolved by updating microprofile to 4.0 and exclude the dependency smallrye-config in our pom directly. 
 ```
      <dependency>
			<groupId>org.keycloak</groupId>
			<artifactId>keycloak-admin-client</artifactId>
			<exclusions>
				<exclusion>
					<artifactId>smallrye-config</artifactId>
					<groupId>io.smallrye.config</groupId>
				</exclusion>
			</exclusions>
			<version>20.0.2</version>
		</dependency>

```
