### ISSUE TITLE
NPE from SipRouter

### ISSUE THREAD

**Issue by epj** [OpenLiberty/open-liberty#23849]
**Describe the bug**  
Under a heavy SIP load an FFDC for NullPointerException is issued from SipRouter:
java.lang.NullPointerException
	at com.ibm.ws.sip.container.router.SipRouter.detectDuplicatedToTag(SipRouter.java:1626)
	at com.ibm.ws.sip.container.router.SipRouter.handleResponse(SipRouter.java:1567)
	at com.ibm.ws.sip.container.protocol.SipProtocolLayer.processResponse(SipProtocolLayer.java:341)
	at com.ibm.ws.jain.protocol.ip.sip.SipProviderImpl.onStackResponseEvent(SipProviderImpl.java:580)
	at com.ibm.ws.jain.protocol.ip.sip.SipProviderImpl.onTransportEvent(SipProviderImpl.java:561)
	at com.ibm.ws.sip.stack.transaction.SIPTransactionStack$UACommLayer$1.run(SIPTransactionStack.java:555)
...

**Steps to Reproduce**  
Heavy load, specific steps not recreatable.

**Expected behavior**  
An NPE with FFDC should not happen in production.

**Diagnostic information:**  
 - OpenLiberty Version: 22.0.0.11
 - Affected feature(s) SIP
 - Java Version: 8

**Comment by epj** [comment]
Obsolete
