### ISSUE TITLE
NPE changing logging configuration

### ISSUE THREAD

**Issue by donbourne** [OpenLiberty/open-liberty#2385]
I'm seeing an NPE when playing with logging configuration as follows:

```
java.lang.NullPointerException
    at com.ibm.ws.collector.manager.internal.SourceManager.addSubscriber(SourceManager.java:96)
    at com.ibm.ws.collector.manager.internal.CollectorManagerImpl.subscribe(CollectorManagerImpl.java:298)
    at com.ibm.ws.logging.internal.impl.JsonLogHandler.modified(JsonLogHandler.java:132)
    at com.ibm.ws.logging.internal.impl.JsonTraceService.update(JsonTraceService.java:166)
    at com.ibm.websphere.ras.TrConfigurator.update(TrConfigurator.java:160)
    at com.ibm.ws.logging.internal.osgi.LoggingConfigurationService.updated(LoggingConfigurationService.java:108)
    at com.ibm.ws.config.admin.internal.ManagedServiceTracker$1.run(ManagedServiceTracker.java:272)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at com.ibm.ws.config.admin.internal.UpdateQueue$Queue.run(UpdateQueue.java:67)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
CWWKG0017I: The server configuration was successfully updated in 0.008 seconds.
```

Steps to recreate...

bootstrap.properties:

```
com.ibm.ws.logging.message.source=message,trace,accessLog,ffdc
com.ibm.ws.logging.message.format=basic
com.ibm.ws.logging.console.source=message,trace,accessLog,ffdc
com.ibm.ws.logging.console.format=json
```

start server 

after startup add this to server.xml and save file

```
<logging consoleLogLevel="INFO" consoleFormat="json" consoleSource="trace" messageFormat="json" messageSource="trace,accesslog" maxFileSize="100"/>
```

after that remove above logging element from server.xml

**Comment by fmhwong** [comment]
The NPE is not reproducible if I just have these 2 lines in bootstrap.properties when the server was started.
```
com.ibm.ws.logging.console.source=message,trace,accessLog,ffdc
com.ibm.ws.logging.console.format=json
```
