### ISSUE TITLE
Caused by: javax.naming.NameNotFoundException: Intermediate context does not exist: tm/default

### ISSUE THREAD

**Issue by Nandaram1994** [OpenLiberty/open-liberty#23852]
I am trying to migrate my application from websphare 9 to open liberty-22.0.0.11 server after upgrading the java from 8 to 11 but facing the below issue. Can anyone help how I can resolve it?

```
root WebApplicationContext
[12/13/22, 22:31:11:946 IST] 0000002e com.ibm.ws.logging.internal.impl.IncidentImpl                I FFDC1015I: An FFDC Incident has been created: "org.springframework.beans.factory.access.BootstrapException: Unable to return specified BeanFactory instance: factory key [server.context], from group with resource name [classpath*:beanRefContext.xml]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'server.context': FactoryBean threw exception on object creation; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'recurringPasswordConversion' defined in class path resource [Spring-Core-Timer.xml]: Invocation of init method failed; nested exception is javax.naming.NameNotFoundException: Intermediate context does not exist: tm/default com.ibm.ws.webcontainer.webapp.WebApp.notifyServletContextCreated 1341" at ffdc_22.12.13_22.31.11.0.log
[12/13/22, 22:31:11:952 IST] 0000002e com.ibm.ws.webcontainer.webapp                               E SRVE0283E: Exception caught while initializing context: org.springframework.beans.factory.access.BootstrapException: Unable to return specified BeanFactory instance: factory key [server.context], from group with resource name [classpath*:beanRefContext.xml]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'server.context': FactoryBean threw exception on object creation; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'recurringPasswordConversion' defined in class path resource [Spring-Core-Timer.xml]: Invocation of init method failed; nested exception is javax.naming.NameNotFoundException: Intermediate context does not exist: tm/default
	at org.springframework.beans.factory.access.SingletonBeanFactoryLocator.useBeanFactory(SingletonBeanFactoryLocator.java:404)
	at org.springframework.web.context.ContextLoader.loadParentContext(ContextLoader.java:563)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:322)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107)
	at com.ecologic.components.server.core.spring.EAComponentsContextLoaderListener.contextInitialized(EAComponentsContextLoaderListener.java:25)
	at com.ecologic.components.server.security.spring.SecurityInitializingContextLoaderListener.contextInitialized(SecurityInitializingContextLoaderListener.java:34)
	at com.ecologic.components.server.security.spring.SOAPWebServicesSecurityInitializingContextLoaderListener.contextInitialized(SOAPWebServicesSecurityInitializingContextLoaderListener.java:253)
	at com.ibm.ws.webcontainer.webapp.WebApp.notifyServletContextCreated(WebApp.java:2446)
	at com.ibm.ws.webcontainer31.osgi.webapp.WebApp31.notifyServletContextCreated(WebApp31.java:510)
	at com.ibm.ws.webcontainer.webapp.WebApp.initialize(WebApp.java:1044)
	at com.ibm.ws.webcontainer.webapp.WebApp.initialize(WebApp.java:6684)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost.startWebApp(DynamicVirtualHost.java:472)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost.startWebApplication(DynamicVirtualHost.java:467)
	at com.ibm.ws.webcontainer.osgi.WebContainer.startWebApplication(WebContainer.java:1188)
	at com.ibm.ws.webcontainer.osgi.WebContainer.access$100(WebContainer.java:111)
	at com.ibm.ws.webcontainer.osgi.WebContainer$3.run(WebContainer.java:985)
	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:245)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'server.context': FactoryBean threw exception on object creation; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'recurringPasswordConversion' defined in class path resource [Spring-Core-Timer.xml]: Invocation of init method failed; nested exception is javax.naming.NameNotFoundException: Intermediate context does not exist: tm/default
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:177)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getObjectFromFactoryBean(FactoryBeanRegistrySupport.java:103)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getObjectForBeanInstance(AbstractBeanFactory.java:1640)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:254)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1086)
	at org.springframework.beans.factory.access.SingletonBeanFactoryLocator.useBeanFactory(SingletonBeanFactoryLocator.java:396)
	... 21 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'recurringPasswordConversion' defined in class path resource [Spring-Core-Timer.xml]: Invocation of init method failed; nested exception is javax.naming.NameNotFoundException: Intermediate context does not exist: tm/default
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1630)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:742)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:105)
	at com.ecologic.server.ServerApplicationContextFactory.getObject(ServerApplicationContextFactory.java:157)
	at com.ecologic.server.ServerApplicationContextFactory.getObject(ServerApplicationContextFactory.java:37)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:170)
	... 27 more
Caused by: javax.naming.NameNotFoundException: Intermediate context does not exist: tm/default
	at com.ibm.ws.jndi.internal.ContextNode.getTargetNode(ContextNode.java:125)
	at com.ibm.ws.jndi.internal.ContextNode.lookup(ContextNode.java:211)
	at com.ibm.ws.jndi.internal.WSContext.lookup(WSContext.java:308)
	at com.ibm.ws.jndi.WSContextBase.lookup(WSContextBase.java:61)
	at org.apache.aries.jndi.DelegateContext.lookup(DelegateContext.java:149)
	at java.naming/javax.naming.InitialContext.lookup(InitialContext.java:409)
	at org.springframework.jndi.JndiTemplate$1.doInContext(JndiTemplate.java:155)
	at org.springframework.jndi.JndiTemplate.execute(JndiTemplate.java:87)
	at org.springframework.jndi.JndiTemplate.lookup(JndiTemplate.java:152)
	at org.springframework.jndi.JndiTemplate.lookup(JndiTemplate.java:179)
	at org.springframework.jndi.JndiLocatorSupport.lookup(JndiLocatorSupport.java:104)
	at org.springframework.scheduling.commonj.TimerManagerAccessor.afterPropertiesSet(TimerManagerAccessor.java:104)
	at org.springframework.scheduling.commonj.TimerManagerFactoryBean.afterPropertiesSet(TimerManagerFactoryBean.java:81)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1688)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1626)
	... 41 more

```

**web.xml file** 

```
<web-app id="server-webservices" xmlns="http://java.sun.com/xml/ns/javaee"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://java.sun.com/xml/ns/javaee http://java.sun.com/xml/ns/javaee/web-app_2_5.xsd"
	version="2.5" metadata-complete="true">
```

```
<!-- commonj resource definitions -->
	<resource-ref id="ResourceRef_SpringPoolTimerManager">
		<description>Spring Thread Pool WorkManager</description>
		<res-ref-name>tm/default</res-ref-name>
		<res-type>commonj.timers.TimerManager</res-type>
		<res-auth>Container</res-auth>
		<res-sharing-scope>Shareable</res-sharing-scope>
	</resource-ref>

	<resource-ref id="ResourceRef_SpringPoolWorkManager">
		<description>Spring Thread Pool WorkManager</description>
		<res-ref-name>wm/default</res-ref-name>
		<res-type>commonj.work.WorkManager</res-type>
		<res-auth>Container</res-auth>
		<res-sharing-scope>Shareable</res-sharing-scope>
	</resource-ref>

```
</web-app>

**ibm-web-bnd.xml**

```
<?xml version="1.0" encoding="UTF-8"?>
    <web-bnd xmlns="http://websphere.ibm.com/xml/ns/javaee"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="http://websphere.ibm.com/xml/ns/javaee http://websphere.ibm.com/xml/ns/javaee/ibm-web-bnd_1_0.xsd"
     version="1.0">
     
     <resource-ref name="tm/default" binding-name="tm/default"/>
     <resource-ref name="wm/default" binding-name="wm/default"/>
</web-bnd>
```

**Spring.xml**

```
<bean id="recurringServiceForDlqCleanup"
		class="org.springframework.scheduling.commonj.TimerManagerFactoryBean">
		<property name="resourceRef" value="true" />
		<property name="timerManagerName" value="tm/default"/>
		<property name="scheduledTimerListeners">
			<list>
				<ref bean="dlqScheduledListenerService" />
			</list>
		</property>
	</bean>
```

```
<bean id="abstractScheduledDlqListener"
		class="org.springframework.scheduling.commonj.ScheduledTimerListener"
		abstract="true">
		<property name="delay" value="1801000" />
		<property name="period" value="86400000" />
	</bean>
```

**Comment by kinueng** [comment]
There are additional conversations about this issue on Gitter https://gitter.im/OpenLiberty/developer-experience?at=639957c2a8211f623d80a608
