### ISSUE TITLE
Test Failure: build.feature.java.level.MinJavaLevelTestAToL.testFeaturesStart

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#23873]
RTC 292352

```
testFeaturesStart:junit.framework.AssertionFailedError: 2022-08-24-10:27:28:147 ATTENTION: ONLY ASSOCIATE THIS FAILURE WITH ANOTHER DEFECT/ISSUE IF THE FEATURE SET AND MESSAGES ARE THE SAME.
Features(s) [logstashcollector-1.0] did not start/stop cleanly on their own, due to the following exceptions: [logstashcollector-1.0=java.lang.RuntimeException: Server stop failed with RC 21.
Stdout:

Stopping server build.feature.java.level.a.to.l.server.
Server build.feature.java.level.a.to.l.server stop failed. Check server logs for details.

Stderr:
]
at build.feature.java.level.MinJavaLevelTestAToL.testFeaturesStart(MinJavaLevelTestAToL.java:229)
at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:197)
at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:347)
at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:171)
```

**Comment by tonyreigns** [comment]
This issue hasn't occurred in over a month and is not reproducible.
