### ISSUE TITLE
ManagementSecurityAuthorizationTable is not thread-safe

### ISSUE THREAD

**Issue by tjwatson** [OpenLiberty/open-liberty#23889]
`com.ibm.ws.ui.tool.serverConfig.fat.gui.nd.rw.tests.ServerConfigValidatorTest` is rather unstable.  I think part of the problem is `ManagementSecurityAuthorizationTable` is not thread-safe.   While running this test in a build I saw this FFDC.  Looking at the `com.ibm.ws.management.security.internal.ManagementSecurityAuthorizationTable` there are tables that are managed without being thread-safe.  The following Maps need to be accessed in a thread-safe way:

```java
    private final Map<String, RoleSet> accessIdToRoles = new HashMap<String, RoleSet>();
    private final Map<String, String> userToAccessId = new HashMap<String, String>();
    private final Map<String, String> groupToAccessId = new HashMap<String, String>();
    private final Map<String, RoleSet> userToRoles = new HashMap<String, RoleSet>();
    private final Map<String, RoleSet> groupToRoles = new HashMap<String, RoleSet>();
```

```
Stack Dump = java.util.ConcurrentModificationException
	at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1511)
	at java.base/java.util.HashMap$KeyIterator.next(HashMap.java:1534)
	at com.ibm.ws.management.security.internal.ManagementSecurityAuthorizationTable.findRolesForAccessId(ManagementSecurityAuthorizationTable.java:268)
	at com.ibm.ws.management.security.internal.ManagementSecurityAuthorizationTable.rolesForAccessId(ManagementSecurityAuthorizationTable.java:241)
	at com.ibm.ws.management.security.internal.ManagementSecurityAuthorizationTable.getRolesForAccessId(ManagementSecurityAuthorizationTable.java:151)
	at com.ibm.ws.management.security.internal.ManagementSecurityAuthorizationTable.getRolesForAccessId(ManagementSecurityAuthorizationTable.java:161)
	at com.ibm.ws.security.authorization.builtin.internal.BuiltinAuthorizationService.getRolesForAccessId(BuiltinAuthorizationService.java:276)
	at com.ibm.ws.security.authorization.builtin.internal.BuiltinAuthorizationService.useAppBndForAccessDecision(BuiltinAuthorizationService.java:353)
	at com.ibm.ws.security.authorization.builtin.internal.BuiltinAuthorizationService.isSubjectAuthorized(BuiltinAuthorizationService.java:335)
	at com.ibm.ws.security.authorization.builtin.internal.BuiltinAuthorizationService.isAuthorized(BuiltinAuthorizationService.java:163)
	at com.ibm.ws.webcontainer.security.WebAppSecurityCollaboratorImpl.authorize(WebAppSecurityCollaboratorImpl.java:1302)
	at com.ibm.ws.webcontainer.security.WebAppSecurityCollaboratorImpl.authorize(WebAppSecurityCollaboratorImpl.java:1629)
	at com.ibm.ws.webcontainer.security.WebAppSecurityCollaboratorImpl.determineWebReply(WebAppSecurityCollaboratorImpl.java:1033)
	at com.ibm.ws.webcontainer.security.WebAppSecurityCollaboratorImpl.determineWebReply(WebAppSecurityCollaboratorImpl.java:1001)
	at com.ibm.ws.webcontainer.security.WebAppSecurityCollaboratorImpl.performSecurityChecks(WebAppSecurityCollaboratorImpl.java:698)
	at com.ibm.ws.webcontainer.security.WebAppSecurityCollaboratorImpl.preInvoke(WebAppSecurityCollaboratorImpl.java:619)
	at com.ibm.wsspi.webcontainer.collaborator.CollaboratorHelper.preInvokeCollaborators(CollaboratorHelper.java:472)
	at com.ibm.ws.webcontainer.osgi.collaborator.CollaboratorHelperImpl.preInvokeCollaborators(CollaboratorHelperImpl.java:272)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1184)
	at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:5080)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.handleRequest(DynamicVirtualHost.java:318)
	at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:1009)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:283)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1248)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:470)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:429)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:569)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:503)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:363)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.ready(HttpInboundLink.java:330)
	at com.ibm.ws.channel.ssl.internal.SSLConnectionLink.determineNextChannel(SSLConnectionLink.java:1131)
	at com.ibm.ws.channel.ssl.internal.SSLConnectionLink$MyReadCompletedCallback.complete(SSLConnectionLink.java:680)
	at com.ibm.ws.channel.ssl.internal.SSLReadServiceContext$SSLReadCompletedCallback.complete(SSLReadServiceContext.java:1826)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:516)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueManager.java:586)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:970)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:1059)
	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:247)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:866)

```

**Comment by jvanhill** [comment]
It appears the two maps that we would have an issue with ConcurrentModificationExceptions would be the `groupToRoles` and the `userToRoles` maps as we iterate over them.

This can be remedied by using ConcurrentHashMap instead of the plain HashMap.

**Comment by tjwatson** [comment]
> It appears the two maps that we would have an issue with ConcurrentModificationExceptions would be the `groupToRoles` and the `userToRoles` maps as we iterate over them.
> 
> This can be remedied by using ConcurrentHashMap instead of the plain HashMap.

I think `accessIdToRoles`, `userToAccessId`, `groupToAccessId` also need a thread-safe map because they can be cleared.  I assume from other threads with this method.

```java
    public void notifyOfUserRegistryChange() {
        isIgnoreCaseSet = false;
        accessIdToRoles.clear();
        userToAccessId.clear();
        groupToAccessId.clear();
    }
```
HashMap is not thread safe and should not be accessed without some protection.  I also do not think swapping in a `ConncurrentHashMap` will be good enough for the iteration cases either.  There is this code:

```java
            for (String user : userToRoles.keySet()) {
                String userAccessId = userToAccessId.get(user);
                if (userAccessId == null) {
                    if (AccessIdUtil.isUserAccessId(user)) {
                        userAccessId = user;
                    } else {
                        // user is not accessId format, so we have to look up the user registry.
                        userAccessId = getUserAccessId(user);
                        if (userAccessId == null) {
                            if (TraceComponent.isAnyTracingEnabled() && tc.isDebugEnabled()) {
                                Tr.debug(tc, "Unable to determine accessId of user " + user);
                            }
                            // We could not determine the access ID here, skip
                            // For all unknown IDs we try to re-compute each time
                            // we see it. This is probably the right thing to do
                            // as the user could add that entry in the future.
                            continue;
                        }
                    }
                    userToAccessId.put(user, userAccessId);
                }
                if (accessIdToRoles.get(userAccessId) == null) {
                    accessIdToRoles.put(userAccessId, userToRoles.get(user)); <<<< the key could have been removed since we started iterating
                }
                if (isMatch(accessId, userAccessId)) {
                    return accessIdToRoles.get(userAccessId);
                }
            }
```
The call back to the map for `userToRoles.get(user)` while iterating on the key set for `userToRoles` could result in a null value if the `user` key got removed by another thread while iterating here.
