### ISSUE TITLE
The io.opentelemetry.api.baggage.propagation package is not visible to the application

### ISSUE THREAD

**Issue by tevans78** [OpenLiberty/open-liberty#23925]
Trying to access the package results in an exception

```
junit.framework.AssertionFailedError: 2023-01-16-17:29:10:779 ERROR: Caught exception attempting to call test method testW3CBaggagePropagator on servlet io.openliberty.microprofile.telemetry.internal_fat.apps.api.BaggageAPIServlet
java.lang.NoClassDefFoundError: io.opentelemetry.api.baggage.propagation.W3CBaggagePropagator
at io.openliberty.microprofile.telemetry.internal_fat.apps.api.BaggageAPIServlet.testW3CBaggagePropagator(BaggageAPIServlet.java:60)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at componenttest.app.FATServlet.doGet(FATServlet.java:73)
at <unknown class>.service(HttpServlet.java:527)
at <unknown class>.service(HttpServlet.java:614)
at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1260)
at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:748)
at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:445)
at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1296)
at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:5080)
at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.handleRequest(DynamicVirtualHost.java:318)
at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:1009)
at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:283)
at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1248)
at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:470)
at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:429)
at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:569)
at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:503)
at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:363)
at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.ready(HttpInboundLink.java:330)
at com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.sendToDiscriminators(NewConnectionInitialReadCallback.java:169)
at com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.complete(NewConnectionInitialReadCallback.java:77)
at com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:516)
at com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueManager.java:586)
at com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:970)
at com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:1059)
at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:247)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:866)
Caused by: java.lang.ClassNotFoundException: io.opentelemetry.api.baggage.propagation.W3CBaggagePropagator
at com.ibm.ws.classloading.internal.AppClassLoader.findClassCommonLibraryClassLoaders(AppClassLoader.java:736)
at com.ibm.ws.classloading.internal.AppClassLoader.findClass(AppClassLoader.java:321)
at com.ibm.ws.classloading.internal.AppClassLoader.findOrDelegateLoadClass(AppClassLoader.java:708)
at com.ibm.ws.classloading.internal.AppClassLoader.loadClass(AppClassLoader.java:580)
at com.ibm.ws.classloading.internal.AppClassLoader.loadClass(AppClassLoader.java:547)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1086) 
```

**Comment by tevans78** [comment]
Note that strictly it isn’t listed in the UFO … `io.opentelemetry.api.baggage` is listed but not the `propagation` sub-package

**Comment by tevans78** [comment]
but this does mention it - https://github.com/open-telemetry/opentelemetry-specification/blob/v1.14.0/specification/baggage/api.md#propagation

**Comment by Azquelt** [comment]
I think we should make this package visible as it's part of the opentelemetry-java API jar, and appears to be an API package.

**Comment by fmhwong** [comment]
I updated the UFO to match what we have in https://github.com/OpenLiberty/open-liberty/blob/4c753201bc652bc54cf57662fd47a98b32b89877/dev/com.ibm.websphere.appserver.features/visibility/public/mpTelemetry-1.0/io.openliberty.mpTelemetry-1.0.feature plus the new `io.opentelemetry.api.baggage.propagation`
