### ISSUE TITLE
Memory in com.ibm.ws.wsat.service.WebClient when creating thread context class loaders

### ISSUE THREAD

**Issue by tjwatson** [OpenLiberty/open-liberty#24047]
**Describe the bug**  
Repeated calls to LogManager$Lock.getLogDomain(Bundle), each one adding a bundle named "gateway.bundle.Thread_Context...." to the "domains" HashMap in Felix SCR.  These entries never get removed and the Map keeps growing leading to a memory leak.
```
 at org/apache/felix/scr/impl/logger/LogManager$Lock.getLogDomain(LogManager.java:69)
 at org/apache/felix/scr/impl/logger/LogManager.getLogger(LogManager.java:174)
 at org/apache/felix/scr/impl/logger/ScrLogManager.bundle(ScrLogManager.java:97)
 at org/apache/felix/scr/impl/logger/ScrLogManager$ScrLoggerFacade.bundle(ScrLogManager.java:282)
 at org/apache/felix/scr/impl/BundleComponentActivator.(BundleComponentActivator.java:202)
 at org/apache/felix/scr/impl/Activator.loadComponents(Activator.java:552)
 at org/apache/felix/scr/impl/Activator.access$200(Activator.java:70)
 at org/apache/felix/scr/impl/Activator$ScrExtension.start(Activator.java:421)
 at org/apache/felix/scr/impl/AbstractExtender.createExtension(AbstractExtender.java:196)
 at org/apache/felix/scr/impl/AbstractExtender.modifiedBundle(AbstractExtender.java:169)
 at org/apache/felix/scr/impl/AbstractExtender.addingBundle(AbstractExtender.java:139)
 at org/apache/felix/scr/impl/AbstractExtender.addingBundle(AbstractExtender.java:49)
 at org/osgi/util/tracker/BundleTracker$Tracked.customizerAdding(BundleTracker.java:475)
 at org/osgi/util/tracker/BundleTracker$Tracked.customizerAdding(BundleTracker.java:1)
 at org/osgi/util/tracker/AbstractTracked.trackAdding(AbstractTracked.java:256)
 at org/osgi/util/tracker/AbstractTracked.track(AbstractTracked.java:229(Compiled Code))
 at org/osgi/util/tracker/BundleTracker$Tracked.bundleChanged(BundleTracker.java:450(Compiled Code))
 at org/eclipse/osgi/internal/framework/BundleContextImpl.dispatchEvent(BundleContextImpl.java:935(Compiled Code))
 at org/eclipse/osgi/framework/eventmgr/EventManager.dispatchEvent(EventManager.java:228(Compiled Code))
 at org/eclipse/osgi/framework/eventmgr/ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
 at org/eclipse/osgi/internal/framework/EquinoxEventPublisher.publishBundleEventPrivileged(EquinoxEventPublisher.java:229)
 at org/eclipse/osgi/internal/framework/EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:138)
 at org/eclipse/osgi/internal/framework/EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:130)
 at org/eclipse/osgi/internal/framework/EquinoxContainerAdaptor.publishModuleEvent(EquinoxContainerAdaptor.java:206(Compiled Code))
 at org/eclipse/osgi/container/Module.publishEvent(Module.java:499(Compiled Code))
 at org/eclipse/osgi/container/Module.start(Module.java:486)
 at org/eclipse/osgi/internal/framework/EquinoxBundle.start(EquinoxBundle.java:439)
 at com/ibm/ws/classloading/internal/GatewayBundleFactory.start(GatewayBundleFactory.java:129)
 at com/ibm/ws/classloading/internal/GatewayBundleFactory.createGatewayBundleClassLoader(GatewayBundleFactory.java:90)
 at com/ibm/ws/classloading/internal/ClassLoadingServiceImpl.createTCCL(ClassLoadingServiceImpl.java:633(Compiled Code))
 at com/ibm/ws/classloading/internal/ClassLoadingServiceImpl.access$200(ClassLoadingServiceImpl.java:102)
 at com/ibm/ws/classloading/internal/ClassLoadingServiceImpl$4.createInstance(ClassLoadingServiceImpl.java:593)
 at com/ibm/ws/classloading/internal/ClassLoadingServiceImpl$4.createInstance(ClassLoadingServiceImpl.java:590)
 at com/ibm/ws/classloading/internal/util/CanonicalStore.retrieveOrCreate(CanonicalStore.java:84(Compiled Code))
 at com/ibm/ws/classloading/internal/util/CanonicalStore.retrieveOrCreate(CanonicalStore.java:74)
 at com/ibm/ws/classloading/internal/ClassLoadingServiceImpl.createThreadContextClassLoader(ClassLoadingServiceImpl.java:590)
 at com/ibm/ws/classloading/internal/ClassLoadingServiceImpl.createThreadContextClassLoader(ClassLoadingServiceImpl.java:98)
 at com/ibm/ws/wsat/tm/impl/TranManagerImpl.getThreadClassLoader(TranManagerImpl.java:338)
 at com/ibm/ws/wsat/service/impl/WebClientImpl$9.run(WebClientImpl.java:218)
 at java/security/AccessController.doPrivileged(AccessController.java:738(Compiled Code))
 at com/ibm/ws/wsat/service/impl/WebClientImpl.invoke(WebClientImpl.java:214)
 at com/ibm/ws/wsat/service/impl/WebClientImpl.prepared(WebClientImpl.java:146)
 at com/ibm/ws/wsat/tm/impl/CoordinatorResource.replayCompletion(CoordinatorResource.java:43)
 at com/ibm/tx/jta/embeddable/impl/WSATRecoveryCoordinator.replayCompletion(WSATRecoveryCoordinator.java:133)
 at com/ibm/tx/jta/embeddable/impl/EmbeddableTransactionImpl.replay(EmbeddableTransactionImpl.java:1067)
 at com/ibm/tx/jta/embeddable/impl/EmbeddableTransactionImpl.retryCompletion(EmbeddableTransactionImpl.java:1020)
 at com/ibm/tx/jta/embeddable/impl/EmbeddableTransactionImpl.recover(EmbeddableTransactionImpl.java:770)
 at com/ibm/tx/jta/impl/RecoveryManager.resync(RecoveryManager.java:1457)
 at com/ibm/tx/jta/impl/RecoveryManager.performResync(RecoveryManager.java:2188)
 at com/ibm/tx/jta/impl/RecoveryManager.run(RecoveryManager.java:2143)
 at java/lang/Thread.run(Thread.java:830)
```

Ultimately this is getting driven by this code:

https://github.com/OpenLiberty/open-liberty/blob/14225e8f48a9040e72e0128f63ecd28de4f57f0f/dev/com.ibm.ws.wsat.common/src/com/ibm/ws/wsat/service/impl/WebClientImpl.java#L214-L235
 
That code seems to have a very large overhead to create a new TCCL each time for the WebClientImpl class `tranService.getThreadClassLoader(WebClientImpl.class);`.  That leads to a bug in Felix SCR which has been fixed in version 2.2.6 (https://issues.apache.org/jira/browse/FELIX-6581).

**Steps to Reproduce**  
Use the WebClientImpl

**Expected behavior**  
Don't have a memory leak

**Comment by tjwatson** [comment]
The memory leak in Felix SCR is fixed now for the next release.  I opened a follow on issue to address what I think is a performance issue with WebClientImpl in issue #24048.
