### ISSUE TITLE
java.lang.IllegalStateException: cannot remove cookie if the response is committed

### ISSUE THREAD

**Issue by c00crane** [OpenLiberty/open-liberty#24062]
I'm running tests that I'm developing for Jakarta logout.
The test in question uses @OpenIdAuthenticationMechanismDefinition to protect/access a test app.  I can log in and access the test app just fine.  I then try to logout using request.logout() and I hit the following failure:
`[1/24/23, 17:18:58:256 CST] 0000003d SystemOut                                                    O Loading config from: /openIdConfig.properties
[1/24/23, 17:18:58:323 CST] 0000003d com.ibm.ws.webcontainer.util.ApplicationErrorUtils           E SRVE0777E: Exception thrown by application class 'com.ibm.ws.webcontainer.srt.SRTServletResponse.removeCookie:2,626'
java.lang.IllegalStateException: cannot remove cookie if the response is committed
	at com.ibm.ws.webcontainer.srt.SRTServletResponse.removeCookie(SRTServletResponse.java:2626)
	at com.ibm.ws.webcontainer.security.SSOCookieHelperImpl.removeSSOCookieFromResponse(SSOCookieHelperImpl.java:215)
	at com.ibm.ws.webcontainer.security.AuthenticateApi.logout(AuthenticateApi.java:206)
	at com.ibm.ws.webcontainer.security.AuthenticateApi.logoutServlet30(AuthenticateApi.java:649)
	at com.ibm.ws.webcontainer.security.WebAppSecurityCollaboratorImpl.logout(WebAppSecurityCollaboratorImpl.java:1201)
	at com.ibm.ws.webcontainer.srt.SRTServletRequest.logout(SRTServletRequest.java:4012)
	at oidc.client.basicLogout.servlets.BasicLogoutServlet.doPost(BasicLogoutServlet.java:63)`
	
I have commits from https://github.com/OpenLiberty/open-liberty/pull/24014, https://github.com/OpenLiberty/open-liberty/pull/23969  as well as an additional update to dev/io.openliberty.security.jakartasec.3.0.internal.cdi/src/io/openliberty/security/jakartasec/cdi/beans/OidcHttpAuthenticationMechanism.java (from Teddy).

[logout.zip](https://github.com/OpenLiberty/open-liberty/files/10503530/logout.zip)

**Comment by teddyjtorres** [comment]
The code path in cleanSubject commits the response when it needs to redirect to the logout redirect uri,

> [1/24/23, 17:18:58:258 CST] 0000003d id=172f68b0 com.ibm.ws.security.javaeesec.HttpMessageContextImpl         > redirect Entry  
>                                                                                                                https://localhost:8940/EndSessionServlet/end_session?client_id=client_1&post_logout_redirect_uri=https%3A%2F%2Flocalhost%3A8940%2FPostLogoutServlet%2FPostLogout

but, request.logout needs to continue much later after this to clean the cookies and the response is already committed.

**Comment by c00crane** [comment]
Problem has been resolved and the test that was hitting it has been enabled.
