### ISSUE TITLE
Test Failure (20180223-0339): org.eclipse.microprofile.metrics.test.MpMetricTest.testApplicationMetricsJSON

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#2427]
Seen in the currently in-flight LAOS Continuous build: LAOS Continuous build 20180223-0339. This is a TCK failure and thus likely a stop ship - @marikaj@ca.ibm.com to confirm.

java.lang.AssertionError: JSON path 'metricTest.test1.histogram'.mean doesn't match.
Expected: <499.5F>
  Actual: 499.59552

at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:88)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:57)
at java.lang.reflect.Constructor.newInstance(Constructor.java:437)
at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:77)
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:102)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:57)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:182)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:190)
at com.jayway.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:572)
at com.jayway.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
at com.jayway.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:731)
at com.jayway.restassured.internal.ResponseSpecificationImpl.this$2$validateResponseIfRequired(ResponseSpecificationImpl.groovy)
at com.jayway.restassured.internal.ResponseSpecificationImpl$this$2$validateResponseIfRequired$1.callCurrent(Unknown Source)
at com.jayway.restassured.internal.ResponseSpecificationImpl.content(ResponseSpecificationImpl.groovy:227)
at com.jayway.restassured.specification.ResponseSpecification$content$2.callCurrent(Unknown Source)
at com.jayway.restassured.internal.ResponseSpecificationImpl.body(ResponseSpecificationImpl.groovy:210)
at com.jayway.restassured.internal.ValidatableResponseOptionsImpl.body(ValidatableResponseOptionsImpl.java:257)
at org.eclipse.microprofile.metrics.test.MpMetricTest.testApplicationMetricsJSON(MpMetricTest.java:438)

**Comment by fmhwong** [comment]
RTC 251858
We shall exclude HistogramTest for now until Microprofile Metrics TCK 1.0 is fixed.
