### ISSUE TITLE
Fix TelemetryMisconfigTest (testNotKnownEndpoint)

### ISSUE THREAD

**Issue by Yas-Franco** [OpenLiberty/open-liberty#24333]
There is a [defect](https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.workitem.viewWorkItem&id=294667) with the following error: 

```
testNotKnownEndpoint:java.lang.NullPointerException: 2023-02-11-01:56:56:692 Cannot invoke "String.isEmpty()" because the return value of "componenttest.topology.impl.LibertyServer.waitForStringInLogUsingMark(String)" is null
at io.openliberty.microprofile.telemetry.internal_fat.TelemetryMisconfigTest.testNotKnownEndpoint(TelemetryMisconfigTest.java:185)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:204)
at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:364)
at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:178)
```

**Comment by Yas-Franco** [comment]
The logs show this error message: 

`Failed to export spans. The request could not be executed. Full error message: No such host is known (invalid_jaeger_endpoint)`

but the [test](https://github.com/OpenLiberty/open-liberty/blob/integration/dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryMisconfigTest.java#L185) checks this string: 

`"Failed to export spans. The request could not be executed. Full error message:" + INVALID_JAEGER_ENDPOINT.toLowerCase()`

It seems like some logs have brackets and the information in a different order so using a regular expression to cover all formats of the error should fix this.
