### ISSUE TITLE
NPE when access_token missing from token endpoint response

### ISSUE THREAD

**Issue by c00crane** [OpenLiberty/open-liberty#24338]
I've omitted the access_token from the response from the token endpoint and received an NPE.

`[2/16/23, 10:18:39:103 CST] 00000052 id=00000000 nliberty.security.jakartasec.identitystore.OidcIdentityStore 3 validate 
                                                                                                               Exception occurred for client client_1
                                                                                                               java.lang.NullPointerException
	at io.openliberty.security.jakartasec.identitystore.OidcIdentityStore.createAccessTokenFromTokenResponse(OidcIdentityStore.java:167)
	at io.openliberty.security.jakartasec.identitystore.OidcIdentityStore.validate(OidcIdentityStore.java:82)
	at org.jboss.weld.generated.proxies.security.enterprise.identitystore.IdentityStore$329146295$Proxy$_$$_WeldClientProxy.validate(Unknown Source)
	at com.ibm.ws.security.javaeesec.identitystore.IdentityStoreHandlerImpl.validate(IdentityStoreHandlerImpl.java:70)
	at com.ibm.ws.security.javaeesec.identitystore.IdentityStoreHandlerImpl.validate(IdentityStoreHandlerImpl.java:58)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.weld.bean.proxy.AbstractBeanInstance.invoke(AbstractBeanInstance.java:38)
	at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:106)
	at org.jboss.weld.generated.proxies.security.enterprise.identitystore.IdentityStoreHandler$1302446337$Proxy$_$$_Wel`

**Comment by c00crane** [comment]
[npe.zip](https://github.com/OpenLiberty/open-liberty/files/10759915/npe.zip)

**Comment by c00crane** [comment]
Tests are no longer getting the NPE.
