### ISSUE TITLE
Skipped Faces Tests (Caused by JavaScript Changes in 4.0.0-RC5)

### ISSUE THREAD

**Issue by volosied** [OpenLiberty/open-liberty#24387]
See 4.0.0-RC5 PR:  https://github.com/OpenLiberty/open-liberty/pull/24370 

**79** Tests Skipped. 26 are being enabled

Applications: 
[applications.zip](https://github.com/OpenLiberty/open-liberty/files/10865518/applications.zip)
[23apps.zip](https://github.com/OpenLiberty/open-liberty/files/10905012/23apps.zip)

## com.ibm.ws.jsf_fat_lWAS_faces4.0 
- JSF20AJAXTag
  - testDisabledFalse
  - testEventDefault
  - testEventSpecified
  - testExecuteAll
  - testExecuteDefault
  - testExecuteForm
  - testExecuteMultiple
  - testExecuteSingle
  - testExecuteThis
  - testListener
  - testOnError
  - testOnEvent
  - testRenderAll
  - testRenderForm
  - testRenderMultipleComponents
  - testRenderSingleComponent
  - testRenderThis
  - testImmediateFalse
  - testImmediateTrue
  - testImmediateDefault
- ~JSF20BeanValidation~ -> Merged: WS-CD-Open/pull/28935
  - ~testSizeConstraint~
  - ~testNotNullConstraint~
  - ~testMinConstraint~
  - ~testMaxConstraint~
  - ~testNullConstraint~
  - ~testAssertTrueConstraint~
  - ~testAssertFalseConstraint~
  - ~testFutureConstraint~
  - ~testPastConstraint~
  - ~testDigitsConstraint~
  - ~testDecimalMaxConstraint~
  - ~testDecimalMinConstraint~
  - ~testPatternConstraint~
  - ~testPatternConstraintOnMethod~
  - ~testValidateBeanTagDefault~
  - ~testValidateBeanTagDisabledTrue~
  - ~testValidationBeanTagGroups~
  - ~testValidationBeanTagWrapMultiple~
  - ~testCustomConstraint~
- JSF20Behaviors
  - ~testAnnotated~ -> enabled WS-CD-Open/pull/28943
  - ~testDefined~ -> enabled WS-CD-Open/pull/28943
  - testAjax
- JSF20JavaScriptAPI
  - testExecuteAll
  - testExecuteDefault
  - testExecuteForm
  - testExecuteMultiple
  - testExecuteNone
  - testExecuteSingle
  - testExecuteThis
  - testOnError
  - testOnEvent
  - testRenderDefault
  - testRenderForm
  - testRenderMultipleComponents
  - testRenderNone
  - testRenderSingleComponent
  - testRenderThis
  - testOnEventCall
  - testOnErrorCall
- JSF20Navigation
  - testConditional
 - JSF20AJAX (recently ported from old testsuite bucket) 
   - testJSF
   - testDojo
   

## com.ibm.ws.jsf.2.2_fat
Failures: 
- [JSF22ComponentTester_TestCommandLinkOrder](https://github.com/OpenLiberty/open-liberty/blob/382c0bac1dbf3e85ed565eb603829255723a08ee/dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSF22ComponentTesterTests.java#L230)
  - JSF22ComponentTester_TestCommandLinkOrder: test output is not correct: Not called 
- [testResetValues](https://github.com/OpenLiberty/open-liberty/blob/c567d068ed5b9d878138d7d22ed6d09d2bc03930/dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSF22MiscellaneousTests.java#L194) (JSF22MiscellaneousTests)
  - expected:<[1]> but was:<[0]> 

Errors ( "missing formal parameter "):
- [JSF22ClientWindowTests](https://github.com/OpenLiberty/open-liberty/blob/7fad9e794d71ef64b1d8cec461b2f50b1094e28a/dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSF22ClientWindowTests.java#L48)  
[jsfTestServer2.zip](https://github.com/OpenLiberty/open-liberty/files/10905261/jsfTestServer2.zip)

  - JSF22ClientWindow_TestAjax
  - JSF22ClientWindow_TestSimpleLink
  - JSF22ClientWindow_TestSimpleLinkNewWindow	JSF22ClientWindow_TestDisabledLink
  - JSF22ClientWindow_TestCommandButton
  - JSF22ClientWindow_TestCommandLink
  - JSF22ClientWindow_TestButton
  - JSF22ClientWindow_TestButtonDisabled
  - JSF22ClientWindow_TestMultipleBasePages
- JSFCompELTests.java
  - testAjaxEvent
- JSF22ResetValuesAndAjaxDelayTests.java
  - testResetValues
  - [testAjaxZeroDelay](https://github.com/OpenLiberty/open-liberty/blob/9185922ddd82d1b5a4f9300d7f71ecd6d32b1f81/dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSF22ResetValuesAndAjaxDelayTests.java#L179)
- JSF22AppConfigPopTests.java
  - testACPNavigationRule -> https://github.com/OpenLiberty/open-liberty/pull/24572
- JSF22AparTests.java
  - testViewScopedJSFManagedBeanPreDestroy -> Enabled with :https://github.com/OpenLiberty/open-liberty/pull/24547

## com.ibm.ws.jsf.2.3_fat

Failures: 
- ~~testFaceletRefreshPeriodProduction~~ [FIXED via context parameter]
  - ~~The correct value of the jakarta.faces.FACELETS_REFRESH_PERIOD context parameter was not found~~
- testPushWebsocket
  -   Expected to find 'Called onopen listener' in response, but response was: JSF 2.3 WebSocket test JSF 2.3 WebSocket - Test message pushed from server to client Click here to send message 
- testOpenAndCloseWebsocket
  - null 
  
Errors ( "syntax error"):
- JSF23CDIGeneralTests.java
  - testInjectableELImplicitObjects
  - testFacesConverterBeanInjection
  - testFacesValidatorBeanInjection
  - testFacesBehaviorBeanInjection
- JSF23ExternalContextStartupShutdownTests.java
  - testExternalContextGetRealPath_Startup_Shutdown -> https://github.com/OpenLiberty/open-liberty/pull/24549
- JSF23CommandScriptTests.java
  - testCommandScriptAutorunDefaultExecute
  - testCommandScriptActionListener
  - testCommandScriptActionListenerAttr
  - testCommandScriptAutorun
  - testCommandScriptParam
  - testCommandScriptButton
- JSF23EvalScriptsTests.java
    - testEvalScriptsSimple
    - testEvalScriptsList
    - testEvalScriptsFunction
    - testEvalScriptsMultiField
- JSF23SpecIssueTests.java
  - testSpecIssue790Test2
- JSF23SelectOneRadioGroupTests.java
  -  testSelectOneRadioGroup_AjaxRequest

## io.openliberty.org.apache.myfaces.4.0_fat

- AjaxRenderExecuteThisTest
  - testAjaxRender
  - testAjaxExecuteThis
  - testAjaxRenderThis
- AnnotationLiteralsTest
  - testFlowMap -> enabled here: https://github.com/OpenLiberty/open-liberty/pull/24551/files
- MultipleInputFileTest
  - testNoMultiple_WithAjax_SingleFile
  - testNoMultiple_WithAjax_MultipleFiles
  - testWithMultiple_WithAjax_SingleFile
  - testWithMultiple_WithAjax_MultipleFiles
- ClientWindowScopedTest
  - testClientWindowReuseInFlow -> https://github.com/OpenLiberty/open-liberty/pull/24574

**Comment by volosied** [comment]
Example of the JS HTMLUnit Error: 
```
2023-02-19-16:34:30:784 syntax error (http://localhost:8010/EvalScripts/jakarta.faces.resource/faces.js.xhtml?ln=jakarta.faces#2)

java.lang.Throwable: 2023-02-19-16:34:30:784 syntax error (http://localhost:8010/EvalScripts/jakarta.faces.resource/faces.js.xhtml?ln=jakarta.faces#2)
at componenttest.custom.junit.runner.FATRunner.newThrowableWithTimeStamp(FATRunner.java:338)
at componenttest.custom.junit.runner.FATRunner.access$700(FATRunner.java:70)
at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:304)
at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:364)
at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:178)
at componenttest.rules.repeater.RepeatTests$CompositeRepeatTestActionStatement.evaluate(RepeatTests.java:145)
Caused by: com.gargoylesoftware.htmlunit.ScriptException: syntax error (http://localhost:8010/EvalScripts/jakarta.faces.resource/faces.js.xhtml?ln=jakarta.faces#2)
at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$HtmlUnitContextAction.run(JavaScriptEngine.java:883)
at net.sourceforge.htmlunit.corejs.javascript.Context.call(Context.java:628)
at net.sourceforge.htmlunit.corejs.javascript.ContextFactory.call(ContextFactory.java:513)
at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.compile(JavaScriptEngine.java:709)
at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.compile(JavaScriptEngine.java:674)
at com.gargoylesoftware.htmlunit.html.HtmlPage.loadJavaScriptFromUrl(HtmlPage.java:1094)
at com.gargoylesoftware.htmlunit.html.HtmlPage.loadExternalJavaScriptFile(HtmlPage.java:982)
at com.gargoylesoftware.htmlunit.html.HtmlScript.executeScriptIfNeeded(HtmlScript.java:352)
at com.gargoylesoftware.htmlunit.html.HtmlScript$2.execute(HtmlScript.java:238)
at com.gargoylesoftware.htmlunit.html.HtmlScript.onAllChildrenAddedToPage(HtmlScript.java:257)
at com.gargoylesoftware.htmlunit.html.HTMLParser$HtmlUnitDOMBuilder.endElement(HTMLParser.java:747)
at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source)
at com.gargoylesoftware.htmlunit.html.HTMLParser$HtmlUnitDOMBuilder.endElement(HTMLParser.java:704)
at org.cyberneko.html.HTMLTagBalancer.callEndElement(HTMLTagBalancer.java:1170)
at org.cyberneko.html.HTMLTagBalancer.endElement(HTMLTagBalancer.java:1072)
at org.cyberneko.html.filters.DefaultFilter.endElement(DefaultFilter.java:206)
at org.cyberneko.html.filters.NamespaceBinder.endElement(NamespaceBinder.java:330)
at org.cyberneko.html.HTMLScanner$ContentScanner.scanEndElement(HTMLScanner.java:3126)
at org.cyberneko.html.HTMLScanner$ContentScanner.scan(HTMLScanner.java:2093)
at org.cyberneko.html.HTMLScanner.scanDocument(HTMLScanner.java:920)
at org.cyberneko.html.HTMLConfiguration.parse(HTMLConfiguration.java:499)
at org.cyberneko.html.HTMLConfiguration.parse(HTMLConfiguration.java:452)
at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
at com.gargoylesoftware.htmlunit.html.HTMLParser$HtmlUnitDOMBuilder.parse(HTMLParser.java:924)
at com.gargoylesoftware.htmlunit.html.HTMLParser.parse(HTMLParser.java:238)
at com.gargoylesoftware.htmlunit.html.HTMLParser.parseHtml(HTMLParser.java:184)
at com.gargoylesoftware.htmlunit.DefaultPageCreator.createHtmlPage(DefaultPageCreator.java:269)
at com.gargoylesoftware.htmlunit.DefaultPageCreator.createPage(DefaultPageCreator.java:157)
at com.gargoylesoftware.htmlunit.WebClient.loadWebResponseInto(WebClient.java:477)
at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:351)
at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:416)
at com.ibm.ws.jsf23.fat.tests.JSF23EvalScriptsTests.testEvalScriptsSimple(JSF23EvalScriptsTests.java:88)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:204)
Caused by: net.sourceforge.htmlunit.corejs.javascript.EvaluatorException: syntax error (http://localhost:8010/EvalScripts/jakarta.faces.resource/faces.js.xhtml?ln=jakarta.faces#2)
at com.gargoylesoftware.htmlunit.javascript.StrictErrorReporter.error(StrictErrorReporter.java:65)
at net.sourceforge.htmlunit.corejs.javascript.Parser.addError(Parser.java:187)
at net.sourceforge.htmlunit.corejs.javascript.Parser.addError(Parser.java:167)
at net.sourceforge.htmlunit.corejs.javascript.Parser.reportError(Parser.java:254)
at net.sourceforge.htmlunit.corejs.javascript.Parser.reportError(Parser.java:243)
at net.sourceforge.htmlunit.corejs.javascript.Parser.reportError(Parser.java:236)
at net.sourceforge.htmlunit.corejs.javascript.Parser.primaryExpr(Parser.java:2816)
at net.sourceforge.htmlunit.corejs.javascript.Parser.memberExpr(Parser.java:2388)
at net.sourceforge.htmlunit.corejs.javascript.Parser.unaryExpr(Parser.java:2292)
at net.sourceforge.htmlunit.corejs.javascript.Parser.mulExpr(Parser.java:2219)
at net.sourceforge.htmlunit.corejs.javascript.Parser.addExpr(Parser.java:2205)
at net.sourceforge.htmlunit.corejs.javascript.Parser.shiftExpr(Parser.java:2188)
at net.sourceforge.htmlunit.corejs.javascript.Parser.relExpr(Parser.java:2165)
at net.sourceforge.htmlunit.corejs.javascript.Parser.eqExpr(Parser.java:2139)
at net.sourceforge.htmlunit.corejs.javascript.Parser.bitAndExpr(Parser.java:2130)
at net.sourceforge.htmlunit.corejs.javascript.Parser.bitXorExpr(Parser.java:2121)
at net.sourceforge.htmlunit.corejs.javascript.Parser.bitOrExpr(Parser.java:2112)
at net.sourceforge.htmlunit.corejs.javascript.Parser.andExpr(Parser.java:2103)
at net.sourceforge.htmlunit.corejs.javascript.Parser.orExpr(Parser.java:2094)
at net.sourceforge.htmlunit.corejs.javascript.Parser.condExpr(Parser.java:2060)
at net.sourceforge.htmlunit.corejs.javascript.Parser.assignExpr(Parser.java:2033)
at net.sourceforge.htmlunit.corejs.javascript.Parser.expr(Parser.java:2014)
at net.sourceforge.htmlunit.corejs.javascript.Parser.parenExpr(Parser.java:2830)
at net.sourceforge.htmlunit.corejs.javascript.Parser.primaryExpr(Parser.java:2758)
at net.sourceforge.htmlunit.corejs.javascript.Parser.memberExpr(Parser.java:2388)
at net.sourceforge.htmlunit.corejs.javascript.Parser.unaryExpr(Parser.java:2292)
at net.sourceforge.htmlunit.corejs.javascript.Parser.mulExpr(Parser.java:2219)
at net.sourceforge.htmlunit.corejs.javascript.Parser.addExpr(Parser.java:2205)
at net.sourceforge.htmlunit.corejs.javascript.Parser.shiftExpr(Parser.java:2188)
at net.sourceforge.htmlunit.corejs.javascript.Parser.relExpr(Parser.java:2165)
at net.sourceforge.htmlunit.corejs.javascript.Parser.eqExpr(Parser.java:2139)
at net.sourceforge.htmlunit.corejs.javascript.Parser.bitAndExpr(Parser.java:2130)
at net.sourceforge.htmlunit.corejs.javascript.Parser.bitXorExpr(Parser.java:2121)
at net.sourceforge.htmlunit.corejs.javascript.Parser.bitOrExpr(Parser.java:2112)
at net.sourceforge.htmlunit.corejs.javascript.Parser.andExpr(Parser.java:2103)
at net.sourceforge.htmlunit.corejs.javascript.Parser.orExpr(Parser.java:2094)
at net.sourceforge.htmlunit.corejs.javascript.Parser.condExpr(Parser.java:2060)
at net.sourceforge.htmlunit.corejs.javascript.Parser.assignExpr(Parser.java:2033)
at net.sourceforge.htmlunit.corejs.javascript.Parser.expr(Parser.java:2014)
at net.sourceforge.htmlunit.corejs.javascript.Parser.parenExpr(Parser.java:2830)
at net.sourceforge.htmlunit.corejs.javascript.Parser.primaryExpr(Parser.java:2758)
at net.sourceforge.htmlunit.corejs.javascript.Parser.memberExpr(Parser.java:2388)
at net.sourceforge.htmlunit.corejs.javascript.Parser.unaryExpr(Parser.java:2292)
at net.sourceforge.htmlunit.corejs.javascript.Parser.mulExpr(Parser.java:2219)
at net.sourceforge.htmlunit.corejs.javascript.Parser.addExpr(Parser.java:2205)
at net.sourceforge.htmlunit.corejs.javascript.Parser.shiftExpr(Parser.java:2188)
at net.sourceforge.htmlunit.corejs.javascript.Parser.relExpr(Parser.java:2165)
at net.sourceforge.htmlunit.corejs.javascript.Parser.eqExpr(Parser.java:2139)
at net.sourceforge.htmlunit.corejs.javascript.Parser.bitAndExpr(Parser.java:2130)
at net.sourceforge.htmlunit.corejs.javascript.Parser.bitXorExpr(Parser.java:2121)
at net.sourceforge.htmlunit.corejs.javascript.Parser.bitOrExpr(Parser.java:2112)
at net.sourceforge.htmlunit.corejs.javascript.Parser.andExpr(Parser.java:2103)
at net.sourceforge.htmlunit.corejs.javascript.Parser.orExpr(Parser.java:2094)
at net.sourceforge.htmlunit.corejs.javascript.Parser.condExpr(Parser.java:2060)
at net.sourceforge.htmlunit.corejs.javascript.Parser.assignExpr(Parser.java:2033)
at net.sourceforge.htmlunit.corejs.javascript.Parser.expr(Parser.java:2014)
at net.sourceforge.htmlunit.corejs.javascript.Parser.statementHelper(Parser.java:1060)
at net.sourceforge.htmlunit.corejs.javascript.Parser.statement(Parser.java:926)
at net.sourceforge.htmlunit.corejs.javascript.Parser.parse(Parser.java:570)
at net.sourceforge.htmlunit.corejs.javascript.Parser.parse(Parser.java:491)
at net.sourceforge.htmlunit.corejs.javascript.Context.compileImpl(Context.java:2661)
at net.sourceforge.htmlunit.corejs.javascript.Context.compileString(Context.java:1624)
at com.gargoylesoftware.htmlunit.javascript.HtmlUnitContextFactory$TimeoutContext.compileString(HtmlUnitContextFactory.java:172)
at net.sourceforge.htmlunit.corejs.javascript.Context.compileString(Context.java:1616)
at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$2.doRun(JavaScriptEngine.java:700)
at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$HtmlUnitContextAction.run(JavaScriptEngine.java:868) 
```

**Comment by volosied** [comment]
URLS For the Faces 4.0 LWAS FAT:

http://localhost:9080/JSF20AJAXTag/DisabledFalse.jsf
http://localhost:9080/JSF20AJAXTag/DisabledTrue.jsf
http://localhost:9080/JSF20AJAXTag/EventDefault.jsf
http://localhost:9080/JSF20AJAXTag/EventSpecified.jsf
http://localhost:9080/JSF20AJAXTag/ExecuteAll.jsf
http://localhost:9080/JSF20AJAXTag/ExecuteDefault.jsf
http://localhost:9080/JSF20AJAXTag/ExecuteForm.jsf
http://localhost:9080/JSF20AJAXTag/ExecuteMultiple.jsf
http://localhost:9080/JSF20AJAXTag/ExecuteNone.jsf
http://localhost:9080/JSF20AJAXTag/ExecuteSingle.jsf
http://localhost:9080/JSF20AJAXTag/ExecuteThis.jsf
http://localhost:9080/JSF20AJAXTag/Listener.jsf
http://localhost:9080/JSF20AJAXTag/OnError.jsf
http://localhost:9080/JSF20AJAXTag/OnEvent.jsf
http://localhost:9080/JSF20AJAXTag/RenderAll.jsf
http://localhost:9080/JSF20AJAXTag/RenderDefault.jsf
http://localhost:9080/JSF20AJAXTag/RenderForm.jsf
http://localhost:9080/JSF20AJAXTag/RenderMultipleComponents.jsf
http://localhost:9080/JSF20AJAXTag/RenderNone.jsf
http://localhost:9080/JSF20AJAXTag/RenderSingleComponent.jsf
http://localhost:9080/JSF20AJAXTag/RenderThis.jsf
http://localhost:9080/JSF20AJAXTag/ImmediateFalse.jsf
http://localhost:9080/JSF20AJAXTag/ImmediateTrue.jsf
http://localhost:9080/JSF20AJAXTag/ImmediateDefault.jsf

http://localhost:9080/JSF20BeanValidation/BeanValidation.jsf

http://localhost:9080/JSF20Behaviors/behaviors.jsf

http://localhost:9080/JSF20JavaScriptAPI/ExecuteAll.jsf
http://localhost:9080/JSF20JavaScriptAPI/ExecuteDefault.jsf
http://localhost:9080/JSF20JavaScriptAPI/ExecuteForm.jsf
http://localhost:9080/JSF20JavaScriptAPI/ExecuteMultiple.jsf
http://localhost:9080/JSF20JavaScriptAPI/ExecuteNone.jsf
http://localhost:9080/JSF20JavaScriptAPI/ExecuteSingle.jsf
http://localhost:9080/JSF20JavaScriptAPI/ExecuteThis.jsf
http://localhost:9080/JSF20JavaScriptAPI/OnError.jsf
http://localhost:9080/JSF20JavaScriptAPI/OnEvent.jsf
http://localhost:9080/JSF20JavaScriptAPI/RenderAll.jsf
http://localhost:9080/JSF20JavaScriptAPI/RenderDefault.jsf
http://localhost:9080/JSF20JavaScriptAPI/RenderForm.jsf
http://localhost:9080/JSF20JavaScriptAPI/RenderMultipleComponents.jsf
http://localhost:9080/JSF20JavaScriptAPI/RenderNone.jsf
http://localhost:9080/JSF20JavaScriptAPI/RenderSingleComponent.jsf
http://localhost:9080/JSF20JavaScriptAPI/RenderThis.jsf
http://localhost:9080/JSF20JavaScriptAPI/OnEventCall.jsf
http://localhost:9080/JSF20JavaScriptAPI/OnErrorCall.jsf

http://localhost:9080/JSF20Navigation/conditionalMain.jsf

**Comment by isaacrivriv** [comment]
@volosied and I manually tested these skipped tests today Wednesday March 15th. We used the zipped image from PR #24618 from the latest ran [build](https://wasrtc.hursley.ibm.com:9443/jazz/resource/itemOid/com.ibm.team.build.BuildResult/_stgbIMKbEe2wjvvdiFn2gA) which contained all the latest changes including CDI/Faces fix for #24631. These are the results

- com.ibm.ws.jsf_fat_lWAS_faces4.0: Ran all tests without encountering issues, everything is working as expected.
- com.ibm.ws.jsf.2.2_fat:  All Passed - Vlad
- com.ibm.ws.jsf.2.3_fat: All Passed - Vlad
- io.openliberty.org.apache.myfaces.4.0_fat: Did not manually test since the remaining tests are already covered by the TCK which no errors are reported as of today.

**Comment by volosied** [comment]
@isaacrivriv  and I manually tested these skipped tests today Friday March 17th. We used the zipped image from PR https://github.com/OpenLiberty/open-liberty/pull/24715 from the latest ran [build](https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_sA_EEMSjEe2wjvvdiFn2gA) which contains the recent code changes. These are the results

- com.ibm.ws.jsf_fat_lWAS_faces4.0: Passed - Vlad
- com.ibm.ws.jsf.2.2_fat: All passed - Isaac
- com.ibm.ws.jsf.2.3_fat: All passed - Isaac
- io.openliberty.org.apache.myfaces.4.0_fat: Did not manually test since the remaining tests are already covered by the TCK which no errors are reported as of today.

**Comment by isaacrivriv** [comment]
Manually tested these skipped tests today Monday March 20th. We used the zipped image from the latest [release build](https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_4-IrsMZ_Ee21SqRkHwL18g) available. These are the results

- com.ibm.ws.jsf_fat_lWAS_faces4.0: All passed
- com.ibm.ws.jsf.2.2_fat: All passed
- com.ibm.ws.jsf.2.3_fat: All passed
- io.openliberty.org.apache.myfaces.4.0_fat: Did not manually test since the remaining tests are already covered by the TCK which no errors are reported as of today.

**Comment by volosied** [comment]
Manually tested these skipped tests today Thursday April 27th. We used the zipped image from the the latest release build - `Build Liberty Official Release Build - Static cl230520230427-0300 ` These are the results

    com.ibm.ws.jsf_fat_lWAS_faces4.0: All passed
    com.ibm.ws.jsf.2.2_fat: All passed
    com.ibm.ws.jsf.2.3_fat: All passed
    io.openliberty.org.apache.myfaces.4.0_fat: Did not manually test since the remaining tests are already covered by the TCK which no errors are reported as of today.

**Comment by isaacrivriv** [comment]
Manually tested these skipped tests today Friday May 5th. We used the zipped image from the the latest release build - `Build Liberty Official Release Build - Static cl230520230504-1900 ` These are the results

    com.ibm.ws.jsf_fat_lWAS_faces4.0: All passed
    com.ibm.ws.jsf.2.2_fat: All passed
    com.ibm.ws.jsf.2.3_fat: All passed
    io.openliberty.org.apache.myfaces.4.0_fat: Did not manually test since the remaining tests are already covered by the TCK which no errors are reported as of today.

**Comment by isaacrivriv** [comment]
Manually tested these skipped tests today Friday May 26th. We used the latest from integration up to commit `35002cb20fc4bd45aa84063fcdfe2d464a563ce3` to test due to builds being unavailable at the moment of testing. These are the results
```
com.ibm.ws.jsf_fat_lWAS_faces4.0: All passed
com.ibm.ws.jsf.2.2_fat: All passed
com.ibm.ws.jsf.2.3_fat: All passed
io.openliberty.org.apache.myfaces.4.0_fat: Did not manually test since the remaining tests are already covered by the TCK which no errors are reported as of today.
```

**Comment by alenanicole** [comment]
JSF20PartialView tests skipped for JakartaEE10 due to HTMLUnit errors.

**Comment by isaacrivriv** [comment]
Manually tested these skipped tests today Friday June 9th. We used the zipped image from the the latest release build - Build Liberty Official Release Build - Static cl230620230608-2336. These are the results
```
com.ibm.ws.jsf_fat_lWAS_faces4.0: All passed
com.ibm.ws.jsf.2.2_fat: All passed
com.ibm.ws.jsf.2.3_fat: All passed
io.openliberty.org.apache.myfaces.4.0_fat: Did not manually test since the remaining tests are already covered by the TCK which no errors are reported as of today.
```

**Comment by alenanicole** [comment]
JSF20AJAX tests skipped for JakartaEE10 due to HTMLUnit/JS errors.

**Comment by volosied** [comment]
Manually tested these skipped tests today - Friday July 7th.  I used the latest integration branch (as I've been working to automate these tests via Selenium).
```
com.ibm.ws.jsf_fat_lWAS_faces4.0: All passed
com.ibm.ws.jsf.2.2_fat: All passed
com.ibm.ws.jsf.2.3_fat: All passed
io.openliberty.org.apache.myfaces.4.0_fat: Did not manually test since the remaining tests are already covered by the TCK which no errors are reported as of today.
```

**Comment by alenanicole** [comment]
**Skipped for JakartaEE10 in the jsf_fat_lWAS bucket due to HTMLUnit/JS errors.**
JSF20FacesConfig1_2.java
JSF20Taglibs.java
- testTopCommandButton
- testBottomCommandButton
- testTopLinks
- testBottomLinks

**Comment by alenanicole** [comment]
**Skipped for JakartaEE10 in the jsf_fat_lWAS bucket due to HTMLUnit/JS errors.**
PI12666Test.java
PI18604Test.java
PI27290Test.java
PI47885Test.java
PM17533Test.java
PM52177Test.java
PM52695Test.java
PM75665Test.java
PM92784Test.java
PM94424Test.java
PM95907Test.java
PM96613Test.java
testPI26201_request (AparTests.java)
testPI26201 (AparTests.java)
testPK91480_1 (AparTests2.java)

**Comment by volosied** [comment]
Tested with `wlp-cl230820230804-0402` and the JSF 2.2, 2.3, and 2.0 FATs all pass. I tested via my selenium PRs locally.

The recently enabled test by Alena have not been tested yet, but will be converted to selenium soon. 

I also tested Tom Watson's dynamicFacesInitializerService PR and these also passed. 

4.0 tests should be verified via TCK.

**Comment by volosied** [comment]
Faces 4.0 PR: #27608 (Some tests, not all)

**Comment by tssmith04** [comment]
All tests listed pass, with the exception of `testNoMultiple_WithAjax_MultipleFiles` as Selenium does not support uploading multiple files when the multiple files attribute is not set. This test was more fitted for HTMLUnit. In terms of client behavior, a User would not conventionally be able to upload multiple files when the multiples files attribute is not set either, so Selenium more closely follows client behavior.

As for the Ajax tests:
- testAjaxRender
- testAjaxExecuteThis
- testAjaxRenderThis

They have been converted to Selenium and pass to comply with the [TCK](https://github.com/jakartaee/faces/blob/master/tck/faces40/ajax/src/test/java/ee/jakarta/tck/faces/test/servlet50/ajax_selenium/Spec1567IT.java).
