### ISSUE TITLE
Test Failure (Tests: 20180225-0336 (for cl180120180224-0700, child-f5)): org.eclipse.microprofile.metrics.tck.MeterTest.testRates

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#2443]
java.lang.AssertionError: expected:<1839.904> but was:<1999.8>
at org.junit.Assert.fail(Assert.java:93)
at org.junit.Assert.failNotEquals(Assert.java:647)
at org.junit.Assert.assertEquals(Assert.java:443)
at org.junit.Assert.assertEquals(Assert.java:512)
at org.eclipse.microprofile.metrics.tck.MeterTest.testRates(MeterTest.java:107)

**Comment by fmhwong** [comment]
RTC 251925
