### ISSUE TITLE
CTS: EE8: JAX-RS bucket: An entity output stream set with ClientRequestContext#setEntityStream() not being used (1 test)

### ISSUE THREAD

**Issue by WhiteCat22** [OpenLiberty/open-liberty#2444]
The following test is failing with the error "ENXIXY_SXREAM_WORKS does NOT contain ENTITY_STREAM_WORKS":
- jaxrs/ee/rs/client/clientrequestcontext/JAXRSClient_getEntityStreamTest_from_standalone

The test creates a ClientRequestFilter that calls ClientRequestContext#setEntityStream() with a custom output stream that replaces all instances of 'X' with 'T'. The test then creates a POST request with the entity "ENXIXY_SXREAM_WORKS". With the custom entity output stream set, the entity should be converted to "ENTITY_STREAM_WORKS", but it does not look like this is happening (see the following packet capture).

POST request packet capture:
POST /jaxrs_ee_rs_client_clientrequestcontext_web/resource/post HTTP/1.1
Content-Type: */*
Accept: */*
User-Agent: Apache-CXF/3.2.1
Cache-Control: no-cache
Pragma: no-cache
Host: localhost:9081
Connection: keep-alive
Content-Length: 19

ENXIXY_SXREAM_WORKS

Test log snippet:
02-08-2018 12:44:27:  TRACE: ABOUT TO INVOKE EETEST RUN METHOD!
02-08-2018 12:44:27:  TRACE: [JAXRSCommonClient] invoke
02-08-2018 12:44:27:  TRACE: [JAXRSCommonClient] setTestProperties
02-08-2018 12:44:27:  TRACE: [JAXRSCommonClient] EXECUTING
02-08-2018 12:44:27:  [Request] Dispatching request: 'POST http://localhost:9081/jaxrs_ee_rs_client_clientrequestcontext_web/resource/post' to target server at 'localhost:9081'
02-08-2018 12:44:27:  ###############################
02-08-2018 12:44:27:  [Request] Adding entity: java.io.ByteArrayInputStream@8f970baa
02-08-2018 12:44:27:  TRACE: [WIRE] - >> POST http://localhost:9081/jaxrs_ee_rs_client_clientrequestcontext_web/resource/post
02-08-2018 12:44:27:  TRACE: [WIRE] - >> Accept:*/*, Content-Type:*/*
02-08-2018 12:44:27:  TRACE: [WIRE] - >> java.io.ByteArrayInputStream@8f970baa
02-08-2018 12:44:29:  TRACE: [WIRE] - << 200 OK
02-08-2018 12:44:29:  TRACE: [WIRE] - << Content-Language: en-US
02-08-2018 12:44:29:  TRACE: [WIRE] - << Content-Length: 19
02-08-2018 12:44:29:  TRACE: [WIRE] - << content-type: application/octet-stream
02-08-2018 12:44:29:  TRACE: [WIRE] - << Date: Thu, 08 Feb 2018 17:44:29 GMT
02-08-2018 12:44:29:  TRACE: [WIRE] - << X-Powered-By: Servlet/4.0
02-08-2018 12:44:29:  TRACE: [WIRE] - << ENXIXY_SXREAM_WORKS
02-08-2018 12:44:29:  TRACE: [WebValidatorBase] Expected Status Code '200' found in response line!
02-08-2018 12:44:29:  ERROR: ENXIXY_SXREAM_WORKS does NOT contain ENTITY_STREAM_WORKS
02-08-2018 12:44:29:  ERROR: Test case throws exception: ENXIXY_SXREAM_WORKS does NOT contain ENTITY_STREAM_WORKS
02-08-2018 12:44:29:  ERROR: Exception at:
02-08-2018 12:44:29:  ERROR: com.sun.ts.lib.harness.EETest$Fault: ENXIXY_SXREAM_WORKS does NOT contain ENTITY_STREAM_WORKS
        at com.sun.ts.tests.jaxrs.common.JAXRSCommonClient.fault(JAXRSCommonClient.java:730)
        at com.sun.ts.tests.jaxrs.common.JAXRSCommonClient.assertTrue(JAXRSCommonClient.java:625)
        at com.sun.ts.tests.jaxrs.common.JAXRSCommonClient.assertFault(JAXRSCommonClient.java:608)
        at com.sun.ts.tests.jaxrs.ee.rs.client.clientrequestcontext.JAXRSClient.assertContains(JAXRSClient.java:156)
        at com.sun.ts.tests.jaxrs.ee.rs.client.clientrequestcontext.JAXRSClient.getEntityStreamTest(JAXRSClient.java:68)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
        at java.lang.reflect.Method.invoke(Method.java:508)
        at com.sun.ts.lib.harness.EETest.run(EETest.java:550)
        at com.sun.ts.lib.harness.ServiceEETest.run(ServiceEETest.java:113)
        at com.sun.ts.tests.common.vehicle.EmptyVehicleRunner.run(EmptyVehicleRunner.java:30)
        at com.sun.ts.lib.harness.ServiceEETest.run(ServiceEETest.java:102)
        at com.sun.ts.lib.harness.EETest.getPropsReady(EETest.java:446)
        at com.sun.ts.lib.harness.ServiceEETest.run(ServiceEETest.java:210)
        at com.sun.ts.lib.harness.EETest.run(EETest.java:257)
        at com.sun.ts.tests.common.vehicle.VehicleClient.main(VehicleClient.java:27)

**Comment by WhiteCat22** [comment]
https://github.com/OpenLiberty/open-liberty/pull/2605

**Comment by WhiteCat22** [comment]
Change has made it to master.
