### ISSUE TITLE
InstantOn OL23.0.0.3-beta: checkpoint fails on RHEL9 Intel VM

### ISSUE THREAD

**Issue by tam512** [OpenLiberty/open-liberty#24522]
On RHEL9 Intel VM, create checkpoint using Open Liberty image ` stg.icr.io/cp/olc/open-liberty:beta-instanton-java17-openj9-ubi@sha256:0ab4affa75676d46fa1fe3e4e60182a7f73ab87a55631beb1fa9cae5fb635ce3`
- Create checkpoint with command:
```
podman build \
   -t mwappee9-ckpt:rhel9-intel \
   --cap-add=CHECKPOINT_RESTORE \
   --cap-add=SYS_PTRACE\
   --cap-add=SETPCAP \
   --security-opt seccomp=unconfined \
   -f Containerfile .
```
and it failed with the following errors:
```
STEP 10/10: RUN checkpoint.sh applications 
Performing checkpoint --at=applications

Launching defaultServer (Open Liberty 23.0.0.3-beta/wlp-1.0.74.cl230220230222-1257) on Eclipse OpenJ9 VM, version 17.0.6-ea+10 (en_US)
CWWKE0953W: This version of Open Liberty is an unsupported early release version.
[AUDIT   ] CWWKE0001I: The server defaultServer has been launched.
[AUDIT   ] CWWKG0093A: Processing configuration drop-ins resource: /opt/ol/wlp/usr/servers/defaultServer/configDropins/defaults/checkpoint.xml
[AUDIT   ] CWWKG0093A: Processing configuration drop-ins resource: /opt/ol/wlp/usr/servers/defaultServer/configDropins/defaults/keystore.xml
[AUDIT   ] CWWKG0093A: Processing configuration drop-ins resource: /opt/ol/wlp/usr/servers/defaultServer/configDropins/defaults/open-default-port.xml
[AUDIT   ] CWWKZ0058I: Monitoring dropins for applications.
[AUDIT   ] CWWKT0016I: Web application available (default_host): http://3ea059c3300b:9080/health/
[AUDIT   ] CWWKT0016I: Web application available (default_host): http://3ea059c3300b:9080/openapi/
[AUDIT   ] CWWKT0016I: Web application available (default_host): http://3ea059c3300b:9080/jwt/
[AUDIT   ] CWWKT0016I: Web application available (default_host): http://3ea059c3300b:9080/openapi/ui/
[AUDIT   ] CWWKT0016I: Web application available (default_host): http://3ea059c3300b:9080/metrics/
[AUDIT   ] CWWKT0016I: Web application available (default_host): http://3ea059c3300b:9080/ibm/api/
[AUDIT   ] CWWKT0016I: Web application available (default_host): http://3ea059c3300b:9080/microwebapp/
[AUDIT   ] CWWKZ0001I: Application microwebapp started in 0.748 seconds.
[AUDIT   ] CWWKC0451I: A server checkpoint was requested. When the checkpoint completes, the server stops.
[ERROR   ] CWWKC0453E: The server checkpoint request failed with the following message: Could not dump the JVM processes, err=-52
[AUDIT   ] CWWKE0084I: The server defaultServer is stopping because thread Checkpoint failed, exiting... (0000003b) called the method java.lang.System.exit: 
	at java.base/java.lang.System.exit(System.java:502)
	at io.openliberty.checkpoint.internal.CheckpointImpl.lambda$checkpointOrExitOnFailure$1(CheckpointImpl.java:265)
	at java.base/java.lang.Thread.run(Thread.java:857)

[AUDIT   ] CWWKE1100I: Waiting for up to 30 seconds for the server to quiesce.
[AUDIT   ] CWWKF0012I: The server installed the following features: [appSecurity-4.0, cdi-3.0, checkpoint-1.0, concurrent-2.0, distributedMap-1.0, expressionLanguage-4.0, jndi-1.0, json-1.0, jsonb-2.0, jsonp-2.0, jwt-1.0, microProfile-5.0, monitor-1.0, mpConfig-3.0, mpFaultTolerance-4.0, mpHealth-4.0, mpJwt-2.0, mpMetrics-4.0, mpOpenAPI-3.0, mpOpenTracing-3.0, mpRestClient-3.0, pages-3.0, restfulWS-3.0, restfulWSClient-3.0, servlet-5.0, ssl-1.0, transportSecurity-1.0].
[AUDIT   ] CWWKF0011I: The defaultServer server is ready to run a smarter planet. The defaultServer server started in 5.011 seconds.
[AUDIT   ] CWWKT0017I: Web application removed (default_host): http://3ea059c3300b:9080/jwt/
[AUDIT   ] CWWKT0017I: Web application removed (default_host): http://3ea059c3300b:9080/openapi/ui/
[AUDIT   ] CWWKT0017I: Web application removed (default_host): http://3ea059c3300b:9080/health/
[AUDIT   ] CWWKT0017I: Web application removed (default_host): http://3ea059c3300b:9080/metrics/
[AUDIT   ] CWWKT0017I: Web application removed (default_host): http://3ea059c3300b:9080/microwebapp/
[AUDIT   ] CWWKT0017I: Web application removed (default_host): http://3ea059c3300b:9080/openapi/
[AUDIT   ] CWWKT0017I: Web application removed (default_host): http://3ea059c3300b:9080/ibm/api/
[AUDIT   ] CWWKZ0009I: The application microwebapp has stopped successfully.
[AUDIT   ] CWWKE0036I: The server defaultServer stopped after 6.356 seconds.
Warn  (criu/kerndat.c:1103): $XDG_RUNTIME_DIR not set. Cannot find location for kerndat file
Error (criu/libnetlink.c:84): Can't send request message: Permission denied
Error (criu/libnetlink.c:84): Can't send request message: Permission denied
Error (criu/libnetlink.c:84): Can't send request message: Permission denied
Error (criu/libnetlink.c:84): Can't send request message: Permission denied
Error (criu/libnetlink.c:84): Can't send request message: Permission denied
Error (criu/libnetlink.c:84): Can't send request message: Permission denied
Warn  (criu/kerndat.c:1103): $XDG_RUNTIME_DIR not set. Cannot find location for kerndat file
Warn  (compel/src/lib/infect.c:133): Unable to interrupt task: 176 (Operation not permitted)
Error (criu/libnetlink.c:84): Can't send request message: Permission denied
Error (criu/libnetlink.c:84): Can't send request message: Permission denied
Error (criu/libnetlink.c:84): Can't send request message: Permission denied
Error (criu/libnetlink.c:84): Can't send request message: Permission denied
Error (criu/libnetlink.c:84): Can't send request message: Permission denied
Error (criu/libnetlink.c:84): Can't send request message: Permission denied
Error (criu/libnetlink.c:84): Can't send request message: Permission denied
Error (criu/libnetlink.c:84): Can't send request message: Permission denied
Error (criu/libnetlink.c:84): Can't send request message: Permission denied
Error (criu/libnetlink.c:84): Can't send request message: Permission denied
Error (criu/libnetlink.c:84): Can't send request message: Permission denied
Error (criu/sockets.c:436): sockets: Sockets (family 1 proto 0) are not collected
Error (criu/sk-unix.c:351): unix: Unix socket 4415037 not found
Error (criu/cr-dump.c:1675): Dump files (pid: 121) failed with -1
Error (criu/cr-dump.c:2099): Dumping FAILED.
Checkpoint failed. The following is the checkpoint.log from CRIU ...
Warn  (criu/kerndat.c:1103): $XDG_RUNTIME_DIR not set. Cannot find location for kerndat file
Error (criu/libnetlink.c:84): Can't send request message: Permission denied
Error (criu/libnetlink.c:84): Can't send request message: Permission denied
Error (criu/libnetlink.c:84): Can't send request message: Permission denied
Error (criu/libnetlink.c:84): Can't send request message: Permission denied
Error (criu/libnetlink.c:84): Can't send request message: Permission denied
Error (criu/libnetlink.c:84): Can't send request message: Permission denied
Warn  (criu/kerndat.c:1103): $XDG_RUNTIME_DIR not set. Cannot find location for kerndat file
Warn  (compel/src/lib/infect.c:133): Unable to interrupt task: 176 (Operation not permitted)
Error (criu/libnetlink.c:84): Can't send request message: Permission denied
Error (criu/libnetlink.c:84): Can't send request message: Permission denied
Error (criu/libnetlink.c:84): Can't send request message: Permission denied
Error (criu/libnetlink.c:84): Can't send request message: Permission denied
Error (criu/libnetlink.c:84): Can't send request message: Permission denied
Error (criu/libnetlink.c:84): Can't send request message: Permission denied
Error (criu/libnetlink.c:84): Can't send request message: Permission denied
Error (criu/libnetlink.c:84): Can't send request message: Permission denied
Error (criu/libnetlink.c:84): Can't send request message: Permission denied
Error (criu/libnetlink.c:84): Can't send request message: Permission denied
Error (criu/libnetlink.c:84): Can't send request message: Permission denied
Error (criu/sockets.c:436): sockets: Sockets (family 1 proto 0) are not collected
Error (criu/sk-unix.c:351): unix: Unix socket 4415037 not found
Error (criu/cr-dump.c:1675): Dump files (pid: 121) failed with -1
Error (criu/cr-dump.c:2099): Dumping FAILED.
Error: error building at STEP "RUN checkpoint.sh applications": error while running runtime: exit status 74
```

**Comment by ymanton** [comment]
The checkpoint fails because on this particular machine SELinux is enabled and also configured to not allow container access to the Netlink subsystem.

The details are in the machine's log:

```
$ journalctl --since=today
...
Mar 21 21:03:42 localhost setroubleshoot[213628]: SELinux is preventing /usr/sbin/criu from nlmsg_read access on the netlink_tcpdiag_socket labeled container_t. For complete SELinux messages run: sealert -l 1401683f-318e-40d8-9493-e9ac7410be72
Mar 21 21:03:42 localhost setroubleshoot[213628]: SELinux is preventing /usr/sbin/criu from nlmsg_read access on the netlink_tcpdiag_socket labeled container_t.

                                                             *****  Plugin catchall_boolean (89.3 confidence) suggests   ******************

                                                             If you want to allow virt to sandbox use netlink
                                                             Then you must tell SELinux about this by enabling the 'virt_sandbox_use_netlink' boolean.

                                                             Do
                                                             setsebool -P virt_sandbox_use_netlink 1

                                                             *****  Plugin catchall (11.6 confidence) suggests   **************************

                                                             If you believe that criu should be allowed nlmsg_read access on netlink_tcpdiag_socket labeled container_t by default.
                                                             Then you should report this as a bug.
                                                             You can generate a local policy module to allow this access.
                                                             Do
                                                             allow this access for now by executing:
                                                             # ausearch -c 'criu' --raw | audit2allow -M my-criu
                                                             # semodule -X 300 -i my-criu.pp
...
```

This machine has the following SELinux variable set to off, preventing containers from accessing Netlink:

```
$ getsebool virt_sandbox_use_netlink
virt_sandbox_use_netlink --> off
```

If I turn it on via `setsebool virt_sandbox_use_netlink 1` I can checkpoint and restore without any issue.

```
$ podman build    -t getting-started-instanton    --cap-add=CHECKPOINT_RESTORE    --cap-add=SYS_PTRACE   --cap-add=SETPCAP    --security-opt seccomp=unconfined .
STEP 1/8: FROM icr.io/appcafe/open-liberty:beta-instanton-java17-openj9-ubi
STEP 2/8: ARG VERSION=1.0
--> Using cache 2bb89f365baeffe925403b0f66828e1187281f606f083aaa1ed91d362c920286
--> 2bb89f365ba
STEP 3/8: ARG REVISION=SNAPSHOT
--> Using cache 83cd704dc00b6ccf654fcf66b9bed9907114932b9ed782e8c8df02bf89d8367d
--> 83cd704dc00
STEP 4/8: LABEL   org.opencontainers.image.authors="Your Name"   org.opencontainers.image.vendor="IBM"   org.opencontainers.image.url="local"   org.opencontainers.image.source="https://github.com/OpenLiberty/guide-getting-started"   org.opencontainers.image.version="$VERSION"   org.opencontainers.image.revision="$REVISION"   vendor="Open Liberty"   name="system"   version="$VERSION-$REVISION"   summary="The system microservice from the Getting Started guide"   description="This image contains the system microservice running with the Open Liberty runtime."
--> Using cache b2b3c92864f54f8ea444a9b506794f20ad2f651ef18cf9c16be2ed0e4bc07b4b
--> b2b3c92864f
STEP 5/8: COPY --chown=1001:0 src/main/liberty/config/ /config/
--> Using cache 944c4f3603acbd78124b9d377513f3a9d6645ea0acdbf5148a804c6fbde8f090
--> 944c4f3603a
STEP 6/8: COPY --chown=1001:0 target/*.war /config/apps/
--> Using cache dd1bddb39bef2c296dfd5b443527630ea2081f7d49cdfc8560c36be6537da65a
--> dd1bddb39be
STEP 7/8: RUN configure.sh
--> Using cache f8aca1eb384349e98d2ef2ae8fa3678fe9e8175d3e3969c64c69c84537718631
--> f8aca1eb384
STEP 8/8: RUN checkpoint.sh applications
Performing checkpoint --at=applications

Launching defaultServer (Open Liberty 23.0.0.2-beta/wlp-1.0.73.cl230120230123-2118) on Eclipse OpenJ9 VM, version 17.0.6-ea+6 (en_US)
CWWKE0953W: This version of Open Liberty is an unsupported early release version.
[AUDIT   ] CWWKE0001I: The server defaultServer has been launched.
[AUDIT   ] CWWKG0093A: Processing configuration drop-ins resource: /opt/ol/wlp/usr/servers/defaultServer/configDropins/defaults/checkpoint.xml
[AUDIT   ] CWWKG0093A: Processing configuration drop-ins resource: /opt/ol/wlp/usr/servers/defaultServer/configDropins/defaults/keystore.xml
[AUDIT   ] CWWKG0093A: Processing configuration drop-ins resource: /opt/ol/wlp/usr/servers/defaultServer/configDropins/defaults/open-default-port.xml
[AUDIT   ] CWWKZ0058I: Monitoring dropins for applications.
[AUDIT   ] CWWKT0016I: Web application available (default_host): http://7b96a36b9586:9080/ibm/api/
[AUDIT   ] CWWKT0016I: Web application available (default_host): http://7b96a36b9586:9080/health/
[AUDIT   ] CWWKT0016I: Web application available (default_host): http://7b96a36b9586:9080/metrics/
[AUDIT   ] CWWKT0016I: Web application available (default_host): http://7b96a36b9586:9080/dev/
[AUDIT   ] CWWKZ0001I: Application guide-getting-started started in 1.647 seconds.
[AUDIT   ] CWWKC0451I: A server checkpoint was requested. When the checkpoint completes, the server stops.
/opt/ol/wlp/bin/server: line 948:   118 Killed                  "${JAVA_CMD}" "$@" >> "${CHECKPOINT_CONSOLE_LOG}" 2>&1 < /dev/null
COMMIT getting-started-instanton
--> 3b8d4cc247a
Successfully tagged localhost/getting-started-instanton:latest
3b8d4cc247ae96e1d2e86a9444c1f17583ccbaa0b216931c7d16b4193e4d2824
```
```
$ podman run --cap-add=CHECKPOINT_RESTORE --cap-add=SETPCAP --security-opt seccomp=unconfined getting-started-instanton:latest

[AUDIT   ] CWWKZ0001I: Application guide-getting-started started in 0.144 seconds.
[AUDIT   ] CWWKC0452I: The Liberty server process resumed operation from a checkpoint in 0.190 seconds.
[AUDIT   ] CWWKF0012I: The server installed the following features: [cdi-3.0, checkpoint-1.0, concurrent-2.0, distributedMap-1.0, jndi-1.0, json-1.0, jsonb-2.0, jsonp-2.0, monitor-1.0, mpConfig-3.0, mpHealth-4.0, mpMetrics-4.0, restfulWS-3.0, restfulWSClient-3.0, servlet-5.0, ssl-1.0, transportSecurity-1.0].
[AUDIT   ] CWWKF0011I: The defaultServer server is ready to run a smarter planet. The defaultServer server started in 0.208 seconds.
^C[AUDIT   ] CWWKE0085I: The server defaultServer is stopping because the JVM is exiting.
[AUDIT   ] CWWKE1100I: Waiting for up to 30 seconds for the server to quiesce.
[AUDIT   ] CWWKT0017I: Web application removed (default_host): https://7b96a36b9586:9443/dev/
[AUDIT   ] CWWKT0017I: Web application removed (default_host): https://7b96a36b9586:9443/health/
[AUDIT   ] CWWKT0017I: Web application removed (default_host): https://7b96a36b9586:9443/metrics/
[AUDIT   ] CWWKT0017I: Web application removed (default_host): https://7b96a36b9586:9443/ibm/api/
[AUDIT   ] CWWKZ0009I: The application guide-getting-started has stopped successfully.
[AUDIT   ] CWWKE0036I: The server defaultServer stopped after 16.991 seconds.
```

**Comment by ymanton** [comment]
The reason it works when you take the checkpoint with `podman run --privileged ...` is because Podman will also disable various SELinux filters like the one above when you use `--privileged`, as per the docs:

https://docs.podman.io/en/latest/markdown/podman-run.1.html#privileged

> A privileged container turns off the security features that isolate the container from the host. Dropped Capabilities, limited devices, read-only mount points, Apparmor/SELinux separation, and Seccomp filters are all disabled.

**Comment by tam512** [comment]
From the checkpoint failure error above, how do users know that the machine setting do not allow container to access the Netlink subsystem?  I think we should document this.

**Comment by vijaysun-omr** [comment]
Was this VM/machine configured differently to the others ? I guess I am wondering if this was just a "default" configuration on RHEL 9 ? If so, why didn't SVT hit the problem earlier ?

**Comment by tam512** [comment]
SVT didn't see the problem earlier on this VM because this is the first time we do checkpoint using `RUN checkpoint.sh applications` in Dockerfile.  The previous tests were done using 3 steps of build, checkpoint with `podman run --privileged ...` , and commit.

**Comment by tjwatson** [comment]
Can we get some details on how the VM was provisioned?  I would like to understand why my VM instances do not see this issue by default.

**Comment by tam512** [comment]
I do not know how this VM was provisioned.  We needed an Intel VM so I request one by open a ticket https://oneticket.devit.ibm.com/ and we got this one.

**Comment by tam512** [comment]
Verified the fix https://github.com/OpenLiberty/open-liberty/pull/24913 for better error message as following:

> CWWKE0963E: The server checkpoint request failed because netlink system calls were unsuccessful. If SELinux is enabled in enforcing mode, netlink system calls might be blocked by the SELinux "virt_sandbox_use_netlink" policy setting. Either disable SELinux or enable the netlink system calls with the "setsebool virt_sandbox_use_netlink 1" command.


Full stack trace
```
Performing checkpoint --at=applications

Launching defaultServer (Open Liberty 23.0.0.5-beta/wlp-1.0.76.cl230420230418-0035) on Eclipse OpenJ9 VM, version 17.0.7+7 (en_US)
CWWKE0953W: This version of Open Liberty is an unsupported early release version.
[AUDIT   ] CWWKE0001I: The server defaultServer has been launched.
[AUDIT   ] CWWKG0093A: Processing configuration drop-ins resource: /opt/ol/wlp/usr/servers/defaultServer/configDropins/defaults/checkpoint.xml
[AUDIT   ] CWWKG0093A: Processing configuration drop-ins resource: /opt/ol/wlp/usr/servers/defaultServer/configDropins/defaults/keystore.xml
[AUDIT   ] CWWKG0093A: Processing configuration drop-ins resource: /opt/ol/wlp/usr/servers/defaultServer/configDropins/defaults/open-default-port.xml
[AUDIT   ] CWWKZ0058I: Monitoring dropins for applications.
[AUDIT   ] CWWKZ0001I: Application microwebapp started in 0.705 seconds.
[AUDIT   ] CWWKC0451I: A server checkpoint was requested. When the checkpoint completes, the server stops.
[ERROR   ] CWWKC0453E: The server checkpoint request failed with the following message: Could not dump the JVM processes, err=-52
[AUDIT   ] CWWKF0012I: The server installed the following features: [appSecurity-4.0, cdi-3.0, checkpoint-1.0, concurrent-2.0, distributedMap-1.0, expressionLanguage-4.0, jndi-1.0, json-1.0, jsonb-2.0, jsonp-2.0, jwt-1.0, microProfile-5.0, monitor-1.0, mpConfig-3.0, mpFaultTolerance-4.0, mpHealth-4.0, mpJwt-2.0, mpMetrics-4.0, mpOpenAPI-3.0, mpOpenTracing-3.0, mpRestClient-3.0, pages-3.0, restfulWS-3.0, restfulWSClient-3.0, servlet-5.0, ssl-1.0, transportSecurity-1.0].
[AUDIT   ] CWWKF0011I: The defaultServer server is ready to run a smarter planet. The defaultServer server started in 5.615 seconds.
[AUDIT   ] CWWKE0084I: The server defaultServer is stopping because thread Checkpoint failed, exiting... (00000043) called the method java.lang.System.exit: 
	at java.base/java.lang.System.exit(System.java:502)
	at io.openliberty.checkpoint.internal.CheckpointImpl.lambda$checkpointOrExitOnFailure$1(CheckpointImpl.java:275)
	at java.base/java.lang.Thread.run(Thread.java:857)

[AUDIT   ] CWWKE1100I: Waiting for up to 30 seconds for the server to quiesce.
[AUDIT   ] CWWKZ0009I: The application microwebapp has stopped successfully.
[AUDIT   ] CWWKE0036I: The server defaultServer stopped after 7.08 seconds.
CWWKE0962E: The server checkpoint request failed. The following output is from the CRIU /logs/checkpoint/checkpoint.log file that contains details on why the checkpoint failed.
Warn  (criu/kerndat.c:1103): $XDG_RUNTIME_DIR not set. Cannot find location for kerndat file
Error (criu/libnetlink.c:84): Can't send request message: Permission denied
Error (criu/libnetlink.c:84): Can't send request message: Permission denied
Error (criu/libnetlink.c:84): Can't send request message: Permission denied
Error (criu/libnetlink.c:84): Can't send request message: Permission denied
Error (criu/libnetlink.c:84): Can't send request message: Permission denied
Error (criu/libnetlink.c:84): Can't send request message: Permission denied
Warn  (criu/kerndat.c:1103): $XDG_RUNTIME_DIR not set. Cannot find location for kerndat file
Warn  (compel/src/lib/infect.c:133): Unable to interrupt task: 184 (Operation not permitted)
Error (criu/libnetlink.c:84): Can't send request message: Permission denied
Error (criu/libnetlink.c:84): Can't send request message: Permission denied
Error (criu/libnetlink.c:84): Can't send request message: Permission denied
Error (criu/libnetlink.c:84): Can't send request message: Permission denied
Error (criu/libnetlink.c:84): Can't send request message: Permission denied
Error (criu/libnetlink.c:84): Can't send request message: Permission denied
Error (criu/libnetlink.c:84): Can't send request message: Permission denied
Error (criu/libnetlink.c:84): Can't send request message: Permission denied
Error (criu/libnetlink.c:84): Can't send request message: Permission denied
Error (criu/libnetlink.c:84): Can't send request message: Permission denied
Error (criu/libnetlink.c:84): Can't send request message: Permission denied
Error (criu/sockets.c:436): sockets: Sockets (family 1 proto 0) are not collected
Error (criu/sk-unix.c:351): unix: Unix socket 301922 not found
Error (criu/cr-dump.c:1675): Dump files (pid: 121) failed with -1
Error (criu/cr-dump.c:2099): Dumping FAILED.
CWWKE0963E: The server checkpoint request failed because netlink system calls were unsuccessful. If SELinux is enabled in enforcing mode, netlink system calls might be blocked by the SELinux "virt_sandbox_use_netlink" policy setting. Either disable SELinux or enable the netlink system calls with the "setsebool virt_sandbox_use_netlink 1" command.
Error: error building at STEP "RUN checkpoint.sh applications": error while running runtime: exit status 74
```
