### ISSUE TITLE
RegistryHelper.getUserRegistry throws an IllegalStateException if no user registries are present

### ISSUE THREAD

**Issue by SoftlySplinter** [OpenLiberty/open-liberty#24565]
**Describe the bug**  
`IllegalStateException` thrown from `RegistryHelper.getUserRegistry(null)` if no user registries are defined in `server.xml` (or its includes)

```
[3/6/23 14:29:26:088 GMT] 00000066 com.ibm.ws.security.internal.SecurityServiceImpl             E CWWKS0005E: A configuration exception has occurred. No available UserRegistry service.
[3/6/23 14:29:26:091 GMT] 00000066 LogService-304-com.ibm.cics.wlp.link.impl                    E CWWKE0701E: [com.ibm.cics.wlp.link.impl.connector] [ECBListener] @Error: waitAndDispatchRequest() - Unexpected exception occured java.lang.IllegalStateException: CWWKS0005E: A configuration exception has occurred. No available UserRegistry service.
        at com.ibm.ws.security.internal.SecurityServiceImpl.autoDetectService(SecurityServiceImpl.java:405)
        at com.ibm.ws.security.internal.SecurityServiceImpl.getUserRegistryService(SecurityServiceImpl.java:544)
        at com.ibm.ws.security.intfc.internal.WSSecurityServiceImpl.getActiveUserRegistry(WSSecurityServiceImpl.java:169)
        at com.ibm.ws.security.intfc.internal.WSSecurityServiceImpl.getUserRegistry(WSSecurityServiceImpl.java:66)
        at com.ibm.wsspi.security.registry.RegistryHelper.getUserRegistry(RegistryHelper.java:71)
        at com.ibm.cics.wlp.link.security.CICSSecurityContextServiceImpl.createCICSSecurityContext(CICSSecurityContextServiceImpl.java:67)
        at com.ibm.cics.wlp.link.impl.CICSSecurityContextFactory.createCICSSecurityContext(CICSSecurityContextFactory.java:104)
        at com.ibm.cics.wlp.link.impl.connector.ECBListener.handleLinkRequest(ECBListener.java:245)
        at com.ibm.cics.wlp.link.impl.connector.ECBListener.waitAndDispatchRequest(ECBListener.java:205)
        at com.ibm.cics.wlp.link.impl.connector.ECBListener.run(ECBListener.java:167)
        at java.lang.Thread.run(Thread.java:825)
```

**Steps to Reproduce**  
Call the `RegistryHelper.getUserRegistry(null)` method when no user registries exist in `server.xml`.

**Expected behavior**  
`null` is returned.

From the JavaDoc:

> ### public static UserRegistry getUserRegistry​(java.lang.String realmName) throws WSSecurityException
> 
> Gets the UserRegistry object for the given realm. If the realm name is null returns the active registry. If the realm is not valid, or security is not enabled, or no registry is configured, returns null.
>
> **Parameters:** realmName - 
> **Returns:** UserRegistry object
> **Throws:** WSSecurityException - if there is an internal error

**Diagnostic information:**  
 - OpenLiberty Version: 22.0.0.12
 - Affected feature(s): N/A
 - Java Version: Java(TM) SE Runtime Environment (8.0.7.20 - pmz6480sr7fp20-20221020_01(SR7 FP20))
 - server.xml configuration: N/A

**Comment by Zech-Hein** [comment]
According to the javadoc for the api method, throwing an IllegalStateException is not valid. Instead it should be cast as a WSSecurityException to indicate there has been an internal error.
