### ISSUE TITLE
Fix ClassCastException during the de-serialization of CDI Injected Event

### ISSUE THREAD

**Issue by volosied** [OpenLiberty/open-liberty#24631]
**Describe the bug**  
A passivated (i.e. serializable) bean which has an injected jakarta.enterprise.event.Event (or javax equivalent) will not be properly restored.  This can be encountered when session persistence is enabled and session data is serialized and de-serialized from a database.

The FFDC: 
```
Stack Dump = java.lang.ClassCastException: cannot assign instance of org.jboss.weld.event.EventImpl$SerializationProxy to field org.apache.myfaces.flow.cdi.FlowScopeContextualStorageHolder.flowDestroyedEvent of type jakarta.enterprise.event.Event in instance of org.apache.myfaces.flow.cdi.FlowScopeContextualStorageHolder
	at java.base/java.io.ObjectStreamClass$FieldReflector.setObjFieldValues(ObjectStreamClass.java:2076)
	at java.base/java.io.ObjectStreamClass$FieldReflector.checkObjectFieldValueTypes(ObjectStreamClass.java:2039)
	at java.base/java.io.ObjectStreamClass.checkObjFieldValueTypes(ObjectStreamClass.java:1293)
	at java.base/java.io.ObjectInputStream.defaultCheckFieldValues(ObjectInputStream.java:2512)
```
 

**Steps to Reproduce**  

If a passivated bean contains code as such below, and this bean is then serialized, such as via sessionDatabase-1.0 , the ClassCastException will occur: 

    @Inject
    private Event<someType> someEvent;

**Expected behavior**  
The CDI event objects should be restored without errors. 

**Diagnostic information:**  
 - OpenLiberty Version: All. (Fix targeted for 22.0.0.3) 
 - Affected feature(s) cdi-1.2, cdi-2.0, cdi-3.0, cdi-4.0, (sessionDatabase-1.0, if following the example above) 
 - Java Version: n/a
 - server.xml configuration: n/a 
 
**Additional context**  
This problem was discovered via faces-4.0 (currently in beta as of this post) for this following event: https://github.com/apache/myfaces/blob/myfaces-core-module-4.0.0/impl/src/main/java/org/apache/myfaces/flow/cdi/FlowScopeContextualStorageHolder.java#L65-L67

**Comment by volosied** [comment]
Fixed, so I'll close it out. 

Tests will be added under #24679
