### ISSUE TITLE
UUID not working as GeneratedValue Id in some cases

### ISSUE THREAD

**Issue by njr-11** [OpenLiberty/open-liberty#24925]
**Describe the bug**  

Jakarta Persistence 3.1 added the ability to have a UUID be the id and to also be generated.  In some cases such as the following, where `strategy = GenerationType.UUID` or strategy is omitted (defaulting to AUTO), an IllegalArgumentException is being raised when trying to save an entity for the first time (when it starts out without an id, needing it generated).

```
    @GeneratedValue(strategy = GenerationType.UUID)
    @Id
    public UUID id;
```

```
java.lang.IllegalArgumentException: Source object is not an instance of java.util.UUID
	at org.eclipse.persistence.mappings.converters.UUIDConverter.convertObjectValueToDataValue(UUIDConverter.java:46)
	at org.eclipse.persistence.mappings.foundation.AbstractDirectMapping.getFieldValue(AbstractDirectMapping.java:790)
	at org.eclipse.persistence.mappings.foundation.AbstractDirectMapping.valueFromObject(AbstractDirectMapping.java:1202)
	at org.eclipse.persistence.internal.descriptors.ObjectBuilder.extractPrimaryKeyFromObject(ObjectBuilder.java:3156)
	at org.eclipse.persistence.internal.sessions.MergeManager.registerObjectForMergeCloneIntoWorkingCopy(MergeManager.java:1062)
	at org.eclipse.persistence.internal.sessions.MergeManager.mergeChangesOfCloneIntoWorkingCopy(MergeManager.java:575)
	at org.eclipse.persistence.internal.sessions.MergeManager.mergeChanges(MergeManager.java:324)
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.mergeCloneWithReferences(UnitOfWorkImpl.java:3641)
	at org.eclipse.persistence.internal.sessions.RepeatableWriteUnitOfWork.mergeCloneWithReferences(RepeatableWriteUnitOfWork.java:402)
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.mergeCloneWithReferences(UnitOfWorkImpl.java:3601)
	at org.eclipse.persistence.internal.jpa.EntityManagerImpl.mergeInternal(EntityManagerImpl.java:644)
	at org.eclipse.persistence.internal.jpa.EntityManagerImpl.merge(EntityManagerImpl.java:622)
```

**Steps to Reproduce**  

Using the latest Open Liberty code, update the following test classes to switch `Long` and `long` and `SEQUENCE` to `UUID`:
https://github.com/OpenLiberty/open-liberty/blob/integration/dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Order.java
https://github.com/OpenLiberty/open-liberty/tree/integration/dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web

Then run the following test bucket:
./gradlew io.openliberty.data.internal_fat_jpa:buildandrun

A single failure is reported, from DataJPATestServlet.testGeneratedKey, which reports the aforementioned IllegalArgumentException as the cause.

**Expected behavior**  
It should be possible to save/merge the entity without the id value, and the UUID value should be generated automatically.

**Diagnostic information:**  
 - OpenLiberty Version: development
 - Affected feature(s) persistence-3.1/data-1.0
 - Java Version: OpenJDK Runtime Environment (11.0.2+9) os = Mac OS X (10.16; amd64) (en_US)
 - server.xml configuration https://github.com/OpenLiberty/open-liberty/blob/integration/dev/io.openliberty.data.internal_fat_jpa/publish/servers/io.openliberty.data.internal.fat.jpa/server.xml

**Additional context**

**Comment by edwinquaihoi** [comment]
Any outlook on this issue, seems a pretty fundamental one?

**Comment by Riva-Tholoor-Philip** [comment]
Created an EclipseLink issue to bring the fix in EclipseLink. Issue #[2086](https://github.com/eclipse-ee4j/eclipselink/issues/2086)

**Comment by tkburroughs** [comment]
Since the problem has been accepted and fixed in EclipseLink, I've added `release bug` label so this will be documented in release notes when included in open liberty.

**Comment by Riva-Tholoor-Philip** [comment]
Working on bringing the changes in EclipseLink to Open Liberty

**Comment by Riva-Tholoor-Philip** [comment]
As PR# [27872](https://github.com/OpenLiberty/open-liberty/pull/27872) is merged , we are closing this issue

**Comment by njr-11** [comment]
Good work fixing the bug.  We should keep this issue open until the Jakarta Data tests that discovered it are re-enabled.  I created pull #27892 for that.
