### ISSUE TITLE
An application bound to a virtual host fails to start if the endpoint is disabled or paused

### ISSUE THREAD

**Issue by ibm-z-pot** [OpenLiberty/open-liberty#24921]
**Describe the bug**  
A web application bound to a virtual host fails to start or restart if the associated endpoint is paused or disabled.
Example server.xml:
```
    <httpEndpoint id="app1Endpoint"
                  host="*" 
                  httpPort="-1" 
                  httpsPort="56100"
                  enabled="false" /> 

    <virtualHost id="app1_host">
        <hostAlias>app1.ibm:56100</hostAlias>
    </virtualHost>    

   <webApplication location="${shared.app.dir}/app1_v1.0.1.war" name="app1" contextRoot="/app1" >  
      <web-bnd>
         <virtual-host name="app1_host" />
      </web-bnd>
   </webApplication>
```

message.log:
```
[4/4/23 8:32:36:635 GMT] 0000002d com.ibm.ws.app.manager.AppMessageHelper                      I CWWKZ0018I: Starting application app1.
[4/4/23 8:32:36:637 GMT] 0000002d bm.ws.app.manager.war.internal.WARDeployedAppInfoFactoryImpl I CWWKZ0133I: The app1 application at the /var/zosconnect/shared/apps/app1_v1.0.1.war location is being expanded to the /var/zosconnect/servers/baqbc01/apps/expanded/app1.war directory.
[4/4/23 8:32:38:931 GMT] 0000002d com.ibm.ws.webcontainer.osgi.webapp.WebGroup                 I SRVE0169I: Loading Web Module: app1_v1.0.1.
[4/4/23 8:32:38:931 GMT] 0000002d com.ibm.ws.webcontainer                                      I SRVE0250I: Web Module app1_v1.0.1 has been bound to app1_host.
[4/4/23 8:32:38:931 GMT] 0000002d com.ibm.ws.webcontainer.webapp                               E SRVE0297E: Web Application app1_v1.0.1 destroy encountered errors: java.lang.NullPointerException
	at com.ibm.ws.webcontainer.webapp.WebApp.getServletWrapper(WebApp.java:1851)
	at com.ibm.ws.webcontainer.webapp.WebApp.getServletWrapper(WebApp.java:1774)
	at com.ibm.ws.webcontainer.webapp.WebApp.destroy(WebApp.java:3977)
	at com.ibm.ws.webcontainer.osgi.webapp.WebApp.destroy(WebApp.java:1470)
	at com.ibm.ws.container.AbstractContainer.destroy(AbstractContainer.java:79)
	at com.ibm.ws.webcontainer.webapp.WebGroup.destroy(WebGroup.java:215)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost.addWebApplication(DynamicVirtualHost.java:181)
	at com.ibm.ws.webcontainer.WebContainer.addWebApp(WebContainer.java:540)
	at com.ibm.ws.webcontainer.WebContainer.addWebApplication(WebContainer.java:495)
	at com.ibm.ws.webcontainer.osgi.WebContainer.startModule(WebContainer.java:971)
	at com.ibm.ws.app.manager.module.internal.ModuleHandlerBase.deployModule(ModuleHandlerBase.java:99)
	at com.ibm.ws.app.manager.module.internal.DeployedModuleInfoImpl.installModule(DeployedModuleInfoImpl.java:49)
	at com.ibm.ws.app.manager.module.internal.SimpleDeployedAppInfoBase.deployModules(SimpleDeployedAppInfoBase.java:597)
	at com.ibm.ws.app.manager.module.internal.SimpleDeployedAppInfoBase.installApp(SimpleDeployedAppInfoBase.java:511)
	at com.ibm.ws.app.manager.module.internal.DeployedAppInfoBase.deployApp(DeployedAppInfoBase.java:349)
	at com.ibm.ws.app.manager.war.internal.WARApplicationHandlerImpl.install(WARApplicationHandlerImpl.java:65)
	at com.ibm.ws.app.manager.internal.statemachine.StartAction.execute(StartAction.java:161)
	at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.enterState(ApplicationStateMachineImpl.java:1357)
	at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.run(ApplicationStateMachineImpl.java:901)
	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:825)
```

**Steps to Reproduce**  
Start a Liberty server with the following configuration:

```
    <httpEndpoint id="app1Endpoint"
                  host="*" 
                  httpPort="-1" 
                  httpsPort="56100"
                  enabled="false" /> 

    <virtualHost id="app1_host">
        <hostAlias>app1.ibm:56100</hostAlias>
    </virtualHost>    

   <webApplication location="${shared.app.dir}/app1_v1.0.1.war" name="app1" contextRoot="/app1" >  
      <web-bnd>
         <virtual-host name="app1_host" />
      </web-bnd>
   </webApplication>
```

**Expected behavior**  
The web application should start successfully without any error messages.

**Diagnostic information:**  
 - OpenLiberty Version: 22.0.0.9
 - Affected feature(s): n/a
 - Java Version: [i.e. full output of `java -version`]
```
java.version = 1.8.0_351
java.runtime = Java(TM) SE Runtime Environment (8.0.7.20 - pmz6480sr7fp20-20221020_01(SR7 FP20))
```
 - server.xml configuration: provided above
 - `$WLP_OUTPUT_DIR/messages.log`: provided above

**Additional context**  
The problem also happens if the endpoint is enabled at startup, but is subsequently paused prior to an app or config refresh.
i.e. if attempting the following sequence:

```
- PAUSE,TARGET='app1Endpoint'
- app or config change
- REFRESH,APPS or REFRESH,CONFIG
- RESUME,TARGET='app1Endpoint'
```

the REFRESH command will fail with the same error described above.

**Comment by pmd1nh** [comment]
hi, how does your application suppose to serve any request if its http endpoint is not active?

**Comment by ibm-z-pot** [comment]
The application is available in 2 or more Liberty servers (standard HA topology). Pausing the endpoint in one server causes requests to be routed to another server.
