### ISSUE TITLE
Current External Upsteam Liberty Arquillian Container 'Hangs' on exit of last test in Liberty FAT tests

### ISSUE THREAD

**Issue by hutchig** [OpenLiberty/open-liberty#2506]
In my experience the Fault Tolerance TCK hangs 9/10 times and I have also seen the Config TCK hang.
Track shows entry of final 'stop' method exit.

**Comment by Azquelt** [comment]
After much cajoling, I managed to get a stack trace out!

Here's what I think is happening:

Surefire starts up a new process to run threads. This process finishes, but the parent thread is still trying to talk to it. The stack dump makes it look like it's stuck doing a write, so I suspect it's trying to talk to the finished process (which blocks) and another thread has requested it stops and is waiting for it to close.

It looks like the code in surefire has been changed recently so it may be worth trying with a newer version of surefire.

**Comment by Azquelt** [comment]
Though it's worth noting that none of that explains why moving up to a newer version of the arquillian wlp container causes it to fail.

It may be that it's causing the surefire process to crash or finish before the parent expects it to. Even if a newer version of surefire does prevent the hang, it might just expose the next problem.

**Comment by Azquelt** [comment]
Obtaining a stack trace (for my future reference):

Usually you can `kill -3 <pid>` to get a javadump from an ibm jvm. For some reason that didn't work in this case.

You can also run `gcore -o outputfile <pid>` to generate a coredump and then use `jdmpview` (part of ibm java sdk) to extract the thread information from that. That did work in this case.

**Comment by Azquelt** [comment]
If you're not using the IBM JVM, the Oracle jdk includes `jstack` which appears to be able to extract a stack trace from either a running process or a core dump, but I have not tried it.

**Comment by Azquelt** [comment]
With a newer version of surefire, this is the error I get:
```
[ERROR] The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /home/andrew/git/liberty/open-liberty/dev/com.ibm.ws.microprofile.faulttolerance_fat_tck/build/libs/autoFVT/publish/tckRunner/tck && /home/andrew/dev/ibm-java-x86_64-80/jre/bin/java -jar /home/andrew/git/liberty/open-liberty/dev/com.ibm.ws.microprofile.faulttolerance_fat_tck/build/libs/autoFVT/results/tck/surefire/surefirebooter7798325326823135205.jar /home/andrew/git/liberty/open-liberty/dev/com.ibm.ws.microprofile.faulttolerance_fat_tck/build/libs/autoFVT/results/tck/surefire 2018-03-14T17-13-35_476-jvmRun1 surefire6397700566978526291tmp surefire_04629373291511119650tmp
[ERROR] Process Exit Code: 0
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /home/andrew/git/liberty/open-liberty/dev/com.ibm.ws.microprofile.faulttolerance_fat_tck/build/libs/autoFVT/publish/tckRunner/tck && /home/andrew/dev/ibm-java-x86_64-80/jre/bin/java -jar /home/andrew/git/liberty/open-liberty/dev/com.ibm.ws.microprofile.faulttolerance_fat_tck/build/libs/autoFVT/results/tck/surefire/surefirebooter7798325326823135205.jar /home/andrew/git/liberty/open-liberty/dev/com.ibm.ws.microprofile.faulttolerance_fat_tck/build/libs/autoFVT/results/tck/surefire 2018-03-14T17-13-35_476-jvmRun1 surefire6397700566978526291tmp surefire_04629373291511119650tmp
[ERROR] Process Exit Code: 0
[ERROR] at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:671)
[ERROR] at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:533)
[ERROR] at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:278)
[ERROR] at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:244)
[ERROR] at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1149)
[ERROR] at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:978)
[ERROR] at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:854)
[ERROR] at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
[ERROR] at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
[ERROR] at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
[ERROR] at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
[ERROR] at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
[ERROR] at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
[ERROR] at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
[ERROR] at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
[ERROR] at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
[ERROR] at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
[ERROR] at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
[ERROR] at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
[ERROR] at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
[ERROR] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
[ERROR] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
[ERROR] at java.lang.reflect.Method.invoke(Method.java:508)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR] -> [Help 1]
```

Much more useful than hanging, but not the root cause of the problem.

**Comment by Azquelt** [comment]
Root cause turned out to be that we weren't consuming stderr from the maven process.

The thread processing messages from the child process would receive logging messages from the child and try to write them to stderr. As nothing was consuming stderr, this write would eventually block and the thread would stop processing messages from the child process.
