### ISSUE TITLE
InstantOn Problems restoring when using a DB for the transaction log.

### ISSUE THREAD

**Issue by jdmcclur** [OpenLiberty/open-liberty#25216]
I am testing InstantOn with rest-crud and using a DB for the transaction log, based on info here: https://openliberty.io/docs/latest/transaction-service.html.

I added this to the server.xml:
```
    <transaction transactionLogDBTableSuffix="${HOSTNAME}${wlp.server.name}"
        recoverOnStartup="false"
        recoveryGroup="peer-group-name"
        recoveryIdentity="${HOSTNAME}${wlp.server.name}">
        <dataSource transactional="false">
        <jdbcDriver libraryRef="postgres"/>
          <properties databaseName="rest-crud" user="restcrud" password="restcrud" serverName="checkers06.rtp.raleigh.ibm.com" portNumber="5432"/>
        </dataSource>
    </transaction>
```

Things work fine in a normal case (not using instantOn).
```
[AUDIT   ] WTRN0108I: Server with identity 16808a2c779fdefaultServer is monitoring its peers for Transaction Peer Recovery
[AUDIT   ] WTRN0108I: Insert New Lease for server with recovery identity 16808a2c779fdefaultServer
```

But using instantOn, after a restore on the first request I see.
```
[5/5/23, 14:32:43:731 EDT] 000000d2 com.ibm.ws.logging.internal.impl.IncidentImpl                I FFDC1015I: An FFDC Incident has been created: "java.lang.IllegalStateException: Required attribute is null,AtomicServiceReference[name=jpaRuntime,ctx=null,ref=null,svc=null] com.ibm.wsspi.injectionengine.InjectionBinding.getInjectionObject 408" at ffdc_23.05.05_14.32.43.0.log
[5/5/23, 14:32:43:824 EDT] 000000d2 com.ibm.ws.logging.internal.impl.IncidentImpl                I FFDC1015I: An FFDC Incident has been created: "com.ibm.wsspi.injectionengine.InjectionException: CWNEN0030E: The server was unable to obtain an object instance for the java:comp/env/com.acme.crud.FruitResource/entityManager reference.  The exception message was: Required attribute is null,AtomicServiceReference[name=jpaRuntime,ctx=null,ref=null,svc=null] com.ibm.ws.cdi.impl.weld.injection.WebSphereInjectionServicesImpl 201" at ffdc_23.05.05_14.32.43.1.log
[5/5/23, 14:32:43:825 EDT] 000000d2 bm.ws.cdi.impl.weld.injection.WebSphereInjectionServicesImpl E CWOWB1000E: A CDI error has occurred: CWNEN0030E: The server was unable to obtain an object instance for the java:comp/env/com.acme.crud.FruitResource/entityManager reference.  The exception message was: Required attribute is null,AtomicServiceReference[name=jpaRuntime,ctx=null,ref=null,svc=null]
[5/5/23, 14:32:43:840 EDT] 000000d2 com.ibm.ws.logging.internal.impl.IncidentImpl                I FFDC1015I: An FFDC Incident has been created: "com.ibm.wsspi.injectionengine.InjectionException: CWNEN0030E: The server was unable to obtain an object instance for the java:comp/env/com.acme.crud.FruitResource/entityManager reference.  The exception message was: Required attribute is null,AtomicServiceReference[name=jpaRuntime,ctx=null,ref=null,svc=null] com.ibm.ws.cdi.impl.weld.injection.WebSphereInjectionServicesImpl.inject 248" at ffdc_23.05.05_14.32.43.2.log
[5/5/23, 14:32:43:867 EDT] 000000d2 com.ibm.ws.logging.internal.impl.IncidentImpl                I FFDC1015I: An FFDC Incident has been created: "java.security.PrivilegedActionException: com.ibm.wsspi.injectionengine.InjectionException: CWNEN0030E: The server was unable to obtain an object instance for the java:comp/env/com.acme.crud.FruitResource/entityManager reference.  The exception message was: Required attribute is null,AtomicServiceReference[name=jpaRuntime,ctx=null,ref=null,svc=null] com.ibm.ws.cdi.impl.weld.injection.WebSphereInjectionServicesImpl 118" at ffdc_23.05.05_14.32.43.3.log
[5/5/23, 14:32:43:867 EDT] 000000d2 bm.ws.cdi.impl.weld.injection.WebSphereInjectionServicesImpl E CWOWB1000E: A CDI error has occurred: CWNEN0030E: The server was unable to obtain an object instance for the java:comp/env/com.acme.crud.FruitResource/entityManager reference.  The exception message was: Required attribute is null,AtomicServiceReference[name=jpaRuntime,ctx=null,ref=null,svc=null]
```

Also, if I set `recoverOnStartup="true"` I see a different error on startup.
```
[AUDIT   ] WTRN0108I: Server with identity HOSTNAMEdefaultServer is monitoring its peers for Transaction Peer Recovery
[ERROR   ] WTRN0016E: Exception caught during transaction service recovery! java.net.URISyntaxException: Illegal character in query at index 80: custom://com.ibm.rls.jdbc.SQLRecoveryLogFactory?datasource=Liberty,tablesuffix=${HOSTNAME}defaultServer
	at java.base/java.net.URI$Parser.fail(URI.java:2976)
	at java.base/java.net.URI$Parser.checkChars(URI.java:3147)
	at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3235)
	at java.base/java.net.URI$Parser.parse(URI.java:3177)
	at java.base/java.net.URI.<init>(URI.java:623)
	at com.ibm.tx.jta.impl.TxRecoveryAgentImpl.createCustomTranLogConfiguration(TxRecoveryAgentImpl.java:840)
	at [internal classes]
```

**Comment by jdmcclur** [comment]
Most of the above has been fixed, but I am seeing this error when I hit the endpoint. The JPA EntityManager is failing to inject.

```
[ERROR   ] CWOWB1000E: A CDI error has occurred: CWNEN0030E: The server was unable to obtain an object instance for the java:comp/env/com.acme.crud.FruitResource/entityManager reference.  The exception message was: Required attribute is null,AtomicServiceReference[name=jpaRuntime,ctx=null,ref=null,svc=null]
[ERROR   ] CWOWB1000E: A CDI error has occurred: CWNEN0030E: The server was unable to obtain an object instance for the java:comp/env/com.acme.crud.FruitResource/entityManager reference.  The exception message was: Required attribute is null,AtomicServiceReference[name=jpaRuntime,ctx=null,ref=null,svc=null]
```

**Comment by dazavala** [comment]
@jdmcclur I've reproduced the problem, FYI.  More to come...

**Comment by dazavala** [comment]
@jdmcclur FYI, devOps still has not approved the merge of 25841. If necessary, the PR references two personal builds you can use in the meanwhile.

**Comment by dazavala** [comment]
Hello, @jdmcclur. You mentioned the problem resolved, so I'm closing the issue for now.
