### ISSUE TITLE
Occasional GOAWAY from Server when using HTTP/2

### ISSUE THREAD

**Issue by dominikrebhan** [OpenLiberty/open-liberty#25279]
**Describe the bug**  
I experienced a strange behavior, that occasionally the server responds with a GOAWAY when using the built in java.net.HttpClient and HTTP/2 (of course) even on the first request.

Client side:
```
Exception in thread "main" java.io.IOException: /127.0.0.1:59522: GOAWAY received
	at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:586)
	at java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:123)
	at com.liberty.demo.RsClient.main(RsClient.java:19)
Caused by: java.io.IOException: /127.0.0.1:59522: GOAWAY received
	at java.net.http/jdk.internal.net.http.Http2Connection.handleGoAway(Http2Connection.java:1008)
	at java.net.http/jdk.internal.net.http.Http2Connection.handleConnectionFrame(Http2Connection.java:873)
	at java.net.http/jdk.internal.net.http.Http2Connection.processFrame(Http2Connection.java:748)
	at java.net.http/jdk.internal.net.http.frame.FramesDecoder.decode(FramesDecoder.java:155)
	at java.net.http/jdk.internal.net.http.Http2Connection$FramesController.processReceivedData(Http2Connection.java:232)
	at java.net.http/jdk.internal.net.http.Http2Connection.asyncReceive(Http2Connection.java:674)
	at java.net.http/jdk.internal.net.http.Http2Connection$Http2TubeSubscriber.processQueue(Http2Connection.java:1310)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$LockingRestartableTask.run(SequentialScheduler.java:205)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:149)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:230)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

Server side:
```
[16.05.23, 15:50:39:369 MESZ] 00000046 org.jboss.resteasy.resteasy_jaxrs.i18n                       W RESTEASY002130: Failed to parse request.
java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because "scheme" is null
	at com.ibm.ws.webcontainer.srt.SRTServletRequest.getRequestURL(SRTServletRequest.java:3194)
	at org.jboss.resteasy.plugins.server.servlet.ServletUtil.extractUriInfo(ServletUtil.java:47)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:233)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:60)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:55)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:614)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1260)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:748)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:445)
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.invokeTarget(WebAppFilterChain.java:197)
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:100)
	at com.ibm.ws.security.jaspi.JaspiServletFilter.doFilter(JaspiServletFilter.java:58)
	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:203)
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:93)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.doFilter(WebAppFilterManager.java:1068)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1260)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1077)
	at com.ibm.ws.webcontainer.servlet.CacheServletWrapper.handleRequest(CacheServletWrapper.java:77)
	at com.ibm.ws.webcontainer40.servlet.CacheServletWrapper40.handleRequest(CacheServletWrapper40.java:87)
	at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:969)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:283)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1248)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:470)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:429)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:569)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:503)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:363)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.ready(HttpInboundLink.java:330)
	at com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.sendToDiscriminators(NewConnectionInitialReadCallback.java:169)
	at com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.complete(NewConnectionInitialReadCallback.java:77)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:516)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueManager.java:586)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:970)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:1059)
	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:247)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Steps to Reproduce**  
I created a simple application to reproduce the error:

```
<?xml version="1.0" encoding="UTF-8"?>
<server description="new server">

    <!-- Enable features -->
    <featureManager>
        <feature>webProfile-10.0</feature>
    </featureManager>

    <!-- To access this server from a remote client add a host attribute to the following element, e.g. host="*" -->
    <httpEndpoint id="defaultHttpEndpoint"
                  httpPort="9080"
                  httpsPort="9443" />
                  
    <!-- Automatically expand WAR files and EAR files -->
    <applicationManager autoExpand="true"/>

    <!-- Default SSL configuration enables trust for default certificates from the Java runtime --> 
    <ssl id="defaultSSLConfig" trustDefaultCerts="true" />

</server>
```

```
@ApplicationPath("api")
public class RsActivator extends Application {
}
```

```
@Path("call")
public class RsResource {
    @POST
    public void call(@Suspended AsyncResponse asyncResponse, String body) {
        asyncResponse.resume("OK");
    }
}
```

```
public class RsClient {
    public static void main(String[] args) throws Exception {
        var httpClient = HttpClient.newBuilder()
                .version(HttpClient.Version.HTTP_2)
                .build();

        var httpRequest = HttpRequest.newBuilder(URI.create("http://localhost:9080/liberty-demo-1.0-SNAPSHOT/api/call"))
                .POST(HttpRequest.BodyPublishers.ofString("IN"))
                .build();

        var httpResponse = httpClient.send(httpRequest, HttpResponse.BodyHandlers.discarding());
        System.out.println(httpResponse.statusCode());
    }
}
```

Sometimes it works, more often it will fail with the error.

**Expected behavior**  
To work and not to fail when using HTTP/2.

**Diagnostic information:**  
product = Open Liberty 23.0.0.4 (wlp-1.0.76.cl230420230418-0035)
java.home = /Library/Java/JavaVirtualMachines/jdk-17.0.7.jdk/Contents/Home
java.version = 17.0.7
java.runtime = Java(TM) SE Runtime Environment (17.0.7+8-LTS-224)
os = Mac OS X (13.4; aarch64) (de_DE)

**Additional context**  
When switching back to HTTP/1.1 no problems at all.

**Comment by WhiteCat22** [comment]
Hi @dominikrebhan, can you enable trace on your liberty, reproduce the problem and then upload the trace.log?

Here is the trace string: `*=info:io.openliberty.restfulWS*=all:org.jboss.resteasy*=all:com.ibm.ws.webcontainer*=all:com.ibm.wsspi.webcontainer*=all`

Here are instructions on how to enable trace: https://openliberty.io/docs/latest/log-trace-configuration.html#log_details

**Comment by dominikrebhan** [comment]
I attached the files. The first request was successful, the second (just rerun the client) failed immediately. 
[trace_23.05.16_17.31.07.0.log](https://github.com/OpenLiberty/open-liberty/files/11489501/trace_23.05.16_17.31.07.0.log)
[trace.log](https://github.com/OpenLiberty/open-liberty/files/11489506/trace.log)

**Comment by dominikrebhan** [comment]
It seems this issue is present for a long time for me. Before 23.0.0.1 or 22.0.0.13 the server didn't send a GOAWAY. Instead I got a message like "EOF reached while reading" on the client side. It only happens with HTTP/2 and POST (with body?) requests. I also could recreate the issue with Java 11, JavaEE 8 and jaxrs-2.1.

**Comment by pmd1nh** [comment]
@dominikrebhan Thanks for providing helpful info!  I'm able to recreate this problem and investigate it from the channel H2 perspective.  The NPE in servlet is not the main root cause.

**Comment by pmd1nh** [comment]
https://github.com/OpenLiberty/open-liberty/issues/25384

**Comment by dominikrebhan** [comment]
Sorry for not providing more insights. I tried to debug it a bit through, and for me it seems that the payload gets lost somewhere in the middle of the stack. Maybe it has to do something with the HTTP upgrade the java.net.http.HttpClient is doing. Calling it with H2_Prior_Knowledge (OkHttp) worked all the time. But I hadn't the time to fully get the debugger running with the sources.. :(

**Comment by pmd1nh** [comment]
Interesting...I may need to try out with different clients.  Can you also try with JAX-RS client? @dominikrebhan

**Comment by dominikrebhan** [comment]
I tried it with the resteasy-client and with the vert.x-webclient. Both won't use http/2 at all in my test cases. OkHttp won't utilize HTTP/2 with the upgrade path on insecure connections, so only the direct H2-path without upgrade works, they didn't implement this. All these clients work without any problem, when there is no upgrade involved. Unfortunately the java.net.http.HttpClient does not support H2_PRIOR_KNOWLEDGE to test this out. 

The support for HTTP/2 seems a little bit lacky by the various clients out there. But as this is the default on the java.HttpClient this GOAWAY/NPE shouldn't happen in liberty.

**Comment by pmd1nh** [comment]
Besides no round trip Upgrade to HTTP 2 (H2), OkHttp is also a cleartext (instead of SSL) H2

**Comment by bmarwell** [comment]
> #25384

Thanks for mentioning! I will close my issue as it is a duplicate. I will also open an IBM case now that we have confirmation that this affects multiple users.

**Comment by bmarwell** [comment]
Case [TS013201209](https://www.ibm.com/mysupport/5003p00002iwxS0AAI) opened, as IBM WebSphere Liberty is also affected.

**Comment by pmd1nh** [comment]
@dominikrebhan @bmarwell can you please try your tests using curl client instead?

In my test, using java.net.http.HttpClient sending HTTP2, the (second and subsequent) requests fail.

When using curl (without --http2-prior-knowledge to trigger the upgrade process), same request works consistently (tested on both JAX-RS and servlet)

`curl -v --http2 --data "CURL_POST_DATA" "http://localhost:9099/prototype_EE8/api/postbody"`

From my debug, during the upgrade, the HttpClient somehow sends the HTTP 2 frames out of order in the subsequent requests.  It sends the DATA_frame/stream before the preface/control stream.  This causes the server to fail the request.

(Note: NPE is the side effect when the upgrade requests have failed.  We will look into that but the main root cause is that the client sending HTTP2 frames/stream out of order).

Thanks,

**Comment by bmarwell** [comment]
> @dominikrebhan @bmarwell can you please try your tests using curl client instead?

> In my test, using java.net.http.HttpClient sending HTTP2, the (second and subsequent) requests fail.

Yes, but they fail with different messages for me (maybe because of Liberty already shutting down?):

```
[ERROR] Errors: 
[ERROR]   A__TarIT » Processing java.nio.channels.ClosedChannelException
[ERROR]   D___TarIT » Processing java.io.IOException: IOException invoking http://localhost:60564/app/postApi: /127.0.0.1:60825: GOAWAY received
[ERROR]   L___TarIT » Processing java.net.SocketException: SocketException invoking http://localhost:60564/app/postApi: Connection reset
[ERROR]   N___TarIT » Processing java.io.IOException: IOException invoking http://localhost:60564/app/postApi: Can't get stream 1: java.io.EOFException: EOF reached while reading
```

This is the call in the Junit extension with the "quick fix":

```
  @Override
  public void beforeAll(ExtensionContext context) throws Exception {
    // FIXME: https://github.com/OpenLiberty/open-liberty/issues/25384
    client.property("org.apache.cxf.transport.http.forceVersion", "1.1");
    final Invocation invocation = client.target(getBaseUri())
        .path("postApi")
        .request("application/x-tar")
        .buildPost(Entity.json(getRequestJson()));

    // error below this line
    try (final Response response = invocation.invoke()) {
    // ...
    }
  }
```

 
> When using curl (without --http2-prior-knowledge to trigger the upgrade process), same request works consistently (tested on both JAX-RS and servlet)
> 
> `curl -v --http2 --data "CURL_POST_DATA" "http://localhost:9099/prototype_EE8/api/postbody"`

Yes, I can confirm that curl always works.

> From my debug, during the upgrade, the HttpClient somehow sends the HTTP 2 frames out of order in the subsequent requests. It sends the DATA_frame/stream before the preface/control stream. This causes the server to fail the request.

> (Note: NPE is the side effect when the upgrade requests have failed. We will look into that but the main root cause is that the client sending HTTP2 frames/stream out of order).

Maybe I can just run one IT and get a trace. What would you need?

**Comment by bmarwell** [comment]
Here's some debugging output. I used this property: `'-Djdk.httpclient.HttpClient.log=errors,requests,headers,frames[:control:data:window:all],content,ssl,trace,channel,all'`.

First run w/ quickfix enabled.

[2023-06-14_h2_disabled_force_h1.1.txt](https://github.com/OpenLiberty/open-liberty/files/11742314/2023-06-14_h2_disabled_force_h1.1.txt)

Nothing unexpected here.

Now here's the output with h2 enabled / no "forceVersion" = "1.1" for CXF / http client

[2023-06-14_h2_enabled.txt](https://github.com/OpenLiberty/open-liberty/files/11742324/2023-06-14_h2_enabled.txt)

**Comment by pmd1nh** [comment]
The problem looks to be that java HttpClient sends the required connection preface AFTER the data frame.

Reference to HTTP 2 spec

========================
https://datatracker.ietf.org/doc/html/rfc7540#section-3.5

`[3.5](https://datatracker.ietf.org/doc/html/rfc7540#section-3.5).  HTTP/2 Connection Preface

   In HTTP/2, each endpoint is required to send a connection preface as
   a final confirmation of the protocol in use and to establish the
   initial settings for the HTTP/2 connection.  The client and server
   each send a different connection preface.

   The client connection preface starts with a sequence of 24 octets,
   which in hex notation is:

     0x505249202a20485454502f322e300d0a0d0a534d0d0a0d0a

   That is, the connection preface starts with the string "PRI *
   HTTP/2.0\r\n\r\nSM\r\n\r\n").  This sequence MUST be followed by a
   SETTINGS frame ([Section 6.5](https://datatracker.ietf.org/doc/html/rfc7540#section-6.5)), which MAY be empty.  The client sends
   the client connection preface immediately upon receipt of a 101
   (Switching Protocols) response (indicating a successful upgrade) or
   as the first application data octets of a TLS connection.  If
   starting an HTTP/2 connection with prior knowledge of server support
   for the protocol, the client connection preface is sent upon
   connection establishment.`
   
==========================

   In my test that sending POST to JAXRS or pure Servlet application using HTTP1 > upgrade > HTTP 2, these are the filtered logs  showing the 101 Switch and the return of the preface frame (Note I added my initial PMDINH in the Liberty code to show the received value of the frame).  The server is expecting `PRI * HTTP/2.0`
   
Test using  HttpClient:
   
```
  //This is first POST request 
[6/2/23, 7:26:10:436 EDT] 00000040 id=00000000 com.ibm.ws.genericbnf.internal.BNFHeadersImpl                1 Adding header [User-Agent] with value [Java-http-client/11.0.18]
[6/2/23, 7:26:10:988 EDT] 00000040 id=00000000 com.ibm.ws.http.channel.internal.HttpResponseMessageImpl     1 Marshalling first line: HTTP/1.1 101 Switching Protocols
[6/2/23, 7:26:11:085 EDT] 00000045 id=00000000 SystemOut                                                    O PMDINH, FrameReadProcessor CHECKPOINT 1, valueString [PRI * HTTP/2.0

//This is second POST request with  _SECOND_POST_PMDINH_ is the body data
[6/2/23, 7:26:39:115 EDT] 0000004a id=00000000 com.ibm.ws.genericbnf.internal.BNFHeadersImpl                1 Adding header [User-Agent] with value [Java-http-client/11.0.18]
[6/2/23, 7:26:39:122 EDT] 0000004a id=00000000 com.ibm.ws.http.channel.internal.HttpResponseMessageImpl     1 Marshalling first line: HTTP/1.1 101 Switching Protocols
[6/2/23, 7:26:39:143 EDT] 00000049 id=00000000 SystemOut                                                    O PMDINH, FrameReadProcessor CHECKPOINT 1, valueString [_SECOND_POST_PMDINH_PRI ]


```
We can see that the POST body data was sent BEFORE the PRI * frame.  This causes the server to close out the connection.

Test using curl  client:

```
//First POST
[6/5/23, 10:37:44:931 EDT] 0000003a id=00000000 com.ibm.ws.genericbnf.internal.BNFHeadersImpl                1 Adding header [User-Agent] with value [curl/7.87.0]
[6/5/23, 10:37:45:629 EDT] 0000003a id=00000000 com.ibm.ws.http.channel.internal.HttpResponseMessageImpl     1 Marshalling first line: HTTP/1.1 101 Switching Protocols
[6/5/23, 10:37:45:719 EDT] 0000005b id=00000000 SystemOut                                                    O PMDINH, FrameReadProcessor CHECKPOINT 1, valueString [PRI * HTTP/2.0

// Second POST
[6/5/23, 10:38:13:541 EDT] 00000037 id=00000000 com.ibm.ws.genericbnf.internal.BNFHeadersImpl                1 Adding header [User-Agent] with value [curl/7.87.0]
[6/5/23, 10:38:13:553 EDT] 00000037 id=00000000 com.ibm.ws.http.channel.internal.HttpResponseMessageImpl     1 Marshalling first line: HTTP/1.1 101 Switching Protocols
[6/5/23, 10:38:13:556 EDT] 00000059 id=00000000 SystemOut                                                    O PMDINH, FrameReadProcessor CHECKPOINT 1, valueString [PRI * HTTP/2.0

//Third POST
[6/5/23, 10:51:39:518 EDT] 0000004a id=00000000 com.ibm.ws.genericbnf.internal.BNFHeadersImpl                1 Adding header [User-Agent] with value [curl/7.87.0]
[6/5/23, 10:51:39:529 EDT] 0000004a id=00000000 com.ibm.ws.http.channel.internal.HttpResponseMessageImpl     1 Marshalling first line: HTTP/1.1 101 Switching Protocols
[6/5/23, 10:51:39:531 EDT] 00000047 id=00000000 SystemOut                                                    O PMDINH, FrameReadProcessor CHECKPOINT 1, valueString [PRI * HTTP/2.0
```

**Comment by bmarwell** [comment]
Related? => https://github.com/OpenLiberty/open-liberty/issues/18843

**Comment by djelinski** [comment]
Hi @pmd1nh ,
The HttpClient is sending the connection preface after the HTTP POST body.
Reference to the HTTP2 spec:
https://datatracker.ietf.org/doc/html/rfc7540#section-3.2

> Requests that contain a payload body MUST be sent in their entirety before the client can send HTTP/2 frames.  This means that a large request can block the use of the connection until it is completely sent.

There is a race condition somewhere in the liberty server code. I ran a test that sends a single HTTP POST request to the server. The same test passed once, failed once. Attached a pcap file containing both tries. Can you spot the difference?

[liberty.zip](https://github.com/OpenLiberty/open-liberty/files/12685586/liberty.zip)

**Comment by pmd1nh** [comment]
@djelinski 

I will take a look.  Thanks!

What puzzling me is that the CURL always work with the same upgrade H2 request to the same server.  Any idea why CURL works?

**Comment by djelinski** [comment]
We will only know for sure when we find and fix the problem. But I noticed that CURL is sending the preface and the settings frame in separate IP packets, and HttpClient is sending them in one.

**Comment by pmd1nh** [comment]
Hi @djelinski  ,

What seems to cause this problem in Liberty is that the Headers and POST data are sent in 2 different packages with HttpClient.  In CURL, both Headers + POST data are sent in one package.  The late arrival of the POST data (when sending separately) causes the server to read that during the process of the Preface (it is the next data on the wire, after the Headers package and before the actual Preface package) on a different thread and throws the GoAWAY. 

If all data is in one package, it works well.

[CURL_H2_2_requests.zip](https://github.com/OpenLiberty/open-liberty/files/12795229/CURL_H2_2_requests.zip)

Can you please review the pcap capture with CURL?
Can HttpClient send Headers and POST in one package?

Thanks,

**Comment by djelinski** [comment]
Hi @pmd1nh,
> What seems to cause this problem in Liberty is that the Headers and POST data are sent in 2 different packages with HttpClient. In CURL, both Headers + POST data are sent in one package.

This would explain the observed behavior.
> The late arrival of the POST data (when sending separately) seems to cause to the server to read that during the process of the Preface

And that is exactly the problem. The server may send `HTTP/1.1 101` immediately, but it must not start reading the preface until the previous request is fully consumed, to the end of `Content-length` or until the final chunk.
> Can HttpClient send Headers and POST in one package?

Not without code changes, no.

**Comment by pmd1nh** [comment]
Hi @djelinski , 

Do you know how to send chunked encoding in HttpRequest?  I try with the .header("Transfer-Encoding" , "chunked") but get a weird length, and the request is rejected.

```
 var httpRequest = HttpRequest.newBuilder(URI.create("http://localhost:9099/pmdinhApp30W/test")) 
              .POST(HttpRequest.BodyPublishers.ofString("_FIRST_POST_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxPMDINH_"))
                .header("Transfer-Encoding" , "chunked")
                .build();
```
Thanks,

**Comment by pmd1nh** [comment]
Merged https://github.com/OpenLiberty/open-liberty/pull/26877
