### ISSUE TITLE
Investigate cleaning up error logging for wrong bcl provider

### ISSUE THREAD

**Issue by c00crane** [OpenLiberty/open-liberty#25348]
We have a test where we invoke end_session and pass a token for another provider.  The test expects failure and the errors issued look good, but, the one error is logging the whole stack.  We should see if that could be cleaned up a bit.

```
[5/24/23, 14:31:42:243 CDT] 0000003b y.openidconnect.web.OidcRpInitiatedLogoutTokenAndRequestData E CWWKS1625E: The OpenID Connect provider failed to validate the ID token due to [com.ibm.ws.security.openidconnect.token.IDTokenValidationFailedException: CWWKS1646E: The [https://localhost:8920/oidc/endpoint/OidcConfigSample_mainPath] issuer claim in the ID token does not match the [https://localhost:8920/oidc/endpoint/OidcConfigSample_http_httpsRequired_true] expected issuer for the OidcConfigSample_http_httpsRequired_true OpenID Connect provider.
	at com.ibm.ws.security.openidconnect.token.IDTokenValidationFailedException.format(IDTokenValidationFailedException.java:39)
	at com.ibm.ws.security.openidconnect.web.OidcRpInitiatedLogoutTokenAndRequestData.verifyIdTokenHintIssuer(OidcRpInitiatedLogoutTokenAndRequestData.java:197)
	at com.ibm.ws.security.openidconnect.web.OidcRpInitiatedLogoutTokenAndRequestData.parseAndValidateIdTokenHint(OidcRpInitiatedLogoutTokenAndRequestData.java:169)
	at com.ibm.ws.security.openidconnect.web.OidcRpInitiatedLogoutTokenAndRequestData.parseAndPopulateDataFromIdTokenHint(OidcRpInitiatedLogoutTokenAndRequestData.java:137)
	at com.ibm.ws.security.openidconnect.web.OidcRpInitiatedLogoutTokenAndRequestData.populate(OidcRpInitiatedLogoutTokenAndRequestData.java:71)
	at com.ibm.ws.security.openidconnect.web.OidcRpInitiatedLogout.processEndSession(OidcRpInitiatedLogout.java:77)
	at com.ibm.ws.security.openidconnect.web.OidcEndpointServices.processEndSession(OidcEndpointServices.java:380)
	at com.ibm.ws.security.openidconnect.web.OidcEndpointServices.handleOidcRequest(OidcEndpointServices.java:289)
	at com.ibm.ws.security.openidconnect.web.OidcEndpointServlet.handleRequest(OidcEndpointServlet.java:111)
	at com.ibm.ws.security.openidconnect.web.OidcEndpointServlet.doPost(OidcEndpointServlet.java:69)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:547)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:614)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1260)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:748)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:445)
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.invokeTarget(WebAppFilterChain.java:197)
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:100)
	at com.ibm.ws.security.openidconnect.web.OidcRequestFilter.setEndpointRequest(OidcRequestFilter.java:43)
	at com.ibm.ws.security.oauth20.web.OAuth20RequestFilter.doFilter(OAuth20RequestFilter.java:97)
	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:203)
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:93)
	at com.ibm.ws.app.manager.wab.internal.OsgiDirectoryProtectionFilter.doFilter(OsgiDirectoryProtectionFilter.java:92)
	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:203)
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:93)
	at com.ibm.ws.security.jaspi.JaspiServletFilter.doFilter(JaspiServletFilter.java:58)
	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:203)
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:93)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.doFilter(WebAppFilterManager.java:1068)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1260)
	at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:5080)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.handleRequest(DynamicVirtualHost.java:318)
	at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:1038)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:283)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1248)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:470)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:429)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:569)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:503)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:363)
	at com.ibm.ws.http.channel.internal.inbound.HttpICLReadCallback.complete(HttpICLReadCallback.java:72)
	at com.ibm.ws.channel.ssl.internal.SSLReadServiceContext$SSLReadCompletedCallback.complete(SSLReadServiceContext.java:1826)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:516)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueManager.java:586)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:970)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:1059)
	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:247)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:866)
```

**Comment by jimmy1wu** [comment]
@c00crane 

merged #26386 which updates the error log to not include the stack trace.

e.g.,
```
[2023-09-25, 10:13:06:062 EDT] 0000003a y.openidconnect.web.OidcRpInitiatedLogoutTokenAndRequestData E CWWKS1625E: The OpenID Connect provider failed to validate the ID token due to [CWWKS1646E: The [http://localhost:8010/oidc/endpoint/OidcConfigSample] issuer claim in the ID token does not match the [http://localhost:8010/oidc/endpoint/OidcConfigSample] expected issuer for the OidcConfigSample OpenID Connect provider.].
```
