### ISSUE TITLE
NPE: RESTEASY002130 NullPointerException because "scheme" is null

### ISSUE THREAD

**Issue by bmarwell** [OpenLiberty/open-liberty#25384]
**Describe the bug**  

Using the feature restfulWS-3.0, a POST request will yield this error:

```
[2023-06-01T11:24:01.967+0200] 0000004b org.jboss.resteasy.resteasy_jaxrs.i18n                       W RESTEASY002130: Failed to parse request.
java.lang.NullPointerException: Cannot invoke "java.lang.String.equals(java.lang.Object)" because "scheme" is null
	at com.ibm.ws.webcontainer.srt.SRTServletRequest.getRequestURL(SRTServletRequest.java:3194)
	at org.jboss.resteasy.plugins.server.servlet.ServletUtil.extractUriInfo(ServletUtil.java:47)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:233)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:60)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:55)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1260)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:748)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:445)
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.invokeTarget(WebAppFilterChain.java:197)
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:100)
	at com.ibm.ws.security.jaspi.JaspiServletFilter.doFilter(JaspiServletFilter.java:58)
	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:203)
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:93)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.doFilter(WebAppFilterManager.java:1068)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1260)
	at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:5080)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.handleRequest(DynamicVirtualHost.java:318)
	at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:1038)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:283)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1248)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:470)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:429)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:569)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:503)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:363)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.ready(HttpInboundLink.java:330)
	at com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.sendToDiscriminators(NewConnectionInitialReadCallback.java:169)
	at com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.complete(NewConnectionInitialReadCallback.java:77)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:516)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueManager.java:586)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:970)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:1059)
	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:247)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:857)
```

**Steps to Reproduce**  

1. create server with restfulWS-3.0
2. Do a POST request

**Expected behavior**  

Either

1. Clear  error message
2. or FFDC (there is none)
3. or no error at all

**Diagnostic information:**  
 - OpenLiberty Version: 22.0.0.12 & 23.0.0.4
 - Affected feature(s) restfulWS-3.0
 - Java Version: 
```
$ java -version
openjdk version "17.0.6" 2023-01-17
IBM Semeru Runtime Open Edition 17.0.6.0 (build 17.0.6+10)
Eclipse OpenJ9 VM 17.0.6.0 (build openj9-0.36.0, JRE 17 Mac OS X aarch64-64-Bit 20230117_255 (JIT enabled, AOT enabled)
OpenJ9   - e68fb241f
OMR      - f491bbf6f
JCL      - 927b34f84c8 based on jdk-17.0.6+10)
```
 - server.xml configuration (WITHOUT sensitive information like passwords)
 ```
<server description="new server">

  <!-- Enable features -->
  <featureManager>
    <feature>transportSecurity-1.0</feature>
    <feature>restfulWS-3.0</feature>
    <feature>passwordUtilities-1.0</feature>
  </featureManager>


  <application location="${app.filename}.ear" context-root="${app.context.root}" />

  <applicationMonitor updateTrigger="disabled" dropinsEnabled="false"/>

  <httpEndpoint id="defaultHttpEndpoint"
                host="${default.http.host}"
                httpPort="${default.http.port}"
                httpsPort="-1" >
    <accessLogging filepath="${server.output.dir}/logs/http_defaultEndpoint_access.log"
                   logFormat='%h %i %u %t "%r" %s %b %D %{R}W'
    />
  </httpEndpoint>

  <httpOptions removeServerHeader="true"/>
  <httpDispatcher enableWelcomePage="false" />

  <!-- SSL Settings -->

  <sslDefault sslRef="defaultSSLConfig" httpHostNameVerification="true" />

  <ssl id="defaultSSLConfig"
       trustStoreRef="TS"
       keyStoreRef="KS"
       securityLevel="CUSTOM"
       enabledCiphers="TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 TLS_DHE_DSS_WITH_AES_256_GCM_SHA384 TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 TLS_DHE_DSS_WITH_AES_128_GCM_SHA256"
       sslProtocol="TLSv1.2"
       verifyHostname="true"
  />

  <keyStore id="KS"
            location="${server.config.dir}/ks.pk12"
            password="{aes}/"
            type="PKCS12"
  />

  <keyStore id="TS"
            location="${server.config.dir}/ts.pk12"
            password="{aes}/"
            type="PKCS12"
  />

  <!-- Webcontainer Settings -->

  <webContainer deferServletLoad="false"/>
  <webContainer skipMetaInfResourcesProcessing="true"/>

</server>
```
 - If it would be useful, upload the messages.log file found in `$WLP_OUTPUT_DIR/messages.log`

There is none, just the stack trace

**Additional context**

**Comment by bmarwell** [comment]
This seems to be the root cause of the NPE:
https://github.com/OpenLiberty/open-liberty/blob/gm-22.0.0.12/dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/srt/SRTServletRequest.java#L3159-L3173

Here's another run with 22.0.0.6 and traceing enabled: [trace.log](https://github.com/OpenLiberty/open-liberty/files/11624144/trace.log) <-- download the trace log here
.

```
  <logging
      traceSpecification="com.ibm.ws.webcontainer.*=finest:org.jboss.resteasy.plugins.server.servlet.*=finest:com.ibm.ws.webcontainer.servlet.*=finest:jakarta.servlet.http.*=finest"
      isoDateFormat="true"
      consoleLogLevel="AUDIT"
  />
```

**Comment by bmarwell** [comment]
Ah. The NPE is only thrown if I use CXF 4.0.1. Running a request with CXF 4.0.0 against OpenLiberty / IBM WebSphere Liberty will not yield this exception. Will investigate further.

**Comment by bmarwell** [comment]
CXF team found the problem. CXF 4.0.1 is sending an h/2 upgrade header by default, 4.0.0 is not.
Disabling the header using `client.property("org.apache.cxf.transport.http.forceVersion", "1.1");` will make it work.
Thus, this is a liberty (restEasy) issue. It should just be ignored as https is not enabled, as you can see from my config.

Thanks @dkulp

**Comment by bmarwell** [comment]
Closed as duplicate of https://github.com/OpenLiberty/open-liberty/issues/25279

**Comment by bmarwell** [comment]
Closed as duplicate of https://github.com/OpenLiberty/open-liberty/issues/25279
