### ISSUE TITLE
SRVE0216E: post body contains less bytes than specified by content-length

### ISSUE THREAD

**Issue by c00crane** [OpenLiberty/open-liberty#25699]
When using a social client to access a protected app, then invoking a test app to invoke req.logout, I get the following ffdc.

`[7/10/23, 11:33:56:484 CDT] 00000040 [com.ibm.ws](http://com.ibm.ws/).logging.internal.impl.IncidentImpl                I FFDC1015I: An FFDC Incident has been created: “java.io.IOException: SRVE0216E: post body contains less bytes than specified by content-length. [com.ibm.ws](http://com.ibm.ws/).webcontainer.security.PostParameterHelper 404” at ffdc_23.07.10_11.33.56.0.log`

I have added an AllowedFFDC to the tests when we run them using a social client - once this is resolved, that AllowedFFDC should be removed.

[socialHttpSesstionEndSession.zip](https://github.com/OpenLiberty/open-liberty/files/12032293/socialHttpSesstionEndSession.zip)
[socialHttpSesstionLogout.zip](https://github.com/OpenLiberty/open-liberty/files/12032294/socialHttpSesstionLogout.zip)

**Comment by ayoho** [comment]
@arunavemulapalli Would you be able to look to see if this has been fixed?

**Comment by arunavemulapalli** [comment]
Yes, this has been fixed along with oidc logout and saml SLO changes.

**Comment by c00crane** [comment]
Just ran the tests and removed the allowedFFDC for "java.io.IOException" and the test fails - doing this doesn't cause the problem, it just masks it to the test case.
The ffdc contains:
```
Exception = java.io.IOException
Source = com.ibm.ws.webcontainer.security.PostParameterHelper
probeid = 404
Stack Dump = java.io.IOException: SRVE0216E: post body contains less bytes than specified by content-length.
        at com.ibm.ws.webcontainer31.srt.SRTServletRequest31.getInputStreamData(SRTServletRequest31.java:431)
        at com.ibm.ws.webcontainer.security.PostParameterHelper.savePostParams(PostParameterHelper.java:401)
        at com.ibm.ws.security.openidconnect.client.internal.OidcClientImpl.getReqProviderHint(OidcClientImpl.java:577)
        at com.ibm.ws.security.openidconnect.client.internal.OidcClientImpl.getOidcProvider(OidcClientImpl.java:529)
        at com.ibm.ws.security.openidconnect.client.internal.OidcClientImpl.logoutIfSessionInvalidated(OidcClientImpl.java:446)
        at com.ibm.ws.webcontainer.security.WebProviderAuthenticatorProxy.handleOidcClient(WebProviderAuthenticatorProxy.java:596)
        at com.ibm.ws.webcontainer.security.WebProviderAuthenticatorProxy.authenticate(WebProviderAuthenticatorProxy.java:465)
        at com.ibm.ws.webcontainer.security.WebAuthenticatorProxy.authenticate(WebAuthenticatorProxy.java:69)
        at com.ibm.ws.webcontainer.security.WebAppSecurityCollaboratorImpl.authenticateRequest(WebAppSecurityCollaboratorImpl.java:1239)
        at com.ibm.ws.webcontainer.security.WebAppSecurityCollaboratorImpl.setAuthenticatedSubjectIfNeeded(WebAppSecurityCollaboratorImpl.java:872)
        at com.ibm.ws.webcontainer.security.WebAppSecurityCollaboratorImpl.optionallyAuthenticateUnprotectedResource(WebAppSecurityCollaboratorImpl.java:829)
        at com.ibm.ws.webcontainer.security.WebAppSecurityCollaboratorImpl.determineWebReply(WebAppSecurityCollaboratorImpl.java:988)
        at com.ibm.ws.webcontainer.security.WebAppSecurityCollaboratorImpl.performSecurityChecks(WebAppSecurityCollaboratorImpl.java:695)
        at com.ibm.ws.webcontainer.security.WebAppSecurityCollaboratorImpl.preInvoke(WebAppSecurityCollaboratorImpl.java:622)
        at com.ibm.wsspi.webcontainer.collaborator.CollaboratorHelper.preInvokeCollaborators(CollaboratorHelper.java:472)
        at com.ibm.ws.webcontainer.osgi.collaborator.CollaboratorHelperImpl.preInvokeCollaborators(CollaboratorHelperImpl.java:290)
        at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1221)
        at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:5076)
        at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.handleRequest(DynamicVirtualHost.java:328)
        at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:1038)
        at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:293)
        at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1260)
        at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:476)
        at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:435)
        at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:569)
        at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:503)
        at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:363)
        at com.ibm.ws.http.channel.internal.inbound.HttpICLReadCallback.complete(HttpICLReadCallback.java:72)
        at com.ibm.ws.channel.ssl.internal.SSLReadServiceContext$SSLReadCompletedCallback.complete(SSLReadServiceContext.java:1826)
        at com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:516)
        at com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueManager.java:586)
        at com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:970)
        at com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:1059)
        at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:280)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:857)
```
[postBody.zip](https://github.com/OpenLiberty/open-liberty/files/14336876/postBody.zip)
