### ISSUE TITLE
PH55995 LTPA key operation fails when IBMJCEHYBRID provider is at the top of the provider list in java.security on zOS Java 11

### ISSUE THREAD

**Issue by una-tapa** [OpenLiberty/open-liberty#25747]
**Describe the bug**  

On Java 11, when IBMJCEHYBRID is at the top of the security provider list, the following error is thrown when sign
This prevents users from logging into an application like LibetyAdmin resulting in the following error. 
This issue started at 22.0.0.11. The issue is fixed when we revert https://github.com/OpenLiberty/open-liberty/pull/22340

------Start of DE processing------ = [6/5/23, 5:40:40:668 GMT]
Exception = com.ibm.websphere.security.auth.InvalidTokenException
Source = com.ibm.ws.security.token.internal.AbstractTokenImpl
probeid = 178
Stack Dump = com.ibm.websphere.security.auth.InvalidTokenException: BigInteger not invertible.
        at com.ibm.ws.security.token.ltpa.internal.LTPAToken2.getBytes(LTPAToken2.java:381)
        at com.ibm.ws.security.token.internal.AbstractTokenImpl.getBytes(AbstractTokenImpl.java:177)
        at com.ibm.ws.security.authentication.internal.cache.keyproviders.SSOTokenBytesCacheKeyProvider.getSingleSignonTokenBytes(SSOTokenBytesCacheKeyProvider.java:56)
        at com.ibm.ws.security.authentication.internal.cache.keyproviders.SSOTokenBytesCacheKeyProvider.provideKey(SSOTokenBytesCacheKeyProvider.java:39)
        at 
com.ibm.ws.security.authentication.internal.cache.AuthCacheServiceImpl.commonInsert(AuthCacheServiceImpl.java:118)
...........
com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:247)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:839)
Caused by: java.lang.ArithmeticException: BigInteger not invertible.
        at java.base/java.math.MutableBigInteger.modInverse(MutableBigInteger.java:2211)
        at java.base/java.math.MutableBigInteger.mutableModInverse(MutableBigInteger.java:2072)
        at java.base/java.math.BigInteger.modInverse(BigInteger.java:3297)
        at com.ibm.ws.crypto.ltpakeyutil.LTPACrypto.setRSAKey(LTPACrypto.java:566)
        at com.ibm.ws.crypto.ltpakeyutil.LTPAKeyUtil.setRSAKey(LTPAKeyUtil.java:42)
        at com.ibm.ws.security.token.ltpa.internal.LTPAToken2.sign(LTPAToken2.java:295)
        at com.ibm.ws.security.token.ltpa.internal.LTPAToken2.sign(LTPAToken2.java:285)
        at com.ibm.ws.security.token.ltpa.internal.LTPAToken2.getBytes(LTPAToken2.java:378)
        ... 51 more

**Steps to Reproduce**  

1. Configure provider in java.security with IBMJCEHYBRID at the top followed by the hardware crypto provider then softoware crypto provider. 
2. Login to the AdminCenter (any login that creates LtpaToken) 

Sample 
```
security.provider.1=IBMJCEHYBRID
security.provider.2=IBMJCECCA
security.provider.3=IBMZSecurity
security.provider.4=OpenJCEPlus
```

**Expected behavior**  
The user is able to login. 

**Diagnostic information:**  
 - OpenLiberty Version: 22.0.0.11 and later 
 - Affected feature(s) appSecurity-2.0, 3.0, 4.0 
 - Java Version: Java 11 

**Additional context**

**Comment by una-tapa** [comment]
This addressed by https://github.com/OpenLiberty/open-liberty/issues/26267
