### ISSUE TITLE
CDI: Java 2 Security issue in AnnotationLiteral

### ISSUE THREAD

**Issue by tevans78** [OpenLiberty/open-liberty#2574]
https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.workitem.viewWorkItem&id=249075

This may need to be fixed in the API code:

Stack Dump = java.security.AccessControlException: Access denied ("java.lang.reflect.ReflectPermission" "suppressAccessChecks")
at java.security.AccessController.throwACE(AccessController.java:157)
at java.security.AccessController.checkPermissionHelper(AccessController.java:217)
at java.security.AccessController.checkPermission(AccessController.java:349)
at java.lang.SecurityManager.checkPermission(SecurityManager.java:562)
at java.lang.reflect.AccessibleObject.setAccessible(AccessibleObject.java:143)
at javax.enterprise.util.AnnotationLiteral.invoke(AnnotationLiteral.java:282)
at javax.enterprise.util.AnnotationLiteral.getMemberValue(AnnotationLiteral.java:271)
at javax.enterprise.util.AnnotationLiteral.hashCode(AnnotationLiteral.java:241)
at java.util.HashMap.hash(HashMap.java:349)
at java.util.HashMap.put(HashMap.java:622)
at java.util.HashSet.add(HashSet.java:230)
at org.jboss.weld.util.collections.ImmutableSet$BuilderImpl.add(ImmutableSet.java:139)
at org.jboss.weld.util.collections.ImmutableSet$BuilderImpl.addAll(ImmutableSet.java:146)
at org.jboss.weld.event.EventMetadataImpl.getQualifiers(EventMetadataImpl.java:65)
at cdi12.helloworld.extension.test.HelloWorldExtensionTestServlet.doGet(HelloWorldExtensionTestServlet.java:72)

**Comment by Emily-Jiang** [comment]
@Azquelt can you raise a jira if not already?

**Comment by Azquelt** [comment]
JIRA issue is https://issues.jboss.org/browse/CDI-699

**Comment by tevans78** [comment]
@Emily-Jiang @Azquelt @benjamin-confino I checked on the jira issue and it was fixed in version 2.0.1 of the cdi-api.jar ... but that is the jakarta version. How can we pick that up? Latest is actually 2.0.2.
http://central.maven.org/maven2/jakarta/enterprise/jakarta.enterprise.cdi-api/2.0.2/jakarta.enterprise.cdi-api-2.0.2.jar

**Comment by Azquelt** [comment]
the JIRA issue seems to suggest it was fixed in the JavaEE 2.0.SP1 release, so we wouldn't _have_ to move to the jakarta artifact to pick up the change.

**Comment by tevans78** [comment]
Should be resolved by https://github.com/OpenLiberty/open-liberty/issues/13653
