### ISSUE TITLE
Upgrade protobuf library from grpc feature

### ISSUE THREAD

**Issue by BryanCutler** [OpenLiberty/open-liberty#25748]
Our app uses the gRPC feature and it looks like protobuf version 3.19.6 is bundled with it. Our app also has proto compiled files and when they are compiled with a newer version 3.23.1, it produces files that are incompatible with 3.19.6. This causes our app to not startup:

```
probeid = startWebApp
Stack Dump = java.lang.IllegalAccessError: Class org/apache/arrow/flight/impl/Flight$FlightDescriptor illegally accessing "package private" member of class com/google/protobuf/LazyStringArrayList
        at org.apache.arrow.flight.impl.Flight$FlightDescriptor.<init>(Flight.java:5204)
        at org.apache.arrow.flight.impl.Flight$FlightDescriptor.<clinit>(Flight.java:5908)
        at org.apache.arrow.flight.impl.FlightServiceGrpc.getGetFlightInfoMethod(FlightServiceGrpc.java:106)
        at org.apache.arrow.flight.impl.FlightServiceGrpc.getServiceDescriptor(FlightServiceGrpc.java:1027)
        at org.apache.arrow.flight.impl.FlightServiceGrpc.bindService(FlightServiceGrpc.java:913)
        at org.apache.arrow.flight.impl.FlightServiceGrpc$FlightServiceImplBase.bindService(FlightServiceGrpc.java:500)
        at org.apache.arrow.flight.FlightBindingService.bindService(FlightBindingService.java:96)
        at io.grpc.ServerInterceptors.interceptForward(ServerInterceptors.java:73)
        at com.ibm.wdp.connect.flight.Service.bindService(Service.java:134)
        at io.openliberty.grpc.internal.servlet.GrpcServerComponent.onStartup(GrpcServerComponent.java:158)
```

Please upgrade protobuf used in the gRPC feature to 3.23.1+

**Comment by hutchig** [comment]
I will upgrade the library.

**Comment by hutchig** [comment]
I merged the fix for this just now in https://github.com/OpenLiberty/open-liberty/pull/25758 it will probably be delivered in the next 4-weekly release, that being 23.0.0.8

**Comment by hutchig** [comment]
I think I can close this now - feel free to feedback if the latest 23.0.0.8 release does not work fine for you @BryanCutler
