### ISSUE TITLE
Liberty Error: CloneNotSupportedException caught while trying to clone MessageDigest with algorithm SHA-512

### ISSUE THREAD

**Issue by simysc** [OpenLiberty/open-liberty#25830]
**Describe the bug:**  
 An exception called "CloneNotSupportedException" is caught while trying to clone MessageDigest with algorithm SHA-512 on Liberty.

**Trace Log:**

[7/18/23 14:52:49:072 UTC] 0000003f id=00000000 cation.internal.cache.keyproviders.BasicAuthCacheKeyProvider 3 CloneNotSupportedException caught while trying to clone MessageDigest with algorithm SHA-512. This is pretty unlikely, and we need to get details about the JDK which is in use. 

               java.lang.CloneNotSupportedException

               at java.security.MessageDigest$Delegate.clone(MessageDigest.java:595)

               at com.ibm.ws.security.authentication.internal.cache.keyproviders.BasicAuthCacheKeyProvider.getMessageDigest(BasicAuthCacheKeyProvider.java:206)

**Steps to Reproduce**  
TBD

**Expected behavior**  
No exception should be logged as Liberty recovers by itself. There is no functional issue due to this.

**Diagnostic information:**  
 - Open Liberty Version: 22.0.0.9
 - Affected feature(s) : IBM JCEPlus provider
 - Java Version: 8.0.7.20

**Additional context**  
Related slack messages: https://ibm-cloud.slack.com/archives/C324NP6H5/p1689784419360069

**Comment by simysc** [comment]
Closing issue.
