### ISSUE TITLE
@Transactional may throw a checked exception which is not allowed according to the interceptor specification

### ISSUE THREAD

**Issue by jonasrutishauser** [OpenLiberty/open-liberty#26171]
**Describe the bug**  
If a method is annotated with `@Transactional(REQUIRES_NEW)` and there is an error during the commit a `javax.transaction.RollbackException` is thrown from the interceptor implementation. This exception is a checked exception and does not comply with the interceptor specification.
The interceptors specification says in section 2.5 the following:
> Interceptor methods are allowed to throw runtime exceptions or any checked exceptions that the associated target method or constructor allows within its throws clause.

As the annotated method normally doesn't declare the `RollbackException` in its throws clause the interceptor implementation should wrap this in a runtime exception (for example the `TransactionalException`).

An example stacktrace looks like the following:
```stacktrace
javax.transaction.RollbackException
  at com.ibm.tx.jta.impl.TransactionImpl.stage3CommitProcessing(TransactionImpl.java:1046)
  at com.ibm.tx.jta.impl.TransactionImpl.processCommit(TransactionImpl.java:844)
  at com.ibm.tx.jta.impl.TransactionImpl.commit(TransactionImpl.java:758)
  at com.ibm.tx.jta.impl.TranManagerImpl.commit(TranManagerImpl.java:155)
  at com.ibm.tx.jta.impl.TranManagerSet.commit(TranManagerSet.java:112)
  at com.ibm.ws.uow.embeddable.EmbeddableUOWManagerImpl.uowCommit(EmbeddableUOWManagerImpl.java:836)
  at com.ibm.ws.uow.embeddable.EmbeddableUOWManagerImpl.uowEnd(EmbeddableUOWManagerImpl.java:814)
  at com.ibm.ws.uow.embeddable.EmbeddableUOWManagerImpl.runUnderNewUOW(EmbeddableUOWManagerImpl.java:1045)
  at com.ibm.ws.uow.embeddable.EmbeddableUOWManagerImpl.runUnderUOW(EmbeddableUOWManagerImpl.java:1015)
  at com.ibm.tx.jta.cdi.interceptors.TransactionalInterceptor.runUnderUOWManagingEnablement(TransactionalInterceptor.java:176)
  at com.ibm.tx.jta.cdi.interceptors.RequiresNew.requiresNew(RequiresNew.java:44)
  at jdk.internal.reflect.GeneratedMethodAccessor265.invoke(Unknown Source)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  at org.jboss.weld.interceptor.reader.SimpleInterceptorInvocation$SimpleMethodInvocation.invoke(SimpleInterceptorInvocation.java:73)
  at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeAroundInvoke(InterceptorMethodHandler.java:84)
  at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeInterception(InterceptorMethodHandler.java:72)
  at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.invoke(InterceptorMethodHandler.java:56)
  at org.jboss.weld.bean.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(CombinedInterceptorAndDecoratorStackMethodHandler.java:79)
  at org.jboss.weld.bean.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(CombinedInterceptorAndDecoratorStackMethodHandler.java:68)
[...]
```

**Steps to Reproduce**  
Add a `@Transactional(REQUIRES_NEW)` annotation to a CDI method and have a transaction rollback.

**Expected behavior**  
I would expect that an exception extinding `RuntimeException` to be thrown like for example `TransactionalException`.

**Diagnostic information:**  
 - OpenLiberty Version: 23.0.0.7
 - Affected feature(s): JTA
 - Java Version: 17.0.8+7

**Additional context**

**Comment by jonhawkes** [comment]
Would be a problem for `@Transactional(REQUIRED)` too.
