### ISSUE TITLE
 No password callback supplied error for SOAP service with IBM liberty 22.0.0.9 or higher version but same is working fine with 22.0.0.6 version.

### ISSUE THREAD

**Issue by bandewarbalaji** [OpenLiberty/open-liberty#26198]
Describe the bug
I am facing No password callback supplied error for SOAP service with IBM liberty 22.0.0.9 or higher version but same is working fine with 22.0.0.6 version.
we have added below configuration

wsSecurityProvider ws-security.validate.token="false" set-jaxb-validation-event-handler="false" ws-security.is-bsp-compliant="false" inInterceptors="WSSInterceptor"
callerToken name="UsernameToken" mapToUserRegistry="User"
wsSecurityProvider

logs shows below error:

org.apache.cxf.binding.soap.SoapFault: No password callback supplied
at org.apache.cxf.binding.soap.SoapFault.createFault(SoapFault.java:258)
at org.apache.cxf.binding.soap.interceptor.Soap11FaultOutInterceptor$Soap11FaultOutInterceptorInternal.handleMessage(Soap11FaultOutInterceptor.java:73)
at org.apache.cxf.binding.soap.interceptor.Soap11FaultOutInterceptor$Soap11FaultOutInterceptorInternal.handleMessage(Soap11FaultOutInterceptor.java:63)
at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307)
at org.apache.cxf.interceptor.AbstractFaultChainInitiatorObserver.onMessage(AbstractFaultChainInitiatorObserver.java:112)
at org.apache.cxf.phase.PhaseInterceptorChain.wrapExceptionAsFault(PhaseInterceptorChain.java:373)
at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:331)
at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:127)
at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:277)
at com.ibm.ws.jaxws.endpoint.AbstractJaxWsWebEndpoint$1.run(AbstractJaxWsWebEndpoint.java:238)
at com.ibm.ws.jaxws.endpoint.AbstractJaxWsWebEndpoint$1.run(AbstractJaxWsWebEndpoint.java:235)
at java.security.AccessController.doPrivileged(Native Method)
at com.ibm.ws.jaxws.endpoint.AbstractJaxWsWebEndpoint.invoke(AbstractJaxWsWebEndpoint.java:235)
at com.ibm.ws.jaxws.webcontainer.LibertyJaxWsServlet.handleRequest(LibertyJaxWsServlet.java:136)
at com.ibm.ws.jaxws.webcontainer.LibertyJaxWsServlet.doPost(LibertyJaxWsServlet.java:95)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
at com.ibm.ws.jaxws.webcontainer.LibertyJaxWsServlet.service(LibertyJaxWsServlet.java:87)
at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1260)
at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:748)
at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:445)
at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1370)
at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:5080)
at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.handleRequest(DynamicVirtualHost.java:318)
at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:1038)
at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:283)
at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1248)
at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:470)
at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:429)
at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:569)
at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:503)
at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:363)
at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.ready(HttpInboundLink.java:330)
at com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.sendToDiscriminators(NewConnectionInitialReadCallback.java:169)
at com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.complete(NewConnectionInitialReadCallback.java:77)
at com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:516)
at com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueManager.java:586)
at com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:970)
at com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:1059)
at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:247)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.wss4j.common.ext.WSSecurityException: No password callback supplied
at org.apache.wss4j.dom.validate.UsernameTokenValidator.verifyDigestPassword(UsernameTokenValidator.java:143)
at org.apache.wss4j.dom.validate.UsernameTokenValidator.verifyPlaintextPassword(UsernameTokenValidator.java:130)
at org.apache.wss4j.dom.validate.UsernameTokenValidator.validate(UsernameTokenValidator.java:90)
at org.apache.wss4j.dom.processor.UsernameTokenProcessor.handleUsernameToken(UsernameTokenProcessor.java:174)
at org.apache.wss4j.dom.processor.UsernameTokenProcessor.handleToken(UsernameTokenProcessor.java:63)
at com.ibm.ws.wssecurity.cxf.interceptor.UsernameTokenInterceptor.validateToken(UsernameTokenInterceptor.java:113)
at org.apache.cxf.ws.security.wss4j.UsernameTokenInterceptor.processToken(UsernameTokenInterceptor.java:113)
at org.apache.cxf.ws.security.wss4j.AbstractTokenInterceptor.handleMessage(AbstractTokenInterceptor.java:108)
at org.apache.cxf.ws.security.wss4j.AbstractTokenInterceptor.handleMessage(AbstractTokenInterceptor.java:64)
at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307)

Steps to Reproduce
SOAP service which built on CXF API jar and use WSSecurity as mentioned below:

wsSecurityProvider ws-security.validate.token="false" set-jaxb-validation-event-handler="false" ws-security.is-bsp-compliant="false" inInterceptors="WSSInterceptor"
callerToken name="UsernameToken" mapToUserRegistry="User"
wsSecurityProvider

Expected behavior
IT should call soap service and respond, as it is working with 22.0.0.6 version.

Diagnostic information:

OpenLiberty Version: 22.0.0.9 or higher (till 23.0.0.6)
Affected feature(s)
Java Version:
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

server.xml configuration (WITHOUT sensitive information like passwords):
Describe the bug
I am facing No password callback supplied error for SOAP service with IBM liberty 22.0.0.9 or higher version but same is working fine with 22.0.0.6 version.
we have added below configuration

wsSecurityProvider ws-security.validate.token="false" set-jaxb-validation-event-handler="false" ws-security.is-bsp-compliant="false" inInterceptors="WSSInterceptor"
callerToken name="UsernameToken" mapToUserRegistry="User"
wsSecurityProvider

logs shows below error:

org.apache.cxf.binding.soap.SoapFault: No password callback supplied
at org.apache.cxf.binding.soap.SoapFault.createFault(SoapFault.java:258)
at org.apache.cxf.binding.soap.interceptor.Soap11FaultOutInterceptor$Soap11FaultOutInterceptorInternal.handleMessage(Soap11FaultOutInterceptor.java:73)
at org.apache.cxf.binding.soap.interceptor.Soap11FaultOutInterceptor$Soap11FaultOutInterceptorInternal.handleMessage(Soap11FaultOutInterceptor.java:63)
at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307)
at org.apache.cxf.interceptor.AbstractFaultChainInitiatorObserver.onMessage(AbstractFaultChainInitiatorObserver.java:112)
at org.apache.cxf.phase.PhaseInterceptorChain.wrapExceptionAsFault(PhaseInterceptorChain.java:373)
at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:331)
at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:127)
at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:277)
at com.ibm.ws.jaxws.endpoint.AbstractJaxWsWebEndpoint$1.run(AbstractJaxWsWebEndpoint.java:238)
at com.ibm.ws.jaxws.endpoint.AbstractJaxWsWebEndpoint$1.run(AbstractJaxWsWebEndpoint.java:235)
at java.security.AccessController.doPrivileged(Native Method)
at com.ibm.ws.jaxws.endpoint.AbstractJaxWsWebEndpoint.invoke(AbstractJaxWsWebEndpoint.java:235)
at com.ibm.ws.jaxws.webcontainer.LibertyJaxWsServlet.handleRequest(LibertyJaxWsServlet.java:136)
at com.ibm.ws.jaxws.webcontainer.LibertyJaxWsServlet.doPost(LibertyJaxWsServlet.java:95)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
at com.ibm.ws.jaxws.webcontainer.LibertyJaxWsServlet.service(LibertyJaxWsServlet.java:87)
at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1260)
at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:748)
at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:445)
at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1370)
at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:5080)
at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.handleRequest(DynamicVirtualHost.java:318)
at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:1038)
at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:283)
at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1248)
at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:470)
at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:429)
at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:569)
at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:503)
at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:363)
at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.ready(HttpInboundLink.java:330)
at com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.sendToDiscriminators(NewConnectionInitialReadCallback.java:169)
at com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.complete(NewConnectionInitialReadCallback.java:77)
at com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:516)
at com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueManager.java:586)
at com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:970)
at com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:1059)
at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:247)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.wss4j.common.ext.WSSecurityException: No password callback supplied
at org.apache.wss4j.dom.validate.UsernameTokenValidator.verifyDigestPassword(UsernameTokenValidator.java:143)
at org.apache.wss4j.dom.validate.UsernameTokenValidator.verifyPlaintextPassword(UsernameTokenValidator.java:130)
at org.apache.wss4j.dom.validate.UsernameTokenValidator.validate(UsernameTokenValidator.java:90)
at org.apache.wss4j.dom.processor.UsernameTokenProcessor.handleUsernameToken(UsernameTokenProcessor.java:174)
at org.apache.wss4j.dom.processor.UsernameTokenProcessor.handleToken(UsernameTokenProcessor.java:63)
at com.ibm.ws.wssecurity.cxf.interceptor.UsernameTokenInterceptor.validateToken(UsernameTokenInterceptor.java:113)
at org.apache.cxf.ws.security.wss4j.UsernameTokenInterceptor.processToken(UsernameTokenInterceptor.java:113)
at org.apache.cxf.ws.security.wss4j.AbstractTokenInterceptor.handleMessage(AbstractTokenInterceptor.java:108)
at org.apache.cxf.ws.security.wss4j.AbstractTokenInterceptor.handleMessage(AbstractTokenInterceptor.java:64)
at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307)

Steps to Reproduce
SOAP service which built on CXF API jar and use WSSecurity as mentioned below:

wsSecurityProvider ws-security.validate.token="false" set-jaxb-validation-event-handler="false" ws-security.is-bsp-compliant="false" inInterceptors="WSSInterceptor"
callerToken name="UsernameToken" mapToUserRegistry="User"
wsSecurityProvider

Expected behavior
IT should call soap service and respond, as it is working with 22.0.0.6 version.

Diagnostic information:

OpenLiberty Version: 22.0.0.9 or higher (till 23.0.0.6)
Affected feature(s)
Java Version:
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

server.xml configuration (WITHOUT sensitive information like passwords):

cdi-1.2
ejbLite-3.2
ejbRemote-3.2
el-3.0
jaxb-2.2
jaxws-2.2
jdbc-4.1
jndi-1.0
jsf-2.2
localConnector-1.0
mdb-3.2
requestTiming-1.0
servlet-3.1
wmqJmsClient-2.0
ldapRegistry-3.0
appSecurity-2.0
jpaContainer-2.1
wsSecurity-1.1
jaxrs-2.0
openidConnectClient-1.0
transportSecurity-1.0
<jndiEntry jndiName="ENVIRONMENT" value=""/>
<jndiEntry jndiName="INTERNAL_EXTERNAL" value=""/>
<jndiEntry jndiName="PA_REGION" value=""/>
<jndiEntry jndiName="OVERRIDING_DETAILED_CONFIG_FILES_LOC" value="${shared.config.dir}"/>
<jndiEntry jndiName="LDAP_URL" value=""/> 
<jndiEntry jndiName="LDAP_HOST" value=""/> 
<jndiEntry jndiName="LDAP_PORT" value=""/> 
<jndiEntry jndiName="LDAP_PROTO" value=""/> 
<jndiEntry jndiName="PA_USER" value=""/>
<jndiEntry jndiName="PA_PASSWORD" value=""/>

<variable name="defaultHostName" value="0.0.0.0"/>
<variable name="wmqJmsClient.rar.location" value=""/>

<webContainer deferServletLoad="false"/>

<keyStore password=""/>

<wsSecurityProvider ws-security.validate.token="false" set-jaxb-validation-event-handler="false" ws-security.is-bsp-compliant="false" inInterceptors="security.ws.cfx.interceptor.WSSInterceptor">
	<callerToken name="UsernameToken" mapToUserRegistry="User" />
</wsSecurityProvider>

<wmqJmsClient reconnectionRetryCount="5760" reconnectionRetryInterval="1500" startupRetryCount="999" startupRetryInterval="1s"/>

 
<logging traceSpecification="com.ibm.ws.jaxws.*=all:org.apache.cxf.*=all:WSSECURITY=all:WSS4J=all" traceFileName="trace.log" maxFileSize="100" maxFiles="20" /> 
<transaction totalTranLifetimeTimeout="6h" />

<jpa defaultPersistenceProvider="org.hibernate.jpa.HibernatePersistenceProvider"/>

<jdbcDriver id="OracleDriver" javax.sql.DataSource="oracle.jdbc.driver.OracleDriver" javax.sql.XADataSource="oracle.jdbc.xa.client.OracleXADataSource" libraryRef="OracleLib"/>
<dataSource id="DefaultDataSource" jdbcDriverRef="OracleDriver" jndiName="">
	<connectionManager maxPoolSize="10" minPoolSize="0"/>
	<properties.oracle TNSEntryName="" URL="" 
	password="" portNumber="" serverName="" user=""/>
</dataSource>

<httpEndpoint httpPort="8080" httpsPort="8443" id="defaultHttpEndpoint"/>
<applicationManager autoExpand="true"/>
<applicationMonitor updateTrigger="mbean"/>

<ssl id="defaultSSLConfig" trustDefaultCerts="true" />

<application id="epw" location=".ear" type="ear" name="epw">
	<classloader commonLibraryRef="global" />
	<application-bnd>
		<security-role name="BIEmployee">
		</security-role>
	</application-bnd>
</application>

**Comment by neuwerk** [comment]
Hi @bandewarbalaji, thank you so much for providing the updated info! I'm not 100% sure why this was working prior to moving to 22.0.0.9. I can tell you what's changed: in wsSecurity-1.1/jaxws-2.2 we upgraded CXF and it's related dependencies to 3.4.3 in 22.0.0.8. The implementation of WS-Security in CXF was completely rewritten, and the forked version we shipped prior to 22.0.0.8 was 2.6.2, which was probably similar enough to the version you were using with your application that this worked. That's no longer the case, so it's not surprising that its failing. It probably never should have worked though, because the environment had two conflicting versions of the implementaiton. 

I think this was conflict was avoided by one of the properties that you are setting in the `wsSecurity-1.1` `server.xml ` configuration: `inInterceptors="WSSInterceptor"`. By setting that to your own WS-Security interceptor, it essentially removes all of our internal JAX-WS/WS-Security interceptors from the `InterceptorChain`, circumventing our security integration. Providing your own implementation of CXF is totally fine, but you definitely do not want to use our wsSecurity-1.1 feature with your own JAX-WS implementation. If you want to use custom interceptors on Liberty, you should remove the jaxws-2.2 and wsSecurity-1.1 features and the related configuration from your `server.xml`

If you would like to use the `wsSecurity-1.1` feature, then I'd suggest dropping the additional properties you've added to the `wsSecurityProvider` configuration in your `server.xml`, at which point you will need to provide a callback handler. That can be implemented as outlined in this documentation: https://www.ibm.com/docs/en/was-liberty/nd?topic=level-developing-password-callback-handler-ws-security

**Comment by bandewarbalaji** [comment]
Thanks @neuwerk for your detailed explanation. could you please let me know what needs to be removed from server.xml apart form wsSecurity-1.1 &  jaxws-2.2 features. i would like to prefer use below configuration as is. 

wsSecurityProvider ws-security.validate.token="false" set-jaxb-validation-event-handler="false" ws-security.is-bsp-compliant="false" inInterceptors="security.ws.cfx.interceptor.WSSInterceptor"
    	callerToken name="UsernameToken" mapToUserRegistry="User"
   wsSecurityProvider

and i have tried to create new password call back handler as mentioned given link but somehow that was also not working. feature got installed while starting server but still i was getting No password callback supplied error. 

currently i am using  CXF 2.5.11 do you recommend to use CXF 3.4.3 or any other version? as far as vulnerabilities considered, 3.5.5 is stable version and good to use. please advise on the same.
