### ISSUE TITLE
Test Failure: com.ibm.ws.logging.fat.CustomAccessLogFieldsTest.testChangeJsonAccessLogFieldsConfigValue

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#26219]
RTC 295987

```
testChangeJsonAccessLogFieldsConfigValue:junit.framework.AssertionFailedError: 2023-05-17-11:37:47:440 TCP Channel defaultHttpEndpoint-ssl has not started (CWWKO0219I not found)
at com.ibm.ws.logging.fat.CustomAccessLogFieldsTest.waitForMetricsToStart(CustomAccessLogFieldsTest.java:819)
at com.ibm.ws.logging.fat.CustomAccessLogFieldsTest.testChangeJsonAccessLogFieldsConfigValue(CustomAccessLogFieldsTest.java:402)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:204)
at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:364)
at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:178)
```

**Comment by fmhwong** [comment]
Found a simple fix since this has failed many times.
