### ISSUE TITLE
Test Failure: com.ibm.ws.logstash.collector.tests.LogstashSSLTest.testLogstashForGCEvent

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#26290]
RTC 295641

```
testLogstashForGCEvent:junit.framework.AssertionFailedError: 2023-04-18-17:01:20:320 liberty_gc not found
at com.ibm.ws.logstash.collector.tests.LogstashSSLTest.testLogstashForGCEvent(LogstashSSLTest.java:228)
at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:204)
at org.testcontainers.containers.FailureDetectingExternalResource$1.evaluate(FailureDetectingExternalResource.java:29)
at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:364)
at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:178)
```

They all failed on IBM JDK 8 builds.

**Comment by Channyboy** [comment]
Closing as there are no recent builds.
