### ISSUE TITLE
potential deadlock with JSON logging at startup

### ISSUE THREAD

**Issue by donbourne** [OpenLiberty/open-liberty#2631]
Intermittently there is a deadlock that occurs when you set your logging configuration as follows in server.xml:

`<logging messageFormat="json" messageSource="message,trace"  traceSpecification="com.ibm.ws.*=all" />`
	
The deadlock seems to occur when the "The server server1 is ready to run a smarter planet." message is trying to be logged.
	
to recreate the problem:

Set server logging configuration as shown above.
Start the server.

About 50% of the time, on Oracle HotSpot JDK, the problem occurs.

Note that no deadlocks were detected using these configurations:

`<logging messageFormat="basic" messageSource="message,trace"  traceSpecification="com.ibm.ws.*=all" />`
`<logging messageFormat="basic" messageSource="message,trace" tracefilename="stdout" traceSpecification="com.ibm.somelogger.QuickLogTest=finest:com.ibm.ws.*=all" />`
	
lock pattern
	        
    In the javacore, I see a few of these...
    
        "Executor Service Control Timer" #22 daemon prio=5 os_prio=31 tid=0x00007fcb2582d000 nid=0x6003 waiting on condition [0x000070000dd89000]
           java.lang.Thread.State: WAITING (parking)
            at sun.misc.Unsafe.park(Native Method)
            - parking to wait for  <0x00000006c039ae60> (a java.util.concurrent.locks.ReentrantReadWriteLock$FairSync)
            at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
            at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
            at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireShared(AbstractQueuedSynchronizer.java:967)
            at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireShared(AbstractQueuedSynchronizer.java:1283)
            at java.util.concurrent.locks.ReentrantReadWriteLock$ReadLock.lock(ReentrantReadWriteLock.java:727)
            at com.ibm.ws.collector.manager.buffer.BufferManagerImpl.add(BufferManagerImpl.java:77)
            at com.ibm.ws.logging.source.TraceSource.publish(TraceSource.java:92)
            at com.ibm.ws.logging.internal.osgi.WsTraceRouterImpl.routeTo(WsTraceRouterImpl.java:151)
            at com.ibm.ws.logging.internal.osgi.WsTraceRouterImpl.routeToAll(WsTraceRouterImpl.java:135)
            at com.ibm.ws.logging.internal.osgi.WsTraceRouterImpl.route(WsTraceRouterImpl.java:117)
            at com.ibm.ws.logging.internal.impl.JsonTraceService.invokeTraceRouters(JsonTraceService.java:297)
            at com.ibm.ws.logging.internal.impl.JsonTraceService.publishTraceLogRecord(JsonTraceService.java:406)
            at com.ibm.ws.logging.internal.impl.BaseTraceService.entry(BaseTraceService.java:364)
            at com.ibm.websphere.ras.Tr.entry(Tr.java:464)
            at com.ibm.ws.threading.internal.IntervalTask.run(ThreadPoolController.java:1676)
            at java.util.TimerThread.mainLoop(Timer.java:555)
            at java.util.TimerThread.run(Timer.java:505)

    and one of these...
    
        "Default Executor-thread-1" #25 daemon prio=5 os_prio=31 tid=0x00007ffa28102000 nid=0x5f03 waiting on condition [0x000070000940c000]
           java.lang.Thread.State: WAITING (parking)
            at sun.misc.Unsafe.park(Native Method)
            - parking to wait for  <0x00000006c04ca808> (a java.util.concurrent.locks.ReentrantReadWriteLock$FairSync)
            at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
            at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
            at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:870)
            at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1199)
            at java.util.concurrent.locks.ReentrantReadWriteLock$WriteLock.lock(ReentrantReadWriteLock.java:943)
            at com.ibm.ws.collector.manager.buffer.BufferManagerImpl.removeEMQTrigger(BufferManagerImpl.java:239)
            at com.ibm.ws.logging.source.LogSource.publish(LogSource.java:118)
            at com.ibm.ws.logging.internal.osgi.WsMessageRouterImpl.routeTo(WsMessageRouterImpl.java:211)
            at com.ibm.ws.logging.internal.osgi.WsMessageRouterImpl.routeToAll(WsMessageRouterImpl.java:194)
            at com.ibm.ws.logging.internal.osgi.WsMessageRouterImpl.route(WsMessageRouterImpl.java:161)
            at com.ibm.ws.logging.internal.impl.JsonTraceService.invokeMessageRouters(JsonTraceService.java:253)
            at com.ibm.ws.logging.internal.impl.JsonTraceService.publishLogRecord(JsonTraceService.java:343)
            at com.ibm.ws.logging.internal.impl.BaseTraceService.audit(BaseTraceService.java:313)
            at com.ibm.websphere.ras.Tr.audit(Tr.java:365)
            at com.ibm.ws.kernel.feature.internal.FeatureManager.writeFeatureChangeMessages(FeatureManager.java:899)
            at com.ibm.ws.kernel.feature.internal.FeatureManager.processFeatureChanges(FeatureManager.java:805)
            at com.ibm.ws.kernel.feature.internal.FeatureManager$1.run(FeatureManager.java:588)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
            at java.lang.Thread.run(Thread.java:748)

suggested fix

    - get rid of the RERWLOCK in BufferManagerImpl.add 
    - replace it with checkandset style concurrency

**Comment by donbourne** [comment]
possible solution...(storing here for safe keeping even though we're not planning to use this approach for now):

```
BufferManagerImpl
    addSyncHandler(syncHandler)
        create HandlerAdapter(SyncHandler)
        add handlerAdapter to list of active syncHandlers  // must do this BEFORE copying emq and init
        sync
            copy emq to emqCopy
        call handlerAdapter.init(emqCopy)

    add(event)
        add event to emq                                   // must be before delivery to handlers
        call SyncHandlerAdapter.add(event)
        add event to ringBuffer

HandlerAdapter(SyncHandler)
    ctor
        initialized = false;

    init(events)
        isInitingTL = true;                                // avoid self-deadlock during init
        loop through events and process them
        initialized = true;

    add(event, eventNumber)
        if (isInitingTL == true) return;                   // avoid self-deadlock during init
        wait while initialized == false;
        process event if eventNumber > lastProcessedEventDuringInit

this ensures calls to BufferManagerImpl.add are properly handled regarless of when handlers are added relative to when events arrive

    add
                    //1 - event will be received 1x by handlers
        emq
                    //2 - event will be received 2x by handlers - HandlerAdapter will filter out 2nd one
        syncH
                    //3 - event will be received 1x by synchandlers, 2x by ringB - HandlerAdapter will filter out 2nd one
        ringB
                    //4 - event will be received 1x by handlers

```

**Comment by Channyboy** [comment]
With the current solution, the synchronized block in `add()` (called by Thread 1) can theoretically cause a deadlock with the the synchronized methods `addSyncHandler()` ( called by Thread 2 ) if the synchronous handler that is being added uses an object for writing out that is synchronized and can be held by Thread 1.

An example to illustrate this scenario would be when the `synchronousWriter` is the `MessageLogHandler`. It should be noted that this "dead-lock" scenario does not happen.
This will be explained later on. For the purpose of the example we will exclude vital information that prevents this dead-lock.

The `MessageLogHandler` uses the `FileLogHolder` class which holds static synchronized methods for writing (i.e. `writeRecord()`) and updating the writer's configuration (i.e. `update()`).

The dead lock occurs as illustrated below:

Thread 1:     `FileLogHolder.update()` **[FLH Lock]**  ---[Trace event]--> `BufferManagerImpl.add()` **[can not obtain BMI lock]**
Thread 2:     `BufferMangerImpl.addSyncHandler()` **{BMI lock]** ---> `MessageLogHandler.synchronousWrite()` ---->`FileLogHolder.writeRecord();` **[can not obtain FLH lock]**

In practice, this does not happen because FileLogholder.update() occurs from a call by `BaseTraceService.initializeWriters()` which is called by `BasetraceService.update()`.
The `addSynchronousHandler` and `removeSynchronousHandler` for `MessageLogHandler` and `ConsoleLogHandler` also occur in `BaseTraceService.update()` _after_ `BaseTraceService.initializeWriters()`.
Therefore it is a sequential call on the same thread and the dead-lock will not occur.
