### ISSUE TITLE
Thin utility for SpringBoot 3 feature install causes NoClassDef

### ISSUE THREAD

**Issue by cbridgha** [OpenLiberty/open-liberty#26357]
**Describe the bug**  
When SpringBoot 3 feature is installed from a smaller package like kernel..  Its possible a jar used by the thin utility (ws-springbootutil.jar) won't be present, and will result in a NoClassDef exception thrown.

```
java.lang.NoClassDefFoundError: com/ibm/ws/app/manager/springboot/util/SpringBootThinUtil
	at com.ibm.ws.springboot.utility.tasks.ThinAppTask.performThinTask(ThinAppTask.java:151)
	at com.ibm.ws.springboot.utility.tasks.ThinAppTask.handleTask(ThinAppTask.java:137)
	at com.ibm.ws.springboot.utility.SpringBootUtility.runProgram(SpringBootUtility.java:127)
	at com.ibm.ws.springboot.utility.SpringBootUtility.main(SpringBootUtility.java:157)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.ibm.ws.kernel.boot.cmdline.UtilityMain.internal_main(UtilityMain.java:175)
	at com.ibm.ws.kernel.boot.cmdline.UtilityMain.main(UtilityMain.java:55)
	at com.ibm.ws.kernel.boot.cmdline.Main.main(Main.java:54)
Caused by: java.lang.ClassNotFoundException: com.ibm.ws.app.manager.springboot.util.SpringBootThinUtil
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
	at com.ibm.ws.kernel.boot.cmdline.PackageDelegateClassLoader.loadClass(PackageDelegateClassLoader.java:57)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 11 more
```

**Steps to Reproduce**  
start with a smaller open liberty zip like openliberty-kernel-23.0.0.9.zip. Add the "springBoot-3.0" feature via the featureUtility command

**Expected behavior**  
springbootutil.jar should run as expected with no issues

**Diagnostic information:**  
 - OpenLiberty Version: [23.0.0.9]
 - Affected feature(s) [springBoot-3.0]

**Comment by cbridgha** [comment]
Issue caused by:  dependent jar listed in the utility MANIFEST.MF is missing because the jar name changes depending on which version of the feature installed, it is either compiled for JavaEE or JakartaEE api's.

**Comment by cbridgha** [comment]
Fixes #PH57263
