### ISSUE TITLE
If Liberty server is started then add heritagenPIs-1.1 feature, start Liberty it will reports ：java.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by youngjane99** [OpenLiberty/open-liberty#26573]
**Describe the bug**  
This is an issue discussed here:
https://ibm-cloud.slack.com/archives/C30NGTBFS/p1695107704879449

**Steps to Reproduce**  

After create liberty server, start it, then add new feature heritagenPIs-1.1 to configure work manager:
<feature>heritagenPIs-1.1</feature>
<feature>concurrent-1.0</feature>
<managedExecutorService id="MulticastwM" indiName="wm/MulticastWM" contextserviceRef="DefaultContextService"><concurrencyPolicy max=n100n min="5"/>
</managedexecutorService>

Then start the Liberty server again, it reports:

com.ibm.websphere.rsadapter.Oracle11gDataStoreHelper：java.lang.ClassNotFoundException: com.ibm.websphere.rsadapter.Oracle11gDataStoreHelper
	at [com.ibm.ws](http://com.ibm.ws/).classloading.internal.AppClassLoader.findClassCommonLibraryClassLoaders(AppClassLoader.java:736)
	at [com.ibm.ws](http://com.ibm.ws/).classloading.internal.AppClassLoader.findClass(AppClassLoader.java:321)
	at [com.ibm.ws](http://com.ibm.ws/).classloading.internal.AppClassLoader.findOrDelegateLoadClass(AppClassLoader.java:708)
	at [com.ibm.ws](http://com.ibm.ws/).classloading.internal.AppClassLoader.loadClass(AppClassLoader.java:580)
	at [com.ibm.ws](http://com.ibm.ws/).classloading.internal.AppClassLoader.loadClass(AppClassLoader.java:547)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1094)
	at [com.ibm.ws](http://com.ibm.ws/).rsadapter.impl.DatabaseHelper.lambda$createDataStoreHelper$0(DatabaseHelper.java:262)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:748)
	at [com.ibm.ws](http://com.ibm.ws/).rsadapter.impl.DatabaseHelper.createDataStoreHelper(DatabaseHelper.java:261)
	at [com.ibm.ws](http://com.ibm.ws/).rsadapter.impl.WSManagedConnectionFactoryImpl.<init>(WSManagedConnectionFactoryImpl.java:354)
	at [com.ibm.ws](http://com.ibm.ws/).jdbc.DataSourceService.init(DataSourceService.java:678)
	at [com.ibm.ws.jca.cm](http://com.ibm.ws.jca.cm/).AbstractConnectionFactoryService$2.run(AbstractConnectionFactoryService.java:524)
	at [com.ibm.ws.jca.cm](http://com.ibm.ws.jca.cm/).AbstractConnectionFactoryService$2.run(AbstractConnectionFactoryService.java:521)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:748)
	at [com.ibm.ws.jca.cm](http://com.ibm.ws.jca.cm/).AbstractConnectionFactoryService.initPrivileged(AbstractConnectionFactoryService.java:521)
	at [com.ibm.ws.jca.cm](http://com.ibm.ws.jca.cm/).AbstractConnectionFactoryService.createResource(AbstractConnectionFactoryService.java:151)
	at [com.ibm.ws](http://com.ibm.ws/).resource.internal.ResourceFactoryTrackerData$1.getService(ResourceFactoryTrackerData.java:122)
	at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse$1.run(ServiceFactoryUse.java:218)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:692)
	at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.factoryGetService(ServiceFactoryUse.java:215)
	at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.getService(ServiceFactoryUse.java:114)
	at org.eclipse.osgi.internal.serviceregistry.ServiceConsumer$2.getService(ServiceConsumer.java:48)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.getService(ServiceRegistrationImpl.java:568)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.getService(ServiceRegistry.java:542)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.getService(BundleContextImpl.java:660)
	at [com.ibm.ws](http://com.ibm.ws/).jndi.internal.WSContextFactory.lambda$getService$0(WSContextFactory.java:83)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:692)
	at [com.ibm.ws](http://com.ibm.ws/).jndi.internal.WSContextFactory.lambda$getService$1(WSContextFactory.java:83)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1713)
	at [com.ibm.ws](http://com.ibm.ws/).jndi.internal.WSContextFactory.getService(WSContextFactory.java:83)
	at [com.ibm.ws](http://com.ibm.ws/).jndi.internal.WSContext.getReference(WSContext.java:522)
	at [com.ibm.ws](http://com.ibm.ws/).jndi.internal.WSContext.resolveObject(WSContext.java:141)
	at [com.ibm.ws](http://com.ibm.ws/).jndi.internal.WSContext.lookup(WSContext.java:311)
	at [com.ibm.ws](http://com.ibm.ws/).jndi.WSContextBase.lookup(WSContextBase.java:63)
	at org.apache.aries.jndi.DelegateContext.lookup(DelegateContext.java:149)
	at java.naming/javax.naming.InitialContext.lookup(InitialContext.java:409)

To fix the issue, need to start Liberty server with clean option.
server start demo --clean

If create Liberty server, add the features without start Liberty and then start LIberty server first time, there is no such issue.

**Expected behavior**  
Expect to avoid the issue by Liberty directly:
After add any feature, if need to start the Liberty with clean, hope it can be done by Liberty process directly without client's action.

Or at least, modify/add document to clearly tell client after add the feature, client need to add clean option when start Liberty server.

**Diagnostic information:**  
 - OpenLiberty Version: Till latest Liberty version 23.0.0.9
 - Affected feature(s) heritageAPIs-1.1
 - Java Version: Not relate to Java version.
 - server.xml configuration (WITHOUT sensitive information like passwords)
 

<server description="master">
   <featureManager>
    <feature>localConnector-1.0</feature>
    <feature>servlet-3.1</feature>
    <feature>el-3.0</feature>
    <feature>jaxrs-2.0</feature>
    <feature>jndi-1.0</feature>
    <feature>ssl-1.0</feature>
    <feature>jsf-2.2</feature>
    <feature>jdbc-4.0</feature>
    <feature>ejbLite-3.2</feature>
    <feature>beanValidation-1.1</feature>
    <feature>monitor-1.0</feature>
    <feature>heritageAPIs-1.1</feature>
    <feature>concurrent-1.0</feature>
  </featureManager>
   <httpEndpoint host="*" httpPort="8888" httpsPort="-1" id="defaultHttpEndpoint"/>
   <applicationManager autoExpand="true"/>
   <variable name="NC_HOME" value="/data/yonbip_home"/>
  <include location="sharelib.xml"/>
  <transaction totalTranLifetimeTimeout="600s">
</transaction>
   <library id="devlib">
    <file name="/data/wlp/dev/api/spec/com.ibm.websphere.javaee.connector.1.6_1.0.78.jar"/>
  </library>
   <library id="oracleLib">
    <file name="${NC_HOME}/lib/ojdbc6.jar"/>
    <fileset dir="${NC_HOME}/lib" includes="orai18n-*.jar"/>
  </library>
  <dataSource id="liberty_0915" jndiName="liberty_0915">
    <jdbcDriver libraryRef="oracleLib"/>
    <properties.oracle URL="jdbc:oracle:thin:@10.10.3.217:1521/ora19c" user="liberty" password="1"/>
    <connectionManager minPoolSize="10" maxPoolSize="50"/>
  </dataSource>
    <managedExecutorService id="MulticastWM" jndiName="wm/WM" contextServiceRef="DefaultContextService">
    <concurrencyPolicy max="100" min="5"/>
  </managedExecutorService>
</server>

**Comment by NottyCode** [comment]
Open Liberty does not have a `heritageAPIs-1.1` feature. WebSphere Liberty (a product that consumes Open Liberty does). Any issues with WebSphere Liberty should be via the vendors [support system](https://www.ibm.com/mysupport/s/) and not this open source project.
