### ISSUE TITLE
InstantOn: tranlog prevents CRIU snapshot

### ISSUE THREAD

**Issue by bmarwell** [OpenLiberty/open-liberty#26623]
**Describe the bug**  

I have a toy/showcase repository over here: https://github.com/bmarwell/social-metricbot/
The idea is to try out new technologies. Please find my InstantOn configuration in this commit: https://github.com/bmarwell/social-metricbot/tree/09eaf4007ec67ae7c05dc2c7342e63920f846dc6

However, running `configure.sh` won't allow me to use `--env WLP_CHECKPOINT=afterAppStart` afterwards.
H2 and Open Liberty seem to leave some transaction logs around, which will hinder the CRIU snapshot:

```
[AUDIT   ] CWWKC0451I: A server checkpoint "afterAppStart" was requested. When the checkpoint completes, the server stops.
[ERROR   ] CWWKC0453E: The server checkpoint request failed with the following message: Could not dump the JVM processes, err=-52
[AUDIT   ] CWWKZ0001I: Application social-metricbot-app-1.0.0-SNAPSHOT started in 2.318 seconds.
[AUDIT   ] CWWKE0084I: The server defaultServer is stopping because thread Checkpoint failed, exiting... (0000005a) called the method java.lang.System.exit: 
        at java.base/java.lang.System.exit(System.java:517)
        at io.openliberty.checkpoint.internal.CheckpointImpl.lambda$checkpointOrExitOnFailure$6(CheckpointImpl.java:334)
        at java.base/java.lang.Thread.run(Thread.java:857)

[AUDIT   ] CWWKE1100I: Waiting for up to 30 seconds for the server to quiesce.
[AUDIT   ] CWWKF0012I: The server installed the following features: [cdi-4.0, concurrent-3.0, jdbc-4.2, jndi-1.0, jsonb-3.0, jsonp-2.1, mpConfig-3.0, persistence-3.1, persistenceContainer-3.1, restfulWS-3.1, restfulWSClient-3.1, servlet-6.0].
[AUDIT   ] CWWKF0011I: The defaultServer server is ready to run a smarter planet. The defaultServer server started in 2.325 seconds.
CWWKE0962E: The server checkpoint request failed. The following output is from the CRIU /logs/checkpoint/checkpoint.log file that contains details on why the checkpoint failed.
Warn  (criu/kerndat.c:1103): $XDG_RUNTIME_DIR not set. Cannot find location for kerndat file
Warn  (criu/kerndat.c:1103): $XDG_RUNTIME_DIR not set. Cannot find location for kerndat file
Warn  (compel/src/lib/infect.c:133): Unable to interrupt task: 1114 (Operation not permitted)
Error (criu/files-reg.c:1146): Can't create link remap for /opt/ol/wlp/output/defaultServer/tranlog/partnerlog/log2. Use link-remap option.
Error (criu/cr-dump.c:1558): Collect mappings (pid: 1028) failed with -1
Error (criu/cr-dump.c:2093): Dumping FAILED.
```

**Steps to Reproduce**  

* Use above repository at selected commit (main might have advanced already)
* use `mvn verify -Pdockerize` to create an image `io.github.bmarwell.social.metricbot/social-metricbot-app-ol-docker:latest` (and 1.0.0-SNAPSHOT)
* run `docker rm social-metricbot || true; docker run --name social-metricbot --privileged --env WLP_CHECKPOINT=afterAppStart io.github.bmarwell.social.metricbot/social-metricbot-app-ol-docker:latest`

The snapshot fails with above error message.

**Expected behavior**  

Snapshot works as expected and can be seen in Thomas' blog posts about InstantOn (thanks, they are SUPER helpful! :) - Please keep them up and coming! )

**Diagnostic information:**  

See Dockerfile: https://github.com/bmarwell/social-metricbot/blob/09eaf4007ec67ae7c05dc2c7342e63920f846dc6/app/openliberty/docker/Dockerfile

See config: https://github.com/bmarwell/social-metricbot/tree/09eaf4007ec67ae7c05dc2c7342e63920f846dc6/app/openliberty/docker/src/main/docker/config

 - OpenLiberty Version: Open Liberty 23.0.0.9
 - Affected feature(s): datasource (jpa)
 - Java Version: See your docker image
 - server.xml configuration:

```
  <library
    id="H2JDBCLib"
  >
    <fileset
      dir="${server.config.dir}/h2"
      includes="*.jar"
    />
  </library>
  <jdbcDriver
    id="h2driver"
    libraryRef="H2JDBCLib"
    javax.sql.DataSource="org.h2.jdbcx.JdbcDataSource"
    javax.sql.XADataSource="org.h2.jdbcx.JdbcDataSource"
    javax.sql.ConnectionPoolDataSource="org.h2.jdbcx.JdbcDataSource"
  />

  <variable
      name="datasource_url"
      defaultValue="jdbc:h2:mem:metricbotdb"
  />

  <dataSource
    jndiName="jdbc/metricbotjpadatasource"
    jdbcDriverRef="h2driver">
    <properties
        URL="${datasource_url};DB_CLOSE_ON_EXIT=FALSE"
    />
  </dataSource>
```

**Additional context**

Workaround: 
At the end of the Dockerfile, remove the `tranlog` directories (which should not be touched according to the docs).
Thanks again Thomas for the workaround! 👍🏻

**Comment by tjwatson** [comment]
I believe this is fixed by PR #26262.  When I try with the latest nightly build I no longer need to remove the tranlog directory to get the checkpoint to work:

- `git clone git@github.com:OpenLiberty/ci.docker.git`
- `cd ci.docker/releases/latest/full/resources/`
- Find the latest development/nightly build from https://openliberty.io/start/#development_builds
- Download the all zip to the `full/resources/wlp.zip` location you cd'ed into above, for example: `wget -O wlp.zip https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/nightly/2023-10-17_0103/openliberty-all-23.0.0.11-cl231120231017-0103.zip`
- Get the sha1sum of the wlp.zip, for example: `sha1sum wlp.zip`
- `cd ..` to get back to the `full/` folder
- build by passing in the `LIBERTY_SHA` calculated from the `sha1sum` above and build like: `docker build -t icr.io/appcafe/open-liberty:full-java17-openj9-ubi --build-arg LIBERTY_SHA=7f8f9959116db92a5a410e74371830a957309e00 -f Dockerfile.ubi.openjdk17 .`
- You will then need to update your `FROM` to point to  `icr.io/appcafe/open-liberty:full-java17-openj9-ubi` and remove the call to `features.sh`

**Comment by vijaysun-omr** [comment]
@bmarwell just checking back with you on any InstantOn requirements that you may have. Is it something that you are using or planning to use ? I noticed that this specific issue was closed today, and thought I'd check back with you about the feature in general.

**Comment by bmarwell** [comment]
@tjwatson said it was fixed a while ago, and while I don't remember testing it myself, that should be good enough. But if I'm not mistaken, I haven't encountered this problem anymore.
