### ISSUE TITLE
Problem: Invoke remote ejb from another openliberty server(servlet client) 

### ISSUE THREAD

**Issue by AngeloRubens** [OpenLiberty/open-liberty#26634]
**Describe the bug**  
Hi All,

i can try to invoke the remote ejb from a openliberty vs another openliberty instance, but i receive this error:
if i execute this lookup inside a openliberty instance with ejb app it's ok.
 Object context =   new InitialContext().lookup("corbaname::localhost:2089/NameService#ejb/hello-world/hello-world-ejb.jar/HelloWorldBean#helloworld.HelloWorldRemote");

but when execute inside servlet from another openliberty istance i receive this error:

 Object context =   new InitialContext().lookup("corbaname::localhost:2089/NameService#ejb/hello-world/hello-world-ejb.jar/HelloWorldBean#helloworld.HelloWorldRemote");
            

Stacktrace:
lookupRemoteBean: JNDI = corbaname::localhost:2089/NameService#ejb/global/hello-world/hello-world-ejb.jar/HelloWorldBean!helloworld.HelloWorldRemote, interface = helloworld.HelloWorldRemote
[17/10/23, 18:12:54:671 CEST] 000000db SystemErr                                                    R org.omg.CORBA.BAD_PARAM: other: corbaname evaluation error:an unknown user exception was raised: IDL:omg.org/CosNaming/NamingContext/NotFound:1.0:  vmcid: OMG minor code: 0xa  completed: No
[17/10/23, 18:12:54:671 CEST] 000000db SystemErr                                                    R 	at org.apache.yoko.orb.OB.CorbanameURLScheme_impl.parse_url(CorbanameURLScheme_impl.java:228)
[17/10/23, 18:12:54:672 CEST] 000000db SystemErr                                                    R 	at org.apache.yoko.orb.OB.URLRegistry_impl.parse_url(URLRegistry_impl.java:69)
[17/10/23, 18:12:54:672 CEST] 000000db SystemErr                                                    R 	at org.apache.yoko.orb.OB.ObjectFactory.stringToObject(ObjectFactory.java:78)
[17/10/23, 18:12:54:672 CEST] 000000db SystemErr                                                    R 	at org.apache.yoko.orb.OBCORBA.ORB_impl.string_to_object(ORB_impl.java:1035)
[17/10/23, 18:12:54:672 CEST] 000000db SystemErr                                                    R 	at com.ibm.ws.jndi.iiop.OrbContext.lookup(OrbContext.java:55)
[17/10/23, 18:12:54:672 CEST] 000000db SystemErr                                                    R 	at org.apache.aries.jndi.DelegateContext.lookup(DelegateContext.java:149)
[17/10/23, 18:12:54:672 CEST] 000000db SystemErr                                                    R 	at java.naming/javax.naming.InitialContext.lookup(InitialContext.java:409)

**Diagnostic information:**  
 - OpenLiberty Version: [23.0.0.9]
 - Affected feature(s) [enterpriseBeansRemote-4.0]
 - Java Version: [openjdk version "11.0.20.1" 2023-08-24]
 - server.xml client side:
<featureManager>
        <feature>servlet-6.0</feature>
        <feature>adminCenter-1.0</feature>
         <feature>enterpriseBeansRemote-4.0</feature>
    </featureManager>
    
       <basicRegistry id="basic">
      <user name="admin" password="adminpwd" />
      <user name="reader" password="readerpwd" />
   </basicRegistry>
   
   <administrator-role>
      <user>admin</user>
   </administrator-role>
   
   <reader-role>
      <user>reader</user>
   </reader-role>
   

    
    <httpEndpoint id="defaultHttpEndpoint"
                  httpPort="9080"
                  httpsPort="9443" />

    
    <applicationManager autoExpand="true"/>

     
    <ssl id="defaultSSLConfig" trustDefaultCerts="true" />
    
    <iiopEndpoint id="defaultIiopEndpoint" iiopPort="2189">
        <iiopsOptions  iiopsPort="2190" sslRef="defaultSSLConfig"/>
    </iiopEndpoint>

    	
    <javaPermission codebase="${server.config.dir}/lib/global/com.ibm.ws.ejbcontainer.fat_tools.jar" className="java.net.SocketPermission" name="*" actions="listen,connect,resolve"/>
    <javaPermission codebase="${server.config.dir}/lib/global/com.ibm.ws.ejbcontainer.fat_tools.jar" className="java.lang.RuntimePermission" name="getClassLoader"/>
    <javaPermission codebase="${server.config.dir}/lib/global/com.ibm.ws.ejbcontainer.fat_tools.jar" className="java.util.PropertyPermission" name="*" actions="read,write"/>
    <javaPermission codebase="${server.config.dir}/lib/global/io.openliberty.ejbcontainer.jakarta.fat_tools.jar" className="java.net.SocketPermission" name="*" actions="listen,connect,resolve"/>
    <javaPermission codebase="${server.config.dir}/lib/global/io.openliberty.ejbcontainer.jakarta.fat_tools.jar" className="java.lang.RuntimePermission" name="getClassLoader"/>
    <javaPermission codebase="${server.config.dir}/lib/global/io.openliberty.ejbcontainer.jakarta.fat_tools.jar" className="java.util.PropertyPermission" name="*" actions="read,write"/>

**Comment by joe-chacko** [comment]
So in the passing case the client code is running in the same Liberty server instance as the EJB that it is accessing?
In the failing case, the client code is running in a separate Liberty server instance, right?

Are they running in containers? VMs? Since you are using localhost as the host name, the two instances **must** be on the same physicial and logical hosts (be that VM, container, or real machine).

The failure you are seeing is a legitimate NameNotFound, meaning that the separate Liberty server acting as IIOP client is contacting a name server that simply does not have that EJB registered on it. Depending on your configuration and topology this could be the same Liberty server instance.

You have not shown the full config for both your Liberty instances, but I see you are looking up the EJB on a non-standard port, 2089. Where is that configured? Also, why are you using that port in particular? I recall that due to a historic typo it was the default port for another ORB but it has never been the default in Liberty.

**Comment by jhanders34** [comment]
Just to clarify the statement about port 2089 not being default.  The default as defined by CORBA is 2809 which is very similar.  So if you are relying on the default by not configuring the port, you will need to update your client lookup to be 2809 instead of 2089.

**Comment by AngeloRubens** [comment]
Hi, i execute two instance of openliberty(different bind port for iiop and http linstener) in same host machine(no docker or podman container) in the server side the iiop port is 2089 by configuration and this is log on startup:

[19/10/23, 18:18:18:498 CEST] 0000001a com.ibm.ws.transport.iiop.internal.ORBWrapperInternal        A CWWKI0001I: Il server dei nomi CORBA è ora disponibile in corbaloc:iiop:localhost:2089/NameService.

[19/10/23, 18:18:19:546 CEST] 00000026 com.ibm.ws.ejbcontainer.osgi.internal.NameSpaceBinderImpl    I CNTR0167I: Il server sta eseguendo il bind dell'interfaccia helloworld.HelloWorldRemote del bean enterprise HelloWorldBean nel modulo hello-world-ejb.jar dell'applicazione hello-world.  L'ubicazione del bind è: ejb/hello-world/hello-world-ejb.jar/HelloWorldBean#helloworld.HelloWorldRemote

I try with this url on client side: 

Context context =   (Context) new InitialContext().lookup("corbaloc:iiop:localhost:2089/NameService");
            final Object lookup = context.lookup("ejb/hello-world/hello-world-ejb.jar/HelloWorldBean#helloworld.HelloWorldRemote");
         

and this is a stacktrace:

[19/10/23, 18:38:51:102 CEST] 00000039 SystemErr                                                    R javax.naming.NameNotFoundException [Root exception is org.omg.CosNaming.NamingContextPackage.NotFound: IDL:omg.org/CosNaming/NamingContext/NotFound:1.0]; remaining name 'hello-world'
[19/10/23, 18:38:51:103 CEST] 00000039 SystemErr                                                    R 	at com.ibm.ws.jndi.iiop.JndiCosNamingContext.lookup(JndiCosNamingContext.java:146)
[19/10/23, 18:38:51:104 CEST] 00000039 SystemErr                                                    R 	at com.ibm.ws.jndi.WSContextBase.lookup(WSContextBase.java:63)
[19/10/23, 18:38:51:105 CEST] 00000039 SystemErr                                                    R 	at com.mycompany.mavenproject6.NewServlet.doGet(NewServlet.java:38)



<server description="new server">

   
    <featureManager>
    <feature>servlet-6.0</feature>
        <feature>adminCenter-1.0</feature>
        <feature>enterpriseBeansRemote-4.0</feature>
    </featureManager>
    
     
  

    
    <httpEndpoint id="defaultHttpEndpoint"
                  httpPort="9081"
                  httpsPort="9444" />

    
    <applicationManager autoExpand="true"/>
    
    <iiopEndpoint id="defaultIiopEndpoint" iiopPort="2089">
        <iiopsOptions  iiopsPort="2090" sslRef="defaultSSLConfig"/>
    </iiopEndpoint>
    

    	
    <javaPermission codebase="${server.config.dir}/lib/global/com.ibm.ws.ejbcontainer.fat_tools.jar" className="java.net.SocketPermission" name="*" actions="listen,connect,resolve"/>
    <javaPermission codebase="${server.config.dir}/lib/global/com.ibm.ws.ejbcontainer.fat_tools.jar" className="java.lang.RuntimePermission" name="getClassLoader"/>
    <javaPermission codebase="${server.config.dir}/lib/global/com.ibm.ws.ejbcontainer.fat_tools.jar" className="java.util.PropertyPermission" name="*" actions="read,write"/>
    <javaPermission codebase="${server.config.dir}/lib/global/io.openliberty.ejbcontainer.jakarta.fat_tools.jar" className="java.net.SocketPermission" name="*" actions="listen,connect,resolve"/>
    <javaPermission codebase="${server.config.dir}/lib/global/io.openliberty.ejbcontainer.jakarta.fat_tools.jar" className="java.lang.RuntimePermission" name="getClassLoader"/>
    <javaPermission codebase="${server.config.dir}/lib/global/io.openliberty.ejbcontainer.jakarta.fat_tools.jar" className="java.util.PropertyPermission" name="*" actions="read,write"/>
    <javaPermission className="java.net.SocketPermission" name="*" actions="listen,connect,resolve"/>
    <javaPermission className="java.lang.RuntimePermission" name="getClassLoader"/>
    <javaPermission className="java.util.PropertyPermission" name="*" actions="read,write"/>


     
    <ssl id="defaultSSLConfig" trustDefaultCerts="true" />

**Comment by AngeloRubens** [comment]
Hi All, i found the tips and tricks....so....

the server bind ejb on nameservice with this 3 names:

[19/10/23, 18:18:19:546 CEST] 00000026 com.ibm.ws.ejbcontainer.osgi.internal.NameSpaceBinderImpl    I CNTR0167I:  ejb/hello-world/hello-world-ejb.jar/HelloWorldBean#helloworld.HelloWorldRemote
[19/10/23, 18:18:19:573 CEST] 00000026 com.ibm.ws.ejbcontainer.osgi.internal.NameSpaceBinderImpl    I CNTR0167I: helloworld.HelloWorldRemote
[19/10/23, 18:18:19:574 CEST] 00000026 com.ibm.ws.ejbcontainer.runtime.AbstractEJBRuntime           I CNTR0167I: java:global/hello-world/hello-world-ejb/HelloWorldBean!helloworld.HelloWorldRemote

on client side the correct steps and urls for lookup is:
from on the server side binding translate from **java:global**/hello-world/hello-world-ejb/HelloWorldBean!helloworld.HelloWorldRemote to 
**ejb/global**/hello-world/hello-world-ejb/HelloWorldBean!helloworld.HelloWorldRemote

replace java: in ejb/ 

Context context =   (Context) new InitialContext().lookup("corbaloc:iiop:localhost:2089/NameService");
Object obj=context.lookup("ejb/global/hello-world/hello-world-ejb/HelloWorldBean!helloworld.HelloWorldRemote");

At this time, can i propose a simple guide in openliberty site for this sample step? i can produce a simple guide for this sample, What do you think?

Thanks all....

**Comment by AngeloRubens** [comment]
on client side the correct steps and urls for lookup is:
from on the server side binding translate from **java:global**/hello-world/hello-world-ejb/HelloWorldBean!helloworld.HelloWorldRemote to 
**ejb/global**/hello-world/hello-world-ejb/HelloWorldBean!helloworld.HelloWorldRemote

replace java: in ejb/ 

Context context =   (Context) new InitialContext().lookup("corbaloc:iiop:localhost:2089/NameService");
Object obj=context.lookup("ejb/global/hello-world/hello-world-ejb/HelloWorldBean!helloworld.HelloWorldRemote");

At this time, can i propose a simple guide in openliberty site for this sample step? i can produce a simple guide for this sample, What do you think? the only guide is: https://www.ibm.com/docs/en/was-liberty/zos?topic=liberty-using-enterprise-javabeans-remote-interfaces

Thanks all....
