### ISSUE TITLE
Investigate TCK failure when using updated SmallRye Config on Java 21

### ISSUE THREAD

**Issue by tevans78** [OpenLiberty/open-liberty#26767]
When SmallRye Config was updated from 3.3.0 to 3.4.1 (and SmallRye Common from 2.1.0 to 2.2.0), a TCK test fails when running on Java 21. We would still like to update but we might need to open a SmallRye issue first and get something fixed there.

```
CDIPropertyNameMatchingTest	testPropertyFromEnvironmentVariables	Failure	Expected: is "haha" but: was "woohoo"


java.lang.AssertionError:
Expected: is "haha"
but: was "woohoo"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
at org.eclipse.microprofile.config.tck.CDIPropertyNameMatchingTest.testPropertyFromEnvironmentVariables(CDIPropertyNameMatchingTest.java:111)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:136)
at org.testng.internal.invokers.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:253)
at org.jboss.arquillian.testng.Arquillian$3.invoke(Arquillian.java:146)
at org.jboss.arquillian.container.test.impl.execution.LocalTestExecuter.execute(LocalTestExecuter.java:57)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86) 
```

**Comment by jakub-pomykala** [comment]
Tested `SmallRye-config` using java 21 locally and the TCKs passed. 

Will start work on #26663.
