### ISSUE TITLE
Lease timestamp not updated for home server when recoveryGroups and tran logs in a database is configured and database outage > couple of seconds occurs

### ISSUE THREAD

**Issue by djmatthews** [OpenLiberty/open-liberty#26809]
**Describe the bug**  
When using a transaction recoveryGroup with the recovery logs in a database, if a database outage occurs, the server's lease renewal process's retry mechanism for its own lease does not perform apply the correct retry algorithm , using instead a lightweight retry mechanism thath gives up after a couple of seconds.  If that mechanism fails then the app server no longer updates its lease timestamp and other app servers in the recovery group will attempt peer recovery.  That peer recovery attempt will fail, because the logs heart beat timestamp will be current (that uses a different/the correct retry algoritm).

**Steps to Reproduce**  
Temporary (short duration of say 10 second) database outage results in peer app servers generating WTRN0108I: HADB Peer Recovery failed... messages

**Expected behavior**  
The app server should keep updating its lease timestamp and the peer recovery should not be attempted (at least not multiple times)

**Diagnostic information:**  
 - OpenLiberty Version: 23.0.0.9 (should be for any version from 23.0.0.5 or versions with internal property enableHADBPeerLocking=true)
 - Affected feature(s) transactions

**Additional context**

**Comment by djmatthews** [comment]
Call stack for initial failure updating lease:

Stack Dump = java.sql.SQLRecoverableException: DSRA9110E: Connection is closed.
	at com.ibm.ws.rsadapter.jdbc.WSJdbcWrapper.createClosedException(WSJdbcWrapper.java:126)
	at com.ibm.ws.rsadapter.jdbc.WSJdbcConnection.rollback(WSJdbcConnection.java:2593)
	at com.ibm.ws.recoverylog.custom.jdbc.impl.SQLSharedServerLeaseLog.getLeasesForPeers(SQLSharedServerLeaseLog.java:202)
	at com.ibm.tx.jta.impl.TxRecoveryAgentImpl.processLeasesForPeers(TxRecoveryAgentImpl.java:788)
	at com.ibm.tx.jta.impl.LeaseTimeoutManager$LeaseChecker.alarm(LeaseTimeoutManager.java:154)
	at com.ibm.tx.jta.util.alarm.AlarmManagerImpl$AlarmListenerWrapper.run(AlarmManagerImpl.java:85)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:522)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:191)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:825)

**Comment by djmatthews** [comment]
Additional call stacks for retry used:

Stack Dump = com.ibm.db2.jcc.am.ClientRerouteException: [jcc][t4][2027][11212][4.31.10] A connection failed but has been re-established. Special register settings have been replayed if necessary. Host name or IP address of the connection: 166.9.30.67. Service name or port number of the connection: 31,305.
Reason code: 1. Failure code: 2, Error code: zero byte read from the server.. ERRORCODE=-4498, SQLSTATE=08506
	at com.ibm.db2.jcc.am.b7.a(b7.java:322)
	at com.ibm.db2.jcc.am.b7.d(b7.java:454)
	at com.ibm.db2.jcc.t4.a.a(a.java:662)
	at com.ibm.db2.jcc.t4.a.a(a.java:619)
	at com.ibm.db2.jcc.t4.a.b(a.java:1185)
	at com.ibm.db2.jcc.t4.a.q(a.java:1043)
	at com.ibm.db2.jcc.t4.r.a(r.java:216)
	at com.ibm.db2.jcc.t4.a.a(a.java:1037)
	at com.ibm.db2.jcc.t4.y.b(y.java:312)
	at com.ibm.db2.jcc.t4.y.c(y.java:342)
	at com.ibm.db2.jcc.t4.y.c(y.java:455)
	at com.ibm.db2.jcc.t4.y.v(y.java:1230)
	at com.ibm.db2.jcc.t4.z.c(z.java:178)
	at com.ibm.db2.jcc.t4.n.c(n.java:42)
	at com.ibm.db2.jcc.t4.b.readLocalRollback_(b.java:3227)
	at com.ibm.db2.jcc.am.Connection.readRollback(Connection.java:1483)
	at com.ibm.db2.jcc.am.Connection.flowRollback(Connection.java:1444)
	at com.ibm.db2.jcc.t4.b.flowRollback(b.java:6382)
	at com.ibm.db2.jcc.am.Connection.rollbackX(Connection.java:1419)
	at com.ibm.db2.jcc.am.Connection.rollback(Connection.java:1407)
	at com.ibm.db2.jcc.am.du.rollback(du.java:180)
	at com.ibm.ws.rsadapter.jdbc.WSJdbcConnection.rollback(WSJdbcConnection.java:2612)
	at com.ibm.ws.recoverylog.custom.jdbc.impl.SQLRetry.retryAfterSQLException(SQLRetry.java:176)
	at com.ibm.ws.recoverylog.custom.jdbc.impl.SQLSharedServerLeaseLog.claimPeerLeaseForRecovery(SQLSharedServerLeaseLog.java:1402)
	at com.ibm.tx.jta.impl.TxRecoveryAgentImpl.claimPeerLeaseForRecovery(TxRecoveryAgentImpl.java:821)
	at com.ibm.ws.recoverylog.spi.RecoveryDirectorImpl.peerRecoverServers(RecoveryDirectorImpl.java:1647)
	at com.ibm.tx.jta.impl.LeaseTimeoutManager$LeaseChecker.alarm(LeaseTimeoutManager.java:157)
	at com.ibm.tx.jta.util.alarm.AlarmManagerImpl$AlarmListenerWrapper.run(AlarmManagerImpl.java:85)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:522)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:191)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:825)

Stack Dump = com.ibm.ws.recoverylog.spi.InternalLogException: com.ibm.db2.jcc.am.SqlException: The statement or command failed because it requires functionality that is not supported on a read-enabled HADR standby database. Reason code = "5".. SQLCODE=-1773, SQLSTATE=     , DRIVER=4.31.10
	at com.ibm.ws.recoverylog.custom.jdbc.impl.SQLSharedServerLeaseLog.claimPeerLeaseForRecovery(SQLSharedServerLeaseLog.java:1419)
	at com.ibm.tx.jta.impl.TxRecoveryAgentImpl.claimPeerLeaseForRecovery(TxRecoveryAgentImpl.java:821)
	at com.ibm.ws.recoverylog.spi.RecoveryDirectorImpl.peerRecoverServers(RecoveryDirectorImpl.java:1647)
	at com.ibm.tx.jta.impl.LeaseTimeoutManager$LeaseChecker.alarm(LeaseTimeoutManager.java:157)
	at com.ibm.tx.jta.util.alarm.AlarmManagerImpl$AlarmListenerWrapper.run(AlarmManagerImpl.java:85)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:522)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:191)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:825)
Caused by: com.ibm.db2.jcc.am.SqlException: The statement or command failed because it requires functionality that is not supported on a read-enabled HADR standby database. Reason code = "5".. SQLCODE=-1773, SQLSTATE=     , DRIVER=4.31.10
	at com.ibm.db2.jcc.am.b7.a(b7.java:815)
	at com.ibm.db2.jcc.am.b7.a(b7.java:66)
	at com.ibm.db2.jcc.am.b7.a(b7.java:140)
	at com.ibm.db2.jcc.am.k_.b(k_.java:2491)
	at com.ibm.db2.jcc.am.k_.c(k_.java:2472)
	at com.ibm.db2.jcc.t4.ab.n(ab.java:917)
	at com.ibm.db2.jcc.t4.ab.a(ab.java:118)
	at com.ibm.db2.jcc.t4.p.a(p.java:50)
	at com.ibm.db2.jcc.t4.aw.b(aw.java:220)
	at com.ibm.db2.jcc.am.la.bm(la.java:3632)
	at com.ibm.db2.jcc.am.la.a(la.java:4677)
	at com.ibm.db2.jcc.am.la.b(la.java:4215)
	at com.ibm.db2.jcc.am.la.be(la.java:832)
	at com.ibm.db2.jcc.t4.j.be(j.java:198)
	at com.ibm.db2.jcc.am.la.executeUpdate(la.java:806)
	at com.ibm.ws.rsadapter.jdbc.WSJdbcPreparedStatement.executeUpdate(WSJdbcPreparedStatement.java:522)
	at com.ibm.ws.recoverylog.custom.jdbc.impl.SQLSharedServerLeaseLog.claimPeerLeaseFromTable(SQLSharedServerLeaseLog.java:1503)
	at com.ibm.ws.recoverylog.custom.jdbc.impl.SQLSharedServerLeaseLog.claimPeerLeaseForRecovery(SQLSharedServerLeaseLog.java:1322)
	... 11 more

**Comment by neilgsyoung** [comment]
Product changes made under PR #26812. To do: provide FAT tests to check this behaviour under another issue.
