### ISSUE TITLE
Fix JaxRs Telemetry-1.1 EE7/8 Async

### ISSUE THREAD

**Issue by Yas-Franco** [OpenLiberty/open-liberty#26811]
Currently, we have had to skip the async tests for JaxRsIntegrationWithConcurrency here for EE7 and EE8: 

https://github.com/OpenLiberty/open-liberty/blob/integration/dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/jaxrspropagation/async/JaxRsServerAsyncTestServlet.java#L58-L66

We are getting the following error: 

```
###AssertionError Json Start###{"exceptionType":"AssertionError","message":"JaxRsServerAsyncTestServlet.testJaxRsServerAsyncCompletionStage: Expected 4 traces but found 3\nSpanData{spanContext=ImmutableSpanContext{traceId=e0f714ef4beb10e675b784d714d6487d, spanId=0e373407d673e84c, traceFlags=01, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=true}, parentSpanContext=ImmutableSpanContext{traceId=e0f714ef4beb10e675b784d714d6487d, spanId=02ff0de2bbd61866, traceFlags=01, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=true}, resource=Resource{schemaUrl=https://opentelemetry.io/schemas/1.20.0, attributes={service.name=\"jaxrsAsyncServer\", telemetry.sdk.language=\"java\", telemetry.sdk.name=\"opentelemetry\", telemetry.sdk.version=\"1.29.0\"}}, instrumentationScopeInfo=InstrumentationScopeInfo{name=io.openliberty.microprofile.telemetry, version=null, schemaUrl=null, attributes={}}, name=subtask, kind=INTERNAL, startEpochNanos=1698938670234524167, endEpochNanos=1698938673236658625, attributes=AttributesMap{data={test.baggage=test.value}, capacity=128, totalAddedValues=1}, totalAttributeCount=1, events=[], totalRecordedEvents=0, links=[], totalRecordedLinks=0, status=ImmutableStatusData{statusCode=UNSET, description=}, hasEnded=true}\nSpanData{spanContext=ImmutableSpanContext{traceId=e0f714ef4beb10e675b784d714d6487d, spanId=8221de4b3988c44a, traceFlags=01, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=true}, parentSpanContext=ImmutableSpanContext{traceId=e0f714ef4beb10e675b784d714d6487d, spanId=2f5ad6e4914ea6a1, traceFlags=01, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=true}, resource=Resource{schemaUrl=https://opentelemetry.io/schemas/1.20.0, attributes={service.name=\"jaxrsAsyncServer\", telemetry.sdk.language=\"java\", telemetry.sdk.name=\"opentelemetry\", telemetry.sdk.version=\"1.29.0\"}}, instrumentationScopeInfo=InstrumentationScopeInfo{name=Client filter, version=null, schemaUrl=null, attributes={}}, name=GET, kind=CLIENT, startEpochNanos=1698938670220604125, endEpochNanos=1698938673256577708, attributes=AttributesMap{data={net.peer.port=8010, http.response_content_length=2, http.url=http://localhost:8010/jaxrsAsyncServer/JaxRsServerAsyncTestEndpoint/completionstage, http.method=GET, http.status_code=200, net.peer.name=localhost, net.transport=ip_tcp}, capacity=128, totalAddedValues=7}, totalAttributeCount=7, events=[], totalRecordedEvents=0, links=[], totalRecordedLinks=0, status=ImmutableStatusData{statusCode=UNSET, description=}, hasEnded=true}\nSpanData{spanContext=ImmutableSpanContext{traceId=e0f714ef4beb10e675b784d714d6487d, spanId=2f5ad6e4914ea6a1, traceFlags=01, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=true}, parentSpanContext=ImmutableSpanContext{traceId=00000000000000000000000000000000, spanId=0000000000000000, traceFlags=00, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=false}, resource=Resource{schemaUrl=https://opentelemetry.io/schemas/1.20.0, attributes={service.name=\"jaxrsAsyncServer\", telemetry.sdk.language=\"java\", telemetry.sdk.name=\"opentelemetry\", telemetry.sdk.version=\"1.29.0\"}}, instrumentationScopeInfo=InstrumentationScopeInfo{name=io.openliberty.microprofile.telemetry, version=null, schemaUrl=null, attributes={}}, name=testSpan-/jaxrsAsyncServer/testJaxrsServerAsync, kind=INTERNAL, startEpochNanos=1698938670209000000, endEpochNanos=1698938673257484792, attributes={}, totalAttributeCount=0, events=[], totalRecordedEvents=0, links=[], totalRecordedLinks=0, status=ImmutableStatusData{statusCode=UNSET, description=}, hasEnded=true}","stack":[{"className":"org.junit.Assert","methodName":"fail","fileName":"Assert.java","lineNumber":93},{"className":"io.openliberty.microprofile.telemetry.internal_fat.common.spanexporter.InMemorySpanExporter","methodName":"getFinishedSpanItems","fileName":"InMemorySpanExporter.java","lineNumber":94},{"className":"io.openliberty.microprofile.telemetry.internal_fat.common.spanexporter.InMemorySpanExporter$Proxy$_$$_WeldClientProxy","methodName":"getFinishedSpanItems","lineNumber":-1},{"className":"io.openliberty.microprofile.telemetry.internal_fat.apps.jaxrspropagation.async.JaxRsServerAsyncTestServlet","methodName":"doAsyncTest","fileName":"JaxRsServerAsyncTestServlet.java","lineNumber":90},{"className":"io.openliberty.microprofile.telemetry.internal_fat.apps.jaxrspropagation.async.JaxRsServerAsyncTestServlet","methodName":"testJaxRsServerAsyncCompletionStage","fileName":"JaxRsServerAsyncTestServlet.java","lineNumber":64},{"className":"jdk.internal.reflect.NativeMethodAccessorImpl","methodName":"invoke0","fileName":"NativeMethodAccessorImpl.java","lineNumber":-2},{"className":"jdk.internal.reflect.NativeMethodAccessorImpl","methodName":"invoke","fileName":"NativeMethodAccessorImpl.java","lineNumber":77},{"className":"jdk.internal.reflect.DelegatingMethodAccessorImpl","methodName":"invoke","fileName":"DelegatingMethodAccessorImpl.java","lineNumber":43},{"className":"java.lang.reflect.Method","methodName":"invoke","fileName":"Method.java","lineNumber":568},{"className":"componenttest.app.FATServlet","methodName":"doGet","fileName":"FATServlet.java","lineNumber":73}]}###AssertionError Json End###

[11/02/2023 15:24:45:359 GMT] 001 JaxRsIntegrationWithConcurrenc JaxRsServerAsyncTestServlet.te I <<< END   JaxRsServerAsyncTestServlet.testJaxRsServerAsyncCompletionStage_EE8_FEATURES_MicroProfile_41_MPTEL11
[11/02/2023 15:24:45:359 GMT] 001 FATRunner                      evaluate                       S null
java.lang.AssertionError: JaxRsServerAsyncTestServlet.testJaxRsServerAsyncCompletionStage: Expected 4 traces but found 3
SpanData{spanContext=ImmutableSpanContext{traceId=e0f714ef4beb10e675b784d714d6487d, spanId=0e373407d673e84c, traceFlags=01, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=true}, parentSpanContext=ImmutableSpanContext{traceId=e0f714ef4beb10e675b784d714d6487d, spanId=02ff0de2bbd61866, traceFlags=01, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=true}, resource=Resource{schemaUrl=https://opentelemetry.io/schemas/1.20.0, attributes={service.name="jaxrsAsyncServer", telemetry.sdk.language="java", telemetry.sdk.name="opentelemetry", telemetry.sdk.version="1.29.0"}}, instrumentationScopeInfo=InstrumentationScopeInfo{name=io.openliberty.microprofile.telemetry, version=null, schemaUrl=null, attributes={}}, name=subtask, kind=INTERNAL, startEpochNanos=1698938670234524167, endEpochNanos=1698938673236658625, attributes=AttributesMap{data={test.baggage=test.value}, capacity=128, totalAddedValues=1}, totalAttributeCount=1, events=[], totalRecordedEvents=0, links=[], totalRecordedLinks=0, status=ImmutableStatusData{statusCode=UNSET, description=}, hasEnded=true}
SpanData{spanContext=ImmutableSpanContext{traceId=e0f714ef4beb10e675b784d714d6487d, spanId=8221de4b3988c44a, traceFlags=01, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=true}, parentSpanContext=ImmutableSpanContext{traceId=e0f714ef4beb10e675b784d714d6487d, spanId=2f5ad6e4914ea6a1, traceFlags=01, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=true}, resource=Resource{schemaUrl=https://opentelemetry.io/schemas/1.20.0, attributes={service.name="jaxrsAsyncServer", telemetry.sdk.language="java", telemetry.sdk.name="opentelemetry", telemetry.sdk.version="1.29.0"}}, instrumentationScopeInfo=InstrumentationScopeInfo{name=Client filter, version=null, schemaUrl=null, attributes={}}, name=GET, kind=CLIENT, startEpochNanos=1698938670220604125, endEpochNanos=1698938673256577708, attributes=AttributesMap{data={net.peer.port=8010, http.response_content_length=2, http.url=http://localhost:8010/jaxrsAsyncServer/JaxRsServerAsyncTestEndpoint/completionstage, http.method=GET, http.status_code=200, net.peer.name=localhost, net.transport=ip_tcp}, capacity=128, totalAddedValues=7}, totalAttributeCount=7, events=[], totalRecordedEvents=0, links=[], totalRecordedLinks=0, status=ImmutableStatusData{statusCode=UNSET, description=}, hasEnded=true}
SpanData{spanContext=ImmutableSpanContext{traceId=e0f714ef4beb10e675b784d714d6487d, spanId=2f5ad6e4914ea6a1, traceFlags=01, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=true}, parentSpanContext=ImmutableSpanContext{traceId=00000000000000000000000000000000, spanId=0000000000000000, traceFlags=00, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=false}, resource=Resource{schemaUrl=https://opentelemetry.io/schemas/1.20.0, attributes={service.name="jaxrsAsyncServer", telemetry.sdk.language="java", telemetry.sdk.name="opentelemetry", telemetry.sdk.version="1.29.0"}}, instrumentationScopeInfo=InstrumentationScopeInfo{name=io.openliberty.microprofile.telemetry, version=null, schemaUrl=null, attributes={}}, name=testSpan-/jaxrsAsyncServer/testJaxrsServerAsync, kind=INTERNAL, startEpochNanos=1698938670209000000, endEpochNanos=1698938673257484792, attributes={}, totalAttributeCount=0, events=[], totalRecordedEvents=0, links=[], totalRecordedLinks=0, status=ImmutableStatusData{statusCode=UNSET, description=}, hasEnded=true}
	at org.junit.Assert.fail(Assert.java:93)
	at io.openliberty.microprofile.telemetry.internal_fat.common.spanexporter.InMemorySpanExporter.getFinishedSpanItems(InMemorySpanExporter.java:94)
	at io.openliberty.microprofile.telemetry.internal_fat.common.spanexporter.InMemorySpanExporter$Proxy$_$$_WeldClientProxy.getFinishedSpanItems(Unknown Source)
	at io.openliberty.microprofile.telemetry.internal_fat.apps.jaxrspropagation.async.JaxRsServerAsyncTestServlet.doAsyncTest(JaxRsServerAsyncTestServlet.java:90)
	at io.openliberty.microprofile.telemetry.internal_fat.apps.jaxrspropagation.async.JaxRsServerAsyncTestServlet.testJaxRsServerAsyncCompletionStage(JaxRsServerAsyncTestServlet.java:64)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:568)
	at componenttest.app.FATServlet.doGet(FATServlet.java:73)
[11/02/2023 15:24:45:359 GMT] 001 FATRunner                      evaluate                       I exiting io.openliberty.microprofile.telemetry.internal_fat.JaxRsIntegrationWithConcurrency.JaxRsServerAsyncTestServlet.testJaxRsServerAsyncCompletionStage```

**Comment by Azquelt** [comment]
This is strange. It looks like the server span is missing.

The test starts a test span, then uses a client to call a JAX-RS async resource method which runs a subtask on another thread. The subtask completes the request asynchronously using `AsyncResponse`.

The subtask span which has `name=subtask, kind=INTERNAL` is there and reports a parent of `spanId=02ff0de2bbd61866` which wasn't found. This suggests to me that a server span was created, but was never ended.

We should check the trace to see if that matches up. I would expect to see the `TelemetryContainerFilter` `filter` method called for the request but not for the response.

**Comment by Azquelt** [comment]
Based on my trace log it looks like the `TelemetryContainerFilter` isn't being called at all when running with EE7/8, only the servlet filter is called.

I'm suspicious of this result because this should cause more things to fail than just these async tests since the container filter is responsible for putting in the route information since that info isn't available to the servlet filter. It would also mean we don't have any tests which exercise the container filter without beta mode enabled.

For some reason, the servlet filter async callback doesn't get called to notify it of the end of the async request so it never ends the span.

**Comment by Azquelt** [comment]
The `TelemetryServletFilter` registers an `AsyncListener`. It looks like our JAX-RS 2.0 and 2.1 implementations call `startAsync()` again when `AsyncResponse.resume()` is called.

When this happens, listeners are informed of this and need to re-register themselves if they want to be notified of async events in the new async cycle (which we do, because the request isn't over yet).

I think we just need to re-register our listener like this, but we might want to confirm with the webcontainer team:

```java
                @Override
                public void onStartAsync(AsyncEvent event) throws IOException {
                    // A new async cycle is starting, we need to re-register ourself
                    event.getAsyncContext().addListener(this);
                }
```

We also still need to get the `TelemetryContainerFilter` registered (probably in `TelemetryJaxRsProviderRegister`) and make sure we have tests for JaxRS integration without tracing via the servlet container and tests for the extra information that the container filter adds when servlet tracing is enabled.
