### ISSUE TITLE
MP Rest Client 2.0 hangs when performing an async request with Java 2 Security enabled

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/open-liberty#26810]
**Describe the bug**  
MP Rest Client 2.0 hangs when performing an async request with Java 2 Security enabled. The request is made, but the returned completion stage never completes.

The following stack trace is printed to stderr on the liberty server:

```java
[err] Exception in thread "ForkJoinPool.commonPool-worker-1" 
[err] java.lang.SecurityException: setContextClassLoader
[err]   at java.base/java.util.concurrent.ForkJoinWorkerThread$InnocuousForkJoinWorkerThread.setContextClassLoader(ForkJoinWorkerThread.java:210)
[err]   at org.apache.cxf.common.classloader.ClassLoaderUtils$1.run(ClassLoaderUtils.java:77)
[err]   at org.apache.cxf.common.classloader.ClassLoaderUtils$1.run(ClassLoaderUtils.java:73)
[err]   at java.base/java.security.AccessController.doPrivileged(AccessController.java:692)
[err]   at org.apache.cxf.common.classloader.ClassLoaderUtils.setThreadContextClassloader(ClassLoaderUtils.java:73)
[err]   at org.apache.cxf.interceptor.AbstractFaultChainInitiatorObserver.onMessage(AbstractFaultChainInitiatorObserver.java:62)
[err]   at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream$1.run(HTTPConduit.java:1268)
[err]   at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
[err]   at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[err]   at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[err]   at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[err]   at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[err]   at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

**Steps to Reproduce**  

* Configure a liberty server with `mpRestClient-2.0` and `jaxrs-2.1`
* Enable Java 2 Security by putting `websphere.java.security` in bootstrap.properties
* Include the below test resource class in a Jax-RS app
* Make a GET request to the root URL of the app

```java
@Path("/")
public class TestResource {

    /**
     * Entry point for test
     */
    @GET
    public String doTest(@Context UriInfo uriInfo) throws InterruptedException, ExecutionException, TimeoutException {
        TestClientInterface client = RestClientBuilder.newBuilder()
                                                      .baseUri(uriInfo.getBaseUri())
                                                      .build(TestClientInterface.class);
        return client.asyncGetTarget().toCompletableFuture().get(10, TimeUnit.SECONDS);
    }

    /**
     * Target for rest client
     * @return constant string
     */
    @GET
    @Path("/target")
    public String getTarget() {
        return "test string";
    }
    
    /**
     * Rest client interface to call to target
     */
    public static interface TestClientInterface {
        @Path("/target")
        @GET
        public CompletionStage<String> asyncGetTarget();
    }

}
```

**Expected behavior**  

The returned completion stage should complete

**Diagnostic information:**  
 - OpenLiberty Version: affects current integration, likely affects many older versions as well
 - Affected feature(s) mpRestClient-1.2 up to including mpRestClient-2.0
 - Java Version:
 ```java version "17.0.7" 2023-04-18
IBM Semeru Runtime Certified Edition 17.0.7.0 (build 17.0.7+7)
Eclipse OpenJ9 VM 17.0.7.0 (build openj9-0.38.0, JRE 17 Linux amd64-64-Bit Compressed References 20230418_417 (JIT enabled, AOT enabled)
OpenJ9   - d57d05932
OMR      - 855813495
JCL      - 7a1e0864e99 based on jdk-17.0.7+7)
```

**Additional context**  

I believe the common fork join pool uses `InnocuousForkJoinWorkerThread` when security is enabled which prevents the thread context class loader from being changed.

In general we shouldn't use the common fork join pool and should use the liberty global thread pool instead.

**Comment by anagha-paulson** [comment]
Checking this
