### ISSUE TITLE
Build fails due to missing dependencies

### ISSUE THREAD

**Issue by gpoul** [OpenLiberty/open-liberty#2688]
These files seem to not be on the IBM server where they should be:

```
Download http://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/wasliberty-open-liberty/com/ibm/ws/org/apache/cxf/cxf-api/2.6.2.ibm-s20180308-1806/cxf-api-2.6.2.ibm-s20180308-1806.jar
Download http://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/wasliberty-open-liberty/com/ibm/ws/org/apache/cxf/cxf-rt-core/2.6.2.ibm-s20180308-1806/cxf-rt-core-2.6.2.ibm-s20180308-1806.jar
Download http://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/wasliberty-open-liberty/com/ibm/ws/org/apache/cxf/cxf-rt-frontend-jaxws/2.6.2.ibm-s20180308-1806/cxf-rt-frontend-jaxws-2.6.2.ibm-s20180308-1806.jar
Download http://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/wasliberty-open-liberty/com/ibm/ws/org/apache/cxf/cxf-rt-transports-http/2.6.2.ibm-s20180308-1806/cxf-rt-transports-http-2.6.2.ibm-s20180308-1806.jar
Download http://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/wasliberty-open-liberty/com/ibm/ws/org/apache/cxf/cxf-rt-ws-policy/2.6.2.ibm-s20180308-1806/cxf-rt-ws-policy-2.6.2.ibm-s20180308-1806.jar
```

As I get the following errors when I follow the build steps in the README.md:

```
> Task :com.ibm.ws.org.osgi.annotation.versioning:jar FAILED
warning: There is an empty jar or directory on the classpath: main
warning: Unreferenced class path entries [javaws, rt, jfxswt, plugin, management-agent, jfr, charsets, resources, jsse, org.osgi.annotation.versioning-1.0.0, jce, deploy]
error  : dev :Exception: java.io.FileNotFoundException: For Maven artifact com.ibm.ws.org.apache.cxf:cxf-api:2.6.2.ibm-s20180308-1806
        at aQute.maven.provider.MavenRepository$1.call(MavenRepository.java:138)
        at aQute.maven.provider.MavenRepository$1.call(MavenRepository.java:133)
        at aQute.lib.promise.PromiseExecutor$1.run(PromiseExecutor.java:23)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

error  : dev :Failed to sync com.ibm.ws.org.apache.cxf:cxf-api:2.6.2.ibm-s20180308-1806
error  : dev :Exception: java.io.FileNotFoundException: For Maven artifact com.ibm.ws.org.apache.cxf:cxf-rt-transports-http:2.6.2.ibm-s20180308-1806
        at aQute.maven.provider.MavenRepository$1.call(MavenRepository.java:138)
        at aQute.maven.provider.MavenRepository$1.call(MavenRepository.java:133)
        at aQute.lib.promise.PromiseExecutor$1.run(PromiseExecutor.java:23)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

error  : dev :Failed to sync com.ibm.ws.org.apache.cxf:cxf-rt-transports-http:2.6.2.ibm-s20180308-1806
error  : dev :Exception: java.io.FileNotFoundException: For Maven artifact com.ibm.ws.org.apache.cxf:cxf-rt-ws-policy:2.6.2.ibm-s20180308-1806
        at aQute.maven.provider.MavenRepository$1.call(MavenRepository.java:138)
        at aQute.maven.provider.MavenRepository$1.call(MavenRepository.java:133)
        at aQute.lib.promise.PromiseExecutor$1.run(PromiseExecutor.java:23)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

error  : dev :Failed to sync com.ibm.ws.org.apache.cxf:cxf-rt-ws-policy:2.6.2.ibm-s20180308-1806
error  : dev :Exception: java.io.FileNotFoundException: For Maven artifact com.ibm.ws.org.apache.cxf:cxf-rt-core:2.6.2.ibm-s20180308-1806
        at aQute.maven.provider.MavenRepository$1.call(MavenRepository.java:138)
        at aQute.maven.provider.MavenRepository$1.call(MavenRepository.java:133)
        at aQute.lib.promise.PromiseExecutor$1.run(PromiseExecutor.java:23)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

error  : dev :Failed to sync com.ibm.ws.org.apache.cxf:cxf-rt-core:2.6.2.ibm-s20180308-1806
error  : dev :Exception: java.io.FileNotFoundException: For Maven artifact com.ibm.ws.org.apache.cxf:cxf-rt-frontend-jaxws:2.6.2.ibm-s20180308-1806
        at aQute.maven.provider.MavenRepository$1.call(MavenRepository.java:138)
        at aQute.maven.provider.MavenRepository$1.call(MavenRepository.java:133)
        at aQute.lib.promise.PromiseExecutor$1.run(PromiseExecutor.java:23)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

error  : dev :Failed to sync com.ibm.ws.org.apache.cxf:cxf-rt-frontend-jaxws:2.6.2.ibm-s20180308-1806


FAILURE: Build failed with an exception.
```

Reproduced on macOS 10.13.3 (17D102) with Oracle Java "1.8.0_162-b12".

**Comment by gpoul** [comment]
The files on public.dhe.ibm.com now seem to be working again and with the satisfied dependencies the `./gradlew assemble` now completes successfully.
