### ISSUE TITLE
java.lang.IllegalStateException: Subject is read-only from WebAppFilterManager.invokeFilters

### ISSUE THREAD

**Issue by tschurins** [OpenLiberty/open-liberty#26886]
We still have the same problem as on issue https://github.com/OpenLiberty/open-liberty/issues/21666, even with the fix.

OpenLiberty version: 23.0.0.6

Stacktrace:
```
java.lang.IllegalStateException: Subject is read-only
        at javax.security.auth.Subject$SecureSet.add(Subject.java:1103)
        at java.util.Collections$SynchronizedCollection.add(Collections.java:2037)
        at com.ibm.ws.webcontainer.security.WebProviderAuthenticatorHelper.removeSecurityNameAndUniquedIdFromHashtable(WebProviderAuthenticatorHelper.java:150)
        at com.ibm.ws.webcontainer.security.WebProviderAuthenticatorHelper.loginWithUserName(WebProviderAuthenticatorHelper.java:80)
        at com.ibm.ws.webcontainer.security.WebProviderAuthenticatorProxy.handleOidcClient(WebProviderAuthenticatorProxy.java:637)
        at com.ibm.ws.webcontainer.security.WebProviderAuthenticatorProxy.authenticate(WebProviderAuthenticatorProxy.java:465)
        at com.ibm.ws.webcontainer.security.WebAuthenticatorProxy.authenticate(WebAuthenticatorProxy.java:69)
        at com.ibm.ws.webcontainer.security.WebAppSecurityCollaboratorImpl.authenticateRequest(WebAppSecurityCollaboratorImpl.java:1243)
        at com.ibm.ws.webcontainer.security.WebAppSecurityCollaboratorImpl.determineWebReply(WebAppSecurityCollaboratorImpl.java:999)
        at com.ibm.ws.webcontainer.security.WebAppSecurityCollaboratorImpl.performSecurityChecks(WebAppSecurityCollaboratorImpl.java:698)
        at com.ibm.ws.webcontainer.security.WebAppSecurityCollaboratorImpl.preInvoke(WebAppSecurityCollaboratorImpl.java:619)
        at com.ibm.wsspi.webcontainer.collaborator.CollaboratorHelper.preInvokeCollaborators(CollaboratorHelper.java:472)
        at com.ibm.ws.webcontainer.osgi.collaborator.CollaboratorHelperImpl.preInvokeCollaborators(CollaboratorHelperImpl.java:272)
        at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1222)
        at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1077)
        at com.ibm.ws.webcontainer.servlet.CacheServletWrapper.handleRequest(CacheServletWrapper.java:77)
        at com.ibm.ws.webcontainer40.servlet.CacheServletWrapper40.handleRequest(CacheServletWrapper40.java:87)
        at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:969)
        at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:283)
```

This seems to occur when the same JWT is used to call some Rest API in parallel. In that case, the same Subject instance is used in different threads, resulting in the possibility of the Subject being writeable when the "isReadOnly" check is done by the first thread, but set read-only just after by the second thread, before the first thread enters the removeSecurityNameAndUniquedIdFromHashtable method.

**Comment by una-tapa** [comment]
@tschurins Thank you for reporting. Will look into this and keep you posted.

**Comment by tschurins** [comment]
Hello,
Thank you for your quick intervention. I already see that you have done a commit (moving the "isReadOnly" check to the synchronized part). But, IMHO, it will not correct the issue.
I've done a bit of investigation to see when the "setReadOnly" was called, and this is unrelated to the WebProviderAuthenticatorHelper class.

**Comment by una-tapa** [comment]
Hi @tschurins Sorry for the delayed reply. Thank you so much for the comment. 
I agree that moving "isReadOnly" does not help (I also commented in the PR)   
I guess adding synchronize() around Subject manipulation during the login is necessary?  I will appreciate your input! 
Also cc: @arunavemulapalli

**Comment by tschurins** [comment]
Hello,
If the Subject is shared, then an (easy) solution would be to make sure that it is shared in a read-only state (in fact, sharing a mutable object can only lead to bugs).
I did not investigate much where the Subject was cached, but I guess that a correction could be applied there: before caching the Subject, make it read-only.

**Comment by tschurins** [comment]
I was able to reproduce the problem (it's a bit cumbersome).

Setup:
- using the OpenLiberty guide-getting-started/finish project (https://github.com/openliberty/guide-getting-started.git), 
- updating the endpoint: adding the @RolesAllowed({"user"}) annotation, and in the method itself, getting the subject: WSSubject.getCallerSubject() - this will call the setReadOnly method internally.
- having an OIDC server configured (I used a local keycloak server).
- configuring the openidConnectClient in server.xml

I wrote a bash file that would first get an access token from the OIDC server, then use it as a bearer token when calling the application. The application is called in a loop, all calls are done in parallel. Something like this:
```
#!/bin/bash
access_token=...

for i in {1..20}
do
  curl -v -H "Authorization: Bearer ${access_token}" http://localhost:9080/dev/system/properties > result-${i}.txt 2>&1 &
  sleep 0.005
done
wait
```

To make sure that it fails, I have added a Thread.sleep(10) in the removeSecurityNameAndUniquedIdFromHashtable method (in a break-point in the IDE).
And indeed, for some of the curl calls, I got a response "500 Internal Server Error" with message "Error 500: java.lang.IllegalStateException: Subject is read-only".

**Comment by tschurins** [comment]
The caching is done in com.ibm.ws.security.authentication.internal.AuthenticationServiceImpl#authenticate(String jaasEntryName, AuthenticationData authenticationData, Subject subject) method (calling insertSubjectInAuthCache).
But of course, if we make the subject readonly at that point, then it means that it will be impossible to call removeSecurityNameAndUniquedIdFromHashtable...

**Comment by una-tapa** [comment]
@tschurins  
Thank you so much for your technical assistance and the insight how it might be fixed. 
Sorry for the delay. I've been out for medical reasons a bit. I will work on the recreate and work with the people in the area.

**Comment by tschurins** [comment]
@una-tapa , I hope that you are well.
Do you have any news regarding this issue?

**Comment by una-tapa** [comment]
I started working on this. Sorry for the delay.

**Comment by una-tapa** [comment]
Hello, @tschurins 

Thank you for the recreate steps.  I admire that you came up with such cool steps and actually enjoy following it.  
Please find my status. I have not been able to recreate the issue but I think/hope I got better understanding. 

- I cloned guide-getting-started and updated the application with getCallerSubject as well as @RolesAllowed.
- The application is secured by OpenLiberty OP instead of keycloak.   
- Liberty was also updated with the suggested Thread.sleep(10) and other debug statements. 
- The script ran curl with the access token 5000 times.  
- The script drove the code path that caused the exception - I see handleOidcClient () calls loginWithUser() in the trace. 
- However the code did not go into  removeSecurityNameAndUniquedIdFromHashtable().  
- I will add/remove sleep and add/remove debug output to see if I can recreate it. 
- In theory, between isReadOnly() check, until any Subject contents manipulation, if getCallerSubject makes the subject readOnly, I guess we should synchronize "isReadOnly to add/remove" operation for a Subject. 
- I will chat with larger team on Slack.

**Comment by tschurins** [comment]
Hello,
To help reproduce the issue, here is a small project. It is based on the open-liberty getting-started guide, with additional configuration for an openidconnect client and an openidconnect server (as you did)
[subject-is-readonly.zip](https://github.com/user-attachments/files/15808992/subject-is-readonly.zip)

You can reproduce by following these steps:
1. mvn clean package
2. docker build -t openliberty-getting-started:1.0-SNAPSHOT .
3. docker run --name gettingstarted-app -e WLP_DEBUG_REMOTE=y -p 9443:9443 -p 9080:9080 -p 7777:7777 --link keycloak --network=kc_default openliberty-getting-started:1.0-SNAPSHOT /opt/ol/wlp/bin/server debug
4. at this point, you will need to connect your debugger to the container (port 7777)
5. in your IDE, put a breakpoint in the WebProviderAuthenticatorHelper#loginWithUserName method (where it calls the removeSecurityNameAndUniquedIdFromHashtable method) and execute a Thread.sleep(100) when hit (don't suspend the execution);
6. run once the loop-secure.sh (the first time everything succeeds certainly due to initialization)
7. run the bash file a second time, this time there might be failures. You can see the executions in the out directory.

**Comment by una-tapa** [comment]
Hello, thank you so much for the recreate steps and actually getting the data. I was not aware of the new recreate steps. My sincere apology having you spend the time. 

The following is the JVM option @tschurins kindly ran and collected the output.  We see within less than a millisecond that the same Subject is checked and found readOnly=false, but before operating on it, another thread came in to set it readOnly.  
We are asking the developer who introduced the subject manipulation routine to allow the failure (=swallow the exception basically), or synchronize the setReadOnly/isReadOnly operation.  We are planning on providing a test fix at a level @tschurins is planning to use... to have his feedback.  
 Xtrace:none,maximal=mt,trigger=method{javax/security/auth/Subject.isReadOnly,jstacktrace},trigger=method{javax/security/auth/Subject.setReadOnly,jstacktrace},buffers=64k                                                                                                                                                                  

-Xdump:java+snap:events=throw+systhrow,filter=java/lang/IllegalStateException,msg_filter=*Subject is read-only*,request=exclusive+serial+preempt

**Comment by una-tapa** [comment]
Thanks to the data @tschurins collected for us, at the very same timestamp when the reported error was thrown,  another thread is calling  "getCallerSubject" from the sample application in the recreation environment. 
If getCallerSubject were called less than 1 millisec earlier, the hashtable manipulation was not even called. 

```
at javax.security.auth.Subject.setReadOnly(Subject.java:246)
at com.ibm.websphere.security.auth.WSSubject$1.run(WSSubject.java:360)
at java.security.AccessController.doPrivileged(AccessController.java:748)
at com.ibm.websphere.security.auth.WSSubject.getCallerSubject(WSSubject.java:342)  <===== 
at jdk.internal.reflect.GeneratedMethodAccessor867.invoke()
at java.lang.reflect.Method.invoke(Method.java:568)
at io.openliberty.sample.system.SystemResource.getProperties(SystemResource.java:47)
at io.openliberty.sample.system.SystemResource$Proxy$_$$_WeldSubclass.getProperties$$super()
at jdk.internal.reflect.GeneratedMethodAccessor865.invoke()
at java.lang.reflect.Method.invoke(Method.java:568)
at org.jboss.weld.interceptor.proxy.TerminalAroundInvokeInvocationContext.proceedInternal(TerminalAroundInvokeInvocationContext.java:51)
at org.jboss.weld.interceptor.proxy.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:78)
at io.smallrye.metrics.legacyapi.interceptors.TimedInterceptor.timedCallable(TimedInterceptor.java:75)
at io.smallrye.metrics.legacyapi.interceptors.TimedInterceptor.timedMethod(TimedInterceptor.java:40)
at jdk.internal.reflect.GeneratedMethodAccessor864.invoke()
at java.lang.reflect.Method.invoke(Method.java:568)
....
```
