### ISSUE TITLE
xmlWS-4.0: wsimport dependencies are not available when xmlWS-3.0 is not installed. 

### ISSUE THREAD

**Issue by neuwerk** [OpenLiberty/open-liberty#26991]
If xmlWS-4.0 is installed on a liberty server, wsimport will not run unless xmlWS-3.0 is also installed, and causing this to occur:

```
wlp/bin/xmlWS/wsimport -d /somedir/ Example.wsdl
java.lang.ClassNotFoundException: jakarta.jws.WebService
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:605)
        at java.base/java.lang.ClassLoader.loadClassHelper(ClassLoader.java:1172)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1087)
        at com.ibm.ws.kernel.boot.cmdline.PackageDelegateClassLoader.loadClass(PackageDelegateClassLoader.java:57)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1070)
        at io.openliberty.xmlWS30.tools.WsImport.main(WsImport.java:47)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.ibm.ws.kernel.boot.cmdline.UtilityMain.internal_main(UtilityMain.java:175)
        at com.ibm.ws.kernel.boot.cmdline.UtilityMain.main(UtilityMain.java:55)
        at com.ibm.ws.kernel.boot.cmdline.Main.main(Main.java:54)
```

Work around is to install both the xmlWS-4.0 and xmlWS-3.0 feature.

**Comment by neuwerk** [comment]
#27092 
Resolved this issue on 12/4/23
