### ISSUE TITLE
Test Failure: io.openliberty.microprofile.telemetry.internal.tests.JaegerOltpTest.testBasic

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#27629]
RTC 294532

```
testBasic:java.lang.Throwable: 2023-01-25-04:10:50:268 UNAVAILABLE: io exception
    at componenttest.custom.junit.runner.FATRunner.newThrowableWithTimeStamp(FATRunner.java:331)
    at componenttest.custom.junit.runner.FATRunner.access$700(FATRunner.java:69)
    at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:303)
    at org.testcontainers.containers.FailureDetectingExternalResource$1.evaluate(FailureDetectingExternalResource.java:29)
    at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:356)
    at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:177)
Caused by: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
    at io.grpc.StatusRuntimeException.fillInStackTrace(StatusRuntimeException.java:68)
    at io.grpc.StatusRuntimeException.<init>(StatusRuntimeException.java:58)
    at io.grpc.StatusRuntimeException.<init>(StatusRuntimeException.java:50)
    at io.grpc.Status.asRuntimeException(Status.java:535)
    at io.grpc.stub.ClientCalls$BlockingResponseStream.hasNext(ClientCalls.java:649)
    at io.openliberty.microprofile.telemetry.internal.utils.jaeger.JaegerQueryClient.consumeChunkedResult(JaegerQueryClient.java:252)
    at io.openliberty.microprofile.telemetry.internal.utils.jaeger.JaegerQueryClient.getSpansForTraceId(JaegerQueryClient.java:105)
    at io.openliberty.microprofile.telemetry.internal.utils.jaeger.JaegerQueryClient.waitForSpansForTraceId(JaegerQueryClient.java:165)
    at io.openliberty.microprofile.telemetry.internal.tests.JaegerBaseTest.testBasic(JaegerBaseTest.java:69)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:203)
Caused by: java.io.IOException: Operation timed out
    at java.base/sun.nio.ch.FileDispatcherImpl.read0(Native Method)
    at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
    at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276)
    at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:233)
    at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223)
    at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:356)
    at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:259)
    at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
    at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.base/java.lang.Thread.run(Thread.java:866)
```

**Comment by fmhwong** [comment]
Found the following messages in Jaeger container.

```
[01/27/2024 22:52:55:494 UTC] 029 JaegerBaseTest                 [jaeger]                       I {"level":"info","ts":1706395974.7365596,"caller":"channelz/funcs.go:340","msg":"[core][Server #9] Server created","system":"grpc","grpc_log":true}
[01/27/2024 22:52:55:494 UTC] 029 JaegerBaseTest                 [jaeger]                       I {"level":"info","ts":1706395974.7368307,"caller":"channelz/funcs.go:340","msg":"[core][Channel #10] Channel created","system":"grpc","grpc_log":true}
[01/27/2024 22:52:55:494 UTC] 029 JaegerBaseTest                 [jaeger]                       I {"level":"info","ts":1706395974.7369926,"caller":"channelz/funcs.go:340","msg":"[core][Channel #10] original dial target is: \":16685\"","system":"grpc","grpc_log":true}
[01/27/2024 22:52:55:494 UTC] 029 JaegerBaseTest                 [jaeger]                       I {"level":"info","ts":1706395974.737196,"caller":"channelz/funcs.go:340","msg":"[core][Channel #10] dial target \":16685\" parse failed: parse \":16685\": missing protocol scheme","system":"grpc","grpc_log":true}
[01/27/2024 22:52:55:494 UTC] 029 JaegerBaseTest                 [jaeger]                       I {"level":"info","ts":1706395974.737387,"caller":"channelz/funcs.go:340","msg":"[core][Channel #10] fallback to scheme \"passthrough\"","system":"grpc","grpc_log":true}

```

It was fixed by JaegerOperator PR#2239
