### ISSUE TITLE
Test Failure: com.ibm.ws.request.timing.hung.fat.HungRequestTiming.testHungRequestTiming_EE10_FEATURES (JDK21)

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#27651]
RTC 298426

Only occurred on Mac ARM64 TEMURIN JDK 21

```
testHungRequestTiming_EE10_FEATURES:junit.framework.AssertionFailedError: 2023-12-23-17:32:59:219 Java core are not generated 1 min apart.
at com.ibm.ws.request.timing.hung.fat.HungRequestTiming.testHungRequestTiming(HungRequestTiming.java:573)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:203)
at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:363)
at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:177)
at componenttest.rules.repeater.RepeatTests$CompositeRepeatTestActionStatement.evaluate(RepeatTests.java:145)
```

**Comment by pgunapal** [comment]
RTC defect updated with analysis.

**Comment by fmhwong** [comment]
It is still happening.  Reopen issue.
