### ISSUE TITLE
CTS: EE8: JAX-RS bucket: URI_TEMPLATE_CACHE data corruption

### ISSUE THREAD

**Issue by jkoehler22** [OpenLiberty/open-liberty#2766]
The key used for the cache map is not unique, resulting in cache containing incorrect data.  Change the key to make it unique.  Here is an example of a failing test:

[javatest.batch] ********************************************************************************
[javatest.batch] Beginning Test:  com/sun/ts/tests/jaxrs/ee/rs/ext/interceptor/containerwriter/interceptorcontext/JAXRSClient.java#getAnnotationsTest_from_standalone
[javatest.batch] ********************************************************************************
[javatest.batch] 
[javatest.batch] 03-13-2018 18:20:41:  Harness - harness.executeMode is set to "0"
[javatest.batch] 03-13-2018 18:20:41:  Harness - keywords (to be passed to tests) set to:  all
[javatest.batch] 03-13-2018 18:20:41:  Harness - sClassPathFromExecProps = 
[javatest.batch] command: com.sun.ts.lib.harness.ExecTSTestCmd -Ddeliverable.class=com.sun.ts.lib.deliverable.tck.TCKDeliverable com.sun.ts.tests.common.vehicle.VehicleClient -p /cts2.1/jaxrstck/bin/xml/../../tmp/tstest.jte -t 
[javatest.batch] ************************************************************
[javatest.batch] * props file set to "/tmp/root-cts-props.txt"
[javatest.batch] ************************************************************
[javatest.batch] 03-13-2018 18:20:41:  [JAXRSCommonClient] Test setup OK
[javatest.batch] 03-13-2018 18:20:41:  [Request] Dispatching request: 'GET http://localhost:9080/jaxrs_ee_rs_ext_interceptor_containerwriter_interceptorcontext_web/resource/getannotations' to target server at 'localhost:9080'
[javatest.batch] 03-13-2018 18:20:41:  ###############################
[javatest.batch] 03-13-2018 18:20:42:  TRACE: [WIRE] - >> GET http://localhost:9080/jaxrs_ee_rs_ext_interceptor_containerwriter_interceptorcontext_web/resource/getannotations
[javatest.batch] 03-13-2018 18:20:42:  TRACE: [WIRE] - >> Accept:*/*
[javatest.batch] 03-13-2018 18:20:43:  TRACE: [WIRE] - << 404 NOT_FOUND
[javatest.batch] 03-13-2018 18:20:43:  TRACE: [WIRE] - << Allow: GET,OPTIONS,HEAD
[javatest.batch] 03-13-2018 18:20:43:  TRACE: [WIRE] - << connection: Close
[javatest.batch] 03-13-2018 18:20:43:  TRACE: [WIRE] - << Content-Language: en-US
[javatest.batch] 03-13-2018 18:20:43:  TRACE: [WIRE] - << Content-Length: 0
[javatest.batch] 03-13-2018 18:20:43:  TRACE: [WIRE] - << Date: Tue, 13 Mar 2018 22:20:43 GMT
[javatest.batch] 03-13-2018 18:20:43:  TRACE: [WIRE] - << X-Powered-By: Servlet/4.0
[javatest.batch] 03-13-2018 18:20:43:  ERROR: [WebValidatorBase] Unexpected Status Code recieved from server.  Expected '200' received '404'
[javatest.batch] 03-13-2018 18:20:43:  ERROR: Test case throws exception: [JAXRSCommonClient] null failed!  Check output for cause of failure.
[javatest.batch] 03-13-2018 18:20:43:  ERROR: Exception at:  
[javatest.batch] 03-13-2018 18:20:43:  ERROR: com.sun.ts.tests.common.webclient.TestFailureException: Test FAILED!
[javatest.batch] 	at com.sun.ts.tests.jaxrs.common.client.JaxrsWebTestCase.execute(JaxrsWebTestCase.java:196)
[javatest.batch] 	at com.sun.ts.tests.jaxrs.common.client.JaxrsCommonClient.invoke(JaxrsCommonClient.java:199)
[javatest.batch] 	at com.sun.ts.tests.jaxrs.ee.rs.ext.interceptor.containerwriter.WriterClient.invoke(WriterClient.java:30)
[javatest.batch] 	at com.sun.ts.tests.jaxrs.ee.rs.ext.interceptor.containerwriter.interceptorcontext.JAXRSClient.getAnnotationsTest(JAXRSClient.java:61)
[javatest.batch] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[javatest.batch] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
[javatest.batch] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
[javatest.batch] 	at java.lang.reflect.Method.invoke(Method.java:508)
[javatest.batch] 	at com.sun.ts.lib.harness.EETest.run(EETest.java:550)
[javatest.batch] 	at com.sun.ts.lib.harness.ServiceEETest.run(ServiceEETest.java:113)
[javatest.batch] 	at com.sun.ts.tests.common.vehicle.EmptyVehicleRunner.run(EmptyVehicleRunner.java:30)
[javatest.batch] 	at com.sun.ts.lib.harness.ServiceEETest.run(ServiceEETest.java:102)
[javatest.batch] 	at com.sun.ts.lib.harness.EETest.getPropsReady(EETest.java:446)
[javatest.batch] 	at com.sun.ts.lib.harness.ServiceEETest.run(ServiceEETest.java:210)
[javatest.batch] 	at com.sun.ts.lib.harness.EETest.run(EETest.java:257)
[javatest.batch] 	at com.sun.ts.tests.common.vehicle.VehicleClient.main(VehicleClient.java:27)
[javatest.batch] 
[javatest.batch] 03-13-2018 18:20:43:  [JAXRSCommonClient] Test cleanup OK
[javatest.batch] STATUS:Failed.Test case throws exception: [JAXRSCommonClient] null failed!  Check output for cause of failure.
[javatest.batch] Failed. Test case throws exception: [JAXRSCommonClient] null failed!  Check output for cause of failure.
[javatest.batch] ********************************************************************************
[javatest.batch] Finished Test:  FAILED........com/sun/ts/tests/jaxrs/ee/rs/ext/interceptor/containerwriter/interceptorcontext/JAXRSClient.java#getAnnotationsTest_from_standalone

**Comment by jkoehler22** [comment]
PR: #2790

**Comment by jkoehler22** [comment]
Closing as this issue in now fixed in the TCK.
