### ISSUE TITLE
Plugin Merge Tool "Error encountered, no merged file was written"

### ISSUE THREAD

**Issue by emanuel2258** [OpenLiberty/open-liberty#27669]
**Describe the bug**  

```
java.lang.RuntimeException: java.lang.RuntimeException: Error encountered, no merged file was written
    at com.ibm.ws.http.plugin.merge.internal.PluginMergeToolImpl.merge(PluginMergeToolImpl.java:797)
    at com.ibm.ws.webserver.plugin.utility.tasks.MergePluginFilesTask.merge(MergePluginFilesTask.java:204)
    at com.ibm.ws.webserver.plugin.utility.tasks.MergePluginFilesTask.mergePluginFilesFromDir(MergePluginFilesTask.java:196)
    at com.ibm.ws.webserver.plugin.utility.tasks.MergePluginFilesTask.execute(MergePluginFilesTask.java:64)
    at com.ibm.ws.webserver.plugin.utility.WebServerPluginUtility.runProgram(WebServerPluginUtility.java:103)
    at com.ibm.ws.webserver.plugin.utility.WebServerPluginUtility.main(WebServerPluginUtility.java:146)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
    at java.lang.reflect.Method.invoke(Method.java:508)
    at com.ibm.ws.kernel.boot.cmdline.UtilityMain.internal_main(UtilityMain.java:175)
    at com.ibm.ws.kernel.boot.cmdline.UtilityMain.main(UtilityMain.java:55)
    at com.ibm.ws.kernel.boot.cmdline.Main.main(Main.java:54)
Caused by: java.lang.RuntimeException: Error encountered, no merged file was written
    at com.ibm.ws.http.plugin.merge.internal.PluginMergeToolImpl.merge(PluginMergeToolImpl.java:793)
    ... 12 more
```
**Steps to Reproduce**  
Steps to reproduce the bug

**Expected behavior**  

**Diagnostic information:**  
 - OpenLiberty Version: [e.g. 21.0.0.8 - 21.0.0.10]
 - Affected feature(s) [e.g. mpHealth-3.0]
 - Java Version: [i.e. full output of `java -version`]
 - server.xml configuration (WITHOUT sensitive information like passwords)
 - If it would be useful, upload the messages.log file found in `$WLP_OUTPUT_DIR/messages.log`

**Additional context**

**Comment by emanuel2258** [comment]
Test fix's PR https://github.ibm.com/websphere/open-liberty-service/pull/1073#issuecomment-73139797

**Comment by emanuel2258** [comment]
No longer need this issue as the code changes are not needed anymore.
