### ISSUE TITLE
Test Failure: com.ibm.ws.logging.fat.TestHideMessages.testEmptyHideMessageAttribute

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#27874]
RTC 295597

```
testEmptyHideMessageAttribute:java.lang.Exception: 2023-04-17-17:14:42:127 Errors/warnings were found in server com.ibm.ws.logging.hidemessage logs:
<br>[4/17/23, 17:14:41:418 PDT] 00000034 com.ibm.ws.runtime.update.internal.RuntimeUpdateManagerImpl  W CWWKE1102W: The quiesce operation did not complete. The server will now stop.
<br>[4/17/23, 17:14:41:418 PDT] 00000034 com.ibm.ws.runtime.update.internal.RuntimeUpdateManagerImpl  W CWWKE1105W: 2 runtime updates did not complete during the quiesce period.
    at componenttest.topology.impl.LibertyServer.checkLogsForErrorsAndWarnings(LibertyServer.java:3108)
    at componenttest.topology.impl.LibertyServer.stopServer(LibertyServer.java:2967)
    at componenttest.topology.impl.LibertyServer.stopServer(LibertyServer.java:2850)
    at componenttest.topology.impl.LibertyServer.stopServer(LibertyServer.java:2759)
    at componenttest.topology.impl.LibertyServer.stopServer(LibertyServer.java:2734)
    at com.ibm.ws.logging.fat.TestHideMessages.cleanupTest(TestHideMessages.java:171)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:204)
    at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:364)
    at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:178)
```

The frequency of this problem is about once per month.

**Comment by tonyreigns** [comment]
This test failure hasn't reoccured since merging my fix, closing the issue.
