### ISSUE TITLE
NullPointerException can occur in Kernel ClassLoader

### ISSUE THREAD

**Issue by jhanders34** [OpenLiberty/open-liberty#27886]
**Describe the bug**  
NullPointerException is possible in Kernel Classloader

java.lang.NullPointerException
	at com.ibm.ws.kernel.internal.classloader.JarFileClassLoader.findClass(JarFileClassLoader.java:165)
	at com.ibm.ws.kernel.internal.classloader.BootstrapChildFirstJarClassloader.loadClass(BootstrapChildFirstJarClassloader.java:92)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1075)
	at org.eclipse.osgi.internal.loader.SystemBundleLoader.findLocalClass(SystemBundleLoader.java:63)
	at org.eclipse.osgi.internal.loader.sources.SingleSourcePackage.loadClass(SingleSourcePackage.java:41)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass0(BundleLoader.java:479)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:416)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:168)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1075)

**Steps to Reproduce**  
An IOException has to happen when trying to load a class or the manifest of the Jar that contains the class.

**Expected behavior**  
The ClassLoader code should not throw a NullPointerException.  It should return null in this case when the returnNull parameter is passed with a true value instead of throwing null.

**Diagnostic information:**  
 - OpenLiberty Version: 19.0.0.1 - 24.0.0.3

**Additional context**  
This problem was introduced due to the changes in PR #5808.

**Comment by jhanders34** [comment]
#regresion

**Comment by jhanders34** [comment]
#regression
