### ISSUE TITLE
Overflowing the usecount of the OSGi service

### ISSUE THREAD

**Issue by una-tapa** [OpenLiberty/open-liberty#28248]
**Describe the bug**  

User authentication no longer works after the following error. 
The org.osgi.framework.ServiceException: The use count for the service overflowed. 

The following FFDC was created.

4/6/24, 7:54:13:805 EDT] 01998087 com.ibm.ws.logging.internal.impl.IncidentImpl        I FFDC1015I: An FFDC Incident has been created: "org.osgi.framework.ServiceException: The use count for the service overflowed. com.ibm.ws.security.authentication.jaas.modules.UsernameAndPasswordLoginModule 116" at ffdc_24.04.06_07.54.13.0.log

Full error stack in the FFDC
```
Stack Dump = org.osgi.framework.ServiceException: The use count for the service overflowed.
	at org.eclipse.osgi.internal.serviceregistry.ServiceUse.incrementUse(ServiceUse.java:197)
	at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.getService(ServiceFactoryUse.java:93)
	at org.eclipse.osgi.internal.serviceregistry.ServiceConsumer$2.getService(ServiceConsumer.java:48)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.getService(ServiceRegistrationImpl.java:568)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.getService(ServiceRegistry.java:542)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.getService(BundleContextImpl.java:660)
	at com.ibm.ws.security.authentication.jaas.modules.LoginModuleHelper.getJAASService(LoginModuleHelper.java:38)
	at com.ibm.ws.security.authentication.internal.jaas.modules.ServerCommonLoginModule.getAuthenticationService(ServerCommonLoginModule.java:85)
	at com.ibm.ws.security.authentication.jaas.modules.UsernameAndPasswordLoginModule.login(UsernameAndPasswordLoginModule.java:85)
	at com.ibm.ws.kernel.boot.security.LoginModuleProxy.login(LoginModuleProxy.java:53)
	at java.base/javax.security.auth.login.LoginContext.invoke(Unknown Source)
	at java.base/javax.security.auth.login.LoginContext$4.run(Unknown Source)
	at java.base/javax.security.auth.login.LoginContext$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/javax.security.auth.login.LoginContext.invokePriv(Unknown Source)
	at java.base/javax.security.auth.login.LoginContext.login(Unknown Source)
	at com.ibm.ws.security.authentication.internal.jaas.JAASServiceImpl.doLoginContext(JAASServiceImpl.java:369)
	at com.ibm.ws.security.authentication.internal.jaas.JAASServiceImpl.performLogin(JAASServiceImpl.java:355)
	at com.ibm.ws.security.authentication.internal.jaas.JAASServiceImpl.performLogin(JAASServiceImpl.java:340)
	at com.ibm.ws.security.authentication.internal.AuthenticationServiceImpl.performJAASLogin(AuthenticationServiceImpl.java:558)
	at com.ibm.ws.security.authentication.internal.AuthenticationServiceImpl.authenticate(AuthenticationServiceImpl.java:223)
	at com.ibm.ws.webcontainer.security.internal.BasicAuthAuthenticator.basicAuthenticate(BasicAuthAuthenticator.java:130)
	at com.ibm.ws.webcontainer.security.internal.BasicAuthAuthenticator.handleBasicAuth(BasicAuthAuthenticator.java:121)
	at com.ibm.ws.webcontainer.security.internal.BasicAuthAuthenticator.authenticate(BasicAuthAuthenticator.java:74)
	at com.ibm.ws.webcontainer.security.WebAuthenticatorProxy.authenticate(WebAuthenticatorProxy.java:103)
	at com.ibm.ws.webcontainer.security.WebAppSecurityCollaboratorImpl.authenticateRequest(WebAppSecurityCollaboratorImpl.java:1239)
	at com.ibm.ws.webcontainer.security.WebAppSecurityCollaboratorImpl.determineWebReply(WebAppSecurityCollaboratorImpl.java:995)
	at com.ibm.ws.webcontainer.security.WebAppSecurityCollaboratorImpl.performSecurityChecks(WebAppSecurityCollaboratorImpl.java:695)
	at com.ibm.ws.webcontainer.security.WebAppSecurityCollaboratorImpl.preInvoke(WebAppSecurityCollaboratorImpl.java:622)
	at com.ibm.wsspi.webcontainer.collaborator.CollaboratorHelper.preInvokeCollaborators(CollaboratorHelper.java:472)
	at com.ibm.ws.webcontainer.osgi.collaborator.CollaboratorHelperImpl.preInvokeCollaborators(CollaboratorHelperImpl.java:290)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1221)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1077)
	at com.ibm.ws.webcontainer.servlet.CacheServletWrapper.handleRequest(CacheServletWrapper.java:77)
	at com.ibm.ws.webcontainer40.servlet.CacheServletWrapper40.handleRequest(CacheServletWrapper40.java:87)
	at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:969)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:283)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1248)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:470)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:429)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:569)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:503)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:363)
	at com.ibm.ws.http.channel.internal.inbound.HttpICLReadCallback.complete(HttpICLReadCallback.java:72)
	at com.ibm.ws.channel.ssl.internal.SSLReadServiceContext$SSLReadCompletedCallback.complete(SSLReadServiceContext.java:1826)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:516)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueManager.java:586)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:970)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:1059)
	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:247)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Steps to Reproduce**  
Reproduction steps are unknown. 

**Expected behavior**  
No error should be thrown. 

**Diagnostic information:**  
 - OpenLiberty Version: 23.0.0.9  (Reported Liberty level) 
 - Affected feature(s) [appSecurity-x.0]

**Additional context**  

The error message indicates a particular code path has run over 2147483647 (Integer.MAX_VALUE) times.  The code always gets the service, but never ungets it so the use count rises for the service instance until it overflows the max usecount.  

The fix is to use a utility that caches the service instance to avoid getting it over and over which avoid raising the use count each call.  

The root cause of this error is unknown. 
It is suspected that session related activities may be related to this error because prior to "org.osgi.framework.ServiceException", the following Session related warning repeatedly appeared in the log. (More than 200k times over 2 month period) 

[4/5/24, 15:25:35:082 EDT] 0193b788 com.ibm.ws.session.WASSessionCore                            W **SESN0116W:** Session identifier 0000JbjY2tRYbAnjT18YT1ZGzT1:fd83d56f-ce12-41ba-87b9-3d02f6f0e48b:5ba33e84-b0c4-4d72-851d-4402026eda38:1adbc3f5-092e-4761-a2d6-8da3a53b595f:bc7112c5-ad99-4eb0-bb4a-f3ef1f95d386:6956ffa6-942f- .... b53-0ffc12609cda has exceeded the maximum length limit of 1024.

**Comment by una-tapa** [comment]
fixes https://github.com/OpenLiberty/open-liberty/pull/28224

**Comment by una-tapa** [comment]
Based on our internal discussion ([private link](https://ibm-cloud.slack.com/archives/C30NGRU48/p1728494042879409)), I have added the release:24005.
