### ISSUE TITLE
JPQLException Syntax error parsing

### ISSUE THREAD

**Issue by ajaypaul-ibm** [OpenLiberty/open-liberty#28285]
Intermittently, a PersistenceException may be thrown from EclipseLink when starting an application while parsing the JPQL named queries. This issue may arise from the asynchronous startup of the servers. For reference, the stack trace observed:

```
org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.createDeployFailedPersistenceException(EntityManagerSetupImpl.java:897)
    at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.deploy(EntityManagerSetupImpl.java:837)
    at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.getAbstractSession(EntityManagerFactoryDelegate.java:207)
    at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.getDatabaseSession(EntityManagerFactoryDelegate.java:185)
    at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.getDatabaseSession(EntityManagerFactoryImpl.java:528)
    at org.eclipse.persistence.jpa.PersistenceProvider.createContainerEntityManagerFactoryImpl(PersistenceProvider.java:372)
    at org.eclipse.persistence.jpa.PersistenceProvider.createContainerEntityManagerFactory(PersistenceProvider.java:305)
    at com.ibm.ws.jpa.management.JPAPUnitInfo.createEMFactory(JPAPUnitInfo.java:919)
    at com.ibm.ws.jpa.management.JPAPUnitInfo.initialize(JPAPUnitInfo.java:766)
    at com.ibm.ws.jpa.management.JPAPxmlInfo.extractPersistenceUnits(JPAPxmlInfo.java:183)
    at com.ibm.ws.jpa.management.JPAScopeInfo.processPersistenceUnit(JPAScopeInfo.java:89)
    at com.ibm.ws.jpa.management.JPAApplInfo.addPersistenceUnits(JPAApplInfo.java:120)
    at com.ibm.ws.jpa.container.osgi.internal.JPAComponentImpl.processWebModulePersistenceXml(JPAComponentImpl.java:517)
    at com.ibm.ws.jpa.container.osgi.internal.JPAComponentImpl.applicationStarting(JPAComponentImpl.java:304)
Caused by: ... [EclipseLink-0] (Eclipse Persistence Services - 2.6.8.WAS-v20191015-5b6c763): org.eclipse.persistence.exceptions.JPQLException
... Syntax error parsing [            *******        ]. 
[34, 34] The select item is missing from the result variable declaration.
[33, 34] The SELECT clause has 'xxxx' and 'xxxxxxxx' that are not separated by a comma.
    at org.eclipse.persistence.internal.jpa.jpql.HermesParser.buildException(HermesParser.java:155)
    at org.eclipse.persistence.internal.jpa.jpql.HermesParser.validate(HermesParser.java:334)
    at org.eclipse.persistence.internal.jpa.jpql.HermesParser.populateQueryImp(HermesParser.java:278)
    at org.eclipse.persistence.internal.jpa.jpql.HermesParser.buildQuery(HermesParser.java:163)
    at org.eclipse.persistence.internal.jpa.EJBQueryImpl.buildEJBQLDatabaseQuery(EJBQueryImpl.java:142)
    at org.eclipse.persistence.internal.jpa.JPAQuery.processJPQLQuery(JPAQuery.java:223)
    at org.eclipse.persistence.internal.jpa.JPAQuery.prepare(JPAQuery.java:184)
    at org.eclipse.persistence.queries.DatabaseQuery.prepareInternal(DatabaseQuery.java:628)
    at org.eclipse.persistence.internal.sessions.AbstractSession.processJPAQuery(AbstractSession.java:4389) 
```
As a serviceability improvement, the JPA Container should be updated to improve handling of the error by implementing a retry mechanism whenever a syntax exception occurs for this scenario, and logging additional diagnostics. This may workaround the issue, but will also provide additional diagnostic information to help determine the underlying cause.

**Note:** this error occurs when the `persistence.xml` file contains named queries and the following EclipseLink property:
```
<property name="eclipselink.deploy-on-startup" value="true" />
```

**Comment by ajaypaul-ibm** [comment]
PR is merged and changes have gone to release. Closing this issue.
