### ISSUE TITLE
+third-party doesn't seem to add internals of xmlBinding-4.0

### ISSUE THREAD

**Issue by danpfe** [OpenLiberty/open-liberty#28408]
**Describe the bug**  
An application trying to access libraries inside the JAXB reference implementation is not able to do so even though apiTypeVisibility has been configured accordingly.

Application fails with following:

[ERROR   ] SRVE0777E: Exception thrown by application class 'java.lang.ClassLoader.defineClass1:-2'
java.lang.NoClassDefFoundError: org/glassfish/jaxb/runtime/marshaller/NamespacePrefixMapper
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027)
        at com.ibm.ws.classloading.internal.AppClassLoader.definePackageAndClass(AppClassLoader.java:435)
        at [internal classes]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:421)
        at java.base/java.lang.Class.forName(Class.java:412)
        at org.docx4j.jaxb.NamespacePrefixMapperUtils.tryUsingRI(NamespacePrefixMapperUtils.java:69)
        at org.docx4j.jaxb.NamespacePrefixMapperUtils.getPrefixMapper(NamespacePrefixMapperUtils.java:61)
        at org.docx4j.openpackaging.contenttype.ContentTypeManager.marshal(ContentTypeManager.java:961)
        at org.docx4j.openpackaging.io3.stores.ZipPartStore.saveContentTypes(ZipPartStore.java:259)
        at org.docx4j.openpackaging.io3.Save.save(Save.java:178)
        at org.docx4j.openpackaging.packages.OpcPackage.save(OpcPackage.java:799)
        at org.docx4j.openpackaging.packages.OpcPackage.save(OpcPackage.java:729)
        at org.docx4j.openpackaging.packages.OpcPackage.save(OpcPackage.java:717)
        at io.whistler.docxwar.GenerateDocument.doGet(GenerateDocument.java:29)
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:527)
        at [internal classes]

**Steps to Reproduce**  
Create a Word document using Docx4j (which in turn uses Glassfish's JAXB-implementation to generate the XML files, which I verified is also used in OpenLiberty), example is found at https://github.com/danpfe/ol-third-party. Download the git-repo, build using `mvn package liberty:deploy` and start the server by `./target/liberty/wlp/server run`. In the end simply curl http://localhost:8080/gendoc/generate and observe the error log. 

**Expected behavior**  
Since +third-party (also tried to explicitly specifying `spec, ibm-api, stable, third-party`) is added to the classpath, I expect the application to see the classes JAXB provides, which I checked exist in OpenLiberty.

**Diagnostic information:**  
 - OpenLiberty Version: 24.0.0.4
 - Affected feature(s): xmlBinding-4.0
 - Java Version: OpenJDK Runtime Environment Temurin-21.0.3+9 (build 21.0.3+9-LTS)
 - server.xml configuration: Present in example

**Additional context**  
A simple example can be downloaded at https://github.com/danpfe/ol-third-party. As Docx4j seems to write a couple of bytes to the OutputStream the error handling is a bit wonky, but that is besides the point to showcase the actual issue.

**Comment by jhanders34** [comment]
Presently the jaxb / xmlBinding features in liberty do not expose any third party packages as seen in their feature documentation on openliberty.io/docs.  We are tracking a similar issue with #28019 for the work to expose the sun / glassfish implementation packages that should be exposed as third party.

**Comment by neuwerk** [comment]
@danpfe thanks for raising the issue! This is intentional by design to prevent dependency on our platforms implementation, that being said, we have a lot of questions about using the JAXB/XML Binding reference implementation APIs  as third-party APIs on Open Liberty. There are good reasons for why you should be able to access them  if you want them, so much so that if you were to open a new [feature request ](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=&labels=Feature+Request%3A+External&projects=&template=02_feature_request.md&title=) I am fairly confident it would be accepted. 

Aside from that, the only alternative if you need the XML Binding spec and Glassfish RI is to package them as a shared library or within your application, and not enable our xmlBinding-4.0 feature in your sever.xml.

**Comment by danpfe** [comment]
I understand that completely. Was a bit disappointed myself that the library in question doesn't function without accessing internals... yet, here we are :). I will post a feature request and will try to proceed as suggested. Thank you!
