### ISSUE TITLE
Warning "Validation not enabled for module" when <feature>persistenceContainer-3.1</feature> + <feature>beanValidation-3.0</feature>

### ISSUE THREAD

**Issue by ghost** [OpenLiberty/open-liberty#28515]
**Describe the bug**  
In Server.xml declaring : 
```xml
<feature>persistenceContainer-3.1</feature>
<feature>beanValidation-3.0</feature>
```

and using as JPA implementation :

```xml
<groupId>org.hibernate</groupId>
<artifactId>hibernate-core</artifactId>
<version>6.4.3.Final</version> 
```
implies, for each jpa entities during application startup, many messages : 

```
[5/22/24, 17:27:56:118 CEST] 00000070 id=         org.hibernate.boot.beanvalidation.TypeSafeActivator          W applyRelationalConstraints HHH000274: Unable to apply constraints on DDL for com.packagename.common.entity.MyEntity
jakarta.validation.ValidationException: Validation not enabled for module myApp-ear-0.0.1-SNAPSHOT-liberty
	at com.ibm.ws.beanvalidation.OSGiBeanValidationImpl.getValidatorFactoryHVProvider(OSGiBeanValidationImpl.java:152)
	at com.ibm.ws.beanvalidation.OSGiBeanValidationImpl.getValidatorFactory(OSGiBeanValidationImpl.java:142)
	at com.ibm.ws.beanvalidation.OSGiBeanValidationImpl.getValidatorFactory(OSGiBeanValidationImpl.java:132)
	at com.ibm.ws.beanvalidation.OSGiBeanValidationImpl.getValidatorFactory(OSGiBeanValidationImpl.java:127)
	at com.ibm.ws.beanvalidation.AbstractBeanValidation.getValidatorFactory(AbstractBeanValidation.java:76)
	at com.ibm.ws.beanvalidation.AbstractBeanValidation.getValidatorFactoryOrDefault(AbstractBeanValidation.java:87)
	at com.ibm.ws.jpa.container.beanvalidation.JPABV20ComponentImpl.getValidatorFactory(JPABV20ComponentImpl.java:45)
	at com.ibm.ws.jpa.container.beanvalidation.JPAValidator.obtainValidator(JPAValidator.java:177)
	at com.ibm.ws.jpa.container.beanvalidation.JPAValidator.getConstraintsForClass(JPAValidator.java:235)
	at org.hibernate.boot.beanvalidation.TypeSafeActivator.applyDDL(TypeSafeActivator.java:205)
	at org.hibernate.boot.beanvalidation.TypeSafeActivator.applyRelationalConstraints(TypeSafeActivator.java:189)
at org.hibernate.boot.beanvalidation.TypeSafeActivator.applyRelationalConstraints(TypeSafeActivator.java:148)
at org.hibernate.boot.beanvalidation.TypeSafeActivator.activate(TypeSafeActivator.java:97)
at jdk.internal.reflect.GeneratedMethodAccessor873.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.hibernate.boot.beanvalidation.BeanValidationIntegrator.integrate(BeanValidationIntegrator.java:139)
at org.hibernate.internal.SessionFactoryImpl.integrate(SessionFactoryImpl.java:506)
at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:269)
at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:450)
at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1507)
at org.hibernate.jpa.HibernatePersistenceProvider.createContainerEntityManagerFactory(HibernatePersistenceProvider.java:142)
at com.ibm.ws.jpa.management.JPAPUnitInfo.createEMFactory(JPAPUnitInfo.java:984)
at com.ibm.ws.jpa.management.JPAPUnitInfo.initialize(JPAPUnitInfo.java:819)
at com.ibm.ws.jpa.management.JPAPxmlInfo.extractPersistenceUnits(JPAPxmlInfo.java:190)
at com.ibm.ws.jpa.management.JPAScopeInfo.processPersistenceUnit(JPAScopeInfo.java:90)
at com.ibm.ws.jpa.management.JPAApplInfo.addPersistenceUnits(JPAApplInfo.java:121)
at com.ibm.ws.jpa.container.osgi.internal.JPAComponentImpl.processLibraryJarPersistenceXml(JPAComponentImpl.java:548)
at com.ibm.ws.jpa.container.osgi.internal.JPAComponentImpl.applicationStarting(JPAComponentImpl.java:333)
at com.ibm.ws.container.service.state.internal.ApplicationStateManager.fireStarting(ApplicationStateManager.java:53)
at com.ibm.ws.container.service.state.internal.StateChangeServiceImpl.fireApplicationStarting(StateChangeServiceImpl.java:52)
at com.ibm.ws.app.manager.module.internal.SimpleDeployedAppInfoBase.preDeployApp(SimpleDeployedAppInfoBase.java:550)
at com.ibm.ws.app.manager.module.internal.SimpleDeployedAppInfoBase.installApp(SimpleDeployedAppInfoBase.java:511)
at com.ibm.ws.app.manager.module.internal.DeployedAppInfoBase.deployApp(DeployedAppInfoBase.java:625)
at com.ibm.ws.app.manager.ear.internal.EARApplicationHandlerImpl.install(EARApplicationHandlerImpl.java:79)
at com.ibm.ws.app.manager.internal.statemachine.StartAction.execute(StartAction.java:189)
at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.enterState(ApplicationStateMachineImpl.java:1369)
at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.run(ApplicationStateMachineImpl.java:912)
at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:280)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:857)
```

**Steps to Reproduce**  
See above for server.xml and pom.xml, declaring some JPA entities having ` <property name="hibernate.hbm2ddl.auto" value="update" />` in persistence.xml

**Expected behavior**  
No warning messages during application startup

**Diagnostic information:**  
 - OpenLiberty Version: 24.0.0.5
 - Affected feature(s) : persistenceContainer-3.1 with beanValidation-3.0
 - Java Version: JDK 17 (open j9)
 - server.xml see features above.

**Additional context**  
Our diagnose is that open liberty "beanValidation-3.0" relies on hibernate validator v7.x (regarding OL logs). If removing "beanValidation-3.0" feature, but adding hibernate validator v8.x packaged within application ear, seems to solve the issue (hibernate validator documentation describes that v8.X is dedicated to Jakarta EE 10, but v7.x is dedicated to Jakarta EE 9).

**Comment by mswatosh** [comment]
The `beanValidation-3.0` feature is compatible with both EE9 and EE10, so instead of using Hibernate Validator 8 for EE10, we handle compatibility in Open Liberty while using Hibernate Validator 7. This error is coming out of the integration layer between Open Liberty and Hibernate Validator, which isn't present when packaging Hibernate Validator with the application. I'll use the information you provided to attempt a recreate locally.

**Comment by ghost** [comment]
Thank for your reply, if may help for local recreate, here is our full persistence.xml (remaining v2.1 grammar) file ; the most important keys to allow OL+Hibernate Core working together are for us : `hibernate.delay_cdi_access`, `hibernate.enhancer.enableDirtyTracking` and `hibernate.enhancer.enableLazyInitialization` (else OL+featureCDI 4.0+Hibernate fails to start with various errors).
Kind regards,

```xml
<persistence version="2.1" xmlns="http://xmlns.jcp.org/xml/ns/persistence" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/persistence http://xmlns.jcp.org/xml/ns/persistence/persistence_2_1.xsd">

	<persistence-unit name="defaultPersistenceUnit" transaction-type="JTA">
        <provider>org.hibernate.jpa.HibernatePersistenceProvider</provider>

        <jta-data-source>jdbc/SampleJPADatabase</jta-data-source>
	
        <class> ...here the list of all project's entities ...</class>

        <properties>
		<property name="hibernate.archive.autodetection" value="class, hbm" />
                <property name="hibernate.delay_cdi_access" value="true"/>
		<property name="showSql" value="true" />
		<property name="generateDdl" value="true" />
		<property name="hibernate.show_sql" value="true" />
		<property name="hibernate.format_sql" value="true" />
		<property name="use_sql_comments" value="true" />
		<property name="hibernate.dialect" value="org.hibernate.dialect.H2Dialect" />
		<property name="hibernate.hbm2ddl.auto" value="update" />
		<property name="hibernate.enhancer.enableDirtyTracking" value="false"/>
		<property name="hibernate.enhancer.enableLazyInitialization" value="false"/>
	</properties>

	</persistence-unit>
</persistence>
```
