### ISSUE TITLE
Regression with jaxb / WADL2java

### ISSUE THREAD

**Issue by pnickoll** [OpenLiberty/open-liberty#28615]
I am trying to execute WADL2Java (in the bin/jaxrs directory)

In Liberty 24.0.0.1 this works but in Liberty 24.0.0.3 it doesn't (not tested on 24.0.0.2 - but can if it is helpful)

I get the following exception (with verbose turned on)

```
wadl2java - Apache CXF 3.1.18


WADLToJava Error: java.lang.IllegalStateException: Unable to create schema compiler

org.apache.cxf.tools.common.ToolException: java.lang.IllegalStateException: Unable to create schema compiler
        at org.apache.cxf.tools.wadlto.jaxrs.JAXRSContainer.execute(JAXRSContainer.java:89)
        at org.apache.cxf.tools.common.toolspec.ToolRunner.runTool(ToolRunner.java:105)
        at org.apache.cxf.tools.wadlto.WADLToJava.run(WADLToJava.java:65)
        at org.apache.cxf.tools.wadlto.WADLToJava.run(WADLToJava.java:57)
        at com.ibm.ws.jaxrs20.tools.WADL2JavaTool.main(WADL2JavaTool.java:57)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
        at java.lang.reflect.Method.invoke(Method.java:508)
        at com.ibm.ws.kernel.boot.cmdline.UtilityMain.internal_main(UtilityMain.java:175)
        at com.ibm.ws.kernel.boot.cmdline.UtilityMain.main(UtilityMain.java:55)
        at com.ibm.ws.kernel.boot.cmdline.Main.main(Main.java:54)
Caused by: java.lang.IllegalStateException: Unable to create schema compiler
        at org.apache.cxf.common.jaxb.JAXBUtils.createSchemaCompilerWithDefaultAllocator(JAXBUtils.java:743)
        at org.apache.cxf.tools.wadlto.jaxrs.SourceGenerator.createCompiler(SourceGenerator.java:1918)
        at org.apache.cxf.tools.wadlto.jaxrs.SourceGenerator.createCodeModel(SourceGenerator.java:1895)
        at org.apache.cxf.tools.wadlto.jaxrs.SourceGenerator.generateSchemaCodeAndInfo(SourceGenerator.java:311)
        at org.apache.cxf.tools.wadlto.jaxrs.SourceGenerator.generateSource(SourceGenerator.java:299)
        at org.apache.cxf.tools.wadlto.jaxrs.JAXRSContainer.processWadl(JAXRSContainer.java:183)
        at org.apache.cxf.tools.wadlto.jaxrs.JAXRSContainer.execute(JAXRSContainer.java:72)
        at org.apache.cxf.tools.wadlto.jaxrs.JAXRSContainer.execute(JAXRSContainer.java:81)
        ... 11 more
Caused by: javax.xml.bind.JAXBException
 - with linked exception:
[java.lang.ClassNotFoundException: com.sun.tools.internal.xjc.api.XJC]
        at org.apache.cxf.common.jaxb.JAXBUtils.createSchemaCompiler(JAXBUtils.java:728)
        at org.apache.cxf.common.jaxb.JAXBUtils.createSchemaCompilerWithDefaultAllocator(JAXBUtils.java:735)
        ... 18 more
Caused by: java.lang.ClassNotFoundException: com.sun.tools.internal.xjc.api.XJC
        at java.lang.Class.forNameImpl(Native Method)
        at java.lang.Class.forName(Class.java:403)
        at org.apache.cxf.common.jaxb.JAXBUtils.createSchemaCompiler(JAXBUtils.java:721)
```

When I look at [JAXBUtils](https://github.com/OpenLiberty/open-liberty/blob/1cb0fb529beae353806c8567bf4cacd8e198a436/dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/common/jaxb/JAXBUtils.java#L754) I see this :

```
            try {
                cls = Class.forName("com.sun.tools.xjc.api.XJC");
                sc = cls.getMethod("createSchemaCompiler").invoke(null);
            } catch (Throwable e) {
                if (LOG.isLoggable(Level.FINEST)) { 
                    LOG.finest("createSchemaCompiler: Caught Throwable: " + e);  // Liberty Change
                }
                cls = Class.forName("com.sun.tools.internal.xjc.api.XJC", true, getXJCClassLoader());
                sc = cls.getMethod("createSchemaCompiler").invoke(null);
            }
```

First it tries to look for _com.sun.tools.xjc.api.XJC_ and then for _com.sun.tools.internal.xjc.api.XJC_ The only class liberty ships is the first of those. From what I can see it is still exported from the _com.ibm.ws.jaxb.tools_  bundle. Could this be related to jaxb changing from version 2.2.10 to a non numbered version?

**Comment by tevans78** [comment]
#regression

**Comment by neuwerk** [comment]
It is for sure related to the upgrade of JAXB I did that went into 24.0.0.2. I'll see what I can find out.

**Comment by soilworker01** [comment]
Maybe similar issue like [CharacterEscapeHandler is not working on liberty](https://github.com/OpenLiberty/open-liberty/issues/28019)?

**Comment by neuwerk** [comment]
@pnickoll  I tested my changes in #28632 against both the `Web Profile-8.0` and `EE 8` images of Open Liberty, and it resolved both issues with `wadl2java`. I merged this fix this morning, so I'm going to close out the issue. Let me know if there are any issues going forward.
