### ISSUE TITLE
Resolve Jakarta Persistence 3.2 timestamp failures in jpa-beanvalidation FAT

### ISSUE THREAD

**Issue by tkburroughs** [OpenLiberty/open-liberty#28659]
It appears that EclipseLink 5.0 (for Persistence 3.2) has changed the default field to column mapping for fields of type Timestamp to a Timestamp column rather than a Blob column.  Need to identify the cause of the change, verify it was intentional (and not just a bug) and update migration impacts if it is intentional

Then, need to re-enable and correct the following tests:

Multiple tests in `com.ibm.ws.jpa.tests.beanvalidation_jpa_3.2_fat` fail with the following error:
```
java.lang.Exception: See nested Throwable
jakarta.ejb.EJBException: See nested exception; nested exception is: java.lang.Exception: See nested Throwable
at com.ibm.ejs.container.util.ExceptionUUtil.EJBException(ExceptionUtil.java:401)

at com.ibm.ejs.container.util.ExceptionUtil.EJBExceptionn(ExceptionUtil.java:287)
at com.ibm.ejs.container.BusinessExceptionMappingStrategy.mapException(BusinessExceptionMappingStrategy.java:349)
at com.ibm.ejs.container.BusinessExceptionMappingStrategy.setUncheckedException(BusinessExceptionMappingStrategy.java:521)
at com.ibm.ejs.container.EJSDeployedSupport.setUncheckedLocalExxception(EJSDeployedSupport.java:451)
at com.ibm.ws.jpa.beanvalidation20.ejblocal.EJSLocal0SFBeanValidation20SFEJB_0adfe5ba.executeTestLogic(EJSLocal0SFBeanValidation20SFEJB_0adfe5ba.java)
at com.ibm.ws.testtooling.vehicle.web.EJBDBTestVehicleServlet.executeTestVehicle(EJBDBTestVehicleServlet.java:39)

at com.ibm.ws.testtooling.vehicle.web.EJBDBTestVehicleServlet.execcuteTestVehicle(EJBDBTestVehicleServlet.java:28)
at com.ibm.ws.testtooling.vehicle.web.JPATestServlet.executeTest(JPATestServlet.java:140)

at com.ibm.ws.testtooling.vehicle.web.JPATesstServlet.executeTest(JPATestServlet.java:124)
at com.ibm.ws.testtooling.vehicle.web.JPATestServlet.executeTest(JPATestServlet.java:117)
at com.ibm.ws.jpa.beanvalidation20.ejb.TestBeeanValidation20_EJB_SF_Servlet.jpa_beanvalidation_testBeanValidationXML004_EJB_SF_CMTS_Web(TestBeanValidation20_EJB_SF_Servlet.java:251)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMetthodAccessorImpl.java:43)
at componenttest.app.FATServlet.doGet(FATServlet.jjava:74)
at com.ibm.ws.testtooling.vehicle.web.JPATestServlet.doGet(JPATestServlet.jjava:113)
at jakarta.servlet.http.HtttpServlet.service(HttpServlet.java:633)
at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:723)
at com.ibm.ws.webcontainer.servlet.ServletWrapper.serrvice(ServletWrapper.java:1266)
at com.ibm.ws.webcoontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:754)
at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:451)
at com.ibm.ws.webcontainer.filter.WebAppFilterManager..invokeFilters(WebAppFilterManager.java:1362)
at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1078)
at com.ibm.ws.webcontainer.servlet.CacheServletWrapper.handleRequest(CacheServletWrapper.java:77)
at com.ibm.ws.webcontainer40.servlet.CacheServletWrapper40.handleRequest(CacheServletWrapper40.java:87)
at com.ibm.ws.webcontainer.WeebContainer.handleRequest(WebContainer.java:978)
at com.ibm.ws.webcontainer.ossgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:293)
at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1260)
at com.ibm.ws.http.dispatcher.internal.channel.HttpDDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:476)
at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:435)
at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:5699)
at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HHttpInboundLink.java:503)
at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java::363)
at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.ready(HttpInboundLink.java:330)
at com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.sendToDiscriminators(NewConnectionInitialReadCallbacck.java:169)
at com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.complete(NewConnectionInitialReadCallback.java:77)
at com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:516)
at com.ibm.ws.tcpchannel.internal.WWorkQueueManager.attemptIO(WorkQueueManager.java:586)
at com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:970)
at com.ibm.ws.tcpchannel.internal.WorkQueueManager$WWorker.run(WorkQueueManager.java:1059)
at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorrServiceImpl.java:280)
at java.base/java.util.concurrent.ThreadPoolExxecutor.runWorker(ThreadPoolExecutor.java:1136)

at java.base/java.util.cooncurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.jaava:857)
Caused by: java.lang.Exception: See nested Throwable
at com.ibm.ejs.container.util.ExceptionUtil.Exception(ExceptionUtil.java:269)
Caused by: java.lang.AssertionError: TestServlet Caught Exception: com.ibm.ws.testtooling.tranjacket.TransactionJacketException: jakarta.transaction.RollbackException
com.ibm.ws.testtooling.tranjacket.TransactionJacketException: jakarta.transaction.RollbackException
at com.ibm.ws.testtooling.tranjacket.JTATransactionJacket.commitTransaction(JTATransactionJacket.java:49)
at com.ibm.ws.jpa.beanvalidation20.testlogic.BeannValidation20Logic.testBeanValidationXML004(BeanValidation20Logic.java:686)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at com.ibm.ws.testtooling.vehicle.JEEExecutionContextHelper.executeTestLogic(JEEExecutionContextHelper.java:410)
at com.ibm.ws.testtooling.vehicle.ejb.BMTEJBTestVehicle.executeTestLogic(BMTEJBTestVehicle.java:88)
at com.ibm.ws.jpa.beanvalidation20.ejblocal.EJSLocal0SFBeanValidation20SFEJB_0adfe5ba.executeTestLoggic(EJSLocal0SFBeanValidation20SFEJB_0adfe5ba.java)
at com.ibm.ws.testtooling.vehicle.web.EJBDBTestVehicleServlet.executeTestVehicle(EJBDBTestVehicleServlet.java:39)

at com.ibm.ws.testtooling.vehicle.web.EJBDBTestVehicleServlet.executeTestVehicle(EJBDBTesttVehicleServlet.java:28)
at com.ibm.ws.testtooling.vehicle.web.JPATestServlet.executeTest(JPATestServlet.java:140)

at com.ibm.ws.testtoooling.vehicle.web.JPATestServlet.executeTest(JPATestServlet.java:124)
at com.ibm.ws.testtooling.vehicle.web.JPATestServlet.executeTest(JPATestServlet.java:117)
at com.ibm.ws.jpa.beanvalidation20.ejb.TestBeanValidation20_EJB_SF_Servlet.jpa_beanvalidation_testBeanValidationXML004_EJB_SF_CMTS_Web(TestBeanValidation20_EJB_SF_Servlet.java:251)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invooke(DelegatingMethodAccessorImpl.java:43)
at componenttest.app.FATServlet.doGet(FATServlet.java:74)
at com.ibm.ws.testtooling.vehicle.web.JPATestServlet.doGet(JPATestServlet.java:113)
at jakkarta.servlet.http.HttpServlet.service(HttpServlet.java:633)
at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:723)
at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1266)
at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:754)
at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:451)
at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1362)
at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1078)
at com.ibm.ws.webcontainer.servlet.CacheServletWrapper.handleRequest(CacheServletWraapper.java:77)
at com.ibm.ws.webcontainer40.servlet.CacheServletWrapper40.handleRequest(CacheServletWrapper40.java:87)
at com.ibm.ws.webcontainer.WeebContainer.handleRequest(WebContainer.java:978)
at com..ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:293)
at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1260)
at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.jaava:476)
at com.ibm.ws.http.dispatcher.internal.channel..HttpDispatcherLink.ready(HttpDispatcherLink.java:435)
at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:569)
at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:503)
at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:363)
at com.ibm.ws..http.channel.internal.inbound.HttpInboundLink.ready(HttpInboundLink.java:330)
at com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.sendToDiscriminators(NewConnectionInitialReadCallback.java:169)
at com.ibm.ws.tcpchanneel.internal.NewConnectionInitialReadCallback.complete(NewConnectionInitialReadCallback.java:77)
at com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:516)
at com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueManager.java:586)
at com.ibm.ws.tcpchannel.internal.WorkQueueManageer.workerRun(WorkQueueManager.java:970)
at com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:1059)
at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:2880)
at java.base/java.util.concurrent.ThreadPoolExxecutor.runWorker(ThreadPoolExecutor.java:1136)

at java.base/java.util.cooncurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:857)
Caused by: jakarta.transaction.RollbackException
at com.ibm.tx.jta.impl.TransactionImpl.stage3CommitProcessing(TransactionImpl.java:1049)
at com.ibm.tx.jta.impl.TransactionImpl.processCommit(TransactionImpl.java:847)
at com.ibm.tx.jta.impl.TransactiionImpl.commit(TransactionImpl.java:761)
at com.ibm.tx.jta.impl.TranManagerIImpl.commit(TranManagerImpl.java:155)
at com.ibm.tx.jta.impl.TranManagerSet.commit(TranManagerSet.java:112)
aat com.ibm.tx.jta.impl.UserTransactionImpl.commit(UserTransactionImpl.java:147)
at com.ibm.tx.jta.embeddable.impl.EmbeddableUserTransactionImpl.commit(EmbeddableUserTransactionImpl.java:103)
at com.ibm.ws.transaction.services.UserTransactionService.commit(UserTransactionService.java:74)
at com.ibm.ejs.container.UserTransactionWrapper.commit(UserTransactionWrapper.java:179)
at com.ibm.ws.testtooling.tranjacket.JTATransactionJacket.commitTransaction(JTATransactionJacket.java:47)
Caused by: jakarta.persistence.PersistenceException: Exception [EcclipseLink-4002] (Eclipse Persistence Services - 5.0.0-B02.v202404111748): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: java.sql.SQLException: An attempt was made to put a data value of type 'java.sql.Timestamp' into a data value oof type 'BLOB'.
Error Code: 20000
Call: INSERT INTO SIMPLEBEANVAL20XMLENTITY (ID, EMAIL, FUTUREINSTANT, VERSION) VALUES (?, ?, ?, ?)
bind => [17,, valid_email@somewhere.com, 2024-06-06T21:59:09.706789900Z, 1]
Query: InsertObjectQuery(com.ibm.ws.jpa.beanvalidation20.model.SimpleBeanVal20XMLEntity@22ca6afb)
at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl$1.handleException(EntityManagerSetupImpl.java:797))
at org.eclipse.persistence.transaction.AbstractSynchronizationLiistener.handleException(AbstractSynchronizationListener.java:279)

at org.eclipse.persistence.transaction.AbstractSynchronizationListener.beforeCompletion(AbstractSynchronizationListener.java:174)
at org.eclipsse.persistence.transaction.JTASynchronizationListener.beforeCompletion(JTASynchronizationListener.java:70)
at com.ibm.tx.jta.impl.RegisteredSyncs.coreDistributeBefore(RegisteredSyncs.java:239)
at com.ibm.tx.jta.impl.RegisteredSyncs.distributeBefore(RegisteredSyncs.java:147)
at com.ibm.tx.jta.impl.TransactionImpl.prePrepare(TransactionImpl.java:1448)
at com.ibm.tx.jta.impl.TransactionImpl.stagee1CommitProcessing(TransactionImpl.java:862)
at com.ibm.tx.jta.impl.TransactionImpl.processCommit(TransactionImpl.java:818)
Caused by: Exception [EclipseLink-4002] (Eclipse Persistence Services - 5.0.0-B02.v202404111748): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: java.sql.SQLException: An attempt was made to put a data value of type 'java.sql.Timestamp' into a data value of type 'BLOB'.
Error Code: 20000
Call: INSERT INTO SIMPLEBEANVAL20XMLENTITY (ID, EMAIL, FUTUREINSTANTT, VERSION) VALUES (?, ?, ?, ?)
bind => [17, valid_email@somewhere.com, 2024-06-06T21:59:09.706789900Z, 1]
Query: InsertObjectQuery(com.ibm.ws.jpa.beanvalidation20.moddel.SimpleBeanVal20XMLEntity@22ca6afb)
at org.eclipse.peersistence.exceptions.DatabaseException.sqlException(DatabaseException.java:346)
at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.basicExecuteCall(DatabaseAccessor.java:702)
at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeCall(DatabaseAccessor.java:569))
at org.eclipse.persistence.internal.sessions.AbstracctSession.basicExecuteCall(AbstractSession.java:2046)
at org.eclipse.persistence.sessions.server.ClientSession.executeCall(ClientSession.java:322)
at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.execcuteCall(DatasourceCallQueryMechanism.java:282)
at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism..executeCall(DatasourceCallQueryMechanism.java:268)
at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.insertObject(DatasourceCallQueryMechanism.java::438)
at org.eclipse.persistence.internal.queries.StatementQueryMechanism.insertObject(StatementQueryMechanism.jjava:194)
at org.eclipse.persistence.internal.queries.StatementQueryMechanism.insertObject(StatementQueryMechanism.java:210)
at org.eclipse.persistence.internal.queries.DatabaseQueryMechanism.insertObjectForWrite(DatabaseQueryMechanism.java:514)
at org.eclipse.persistence.queries.InsertObjeectQuery.executeCommit(InsertObjectQuery.java:86)
at org.eclipse.persistence.queries.InsertObjectQuery.executeCommitWithChangeSet(InsertObjectQuery.java:97)
at org.eclipse.persistence.internal.queries.DatabaseQueryMechanism.executeWriteWithChangeSet(DatabbaseQueryMechanism.java:326)
at org.eclipse.persistence.queries.WriteObjectQuery.executeDatabaseQuery(WriteObjectQuery..java:63)
at org.eclipse.persistence.queries.DaatabaseQuery.execute(DatabaseQuery.java:934)
at org.eclipse.persisttence.queries.DatabaseQuery.executeInUnitOfWork(DatabaseQuery.java:833)
at org.eclipse.persistence.queries.ObjectLevelModifyQuery.executeInUnitOfWorkObjectLevellModifyQuery(ObjectLevelModifyQuery.java:114)
at org.eclipse.persistence.queries.ObjectLevelModifyQuery.executeInUnitOfWork(ObjectLevelModifyQuery.java:91)
at org.eclipse.persistence.internal.sessions.UniitOfWorkImpl.internalExecuteQuery(UnitOfWorkImpl.java:3015)
at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1841)
at org.eclipse.persistence.internal.sessions.AbstrractSession.executeQuery(AbstractSession.java:1823)

at org.eclipse.persistence.internal.sessions.AbstractSessionn.executeQuery(AbstractSession.java:1773)
at org.eclipse.persistence.internal.sessions.CommitManager.commitNewObjecttsForClassWithChangeSet(CommitManager.java:248)
at org.eclipse.persistence.internal.sessions.CommitManager.commitAllObjectsWithChangeSet(CommitManager.java:147)
at org.eclipse.persistence.internal.sessions.AbbstractSession.writeAllObjectsWithChangeSet(AbstractSession.java:4333)
at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.commitToDatabase(UnitOfWorkImpl.java:1515)
at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.commitToDatabaseWithChangeSet(UnitOfWorkImpl.java:1602)
at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.issueSQLbeforeCoompletion(UnitOfWorkImpl.java:3312)
at org.eclipse.persistence.internal.sessions.RepeatableWriteUnitOfWork.issueSQLbeforeCompletion(RepeatableWriteUnitOfWork.java:367)
at org.eclipse.persistence.transaction.AbstractSynchronizationListener.beforeCompletion(AbstractSynchronizationListener.java:162)
Caused by: java.sql.SQLException: An attempt was made to put a data value of type 'java.sql.Timestamp' into a data value of type 'BLOB'.
at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
at org.apache.derby.impl.jdbc.Util.generateCsSQLExceptiion(Unknown Source)
at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Sourcce)
at org.apache.derby.impl.jdbc.EmbedResultSet.noStateChangeException(Unknown Source)
at org.apache.derby.impl.jdbc.EmbedPreparedStatement.setTimestamp(Unknown Source)
at org.apache.derby.impl.jdbc.EmbedPreparedStatement.setTimestamp(Unknown Source)
at com.ibm.ws.rsadapter.jdbc.WSJdbcPreparedStatement.setTimestamp(WSJdbcPPreparedStatement.java:1898)
at org.eclipse.persistence.innternal.databaseaccess.DatabasePlatform.setParameterValueInDatabaseCall(DatabasePlatform.java:2428)
at org.eclipse.persistence.platform.database.DerbyPlatform.setParameterValueInDatabaseCall(DerbyPlatform.java:1027)
at org.eclipse.persistence.internal.databaseaccess.DatabaseCall.prepareStatement(DatabaseCall.java:795)
at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.basicExecuteCall(DatabaseAccessor..java:630)
Caused by: ERROR XCL12: An attempt was made to put a data value of type 'java.sql.Timestamp' into a datta value of type 'BLOB'.
at org.apache.derby.iapi.error.StandardException.newEException(Unknown Source)
at org.apache.derby.iapi.error.StandardException.newException(Unknown Source))
at org.apache.derby.iapi.types.DataType.throwLangSetMismatch(Unknown Source)
at org.apache.derby.iapi.types.DataType.setValue(Unknown Source)

at com.ibm.ws.testtooling.vehicle.ejb.BMTEJBTestVehicle.logExcepttion(BMTEJBTestVehicle.java:126)
at com.ibm..ws.testtooling.vehicle.ejb.BMTEJBTestVehicle.executeTestLogic(BMTEJBTestVehicle.java:90)

at com.ibm.ws.testtooling.vehicle.web.JPATestServlet.logException(JPATestServlet.java:186)
at com.ibm.ws.testtooling.vehicle.web.EJBDBTestVehicleServlet.executeTestVehicle(EJBDBTestVehicleServlet.java:47)
at com.ibm.ws.testtooling.vehicle.web.EJBDBTestVehicleServlet.executeTestVehicle(EJBDBTesstVehicleServlet.java:28)
at com.ibm.ws.testtooling.vehicle.web.JPATestServlet.executeTest(JPATestServlet.java:140)
at com.ibm.ws.testtooling.vehicle.web.JPATestServlet.executeTest(JPATestServlet.java:124)
at com.ibm.ws.testtooling.vehicle.web.JPATesstServlet.executeTest(JPATestServlet.java:117)
at com.ibm.ws.jpa.beanvalidation20.ejb.TestBeanValidation20_EJB_SF_Servlet.jpa_beanvalidation_testBeanValidationXML004_EJB_SF_CMTS_Web(TestBeanValidation20_EJB_SF_Servlet.java:251)
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Methood)
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at componenttest.app.FATServlet.doGet(FATServlet.java:74) 
```

for #25091

**Comment by anija-anil** [comment]
This issue has been fixed with  #31063
