### ISSUE TITLE
Default "target" value in Liberty Embedded Messaging can cause NullPointerExceptions when connecting to remote messaging engine

### ISSUE THREAD

**Issue by sakerl** [OpenLiberty/open-liberty#28805]
When connecting from Liberty to a remote SIBus in traditional WAS, this can intermittently fail.
This can be resolved by setting appropriate values for target, targetType, and TargetSignificance.
These properties are not well documented, and with the default values, failed connection attempts can result in a NullPointerException begin thrown, with a stack trace similar to:
```
java.lang.NullPointerException: Cannot invoke "com.ibm.wsspi.sib.core.SICoreConnection.addConnectionListener(com.ibm.wsspi.sib.core.SICoreConnectionListener)" because "this._coreConnection" is null
	at com.ibm.ws.sib.api.jmsra.impl.JmsJcaManagedConnection.<init>(JmsJcaManagedConnection.java:183)
	at com.ibm.ws.sib.api.jmsra.impl.JmsJcaManagedConnectionFactoryImpl.createManagedConnection(JmsJcaManagedConnectionFactoryImpl.java:474)
	at com.ibm.ejs.j2c.FreePool.createManagedConnectionWithMCWrapper(FreePool.java:1373)
	at com.ibm.ejs.j2c.FreePool.createOrWaitForConnection(FreePool.java:1247)
	.....
```

**Comment by gnadell** [comment]
@sakerl , another symptom for the same scenario(connecting from liberty to a remote ME in tWAS):
**CWSIJ0055E: A resource shortage stopped a new connection from being established.:com.ibm.ws.sib.jfapchannel.impl.IdTableFullException**

Ultimately leading to **java.lang.OutOfMemoryError**
