### ISSUE TITLE
Test Failure: io.openliberty.microprofile.metrics.internal.fat.BadHistogramTimerConfigTest.checkBadHistogramPercentiles

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#28878]
RTC 300666

```
checkBadHistogramPercentiles:java.net.ConnectException: 2024-06-21-11:32:17:276 A remote host refused an attempted connect operation. (Connection refused)
    at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
    at java.base/java.net.Socket.connect(Socket.java:609)
    at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:305)
    at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
    at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)
    at java.base/sun.net.[www.http.HttpClient.openServer(HttpClient.java:509)](http://www.http.HttpClient.openServer(HttpClient.java:509))
    at java.base/sun.net.[www.http.HttpClient.openServer(HttpClient.java:604)](http://www.http.HttpClient.openServer(HttpClient.java:604))
    at java.base/sun.net.[www.protocol.https.HttpsClient](http://www.protocol.https.httpsclient/).<init>(HttpsClient.java:266)
    at java.base/sun.net.[www.protocol.https.HttpsClient.New(HttpsClient.java:373)](http://www.protocol.https.HttpsClient.New(HttpsClient.java:373))
    at java.base/sun.net.[www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:207)](http://www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:207))
    at java.base/sun.net.[www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)](http://www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187))
    at java.base/sun.net.[www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)](http://www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081))
    at java.base/sun.net.[www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:193)](http://www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:193))
    at java.base/sun.net.[www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1592)](http://www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1592))
    at java.base/sun.net.[www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)](http://www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520))
    at java.base/sun.net.[www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)](http://www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250))
    at io.openliberty.microprofile.metrics.internal.fat.BadHistogramTimerConfigTest.getHttpsServlet(BadHistogramTimerConfigTest.java:411)
    at io.openliberty.microprofile.metrics.internal.fat.BadHistogramTimerConfigTest.checkBadHistogramPercentiles(BadHistogramTimerConfigTest.java:162)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:203)
    at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:363)
    at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:177)
    at componenttest.rules.repeater.RepeatTests$CompositeRepeatTestActionStatement.evaluate(RepeatTests.java:145)
```

**Comment by tonyreigns** [comment]
Issue has been resolved, failures haven't reoccurred in over a week.
