### ISSUE TITLE
Fault Tolerence 4.1 TCK Fails becuase metadata is not on the thread

### ISSUE THREAD

**Issue by benjamin-confino** [OpenLiberty/open-liberty#28892]
When I enable and run the FT TCK I get the following: 

```
Stack Dump = java.lang.NullPointerException: Cannot invoke "[com.ibm.ws](http://com.ibm.ws/).runtime.metadata.ApplicationMetaData.getMetaData([com.ibm.ws](http://com.ibm.ws/).runtime.metadata.MetaDataSlot)" because "metaData" is null
	at [io.openliberty.microprofile.telemetry.internal.common.info](http://io.openliberty.microprofile.telemetry.internal.common.info/).OpenTelemetryInfoFactoryImpl.getOpenTelemetryInfo(OpenTelemetryInfoFactoryImpl.java:125)
	at [io.openliberty.microprofile.telemetry.internal.common.info](http://io.openliberty.microprofile.telemetry.internal.common.info/).OpenTelemetryInfoFactoryImpl.getOpenTelemetryInfo(OpenTelemetryInfoFactoryImpl.java:105)
	at io.openliberty.microprofile.telemetry.internal.interfaces.OpenTelemetryAccessor.lambda$getOpenTelemetryInfo$0(OpenTelemetryAccessor.java:48)
	at [com.ibm.ws](http://com.ibm.ws/).kernel.service.util.ServiceCaller.lambda$call$3(ServiceCaller.java:457)
	at java.base/java.util.Optional.map(Optional.java:260)
	at [com.ibm.ws](http://com.ibm.ws/).kernel.service.util.ServiceCaller.call(ServiceCaller.java:456)
	at io.openliberty.microprofile.telemetry.internal.interfaces.OpenTelemetryAccessor.getOpenTelemetryInfo(OpenTelemetryAccessor.java:47)
	at io.openliberty.microprofile.faulttolerance.telemetry.metrics.integration.MetricRecorderProviderImpl.createNewRecorder(MetricRecorderProviderImpl.java:79)
	at io.openliberty.microprofile.faulttolerance.telemetry.metrics.integration.MetricRecorderProviderImpl.getMetricRecorder(MetricRecorderProviderImpl.java:69)
	at [com.ibm.ws](http://com.ibm.ws/).microprofile.faulttolerance.cdi.AggregatedFTPolicy.lambda$updateBuilder$0(AggregatedFTPolicy.java:187)
	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891)
	at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1116)
	at [com.ibm.ws](http://com.ibm.ws/).microprofile.faulttolerance.cdi.AggregatedFTPolicy.updateBuilder(AggregatedFTPolicy.java:187)
	at [com.ibm.ws](http://com.ibm.ws/).microprofile.faulttolerance.cdi.AggregatedFTPolicy.newBuilder(AggregatedFTPolicy.java:157)
	at [com.ibm.ws](http://com.ibm.ws/).microprofile.faulttolerance.cdi.AggregatedFTPolicy.getExecutor(AggregatedFTPolicy.java:139)
	at [com.ibm.ws](http://com.ibm.ws/).microprofile.faulttolerance.cdi.FaultToleranceInterceptor.execute(FaultToleranceInterceptor.java:252)
	at [com.ibm.ws](http://com.ibm.ws/).microprofile.faulttolerance.cdi.FaultToleranceInterceptor.executeFT(FaultToleranceInterceptor.java:90)
	at [com.ibm.ws](http://com.ibm.ws/).microprofile.faulttolerance.cdi20.FaultToleranceCDI20Interceptor.intercept(FaultToleranceCDI20Interceptor.java:134)
	at [com.ibm.ws](http://com.ibm.ws/).microprofile.faulttolerance.cdi20.FaultToleranceCDI20Interceptor.intercept(FaultToleranceCDI20Interceptor.java:44)
	at org.jboss.weld.interceptor.proxy.CustomInterceptorInvocation$CustomInterceptorMethodInvocation.invoke(CustomInterceptorInvocation.java:36)
	at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeAroundInvoke(InterceptorMethodHandler.java:90)
	at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeInterception(InterceptorMethodHandler.java:73)
	at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.invoke(InterceptorMethodHandler.java:56)
	at org.jboss.weld.bean.proxy.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(CombinedInterceptorAndDecoratorStackMethodHandler.java:80)
	at org.jboss.weld.bean.proxy.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(CombinedInterceptorAndDecoratorStackMethodHandler.java:68)
	at org.eclipse.microprofile.fault.tolerance.tck.disableEnv.DisableAnnotationClient$Proxy$_$$_WeldSubclass.waitWithBulkhead(Unknown Source)
	at org.eclipse.microprofile.fault.tolerance.tck.disableEnv.DisableAnnotationClient$Proxy$_$$_WeldClientProxy.waitWithBulkhead(Unknown Source)
	at org.eclipse.microprofile.fault.tolerance.tck.disableEnv.DisableAnnotationGloballyEnableOnClassTest.lambda$testBulkhead$4(DisableAnnotationGloballyEnableOnClassTest.java:170)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)Stack Dump = java.lang.NullPointerException: Cannot invoke "[com.ibm.ws](http://com.ibm.ws/).runtime.metadata.ApplicationMetaData.getMetaData([com.ibm.ws](http://com.ibm.ws/).runtime.metadata.MetaDataSlot)" because "metaData" is null
	at [io.openliberty.microprofile.telemetry.internal.common.info](http://io.openliberty.microprofile.telemetry.internal.common.info/).OpenTelemetryInfoFactoryImpl.getOpenTelemetryInfo(OpenTelemetryInfoFactoryImpl.java:125)
	at [io.openliberty.microprofile.telemetry.internal.common.info](http://io.openliberty.microprofile.telemetry.internal.common.info/).OpenTelemetryInfoFactoryImpl.getOpenTelemetryInfo(OpenTelemetryInfoFactoryImpl.java:105)
	at io.openliberty.microprofile.telemetry.internal.interfaces.OpenTelemetryAccessor.lambda$getOpenTelemetryInfo$0(OpenTelemetryAccessor.java:48)
	at [com.ibm.ws](http://com.ibm.ws/).kernel.service.util.ServiceCaller.lambda$call$3(ServiceCaller.java:457)
	at java.base/java.util.Optional.map(Optional.java:260)
	at [com.ibm.ws](http://com.ibm.ws/).kernel.service.util.ServiceCaller.call(ServiceCaller.java:456)
	at io.openliberty.microprofile.telemetry.internal.interfaces.OpenTelemetryAccessor.getOpenTelemetryInfo(OpenTelemetryAccessor.java:47)
	at io.openliberty.microprofile.faulttolerance.telemetry.metrics.integration.MetricRecorderProviderImpl.createNewRecorder(MetricRecorderProviderImpl.java:79)
	at io.openliberty.microprofile.faulttolerance.telemetry.metrics.integration.MetricRecorderProviderImpl.getMetricRecorder(MetricRecorderProviderImpl.java:69)
	at [com.ibm.ws](http://com.ibm.ws/).microprofile.faulttolerance.cdi.AggregatedFTPolicy.lambda$updateBuilder$0(AggregatedFTPolicy.java:187)
	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891)
	at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1116)
	at [com.ibm.ws](http://com.ibm.ws/).microprofile.faulttolerance.cdi.AggregatedFTPolicy.updateBuilder(AggregatedFTPolicy.java:187)
	at [com.ibm.ws](http://com.ibm.ws/).microprofile.faulttolerance.cdi.AggregatedFTPolicy.newBuilder(AggregatedFTPolicy.java:157)
	at [com.ibm.ws](http://com.ibm.ws/).microprofile.faulttolerance.cdi.AggregatedFTPolicy.getExecutor(AggregatedFTPolicy.java:139)
	at [com.ibm.ws](http://com.ibm.ws/).microprofile.faulttolerance.cdi.FaultToleranceInterceptor.execute(FaultToleranceInterceptor.java:252)
	at [com.ibm.ws](http://com.ibm.ws/).microprofile.faulttolerance.cdi.FaultToleranceInterceptor.executeFT(FaultToleranceInterceptor.java:90)
	at [com.ibm.ws](http://com.ibm.ws/).microprofile.faulttolerance.cdi20.FaultToleranceCDI20Interceptor.intercept(FaultToleranceCDI20Interceptor.java:134)
	at [com.ibm.ws](http://com.ibm.ws/).microprofile.faulttolerance.cdi20.FaultToleranceCDI20Interceptor.intercept(FaultToleranceCDI20Interceptor.java:44)
	at org.jboss.weld.interceptor.proxy.CustomInterceptorInvocation$CustomInterceptorMethodInvocation.invoke(CustomInterceptorInvocation.java:36)
	at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeAroundInvoke(InterceptorMethodHandler.java:90)
	at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeInterception(InterceptorMethodHandler.java:73)
	at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.invoke(InterceptorMethodHandler.java:56)
	at org.jboss.weld.bean.proxy.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(CombinedInterceptorAndDecoratorStackMethodHandler.java:80)
	at org.jboss.weld.bean.proxy.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(CombinedInterceptorAndDecoratorStackMethodHandler.java:68)
	at org.eclipse.microprofile.fault.tolerance.tck.disableEnv.DisableAnnotationClient$Proxy$_$$_WeldSubclass.waitWithBulkhead(Unknown Source)
	at org.eclipse.microprofile.fault.tolerance.tck.disableEnv.DisableAnnotationClient$Proxy$_$$_WeldClientProxy.waitWithBulkhead(Unknown Source)
	at org.eclipse.microprofile.fault.tolerance.tck.disableEnv.DisableAnnotationGloballyEnableOnClassTest.lambda$testBulkhead$4(DisableAnnotationGloballyEnableOnClassTest.java:170)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)Stack Dump = java.lang.NullPointerException: Cannot invoke "[com.ibm.ws](http://com.ibm.ws/).runtime.metadata.ApplicationMetaData.getMetaData([com.ibm.ws](http://com.ibm.ws/).runtime.metadata.MetaDataSlot)" because "metaData" is null
	at [io.openliberty.microprofile.telemetry.internal.common.info](http://io.openliberty.microprofile.telemetry.internal.common.info/).OpenTelemetryInfoFactoryImpl.getOpenTelemetryInfo(OpenTelemetryInfoFactoryImpl.java:125)
	at [io.openliberty.microprofile.telemetry.internal.common.info](http://io.openliberty.microprofile.telemetry.internal.common.info/).OpenTelemetryInfoFactoryImpl.getOpenTelemetryInfo(OpenTelemetryInfoFactoryImpl.java:105)
	at io.openliberty.microprofile.telemetry.internal.interfaces.OpenTelemetryAccessor.lambda$getOpenTelemetryInfo$0(OpenTelemetryAccessor.java:48)
	at [com.ibm.ws](http://com.ibm.ws/).kernel.service.util.ServiceCaller.lambda$call$3(ServiceCaller.java:457)
	at java.base/java.util.Optional.map(Optional.java:260)
	at [com.ibm.ws](http://com.ibm.ws/).kernel.service.util.ServiceCaller.call(ServiceCaller.java:456)
	at io.openliberty.microprofile.telemetry.internal.interfaces.OpenTelemetryAccessor.getOpenTelemetryInfo(OpenTelemetryAccessor.java:47)
	at io.openliberty.microprofile.faulttolerance.telemetry.metrics.integration.MetricRecorderProviderImpl.createNewRecorder(MetricRecorderProviderImpl.java:79)
	at io.openliberty.microprofile.faulttolerance.telemetry.metrics.integration.MetricRecorderProviderImpl.getMetricRecorder(MetricRecorderProviderImpl.java:69)
	at [com.ibm.ws](http://com.ibm.ws/).microprofile.faulttolerance.cdi.AggregatedFTPolicy.lambda$updateBuilder$0(AggregatedFTPolicy.java:187)
	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891)
	at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1116)
	at [com.ibm.ws](http://com.ibm.ws/).microprofile.faulttolerance.cdi.AggregatedFTPolicy.updateBuilder(AggregatedFTPolicy.java:187)
	at [com.ibm.ws](http://com.ibm.ws/).microprofile.faulttolerance.cdi.AggregatedFTPolicy.newBuilder(AggregatedFTPolicy.java:157)
	at [com.ibm.ws](http://com.ibm.ws/).microprofile.faulttolerance.cdi.AggregatedFTPolicy.getExecutor(AggregatedFTPolicy.java:139)
	at [com.ibm.ws](http://com.ibm.ws/).microprofile.faulttolerance.cdi.FaultToleranceInterceptor.execute(FaultToleranceInterceptor.java:252)
	at [com.ibm.ws](http://com.ibm.ws/).microprofile.faulttolerance.cdi.FaultToleranceInterceptor.executeFT(FaultToleranceInterceptor.java:90)
	at [com.ibm.ws](http://com.ibm.ws/).microprofile.faulttolerance.cdi20.FaultToleranceCDI20Interceptor.intercept(FaultToleranceCDI20Interceptor.java:134)
	at [com.ibm.ws](http://com.ibm.ws/).microprofile.faulttolerance.cdi20.FaultToleranceCDI20Interceptor.intercept(FaultToleranceCDI20Interceptor.java:44)
	at org.jboss.weld.interceptor.proxy.CustomInterceptorInvocation$CustomInterceptorMethodInvocation.invoke(CustomInterceptorInvocation.java:36)
	at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeAroundInvoke(InterceptorMethodHandler.java:90)
	at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeInterception(InterceptorMethodHandler.java:73)
	at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.invoke(InterceptorMethodHandler.java:56)
	at org.jboss.weld.bean.proxy.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(CombinedInterceptorAndDecoratorStackMethodHandler.java:80)
	at org.jboss.weld.bean.proxy.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(CombinedInterceptorAndDecoratorStackMethodHandler.java:68)
	at org.eclipse.microprofile.fault.tolerance.tck.disableEnv.DisableAnnotationClient$Proxy$_$$_WeldSubclass.waitWithBulkhead(Unknown Source)
	at org.eclipse.microprofile.fault.tolerance.tck.disableEnv.DisableAnnotationClient$Proxy$_$$_WeldClientProxy.waitWithBulkhead(Unknown Source)
	at org.eclipse.microprofile.fault.tolerance.tck.disableEnv.DisableAnnotationGloballyEnableOnClassTest.lambda$testBulkhead$4(DisableAnnotationGloballyEnableOnClassTest.java:170)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

This is because it uses an executor that does not put the app metadata on the new threads it spawns. While that needs to be fixed in FT itself, in OL we will need to weave in our managed executor service so the updated TCK can pick it up. And we should have a nicer error message than an NPE.

**Comment by benjamin-confino** [comment]
This will be resolved in the FT TCK.
