### ISSUE TITLE
Entity identifier 'this' is broken for comparisons with numeric values 

### ISSUE THREAD

**Issue by njr-11** [OpenLiberty/open-liberty#28898]
This might be related to #28874 which also involves errors when referring to an entity attribute with the "this." entity identification variable.

A JPQL DELETE query that compares a numeric attribute value using `this.` is misinterpreted by EclipseLink as an Object comparison.

```
[6/26/24, 10:10:25:787 CDT] 00000053 id=53654d30 io.openliberty.data.internal.persistence.RepositoryImpl      > invoke Receipts.removeIfTotalUnder Entry  
                                                                                                               2000.0
[6/26/24, 10:10:25:787 CDT] 00000053 id=53654d30 io.openliberty.data.internal.persistence.RepositoryImpl      3 QueryInfo@4e64517f int removeIfTotalUnder(float) DELETE FROM ReceiptEntity WHERE this.total < :max [1 named params]
[6/26/24, 10:10:25:787 CDT] 00000053 id=5eca384d enliberty.data.internal.persistence.service.DBStoreEMBuilder > createEntityManager Entry 
[6/26/24, 10:10:25:787 CDT] 00000053 id=24bddbbf om.ibm.wsspi.persistence.internal.PersistenceServiceUnitImpl > createEntityManager Entry 
[6/26/24, 10:10:25:787 CDT] 00000053 id=24bddbbf om.ibm.wsspi.persistence.internal.PersistenceServiceUnitImpl < createEntityManager Exit  
                                                                                                               org.eclipse.persistence.internal.jpa.EntityManagerImpl@7127ef1e
[6/26/24, 10:10:25:787 CDT] 00000053 id=5eca384d enliberty.data.internal.persistence.service.DBStoreEMBuilder < createEntityManager Exit  
                                                                                                               org.eclipse.persistence.internal.jpa.EntityManagerImpl@7127ef1e
[6/26/24, 10:10:25:790 CDT] 00000053 id=00000000 io.openliberty.data.internal.persistence.RepositoryImpl      3 Failure occurred: org.eclipse.persistence.exceptions.QueryException
[6/26/24, 10:10:25:790 CDT] 00000053 id=53654d30 io.openliberty.data.internal.persistence.RepositoryImpl      < invoke Receipts.removeIfTotalUnder Exit  
                                                                                                               Local Exception Stack: 
Exception [EclipseLink-6075] (Eclipse Persistence Services - 5.0.0-B02.v202404111748): org.eclipse.persistence.exceptions.QueryException
Exception Description: Object comparisons can only use the equal() or notEqual() operators.  Other comparisons must be done through query keys or direct attribute level comparisons. 
Expression: [
Relation operator [ < ]
   Base test.jakarta.data.web.ReceiptEntity
   Parameter max]
Query: DeleteAllQuery(referenceClass=ReceiptEntity jpql="DELETE FROM ReceiptEntity WHERE this.total < :max")
	at org.eclipse.persistence.exceptions.QueryException.invalidOperatorForObjectComparison(QueryException.java:681)
	at org.eclipse.persistence.internal.expressions.RelationExpression.normalize(RelationExpression.java:600)
	at org.eclipse.persistence.internal.expressions.SQLSelectStatement.normalize(SQLSelectStatement.java:1544)
	at org.eclipse.persistence.internal.queries.ExpressionQueryMechanism.buildReportQuerySelectStatement(ExpressionQueryMechanism.java:694)
	at org.eclipse.persistence.internal.queries.ExpressionQueryMechanism.createSQLSelectStatementForModifyAll(ExpressionQueryMechanism.java:1647)
	at org.eclipse.persistence.internal.queries.ExpressionQueryMechanism.createSQLSelectStatementForModifyAll(ExpressionQueryMechanism.java:1623)
	at org.eclipse.persistence.internal.queries.ExpressionQueryMechanism.prepareDeleteAll(ExpressionQueryMechanism.java:1277)
	at org.eclipse.persistence.internal.queries.ExpressionQueryMechanism.prepareDeleteAll(ExpressionQueryMechanism.java:1202)
	at org.eclipse.persistence.queries.DeleteAllQuery.prepare(DeleteAllQuery.java:282)
	at org.eclipse.persistence.queries.DatabaseQuery.checkPrepare(DatabaseQuery.java:696)
	at org.eclipse.persistence.queries.DatabaseQuery.checkPrepare(DatabaseQuery.java:645)
	at org.eclipse.persistence.internal.jpa.EJBQueryImpl.buildEJBQLDatabaseQuery(EJBQueryImpl.java:196)
	at org.eclipse.persistence.internal.jpa.EJBQueryImpl.buildEJBQLDatabaseQuery(EJBQueryImpl.java:120)
	at org.eclipse.persistence.internal.jpa.EJBQueryImpl.<init>(EJBQueryImpl.java:107)
	at org.eclipse.persistence.internal.jpa.EJBQueryImpl.<init>(EJBQueryImpl.java:91)
	at org.eclipse.persistence.internal.jpa.EntityManagerImpl.createQuery(EntityManagerImpl.java:1846)
	at io.openliberty.data.internal.persistence.RepositoryImpl.invoke(RepositoryImpl.java:1079)
	at jdk.proxy14/jdk.proxy14.$Proxy62.removeIfTotalUnder(Unknown Source)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.jboss.weld.bean.proxy.InterceptedProxyMethodHandler.invoke(InterceptedProxyMethodHandler.java:52)
	at test.jakarta.data.web.Receipts$Proxy$_$$_WeldInterceptedProxy5.removeIfTotalUnder(Unknown Source)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.jboss.weld.bean.proxy.AbstractBeanInstance.invoke(AbstractBeanInstance.java:38)
	at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:109)
	at test.jakarta.data.web.Receipts$1025303033$Proxy$_$$_WeldClientProxy.removeIfTotalUnder(Unknown Source)
	at test.jakarta.data.web.DataTestServlet.testRecordInFromClause(DataTestServlet.java:3658)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at componenttest.app.FATServlet.doGet(FATServlet.java:74)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:633)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:723)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1266)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:754)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:451)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1362)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1078)
	at com.ibm.ws.webcontainer.servlet.CacheServletWrapper.handleRequest(CacheServletWrapper.java:77)
	at com.ibm.ws.webcontainer40.servlet.CacheServletWrapper40.handleRequest(CacheServletWrapper40.java:87)
	at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:978)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:293)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1260)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:476)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:435)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:569)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:503)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:363)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.ready(HttpInboundLink.java:330)
	at com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.sendToDiscriminators(NewConnectionInitialReadCallback.java:169)
	at com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.complete(NewConnectionInitialReadCallback.java:77)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:516)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueManager.java:586)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:970)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:1059)
	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:280)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by Riva-Tholoor-Philip** [comment]
See EclipseLink Issue : [2198](https://github.com/eclipse-ee4j/eclipselink/issues/2198)

**Comment by Riva-Tholoor-Philip** [comment]
This issue is addressed with EclipseLink PR [2224](https://github.com/eclipse-ee4j/eclipselink/pull/2224). Hence closing the issue
