### ISSUE TITLE
jax-ws/jax-rs XML Date regression problem w/java.sql.Date

### ISSUE THREAD

**Issue by nadiramra** [OpenLiberty/open-liberty#2899]
A JAX-WS that has a java.util.Date return parameter that has been set to java.sql.Date object no longer works when IBM Liberty 18.0.0.1 is used.  Prior to that the runtime handled it and returned only the date. This needs to be corrected ASAP with an iFix for 18.0.0.1.   If we release 18.0.0.1 and people are returning dates, they will get an exception.  (Note the problem also affects JAX-RS when processing the Date as XML.)

WAR file (the source is included) is attached. Attached also is Liberty auto-generated WSDL.  

Unzip into apps directory and configure server.xml as follows:
  <featureManager onError="WARN">
    <feature>jaxws-2.2</feature>
    <feature>servlet-3.1</feature>
  </featureManager>

  <application autoStart="true" context-root="/DATETESTsoap" id="DATETESTsoap" location="DATETESTsoap.war" name="DATETESTsoap" type="war"/>

I was able to access WSDL with (replace host/port with you server host/port):

http://<host name>:10011/DATETESTsoap/DATETESTsoap?wsdl

Here is the request/response I get when running 17.0.0.4:

REQUEST:
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:dat="http://datetestsoap.wsbeans.iseries/">
   <soapenv:Header/>
   <soapenv:Body>
      <dat:datetest/>
   </soapenv:Body>
</soapenv:Envelope>

RESPONSE:
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
   <soap:Body>
      <ns2:datetestResponse xmlns:ns2="http://datetestsoap.wsbeans.iseries/">
         <return>
            <dateOut>2017-01-01-06:00</dateOut>
         </return>
      </ns2:datetestResponse>
   </soap:Body>
</soap:Envelope>

After loading 18.0.0.1, sending the same request results in:

<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
   <soap:Body>
      <soap:Fault>
         <faultcode>soap:Server</faultcode>
         <faultstring>Marshalling Error: null</faultstring>
      </soap:Fault>
   </soap:Body>
</soap:Envelope>

In the messages.log:

[3/27/18 14:52:04:219 CDT] 00000059 org.apache.cxf.phase.PhaseInterceptorChain                   W Interceptor for {http://datetestsoap.wsbeans.iseries/}DATETESTsoap#{http://datetestsoap.wsbeans.iseries/}datetest has thrown exception, unwinding now
org.apache.cxf.interceptor.Fault: Marshalling Error: null
		 at org.apache.cxf.jaxb.JAXBEncoderDecoder.marshall(JAXBEncoderDecoder.java:263)
		 at org.apache.cxf.jaxb.io.DataWriterImpl.write(DataWriterImpl.java:177)
		 at org.apache.cxf.interceptor.AbstractOutDatabindingInterceptor.writeParts(AbstractOutDatabindingInterceptor.java:110)
		 at org.apache.cxf.interceptor.BareOutInterceptor.handleMessage(BareOutInterceptor.java:68)
		 at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:262)
		 at org.apache.cxf.interceptor.OutgoingChainInterceptor.handleMessage(OutgoingChainInterceptor.java:77)
		 at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:262)
		 at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
		 at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:211)
		 at com.ibm.ws.jaxws.endpoint.AbstractJaxWsWebEndpoint.invoke(AbstractJaxWsWebEndpoint.java:181)
		 at com.ibm.ws.jaxws.webcontainer.LibertyJaxWsServlet.handleRequest(LibertyJaxWsServlet.java:134)
		 at com.ibm.ws.jaxws.webcontainer.LibertyJaxWsServlet.doPost(LibertyJaxWsServlet.java:93)
		 at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
		 at com.ibm.ws.jaxws.webcontainer.LibertyJaxWsServlet.service(LibertyJaxWsServlet.java:85)
		 at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1255)
		 at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:743)
		 at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:440)
		 at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1155)
		 at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1004)
		 at com.ibm.ws.webcontainer.servlet.CacheServletWrapper.handleRequest(CacheServletWrapper.java:76)
		 at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:926)
		 at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:279)
		 at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1009)
		 at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:412)
		 at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:371)
		 at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:530)
		 at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:464)
		 at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:329)
		 at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.ready(HttpInboundLink.java:300)
		 at com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.sendToDiscriminators(NewConnectionInitialReadCallback.java:165)
		 at com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.complete(NewConnectionInitialReadCallback.java:74)
		 at com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:501)
		 at com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueManager.java:571)
		 at com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:926)
		 at com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:1015)
		 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
		 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
		 at java.lang.Thread.run(Thread.java:811)
Caused by: java.lang.IllegalArgumentException
		 at java.sql.Date.getHours(Date.java:198)
		 at com.ibm.xml.xlxp2.jaxb.marshal.impl.ValueWriter.writeDate(ValueWriter.java:896)
		 at com.ibm.xml.xlxp2.jaxb.marshal.impl.ValueWriter.writeDateElem(ValueWriter.java:942)
		 at com.ibm.xml.xlxp2.jaxb.marshal.impl.SerializationContext.writeDateValue(SerializationContext.java:647)
		 at iseries.wsbeans.datetestsoap.DateTestResult_JAXB_Serialization_Stub.write(iseries.wsbeans.datetestsoap.DateTestResult_JAXB_Serialization_Stub.java)
		 at iseries.wsbeans.datetestsoap.jaxws_asm.DatetestResponse_JAXB_Serialization_Stub.write(iseries.wsbeans.datetestsoap.jaxws_asm.DatetestResponse_JAXB_Serialization_Stub.java)
		 at com.ibm.xml.xlxp2.jaxb.marshal.impl.SerializationStub.writeJAXBElementCommon(SerializationStub.java:245)
		 at com.ibm.xml.xlxp2.jaxb.marshal.impl.SerializationStub.writeRootJAXBElement(SerializationStub.java:192)
		 at com.ibm.xml.xlxp2.jaxb.marshal.JAXB_Serialization_Root_Stub.write(com.ibm.xml.xlxp2.jaxb.marshal.JAXB_Serialization_Root_Stub.java)
		 at com.ibm.xml.xlxp2.jaxb.marshal.MarshallerImpl.marshal(MarshallerImpl.java:165)
		 at org.apache.cxf.jaxb.JAXBEncoderDecoder.writeObject(JAXBEncoderDecoder.java:566)
		 at org.apache.cxf.jaxb.JAXBEncoderDecoder.marshall(JAXBEncoderDecoder.java:236)
		 ... 37 more

Adding the following JVM property:

-Dcom.ibm.xml.xlxp.jaxb.opti.level=2

did resolve the problem.  However, customers will not know to add this and it appears to affect performance of the web service, so it needs to be resolved so things work as before. 

[DATETESTsoap.wsdl.txt](https://github.com/OpenLiberty/open-liberty/files/1861693/DATETESTsoap.wsdl.txt)
[DATETESTsoap.war.zip](https://github.com/OpenLiberty/open-liberty/files/1861697/DATETESTsoap.war.zip)

**Comment by sawadood** [comment]
As mentioned in the previous comment, please open a PMR for this issue.

**Comment by sawadood** [comment]
By the way, this is not an open liberty issue, this issue is caused by the version of xlxp that is used in CD-Open.
