### ISSUE TITLE
SELECT ID(entityvar) only returns part of IdClass

### ISSUE THREAD

**Issue by njr-11** [OpenLiberty/open-liberty#29073]
The following JPQL,
```
SELECT ID(THIS) FROM City WHERE (name=?1) ORDER BY population DESC
```

is used on an entity,
```
@Entity
@IdClass(CityId.class)
public class City {
    @Id
    public String name;
    public int population;
    @Id
    public String stateName;
    ...
}
```

with an IdClass
```
public record CityId(String name, String state) implements Serializable
```

The result ought to be a list of CityId.
Instead, it returns a list of String where the values are the `stateName` entity attribute, which is only one of the two components of the ID.

It looks like the same error occurs with the ID() function regardless of whether the entity identification variable is `THIS` or something else.  I tried with `SELECT ID(o) FROM City o` and saw the same result.

It should be noted that section 4.7.11 of the Jakarta Persistence 3.2 specification states that, "A persistence provider is not required to support the use of the ID function for entities with composite primary keys."  That means EclipseLink would have the option of raising an error and declaring the `ID()` function to be unsupported when IdClass is used.  However, that is not what is happening here either.  It is clearly trying to support the function, but returning the wrong value--only part of the composite primary key rather than the IdClass value that is the entire primary key.  This behavior will be useful to Jakarta Data (and some direct users of Jakarta Persistence can also benefit), so we would prefer to see it fixed rather than switched to unsupported.

**Comment by Riva-Tholoor-Philip** [comment]
See EclipseLink issue# [2211](https://github.com/eclipse-ee4j/eclipselink/issues/2211)

**Comment by njr-11** [comment]
FYI: Another variant of this problem which I noticed in tests is when we run the JPQL,
```
SELECT VERSION(THIS) FROM City WHERE ID(THIS) = ?1
```
EclipseLink is erroneously converting this to the SQL,
```
[5/15/25, 10:02:03:792 CDT] 00000038 id=00000000 eclipselink.ps.sql                                           3 SELECT CHANGECOUNT FROM City WHERE (STATENAME = ?)
```
which is wrong because it only includes the STATENAME field of CityId and not the city name.  EclipseLink actually accepts the CityId parameter here and converts it to something (maybe the toString of the CityId?) and runs the query, returning no matching results, indicating that whatever it sent to the database was not the state name, which would have matched entries in the database for this test.

**Comment by njr-11** [comment]
Retrying after EclipseLink beta 08, there has been some improvement to `SELECT ID(THIS)` in that it now returns all attributes of the IdClass type, but it erroneously returns them as `Object[]` rather than the IdClass type.
The variant of this issue with `WHERE ID(THIS)` is not fixed at all.

**Comment by njr-11** [comment]
The fix from @ChithraMini is a good improvement. It has all of the tests passing now except one, which does,

```
[1/30/26, 13:48:37:114 CST] 00000068 id=00000000 eclipselink.ps.query                                         3 Execute query ReportQuery(referenceClass=City sql="SELECT STATENAME, NAME FROM City ORDER BY STATENAME, NAME")
[1/30/26, 13:48:37:114 CST] 00000068 id=00000000 eclipselink.ps.connection                                    3 Connection acquired from connection pool [read].
[1/30/26, 13:48:37:114 CST] 00000068 id=00000000 eclipselink.ps.connection                                    3 reconnecting to external connection pool
[1/30/26, 13:48:37:114 CST] 00000068 id=00000000 eclipselink.ps.sql                                           3 SELECT STATENAME, NAME FROM City ORDER BY STATENAME, NAME
[1/30/26, 13:48:37:115 CST] 00000068 id=00000000 eclipselink.ps.connection                                    3 Connection released to connection pool [read].
[1/30/26, 13:48:37:115 CST] 00000068 id=3fc5b92a io.openliberty.data.internal.persistence.QueryInfo           3 result list type: public class java.util.Vector<E>
[1/30/26, 13:48:37:115 CST] 00000068 id=3fc5b92a io.openliberty.data.internal.persistence.QueryInfo           3 type of first result: java.lang.Object[]
```

The type of elements in the result list should be `CityId` (which is the IdClass), not an `Object[]` containing the fields that make up a `CityId` each as a separate element.

**Comment by njr-11** [comment]
I moved up to the latest that includes #34025 , cleaned up an area of the tests that is now passing, and removed the last remaining workaround for this from the Jakarta Data code.  That was mostly successful because in the past many tests required the workaround, but now only one test remains failing without the workaround in place.

It is a test that runs this JPQL query,

```SQL
SELECT ID(this) FROM CreditCard WHERE (this.securityCode=?1) ORDER BY this.issuer, this.number
```

against this entity:

```java
@Entity
@IdClass(CreditCard.CardId.class)
public class CreditCard {
    public static enum Issuer {
        AmericanExtravagance, Discrooger, MonsterCard, Feesa
    }

    public static record CardId(Issuer issuer, long number) {
        @Override
        public String toString() {
            return issuer + " card #" + number;
        }
    }

    @ManyToOne(cascade = CascadeType.ALL)
    public Customer debtor;

    @Column
    public LocalDate expiresOn;

    @Column
    public LocalDate issuedOn;

    @Id
    public Issuer issuer;

    @Id
    @Column(name = "ccnumber")
    public long number;

    @Column
    public int securityCode;

    ...
```

EclipseLink fails with:

```
[2/19/26, 8:43:47:103 CST] 0000005c id=00000000 eclipselink.ps.sql                                           3 SELECT ccnumber, ISSUER FROM CreditCard WHERE (SECURITYCODE = ?) ORDER BY ISSUER, ccnumber
	bind => [1 parameter bound]
[2/19/26, 8:43:47:104 CST] 0000005c id=00000000 eclipselink.ps.connection                                    3 Connection released to connection pool [read].
[2/19/26, 8:43:47:106 CST] 0000005c id=00000000 eclipselink.ps                                               3 CWWKD0291W: Exception [EclipseLink-6007] (Eclipse Persistence Services - 5.0.0-B13.v202512111447-a92ecc697995fa55709edc3c28d855c9c3ac2a1d): org.eclipse.persistence.exceptions.QueryException
Exception Description: Missing descriptor for [class test.jakarta.data.jpa.web.CreditCard$CardId].
Query: ReadObjectQuery(referenceClass=CardId )
[2/19/26, 8:43:47:106 CST] 0000005c id=00000000 eclipselink.ps                                               3 throwable 
                                                                                                               Local Exception Stack: 
Exception [EclipseLink-6007] (Eclipse Persistence Services - 5.0.0-B13.v202512111447-a92ecc697995fa55709edc3c28d855c9c3ac2a1d): org.eclipse.persistence.exceptions.QueryException
Exception Description: Missing descriptor for [class test.jakarta.data.jpa.web.CreditCard$CardId].
Query: ReadObjectQuery(referenceClass=CardId )
	at org.eclipse.persistence.exceptions.QueryException.descriptorIsMissing(QueryException.java:486)
	at org.eclipse.persistence.queries.ReadObjectQuery.checkDescriptor(ReadObjectQuery.java:247)
	at org.eclipse.persistence.internal.sessions.IsolatedClientSession.isIsolatedQuery(IsolatedClientSession.java:74)
	at org.eclipse.persistence.internal.sessions.IsolatedClientSession.shouldExecuteLocally(IsolatedClientSession.java:63)
	at org.eclipse.persistence.internal.sessions.IsolatedClientSession.getExecutionSession(IsolatedClientSession.java:142)
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.getExecutionSession(UnitOfWorkImpl.java:2202)
	at org.eclipse.persistence.queries.DatabaseQuery.getExecutionSession(DatabaseQuery.java:1399)
	at org.eclipse.persistence.mappings.DatabaseMapping.valueFromRow(DatabaseMapping.java:1888)
	at org.eclipse.persistence.internal.descriptors.ObjectBuilder.buildNewRecordInstance(ObjectBuilder.java:777)
	at org.eclipse.persistence.queries.ReportQuery.buildObject(ReportQuery.java:690)
	at org.eclipse.persistence.queries.ReportQuery.buildObjects(ReportQuery.java:750)
	at org.eclipse.persistence.queries.ReportQuery.executeDatabaseQuery(ReportQuery.java:991)
	at org.eclipse.persistence.queries.DatabaseQuery.execute(DatabaseQuery.java:937)
	at org.eclipse.persistence.queries.ObjectLevelReadQuery.execute(ObjectLevelReadQuery.java:1256)
	at org.eclipse.persistence.queries.ReadAllQuery.execute(ReadAllQuery.java:485)
	at org.eclipse.persistence.queries.ObjectLevelReadQuery.executeInUnitOfWork(ObjectLevelReadQuery.java:1344)
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.internalExecuteQuery(UnitOfWorkImpl.java:3018)
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1866)
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1848)
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1813)
	at org.eclipse.persistence.internal.jpa.QueryImpl.executeReadQuery(QueryImpl.java:264)
	at org.eclipse.persistence.internal.jpa.QueryImpl.getResultList(QueryImpl.java:481)
```
