### ISSUE TITLE
Test Failure: io.openliberty.microprofile.telemetry.logging.internal_fat.TelemetryFFDCTest.testTelemetryFFDCMessages

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#29316]
RTC 301134

```
testTelemetryFFDCMessages:junit.framework.AssertionFailedError: 2024-08-04-10:49:01:556 Should contain early FFDC message FFDC_TEST_INIT
    at io.openliberty.microprofile.telemetry.logging.internal_fat.TelemetryFFDCTest.lambda$testTelemetryFFDCMessages$1(TelemetryFFDCTest.java:83)
    at io.openliberty.microprofile.telemetry.logging.internal_fat.TelemetryFFDCTest.testTelemetryFFDCMessages(TelemetryFFDCTest.java:98)
    at io.openliberty.microprofile.telemetry.logging.internal_fat.TelemetryFFDCTest.testTelemetryFFDCMessages(TelemetryFFDCTest.java:77)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:204)
    at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:364)
    at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:178)
```

**Comment by tonyreigns** [comment]
New issue: https://github.com/OpenLiberty/open-liberty/issues/29367

This test was removed while the release bug is resolved.
