### ISSUE TITLE
Test Failure: io.openliberty.microprofile.telemetry.internal.monitor_fat.LibertyMetricsTest.sessionsMetricTest

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#29314]
RTC 301092

```
sessionsMetricTest:junit.framework.AssertionFailedError: 2024-08-01-13:39:52:271 Did not contain string: io_openliberty_session_created_total{io_openliberty_application_name="default_host/testSessionApp",job="io.openliberty.microprofile.telemetry.runtime"}
at io.openliberty.microprofile.telemetry.internal.monitor_fat.BaseTestClass.checkStrings(BaseTestClass.java:90)
at io.openliberty.microprofile.telemetry.internal.monitor_fat.LibertyMetricsTest.sessionsMetricTest(LibertyMetricsTest.java:113)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:204)
at org.testcontainers.containers.FailureDetectingExternalResource$1.evaluate(FailureDetectingExternalResource.java:29)
at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:364)
at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:178)
```

**Comment by Channyboy** [comment]
Appears to have stopped occurring as of August 1st.

**Comment by Channyboy** [comment]
Root issue solved.
