### ISSUE TITLE
jakarta.ws.rs.NotSupportedException with content type application/json when using mpOpenAPI-4.0 feature

### ISSUE THREAD

**Issue by tam512** [OpenLiberty/open-liberty#29334]
Use Open Liberty `24.0.0.9-beta (wlp-1.0.92.cl240820240729-1903) `and java.version = 17.0.11
Use the following features
```
	<featureManager>
		<platform>jakartaee-11.0</platform>
		<feature>appSecurity</feature>
		<feature>beanValidation</feature>
		<feature>cdi</feature>
		<feature>enterpriseBeansLite</feature>
		<feature>faces</feature>
		<feature>pages</feature>
		<feature>persistence</feature>
		<feature>restfulWS</feature>
		<feature>websocket</feature>
		<feature>xmlWS</feature>
		<feature>jndi-1.0</feature>
		<feature>ldapRegistry-3.0</feature>
		<feature>localConnector-1.0</feature>
		<platform>microProfile-7.0</platform>
		<feature>mpOpenAPI</feature>
		<feature>mphealth</feature>
	  </featureManager>
```

Run a POST operation on http://localhost:9081/openapi/ui/ and I got  return code 415 with `Error: Unsupported Media Type`
and here is the error in messages.log

This POST operation works OK when using _microProfile-6.0_ or _mpOpenAPI-3.1_ feature

```
[8/8/24, 14:12:58:346 CDT] 0000003e org.jboss.resteasy.resteasy_jaxrs.i18n                       E RESTEASY002010: Failed to execute
jakarta.ws.rs.NotSupportedException: RESTEASY003200: Could not find message body reader for type: class io.microprofile.openapi.model.Forecast of content type: application/json
	at org.jboss.resteasy.core.interception.jaxrs.ServerReaderInterceptorContext.throwReaderNotFound(ServerReaderInterceptorContext.java:54)
	at org.jboss.resteasy.core.interception.jaxrs.AbstractReaderInterceptorContext.getReader(AbstractReaderInterceptorContext.java:129)
	at org.jboss.resteasy.core.interception.jaxrs.AbstractReaderInterceptorContext.proceed(AbstractReaderInterceptorContext.java:76)
	at org.jboss.resteasy.core.MessageBodyParameterInjector.inject(MessageBodyParameterInjector.java:192)
	at org.jboss.resteasy.core.MethodInjectorImpl.injectArguments(MethodInjectorImpl.java:87)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:116)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:560)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:452)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:413)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:397)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:415)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:378)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:356)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:70)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:429)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:240)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:154)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:397)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:157)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:229)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:245)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:55)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:723)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1266)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:754)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:451)
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.invokeTarget(WebAppFilterChain.java:197)
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:100)
	at com.ibm.ws.security.jaspi.JaspiServletFilter.doFilter(JaspiServletFilter.java:58)
	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:203)
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:93)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.doFilter(WebAppFilterManager.java:1069)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1260)
	at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:5096)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.handleRequest(DynamicVirtualHost.java:328)
	at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:1047)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:293)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1260)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:476)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:435)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:569)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:503)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:363)
	at com.ibm.ws.http.channel.internal.inbound.HttpICLReadCallback.complete(HttpICLReadCallback.java:72)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:516)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueManager.java:586)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:970)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:1059)
	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:280)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:857)
```

Looking at [Migrating from OpenAPI 3.0 to 3.1.0](https://www.openapis.org/blog/2021/02/16/migrating-from-openapi-3-0-to-3-1-0) doc, I do not see anything about not supporting content type `application/json` in openapi 3.1.0

**Comment by Azquelt** [comment]
The error looks like it's being reported by the endpoint you're making the POST request to, not by the `mpOpenAPI` feature. I suspect you would get the same error if you made the same request without the `mpOpenAPI` feature active.

Based on the error and your server.xml, you might be missing the `jsonb` feature? If you were previously using `microProfile-6.0`, that would include `jsonb`, but your current configuration does not.

If that doesn't fix the problem, please provide more information about your application, particularly the java method that implements the endpoint you're trying to POST to and we can investigate further.

**Comment by tam512** [comment]
You are right about I was missing the `jsonb` feature.
when I specified features list above, Liberty installed the following features
```
The server installed the following features: [appSecurity-6.0, cdi-4.1, distributedMap-1.0, enterpriseBeansLite-4.0, expressionLanguage-6.0, faces-4.1, federatedRegistry-1.0, jdbc-4.3, jndi-1.0, json-1.0, jsonp-2.1, ldapRegistry-3.0, localConnector-1.0, mpConfig-3.1, mpHealth-4.0, mpOpenAPI-4.0, pages-4.0, persistence-3.2, persistenceContainer-3.2, restfulWS-4.0, restfulWSClient-4.0, servlet-6.1, ssl-1.0, transportSecurity-1.0, validation-3.1, websocket-2.2, xmlBinding-4.0, xmlWS-4.0].
```
I just updated to use `<feature>microProfile-7.0</feature>` and I see it installed `jsonb-3.0`
```
The server installed the following features: [appSecurity-6.0, cdi-4.1, distributedMap-1.0, enterpriseBeansLite-4.0, expressionLanguage-6.0, faces-4.1, federatedRegistry-1.0, jdbc-4.3, jndi-1.0, json-1.0, jsonb-3.0, jsonp-2.1, jwt-1.0, ldapRegistry-3.0, localConnector-1.0, microProfile-7.0, monitor-1.0, mpConfig-3.1, mpFaultTolerance-4.1, mpHealth-4.0, mpJwt-2.1, mpOpenAPI-4.0, mpRestClient-4.0, mpTelemetry-2.0, pages-4.0, persistence-3.2, persistenceContainer-3.2, restfulWS-4.0, restfulWSClient-4.0, servlet-6.1, ssl-1.0, transportSecurity-1.0, validation-3.1, websocket-2.2, xmlBinding-4.0, xmlWS-4.0].
```
I can run the POST ok now.  Thanks @Azquelt for looking into this issue!
