### ISSUE TITLE
Update Kafka Client used by Reactive tests to one that supports Java23

### ISSUE THREAD

**Issue by abutch3r** [OpenLiberty/open-liberty#29403]
The current Kafka Clients used for Reactive testing do not support Java23, in particular when using SASL - https://issues.apache.org/jira/browse/KAFKA-15862.

```
Caused by: org.apache.kafka.common.errors.SaslAuthenticationException: Failed to configure SaslClientAuthenticator
Caused by: java.lang.UnsupportedOperationException: getSubject is supported only if a security manager is allowed
	at java.base/javax.security.auth.Subject.getSubject(Subject.java:347)
	at org.apache.kafka.common.security.authenticator.SaslClientCallbackHandler.handle(SaslClientCallbackHandler.java:58)
	at java.security.sasl/com.sun.security.sasl.ClientFactoryImpl.getUserInfo(ClientFactoryImpl.java:138)
	at java.security.sasl/com.sun.security.sasl.ClientFactoryImpl.createSaslClient(ClientFactoryImpl.java:96)
```

When a client is available that resolves this issue we will need to pull that in to get the Reactive Messaging SASL tests.  #29455 is the PR that disabled the tests for Java versions 23+.

Shims were added to 4.0.0 and 3.9.1 to work with Java23 - though whether they continue to work from Java25 onwards is questionable with

**Comment by abutch3r** [comment]
4.0.0 testing was added as part of https://github.com/OpenLiberty/open-liberty/pull/31271
so updating the 3.x library to 3.9.1 should allow for us to increase the Max java version for running the security tests
