### ISSUE TITLE
Cannot reflect on an injected ServletContext

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/open-liberty#29447]
**Describe the bug**  
If a `ServletContext` is injected with `@Inject`, calling `getMethods()` on the class may fail with the following error:

```
java.lang.NoClassDefFoundError: jakarta.servlet.descriptor.JspConfigDescriptor
    at java.base/java.lang.Class.getVirtualMethodsImpl(Native Method)
    at java.base/java.lang.Class.getMethodSet(Class.java:1811)
    at java.base/java.lang.Class.getMethods(Class.java:1774)
    at com.example.MyClass.myMethod(...)
    [...]
Caused by: java.lang.ClassNotFoundException: jakarta.servlet.descriptor.JspConfigDescriptor cannot be found by io.openliberty.org.jboss.weld5_1.0.93.202408191114
    at org.eclipse.osgi.internal.loader.BundleLoader.generateException(BundleLoader.java:541)
    at org.eclipse.osgi.internal.loader.BundleLoader.findClass0(BundleLoader.java:536)
    at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:416)
    at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:168)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1094)
    ... 38 more
```

This may also occur during other operations which involve reflection, such as attempting to serialize the object for session persistence.

**Steps to Reproduce**  
```java
@Inject private ServletContext context;

public void testMethod() {
    context.getClass().getMethods();
}
```

**Expected behavior**  
`getMethods` should return normally

**Diagnostic information:**  
 - OpenLiberty Version: current integration
 - Affected feature(s) cdi-3.0, cdi-4.0, cdi-4.1
 - Java Version:
   - OpenJDK Runtime Environment (21+35-2513)
   - OpenJDK Runtime Environment (17.0.7+7)
   - IBM Semeru Runtime Certified Edition (17.0.7+7)

**Comment by Azquelt** [comment]
We're creating the proxy for the ServletContext built-in bean using the weld bundle. Weld is giving us the `Bean<T>` class for the bean, not the `ServletContext` class to use to find the correct classloader to define the proxy class.

We could manually add the import for `jakarta.servlet.descriptor` to the weld bundle, but that feels like a hack.

Raised https://issues.redhat.com/browse/WELD-2796 to query how this is supposed to work.

**Comment by Azquelt** [comment]
The conclusion of the Weld issue is that this isn't a case that was fully considered for `ProxyServices` and that, at least for the moment, we should require bundles which provide synthetic beans to import all packages necessary to load the proxy object for that bean.

This means adding the import of `jakarta.servlet.descriptor` to our weld bundles. We'll also make this change in Weld itself.
