### ISSUE TITLE
JPQL SELECT NEW not joining nor recogning ElementCollection as a collection type

### ISSUE THREAD

**Issue by KyleAure** [OpenLiberty/open-liberty#29475]
EclipseLink is rejecting JPQL SELECT NEW clauses where an entity contains an attribute that is an ElementCollection.

For example, `SELECT o.comments FROM Rating o WHERE o.id = :id` where the column `comments` is an ElementCollection is correctly returned as a result set.
We can see from the SQL generated by EclipseLink that a JOIN is required to get the data from the `Rating_COMMENTS` table:
```sql
SELECT t1.COMMENTS 
FROM RATING t0 
  LEFT OUTER JOIN Rating_COMMENTS t1 
  ON (t1.Rating_ID = t0.ID) 
WHERE (t0.ID = ?)
```

However, when we try to use `o.comments` in a `SELECT NEW` query like the one below:
```sql
SELECT NEW 
  io.openliberty.jpa.data.tests.models.Rating( o.id, o.item, o.numStars, o.reviewer, o.comments )
FROM Rating o 
WHERE o.id = :id
```

The following error is thrown: 
```txt
Exception [EclipseLink-0] (Eclipse Persistence Services - 5.0.0.v202408071314-43356e84b79e71022b1656a5462b0a72d70787a4): org.eclipse.persistence.exceptions.JPQLException
Exception Description: Problem compiling [SELECT NEW io.openliberty.jpa.data.tests.models.Rating( o.id, o.item, o.numStars, o.reviewer, o.comments ) FROM Rating o WHERE o.id = :id].
[93, 103] The state field path 'o.comments' cannot be resolved to a collection type. (SELECT NEW io.openliberty.jpa.data.tests.models.Rating(o.id, o.item, o.numStars, o.reviewer, [ o.comments ] ...
at org.eclipse.persistence.internal.jpa.jpql.HermesParser.buildException(HermesParser.java:175)
at org.eclipse.persistence.internal.jpa.jpql.HermesParser.validate(HermesParser.java:364)
at org.eclipse.persistence.internal.jpa.jpql.HermesParser.populateQueryImp(HermesParser.java:298)
at org.eclipse.persistence.internal.jpa.jpql.HermesParser.buildQuery(HermesParser.java:180) 
```

I would have expected EclipseLink to be able to satisfy this JPQL query with a SQL Query something like:
```sql
SELECT t0.ID, t0.NAME, t0.PRICE, t0.NUMSTARS, t0.EMAIL, t0.FIRSTNAME, t0.LASTNAME, t1.COMMENTS 
FROM RATING t0
  LEFT OUTER JOIN Rating_COMMENTS t1 
  ON (t1.Rating_ID = t0.ID) 
WHERE (t0.ID = ?)
```

**Comment by Riva-Tholoor-Philip** [comment]
Refer the EclipseLink Issue# [2264](https://github.com/eclipse-ee4j/eclipselink/issues/2264)

**Comment by ajaypaul-ibm** [comment]
@njr-11 Can we close this issue as we are checking the Element Collection issues in #28589 ?

**Comment by njr-11** [comment]
> [@njr-11](https://github.com/njr-11) Can we close this issue as we are checking the Element Collection issues in [#28589](https://github.com/OpenLiberty/open-liberty/issues/28589) ?

That's fine with me given that you are tracking it under the other issue.

**Comment by ajaypaul-ibm** [comment]
Closing this issue
