### ISSUE TITLE
Remove extra FFDC when monitor-1.0 is enabled

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#29581]
RTC 301370

```
VoidQueryTestServlet.testSimpleQueryFails_EE8_FEATURES_MicroProfile_40_mpGraphQL10:junit.framework.AssertionFailedError: 2024-08-16-06:47:55:140 [Unexpected FFDC reporting java.io.FileNotFoundException was found (count = 1): C:\Users\jazz_build\Build\workspace\ebcTestRunner\dev\autoFVT\image\output\wlp\usr\servers\mpGraphQL10.voidQuery\logs\ffdc\ffdc_24.08.16_06.47.51.0.log
>------Start of DE processing------ = [8/16/24 6:47:51:875 PDT]
>Exception = java.io.FileNotFoundException
>Source = io.openliberty.http.monitor.ServletFilter
>probeid = 66
>Stack Dump = java.io.FileNotFoundException: SRVE0190E: File not found: /graphql
> at com.ibm.ws.webcontainer.extension.DefaultExtensionProcessor.handleRequest(DefaultExtensionProcessor.java:496)
> at com.ibm.ws.webcontainer.filter.WebAppFilterChain.invokeTarget(WebAppFilterChain.java:197)
> at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:100)
> at io.openliberty.http.monitor.ServletFilter.doFilter(ServletFilter.java:65)
> at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:203)
> at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:93)
> at com.ibm.ws.webcontainer.filter.WebAppFilterManager.doFilter(WebAppFilterManager.java:1069)
> at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1260)
> at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:5096)
> at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.handleRequest(DynamicVirtualHost.java:328)
> at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:1047)
> at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:293)
> at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1260)
> at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:476)
> at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:435)
> at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:569)
> at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:503)
> at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:363)
> at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.ready(HttpInboundLink.java:330)
> at com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.sendToDiscriminators(NewConnectionInitialReadCallback.java:169)
> at com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.complete(NewConnectionInitialReadCallback.java:77)
> at com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:516)
> at com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueManager.java:586)
> at com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:970)
> at com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:1059)
> at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:298)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
> at java.lang.Thread.run(Thread.java:825)
]
at componenttest.custom.junit.runner.FATRunner.blowup(FATRunner.java:347)
at componenttest.custom.junit.runner.FATRunner.access$600(FATRunner.java:70)
at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:290)
at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:365)
at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:178)
at componenttest.rules.repeater.RepeatTests$CompositeRepeatTestActionStatement.evaluate(RepeatTests.java:145)
```

**Comment by Channyboy** [comment]
Opened release bug at https://github.com/OpenLiberty/open-liberty/issues/29584
