### ISSUE TITLE
Using the mpTelemetry-1.1 feature in a z/OS Connect server on Zos leads to FFDCs

### ISSUE THREAD

**Issue by JDUNNIN** [OpenLiberty/open-liberty#29591]
**Describe the bug**  
Previously raised in was-embedders Slack channel.

From messages.log
```
product = WAS FOR Z/OS 24.0.0.6, z/OS Connect 03.00.84
...
[9/5/24, 13:49:55:912 GMT] 0000002d com.ibm.ws.webcontainer.servlet                              I SRVE0242I: [com.ibm.zosconnect.apirequester] [/zosConnect/apiRequesters] [com.ibm.zosconnect.apirequester.internal.web.ApiRequesterServlet]: Initialization successful.
[9/5/24, 13:49:55:956 GMT] 0000002d com.ibm.ws.logging.internal.impl.IncidentImpl                I FFDC1015I: An FFDC Incident has been created: "java.lang.IllegalStateException: Attempted to create openTelemetaryInfo for application com.ibm.zosconnect.apirequester which has not gone through ApplicationStarting io.openliberty.microprofile.telemetry.internal.common.info.OpenTelemetryInfoFactoryImpl 120" at ffdc_24.09.05_13.49.55.0.log
[9/5/24, 13:49:55:962 GMT] 0000002d .telemetry.internal.common.info.OpenTelemetryInfoFactoryImpl E CWMOT5002E: An internal error occurred in MicroProfile Telemetry. The error is: java.lang.IllegalStateException: Attempted to create openTelemetaryInfo for application com.ibm.zosconnect.apirequester which has not gone through ApplicationStarting.
...
[9/5/24, 13:50:00:689 GMT] 0000002d com.ibm.ws.webcontainer.servlet                              I SRVE0242I: [com.ibm.zosconnect] [/] [com.ibm.zosconnect.internal.web.ServiceProxyServlet]: Initialization successful.
[9/5/24, 13:50:01:309 GMT] 0000002f om.ibm.ws.app.manager.rar.internal.RARApplicationHandlerImpl A J2CA7001I: Resource adapter gmoa installed in 6.424 seconds.
[9/5/24, 13:50:01:326 GMT] 0000002d com.ibm.ws.logging.internal.impl.IncidentImpl                I FFDC1015I: An FFDC Incident has been created: "java.lang.IllegalStateException: Attempted to create openTelemetaryInfo for application com.ibm.zosconnect which has not gone through ApplicationStarting io.openliberty.microprofile.telemetry.internal.common.info.OpenTelemetryInfoFactoryImpl 120" at ffdc_24.09.05_13.50.01.0.log
[9/5/24, 13:50:01:327 GMT] 0000002d .telemetry.internal.common.info.OpenTelemetryInfoFactoryImpl E CWMOT5002E: An internal error occurred in MicroProfile Telemetry. The error is: java.lang.IllegalStateException: Attempted to create openTelemetaryInfo for application com.ibm.zosconnect which has not gone through ApplicationStarting.
...
[9/5/24, 13:50:01:377 GMT] 00000026 com.ibm.ws.kernel.feature.internal.FeatureManager            A CWWKF0012I: The server installed the following features: [apiDiscovery-1.0, appSecurity-2.0, cdi-1.2, distributedMap-1.0, ejbLite-3.2, imsmobile:imsmobile-2.0, jaxb-2.2, jaxrs-2.0, jaxrsClient-2.0, jaxws-2.2, jca-1.7, jndi-1.0, json-1.0, jsonp-1.0, jwt-1.0, mpConfig-1.3, mpTelemetry-1.1, servlet-3.1, ssl-1.0, wmqJmsClient-2.0, zosSecurity-1.0, zosTransaction-1.0, zosconnect:apiRequester-1.0, zosconnect:cicsService-1.0, zosconnect:mqService-1.0, zosconnect:zosConnect-2.0, zosconnect:zosConnectApiDiscovery-1.0, zosconnect:zosConnectCommands-1.0].
[9/5/24, 13:50:01:377 GMT] 00000026 com.ibm.ws.kernel.feature.internal.FeatureManager            I CWWKF0008I: Feature update completed in 22.782 seconds.
```

From FFDC:
```
Exception = java.lang.IllegalStateException
Source = io.openliberty.microprofile.telemetry.internal.common.info.OpenTelemetryInfoFactoryImpl
probeid = 120
Stack Dump = java.lang.IllegalStateException: Attempted to create openTelemetaryInfo for application com.ibm.zosconnect.apirequester which has not gone through ApplicationStarting
	at io.openliberty.microprofile.telemetry.internal.common.info.OpenTelemetryInfoFactoryImpl.getOpenTelemetryInfo(OpenTelemetryInfoFactoryImpl.java:116)
	at io.openliberty.microprofile.telemetry.internal.common.info.OpenTelemetryInfoFactoryImpl.getOpenTelemetryInfo(OpenTelemetryInfoFactoryImpl.java:96)
	at io.openliberty.microprofile.telemetry.internal.interfaces.OpenTelemetryAccessor.lambda$getOpenTelemetryInfo$0(OpenTelemetryAccessor.java:48)
	at com.ibm.ws.kernel.service.util.ServiceCaller.lambda$call$3(ServiceCaller.java:457)
	at java.base/java.util.Optional.map(Optional.java:260)
	at com.ibm.ws.kernel.service.util.ServiceCaller.call(ServiceCaller.java:456)
	at io.openliberty.microprofile.telemetry.internal.interfaces.OpenTelemetryAccessor.getOpenTelemetryInfo(OpenTelemetryAccessor.java:47)
	at io.openliberty.microprofile.telemetry11.internal.rest.TelemetryServletFilter.createInstrumenter(TelemetryServletFilter.java:100)
	at io.openliberty.microprofile.telemetry11.internal.rest.TelemetryServletFilter.init(TelemetryServletFilter.java:76)
	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.init(FilterInstanceWrapper.java:145)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager._loadFilter(WebAppFilterManager.java:694)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.loadFilter(WebAppFilterManager.java:555)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.init(WebAppFilterManager.java:286)
	at com.ibm.ws.webcontainer.osgi.webapp.WebApp.initializeFilterManager(WebApp.java:859)
	at com.ibm.ws.webcontainer.webapp.WebApp.commonInitializationFinally(WebApp.java:1213)
	at com.ibm.ws.webcontainer.webapp.WebApp.initialize(WebApp.java:1094)
	at com.ibm.ws.webcontainer.webapp.WebApp.initialize(WebApp.java:6722)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost.startWebApp(DynamicVirtualHost.java:484)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost.startWebApplication(DynamicVirtualHost.java:479)
	at com.ibm.ws.webcontainer.osgi.WebContainer.startWebApplication(WebContainer.java:1208)
	at com.ibm.ws.webcontainer.osgi.WebContainer.access$100(WebContainer.java:113)
	at com.ibm.ws.webcontainer.osgi.WebContainer$3.run(WebContainer.java:996)
	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:280)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:857)
```

**Steps to Reproduce**  
Steps to reproduce the bug

I would expect that taking Liberty, adding a product extension with a custom liberty feature (e.g. test-1.0) then also making a servlet inside that feature in the same way I describe below. If that server gets started with both `test-1.0` and `mpTelemetry-1.1` I expect the error occur (?).

**Expected behavior**  
Enabling the feature does not cause errors.

**Diagnostic information:**  
 - OpenLiberty Version: WAS FOR Z/OS 24.0.0.6, z/OS Connect 03.00.84
 - Affected feature(s) mpTelemetry-1.1
 - Java Version:  IBM Semeru Runtime Certified Edition for z/OS (17.0.10+7)
 - server.xml configuration
```
<featureManager>
    <feature>zosconnect:zosconnect-2.0</feature> 
    <feature>mpTelemetry-1.1</feature>
</featureManager>
```
 - If it would be useful, upload the messages.log file found in `$WLP_OUTPUT_DIR/messages.log`

**Additional context**  
z/OS Connect is a Liberty product extension and as part of that provides two servlets (both extending HttpServlet) using the `@WebServlet` annotation with options `asyncSupported = true, urlPatterns = { <many patterns> }, loadOnStartup = 1, displayName = "z/OS Connect"`

As `loadOnStartup = 1` we also `@Override` the `public void init(ServletConfig servletConfig)` method. In this code we use the `servletConfig` to get a `ServletContext` then `BundleContext` from which we then obtain `ServiceReference`'s to multiple z/OS Connect OSGi resources.

Our `bnd.bnd` for one of the features which provides a servlet has `Web-ContextPath: /` in it if that matters.

**Comment by benjamin-confino** [comment]
I've created a branch [here](https://github.com/benjamin-confino/open-liberty/tree/29591-telemetry-cannot-handle-user-feature-wab) that recreates the issue. Actually solving it will require dicsussion with the team to pick one of four options. Or maybe someone has an even better idea

Since this only occurs when OpenTelemetry is running in application mode we know that the application must have a microprofile.config.properties to be enabled. We can add a second check to that file, skip the exception if the user feature is not enabled, or if it is we could check a new config property that allows OpenTelemetry to be created for this WAB.

We could make WABInstaller add something to ApplicationMetaData so we can tell we're looking at a user feature and behave accordingly. (A quick look suggests a way: WABInstaller has access to a Bundle object, `bundle.getLocation()` returns a string that looks like it can be used to tell if its a User Feature, then that info can be passed into `createApplicationInfo` at line 484 to become part of the ApplicationMetaData). 

We could skip this check entirely and just create a no-op OpenTelemetry if we ever get asked for one for an application that has never started.

We could skip this check entirely and always create a working OpenTelemetry. 

Currently we stash OpenTelemetry objects in the ApplicationMetaData's slots, so if ApplicationMetaData gets cleaned up if a WAB is ever uninstalled we will not have to worry about derefrencing the OpenTelemetry object.
