### ISSUE TITLE
Handle field name collisions with embeddables

### ISSUE THREAD

**Issue by KyleAure** [OpenLiberty/open-liberty#29643]
User story:
As a user of Open Liberty and Jakarta Data, I may accidentally configure an entity field which collides with the field name of an embedded or mapped superclass without realizing it, resulting in an effectively transient field.  When this happens Jakarta Persistence will throw errors on `insert` as it will attempt insert into the same column twice.

Example exception:
```txt
jakarta.persistence.PersistenceException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 5.0.0.v202408200932-f556522e743c87b8097f78cefe2b8f24f68cf79e): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: java.sql.SQLSyntaxErrorException: Column name 'BEDROOMWIDTH' appears more than once times in the column list of an INSERT statement. 
Error Code: 20000
Call: INSERT INTO WLPApartment (APTID, BEDROOMWIDTH, BEDROOMLENGTH, BEDROOMWIDTH) VALUES (?, ?, ?, ?)
	bind => [4 parameters bound]
Query: InsertObjectQuery(test.jakarta.data.web.Apartment@a2006507)
	at io.openliberty.data.internal.persistence.RepositoryImpl.failure(RepositoryImpl.java:503)
	at io.openliberty.data.internal.persistence.RepositoryImpl.invoke(RepositoryImpl.java:1547)
	at jdk.proxy14/jdk.proxy14.$Proxy66.saveAll(Unknown Source)
```

## Jakarta Persistence annotated entity

The following entity and embeddable:
```java
@Entity
public class Apartment {
    @Id
    public long aptId;
    public int width;
    @Embedded
    public Bedroom quarters;
}

@Embeddable
public class Bedroom {
    public int width;
    public int length;
}
```

Will generate the following table:
```SQL
CREATE TABLE WLPApartment (
  APTID BIGINT NOT NULL, 
  LENGTH INTEGER, 
  WIDTH INTEGER, 
  PRIMARY KEY (APTID)
)
```

Resulting in the `width` field of Apartment being transient.

## Unannotated entitiy

The following entity and embeddable:
```java
public class Apartment  {
    public long aptId;
    public int bedroomWidth;
    public Bedroom quarters;
}

public class Bedroom {
    public int width;
    public int length;
}
```

Will generate the following table:
```SQL
CREATE TABLE WLPApartment (
  APTID BIGINT NOT NULL, 
  BEDROOMLENGTH INTEGER,
  BEDROOMWIDTH INTEGER,
  PRIMARY KEY (APTID)
)
```

Resulting in the `bedroomWidth` field of Apartment being transient.

**Comment by KyleAure** [comment]
This has already been implemented and tests have been written for both annotated and unannotated entities, along with collisions based on embeddable in the entity and in a mappedsuperclass.  

See: 
https://github.com/OpenLiberty/open-liberty/pull/29637
