### ISSUE TITLE
Fix GVT failure for non-English locales

### ISSUE THREAD

**Issue by nijoj** [OpenLiberty/open-liberty#29665]
Currently GVT UI tests fails in some non-English locales (e.g. GVT in JMX REST Connector APIs). This is due to the server logs are read in ISO format instead of UTF-8

For RTC 301296

```
testUnicodeForNotification:junit.framework.AssertionFailedError: 2024-08-13-01:29:16:852 The SSL TCP Channel for default HTTPS endpoint did not start in time.
    at com.ibm.ws.gvt.rest.fat.BaseTestCase.waitForDefaultHttpsEndpoint(BaseTestCase.java:78)
    at com.ibm.ws.gvt.rest.fat.GvtTest.before(GvtTest.java:44)
...
```

**Comment by nijoj** [comment]
Initial fix was reverted due to issues with running in ZOS
