### ISSUE TITLE
setServerStarted method throws exception in ThreadPoolController.startupCompleted()

### ISSUE THREAD

**Issue by gjdeval** [OpenLiberty/open-liberty#29711]
**Describe the bug**  
Changes in [PR29255](https://github.com/OpenLiberty/open-liberty/pull/29255) introduced a race condition under which two threads can simultaneously try to change the pool size. 

This race condition can lead to an exception at the time that "server started" is reported in the messages.log, with a callstack showing the `ThreadPoolController.startupCompleted` method, like this (showing top of stack only):

```
The setServerStarted method has thrown an exception java.lang.IllegalArgumentException
        at java.base/java.util.concurrent.ThreadPoolExecutor.setMaximumPoolSize(ThreadPoolExecutor.java:1686)
        at com.ibm.ws.threading.internal.ThreadPoolController.setPoolSize(ThreadPoolController.java:1824)
        at com.ibm.ws.threading.internal.ThreadPoolController.startupCompleted(ThreadPoolController.java:781)
        at com.ibm.ws.threading.internal.ExecutorServiceImpl.setServerStarted(ExecutorServiceImpl.java:88)
   ... snip ...
```

**Steps to Reproduce**  
There is no reliable way to reproduce a race condition problem. This issue may or may not occur any time Liberty is started.

**Expected behavior**  
Liberty should start without an exception thrown by `ThreadPoolController.startupCompleted` method.

**Diagnostic information:**  
 - OpenLiberty Version: 24.0.0.9 - 24.0.0.10

**Comment by jhanders34** [comment]
#regression
