### ISSUE TITLE
SVT:Cannot find component for expression

### ISSUE THREAD

**Issue by jagraj** [OpenLiberty/open-liberty#29725]
My Jakarta EE10 application is failing after enabling Jakarta EE11 features in the server.xml file with the following exception.
Looks like Ajax calls are failing in one of the JSF facelet page. I also captured the logs with this tracespec "*=info:com.ibm.ws.webcontainer*=all:com.ibm.wsspi.webcontainer*=all:com.ibm.ws.webcontainer31*=all:HTTPChannel=all:TCPChannel=all:websockets=all:com.ibm.ws.jsf*=all:org.apache.myfaces*=all"

**Logs**
[logs.zip](https://github.com/user-attachments/files/17134082/logs.zip)

**server.xml** 

```
    <featureManager>
		<feature>xmlWS-4.0</feature>
		<feature>xmlBinding-4.0</feature>
		<!-- <feature>managedBeans-2.0</feature> -->
		<feature>appSecurity-6.0</feature>
        <feature>jdbc-4.3</feature>
    	<feature>concurrent-3.1</feature>
		<!-- <feature>osgiConsole-1.0</feature> -->
		 <feature>usr:WASPersonaWebServicesHandlerFeature</feature>
		<feature>websocket-2.2</feature>
    	<feature>expressionLanguage-6.0</feature>
		<feature>validation-3.1</feature>
		<feature>cdi-4.1</feature>
		<feature>faces-4.1</feature>
		<feature>enterpriseBeansLite-4.0</feature>
		<feature>persistence-3.2</feature>
		<feature>restfulWS-4.0</feature>
 		<!--  <feature>wsAtomicTransaction-1.2</feature>--> 		
    	<feature>mpHealth-4.0</feature>
    	<feature>mpMetrics-5.1</feature>
    	<feature>mpConfig-3.1</feature>
    	<feature>mpTelemetry-2.0</feature>
		<!-- Features with the versions -->
    	<feature>jndi-1.0</feature>
		<feature>localConnector-1.0</feature>
		<feature>monitor-1.0</feature>
		<feature>ssl-1.0</feature>
		<feature>sessionDatabase-1.0</feature>
    	<feature>json-1.0</feature>
	</featureManager>

```

```
[err] jakarta.faces.component.search.ComponentNotFoundException: Cannot find component for expression "cartForm:cartTable cartForm:subTotal cartForm:taxAmount cartForm:total" referenced from "shoppingCartForm_form:updateButton".
[err] 	at org.apache.myfaces.component.search.SearchExpressionHandlerImpl.resolveClientIds(SearchExpressionHandlerImpl.java:179)
[err] 	at org.apache.myfaces.renderkit.html.util.AjaxScriptBuilder.appendIds(AjaxScriptBuilder.java:278)
[err] 	at org.apache.myfaces.renderkit.html.util.AjaxScriptBuilder.build(AjaxScriptBuilder.java:205)
[err] 	at org.apache.myfaces.renderkit.html.util.AjaxScriptBuilder.build(AjaxScriptBuilder.java:117)
[err] 	at org.apache.myfaces.renderkit.html.HtmlAjaxBehaviorRenderer.getScript(HtmlAjaxBehaviorRenderer.java:71)
[err] 	at jakarta.faces.component.behavior.ClientBehaviorBase.getScript(ClientBehaviorBase.java:92)
[err] 	at org.apache.myfaces.renderkit.html.util.ClientBehaviorRendererUtils.appendClientBehaviourScript(ClientBehaviorRendererUtils.java:208)
[err] 	at org.apache.myfaces.renderkit.html.util.ClientBehaviorRendererUtils.getClientBehaviorScript(ClientBehaviorRendererUtils.java:186)
[err] 	at org.apache.myfaces.renderkit.html.util.ClientBehaviorRendererUtils.buildBehaviorChain(ClientBehaviorRendererUtils.java:349)
[err] 	at org.apache.myfaces.renderkit.html.util.ClientBehaviorRendererUtils.buildBehaviorChain(ClientBehaviorRendererUtils.java:315)
[err] 	at org.apache.myfaces.renderkit.html.base.HtmlButtonRendererBase.buildBehaviorizedOnClick(HtmlButtonRendererBase.java:340)
[err] 	at org.apache.myfaces.renderkit.html.base.HtmlButtonRendererBase.encodeBegin(HtmlButtonRendererBase.java:186)
[err] 	at jakarta.faces.component.UIComponentBase.encodeBegin(UIComponentBase.java:561)
[err] 	at jakarta.faces.component.UIComponentBase.encodeAll(UIComponentBase.java:495)
[err] 	at jakarta.faces.component.UIComponentBase.encodeAll(UIComponentBase.java:519)
[err] 	at org.apache.myfaces.renderkit.RendererUtils.renderChildren(RendererUtils.java:536)
[err] 	at org.apache.myfaces.renderkit.html.base.HtmlGroupRendererBase.encodeEnd(HtmlGroupRendererBase.java:154)
[err] 	at jakarta.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:634)
[err] 	at jakarta.faces.component.UIComponentBase.encodeAll(UIComponentBase.java:523)
[err] 	at jakarta.faces.component.UIComponentBase.encodeAll(UIComponentBase.java:519)
[err] 	at jakarta.faces.component.UIComponentBase.encodeAll(UIComponentBase.java:519)
[err] 	at org.apache.myfaces.view.facelets.FaceletViewDeclarationLanguage.renderView(FaceletViewDeclarationLanguage.java:1779)
[err] 	at [internal classes]
[err] 	at jakarta.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:74)
[err] 	at org.apache.myfaces.lifecycle.RenderResponseExecutor.execute(RenderResponseExecutor.java:122)
[err] 	at [internal classes]
[err] 	at jakarta.faces.webapp.FacesServlet.service(FacesServlet.java:225)
[err] 	at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1266)
[err] 	at [internal classes]
[err] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[err] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[err] 	at java.base/java.lang.Thread.run(Thread.java:1583)
[ERROR   ] SRVE0777E: Exception thrown by application class 'io.openliberty.webcontainer61.osgi.webapp.WebAppDispatcherContext61.sendRedirect:81'
java.lang.IllegalStateException: CWWWC0007E: The response sendRedirect is not allowed after the response is committed.
	at io.openliberty.webcontainer61.osgi.webapp.WebAppDispatcherContext61.sendRedirect(WebAppDispatcherContext61.java:81)
	at [internal classes]
	at com.ibm.websphere.svt.gs.gsjsfweb.utils.GSJSFExceptionHandler.handle(GSJSFExceptionHandler.java:75)
	at org.apache.myfaces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:261)
	at [internal classes]

[ERROR   ] SRVE0315E: An exception occurred: java.lang.Throwable: java.lang.IllegalStateException: CWWWC0007E: The response sendRedirect is not allowed after the response is committed.
	at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:5154)
	at [internal classes]
Caused by: java.lang.IllegalStateException: CWWWC0007E: The response sendRedirect is not allowed after the response is committed.
	at io.openliberty.webcontainer61.osgi.webapp.WebAppDispatcherContext61.sendRedirect(WebAppDispatcherContext61.java:81)
	at [internal classes]
	at com.ibm.websphere.svt.gs.gsjsfweb.utils.GSJSFExceptionHandler.handle(GSJSFExceptionHandler.java:75)
	at org.apache.myfaces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:261)
	... 1 more
```

**Comment by volosied** [comment]
This issue (ComponentNotFoundException) is a regression caused by `MYFACES-4624`.

I added a [comment](https://issues.apache.org/jira/browse/MYFACES-4624?focusedCommentId=17889824&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17889824) to the Jira making note of this regression.

The issue is that the ajax render is referencing ids in a composite component that's included from another xhtml file.  See the example in the comment linked above.

I'm assuming the ComponentNotFoundException then causes the` java.lang.IllegalStateException: CWWWC0007E`
