### ISSUE TITLE
Gradle with --parallel enabled fails intermittently in bnd

### ISSUE THREAD

**Issue by fritze2** [OpenLiberty/open-liberty#29757]
Exception with `assemble` for open-liberty when --parallel is enabled:
```
> Task :com.ibm.ws.org.osgi.annotation.versioning:jar FAILED
warning: No translation found for macro: repo;org.osgi:org.osgi.annotation.versioning;1.1.0
warning: Unreferenced class path entries [org.osgi.annotation.versioning-1.1.0]
error  : null, for cmd: repo, arguments; [repo, org.osgi:org.osgi.annotation.versioning, 1.1.0]
error  : Exception: java.util.regex.PatternSyntaxException: Unclosed group near index 9
\$(?:repo
        at java.base/java.util.regex.Pattern.error(Pattern.java:2204)
        at java.base/java.util.regex.Pattern.accept(Pattern.java:2054)
        at java.base/java.util.regex.Pattern.group0(Pattern.java:3232)
        at java.base/java.util.regex.Pattern.sequence(Pattern.java:2300)
        at java.base/java.util.regex.Pattern.expr(Pattern.java:2245)
        at java.base/java.util.regex.Pattern.compile(Pattern.java:1945)
        at java.base/java.util.regex.Pattern.<init>(Pattern.java:1576)
        at java.base/java.util.regex.Pattern.compile(Pattern.java:1134)
        at aQute.libg.glob.Glob.toPattern(Glob.java:162)
        at aQute.libg.glob.Glob.<init>(Glob.java:35)
        at aQute.libg.glob.Glob.<init>(Glob.java:31)
        at aQute.bnd.osgi.Analyzer.jarsFromName(Analyzer.java:1800)
        at aQute.bnd.osgi.Analyzer.getJarsFromName(Analyzer.java:1788)
```

Doing another `assemble` I think has gotten passed this, but I don't see how such an error can be intermittent.

**Comment by Zech-Hein** [comment]
I also hit this same problem on my PB for a different jar
```
error  : com.ibm.ws.org.apache.wss4j.bindings: null, for cmd: repo, arguments; [repo, org.apache.wss4j:wss4j-bindings, 2.4.1]
error  : com.ibm.ws.org.apache.wss4j.bindings: Exception: java.util.regex.PatternSyntaxException: Unclosed group near index 9
\$(?:repo
	at java.base/java.util.regex.Pattern.error(Pattern.java:2028)
```
