### ISSUE TITLE
TCCL is different in CDI extension constructor and Observer methods

### ISSUE THREAD

**Issue by benjamin-confino** [OpenLiberty/open-liberty#29788]
**Describe the bug**  

When an application contains a CDI Extension the TCCL in the constructor is different from the TCCL during the observer methods.

This is because of the architecture of weld. There are two seperate methods on WeldBootsrap that liberty calls at different times. `loadExtensions` is called in WebSphereCDIDeploymentImpl, and it triggers the constructors. This is called once per classloader, and triggers extensions listed as a service in that classloader.

`startInitialization` called in CDIContainerImpl. When invoked this method eventually triggers the observer for every CDI Extension.

Currently the TCCL for constructors is correctly set to whichever ClassLoader contains the extension being constructed. And the TCCL for observer methods is set to an arbitrary CL from the application. 

While it is not possible for an ear file with many applications to have the same TCCL in all cases, it would be possible for them to match in an application with only a single app classloader. The question is wheather we should do so.

[ ] Investigate why we currently wrap the TCCL we get from the app using ClassLoadingService
[ ] Decide if we can and should remove the code that performs that wrap

**Comment by benjamin-confino** [comment]
I spoke with David Zavala from ClassLoading. He agreed we'd be safe to not use this if either of the following is true: 

- No CDI extension calls thread.getContextClassLoader().loadClass()
- No CDI extension calls thread.getContextClassLoader().loadClass() to load a liberty class marked "thread-context" in the bnd.bnd

**Comment by benjamin-confino** [comment]
We have at least one extension that does need the TCCL to access liberty internals:

```	
Caused by: java.util.ServiceConfigurationError: io.opentelemetry.sdk.autoconfigure.spi.ResourceProvider: Provider io.opentelemetry.sdk.autoconfigure.internal.EnvironmentResourceProvider not found
        at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:593)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1219)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1228)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393)
	at io.opentelemetry.sdk.autoconfigure.internal.SpiHelper.load(SpiHelper.java:101)
	at io.opentelemetry.sdk.autoconfigure.internal.SpiHelper.loadOrdered(SpiHelper.java:87)
	at io.opentelemetry.sdk.autoconfigure.ResourceConfiguration.configureResource(ResourceConfiguration.java:94)
	at io.opentelemetry.sdk.autoconfigure.AutoConfiguredOpenTelemetrySdkBuilder.build(AutoConfiguredOpenTelemetrySdkBuilder.java:439)
	at io.openliberty.microprofile.telemetry20.internal.info.OpenTelemetryInfoFactoryImpl.buildOpenTelemetry(OpenTelemetryInfoFactoryImpl.java:59)
	at io.openliberty.microprofile.telemetry.internal.common.info.AbstractOpenTelemetryInfoFactory.lambda$createOpenTelemetryInfo$0(AbstractOpenTelemetryInfoFactory.java:82)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:319)
	at io.openliberty.microprofile.telemetry.internal.common.info.AbstractOpenTelemetryInfoFactory.createOpenTelemetryInfo(AbstractOpenTelemetryInfoFactory.java:79)
	at io.openliberty.microprofile.telemetry.internal.common.info.OpenTelemtryLifecycleManagerImpl.lambda$curryInfoFactory$0(OpenTelemtryLifecycleManagerImpl.java:91)
	at org.apache.commons.lang3.concurrent.AbstractConcurrentInitializer.initialize(AbstractConcurrentInitializer.java:172)
	at org.apache.commons.lang3.concurrent.LazyInitializer.get(LazyInitializer.java:143)
	at io.openliberty.microprofile.telemetry.internal.common.info.OpenTelemtryLifecycleManagerImpl.getOpenTelemetryInfo(OpenTelemtryLifecycleManagerImpl.java:245)
	at io.openliberty.microprofile.telemetry.internal.common.info.OpenTelemtryLifecycleManagerImpl.getOpenTelemetryInfo(OpenTelemtryLifecycleManagerImpl.java:191)
	at io.openliberty.microprofile.telemetry.internal.interfaces.OpenTelemetryAccessor.lambda$getOpenTelemetryInfo$0(OpenTelemetryAccessor.java:47)
	at com.ibm.ws.kernel.service.util.ServiceCaller.lambda$run$3(ServiceCaller.java:457)
	at java.base/java.util.Optional.map(Optional.java:260)
	at com.ibm.ws.kernel.service.util.ServiceCaller.run(ServiceCaller.java:456)
	at io.openliberty.microprofile.telemetry.internal.interfaces.OpenTelemetryAccessor.getOpenTelemetryInfo(OpenTelemetryAccessor.java:46)
	at io.openliberty.microprofile.telemetry20.logging.internal.OpenTelemetryLogHandler.synchronousWrite(OpenTelemetryLogHandler.java:170)
	at com.ibm.ws.collector.manager.buffer.BufferManagerImpl.add(BufferManagerImpl.java:117)
	at com.ibm.ws.logging.source.LogSource.publish(LogSource.java:108)
	at com.ibm.ws.logging.internal.impl.BaseTraceService.publishToLogSource0(BaseTraceService.java:1194)
	at com.ibm.ws.logging.internal.impl.BaseTraceService.publishToLogSource(BaseTraceService.java:1183)
	at com.ibm.ws.logging.internal.impl.BaseTraceService.echo(BaseTraceService.java:982)
	at com.ibm.ws.logging.internal.impl.BaseTraceService$TrOutputStream.flush(BaseTraceService.java:1976)
	at java.base/java.io.PrintStream.implFlush(PrintStream.java:464)
	at java.base/java.io.PrintStream.flush(PrintStream.java:456)
	at com.ibm.ws.logging.internal.impl.BaseTraceService$TeePrintStream.println(BaseTraceService.java:1899)
	at com.ibm.ws.concurrent.internal.ManagedThreadFactoryService.createResource(ManagedThreadFactoryService.java:311)
	at io.openliberty.concurrent.internal.cdi.ManagedThreadFactoryBean.create(ManagedThreadFactoryBean.java:137)
	at io.openliberty.concurrent.internal.cdi.ManagedThreadFactoryBean.create(ManagedThreadFactoryBean.java:47)
	at org.jboss.weld.contexts.AbstractContext.get(AbstractContext.java:96)
	at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get(ContextualInstanceStrategy.java:104)
	at org.jboss.weld.bean.ContextualInstance.get(ContextualInstance.java:50)
	at org.jboss.weld.bean.proxy.ContextBeanInstance.getInstance(ContextBeanInstance.java:101)
	at org.jboss.weld.bean.proxy.ProxyMethodHandler.getInstance(ProxyMethodHandler.java:136)
	at org.jboss.weld.generated.proxies.enterprise.concurrent.ManagedThreadFactory$1772716372$Proxy$_$$_WeldClientProxy.toString(Unknown Source)
	at io.openliberty.concurrent.internal.cdi.ConcurrencyExtension.afterDeploymentValidation(ConcurrencyExtension.java:221)```
	
However resolving this issue in the opposite direction, making the TCCL for CDI extension constructors match the TCCL present for observer methods was successfull.
