### ISSUE TITLE
testBulkheadMethodAsynchronousRetry55Trip

### ISSUE THREAD

**Issue by hutchig** [OpenLiberty/open-liberty#2994]
I was running a regression test when testing 2887 and saw: 

testBulkheadMethodAsynchronousRetry55Trip failing:

```
testBulkheadMethodAsynchronousRetry55Trip	Failure	Asynchronous class Bulkead Retry not throwing Bulkhead exception when retry limit just exceeded expected [true] but found [false]


java.lang.AssertionError: Asynchronous class Bulkead Retry not throwing Bulkhead exception when retry limit just exceeded expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:94)
at org.testng.Assert.failNottEquals(Assert.java:496)
at org.testng.Assert.assertTrue(Assert.java:42)
at org.eclipse.microprofile.fault.tolerance.tck.bulkhead.BulkheadAsynchRetryTest.testBulkheadMethodAsynchronousRetry55Trip(BulkheadAsynchRetryTest.java:149)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internaal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:196)
at org.jboss.arquillian.testng.Arquillian$2.invoke(Arquillian.java:173)
at org.jboss.arquillian.container.test.impl.execution.LocalTestExecuter.execute(LocalTestExecuter.java:60)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(MMethod.java:498)
at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:96)
at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:103)
at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:85)
at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:143)
at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:114)
at org.jboss.arquillian.core.impl.EventImpl.fire((EventImpl.java:67)
at org.jboss.arquillian.container.test.impl.execution.ContainerTestExecuter.execute(ContainerTestExecuter.java:38)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:96)
at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java::103)
at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:85)
at org.jboss.arquillian.test.impl.TestContextHandler.createTestContext(TestContextHandler.java:130)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:96)
at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:92)
at org.jboss.arquillian.test.impl.TestContextHandler.createClassContext(TestContextHandler.java:92)
at sun.reflect.GeneratedMethodAccessor87.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:96)
at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:92)
at org.jboss.arquillian.test.impl.TestContextHandler.createSuiteContext(TestContextHandler.java:73)
at sun.reflect.GeneratedMethodAccessor86.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:96)
at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:92)
at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:143)
at org.jboss.arquillian.test.impl.EventTestRunnerAdaptor.test(EventTestRunnerAdaptor.java:1136)
at org.jboss.arquillian.testng.Arquillian.run(Arquillian.java:164)
at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:208)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:635)
at org.testng.internal.Invoker.invookeTestMethod(Invoker.java:816)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.javva:125)
at org.testng.internal.TestMethodWorker.run(TeestMethodWorker.java:108)
at org.testng.TestRunner.privateRun(TestRunner.java:7774)
at org.testng.TestRunner.run(TestRunner.java:624)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java::354)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:3312)
at org.testng.SuiteRunner.run(SuiteRunner.java:261)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWoorker.run(SuiteRunnerWorker.java:86)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.run(TestNG.java:10048)
att org.jboss.arquillian.testng.container.TestNGTestRunner.execute(TestNGTestRunner.java:53)
at org.jboss.arquillian.protocol.servlet.runner.ServletTestRunner.executeTest(ServletTestRunner.java:170)
at org.jboss.arquillian.protocol.servlet.runner.ServletTestRunner.execute(ServletTestRunner.java:135)
at org.jboss.arquillian.protocol.servlet.runner.ServletTestRunner.doGet(ServletTestRunner.java:98)
at javax.servllet.http.HttpServlet.service(HttpServlet.java:687)
at javax.servlet.http.HttpServlet.seervice(HttpServlet.java:790)
at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1255)
at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:743)
at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:440)
at com.ibm.ws.webcontainer.filter.WebAppFilterManager..invokeFilters(WebAppFilterManager.java:1154)
at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManageer.java:1004)
at com.ibm.ws.webcontainer.servlet.CacheServletWrapper.handleRequest(CacheServletWrapper.java:75)
at com.ibm.ws.webcontainer.WebCoontainer.handleRequest(WebContainer.java:927)
at com.ibm.ws.webcontainer.ossgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:279)
at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1011)
at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLinkk.java:414)
at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:373)
at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:530)
at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:464))
at com.ibm.ws.http.channel.internal.inbound.HttpIInboundLink.processRequest(HttpInboundLink.java:329)
at com.ibm.ws.http.channel.internal.inbound.HttpICLReadCallback.complete(HttpICLReadCallback.java:70)
at com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:5001)
at com.ibm.ws.tcpchannel.internal.WorkQQueueManager.attemptIO(WorkQueueManager.java:571)
at com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:926)
at com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:1015)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
```

**Comment by hutchig** [comment]
Appearing in builds https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.workitem.viewWorkItem&id=253258

**Comment by hutchig** [comment]
The war does not install: 

[WARNING ] CWMFT5019W: The Retry policy jitter delay of 200 Millis for the org.eclipse.microprofile.fault.tolerance.tck.bulkhead.clientserver.BulkheadRapidRetry550MethodSynchBean.test target is not valid because the jitter delay must be less than the delay duration of 1 Micros.
[WARNING ] CWMFT5019W: The Retry policy jitter delay of 200 Millis for the org.eclipse.microprofile.fault.tolerance.tck.bulkhead.clientserver.BulkheadRapidRetry55ClassAsynchBean target is not valid because the jitter delay must be less than the delay duration of 1 Micros.
```
public class BulkheadRapidRetry550MethodSynchBean implements BulkheadTestBackend {

    @Override
    @ApplicationScoped
    @Bulkhead(waitingTaskQueue = 5, value = 5)
    @Asynchronous
    @Retry(retryOn =
     { BulkheadException.class }, delay = 1, delayUnit = ChronoUnit.MICROS,
     maxRetries = 0, maxDuration=999999 )
    public Future test(BackendTestDelegate action) throws InterruptedException {
        Utils.log("in business method of bean " + this.getClass().getName());
        return action.perform();
    }

};
```

**Comment by hutchig** [comment]
OK - so in the above run the app did not start in 30 seconds.
However - if I look at 
https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.workitem.viewWorkItem&id=253258&tab=com.ibm.team.workitem.tab.links
https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_Z075IjkXEeiflZsT47ItAA&tab=com.ibm.team.build.web.ui.internal.editors.result.download.DownloadsProvider
https://libfsfe01.hursley.ibm.com/liberty/dev/Xo/cont/20180405-2229-_Z075IjkXEeiflZsT47ItAA/child-f0-20180406-0147/fatoutput-com.ibm.ws.microprofile.faulttolerance_fat_tck.zip
I see: 
$ grep started trace.log
[4/6/18 3:03:22:300 UTC] 00000124 id=         com.ibm.ws.app.manager.AppMessageHelper                      A CWWKZ0001I: Application ftCircuitBreakerRetry started in 4.028 seconds.
[4/6/18 3:03:30:807 UTC] 00000094 id=         com.ibm.ws.app.manager.AppMessageHelper                      A CWWKZ0001I: Application ftConfig started in 1.210 seconds.
[4/6/18 3:03:38:505 UTC] 00000137 id=         com.ibm.ws.app.manager.AppMessageHelper                      A CWWKZ0001I: Application ftBulkheadSynchTest started in 1.249 seconds.
[4/6/18 3:03:54:943 UTC] 00000115 id=         com.ibm.ws.app.manager.AppMessageHelper                      A CWWKZ0001I: Application ftRetryCondition started in 0.863 seconds.
[4/6/18 3:06:03:308 UTC] 00000058 id=         com.ibm.ws.app.manager.AppMessageHelper                      A CWWKZ0001I: Application ftRetry started in 0.882 seconds.
[4/6/18 3:06:15:025 UTC] 0000011b id=         com.ibm.ws.app.manager.AppMessageHelper                      A CWWKZ0001I: Application ftRetryTimeout started in 0.892 seconds.
[4/6/18 3:08:23:392 UTC] 000001ef id=         com.ibm.ws.app.manager.AppMessageHelper                      A CWWKZ0001I: Application ftBulkheadTest started in 0.851 seconds.
[4/6/18 3:08:27:445 UTC] 00000106 id=         com.ibm.ws.app.manager.AppMessageHelper                      A CWWKZ0001I: Application ftDisableAllButFallback started in 0.796 seconds.
[4/6/18 3:08:34:123 UTC] 0000009d id=         com.ibm.ws.app.manager.AppMessageHelper                      A CWWKZ0001I: Application ftBulkheadAsynchRetryTest started in 0.858 seconds.
[4/6/18 3:09:29:869 UTC] 00000217 id=         com.ibm.ws.app.manager.AppMessageHelper                      A CWWKZ0001I: Application ftCircuitBreaker started in 0.548 seconds.
[4/6/18 3:10:39:928 UTC] 00000239 id=         com.ibm.ws.app.manager.AppMessageHelper                      A CWWKZ0001I: Application ftBulkheadAsynchTest started in 0.757 seconds.
[4/6/18 3:12:20:321 UTC] 00000264 id=         com.ibm.ws.app.manager.AppMessageHelper                      A CWWKZ0001I: Application ftTimeout started in 0.646 seconds.
[4/6/18 3:13:43:034 UTC] 00000237 id=         com.ibm.ws.app.manager.AppMessageHelper                      A CWWKZ0001I: Application ftBulkheadSynchRetryTest started in 0.789 seconds.
[4/6/18 3:16:08:604 UTC] 00000311 id=         com.ibm.ws.app.manager.AppMessageHelper                      A CWWKZ0001I: Application ftFallback started in 0.635 seconds.

and yet the test fails:
file:///Users/hutchig/Downloads/fatoutput-com.ibm.ws.microprofile.faulttolerance_fat_tck(4)/results/junit.html/index.html

BulkheadAsynchRetryTest | testBulkheadMethodAsynchronousRetry55Trip | Failure | Asynchronous  class Bulkead Retry not throwing Bulkhead exception when retry limit  just exceeded expected [true] but found [false]         java.lang.AssertionError: Asynchronous class Bulkead Retry not  throwing Bulkhead exception when retry limit just exceeded expected  [true] but found [false]	at org.testng.Assert.fail(Assert.java:94)	at org.testng.Assert.failNotEquals(Assert.java:496)	at org.testng.Assert.assertTrue(Assert.java:42) 	at  org.eclipse.microprofile.fault.tolerance.tck.bulkhead.BulkheadAsynchRetryTest.testBulkheadMethodAsynchronousRetry55Trip(BulkheadAsynchRetryTest.java:149)

**Comment by hutchig** [comment]
<testsuite hostname="ebc6K3hyO6v" name="org.eclipse.microprofile.fault.tolerance.tck.bulkhead.BulkheadAsynchRetryTest" tests="7" failures="1" timestamp="6 Apr 2018 03:16:11 GMT" time="22.073" errors="0">
  <testcase name="testBulkheadMethodAsynchronousRetry55Trip" time="4.092" classname="org.eclipse.microprofile.fault.tolerance.tck.bulkhead.BulkheadAsynchRetryTest">
    <failure type="java.lang.AssertionError" message="Asynchronous class Bulkead Retry not throwing Bulkhead exception when retry limit just exceeded expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Asynchronous class Bulkead Retry not throwing Bulkhead exception when retry limit just exceeded expected [true] but found [false]

$ grep "Testmethod: Arquillian - class org.eclipse.microprofile.fault.tolerance.tck.bulkhead.BulkheadAsynchRetryTest"  messages.log 
[4/6/18 3:08:34:504 UTC] 000001f3 SystemOut                                                    O 499 03:08:34:50: Testmethod: Arquillian - class org.eclipse.microprofile.fault.tolerance.tck.bulkhead.BulkheadAsynchRetryTest
[4/6/18 3:08:34:961 UTC] 000001ef SystemOut                                                    O 495 03:08:34:96: Testmethod: Arquillian - class org.eclipse.microprofile.fault.tolerance.tck.bulkhead.BulkheadAsynchRetryTest
[4/6/18 3:08:38:030 UTC] 000001f4 SystemOut                                                    O 500 03:08:38:03: Testmethod: Arquillian - class org.eclipse.microprofile.fault.tolerance.tck.bulkhead.BulkheadAsynchRetryTest
[4/6/18 3:08:38:949 UTC] 00000130 SystemOut                                                    O 304 03:08:38:94: Testmethod: Arquillian - class org.eclipse.microprofile.fault.tolerance.tck.bulkhead.BulkheadAsynchRetryTest
[4/6/18 3:08:44:033 UTC] 00000115 SystemOut                                                    O 277 03:08:44:03: Testmethod: Arquillian - class org.eclipse.microprofile.fault.tolerance.tck.bulkhead.BulkheadAsynchRetryTest
[4/6/18 3:08:48:133 UTC] 0000012a SystemOut                                                    O 298 03:08:48:13: Testmethod: Arquillian - class org.eclipse.microprofile.fault.tolerance.tck.bulkhead.BulkheadAsynchRetryTest
[4/6/18 3:08:51:216 UTC] 00000206 SystemOut                                                    O 518 03:08:51:21: Testmethod: Arquillian - class org.eclipse.microprofile.fault.tolerance.tck.bulkhead.BulkheadAsynchRetryTest

**Comment by hutchig** [comment]
[4/6/18 3:08:44:046 UTC] 00000117 id=         SystemOut                                                    O 279 03:08:44:04: in business method of bean org.eclipse.microprofile.fault.tolerance.tck.bulkhead.clientserver.BulkheadRapidRetry55MethodAsynchBean$Proxy$_$$_WeldSubclass
[4/6/18 3:08:44:047 UTC] 00000115 id=         SystemOut                                                    O 277 03:08:44:04: Starting test 3
[4/6/18 3:08:44:047 UTC] 00000115 id=         ibm.ws.microprofile.faulttolerance.impl.ExecutionContextImpl 3 Execution Context[test_b2a39293-b2bb-4a69-9ca1-2d246e23bfdb]: start: 0
[4/6/18 3:08:44:047 UTC] 000001e0 id=         SystemOut                                                    O 480 03:08:44:04: in business method of bean org.eclipse.microprofile.fault.tolerance.tck.bulkhead.clientserver.BulkheadRapidRetry55MethodAsynchBean$Proxy$_$$_WeldSubclass
[4/6/18 3:08:44:049 UTC] 0000009d id=         SystemOut                                                    O 157 03:08:44:04: in business method of bean org.eclipse.microprofile.fault.tolerance.tck.bulkhead.clientserver.BulkheadRapidRetry55MethodAsynchBean$Proxy$_$$_WeldSubclass
[4/6/18 3:08:44:050 UTC] 00000117 id=         SystemOut                                                    O 279 03:08:44:04: Task 1 sleeping for 1000 milliseconds. 1 workers inside Bulkhead from 3 instances *
[4/6/18 3:08:44:051 UTC] 00000115 id=         SystemOut                                                    O 277 03:08:44:05: Starting test 4
[4/6/18 3:08:44:052 UTC] 00000115 id=         ibm.ws.microprofile.faulttolerance.impl.ExecutionContextImpl 3 Execution Context[test_1dc708df-125a-45d9-922d-cab3acac6074]: start: 0
[4/6/18 3:08:44:052 UTC] 000001e0 id=         SystemOut                                                    O 480 03:08:44:05: Task 2 sleeping for 1000 milliseconds. 2 workers inside Bulkhead from 4 instances **
[4/6/18 3:08:44:052 UTC] 000000a4 id=         SystemOut                                                    O 164 03:08:44:05: in business method of bean org.eclipse.microprofile.fault.tolerance.tck.bulkhead.clientserver.BulkheadRapidRetry55MethodAsynchBean$Proxy$_$$_WeldSubclass
[4/6/18 3:08:44:052 UTC] 000000a4 id=         SystemOut                                                    O 164 03:08:44:05: Task 4 sleeping for 1000 milliseconds. 4 workers inside Bulkhead from 5 instances ****
[4/6/18 3:08:44:053 UTC] 00000115 id=         SystemOut                                                    O 277 03:08:44:05: Starting test 5
[4/6/18 3:08:44:054 UTC] 00000115 id=         ibm.ws.microprofile.faulttolerance.impl.ExecutionContextImpl 3 Execution Context[test_1f94528a-df2f-40bd-89f1-e066b61a0f53]: start: 0
[4/6/18 3:08:44:054 UTC] 0000009d id=         SystemOut                                                    O 157 03:08:44:05: Task 3 sleeping for 1000 milliseconds. 3 workers inside Bulkhead from 4 instances ***
[4/6/18 3:08:44:054 UTC] 00000202 id=         SystemOut                                                    O 514 03:08:44:05: in business method of bean org.eclipse.microprofile.fault.tolerance.tck.bulkhead.clientserver.BulkheadRapidRetry55MethodAsynchBean$Proxy$_$$_WeldSubclass
[4/6/18 3:08:44:055 UTC] 00000202 id=         SystemOut                                                    O 514 03:08:44:05: Task 5 sleeping for 1000 milliseconds. 5 workers inside Bulkhead from 6 instances *****
[4/6/18 3:08:44:056 UTC] 00000115 id=         SystemOut                                                    O 277 03:08:44:05: Starting test 6
[4/6/18 3:08:44:056 UTC] 00000115 id=         ibm.ws.microprofile.faulttolerance.impl.ExecutionContextImpl 3 Execution Context[test_a53c7cc1-b5e8-48ae-bc29-e0e358491dbd]: start: 0
[4/6/18 3:08:44:056 UTC] 00000115 id=         SystemOut                                                    O 277 03:08:44:05: Starting test 7
[4/6/18 3:08:44:057 UTC] 00000115 id=         ibm.ws.microprofile.faulttolerance.impl.ExecutionContextImpl 3 Execution Context[test_e9628958-db3a-4b0f-a0e7-81c46d46988f]: start: 0
[4/6/18 3:08:44:057 UTC] 00000115 id=         SystemOut                                                    O 277 03:08:44:05: Starting test 8
[4/6/18 3:08:44:058 UTC] 00000115 id=         ibm.ws.microprofile.faulttolerance.impl.ExecutionContextImpl 3 Execution Context[test_2eb2f6e0-eda9-47b6-9fe7-85764b5760c9]: start: 0
[4/6/18 3:08:44:058 UTC] 00000115 id=         SystemOut                                                    O 277 03:08:44:05: Starting test 9
[4/6/18 3:08:44:059 UTC] 00000115 id=         ibm.ws.microprofile.faulttolerance.impl.ExecutionContextImpl 3 Execution Context[test_1f0491aa-f77e-4a8d-af95-0b85a88c07d3]: start: 0
[4/6/18 3:08:44:059 UTC] 00000115 id=         SystemOut                                                    O 277 03:08:44:05: Starting test 10
[4/6/18 3:08:44:060 UTC] 00000115 id=         ibm.ws.microprofile.faulttolerance.impl.ExecutionContextImpl 3 Execution Context[test_161edf4e-c682-43a8-b3a1-6845fd1af859]: start: 0
[4/6/18 3:08:44:227 UTC] 00000115 id=         ibm.ws.microprofile.faulttolerance.impl.ExecutionContextImpl 3 Execution Context[test_161edf4e-c682-43a8-b3a1-6845fd1af859]: onRetry: 1: 0.168
[4/6/18 3:08:44:425 UTC] 00000115 id=         ibm.ws.microprofile.faulttolerance.impl.ExecutionContextImpl 3 Execution Context[test_161edf4e-c682-43a8-b3a1-6845fd1af859]: onRetry: 2: 0.365
[4/6/18 3:08:44:543 UTC] 00000115 id=         ibm.ws.microprofile.faulttolerance.impl.ExecutionContextImpl 3 Execution Context[test_161edf4e-c682-43a8-b3a1-6845fd1af859]: onRetry: 3: 0.483
[4/6/18 3:08:44:702 UTC] 00000115 id=         ibm.ws.microprofile.faulttolerance.impl.ExecutionContextImpl 3 Execution Context[test_161edf4e-c682-43a8-b3a1-6845fd1af859]: onRetry: 4: 0.643
[4/6/18 3:08:44:813 UTC] 00000115 id=         ibm.ws.microprofile.faulttolerance.impl.ExecutionContextImpl 3 Execution Context[test_161edf4e-c682-43a8-b3a1-6845fd1af859]: onRetry: 5: 0.754
[4/6/18 3:08:44:814 UTC] 00000115 id=         ibm.ws.microprofile.faulttolerance.impl.ExecutionContextImpl 3 Execution Context[test_161edf4e-c682-43a8-b3a1-6845fd1af859]: onRetry: 6: 0.755
[4/6/18 3:08:44:909 UTC] 00000115 id=         ibm.ws.microprofile.faulttolerance.impl.ExecutionContextImpl 3 Execution Context[test_161edf4e-c682-43a8-b3a1-6845fd1af859]: onRetry: 7: 0.849
[4/6/18 3:08:44:920 UTC] 00000115 id=         ibm.ws.microprofile.faulttolerance.impl.ExecutionContextImpl 3 Execution Context[test_161edf4e-c682-43a8-b3a1-6845fd1af859]: onRetry: 8: 0.86
[4/6/18 3:08:44:935 UTC] 00000115 id=         ibm.ws.microprofile.faulttolerance.impl.ExecutionContextImpl 3 Execution Context[test_161edf4e-c682-43a8-b3a1-6845fd1af859]: onRetry: 9: 0.876
[4/6/18 3:08:45:052 UTC] 00000117 id=         SystemOut                                                    O 279 03:08:45:05: Task 1 woke.
[4/6/18 3:08:45:052 UTC] 00000117 id=         ibm.ws.microprofile.faulttolerance.impl.ExecutionContextImpl 3 Execution Context[test_86d7238c-985c-41c5-b5dc-1ffaceda2e3a]: end: 1.008
[4/6/18 3:08:45:052 UTC] 000001e0 id=         SystemOut                                                    O 480 03:08:45:05: Task 2 woke.
[4/6/18 3:08:45:053 UTC] 000001e0 id=         ibm.ws.microprofile.faulttolerance.impl.ExecutionContextImpl 3 Execution Context[test_6d8e3be1-d6c2-40ad-9a89-cd8789e9340d]: end: 1.007
[4/6/18 3:08:45:054 UTC] 00000117 id=         SystemOut                                                    O 279 03:08:45:05: in business method of bean org.eclipse.microprofile.fault.tolerance.tck.bulkhead.clientserver.BulkheadRapidRetry55MethodAsynchBean$Proxy$_$$_WeldSubclass

**Comment by hutchig** [comment]
Tom - observe the early retries (spec'ed at  1 microsecond) taking 170 and 200 ms etc. when nothing else is being traced?

**Comment by hutchig** [comment]
Currently fixing the external testcase to be more robust."in progress"

**Comment by hutchig** [comment]
This has been fixed in the current version of the test source and excluded from the list of
tests run via tck-suite.xml
