### ISSUE TITLE
Test Failure: com.ibm.ws.logging.fat.TimeBasedLogRolloverTest.testTimedRolloverXMLOverrides

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#30053]
RTC 301103

```
testTimedRolloverXMLOverrides:junit.framework.AssertionFailedError: 2024-08-02-04:44:33:238 The rolled messages.log file /Users/jazz_build/Build/workspace/ebcTestRunner/dev/autoFVT/image/output/wlp/usr/servers/com.ibm.ws.logging.timedrolloverbootstrap/logs/messages_24.08.02_04.44.00.0.log doesn't exist.
at com.ibm.ws.logging.fat.TimeBasedLogRolloverTest.checkForRolledLogsAtTime(TimeBasedLogRolloverTest.java:421)
at com.ibm.ws.logging.fat.TimeBasedLogRolloverTest.checkForRolledLogsAtTime(TimeBasedLogRolloverTest.java:403)
at com.ibm.ws.logging.fat.TimeBasedLogRolloverTest.testTimedRolloverXMLOverrides(TimeBasedLogRolloverTest.java:193)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:204)
at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:364)
at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:178)
```

**Comment by fmhwong** [comment]
@ellen-lau Please take a look of this one again as the RTC defect has been marked as high impact.
