### ISSUE TITLE
CWWKD0202E: This DatabaseStore has been deactivated. when application stopped before EMs finish building

### ISSUE THREAD

**Issue by tkburroughs** [OpenLiberty/open-liberty#30155]
When a Jakarta Data application is started, the EMs are built asynchronously, which may result in errors if the application is stopped before the asynchronous threads complete. The errors appear as below.

Note that FFDC is no longer logged, as it is suppressed in FutureEMBuilder in favor of logging CWWKD1080E.

The most common scenario for the error is:
Thread 1 : createEMBuilder creates the DatabaseStore
Thread 2 : application stop - destroys the DatabaseStore   (DataProvider.applicationStopped)
Thread 1 : attempts to go on and use the DatabaseStore it just created, only to find it destroyed.

Some thoughts on resolving:

Application stopping could:
- attempt to cancel all of the async threads; but currently the futures for them are not saved anywhere
- attempt to wait for any futures that could not be cancelled

createEMBuild could
- check periodically to see if the app was uninstalled and stop processing

```
[10/28/24, 21:31:11:268 PDT] 0000009c com.ibm.wsspi.persistence.internal.DatabaseStoreImpl         E CWWKD0202E: This DatabaseStore has been deactivated.
[10/28/24, 21:31:11:284 PDT] 0000009c io.openliberty.data.internal.persistence.cdi.DataExtension   E CWWKD1080E: One or more repository interfaces (ee.jakarta.tck.data.framework.read.only.AsciiCharacters, ee.jakarta.tck.data.framework.read.only.CustomRepository, ee.jakarta.tck.data.framework.read.only.NaturalNumbers, ee.jakarta.tck.data.framework.read.only.PositiveIntegers, ee.jakarta.tck.data.standalone.entity.Boxes) from the null application artifact are not available because of an error. The error might be due to a configuration problem, or the java:comp/DefaultDataSource data store for the repository might not be available. The error is: java.lang.IllegalStateException: CWWKD0202E: This DatabaseStore has been deactivated.
	at com.ibm.wsspi.persistence.internal.DatabaseStoreImpl.createPersistenceServiceUnit(DatabaseStoreImpl.java:304)
	at io.openliberty.data.internal.persistence.service.DBStoreEMBuilder.<init>(DBStoreEMBuilder.java:452)
	at io.openliberty.data.internal.persistence.cdi.FutureEMBuilder.createEMBuilder(FutureEMBuilder.java:367)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:298)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:857)
.```

**Comment by KyleAure** [comment]
For completion and debugging purposes another error that has been observed that is caused by the same root issue (the application is stopped before the asynchronous threads complete) is below: 

```
[2/16/25, 9:55:51:232 PST] 00000077 io.openliberty.data.internal.persistence.cdi.DataExtension   E CWWKD1080E: One or more repository interfaces (ee.jakarta.tck.data.framework.read.only.AsciiCharacters, ee.jakarta.tck.data.framework.read.only.CustomRepository, ee.jakarta.tck.data.framework.read.only.NaturalNumbers, ee.jakarta.tck.data.framework.read.only.PositiveIntegers, ee.jakarta.tck.data.standalone.entity.Boxes) from the 2a845dd2-2a49-4ec4-b97d-d4c93b0f393a#2a845dd2-2a49-4ec4-b97d-d4c93b0f393a.war application artifact are not available because of an error. The error might be due to a configuration problem, or the java:comp/DefaultDataSource data store for the repository might not be available. The error is: jakarta.persistence.PersistenceException: Exception [EclipseLink-28018] (Eclipse Persistence Services - 5.0.0-B06.v202502011023-b917c302c409eeca1a2c4002bd8b725a004ea7f6): org.eclipse.persistence.exceptions.EntityManagerSetupException
Exception Description: Predeployment of PersistenceUnit [persistence_service_pu-1] failed.
Internal Exception: Exception [EclipseLink-7161] (Eclipse Persistence Services - 5.0.0-B06.v202502011023-b917c302c409eeca1a2c4002bd8b725a004ea7f6): org.eclipse.persistence.exceptions.ValidationException
Exception Description: Entity class [class ee.jakarta.tck.data.framework.read.only.NaturalNumber] has no primary key specified. It should define either an [@Id], [@EmbeddedId] or an [@IdClass]. If you have defined PK using any of these annotations then make sure that you do not have mixed access-type (both fields and properties annotated) in your entity class hierarchy.
    at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.createPredeployFailedPersistenceException(EntityManagerSetupImpl.java:2157)
    at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.predeploy(EntityManagerSetupImpl.java:2133)
    at org.eclipse.persistence.jpa.PersistenceProvider.createContainerEntityManagerFactoryImpl(PersistenceProvider.java:424)
    at org.eclipse.persistence.jpa.PersistenceProvider.createContainerEntityManagerFactory(PersistenceProvider.java:388)
    at com.ibm.wsspi.persistence.internal.PersistenceServiceUnitImpl.<init>(PersistenceServiceUnitImpl.java:91)
    at com.ibm.wsspi.persistence.internal.PersistenceServiceImpl.createPersistenceServiceUnit(PersistenceServiceImpl.java:64)
    at com.ibm.wsspi.persistence.internal.DatabaseStoreImpl.createPersistenceServiceUnit(DatabaseStoreImpl.java:351)
    at io.openliberty.data.internal.persistence.service.DBStoreEMBuilder.<init>(DBStoreEMBuilder.java:453)
```

This happened further into the the creation of the `createPersistenceServiceUnit` stack, but is caused by the fact that eclipselink was given a classloader to an entity class that no longer exists (since the application has been removed) and thus cannot process the annotations on the classes fields.

This is able to happen because there are repositories in the `read/only` package which use `NaturalNumber` but are not tested (injected).
