### ISSUE TITLE
Setting the client property com.ibm.ws.jaxrs.client.disableCNCheck to true cannot be set back to false without restarting app

### ISSUE THREAD

**Issue by jim-krueger** [OpenLiberty/open-liberty#30253]
It appears that once the client property `com.ibm.ws.jaxrs.client.disableCNCheck` has been set to "true", it cannot be set back to the default of "false"  without restarting the application.   Closing and restarting the client is not enough.   Is this expected behavior?     

        client = ClientBuilder.newClient();
        client.property("com.ibm.ws.jaxrs.client.ssl.config", "mySSLConfigNoHNV");
        client.property("com.ibm.ws.jaxrs.client.disableCNCheck", "true");

`See #30251`

**Full Stack Trace:**

```
junit.framework.AssertionFailedError: 2026-02-22-18:58:03:211 HostnameVerificationClientTestServlet.testNoHostnameVerificationDisableCNCheckFalse: request should have failed with ProcessingException
	at io.openliberty.jaxrs.client.fat.hostnameverification.servlet.HostnameVerificationClientTestServlet.testNoHostnameVerificationDisableCNCheckFalse(HostnameVerificationClientTestServlet.java:151)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at componenttest.app.FATServlet.doGet(FATServlet.java:80)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
```

**Steps to Reproduce**

1. Set up a test environment on Windows
2. Configure SSL with hostname verification disabled:
   ```xml
   <ssl id="mySSLConfigNoHNV" keyStoreRef="clientKeyStore" trustStoreRef="clientTrustStore" verifyHostname="false"/>
   ```
3. Create a JAX-RS client with the `disableCNCheck` property explicitly set to the String value `"false"`:
   ```java
   ClientBuilder builder = ClientBuilder.newBuilder();
   builder.property("com.ibm.ws.jaxrs.client.disableCNCheck", "false");  // String value, not boolean
   builder.sslContext(sslContext);
   Client client = builder.build();
   ```
4. Make a request to an HTTPS endpoint with a hostname mismatch
5. Observe that the request succeeds when it should fail with a `ProcessingException`

**Expected behavior**

The request should fail with a `ProcessingException` because:
1. The SSL configuration has `verifyHostname="false"` (hostname verification disabled)
2. The JAX-RS client property `disableCNCheck="false"` should **override** the SSL config and **enable** hostname verification
3. With hostname verification enabled and a hostname mismatch, the request should fail

**Diagnostic information:**

- **OpenLiberty Version:** Current development version (issue exists in JAX-RS 2.0 implementation)
- **Affected feature(s):** `jaxrs-2.0`, `transportSecurity-1.0`
- **Java Version:** (Windows platform )
- **Platform:** Windows (issue is Windows-specific; tests pass on other platforms)
- **CXF Version:** 3.1.18 

**server.xml configuration:**
```xml
<server>
    <featureManager>
        <feature>componenttest-1.0</feature>
        <feature>jaxrs-2.0</feature>
        <feature>transportSecurity-1.0</feature>
    </featureManager>

    <!-- Server SSL configuration -->
    <ssl id="defaultSSLConfig" keyStoreRef="clientKeyStore" trustStoreRef="clientTrustStore" verifyHostname="true"/>
    
    <!-- SSL configuration with hostname verification disabled -->
    <ssl id="mySSLConfig" keyStoreRef="clientKeyStore" trustStoreRef="clientTrustStore" verifyHostname="true"/>
    <ssl id="mySSLConfigNoHNV" keyStoreRef="clientKeyStore" trustStoreRef="clientTrustStore" verifyHostname="false"/>

    <keyStore id="clientKeyStore" location="key.p12" type="PKCS12" password="****" />
    <keyStore id="clientTrustStore" location="trust.p12" type="PKCS12" password="****" />

    <quickStartSecurity userName="test" userPassword="****" />
</server>
```

### Root Cause Analysis

The issue appears to be in the property conversion logic in:
**File:** `com.ibm.ws.jaxrs.2.0.client/src/com/ibm/ws/jaxrs20/client/security/LibertyJaxRsClientSSLOutInterceptor.java`

**Lines 88-90:**
```java
Object disableCNCheckObj = message.get("disableCNCheck");
// convert the property to boolean
boolean disableCNCheck = PropertyUtils.isTrue(disableCNCheckObj);
```

The property is passed as a String `"false"` and  converted correctly by `PropertyUtils.isTrue()` on Windows (verifed in the logs) , but somehow JVM (Hotspot) causing the hostname verification to not be enforced.

### Investigation Steps Taken

1. Added trace logging to server.xml for diagnostics:
   ```xml
   <logging traceSpecification="com.ibm.ws.jaxrs*=all:org.apache.cxf.*=all:" />
   ```

2. Identified that JAX-RS 2.0 uses Apache CXF 3.1.18 (not the newer 3.2+ which has different hostname verification logic)

3. Confirmed the issue is Windows-specific (tests pass on other platforms)

### Affected Files

- **Implementation:** `com.ibm.ws.jaxrs.2.0.client/src/com/ibm/ws/jaxrs20/client/security/LibertyJaxRsClientSSLOutInterceptor.java`

**Comment by WhiteCat22** [comment]
By restart the application, do you mean create a new Client? I could see where once it's set on a Client then you'd have to create a new Client to disable it. That seems like a bug, but I'm not 100% sure. Either way, whether a bug or intentional, I think it's very low priority to change.

**Comment by jim-krueger** [comment]
No, the tests that have this problem are all written with a 
`       } finally {
            client.close();
        }`

So somehow the value is being cached or something.
