### ISSUE TITLE
CNTR0020E caused by java.lang.NoClassDefFoundError: com/ibm/ejs/container/util/ExceptionUtil

### ISSUE THREAD

**Issue by tkburroughs** [OpenLiberty/open-liberty#30399]
**Describe the bug**  
For an Enterprise Bean (EJB) configured as a JAX-WS Endpoint, the following error will be reported if an EJB interceptor throws an exception that is not on the throws clause of the EJB method, not a RuntimeException, and not an Error.

```
CNTR0020E: EJB threw an unexpected (non-declared) exception during invocation of method "xxxxxx" on bean "BeanId(appA#moduleB.war#beanC, null)". Exception data: java.lang.NoClassDefFoundError: com/ibm/ejs/container/util/ExceptionUtil
	at xx.yy.WSEJBProxySLbeanC_54321c678.xxxxxx(WSEJBProxySLbeanC_54321c678.java)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:184)
	at com.ibm.ws.jaxws.ejb.EJBMethodInvoker.performInvocation(EJBMethodInvoker.java:107)
Caused by: java.lang.ClassNotFoundException: com.ibm.ejs.container.util.ExceptionUtil
	at com.ibm.ws.classloading.internal.AppClassLoader.findClassCommonLibraryClassLoaders(AppClassLoader.java:751)
	at com.ibm.ws.classloading.internal.AppClassLoader.findClass(AppClassLoader.java:327)
	at com.ibm.ws.classloading.internal.AppClassLoader.findOrDelegateLoadClass(AppClassLoader.java:705)
	at com.ibm.ws.classloading.internal.AppClassLoader.loadClass(AppClassLoader.java:584)
	at com.ibm.ws.classloading.internal.AppClassLoader.loadClass(AppClassLoader.java:553)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
```

**Steps to Reproduce**  
Install a JAX-WS application that uses an EJB as the endpoint, and include an interceptor that will throw an exception that is not on the throws clause of the EJB interface.  Then invoke that JAX-WS endpoint.

**Expected behavior**  
Invoking the JAX-WS Endpoint should result in an EJBException that has the exception thrown by the interceptor as the cause.

**Diagnostic information:**  
 - OpenLiberty Version: all
 - Affected feature(s): jaxws-2.2, xmlWS-3.0, xmlWS-4.0, ejbLite-3.2, enterpriseBeans-4.0
 - Java Version: any

**Additional context**  
None

**Comment by tkburroughs** [comment]
Note: tested by PR #30396
