### ISSUE TITLE
JPQL query for all entities in descending order returns no results on Oracle

### ISSUE THREAD

**Issue by njr-11** [OpenLiberty/open-liberty#30444]
A Jakarta Data test fails with,
```
java.util.NoSuchElementException: No value present at java.base/java.util.Optional.orElseThrow(Optional.java:377) at test.jakarta.data.web.DataTestServlet.testFindAndDeleteReturnsIds(DataTestServlet.java:1822)
```

After persisting a number of entities, Jakarta Data sent the following JPQL:
```
SELECT ID FROM Package ORDER BY WIDTH DESC
```

EclipseLink turned this into a SQL query that didn't produce any results:

```
[12/19/24, 13:27:49:861 CST] 00000039 id=00000000 eclipselink.ps.query                                         3 Execute query ReportQuery(referenceClass=Package sql="SELECT ID FROM Package ORDER BY WIDTH DESC")
[12/19/24, 13:27:49:861 CST] 00000039 id=00000000 eclipselink.ps.transaction                                   3 TX beginTransaction, status=STATUS_ACTIVE
[12/19/24, 13:27:49:861 CST] 00000039 id=00000000 eclipselink.ps.connection                                    3 Connection acquired from connection pool [default].
[12/19/24, 13:27:49:861 CST] 00000039 id=00000000 eclipselink.ps.connection                                    3 reconnecting to external connection pool
[12/19/24, 13:27:49:954 CST] 00000039 id=00000000 eclipselink.ps.sql                                           3 SELECT ID AS a1 FROM Package WHERE (ID) IN (SELECT null FROM (SELECT null, ROWNUM rnum  FROM (SELECT ID AS a1 FROM Package ORDER BY WIDTH DESC) WHERE ROWNUM <= ?) WHERE rnum > ? )  ORDER BY WIDTH DESC FOR UPDATE
	bind => [2 parameters bound]
```

Also, a second Jakarta Data test fails similarly,
```
java.util.NoSuchElementException: No value present
at java.base/java.util.Optional.orElseThrow(Optional.java:377)
at test.jakarta.data.web.DataTestServlet.testFindAndDeleteReturnsIds(DataTestServlet.java:1822) 
```

In this test, Jakarta Data persists entities and then sends the following JPQL:
```
SELECT NEW test.jakarta.data.jpa.web.CityId(o.name, o.stateName) FROM City o WHERE (o.stateName=?1) ORDER BY o.name
```

EclipseLink turns this into a SQL query and finds no results:
```
[12/19/24, 13:18:58:006 CST] 0000003a id=00000000 eclipselink.ps.query                                         3 Execute query ReportQuery(referenceClass=City sql="SELECT NAME, STATENAME FROM City WHERE (STATENAME = ?) ORDER BY NAME")
[12/19/24, 13:18:58:006 CST] 0000003a id=00000000 eclipselink.ps.transaction                                   3 TX beginTransaction, status=STATUS_ACTIVE
[12/19/24, 13:18:58:006 CST] 0000003a id=00000000 eclipselink.ps.connection                                    3 Connection acquired from connection pool [default].
[12/19/24, 13:18:58:006 CST] 0000003a id=00000000 eclipselink.ps.connection                                    3 reconnecting to external connection pool
[12/19/24, 13:18:58:082 CST] 0000003a id=00000000 eclipselink.ps.sql                                           3 SELECT NAME AS a1, STATENAME AS a2 FROM City WHERE (STATENAME = ?) AND (STATENAME,NAME) IN (SELECT null,null FROM (SELECT null,null, ROWNUM rnum  FROM (SELECT NAME AS a1, STATENAME AS a2 FROM City WHERE (STATENAME = ?) ORDER BY NAME) WHERE ROWNUM <= ?) WHERE rnum > ? )  ORDER BY NAME FOR UPDATE
	bind => [4 parameters bound]
```

It should be noted that the City entity has an `@IdClass(CityId.class)` where CityId has String fields: `name`, `stateName` corresponding to fields of the City entity:
```
    @Id
    public String name;

    @Id
    public String stateName;
```

**Comment by anija-anil** [comment]
EclipseLink Issue : [2339](https://github.com/eclipse-ee4j/eclipselink/issues/2339)
