### ISSUE TITLE
CTS: EE8: JAX-RS bucket: SseEventSource xmlTest_from_standalone testcase fails

### ISSUE THREAD

**Issue by jim-krueger** [OpenLiberty/open-liberty#3056]
The following test fails to unmarshal JAXB beans that begin with at least two uppercase letters:
- jaxrs/jaxrs21/ee/sse/sseeventsource/JAXRSClient_xmlTest_from_standalone

jaxrs/jaxrs21/ee/sse/sseeventsource/JAXRSClient_xmlTest_from_standalone trace:
03-21-2018 19:52:45:  TRACE: [JAXRSCommonClient] EXECUTING
03-21-2018 19:52:45:  [Request] Dispatching request: 'POST http://localhost:9081/jaxrs_jaxrs21_ee_sse_sseeventsource_web/media/set' to target server at 'localhost:9081'
03-21-2018 19:52:45:  ###############################
03-21-2018 19:52:46:  [Request] Adding entity: text/xml
03-21-2018 19:52:46:  TRACE: [WIRE] - >> POST http://localhost:9081/jaxrs_jaxrs21_ee_sse_sseeventsource_web/media/set
03-21-2018 19:52:46:  TRACE: [WIRE] - >> Accept:*/*, Content-Type:text/plain
03-21-2018 19:52:46:  TRACE: [WIRE] - >> text/xml
03-21-2018 19:52:52:  TRACE: [WIRE] - << 200 OK
03-21-2018 19:52:52:  TRACE: [WIRE] - << Content-Language: en-US
03-21-2018 19:52:52:  TRACE: [WIRE] - << Content-Length: 8
03-21-2018 19:52:52:  TRACE: [WIRE] - << content-type: application/octet-stream
03-21-2018 19:52:52:  TRACE: [WIRE] - << Date: Wed, 21 Mar 2018 23:52:52 GMT
03-21-2018 19:52:52:  TRACE: [WIRE] - << X-Powered-By: Servlet/4.0
03-21-2018 19:52:52:  TRACE: [WIRE] - << text/xml
03-21-2018 19:52:53:  TRACE: [WebValidatorBase] Expected Status Code '200' found in response line!
03-21-2018 19:52:53:  TRACE: [WebValidatorBase] Scanning response for search string: 'text/xml' starting at index location: 0
03-21-2018 19:52:53:  TRACE: [WebValidatorBase] Found search string: 'text/xml' at index '0' in the server's response
03-21-2018 19:52:53:  TRACE: [JAXRSCommonClient]getContextRoot
HWI type class com.sun.ts.tests.jaxrs.common.impl.JAXBKeyValueBean
Mar 21, 2018 7:52:54 PM org.apache.cxf.staxutils.StaxUtils createXMLInputFactory
WARNING: Could not create a secure Stax XMLInputFactory.  Found class com.ibm.xml.xlxp.api.stax.XMLInputFactoryImpl.  Suggest Woodstox 4.2.0 or newer.
Mar 21, 2018 7:52:54 PM org.apache.cxf.jaxrs.provider.AbstractJAXBProvider handleExceptionStart
WARNING: javax.xml.bind.UnmarshalException
- with linked exception:
[javax.xml.bind.UnmarshalException: unexpected element (uri:"", local:"JAXBKeyValueBean"). Expected elements are <{}jaxbKeyValueBean>]
        at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.handleStreamException(UnmarshallerImpl.java:483)
        at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:417)
        at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:386)
        at org.apache.cxf.jaxrs.provider.JAXBElementProvider.unmarshalFromInputStream(JAXBElementProvider.java:293)
        at org.apache.cxf.jaxrs.provider.JAXBElementProvider.doUnmarshal(JAXBElementProvider.java:245)
        at org.apache.cxf.jaxrs.provider.JAXBElementProvider.readFrom(JAXBElementProvider.java:192)
        at org.apache.cxf.jaxrs.sse.client.InboundSseEventImpl.read(InboundSseEventImpl.java:185)
        at org.apache.cxf.jaxrs.sse.client.InboundSseEventImpl.readData(InboundSseEventImpl.java:160)
        at com.sun.ts.tests.jaxrs.jaxrs21.ee.sse.sseeventsource.JAXRSClient.assertHolder(JAXRSClient.java:604)
        at com.sun.ts.tests.jaxrs.jaxrs21.ee.sse.sseeventsource.JAXRSClient.mediaTest(JAXRSClient.java:576)
        at com.sun.ts.tests.jaxrs.jaxrs21.ee.sse.sseeventsource.JAXRSClient.xmlTest(JAXRSClient.java:414)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
        at java.lang.reflect.Method.invoke(Method.java:508)
        at com.sun.ts.lib.harness.EETest.run(EETest.java:550)
        at com.sun.ts.lib.harness.ServiceEETest.run(ServiceEETest.java:113)
        at com.sun.ts.tests.common.vehicle.EmptyVehicleRunner.run(EmptyVehicleRunner.java:30)
        at com.sun.ts.lib.harness.ServiceEETest.run(ServiceEETest.java:102)
        at com.sun.ts.lib.harness.EETest.getPropsReady(EETest.java:446)
        at com.sun.ts.lib.harness.ServiceEETest.run(ServiceEETest.java:210)
        at com.sun.ts.lib.harness.EETest.run(EETest.java:257)
        at com.sun.ts.tests.common.vehicle.VehicleClient.main(VehicleClient.java:27)
Caused by: javax.xml.bind.UnmarshalException: unexpected element (uri:"", local:"JAXBKeyValueBean"). Expected elements are <{}jaxbKeyValueBean>
        at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallingContext.handleEvent(UnmarshallingContext.java:662)
        at com.sun.xml.bind.v2.runtime.unmarshaller.Loader.reportError(Loader.java:258)
        at com.sun.xml.bind.v2.runtime.unmarshaller.Loader.reportError(Loader.java:253)
        at com.sun.xml.bind.v2.runtime.unmarshaller.Loader.reportUnexpectedChildElement(Loader.java:120)
        at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallingContext$DefaultRootLoader.childElement(UnmarshallingContext.java:1063)
        at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallingContext._startElement(UnmarshallingContext.java:498)
        at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallingContext.startElement(UnmarshallingContext.java:480)
        at com.sun.xml.bind.v2.runtime.unmarshaller.InterningXmlVisitor.startElement(InterningXmlVisitor.java:75)
        at com.sun.xml.bind.v2.runtime.unmarshaller.StAXStreamConnector.handleStartElement(StAXStreamConnector.java:246)
        at com.sun.xml.bind.v2.runtime.unmarshaller.StAXStreamConnector.bridge(StAXStreamConnector.java:180)
        at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:415)
        ... 21 more
Caused by: javax.xml.bind.UnmarshalException: unexpected element (uri:"", local:"JAXBKeyValueBean"). Expected elements are <{}jaxbKeyValueBean>
        ... 32 more

I was unable to pinpoint where the issue was, but I saw that some of the JAXB code uses java.beans.Introspector.decapitalize(clazz.getSimpleName()) when marshalling @XmlRootElement annotated beans without a name specified. According to the JavaDoc for java.beans.Introspector.decapitalize(), it should leave the argument alone if it starts with multiple uppercase characters. I believe there is a mismatch in the names chosen when marshalling/unmarshalling the JAXB beans whose class starts with multiple uppercase characters (e.g. "JAXBKeyValueBean").

I checked for other @XmlRootElement annotated beans, and found two others that have 'normal' class names that begin with just a single capital letter:
api/rs/core/linkjaxbadapter/JaxbLinkEx.java:
@XmlRootElement
public class JaxbLinkEx {
   // ...
}

api/rs/core/linkjaxbadapter/Model.java:
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
public class Model {
    // ...
}

Note that I was able to get the test to pass by manually specifying the name in @XmlRootElement for the problem bean:
@XmlRootElement(name="JAXBKeyValueBean")
@XmlAccessorType(XmlAccessType.FIELD)
public class JAXBKeyValueBean {
    // ...
}

**Comment by jim-krueger** [comment]
This issue no longer fails in the official CTS run for 18.0.0.2

**Comment by jim-krueger** [comment]
Closing the issue
