### ISSUE TITLE
Test Failure (20171204-1131): com.ibm.ws.zos.logging.zfat.ZosLoggingTest.testMsgLog

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#3312]
RTC 249102

junit.framework.AssertionFailedError: 2017-12-04-12:40:40:038 null
at com.ibm.ws.zos.logging.zfat.ZosLoggingTest.testMsgLog(ZosLoggingTest.java:223)
at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:176)
at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:314)
at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:153)

**Comment by fmhwong** [comment]
6. Timothy D Kaczynski Apr 23, 2018 2:37 PM Something has changed in the past week or so, such that when we call RoutedMessage.getMessageLogFormat(), the message we get back has not been "expanded" from the short form that is in the nlsprops file.  For example, here is a portion of the message log that has been routed to the MSGLOG DD on z/OS:

[4/23/18 18:33:14:139 GMT] 00000001 com.ibm.ws.kernel.launch.internal.FrameworkManager   
     I audit.kernelStartTime                                                             
[4/23/18 18:33:14:210 GMT] 00000022 com.ibm.ws.kernel.feature.internal.FeatureManager    
     I STARTING_AUDIT                                                                    
[4/23/18 18:33:14:675 GMT] 00000016 com.ibm.ws.app.manager.internal.monitor.DropinMonitor
     A APPLICATION_MONITOR_STARTED                                                       
[4/23/18 18:33:14:786 GMT] 00000025 com.ibm.ws.tcpchannel.internal.TCPChannel            
     I TCP_CHANNEL_STARTED                                                               
[4/23/18 18:33:14:980 GMT] 00000022 com.ibm.ws.kernel.feature.internal.FeatureManager    
     A FEATURES_ADDED                                                                    
[4/23/18 18:33:14:981 GMT] 00000022 com.ibm.ws.kernel.feature.internal.FeatureManager    
     I COMPLETE_AUDIT                                                                    
[4/23/18 18:33:14:982 GMT] 00000022 com.ibm.ws.kernel.feature.internal.FeatureManager    
     A SERVER_STARTED                                                                    
    
It seems like a call to retrieve the text of the message is missing.  This makes the MSGLOG DD on z/OS un-usable.

I am re-assigning the functional area to "servicability" to get some feedback.

**Comment by Channyboy** [comment]
The issue seems to be the wrong parameter was used for:
**messageLogFormat(LogRecord logRecord, String formattedVerboseMsg)** 

The existing code was:
```String message = formatter.messageLogFormat(logRecord, logRecord.getMessage());```

And is now changed to:
```String message = formatter.messageLogFormat(logRecord, formattedVerboseMsg);```
