### ISSUE TITLE
Issues running unit tests via Eclipse JUnit plugin (loading resource bundles)

### ISSUE THREAD

**Issue by scottkurz** [OpenLiberty/open-liberty#348]
Seems like the UTs which depend on loading messages from resource bundles (I think either directly or indirectly via the runtime classes being tested) work only when run from Gradle, but not from the *Run As -> JUnit Test* run config via Eclipse's JUnit plugin). 

So though Gradle is able to build the correct "classpath" via **bnd.bnd**, there is not the equivalent capability in the JUnit "Run config".

E.g for project **com.ibm.jbatch.container** I can do
> ./gradlew com.ibm.jbatch.container:test

but not run this project's tests via *Run As -> JUnit Test*, which shows issues like:

> java.lang.Exception: Unexpected exception, expected<com.ibm.jbatch.container.exception.PersistenceException> but was<java.lang.ExceptionInInitializerError>
> 	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:31)
> 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
> 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
> 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
> 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
> 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
> 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
> 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
> 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
> 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
> 	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
> 	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
> 	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
> 	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
> 	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
> 	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
> 	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
> Caused by: java.lang.ExceptionInInitializerError
> 	at java.lang.J9VMInternals.ensureError(J9VMInternals.java:141)
> 	at java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:130)
> 	at com.ibm.jbatch.container.validation.IdentifierValidatorTest.testValidatePersistedJobExecutionException(IdentifierValidatorTest.java:95)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
> 	at java.lang.reflect.Method.invoke(Method.java:508)
> 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
> 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
> 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
> 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
> 	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:22)
> 	... 16 more
> Caused by: java.util.MissingResourceException: Can't find com.ibm.jbatch.container.internal.resources.JBatchMessages bundle
> 	at java.util.logging.Logger.setupResourceInfo(Logger.java:1957)
> 	at java.util.logging.Logger.<init>(Logger.java:391)
> 	at java.util.logging.LogManager.demandLogger(LogManager.java:565)
> 	at java.util.logging.Logger.demandLogger(Logger.java:466)
> 	at java.util.logging.Logger.getLogger(Logger.java:564)
> 	at com.ibm.jbatch.container.services.impl.JPAPersistenceManagerImpl.<clinit>(JPAPersistenceManagerImpl.java:115)
> 	... 26 more
> 
>

**Comment by scottkurz** [comment]
I tried adding this to a couple **bnd.bnd** files under the `-testpath` portion without noticing any difference:

> ./resources/;version=file

**Comment by scottkurz** [comment]
From the Eclipse JUnit "Run Configurations" wizard, **Classpath** tab, clicking _Advanced_ , then adding folder `build/classes/java/main`.

![image](https://user-images.githubusercontent.com/4081634/67131082-48011480-f1d1-11e9-9160-f1b6325d516c.png)

Is this a good/valid way to do it though?   You'd think there could only be one compiled copy of the classes I'm testing, but without understanding in more detail, I wonder...
