### ISSUE TITLE
Runnable jars fail to run on more recent IBM Javas

### ISSUE THREAD

**Issue by gcharters** [OpenLiberty/open-liberty#349]
1. Unzip Open Liberty
2. Create server
3. Create jar server package that's 'runnable'
4. Run the server package

Results in...

CWWKE0018E: An exception occurred while launching the runtime environment: java.lang.NullPointerException
java.lang.NullPointerException
        at com.ibm.ws.kernel.boot.BootstrapConfig.findLocations(BootstrapConfig.java:158)
        at com.ibm.ws.kernel.boot.Launcher.findLocations(Launcher.java:336)
        at com.ibm.ws.kernel.boot.Launcher.createPlatform(Launcher.java:85)
        at com.ibm.ws.kernel.boot.cmdline.EnvCheck.main(EnvCheck.java:59)
        at com.ibm.ws.kernel.boot.cmdline.EnvCheck.main(EnvCheck.java:35)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
        at java.lang.reflect.Method.invoke(Method.java:508)
        at wlp.lib.extract.SelfExtractRun.runServerInline(SelfExtractRun.java:325)
        at wlp.lib.extract.SelfExtractRun.main(SelfExtractRun.java:280)

**Comment by aguibert** [comment]
@gcharters fix has been delivered in PR #351.  Once the fix is included in the next build (should be in by Monday), please verify using the latest dev image available on openlibery.io.

**Comment by aguibert** [comment]
closing out this issue since the fix has been delivered for a while and I have verified it fixes the issue locally

**Comment by gcharters** [comment]
Thanks @aguibert  - sorry for not verifying, but I can confirm this is fixed :)
