### ISSUE TITLE
ejbcontainer.tx_fat missing test dependency - servlet-4.0

### ISSUE THREAD

**Issue by tkburroughs** [OpenLiberty/open-liberty#3540]
java.lang.Exception: Installed feature(s) [servlet-4.0] were not defined in the autoFVT/fat-feature-deps.json file! To correct this, add [servlet-4.0] to the 'tested.features' property in the bnd.bnd file for this FAT so that an accurate test depdendency graph can be generated in the future.
    at componenttest.depchain.FeatureDependencyProcessor.validateTestedFeatures(FeatureDependencyProcessor.java:79)
    at componenttest.depchain.FeatureDependencyProcessor.validateTestedFeatures(FeatureDependencyProcessor.java:77)
    at componenttest.topology.impl.LibertyServer.validateServerStarted(LibertyServer.java:1875)
    at componenttest.topology.impl.LibertyServer.startServerWithArgs(LibertyServer.java:1201)
    at componenttest.topology.impl.LibertyServer.startServerAndValidate(LibertyServer.java:842)
    at componenttest.topology.impl.LibertyServer.startServerAndValidate(LibertyServer.java:824)
    at componenttest.topology.impl.LibertyServer.startServerAndValidate(LibertyServer.java:811)
    at componenttest.topology.impl.LibertyServer.startServer(LibertyServer.java:659)
    at com.ibm.ws.ejbcontainer.tx.fat.RunUnderUOWTest.setUp(RunUnderUOWTest.java:57)
    at componenttest.rules.repeater.RepeatTests$CompositeRepeatTestActionStatement.evaluate(RepeatTests.java:110)
    at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:315)
    at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:167)

**Comment by tkburroughs** [comment]
#link 254752
