### ISSUE TITLE
JWT SSO: NPE in CookieHelper.getCookieValues()

### ISSUE THREAD

**Issue by ayoho** [OpenLiberty/open-liberty#3550]
I'm working on adding a test that sets the `cookieName` attribute in the `jwtSso` config to an empty string. When I submit the login form to log into the protected resource, I get a 500 Internal Server Error with an FFDC for an NPE:

```
------Start of DE processing------ = [5/14/18 9:15:38:608 CDT]
Exception = java.lang.NullPointerException
Source = com.ibm.ws.webcontainer.webapp.WebApp.handleRequest
probeid = 985
Stack Dump = java.lang.NullPointerException
    at com.ibm.ws.webcontainer.security.CookieHelper.getCookieValues(CookieHelper.java:71)
    at com.ibm.ws.webcontainer.security.SSOCookieHelperImpl.getCookieValue(SSOCookieHelperImpl.java:530)
    at com.ibm.ws.webcontainer.security.SSOCookieHelperImpl.getJwtSsoTokenFromCookies(SSOCookieHelperImpl.java:518)
    at com.ibm.ws.webcontainer.security.SSOCookieHelperImpl.addJwtSsoCookiesToResponse(SSOCookieHelperImpl.java:116)
    at com.ibm.ws.webcontainer.security.SSOCookieHelperImpl.addSSOCookiesToResponse(SSOCookieHelperImpl.java:78)
    at com.ibm.ws.webcontainer.security.internal.FormLoginExtensionProcessor.postFormLoginProcess(FormLoginExtensionProcessor.java:221)
    at com.ibm.ws.webcontainer.security.internal.FormLoginExtensionProcessor.formLogin(FormLoginExtensionProcessor.java:190)
    at com.ibm.ws.webcontainer.security.internal.FormLoginExtensionProcessor.handleRequest(FormLoginExtensionProcessor.java:113)
    at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:4849)
```

**Comment by ayoho** [comment]
Looks like this has been fixed.
