### ISSUE TITLE
MP Fault Tolerance using EJBs with @Asynchronous throws a NPE

### ISSUE THREAD

**Issue by bpaskin** [OpenLiberty/open-liberty#3573]
When injecting an EJB and having `@Asynchronous` on method a NPE is raised.   Using a proper CDI Bean works correctly, but this should also work with an EJB.

```
@Path("v1")
public class RESTServices {
	
	@Inject private NumberGenerator generator;

	@GET
	@Path("number")
	@Produces(MediaType.APPLICATION_JSON)
	public Integer getNumber() {
		
		try {
			if (null == generator) {
				return 0;
			}
			
			Future<Integer> future = generator.generateNumber();
			return future.get();
			
		} catch (Exception e) {
			e.printStackTrace(System.err);
		}
		return -1;
	}

@Stateless
//@ApplicationScoped
public class NumberGenerator {
	
	private SecureRandom random = new SecureRandom();

	@Asynchronous
	@Timeout(value=100, unit=ChronoUnit.MILLIS)
	public Future<Integer> generateNumber() {
		return CompletableFuture.completedFuture(random.nextInt()); 
	}
}

```
Exception: 
```
Caused by: java.lang.NullPointerException
	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:947)
	at com.ibm.ws.microprofile.faulttolerance.cdi.FaultToleranceInterceptor.getFTPolicies(FaultToleranceInterceptor.java:87)
	at com.ibm.ws.microprofile.faulttolerance.cdi.FaultToleranceInterceptor.executeFT(FaultToleranceInterceptor.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:95)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.jboss.weld.interceptor.reader.SimpleInterceptorInvocation$SimpleMethodInvocation.invoke(SimpleInterceptorInvocation.java:73)

```
@tevans78

**Comment by benjamin-confino** [comment]
I have been informed that the real issue is that the FT interceptor is being called on the new thread when it should not be.

**Comment by benjamin-confino** [comment]
FaultToleranceInterceptor line 223 puts a WeldInvocationContextImpl on the thread. This invocation context holds the FTInterceptor, and WeldInvocationContextImpl. 

WeldInvocationContextImpl.invokeNext() sets position back to 0 in the finally, so this results in the FTinterceptor being called twice.

**Comment by tevans78** [comment]
This is a limitation. To fix it would required very substantial changes and is not currently something we want to do. Closing this for now.
