### ISSUE TITLE
Fix NPE when enablemultireadofpostdata and HTTP/2 are enabled

### ISSUE THREAD

**Issue by pmd1nh** [OpenLiberty/open-liberty#3724]
This also happens with websockets.

**Comment by pmd1nh** [comment]
https://github.com/OpenLiberty/open-liberty/pull/3725

**Comment by pnicolucci** [comment]
When    <webContainer enablemultireadofpostdata="true" /> is enabled in a server.xml and a Http/2 h2c upgrade request or websocket upgrade request occurs the following NPE happens:

java.lang.NullPointerException
    at com.ibm.ws.webcontainer.srt.SRTServletRequest$SRTServletRequestHelper.access$802(SRTServletRequest.java:3342)
    at com.ibm.ws.webcontainer.srt.SRTServletRequest.alertISClose(SRTServletRequest.java:4217)
    at com.ibm.ws.http.channel.internal.inbound.HttpInputStreamImpl.close(HttpInputStreamImpl.java:342)
    at com.ibm.wsspi.http.ee7.HttpInputStreamEE7.close(HttpInputStreamEE7.java:47)
    at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.tryToCloseStream(HttpDispatcherLink.java:1048)
    at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.closeStreams(HttpDispatcherLink.java:958)
    at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.finish(HttpDispatcherLink.java:942)
    at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:293)
    at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1011)
    at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:414)
    at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:373)
    at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:530)
    at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:464)
    at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:329)
    at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.ready(HttpInboundLink.java:300)
    at com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.sendToDiscriminators(NewConnectionInitialReadCallback.java:165)
    at com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.complete(NewConnectionInitialReadCallback.java:74)
    at com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:501)
    at com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueManager.java:571)
    at com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:926)
    at com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:1015)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.lang.Thread.run(Thread.java:811)
