### ISSUE TITLE
Cannot get Subject from PolicyContext

### ISSUE THREAD

**Issue by ggam** [OpenLiberty/open-liberty#3786]
I'm trying to get the Subject on a Servlet from the PolicyContext via `PolicyContext.getContext("javax.security.auth.Subject.container")`. 

From the JACC spec 4.6.1.1 I expect get a null subject when the call is unauthenticated, and a non-null one for authenticated callers. However, I'm always getting an error when calling it from a Servlet:
```
[ERROR   ] SRVE0777E: Excepción lanzada por la clase de aplicación 'javax.security.jacc.PolicyContext.getContext:309'
java.lang.IllegalArgumentException: unknown handler key
	at javax.security.jacc.PolicyContext.getContext(PolicyContext.java:309)
	at eu.ggam.testwebapp.UnprotectedServlet.doGet(UnprotectedServlet.java:26)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1255)
	at [internal classes]
```

Reproducer application: [testwebapp.zip](https://github.com/OpenLiberty/open-liberty/files/2054903/testwebapp.zip)
And my server.xml:
```
<?xml version="1.0" encoding="UTF-8"?>
<server description="new server">

    <!-- Enable features -->
    <featureManager>
        <feature>javaee-7.0</feature>
    </featureManager>

    <!-- To access this server from a remote client add a host attribute to the following element, e.g. host="*" -->
    <httpEndpoint id="defaultHttpEndpoint"
                  httpPort="9080"
                  httpsPort="9443" />

    <ssl id="defaultSSLConfig" keyStoreRef="defaultKeyStore" />
    <keyStore id="defaultKeyStore" password="CHANGEIT" />
    
    <basicRegistry id="basic" realm="customRealm">
        <user name="admin" password="admin" />
        <group name="admin">
            <member name="admin" />
            <member name="admin" />
        </group>
    </basicRegistry>

    <!-- Automatically expand WAR files and EAR files -->
    <applicationManager autoExpand="true"/>
</server>
```

Reproducer steps:
- Deploy the application.
- Go to http://localhost:9080/testwebapp/servlet. You'll get the error
- Go to http://localhost:9080/testwebapp/login and login with admin/admin.
- Go back again to to http://localhost:9080/testwebapp/servlet. The error persists.
- Try with to http://localhost:9080/testwebapp/protectedServlet which is role protected. The same error happens.

I expect the Subject to be available at the `javax.security.auth.Subject.container` key even if I haven't configured a JACC provider.

**Comment by ggam** [comment]
Btw, this is on OpenLiberty 18.0.0.1. I tried to add the "release-bug" label but I couldn't find the way to do it, so I just put it on the issue title

**Comment by ggam** [comment]
Closing since it was my fault. JACC dependency on OSGi manifest should be ` com.ibm.websphere.appserver.jacc-1.5; type="osgi.subsystem.feature"`.
