### ISSUE TITLE
MicroProfile Fault Tolerance/Metrics: @Timeout and @Timed on a class prevents application from starting

### ISSUE THREAD

**Issue by realModusOperandi** [OpenLiberty/open-liberty#380]
**Problem**
Specifying both the `@Timeout` annotation from Fault Tolerance and the `@Timed` annotation from Metrics on a single class results in a RuntimeException when the application tries to start, when specifying only one or the other does not have any problem. I am not sure whether this is a documented incompatibility between the two annotations, but the nature of the error makes it seems like the problem is unexpected. The root "caused by" exception is:

```
Caused by: java.lang.RuntimeException: internal.error.CWMFT4999E
	at com.ibm.ws.microprofile.faulttolerance.cdi.AnnotatedTypeWrapper.<init>(AnnotatedTypeWrapper.java:47)
	at com.ibm.ws.microprofile.faulttolerance.cdi.FaultToleranceCDIExtension.addFaultToleranceAnnotation(FaultToleranceCDIExtension.java:170)
	at com.ibm.ws.microprofile.faulttolerance.cdi.FaultToleranceCDIExtension.processAnnotatedType(FaultToleranceCDIExtension.java:119)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:88)
	at org.jboss.weld.injection.MethodInvocationStrategy$SpecialParamPlusBeanManagerStrategy.invoke(MethodInvocationStrategy.java:144)
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:299)
	at org.jboss.weld.event.ExtensionObserverMethodImpl.sendEvent(ExtensionObserverMethodImpl.java:124)
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:277)
	at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:255)
	at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:269)
	at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:258)
	at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:166)
	at org.jboss.weld.bootstrap.events.ContainerLifecycleEvents.fireProcessAnnotatedType(ContainerLifecycleEvents.java:180)
	... 21 more
```

**Steps to Reproduce**
1. Clone the `microprofile-conference` project from Eclipse:
`$ git clone https://github.com/eclipse/microprofile-conference`

1. Edit the file `microprofile-conference/microservice-vote/src/main/java/io/microprofile/showcase/vote/persistence/couch/CouchAttendeeDAO.java` to add `@Timed` to the class declaration, alongside the existing `@Timeout`

1. Return to the root of the `microprofile-conferece` folder (not just the `microservice-vote` folder) and package the application: 
`$ mvn package`

1. Descend back to `microprofile-conference/microservice-vote/target` and unzip `microservice-vote.jar` to its own folder. This is the OpenLiberty server with the microservice deployed:
`$ unzip microservice-vote.jar -d vote/`

1. Start VoteServer from the `wlp/bin` dir and note in `messages.log` that the application ROOT fails to start. Consult the ffdc folder for a detailed stack trace. I will attach mine here:

[ffdc_17.10.02_12.47.21.1.log](https://github.com/OpenLiberty/open-liberty/files/1352340/ffdc_17.10.02_12.47.21.1.log)

I tried to do a minimal recreation but was not successful, so there must be something else required to trigger this, but I have seen this across two platforms in this application. It prevented me from adding these metrics to the Couch portions of the demo. If this is user error, I think a specific error for the case would be very helpful.

Let me know if I can provide anything else.

**Comment by tevans78** [comment]
fixed #1229
