### ISSUE TITLE
Fix caching servlet prematurely in certain case.

### ISSUE THREAD

**Issue by pmd1nh** [OpenLiberty/open-liberty#3948]
Fixing premature caching servlet during serve servlet by className.

The problem is in the InvokerExtensionProcessor.  During the getServletWrapper(), it prematually add the servlet to cache (addToCache) at the end.  It should not be cached since this getServletWrapper() merely create a wrapper for /servlet/*  (i.e serveServletByClassName)

The addToCache should only be added after the filter.service > servlet.service complete without any exception.  This is happening inside the WebApp.handleRequest after filterManager.invokeFilters()  (˜line 4954 )

Because of this premature addToCache, the mapping is null (mapping -> [null]) inside the CacheServletWrapper40() as seen in the debug added trace

[6/7/18 15:02:42:381 EDT] 0000001a id=00000000 com.ibm.ws.webcontainer40.servlet.CacheServletWrapper40      > CacheServletWrapper40 ENTRY

[6/7/18 15:02:42:382 EDT] 0000001a id=00000000 SystemOut                                                    O PMDINH_246748_DEBUG, com.ibm.ws.webcontainer40.servlet.CacheServletWrapper40 CacheServletWrapper40req.getRequestURL() -> [http://localhost:8010/webcontainer.fvt.asyncservlet/servlet/servlets.javax.servlet.AsyncContext.MultipleAsyncTimersServlet] , queryString -> [beginTimeout=3000&endTimeout=10000]
[6/7/18 15:02:42:384 EDT] 0000001a id=00000000 SystemOut                                                    O PMDINH_246748_DEBUG, com.ibm.ws.webcontainer40.servlet.CacheServletWrapper40CacheServletWrapper40 dispatchContext -> [com.ibm.ws.webcontainer40.osgi.webapp.WebAppDispatcherContext40@6726233b] mapping -> [null]
[6/7/18 15:02:42:384 EDT] 0000001a id=00000000 com.ibm.ws.webcontainer40.servlet.CacheServletWrapper40      < CacheServletWrapper40 RETURN

The com.ibm.ws.webcontainer.servlet.4.0_fat_tolerate_3.0.TestMultipleAsyncTimers sent concurrent requests using the /servlet/*

/webcontainer.fvt.asyncservlet/servlet/servlets.javax.servlet.AsyncContext.MultipleAsyncTimersServlet

The first request created the CacheServletWrapper40() with mapping is null.  (Timing issue here) if the next requests happen to find the cache and use the premature CacheServletWrapper40() to handle their requests, the NPE would happen on line 77 while call mapping.getMappingMatch().  Otherwise, everything is working.  Thus we see this problem intermittently.

public void handleRequest(ServletRequest req, ServletResponse res) throws Exception {
        String methodName = "handleRequest";

        // set the MappingMatch here as when the CacheServletWrapper is being used we will not go
        // through the path of URIMatcher.
        //reqData.setMappingMatch(this.mapping.getMappingMatch());
        WebAppDispatcherContext40 dispatchContext = (WebAppDispatcherContext40) ((SRTServletRequest40) req).getWebAppDispatcherContext();
        System.out.println("PMDINH_246748_DEBUG, " + CLASS_NAME + " " + methodName + ", dispatchContext -> ["
                           + dispatchContext + "] mapping -> [" + mapping + "]");

        dispatchContext.setMappingMatch(mapping.getMappingMatch());    <<<<<<< THIS IS LINE # 77 in the NPE stack

        if (com.ibm.ejs.ras.TraceComponent.isAnyTracingEnabled() && logger.isLoggable(Level.FINE)) {
            logger.logp(Level.FINE, CLASS_NAME, methodName, "MappingMatch: " + mapping.getMappingMatch());
        }

        super.handleRequest(req, res);
    }

NPE stack

Exception = java.lang.NullPointerException
Source = com.ibm.ws.webcontainer.internal.WebContainer
probeid = 162
Stack Dump = java.lang.NullPointerException
    at com.ibm.ws.webcontainer40.servlet.CacheServletWrapper40.handleRequest(CacheServletWrapper40.java:77)
    at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:927)
    at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:279)
    at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1011)
    at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:414)
    at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:373)
    at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:530)
    at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:464)
    at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:329)
    at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.ready(HttpInboundLink.java:300)
    at com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.sendToDiscriminators(NewConnectionInitialReadCallback.java:165)
    at com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.complete(NewConnectionInitialReadCallback.java:74)
    at com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:501)
    at com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueManager.java:571)
    at com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:926)
    at com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:1015)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1153)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.lang.Thread.run(Thread.java:785)

**Comment by pmd1nh** [comment]
https://github.com/OpenLiberty/open-liberty/pull/3950

**Comment by pmd1nh** [comment]
see detail in 246748
