### ISSUE TITLE
Update EclipseLink 2.6_WAS to support Java 11

### ISSUE THREAD

**Issue by dazey3** [OpenLiberty/open-liberty#4023]
EclipseLink 2.6_WAS does not currently support versions of Java >9. This issue is to fix this issue in support of #540

**Comment by aguibert** [comment]
@dazey3 It seems that PR #4024 didn't resolve the issue.  Trying to build OpenLiberty still results in an NPE when the eclipselink compile-time annotation processors run.  

Java version:
```
$ java --version
openjdk 11-ea 2018-09-25
OpenJDK Runtime Environment 18.9 (build 11-ea+19)
OpenJDK 64-Bit Server VM 18.9 (build 11-ea+19, mixed mode)
```

Relevant stack trace:
```
Caused by: java.lang.ExceptionInInitializerError
        at org.eclipse.persistence.internal.helper.ClassConstants.<clinit>(ClassConstants.java:64)
        at org.eclipse.persistence.internal.identitymaps.AbstractIdentityMap.getDefaultIdentityMapClass(AbstractIdentityMap.java:339)
        at org.eclipse.persistence.sessions.Project.<init>(Project.java:111)
        at org.eclipse.persistence.sessions.Project.<init>(Project.java:213)
        at org.eclipse.persistence.internal.jpa.modelgen.CanonicalModelProcessor.process(CanonicalModelProcessor.java:349)
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:972)
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:888)
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.access$2200(JavacProcessingEnvironment.java:110)
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1212)
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1321)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1258)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:936)
        at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:104)
        at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:147)
        ... 24 more
Caused by: java.lang.NullPointerException
        at org.eclipse.persistence.internal.helper.JavaSEPlatform.atLeast(JavaSEPlatform.java:150)
        at org.eclipse.persistence.indirection.IndirectCollectionsFactory.getProvider(IndirectCollectionsFactory.java:190)
        at org.eclipse.persistence.indirection.IndirectCollectionsFactory.<clinit>(IndirectCollectionsFactory.java:43)
        ... 38 more
```
