### ISSUE TITLE
Need to propagate authorization header using MP Rest Client 

### ISSUE THREAD

**Issue by justineechen** [OpenLiberty/open-liberty#4112]
While attempting to update the rest client for open liberty's JWT guide, I ran into an issue propagating the authorization header. I tried using the fix found in this issue:
https://github.com/eclipse/microprofile-rest-client/issues/73

But received the following error:
```
javax.ws.rs.ProcessingException: javax.net.ssl.SSLException: SSLException invoking https://localhost:5050/system/properties: Unrecognized SSL message, plaintext connection?
        at it.io.openliberty.guides.jwt.SystemEndpointTest.testGetPropertiesWithJwt(SystemEndpointTest.java:49)
        at it.io.openliberty.guides.jwt.SystemEndpointTest.testSuite(SystemEndpointTest.java:43)
Caused by: javax.net.ssl.SSLException: SSLException invoking https://localhost:5050/system/properties: Unrecognized SSL message, plaintext connection?
        at it.io.openliberty.guides.jwt.SystemEndpointTest.testGetPropertiesWithJwt(SystemEndpointTest.java:49)
        at it.io.openliberty.guides.jwt.SystemEndpointTest.testSuite(SystemEndpointTest.java:43)
Caused by: javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?
        at it.io.openliberty.guides.jwt.SystemEndpointTest.testGetPropertiesWithJwt(SystemEndpointTest.java:49)
        at it.io.openliberty.guides.jwt.SystemEndpointTest.testSuite(SystemEndpointTest.java:43)

```

Open Liberty 18.0.0.1/wlp-1.0.20.cl180120180309-2209 on IBM J9 VM, version 8.0.5.11

**Comment by evelinec** [comment]
@andymc12 Tagging Andy FYI.

**Comment by andymc12** [comment]
Hi @justineechen - I think the problem listed is that at least one of the requests is sending unencrypted data to a port that expects encrypted data.  Possibly the URL contains "http" instead of "https"?

That said, I think you will still be broken when using SSL until the change for PR #3618 is integrated.  This enabled MP Rest Clients to use custom SSL configurations.  I am also attempting to integrate a test case that shows HTTP header propagation (over HTTP or HTTPS - including the `Authorization` header) in PR #4153.  If you look at that code and test server config, it may help with the issue you are facing.

**Comment by gkwan-ibm** [comment]
1. have to make the keystore files same in both backendServer and UIServer
1. For backendServer,
    - the jvm.options file is available at the src but not at the target server 
    - server.xml should include appSecurity-2.0

**Comment by gkwan-ibm** [comment]
close
- the application of the JWT guide was refactored. It uses the same keystore file for the frontend and system services.
