### ISSUE TITLE
[18.0.0.2] MPJWT 1.0 issue/regression?

### ISSUE THREAD

**Issue by hrstoyanov** [OpenLiberty/open-liberty#4193]
I started having issues with MP JWT 1.0 after the upgrade from 18.0.0.1->18.0.0.2. What happens is that this piece of code:
```
@RequestScoped
public class StafferSvcImpl implements StafferSvc {

    @Context
    private JsonWebToken jwtPrincipal;
     ...
```
which used to work under 18.0.0.1, now injects NULL with 18.0.0.2 (I see this in my debugger) and below is the fall out from this. I verified and the ```Authrorisation``` header is sent appropriately from the browser.

```
Listening for transport dt_socket at address: 7777
Launching defaultServer (Open Liberty 18.0.0.2/wlp-1.0.21.cl180220180619-0403) on Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_172-b11 (en_US)
[AUDIT   ] CWWKE0001I: The server defaultServer has been launched.
[AUDIT   ] CWWKZ0058I: Monitoring dropins for applications.
[AUDIT   ] CWWKT0016I: Web application available (default_host): http://192.168.1.14:9090/jwt/
[WARNING ] Authenticated clients can execute any kind of code into the server by using the following allowed languages: [sql]
[AUDIT   ] J2CA7001I: Resource adapter odbjca installed in 5.707 seconds.
[err] SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
[err] SLF4J: Defaulting to no-operation (NOP) logger implementation
[err] SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[AUDIT   ] CWWKT0016I: Web application available (default_host): http://192.168.1.14:9090/
[AUDIT   ] CWWKZ0001I: Application recres web app started in 7.910 seconds.
[AUDIT   ] CWWKF0012I: The server installed the following features: [jwt-1.0, servlet-4.0, ssl-1.0, jndi-1.0, jca-1.7, cdi-2.0, mpJwt-1.0, jsonp-1.1, distributedMap-1.0, mpConfig-1.2, jaxrsClient-2.1, jaxrs-2.1].
[AUDIT   ] CWWKF0011I: The server defaultServer is ready to run a smarter planet.
[ERROR   ] cdi.resource.injection.error.CWOWB1000E 
                                                                                                               CWNEN0030E: The server was unable to obtain an object instance for the @Context java.lang.reflect.Field.jwtPrincipal reference.  The exception message was: org.eclipse.microprofile.jwt.JsonWebToken cannot be found by com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2_1.0.21.cl180220180619-0403
[ERROR   ] cdi.resource.injection.error.CWOWB1000E 
                                                                                                               CWNEN0030E: The server was unable to obtain an object instance for the @Context java.lang.reflect.Field.jwtPrincipal reference.  The exception message was: org.eclipse.microprofile.jwt.JsonWebToken cannot be found by com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2_1.0.21.cl180220180619-0403
[WARNING ] Application {http://server.web.recres.com/}StafferSvcImpl has thrown exception, unwinding now
org.apache.cxf.interceptor.Fault
[WARNING ] Exception in handleFault on interceptor org.apache.cxf.jaxrs.interceptor.JAXRSDefaultFaultOutInterceptor@7a2564dd
org.apache.cxf.interceptor.Fault
[ERROR   ] An unexpected error occurred during error handling. No further error processing will occur.
org.apache.cxf.interceptor.Fault
[ERROR   ] SRVE0777E: Exception thrown by application class 'com.recres.web.server.StafferSvcImpl.load:44'
java.lang.NullPointerException
        at com.recres.web.server.StafferSvcImpl.load(StafferSvcImpl.java:44)
        at com.recres.web.server.StafferSvcImpl$Proxy$_$$_WeldClientProxy.load(Unknown Source)
        at sun.reflect.GeneratedMethodAccessor707.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.ibm.ws.jaxrs20.server.LibertyJaxRsServerFactoryBean.performInvocation(LibertyJaxRsServerFactoryBean.java:652)
        at [internal classes]
        at com.recres.web.server.BootstrapFilter.doFilter(BootstrapFilter.java:32)
        at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:201)
        at [internal classes]

[ERROR   ] SRVE0315E: An exception occurred: java.lang.Throwable: java.lang.NullPointerException
        at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:4998)
        at [internal classes]
Caused by: java.lang.NullPointerException
        at com.recres.web.server.StafferSvcImpl.load(StafferSvcImpl.java:44)
        at com.recres.web.server.StafferSvcImpl$Proxy$_$$_WeldClientProxy.load(Unknown Source)
        at sun.reflect.GeneratedMethodAccessor707.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.ibm.ws.jaxrs20.server.LibertyJaxRsServerFactoryBean.performInvocation(LibertyJaxRsServerFactoryBean.java:652)
        at [internal classes]
        at com.recres.web.server.BootstrapFilter.doFilter(BootstrapFilter.java:32)
        at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:201)
        ... 1 more
```

**Comment by hrstoyanov** [comment]
I modified my code slightly by replacing @Context with @Inject - I am not sure if I need that, but it gives me different error:

```
@RequestScoped
public class StafferSvcImpl implements StafferSvc {

    @Inject
    private JsonWebToken jwtPrincipal;
     ...
```
and started getting different error:
```
[ERROR   ] CWWKS5604E: A JsonWebToken Principal can't be injected because one is not available. Protect the requesting resource so authentication occurs before the resource is accessed.
[ERROR   ] CWWKS5604E: A JsonWebToken Principal can't be injected because one is not available. Protect the requesting resource so authentication occurs before the resource is accessed.
[WARNING ] Application {http://server.web.recres.com/}StafferSvcImpl has thrown exception, unwinding now
org.apache.cxf.interceptor.Fault
[WARNING ] Exception in handleFault on interceptor org.apache.cxf.jaxrs.interceptor.JAXRSDefaultFaultOutInterceptor@2e852bc8
org.apache.cxf.interceptor.Fault
[ERROR   ] An unexpected error occurred during error handling. No further error processing will occur.
org.apache.cxf.interceptor.Fault
[ERROR   ] SRVE0777E: Exception thrown by application class 'com.ibm.ws.security.mp.jwt.cdi.JsonWebTokenBean.create:83'
javax.enterprise.inject.CreationException
        at com.ibm.ws.security.mp.jwt.cdi.JsonWebTokenBean.create(JsonWebTokenBean.java:83)
        at [internal classes]
        at com.recres.web.server.StafferSvcImpl.load(StafferSvcImpl.java:44)
        at com.recres.web.server.StafferSvcImpl$Proxy$_$$_WeldClientProxy.load(Unknown Source)
        at sun.reflect.GeneratedMethodAccessor733.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.ibm.ws.jaxrs20.server.LibertyJaxRsServerFactoryBean.performInvocation(LibertyJaxRsServerFactoryBean.java:652)
        at [internal classes]
        at com.recres.web.server.BootstrapFilter.doFilter(BootstrapFilter.java:32)
        at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:201)
        at [internal classes]

[ERROR   ] SRVE0315E: An exception occurred: java.lang.Throwable: javax.enterprise.inject.CreationException
        at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:4998)
        at [internal classes]
Caused by: javax.enterprise.inject.CreationException
        at com.ibm.ws.security.mp.jwt.cdi.JsonWebTokenBean.create(JsonWebTokenBean.java:83)
        at [internal classes]
        at com.recres.web.server.StafferSvcImpl.load(StafferSvcImpl.java:44)
        at com.recres.web.server.StafferSvcImpl$Proxy$_$$_WeldClientProxy.load(Unknown Source)
        at sun.reflect.GeneratedMethodAccessor733.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.ibm.ws.jaxrs20.server.LibertyJaxRsServerFactoryBean.performInvocation(LibertyJaxRsServerFactoryBean.java:652)
        at [internal classes]
        at com.recres.web.server.BootstrapFilter.doFilter(BootstrapFilter.java:32)
        at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:201)
        ... 1 more
``` 


Just for reference, here are my request headers as captured in Chrome network tab - __why does OL 18.0.0.2 fail to extract principal ???__ :
```
Accept: application/json
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IlJETTVNall4TkRrMk1VTkNSVFJGUXpsR01FWTNPRGREUWtWQ05FTTNPRVV4UXpWRFJUazJOQSJ9.eyJpc3MiOiJodHRwczovL3Job3duLWRldi5hdXRoMC5jb20vIiwic3ViIjoiYXV0aDB8NWIzY2ZlZGVhMTc3YWMxOTY1ZmFiMTg1IiwiYXVkIjpbImh0dHBzOi8vd2ViYXBwIiwiaHR0cHM6Ly9yaG93bi1kZXYuYXV0aDAuY29tL3VzZXJpbmZvIl0sImlhdCI6MTUzMDcyNjU5MiwiZXhwIjoxNTMwNzMzNzkyLCJhenAiOiJpWWdWSEg3VTUzTjdPRnZzM1cxbnZ2UU5za3YzckRrUSIsInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwifQ.rQm-9tFzBZC74OquQ5j9oxzNP3hdfN0gmrMMKS0vJN45HD6DkFL5rAh8OdiuCKP_3oXDrRZZz6OJ5gpf-EebtXTG132n2sQcOKDhMSXkfKyb1eCTxWWdBnpLkjuXEauwafZ6EGKyAAzgl6LoUH46NH1ZkIdR8YzWY7pFSJLhjqH_598GROvpuzzOTFhtK0C6Fc-VJeRluclFNDbt7lVZmP2QYE4N4tMZyhgZq2V_y4LkrEjXaQNvq7YJfeX-sV9P2OQnv0M6ScLiZf74Q7gA8XcA4RvNWs2AGBK32pWN2HYONTTVbYZIVSKwbscUpC3eOAyfTlowbSiMnUrIIukM8w
Connection: keep-alive
Host: 127.0.0.1:9090
Referer: http://127.0.0.1:9090/
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
```

**Comment by hrstoyanov** [comment]
And just to confirm, rolling back to 18.0.0.1 resolves the issue.

**Comment by Emily-Jiang** [comment]
Can you post your server.xml?

**Comment by hrstoyanov** [comment]
```xml
<?xml version="1.0" encoding="UTF-8"?>

<server description="Sample Liberty server">
    <!--Trimmed-down feature set-->
    <featureManager>
        <feature>jca-${featureJcaVersion}</feature>
        <feature>jaxrs-${featureJaxrsVersion}</feature>
        <feature>mpConfig-${featureMPConfigVersion}</feature>
        <feature>mpJwt-${featureMPJwtVersion}</feature>
    </featureManager>

    <!-- This is the keystore that will be used by SSL and by JWT. -->
    <keyStore id="defaultKeyStore" location="${serverKeystoreLocation}" type="PKCS12" password="${serverKeystorePassword}" />

    <!-- The MP JWT configuration that injects the caller's JWT into a ResourceScoped bean for inspection. -->
    <mpJwt id="jwtUserConsumer" userNameAttribute="sub" keyName="${auth0Tenant}-webapp" audiences="${auth0Audience}, ${auth0Domain}/userinfo" issuer="https://${auth0Domain}/"/>

    <library id="erraiLib">
        <fileset dir="${server.config.dir}/errai" includes="*.jar" scanInterval="5s"/>
    </library>

    <library id="odbLib">
        <fileset dir="${server.config.dir}/odb" includes="*.jar" scanInterval="5s"/>
    </library>

    <library id="auth0Lib">
        <fileset dir="${server.config.dir}/auth0" includes="*.jar" scanInterval="5s"/>
    </library>

    <library id="awsLib">
        <fileset dir="${server.config.dir}/aws" includes="*.jar" scanInterval="5s"/>
    </library>

    <library id="stripeLib">
        <fileset dir="${server.config.dir}/stripe" includes="*.jar" scanInterval="5s"/>
    </library>

    <resourceAdapter id="odbjca" location="${server.config.dir}jca/odbjca/odbjca-rar-${odbjcaVersion}.rar">
        <properties.odbjca embeddedServerConfiguration="odb-server.xml" orientdbHome="../../../../../../db"/>
        <classloader commonLibraryRef="odbLib"/>
    </resourceAdapter>

    <connectionFactory jndiName="eis/odbFactory">
        <properties.odbjca url="remote:127.0.0.1:3424/rehabowner.db"
                           username="admin"
                           password="admin"/>
    </connectionFactory>

    <httpEndpoint id="defaultHttpEndpoint"
                  host="*"
                  httpPort="9090"
                  httpsPort="9493"/>

    <application context-root="/"
                 type="war"
                 id="recres_webapp"
                 location="recres-webapp.war"
                 name="recres web app">
        <classloader commonLibraryRef="erraiLib, odbLib, auth0Lib, awsLib, stripeLib" classProviderRef="odbjca"/>
    </application>

</server>
```

**Comment by hrstoyanov** [comment]
@Emily-Jiang  You can see the exact features from the log dumps I provided earlier. There are some shared libs and a JCA adapter that you can ignore (i don't think they matter)

**Comment by Emily-Jiang** [comment]
Thanks @hrstoyanov ! Sorry for the late response! It looks like previously you used JAX-RS 2.0 but now you are using JAX-RS 2.1 There might be an integration issue you discovered between MP JWT 1.0 and JAX-RS 2.1. We are debugging the issue and will provide an update in due course.

**Comment by chunlongliang-ibm** [comment]
This problem is due to the behavior change between Liberty feature jaxrs-2.0 and jax-rs-2.1. Specifically, jaxrs-2.0 automatically install Liberty  appSecurity-2.0  feature, but jaxrs-2.1 requires  appSecurity-2.0  explicitly installed if application security is required. This change impacts all jax-rs applications that uses application security. We need discuss if this behavior change is correct or not, but the solution for now is to add  appSecurity-2.0  feature. See https://www.ibm.com/support/knowledgecenter/en/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/cwlp_jaxrs21_behavior.html

**Comment by hrstoyanov** [comment]
I am stuck with 18.0.0.1 for now (not a show-stopepr issue for me). Will wait until OL implements MP 2.x,  will try to upgrade then.

**Comment by tevans78** [comment]
@hrstoyanov MP 2.0 was released as part of Open Liberty 18.0.0.3 which is available now
https://openliberty.io/blog/2018/09/19/get-more-metrics-microprofile20.html

Please let me know if you have any further problems.
