### ISSUE TITLE
In 18.0.0.2 an IllegalArgumentException can occur when "maxParamPerRequest="-1"

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#4203]
When the following is set in a server.xml:

<webContainer  maxParamPerRequest="-1"/> 

Basically allowing an unlimited number of parameters: http://www-01.ibm.com/support/docview.wss?uid=swg21962614

The following IllegalArgumentException will occur when calling getParameterNames:

Caused by: java.lang.IllegalArgumentException
at com.ibm.wsspi.webcontainer.util.RequestUtils.parseQueryString(RequestUtils.java:233)
at com.ibm.wsspi.webcontainer.util.RequestUtils.parseQueryString(RequestUtils.java:93)
at com.ibm.ws.webcontainer.servlet.RequestUtils.parsePostData(RequestUtils.java:358)
at com.ibm.ws.webcontainer.srt.SRTServletRequest.parsePostData(SRTServletRequest.java:2486)
at com.ibm.ws.webcontainer.srt.SRTServletRequest.parseParameters(SRTServletRequest.java:2335)
at com.ibm.ws.webcontainer.srt.SRTServletRequest.getParameterNames(SRTServletRequest.java:190

**Comment by pnicolucci** [comment]
Merged to master, closing.
