### ISSUE TITLE
OpenLiberty does not start on z/OS

### ISSUE THREAD

**Issue by aguibert** [OpenLiberty/open-liberty#425]
Although there are no z/OS specific features or support in OpenLiberty, a server should still start with the basic set of distributed OS features.

Currently, starting a server on z/OS gives the following error:
```
com.ibm.ws.kernel.boot.LaunchException: Kernel definition could not be found: /www/wlp/lib/platform/zosExtensions-1.0.mf
        at com.ibm.ws.kernel.boot.internal.KernelResolver.<init>(KernelResolver.java:176)
        at com.ibm.ws.kernel.boot.internal.KernelBootstrap.go(KernelBootstrap.java:142)
        at com.ibm.ws.kernel.boot.Launcher.handleActions(Launcher.java:244)
        at com.ibm.ws.kernel.boot.Launcher.createPlatform(Launcher.java:119)
        at com.ibm.ws.kernel.boot.cmdline.EnvCheck.main(EnvCheck.java:59)
        at com.ibm.ws.kernel.boot.cmdline.EnvCheck.main(EnvCheck.java:35)
CWWKE0005E: The runtime environment could not be launched.
CWWKE0023E: The specified kernel definition (zosExtensions-1.0) does not exist.
```

This appears to be because in `wlp/lib/platform/defaults` we try to apply a non-existent z/OS extensions feature via: `WebSphere-DefaultExtension-zos: zosExtensions-1.0`

Instead, OpenLiberty should not attempt to apply any extensions features for zOS and run as if it were any other OS.

**Comment by yeekangc** [comment]
#1004 has been merged.  Looks like this issue is resolved now, @kaczyns?

**Comment by kaczyns** [comment]
Yes, I must have missed this last year when I merged the PR.  Thanks!
