### ISSUE TITLE
Test Failure (20180613-0138): com.ibm.ws.logging.json.fat.ServerConfigUpdateTest.enableAndDisableMessagesLog

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#4291]
RTC 255964

```
junit.framework.AssertionFailedError: 2018-06-13-06:49:54:953 CWWKF0011I is not found
at com.ibm.ws.logging.json.fat.ServerConfigUpdateTest.enableAndDisableMessagesLog(ServerConfigUpdateTest.java:53)
at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:193)
at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:315)
at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:167)
```
Seen in build:
Liberty - Sun EBC 20180613-0138

**Comment by fmhwong** [comment]
This ServerConfigUpdateTest works only when running in sequential order on IBM JDKs.  When running on Sun JDKs, the sequence is not guaranteed, so please fix the tests so that it can be run in any order.

**Comment by fmhwong** [comment]
@Yushan-Lin I'll assign this to Sarah.  Please help her on this one.
