### ISSUE TITLE
ConcurrentModificationException when a JAXRS API has multiple consume and/or produce MediaTypes

### ISSUE THREAD

**Issue by jhanders34** [OpenLiberty/open-liberty#4368]
When a JAXRS API has multiple consume or produce MediaTypes, the list of MediaTypes is sorted for comparison purposes.  The same collection of MediaTypes is being sorted by multiple threads instead of just once.

Below is a stack trace for the reported issue.

java.util.ConcurrentModificationException
       at java.util.ArrayList.sort(ArrayList.java:1475)
       at java.util.Collections.sort(Collections.java:186)
       at org.apache.cxf.jaxrs.utils.JAXRSUtils.sortMediaTypes(JAXRSUtils.java:1744)
       at org.apache.cxf.jaxrs.provider.ProviderFactory$MessageBodyReaderComparator.compare(ProviderFactory.java:1181)
       at org.apache.cxf.jaxrs.provider.ProviderFactory$MessageBodyReaderComparator.compare(ProviderFactory.java:1166)
       at java.util.TimSort.countRunAndMakeAscending(TimSort.java:366)
       at java.util.TimSort.sort(TimSort.java:231)
       at java.util.Arrays.sort(Arrays.java:1856)
       at java.util.ArrayList.sort(ArrayList.java:1473)
       at java.util.Collections.sort(Collections.java:186)
       at org.apache.cxf.jaxrs.provider.ProviderFactory$AtomicReferenceProviderList.addAndSortProviders(ProviderFactory.java:965)
       at org.apache.cxf.jaxrs.provider.ProviderFactory.addAndSortReaders(ProviderFactory.java:907)
       at org.apache.cxf.jaxrs.provider.ProviderFactory.setCommonProviders(ProviderFactory.java:828)
       at org.apache.cxf.jaxrs.client.ClientProviderFactory.setProviders(ClientProviderFactory.java:77)
       at org.apache.cxf.jaxrs.provider.ProviderFactory.setUserProviders(ProviderFactory.java:1162)
       at org.apache.cxf.jaxrs.client.spec.ClientImpl$WebTargetImpl.request(ClientImpl.java:336)
       at org.apache.cxf.jaxrs.client.spec.ClientImpl$WebTargetImpl.request(ClientImpl.java:421)

**Comment by annaguri** [comment]
@jhanders34  can we have an iFix for 18.0.0.2?
