### ISSUE TITLE
JAXB classloading issue after upgrading to 18.0.0.2

### ISSUE THREAD

**Issue by lmsurpre** [OpenLiberty/open-liberty#4404]
After upgrading from 18.0.0.1 to 18.0.0.2, we started hitting a strange JAXB error when we try to explicitly load the JAXBContext for our model classes: 
```
[7/28/18 6:11:07:486 UTC] 0000002a id=         watsonhealth.fhir.server.listener.FHIRServletContextListenerEEncountered an exception while initializing the servlet context.
java.lang.Error: javax.xml.bind.JAXBException: Unable to create context
 - with linked exception:
[java.lang.reflect.InvocationTargetException]
	at com.ibm.watsonhealth.fhir.model.util.FHIRUtil.createContext(FHIRUtil.java:225)
	at com.ibm.watsonhealth.fhir.model.util.FHIRUtil.<clinit>(FHIRUtil.java:147)
	at com.ibm.watsonhealth.fhir.server.listener.FHIRServletContextListener.contextInitialized(FHIRServletContextListener.java:74)
	at com.ibm.ws.webcontainer.webapp.WebApp.notifyServletContextCreated(WebApp.java:2376)
	at com.ibm.ws.webcontainer31.osgi.webapp.WebApp31.notifyServletContextCreated(WebApp31.java:514)
	at com.ibm.ws.webcontainer.webapp.WebApp.initialize(WebApp.java:1004)
	at com.ibm.ws.webcontainer.webapp.WebApp.initialize(WebApp.java:6566)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost.startWebApp(DynamicVirtualHost.java:467)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost.startWebApplication(DynamicVirtualHost.java:462)
	at com.ibm.ws.webcontainer.osgi.WebContainer.startWebApplication(WebContainer.java:1132)
	at com.ibm.ws.webcontainer.osgi.WebContainer.startModule(WebContainer.java:937)
	at com.ibm.ws.app.manager.module.internal.ModuleHandlerBase.deployModule(ModuleHandlerBase.java:99)
	at com.ibm.ws.app.manager.module.internal.DeployedModuleInfoImpl.installModule(DeployedModuleInfoImpl.java:49)
	at com.ibm.ws.app.manager.module.internal.DeployedAppInfoBase.deployModules(DeployedAppInfoBase.java:429)
	at com.ibm.ws.app.manager.module.internal.DeployedAppInfoBase.deployApp(DeployedAppInfoBase.java:415)
	at com.ibm.ws.app.manager.war.internal.WARApplicationHandlerImpl.install(WARApplicationHandlerImpl.java:65)
	at com.ibm.ws.app.manager.internal.statemachine.StartAction.execute(StartAction.java:140)
	at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.enterState(ApplicationStateMachineImpl.java:1258)
	at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.run(ApplicationStateMachineImpl.java:873)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:811)
Caused by: javax.xml.bind.JAXBException: Unable to create context
 - with linked exception:
[java.lang.reflect.InvocationTargetException]
	at javax.xml.bind.ContextFinder.find(ContextFinder.java:70)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:77)
	at com.ibm.watsonhealth.fhir.model.util.FHIRUtil.createContext(FHIRUtil.java:223)
	... 21 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at javax.xml.bind.ContextFinder.find(ContextFinder.java:66)
	... 23 more
Caused by: javax.xml.bind.JAXBException: 
Descriptor Exceptions: 
---------------------------------------------------------

Runtime Exceptions: 
---------------------------------------------------------

Exception [EclipseLink-50033] (Eclipse Persistence Services - 2.6.4.v20160829-44060b6): org.eclipse.persistence.exceptions.JAXBException
Exception Description: The DomHandlerConverter for DomHandler [javax.xml.bind.annotation.W3CDomHandler] set on property [div] could not be initialized.
Internal Exception: java.lang.NoSuchMethodException: javax.xml.bind.annotation.W3CDomHandler.createUnmarshaller(javax.xml.bind.ValidationEventHandler)

 - with linked exception:
[Exception [EclipseLink-0] (Eclipse Persistence Services - 2.6.4.v20160829-44060b6): org.eclipse.persistence.exceptions.IntegrityException
Descriptor Exceptions: 
---------------------------------------------------------

Runtime Exceptions: 
---------------------------------------------------------

Exception [EclipseLink-50033] (Eclipse Persistence Services - 2.6.4.v20160829-44060b6): org.eclipse.persistence.exceptions.JAXBException
Exception Description: The DomHandlerConverter for DomHandler [javax.xml.bind.annotation.W3CDomHandler] set on property [div] could not be initialized.
Internal Exception: java.lang.NoSuchMethodException: javax.xml.bind.annotation.W3CDomHandler.createUnmarshaller(javax.xml.bind.ValidationEventHandler)
]
	at org.eclipse.persistence.jaxb.JAXBContext$ContextPathInput.createContextState(JAXBContext.java:961)
	at org.eclipse.persistence.jaxb.JAXBContext$ContextPathInput.createContextState(JAXBContext.java:893)
	at org.eclipse.persistence.jaxb.JAXBContext.<init>(JAXBContext.java:193)
	at org.eclipse.persistence.jaxb.JAXBContextFactory.createContext(JAXBContextFactory.java:129)
	... 28 more
Caused by: Exception [EclipseLink-0] (Eclipse Persistence Services - 2.6.4.v20160829-44060b6): org.eclipse.persistence.exceptions.IntegrityException
Descriptor Exceptions: 
---------------------------------------------------------

Runtime Exceptions: 
---------------------------------------------------------

Exception [EclipseLink-50033] (Eclipse Persistence Services - 2.6.4.v20160829-44060b6): org.eclipse.persistence.exceptions.JAXBException
Exception Description: The DomHandlerConverter for DomHandler [javax.xml.bind.annotation.W3CDomHandler] set on property [div] could not be initialized.
Internal Exception: java.lang.NoSuchMethodException: javax.xml.bind.annotation.W3CDomHandler.createUnmarshaller(javax.xml.bind.ValidationEventHandler)

	at org.eclipse.persistence.internal.sessions.DatabaseSessionImpl.initializeDescriptors(DatabaseSessionImpl.java:715)
	at org.eclipse.persistence.internal.sessions.DatabaseSessionImpl.initializeDescriptors(DatabaseSessionImpl.java:651)
	at org.eclipse.persistence.internal.sessions.DatabaseSessionImpl.initializeDescriptors(DatabaseSessionImpl.java:582)
	at org.eclipse.persistence.internal.sessions.DatabaseSessionImpl.postConnectDatasource(DatabaseSessionImpl.java:818)
	at org.eclipse.persistence.internal.sessions.DatabaseSessionImpl.login(DatabaseSessionImpl.java:775)
	at org.eclipse.persistence.oxm.XMLContext$XMLContextState.setupSession(XMLContext.java:749)
	at org.eclipse.persistence.oxm.XMLContext$XMLContextState.setupSession(XMLContext.java:1)
	at org.eclipse.persistence.internal.oxm.Context$ContextState.<init>(Context.java:80)
	at org.eclipse.persistence.oxm.XMLContext$XMLContextState.<init>(XMLContext.java:712)
	at org.eclipse.persistence.oxm.XMLContext.<init>(XMLContext.java:194)
	at org.eclipse.persistence.jaxb.JAXBContext$ContextPathInput.createContextState(JAXBContext.java:986)
	at org.eclipse.persistence.jaxb.JAXBContext$ContextPathInput.createContextState(JAXBContext.java:959)
	... 31 more
```

We are doing something a bit unusual in that we are packaging our own JPA and JAXB implementations with our application in order to use some specific features of the Moxy implementation that are not exposed from the Liberty jpa or jaxb features.

I turned on verbose ClassLoading trace and found that in 18.0.0.1 some javax.xml.bind classes were coming from the JRE. For example:
[Loaded javax.xml.bind.ValidationEventHandler from /Users/lmsurpre/IBM/macosxx6480sr2fp10hybrid-20160121_01-sdk/jre/lib/rt.jar]

But in 18.0.0.2 these classes are now being loaded from the Liberty dev folder and it seems like that is causing the error:
[Loaded javax.xml.bind.ValidationEventHandler from file:/Users/lmsurpre/liberty-runtime/wlp/lib/../dev/api/spec/com.ibm.websphere.javaee.jaxb.2.2_1.0.21.jar]

Is it right for Liberty to be finding these classes in wlp/dev/api/spec at runtime even without the jaxb feature enabled?
And any idea why it might claim that the jaxb spec jar is missing this method from javax.xml.bind.annotation.W3CDomHandler when it seems it should be there?

**Comment by aguibert** [comment]
hi @lmsurpre, thanks for opening this issue.  Could you please attach your server.xml (feature list at minimum) and also the classloading trace you collected?

**Comment by lmsurpre** [comment]
here is the feature list:
```
<featureManager>
        <feature>localConnector-1.0</feature>
        <feature>jaxrs-2.0</feature>
        <feature>openidConnectServer-1.0</feature>
        <feature>appSecurity-2.0</feature>
        <feature>ssl-1.0</feature>
        <feature>cdi-1.2</feature>
        <feature>jsonp-1.0</feature>
        <feature>jsf-2.2</feature>
        <feature>servlet-3.1</feature>
        <feature>websocket-1.1</feature>
    	<feature>jdbc-4.1</feature>
</featureManager>
```

I'll need to check to make sure we can share the classloading trace in the open.

**Comment by aguibert** [comment]
I believe the regression is caused by this PR I made: 
https://github.com/OpenLiberty/open-liberty/pull/3667

Undoing the content of that PR seems to resolve the issue.

**Comment by vtkac** [comment]
Hi, we're also facing similar issue, here: https://stackoverflow.com/questions/51617603/liberty-18-0-0-2-jaxrs-2-0-is-not-working-with-ldapregistry-3-0

@aguibert thx for your reply. Just posting this ^ here to have cross reference :) 
Hopefully you don't mind

Thank you

**Comment by aguibert** [comment]
This seems to be caused by a subtle split package classloading conflict. I was able to reproduce this issue with Liberty 18.0.0.2 and the underlying exception looks something like this:

In this case it seems that javax.xml.bind.annotation.W3CDomHandler was loaded from classloader A, and javax.xml.bind.ValidationEventHandler was loaded twice -- once from classloader A and once from classloader B. The error we get here is caused by the JVM looking for javax.xml.bind.annotation.W3CDomHandler.createUnmarshaller(javax.xml.bind.ValidationEventHandler) where both classes are from classloader A, but instead it looks for a createUnmarshaller(ValidationEventHandler) method where ValidationEventHandler comes from classloader B.
