### ISSUE TITLE
WABInstaller throws IllegalStateException when swtiching features

### ISSUE THREAD

**Issue by navidsh** [OpenLiberty/open-liberty#4447]
The problem happens if one feature is replaced with another feature AND both features include a bundle that includes a dynamic `Web-ContextPath` e.g. `Web-ContextPath: @contextRoot`. In this case the following exception will be thrown:
```
[02/08/18 16:33:57:977 EDT] 0000000e LogService-0-org.eclipse.osgi                                E CWWKE0701E: FrameworkEvent ERROR Bundle:org.eclipse.osgi(id=0) java.lang.IllegalStateException: A bundle is already attempting to use the name: publicMetricsURL - com.ibm.ws.microprofile.metrics.public_1.0.22.201808021436 [152]
    at com.ibm.ws.app.manager.wab.internal.WABInstaller$WABTrackerCustomizer.createConfigurableWAB(WABInstaller.java:706)
    at com.ibm.ws.app.manager.wab.internal.WABInstaller$WABTrackerCustomizer.addingBundle(WABInstaller.java:669)
    at com.ibm.ws.app.manager.wab.internal.WABInstaller$WABTrackerCustomizer.addingBundle(WABInstaller.java:648)
    at org.osgi.util.tracker.BundleTracker$Tracked.customizerAdding(BundleTracker.java:469)
    at org.osgi.util.tracker.BundleTracker$Tracked.customizerAdding(BundleTracker.java:1)
    at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256)
    at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:229)
    at org.osgi.util.tracker.BundleTracker$Tracked.bundleChanged(BundleTracker.java:444)
    at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:908)
    at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
    at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
    at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEventPrivileged(EquinoxEventPublisher.java:213)
    at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:120)
    at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:112)
    at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor.publishModuleEvent(EquinoxContainerAdaptor.java:168)
    at org.eclipse.osgi.container.Module.publishEvent(Module.java:476)
    at org.eclipse.osgi.container.Module.doStart(Module.java:578)
    at org.eclipse.osgi.container.Module.start(Module.java:449)
    at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:468)
    at org.eclipse.osgi.container.ModuleContainer.start(ModuleContainer.java:750)
    at org.eclipse.osgi.container.ModuleContainer.applyDelta(ModuleContainer.java:727)
    at org.eclipse.osgi.container.ModuleContainer.resolveAndApply(ModuleContainer.java:511)
    at org.eclipse.osgi.container.ModuleContainer.resolve(ModuleContainer.java:457)
    at org.eclipse.osgi.container.ModuleContainer.refresh(ModuleContainer.java:1001)
    at org.eclipse.osgi.container.ModuleContainer$ContainerWiring.dispatchEvent(ModuleContainer.java:1382)
    at org.eclipse.osgi.container.ModuleContainer$ContainerWiring.dispatchEvent(ModuleContainer.java:1)
    at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
    at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
 Event:org.osgi.framework.FrameworkEvent[source=org.eclipse.osgi_3.12.100.201808011821 [0]] 
```

**Comment by tkburroughs** [comment]
Is this issue ready to be closed?

**Comment by navidsh** [comment]
Delivered. Closing.
