### ISSUE TITLE
RejectedExecutionException: Trigger.getNextRunTime: null creating EJB timer

### ISSUE THREAD

**Issue by tkburroughs** [OpenLiberty/open-liberty#4465]
Creating a persistent EJB timer may fail with the following exception:

Caused by: java.util.concurrent.RejectedExecutionException: Trigger.getNextRunTime: null
at com.ibm.ws.concurrent.persistent.internal.PersistentExecutorImpl.newTask(PersistentExecutorImpl.java:1146)
at com.ibm.ws.concurrent.persistent.internal.PersistentExecutorImpl.schedule(PersistentExecutorImpl.java:1440)
at com.ibm.ws.ejbcontainer.timer.persistent.osgi.internal.EJBPersistentTimerRuntimeImpl.createPersistentCalendarTimer(EJBPersistentTimerRuntimeImpl.java:190)
at com.ibm.ws.ejbcontainer.osgi.internal.EJBRuntimeImpl.createPersistentCalendarTimer(EJBRuntimeImpl.java:582)
at com.ibm.ws.ejbcontainer.runtime.AbstractEJBRuntime.createTimer(AbstractEJBRuntime.java:2018)
at com.ibm.ejs.container.BeanO.createCalendarTimer(BeanO.java:2086)
at suite.timer.persistent.ejb.NoMoreTimeoutsBean.createTimer(NoMoreTimeoutsBean.java:147) ... 37 more "

**Comment by tkburroughs** [comment]
This error may occur when creating a persistent Calendar based EJB timer, which only has one scheduled time, and that time expires while the timer is being created.

Specifically, the EJB Container checked the scheduled expression to ensure it has at least one expiration in the future.  If there is at least one timeout, then the timer is created and scheduled to run.  When scheduled, the first timeout is calculated again.  However, if the one timeout for the timer has passed between the time the EJB Container checked and the timer is scheduled, then the RejectedExcecutionException occurs and timer creation fails.

The EJB specification indicates an EJB timer should determine timeouts based on the time the EJB timer is created, not when the transaction commits, so the timer should be valid and should run immediately.

The fix will be to detect the small timing window, and schedule to run the timer immediately, avoiding the failed timer creation.
