### ISSUE TITLE
CDI inject Optional configuration failed if configuraiton property is not defined

### ISSUE THREAD

**Issue by wayne-zhang** [OpenLiberty/open-liberty#4688]
Optional<T> is not injected if an Optional property declared but the property is not defined.

The following code
    // Example injection of an optional value that's not required to be present
    @Inject 
    @ConfigProperty(name = "application.optionalProperty")
    Optional<String> optionalApplicationProperty;

will trigger the following error in an Open Liberty micro profile server:

[17/08/18 15:37:42:018 AWST] 00002982 com.ibm.ws.app.manager.AppMessageHelper                      E CWWKZ0004E: An exception occurred while starting the application config-injection-1.0-SNAPSHOT. The exception message was: com.ibm.ws.container.service.state.StateChangeException: org.jboss.weld.exceptions.DeploymentException: WELD-001408: Unsatisfied dependencies for type Optional<String> with qualifiers @ConfigProperty
  at injection point [BackedAnnotatedField] @Inject @ConfigProperty fish.payara.examples.microprofile.configinjection.ShowConfigValues.optionalApplicationProperty
  at fish.payara.examples.microprofile.configinjection.ShowConfigValues.optionalApplicationProperty(ShowConfigValues.java:0)
WELD-001475: The following beans match by type, but none have matching qualifiers:
  - Producer Method [Optional<T>] with qualifiers [@Claim @Any] declared as [[UnbackedAnnotatedMethod] @Produces @Dependent @ManualTrace @Claim public com.ibm.ws.security.mp.jwt.cdi.ClaimProducer.getOptional(InjectionPoint)]

Open Liberty version is: 18.0.0.2

**Comment by benjamin-confino** [comment]
Hello. 

Could you try changing the type of `optionalApplicationProperty` from `Optional` to `Optional<The Actual Type>` I was able to recreate the error message you've seen and then fix it by adding a type parameter to Optional. I would like to know if adding a Type parameter resolves it on your end too. 

Regards
Benjamin

**Comment by benjamin-confino** [comment]
This sounds like it is behaving as expected. If you look at the docs for [ConfigProperty](https://openliberty.io/javadocs/microprofile-1.2-javadoc/org/eclipse/microprofile/config/inject/ConfigProperty.html) it says

> Binds the injection point with a configured value. Can be used to annotate injection points of type TYPE, Optional<TYPE> or javax.inject.Provider<TYPE>, where TYPE can be String and all types which have appropriate converters. 

Notice that it says Optional<TYPE>. If you want to use Optional without a <TYPE> you need to use a producer.

**Comment by wayne-zhang** [comment]
I think it's a bug. The producer of Optional Open Liberty supplied has qualifier @Claim (for JWT only?):

Producer Method [Optional] with qualifiers [@claim @Any] declared as [[UnbackedAnnotatedMethod] @Produces @dependent @ManualTrace @claim public com.ibm.ws.security.mp.jwt.cdi.ClaimProducer.getOptional(InjectionPoint)]

Open Liberty to implement a producer for @Default @Any Optional. 

Configuration property without defined should be able to be injected (instead of fail), that is why the property is declared as Optional.

**Comment by wayne-zhang** [comment]
Java Optional<T> don't have public constructor and it is not a CDI bean, so a producer is required. Open Liberty don't supply a @Default @Any Optional producer and let the application to create one is crazy.

I guess it not only @ConfigurationProperty, inject a POJO Optinonal<T> will fail too.

**Comment by wayne-zhang** [comment]
Actually the block of application deployment is dynamicOptinalProperty (not optionalProperty, even though this is a warning), inject Provider<Optional<String>> failed:

    @Inject 
    @ConfigProperty(name = "application.dynamicOptionalProperty")
    Provider<Optional<String>> dynamicOptionalProperty;

[22/08/18 16:55:05:975 AWST] 00000335 com.ibm.ws.microprofile.config.cdi.ConfigCDIExtension        E CWMCG5003E: The [BackedAnnotatedField] @Inject @ConfigProperty fish.payara.examples.microprofile.configinjection.ShowConfigValues.dynamicOptionalProperty InjectionPoint dependency was not resolved. Error: java.util.NoSuchElementException: CWMCG0015E: The property application.dynamicOptionalProperty was not found in the configuration.
        at com.ibm.ws.microprofile.config.impl.AbstractConfig.getValue(AbstractConfig.java:145)
        at com.ibm.ws.microprofile.config.cdi.ConfigProducer.newValue(ConfigProducer.java:44)
        at com.ibm.ws.microprofile.config.cdi.ConfigCDIExtension.processConversionType(ConfigCDIExtension.java:131)
        at com.ibm.ws.microprofile.config.cdi.ConfigCDIExtension.processParameterizedType(ConfigCDIExtension.java:115)
        at com.ibm.ws.microprofile.config.cdi.ConfigCDIExtension.processInjectionTarget(ConfigCDIExtension.java:74)
        at sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:88)
        at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:78)
        at org.jboss.weld.injection.MethodInvocationStrategy$SimpleMethodInvocationStrategy.invoke(MethodInvocationStrategy.java:129)
        at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:299)
        at org.jboss.weld.event.ExtensionObserverMethodImpl.sendEvent(ExtensionObserverMethodImpl.java:124)
        at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:277)
        at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:255)
        at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:269)
        at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:258)
        at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:154)
        at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:148)
        at org.jboss.weld.bootstrap.events.AbstractContainerEvent.fire(AbstractContainerEvent.java:53)
        at org.jboss.weld.bootstrap.events.AbstractDefinitionContainerEvent.fire(AbstractDefinitionContainerEvent.java:44)
        at org.jboss.weld.bootstrap.events.AbstractProcessInjectionTarget.fire(AbstractProcessInjectionTarget.java:40)
        at org.jboss.weld.bootstrap.events.ContainerLifecycleEvents.fireProcessInjectionTarget(ContainerLifecycleEvents.java:255)
        at org.jboss.weld.manager.BeanManagerImpl.fireProcessInjectionTarget(BeanManagerImpl.java:1361)
        at org.jboss.weld.manager.BeanManagerImpl.fireProcessInjectionTarget(BeanManagerImpl.java:1356)
        at com.ibm.ws.cdi.impl.weld.BeanDeploymentArchiveImpl.createJEEComponentInjectionTarget(BeanDeploymentArchiveImpl.java:888)
        at com.ibm.ws.cdi.impl.weld.BeanDeploymentArchiveImpl.createInjectionTargetsForJEEComponentClass(BeanDeploymentArchiveImpl.java:826)
        at com.ibm.ws.cdi.impl.weld.BeanDeploymentArchiveImpl.createInjectionTargetsForJEEComponentClasses(BeanDeploymentArchiveImpl.java:812)
        at com.ibm.ws.cdi.impl.weld.WebSphereCDIDeploymentImpl.validateJEEComponentClasses(WebSphereCDIDeploymentImpl.java:671)
        at com.ibm.ws.cdi.impl.CDIContainerImpl.startInitialization(CDIContainerImpl.java:150)
        at com.ibm.ws.cdi.liberty.CDIRuntimeImpl.applicationStarting(CDIRuntimeImpl.java:400)
        at com.ibm.ws.container.service.state.internal.ApplicationStateManager.fireStarting(ApplicationStateManager.java:28)
        at com.ibm.ws.container.service.state.internal.StateChangeServiceImpl.fireApplicationStarting(StateChangeServiceImpl.java:50)
        at com.ibm.ws.app.manager.module.internal.DeployedAppInfoBase.preDeployApp(DeployedAppInfoBase.java:383)
        at com.ibm.ws.app.manager.module.internal.DeployedAppInfoBase.deployApp(DeployedAppInfoBase.java:412)
        at com.ibm.ws.app.manager.war.internal.WARApplicationHandlerImpl.install(WARApplicationHandlerImpl.java:65)
        at com.ibm.ws.app.manager.internal.statemachine.StartAction.execute(StartAction.java:140)
        at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.enterState(ApplicationStateMachineImpl.java:1258)
        at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.performAction(ApplicationStateMachineImpl.java:1126)
        at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.run(ApplicationStateMachineImpl.java:881)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)

**Comment by wayne-zhang** [comment]
I can confirm inject a POJO Optional<T> fails deployment of a WAR (without define an Optional Producer)

    @Inject
    Optional<String> option;

**Comment by wayne-zhang** [comment]
I guess Open Liberty is missing a producer for Optional<T> with qualifier @ConfigProperty?

**Comment by Emily-Jiang** [comment]
@wayne-zhang thanks for the report! 
You mentioned a few examples here. Let me try to put some analysis here

1. Inject an Optional without a type
`@Inject
@ConfigProperty(name = "application.optionalProperty")
Optional optionalApplicationProperty;`

The above should be user error. The exception message displayed is correct. 
2. `@Inject 
//@Preferred
@ConfigProperty(name = "application.optionalProperty")
Optional<String> optionalApplicationProperty;
`
This should work. We are trying to reproduce this and report back.

**Comment by wayne-zhang** [comment]
Emily,
I think it is caused by Open Liberty doesn't supply an out of box producer for @ConfigProperty Optional<T> in the the config module (JWT module has one for @Claim). The following code that creates a producer in the application can make it work:

@ApplicationScoped
public class BeanFactory {
    // IBM Open Libery fails when there is no property defined for Optional<String>.
    // Define a producer
    @Produces 
    @Preferred
    @ConfigProperty
    public <T> Optional<T> forIbmOpenLibertyConfigProperty(){
        return Optional.empty();
    }   
}

The @Preferred qualifier is to make this code works on both Payara Micro and Open Liberty. Payara supplies a producer for @ConfigProperty Optional<T>, @Preferred make CDI choose the application one.

**Comment by wayne-zhang** [comment]
I have mentioned in my previous comment already, Optional without generic type (it's Optional<Object> anyway, isn't it?) is a typo. The original code do have generic type.

Even with type in Optional<T>, it still fails where is no configuration defined.

**Comment by wayne-zhang** [comment]
Actually, it failed at Provider<Optional<T>>, not Optional<T>. A deployment error, caused by NoSuchElementException:

[3/09/18 13:19:31:023 AWST] 00000403 com.ibm.ws.microprofile.config.cdi.ConfigCDIExtension        E CWMCG5003E: The [BackedAnnotatedField] @Inject @ConfigProperty fish.payara.examples.microprofile.configinjection.ShowConfigValues.dynamicOptionalProperty InjectionPoint dependency was not resolved. Error: java.util.NoSuchElementException: CWMCG0015E: The property application.dynamicOptionalProperty was not found in the configuration.
        at com.ibm.ws.microprofile.config.impl.AbstractConfig.getValue(AbstractConfig.java:145)

Code:

    @Inject 
    @ConfigProperty(name = "application.dynamicOptionalProperty")
    Provider<Optional<String>> dynamicOptionalProperty;

Can be fixed by adding a Optionla<String> producer.

**Comment by benjamin-confino** [comment]
While I have reproduced the failure for 

```
@ConfigPropety
Optional
```

I have found that 


```
@ConfigPropety
Optional<String> 
```
Works without trouble.

**Comment by wayne-zhang** [comment]
@benjamin-confino 
How about 
@ConfigProperty
Provider<Optional<String>>  p;

I don't think it work.

**Comment by benjamin-confino** [comment]
@Inject
  @ConfigProperty(name = "application.optionalProperty")
  Provider<Optional> optionalApplicationProperty;

Injects an optional correctly.

**Comment by wayne-zhang** [comment]
Please try 
@Inject
@ConfigProperty(name = "application.optionalProperty")
Provider<Optional<String>> optionalApplicationProperty;

Provider doesn't make sense in CDI.

**Comment by wayne-zhang** [comment]
It should be 
Provider<Optional&lt;String&gt;>, you site has problems to post generics in generics.

**Comment by benjamin-confino** [comment]
I'm hopeful to have a fix in today or tomorrow.

**Comment by benjamin-confino** [comment]
The fix is in.

**Comment by wayne-zhang** [comment]
@benjamin-confino 
Hi Benjamin, 
Thanks for you fix. Has your fix included in the current development build release?
Cheers,
Wayne

**Comment by wayne-zhang** [comment]
I can confirm it works on build openliberty-all-18.0.0.4-20181009-2101.zip. This issue can be closed.
