### ISSUE TITLE
SRVE0777E: Exception thrown by application class 'com.ibm.ws.security.authentication.principals.WSPrincipal.<init>:65'

### ISSUE THREAD

**Issue by dburdine** [OpenLiberty/open-liberty#4715]
After upgrading from 18.0.0.1 to 18.0.0.2 the following exception was seen.

WSPrincipal init fails because securityName is an empty string.
```
22706 [8/7/18 10:13:40:014 EDT] 000000cf ApplicationEr E   SRVE0777E: Exception thrown by application class 'com.ibm.ws.security.authentication.principals.WSPrincipal.<init>:65'
22707 java.lang.IllegalArgumentException: Sanity check, null / empty values are invalid here
22708 	at com.ibm.ws.security.authentication.principals.WSPrincipal.<init>(WSPrincipal.java:65)
22709 	at com.ibm.ws.security.collaborator.CollaboratorUtils.getCallerPrincipal(CollaboratorUtils.java:98)
22710 	at com.ibm.ws.webcontainer.security.WebAppSecurityCollaboratorImpl.getUserPrincipal(WebAppSecurityCollaboratorImpl.java:423)
22711 	at com.ibm.ws.webcontainer.srt.SRTServletRequest.getUserPrincipal(SRTServletRequest.java:2805)
22712 	at org.apache.cxf.transport.http.AbstractHTTPDestination$2.<init>(AbstractHTTPDestination.java:308)
22713 	at org.apache.cxf.transport.http.AbstractHTTPDestination.setupMessage(AbstractHTTPDestination.java:307)
22714 	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:195)
22715 	at com.ibm.ws.jaxws.endpoint.AbstractJaxWsWebEndpoint.invoke(AbstractJaxWsWebEndpoint.java:181)
22716 	at com.ibm.ws.jaxws.webcontainer.LibertyJaxWsServlet.handleRequest(LibertyJaxWsServlet.java:134)
22717 	at com.ibm.ws.jaxws.webcontainer.LibertyJaxWsServlet.doPost(LibertyJaxWsServlet.java:93)
22718 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
22719 	at com.ibm.ws.jaxws.webcontainer.LibertyJaxWsServlet.service(LibertyJaxWsServlet.java:85)
22720 	at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1255)
22721 	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:743)
22722 	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:440)
22723 	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1208)
22724 	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1005)
22725 	at com.ibm.ws.webcontainer.servlet.CacheServletWrapper.handleRequest(CacheServletWrapper.java:75)
22726 	at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:927)
22727 	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:279)
22728 	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1011)
22729 	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:414)
22730 	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:373)
22731 	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:532)
22732 	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:466)
22733 	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:331)
22734 	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.ready(HttpInboundLink.java:302)
22735 	at com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.sendToDiscriminators(NewConnectionInitialReadCallback.java:165)
22736 	at com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.complete(NewConnectionInitialReadCallback.java:74)
22737 	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:501)
22738 	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueManager.java:571)
22739 	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:926)
22740 	at com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:1015)
22741 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
22742 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
22743 	at java.lang.Thread.run(Thread.java:811)
```

This can occur when using the ldapRegistry-3.0 feature if the LDAP registry's user filter may return user's whose objectclass does not map to the PersonAccount entity. To resolve this issue map all expected LDAP user objectclasses to the PersonAccount entity in the problematic LDAP registry. For example:

```
<ldapRegistry ...>
    <ldapEntityType name="PersonAccount">
        <objectClass>inetOrgPerson</objectClass>
        <objectClass>anotherUserClass</objectClass>
    </ldapEntityType>
</ldapRegistry>
```

**Comment by dburdine** [comment]
Merged in PR 4741
