### ISSUE TITLE
NullPointerException is thrown when an application builds a request to the targeted web resource

### ISSUE THREAD

**Issue by annaguri** [OpenLiberty/open-liberty#4815]
The following NPE is thrown when an application builds a request to the targeted web resource.
The issue happens in 18.0.0.3. It looks like a regression as the same code worked with no issues in the previous releases. 

java.lang.NullPointerException
        at org.apache.cxf.endpoint.AbstractConduitSelector.matchAddresses(AbstractConduitSelector.java:269)
        at org.apache.cxf.endpoint.AbstractConduitSelector.findCompatibleConduit(AbstractConduitSelector.java:254)
        at org.apache.cxf.endpoint.AbstractConduitSelector.getSelectedConduit(AbstractConduitSelector.java:95)
        at org.apache.cxf.endpoint.UpfrontConduitSelector.prepare(UpfrontConduitSelector.java:63)
        at org.apache.cxf.jaxrs.client.ClientConfiguration.prepareConduitSelector(ClientConfiguration.java:110)
        at org.apache.cxf.jaxrs.client.ClientConfiguration.getConduit(ClientConfiguration.java:204)
        at org.apache.cxf.jaxrs.client.ClientConfiguration.getHttpConduit(ClientConfiguration.java:214)
        at org.apache.cxf.jaxrs.client.spec.ClientImpl$WebTargetImpl.request(ClientImpl.java:355)
        at org.apache.cxf.jaxrs.client.spec.ClientImpl$WebTargetImpl.request(ClientImpl.java:422)

**Comment by jim-krueger** [comment]
Fix included in 18.0.0.3 stream.
