### ISSUE TITLE
JAX-WS attempts to initialize extensions during app shutdown

### ISSUE THREAD

**Issue by aguibert** [OpenLiberty/open-liberty#4857]
While working on a new FAT for OpenLiberty, I saw the following error in logs (the app was just enabling the javaee-8.0 feature and not even using JAX-WS):

```
[8/27/18 16:08:00:823 CDT] 00000072 com.ibm.ws.webcontainer.webapp                               E SRVE0280E: Extension processor failed to initialize in factory [com.ibm.ws.jaxws.webcontainer.JaxWsExtensionFactory@59a4e43b]: java.lang.IllegalStateException: SRVE0320E: Programmatic configuration methods must be called from within contextInitialized.
	at com.ibm.ws.webcontainer.webapp.WebApp.commonAddServlet(WebApp.java:5935)
	at com.ibm.ws.webcontainer.webapp.WebApp.addServlet(WebApp.java:5906)
	at com.ibm.ws.jaxws.webcontainer.WebEndpointPublisher.publish(WebEndpointPublisher.java:129)
	at com.ibm.ws.jaxws.webcontainer.JaxWsExtensionFactory.createExtensionProcessor(JaxWsExtensionFactory.java:120)
	at com.ibm.ws.webcontainer.webapp.WebApp.initializeExtensionProcessors(WebApp.java:2035)
	at com.ibm.ws.webcontainer.webapp.WebApp.removeExtensionFactory(WebApp.java:6381)
	at com.ibm.ws.webcontainer.osgi.WebContainer.unsetExtensionFactory(WebContainer.java:1294)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.felix.scr.impl.inject.BaseMethod.invokeMethod(BaseMethod.java:229)
        more OSGi stack...
```

**Comment by aguibert** [comment]
[ffdc_18.08.27_16.08.00.0.log](https://github.com/OpenLiberty/open-liberty/files/2325647/ffdc_18.08.27_16.08.00.0.log)

**Comment by ashankar** [comment]
Is this issue resolved or not yet?
I'm also facing the same issue.

**Comment by tbitonti** [comment]
This is still observed on 31-July-2024.
