### ISSUE TITLE
JDK11: DateTimeParseException: Text ... could not be parsed at index ...

### ISSUE THREAD

**Issue by nmittles** [OpenLiberty/open-liberty#5078]
When running the com.ibm.ws.ebjcontainer.timer_fat bucket with JDK 11 the com.ibm.ws.metadata/ejb/AutomaticTimerBean$DateHelper.parse() method is going down a different code path due to the removal of JAXB.  As a result the following ffdc occurs:

java.lang.IllegalArgumentException: java.lang.reflect.InvocationTargetException

	at com.ibm.ws.metadata.ejb.AutomaticTimerBean$DateHelper.parse(AutomaticTimerBean.java:250)

	at com.ibm.ws.metadata.ejb.AutomaticTimerBean.parseXSDDateTime(AutomaticTimerBean.java:197)

	at com.ibm.ws.metadata.ejb.AutomaticTimerBean.parseScheduleExpression(AutomaticTimerBean.java:164)

	at com.ibm.ws.ejbcontainer.runtime.AbstractEJBRuntime.createNonPersistentAutomaticTimer(AbstractEJBRuntime.java:1947)

	at com.ibm.ws.ejbcontainer.runtime.AbstractEJBRuntime.createNonPersistentAutomaticTimers(AbstractEJBRuntime.java:1925)

	at com.ibm.ws.ejbcontainer.osgi.internal.EJBRuntimeImpl.createNonPersistentAutomaticTimers(EJBRuntimeImpl.java:554)

	at com.ibm.ws.ejbcontainer.runtime.AbstractEJBRuntime.startModule(AbstractEJBRuntime.java:613)

	at com.ibm.ws.ejbcontainer.osgi.internal.EJBRuntimeImpl.start(EJBRuntimeImpl.java:970)

	at com.ibm.ws.ejbcontainer.osgi.internal.EJBModuleRuntimeContainerImpl.startModule(EJBModuleRuntimeContainerImpl.java:145)

	at com.ibm.ws.app.manager.module.internal.ModuleHandlerBase.deployModule(ModuleHandlerBase.java:99)

	at com.ibm.ws.app.manager.module.internal.DeployedModuleInfoImpl.installModule(DeployedModuleInfoImpl.java:49)

	at com.ibm.ws.app.manager.module.internal.DeployedAppInfoBase.deployModules(DeployedAppInfoBase.java:429)

	at com.ibm.ws.app.manager.module.internal.DeployedAppInfoBase.deployApp(DeployedAppInfoBase.java:415)

	at com.ibm.ws.app.manager.ear.internal.EARApplicationHandlerImpl.install(EARApplicationHandlerImpl.java:76)

	at com.ibm.ws.app.manager.internal.statemachine.StartAction.execute(StartAction.java:140)

	at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.enterState(ApplicationStateMachineImpl.java:1258)

	at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.run(ApplicationStateMachineImpl.java:873)

	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)

	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)

	at java.base/java.lang.Thread.run(Thread.java:834)

Caused by: java.lang.reflect.InvocationTargetException

	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

	at java.base/java.lang.reflect.Method.invoke(Method.java:566)

	at com.ibm.ws.metadata.ejb.AutomaticTimerBean$DateHelper.parse(AutomaticTimerBean.java:245)

	... 19 more

Caused by: java.time.format.DateTimeParseException: Text '2050' could not be parsed at index 4

	at java.base/java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2046)

	at java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1874)

	... 24 more

I manually reproduced this in straight java by copying part of the code out of the parse() method.  It seems the code can't handle parsing a date that is a 4 digit year, such as 2050.
If I change the parse string from "2050" to "2050-12-31T01:01:01" it works fine.

**Comment by nmittles** [comment]
This non-JAXB code path was added by:
 https://github.com/OpenLiberty/open-liberty/pull/4683/files#diff-7dc460d94709f1814108a5e0c9d037e5

**Comment by olendvcook** [comment]
#link 258334

**Comment by tkburroughs** [comment]
open-liberty PR merged; closing
