### ISSUE TITLE
SpringBoot applications fail to start when a non jar file is in the library directory

### ISSUE THREAD

**Issue by bpaskin-ibm** [OpenLiberty/open-liberty#5088]
When using SpringBoot (1.5 or 2.0) in 18.0.0.2 the application will fail with a NPE when trying to start the application.  This is do to having with having a non library in a the library folder (WEB-INF/lib) or other library directory.  Removing the file fixes the issue.

Error:
```
Stack Dump = java.lang.NullPointerException
        at com.ibm.ws.artifact.overlay.internal.DirectoryBasedOverlayContainerImpl.<init>(DirectoryBasedOverlayContainerImpl.java:87)
        at com.ibm.ws.artifact.overlay.internal.DirectoryBasedOverlayContainerImpl.<init>(DirectoryBasedOverlayContainerImpl.java:78)
        at com.ibm.ws.artifact.overlay.internal.OverlayContainerFactoryImpl.createOverlay(OverlayContainerFactoryImpl.java:37)
        at com.ibm.ws.adaptable.module.internal.AdaptableModuleFactoryImpl.getContainer(AdaptableModuleFactoryImpl.java:77)
        at com.ibm.ws.app.manager.springboot.internal.LibIndexCache.getLibraryContainer(LibIndexCache.java:104)
        at com.ibm.ws.app.manager.springboot.internal.SpringBootApplicationImpl.getStoredIndexClassesInfos(SpringBootApplicationImpl.java:767)
        at com.ibm.ws.app.manager.springboot.internal.SpringBootApplicationImpl.getContainerInfos(SpringBootApplicationImpl.java:723)
        at com.ibm.ws.app.manager.springboot.internal.SpringBootApplicationImpl.<init>(SpringBootApplicationImpl.java:513)
        at com.ibm.ws.app.manager.springboot.internal.SpringBootApplicationFactory.createDeployedAppInfo(SpringBootApplicationFactory.java:83)
        at com.ibm.ws.app.manager.springboot.internal.SpringBootHandler.setUpApplicationMonitoring(SpringBootHandler.java:159)
        at com.ibm.ws.app.manager.internal.statemachine.StartAction.execute(StartAction.java:136)
        at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.enterState(ApplicationStateMachineImpl.java:1258)
        at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.run(ApplicationStateMachineImpl.java:873)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.lang.Thread.run(Thread.java:812)
```

**Comment by tjwatson** [comment]
At a minimum we need to filter out the libraries that do not have the extensions we support currently for the embedded library JARs.  Currently that is files with the following extensions: "jar", "zip", "ear", "war", "rar", "eba", "esa", "sar", and "spring".

This may become problematic if applications really do expect other library extensions to be loaded by the application's class loader.  I have not confirmed the behavior, but looking at the Spring Boot loader code, it does appear to put any file in the BOOT-INF/lib folder on the classpath of the class loader with no regard to the file extension.  If that becomes a real problem then we will need a more involved fix to allow us to load any file extension as a library JAR.

**Comment by tjwatson** [comment]
Fir the first thing, the most simple solution would be to do a check in com.ibm.ws.app.manager.springboot.internal.SpringBootApplicationImpl.getStoredIndexClassesInfos(Entry, LibIndexCache) in the for loop that iterates over the entries in the indexMap.  Here we can check the key for the proper extension and only create containers for the ones that have good extensions.

**Comment by tjwatson** [comment]
This has been merged into master.
