### ISSUE TITLE
NullPointerException received while building open-liberty using OpenJ9 JDK 8 (Linux)

### ISSUE THREAD

**Issue by Mesbah-Alam** [OpenLiberty/open-liberty#5125]
Attempt to build open-liberty  (`./gradlew assemble :com.ibm.websphere.appserver.features:releaseNeeded`) using OpenJ9 JDK 8 SDK yields the following NullPointerException : 

```

> Task :com.ibm.websphere.appserver.features:generateSingleJsonRepo FAILED
[ant:singleJsonRepo] java.lang.NullPointerException
[ant:singleJsonRepo]    at com.ibm.ws.repository.transport.client.DataModelSerializer.processJsonObjectBackIntoDataModelInstance(DataModelSerializer.java:497)
[ant:singleJsonRepo]    at com.ibm.ws.repository.transport.client.DataModelSerializer.processJsonObjectBackIntoDataModelInstance(DataModelSerializer.java:541)
[ant:singleJsonRepo]    at com.ibm.ws.repository.transport.client.DataModelSerializer.deserializeObject(DataModelSerializer.java:754)
[ant:singleJsonRepo]    at com.ibm.ws.repository.transport.client.SingleFileClient.getAllAssets(SingleFileClient.java:132)
[ant:singleJsonRepo]    at com.ibm.ws.repository.transport.client.AbstractRepositoryClient.getFilteredAssets(AbstractRepositoryClient.java:103)
[ant:singleJsonRepo]    at com.ibm.ws.repository.connections.internal.AbstractRepositoryConnection.getMatchingResources(AbstractRepositoryConnection.java:255)
[ant:singleJsonRepo]    at com.ibm.ws.repository.resources.internal.EsaResourceImpl.getPotentiallyMatchingResources(EsaResourceImpl.java:370)
[ant:singleJsonRepo]    at com.ibm.ws.repository.resources.internal.RepositoryResourceImpl.performMatching(RepositoryResourceImpl.java:959)
[ant:singleJsonRepo]    at com.ibm.ws.repository.resources.internal.RepositoryResourceImpl.findMatchingResource(RepositoryResourceImpl.java:1031)
[ant:singleJsonRepo]    at com.ibm.ws.repository.strategies.writeable.AddThenDeleteStrategy.findMatchingResources(AddThenDeleteStrategy.java:195)
[ant:singleJsonRepo]    at com.ibm.ws.repository.resources.internal.RepositoryResourceImpl.uploadToMassive(RepositoryResourceImpl.java:1220)
[ant:singleJsonRepo]    at com.ibm.ws.repository.generator.SingleJsonRepositoryGenerator.execute(SingleJsonRepositoryGenerator.java:120)
[ant:singleJsonRepo]    at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
[ant:singleJsonRepo]    at sun.reflect.GeneratedMethodAccessor483.invoke(Unknown Source)
[ant:singleJsonRepo]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ant:singleJsonRepo]    at java.lang.reflect.Method.invoke(Method.java:498)
[ant:singleJsonRepo]    at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[ant:singleJsonRepo]    at groovy.util.AntBuilder.performTask(AntBuilder.java:327)
[ant:singleJsonRepo]    at groovy.util.AntBuilder.nodeCompleted(AntBuilder.java:272)
[ant:singleJsonRepo]    at org.gradle.api.internal.project.ant.BasicAntBuilder.nodeCompleted(BasicAntBuilder.java:78)
[ant:singleJsonRepo]    at groovy.util.BuilderSupport.doInvokeMethod(BuilderSupport.java:154)
[ant:singleJsonRepo]    at groovy.util.AntBuilder.doInvokeMethod(AntBuilder.java:207)
[ant:singleJsonRepo]    at org.gradle.api.internal.project.ant.BasicAntBuilder.doInvokeMethod(BasicAntBuilder.java:103)
[ant:singleJsonRepo]    at groovy.util.BuilderSupport.invokeMethod(BuilderSupport.java:67)
[ant:singleJsonRepo]    at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:48)
[ant:singleJsonRepo]    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
[ant:singleJsonRepo]    at build_els0myzh8sbmiajcvcirdavi6$_run_closure11$_closure40$_closure41.doCall(/tmp/mesbah/open-liberty/dev/com.ibm.websphere.appserver.features/build.gradle:332)
[ant:singleJsonRepo]    at sun.reflect.GeneratedMethodAccessor785.invoke(Unknown Source)
[ant:singleJsonRepo]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ant:singleJsonRepo]    at java.lang.reflect.Method.invoke(Method.java:498)
[ant:singleJsonRepo]    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
[ant:singleJsonRepo]    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
[ant:singleJsonRepo]    at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
[ant:singleJsonRepo]    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
[ant:singleJsonRepo]    at groovy.lang.Closure.call(Closure.java:414)
[ant:singleJsonRepo]    at groovy.lang.Closure.call(Closure.java:430)
[ant:singleJsonRepo]    at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2040)
[ant:singleJsonRepo]    at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2025)
[ant:singleJsonRepo]    at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2090)
[ant:singleJsonRepo]    at org.codehaus.groovy.runtime.dgm$166.invoke(Unknown Source)
[ant:singleJsonRepo]    at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:274)
[ant:singleJsonRepo]    at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
[ant:singleJsonRepo]    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
[ant:singleJsonRepo]    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
[ant:singleJsonRepo]    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
[ant:singleJsonRepo]    at build_els0myzh8sbmiajcvcirdavi6$_run_closure11$_closure40.doCall(/tmp/mesbah/open-liberty/dev/com.ibm.websphere.appserver.features/build.gradle:328)
[ant:singleJsonRepo]    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ant:singleJsonRepo]    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ant:singleJsonRepo]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ant:singleJsonRepo]    at java.lang.reflect.Method.invoke(Method.java:498)
[ant:singleJsonRepo]    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
[ant:singleJsonRepo]    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
[ant:singleJsonRepo]    at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
[ant:singleJsonRepo]    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
[ant:singleJsonRepo]    at groovy.lang.Closure.call(Closure.java:414)
[ant:singleJsonRepo]    at groovy.lang.Closure.call(Closure.java:430)
[ant:singleJsonRepo]    at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:732)
[ant:singleJsonRepo]    at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:705)
[ant:singleJsonRepo]    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:131)
[ant:singleJsonRepo]    at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
[ant:singleJsonRepo]    at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
[ant:singleJsonRepo]    at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
[ant:singleJsonRepo]    at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:97)
[ant:singleJsonRepo]    at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
[ant:singleJsonRepo]    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:120)
[ant:singleJsonRepo]    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:99)
[ant:singleJsonRepo]    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
[ant:singleJsonRepo]    at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
[ant:singleJsonRepo]    at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
[ant:singleJsonRepo]    at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
[ant:singleJsonRepo]    at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
[ant:singleJsonRepo]    at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
[ant:singleJsonRepo]    at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
[ant:singleJsonRepo]    at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
[ant:singleJsonRepo]    at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
[ant:singleJsonRepo]    at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
[ant:singleJsonRepo]    at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
[ant:singleJsonRepo]    at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
[ant:singleJsonRepo]    at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
[ant:singleJsonRepo]    at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:51)
[ant:singleJsonRepo]    at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
[ant:singleJsonRepo]    at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
[ant:singleJsonRepo]    at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
[ant:singleJsonRepo]    at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:97)
[ant:singleJsonRepo]    at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
[ant:singleJsonRepo]    at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
[ant:singleJsonRepo]    at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$ExecuteTaskAction.execute(DefaultTaskExecutionGraph.java:262)
[ant:singleJsonRepo]    at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$ExecuteTaskAction.execute(DefaultTaskExecutionGraph.java:246)
[ant:singleJsonRepo]    at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:136)
[ant:singleJsonRepo]    at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:130)
[ant:singleJsonRepo]    at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.execute(DefaultTaskPlanExecutor.java:201)
[ant:singleJsonRepo]    at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.executeWithTask(DefaultTaskPlanExecutor.java:192)
[ant:singleJsonRepo]    at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
[ant:singleJsonRepo]    at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
[ant:singleJsonRepo]    at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
[ant:singleJsonRepo]    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[ant:singleJsonRepo]    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[ant:singleJsonRepo]    at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
[ant:singleJsonRepo]    at java.lang.Thread.run(Thread.java:813)

FAILURE: Build failed with an exception.

* Where:
Build file '/tmp/mesbah/open-liberty/dev/com.ibm.websphere.appserver.features/build.gradle' line: 332

* What went wrong:
Execution failed for task ':com.ibm.websphere.appserver.features:generateSingleJsonRepo'.
> java.lang.NullPointerException

```

**Java version details**
```
openjdk version "1.8.0_192-adoptopenjdk"
OpenJDK Runtime Environment (build 1.8.0_192-adoptopenjdk-03)
Eclipse OpenJ9 VM (build master-92b34592, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20180914_12 (JIT enabled, AOT enabled)
OpenJ9   - 92b34592
OMR      - 97818b41
JCL      - df909af63f based on jdk8u192-b03)
```
**Here are the steps I followed to produce the NPE:**
```
1) Obtain OpenJ9 JDK 8 Linux x64 jdk from Adopt (nightly builds can be found here: https://adoptopenjdk.net/nightly.html?variant=openjdk8&jvmVariant=openj9 , please choose "OpenJDK 8 with Eclipse OpenJ9") 
2) export JAVA_HOME = <OpenJ9 JDK 8>
3) git clone https://github.com/OpenLiberty/open-liberty
4) cd open-liberty/dev
5) ./gradlew cnf:initialize
6) ./gradlew assemble :com.ibm.websphere.appserver.features:releaseNeeded
```

**Comment by fritze2** [comment]
Fixed by #6074
