### ISSUE TITLE
Test Failure (Liberty - Mac EBC - 20180917-0110): ConcurrentRxTest.testActionlessFutureWithSpecifiedExecutor

### ISSUE THREAD

**Issue by njr-11** [OpenLiberty/open-liberty#5141]
Test Failure (Liberty - Mac EBC - 20180917-0110): com.ibm.ws.concurrent.rx.ConcurrentRxTest.testActionlessFutureWithSpecifiedExecutor

testActionlessFutureWithSpecifiedExecutor
junit.framework.AssertionFailedError: 2018-09-17-06:49:58:144 The response did not contain [SUCCESS].  Full output is:
ERROR: Caught exception attempting to call test method testActionlessFutureWithSpecifiedExecutor on servlet web.ConcurrentRxTestServlet
java.lang.AssertionError: expected:<Thread[Default Executor-thread-55Default Executor Thread Group]> but was:<Thread[Default Executor-thread-105Default Executor Thread Group]>
at web.ConcurrentRxTestServlet.testActionlessFutureWithSpecifiedExecutor(ConcurrentRxTestServlet.java:451)
at componenttest.app.FATServlet.doGet(FATServlet.java:71)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:686)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:791)
at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1255)
at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:743)
at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:440)
at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1221)
at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1005)
at com.ibm.ws.webcontainer.servlet.CacheServletWrapper.handleRequest(CacheServletWrapper.java:75)
at com.ibm.ws.webcontainer40.servlet.CacheServletWrapper40.handleRequest(CacheServletWrapper40.java:83)
at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:927)
at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:279)
at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1011)
at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:414)
at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:373)
at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.

Upon investigation, it looks like an erroneous assert in the test case was replaced by a valid one, except that the old, invalid assertion was accidentally left in place. It needs to be removed to avoid these infrequent intermittent failures.

**Comment by tkburroughs** [comment]
Is this issue ready to be closed?
