### ISSUE TITLE
Occasional HTTP/2 MessageSentException: Message already sent 

### ISSUE THREAD

**Issue by wtlucy** [OpenLiberty/open-liberty#5383]
In rare cases, a "MessageSentException" can occur during a HTTP/2 connection.  This does not cause any client-visible problem; the correct response is written, but due to a race condition an attempt is made by the HTTP channel to flush the response again.

>Exception = com.ibm.wsspi.genericbnf.exception.MessageSentException
>Source = com.ibm.wsspi.http.ee7.HttpOutputStreamEE7
>probeid = flushBuffers
>Stack Dump = com.ibm.wsspi.genericbnf.exception.MessageSentException: Message already sent
> at com.ibm.ws.http.channel.internal.inbound.HttpInboundServiceContextImpl.finishResponseMessage(HttpInboundServiceContextImpl.java:1001)
> at com.ibm.ws.http.channel.internal.outbound.HttpOutputStreamImpl.flushBuffers(HttpOutputStreamImpl.java:508)
> at com.ibm.ws.http.channel.internal.outbound.HttpOutputStreamImpl.close(HttpOutputStreamImpl.java:595)
> at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.tryToCloseStream(HttpDispatcherLink.java:1048)

**Comment by jwalcorn** [comment]
I still see this occasionally, on Open Liberty 22.0.0.6.  As said here, it seems benign, but log watchers will see the FFDC being generated:

com.ibm.wsspi.genericbnf.exception.MessageSentException: Message already sent
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundServiceContextImpl.finishResponseMessage(HttpInboundServiceContextImpl.java:920)
	at com.ibm.ws.http.channel.internal.outbound.HttpOutputStreamImpl.flushBuffers(HttpOutputStreamImpl.java:538)
	at com.ibm.ws.http.channel.internal.outbound.HttpOutputStreamImpl.close(HttpOutputStreamImpl.java:625)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.tryToCloseStream(HttpDispatcherLink.java:1221)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.closeStreams(HttpDispatcherLink.java:1135)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.finish(HttpDispatcherLink.java:1035)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:295)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1184)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:453)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:412)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:566)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:500)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:360)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.ready(HttpInboundLink.java:327)
	at com.ibm.ws.http.channel.h2internal.H2StreamProcessor$Http2Ready.run(H2StreamProcessor.java:1789)
	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:245)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:889)

[ffdc_22.08.01_18.16.47.0.log](https://github.com/OpenLiberty/open-liberty/files/9236402/ffdc_22.08.01_18.16.47.0.log)
[messages.log](https://github.com/OpenLiberty/open-liberty/files/9236407/messages.log)
