### ISSUE TITLE
[Java11] Test Failure (20181011-1532): com.ibm.ws.microprofile.metrics.tck.launcher.MetricsAuthenticationTest.testMetrics10Auth

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#5384]
RTC 258661

```
junit.framework.AssertionFailedError: 2018-10-12-09:16:06:730 Web application is not available at */metrics/
at com.ibm.ws.microprofile.metrics.tck.launcher.MetricsAuthenticationTest.waitForMetricsEndpoint(MetricsAuthenticationTest.java:82)
at com.ibm.ws.microprofile.metrics.tck.launcher.MetricsAuthenticationTest.testMetricsAuth(MetricsAuthenticationTest.java:130)
at com.ibm.ws.microprofile.metrics.tck.launcher.MetricsAuthenticationTest.testMetrics10Auth(MetricsAuthenticationTest.java:63)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:193)
at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:323)
at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:167)
```

**Comment by donbourne** [comment]
this has been returned on RTC side
