### ISSUE TITLE
Test Failure (20181013-0121): com.ibm.ws.fat.hpel.tests.ConcurrentLoggingAccuracyTest.testConcurrentLoggingAccuracyCheck

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#5419]
RTC 258701

```
junit.framework.AssertionFailedError: The repository does not contain the number of records it had wrote for Level.SEVERE {counted:wrote} {1560:1600}
at com.ibm.ws.fat.hpel.tests.ConcurrentLoggingAccuracyTest.testConcurrentLoggingAccuracyCheck(ConcurrentLoggingAccuracyTest.java:196)
at com.ibm.ws.fat.phasedjunit.PhasedTestCase.runTestPhase(PhasedTestCase.java:68)
at com.ibm.ws.fat.phasedjunit.TestPhaseRunner.runPhase(TestPhaseRunner.java:179)
at com.ibm.ws.fat.phasedjunit.TestPhaseRunner.protect(TestPhaseRunner.java:118)
at com.ibm.ws.fat.phasedjunit.TestPhaseRunner.runProtected(TestPhaseRunner.java:91)
at com.ibm.ws.fat.phasedjunit.PhasedTestCase.run(PhasedTestCase.java:49)
at junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)
at com.ibm.ws.fat.phasedjunit.PhasedTestSetup.runTestPhase(PhasedTestSetup.java:59)
at com.ibm.ws.fat.phasedjunit.TestPhaseRunner.runPhase(TestPhaseRunner.java:179)
at com.ibm.ws.fat.phasedjunit.TestPhaseRunner.protect(TestPhaseRunner.java:118)
at com.ibm.ws.fat.phasedjunit.TestPhaseRunner.runProtected(TestPhaseRunner.java:91)
at com.ibm.ws.fat.VerboseTestSetup.run(VerboseTestSetup.java:59)
```

**Comment by fmhwong** [comment]
@pgunapal This occurred once on Oct 13 only.  Do you want to investigate or close it?

**Comment by pgunapal** [comment]
Yes, I have been monitoring it, and it looks like it is intermittent issue, and has not occurred in the latest builds. I will close it.
