### ISSUE TITLE
SimpleDateFormat usage in JAX-RS Headers class causing ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by andymc12** [OpenLiberty/open-liberty#5439]
An internal customer ran into an ArrayIndexOutOfBoundsException that appears to be the result of multiple threads using the same SimpleDateFormat instance.  According to the JavaDocs, SimpleDateFormat instances are not thread safe and can result in these types of exceptions.  The stack trace reported was:
```
Caused by: java.lang.ArrayIndexOutOfBoundsException
at java.util.Calendar.getDisplayName(Calendar.java:2125)
at java.text.SimpleDateFormat.subFormat(SimpleDateFormat.java:1136)
at java.text.SimpleDateFormat.format(SimpleDateFormat.java:977)
at java.text.SimpleDateFormat.format(SimpleDateFormat.java:947)
at java.text.DateFormat.format(DateFormat.java:356)
at org.apache.cxf.transport.http.Headers.toHttpDate(Headers.java:591)
at org.apache.cxf.transport.http.Headers.headerObjectToString(Headers.java:559)
at org.apache.cxf.transport.http.Headers.copyToResponse(Headers.java:534)
at org.apache.cxf.transport.http.AbstractHTTPDestination.flushHeaders(AbstractHTTPDestination.java:669)
at org.apache.cxf.transport.http.AbstractHTTPDestination.flushHeaders(AbstractHTTPDestination.java:641)
at org.apache.cxf.transport.http.AbstractHTTPDestination$WrappedOutputStream.onFirstWrite(AbstractHTTPDestination.java:836)
at org.apache.cxf.io.AbstractWrappedOutputStream.write(AbstractWrappedOutputStream.java:47)
at org.codehaus.jackson.impl.Utf8Generator._flushBuffer(Utf8Generator.java:1754)
at org.codehaus.jackson.impl.Utf8Generator._writeBytes(Utf8Generator.java:1164)
at org.codehaus.jackson.impl.Utf8Generator._writeFieldName(Utf8Generator.java:457)
at org.codehaus.jackson.impl.Utf8Generator.writeFieldName(Utf8Generator.java:304)
at org.codehaus.jackson.map.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:444)
at org.codehaus.jackson.map.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:150)
... 124 more
```

The fix should be to create a new SimpleDateFormat when needed.

**Comment by lacompas** [comment]
Can ThreadLocal be leveraged?

**Comment by andymc12** [comment]
Hi @lacompas - sorry I missed your question.  Do you have a proposed example?

**Comment by lacompas** [comment]
Here is what I mean:

**Line 74:**
` 
   private static final ThreadLocal<SimpleDateFormat> dateFormat = new ThreadLocal<SimpleDateFormat>() {
    		@Override
    		protected SimpleDateFormat initialValue() {
    			return new SimpleDateFormat("EEE, dd MMM yyyy HH:mm:ss zzz", Locale.US);
    		}
    	};
`
**Line 87:**
`
    static {
        HTTP_HEADERS_SINGLE_VALUE_ONLY = new HashSet<String>();
        HTTP_HEADERS_SINGLE_VALUE_ONLY.add(HTTP_HEADERS_SETCOOKIE);
        HTTP_HEADERS_SINGLE_VALUE_ONLY.add(HTTP_HEADERS_LINK);
        USER_AGENT = initUserAgent();
        // Liberty Change for CXF Begin
        dateFormat.get().setTimeZone(TIME_ZONE_GMT);
        // Liberty Change for CXF End
    }
`
**Line 585:**
`
    public static SimpleDateFormat getHttpDateFormat() {
        // Liberty Change for CXF Begin
        return dateFormat;
        // Liberty Change for CXF End
    }

    public static String toHttpDate(Date date) {
        SimpleDateFormat format = getHttpDateFormat();
        return format.format(date);
    }
`

**Comment by andymc12** [comment]
Hey @lacompas I think this is a good idea.  I need to close out this issue for this release.  Can you open a new issue - something like "improve performance of SimpleDateFormat" and reference this issue?

Thanks for the suggestion!

**Comment by lacompas** [comment]
@andymc12 Thx, created issue #5847
