### ISSUE TITLE
OpenAPIUIBundlesUpdater throws exception when server started/stopped quickly

### ISSUE THREAD

**Issue by navidsh** [OpenLiberty/open-liberty#5511]
When start a server with `mpOpenAPI-1.0` and stop it quickly, `OpenAPIUIBundlesUpdater` throws `IllegalStateException` and FFDC would be generated.

This is reproducible on `18.0.0.3`. Haven't tried prior versions.

```java
Source = com.ibm.ws.microprofile.openapi.impl.OpenAPIUIBundlesUpdater
Stack Dump = java.lang.IllegalStateException: BundleContext is no longer valid
	at org.eclipse.osgi.internal.framework.BundleContextImpl.checkValid(BundleContextImpl.java:989)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.getServiceReferences(BundleContextImpl.java:534)
	at com.ibm.ws.microprofile.openapi.impl.OpenAPIUIBundlesUpdater.waitForBundlesToStart(OpenAPIUIBundlesUpdater.java:322)
	at com.ibm.ws.microprofile.openapi.impl.OpenAPIUIBundlesUpdater.updateResources(OpenAPIUIBundlesUpdater.java:66)
	at com.ibm.ws.microprofile.openapi.impl.CustomCSSWABUpdater.restoreDefaults(CustomCSSWABUpdater.java:46)
	at com.ibm.ws.microprofile.openapi.impl.CustomCSSProcessor$1.run(CustomCSSProcessor.java:234)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:522)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:812)
```

**Comment by Emily-Jiang** [comment]
@navidsh This issue is very old. Can you check whether it is valid if this still affects your usage? At the moment, the priority is to deal with customer raised issues first. Please reopen if you think this has a big impact and it is still happening.
