### ISSUE TITLE
[Java11] com.ibm.ws.microprofile.metrics_fat_tck: com.ibm.ws.microprofile.metrics.tck.launcher.MetricsTCKLauncher.launchTck

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#5536]
RTC 258571

```
junit.framework.AssertionFailedError: 2018-10-02-21:36:46:059 No TCK test JUnit result files were found in the results directory which suggests the TCK tests did not run - check build logs.
ResultsDir: /home/jazz_build/_KvHIIMZyEeiA6ZPkBDHUqw-EBC.PROD.WASRTC-BSA-000-00-00/jbe/build/dev/com.ibm.ws.microprofile.metrics_fat_tck/autoFVT/results/tck/surefire-reports
at componenttest.topology.utils.MvnUtils.findJunitResultFiles(MvnUtils.java:411)
at componenttest.topology.utils.MvnUtils.postProcessTestResults(MvnUtils.java:369)
at componenttest.topology.utils.MvnUtils.runTCKMvnCmd(MvnUtils.java:343)
at com.ibm.ws.microprofile.metrics.tck.launcher.MetricsTCKLauncher.launchTck(MetricsTCKLauncher.java:60)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:193)
at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:323)
at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:167)
```

The following was found in mvnOutput_TCK
```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] MicroProfile Metrics TCK Runner 1.0 TCK Module ..... FAILURE [08:02 min]
[INFO] MicroProfile Metrics TCK 1.0 Runner ................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 08:06 min
[INFO] Finished at: 2018-10-14T06:54:23Z
[INFO] Final Memory: 20M/35M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project tck.runner.tck: Could not resolve dependencies for project com.ibm.ws.microprofile.metrics:tck.runner.tck:jar:1.0-SNAPSHOT: Could not find artifact com.sun:tools:jar:1.6.0 at specified path /home/jazz_build/_XhJOEM9jEeio4_O0Fzon5g-EBC.PROD.WASRTC-9LP-000-00-00/jbe/jvms/openj9_jdk11_20180929-sdk/../lib/tools.jar -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

```

**Comment by fmhwong** [comment]
I hope this will be fixed by fixing `https://github.com/eclipse/microprofile-metrics/issues/289`
