### ISSUE TITLE
MessageSentException intermittently during flushBuffers

### ISSUE THREAD

**Issue by dettmoney** [OpenLiberty/open-liberty#5560]
I'm seeing this in at least 18.0.0.3 (and possibly before that) and 18.0.0.4 drivers. I'm doing performance testing for the new SPECjEnterprise web profile benchmark. I don't see any failed requests, but when I see the exception at the start of my run, it seems to happen for every forward. For example, in my long running test, I have 4 liberty servers with this app installed. Currently, I see the exception on two of my servers, and each one has over 700k instances.  Here's the stack from FFDC:

Exception = com.ibm.wsspi.genericbnf.exception.MessageSentException
Source = com.ibm.wsspi.http.ee7.HttpOutputStreamEE7
probeid = flushBuffers
Stack Dump = com.ibm.wsspi.genericbnf.exception.MessageSentException: Message already sent
        at com.ibm.ws.http.channel.internal.inbound.HttpInboundServiceContextImpl.sendResponseBody(HttpInboundServiceContextImpl.java:773)
        at com.ibm.ws.http.channel.internal.outbound.HttpOutputStreamImpl.flushBuffers(HttpOutputStreamImpl.java:514)
        at com.ibm.ws.http.channel.internal.outbound.HttpOutputStreamImpl.flush(HttpOutputStreamImpl.java:618)
        at com.ibm.wsspi.http.ee7.HttpOutputStreamEE7.flush(HttpOutputStreamEE7.java:299)
        at com.ibm.ws.http.channel.internal.outbound.HttpOutputStreamImpl.flush(HttpOutputStreamImpl.java:629)
        at com.ibm.ws.webcontainer.osgi.response.WCOutputStream.flush(WCOutputStream.java:242)
        at com.ibm.ws.webcontainer.srt.SRTOutputStream.flush(SRTOutputStream.java:72)
        at java.base/sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:318)
        at java.base/sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:153)
        at java.base/java.io.OutputStreamWriter.flush(OutputStreamWriter.java:254)
        at com.ibm.wsspi.webcontainer.util.BufferedWriter.writeOut(BufferedWriter.java:696)
        at com.ibm.wsspi.webcontainer.util.BufferedWriter.flushChars(BufferedWriter.java:518)
        at com.ibm.wsspi.webcontainer.util.BufferedWriter.flush(BufferedWriter.java:490)
        at java.base/java.io.PrintWriter.flush(PrintWriter.java:396)
        at com.ibm.ws.webcontainer.srt.SRTServletResponse.closeResponseOutput(SRTServletResponse.java:495)
        at com.ibm.ws.webcontainer.srt.SRTServletResponse.closeResponseOutput(SRTServletResponse.java:442)
        at com.ibm.ws.webcontainer.webapp.WebAppRequestDispatcher.dispatch(WebAppRequestDispatcher.java:1537)
        at com.ibm.ws.webcontainer.webapp.WebAppRequestDispatcher.forward(WebAppRequestDispatcher.java:171)
        at com.ibm.ws.webcontainer.extension.DefaultExtensionProcessor.handleRequest(DefaultExtensionProcessor.java:790)....

I will attach traces from a run where it fails and passes so you can compare. 
[trace4NoFlushError.zip](https://github.com/OpenLiberty/open-liberty/files/2535411/trace4NoFlushError.zip)
[trace5FlushError.zip](https://github.com/OpenLiberty/open-liberty/files/2535412/trace5FlushError.zip)

**Comment by dettmoney** [comment]
I'm using webProfile-8.0 in the server.xml, running on the 1020-2100 18.0.0.4 build for the traces
