### ISSUE TITLE
Warning with full exception stack traces shown in console.log and messages.log 

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/open-liberty#5708]
Implemented a REST API which may throw BadRequestException

When run it and expect the exception, a warning with full exception stack traces shown in console.log and [messages.log](https://github.com/OpenLiberty/open-liberty/files/2567708/messages.log)

EventResource is the class to provide rest api and it throws BadRequestException

[09/11/18 11:44:56:494 EST] 000009d4 xf.rt.frontend.jaxrs.3.2:1.0.22.cl180320180905-2337(id=143)] W javax.ws.rs.BadRequestException: Event already exists!
    at io.openliberty.guides.resources.EventResource.addNewEvent(EventResource.java:57)
    at io.openliberty.guides.resources.EventResource$Proxy$_$$_WeldSubclass.addNewEvent$$super(Unknown Source)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)

**Comment by gkwan-ibm** [comment]
close
- didn't see the problem for a while
