### ISSUE TITLE
[Java11] Test Failure (20181111-0324): com.ibm.ws.microprofile.metrics.monitor_fat.MetricsMonitorTest.testEnableDisableFeatures

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#5757]
RTC 259149
```
java.lang.Exception: 2018-11-11-08:47:01:096 Errors/warnings were found in server MetricsMonitorServer logs:
<br>[11/11/18, 8:42:40:539 UTC] 00000061 com.ibm.wsspi.injectionengine.MethodMap                      W CWNEN0049W: Resource annotations on the methods of the com.ibm.ws.microprofile.metrics.monitor_fat.jaxws.client.SimpleStubClientServlet class will be ignored. The annotations could not be obtained because of the exception : java.lang.NoClassDefFoundError: javax.xml.ws.BindingProvider
at componenttest.topology.impl.LibertyServer.checkLogsForErrorsAndWarnings(LibertyServer.java:2359)
at componenttest.topology.impl.LibertyServer.stopServer(LibertyServer.java:2235)
at componenttest.topology.impl.LibertyServer.stopServer(LibertyServer.java:2080)
at componenttest.topology.impl.LibertyServer.stopServer(LibertyServer.java:2055)
at com.ibm.ws.microprofile.metrics.monitor_fat.MetricsMonitorTest.tearDown(MetricsMonitorTest.java:86)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:193)
at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:323)
at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:167)
```

**Comment by aguibert** [comment]
this one should be a straightforward fix. The JAX-WS API is no longer provided from the JDK in Java 11, and it looks like the test app has a ref to JAX-WS API but there is no jaxws-2.2 feature enabled in server.xml.

To fix this, simply enable the `jaxws-2.2` feature in server.xml, or remove jax-ws reference in the test app.

**Comment by jhanders34** [comment]
@Erikkre I assume your pull request is a temporary change until the changes that @aguibert suggested are completed?

**Comment by Erikkre** [comment]
Merged and closed, will work on the few leftover timeout and fileNotFound defects separately.
