### ISSUE TITLE
ConcurrentModificationException happens when a web application receives a large number of requests immediately after it starts.

### ISSUE THREAD

**Issue by pmd1nh** [OpenLiberty/open-liberty#5862]
Immediately after application is started, a large number of concurrent requests to the application can randomly get the java.util.ConcurrentModificationException.  Example of the stack for this issue:

Caused by: java.util.ConcurrentModificationException
at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:912)
at java.util.ArrayList$Itr.next(ArrayList.java:862)
at com.ibm.ws.webcontainer.util.MetaInfResourcesFileUtils.<init>(MetaInfResourcesFileUtils.java:81)
at com.ibm.ws.webcontainer.util.DocumentRootUtils.getMetaInfRes(DocumentRootUtils.java:492)
at com.ibm.ws.webcontainer.util.DocumentRootUtils.handleDocumentRoots(DocumentRootUtils.java:204)
at com.ibm.ws.webcontainer.util.DocumentRootUtils.handleDocumentRoots(DocumentRootUtils.java:171)
at com.ibm.ws.webcontainer.osgi.webapp.WebApp.getResourceAsStream(WebApp.java:544)
at com.ibm.wsspi.webcontainer.facade.ServletContextFacade.getResourceAsStream(ServletContextFacade.java:158)

**Comment by pmd1nh** [comment]
TS001335458

**Comment by pmd1nh** [comment]
PH05787
