### ISSUE TITLE
ManagedObject calls getBean on non-contextual beans

### ISSUE THREAD

**Issue by benjamin-confino** [OpenLiberty/open-liberty#5883]
The following stack may result in rare circumstances. 

Caused by: com.ibm.ws.managedobject.ManagedObjectException: Managed Class {org.springframework.web.context.ContextLoaderListener} does not match Bean Class {com.travelers.bi.scbp.trvpas.pd.web.SpringContextLoaderListener}
at com.ibm.ws.cdi.impl.managedobject.AbstractManagedObjectFactory.getBean(AbstractManagedObjectFactory.java:135)
at com.ibm.ws.cdi.impl.managedobject.AbstractManagedObjectFactory.getBeanScope(AbstractManagedObjectFactory.java:144)
at com.ibm.ws.cdi.impl.managedobject.AbstractManagedObjectFactory.createManagedObject(AbstractManagedObjectFactory.java:269)
at com.ibm.ws.cdi.impl.managedobject.AbstractManagedObjectFactory.createManagedObject(AbstractManagedObjectFactory.java:247)
at com.ibm.ws.cdi.impl.managedobject.AbstractManagedObjectFactory.createManagedObject(AbstractManagedObjectFactory.java:254)
at com.ibm.ws.cdi.impl.managedobject.CDIManagedObjectFactoryImpl.createManagedObject(CDIManagedObjectFactoryImpl.java:60)
at com.ibm.ws.webcontainer.osgi.webapp.WebApp.inject(WebApp.java:1260)

**Comment by benjamin-confino** [comment]
Resolved by #5884
