### ISSUE TITLE
JSF 2.2 and 2.3 may need to check isCommitted in certain situations

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#5920]
We can see with some applications the following warning is coming from MyFaces:

[WARNING ] SESN0066E: The response is already committed to the client. The session cookie cannot be set.
[WARNING ] SRVE8114W: WARNING: Cannot set session cookie. Response already committed.

And when I dump a stack I see myfaces at the top of it. 

19:58:17.868 0x2c10a00       j9trc_aux.1          - [1] com.ibm.ws.webcontainer.srt.SRTServletResponse.addCookie (SRTServletResponse.java:908)
19:58:17.868 0x2c10a00       j9trc_aux.1          - [2] org.apache.myfaces.shared.context.flash.FlashImpl._saveRenderFlashMapTokenForNextRequest (FlashImpl.java:777)
19:58:17.868 0x2c10a00       j9trc_aux.1          - [3] org.apache.myfaces.shared.context.flash.FlashImpl._manageFlashMapTokens (FlashImpl.java:891)
19:58:17.868 0x2c10a00       j9trc_aux.1          - [4] org.apache.myfaces.shared.context.flash.FlashImpl.doPrePhaseActions (FlashImpl.java:227)
19:58:17.868 0x2c10a00       j9trc_aux.1          - [5] org.apache.myfaces.lifecycle.LifecycleImpl.executePhase (LifecycleImpl.java:179)
19:58:17.868 0x2c10a00       j9trc_aux.1          - [6] org.apache.myfaces.lifecycle.LifecycleImpl.execute (LifecycleImpl.java:143)
19:58:17.868 0x2c10a00       j9trc_aux.1          - [7] javax.faces.webapp.FacesServlet.service (FacesServlet.java:198)

**Comment by ebreijo** [comment]
The reported stack in this issue is not the correct one that generates the "[WARNING ] SRVE8114W: WARNING: Cannot set session cookie. Response already committed." message. 

The following stack is actually the correct one.
[1/30/19 10:26:43:996 EST] 0000002f com.ibm.ws.session.WASSessionCore                            W SESN0066E: The response is already committed to the client. The session cookie cannot be set.
[1/30/19 10:26:43:996 EST] 0000002f SystemErr                                                    R java.lang.Exception: Stack trace
[1/30/19 10:26:43:996 EST] 0000002f SystemErr                                                    R  at java.lang.Thread.dumpStack(Thread.java:1336)
[1/30/19 10:26:43:996 EST] 0000002f SystemErr                                                    R  at com.ibm.ws.webcontainer.srt.SRTServletResponse.addSessionCookie(SRTServletResponse.java:2287)
[1/30/19 10:26:43:996 EST] 0000002f SystemErr                                                    R  at com.ibm.ws.webcontainer.session.impl.SessionAffinityManagerImpl.setCookie(SessionAffinityManagerImpl.java:492)
[1/30/19 10:26:43:997 EST] 0000002f SystemErr                                                    R  at com.ibm.ws.session.SessionManager.adaptAndSetCookie(SessionManager.java:760)
[1/30/19 10:26:43:997 EST] 0000002f SystemErr                                                    R  at com.ibm.ws.session.SessionManager.createSession(SessionManager.java:728)
[1/30/19 10:26:43:997 EST] 0000002f SystemErr                                                    R  at com.ibm.ws.webcontainer.session.impl.HttpSessionContextImpl.getIHttpSession(HttpSessionContextImpl.java:532)
[1/30/19 10:26:43:997 EST] 0000002f SystemErr                                                    R  at com.ibm.ws.webcontainer.session.impl.HttpSessionContextImpl.getIHttpSession(HttpSessionContextImpl.java:661)
[1/30/19 10:26:43:997 EST] 0000002f SystemErr                                                    R  at com.ibm.ws.webcontainer.srt.SRTRequestContext.getSession(SRTRequestContext.java:103)
[1/30/19 10:26:43:997 EST] 0000002f SystemErr                                                    R  at com.ibm.ws.webcontainer.srt.SRTServletRequest.getSession(SRTServletRequest.java:2230)
[1/30/19 10:26:43:997 EST] 0000002f SystemErr                                                    R  at org.jboss.weld.servlet.SessionHolder.getSession(SessionHolder.java:61)
[1/30/19 10:26:43:997 EST] 0000002f SystemErr                                                    R  at org.jboss.weld.context.beanstore.http.LazySessionBeanStore.getSession(LazySessionBeanStore.java:84)
[1/30/19 10:26:43:998 EST] 0000002f SystemErr                                                    R  at org.jboss.weld.context.beanstore.http.AbstractSessionBeanStore.getLockStore(AbstractSessionBeanStore.java:120)
[1/30/19 10:26:43:998 EST] 0000002f SystemErr                                                    R  at org.jboss.weld.context.beanstore.AttributeBeanStore.lock(AttributeBeanStore.java:251)
[1/30/19 10:26:43:998 EST] 0000002f SystemErr                                                    R  at org.jboss.weld.context.AbstractContext.get(AbstractContext.java:90)
[1/30/19 10:26:43:998 EST] 0000002f SystemErr                                                    R  at org.jboss.weld.context.PassivatingContextWrapper$AbstractPassivatingContextWrapper.get(PassivatingContextWrapper.java:76)
[1/30/19 10:26:43:998 EST] 0000002f SystemErr                                                    R  at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get(ContextualInstanceStrategy.java:100)
[1/30/19 10:26:43:998 EST] 0000002f SystemErr                                                    R  at org.jboss.weld.bean.ContextualInstanceStrategy$CachingContextualInstanceStrategy.get(ContextualInstanceStrategy.java:177)
[1/30/19 10:26:43:998 EST] 0000002f SystemErr                                                    R  at org.jboss.weld.bean.ContextualInstance.get(ContextualInstance.java:50)
[1/30/19 10:26:43:999 EST] 0000002f SystemErr                                                    R  at org.jboss.weld.bean.proxy.ContextBeanInstance.getInstance(ContextBeanInstance.java:99)
[1/30/19 10:26:43:999 EST] 0000002f SystemErr                                                    R  at org.jboss.weld.bean.proxy.ProxyMethodHandler.getInstance(ProxyMethodHandler.java:125)
[1/30/19 10:26:43:999 EST] 0000002f SystemErr                                                    R  at org.apache.myfaces.cdi.view.ViewScopeBeanHolder$Proxy$_$$_WeldClientProxy.generateUniqueViewScopeId(Unknown Source)
[1/30/19 10:26:43:999 EST] 0000002f SystemErr                                                    R  at org.apache.myfaces.cdi.impl.CDIManagedBeanHandlerImpl.generateViewScopeId(CDIManagedBeanHandlerImpl.java:92)
[1/30/19 10:26:43:999 EST] 0000002f SystemErr                                                    R  at org.apache.myfaces.view.ViewScopeProxyMap.getWrapped(ViewScopeProxyMap.java:76)
[1/30/19 10:26:43:999 EST] 0000002f SystemErr                                                    R  at org.apache.myfaces.view.ViewScopeProxyMap.isEmpty(ViewScopeProxyMap.java:94)
[1/30/19 10:26:43:999 EST] 0000002f SystemErr                                                    R  at org.apache.myfaces.renderkit.ErrorPageWriter._writeVariables(ErrorPageWriter.java:792)
[1/30/19 10:26:44:000 EST] 0000002f SystemErr                                                    R  at org.apache.myfaces.renderkit.ErrorPageWriter._writeVariables(ErrorPageWriter.java:770)
[1/30/19 10:26:44:000 EST] 0000002f SystemErr                                                    R  at org.apache.myfaces.renderkit.ErrorPageWriter.debugHtml(ErrorPageWriter.java:357)
[1/30/19 10:26:44:000 EST] 0000002f SystemErr                                                    R  at org.apache.myfaces.renderkit.ErrorPageWriter.handle(ErrorPageWriter.java:471)
[1/30/19 10:26:44:000 EST] 0000002f SystemErr                                                    R  at org.apache.myfaces.context.MyFacesExceptionHandlerWrapperImpl.handle(MyFacesExceptionHandlerWrapperImpl.java:301)
[1/30/19 10:26:44:000 EST] 0000002f SystemErr                                                    R  at javax.faces.context.ExceptionHandlerWrapper.handle(ExceptionHandlerWrapper.java:61)
[1/30/19 10:26:44:000 EST] 0000002f SystemErr                                                    R  at org.apache.myfaces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:287)
[1/30/19 10:26:44:000 EST] 0000002f SystemErr                                                    R  at javax.faces.webapp.FacesServlet.service(FacesServlet.java:200)
[1/30/19 10:26:44:001 EST] 0000002f SystemErr                                                    R  at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1255)
[1/30/19 10:26:44:001 EST] 0000002f SystemErr                                                    R  at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:743)
...
[1/30/19 10:26:44:004 EST] 0000002f com.ibm.ws.webcontainer.srt                                  W SRVE8114W: WARNING: Cannot set session cookie. Response already committed.


If you look at the stack, this issue usually happens at the time of an error, where the MyFacesExceptionHandler is used, then when the ErrorPageWriter class calls to write the ViewScopeProxyMap variables, at this point, at the time of checking if the ViewScopeProxyMap is empty, the getWrapped() method is called which then calls the generateViewScopeId method of the ViewScopeProvider handler that is set at runtime which ends up calling getSession and setting the session cookie, resulting in the warning reported here. 

I don't think we need to worry about this SRVE8114W warning message as this only happens at the time of an error where the error page is generated. Maybe we could avoid the warning but I don't think it's worth it. As a result, I'm just closing this issue with no code change.
