### ISSUE TITLE
Test Failure (Liberty z/OS Platform Build - 20181203-0225): com.ibm.ws.microprofile.metrics.monitor_fat.MetricsMonitorTest.testEnableDisableFeatures

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#5937]
RTC 259568

```
testEnableDisableFeatures
java.io.FileNotFoundException: 2018-12-03-10:07:14:396 http://localhost:8010/testSessionApp/testSessionServlet
at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1902)
at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1504)
at com.ibm.ws.microprofile.metrics.monitor_fat.MetricsMonitorTest.getHttpServlet(MetricsMonitorTest.java:333)
at com.ibm.ws.microprofile.metrics.monitor_fat.MetricsMonitorTest.testEnableDisableFeatures(MetricsMonitorTest.java:202)
at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:193)
at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:323)
at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:167)
```

**Comment by AidanPolese** [comment]
I believe this error has been resolved in one of my previous fixes  
https://github.com/OpenLiberty/open-liberty/pull/6007/commits/974d8a5b5460c1d0ffd46e4e747163420844adb9

**Comment by AidanPolese** [comment]
from PR #6007
