### ISSUE TITLE
ConcurrentModificationException from ReferenceContext starting web application

### ISSUE THREAD

**Issue by tkburroughs** [OpenLiberty/open-liberty#5976]
Caused by: java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextNode(HashMap.java:1448)
    at java.util.HashMap$KeyIterator.next(HashMap.java:1472)
    at java.util.AbstractCollection.addAll(AbstractCollection.java:354)
    at java.util.HashSet.<init>(HashSet.java:130)
    at com.ibm.ws.injectionengine.ReferenceContextImpl.getProcessedInjectionClasses(ReferenceContextImpl.java:1080)
    at com.ibm.ws.cdi.impl.weld.injection.WebSphereInjectionServicesImpl.addReferenceContext(WebSphereInjectionServicesImpl.java:101)
        .....
    at com.ibm.ws.cdi.impl.weld.injection.WebSphereInjectionServicesImpl.aroundInject(WebSphereInjectionServicesImpl.java:316)
        .....
    at com.ibm.ws.cdi.impl.managedobject.CDIManagedObject.cdiInjection(CDIManagedObject.java:202)
        .....
    at com.ibm.wsspi.webcontainer.annotation.AnnotationHelper.inject(AnnotationHelper.java:106)
    at com.ibm.ws.jsf.cdi.WASCDIAnnotationInjectionProvider.inject(WASCDIAnnotationInjectionProvider.java:70)

**Comment by tkburroughs** [comment]
What's happening here is that one thread is running through processDynamicPrivileged while another is calling getProcessedInjectionClasses.  It doesn't look like anything in this area of code has changed recently - the window for this exception to occur is very small, so this probably will to occur very infrequently.  Also, it doesn't look like any functional issues were seen by the test, just the unexpected FFDC.

The obvious/naive fix for this would be to synchronize access to Set<Class<?>> ivProcessedInjectionClasses in com.ibm.ws.injectionengine.ReferenceContextImpl.
