### ISSUE TITLE
Test Failure (Liberty - Sun EBC - 20181210-0241): com.ibm.ws.logging.json.fat.ConsoleFormatTest.testBasicConsoleTraceFileNameStdout

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#6003]
RTC 259732

```
testBasicConsoleTraceFileNameStdout
junit.framework.AssertionFailedError: 2018-12-10-08:49:59:482 null
at com.ibm.ws.logging.json.fat.ConsoleFormatTest.testBasicConsoleTraceFileNameStdout(ConsoleFormatTest.java:99)
at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:193)
at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:314)
at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:167)
```

**Comment by fmhwong** [comment]
@kbaillie Please close the corresponding RTC defect.
