### ISSUE TITLE
NoClassDefFoundError: javax/activation/DataHandler

### ISSUE THREAD

**Issue by alexmulholland** [OpenLiberty/open-liberty#612]
When starting an application that uses javax/activation/DataHandler in a server with the apiDiscovery-1.0 feature configured, an exception occurs during startup:

[ERROR   ] CWWKE0701E: [com.ibm.ws.rest.api.discovery.APIProviderAggregator(218)] The setApiProvider method has thrown an exception Bundle:com.ibm.ws.rest.api.discovery(id=106) java.lang.NoClassDefFoundError: javax/activation/DataHandler

            at java.lang.Class.getDeclaredMethods0(Native Method)

            at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)

            at java.lang.Class.getDeclaredMethods(Class.java:1975)

            at com.fasterxml.jackson.databind.introspect.AnnotatedClass._addMemberMethods(AnnotatedClass.java:601)

            at [internal classes]

Caused by: java.lang.ClassNotFoundException: javax.activation.DataHandler cannot be found by com.ibm.websphere.appserver.api.jaxrs20_1.0.18.cl170320170927-1854

            at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:469)

            ... 1 more

 The application source was cut/pasted from this KC article: https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/twlp_jaxrs_multipart_formdata_from_html.html

This happens on liberty 17.0.0.3.  If we remove the apiDiscovery feature and just use jaxrs-2.0, the application starts successfully.

**Comment by andymc12** [comment]
@alexmulholland Could you provide the full stack trace?  Also, if possible could you provide your server logs (via Box, Dropbox, SameTime, etc.) and/or your server directory so that I could try to recreate the issue?  Thanks!

**Comment by WhiteCat22** [comment]
I was able to reproduce the issue and I'm taking a look.
