### ISSUE TITLE
NPE possible in TrOSGiLogForwarder.logged if LogEntry.getBundle is null

### ISSUE THREAD

**Issue by tjwatson** [OpenLiberty/open-liberty#6364]
The following NPE is possible if `LogEntry.getBundle()` returns null

```
1/30/19 6:47:43:009 UTC] 0000001f SystemErr                                                    R LogListener.logged threw a non-fatal unchecked exception as follows:
[1/30/19 6:47:43:009 UTC] 0000001f SystemErr                                                    R java.lang.NullPointerException
[1/30/19 6:47:43:009 UTC] 0000001f SystemErr                                                    R   at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:947)
[1/30/19 6:47:43:010 UTC] 0000001f SystemErr                                                    R   at com.ibm.ws.logging.internal.osgi.TrOSGiLogForwarder.getTraceComponent(TrOSGiLogForwarder.java:58)
[1/30/19 6:47:43:010 UTC] 0000001f SystemErr                                                    R   at com.ibm.ws.logging.internal.osgi.TrOSGiLogForwarder.logged(TrOSGiLogForwarder.java:99)
[1/30/19 6:47:43:010 UTC] 0000001f SystemErr                                                    R   at org.eclipse.osgi.internal.log.ExtendedLogReaderServiceFactory.safeLogged(ExtendedLogReaderServiceFactory.java:111)
[1/30/19 6:47:43:010 UTC] 0000001f SystemErr                                                    R   at org.eclipse.osgi.internal.log.ExtendedLogReaderServiceFactory.logPrivileged(ExtendedLogReaderServiceFactory.java:253)
[1/30/19 6:47:43:011 UTC] 0000001f SystemErr                                                    R   at org.eclipse.osgi.internal.log.ExtendedLogReaderServiceFactory.log(ExtendedLogReaderServiceFactory.java:225)
[1/30/19 6:47:43:011 UTC] 0000001f SystemErr                                                    R   at org.eclipse.osgi.internal.log.ExtendedLogServiceFactory.log(ExtendedLogServiceFactory.java:94)
[1/30/19 6:47:43:011 UTC] 0000001f SystemErr                                                    R   at org.eclipse.osgi.internal.log.LoggerImpl.log(LoggerImpl.java:80)
[1/30/19 6:47:43:011 UTC] 0000001f SystemErr                                                    R   at org.eclipse.osgi.internal.log.LogServiceManager.serviceChanged(LogServiceManager.java:149)
```

**Comment by tjwatson** [comment]
This has been fixed in master for a long time.
