### ISSUE TITLE
Building .tar.gz server package fails on Windows

### ISSUE THREAD

**Issue by gcharters** [OpenLiberty/open-liberty#6391]
When trying to build a .tar.gz on Windows using maven, I get the following error and it fails.  The identical build works find on Mac . Produced on 18.0.04 and 19.0.0.1

[INFO] CWWKM2001I: Invoke command is ["C:\open-cloud-native-intro\target\liberty\wlp\bin\server.bat", package, defaultServer, --archive=C:\open-cloud-native-intro\target\mpservice.tar.gz, --include=usr].
[INFO] Packaging server defaultServer.
[INFO] in Launcher, about to error.unknownException
[INFO] CWWKE0005E: The runtime environment could not be launched.
[INFO] CWWKE0018E: An exception occurred while launching the runtime environment: java.lang.RuntimeException: mode '-1' is too big ( > 2097151 ).
[INFO] java.lang.RuntimeException: mode '-1' is too big ( > 2097151 ).
[INFO]  at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.failForBigNumber(TarArchiveOutputStream.java:636)
[INFO]  at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.failForBigNumber(TarArchiveOutputStream.java:624)
[INFO]  at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.failForBigNumbers(TarArchiveOutputStream.java:616)
[INFO]  at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.putArchiveEntry(TarArchiveOutputStream.java:369)
[INFO]  at com.ibm.ws.kernel.boot.archive.internal.ZipArchive.processEntry(ZipArchive.java:124)
[INFO]  at com.ibm.ws.kernel.boot.archive.internal.ZipArchive.addDirEntry(ZipArchive.java:85)
[INFO]  at com.ibm.ws.kernel.boot.archive.DirEntryConfig.configure(DirEntryConfig.java:77)
[INFO]  at com.ibm.ws.kernel.boot.archive.internal.AbstractArchive.create(AbstractArchive.java:49)
[INFO]  at com.ibm.ws.kernel.boot.internal.commands.PackageProcessor.execute(PackageProcessor.java:228)
[INFO]  at com.ibm.ws.kernel.boot.internal.commands.PackageCommand.packageServerRuntime(PackageCommand.java:281)
[INFO]  at com.ibm.ws.kernel.boot.internal.commands.PackageCommand.doPackage(PackageCommand.java:119)
[INFO]  at com.ibm.ws.kernel.boot.Launcher.handleActions(Launcher.java:274)
[INFO]  at com.ibm.ws.kernel.boot.Launcher.createPlatform(Launcher.java:117)
[INFO]  at com.ibm.ws.kernel.boot.cmdline.EnvCheck.main(EnvCheck.java:59)
[INFO]  at com.ibm.ws.kernel.boot.cmdline.EnvCheck.main(EnvCheck.java:35)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  5.055 s
[INFO] Finished at: 2019-02-04T15:21:27+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal net.wasdev.wlp.maven.plugins:liberty-maven-plugin:2.1.2:package-server (package-server) on project mpservice: CWWKM2002E: Failed to invoke ["C:\open-cloud-native-intro\target\liberty\wlp\bin\server.bat", package, defaultServer, --archive=C:\open-cloud-native-intro\target\mpservice.tar.gz, --include=usr]. RC= 25 but expected=[0]. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

The Java and maven versions I'm using are

C:\Users\User>java -version
openjdk version "1.8.0_192"
OpenJDK Runtime Environment (build 1.8.0_192-201811210433-b12)
Eclipse OpenJ9 VM (build master-61a34f6be, JRE 1.8.0 Windows 10 amd64-64-Bit Compressed References 20181120_164 (JIT enabled, AOT enabled)
OpenJ9   - 61a34f6be
OMR      - 1b8bfbae
JCL      - 8ef74afc70 based on jdk8u192-b12)

C:\Users\User>mvn -version
Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-24T20:41:47+02:00)
Maven home: C:\QuickLabs\Windows\apache-maven-3.6.0-bin\apache-maven-3.6.0\bin\..
Java version: 1.8.0_192, vendor: Eclipse OpenJ9, runtime: C:\QuickLabs\Windows\OpenJDK8U-jdk_x64_windows_openj9_8u192b12_openj9-0.11.0\jdk8u192-b12\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Comment by benjamin-confino** [comment]
Sorry, that was a typo

**Comment by gcharters** [comment]
Hi @njr-11 - is this issue being resolved as part of #6396 ?
