### ISSUE TITLE
Test Failure: io.astefanutti.metrics.cdi.se.ApplicationScopedTimedMethodBeanTest.io.astefanutti.metrics.cdi.se.ApplicationScopedTimedMethodBeanTest

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#6401]
RTC 260680
RTC 262549

```
io.astefanutti.metrics.cdi.se.ApplicationScopedTimedMethodBeanTest
org.jboss.arquillian.container.spi.client.container.DeploymentException: Exception while deploying application.
at io.openliberty.arquillian.managed.WLPManagedContainer.deploy(WLPManagedContainer.java:503)
at org.jboss.arquillian.container.impl.client.container.ContainerDeployController$3.call(ContainerDeployController.java:161)
at org.jboss.arquillian.container.impl.client.container.ContainerDeployController$3.call(ContainerDeployController.java:128)
at org.jboss.arquillian.container.impl.client.container.ContainerDeployController.executeOperation(ContainerDeployController.java:271)
at org.jboss.arquillian.container.impl.client.container.ContainerDeployController.deploy(ContainerDeployController.java:127)
at jdk.internal.reflect.GeneratedMethodAccessor136.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:96)
at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:103)
at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:85)
at org.jboss.arquillian.container.impl.client.container.DeploymentExceptionHandler.verifyExpectedExceptionDuringDeploy(DeploymentExceptionHandler.java:50)
at jdk.internal.reflect.GeneratedMethodAccessor135.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:96)
at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:92)
at org.jboss.arquillian.container.impl.client.ContainerDeploymentContextHandler.createContainerContext(ContainerDeploymentContextHandler.java:57)
at jdk.internal.reflect.GeneratedMethodAccessor128.invoke(Un
```

**Comment by Erikkre** [comment]
We do not support Java 11 hotspot for Liberty. Closed as not reproducible.

**Comment by fmhwong** [comment]
RTC defect was reopened as it occurred again.

Can you enable the trace in https://github.com/OpenLiberty/liberty-arquillian/blob/arquillian-parent-liberty-1.0.3/liberty-managed/src/main/java/io/openliberty/arquillian/managed/WLPManagedContainer.java and check it into the build?

**Comment by fmhwong** [comment]
@Erikkre There was a new occurrence.  Please check the trace.

**Comment by fmhwong** [comment]
It occurs again. See RTC 260680.

**Comment by fmhwong** [comment]
@Erikkre Your fix doesn't seem to fix the problem.  See RTC 262549

**Comment by fmhwong** [comment]
See https://github.ibm.com/was-liberty/WS-CD-Open/issues/17141 for related Windows file locking problem.

**Comment by Erikkre** [comment]
Waiting on PR https://github.com/OpenLiberty/open-liberty/pull/8202 for a potential fix.

**Comment by fmhwong** [comment]
This did not re-occurred in last 2 weeks
