### ISSUE TITLE
Test Failure (Liberty - Sun EBC - 20181210-0241): com.ibm.ws.microprofile.metrics.monitor_fat.MetricsMonitorTest.testDisableMpMetricsFeature

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#6402]
RTC 259731

```
testDisableMpMetricsFeature
java.io.FileNotFoundException: 2018-12-10-10:07:44:814 https://localhost:8020/metrics
at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1836)
at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
at com.ibm.ws.microprofile.metrics.monitor_fat.MetricsMonitorTest.getHttpsServlet(MetricsMonitorTest.java:368)
at com.ibm.ws.microprofile.metrics.monitor_fat.MetricsMonitorTest.testDisableMpMetricsFeature(MetricsMonitorTest.java:275)
at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:193)
at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:314)
at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:167)
```

**Comment by fmhwong** [comment]
This failed on Sun JDK only.  Unlink IBM JDK, Sun JDK does not guarantee the test sequence which some poorly written test will fail when they are executed out of sequence.
