### ISSUE TITLE
[Java11] Test Failure (Liberty Full Fat - EBC - no personal builds please - 20180915-0122): com.ibm.ws.microprofile.metrics11.tck.launcher.MetricsTCKLauncher.launchTck

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#6412]
RTC 258173

```
junit.framework.AssertionFailedError: 2018-09-15-09:46:40:451 No TCK test JUnit result files were found in the results directory which suggests the TCK tests did not run - check build logs.
ResultsDir: /home/jazz_build/_RWd1kLibEeixPpRs8MC_mg-EBC.PROD.WASRTC-BSA-000-00-00/jbe/build/dev/com.ibm.ws.microprofile.metrics.1.1_fat_tck/autoFVT/results/tck/surefire-reports
at componenttest.topology.utils.MvnUtils.findJunitResultFiles(MvnUtils.java:392)
at componenttest.topology.utils.MvnUtils.postProcessTestResults(MvnUtils.java:354)
at componenttest.topology.utils.MvnUtils.runTCKMvnCmd(MvnUtils.java:328)
at com.ibm.ws.microprofile.metrics11.tck.launcher.MetricsTCKLauncher.launchTck(MetricsTCKLauncher.java:60)
at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:193)
at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:323)
at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:167)
```

**Comment by fmhwong** [comment]
It didn't re-occurred in last 4 weeks.
