### ISSUE TITLE
[Java 11] localConnector-1.0 now requires JDK instead of JRE

### ISSUE THREAD

**Issue by aguibert** [OpenLiberty/open-liberty#6533]
In Liberty we have the `localConnector-1.0` feature which depends on the attach API. Between Java 8 and 11, the attach agent moved from the JRE to the JDK, meaning that this feature can no longer be used on JRE 11 environments.

If you attempt to start a server with the `localConnector-1.0` feature using JRE 11, we get the following FFDC:
```
Stack Dump = java.lang.ClassNotFoundException: jdk.internal.agent.Agent
	at java.base/java.lang.Class.forNameImpl(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
	at com.ibm.ws.jmx.connector.local.LocalConnectorActivator$LocalConnectorHelper$1.run(LocalConnectorActivator.java:71)
	at com.ibm.ws.jmx.connector.local.LocalConnectorActivator$LocalConnectorHelper$1.run(LocalConnectorActivator.java:55)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at com.ibm.ws.jmx.connector.local.LocalConnectorActivator$LocalConnectorHelper.initConnectorAddress(LocalConnectorActivator.java:55)
	at com.ibm.ws.jmx.connector.local.LocalConnectorActivator$LocalConnectorHelper.<clinit>(LocalConnectorActivator.java:45)
	at com.ibm.ws.jmx.connector.local.LocalConnectorActivator.createJmxAddressResource(LocalConnectorActivator.java:181)
	at com.ibm.ws.jmx.connector.local.LocalConnectorActivator.createJMXWorkAreaResource(LocalConnectorActivator.java:173)
	at com.ibm.ws.jmx.connector.local.LocalConnectorActivator.setLocationService(LocalConnectorActivator.java:149)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

**Comment by aguibert** [comment]
originally reported by @frowe

**Comment by tevans78** [comment]
Investigate to see if the localConnector-1.0 feature can be re-worked, to avoid use of the internal class.

Talk to Kevin to see if the SOE should/could include a JRE as well (one platform).

**Comment by marlowa** [comment]
According to this StackOverflow article https://stackoverflow.com/questions/53111921/how-to-get-java-11-run-time-environment-working-since-there-is-no-more-jre-11-fo there is no longer a JRE for java as of java 11. See also https://stackoverflow.com/a/53112096/642706.

**Comment by frowe** [comment]
That's not true, have a look at the final answer in that thread (from matson kepson), you can download either a JRE or a JDK from adoptopenjdk, for example: https://adoptopenjdk.net/releases.html?variant=openjdk11&jvmVariant=openj9#x64_mac

**Comment by tevans78** [comment]
LibertyServer.java in fattest.simplicity has code that looks for the `jar` command. So at the moment no FAT tests can run against a JRE. Ought to be possible to remove that dependency if we wanted.

**Comment by frowe** [comment]
With java 11 jdk, and no localConnector-1.0 feature
ws-server.jar <serverName> appears in the Local Process list of the JConsole connect UI
and a connection succeeds
With java 11 jre, and no localConnector-1.0 feature
ws-server.jar <serverName> appears in the Local Process list of the JConsole connect UI
but connection fails.

**Comment by aguibert** [comment]
to qualify what @frowe mentioned above, a Java 11 JRE does not even contain `$JAVA_HOME/bin/jconsole`, so he must have used a different JDK to try and connect to the Java 11 JRE VM. I believe the localConnector-1.0 feature only assists with self-attach (i.e. connecting with JMX to the same JVM).

Given the above outcome, we should update the localConnector-1.0 feature to emit an ERROR message for JDK 11+ indicating that the `jdk.attach` module must be present in order to use the localConnector-1.0 feature, if it is not present.

CC @NottyCode

**Comment by aguibert** [comment]
Will do further investigation under issue #6989 to see if there is any way of allowing localConnector-1.0 to work on a JRE set of modules.
