### ISSUE TITLE
Fix test bug in com.ibm.ws.kernel.boot.ServerStartAsServiceTest.testWinServiceAppAccess

### ISSUE THREAD

**Issue by hlhoots** [OpenLiberty/open-liberty#6745]
java.lang.RuntimeException: 2017-03-04-02:55:51:067 Error getting server
at componenttest.topology.impl.LibertyServerFactory.getLibertyServer(LibertyServerFactory.java:215)
at componenttest.topology.impl.LibertyServerFactory.getLibertyServer(LibertyServerFactory.java:101)
at com.ibm.ws.kernel.boot.ServerStartAsServiceTest.testWinServiceAppAccess(ServerStartAsServiceTest.java:85)
at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:197)
at com.ibm.ws.kernel.boot.OnlyRunOnWinRule$1.evaluate(OnlyRunOnWinRule.java:34)
at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:314)
at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:171)

**Comment by hlhoots** [comment]
The Runtime exception is a result of: 
componenttest.exception.TopologyException: Unable to delete pre-existing server directory: C:/jazz-build-engines/jazz112.hursley.ibm.com/EBC.PROD.WASRTC/build/dev/image/output/wlp/usr/servers/ServerStartAsServiceTest
	at componenttest.topology.impl.LibertyServer.setup(LibertyServer.java:630)
	at componenttest.topology.impl.LibertyServer.<init>(LibertyServer.java:571)
	at componenttest.topology.impl.LibertyServerFactory.getLibertyServer(LibertyServerFactory.java:160)
	at componenttest.topology.impl.LibertyServerFactory.getLibertyServer(LibertyServerFactory.java:91)
	at com.ibm.ws.kernel.boot.ServerStartAsServiceTest.testWinServiceAppAccess(ServerStartAsServiceTest.java:84)

Differences in the output.txt results logs for the success and fail case:

Failing case:

[03/01/2019 05:51:34:320 GMT] 001 LibertyServer                  stopServer                     I <<< STOPPING SERVER: ServerStartAsServiceTest
[03/01/2019 05:51:40:728 GMT] 001 LibertyServer                  stopServer                     I Stop Server Response: 

Success case:
[02/14/2019 10:52:26:581 GMT] 001 LibertyServer                  stopServer                     I <<< STOPPING SERVER: com.ibm.ws.kernel.bootstrap.fat
[02/14/2019 10:52:27:909 GMT] 001 LibertyServer                  stopServer                     I Stop Server Response: Stopping server com.ibm.ws.kernel.bootstrap.fat.
Server com.ibm.ws.kernel.bootstrap.fat stopped.

Seems to just be that the server has not stopped successfully yet.  Adding code to ensure the server is stopped prior to running the next test case so that the prior log files can be deleted

**Comment by hlhoots** [comment]
Closing...
