### ISSUE TITLE
[Java11] Test Failure: com.ibm.ws.microprofile.metrics11.tck.launcher.MetricsTCKLauncher.launchTck

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#6780]
RTC 261073

```
launchTck
junit.framework.AssertionFailedError: 2019-02-20-08:05:30:055 No TCK test JUnit result files were found in the results directory which suggests the TCK tests did not run - check build logs.
ResultsDir: /home/jazz_build/_3eKQ4DTHEemUn-nbjMTX6w-EBC.PROD.WASRTC-DEV-000-00-00/jbe/build/dev/com.ibm.ws.microprofile.metrics.1.1_fat_tck/autoFVT/results/tck/surefire-reports
at componenttest.topology.utils.MvnUtils.findJunitResultFiles(MvnUtils.java:411)
at componenttest.topology.utils.MvnUtils.postProcessTestResults(MvnUtils.java:369)
at componenttest.topology.utils.MvnUtils.runTCKMvnCmd(MvnUtils.java:343)
at com.ibm.ws.microprofile.metrics11.tck.launcher.MetricsTCKLauncher.launchTck(MetricsTCKLauncher.java:60)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:193)
at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:314)
at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:167)

Occurred on the following Platforms:
Liberty - Java 11 OpenJ9 EBC - 20190220-0207
```

**Comment by fmhwong** [comment]
It didn't re-occurred in last 4 weeks.
