### ISSUE TITLE
z/OS test cases: Limit the hazelcast thread pool size

### ISSUE THREAD

**Issue by zhang-ca** [OpenLiberty/open-liberty#6823]
On z/OS, every thread Hazelcast create requires a task, and that task requires storage from a pool of storage which is limited. When limit is reached it can cause java.lang.OutOfMemoryError: 

[2/26/19 3:41:09:177 GMT] 000002ef id=00000000 SystemErr                                                    R java.lang.OutOfMemoryError: Failed to create a thread: retVal -1073741830, errno 132 (0x84), errno2 -1055784930 (0xffffffffc112001e)
	at java.lang.Thread.startImpl(Native Method)
	at java.lang.Thread.start(Thread.java:982)
	at com.hazelcast.spi.impl.operationexecutor.slowoperationdetector.SlowOperationDetector.start(SlowOperationDetector.java:107)
	at com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl.start(OperationServiceImpl.java:440)
	at com.hazelcast.spi.impl.NodeEngineImpl.start(NodeEngineImpl.java:230)
	at com.hazelcast.instance.Node.start(Node.java:366)
	at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:133)
	at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:195)
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:174)
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:124)
	at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:92)
	at com.hazelcast.cache.impl.HazelcastServerCachingProvider.getDefaultInstance(HazelcastServerCachingProvider.java:131)
	at com.hazelcast.cache.impl.HazelcastServerCachingProvider.getOrCreateInstance(HazelcastServerCachingProvider.java:122)
	at com.hazelcast.cache.impl.AbstractHazelcastCachingProvider.createHazelcastCacheManager(AbstractHazelcastCachingProvider.java:224)
	at com.hazelcast.cache.impl.AbstractHazelcastCachingProvider.getCacheManager(AbstractHazelcastCachingProvider.java:108)
	at com.hazelcast.cache.impl.AbstractHazelcastCachingProvider.getCacheManager(AbstractHazelcastCachingProvider.java:140)
	at com.hazelcast.cache.HazelcastCachingProvider.getCacheManager(HazelcastCachingProvider.java:174)
	at javax.cache.Caching.getCache(Caching.java:289)

**Comment by zhang-ca** [comment]
Change to 5 threads in the pool-size for z/OS test cases is bit small, need to increase it to 12 threads.
