### ISSUE TITLE
Test Failure: com.ibm.ws.request.timing.monitor.fat.RequestTimingMbeanTest.testActiveRequestsToServer

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#6837]
RTC 261300

```
testActiveRequestsToServer
java.lang.Throwable: 2019-03-06-04:30:09:073 There were 2 errors:
  java.lang.AssertionError(Incorrect active requests to server found. Expected: 1 Found: 4)
  java.lang.AssertionError(Incorrect total requests to server found. Expected: 23 Found: 26)
at componenttest.custom.junit.runner.FATRunner.newThrowableWithTimeStamp(FATRunner.java:287)
at componenttest.custom.junit.runner.FATRunner.access$600(FATRunner.java:65)
at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:259)
at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:334)
at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:168)
  java.lang.AssertionError(Incorrect active requests to server found. Expected: 1 Found: 4)
  java.lang.AssertionError(Incorrect total requests to server found. Expected: 23 Found: 26)
at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:194)
```

**Comment by fmhwong** [comment]
This is in WL.  Closing
