### ISSUE TITLE
configuring a only usr feature which depends on no other features causes Liberty to fail to restart

### ISSUE THREAD

**Issue by tjwatson** [OpenLiberty/open-liberty#6872]
If a usr feature is configured in the server.xml:
```
<featureManager>
    <feature>usr:sampleFeature-1.0</feature>
</featureManager>
```
And the `sampleFeature-1.0` has no dependencies on other liberty features the server will start successfully the first time (or when using --clean).  It will fail with the following FFDC if started from a cached state:

```
Stack Dump = java.lang.NullPointerException
	at com.ibm.ws.kernel.service.location.internal.Activator.start(Activator.java:53)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:814)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:807)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:764)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1005)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:357)
	at org.eclipse.osgi.container.Module.doStart(Module.java:589)
	at org.eclipse.osgi.container.Module.start(Module.java:457)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1784)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1764)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1726)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1657)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:233)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:343)
```

**Comment by tjwatson** [comment]
The issue is the feature manager is not setting up the kernel region properly which ends up completely busting the kernel bundles.  The fix is a one line fix.  I will open a PR

**Comment by tjwatson** [comment]
fixed in master.
