### ISSUE TITLE
NullPointerException in concurrent.persistent.internal.InvokerTask

### ISSUE THREAD

**Issue by olendvcook** [OpenLiberty/open-liberty#6914]
There's an EJB Persistent Timer test `PersistentTimerSupportLostTest.testPersistentTimerSupportLost()` that first creates persistent timers and then removes the `ejbPersistentTimer-3.2` feature and makes sure creation fails, it then re-adds the feature and makes sure creation succeeds again. The test is running into a timing problem where a timer timeouts as the feature is going down and InvokerTask is in the middle of running it. Naturally, we don't expect the timer to keep working, but it's throwing an ugly NPE and I thought maybe there could be a small update to InvokerTask to make the exception nicer or gracefully exit out of the run method.

FFDC:
```
Exception = java.lang.NullPointerException
Source = com.ibm.ws.concurrent.persistent.internal.InvokerTask
probeid = 578
Stack Dump = java.lang.NullPointerException
	at com.ibm.ws.concurrent.persistent.internal.InvokerTask.run(InvokerTask.java:566)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:522)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:239)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1153)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:785)
```

logs on RTC259400 if needed (unfortunately only EJB trace) and it is causing a slightly frequent BuildBreak.

**Comment by njr-11** [comment]
This seems like a reasonable error path to avoid.  While there are many possible places where runtime errors could occur because the persistent executor gets deactivated while other processing is ongoing and there is no way of handling all of them, this particular place does seem more likely to see a failure like this due to it being right after the execution of a task.
