### ISSUE TITLE
Login errors are logging stack traces twice 

### ISSUE THREAD

**Issue by jvanhill** [OpenLiberty/open-liberty#6930]
I was testing app-passwords and forgot to enable passwordGrantRequiresAppPassword=true in the provider.  When I passed the app-token to the token endpoint, I found this in the log:

```
[3/15/19 10:26:35:966 CDT] 00000060 SystemOut                                                    O client.jsp: Start Test Case:  null===============================
[3/15/19 10:26:38:124 CDT] 00000044 com.ibm.ws.security.wim.registry.util.LoginBridge            E CWIML4537E: The login operation could not be completed. The specified principal name testuser is not found in the back-end repository. 
com.ibm.wsspi.security.wim.exception.PasswordCheckFailedException: CWIML4537E: The login operation could not be completed. The specified principal name testuser is not found in the back-end repository.
	at com.ibm.ws.security.wim.ProfileManager.loginImpl(ProfileManager.java:1845)
	at com.ibm.ws.security.wim.ProfileManager.genericProfileManagerMethod(ProfileManager.java:240)
	at com.ibm.ws.security.wim.ProfileManager.login(ProfileManager.java:206)
	at com.ibm.ws.security.wim.VMMService.login(VMMService.java:246)
	at com.ibm.ws.security.wim.registry.util.LoginBridge.checkPassword(LoginBridge.java:115)
	at com.ibm.ws.security.wim.registry.WIMUserRegistry.checkPassword(WIMUserRegistry.java:171)
	at com.ibm.ws.security.registry.internal.UserRegistryWrapper.checkPassword(UserRegistryWrapper.java:54)
	at com.ibm.ws.security.oauth20.web.ClientAuthentication.validateResourceOwnerCredential(ClientAuthentication.java:345)
	at com.ibm.ws.security.oauth20.web.ClientAuthentication.verify(ClientAuthentication.java:212)
	at com.ibm.ws.security.oauth20.web.OAuth20EndpointServices.handleEndpointRequest(OAuth20EndpointServices.java:211)
	at com.ibm.ws.security.openidconnect.web.OidcEndpointServices.handleOidcRequest(OidcEndpointServices.java:248)
	at com.ibm.ws.security.openidconnect.web.OidcEndpointServlet.doPost(OidcEndpointServlet.java:56)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:595)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:668)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1255)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:743)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:440)
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.invokeTarget(WebAppFilterChain.java:182)
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:93)
	at com.ibm.ws.security.openidconnect.web.OidcRequestFilter.setEndpointRequest(OidcRequestFilter.java:42)
	at com.ibm.ws.security.oauth20.web.OAuth20RequestFilter.doFilter(OAuth20RequestFilter.java:85)
	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:201)
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:90) 

```

- do we need the stack trace in the messages.log (should we be modifying existing behavior)
- there are cases where it should show twice (once if Debug is enabled and once if Error is enabled).  If shown, it should only be once

Affected code is: https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.security.wim.registry/src/com/ibm/ws/security/wim/registry/util/LoginBridge.java#L148

Probably should check all of the methods for similar issues

**Comment by jvanhill** [comment]
[userNotFound.zip](https://github.com/OpenLiberty/open-liberty/files/2972197/userNotFound.zip)

**Comment by nadiramra** [comment]
I believe this is a bug.  It is a  bug because  the security  framework is not recognizing the fact that the user is valid.   The other problem would be if the  user want no in user-defined registry.  I think it automatically  tries to find it in another user repository even though none is configured.  And there  does  not seem  to  be a  way to suppress the message - I  have tried:
hideMessage=“CWWKS4001I CWIML4537E”
There is no reason to dump out  the stack trace.  And it seems to  be  dumped  out  EVERYTIME.
Here is my background.
Java 8 and Liberty version 20.0.0.12.  A user-defined user registry is configured, in the trace it is com.ibm.ibmi.lwi.ibmiuserregistry.IBMiUserRegistry. It is the ONLY registry  configured.
I am not sure why CWIML4537E and stack trace is being dumped to log file if a user fails to authenticate.  I send in  user AMRA with bad password:
[12/10/20 15:59:17:649 CST] 0000003d id=00000000 com.ibm.ibmi.lwi.ibmiuserregistry.IBMiUserRegistry      3 getRealm: newiws1Realm
[12/10/20 15:59:17:655 CST] 0000003d id=00000000 com.ibm.ibmi.lwi.ibmiuserregistry.IBMiUserRegistry      3 getRealm: newiws1Realm
[12/10/20 15:59:17:697 CST] 0000003d id=00000000 com.ibm.ibmi.lwi.ibmiuserregistry.IBMiUserRegistry      3 getRealm: newiws1Realm
[12/10/20 15:59:17:698 CST] 0000003d id=00000000 com.ibm.ibmi.lwi.ibmiuserregistry.IBMiUserRegistry      3 getRealm: newiws1Realm
[12/10/20 15:59:17:699 CST] 0000003d id=00000000 com.ibm.ibmi.lwi.ibmiuserregistry.IBMiUserRegistry      3 getRealm: newiws1Realm
[12/10/20 15:59:17:700 CST] 0000003d id=00000000 com.ibm.ibmi.lwi.ibmiuserregistry.IBMiUserRegistry      3 getRealm: newiws1Realm
[12/10/20 15:59:17:703 CST] 0000003d id=00000000 com.ibm.ibmi.lwi.ibmiuserregistry.IBMiUserRegistry      3 getRealm: newiws1Realm
[12/10/20 15:59:17:706 CST] 0000003d id=00000000 com.ibm.ibmi.lwi.ibmiuserregistry.IBMiUserRegistry      3 getUsers: AMRA;limit=1
[12/10/20 15:59:17:713 CST] 0000003d id=00000000 com.ibm.ibmi.lwi.ibmiuserregistry.IBMiUserRegistry      3 getUsers: [AMRA]
[12/10/20 15:59:17:745 CST] 0000003d id=00000000 com.ibm.ibmi.lwi.ibmiuserregistry.IBMiUserRegistry      3 UserProfile:checkPassword: Password is incorrect.:AMRA(8)
[12/10/20 15:59:17:745 CST] 0000003d id=00000000 com.ibm.ibmi.lwi.ibmiuserregistry.IBMiUserRegistry      3 UserProfile:checkPassword:FAIL AMRA
[12/10/20 15:59:17:746 CST] 0000003d id=00000000 com.ibm.ws.security.wim.registry.util.LoginBridge      E CWIML4537E: The login operation could not be completed. The specified principal name AMRA is not found in the back-end repository. 
                                                        com.ibm.wsspi.security.wim.exception.PasswordCheckFailedException: CWIML4537E: The login operation could not be completed. The specified principal name AMRA is not found in the back-end repository.
	at com.ibm.ws.security.wim.ProfileManager.loginImpl(ProfileManager.java:1870)
	at com.ibm.ws.security.wim.ProfileManager.genericProfileManagerMethod(ProfileManager.java:254)
	at com.ibm.ws.security.wim.ProfileManager.login(ProfileManager.java:217)
	at com.ibm.ws.security.wim.VMMService.login(VMMService.java:249)
	at com.ibm.ws.security.wim.registry.util.LoginBridge.checkPassword(LoginBridge.java:116)
	at com.ibm.ws.security.wim.registry.WIMUserRegistry.checkPassword(WIMUserRegistry.java:151)
	at com.ibm.ws.security.authentication.jaas.modules.UsernameAndPasswordLoginModule.login(UsernameAndPasswordLoginModule.java:75)
	at com.ibm.ws.kernel.boot.security.LoginModuleProxy.login(LoginModuleProxy.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at javax.security.auth.login.LoginContext.invoke(LoginContext.java:788)
	at javax.security.auth.login.LoginContext.access$000(LoginContext.java:196)
	at javax.security.auth.login.LoginContext$4.run(LoginContext.java:698)
	at javax.security.auth.login.LoginContext$4.run(LoginContext.java:696)
	at java.security.AccessController.doPrivileged(AccessController.java:734)
	at javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:696)
	at javax.security.auth.login.LoginContext.login(LoginContext.java:597)
	at com.ibm.ws.security.authentication.internal.jaas.JAASServiceImpl.doLoginContext(JAASServiceImpl.java:343)
	at com.ibm.ws.security.authentication.internal.jaas.JAASServiceImpl.performLogin(JAASServiceImpl.java:329)
	at com.ibm.ws.security.authentication.internal.jaas.JAASServiceImpl.performLogin(JAASServiceImpl.java:314)
	at com.ibm.ws.security.authentication.internal.AuthenticationServiceImpl.performJAASLogin(AuthenticationServiceImpl.java:495)
	at com.ibm.ws.security.authentication.internal.AuthenticationServiceImpl.authenticate(AuthenticationServiceImpl.java:210)
	at com.ibm.ws.webcontainer.security.internal.BasicAuthAuthenticator.basicAuthenticate(BasicAuthAuthenticator.java:126)
	at com.ibm.ws.webcontainer.security.internal.BasicAuthAuthenticator.handleBasicAuth(BasicAuthAuthenticator.java:117)
	at com.ibm.ws.webcontainer.security.internal.BasicAuthAuthenticator.authenticate(BasicAuthAuthenticator.java:70)
	at com.ibm.ws.webcontainer.security.WebAuthenticatorProxy.authenticate(WebAuthenticatorProxy.java:88)
	at com.ibm.ws.webcontainer.security.WebAppSecurityCollaboratorImpl.authenticateRequest(WebAppSecurityCollaboratorImpl.java:1233)
	at com.ibm.ws.webcontainer.security.WebAppSecurityCollaboratorImpl.determineWebReply(WebAppSecurityCollaboratorImpl.java:989)
	at com.ibm.ws.webcontainer.security.WebAppSecurityCollaboratorImpl.performSecurityChecks(WebAppSecurityCollaboratorImpl.java:678)
	at com.ibm.ws.webcontainer.security.WebAppSecurityCollaboratorImpl.preInvoke(WebAppSecurityCollaboratorImpl.java:596)
	at com.ibm.wsspi.webcontainer.collaborator.CollaboratorHelper.preInvokeCollaborators(CollaboratorHelper.java:459)
	at com.ibm.ws.webcontainer.osgi.collaborator.CollaboratorHelperImpl.preInvokeCollaborators(CollaboratorHelperImpl.java:270)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1114)
	at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:5057)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.handleRequest(DynamicVirtualHost.java:314)
	at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:1005)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:279)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1141)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:422)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:381)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:565)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:499)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:359)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.ready(HttpInboundLink.java:326)
	at com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.sendToDiscriminators(NewConnectionInitialReadCallback.java:167)
	at com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.complete(NewConnectionInitialReadCallback.java:75)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:504)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueManager.java:574)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:958)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:1047)
	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:239)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:822)
[12/10/20 15:59:17:814 CST] 0000003d id=00000000 y.authentication.jaas.modules.UsernameAndPasswordLoginModule A CWWKS1100A: Authentication did not succeed for user ID AMRA. An invalid user ID or password was specified.

**Comment by nadiramra** [comment]
And  I   think if the exception from checkuserandpassword is com.ibm.websphere.security.PasswordCheckFailedException
, we should not log any message unless finest or something  similar.
