### ISSUE TITLE
Liberty depends on the ps command during shutdown

### ISSUE THREAD

**Issue by arthurdm** [OpenLiberty/open-liberty#6956]
If using a container that has `ps` removed (such as a minimalist Docker image) we get this error from Liberty while performing `server stop`:

```
java.io.IOException: Cannot run program "ps": error=2, No such file or directory
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1059)
    at com.ibm.ws.kernel.boot.internal.PSProcessStatusImpl.isPossiblyRunning(PSProcessStatusImpl.java:62)
    at com.ibm.ws.kernel.boot.internal.commands.ProcessControlHelper.waitForProcessStop(ProcessControlHelper.java:142)
    at com.ibm.ws.kernel.boot.internal.commands.ProcessControlHelper.stop(ProcessControlHelper.java:120)
    at com.ibm.ws.kernel.boot.Launcher.handleActions(Launcher.java:262)
    at com.ibm.ws.kernel.boot.Launcher.createPlatform(Launcher.java:117)
    at com.ibm.ws.kernel.boot.cmdline.EnvCheck.main(EnvCheck.java:59)
    at com.ibm.ws.kernel.boot.cmdline.EnvCheck.main(EnvCheck.java:35)
Caused by: java.io.IOException: error=2, No such file or directory
    at java.lang.UNIXProcess.<init>(UNIXProcess.java:291)
    at java.lang.ProcessImpl.start(ProcessImpl.java:167)
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1040)
    ... 7 more
```

**Comment by cbridgha** [comment]
PR: https://github.com/OpenLiberty/open-liberty/pull/6953

**Comment by cbridgha** [comment]
OK So after more testing, and I messed up the initial fix - I had to create another PR - but have def validated it fixes the issue...  https://github.com/OpenLiberty/open-liberty/pull/6998

Will be in 19004 (Not 19003)

**Comment by cbridgha** [comment]
This was fixed in 19004
