### ISSUE TITLE
[Java11] Test Failure: com.ibm.ws.microprofile.metrics.tck.launcher.MetricsAuthenticationTest.testMetrics10Auth

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#6978]
RTC 261539

```
testMetrics10Auth
java.lang.Exception: 2019-03-20-07:20:44:810 Errors/warnings were found in server MetricsAuthenticationServer logs:
<br>[3/20/19 7:20:29:189 UTC] 00000029 LogService-53-com.ibm.ws.injection                           E CWWKE0701E: bundle com.ibm.ws.injection:1.0.26.201903200222 (53)[com.ibm.ws.injectionengine.osgi.internal.OSGiInjectionEngineImpl(125)] : The registerInjectionProcessorProvider method has thrown an exception com.ibm.wsspi.injectionengine.InjectionException: provider already registered for javax.inject.Inject
at componenttest.topology.impl.LibertyServer.checkLogsForErrorsAndWarnings(LibertyServer.java:2495)
at componenttest.topology.impl.LibertyServer.stopServer(LibertyServer.java:2371)
at componenttest.topology.impl.LibertyServer.stopServer(LibertyServer.java:2211)
at componenttest.topology.impl.LibertyServer.stopServer(LibertyServer.java:2186)
at com.ibm.ws.microprofile.metrics.tck.launcher.MetricsAuthenticationTest.tearDown(MetricsAuthenticationTest.java:54)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:193)
at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:314)
at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:167)

```

**Comment by fmhwong** [comment]
Dup of #7442
