### ISSUE TITLE
com.ibm.ws.logstash.collector_fat: com.ibm.ws.logstash.collector.tests.LogsStashSSLTest.testModifiedSourceSubscription

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#7084]
RTC 257169

```
Exception = java.lang.NullPointerException
Source = com.ibm.ws.collector.internal.TaskImpl
probeid = 71
Stack Dump = java.lang.NullPointerException
	at com.ibm.ws.collector.manager.buffer.BufferManagerImpl.getNextEvent(BufferManagerImpl.java:154)
	at com.ibm.ws.collector.internal.TaskImpl.run(TaskImpl.java:55)
	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:239)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:522)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1153)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:785)

```

**Comment by fmhwong** [comment]
[ffdc_19.03.29_12.41.52.0.log](https://github.com/OpenLiberty/open-liberty/files/3030357/ffdc_19.03.29_12.41.52.0.log)

**Comment by fmhwong** [comment]
Not re-occurred recently
