### ISSUE TITLE
CSIv2 outbound request NullPointerException when sending a BasicAuth Subject via GSSUP

### ISSUE THREAD

**Issue by dburdine** [OpenLiberty/open-liberty#7236]
Customers performing ORB CSIv2 outbound requests using GSSUP to send a BasicAuth Subject can fail with a NPE. As a workaround, specify GSSUP as the only outbound mechanism in the server.xml ORB element, clientPolicy attribute. ie:

           <clientPolicy.csiv2>
               <layers>
                   <attributeLayer identityAssertionEnabled="false"/>
                   <authenticationLayer **mechanisms="GSSUP"** establishTrustInClient="Required"/>
                   <transportLayer/>
               </layers>
           </clientPolicy.csiv2>

Exception = java.lang.NullPointerException
Source = com.ibm.ws.transport.iiop.security.util.Util
probeid = 418
Stack Dump = java.lang.NullPointerException
	at org.omg.Security.OpaqueHelper.write(OpaqueHelper.java:56)
	at org.omg.Security.OpaqueHelper.insert(OpaqueHelper.java:19)
	at com.ibm.ws.transport.iiop.security.util.Util.encodeLTPAToken(Util.java:414)
	at com.ibm.ws.transport.iiop.security.util.Util.encodeLTPATokenForWASClassic(Util.java:436)
	at com.ibm.ws.security.csiv2.server.config.css.ClientLTPAMechConfig.createEncoding(ClientLTPAMechConfig.java:119)
	at com.ibm.ws.security.csiv2.server.config.css.ClientLTPAMechConfig.encode(ClientLTPAMechConfig.java:91)
	at com.ibm.ws.transport.iiop.security.config.css.CSSCompoundSecMechConfig.generateServiceContext(CSSCompoundSecMechConfig.java:326)
	at com.ibm.ws.transport.iiop.security.ClientSecurityInterceptor.send_request(ClientSecurityInterceptor.java:153)
	at org.apache.yoko.orb.PortableInterceptor.ClientRequestInfo_impl._OB_request(ClientRequestInfo_impl.java:376)
	at org.apache.yoko.orb.OB.PIManager.clientSendRequest(PIManager.java:306)
	at org.apache.yoko.orb.OB.PIDIIDowncall.preMarshal(PIDIIDowncall.java:54)
	at org.apache.yoko.orb.OB.DowncallStub.preMarshal(DowncallStub.java:254)
	at org.apache.yoko.orb.CORBA.Request.marshal(Request.java:80)
	at org.apache.yoko.orb.CORBA.Request.invoke(Request.java:294)
	at org.apache.yoko.orb.OB.CorbanameURLScheme_impl.parse_url(CorbanameURLScheme_impl.java:215)
	at org.apache.yoko.orb.OB.URLRegistry_impl.parse_url(URLRegistry_impl.java:70)
	at org.apache.yoko.orb.OB.ObjectFactory.stringToObject(ObjectFactory.java:118)
	at org.apache.yoko.orb.OBCORBA.ORB_impl.string_to_object(ORB_impl.java:1184)
	at com.ibm.ws.jndi.iiop.OrbContext.lookup(OrbContext.java:53)
	at org.apache.aries.jndi.DelegateContext.lookup(DelegateContext.java:161)
	at javax.naming.InitialContext.lookup(InitialContext.java:428)
	at com.ibm.tws.api.csc.LoginBean$1.run(LoginBean.java:174)
	at com.ibm.tws.api.csc.LoginBean$1.run(LoginBean.java:1)
	at java.security.AccessController.doPrivileged(AccessController.java:620)
	at javax.security.auth.Subject.doAs(Subject.java:488)
	at com.ibm.websphere.security.auth.WSSubject.doAs(WSSubject.java:123)
	at com.ibm.websphere.security.auth.WSSubject.doAs(WSSubject.java:90)
	at com.ibm.tws.api.csc.LoginBean.getPlanRemote(LoginBean.java:161)
	at com.ibm.tws.api.csc.LoginBean.login(LoginBean.java:139)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:95)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.apache.el.parser.AstValue.invoke(AstValue.java:245)
	at org.apache.el.MethodExpressionImpl.invoke(MethodExpressionImpl.java:267)
	at org.apache.myfaces.view.facelets.el.ContextAwareTagMethodExpression.invoke(ContextAwareTagMethodExpression.java:96)
	at org.apache.myfaces.application.ActionListenerImpl.processAction(ActionListenerImpl.java:74)
	at javax.faces.component.UICommand.broadcast(UICommand.java:120)
	at javax.faces.component.UIViewRoot._broadcastAll(UIViewRoot.java:1255)
	at javax.faces.component.UIViewRoot.broadcastEvents(UIViewRoot.java:420)
	at javax.faces.component.UIViewRoot._process(UIViewRoot.java:1741)
	at javax.faces.component.UIViewRoot.processApplication(UIViewRoot.java:935)
	at org.apache.myfaces.lifecycle.InvokeApplicationExecutor.execute(InvokeApplicationExecutor.java:42)
	at org.apache.myfaces.lifecycle.LifecycleImpl.executePhase(LifecycleImpl.java:195)
	at org.apache.myfaces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:142)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:204)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1255)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:743)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:440)
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.invokeTarget(WebAppFilterChain.java:182)
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:93)
	at com.ibm.ws.security.jaspi.JaspiServletFilter.doFilter(JaspiServletFilter.java:56)
	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:201)
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:90)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.doFilter(WebAppFilterManager.java:996)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1134)
	at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:4954)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.handleRequest(DynamicVirtualHost.java:314)
	at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:996)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:279)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1023)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:417)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:376)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:532)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:466)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:331)
	at com.ibm.ws.http.channel.internal.inbound.HttpICLReadCallback.complete(HttpICLReadCallback.java:70)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:501)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueManager.java:571)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:926)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:1015)
	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:232)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1153)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:785)

**Comment by dburdine** [comment]
Duplicate of issue #7238
