### ISSUE TITLE
Non-deterministic NPE thrown by Websphere liberty in com.ibm.ws.classloading.internal.AppClassLoader

### ISSUE THREAD

**Issue by e1m7bo** [OpenLiberty/open-liberty#7345]
Very often I'm getting following exception when starting multiple WARs with applications based on Spring Boot:
`Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.foo.SomeService]: Factory method 'someService' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'someBean' defined in com.foo.SomeJavaConfig: Post-processing of merged bean definition failed; nested exception is java.lang.NullPointerException
at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:599)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1181)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1075)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:513)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312)
at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308)
at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761)
at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:169)
at com.ibm.ws.webcontainer.webapp.WebApp.initializeServletContainerInitializers(WebApp.java:2487)
at com.ibm.ws.webcontainer.webapp.WebApp.initialize(WebApp.java:994)
at com.ibm.ws.webcontainer.webapp.WebApp.initialize(WebApp.java:6566)
...
Caused by: java.lang.NullPointerException: null
at com.ibm.ws.classloading.internal.AppClassLoader.getClassSpecificProtectionDomainPrivileged(AppClassLoader.java:367)
at com.ibm.ws.classloading.internal.AppClassLoader.access$000(AppClassLoader.java:64)
at com.ibm.ws.classloading.internal.AppClassLoader$2.run(AppClassLoader.java:351)
at com.ibm.ws.classloading.internal.AppClassLoader$2.run(AppClassLoader.java:348)
at java.security.AccessController.doPrivileged(Native Method)
at com.ibm.ws.classloading.internal.AppClassLoader.getClassSpecificProtectionDomain(AppClassLoader.java:348)
at com.ibm.ws.classloading.internal.AppClassLoader.definePackageAndClass(AppClassLoader.java:325)
at com.ibm.ws.classloading.internal.AppClassLoader.findClass(AppClassLoader.java:271)
at com.ibm.ws.classloading.internal.ParentLastClassLoader.findOrDelegateLoadClass(ParentLastClassLoader.java:80)
at com.ibm.ws.classloading.internal.AppClassLoader.loadClass(AppClassLoader.java:443)
at com.ibm.ws.classloading.internal.ParentLastClassLoader.loadClass(ParentLastClassLoader.java:50)
at java.lang.Class.getDeclaredMethods0(Native Method)
at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
at java.lang.Class.getDeclaredMethods(Class.java:1975)
at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:613)
at org.springframework.util.ReflectionUtils.doWithLocalMethods(ReflectionUtils.java:489)
at org.springframework.orm.jpa.support.PersistenceAnnotationBeanPostProcessor.buildPersistenceMetadata(PersistenceAnnotationBeanPostProcessor.java:431)
at org.springframework.orm.jpa.support.PersistenceAnnotationBeanPostProcessor.findPersistenceMetadata(PersistenceAnnotationBeanPostProcessor.java:397)
at org.springframework.orm.jpa.support.PersistenceAnnotationBeanPostProcessor.postProcessMergedBeanDefinition(PersistenceAnnotationBeanPostProcessor.java:333)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyMergedBeanDefinitionPostProcessors(AbstractAutowireCapableBeanFactory.java:1000)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:523)
... 76 common frames omitted`

It is non-deteministic - it happens that all WARs are starting well.
Issue is reproducible on WLP ver: 18.0.0.3 and 19.0.0.3 (didn't tested on other).
Spring version 4.3.17.RELEASE
I've also noticed that issue occur more ofter if many application WARs are started at the same time.

**Comment by jhanders34** [comment]
Cross referencing stackoverflow issue:  https://stackoverflow.com/questions/55844487/non-deterministic-npe-thrown-by-websphere-liberty-in-com-ibm-ws-classloading-int

**Comment by tbitonti** [comment]
Trace will be needed to investigate further.  
@e1m7bo, can you reproduce with this trace specification:
com.ibm.ws.classloading.*=finest:com.ibm.ws.artifact.*=finest:com.ibm.ws.adaptable.module.*=finest
Or, if you could put together a github repository with a test case that reproduces the problem, then we (IBM dev) can collect the trace ourselves.

**Comment by e1m7bo** [comment]
Unfortunately when I've enabled trace, problem is not reproducible anymore (I tried few times in the row).
Perhaps it is due the fact trace level slows down server significantly which has impact on this non-determinisntic error. 

Additional finding - when I started WARs one by one (not in parallel) error is not reproducible.

**Comment by tbitonti** [comment]
@e1m7bo Would you be able to run with a diagnostic fix (which would have specific output to help highlight the problem)?

**Comment by e1m7bo** [comment]
@tbitonti Sure. How we should proceed now? You will provide me some patch WLP's JAR ?

**Comment by tbitonti** [comment]
This looks to be a strange timing / concurrency issue.
The NPE is on a value (instance variable 'config') which is assigned during AppClassLoader.<init>, which is guarded by a factory test that should ensure the value is never null.  Which means either a non-factory construction path, or a reference leak during construction.  I have a code update which I am testing which attempts to detect either of these cases.  Not a fix, but hopefully we will get more useful exception information if either case occurs.  See the linked pull request #8941

**Comment by tbitonti** [comment]
Hi; I have code updates to provide tracking information to detect the null value condition which leads to the error.  Can you let me know what release you are working with and I'll get you patch classes appropriate for that release.
Our analysis is that the null value which is causing the NPE *should* be assigned during initialization of the AppClassLoader object.  And, there is a test in the factory method of the AppClassLoader which should prevent a null value.  That indicates that there is a non-factory path which is creating instances with a null value, or, there is a timing/concurrency issue, in which a reference to the new class loader leaks out of the thread which is creating the new class loader before the class loader initialization completes.
A code update is being made which attempts to detect either case, and which will provide better exception information so that the problem code path (non-factory construction of the class loader *or* reference leak) can be determined.
