### ISSUE TITLE
Test Failure: build.feature.java.level.MinJavaLevelTest.testFeaturesStart

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#7386]
RTC 261924

```
testFeaturesStart:junit.framework.AssertionFailedError: 2019-04-08-22:04:10:170 Features(s) [mpMetrics-1.1] did not start/stop cleanly on their own due to the following exceptions: [mpMetrics-1.1=java.lang.Exception: Errors/warnings were found in server build.feature.java.level logs:
<br>[4/8/19 21:59:24:481 UTC] 0000001e LogService-53-com.ibm.ws.injection                           E CWWKE0701E: bundle com.ibm.ws.injection:1.0.27.201904081619 (53)[com.ibm.ws.injectionengine.osgi.internal.OSGiInjectionEngineImpl(150)] : The registerInjectionProcessorProvider method has thrown an exception com.ibm.wsspi.injectionengine.InjectionException: provider already registered for javax.inject.Inject]
at build.feature.java.level.MinJavaLevelTest.testFeaturesStart(MinJavaLevelTest.java:184)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:194)
at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:334)
at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:168)
```

**Comment by fmhwong** [comment]
Return as dup of #7442
