### ISSUE TITLE
com.ibm.wsspi.injectionengine.InjectionException: provider already registered for javax.inject.Inject

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#7442]
We have a number of defects in RTC with similar symptoms.

RTC 262434
```
com.ibm.ws.microprofile.health.fat.HealthCheckExceptionTest:java.lang.Exception: Errors/warnings were found in server CDIHealthException logs:
<br>[4/28/19 8:17:12:282 UTC] 0000001d LogService-84-com.ibm.ws.injection                           E CWWKE0701E: bundle com.ibm.ws.injection:1.0.28.201904280159 (84)[com.ibm.ws.injectionengine.osgi.internal.OSGiInjectionEngineImpl(192)] : The registerInjectionProcessorProvider method has thrown an exception com.ibm.wsspi.injectionengine.InjectionException: provider already registered for javax.inject.Inject
at componenttest.topology.impl.LibertyServer.checkLogsForErrorsAndWarnings(LibertyServer.java:2528)
```

RTC 261997
```
estEDF12:java.lang.Exception: 2019-04-11-19:26:42:439 Errors/warnings were found in server TestEDF12 logs:
<br>[4/11/19 19:26:36:233 UTC] 0000002a LogService-52-com.ibm.ws.injection                           E CWWKE0701E: bundle com.ibm.ws.injection:1.0.27.cl190420190411-1311 (52)[com.ibm.ws.injectionengine.osgi.internal.OSGiInjectionEngineImpl(150)] : The registerInjectionProcessorProvider method has thrown an exception com.ibm.wsspi.injectionengine.InjectionException: provider already registered for javax.inject.Inject
at componenttest.topology.impl.LibertyServer.checkLogsForErrorsAndWarnings(LibertyServer.java:2528)
```

RTC 262114

```
junit.framework.AssertionFailedError: 2019-04-18-10:18:10:827 ATTENTION: ONLY ASSOCIATE THIS FAILURE WITH ANOTHER DEFECT/ISSUE IF THE FEATURE SET AND MESSAGES ARE THE SAME.
Features(s) [mpHealth-1.0] did not start/stop cleanly on their own, due to the following exceptions: [mpHealth-1.0=java.lang.Exception: Errors/warnings were found in server build.feature.java.level logs:
<br>[18/04/19 10:06:03:025 BST] 00000012 LogService-52-com.ibm.ws.injection                           E CWWKE0701E: bundle com.ibm.ws.injection:1.0.27.201904180420 (52)[com.ibm.ws.injectionengine.osgi.internal.OSGiInjectionEngineImpl(119)] : The registerInjectionProcessorProvider method has thrown an exception com.ibm.wsspi.injectionengine.InjectionException: provider already registered for javax.inject.Inject]
at build.feature.java.level.MinJavaLevelTest.testFeaturesStart(MinJavaLevelTest.java:184)
at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:194)
at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:334)
at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:168)
```

**Comment by fmhwong** [comment]
Not occurred in last 4 weeks
