### ISSUE TITLE
Test Failed: com.ibm.ws.microprofile.metrics_fat_tck: com.ibm.ws.microprofile.metrics.tck.launcher.MetricsTCKLauncher.launchTck

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#7472]
RTC 262120

```
junit.framework.AssertionFailedError: 2019-04-19-09:28:01:622 No TCK test JUnit result files were found in the results directory which suggests the TCK tests did not run - check build logs. 
ResultsDir: /home/jazz_build/_2FphsGJtEemP6vsjGLPPfg-EBC.PROD.WASRTC-6CX-000-00-00/jbe/build/dev/com.ibm.ws.microprofile.metrics_fat_tck/autoFVT/results/tck/surefire-reports at componenttest.topology.utils.MvnUtils.findJunitResultFiles(MvnUtils.java:415) 
  at componenttest.topology.utils.MvnUtils.postProcessTestResults(MvnUtils.java:378) 
  at componenttest.topology.utils.MvnUtils.runTCKMvnCmd(MvnUtils.java:330) 
  at com.ibm.ws.microprofile.metrics.tck.launcher.MetricsTCKLauncher.launchTck(MetricsTCKLauncher.java:60) 
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
  at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:193) 
  at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:314) 
  at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:167)
```

**Comment by fmhwong** [comment]
No occurrences in last 3 weeks
