### ISSUE TITLE
java.util.NoSuchElementException in EJBSecurityCollaboratorImpl.authorizeEJB

### ISSUE THREAD

**Issue by zniehsen** [OpenLiberty/open-liberty#7510]
https://github.com/OpenLiberty/open-liberty/blob/6ebcdf86c2904db1db4053d13eecf9f19c723ebe/dev/com.ibm.ws.ejbcontainer.security/src/com/ibm/ws/ejbcontainer/security/internal/EJBSecurityCollaboratorImpl.java#L433

**Trace:**
```
javax.ejb.EJBException: See nested exception; nested exception is: java.util.NoSuchElementException
	at com.ibm.ejs.container.util.ExceptionUtil.EJBException(ExceptionUtil.java:399) ~[na:na]
	at com.ibm.ejs.container.util.ExceptionUtil.EJBException(ExceptionUtil.java:285) ~[na:na]
	at com.ibm.ejs.container.BusinessExceptionMappingStrategy.mapException(BusinessExceptionMappingStrategy.java:347) ~[com.ibm.ws.ejbcontainer_1.0.23.jar:na]
	at com.ibm.ejs.container.BusinessExceptionMappingStrategy.setUncheckedException(BusinessExceptionMappingStrategy.java:519) ~[com.ibm.ws.ejbcontainer_1.0.23.jar:na]
	at com.ibm.ejs.container.EJSDeployedSupport.setUncheckedException(EJSDeployedSupport.java:419) ~[com.ibm.ws.ejbcontainer_1.0.23.jar:na]
	at com.ibm.ejs.container.EJSContainer.preinvokeHandleException(EJSContainer.java:2652) ~[com.ibm.ws.ejbcontainer_1.0.23.jar:na]
	at com.ibm.ejs.container.EJSContainer.EjbPreInvoke(EJSContainer.java:2433) ~[com.ibm.ws.ejbcontainer_1.0.23.jar:na]
	at 
...
	at java.util.concurrent.FutureTask.run(FutureTask.java:277) [na:1.8.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160) [na:1.8.0]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [na:1.8.0]
	at java.lang.Thread.run(Thread.java:812) [na:2.9 (11-06-2018)]
	at com.ibm.ws.concurrent.internal.ManagedThreadImpl.run(ManagedThreadImpl.java:94) [com.ibm.ws.concurrent_1.0.23.jar:na]
Caused by: java.util.NoSuchElementException: null
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1455) ~[na:1.8.0]
	at java.util.HashMap$KeyIterator.next(HashMap.java:1477) ~[na:1.8.0]
	at com.ibm.ws.ejbcontainer.security.internal.EJBSecurityCollaboratorImpl.authorizeEJB(EJBSecurityCollaboratorImpl.java:433) ~[na:na]
	at com.ibm.ws.ejbcontainer.security.internal.EJBSecurityCollaboratorImpl.preInvoke(EJBSecurityCollaboratorImpl.java:194) ~[na:na]
	at com.ibm.ws.ejbcontainer.security.internal.EJBSecurityCollaboratorImpl.preInvoke(EJBSecurityCollaboratorImpl.java:69) ~[na:na]
	at com.ibm.ejs.container.EJSContainer.notifySecurityCollaboratorPreInvoke(EJSContainer.java:3147) ~[com.ibm.ws.ejbcontainer_1.0.23.jar:na]
	at com.ibm.ejs.container.EJSContainer.preInvokeAfterActivate(EJSContainer.java:3092) ~[com.ibm.ws.ejbcontainer_1.0.23.jar:na]
	at com.ibm.ejs.container.EJSContainer.EjbPreInvoke(EJSContainer.java:2394) ~[com.ibm.ws.ejbcontainer_1.0.23.jar:na]
```

**Background**
Called method of local EJB from asynch future task (Callable) using ThreadPoolExecutor.
Currently I do not know, why the principal collection is empty. 
When we call the local EJB method directly (synchronously / without ThreadPoolExecutor) everything works fine.

**Comment by njr-11** [comment]
ThreadPoolExecutor does not propagate context information.  Try using a ManagedExecutorService.  For this, you will need to enable the `concurrent-1.0` feature.  You can inject the default instance into a web or ejb component as follows,
```
@Resource ManagedExecutorService executor;
```
Alternatively, if you have the `jndi-1.0` feature enabled, you can look it up,
```
ManagedExecutorService executor = InitialContext.doLookup("java:comp/DefaultManagedExecutorService");
```

It is also possible configure difference instances. Refer to the [knowledge center documentation](https://www.ibm.com/support/knowledgecenter/en/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/twlp_config_managedexecutor.html) for that.

**Comment by zniehsen** [comment]
We create the `ThreadPoolExecutor` using a configured `ManagedThreadFactory`.

```
	<managedThreadFactory jndiName="concurrent/my_ThreadFactory">
		<contextService>
			<classloaderContext />
			<jeeMetadataContext />
			<securityContext />
		</contextService>
	</managedThreadFactory>
```
`concurrent-1.0` and `appSecurity-2.0` are set as feature.

The configuration is same as example in following documentation:
https://www.ibm.com/support/knowledgecenter/en/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/twlp_config_threadfactory.html

And the documentation says, that the security context will be propagated:

> Managed thread factory with context service configured to capture and propagate securityContext only

**Comment by njr-11** [comment]
> We create the `ThreadPoolExecutor` using a configured `ManagedThreadFactory`

In that case, yes security context will be propagated.  For ManagedThreadFactory, context is captured from the thread that injects or looks up the ManagedThreadFactory, (refer to [JavaDoc](https://javaee.github.io/javaee-spec/javadocs/javax/enterprise/concurrent/ManagedThreadFactory.html)) not per request to the thread pool, so you should confirm that is the security context that you want.  If the correct security context is on the thread at that point and you are still seeing the error, that suggests there may be a bug in this area.

Regarding configurable attributes for ManagedExecutorService, there are some similarities with ThreadPoolExecutor, as [documented here](https://www.ibm.com/support/knowledgecenter/en/SSEQTP_liberty/com.ibm.websphere.liberty.autogen.base.doc/ae/rwlp_config_managedExecutorService.html#concurrencyPolicy), but it is certainly not a direct match.  ManagedExecutorService is not a separate thread pool and reuses threads from the Liberty global thread pool, which is why the settings are different.  If you see advantages of ThreadPoolExecutor over ManagedExecutorService, I'd be curious to hear about the specifics of that so we can consider if enhancements ought to be made to ManagedExecutorService.

> Btw.: Throwing a `NoSuchElementException` makes it very hard to identify the problem

I agree  - this error path needs improvement.

**Comment by zniehsen** [comment]
Ok, we tried to use `ManagedExecutorService` instead, which seems to work now.
In one of our usecases the developer read the number of cpu cores to define the threads used by `ThreadPoolExecutor `. There is no dynamic approach for the executor service, right?

**Comment by njr-11** [comment]
Correct, ManagedExecutorService is not configurable programmatically. However, a MicroProfile spec (which is currently in beta in Liberty) is prototyping an enhancement to managed executors where you can create them programmatically via a builder pattern.

**Comment by arkarkala** [comment]
We will fix the NPE issue by providing a better message/exception.

**Comment by kinglite** [comment]
I'm facing the same error here using Liberty 19.0.0.3 (wlp-1.0.26.cl190320190321-1636).
In my case, I'm calling an bean method from a doGet()-servlet call with basic auth http header: "Authorization: Basic Og==" (no user and password, just ":")

**Comment by toshiyamamoto** [comment]
Hi @kinglite, I'm wondering whether you are using programmatic login to construct a Subject for invoking downstream ejb. Or is the servlet which invokes the ejb protected? The reason why I'm asking the questions is to identify how the Subject which used to invoke EJB came from. If you still have a complete stack dump when the NPE is thrown, it would be very helpful if you can paste it in here or send it to me. Thank you.
