### ISSUE TITLE
Test Failure: com.ibm.ws.logging.fat.LogServiceTest.testServiceDebug

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#7603]
RTC 262183

```
testServiceDebug:junit.framework.AssertionFailedError: 2019-04-21-03:51:16:779 Found unexpected message in console log: ServiceRef:
at com.ibm.ws.logging.fat.LogServiceTest.assertExpectMessage(LogServiceTest.java:470)
at com.ibm.ws.logging.fat.LogServiceTest.doTestServiceReference(LogServiceTest.java:458)
at com.ibm.ws.logging.fat.LogServiceTest.testServiceDebug(LogServiceTest.java:428)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:193)
at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:314)
at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:167)
```

**Comment by lamkavan** [comment]
Issue has been resolved.
