### ISSUE TITLE
IllegalArgumentException in MP Metrics from timing issue

### ISSUE THREAD

**Issue by olendvcook** [OpenLiberty/open-liberty#7670]
Programmatically calling `MetricRegistry.counter(MetricMetadata).inc();` and hitting an IAE rarely:

```
Exception = java.lang.IllegalArgumentException
Source = com.ibm.ws.microprofile.metrics.impl.MetricRegistryImpl
probeid = 439

Stack Dump = java.lang.IllegalArgumentException: A metric named num_player_logins already exists
    at com.ibm.ws.microprofile.metrics11.impl.MetricRegistry11Impl.register(MetricRegistry11Impl.java:86)
    at com.ibm.ws.microprofile.metrics11.impl.MetricRegistry11Impl.register(MetricRegistry11Impl.java:53)
    at com.ibm.ws.microprofile.metrics.impl.MetricRegistryImpl.getOrAdd(MetricRegistryImpl.java:438)
    at com.ibm.ws.microprofile.metrics.impl.MetricRegistryImpl.counter(MetricRegistryImpl.java:230)
    at org.eclipse.microprofile.metrics.MetricRegistry$Proxy$_$$_WeldClientProxy.counter(Unknown Source)
    at org.libertybikes.player.service.PlayerService.createPlayer(PlayerService.java:67)
``` 

Seems to be some missing synchronization in `MetricRegistryImpl.getOrAdd`

**Comment by AidanPolese** [comment]
@olendvcook Could you please tell me the circumstances under which this bug occurred, I think I may have a solution however I cannot test it as I have been unable to recreate the issue.
