### ISSUE TITLE
Unable to start localConnector-1.0 when j2security is enabled

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/open-liberty#7787]
With Java 2 Security enabled, I see this error on startup (running on Java 11, OpenJ9):

```
java.util.ServiceConfigurationError: com.sun.tools.attach.spi.AttachProvider: Unable to get public provider() method
   at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:581)
   at java.base/java.util.ServiceLoader.findStaticProviderMethod(ServiceLoader.java:617)
   at java.base/java.util.ServiceLoader.loadProvider(ServiceLoader.java:877)
   at java.base/java.util.ServiceLoader$ModuleServicesLookupIterator.hasNext(ServiceLoader.java:1076)
   at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1299)
   at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1384)
   at com.sun.tools.attach.spi.AttachProvider.providers(AttachProvider.java:258)
   at com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:200)
   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   at java.base/java.lang.reflect.Method.invoke(Method.java:566)
   at com.ibm.ws.jmx.connector.local.LocalConnectorActivator$LocalConnectorHelper$1.run(LocalConnectorActivator.java:95)
   at com.ibm.ws.jmx.connector.local.LocalConnectorActivator$LocalConnectorHelper$1.run(LocalConnectorActivator.java:54)
   at java.base/java.security.AccessController.doPrivileged(AccessController.java:647)
   at com.ibm.ws.jmx.connector.local.LocalConnectorActivator$LocalConnectorHelper.initConnectorAddress(LocalConnectorActivator.java:54)
   at com.ibm.ws.jmx.connector.local.LocalConnectorActivator$LocalConnectorHelper.<clinit>(LocalConnectorActivator.java:44)
   at com.ibm.ws.jmx.connector.local.LocalConnectorActivator.createJmxAddressResource(LocalConnectorActivator.java:196)
   at com.ibm.ws.jmx.connector.local.LocalConnectorActivator.createJMXWorkAreaResource(LocalConnectorActivator.java:188)
   at com.ibm.ws.jmx.connector.local.LocalConnectorActivator.setLocationService(LocalConnectorActivator.java:164)
   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   at java.base/java.lang.reflect.Method.invoke(Method.java:566)
   at org.apache.felix.scr.impl.inject.methods.BaseMethod.invokeMethod(BaseMethod.java:228)
   at org.apache.felix.scr.impl.inject.methods.BaseMethod.access$500(BaseMethod.java:41)
   at org.apache.felix.scr.impl.inject.methods.BaseMethod$Resolved.invoke(BaseMethod.java:664)
   at org.apache.felix.scr.impl.inject.methods.BaseMethod.invoke(BaseMethod.java:510)
   at org.apache.felix.scr.impl.inject.methods.BindMethod.invoke(BindMethod.java:42)
   at org.apache.felix.scr.impl.manager.DependencyManager.doInvokeBindMethod(DependencyManager.java:1813)
   at org.apache.felix.scr.impl.manager.DependencyManager.bindDependency(DependencyManager.java:1637)
   at org.apache.felix.scr.impl.manager.DependencyManager.bind(DependencyManager.java:1624)
   at org.apache.felix.scr.impl.manager.SingleComponentManager.createImplementationObject(SingleComponentManager.java:307)
   at org.apache.felix.scr.impl.manager.SingleComponentManager.createComponent(SingleComponentManager.java:114)
   at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:982)
   at org.apache.felix.scr.impl.manager.SingleComponentManager.getServiceInternal(SingleComponentManager.java:955)
   at org.apache.felix.scr.impl.manager.AbstractComponentManager.activateInternal(AbstractComponentManager.java:765)
   at org.apache.felix.scr.impl.manager.AbstractComponentManager.enableInternal(AbstractComponentManager.java:666)
   at org.apache.felix.scr.impl.manager.AbstractComponentManager.enable(AbstractComponentManager.java:432)
   at org.apache.felix.scr.impl.manager.ConfigurableComponentHolder.enableComponents(ConfigurableComponentHolder.java:665)
   at org.apache.felix.scr.impl.BundleComponentActivator.initialEnable(BundleComponentActivator.java:338)
   at org.apache.felix.scr.impl.Activator.loadComponents(Activator.java:382)
   at org.apache.felix.scr.impl.Activator.access$200(Activator.java:49)
   at org.apache.felix.scr.impl.Activator$ScrExtension.start(Activator.java:264)
   at org.apache.felix.scr.impl.AbstractExtender.createExtension(AbstractExtender.java:196)
   at org.apache.felix.scr.impl.AbstractExtender.modifiedBundle(AbstractExtender.java:169)
   at org.apache.felix.scr.impl.AbstractExtender.modifiedBundle(AbstractExtender.java:49)
   at org.osgi.util.tracker.BundleTracker$Tracked.customizerModified(BundleTracker.java:488)
   at org.osgi.util.tracker.BundleTracker$Tracked.customizerModified(BundleTracker.java:1)
   at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:232)
   at org.osgi.util.tracker.BundleTracker$Tracked.bundleChanged(BundleTracker.java:450)
   at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:944)
   at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:233)
   at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
   at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEventPrivileged(EquinoxEventPublisher.java:233)
   at org.eclipse.osgi.internal.framework.EquinoxEventPublisher$1.run(EquinoxEventPublisher.java:144)
   at org.eclipse.osgi.internal.framework.EquinoxEventPublisher$1.run(EquinoxEventPublisher.java:1)
   at java.base/java.security.AccessController.doPrivileged(AccessController.java:647)
   at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:142)
   at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:132)
   at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor.publishModuleEvent(EquinoxContainerAdaptor.java:231)
   at org.eclipse.osgi.container.Module.publishEvent(Module.java:493)
   at org.eclipse.osgi.container.Module.start(Module.java:480)
   at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$1.run(ModuleContainer.java:1823)
   at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$2$1.execute(EquinoxContainerAdaptor.java:150)
   at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1816)
   at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1773)
   at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1735)
   at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1661)
   at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
   at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:233)
   at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:343)
Caused by: 
java.security.AccessControlException: Access denied ("java.lang.RuntimePermission" "accessClassInPackage.com.ibm.tools.attach.target")
   at java.base/java.security.AccessController.throwACE(AccessController.java:176)
   at java.base/java.security.AccessController.checkPermissionHelper(AccessController.java:237)
   at java.base/java.security.AccessController.checkPermission(AccessController.java:373)
   at java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:322)
   at java.base/java.lang.SecurityManager.checkPackageAccess(SecurityManager.java:1238)
   at java.base/java.lang.J9VMInternals$2.run(J9VMInternals.java:313)
   at java.base/java.security.AccessController.doPrivileged(AccessController.java:673)
   at java.base/java.lang.J9VMInternals.checkPackageAccess(J9VMInternals.java:308)
   at java.base/java.lang.ClassLoader.defineClassImpl(Native Method)
   at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:459)
   at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1991)
   at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:206)
   at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:1022)
   at java.base/jdk.internal.loader.BuiltinClassLoader.lambda$findClassInModuleOrNull$5(BuiltinClassLoader.java:866)
   at jdk.internal.loader.BuiltinClassLoader$$Lambda$143.00000000FC4143F0.run(Unknown Source)
   at java.base/java.security.AccessController.doPrivileged(AccessController.java:647)
   at java.base/jdk.internal.loader.BuiltinClassLoader.findClassInModuleOrNull(BuiltinClassLoader.java:867)
   at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:777)
   at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:751)
   at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
   at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1032)
   at java.base/java.lang.J9VMInternals.prepareClassImpl(Native Method)
   at java.base/java.lang.J9VMInternals.prepare(J9VMInternals.java:347)
   at java.base/java.lang.Class.getMethodHelper(Class.java:1391)
   at java.base/java.lang.Class.getDeclaredPublicMethods(Class.java:981)
   at java.base/java.lang.Access.getDeclaredPublicMethods(Access.java:289)
   at java.base/java.util.ServiceLoader.findStaticProviderMethod(ServiceLoader.java:615)
   ... 70 more
```

Looks like this started when #7648 was merged.

**Comment by aguibert** [comment]
Closing this issue because PR #7648 was backed out.

This does need to be resolved eventually though and I've raised an OpenJ9 issue here: https://github.com/eclipse/openj9/issues/6119

**Comment by Azquelt** [comment]
Reopened as #7968 appears to have broken it again.

**Comment by Azquelt** [comment]
Clarification: the stack trace with #7968 is different, though the end result is the same (localConnector doesn't work).

New stack:
```
Stack Dump = java.lang.ClassNotFoundException: sun.management.Agent
	at java.base/java.lang.Class.forNameImpl(Native Method)
	at java.base/java.lang.Class.forName(Class.java:422)
	at com.ibm.ws.jmx.connector.local.LocalConnectorActivator$LocalConnectorHelper$1.run(LocalConnectorActivator.java:79)
	at com.ibm.ws.jmx.connector.local.LocalConnectorActivator$LocalConnectorHelper$1.run(LocalConnectorActivator.java:55)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:647)
	at com.ibm.ws.jmx.connector.local.LocalConnectorActivator$LocalConnectorHelper.initConnectorAddress(LocalConnectorActivator.java:55)
	at com.ibm.ws.jmx.connector.local.LocalConnectorActivator$LocalConnectorHelper.<clinit>(LocalConnectorActivator.java:45)
	at com.ibm.ws.jmx.connector.local.LocalConnectorActivator.createJmxAddressResource(LocalConnectorActivator.java:208)
	at com.ibm.ws.jmx.connector.local.LocalConnectorActivator.createJMXWorkAreaResource(LocalConnectorActivator.java:200)
	at com.ibm.ws.jmx.connector.local.LocalConnectorActivator.setLocationService(LocalConnectorActivator.java:176)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.felix.scr.impl.inject.methods.BaseMethod.invokeMethod(BaseMethod.java:228)
	at org.apache.felix.scr.impl.inject.methods.BaseMethod.access$500(BaseMethod.java:41)
	at org.apache.felix.scr.impl.inject.methods.BaseMethod$Resolved.invoke(BaseMethod.java:664)
	at org.apache.felix.scr.impl.inject.methods.BaseMethod.invoke(BaseMethod.java:510)
	at org.apache.felix.scr.impl.inject.methods.BindMethod.invoke(BindMethod.java:42)
	at org.apache.felix.scr.impl.manager.DependencyManager.doInvokeBindMethod(DependencyManager.java:1813)
	at org.apache.felix.scr.impl.manager.DependencyManager.bindDependency(DependencyManager.java:1637)
	at org.apache.felix.scr.impl.manager.DependencyManager.bind(DependencyManager.java:1624)
	at org.apache.felix.scr.impl.manager.SingleComponentManager.createImplementationObject(SingleComponentManager.java:307)
	at org.apache.felix.scr.impl.manager.SingleComponentManager.createComponent(SingleComponentManager.java:114)
	at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:982)
	at org.apache.felix.scr.impl.manager.SingleComponentManager.getServiceInternal(SingleComponentManager.java:955)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.activateInternal(AbstractComponentManager.java:765)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.enableInternal(AbstractComponentManager.java:666)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.enable(AbstractComponentManager.java:432)
	at org.apache.felix.scr.impl.manager.ConfigurableComponentHolder.enableComponents(ConfigurableComponentHolder.java:665)
	at org.apache.felix.scr.impl.BundleComponentActivator.initialEnable(BundleComponentActivator.java:338)
	at org.apache.felix.scr.impl.Activator.loadComponents(Activator.java:382)
	at org.apache.felix.scr.impl.Activator.access$200(Activator.java:49)
	at org.apache.felix.scr.impl.Activator$ScrExtension.start(Activator.java:264)
	at org.apache.felix.scr.impl.AbstractExtender.createExtension(AbstractExtender.java:196)
	at org.apache.felix.scr.impl.AbstractExtender.modifiedBundle(AbstractExtender.java:169)
	at org.apache.felix.scr.impl.AbstractExtender.modifiedBundle(AbstractExtender.java:49)
	at org.osgi.util.tracker.BundleTracker$Tracked.customizerModified(BundleTracker.java:488)
	at org.osgi.util.tracker.BundleTracker$Tracked.customizerModified(BundleTracker.java:1)
	at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:232)
	at org.osgi.util.tracker.BundleTracker$Tracked.bundleChanged(BundleTracker.java:450)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:973)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEventPrivileged(EquinoxEventPublisher.java:234)
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher$1.run(EquinoxEventPublisher.java:145)
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher$1.run(EquinoxEventPublisher.java:1)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:647)
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:142)
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:132)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor.publishModuleEvent(EquinoxContainerAdaptor.java:231)
	at org.eclipse.osgi.container.Module.publishEvent(Module.java:498)
	at org.eclipse.osgi.container.Module.start(Module.java:485)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1844)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$2$1.execute(EquinoxContainerAdaptor.java:150)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1837)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1780)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1742)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1664)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)
```
