### ISSUE TITLE
NPE in com.ibm.ws.logging.internal.impl.BaseTraceService$TrOutputStream.flush(BaseTraceService.java:1383)

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#7792]
RTC 262181

```
Caused by: java.lang.NullPointerException
at com.ibm.ws.logging.internal.impl.BaseTraceService$TrOutputStream.flush(BaseTraceService.java:1383)
at java.base/java.io.PrintStream.write(PrintStream.java:561)
at org.apache.felix.gogo.runtime.threadio.ThreadPrintStream.write(ThreadPrintStream.java:91)
at java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:233)
```

**Comment by AidanPolese** [comment]
closed as non-reproducible for now

**Comment by fmhwong** [comment]
Occurred again on 7/03 and 7/11

**Comment by AidanPolese** [comment]
Closing this issue as it was incorrectly triaged.
