### ISSUE TITLE
config REST endpoint not generating output for library/folder correctly

### ISSUE THREAD

**Issue by njr-11** [OpenLiberty/open-liberty#7811]
@frowe noted the following issues when experimenting with the /config/ REST endpoint on the library/folder elements,

1) If I have config element like:
```
    <library>
        <folder dir="/tmp" id="1"></folder>
    </library>
```
I get this output, but the folder output seems incorrect?
```
   {
      "configElementName": "library",
      "uid": "com.ibm.ws.classloading.sharedlibrary_1",
      "id": "com.ibm.ws.classloading.sharedlibrary_1",
      "apiTypeVisibility": "spec,ibm-api,api,stable",
      "folderRef": [
         "com.ibm.ws.classloading.sharedlibrary.folder_2"
      ]
   },
```
2) for the config snippet
```
    <library id="1">
        <folder dir="/tmp" id="1"></folder>
    </library>
    <library id="2">
        <folder dir="/tmp/" id="2"></folder>
    </library>
```
I get this output:
```
   {
      "configElementName": "library",
      "uid": "com.ibm.ws.classloading.sharedlibrary_1",
      "id": "com.ibm.ws.classloading.sharedlibrary_1",
      "apiTypeVisibility": "spec,ibm-api,api,stable",
      "folderRef": [
         "com.ibm.ws.classloading.sharedlibrary.folder_2"
      ]
   },
   {
      "configElementName": "library",
      "uid": "2",
      "id": "2",
      "apiTypeVisibility": "spec,ibm-api,api,stable",
      "folderRef": [
         {
            "configElementName": "folder",
            "uid": "library[2]\/folder[2]",
            "id": "2",
            "dir": "\/tmp\/"
         }
      ]
   },
```
In this case, the second element looks correct, at least the folder element portion, but the uid of the second element and the entire first element seems totally wrong.
 
3)  for the snippet
```
    <library>
        <folder dir="/tmp" id="1"></folder>
    </library>
    <library>
        <folder dir="/tmp/" id="2"></folder>
    </library>
```
I got output :
```
   {
      "configElementName": "library",
      "uid": "com.ibm.ws.classloading.sharedlibrary_1",
      "id": "com.ibm.ws.classloading.sharedlibrary_1",
      "apiTypeVisibility": "spec,ibm-api,api,stable",
      "folderRef": [
         "com.ibm.ws.classloading.sharedlibrary.folder_2"
      ]
   },
```
based on my understanding of config, those should be two distinct elements and not one as shown in the output?

**Comment by frowe** [comment]
Please look at issue https://github.com/OpenLiberty/open-liberty/issues/7732 before starting debug.  It is possible the failure of the library element to have a correct uid as described in that issue could cause some of the above problems.

**Comment by njr-11** [comment]
Here are the results of an experiment where I attempted to remove the erroneously-specified default id value from the library element.

The errors occur on the path where nested library element is used and has no id, such as,
```
    <jdbcDriver id="FATJDBCDriver1">
      <library filesetRef="FATfileset1"/>
    </jdbcDriver>
```

```
Exception = org.osgi.framework.InvalidSyntaxException
Source = com.ibm.ws.library.internal.SharedLibraryImpl
probeid = 112
Stack Dump = org.osgi.framework.InvalidSyntaxException: Invalid value at "(library)[default-0])(libraryRef=*com.ibm.ws.classloading.sharedlibrary_89*)))": (&(objectClass=com.ibm.wsspi.library.LibraryChangeListener)(|(library=jdbcDriver[FATJDBCDriver1]//com.ibm.ws.classloading.sharedlibrary(library)[default-0])(libraryRef=*com.ibm.ws.classloading.sharedlibrary_89*)))
	at org.eclipse.osgi.internal.framework.FilterImpl$Parser.parse_substring(FilterImpl.java:1706)
	at org.eclipse.osgi.internal.framework.FilterImpl$Parser.parse_item(FilterImpl.java:1613)
	at org.eclipse.osgi.internal.framework.FilterImpl$Parser.parse_filtercomp(FilterImpl.java:1519)
	at org.eclipse.osgi.internal.framework.FilterImpl$Parser.parse_filter(FilterImpl.java:1485)
	at org.eclipse.osgi.internal.framework.FilterImpl$Parser.parse_or(FilterImpl.java:1553)
	at org.eclipse.osgi.internal.framework.FilterImpl$Parser.parse_filtercomp(FilterImpl.java:1512)
	at org.eclipse.osgi.internal.framework.FilterImpl$Parser.parse_filter(FilterImpl.java:1485)
	at org.eclipse.osgi.internal.framework.FilterImpl$Parser.parse_and(FilterImpl.java:1534)
	at org.eclipse.osgi.internal.framework.FilterImpl$Parser.parse_filtercomp(FilterImpl.java:1508)
	at org.eclipse.osgi.internal.framework.FilterImpl$Parser.parse_filter(FilterImpl.java:1485)
	at org.eclipse.osgi.internal.framework.FilterImpl$Parser.parse(FilterImpl.java:1464)
	at org.eclipse.osgi.internal.framework.FilterImpl.newInstance(FilterImpl.java:150)
	at org.eclipse.osgi.internal.framework.FilterImpl.newInstance(FilterImpl.java:146)
	at org.osgi.framework.FrameworkUtil.createFilter(FrameworkUtil.java:72)
	at com.ibm.ws.library.internal.SharedLibraryImpl.update(SharedLibraryImpl.java:110)
	at com.ibm.ws.library.internal.SharedLibraryFactory.updated(SharedLibraryFactory.java:242)
	at com.ibm.ws.config.admin.internal.ManagedServiceFactoryTracker$2.run(ManagedServiceFactoryTracker.java:267)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.ibm.ws.config.admin.internal.UpdateQueue$Queue.run(UpdateQueue.java:66)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:825)
```

This leads to the following in the log,
```
[6/25/19, 0:48:02:115 UTC] 0000001f com.ibm.ws.logging.internal.impl.IncidentImpl                I FFDC1015I: An FFDC Incident has been created: "org.osgi.framework.InvalidSyntaxException: Invalid value at "(library)[default-0])(libraryRef=*com.ibm.ws.classloading.sharedlibrary_90*)))": (&(objectClass=com.ibm.wsspi.library.LibraryChangeListener)(|(library=jdbcDriver[FATJDBCDriver]//com.ibm.ws.classloading.sharedlibrary(library)[default-0])(libraryRef=*com.ibm.ws.classloading.sharedlibrary_90*))) com.ibm.ws.library.internal.SharedLibraryImpl 112" at ffdc_19.06.25_00.48.02.0.log

[6/25/19, 0:48:02:118 UTC] 0000001f com.ibm.ws.library.internal.SharedLibraryImpl                E CWWKL0006E: A shared library has an invalid ID [jdbcDriver[FATJDBCDriver]//com.ibm.ws.classloading.sharedlibrary(library)[default-0]] due to error [org.osgi.framework.InvalidSyntaxException: Invalid value at "(library)[default-0])(libraryRef=*com.ibm.ws.classloading.sharedlibrary_90*)))": (&(objectClass=com.ibm.wsspi.library.LibraryChangeListener)(|(library=jdbcDriver[FATJDBCDriver]//com.ibm.ws.classloading.sharedlibrary(library)[default-0])(libraryRef=*com.ibm.ws.classloading.sharedlibrary_90*)))] 
```

Here is the nls message info:
```
cls.library.id.invalid=CWWKL0006E: A shared library has an invalid ID [{0}] due to error [{1}] 
cls.library.id.invalid.explanation=To specify the ID for a shared library in the server configuration, you must follow attribute naming conventions.
cls.library.id.invalid.useraction=Edit the server configuration and modify the ID attribute of the library element.
```

Here is the code that raises it, within com.ibm.ws.library.internal.SharedLibraryImpl.update(Dictionary<String, Object>)
```
        if (libraryListenersTracker == null) {
            //set up a tracker for notification listeners for this library
            Filter listenerFilter = null;
            // To better support parent first nested config, also filter on libraryRef,
            // which will be a list of pid (or, if cardinality=0, then just a pid).
            try {
                listenerFilter = FrameworkUtil.createFilter("(&(objectClass=" + LibraryChangeListener.class.getName() +
                                                            ")(|(library=" + instanceId + ")(libraryRef=*" + instancePid + "*)))");
            } catch (InvalidSyntaxException e) {
                //auto FFDC because the syntax shouldn't be wrong!
                Tr.error(tc, "cls.library.id.invalid", instanceId, e.toString());
            }

            ServiceTracker<LibraryChangeListener, LibraryChangeListener> tracker;
            tracker = new ServiceTracker<LibraryChangeListener, LibraryChangeListener>(this.ctx, listenerFilter, null);
            tracker.open();
            libraryListenersTracker = tracker;
        }
```

**Comment by njr-11** [comment]
First issue appears to be fixed now:
```
{
      "configElementName": "library",
      "uid": "library[default-0]",
      "apiTypeVisibility": "spec,ibm-api,api,stable",
      "folderRef": [
         {
            "configElementName": "folder",
            "uid": "library[default-0]/folder[1]",
            "id": "1",
            "dir": "/tmp"
         }
      ]
   }
```

Second issue is also fixed now:
```
   {
      "configElementName": "library",
      "uid": "1",
      "id": "1",
      "apiTypeVisibility": "spec,ibm-api,api,stable",
      "folderRef": [
         {
            "configElementName": "folder",
            "uid": "library[1]/folder[1]",
            "id": "1",
            "dir": "/tmp"
         }
      ]
   },
   {
      "configElementName": "library",
      "uid": "2",
      "id": "2",
      "apiTypeVisibility": "spec,ibm-api,api,stable",
      "folderRef": [
         {
            "configElementName": "folder",
            "uid": "library[2]/folder[2]",
            "id": "2",
            "dir": "/tmp/"
         }
      ]
   },
```

And also fixed for issue 3,
```
   {
      "configElementName": "library",
      "uid": "library[default-0]",
      "apiTypeVisibility": "spec,ibm-api,api,stable",
      "folderRef": [
         {
            "configElementName": "folder",
            "uid": "library[default-0]/folder[1]",
            "id": "1",
            "dir": "/tmp"
         }
      ]
   },
   {
      "configElementName": "library",
      "uid": "library[default-1]",
      "apiTypeVisibility": "spec,ibm-api,api,stable",
      "folderRef": [
         {
            "configElementName": "folder",
            "uid": "library[default-1]/folder[2]",
            "id": "2",
            "dir": "/tmp/"
         }
      ]
   },
```
