### ISSUE TITLE
Timing issue between deleted configuration and configuration store

### ISSUE THREAD

**Issue by tjwatson** [OpenLiberty/open-liberty#7831]
The following FFDC is possible
```
Stack Dump = java.lang.IllegalStateException: Configuration pid com.ibm.ws.security.authentication.internal.jaas.jaasLoginContextEntry_93 was deleted.
at com.ibm.ws.config.admin.internal.ExtendedConfigurationImpl.exceptionIfDeleted(ExtendedConfigurationImpl.java:666)
at com.ibm.ws.config.admin.internal.ExtendedConfigurationImpl.getReadOnlyProperties(ExtendedConfigurationImpl.java:337)
at com.ibm.ws.config.admin.internal.ConfigurationStorageHelper.store(ConfigurationStorageHelper.java:153)
at com.ibm.ws.config.admin.internal.ConfigurationStore.saveConfigurationDatas(ConfigurationStore.java:225)
at com.ibm.ws.config.admin.internal.ConfigurationStore.run(ConfigurationStore.java:283)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:825)
```

This happens if the configuration store thread is in the process of saving configurations and one of the configurations is deleted.  The ConfigurationStore will likely need to snapshot the dictionaries to save  and cache the IllegalStateException in this case.

**Comment by marikaj123** [comment]
Waiting for the fix to make the GM build and then getting it verified and closed.

**Comment by marikaj123** [comment]
@tjwatson - Has the fix make it into the release build?  If yes, please verify and close the issue.  Thank you.

**Comment by tjwatson** [comment]
Fix is in the release build.
