### ISSUE TITLE
Test Failure: junit.framework.TestSuite.com.ibm.ws.logging.fat.RealFlushTest

### ISSUE THREAD

**Issue by Erikkre** [OpenLiberty/open-liberty#8035]
#link 263952

com.ibm.ws.logging.fat.RealFlushTest:componenttest.exception.TopologyException: Timed out waiting for application [RealFlushTestApp] to start.
at componenttest.topology.impl.LibertyServer.validateAppsLoaded(LibertyServer.java:1614)
at componenttest.topology.impl.LibertyServer.validateServerStarted(LibertyServer.java:2143)
at componenttest.topology.impl.LibertyServer.startServerWithArgs(LibertyServer.java:1435)
at componenttest.topology.impl.LibertyServer.startServerAndValidate(LibertyServer.java:1048)
at componenttest.topology.impl.LibertyServer.startServerAndValidate(LibertyServer.java:1030)
at componenttest.topology.impl.LibertyServer.startServerAndValidate(LibertyServer.java:1017)
at componenttest.topology.impl.LibertyServer.startServer(LibertyServer.java:865)
at com.ibm.ws.logging.fat.RealFlushTest.setUp(RealFlushTest.java:51)
at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:314)
at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:167)

**Comment by Erikkre** [comment]
Updated RealFlushServer's server.xml to older features supported by the Java 7 that is used
