### ISSUE TITLE
Unable to write multipart data in Jax-Rs

### ISSUE THREAD

**Issue by rosczja** [OpenLiberty/open-liberty#8048]
I cannot find any way to write a multipart/mixed or multipart/form-data response with jax-rs. If I use a java.util.Map with DataSource entities I reach the writeTo method of the IBMMultipartProvider which in turn calls the writeTo method of the Apache CXF MultipartProvider. Then a NullPointer is raised because the MessageContext is not set.

I would like two things:

- Provide API tro create IMultiPartBody and / or IAttachment classes
- set the message context when constructing the Apache CXF MultiPartProvider

**Comment by WhiteCat22** [comment]
I'm sorry if this is an obvious question, but are you adding 
```@Produces("multipart/form-data")```
to your resource method?

**Comment by andymc12** [comment]
Hi @rosczja - do you have a sample app that reproduces the problem that we could view?  Also, could you provide the log files that show the NPE and the version of Liberty in use?  Thanks!

**Comment by rosczja** [comment]
@WhiteCat22 , I think adding this annotation will not help with the nullpointer.

Here is the exception:
```
java.lang.NullPointerException: null
	at org.apache.cxf.jaxrs.provider.MultipartProvider.writeTo(MultipartProvider.java:265) ~[com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2_1.0.22.jar:3.2.6]
	at com.ibm.ws.jaxrs20.providers.multipart.IBMMultipartProvider.writeTo(IBMMultipartProvider.java:164) ~[com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2_1.0.22.jar:3.2.6]
	at org.apache.cxf.jaxrs.utils.JAXRSUtils$3.run(JAXRSUtils.java:1424) ~[com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2_1.0.22.jar:3.2.6]
	at org.apache.cxf.jaxrs.utils.JAXRSUtils$3.run(JAXRSUtils.java:1421) ~[com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2_1.0.22.jar:3.2.6]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_172]
	at org.apache.cxf.jaxrs.utils.JAXRSUtils.writeMessageBody(JAXRSUtils.java:1421) ~[com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2_1.0.22.jar:3.2.6]
	at org.apache.cxf.jaxrs.interceptor.JAXRSOutInterceptor.serializeMessage(JAXRSOutInterceptor.java:249) [com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2_1.0.22.jar:3.2.6]
	at org.apache.cxf.jaxrs.interceptor.JAXRSOutInterceptor.processResponse(JAXRSOutInterceptor.java:124) [com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2_1.0.22.jar:3.2.6]
	at org.apache.cxf.jaxrs.interceptor.JAXRSOutInterceptor.handleMessage(JAXRSOutInterceptor.java:85) [com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2_1.0.22.jar:3.2.6]
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308) [com.ibm.ws.org.apache.cxf.cxf.core.3.2_1.0.22.jar:3.2.6]
	at org.apache.cxf.interceptor.OutgoingChainInterceptor.handleMessage(OutgoingChainInterceptor.java:90) [com.ibm.ws.org.apache.cxf.cxf.core.3.2_1.0.22.jar:3.2.6]
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308) [com.ibm.ws.org.apache.cxf.cxf.core.3.2_1.0.22.jar:3.2.6]
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:124) [com.ibm.ws.org.apache.cxf.cxf.core.3.2_1.0.22.jar:3.2.6]
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:274) [com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.3.2_1.0.22.jar:3.2.6]
	at com.ibm.ws.jaxrs20.endpoint.AbstractJaxRsWebEndpoint.invoke(AbstractJaxRsWebEndpoint.java:134) [com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2_1.0.22.jar:3.2.6]
	at com.ibm.websphere.jaxrs.server.IBMRestServlet.handleRequest(IBMRestServlet.java:146) [com.ibm.ws.jaxrs.2.0.server_1.0.22.jar:?]
	at com.ibm.websphere.jaxrs.server.IBMRestServlet.doPost(IBMRestServlet.java:104) [com.ibm.ws.jaxrs.2.0.server_1.0.22.jar:?]

```

**Comment by rosczja** [comment]
@andymc12 I cannot provide parts of my app as this is an in-house company app. But basically I am creating a java.util.Map, with MediaType as key and one DataSource and one InputStream as values.

I am using OpenLiberty 18.0.0.4

**Comment by andymc12** [comment]
@rosczja Can you replace (back up your originals first) the files in the `wlp/lib` directory with these?

This includes a test fix to IBMMultipartProvider.java (for both jaxrs-2.0 and 2.1) that sets the messageContext in CXF's MultipartProvider.  I believe that is what is null based on the stack trace.  I can see that it is set in the readFrom method flow, but not the writeTo flow.  This fixes that.


[multipart-fix.zip](https://github.com/OpenLiberty/open-liberty/files/3336412/multipart-fix.zip)

After you replace these files, please restart the server using the `--clean` option and see if that resolves the problem.  Thanks, and good luck!

**Comment by rosczja** [comment]
@andymc12 Very cool. Thank you. It works :-)
