### ISSUE TITLE
Test Failure: org.eclipse.microprofile.opentracing.tck.ClientRegistrarTests.testClientRegistrar (Could not start container on zOS)

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#8269]
RTC 261444

```
testClientRegistrar

      org.jboss.arquillian.container.spi.client.container.LifecycleException: Could not start container
at io.openliberty.arquillian.managed.WLPManagedContainer.start(WLPManagedContainer.java:282)
at org.jboss.arquillian.container.impl.ContainerImpl.start(ContainerImpl.java:199)
at org.jboss.arquillian.container.impl.client.container.ContainerLifecycleController$8.perform(ContainerLifecycleController.java:163)
at org.jboss.arquillian.container.impl.client.container.ContainerLifecycleController$8.perform(ContainerLifecycleController.java:157)
at org.jboss.arquillian.container.impl.cålient.container.ContainerLifecycleController.forContainer(ContainerLifecycleController.java:255)
at org.jboss.arquillian.container.impl.client.container.ContainerLifecycleController.startContainer(ContainerLifecycleController.java:156)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
at java.lang.reflect.Method.invoke(Method.java:508)
at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:96)
at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:103)
at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:85)
at org.jboss.arquillian.container.impl.client.ContainerDeploymentContextHandler.createContainerContext(ContainerDeploymentContextHandler.java:57)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
at java.lang.reflect.Method.invoke(Method.java:508)
at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:96)
at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:92)
at org.jboss.arquillia
Occurred on the following Platforms:
Liberty z/OS Platform Build - 20190312-0223
Liberty z/OS Platform Build - 20190309-0227
Liberty z/OS Platform Build - 20190310-1826
Liberty z/OS Platform Build - 20190311-1656
Liberty z/OS Platform Build - 20190313-0225
```

**Comment by tonyreigns** [comment]
Closed issue due to not having recently occurred.
