### ISSUE TITLE
OIDC provider may get exception using Oracle database: ORA-00933: SQL command not properly ended

### ISSUE THREAD

**Issue by barbj** [OpenLiberty/open-liberty#8357]
When using an OIDC provider with an Oracle database, the following exception can be observed during cache cleanup:

java.sql.SQLSyntaxErrorException: ORA-00933: SQL command not properly ended

    at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:494)
    at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:446)
    at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1052)
    at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:537)
    at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:255)
    at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:610)
    at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:253)
    at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:86)
    at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:928)
    at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1136)
    at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3640)
    at oracle.jdbc.driver.T4CPreparedStatement.executeInternal(T4CPreparedStatement.java:1384)
    at oracle.jdbc.driver.OraclePreparedStatement.execute(OraclePreparedStatement.java:3752)
    at oracle.jdbc.driver.OraclePreparedStatementWrapper.execute(OraclePreparedStatementWrapper.java:1079)
    at com.ibm.ws.rsadapter.jdbc.WSJdbcPreparedStatement.execute(WSJdbcPreparedStatement.java:391)
    at com.ibm.ws.security.oauth20.plugins.db.DBConsentCache$CleanupThread.runCleanup(DBConsentCache.java:382)
    at com.ibm.ws.security.oauth20.plugins.db.DBConsentCache$CleanupThread.run(DBConsentCache.java:315)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:522)
    at java.util.concurrent.FutureTask.run(FutureTask.java:277)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.lang.Thread.run(Thread.java:812)
Caused by: Error : 933, Position : 83, Sql = DELETE FROM OAuthDBSchema.OAUTH20CONSENTCACHE WHERE EXPIRES > 0 AND EXPIRES <= :1  LIMIT 250, OriginalSql = DELETE FROM OAuthDBSchema.OAUTH20CONSENTCACHE WHERE EXPIRES > 0 AND EXPIRES <= ? LIMIT 250, Error Msg = ORA-00933: SQL command not properly ended

    at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:498)
    ... 21 more

**Comment by barbj** [comment]
fixed by #8360
