### ISSUE TITLE
PushBuilder should ignore headers with null values

### ISSUE THREAD

**Issue by wtlucy** [OpenLiberty/open-liberty#8474]
The Servlet 4 PushBuilder should ignore (not add) headers that are added via the `addHeader(String name, String value)` API [1].  Currently, passing headers with null values to a push request can result in the following `NullPointerException`:

```
java.lang.NullPointerException
    at com.ibm.ws.http.channel.h2internal.hpack.H2HeaderTable.getHeaderEntry(H2HeaderTable.java:41)
    at com.ibm.ws.http.channel.h2internal.hpack.H2Headers.encodeHeader(H2Headers.java:353)
    at com.ibm.ws.http.channel.h2internal.hpack.H2Headers.encodeHeader(H2Headers.java:320)
    at com.ibm.ws.http.channel.internal.HttpRequestMessageImpl.pushNewRequest(HttpRequestMessageImpl.java:2066)
    at com.ibm.ws.http.dispatcher.internal.channel.HttpRequestImpl.pushNewRequest(HttpRequestImpl.java:214)
    at com.ibm.ws.webcontainer40.srt.http.HttpPushBuilder.push(HttpPushBuilder.java:289)
```

[1] https://javaee.github.io/javaee-spec/javadocs/javax/servlet/http/PushBuilder.html#addHeader-java.lang.String-java.lang.String-

**Comment by mah454** [comment]
Hey , I have this problem too . 
https://stackoverflow.com/questions/57356717/liberty-null-pointer-exception/57361812#57361812
