### ISSUE TITLE
URBridgeEntity uses NLS message key, REQUIRED_IDENTIFIERS_MISSING, which is not defined

### ISSUE THREAD

**Issue by jvanhill** [OpenLiberty/open-liberty#8482]
The URBridgeEntity class uses NLS message key, REQUIRED_IDENTIFIERS_MISSING, which is not defined. It results in an message such as the one below being produced, and is not helpful:

```
Caused by: com.ibm.wsspi.security.wim.exception.WIMApplicationException: REQUIRED_IDENTIFIERS_MISSING
	at com.ibm.ws.security.wim.adapter.urbridge.utils.URBridgeEntity.getUniqueId(URBridgeEntity.java:216)
	at com.ibm.ws.security.wim.adapter.urbridge.utils.URBridgeEntity.setIdentifierProperties(URBridgeEntity.java:190)
	... 136 more
```

The new message will look like the following:

```
Caused by: com.ibm.wsspi.security.wim.exception.WIMApplicationException: CWIML3001W: The required identifiers for the entity are missing.
	at com.ibm.ws.security.wim.adapter.urbridge.utils.URBridgeEntity.getUniqueId(URBridgeEntity.java:216)
	at com.ibm.ws.security.wim.adapter.urbridge.utils.URBridgeEntity.setIdentifierProperties(URBridgeEntity.java:190)
	... 136 more
```

**Comment by kristip17** [comment]
I found the message in the equivalent message in WebSphere Application Server code base. I will copy it over to Liberty.
