### ISSUE TITLE
Problem with error handling in AccessTokenAuthenticator.parseJwtToken

### ISSUE THREAD

**Issue by barbj** [OpenLiberty/open-liberty#8515]
com.ibm.ws.security.openidconnect.client.AccessTokenAuthenticator.parseJwtToken 
expects an exception if there is an error, but com.ibm.ws.security.openidconnect.client.jose4j.util.Jose4jUtil.createResultWithJose4JForJwt 
doesn't throw an exception if there is an error.

**Comment by barbj** [comment]
Here is a stack from a trace:

`[8/6/19 13:21:20:497 BST] 00000088 id=3592c792 curity.openidconnect.token.JWTTokenValidationFailedException < <init> Exit  
                                                                                                               com.ibm.ws.security.openidconnect.token.JWTTokenValidationFailedException: CWWKS1773E: Validation failed for the token requested by [CLIENT99] because the token is outside of its valid range. This might have been caused by either the current time [2019-08-06T12:21:20.462Z] being after the token expiration time [2019-08-01T17:37:26.000Z] or the issue time [1970-01-01T00:00:00.000Z] being too far away from the current time [2019-08-06T12:21:20.462Z].
	at com.ibm.ws.security.openidconnect.token.JWTTokenValidationFailedException.format(JWTTokenValidationFailedException.java:38)
	at com.ibm.ws.security.openidconnect.common.OidcCommonClientRequest.errorCommon(OidcCommonClientRequest.java:82)
	at com.ibm.ws.security.openidconnect.jose4j.Jose4jValidator.parseJwtWithValidation(Jose4jValidator.java:181)	FFDCIgnore
	at com.ibm.ws.security.openidconnect.client.jose4j.util.Jose4jUtil.parseJwtWithValidation(Jose4jUtil.java:341)		FFDCIgnore
	at com.ibm.ws.security.openidconnect.client.jose4j.util.Jose4jUtil.createResultWithJose4JForJwt(Jose4jUtil.java:415)	FFDCIgnore
	at com.ibm.ws.security.openidconnect.client.AccessTokenAuthenticator.parseJwtToken(AccessTokenAuthenticator.java:428) No FFDCIgnore, however, 
the invocation is inside a try/catch
	at com.ibm.ws.security.openidconnect.client.internal.OidcClientImpl.authenticate(OidcClientImpl.java:365)
....
`

- The `exception during introspectionToken` debug text that is in the catch block in createResultWithJose4JForJwt is nowhere in the trace.
- The PROPAGATION_TOKEN_INTERNAL_ERR that is in the catch block in createResultWithJose4JForJwt also isn't in the trace.
- PROPAGATION_TOKEN_INTERNAL_ERR=CWWKS1727E: The resource server failed the authentication request because it cannot validate the access token due to an error [{0}]. The validation method is [{1}], and the validation endpoint url is [{2}].

**Comment by brutif** [comment]
looks like the catch block in A.T.A.java just needs to be removed.  Catch and log is in Jose4jUtil:451

**Comment by brutif** [comment]
resolved by #8847
