### ISSUE TITLE
WELD-001408: Unsatisfied dependencies for type HAMProperties with qualifiers @Default

### ISSUE THREAD

**Issue by toshiyamamoto** [OpenLiberty/open-liberty#853]
When appSecurity-3.0 feature is enabled, but there is no JSR375 annotation in a war file, we get the following error:

```
Stack Dump = org.jboss.weld.exceptions.DeploymentException: WELD-001408: Unsatisfied dependencies for type HAMProperties with qualifiers @Default
  at injection point [BackedAnnotatedField] @Inject private com.ibm.ws.security.javaeesec.cdi.beans.BasicHttpAuthenticationMechanism.hamp
  at com.ibm.ws.security.javaeesec.cdi.beans.BasicHttpAuthenticationMechanism.hamp(BasicHttpAuthenticationMechanism.java:0)
  at org.jboss.weld.bootstrap.Validator.validateInjectionPointForDeploymentProblems(Validator.java:375)
  at org.jboss.weld.bootstrap.Validator.validateInjectionPoint(Validator.java:287)
  at org.jboss.weld.bootstrap.Validator.validateGeneralBean(Validator.java:140)
  at org.jboss.weld.bootstrap.Validator.validateRIBean(Validator.java:161)
  at org.jboss.weld.bootstrap.Validator.validateBean(Validator.java:518)
  at org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:63)
  at org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:61)
  at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:62)
  at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:55)
  at java.util.concurrent.FutureTask.run(FutureTask.java:277)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1153)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
  at java.lang.Thread.run(Thread.java:785)
```

**Comment by toshiyamamoto** [comment]
PR#855 was created.

**Comment by aguibert** [comment]
@toshiyamamoto I've verified that PR #855 fixes this issue, thanks!

This allows us to add appSecurity-3.0 into the EE8 convenience features, which I am doing in PR #916
