### ISSUE TITLE
Test Failure: com.ibm.ws.rest.handler.config.fat.ConfigOpenApiSchemaTest.testConfigOpenAPIAsJSON and com.ibm.ws.rest.handler.validator.fat.ValidateOpenApiSchemaTest.testAllValidatorsAsJSON

### ISSUE THREAD

**Issue by nmittles** [OpenLiberty/open-liberty#8688]
Windows only bug where the path for Class.getResourceAsStream("/META-INF/openapi.yaml") was incorrect due to using the Windows File.separator().

java.lang.Exception: 2019-08-20-13:44:05:198 Unexpected response (See HTTP_* constant values on HttpURLConnection): 500
    at componenttest.topology.utils.HttpsRequest.run(HttpsRequest.java:217)
    at com.ibm.ws.rest.handler.config.fat.ConfigOpenApiSchemaTest.testConfigOpenAPIAsJSON(ConfigOpenApiSchemaTest.java:70)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:193)
    at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:314)
    at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:167)

**Comment by nmittles** [comment]
Merged fix under pull:
https://github.com/OpenLiberty/open-liberty/pull/8689
