### ISSUE TITLE
Failure to parse multiple comma separated links in an HTTP Link header on a Jaxrs Response object

### ISSUE THREAD

**Issue by WhiteCat22** [OpenLiberty/open-liberty#8863]
Parsing multiple comma separated links in a HTTP Link header on a Jaxrs Response object throws the following error:

java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: Illegal character in authority at index 7: http://test>;rel="first",<http://test>;rel="next",<http:test
	at org.apache.cxf.jaxrs.impl.UriBuilderImpl.uri(UriBuilderImpl.java:896)
	at javax.ws.rs.core.UriBuilder.fromUri(UriBuilder.java:119)
	at org.apache.cxf.jaxrs.impl.LinkBuilderImpl.link(LinkBuilderImpl.java:90)
	at javax.ws.rs.core.Link.valueOf(Link.java:173)
	at org.apache.cxf.jaxrs.impl.ResponseImpl.getAllLinks(ResponseImpl.java:364)
	at org.apache.cxf.jaxrs.impl.ResponseImpl.getLinks(ResponseImpl.java:354)
	at com.ibm.ws.jaxrs.fat.linkheader.ClientTestServlet.testResponseSingleLinkHeaderMultipleLinks(ClientTestServlet.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at componenttest.app.FATServlet.doGet(FATServlet.java:71)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1230)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:729)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:426)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1218)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1002)
	at com.ibm.ws.webcontainer.servlet.CacheServletWrapper.handleRequest(CacheServletWrapper.java:75)
	at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:938)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:279)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1136)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:417)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:376)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:547)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:481)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:346)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.ready(HttpInboundLink.java:317)
	at com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.sendToDiscriminators(NewConnectionInitialReadCallback.java:165)
	at com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.complete(NewConnectionInitialReadCallback.java:74)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:503)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueManager.java:573)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:954)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:1043)
	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:239)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: Illegal character in authority at index 7: http://test>;rel="first",<http://test>;rel="next",<http:test
	at java.net.URI.create(URI.java:852)
	at org.apache.cxf.jaxrs.impl.UriBuilderImpl.uri(UriBuilderImpl.java:893)
	... 38 more
Caused by: java.net.URISyntaxException: Illegal character in authority at index 7: http://test>;rel="first",<http://test>;rel="next",<http:test
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.parseAuthority(URI.java:3186)
	at java.net.URI$Parser.parseHierarchical(URI.java:3097)
	at java.net.URI$Parser.parse(URI.java:3053)
	at java.net.URI.<init>(URI.java:588)
	at java.net.URI.create(URI.java:850)
	... 39 more

Example header:
Link=[<http://test>;rel="first",<http://test>;rel="next",<http:test>;rel="last"]

**Comment by WhiteCat22** [comment]
Fix has been merged into the master branch
