### ISSUE TITLE
Test Failure: com.ibm.ws.logging.json.fat.JsonConfigTest.testJsonFieldExtensions

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#8913]
RTC 267367

```
testJsonFieldExtensions:junit.framework.AssertionFailedError: 2019-09-10-21:29:43:668 Cannot find \{.*Correct_bool123.*\}
at com.ibm.ws.logging.json.fat.JsonConfigTest.checkLine(JsonConfigTest.java:318)
at com.ibm.ws.logging.json.fat.JsonConfigTest.testJsonFieldExtensions(JsonConfigTest.java:236)
at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:193)
at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:314)
at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:167)

```

**Comment by Yushan-Lin** [comment]
https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_TIIuMNdWEemLrPck_nv5Ag&tab=com.ibm.team.build.web.ui.internal.editors.result.test.TestProvider
New build passes JsonConfigTest with update FAT changes
