### ISSUE TITLE
Test Failure: com.ibm.ws.logging.fat.JSONFieldsTest.testMessageFieldNamesEnv

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#8914]
RTC 267368

```
testMessageFieldNamesEnv:junit.framework.AssertionFailedError: 2019-09-10-20:49:02:438 The message field name was not formatted in the new configuration in messages.log.
at com.ibm.ws.logging.fat.JSONFieldsTest.testMessageFieldNamesEnv(JSONFieldsTest.java:77)
at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:193)
at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:314)
at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:167)
```

**Comment by Yushan-Lin** [comment]
https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_TIIuMNdWEemLrPck_nv5Ag&tab=com.ibm.team.build.web.ui.internal.editors.result.test.TestProvider
New build passes JSONFieldsTest with update FAT changes
