### ISSUE TITLE
"third-party" apiTypeVisibility not working

### ISSUE THREAD

**Issue by mikecai** [OpenLiberty/open-liberty#8957]
According to [https://www.ibm.com/support/knowledgecenter/en/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/twlp_classloader_3p_apis.html](url), if I create a `<classloader>` configuration for my `<webApplication>` and set the `@apiTypeVisibility="+third-party"`, seems I should be able to access third-party libraries in the Liberty runtime.  However, it does not seem to work.  I have maven dependency `net.wasdev.maven.tools.targets:liberty-target:19.0.0.6` set, which added the `httpclient-4.3.jar` in my Maven dependency library.  This JAR contains the `org.apache.http.client.utils.URIBuilder` class which is being declared in my servlet.  I have not compilation errors, but upon deploying the app and testing it, it generates a `NoClassDefFoundException` on the `URIBuilder` class.  I've tried this on both the OpenLiberty and WebSphere Liberty.  Also with both EAR and WAR deployable.  The class is available in the `<wlp_install>/lib/com.ibm.ws.org.apache.httpcomponents_1.0.27.jar` of the Liberty runtime.

Sample app repo:
[https://github.com/mikecai/misc-apps](url)

Relavent pom.xml section:
```
<dependencies>
	<dependency>
		<groupId>net.wasdev.maven.tools.targets</groupId>
		<artifactId>liberty-target</artifactId>
		<version>19.0.0.6</version>
		<type>pom</type>
		<scope>provided</scope>
	</dependency>
</dependencies>
```

Relavent server.xml section:
```
<webApplication location="misc-apps.war" id="misc-apps" contextRoot="miscapps">
	<classloader apiTypeVisibility="+third-party"></classloader>
</webApplication>
```

Exception stack trace:
```
9/13/19 15:55:52:212 PDT] 00000048 com.ibm.ws.webcontainer.util.ApplicationErrorUtils           E SRVE0777E: Exception thrown by application class 'com.ibm.migr.misc.ncdfe.test.URIBuilderTest.doGet:32'
java.lang.NoClassDefFoundError: org/apache/http/client/utils/URIBuilder
	at com.ibm.migr.misc.ncdfe.test.URIBuilderTest.doGet(URIBuilderTest.java:32)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:686)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:791)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1255)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:743)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:440)
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.invokeTarget(WebAppFilterChain.java:182)
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:93)
	at com.ibm.ws.security.jaspi.JaspiServletFilter.doFilter(JaspiServletFilter.java:56)
	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:201)
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:90)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.doFilter(WebAppFilterManager.java:996)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1134)
	at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:4975)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.handleRequest(DynamicVirtualHost.java:314)
	at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:1007)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:279)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1061)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:417)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:376)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:532)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:466)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:331)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.ready(HttpInboundLink.java:302)
	at com.ibm.ws.channel.ssl.internal.SSLConnectionLink.determineNextChannel(SSLConnectionLink.java:1077)
	at com.ibm.ws.channel.ssl.internal.SSLConnectionLink.readyInboundPostHandshake(SSLConnectionLink.java:738)
	at com.ibm.ws.channel.ssl.internal.SSLConnectionLink$MyHandshakeCompletedCallback.complete(SSLConnectionLink.java:414)
	at com.ibm.ws.channel.ssl.internal.SSLUtils.handleHandshake(SSLUtils.java:950)
	at com.ibm.ws.channel.ssl.internal.SSLHandshakeIOCallback.complete(SSLHandshakeIOCallback.java:85)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:503)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueManager.java:573)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:954)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:1043)
	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:239)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.apache.http.client.utils.URIBuilder
	at com.ibm.ws.classloading.internal.AppClassLoader.findClassCommonLibraryClassLoaders(AppClassLoader.java:544)
	at com.ibm.ws.classloading.internal.AppClassLoader.findClass(AppClassLoader.java:286)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at com.ibm.ws.classloading.internal.AppClassLoader.findOrDelegateLoadClass(AppClassLoader.java:522)
	at com.ibm.ws.classloading.internal.AppClassLoader.loadClass(AppClassLoader.java:482)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 37 more
```

**Comment by andymc12** [comment]
The title _"third-party" apiTypeVisibility not working_ is inaccurate, as there are no features in the server.xml that list `org.apache.http.client.utils` as a third-party API package.  

I have not seen anywhere in the Open Liberty code base where Apache HTTP Client packages are exposed to user applications.  

It sounds like there may be some error with the maven tools that is incorrectly listing this package as available - perhaps some other IBM API exposes the URIBuilder class which confuses the maven tool into thinking that it is exposes (if so that would be a bug in the API code that exposes URIBuilder).  Is it possible that you were looking for URIBuilder in a different package (like java.ws.rs.core)? 

I think it is important that we figure out why the maven tooling says that it is available, but the solution for your application is to package your own version of Apache HTTP Client libraries if you need those APIs.  If not, then you should change your code to use APIs that are provided by Liberty (perhaps the JAX-RS URIBuilder will work for you?).

Hope this helps!

**Comment by mikecai** [comment]
@andymc12 I'm using the official WASdev Maven target for my WLP runtime libs from https://github.com/WASdev/ci.maven.tools.  The HTTP client jar is clearly listed in the third-party/pom.xml (https://github.com/WASdev/ci.maven.tools/blob/master/targets/third-party/pom.xml, 3rd from the bottom).  If you can confirm that is incorrect, then I'll move this issue to the WASdev/ci.maven.tools repo.

**Comment by andymc12** [comment]
Hi @mikecai, It definitely is incorrect for OpenLiberty.  Aside from the Apache HTTP Client libraries, it also lists third party dependencies for Jackson and Apache Wink.  Those should not be third party APIs in OpenLiberty at all (OL ships a version of Jackson, but afaik it is not visible to users; OL doesn't ship Wink at all). 

The version number on the pom.xml that you referenced shows 8.5.5.8.  I wonder if that is referring to a version of WebSphere Liberty that existed before OpenLiberty was released to the open source?  Or maybe it is referring to a version of traditional WAS?

Hope this helps!

**Comment by mikecai** [comment]
Hi @andymc12, thanks for the confirmation.  I'll close the issue here and open it against the WASdev/ci.maven.tools repo.
