### ISSUE TITLE
Add logging element in server.xml on OpenJ9 causes system dump

### ISSUE THREAD

**Issue by ericglau** [OpenLiberty/open-liberty#9039]
**Summary:**
When Open Liberty is in loose application mode, and you add a logging element into server.xml, the server crashes with a system dump when using OpenJDK 8/11/12 on OpenJ9.   This has been observed on Mac, Linux, and Windows. 

The issue does not occur with OpenJDK 13 on OpenJ9, and it also does not occur with OpenJDK 8/11/12 on Hotspot.

**To reproduce the issue:**
1. Set $JAVA_HOME to OpenJDK 8 or 11 or 12 with OpenJ9, downloaded from https://adoptopenjdk.net
2. Run the following
```
git clone https://github.com/OpenLiberty/guide-getting-started.git
cd guide-getting-started/start
mvn clean install liberty:run
```
3. Once the server has started, add the following into `target/liberty/wlp/usr/servers/GettingStartedServer/server.xml` between the `<featureManager>` and `</featureManager>` tags and save the file.
```
<feature>mpHealth-1.0</feature>
```

4. Add the following after the `</featureManager>` tag and save the file again.
```
<logging traceSpecification="com.ibm.ws.microprofile.health.*=all" />
```

5. If the core dump doesn't happen, delete the added lines from the two above steps and save the file again.

6. The console output shows:
```
[INFO] [AUDIT   ] CWWKG0016I: Starting server configuration update.
[INFO] JVMDUMP039I Processing dump event "abort", detail "" at 2019/09/18 15:29:08 - please wait.
[INFO] [AUDIT   ] CWWKG0017I: The server configuration was successfully updated in 0.033 seconds.
[INFO] JVMDUMP032I JVM requested System dump using '/Users/eric/git/guide-getting-started/start/target/liberty/wlp/usr/servers/GettingStartedServer/core.20190918.152908.89839.0001.dmp' in response to an event
[INFO] JVMDUMP010I System dump written to /Users/eric/git/guide-getting-started/start/target/liberty/wlp/usr/servers/GettingStartedServer/core.20190918.152908.89839.0001.dmp
[INFO] JVMDUMP032I JVM requested Java dump using '/Users/eric/git/guide-getting-started/start/target/liberty/wlp/usr/servers/GettingStartedServer/javacore.20190918.152908.89839.0002.txt' in response to an event
[INFO] JVMDUMP010I Java dump written to /Users/eric/git/guide-getting-started/start/target/liberty/wlp/usr/servers/GettingStartedServer/javacore.20190918.152908.89839.0002.txt
[INFO] JVMDUMP032I JVM requested Snap dump using '/Users/eric/git/guide-getting-started/start/target/liberty/wlp/usr/servers/GettingStartedServer/Snap.20190918.152908.89839.0003.trc' in response to an event
[INFO] JVMDUMP010I Snap dump written to /Users/eric/git/guide-getting-started/start/target/liberty/wlp/usr/servers/GettingStartedServer/Snap.20190918.152908.89839.0003.trc
[INFO] JVMDUMP007I JVM Requesting JIT dump using '/Users/eric/git/guide-getting-started/start/target/liberty/wlp/usr/servers/GettingStartedServer/jitdump.20190918.152908.89839.0004.dmp'
[INFO] JVMDUMP010I JIT dump written to /Users/eric/git/guide-getting-started/start/target/liberty/wlp/usr/servers/GettingStartedServer/jitdump.20190918.152908.89839.0004.dmp
[INFO] JVMDUMP013I Processed dump event "abort", detail "".
```

Attachments:
[Maven command output](https://github.com/OpenLiberty/open-liberty/files/3628088/maven_output.txt)
[java -version output](https://github.com/OpenLiberty/open-liberty/files/3628089/java_version_output.txt)
[Dump files](https://github.com/OpenLiberty/open-liberty/files/3628095/dump_files.zip)

**Comment by ericglau** [comment]
javacore shows the following callstack:

```
3XMTHREADINFO      "main" J9VMThread:0x000000000763AA00, omrthread_t:0x00007FCC16803450, java/lang/Thread:0x0000000700048330, state:CW, prio=5
3XMJAVALTHREAD            (java/lang/Thread getId:0x1, isDaemon:false)
3XMTHREADINFO1            (native thread ID:0x14D1B3, native priority:0x5, native policy:UNKNOWN, vmstate:CW, vm thread flags:0x00000100)
3XMTHREADINFO2            (native stack address range from:0x000070000B182000, to:0x000070000B202000, size:0x80000)
3XMCPUTIME               CPU usage total: 0.532601000 secs, current category="Application"
3XMTHREADBLOCK     Waiting on: java/util/concurrent/atomic/AtomicReference@0x000000070041CD90 Owned by: <unowned>
3XMHEAPALLOC             Heap bytes allocated since last GC cycle=0 (0x0)
3XMTHREADINFO3           Java callstack:
4XESTACKTRACE                at java/lang/Object.wait(Native Method)
4XESTACKTRACE                at java/lang/Object.wait(Object.java:221)
4XESTACKTRACE                at org/eclipse/osgi/container/SystemModule.waitForStop(SystemModule.java:173)
5XESTACKTRACE                   (entered lock: java/util/concurrent/atomic/AtomicReference@0x000000070041CD90, entry count: 1)
4XESTACKTRACE                at org/eclipse/osgi/internal/framework/EquinoxBundle$SystemBundle.waitForStop(EquinoxBundle.java:306)
4XESTACKTRACE                at org/eclipse/osgi/launch/Equinox.waitForStop(Equinox.java:198)
4XESTACKTRACE                at com/ibm/ws/kernel/launch/internal/FrameworkManager.waitForFrameworkStop(FrameworkManager.java:726)
4XESTACKTRACE                at com/ibm/ws/kernel/launch/internal/FrameworkManager.launchFramework(FrameworkManager.java:313)
4XESTACKTRACE                at com/ibm/ws/kernel/launch/internal/LauncherDelegateImpl.doFrameworkLaunch(LauncherDelegateImpl.java:114)
4XESTACKTRACE                at com/ibm/ws/kernel/launch/internal/LauncherDelegateImpl.launchFramework(LauncherDelegateImpl.java:100)
4XESTACKTRACE                at com/ibm/ws/kernel/boot/internal/KernelBootstrap.go(KernelBootstrap.java:213)
4XESTACKTRACE                at com/ibm/ws/kernel/boot/Launcher.handleActions(Launcher.java:241)
4XESTACKTRACE                at com/ibm/ws/kernel/boot/Launcher.createPlatform(Launcher.java:117)
4XESTACKTRACE                at com/ibm/ws/kernel/boot/cmdline/EnvCheck.main(EnvCheck.java:59)
4XESTACKTRACE                at com/ibm/ws/kernel/boot/cmdline/EnvCheck.main(EnvCheck.java:35)
3XMTHREADINFO3           No native callstack available for this thread
```

**Comment by yeekangc** [comment]
@loriadi, not sure how we should handle this issue?

**Comment by yeekangc** [comment]
@ericglau indicated this appears to be similar to https://github.com/eclipse/openj9/issues/6875.

**Comment by ericglau** [comment]
Closing since this no longer occurs in the OpenJ9 nightly build (tested with 11.0.5+8) and the OpenJ9 issue mentioned above is also closed.
