### ISSUE TITLE
Microprofile and Apache CXF Soap client

### ISSUE THREAD

**Issue by k8vance88** [OpenLiberty/open-liberty#9106]
@kvenkatramreddy commented on [Wed Sep 18 2019](https://github.com/OpenLiberty/openliberty.io/issues/1387)

Hi Team,

We are facing an issue when we run microprofile with CXF client. It is throwing an following exception.

E0207E: Uncaught initialization exception created by servlet com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters 1064" at ffdc_19.09.18_14.48.40.1.log
[18/9/19 14:48:40:449 IST] 000000ea com.ibm.ws.webcontainer.webapp                               E SRVE0315E: An exception occurred: java.lang.Throwable: javax.servlet.ServletException: SRVE0207E: Uncaught initialization exception created by servlet
	at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:5051)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.handleRequest(DynamicVirtualHost.java:314)
	at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:1007)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:279)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1136)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:417)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:376)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:547)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:481)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:346)
	at com.ibm.ws.http.channel.internal.inbound.HttpICLReadCallback.complete(HttpICLReadCallback.java:70)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:503)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueManager.java:573)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:954)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:1043)
	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:239)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.servlet.ServletException: SRVE0207E: Uncaught initialization exception created by servlet
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.init(ServletWrapper.java:360)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:584)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:426)
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.invokeTarget(WebAppFilterChain.java:182)
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:93)
	at com.ibm.ws.security.jaspi.JaspiServletFilter.doFilter(JaspiServletFilter.java:56)
	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:201)
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:90)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.doFilter(WebAppFilterManager.java:993)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1131)
	at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:4993)
	... 18 more
Caused by: org.apache.cxf.bus.extension.ExtensionException: Could not find constructor for class org.apache.cxf.ws.policy.PolicyDataEngineImpl for args [com.ibm.ws.jaxrs20.bus.LibertyApplicationBus@2a609be6].
	at org.apache.cxf.bus.extension.Extension.load(Extension.java:266)
	at org.apache.cxf.bus.extension.ExtensionManagerImpl.loadAndRegister(ExtensionManagerImpl.java:208)
	at org.apache.cxf.bus.extension.ExtensionManagerImpl.initialize(ExtensionManagerImpl.java:116)
	at org.apache.cxf.bus.extension.ExtensionManagerBus.doInitializeInternal(ExtensionManagerBus.java:260)
	at org.apache.cxf.bus.extension.ExtensionManagerBus.initialize(ExtensionManagerBus.java:250)
	at com.ibm.ws.jaxrs20.bus.LibertyApplicationBusFactory.createBus(LibertyApplicationBusFactory.java:135)
	at com.ibm.ws.jaxrs20.bus.LibertyApplicationBusFactory.createServerScopedBus(LibertyApplicationBusFactory.java:87)
	at com.ibm.ws.jaxrs20.metadata.JaxRsServerMetaData.<init>(JaxRsServerMetaData.java:29)
	at com.ibm.ws.jaxrs20.metadata.JaxRsModuleMetaData.getServerMetaData(JaxRsModuleMetaData.java:111)
	at com.ibm.ws.jaxrs20.server.LibertyJaxRsServerFactoryBean.<init>(LibertyJaxRsServerFactoryBean.java:97)
	at com.ibm.ws.jaxrs20.server.JaxRsWebEndpointImpl.init(JaxRsWebEndpointImpl.java:62)
	at com.ibm.websphere.jaxrs.server.IBMRestServlet.init(IBMRestServlet.java:64)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.init(ServletWrapper.java:291)
	... 28 more
Caused by: java.lang.NoSuchMethodException: org.apache.cxf.ws.policy.PolicyDataEngineImpl.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.getConstructor(Class.java:1825)
	at org.apache.cxf.bus.extension.Extension.load(Extension.java:241)
	... 40 more

If I do not add cxf-jax-ws jars, we are receiving java.lang.NoClassDefFoundError: org/apache/cxf/jaxws/JaxWsProxyFactoryBean

**Comment by vladtsepesh** [comment]
Sorry to bother, I came into this issue two years later, but I cant see any solution.
Both this issue and [this other one](https://github.com/OpenLiberty/openliberty.io/issues/1387) are closed with no solution, for what I see.
I'm sure this is a silly question, but I'm going slightly mad.
