### ISSUE TITLE
Serialization error in EJB call: no feedback

### ISSUE THREAD

**Issue by tschurins** [OpenLiberty/open-liberty#9209]
## Problem
We have an EJB returning a serializable object. By mistake, the returned object is a non static inner class, where the enclosing parent is not serializable.
When we call this EJB, an exception is shown on the server side:
```
Exception in thread "Default Executor-thread-34" 
org.apache.yoko.orb.OB.AssertionFailed: Yoko encountered an internal error
    at org.apache.yoko.orb.OB.Assert._OB_assert(Assert.java:23)
    at org.apache.yoko.orb.OB.Downcall.setReplySCL(Downcall.java:229)
    at org.apache.yoko.orb.OB.CollocatedServer.upcallSystemException(CollocatedServer.java:427)
    at org.apache.yoko.orb.OB.Upcall.setSystemException(Upcall.java:450)
    at org.apache.yoko.orb.OB.PIUpcall.setSystemException(PIUpcall.java:156)
    at org.apache.yoko.orb.OBPortableServer.POA_impl._OB_dispatch(POA_impl.java:1678)
    at org.apache.yoko.orb.OB.DispatchRequest_impl.invoke(DispatchRequest_impl.java:56)
    at com.ibm.ws.transport.iiop.yoko.ExecutorDispatchStrategy$1.run(ExecutorDispatchStrategy.java:42)
    at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:239)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.lang.Thread.run(Thread.java:818)
```
but the client side never receives anything and keeps hanging.

## Expected behaviour
The EJB client receives an exception with proper detail (this or that class is not serializable, &c.)

## Details
* Server details: defaultServer (Open Liberty 19.0.0.8/wlp-1.0.31.cl190820190813-1136) on IBM J9 VM, version 8.0.5.40 - pxa6480sr5fp40-20190807_01(SR5 FP40) (en_US)
* Features used: jndi-1.0, servlet-4.0, ejb-3.2

**Comment by tschurins** [comment]
See attached sample application:
[ol9209.zip](https://github.com/OpenLiberty/open-liberty/files/3760613/ol9209.zip)

maven project creating a ear file that can be deployed in openliberty via docker (see readme.md)
The servlet will call the EJB, causing the error.

**Comment by gssandesh** [comment]
@tschurins even i am facing the same problem can you help to resolve this issue
