### ISSUE TITLE
Incorrect API usaged to obtain injection classes

### ISSUE THREAD

**Issue by tbitonti** [OpenLiberty/open-liberty#9283]
From LAOS build:

https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_JKMIQOrnEemoq4hjSBupzg&tab=com.ibm.team.build.web.ui.internal.editors.result.download.DownloadsProvider

For these tests:

com.ibm.ws.jsf.2.3_fat FAT tests 41 2 0
com.ibm.ws.jsf23.fat.tests.JSF23WebSocketTests 2 2 0 5s 3
testPushWebsocket 1 1 0 5s 1 testOpenAndCloseWebsocket

The following exception is noted:

[10/10/19, 8:39:12:800 UTC] 0000002a jsf           1 com.ibm.ws.jsf.shared.util.JSFInjectionClassListCollaborator getInjectionClasses failed to adapt to InfoStore for class annotations
                                 com.ibm.wsspi.adaptable.module.UnableToAdaptException: CWWKM0464E: WebSphere Application Server internal error occurred. Please contact WebSphere Application Server support with the following data: Container is not a web module com.ibm.ws.adaptable.module.internal.AdaptableContainerImpl@acce5cde ( bundleentry://94.fwk1031745859/ file:/home/jazz_build/_RaglkOscEemoq4hjSBupzg-EBC.PROD.WASRTC-7Q6-000-00-00/jbe/build/dev/image/output/wlp/usr/servers/jsf23CDIWSOCServer/workarea/org.eclipse.osgi/94/data/cacheAdapt/.overlay/ )
	at com.ibm.ws.container.service.annotations.internal.WebAnnotationsAdapter.adapt(WebAnnotationsAdapter.java:73)
	at com.ibm.ws.container.service.annotations.internal.WebAnnotationsAdapter.adapt(WebAnnotationsAdapter.java:31)
	at com.ibm.ws.adaptable.module.internal.AdapterFactoryServiceImpl.adapt(AdapterFactoryServiceImpl.java:200)
	at com.ibm.ws.adaptable.module.internal.AdaptableContainerImpl.adapt(AdaptableContainerImpl.java:174)
	at com.ibm.ws.container.service.annocache.AnnotationsBetaHelper.getWebAnnotations(AnnotationsBetaHelper.java:218)
	at com.ibm.ws.jsf.shared.util.JSFInjectionClassListCollaborator.getInjectionClasses(JSFInjectionClassListCollaborator.java:100)
	at com.ibm.ws.webcontainer.osgi.webapp.WebAppInjectionClassListAdapter.getInjectionClasses(WebAppInjectionClassListAdapter.java:98)
	at com.ibm.ws.container.service.app.deploy.internal.InjectionClassListAdapter.adapt(InjectionClassListAdapter.java:41)
	at com.ibm.ws.container.service.app.deploy.internal.InjectionClassListAdapter.adapt(InjectionClassListAdapter.java:31)
	at com.ibm.ws.adaptable.module.internal.AdapterFactoryServiceImpl.adapt(AdapterFactoryServiceImpl.java:200)
	at com.ibm.ws.adaptable.module.internal.AdaptableContainerImpl.adapt(AdaptableContainerImpl.java:174)
	at com.ibm.ws.cdi.internal.archive.liberty.CDIArchiveImpl.getInjectionClassList(CDIArchiveImpl.java:403)
	at com.ibm.ws.cdi.impl.weld.BeanDeploymentArchiveImpl.initializeJEEComponentClasses(BeanDeploymentArchiveImpl.java:361)
	at com.ibm.ws.cdi.impl.weld.BeanDeploymentArchiveImpl.scan(BeanDeploymentArchiveImpl.java:289)
	at com.ibm.ws.cdi.impl.weld.WebSphereCDIDeploymentImpl.scan(WebSphereCDIDeploymentImpl.java:601)
	at com.ibm.ws.cdi.impl.CDIContainerImpl.startInitialization(CDIContainerImpl.java:128)
	at com.ibm.ws.cdi.liberty.CDIRuntimeImpl.applicationStarting(CDIRuntimeImpl.java:448)
	at com.ibm.ws.container.service.state.internal.ApplicationStateManager.fireStarting(ApplicationStateManager.java:51)
	at com.ibm.ws.container.service.state.internal.StateChangeServiceImpl.fireApplicationStarting(StateChangeServiceImpl.java:50)
	at com.ibm.ws.app.manager.module.internal.SimpleDeployedAppInfoBase.preDeployApp(SimpleDeployedAppInfoBase.java:550)
	at com.ibm.ws.app.manager.module.internal.SimpleDeployedAppInfoBase.installApp(SimpleDeployedAppInfoBase.java:511)
	at com.ibm.ws.app.manager.module.internal.DeployedAppInfoBase.deployApp(DeployedAppInfoBase.java:347)
	at com.ibm.ws.app.manager.war.internal.WARApplicationHandlerImpl.install(WARApplicationHandlerImpl.java:65)
	at com.ibm.ws.app.manager.internal.statemachine.StartAction.execute(StartAction.java:140)
	at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.enterState(ApplicationStateMachineImpl.java:1266)
	at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.run(ApplicationStateMachineImpl.java:881)
	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:239)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:825)

The exception doesn't cause the test failure, but is an indication that annotation processing is not being performed correctly.

Further review shows the same exception for other JSF 2.3 tests.  The failure also occurs locally when using the annotation caching code.

Locally running the server:

open-liberty/dev/com.ibm.ws.jsf.2.3_fat/build/libs/autoFVT/publish/servers/jsf23CDIWSOCServer

With the dropin application "WebSocket.war" as provided for this FAT test server.

The exception is nearly the same:

[10/10/19 16:22:19:631 EDT] 0000003d jsf           1 

com.ibm.ws.jsf.shared.util.JSFInjectionClassListCollaborator getInjectionClasses failed to adapt to InfoStore for class annotations
  com.ibm.wsspi.adaptable.module.UnableToAdaptException:
    CWWKM0453E: WebSphere Application Server internal error occurred. Please contact WebSphere Application Server support with the following data:
      Container is not a module com.ibm.ws.adaptable.module.internal.AdaptableContainerImpl@29de99ae
        ( bundleentry://89.fwk-1185015430/ file:/C:/dev/repos-pub/anno-beta/dev/build.image/wlp/usr/servers/jsf23CDIWSOCServer/workarea/org.eclipse.osgi/89/data/cacheAdapt/.overlay/ )
  at com.ibm.ws.container.service.annocache.internal.WebAnnotationsAdapterImpl.adapt(WebAnnotationsAdapterImpl.java:54)
  at com.ibm.ws.container.service.annocache.internal.WebAnnotationsAdapterImpl.adapt(WebAnnotationsAdapterImpl.java:33)
  at com.ibm.ws.adaptable.module.internal.AdapterFactoryServiceImpl.adapt(AdapterFactoryServiceImpl.java:200)
  at com.ibm.ws.adaptable.module.internal.AdaptableContainerImpl.adapt(AdaptableContainerImpl.java:174)
  at com.ibm.ws.container.service.annocache.AnnotationsBetaHelper.getWebAnnotations(AnnotationsBetaHelper.java:216)

Looking at the non-caching case, the exception is from:

open-liberty/dev/com.ibm.ws.container.service/src/com/ibm/ws/container/service/annotations/internal/WebAnnotationsAdapter.java

Which has:

  Object webModuleInfo = rootOverlay.getFromNonPersistentCache(artifactContainer.getPath(), WebModuleInfo.class);
  if (webModuleInfo == null) {
    String msg = Tr.formatMessage(tc, "container.is.not.a.web.module.CWWKM0464E", "Container is not a web module", containerToAdapt);
    throw new UnableToAdaptException(msg);
  }

Web annotations are being requested for a container, but that container does not have associated web module information, leading to the exception.

Following a server startup, the overlay state is:

The description of this introspector:
Overlay Container Diagnostics

Active Containers:
  Number of Registered Containers: [ 3 ]

Containers in Set:
  [ ROOT ] [ com.ibm.ws.artifact.overlay.internal.DirectoryBasedOverlayContainerImpl@9a90bf11 ]
      Base [ com.ibm.ws.artifact.bundle.internal.BundleArchive@f70c4ec0 ]
        URL [ bundleentry://102.fwk-1185015430/ ]
      File [ com.ibm.ws.artifact.file.internal.FileContainer@2faff681 ]
        URL [ file:/C:/dev/repos-pub/anno-beta/dev/build.image/wlp/usr/servers/jsf23CDIWSOCServer/workarea/org.eclipse.osgi/102/data/cacheAdapt/.overlay/ ]

  [ ROOT ] [ com.ibm.ws.artifact.overlay.internal.DirectoryBasedOverlayContainerImpl@3f783e6b ]
      Base [ com.ibm.ws.artifact.zip.internal.ZipFileContainer@708b3e01 ]
        URL [ file:/c:/dev/repos-pub/anno-beta/dev/build.image/wlp/usr/servers/jsf23CDIWSOCServer/dropins/WebSocket.war ]
      File [ com.ibm.ws.artifact.file.internal.FileContainer@4751e890 ]
        URL [ file:/C:/dev/repos-pub/anno-beta/dev/build.image/wlp/usr/servers/jsf23CDIWSOCServer/workarea/org.eclipse.osgi/66/data/cacheAdapt/com.ibm.ws.app.manager_16/.overlay/ ]

  [ ROOT ] [ com.ibm.ws.artifact.overlay.internal.DirectoryBasedOverlayContainerImpl@217e5e55 ]
      Base [ com.ibm.ws.artifact.bundle.internal.BundleArchive@74cf2fe2 ]
        URL [ bundleentry://89.fwk-1185015430/ ]
      File [ com.ibm.ws.artifact.file.internal.FileContainer@c02e6cd0 ]
        URL [ file:/C:/dev/repos-pub/anno-beta/dev/build.image/wlp/usr/servers/jsf23CDIWSOCServer/workarea/org.eclipse.osgi/89/data/cacheAdapt/.overlay/ ]

Directory Overlay Container [ ROOT ] [ com.ibm.ws.artifact.overlay.internal.DirectoryBasedOverlayContainerImpl@9a90bf11 ]
  ** EMPTY **

Directory Overlay Container [ ROOT ] [ com.ibm.ws.artifact.overlay.internal.DirectoryBasedOverlayContainerImpl@3f783e6b ]
  [ /WEB-INF/web.xml ]
      [ interface com.ibm.ws.javaee.dd.web.WebApp ] [ web-app ]
  [ / ]
      [ interface com.ibm.ws.container.service.config.WebFragmentsInfo ] [ com.ibm.ws.container.service.config.internal.WebFragmentsInfoImpl@9cfb4a71 ]
      [ interface com.ibm.ws.container.service.app.deploy.ModuleInfo ] [ com.ibm.ws.app.manager.module.internal.WebModuleInfoImpl@55666993 ]
      [ interface com.ibm.ws.jsp.configuration.JspXmlExtConfig ] [ com.ibm.ws.jsp.webxml.JspConfiguratorHelper@6afb0c2d ]
      [ interface com.ibm.ws.container.service.annocache.WebAnnotations ] [ com.ibm.ws.container.service.annocache.internal.WebAnnotationsImpl@ae5ab613 ]
      [ interface com.ibm.ws.container.service.app.deploy.ApplicationInfo ] [ com.ibm.ws.container.service.app.deploy.internal.ApplicationInfoImpl@352f91b8[WebSocket] ]
      [ interface com.ibm.ws.container.service.app.deploy.extended.ApplicationInfoForContainer ] [ com.ibm.ws.app.manager.internal.ApplicationInstallInfo@a7e492ee ]
      [ interface com.ibm.ws.container.service.app.deploy.WebModuleInfo ] [ com.ibm.ws.app.manager.module.internal.WebModuleInfoImpl@55666993 ]
      [ interface com.ibm.ws.classloading.ClassLoadingButler ] [ com.ibm.ws.classloading.internal.ClassLoadingButlerImpl@b2c93731 ]
      [ interface com.ibm.wsspi.webcontainer.metadata.WebModuleMetaData ] [ com.ibm.ws.webcontainer.osgi.metadata.WebModuleMetaDataImpl@c73898f4[WebSocket#WebSocket.war] ]
      [ interface com.ibm.ws.container.service.app.deploy.WebModuleClassesInfo ] [ com.ibm.ws.container.service.app.deploy.internal.WebModuleClassesInfoAdapter$3@cd041d7a ]
      [ interface com.ibm.ws.container.service.app.deploy.ApplicationClassesContainerInfo ] [ com.ibm.ws.app.manager.war.internal.WARDeployedAppInfo@47bc6a6f ]
      [ interface com.ibm.wsspi.webcontainer.webapp.WebAppConfig ] [ JSF23WebSocketTest ]

Directory Overlay Container [ ROOT ] [ com.ibm.ws.artifact.overlay.internal.DirectoryBasedOverlayContainerImpl@217e5e55 ]
  ** EMPTY **

**Comment by tbitonti** [comment]
Here is a complete exception stack from failure in continuous build:

                                 com.ibm.wsspi.adaptable.module.UnableToAdaptException: CWWKM0464E: WebSphere Application Server internal error occurred. Please contact WebSphere Application Server support with the following data: Container is not a web module com.ibm.ws.adaptable.module.internal.AdaptableContainerImpl@acce5cde ( bundleentry://94.fwk1031745859/ file:/home/jazz_build/_RaglkOscEemoq4hjSBupzg-EBC.PROD.WASRTC-7Q6-000-00-00/jbe/build/dev/image/output/wlp/usr/servers/jsf23CDIWSOCServer/workarea/org.eclipse.osgi/94/data/cacheAdapt/.overlay/ )
	at com.ibm.ws.container.service.annotations.internal.WebAnnotationsAdapter.adapt(WebAnnotationsAdapter.java:73)
	at com.ibm.ws.container.service.annotations.internal.WebAnnotationsAdapter.adapt(WebAnnotationsAdapter.java:31)
	at com.ibm.ws.adaptable.module.internal.AdapterFactoryServiceImpl.adapt(AdapterFactoryServiceImpl.java:200)
	at com.ibm.ws.adaptable.module.internal.AdaptableContainerImpl.adapt(AdaptableContainerImpl.java:174)
	at com.ibm.ws.container.service.annocache.AnnotationsBetaHelper.getWebAnnotations(AnnotationsBetaHelper.java:218)
	at com.ibm.ws.jsf.shared.util.JSFInjectionClassListCollaborator.getInjectionClasses(JSFInjectionClassListCollaborator.java:100)
	at com.ibm.ws.webcontainer.osgi.webapp.WebAppInjectionClassListAdapter.getInjectionClasses(WebAppInjectionClassListAdapter.java:98)
	at com.ibm.ws.container.service.app.deploy.internal.InjectionClassListAdapter.adapt(InjectionClassListAdapter.java:41)
	at com.ibm.ws.container.service.app.deploy.internal.InjectionClassListAdapter.adapt(InjectionClassListAdapter.java:31)
	at com.ibm.ws.adaptable.module.internal.AdapterFactoryServiceImpl.adapt(AdapterFactoryServiceImpl.java:200)
	at com.ibm.ws.adaptable.module.internal.AdaptableContainerImpl.adapt(AdaptableContainerImpl.java:174)
	at com.ibm.ws.cdi.internal.archive.liberty.CDIArchiveImpl.getInjectionClassList(CDIArchiveImpl.java:403)
	at com.ibm.ws.cdi.impl.weld.BeanDeploymentArchiveImpl.initializeJEEComponentClasses(BeanDeploymentArchiveImpl.java:361)
	at com.ibm.ws.cdi.impl.weld.BeanDeploymentArchiveImpl.scan(BeanDeploymentArchiveImpl.java:289)
	at com.ibm.ws.cdi.impl.weld.WebSphereCDIDeploymentImpl.scan(WebSphereCDIDeploymentImpl.java:601)
	at com.ibm.ws.cdi.impl.CDIContainerImpl.startInitialization(CDIContainerImpl.java:128)
	at com.ibm.ws.cdi.liberty.CDIRuntimeImpl.applicationStarting(CDIRuntimeImpl.java:448)
	at com.ibm.ws.container.service.state.internal.ApplicationStateManager.fireStarting(ApplicationStateManager.java:51)
	at com.ibm.ws.container.service.state.internal.StateChangeServiceImpl.fireApplicationStarting(StateChangeServiceImpl.java:50)
	at com.ibm.ws.app.manager.module.internal.SimpleDeployedAppInfoBase.preDeployApp(SimpleDeployedAppInfoBase.java:550)
	at com.ibm.ws.app.manager.module.internal.SimpleDeployedAppInfoBase.installApp(SimpleDeployedAppInfoBase.java:511)
	at com.ibm.ws.app.manager.module.internal.DeployedAppInfoBase.deployApp(DeployedAppInfoBase.java:347)
	at com.ibm.ws.app.manager.war.internal.WARApplicationHandlerImpl.install(WARApplicationHandlerImpl.java:65)
	at com.ibm.ws.app.manager.internal.statemachine.StartAction.execute(StartAction.java:140)
	at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.enterState(ApplicationStateMachineImpl.java:1266)
	at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.run(ApplicationStateMachineImpl.java:881)
	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:239)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:825)

The problem is that a container is provided to CDIArchiveImpl.getInjectionClassList does not associated data under type "WebModuleInfo".

**Comment by tbitonti** [comment]
The container data, slightly rearranged:

[10/10/19, 8:39:12:488 UTC] 0000002a WARDeployedAp I   CWWKZ0136I: The WebSocket application is using the archive file at the /home/jazz_build/_RaglkOscEemoq4hjSBupzg-EBC.PROD.WASRTC-7Q6-000-00-00/jbe/build/dev/image/output/wlp/usr/servers/jsf23CDIWSOCServer/dropins/WebSocket.war location.

[ ROOT ] [ com.ibm.ws.artifact.overlay.internal.DirectoryBasedOverlayContainerImpl@3f783e6b ]
Base [ com.ibm.ws.artifact.zip.internal.ZipFileContainer@708b3e01 ]
URL [ file:/c:/dev/repos-pub/anno-beta/dev/build.image/wlp/usr/servers/jsf23CDIWSOCServer/dropins/WebSocket.war ]
File [ com.ibm.ws.artifact.file.internal.FileContainer@4751e890 ]
URL [ file:/C:/dev/repos-pub/anno-beta/dev/build.image/wlp/usr/servers/jsf23CDIWSOCServer/workarea/org.eclipse.osgi/66/data/cacheAdapt/com.ibm.ws.app.manager_16/.overlay/ ]

[ ROOT ] [ com.ibm.ws.artifact.overlay.internal.DirectoryBasedOverlayContainerImpl@217e5e55 ]
Base [ com.ibm.ws.artifact.bundle.internal.BundleArchive@74cf2fe2 ]
URL [ bundleentry://89.fwk-1185015430/ ]
File [ com.ibm.ws.artifact.file.internal.FileContainer@c02e6cd0 ]
URL [ file:/C:/dev/repos-pub/anno-beta/dev/build.image/wlp/usr/servers/jsf23CDIWSOCServer/workarea/org.eclipse.osgi/89/data/cacheAdapt/.overlay/ ]

[ ROOT ] [ com.ibm.ws.artifact.overlay.internal.DirectoryBasedOverlayContainerImpl@9a90bf11 ]
Base [ com.ibm.ws.artifact.bundle.internal.BundleArchive@f70c4ec0 ]
URL [ bundleentry://102.fwk-1185015430/ ]
File [ com.ibm.ws.artifact.file.internal.FileContainer@2faff681 ]
URL [ file:/C:/dev/repos-pub/anno-beta/dev/build.image/wlp/usr/servers/jsf23CDIWSOCServer/workarea/org.eclipse.osgi/102/data/cacheAdapt/.overlay/ ]

Directory Overlay Container [ ROOT ] [ com.ibm.ws.artifact.overlay.internal.DirectoryBasedOverlayContainerImpl@3f783e6b ]
[ /WEB-INF/web.xml ]
  [ interface com.ibm.ws.javaee.dd.web.WebApp ] [ web-app ]
[ / ]
  [ interface com.ibm.ws.container.service.config.WebFragmentsInfo ] [ com.ibm.ws.container.service.config.internal.WebFragmentsInfoImpl@9cfb4a71 ]
  [ interface com.ibm.ws.container.service.app.deploy.ModuleInfo ] [ com.ibm.ws.app.manager.module.internal.WebModuleInfoImpl@55666993 ]
  [ interface com.ibm.ws.jsp.configuration.JspXmlExtConfig ] [ com.ibm.ws.jsp.webxml.JspConfiguratorHelper@6afb0c2d ]
  [ interface com.ibm.ws.container.service.annocache.WebAnnotations ] [ com.ibm.ws.container.service.annocache.internal.WebAnnotationsImpl@ae5ab613 ]
  [ interface com.ibm.ws.container.service.app.deploy.ApplicationInfo ] [ com.ibm.ws.container.service.app.deploy.internal.ApplicationInfoImpl@352f91b8[WebSocket] ]
  [ interface com.ibm.ws.container.service.app.deploy.extended.ApplicationInfoForContainer ] [ com.ibm.ws.app.manager.internal.ApplicationInstallInfo@a7e492ee ]
  [ interface com.ibm.ws.container.service.app.deploy.WebModuleInfo ] [ com.ibm.ws.app.manager.module.internal.WebModuleInfoImpl@55666993 ]
  [ interface com.ibm.ws.classloading.ClassLoadingButler ] [ com.ibm.ws.classloading.internal.ClassLoadingButlerImpl@b2c93731 ]
  [ interface com.ibm.wsspi.webcontainer.metadata.WebModuleMetaData ] [ com.ibm.ws.webcontainer.osgi.metadata.WebModuleMetaDataImpl@c73898f4[WebSocket#WebSocket.war] ]
  [ interface com.ibm.ws.container.service.app.deploy.WebModuleClassesInfo ] [ com.ibm.ws.container.service.app.deploy.internal.WebModuleClassesInfoAdapter$3@cd041d7a ]
  [ interface com.ibm.ws.container.service.app.deploy.ApplicationClassesContainerInfo ] [ com.ibm.ws.app.manager.war.internal.WARDeployedAppInfo@47bc6a6f ]
  [ interface com.ibm.wsspi.webcontainer.webapp.WebAppConfig ] [ JSF23WebSocketTest ]

Directory Overlay Container [ ROOT ] [ com.ibm.ws.artifact.overlay.internal.DirectoryBasedOverlayContainerImpl@217e5e55 ]
** EMPTY **

Directory Overlay Container [ ROOT ] [ com.ibm.ws.artifact.overlay.internal.DirectoryBasedOverlayContainerImpl@9a90bf11 ]
** EMPTY **

**Comment by tbitonti** [comment]
(working from different logs; hash values and directories won't usually be the same)

The containers seem to have been created from:

[10/11/19 13:20:00:782 EDT] 0000003c FileContainer >  createContainer Entry  
                                 C:\dev\repos-pub\anno-beta\dev\build.image\wlp\usr\servers\jsf23CDIWSOCServer\workarea\org.eclipse.osgi\66\data\cache\com.ibm.ws.app.manager_15
                                 c:\dev\repos-pub\anno-beta\dev\build.image\wlp\usr\servers\jsf23CDIWSOCServer\dropins\WebSocket.war

[10/11/19 13:20:01:721 EDT] 0000003c BundleContain >  createContainer Entry  
                                 C:\dev\repos-pub\anno-beta\dev\build.image\wlp\usr\servers\jsf23CDIWSOCServer\workarea\org.eclipse.osgi\102\data\cache
                                 com.ibm.ws.transaction.cdi_1.0.33.201910081301 [102]

[10/11/19 13:20:01:752 EDT] 0000003c BundleContain >  createContainer Entry  
                                 C:\dev\repos-pub\anno-beta\dev\build.image\wlp\usr\servers\jsf23CDIWSOCServer\workarea\org.eclipse.osgi\89\data\cache
                                 com.ibm.ws.org.apache.myfaces.2.3_1.0.33.201910081430 [89]
