### ISSUE TITLE
opentracing can cause jaxrs exceptions to not be logged

### ISSUE THREAD

**Issue by brutif** [OpenLiberty/open-liberty#9293]
Open Liberty 19.0.0.8 (wlp-1.0.31.cl190820190730-1310) 

If I include <feature>microProfile-2.0</feature>  I get OpenTracing.
I don’t intend to use it but would like to use some of the other microprofile stuff.
If no further configuration is done,  opentracing “eats” any runtime exceptions which would otherwise be logged.  This looks like a bug.
Without OT:
```
[8/14/19, 9:06:31:225 CDT] 00000041 SystemOut                                                    O ** throwing NPE now...
[8/14/19, 9:06:31:226 CDT] 00000041 .apache.cxf.cxf.core.3.2:1.0.31.cl190820190730-1310(id=176)] W Application {http://kabasec/}Logout has thrown exception, unwinding now
org.apache.cxf.interceptor.Fault
    at org.apache.cxf.service.invoker.AbstractInvoker.createFault(AbstractInvoker.java:162)
    at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:128)
    at com.ibm.ws.jaxrs20.server.LibertyJaxRsInvoker.invoke(LibertyJaxRsInvoker.java:273)
    at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:205)
```

With OT:
```
[8/14/19, 9:08:10:338 CDT] 00000080 com.ibm.ws.opentracing.OpentracingUserFeatureAccessService   E CWMOT0008E: OpenTracing cannot track JAX-RS requests because an OpentracingTracerFactory class was not provided.
[8/14/19, 9:08:10:339 CDT] 00000080 SystemOut                                                    O ** throwing NPE now...
```

**Comment by andymc12** [comment]
It looks like OpenTracing is registering a global JAX-RS ExceptionMapper that converts all thrown exceptions (that are not handled by any application-supplied ExceptionMappers) into a 500 Internal Server Error response with a new header.  This occurs even if the request/response is not traced by OT.

Here is the trace output:
```
[10/28/19, 16:38:09:011 CDT] 00000035 id=00000000 com.ibm.ws.kernel.feature.internal.FeatureManager            A CWWKF0011I: The defaultServer server is ready to run a smarter planet. The defaultServer server started in 2.730 seconds.
[10/28/19, 16:38:15:577 CDT] 0000004d id=00000000 com.ibm.ws.opentracing.OpentracingJaxRsProviderRegister      3 installProvider 
                                                                                                               Container Filter
                                                                                                               com.ibm.ws.opentracing.OpentracingContainerFilter@2a8cc0c5
[10/28/19, 16:38:15:605 CDT] 0000004d id=00000000 .apache.cxf.cxf.core.3.2:1.0.34.cl191120191028-0810(id=102)] I Setting the server's publish address to be /
[10/28/19, 16:38:15:651 CDT] 0000004d id=00000000 com.ibm.ws.webcontainer.servlet.ServletWrapper               I init SRVE0242I: [jaxrsfun] [/jaxrsfun] [kabasec.KabaSecApp]: Initialization successful.
[10/28/19, 16:38:15:673 CDT] 0000004d id=2a8cc0c5 com.ibm.ws.opentracing.OpentracingContainerFilter            > filter Entry  
                                                                                                               org.apache.cxf.jaxrs.impl.ContainerRequestContextImpl@f9736476
[10/28/19, 16:38:15:706 CDT] 0000004d id=00000000 .opentracing.OpentracingTracerManager$ApplicationTracersLock > <init> Entry 
[10/28/19, 16:38:15:706 CDT] 0000004d id=8d912551 .opentracing.OpentracingTracerManager$ApplicationTracersLock < <init> Exit  
                                                                                                               com.ibm.ws.opentracing.OpentracingTracerManager$ApplicationTracersLock@8d912551
[10/28/19, 16:38:15:720 CDT] 0000004d id=00000000 .opentracing.OpentracingTracerManager$OpentracingThreadLocal > <init> Entry 
[10/28/19, 16:38:15:721 CDT] 0000004d id=8290a783 .opentracing.OpentracingTracerManager$OpentracingThreadLocal < <init> Exit  
                                                                                                               com.ibm.ws.opentracing.OpentracingTracerManager$OpentracingThreadLocal@8290a783
[10/28/19, 16:38:15:721 CDT] 0000004d id=00000000 com.ibm.ws.opentracing.OpentracingTracerManager              > getTracer Entry 
[10/28/19, 16:38:15:721 CDT] 0000004d id=8290a783 .opentracing.OpentracingTracerManager$OpentracingThreadLocal > initialValue Entry 
[10/28/19, 16:38:15:735 CDT] 0000004d id=00000000 com.ibm.ws.opentracing.OpentracingContext                    > <init> Entry 
[10/28/19, 16:38:15:735 CDT] 0000004d id=65f68ffb com.ibm.ws.opentracing.OpentracingContext                    < <init> Exit  
                                                                                                               com.ibm.ws.opentracing.OpentracingContext@65f68ffb
[10/28/19, 16:38:15:735 CDT] 0000004d id=8290a783 .opentracing.OpentracingTracerManager$OpentracingThreadLocal < initialValue Exit  
                                                                                                               com.ibm.ws.opentracing.OpentracingContext@65f68ffb
[10/28/19, 16:38:15:774 CDT] 0000004d id=00000000 com.ibm.ws.opentracing.OpentracingTracerManager              > ensureTracer Entry  
                                                                                                               jaxrsfun
[10/28/19, 16:38:15:790 CDT] 0000004d id=00000000 com.ibm.ws.opentracing.OpentracingUserFeatureAccessService   > getTracerInstance Entry  
                                                                                                               jaxrsfun
[10/28/19, 16:38:15:790 CDT] 0000004d id=00000000 com.ibm.ws.opentracing.OpentracingUserFeatureAccessService   E CWMOT0008E: OpenTracing cannot track JAX-RS requests because an OpentracingTracerFactory class was not provided.
[10/28/19, 16:38:15:790 CDT] 0000004d id=00000000 com.ibm.ws.opentracing.OpentracingUserFeatureAccessService   < getTracerInstance Exit  
                                                                                                               null
[10/28/19, 16:38:15:790 CDT] 0000004d id=00000000 com.ibm.ws.opentracing.OpentracingTracerManager              < ensureTracer (newly created) Exit  
                                                                                                               null
[10/28/19, 16:38:15:791 CDT] 0000004d id=00000000 com.ibm.ws.opentracing.OpentracingTracerManager              < getTracer (newly stored for jaxrsfun) in (Default Executor-thread-16:77) Exit  
                                                                                                               null
[10/28/19, 16:38:15:791 CDT] 0000004d id=00000000 com.ibm.ws.opentracing.OpentracingContainerFilter            3 filter(incoming) no tracer
[10/28/19, 16:38:15:791 CDT] 0000004d id=2a8cc0c5 com.ibm.ws.opentracing.OpentracingContainerFilter            < filter Exit 
[10/28/19, 16:38:15:793 CDT] 0000004d id=00000000 SystemOut                                                    O ** throwing npe
[10/28/19, 16:38:15:801 CDT] 0000004d id=2a8cc0c5 com.ibm.ws.opentracing.OpentracingContainerFilter            > toResponse Entry  
                                                                                                               java.lang.NullPointerException: argh
	at kabasec.Logout.logout(Logout.java:55)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.ibm.ws.jaxrs20.server.LibertyJaxRsServerFactoryBean.performInvocation(LibertyJaxRsServerFactoryBean.java:656)
	at com.ibm.ws.jaxrs20.server.LibertyJaxRsInvoker.performInvocation(LibertyJaxRsInvoker.java:160)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
	at com.ibm.ws.jaxrs20.server.LibertyJaxRsInvoker.invoke(LibertyJaxRsInvoker.java:273)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:205)
	at com.ibm.ws.jaxrs20.server.LibertyJaxRsInvoker.invoke(LibertyJaxRsInvoker.java:444)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:111)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:61)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:99)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:124)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:275)
	at com.ibm.ws.jaxrs20.endpoint.AbstractJaxRsWebEndpoint.invoke(AbstractJaxRsWebEndpoint.java:134)
	at com.ibm.websphere.jaxrs.server.IBMRestServlet.handleRequest(IBMRestServlet.java:146)
	at com.ibm.websphere.jaxrs.server.IBMRestServlet.doGet(IBMRestServlet.java:112)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:686)
	at com.ibm.websphere.jaxrs.server.IBMRestServlet.service(IBMRestServlet.java:96)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1230)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:729)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:426)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1218)
	at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:5017)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.handleRequest(DynamicVirtualHost.java:314)
	at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:1007)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:279)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1136)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:417)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:376)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:547)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:481)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:346)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.ready(HttpInboundLink.java:317)
	at com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.sendToDiscriminators(NewConnectionInitialReadCallback.java:165)
	at com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.complete(NewConnectionInitialReadCallback.java:74)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:503)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueManager.java:573)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:954)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:1043)
	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:239)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:825)

[10/28/19, 16:38:15:805 CDT] 0000004d id=2a8cc0c5 com.ibm.ws.opentracing.OpentracingContainerFilter            < toResponse Exit  
                                                                                                               org.apache.cxf.jaxrs.impl.ResponseImpl@bfba4706
[10/28/19, 16:38:15:807 CDT] 0000004d id=2a8cc0c5 com.ibm.ws.opentracing.OpentracingContainerFilter            > filter Entry  
                                                                                                               org.apache.cxf.jaxrs.impl.ContainerRequestContextImpl@bf5dfe7d
                                                                                                               org.apache.cxf.jaxrs.impl.ContainerResponseContextImpl@5a8c5d32
[10/28/19, 16:38:15:808 CDT] 0000004d id=00000000 com.ibm.ws.opentracing.OpentracingContainerFilter            3 filter(outgoing) no span
[10/28/19, 16:38:15:808 CDT] 0000004d id=2a8cc0c5 com.ibm.ws.opentracing.OpentracingContainerFilter            < filter Exit 
```

I don't like how this is designed... basically it tells OpenLiberty that this exception is "handled" by mapping it to a Response.  Without OT, the exception is unhandled (the application provides no ExceptionMapper), and so the exception is logged.  But with OT, the JAX-RS implementation code thinks that the exception is handled and just returns the mapped response.  This seems to violate the JAX-RS specification section 3.3.4 - sub-paragraph 3, which says:
```
3. Unchecked exceptions and errors that have not been mapped MUST be re-thrown and allowed to propagate to the underlying container.
```

So the OT feature is preventing that by performing it's own mapping.  Maybe that is ok because the user would have had to specifically request a non-Java-EE feature, but it seems unintuitive to me.  

So the question now is what can we do to fix it?
1) The zero-migration policy (and possibly the MP OT Spec/TCK) might end up preventing us from changing the OT implementation to no longer map unhandled exceptions to responses... but if not, then that seems like the best course of action to me.
2) If we cannot change the behavior of OT, then we could log the exception in the OT's ExceptionMapper, basically modify `com.ibm.ws.opentracing.OpentracingContainerFilter.toResponse(...)` from:
```
    public Response toResponse(Throwable exception) {
        return Response.serverError().header(EXCEPTION_KEY, exception).build();
    }
```

to something like:
```
    public Response toResponse(Throwable exception) {
        Tr.warning(tc, CONVERTING_UNHANDLED_THROWABLE_TO_RESPONSE, exception);
        return Response.serverError().header(EXCEPTION_KEY, exception).build();
    }
```

That would at least put the stack trace back in the logs - it won't be completely consistent with the non-OT case (the exception will be logged from another spot in the code), but it will help the user understand what went wrong.
