### ISSUE TITLE
ClassNotFoundException during deployment

### ISSUE THREAD

**Issue by oskar7000** [OpenLiberty/open-liberty#9353]
I'm getting FFDC errors during deployment.
This is on wlp version 19.0.0.9 running in a Kubernetes container.

Here is a stack trace
```
Stack Dump = com.ibm.ws.container.service.state.StateChangeException: com.ibm.ws.cdi.CDIException: com.ibm.wsspi.injectionengine.InjectionException: com.ibm.ejs.container.EJBConfigurationException: EJB class com.ibm.entity.analytics.operational.cache.api.rest.service.ConnectionService must have a public constructor that takes no parameters : operational-cache-api-rest#operational-cache-api-rest.war#ConnectionService
        at com.ibm.ws.cdi.liberty.CDIRuntimeImpl.applicationStarting(CDIRuntimeImpl.java:453)
        at com.ibm.ws.container.service.state.internal.ApplicationStateManager.fireStarting(ApplicationStateManager.java:51)
        at com.ibm.ws.container.service.state.internal.StateChangeServiceImpl.fireApplicationStarting(StateChangeServiceImpl.java:50)
        at com.ibm.ws.app.manager.module.internal.SimpleDeployedAppInfoBase.preDeployApp(SimpleDeployedAppInfoBase.java:550)
        at com.ibm.ws.app.manager.module.internal.SimpleDeployedAppInfoBase.installApp(SimpleDeployedAppInfoBase.java:511)
        at com.ibm.ws.app.manager.module.internal.DeployedAppInfoBase.deployApp(DeployedAppInfoBase.java:347)
        at com.ibm.ws.app.manager.war.internal.WARApplicationHandlerImpl.install(WARApplicationHandlerImpl.java:65)
        at com.ibm.ws.app.manager.internal.statemachine.StartAction.execute(StartAction.java:140)
        at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.enterState(ApplicationStateMachineImpl.java:1266)
        at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.performAction(ApplicationStateMachineImpl.java:1146)
        at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.run(ApplicationStateMachineImpl.java:889)
        at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:239)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: com.ibm.ws.cdi.CDIException: com.ibm.wsspi.injectionengine.InjectionException: com.ibm.ejs.container.EJBConfigurationException: EJB class com.ibm.entity.analytics.operational.cache.api.rest.service.ConnectionService must have a public constructor that takes no parameters : operational-cache-api-rest#operational-cache-api-rest.war#ConnectionService
        at com.ibm.ws.cdi.impl.weld.WebSphereCDIDeploymentImpl.initializeInjectionServices(WebSphereCDIDeploymentImpl.java:633)
        at com.ibm.ws.cdi.impl.CDIContainerImpl.startInitialization(CDIContainerImpl.java:138)
        at com.ibm.ws.cdi.liberty.CDIRuntimeImpl.applicationStarting(CDIRuntimeImpl.java:448)
        ... 14 more
Caused by: com.ibm.wsspi.injectionengine.InjectionException: com.ibm.ejs.container.EJBConfigurationException: EJB class com.ibm.entity.analytics.operational.cache.api.rest.service.ConnectionService must have a public constructor that takes no parameters : operational-cache-api-rest#operational-cache-api-rest.war#ConnectionService
        at com.ibm.ws.ejbcontainer.runtime.ComponentNameSpaceConfigurationProviderImpl.getComponentNameSpaceConfiguration(ComponentNameSpaceConfigurationProviderImpl.java:49)
        at com.ibm.ws.injectionengine.ReferenceContextImpl.processImpl(ReferenceContextImpl.java:326)
        at com.ibm.ws.injectionengine.ReferenceContextImpl.process(ReferenceContextImpl.java:287)
        at com.ibm.ws.injectionengine.osgi.internal.OSGiReferenceContextImpl.process(OSGiReferenceContextImpl.java:30)
        at com.ibm.ws.cdi.impl.weld.WebSphereCDIDeploymentImpl.initializeInjectionServices(WebSphereCDIDeploymentImpl.java:631)
        ... 16 more
Caused by: com.ibm.ejs.container.EJBConfigurationException: EJB class com.ibm.entity.analytics.operational.cache.api.rest.service.ConnectionService must have a public constructor that takes no parameters : operational-cache-api-rest#operational-cache-api-rest.war#ConnectionService
        at com.ibm.ws.ejbcontainer.jitdeploy.EJBUtils.validateEjbClass(EJBUtils.java:346)
        at com.ibm.ws.ejbcontainer.jitdeploy.JITDeploy.validateInterfaceBasics(JITDeploy.java:203)
        at com.ibm.ws.metadata.ejb.EJBMDOrchestrator.loadCustomerProvidedClasses(EJBMDOrchestrator.java:3655)
        at com.ibm.ws.metadata.ejb.EJBMDOrchestrator.finishBMDInitForReferenceContext(EJBMDOrchestrator.java:6832)
        at com.ibm.ws.ejbcontainer.osgi.internal.EJBMDOrchestratorImpl.finishBMDInitForReferenceContextPrivileged(EJBMDOrchestratorImpl.java:782)
        at com.ibm.ws.ejbcontainer.osgi.internal.EJBMDOrchestratorImpl.access$000(EJBMDOrchestratorImpl.java:69)
        at com.ibm.ws.ejbcontainer.osgi.internal.EJBMDOrchestratorImpl$1.run(EJBMDOrchestratorImpl.java:795)
        at com.ibm.ws.ejbcontainer.osgi.internal.EJBMDOrchestratorImpl$1.run(EJBMDOrchestratorImpl.java:792)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.ibm.ws.ejbcontainer.osgi.internal.EJBMDOrchestratorImpl.finishBMDInitForReferenceContext(EJBMDOrchestratorImpl.java:792)
        at com.ibm.ws.ejbcontainer.runtime.AbstractEJBRuntime.finishBMDInitForReferenceContext(AbstractEJBRuntime.java:1526)
        at com.ibm.ws.ejbcontainer.runtime.ComponentNameSpaceConfigurationProviderImpl.getComponentNameSpaceConfiguration(ComponentNameSpaceConfigurationProviderImpl.java:43)
        ... 20 more
Caused by: java.lang.NoClassDefFoundError: com/ibm/entity/analytics/graph/core/exception/AnalyticsGraphException
        at java.lang.Class.getDeclaredConstructors0(Native Method)
        at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
        at java.lang.Class.getConstructor0(Class.java:3075)
        at java.lang.Class.getConstructor(Class.java:1825)
        at com.ibm.ws.ejbcontainer.jitdeploy.EJBUtils.validateEjbClass(EJBUtils.java:337)
        ... 31 more
Caused by: java.lang.ClassNotFoundException: com.ibm.entity.analytics.graph.core.exception.AnalyticsGraphException
        at com.ibm.ws.classloading.internal.AppClassLoader.findClassCommonLibraryClassLoaders(AppClassLoader.java:546)
        at com.ibm.ws.classloading.internal.AppClassLoader.findClass(AppClassLoader.java:288)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at com.ibm.ws.classloading.internal.AppClassLoader.findOrDelegateLoadClass(AppClassLoader.java:524)
        at com.ibm.ws.classloading.internal.AppClassLoader.loadClass(AppClassLoader.java:484)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 36 more
```

Library specification in server.xml
```
	<library id="cacheLibrary">
		<folder dir="${product.home}/conf/spark"/>
		<fileset dir="${product.home}/lib" includes="*.jar"/>
		<fileset dir="${product.home}/lib/transform" includes="*.jar"/>
	</library>
```

and webAplication
```
	<webApplication id="cache-api-rest" location="operational-cache-api-rest.war" name="cache-api-rest">
		<classloader privateLibraryRef="cacheLibrary"/>
	</webApplication>
```

product.home is specified in bootstrap.properties
`product.home=${wlp.install.dir}/..`

The project directory
bash-4.4$ ls -l
total 4
drwxrwxr-x  2 root root  141 Oct 10 03:27 bin
drwxrwxr-x  1 root root   22 Oct 15 13:26 conf
drwxrwxr-x  4 root root   57 Oct 10 03:27 derby
drwxrwxr-x  4 root root   41 Oct 10 03:27 etc
drwxrwxr-x 12 root root  221 Oct 10 03:27 janus
drwxrwxr-x  2 root root 4096 Oct 10 03:27 lib
drwxrwxr-x  2 root root   58 Oct 10 03:27 newrelic
drwxrwxr-x  1 root root   28 Oct 15 13:51 wlp

and verification the class does exist
bash-4.4$ grep -l com.ibm/entity/analytics/graph/core/exception/AnalyticsGraphException lib/*
lib/analytics-graph-core-0.1.0-20191007.195739-42.jar

What might be happening here?

**Comment by oskar7000** [comment]
I uploaded the files to https://ibm.ent.box.com/folder/90483009886

**Comment by jaridk** [comment]
Hi, Oskar. I'm unable to access that file - can you add Andy and me to the access list for it?

**Comment by jaridk** [comment]
Also curious if this is a regression (something that worked in a previous Liberty build) or a new application, as that affects how we approach the investigation.

**Comment by oskar7000** [comment]
You have both been added.
This has be an issue for a while, not sure how long, so I don't know if this is a regression or not.  The services work after the deployment but the errors are affecting our build process where readiness checks are failing during build testing.
I can set up a server you can access.  I will send you the details once this is ready.

**Comment by oskar7000** [comment]
I have set up a box `tectrix1.fyre.ibm.com`.
I will send you the credentials on slack.
To access the WLP Kubernetes container type
`kubectl exec -it operational-cache-6dbcc476fc-wwr9v bash`
WLP is located at `/usr/operational-cache/wlp/`

**Comment by andymc12** [comment]
Hi @oskar7000 - it looks like you have two versions of the same app starting.  From looking at the ApplicationConfigurator.txt file in the dump, I see the following:
```
Applications
------------
  app[analytics-gateway-api-rest,war]
ASM
Sequence Number: 0
Internal State: STARTED
Callback State: null
Waiting for App Handler: AppDep[7]: desc="resolves when the app handler for this app arrives", future=com.ibm.ws.threading.internal.NonCancelableResultFuture@566f586b[success result=java.lang.Boolean@5acf71e3]
  app[cache-api-rest,war]
ASM
Sequence Number: 1
Internal State: STARTED
Callback State: null
Waiting for App Handler: AppDep[12]: desc="resolves when the app handler for this app arrives", future=com.ibm.ws.threading.internal.NonCancelableResultFuture@1a2ac274[success result=java.lang.Boolean@5acf71e3]
  app[operational-cache-api-rest,war]
ASM
Sequence Number: 2
Internal State: FAILED
Callback State: null
Waiting for App Handler: AppDep[17]: desc="resolves when the app handler for this app arrives", future=com.ibm.ws.threading.internal.NonCancelableResultFuture@471eb653[success result=java.lang.Boolean@5acf71e3]
```

Note that your server.xml only specifies two apps:
```
	<!-- Application config -->
	<webApplication id="analytics-gateway-api-rest" location="analytics-gateway-api-rest.war" name="analytics-gateway-api-rest">
...
	</webApplication>
	
	<webApplication id="cache-api-rest" location="operational-cache-api-rest.war" name="cache-api-rest">
		<classloader privateLibraryRef="cacheLibrary"/>
...
	</webApplication>
```

The second app is interesting in that it has a different name and id than the file name - the file name is `operational-cache-api-rest.war`, but the id and name are both `cache-api-rest`.  Also, note that the `cache-api-rest` app started successfully, according to the ApplicationConfigurator.txt output, but that the `operational-cache-api-rest` did not.

My guess is that the operational-cache-api-rest.war file may also exist in the `dropins` directory, and since the name/ID does not clash, it is starting _three_ apps:  the two apps specified in the server.xml plus the (duplicated) operational-cache-api-rest.war in the dropins directory.  Since apps in the dropins directory cannot be configured to use shared libraries, it fails to find the AnalyticsGraphException and fails to start. 

Please check your server directory to see if there is a dropins directory, and whether there are any war files there.  If so, you should delete them, and then I think everything will work as expected.  If not, then there may be some sort of bug in how Liberty handles an application that uses a different name/ID than the file name...

Hope this helps

**Comment by oskar7000** [comment]
Thanks @andymc12, this really helped.  I checked the dropins directory and it is empty
```
bash-4.4$ ls -l /usr/operational-cache/wlp/usr/servers/cache-server/dropins/
total 0
```

I changed the name and id to match the file name and the problem disappeared.  I also tried changing just the name and again the problem vanished.  I tried the same for the id and the problem was gone.
In this case it seems having the name and id the same but differing from the file name causes the issue.

**Comment by andymc12** [comment]
@oskar7000 - yeah, that definitely sounds like a bug, but I cannot seem to reproduce it.  I'll attach the server zip that I'm using (very simple JAX-RS app that depends on a shared library - has the same value for app id and name, but different from the location).  For me, it only starts one instance of the app, and if I attempt to access the JAX-RS resource it is able to load the class from the shared library.  If I copy the WAR file to the dropins directory, and then try to invoke the JAX-RS resource, then it fails (as expected) because it cannot find the shared library class.
[issue9353.zip](https://github.com/OpenLiberty/open-liberty/files/3768553/issue9353.zip)

Could you either post your zipped up server environment or modify mine to reproduce the problem and repost it?

Also, I've asked the kernel / app manager team to take a look at this issue too, as I'm more of a JAX-RS/classloading guy.

Thanks!

**Comment by oskar7000** [comment]
@andymc12 sorry for a late response.  It turns out the problem was caused by content in the `usr/servers/cache-server/configDropins` folder.  Cleaning out that folder cleared up the issue.
