### ISSUE TITLE
NullPointerException when using dynamic filter to add mapping for servlet name

### ISSUE THREAD

**Issue by pmd1nh** [OpenLiberty/open-liberty#9386]
If application first adds a filter and maps it to a named servlet, for example:

FilterRegistration.Dynamic filter = servletContext.addFilter( "myFilter" , myFilter.class);
filter.addMappingForServletNames(dispatcherTypes, true,"myServlet");

Note that the target servlet "myServlet" has been not defined yet at this point, and it is going to be defined later with
ServletRegistration.Dynamic servlet = servletContext.addServlet("myServlet" , myServlet.class);

When the web request is processed later, a NullPointerException may occur with similar stack:

SRVE0293E: [Servlet Error]-[xxxx]: java.lang.NullPointerException
at com.ibm.ws.webcontainer.filter.WebAppFilterManager.getFilterChainContents(WebAppFilterManager.java:777)
at com.ibm.ws.webcontainer.filter.WebAppFilterManager.getFilterChain(WebAppFilterManager.java:373)
at com.ibm.ws.webcontainer.filter.WebAppFilterManager.doFilter(WebAppFilterManager.java:933)
at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:109)
at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:4217)
...

A workaround is to define the servlets prior to use it in the dynamic filter mappings.  However, this rearrangement does not work when using with Spring Boot container which always invoke the filter operations before the servlet.

**Comment by pmd1nh** [comment]
https://github.com/OpenLiberty/open-liberty/pull/9390
