### ISSUE TITLE
Enable parallel bundle activation in the security features

### ISSUE THREAD

**Issue by tevans78** [OpenLiberty/open-liberty#9407]
While working on parallel bundle activation for the MicroProfile features (https://github.com/OpenLiberty/open-liberty/issues/8854), I encountered some issues in the security code. Therefore parallel activation for the security features need to be worked on separately. See the issue above for instructions on enabling parallel bundle activation.

The specific issue that I encountered was a NPE in `com.ibm.ws.security.appbnd.internal.delegation.DefaultDelegationProvider`.
```
Stack Dump = java.lang.NullPointerException
    at com.ibm.ws.security.appbnd.internal.delegation.DefaultDelegationProvider.authenticateRunAsUser(DefaultDelegationProvider.java:186)
    at com.ibm.ws.security.appbnd.internal.delegation.DefaultDelegationProvider.getRunAsSubject(DefaultDelegationProvider.java:64)
    at com.ibm.ws.security.authentication.internal.AuthenticationServiceImpl.getRunAsSubjectFromProvider(AuthenticationServiceImpl.java:555)
    at com.ibm.ws.security.authentication.internal.AuthenticationServiceImpl.delegate(AuthenticationServiceImpl.java:541)
    at com.ibm.ws.ejbcontainer.security.internal.EJBSecurityCollaboratorImpl.performDelegation(EJBSecurityCollaboratorImpl.java:612)
    at com.ibm.ws.ejbcontainer.security.internal.EJBSecurityCollaboratorImpl.preInvoke(EJBSecurityCollaboratorImpl.java:197)
    at com.ibm.ws.ejbcontainer.security.internal.EJBSecurityCollaboratorImpl.preInvoke(EJBSecurityCollaboratorImpl.java:69)
    at com.ibm.ejs.container.EJSContainer.notifySecurityCollaboratorPreInvoke(EJSContainer.java:3147)
    at com.ibm.ejs.container.EJSContainer.preInvokeAfterActivate(EJSContainer.java:3092)
    at com.ibm.ejs.container.EJSContainer.preInvoke(EJSContainer.java:2322)
    at com.ibm.ejs.container.EJSContainer.preInvoke(EJSContainer.java:2253)
    at com.ibm.ejs.container.EJSHome.createBusinessObjectWrappers(EJSHome.java:1816)
    at com.ibm.ws.ejbcontainer.internal.EJBReferenceFactoryImpl.create(EJBReferenceFactoryImpl.java:56)
    at com.ibm.ws.cdi.ejb.impl.WebSphereEjbServicesImpl.resolveEjb(WebSphereEjbServicesImpl.java:106)
    at org.jboss.weld.bean.SessionBean.createReference(SessionBean.java:235)
```
This suggests that `DefaultDelegationProvider.securityService` is null. That is set during activation of AppBndAuthorizationTableService. The SecurityService reference in BaseAuthorizationTableService is OPTIONAL and DYNAMIC so it can easy be null at that point. 

Either the reference to SecurityService in BaseAuthorizationTableService needs to be changed so that it is never null OR DefaultDelegationProvider needs to be able to cope with the fact that it can be null.

**Comment by utle** [comment]
Fixed AppBndAuthorizationTableService for security service from OPTIONAL to MANDATORY
https://github.com/OpenLiberty/open-liberty/pull/9415
