### ISSUE TITLE
Test Failure: junit.framework.TestSuite.com.ibm.ws.logging.fat.JSONFieldsTest

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#9419]
RTC 268744

```
com.ibm.ws.logging.fat.JSONFieldsTest:junit.framework.AssertionFailedError: A problem was detected during post-test tidy up. New FFDC file is generated. Please check the log directory. The beginning of the FFDC file is:
>------Start of DE processing------ = [10/20/19 16:50:10:743 GMT]
>Exception = com.ibm.ws.timedexit.internal.TimedExitThread$TimedExitException
>Source = com.ibm.ws.timedexit.internal.TimedExitThread
>probeid = run
>Stack Dump = com.ibm.ws.timedexit.internal.TimedExitThread$TimedExitException: Server was forced to shutdown by timed exit.
>at com.ibm.ws.timedexit.internal.TimedExitThread.run(TimedExitThread.java:137)

at componenttest.custom.junit.runner.FATRunner.blowup(FATRunner.java:296)
at componenttest.custom.junit.runner.FATRunner.access$600(FATRunner.java:64)
at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:337)
at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:167)

```

**Comment by fmhwong** [comment]
Not occurred in last 2 weeks
