### ISSUE TITLE
EJB Custom Bindings: Investigate 'ejblocal:' added to jndi name in xmi (for remote beans)

### ISSUE THREAD

**Issue by olendvcook** [OpenLiberty/open-liberty#9461]
In #8999 I tested only local beans.

**Comment by olendvcook** [comment]
Conclusion: remote beans fail to bind when namespaces are in the jndiName element:

```
[10/31/19 10:46:08:253 CDT] 000000a1 SharedEJBRunt E   WSVR0062E: Unable to start EJB, JNDINameTestApp#JNDINameEJB.jar#RemoteJNDIName3: javax.naming.OperationNotSupportedException: URL ejblocal:com/ibm/ejb2x/jndiName/ejb/RemoteJNDINameHome3 does not resolve to a context which supports IOR bindings.
	at com.ibm.ws.naming.jndicos.CNContextImpl.bindIOR(CNContextImpl.java:1551)
	at com.ibm.ws.naming.jndicos.CNContextImpl.rebindIOR(CNContextImpl.java:1512)
	at com.ibm.ws.runtime.component.WASNameSpaceBinderImpl$IORBindableObjectImpl.rebind(WASNameSpaceBinderImpl.java:438)
	at com.ibm.ws.ejbcontainer.runtime.SharedNameSpaceBinderImpl.bindObject(SharedNameSpaceBinderImpl.java:308)
	at com.ibm.ws.runtime.component.WASNameSpaceBinderImpl.recursiveBindObject(WASNameSpaceBinderImpl.java:696)
	at com.ibm.ws.runtime.component.WASNameSpaceBinderImpl.bindBindings(WASNameSpaceBinderImpl.java:823)
	at com.ibm.ws.ejbcontainer.runtime.AbstractEJBRuntime.bindInterface(AbstractEJBRuntime.java:1199)
	at com.ibm.ws.ejbcontainer.runtime.AbstractEJBRuntime.bindInterfaces(AbstractEJBRuntime.java:1134)
	at com.ibm.ws.ejbcontainer.runtime.AbstractEJBRuntime.bindInterfaces(AbstractEJBRuntime.java:1056)
	at com.ibm.ws.ejbcontainer.runtime.SharedEJBRuntimeImpl.bindInterfaces(SharedEJBRuntimeImpl.java:372)
	at com.ibm.ws.ejbcontainer.runtime.AbstractEJBRuntime.startModule(AbstractEJBRuntime.java:680)
	at com.ibm.ws.ejbcontainer.runtime.SharedEJBRuntimeImpl.startModule(SharedEJBRuntimeImpl.java:338)
	at com.ibm.ws.runtime.component.EJBContainerImpl.start(EJBContainerImpl.java:3588)
```

**Comment by olendvcook** [comment]
Opened #9557 to add tests to address the concluded behavior
