### ISSUE TITLE
EJB Custom Bindings: Investigate 'ejblocal:' added to simple-binding-name in xml (for remote beans)

### ISSUE THREAD

**Issue by olendvcook** [OpenLiberty/open-liberty#9462]
In #8999 I investigated adding `ejblocal:` to the `jndiName=` xmi element but only for local beans, I opened #9461 to investigate that for remote beans.

After starting to look at our implementation I discovered that the jndiName element in xmi and the simple-binding-name element in xml go to the same variable in BeanMetaData. I'm pretty sure this is true, be should confirm all the rules discovered in #9461 apply to simple-binding-name for remote beans.
(Note that this task exists for local beans here: #9456 they could possibly be combined)

**Comment by olendvcook** [comment]
I have discovered that the application fails to start with an error if you stick `local:` or `ejblocal:` in the simple-binding-name xml element for remote beans:

(Note: as discovered in #9456, local beans will work, if a bean has local and remote homes, the local will be bound but then the remote will fail)

```
[10/29/19 16:16:26:235 CDT] 000000a8 SharedEJBRunt E   WSVR0062E: Unable to start EJB, SimpleBindingNameTestApp#SimpleBindingNameEJB.jar#RemoteSimpleBindingName3: javax.naming.OperationNotSupportedException: URL ejblocal:com/ibm/ejb3x/SimpleBindingName/ejb/RemoteSimpleBindingNameHome3 does not resolve to a context which supports IOR bindings.
	at com.ibm.ws.naming.jndicos.CNContextImpl.bindIOR(CNContextImpl.java:1551)
	at com.ibm.ws.naming.jndicos.CNContextImpl.rebindIOR(CNContextImpl.java:1512)
	at com.ibm.ws.runtime.component.WASNameSpaceBinderImpl$IORBindableObjectImpl.rebind(WASNameSpaceBinderImpl.java:438)
	at com.ibm.ws.ejbcontainer.runtime.SharedNameSpaceBinderImpl.bindObject(SharedNameSpaceBinderImpl.java:308)
	at com.ibm.ws.runtime.component.WASNameSpaceBinderImpl.recursiveBindObject(WASNameSpaceBinderImpl.java:696)
	at com.ibm.ws.runtime.component.WASNameSpaceBinderImpl.bindBindings(WASNameSpaceBinderImpl.java:823)
	at com.ibm.ws.ejbcontainer.runtime.AbstractEJBRuntime.bindInterface(AbstractEJBRuntime.java:1199)
	at com.ibm.ws.ejbcontainer.runtime.AbstractEJBRuntime.bindInterfaces(AbstractEJBRuntime.java:1134)
	at com.ibm.ws.ejbcontainer.runtime.AbstractEJBRuntime.bindInterfaces(AbstractEJBRuntime.java:1056)
	at com.ibm.ws.ejbcontainer.runtime.SharedEJBRuntimeImpl.bindInterfaces(SharedEJBRuntimeImpl.java:372)
	at com.ibm.ws.ejbcontainer.runtime.AbstractEJBRuntime.startModule(AbstractEJBRuntime.java:680)
	at com.ibm.ws.ejbcontainer.runtime.SharedEJBRuntimeImpl.startModule(SharedEJBRuntimeImpl.java:338)
	at com.ibm.ws.runtime.component.EJBContainerImpl.start(EJBContainerImpl.java:3588)
```

```
[10/29/19 16:16:26:292 CDT] 000000a8 DeployedAppli W   WSVR0206E: Module, SimpleBindingNameEJB.jar, of application, SimpleBindingNameTestApp.ear/deployments/SimpleBindingNameTestApp, failed to start
[10/29/19 16:16:26:294 CDT] 000000a8 ApplicationMg E   WSVR0101W: An error occurred starting, SimpleBindingNameTestApp
[10/29/19 16:16:26:294 CDT] 000000a8 ApplicationMg A   WSVR0217I: Stopping application: SimpleBindingNameTestApp
```

**Comment by olendvcook** [comment]
Opened #9557 to add tests to address the concluded behavior
