### ISSUE TITLE
EJB Custom Bindings: Investigate 'local:' added to (local|remote)-home-binding in xml

### ISSUE THREAD

**Issue by olendvcook** [OpenLiberty/open-liberty#9463]
In #8999 I discovered that you can stick multiple namespaces in the `jndiName` element for xmi, and all but the innermost element is ignored. We have code that validates that `local-home-binding` starts with `ejblocal:` but what happens if it starts with `ejblocal:local:`?

Similarly, we validate that `remote-home-binding` does not start with `ejblocal:` but what if it starts with `local:`?

**Comment by olendvcook** [comment]
All the `remote-home-binding` binds with `local:` in them fail:

```
[12/3/19 16:57:37:558 CST] 000000b7 SharedEJBRunt E   WSVR0062E: Unable to start EJB, HomeBindingNameTestApp#HomeBindingNameEJB.jar#RemoteHomeBindingName3: javax.naming.OperationNotSupportedException: URL local:com/ibm/ejb3x/HomeBindingName/ejb/RemoteHomeBindingNameHome3 does not resolve to a context which supports IOR bindings.
	at com.ibm.ws.naming.jndicos.CNContextImpl.bindIOR(CNContextImpl.java:1551)
	at com.ibm.ws.naming.jndicos.CNContextImpl.rebindIOR(CNContextImpl.java:1512)
	at com.ibm.ws.runtime.component.WASNameSpaceBinderImpl$IORBindableObjectImpl.rebind(WASNameSpaceBinderImpl.java:438)
	at com.ibm.ws.ejbcontainer.runtime.SharedNameSpaceBinderImpl.bindObject(SharedNameSpaceBinderImpl.java:308)
	at com.ibm.ws.runtime.component.WASNameSpaceBinderImpl.recursiveBindObject(WASNameSpaceBinderImpl.java:696)
	at com.ibm.ws.runtime.component.WASNameSpaceBinderImpl.bindBindings(WASNameSpaceBinderImpl.java:823)
	at com.ibm.ws.ejbcontainer.runtime.AbstractEJBRuntime.bindInterface(AbstractEJBRuntime.java:1199)
	at com.ibm.ws.ejbcontainer.runtime.AbstractEJBRuntime.bindInterfaces(AbstractEJBRuntime.java:1134)
	at com.ibm.ws.ejbcontainer.runtime.AbstractEJBRuntime.bindInterfaces(AbstractEJBRuntime.java:1056)
	at com.ibm.ws.ejbcontainer.runtime.SharedEJBRuntimeImpl.bindInterfaces(SharedEJBRuntimeImpl.java:372)
	at com.ibm.ws.ejbcontainer.runtime.AbstractEJBRuntime.startModule(AbstractEJBRuntime.java:680)
	at com.ibm.ws.ejbcontainer.runtime.SharedEJBRuntimeImpl.startModule(SharedEJBRuntimeImpl.java:338)
	at com.ibm.ws.runtime.component.EJBContainerImpl.start(EJBContainerImpl.java:3588)
```
