### ISSUE TITLE
ConcurrentModificationException in JAX-RS on shutdown

### ISSUE THREAD

**Issue by andymc12** [OpenLiberty/open-liberty#9492]
When using JAX-RS and CDI, it is possible to see a ConcurrentModificationException on app shutdown that looks like this:

```
Stack Dump = javax.servlet.ServletException: java.util.ConcurrentModificationException
    at com.ibm.ws.webcontainer.servlet.ServletWrapper.doDestroy(ServletWrapper.java:1049)
    at com.ibm.ws.webcontainer.servlet.ServletWrapper.destroy(ServletWrapper.java:1126)
    at com.ibm.ws.webcontainer.osgi.servlet.ServletWrapper.destroy(ServletWrapper.java:91)
    at com.ibm.ws.webcontainer.webapp.WebApp.destroy(WebApp.java:3939)
    at com.ibm.ws.webcontainer.osgi.webapp.WebApp.destroy(WebApp.java:1477)
    at com.ibm.ws.container.AbstractContainer.destroy(AbstractContainer.java:79)
    at com.ibm.ws.webcontainer.webapp.WebGroup.destroy(WebGroup.java:215)
    at com.ibm.ws.webcontainer.webapp.WebGroup.removeWebApplication(WebGroup.java:256)
    at com.ibm.ws.webcontainer.VirtualHost.removeWebApplication(VirtualHost.java:264)
    at com.ibm.ws.webcontainer.VirtualHost.removeWebApplication(VirtualHost.java:241)
    at com.ibm.ws.webcontainer.WebContainer.removeWebApplication(WebContainer.java:596)
    at com.ibm.ws.webcontainer.osgi.WebContainer.removeModule(WebContainer.java:1223)
    at com.ibm.ws.webcontainer.osgi.WebContainer.stopModule(WebContainer.java:1187)
    at com.ibm.ws.app.manager.module.internal.ModuleHandlerBase.undeployModule(ModuleHandlerBase.java:133)
    at com.ibm.ws.app.manager.module.internal.DeployedModuleInfoImpl.uninstallModule(DeployedModuleInfoImpl.java:64)
    at com.ibm.ws.app.manager.module.internal.SimpleDeployedAppInfoBase.uninstallApp(SimpleDeployedAppInfoBase.java:638)
    at com.ibm.ws.app.manager.war.internal.WARApplicationHandlerImpl.uninstall(WARApplicationHandlerImpl.java:81)
    at com.ibm.ws.app.manager.internal.statemachine.StopAction.execute(StopAction.java:83)
    at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.enterState(ApplicationStateMachineImpl.java:1291)
    at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.performAction(ApplicationStateMachineImpl.java:1134)
    at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.run(ApplicationStateMachineImpl.java:889)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:825)
Caused by: java.util.ConcurrentModificationException
    at java.base/java.util.WeakHashMap$HashIterator.remove(WeakHashMap.java:822)
    at com.ibm.ws.jaxrs20.cdi.component.JaxRsFactoryImplicitBeanCDICustomizer.destroyApplicationScopeResources(JaxRsFactoryImplicitBeanCDICustomizer.java:735)
    at com.ibm.ws.jaxrs20.server.JaxRsWebEndpointImpl.destroy(JaxRsWebEndpointImpl.java:120)
    at com.ibm.websphere.jaxrs.server.IBMRestServlet.destroy(IBMRestServlet.java:164)
    at com.ibm.ws.webcontainer.servlet.ServletWrapper.doDestroy(ServletWrapper.java:1038)
    ... 23 more
```

This is the result of iterating over and removing items from a hash map while other threads could be doing the same (or clearing the map or adding to it).

**Comment by andymc12** [comment]
fixed by #9493
