### ISSUE TITLE
H2 intermittent error when upgrade fails

### ISSUE THREAD

**Issue by loriadi** [OpenLiberty/open-liberty#9679]

**Comment by loriadi** [comment]
>Stack Dump = com.ibm.wsspi.genericbnf.exception.MessageSentException: Message already sent
>at com.ibm.ws.http.channel.internal.inbound.HttpInboundServiceContextImpl.sendResponseHeaders(HttpInboundServiceContextImpl.java:685)
>at com.ibm.ws.http.channel.internal.outbound.HttpOutputStreamImpl.flushHeaders(HttpOutputStreamImpl.java:452)
>at com.ibm.ws.webcontainer31.osgi.response.IResponse31Impl.flushHeaders(IResponse31Impl.java:70)
>at com.ibm.ws.webcontainer31.srt.SRTServletResponse31.flushData(SRTServletResponse31.java:142)
>at com.ibm.ws.webcontainer31.srt.SRTServletResponse31.finishKeepConnection(SRTServletResponse31.java:107)
>at com.ibm.ws.webcontainer31.osgi.srt.SRTConnectionContext31.finishConnection(SRTConnectionContext31.java:152)
>at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:1166)
>at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:279)
>at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1136)
>at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:417)
>at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:376)
>at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:547)
>at com.ibm.ws.http.channel.internal.inbound.HttpInbound
