### ISSUE TITLE
Build break Test Failure: junit.framework.TestSuite.com.ibm.ws.session.cache.fat.infinispan.SessionCacheTimeoutTest

### ISSUE THREAD

**Issue by nmittles** [OpenLiberty/open-liberty#9687]
com.ibm.ws.session.cache.fat.infinispan.SessionCacheTimeoutTest:junit.framework.AssertionFailedError: Servlet call was not successful: ERROR: Caught exception
attempting to call test method sessionPut on servlet session.cache.infinispan.web.SessionCacheTestServlet java.lang.NullPointerException
at session.cache.infinispan.web.SessionCacheTestServlet.sessionPut(SessionCacheTestServlet.java:686)
at componenttest.app.FATServlet.doGet(FATServlet.java:67)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1230)

The test fails with the above exception.  The root exception is the SocketException shown below.  

java.net.SocketException: EDC8116I Address not available. (Error setting socket option)
    at java.net.PlainDatagramSocketImpl.socketSetOption0(Native Method)
    at java.net.PlainDatagramSocketImpl.socketSetOption(PlainDatagramSocketImpl.java:85)
    at java.net.AbstractPlainDatagramSocketImpl.setOption(AbstractPlainDatagramSocketImpl.java:320)
    at java.net.MulticastSocket.setInterface(MulticastSocket.java:482)
    at org.jgroups.protocols.MPING.start(MPING.java:190)
    at org.jgroups.stack.ProtocolStack.startStack(ProtocolStack.java:888)
    at org.jgroups.JChannel.startStack(JChannel.java:980)
    at org.jgroups.JChannel._preConnect(JChannel.java:844)
    at org.jgroups.JChannel.connect(JChannel.java:349)
    at org.jgroups.JChannel.connect(JChannel.java:343)
    at org.infinispan.remoting.transport.jgroups.JGroupsTransport.startJGroupsChannelIfNeeded(JGroupsTransport.java:510)
    ... 64 more

Server trace showing the infinispan config that is configured to use TCP:

[11/6/19 19:18:26:412 GMT] 0000002b id=7612bb2f com.ibm.ws.session.store.cache.CacheStoreService             3 generateOrUpdateInfinispanConfig
                                                                                                               /WebSphere/Misc/jazz_build/jbe_boss0228/jazz/buildsystem/buildengine/eclipse/build/dev/build.image/build/tmp/infinispan2891489551713766838.xml
                                                                                                               <?xml version="1.0" encoding="UTF-8"?><infinispan>
  <jgroups>
     <stack-file name="jgroups-tcp" path="/default-configs/default-jgroups-tcp.xml"/>
  </jgroups>

  <cache-container>
    <transport stack="jgroups-tcp"/>
    <replicated-cache-configuration name="com.ibm.ws.MyCache.attr"/>
    <invalidation-cache-configuration name="*.session.*.inval"/>
  <replicated-cache-configuration name="com.ibm.ws.session.*"/></cache-container>
</infinispan>

**Comment by nmittles** [comment]
Merged the PR with the fix on the 11th.
