### ISSUE TITLE
Segmentation fault after logging config added to server.xml

### ISSUE THREAD

**Issue by gjwatts** [OpenLiberty/open-liberty#9797]
[segmentation.txt](https://github.com/OpenLiberty/open-liberty/files/3852934/segmentation.txt)
[defaultServer.zip](https://github.com/OpenLiberty/open-liberty/files/3852915/defaultServer.zip)

**Describe the bug**
Segmentation fault after logging config added to server.xml following the steps in the main liberty beginner documentation -> https://openliberty.io/guides/getting-started.html#checking-the-open-liberty-server-logs

```
[INFO] [AUDIT   ] CWWKG0093A: Processing configuration drop-ins resource: C:\Users\GregoryWatts\git\guide-getting-started\start\target\liberty\wlp\usr\servers\defaultServer\configDropins\overrides\liberty-plugin-variable-config.xml
[INFO] [AUDIT   ] CWWKG0017I: The server configuration was successfully updated in 1.765 seconds.
[INFO] Unhandled exception
[INFO] Type=Segmentation error vmState=0x00000000
[INFO] Windows_ExceptionCode=c0000005 J9Generic_Signal=00000004 ExceptionAddress=00007FFCA8322F03 ContextFlags=0010005f
[INFO] Handler1=00007FFCE22DC290 Handler2=00007FFCF0DBCF20 InaccessibleReadAddress=FFFFFFFFFFFFFFFF
[INFO] RDI=00000000032E1E28 RSI=000000000FE922C0 RAX=AC4B4E2F08B5F138 RBX=CCCCCCCCCC0000C2
[INFO] RCX=0000000000001B0B RDX=00000000032E031D R8=00000000032E1E28 R9=0000000000000001
[INFO] R10=000000001A07DCB6 R11=0000000016524F90 R12=0000000000001B0B R13=00000000032E1A00
[INFO] R14=000000000000001C R15=000000000101F201
[INFO] RIP=00007FFCA8322F03 RSP=000000001930ECB0 RBP=00000000031A54D0 GS=002B
[INFO] FS=0053 ES=002B DS=002B
[INFO] XMM0 0000000000000006 (f: 6.000000, d: 2.964394e-323)
[INFO] XMM1 006e006500720061 (f: 7471201.000000, d: 1.335113e-306)
[INFO] XMM2 0000000003509100 (f: 55611648.000000, d: 2.747580e-316)
[INFO] XMM3 00007ffce2372c1a (f: 3795266560.000000, d: 6.952695e-310)
[INFO] XMM4 0000000000000000 (f: 0.000000, d: 0.000000e+000)
[INFO] XMM5 0000000000000000 (f: 0.000000, d: 0.000000e+000)
[INFO] XMM6 0000000000000000 (f: 0.000000, d: 0.000000e+000)
[INFO] XMM7 0000000000000000 (f: 0.000000, d: 0.000000e+000)
[INFO] XMM8 0000000000000000 (f: 0.000000, d: 0.000000e+000)
[INFO] XMM9 0000000000000000 (f: 0.000000, d: 0.000000e+000)
[INFO] XMM10 0000000000000000 (f: 0.000000, d: 0.000000e+000)
[INFO] XMM11 0000000000000000 (f: 0.000000, d: 0.000000e+000)
[INFO] XMM12 0000000000000000 (f: 0.000000, d: 0.000000e+000)
[INFO] XMM13 0000000000000000 (f: 0.000000, d: 0.000000e+000)
[INFO] XMM14 0000000000000000 (f: 0.000000, d: 0.000000e+000)
[INFO] XMM15 0000000000000000 (f: 0.000000, d: 0.000000e+000)
[INFO] Module=C:\Program Files\IBM\Java80\jre\bin\compressedrefs\j9jit29.dll
[INFO] Module_base_address=00007FFCA81F0000 Offset_in_DLL=0000000000132f03
[INFO] Target=2_90_20190617_419755 (Windows 10 10.0 build 18362)
[INFO] CPU=amd64 (8 logical CPUs) (0x7f2c10000 RAM)
[INFO] ----------- Stack Backtrace -----------
[ERROR] An error occurred while starting the server: CWWKM2002E: Failed to invoke ["C:\Users\GregoryWatts\git\guide-getting-started\start\target\liberty\wlp\bin\server.bat", debug, defaultServer]. RC= -1,073,741,819 but expected=[0].
org.apache.tools.ant.BuildException: CWWKM2002E: Failed to invoke ["C:\Users\GregoryWatts\git\guide-getting-started\start\target\liberty\wlp\bin\server.bat", debug, defaultServer]. RC= -1,073,741,819 but expected=[0].
    at io.openliberty.tools.ant.AbstractTask.checkReturnCode (AbstractTask.java:212)
    at io.openliberty.tools.ant.ServerTask.doDebug (ServerTask.java:442)
    at io.openliberty.tools.ant.ServerTask.execute (ServerTask.java:171)
    at io.openliberty.tools.common.plugins.util.DevUtil$1.run (DevUtil.java:440)
    at java.lang.Thread.run (Thread.java:818)
Exception in thread "Thread-9" CWWKM2002E: Failed to invoke ["C:\Users\GregoryWatts\git\guide-getting-started\start\target\liberty\wlp\bin\server.bat", debug, defaultServer]. RC= -1,073,741,819 but expected=[0].
        at io.openliberty.tools.ant.AbstractTask.checkReturnCode(AbstractTask.java:212)
        at io.openliberty.tools.ant.ServerTask.doDebug(ServerTask.java:442)
        at io.openliberty.tools.ant.ServerTask.execute(ServerTask.java:171)
        at io.openliberty.tools.common.plugins.util.DevUtil$1.run(DevUtil.java:440)
        at java.lang.Thread.run(Thread.java:818)
[INFO] The server has stopped. Exiting dev mode.
```

If there is a stack trace, please include the FULL stack trace (without any `[internal classes]` lines in it). 
To find the full stack trace, you may need to check in `$WLP_OUTPUT_DIR/messages.log`

**Steps to Reproduce**
Follow the liberty example doc on https://openliberty.io/guides/getting-started.html#checking-the-open-liberty-server-logs

**Expected behavior**

**Diagnostic information:**
- Platform: Windows 10
 - OpenLiberty Version: Open Liberty 19.0.0.11 (wlp-1.0.34.cl191120191031-0300)
 - Java Version:
java.version = 1.8.0_211
java.runtime = Java(TM) SE Runtime Environment (8.0.5.37 - pwa6480sr5fp37-20190618_01(SR5 FP37))
 - server.xml configuration (WITHOUT sensitive information like passwords)
Before
```
<server description="Sample Liberty server">
    <featureManager>
        <feature>jaxrs-2.1</feature>
        <feature>jsonp-1.1</feature>
        <feature>cdi-2.0</feature>
        <feature>mpMetrics-2.0</feature>
		<feature>mpHealth-2.0</feature>
        <feature>mpConfig-1.3</feature>
    </featureManager>

    <variable name="default.http.port" defaultValue="9080"/>
    <variable name="default.https.port" defaultValue="9443"/>

    <webApplication location="guide-getting-started.war" contextRoot="/" />
    <mpMetrics authentication="false"/>

    <httpEndpoint host="*" httpPort="${default.http.port}"
        httpsPort="${default.https.port}" id="defaultHttpEndpoint"/>

    <variable name="io_openliberty_guides_system_inMaintenance" value="false"/>
</server>
```

After
```
<server description="Sample Liberty server">
    <featureManager>
        <feature>jaxrs-2.1</feature>
        <feature>jsonp-1.1</feature>
        <feature>cdi-2.0</feature>
        <feature>mpMetrics-2.0</feature>
		<feature>mpHealth-2.0</feature>
        <feature>mpConfig-1.3</feature>
    </featureManager>

    <variable name="default.http.port" defaultValue="9080"/>
    <variable name="default.https.port" defaultValue="9443"/>

    <webApplication location="guide-getting-started.war" contextRoot="/" />
    <mpMetrics authentication="false"/>

    <logging traceSpecification="com.ibm.ws.microprofile.health.*=all" />

    <httpEndpoint host="*" httpPort="${default.http.port}"
        httpsPort="${default.https.port}" id="defaultHttpEndpoint"/>

    <variable name="io_openliberty_guides_system_inMaintenance" value="false"/>
</server>
```

 - If it would be useful, upload the messages.log file found in `$WLP_OUTPUT_DIR/messages.log`

**Additional context**

**Comment by jhanders34** [comment]
#run-libby-bot

**Comment by gjwatts** [comment]
This has gotten too old to be worth processing.  Closing.
