### ISSUE TITLE
Resolve ClassCastException in SecurityNameBridge

### ISSUE THREAD

**Issue by kristip17** [OpenLiberty/open-liberty#981]
In some cases, on release 17.0.0.3, a user can encounter a ClassCastException in SecurityNameBridge and fail to login. 

This can occur when the ObjectClass in the userFilter is not defined and is not the default ObjectClass for the LdapType.

The best practice is to add an LdapEntityType configuration.
For example, for the user filter, `userFilter='(&amp;(cn=%v)(objectClass=User))'`

Add:
 ```
<ldapEntityType name="PersonAccount">
  <objectClass>user</objectClass>
</ldapEntityType>
```

Example FFDC snippet:

Exception = com.ibm.ws.security.registry.RegistryException
Source = com.ibm.ws.security.authentication.jaas.modules.UsernameAndPasswordLoginModule
probeid = 92
Stack Dump = com.ibm.ws.security.registry.RegistryException: com.ibm.wsspi.security.wim.model.Entity incompatible with com.ibm.wsspi.security.wim.model.LoginAccount
	at com.ibm.ws.security.wim.registry.WIMUserRegistry.getUserSecurityName(WIMUserRegistry.java:321)
	at com.ibm.ws.security.authentication.internal.jaas.modules.ServerCommonLoginModule.getSecurityName(ServerCommonLoginModule.java:104)
	at com.ibm.ws.security.authentication.jaas.modules.UsernameAndPasswordLoginModule.login(UsernameAndPasswordLoginModule.java:74)

Example trace snippet:

RegistryExcep >  <init> Entry  
                                 com.ibm.wsspi.security.wim.model.Entity incompatible with com.ibm.wsspi.security.wim.model.LoginAccount
                                 java.lang.ClassCastException: com.ibm.wsspi.security.wim.model.Entity incompatible with com.ibm.wsspi.security.wim.model.LoginAccount
	at com.ibm.ws.security.wim.registry.util.SecurityNameBridge.getUserSecurityName(SecurityNameBridge.java:203)
	at com.ibm.ws.security.wim.registry.WIMUserRegistry.getUserSecurityName(WIMUserRegistry.java:316)
	at com.ibm.ws.security.registry.internal.UserRegistryWrapper.getUserSecurityName(UserRegistryWrapper.java:136)

**Comment by kristip17** [comment]
This fix is listed under its Pull Request number for inclusion in IBM WebSphere Application Server Liberty 17.0.0.4: OLGH1011
