### ISSUE TITLE
Resource adapters might fail to start with Bean Validation 1.1 and CDI 1.2 enabled.

### ISSUE THREAD

**Issue by nmittles** [OpenLiberty/open-liberty#9848]
A resource adapter could fail to activate with the following error when Bean Validation 1.1 and CDI 1.2 are enabled.

CWWKE0701E: bundle com.ibm.ws.jca:1.0.32.cl190920190905-0148 (81)[com.ibm.ws.jca.resourceAdapter.properties(677)] : The activate method has thrown an exception java.lang.NullPointerException
    at com.ibm.ws.beanvalidation.v11.cdi.internal.ValidationReleasableFactoryImpl.getCurrentBeanManager(ValidationReleasableFactoryImpl.java:90)
    at com.ibm.ws.beanvalidation.v11.cdi.internal.ValidationReleasableFactoryImpl.createConstraintValidatorFactory(ValidationReleasableFactoryImpl.java:81)
    at com.ibm.ws.beanvalidation.v11.config.ValidationConfiguratorV11.setConstraintValidatorFactory(ValidationConfiguratorV11.java:100)
    at com.ibm.ws.beanvalidation.config.ValidationConfigurator.configure(ValidationConfigurator.java:214)
    at com.ibm.ws.beanvalidation.v11.config.ValidationConfiguratorV11.configure(ValidationConfiguratorV11.java:68)
    at com.ibm.ws.beanvalidation.ValidatorFactoryAccessor.getValidatorFactory(ValidatorFactoryAccessor.java:100)
    at com.ibm.ws.beanvalidation.OSGiBeanValidationImpl.getValidatorFactoryApacheProvider(OSGiBeanValidationImpl.java:232)
    at com.ibm.ws.beanvalidation.OSGiBeanValidationImpl.getValidatorFactory(OSGiBeanValidationImpl.java:131)
    at com.ibm.ws.beanvalidation.OSGiBeanValidationImpl.getValidatorFactory(OSGiBeanValidationImpl.java:119)
    at com.ibm.ws.beanvalidation.OSGiBeanValidationImpl.getValidator(OSGiBeanValidationImpl.java:272)
    at com.ibm.ws.jca.internal.BeanValidationHelperImpl.validateInstance(BeanValidationHelperImpl.java:45)
    at com.ibm.ws.jca.internal.BootstrapContextImpl.configureResourceAdapter(BootstrapContextImpl.java:591)
    at com.ibm.ws.jca.internal.BootstrapContextImpl.activate(BootstrapContextImpl.java:311)

**Comment by nmittles** [comment]
Fix via PR #9849
