### ISSUE TITLE
Test Failure: junit.framework.TestSuite.com.ibm.ws.session.cache.config.fat.infinispan.SessionCacheConfigUpdateTest

### ISSUE THREAD

**Issue by nmittles** [OpenLiberty/open-liberty#9858]
In the trace below we can see two different machines(ebccOwkM9J9 and ebcuG9QOhDs) joining the same jgroup cluster.  This should never happen, as all the Infinispan FAT bucket sonly use a single virtual machine for testing.
`Received new cluster view for channel ISPN: [ebccOwkM9J9-57916|113] (2) [ebccOwkM9J9-57916, ebcuG9QOhDs-28822]`

[11/16/19, 4:31:22:694 UTC] 0000002b org.jgroups.protocols.pbcast.ClientGmsImpl                   W ebcuG9QOhDs-28822: JOIN(ebcuG9QOhDs-28822) sent to ebcb5UCrG0X-57635 timed out (after 2000 ms), on try 0
[11/16/19, 4:31:22:731 UTC] 0000002b org.infinispan.CLUSTER                                       I ISPN000094: Received new cluster view for channel ISPN: [ebccOwkM9J9-57916|113] (2) [ebccOwkM9J9-57916, ebcuG9QOhDs-28822]
[11/16/19, 4:31:22:835 UTC] 0000002b org.infinispan.CLUSTER                                       I ISPN000079: Channel ISPN local address is ebcuG9QOhDs-28822, physical addresses are [10.34.1.98:37515]
[11/16/19, 4:32:23:303 UTC] 00000050 org.infinispan.expiration.impl.ClusterExpirationManager      W ISPN000026: Caught exception purging data container!
java.lang.IllegalArgumentException: The node is not a member : ebcuG9QOhDs-28822
	at org.infinispan.distribution.ch.impl.ReplicatedConsistentHash.getPrimarySegmentsForOwner(ReplicatedConsistentHash.java:159)
	at org.infinispan.distribution.group.impl.PartitionerConsistentHash.getPrimarySegmentsForOwner(PartitionerConsistentHash.java:76)
	at org.infinispan.expiration.impl.ClusterExpirationManager.purgeInMemoryContents(ClusterExpirationManager.java:123)
	at org.infinispan.expiration.impl.ClusterExpirationManager.processExpiration(ClusterExpirationManager.java:98)
	at org.infinispan.expiration.impl.ExpirationManagerImpl$ScheduledTask.run(ExpirationManagerImpl.java:282)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by nmittles** [comment]
Fix via PR #9857
