### ISSUE TITLE
Test Failure: com.ibm.ws.logging.fat.InvalidTraceSpecificationTest.testMultipleInvalidTraceSpec

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#9983]
RTC 270132

```
testMultipleInvalidTraceSpec:java.lang.Exception: 2019-11-28-10:43:02:606 Errors/warnings were found in server com.ibm.ws.logging.tracespec logs:
<br>[11/28/19 10:42:41:480 UTC] 00000013 LogService-9-com.ibm.ws.config                               E CWWKE0701E: bundle com.ibm.ws.config:1.0.35.201911280356 (9)[com.ibm.ws.config.xml.internal.ConfigIntrospection(9)] : The setMetaTypeRegistry method has thrown an exception java.lang.LinkageError: loader (instance of  com/ibm/ws/kernel/internal/classloader/BootstrapChildFirstJarClassloader): attempted  duplicate class definition for name: com/ibm/ws/logging/synch/ThreadLocalHandler$1
at componenttest.topology.impl.LibertyServer.checkLogsForErrorsAndWarnings(LibertyServer.java:2528)
at componenttest.topology.impl.LibertyServer.stopServer(LibertyServer.java:2406)
at componenttest.topology.impl.LibertyServer.stopServer(LibertyServer.java:2221)
at componenttest.topology.impl.LibertyServer.stopServer(LibertyServer.java:2196)
at com.ibm.ws.logging.fat.InvalidTraceSpecificationTest.tearDown(InvalidTraceSpecificationTest.java:162)
at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:193)
at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:314)
at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:167)
```

**Comment by Yushan-Lin** [comment]
Seems like an issue with the method: `com.ibm.ws.kernel.internal.classloader.BootstrapChildFirstJarClassloader.loadClass(String, boolean)`

**Comment by fmhwong** [comment]
No occurrences in last 2 weeks
